### ISSUE TITLE
mistyping command executes `yarn` install

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#1002]
Yarn v0.15.1

I keep accidentally typing `yarn -v` instead of `yarn -V` and then yarn treats it as `yarn` and goes through its install hoops. It'd be nice if it warned me of the invalid command and full-stopped.

**Comment by STRML** [comment]
This may require forking `commander`: https://github.com/tj/commander.js/issues/482

**Comment by wyze** [comment]
The fix landed in #777, but a release hasn't been cut since then.

**Comment by Daniel15** [comment]
I'm going to close this as it's fixed by #777 like @wyze mentioned. Thank you for trying Yarn and reporting this issue! 😄
