### ISSUE TITLE
warning lodash@1.0.0: The engine "rhino" appears to be invalid.

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#1003]
I've seen this warning [popup](https://twitter.com/nodemotw/status/786575173243789334) when installing packages with yarn:
> warning lodash@1.0.0: The engine "rhino" appears to be invalid.

For older packages, when Rhino support was more of a thing, it was indicated with an entry in the `engines` array/object of the package.json.

You can see it
https://github.com/persvr/perstore/blob/master/package.json#L19

**Comment by jdalton** [comment]
Thanks! ✨

**Comment by frank-dspeed** [comment]
#1552 Should fix this.
