### ISSUE TITLE
--clean breaks some packages

### ISSUE THREAD

**Issue by prakharsingh** [yarnpkg/yarn#1008]
I have migrated to yarn yesterday and npm package browser-sync-ui gets broken by using "yarn --clean".
yarn deletes history plugin file from the module.

Yarn version v0.15.1
OS Ubuntu 14.04 LTS

**Comment by marzepani** [comment]
I can confirm, as the same happened to me.
`yarn clean` removed `node_modules/browser-sync-ui/lib/plugins/history`

**Comment by yannickoo** [comment]
You can specify files in the `.yarnclean` file, check [this](https://github.com/yarnpkg/yarn/issues/1051#issuecomment-254334628) comment 😇

**Comment by marzepani** [comment]
Thx, but beware. [See details](https://github.com/yarnpkg/yarn/issues/1051#issuecomment-254438695).

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? If yes, can you supply a `package.json` file that recreates the issue?

**Comment by hpurmann** [comment]
I'd vote for closing this if it's no longer reproducible.
