### ISSUE TITLE
are postinstall/install/preinstall scripts run before dev deps are installed?

### ISSUE THREAD

**Issue by sam-github** [yarnpkg/yarn#1010]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

yarn install of strongloop fails, the install script fails to find a dependency, this appears similar to the npm@2 problem where the order of scripts being run, and dev deps being installed was indeterminate.

**If the current behavior is a bug, please provide the steps to reproduce.**

git clone http://github.com/strongloop/strongloop; cd strongloop; yarn install

**What is the expected behavior?**

it installs

**Please mention your node.js, yarn and operating system version.**

> 0.15.1
> Linux samtu 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wyze** [comment]
Lifecycle methods are now executed with Yarn 0.16.0. @sam-github can you reproduce this on the latest version of yarn or has it been resolved?

**Comment by sam-github** [comment]
resolved
