### ISSUE TITLE
packages not-in the registry issue.

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#1012]
Yarn 0.15.1:

While switching Lodash's [travis-ci runs](https://github.com/lodash/lodash/blob/master/.travis.yml)  to yarn I ran into an issue. In order to test work-in-progress bits I `git clone` the master of [lodash-cli](https://github.com/lodash/lodash-cli) in to the `node_modules/lodash-cli` folder. It's bumped in master to `xyz-pre` it [then depends](https://github.com/lodash/lodash-cli/blob/db6aaf605a0795665114599ae0f13fe6220f15be/package.json#L26) on `lodash` of `xyz-pre` (so not in the registry but in [the master](https://github.com/lodash/lodash/blob/26bfb74a604704d571b6e65aa7ae4f3472387c4d/package.json#L3) of the lodash repo). I create a symlink from the root of the lodash repo to `node_modules/lodash-cli/node_nodules/lodash`.

In the [following bit](https://github.com/lodash/lodash/blob/26bfb74a604704d571b6e65aa7ae4f3472387c4d/.travis.yml#L83-L86) if I replace `npm i --production` with `yarn --prod` it fails saying that `lodash@4.16.5-pre` does not exist.

**Comment by bestander** [comment]
We'll sort out all this first/third-party development workflows with workspaces and link: feature.
Closing this for now
