### ISSUE TITLE
Clarify what' yarn ls' is showing

### ISSUE THREAD

**Issue by swang** [yarnpkg/yarn#1022]
**Do you want to request a *feature* or report a *bug*?**
Feature? 

`yarn ls` has no clear documentation. I would like to add some but it I want to be clear what is going on.

![modules](https://cloud.githubusercontent.com/assets/49867/19367199/01aeeae2-914f-11e6-91a9-54085c10929a.png)
From the screenshot, it looks like zip-stream requires a versioning of lodash@~3.2.0 in grey, while the bolded **lodash@3.2.0** is the actual version of lodash that was installed.

But.. looking into the code, the grey/"dim" npm modules that don't have a bold equivalent (ex: compress-commons) means that they have been hoisted up to the main `node_modules/` folder. So anything that is bolded, is actually dependencies that yarn decided it couldn't hoist out to the main folder. Is this mostly correct? Is there something else that should be known in the documentation?

**Comment by kittens** [comment]
Please open docs/website issues on [yarnpkg/website](https://github.com/yarnpkg/website).
