### ISSUE TITLE
restrict licenses of installed modules

### ISSUE THREAD

**Issue by bbodenmiller** [yarnpkg/yarn#1026]
There is mentions of restrict licenses of installed modules at https://code.facebook.com/posts/1840075619545360 but I cannot seem to find how to do so?

**Comment by rjmunro** [comment]
There are commands to list licenses `yarn licenses ls` and `yarn licenses generate-disclaimer`, but I can't see how to restrict them. I guess this is a documentation issue.

**Comment by Daniel15** [comment]
I think this is covered by https://github.com/yarnpkg/rfcs/pull/7. I don't think the functionality currently exists.

**Comment by bestander** [comment]
Covered with RFC.
Continue discussion there
