### ISSUE TITLE
Failed to lunch Rollup.js

### ISSUE THREAD

**Issue by dangvanthanh** [yarnpkg/yarn#1030]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

```
$ yarn run dev
yarn run v0.15.1
$ "rollup -c"
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`package.json`
```json
{
  "scripts": {
    "dev": "rollup -c"
  }
}
```

**What is the expected behavior?**

Yarn working as well with Rollup.js

**Please mention your node.js, yarn and operating system version.**

Node: v6.8.0
Yarn: v0.15.1
Rollup: v0.36.3
OS: macOS Sierra v10.12

**Comment by Kovensky** [comment]
Fixed by https://github.com/yarnpkg/yarn/pull/809
