### ISSUE TITLE
in npm `run` is an alias to `run-script`.

### ISSUE THREAD

**Issue by joscha** [yarnpkg/yarn#1035]
**Do you want to request a *feature* or report a *bug*?**

Something of both.

**What is the current behavior?**

yarn has a `run` command. However `npm run` is only an alias for `npm run-script`, which means that packages are using that - such as [npm-run-all](https://www.npmjs.com/package/npm-run-all) for example. These packages currently fail and it makes me wonder whether yarn should provide an alias `run-script` for the `run` command in order to be backwards-compatible with npm in that respect.

**What is the expected behavior?**

`yarn run-script bla` executes the script `bla`.

**Please mention your node.js, yarn and operating system version.**
node 6.5.0
yarn 0.15.1
OSX 10.12

**Comment by cpojer** [comment]
See my response in #1044. We are compatible with the npm registry, not with the npm client and made a deliberate choice not to pollute Yarn's CLI with aliases.
