### ISSUE TITLE
feature: Implement `yarn global config set|get`

### ISSUE THREAD

**Issue by FLGMwt** [yarnpkg/yarn#1037]
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behavior?**
Currently, all `yarn config set` and `yarn config remove` commands modify home config, whether `-g` is set or not.
**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn config set foo bar`
notice user level .yarnrc is modified
👍 

`yarn config set foo bar --global`
notice user level .yarnrc is modified and global .yarnrc is _unmodified_
👎 

**What is the expected behavior?**
--global should only modify global .yarnrc
**Please mention your node.js, yarn and operating system version.**

```
> node -v
v6.7.0
> npm -v
3.10.3
> yarn --version
0.15.1
```

**Comment by BYK** [comment]
I've changed the issue since I don't think we are going to implement `-g` or `--global` flags. That would be inconsistent with how we do things. I think having a `yarn global config` command would be nice tho.

**Comment by sla89** [comment]
You know, that the [yarn config documentation](https://yarnpkg.com/lang/en/docs/cli/config/) mentions the ```-g```and ```--global``` flag for setting configuration values globally but as mentioned here this feature does not work.

**Comment by paul-soporan** [comment]
Closing as fixed in v2: v2's `yarn config set` works on the project configuration and `yarn config set --home` works on the home configuration.
