### ISSUE TITLE
yarn : 依赖: nodejs (>= 4.0.0) 但是它将不会被安装

### ISSUE THREAD

**Issue by smalike** [yarnpkg/yarn#1042]
源码安装 nodejs 6.0.0，执行 sudo apt-get install yarn 得到提示：
- 下列软件包有未满足的依赖关系：
- yarn : 依赖: nodejs (>= 4.0.0) 但是它将不会被安装
- E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

---

**GOOGLE TRANSLATION BELOW** - edit by @thejameskyle

Source installed nodejs 6.0.0, the implementation of sudo apt-get install yarn was suggested:

The following packages have unmet dependencies:

Yarn: Dependency: nodejs (> = 4.0.0) But it will not be installed

E: The error can not be fixed because you are asking some packages to stay in the status quo, that is, they break dependencies between packages.

**Comment by quietshu** [comment]
可以等待更新，之后使用 `yarn install --ignore-engines` 即可。
via https://github.com/yarnpkg/yarn/issues/972

> Duplicate of #638, solved in #647, not yet shipped.

**Comment by dandv** [comment]
English please.

**Comment by Daniel15** [comment]
Hi @smalike! I don't know Chinese, but it looks like you're asking about the `nodejs` dependency of the Ubuntu/Debian package. That'll be changed to a "Recommended" package in #916. Do you have Node.js installed via something like NVM? If you're using a package for Node.js, adding the NodeSource repository (https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) should give you a newer Node.js version, then you can `sudo apt-get install yarn`.

**Comment by dandv** [comment]
@smalike, what makes you think people here would be able to read Chinese?

I don't know how bad the Great Firewall situation is where you are, but surely there must be some automatic translation tool you can use to translate from Chinese into English and show respect to the community.

Try http://translate.google.cn

**Comment by thejameskyle** [comment]
@dandv deleted your comment, please be more respectful of others on yarn projects if you wish to be a participant in them

**Comment by dandv** [comment]
@thejameskyle I was trying to help others be more respectful by pointing them to tools they can use to do so. Censorship wasn't one of them.

**Comment by dandv** [comment]
@thejameskyle Feel free to delete my comments since the *are* off-topic, but it might be worth mentioning in the Code of Conduct that the language of the project is English. Note that I'm not a native English speaker either.

**Comment by thejameskyle** [comment]
@dandv once we set up crowd sourced automated translations, the language of the project will not be English. Using the CoC as a way to try and force a language on people is a gross misuse of a CoC

**Comment by dandv** [comment]
@smalike: thank you for using Google Translate!

@thejameskyle: my mission was accomplished.

**Comment by thejameskyle** [comment]
@dandv I was the one that edited the issue, now please go do something useful with your time

**Comment by Shyam-Chen** [comment]
@smalike 我在 Ubuntu 上可以安裝

![default](https://cloud.githubusercontent.com/assets/13535256/19386468/f46313e2-9246-11e6-99cf-600e264aa763.png)

**Comment by Shyam-Chen** [comment]
error in Dockerfile
```bash
apt-get install yarn
```
```bash
FROM buildpack-deps:jessie
[...]
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get update && \
    apt-get install -y \
    nodejs yarn xvfb chromium libgconf-2-4 openjdk-7-jre-headless && \
    rm -rf /var/lib/apt/lists/*
[...]
```

**Comment by bestander** [comment]
Should be fixed I reckon
