### ISSUE TITLE
yarn throws 0.15.1 throws TypeError when author is null

### ISSUE THREAD

**Issue by krstffr** [yarnpkg/yarn#1047]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Running `yarn` or any `yarn` command throws this error:

```
yarn install v0.15.1
info No lockfile found.
error TypeError: Cannot read property 'name' of null
    at stringifyPerson (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/lib/util/normalize-manifest/util.js:25:13)
    at normalizePerson (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/lib/util/normalize-manifest/util.js:72:22)
    at /usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/lib/util/normalize-manifest/fix.js:107:65
    at next (native)
    at step (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`brew update`
`brew install yarn`
`yarn`

**What is the expected behavior?**

To not throw errors.

**Please mention your node.js, yarn and operating system version.**

Node v6.8.0
Yarn 0.15.1
Mac OS 10.11.6

**Comment by Tapppi** [comment]
Remove your `node_modules` folder and try again. You are attempting to install dependencies, but you do not have a `yarn.lock` file for yarn to use.

**Comment by krstffr** [comment]
Removed node_modules and tried again, still not working. 

Tried another project though which actually works!

So seems to be specific to the first project I tried, no clues in the error message though as all files pointed to in the error message seems yarn specific.

**Comment by wyze** [comment]
Looks like it has an issue with the `author` field. Are you able to post your `package.json` @krstffr?

**Comment by akoskm** [comment]
@krstffr had a similar problem, just fixed it. @wyze it runs fine for me with `author: ""` but looks like `license` is mandatory.

**Comment by miscbits** [comment]
This bug happens to me when my packages/bower.json is either not present or not formatted correctly.

**Comment by krstffr** [comment]
I'm on my phone now, but the author field is actually null and there's no license field, so that should be it! Thanks guys.

**Comment by krstffr** [comment]
So maybe add a better error message?

**Comment by wyze** [comment]
The error thrown by `stringifyPerson` was fixed in https://github.com/yarnpkg/yarn/pull/890 but hasn't been released yet.

**Comment by samccone** [comment]
thanks again @wyze for dedupuing!
