### ISSUE TITLE
Support CSON or JSON with comments?

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/yarn#1049]
Since Yarn is independent from npm, could you consider to support comments in `package.json` or support a `package.cson` version of it?

**Comment by wyze** [comment]
Someone previously asked about supporting `.hjson` and was directed to [yarnpkg/rfcs](https://github.com/yarnpkg/rfcs). So you should probably close the issue here and follow the instructions for an RFC.

**Comment by FezVrasta** [comment]
Oh, that's weird. I write RFCs all the day at work already, I have no time to write an RFC for a feature request 😥

**Comment by kittens** [comment]
Dupe of #178.

**Comment by danielbayley** [comment]
Massive +1 for `package.cson`! This would go _so_ nicely with Atom!
