### ISSUE TITLE
A way to detect the origin of a package from a lifecycle script (for native module binaries)

### ISSUE THREAD

**Issue by mourner** [yarnpkg/yarn#1050]
**Do you want to request a _feature_ or report a _bug_?** 
Compatibility issue vs NPM that causes [prebuild](https://github.com/mafintosh/prebuild), a tool for prebuilding binaries for native NPM modules, to compile the package on install/update every time instead of using a prebuilt binary. See https://github.com/mafintosh/prebuild/issues/132

**What is the expected behavior?**
When you install a module with NPM CLI, it augments `package.json` in the installed package in `node_modules` with custom attributes like `"_from": "gl@>=4.0.0 <5.0.0"`. `prebuild` uses that metadata to detect whether the package is a released tagged version installed with NPM (which means there's a binary available), or just a working directory, or a installed from a git URL (in which case it needs compiling).

**What is the current behavior?**
Yarn does not leave any traces in the installed package, and there's no apparent way to detect from within a `package.json` script like `install` whether the package is a released version from the NPM registry or not.

**Please mention your node.js, yarn and operating system version.**
Yarn v0.15.1, all Node and OS versions.

@bestander @cpojer @kittens is there any way you could detect the nature of the installed package with a script? Happy to do a PR if there's currently no way but you have an idea how to provide it within Yarn.

cc @mafintosh

**Comment by nrako** [comment]
😱this actually kill the usability of `yarn add`, rebuilding the native module binaries every time, bye bye ✨. Kinda serious issue IMHO.

**Comment by benthemonkey** [comment]
A fix for this has already been released: https://github.com/mafintosh/prebuild/issues/132 and https://github.com/mafintosh/prebuild/pull/151 (released in prebuild@5.0.3)

**Comment by nrako** [comment]
Thank your very much for the update @benthemonkey
