### ISSUE TITLE
"yarn clean" / ".yarnclean" breaks svgo

### ISSUE THREAD

**Issue by marzepani** [yarnpkg/yarn#1051]
`svgo`requires `.svgo.yml` and is a dependency of popular `gulp-svgmin`.

The clean command (and the resulting `.yarnclean`) keep removing hidden files and therefore break `svgo`.

I know [you warned us](https://yarnpkg.com/en/docs/cli/clean), but maybe an option to exclude files from being cleaned would be nice.

What about listing files to ignore in `.yarnclean`, like we do in `.gitignore`. Or something smarter. :)

(node 6.8.0, yarn 0.15.1, macOS)

**Comment by zcei** [comment]
There already is [a way to ignore files](https://github.com/yarnpkg/yarn/blob/271ef9a9d021e59fbced660989d1fa5589413eca/src/util/filter.js#L44) & folders within yarn.

Basically it's a [minimatch](https://github.com/isaacs/minimatch) regex, and the leading `!` indicates to keep this path.

e.g. `!.svgo.yml`

**Comment by marzepani** [comment]
Thank you @zcei for investigating.

But there is a big issue with this, as `yarn clean` creates a blank new `.yarnclean` file every time. Added filter rules will be wiped. :-(

The only way it works right now:

1. Manually create `.yarncean` file.
2. Add filter rules, like `!.svgo.yml`
3. Add modules, like `yarn add svgo --dev`
4. **Never** call `yarn clean`, as all filters will be lost and modules will be cleaned –> you are doomed. ;-)

**Comment by zcei** [comment]
Oh well, this is not good for obvious reasons 😄 
Hope your PR gets merged soon 👍

**Comment by kittens** [comment]
Fixed via #1430, the default filters are now added to `.yarnclean` and you can remove specific rules if you wish.
