### ISSUE TITLE
Built-in support for .nvmrc file

### ISSUE THREAD

**Issue by rochdev** [yarnpkg/yarn#1053]
It would be nice if yarn could automatically use the node version defined in `.nvmrc`. By far the most common node-related error within teams I've worked with is using the wrong node version for a project since they usually have many projects requiring different versions. Even though `nvm` makes changing the current node version a breeze, there is no easy way to automatically use the correct version for a project. I think `nvm` is widespread enough that supporting it makes sense for a package manager.

**Comment by ericclemmons** [comment]
What did you have in mind?  `yarn` calling `nvm install && nvm use` when the `node --version` differs from that in `.npmrc`?

I had a similar problem, until we adopted [`avn`](https://github.com/wbyoung/avn).  Since then, our problems have been primarily with `npm i` not being deterministic.

**Comment by rochdev** [comment]
Something like that. Another solution could be to throw an error if the current version of node doesn't match the engines from package.json so at least it would fail fast.

**Comment by ljharb** [comment]
I maintain http://nvm.sh, and I don't think it'd be a good idea for yarn, or npm, or anything but nvm itself, to read from `.nvmrc`.

Simply run `nvm use` and it will read from that file and use the proper version (or use something like `avn`, or one of the scripts in nvm's readme, which does that for you), and then at that point `yarn` can check the "engines" field as it likes.

**Comment by rochdev** [comment]
Fair enough. I agree that reading another libary's config file might not be the best idea (it would be nice if there was a standard node file to do it, but that is a discussion for another day).

There is no point however in allowing to run a project on an unsupported node version (regardless of a version manager being used or not) since it WILL cause issues at some point, so what about the other option?

**Comment by kittens** [comment]
Going to have to agree with @ljharb here, it doesn't make sense for us to have any opinions on Node versioning.
