### ISSUE TITLE
Drop a dependency map next to package.json for improving startup times

### ISSUE THREAD

**Issue by AlicanC** [yarnpkg/yarn#1054]
(This is a feature request.)

When I start React Native's packager in one of my projects, I see steps like "Crawling File System", "Building Dependency Graph" and "Building Haste Map" which take around 3 seconds to complete.

Since Yarn knows about all the dependencies in a project, could it also drop something like a dependency map in project root so tools like RN packager can read this file to improve their startup times?

**Comment by bestander** [comment]
We actively work on performance.
As of 0.23 Yarn is a single file JS
