### ISSUE TITLE
Couldn't find a package.json ... when install react-scripts

### ISSUE THREAD

**Issue by schovi** [yarnpkg/yarn#1058]
1) Having empty new directory
2) Init new package.json (tried with yarn and npm)
3) add react-scripts package (can be added manually into package.json, but it does not matter)
4) Getting error: `error Couldn't find a package.json (or bower.json) file in /Users/schovi/tmp/xxx/node_modules/react-scripts/node_modules/autoprefixer`

```
15:51 $ mkdir ~/tmp/xxx && cd ~/tmp/xxx
~/tmp/xxx
15:51 $ yarn init
yarn init v0.15.1
questions ...
✨  Done in 2.89s.
15:51 $ yarn add react-scripts
yarn add v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-scripts > jest > jest-cli > istanbul-api > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error Couldn't find a package.json (or bower.json) file in /Users/schovi/tmp/xxx/node_modules/react-scripts/node_modules/autoprefixer
    at /usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/lib/config.js:355:13
    at next (native)
    at step (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

System:
OSx Sierra
Node 6.8.0
Yarn 0.15.1 (installed via homebrew)

PS: when installing with npm, everything is fine.

**Comment by trbngr** [comment]
Same issue here.

**Comment by busches** [comment]
Please retest with `yarn 0.16.+`, I'm unable to reproduce the error now.

**Comment by schovi** [comment]
@busches Same error
```
[3/4] 🔗  Linking dependencies...
error Couldn't find a package.json (or bower.json) file in /Users/schovi/tmp/xx/node_modules/react-scripts/node_modules/autoprefixer
```

version is really 0.16.0

**Comment by torifat** [comment]
Weird! works for me. I'm using the same version `0.16.0`. Node `v6.9.1` & macOS `10.12`.

<img width="1098" alt="screenshot 2016-10-20 16 21 49" src="https://cloud.githubusercontent.com/assets/208544/19556090/51a393f8-96e1-11e6-904a-ea005a740ee6.png">

**Comment by schovi** [comment]
Solved! `yarn cache clean` helped. Not sure how broken version get there.

**Comment by joe4mg** [comment]
This might help someone else who stumbles across this page - I had this error when my directory/package.json didn't have the right file permissions

**Comment by jalavosus** [comment]
@joe4mg, what permissions does the package.json need?

**Comment by philpoore** [comment]
I was also finding this issue.
@schovi `yarn cache clean` didn't fix the problem for me.

Was running version `v0.27.5`, fairly out of date.
Upgraded yarn via brew with:
```
brew upgrade yarn
```
And that fixed it.

package.json resolution works in sub-folders again.
😃😃😃😃😃😃😃😃

**Comment by MoonMoonLight** [comment]
yarn cache clean didn't solve my problem (couldn't find package,json file). But running it as administrator (-@windows) did.

**Comment by kleviss** [comment]
My case was that I was **not in the right folder** when I run `yarn`. I had another **folder inside the folder** where I tried to run `yarn start`. The **project files** were in the **other folder nested**.` cd `to the correct folder and run `yarn start`  - _This worked for me._

**Comment by lalaphoon** [comment]
In my case, I just went to a wrong directory - the parent directory of my react project.
So just make sure in the directory where you contains your react project.
(Yes, I guessed. My comment will be downvoted.)

**Comment by namdh-1522** [comment]
`cd your_react_app`
then
`yarn start`

**Comment by RamonPereira88** [comment]
> My case was that I was **not in the right folder** when I run `yarn`. I had another **folder inside the folder** where I tried to run `yarn start`. The **project files** were in the **other folder nested**.`cd`to the correct folder and run `yarn start` - _This worked for me._

this was the fix, it worked for me, thanks a lot man, really helped me a lot

**Comment by mali30** [comment]
just ran into this issue also. make sure your in the same directory as your package.json.

**Comment by magaldistudio** [comment]
Muito bom !!!
eu tbm acionei yarn start no diretorio errado .
obrigado

**Comment by AtikRhaman** [comment]
For me, I wan in the wrong folder, cd to the right project and `yarn run develop`

**Comment by abdifatahali** [comment]
> `cd your_react_app`
> then
> `yarn start`

Thank you, it did work for me.

**Comment by freshmurry** [comment]
`yarn add package.json` worked for me

**Comment by GustavoMori** [comment]
When you create a new project with "yarn create ..." you aren't in the correct folder, so cd (name of project) then yarn start :)

**Comment by freshmurry** [comment]
Not sure why I received this email?


Sent from Yahoo Mail for iPhone


On Monday, August 3, 2020, 9:50 AM, Gustavo Mori <notifications@github.com> wrote:




When you create a new project with "yarn create ..." you aren't in the correct folder, so cd (name of project) then yarn start :)

**Comment by Marcianas1l** [comment]
> Meu caso foi que eu **não** estava **na pasta correta** quando executo `yarn`. Eu tinha outra **pasta dentro da pasta** onde tentei executar `yarn start`. Os **arquivos do projeto** estavam na **outra pasta aninhada** . `cd`para a pasta correta e execute `yarn start` - _Isso funcionou para mim._

Obrigada por compartilhar essa informação, resolveu meu problema!

**Comment by eddskt** [comment]
> yarn cache clean didn't solve my problem (couldn't find package,json file). But running it as administrator (-@windows) did.

this solved my problem, simple, thks

**Comment by anedejour** [comment]
> 
> 
> My case was that I was **not in the right folder** when I run `yarn`. I had another **folder inside the folder** where I tried to run `yarn start`. The **project files** were in the **other folder nested**.`cd`to the correct folder and run `yarn start` - _This worked for me._

tks a lot!
