### ISSUE TITLE
yarn cannot install correct versions when using @next

### ISSUE THREAD

**Issue by azappa** [yarnpkg/yarn#1062]
**Do you want to request a *feature* or report a *bug*?**
Probably bug.

**What is the current behavior?**
Node modules installed versions

**If the current behavior is a bug, please provide the steps to reproduce.**
When using npm as package manager if I use @next as a version (for example `npm install --save koa@next`) it installs the correct version. Running `yarn outdated` output is another version (yarn.lock displays the correct and currently @next version installed instead).

```bash
Package              Current Wanted Latest
koa-router           7.0.1   7.0.1  5.4.0 
koa                  2.0.0   2.0.0  1.2.4 
```

**What is the expected behavior?**
Output correctly latest versions (if they exist).

**Please mention your node.js, yarn and operating system version.**
```
/home/alessio/.nvm/versions/node/v6.6.0/bin/node
Linux pandadev 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
yarn install v0.15.
```

**Comment by samccone** [comment]
This is fixed on master
