### ISSUE TITLE
Yarn on Bash On Windows error invalid argument, uv_interface_addresses

### ISSUE THREAD

**Issue by nick2il** [yarnpkg/yarn#1063]
I think it's the latest, not sure because it returns bug error. 
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
/usr/share/yarn/bin/yarn.js:48
      throw err;
      ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.isOffline (/usr/share/yarn/lib-legacy/util/network.js:13:25)
    at Object.<anonymous> (/usr/share/yarn/lib-legacy/util/request-manager.js:58:54)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at _load_requestManager (/usr/share/yarn/lib-legacy/config.js:46:51)
**If the current behavior is a bug, please provide the steps to reproduce.**
I installed the Yarn via instructions for linux on Bash on Windows 
it installed yarn but it returns error,  before I tried to install yarn by npm but it had same problem. 
So I uninstalled it and installed yarn by the guide, I installed by npm before because I had issues to install it by linux guide. In the I found a way to install it but it's still return the same error.
**What is the expected behavior?**
It supposed give the option to install things and do what the commands need to do but instead it return for yarn command returns the "invalid argument, uv_interface_addresses" error.
**Please mention your node.js, yarn and operating system version.**
Ubuntu - Bash on Windows, linux subsystem
node version v4.4.7
using nvm version 0.11.1

`Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty`

**Comment by TAGraves** [comment]
This looks like a duplicate of https://github.com/yarnpkg/yarn/issues/907

**Comment by nick2il** [comment]
@TAGraves  The issue #907 you linked helped to solve the problem.  So it's seems it's duplicate :( 👍
