### ISSUE TITLE
What is the benefit of this in comparison to NPM?

### ISSUE THREAD

**Issue by AndrewEastwood** [yarnpkg/yarn#1065]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by troydemonbreun** [comment]
https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/

http://blog.npmjs.org/post/151660845210/hello-yarn

**Comment by Seiifer** [comment]
Mainly, it supports bower packages as well.
Also, it has no (or less) dependancies duplicates, and is supposed to be faster and more secure.

That's the main attractive features among other things imo.

**Comment by AndrewEastwood** [comment]
interesting

**Comment by samccone** [comment]
closing as this is not an a direct issue with yarn. Feel free to follow up here though :)

**Comment by AndrewEastwood** [comment]
I think jspm is way better than this
