### ISSUE TITLE
OHAI UR BUILD IS BROKEN

### ISSUE THREAD

**Issue by misterbrownlee** [yarnpkg/yarn#1066]
OHAI UR BUILD IS BROKEN

![error](https://cloud.githubusercontent.com/assets/333458/19393878/85595f34-91eb-11e6-9b48-5b304617a57e.png)

It's a little ironic that is says 'reliable' right below that badge...

  ¯\_(ツ)_/¯

**Comment by samccone** [comment]
thanks

**Comment by misterbrownlee** [comment]
Sure...  Sorry I didn't do the right thing and PR in a fix.  Any code I write would be super scary anyway.  😬

**Comment by Daniel15** [comment]
![](https://wordandimage.files.wordpress.com/2008/04/pctechsupportcat.jpg)
