### ISSUE TITLE
Fix TODO in shrinkwrapWarning string

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1069]
https://github.com/yarnpkg/yarn/blob/22d0ac99bc2dc070ef109ea02b6d29ebcb4dc5df/src/reporters/lang/en.js#L61

```
shrinkwrapWarning: 'npm-shrinkwrap.json found. This will not be updated or respected. See [TODO] for more information.',
```

I assume `[TODO]` is supposed to be a link to a page on the website.

**Comment by btmills** [comment]
Would https://yarnpkg.com/en/docs/migrating-from-npm be an appropriate destination for this? I can send a quick PR if so. The relevant paragraph on that page:

> If you are using an npm-shrinkwrap.json file right now, be aware that you may end up with a different set of dependencies. Yarn does not support npm shrinkwrap files as they don’t have enough information in them to power Yarn’s more deterministic algorithm. If you are using a shrinkwrap file it may be easier to convert everyone working on the project to use Yarn at the same time. Simply remove your existing npm-shrinkwrap.json file and check in the newly created yarn.lock file.

**Comment by Daniel15** [comment]
Sounds good to me - @kittens does that sound right to you?
