### ISSUE TITLE
Package.json indent

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#1091]
We already have [NPM's opinion](https://github.com/npm/npm/pull/3062), so let's see what Yarn has to say about it :)

It would be nice if Yarn was able to [detect the current indentation](https://www.npmjs.com/package/detect-indent) of the package.json file when overwriting it (via `yarn add`, for example). It would be a bit less troublesome to manually edit when not using editorconfig files.

**Comment by kittens** [comment]
Yeah, let's detect this.

**Comment by kittens** [comment]
Moving to #1098.
