### ISSUE TITLE
yarn build

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#1092]
I've noticed that the `yarn build` command is currently missing, and I quite appreciate it. In NPM, this command [does something completely different from what could one expect](http://stackoverflow.com/questions/29939697/npm-build-doesnt-run-the-script-named-build-in-package-json) (ie it runs an internal build command instead of running the `build` script). It's quite common to accidentally run `npm build` instead of `npm run build` and wonder why nothing happened.

Would it be possible to fix this discrepancy in Yarn, since it already break BC on this regard by not implementing the command yet?

**Comment by kittens** [comment]
Yeah we'll keep the behaviour as -is. You can actually run `yarn <script-name>` and it'll use a script in `package.json` if we have no internal commands of the same name so we don't actually special-case `build`.
