### ISSUE TITLE
Cannot install strongloop package

### ISSUE THREAD

**Issue by DimitryDushkin** [yarnpkg/yarn#1095]
Looks like a bug.

```
yarn global add strongloop
```

1st:
```
error /Users/dndushkin/.yarn-cache/.global/node_modules/strong-mesh-client: Command failed.
Exit code: 1
Command: sh
Arguments: -c node proxy/build-client.js
Directory: /Users/dndushkin/.yarn-cache/.global/node_modules/strong-mesh-client
Output:
module.js:442
    throw err;
    ^

Error: Cannot find module 'JSONStream'
```

After manual install JSONStream and next try:

```
error /Users/dndushkin/.yarn-cache/.global/node_modules/strong-mesh-client: Command failed.
Exit code: 1
Command: sh
Arguments: -c node proxy/build-client.js
Directory: /Users/dndushkin/.yarn-cache/.global/node_modules/strong-mesh-client
Output:
unable to generate browser bundle: Cannot find module 'jodid25519' from '/Users/dndushkin/.yarn-cache/.global/node_modules/sshpk/lib'
```

node.js 6.3.0,  mac os sierra, yarn v0.15.1 installed via brew

**Comment by hemanth** [comment]
`$ yarn global add strongloop` works fine.

**Comment by snak1t** [comment]
Hmm, it is very strange, but I have the same issue after the first attempt to install this package. Repeat this command
```
$ yarn global add strongloop
```
And it works fine.
node 6.8 Linux Mint 18.3

**Comment by hemanth** [comment]
No, your first command was wrong, you did an `install` instead of an `add`

**Comment by snak1t** [comment]
As for me, my first and second command was ```add``` and not ```install``` I've reinstalled yarn, and know everything works fine.

**Comment by DimitryDushkin** [comment]
I've used `yarn global add strongloop`. Mistake was in first message. Still no luck.

**Comment by busches** [comment]
Is everyone using `0.15.1` or have some upgraded to `0.16.1`?

**Comment by DimitryDushkin** [comment]
I've tried `0.16.1` and it works! I guess issue can be closed.
