### ISSUE TITLE
Webpack 2.1.0 beta.25 watch not working

### ISSUE THREAD

**Issue by DOMEYD** [yarnpkg/yarn#1099]
Webpack 2.1.0-beta.25 watcher seem to not work with Yarn. 
Webpack building sources and closing, using `webpack --watch`, without error message

This is not happen when using `npm install` instead of `yarn install`

node : v6.7.0
npm : v3.10.3
yarn : v0.15.0 (installed as apt-get package)

**Comment by samccone** [comment]
Hello this is a very difficult bug report for us to debug. Would you mind creating a reduced test case and report back?

I am going to close until we have that info since this is not really actionable. 

Thanks for opening the issue and I look forward to your response.
