### ISSUE TITLE
bug can not uninstall global pkg

### ISSUE THREAD

**Issue by foxundermoon** [yarnpkg/yarn#1101]
after i  uninstall some  global package

yarn global remove electron
yarn global v0.15.1
[1/2] Removing module electron...
[2/2] Regenerating lockfile and installing missing dependencies...
warning No license field
error ENOENT: no such file or directory, open 'C:\Users\foxundermoon\AppData\Local\Yarn.global\node_modules\ansi-regex\index.js'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/global for documentation about this command.

node  6.5.0

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? I'm not able to recreate the issue using the latest Yarn `v0.17.10`.
