### ISSUE TITLE
Omit devDependencies from `licenses`

### ISSUE THREAD

**Issue by remko** [yarnpkg/yarn#1103]
**Do you want to request a *feature* or report a *bug*?**

Feature (I think)

**What is the current behavior?**

`licenses` commands list both `dependencies` and `devDependencies`. This tends to be a huge list if your entire toolchain is installed, and is not helpful (at least to me; I don't care about listing or generating disclaimers for licenses of the tools I use, only my real dependencies).

**What is the expected behavior?**

`licenses` should only list the real dependencies.

**Comment by kittens** [comment]
Depending on the licenses of your `devDependencies` it may actually be required to list them as they were involved in the generation/creation of your code. I think it's safer if we just add a `--production` flag to `yarn licenses` that filters these.

**Comment by kittens** [comment]
Created #1104 to fix this, pending approval.

**Comment by kittens** [comment]
Looks like we actually already support `yarn licenses ls --production` but it currently mutates the current folder. The PR I've opened addresses this and makes it function as expected.

**Comment by Daniel15** [comment]
Good catch! I agree with this - I was going to submit a bug report for it, but I forgot to. Having a `--production` flag sounds good to me.
