### ISSUE TITLE
Fail to install using exsisting package.json that works with npm

### ISSUE THREAD

**Issue by virror** [yarnpkg/yarn#1105]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behavior?**
It fails to finish the install
**If the current behavior is a bug, please provide the steps to reproduce.**
Just run "yarn" using the package,json file.
**What is the expected behavior?**
To finish the install as it works with npm.
**Please mention your node.js, yarn and operating system version.**
Yarn 0.15.1 
Windows 10 using node.js command prompt

package.json file:
[package.txt](https://github.com/yarnpkg/yarn/files/531386/package.txt)

**Comment by jiripospisil** [comment]
It works on my machine. Does it throw an error for you? If so, please include the full output.

**Comment by virror** [comment]
This is the last few lines that i get as output:
[2/4] Fetching packages...
warning lodash@0.9.2: The engine "rhino" appears to be invalid.
warning lodash@2.4.2: The engine "rhino" appears to be invalid.
warning lodash@2.2.1: The engine "rhino" appears to be invalid.
warning lodash@1.0.2: The engine "rhino" appears to be invalid.
error punycode@2.0.0: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jiripospisil** [comment]
Somewhat. Yarn is more strict when it comes to the "engines" directive. The `punycode` package [specifies](https://github.com/bestiejs/punycode.js/blob/a541fe6c911fe2abca97b6f5c5f9870ac5e6f9d1/package.json#L8) that it wants Node.js version >= 6 and Yarn will throw an error if you don't meet the requirement. There's the `--ignore-flags` (as in `yarn install --ignore-flags`) flag to ignore the `engines` directives but I believe it's not honored in the current version (#647 fixes it). You can either wait for the next release or install Yarn directly from master.

**Comment by jiripospisil** [comment]
Note that there's probably a reason why the package requires the particular version and throwing an error is often the right thing to do. Ignore the flags only when you're really confident that the package will work for you on the older Node version.

**Comment by virror** [comment]
Since npm never threw as a serious error, we never even noticed it before, it just got lost in the mass of text, and we never had any issues. Thanx for clearing it up though : )

**Comment by Daniel15** [comment]
> The engine "node" is incompatible with this module. Expected version ">=6".

Which version of Node.js are you using? If you're using an older version, simply upgrading to Node.js 6 should fix this.

**Comment by wyze** [comment]
Please upgrade to Node 6 or use `yarn install --ignore-engines`.
