### ISSUE TITLE
yarn does not install sub dependency if two other dependencies should be installed

### ISSUE THREAD

**Issue by jdoose** [yarnpkg/yarn#1112]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Yarn did not install a module, which is a dependency of a module (in package.json) if certain other modules are also referenced in package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**

From one of my projects I stripped down the following minimal package.json:

```
{
  "name": "yarntest-graceful-fs",
  "dependencies": {
    "nodemon": "~1.9.*"
  },
  "devDependencies": {
    "grunt": "~1.0.*",
    "grunt-contrib-less": "~1.*"
  }
}
```

Putting this file in a new directory and running `yarn` (so without any node_modules folder or yarn.lock) it does **not** install `graceful-fs` although nodemon depends on it.
If I delete _any_ of the two devDependencies `graceful-fs` gets correctly installed in the node_modules folder.

**What is the expected behavior?**

I expect yarn to install `graceful-fs` if any of the modules depend on it.

**Please mention your node.js, yarn and operating system version.**
node: 4.4.7
yarn: v0.15.1
OS: Windows 10 Pro

Thanks for the incredible work! I am really looking forward to using yarn!

**Comment by mtraynham** [comment]
I also ran into the `graceful-fs` missing issue, but I can't particularly pinpoint which combination of dependencies is causing the problem.  I know `gulp` requires it, but I have two gulp projects and it works correctly for one, but not the other.  I tried this on both Linux Mint and OSX, both experience the same symptoms.

Potentially a dependency version conflict?

node 6.8.1
yarn 0.15.1
Linux Mint & OSX

**Comment by cebor** [comment]
Same issu, with following package.json https://github.com/cebor/ng2-start/blob/master/package.json

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? I'm not able to recreate the issue using the latest Yarn `v0.17.10` using node `v6.9.1`. `graceful-fs` is correctly installed.

```
 more yarn.lock | grep graceful-fs
    graceful-fs "^4.1.2"
    graceful-fs "^4.1.2"
graceful-fs@^4.1.2:
  resolved "https://registry.yarnpkg.com/graceful-fs/-/graceful-fs-4.1.11.tgz#0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658"
    graceful-fs "^4.1.2"
    graceful-fs "^4.1.2"
    graceful-fs "^4.1.2"
    graceful-fs "^4.1.2"
    graceful-fs "^4.1.2"
```

Either way appears to be a duplicate of https://github.com/yarnpkg/yarn/issues/785

**Comment by jdoose** [comment]
It was still present with yarn 0.17.8, after updating to 0.17.10 it seems ok.
I am closing this issue.

(and yes, I think it is a duplicate to #785, I somehow missed that when I opened the issue)

Thanks to everybody for the great work done here!
