### ISSUE TITLE
yarn install --production complains about missing devDependencies

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1115]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `package.json` for Yarn itself has this `devDependency`:
```
  "devDependencies": {
    "eslint-plugin-yarn-internal": "file:scripts/eslint-rules",
  }
```

As part of building the distribution tarball, we run `npm pack`, extract the resulting tarball, run `npm install --production` to install just the prod dependencies, then archive the resulting files (see `build-dist.sh` and `build-dist.ps1`).

`scripts/eslint-rules` is only needed for dev builds and not for production builds, and we **don't** want to distribute it with Yarn,, so we do not copy it into the `dist` directory. `npm install --production` is fine with that, while `yarn install --production` complains:

```
λ yarn install --production
yarn install v0.15.1
[1/4] Resolving packages...
error "C:\\src\\yarn\\dist\\scripts\\eslint-rules" doesn't exist.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`git clone https://github.com/yarnpkg/yarn.git', modify `scripts/build-dist.ps1` (on Windows) or `scripts/build-dist.sh` to run `yarn install --production`  rather than `npm install --production`, watch it fail.

**What is the expected behavior?**
`yarn install --production` should ignore all issues relating to devDependencies

**Please mention your node.js, yarn and operating system version.**
Node.js v6.7.0
Windows 10 64-bit
Latest master of Yarn as of a few minutes ago

**Comment by kittens** [comment]
This is intentional behaviour. `devDependencies` need to be discoverable so we can build up the entire dependency graph. We omit dev nodes when in production and still take them into consideration when we perform the deduping hoisting so we get consistent module positions in the graph for dev and prod.

**Comment by Daniel15** [comment]
Ahh, that makes sense. I guess we'll have to do something special when building Yarn itself. Thanks!
