### ISSUE TITLE
Error: Cannot find module 'user-home'

### ISSUE THREAD

**Issue by noahsw** [yarnpkg/yarn#1118]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Ran into trouble install Yarn using apt-get on Ubuntu 14.04 (CircleCI)

```
sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
"deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update -y
```

```
ubuntu@box1015:~$ node -v
v4.5.0
ubuntu@box1015:~$ sudo apt-get install yarn
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libc-ares2 libv8-3.14.5 os-prober
Use 'apt-get autoremove' to remove it.
Recommended packages:
  nodejs
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 0 to remove and 84 not upgraded.
Need to get 1,546 kB of archives.
After this operation, 23.2 MB of additional disk space will be used.
Get:1 http://dl.yarnpkg.com/debian/ stable/main yarn all 0.15.1-2 [1,546 kB]
Fetched 1,546 kB in 0s (26.2 MB/s)
Selecting previously unselected package yarn.
(Reading database ... 341963 files and directories currently installed.)
Preparing to unpack .../archives/yarn_0.15.1-2_all.deb ...
Unpacking yarn (0.15.1-2) ...
Setting up yarn (0.15.1-2) ...
ubuntu@box1015:~$ export PATH="$HOME/.yarn/bin:$PATH"
ubuntu@box1015:~$ which yarn
/home/ubuntu/.yarn/bin/yarn
ubuntu@box1015:~$ yarn --version
module.js:327
    throw err;
    ^

Error: Cannot find module 'user-home'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.yarn/bin/yarn.js:8:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
Yarn should run properly after `apt-get install yarn`

**Please mention your node.js, yarn and operating system version.**
Node: 4.5.0
Yarn: N/A
OS: Ubuntu 14.04

**Comment by Daniel15** [comment]
Hi @noahsw! 

That path looks incorrect - It should be executing `/usr/bin/yarn`, not `/home/ubuntu/.yarn/bin/yarn`. Can you please update the PATH to either remove `$HOME/.yarn/bin` or add it to the end rather than the start, and see if that helps?

We're using the Ubuntu package for Yarn on CircleCI as well, and it's working well: https://circleci.com/gh/yarnpkg/yarn/1441

**Comment by noahsw** [comment]
Hey @Daniel15,

I was just following the instructions at the bottom of the Linux tab on https://yarnpkg.com/en/docs/install

```
You will need to set up the PATH environment variable in your terminal to have access to Yarn’s binaries globally.

Add export PATH="$HOME/.yarn/bin:$PATH" to your profile (this may be in your .profile, .bashrc, .zshrc, etc.)
```

btw - Yarn is *lightyears* ahead of NPM. Thank you thank you thank you!

**Comment by Daniel15** [comment]
Good catch! I just updated the site to add Yarn's `.bin` to the end of the path rather than the start: https://github.com/yarnpkg/website/commit/9f694513faefa80f3c2bc5d992265ea445e0a568

Can you confirm if changing the path fixes it?

**Comment by busches** [comment]
@noahsw Did @Daniel15's suggestion work?

Otherwise six weeks with no reply, can this be closed?

**Comment by noahsw** [comment]
Sorry @busches , haven't been able to verify the fix firsthand but I believe it should be good enough to close.
