### ISSUE TITLE
yarn help COMMAD does not output command description

### ISSUE THREAD

**Issue by mickeyvip** [yarnpkg/yarn#1119]
When typing the following for any `COMMAND`

```
$ yarn help COMMAND
```

the output is `usage` and `options`, but there is no `description` about what the command actually does.

One would expect to see a command description. For example:

```
$ yarn help install

    Install all the dependencies listed within `package.json` in the local `node_modules` folder

    Usage: `yarn install [flags]`

    Options:

        ...
```

node.js version `6.7.0`
yarn version `0.15.1`

**Comment by lorensr** [comment]
It would be nice to see different Usage forms, as discussed in #947

**Comment by Joklogh** [comment]
Can i try to implement this feature? 
If yes, where i can start?

**Comment by BYK** [comment]
@Joklogh - Take a look at https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/help.js

You can probably add a `helpText` field to all commands and make the `help` command use that.

**Comment by Marko50** [comment]
I believe @Joklogh dropped this. Will try to start implementing this, and submit a pull request next week.
