### ISSUE TITLE
yarn-offline-mirror is read from .npmrc, support .yarnrc

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#1128]
**Do you want to request a _feature_ or report a _bug_?**

_feature_

**What is the current behavior?**

Putting `yarn-offline-mirror` setting in .yarnrc does not work, it is only read from .npmrc

**Please mention your node.js, yarn and operating system version.**
yarn 0.15.1

**Comment by FLGMwt** [comment]
Should this be *removed* from .npmrc in favor of .yarnrc?

**Comment by bestander** [comment]
I think it should but we need to be backwards compatible for some time
