### ISSUE TITLE
Doesn't install dependencies' bins to node_modules/.bin/

### ISSUE THREAD

**Issue by corysimmons** [yarnpkg/yarn#1130]
I'm not sure if it should install devDependencies to .bin, but I think it should definitely install dependencies to .bin.

Works like this with npm.

**Comment by joscha** [comment]
cc @treshugart

**Comment by DanielZlotin** [comment]
Duplicate of #760 ?

**Comment by corysimmons** [comment]
Yup, and his is filled out with more deets.
