### ISSUE TITLE
Error: Cannot install packages on ubuntu 16.04

### ISSUE THREAD

**Issue by igorvisi** [yarnpkg/yarn#1133]
$yarn global add taco
yarn global v0.15.1
[1/4] Resolving packages...
error An unexpected error occured, please open a bug report with the information provided in "/home/visi/.yarn-config/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by Daniel15** [comment]
Hi @igorvisi! Could you please include the contents of `/home/visi/.yarn-config/global/yarn-error.log` here? Thanks!

**Comment by igorvisi** [comment]
@Daniel15 ,here they are:
 $cat .yarn-config/global/yarn-error.log

Arguments: 
  /usr/bin/nodejs /usr/bin/yarn global add taco

PATH: 
  /home/visi/.nvm/versions/node/v6.0.0/bin:/home/visi/.rbenv/shims:/home/visi/.rbenv/bin:/home/visi/.rbenv/shims:/home/visi/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
  0.15.1

Node version: 
  6.8.0

Platform: 
  linux x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: connect ECONNREFUSED 127.0.0.1:5080
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

**Comment by Daniel15** [comment]
`127.0.0.1:5080` looks suspect... Are you using a local proxy or something like that?

**Comment by Daniel15** [comment]
@igorvisi  - Did you ever use "local-npm" at some stage? Could you please check `~/.npmrc`  and see if `127.0.0.1:5080` is mentioned in there? It looks like local-npm uses that URL as its proxy: https://github.com/nolanlawson/local-npm

**Comment by igorvisi** [comment]
@Daniel15 yes I have used local-npm ! thanks It Works
