### ISSUE TITLE
Error : Intalling packages offline on Arch 

### ISSUE THREAD

**Issue by igorvisi** [yarnpkg/yarn#1135]
I previously installed babel when I was connected , but when I'm offline : 

$yarn add --offline babel  
yarn add v0.15.1
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find any versions for "babel" that matches "latest" in our cache. Possible versions: ""
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by hpurmann** [comment]
This behaviour is _not_ a bug. With `yarn add --offline babel` you are requesting `babel@latest` implicitly. Without an internet connection, there is no way to tell if the version in your cache is the latest available.

Instead, you have to specify the `babel` version when installing offline, e.g. `yarn add --offline babel@^6.5.2`.

In a real world use-case you'd rather do `yarn install --offline` which uses the versions specified in your `yarn.lock`.

Can you close this, @Daniel15?

**Comment by wyze** [comment]
Thanks for the explanation @hpurmann!
