### ISSUE TITLE
Completely hung when installing example project.

### ISSUE THREAD

**Issue by jordwalke** [yarnpkg/yarn#1144]
**Do you want to request a _feature_ or report a _bug_?**

Bug.

**What is the current behavior?**

Installation of ExampleProject hangs.

**If the current behavior is a bug, please provide the steps to reproduce.**

Try to install `ExampleProject` on my macbook (12" macbook 2 cores, not fast).

Follow yarn instructions here:
https://github.com/reasonml/ExampleProject

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

Node v6.2.1. yarn 0.15.1.

**Comment by jordwalke** [comment]
Installation remains stuck like this screenshot.

<img width="1107" alt="stuck" src="https://cloud.githubusercontent.com/assets/977348/19426974/84b336de-93f5-11e6-968a-3183cc9ed286.png">

**Comment by jordwalke** [comment]
Please add to the Reason milestone  @cpojer 
(Not sure if I have the perms to do it).

**Comment by SanderSpies** [comment]
Reproducing this issue has been interesting: on a corporate internet connection it took significantly longer compared to a mobile or home internet connection.

Mobile: 35 seconds
Corporate: 443 seconds

**Comment by bestander** [comment]
Not relevant at this point, we'll get back to this later

**Comment by christo8989** [comment]
We had this issue and it was because the vpn got disconnected.
