### ISSUE TITLE
Roadmap to 1.0?

### ISSUE THREAD

**Issue by wearhere** [yarnpkg/yarn#1147]
Hi folks, I'm extremely impressed by the fast progress you're making. I see that the current version is a 0.x release i.e. still subject to breaking changes, but I can't find any sort of roadmap to a 1.0. What does that milestone entail? What would block an organization from using Yarn in production? Thanks!

**Comment by thejameskyle** [comment]
>  What would block an organization from using Yarn in production

Don't consider Yarn being pre-1.0 a reason not to use it in production

**Comment by cpojer** [comment]
We didn't feel confident bumping Yarn to 1.0 for the initial open source release and decided to go with `0.x`. Many FB projects (React, Jest) have dropped the leading zero indicating they are "way past 1.0". It is hard to say where Yarn would be on the traditional scale of version numbers but as @thejameskyle pointed out, the version number is not an indicator whether or not to use it in production.

At Facebook we use Yarn for all react-native development and are currently converting all remaining projects to use Yarn. That should be enough of an indicator of its stability.

We don't have a formal roadmap yet but we will eventually share one. Please stay tuned!
