### ISSUE TITLE
clash with git bash.

### ISSUE THREAD

**Issue by fridaymeng** [yarnpkg/yarn#1149]
the windows installer is clash with git bash.

**Comment by thejameskyle** [comment]
Can you provide more information about the problem?

**Comment by fridaymeng** [comment]
ok, my os is win10,when i installed,the git bash is not working.

**Comment by busches** [comment]
Can you provide even more clarification? Git bash no longer works after installing Yarn? How did you install Yarn?

**Comment by gsklee** [comment]
@fridaymeng Is this still happening with the latest version of Yarn (v0.24)?

**Comment by gsklee** [comment]
Issue closed due to lack of further information; if you can still reproduce it on the latest Yarn (v0.27), please submit a new issue with detailed info, thanks!
