### ISSUE TITLE
`npm i yarn -g` speed (bundledDependencies?)

### ISSUE THREAD

**Issue by puzrin** [yarnpkg/yarn#1159]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behavior?**

``` sh
$ time npm install yarn -g

real    0m8.281s
user    0m5.594s
sys 0m0.809s
```

**What is the expected behavior?**

It's common to run `npm i yarn -g` for travis-ci and other things. It would be nice to make it faster if possible. 10 seconds seems a bit slow.

May be it worth to add `bundledDependencies` property to `package.json`? Total downloads size will be the same anyway.

**Please mention your node.js, yarn and operating system version.**

node 6.8.1, npm 3.10.8, yarn 0.15.1

**Comment by Daniel15** [comment]
Hmm, I don't think we can do a lot about npm being slow. 

On a continuous integration system, try using our Linux packages rather than npm. We recently added relevant documentation here: https://yarnpkg.com/en/docs/install_ci

**Comment by puzrin** [comment]
1. I didn't measured, but bundled dependencies should save fetches and probably unpack time
2. Install from foreign repos on travis will not work for docker containers, until whitelisted (at least now https://github.com/travis-ci/apt-source-whitelist/issues/321)

IMHO it costs nothing to add `bundledDependencies` but if you don't like this idea - feel free to close this issue. I'll wait until install from deb work.

**Comment by Daniel15** [comment]
I didn't actually know about `bundledDependencies` until today. Interesting idea!

> Install from foreign repos on travis will not work for docker containers

I find this limitation really strange... CircleCI also uses Docker, but `sudo` and foreign repos work fine there.  We're using both Travis and CircleCI for Yarn, and in generally I've found Circle much more powerful and easier to deal with.

**Comment by puzrin** [comment]
See npm's config for live example https://github.com/npm/npm/blob/v3.10.9/package.json#L105-L188 if it helps

I know about `sudo: required`, but idea is to minimize total test time and `sudo: false` is faster. It's not a problem to install yarn, goal is how to do it quickly with minimal efforts.

**Comment by Daniel15** [comment]
`sudo: false` is only faster due to limitations in Travis' architecture, there's no intrinsic reason why it has to be slower. I hope they fix that in the future 😄 

For what it's worth, with Yarn we didn't see any statistically significant change in build time after changing `sudo: false` to `sudo: required`

**Comment by puzrin** [comment]
Did you counted delay before VM start? The main difference is there.

**Comment by Daniel15** [comment]
I don't think this is an issue any more. We can consider `bundledDependencies`, but most remotely-hosted CI systems preinstall Yarn now, so installation time of Yarn itself is not an issue. Additionally, we dramatically improved the installation speed of all the non-npm installation methods with the most recent Yarn release.
