### ISSUE TITLE
incompatible engine "node" with an npm module

### ISSUE THREAD

**Issue by rogervila** [yarnpkg/yarn#1160]
**Do you want to request a *feature* or report a *bug*?** a bug

**What is the current behavior?** incompatible engine "node" with an npm module

**If the current behavior is a bug, please provide the steps to reproduce.**
1 - create this `package.json`:
```json
{
  "name": "vueadmin",
  "dependencies": {
    "vue-admin": "^0.1.6"
  }
}
```
2 -then run `yarn`

**What is the expected behavior?**
It should install `vue-admin`, but it fails. I can install it with `npm install`

**Please mention your node.js, yarn and operating system version.**
OSX El Capitan, Yarn 0.15.1, Node 6.2.2

The terminal output:
![yarn](https://cloud.githubusercontent.com/assets/6053012/19439668/46c5c154-947f-11e6-9fa5-6bf66203984b.png)

**Comment by jbe456** [comment]
Seems duplicate of https://github.com/yarnpkg/yarn/issues/638

**Comment by rogervila** [comment]
@jbe456, yes its similar, but the scenario is different. I hope it helps to solve the bug.

**Comment by mrichards-mdsol** [comment]
This can be a blocker for adoption.

swagger doesn't install with yarn for a similar reason.
Using Node 4.6.1 (latest recommended release) I get the following:
```
error swagger-editor@2.10.4: The engine "node" is incompatible with this module. Expected version ">=5.8.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Swagger has a dependency of ^2.9.2, but swagger-editor has an engine limitation, so yarn should try an older version (eg; 2.9.9) or make it easy to manually provide an alternative preferred version.

**Comment by wmertens** [comment]
@rogervila how is this different? You want to install a module that declares a different node engine than what you have, and the `--ignore-engines` flag is there for that purpose?

**Comment by rogervila** [comment]
After updating yarn to 0.16.1 everything works perfectly, with & without `--ignore-engines`
Looks like vue-admin has added yarn support now.
