### ISSUE TITLE
yarn link doesn't work when project name has sub-folder

### ISSUE THREAD

**Issue by singuerinc** [yarnpkg/yarn#1161]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn links` fails if the package name is for instance `@company/package-name`

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an empty project: `mkdir -p ~/code/mycompany/project`
2. Create package.json with `yarn init`
3. Use `@company/name` as project name inside `package.json`
4. Run `yarn link`
5. Yarn fails with:
```
yarn link v0.15.1
error ENOENT: no such file or directory, symlink '../../../code/mycompany/project' -> '/Users/username/.yarn-cache/.link/@company/name'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/link for documentation about this command.
```

**What is the expected behavior?**
Yarn should create a link to the package.

**Please mention your node.js, yarn and operating system version.**
```
node v5.12.0
yarn v0.15.1
mac os x 10.11.16
```

It works if I manually create the folder:
```
mkdir -p /Users/username/.yarn-cache/.link/@company
yarn link
# success Registered "@company/name"
```

**Comment by vfernandestoptal** [comment]
Looks like this was fixed in https://github.com/yarnpkg/yarn/pull/910

**Comment by singuerinc** [comment]
I have tested it in v0.16.1 and it's working!
