### ISSUE TITLE
When installing with yarn, deps don't work as they would when installing with npm

### ISSUE THREAD

**Issue by jh3y** [yarnpkg/yarn#1164]
_using yarn 0.15.1, OSX 10.10.1 and node 6.3.1_

Might be overlooking something really simple here :confused:

But I may have encountered a possible bug with how dependencies are being installed or the versions that may be being installed.

I'm working on a simple project that makes use of `webpack-dev-server` and utilizes the hot module reloading feature for live updates in the browser and auto bundling.

I set up a clean simple project, and thought I'd give `yarn` a spin to pull in the dependencies. HMR wouldn't work at all.

As the source hasn't changed I figured it must be the `node_modules`. I removed all dependencies and reinstalled with `npm`. HMR has returned and is working as expected.

To make sure `yarn` was the issue, I removed all deps again and reinstalled with `yarn`. Sure enough, HMR ceased to work again.

To reproduce, simply start up a project that uses `webpack-dev-server` with HMR. Test it using deps installed with `yarn` and then when the deps are installed using `npm`.

You'd expect HMR to work regardless of which package manager you use to install dependencies.

@jh3y

**Comment by betoflakes** [comment]
Same here, but it happens with browsersync, when start my watch gulp job where is browsersync, the job doesn't works

**Comment by jh3y** [comment]
Hmm. Maybe a dependency that both `browser-sync` and `webpack-dev-server` rely on then that isn't sitting quite right when installed with `yarn` :cry:

**Comment by altayaydemir** [comment]
when I tried to migrate my project to yarn, I'm had the same issue with `webpack-dev-server` and `react-hot-loader v3`. 

no idea why 🤔

**Comment by jh3y** [comment]
Hopefully it's something trivial 🙏

**Comment by tlaak** [comment]
I've encountered a similar issue in the project I'm working on. Slick-carousel works when installed with npm, but fails when installed with yarn.

**Comment by altayaydemir** [comment]
@tlaak @jh3y have you guys find any solutions? 😅

**Comment by jh3y** [comment]
Nope 😭 

So I'm still not committed to using it.

**Comment by tlaak** [comment]
It worked with version 0.16, but now that I upgraded to 0.16.1 my project is not even building anymore 😭

**Comment by altayaydemir** [comment]
😭

**Comment by jh3y** [comment]
I seem to be having much better luck with everything now 😸 

`browser-sync` has been working fine for me :tada:

@jh3y

**Comment by J-Katzen** [comment]
Having similar issues with webpack

**Comment by gsklee** [comment]
@jh3y Is this still happening on the latest version of Yarn (v0.24)?

**Comment by jh3y** [comment]
Sorry for the delayed response 😅 

Wanted to make sure and try this out with a fresh clone of the same project that prompted opening the issue. Good news! Seems the issue has gone for me :tada: `HMR` and everything else working as expected. It may have been resolved some time/versions ago.

Happy to close this 👍

**Comment by gsklee** [comment]
@jh3y Great to know! 👍
