### ISSUE TITLE
Support TLS client certificates for connecting to the registry

### ISSUE THREAD

**Issue by cnorthwood** [yarnpkg/yarn#1165]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

When using a private NPM registry which is protected by TLS client certificates, the following error occurs:

`error write EPROTO 140735275094016:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 40
140735275094016:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:656:`

The cert and key are specified in the `.npmrc`, which display when running `yarn config list`. `npm install` behaves correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

Yarn uses the configured client certificate and key to connect to the registry.

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v6.3.1
$ yarn --version
0.15.1
$ sw_vers -productVersion 
10.11.6
```

**Comment by Daniel15** [comment]
Does npm support client certs?
