### ISSUE TITLE
`yarn check --integrity` fails

### ISSUE THREAD

**Issue by grempe** [yarnpkg/yarn#1167]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

The yarn documentation documents the `yarn check --integrity` command:

https://yarnpkg.com/en/docs/cli/check

However running `yarn check --integrity` fails with the following error:

```
$ yarn check
yarn check v0.15.1
success Folder in sync.
✨  Done in 0.63s.

$ yarn check --integrity
yarn check v0.15.1
error This command doesn't require any arguments.
info Visit http://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn check --integrity`

**What is the expected behavior?**

Runs without error.

**Please mention your node.js, yarn and operating system version.**

macOS : 10.12

yarn installed via homebrew:

```
$ brew info yarn
yarn: stable 0.15.1 (bottled), HEAD
Javascript package manager
https://yarnpkg.com/
/usr/local/Cellar/yarn/0.15.1 (5,254 files, 13M) *
  Poured from bottle on 2016-10-17 at 10:30:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb
==> Dependencies
Required: node ✔
```

Node:

```
$ brew info node
node: stable 6.8.1 (bottled), HEAD
```

**Comment by kittens** [comment]
This is fixed on `master`.

**Comment by grempe** [comment]
@kittens Do you have a link to the commit that fixes this please? Or to another bug?
