### ISSUE TITLE
[feature] --warmup flag to only write cache

### ISSUE THREAD

**Issue by ghost** [yarnpkg/yarn#1170]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

`yarn add [package]` and `yarn install` resolve packages and copies the node_modules structure. Dependant on flags it writes `package.json` and `yarn.lock` as-well.

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected (extended) behavior?**

The idea would be an extra flag `--warmup`, adding or installing packages with this flag would only write to the `.yarn-cache`, ignoring the link step. Since nothing would be linked it would also skip writing the `package.json` and `yarn.lock` file.

I believe it might come in useful while setting up a development environment for the first time, while getting everything up and running you could already warmup the `.yarn-cache` if you know for example a lot of your future projects will have `react`, `babel`, `webpack`,... dependencies before even ever starting. In the same way it could come in handy in some other smaller cases, ex. installing (preparing) dependencies from anywhere without being in the correct directory.

`--warmup` flag felt more intuitive to me, but it could of course just be `yarn warmup [package]` as well.

**Please mention your node.js, yarn and operating system version.**

N/A

**Comment by gsklee** [comment]
@bestander close

The scale of this feature request means that it needs to go through the [proper RFC process](https://github.com/yarnpkg/rfcs).

**Comment by bestander** [comment]
@ghost, the idea seems legit, send an RFC
