### ISSUE TITLE
Feature Request: Multi-context authenticated actions.

### ISSUE THREAD

**Issue by joshmanders** [yarnpkg/yarn#1172]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

Only single user

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

When I am working on package, I often publish different ones under different accounts, in any given moment I may be building a package for internal usage, but abstract parts of it out into a package for general usage under a different name. Currently my company runs under one name, I have my own name, and another account for scoped public packages. Context switching between all these accounts using npm is cumbersome, and I have made [a wrapper script](https://github.com/aniftyco/npm-as) around it to help, but I'd like to see this ability native in Yarn.

So add support for a global `--as` flag, that allows me to basically `yarn login` for many accounts, say `yarn login --as joshmanders` and then the credentials are saved for that alias, and I can do `yarn login --as mycompany` and then when I publish I can do `yarn publish --access public --as mycompany` but keep default account to `joshmanders`

**Please mention your node.js, yarn and operating system version.**

**Node** v6.8.1
**Yarn** v0.15.1
**macOS** v10.12 (16A323)

**Comment by gsklee** [comment]
@bestander close

The scale of this feature request means that it needs to go through the [proper RFC process](https://github.com/yarnpkg/rfcs).
