### ISSUE TITLE
Please add support for private npm repos

### ISSUE THREAD

**Issue by jitcoder** [yarnpkg/yarn#1173]
**Do you want to request a *feature* or report a *bug*?** 
feature

**What is the current behavior?** 
error https://registry.yarnpkg.com/<NPM PRIVATE REPO>: NOT FOUND

**If the current behavior is a bug, please provide the steps to reproduce.**
run yarn with private npm repo dependency

**What is the expected behavior?** 
yarn runs install successfully

**Please mention your node.js, yarn and operating system version.**
node -v "v4.3.2"
macOS

**Comment by chicoxyzzy** [comment]
They are already supported. #839

**Comment by jitcoder** [comment]
my bad, thanks!
