### ISSUE TITLE
`yarn help config` has the wrong wording in the output

### ISSUE THREAD

**Issue by deecewan** [yarnpkg/yarn#1174]
Running OSX 10.11, yarn v0.15.1.  node v6.7.0

When running `yarn help config`, the output contains `access` as the command title, instead of config.

![image](https://cloud.githubusercontent.com/assets/4755785/19459298/1b64753c-9515-11e6-8a0f-82270990e506.png)

I had a look through the codebase, and it seems that `buildSubCommands` is being passed the right name, so this may be fixed and not released yet.

**Comment by yupkey** [comment]
I've checked it locally. There is no longer an issue. Npm package need to be updated.

node bin/yarn.js help config
  Usage: yarn config [set|get|delete|list] [flags]

**Comment by samccone** [comment]
This has been fixed.

Thanks @deecewan for the issue and @yupkey for the follow up :heart:
