### ISSUE TITLE
yarn install succeeds with missing dependency

### ISSUE THREAD

**Issue by joefiorini** [yarnpkg/yarn#1175]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

If I manually remove a single dependency from `node_modules`, then run `yarn`, it does not reinstall that dependency. Running `yarn check` _does_ report that that dependency is missing, however the dependency shows up in `yarn ls`.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Clone https://github.com/joefiorini/yarn-dep-test
- Run `yarn` to install deps from lockfile
- `rm -rf node_modules/react` to remove a single dependency
- Run `yarn` again to try to reinstall the missing dependency, witness yarn report success

**What is the expected behavior?**

The "current behavior" listed above seems very inconsistent. I would expect that my dependencies are returned to the state described by the lockfile after any time I run `yarn`.

**Please mention your node.js, yarn and operating system version.**

node.js: 6.8.1
yarn: 0.15.1
os: macOS Sierra

**Comment by joefiorini** [comment]
@Daniel15 FWIW, I did a little digging on this. It looks like the problem is in `generateIntegrityHash`. When checking for what to install, yarn generates an integrity hash describing the current state of the installed world, then caches it to `node_modulues/.integrity-hash`. Then it compares that to a freshly generated hash from the lockfile, and if they haven't changed no need for install.

So there seems to be an assumption here that the state of installed modules will not change between yarn install runs, which is not _always_ true. Maybe there is no need to cache the integrity hash and instead just always regenerate from registries? That might be slow on a large project thouugh, so not sure if it's a viable approach.

**Comment by joefiorini** [comment]
Also, manually removing the `node_modules/.integrity-hash` file fixes the issue since it regenerates the hash from the current state of the `node_modules` folder.

**Comment by kittens** [comment]
The behaviour is expected. You shouldn't be directly touching things in `node_modules`, that's the job of the package manager. You can do `yarn install --force` to skip the validation we do up front and force an install.

**Comment by srounce** [comment]
> You shouldn't be directly touching things in node_modules, that's the job of the package manager.

@kittens Why so quick to dismiss? This seems a valid (and annoying) issue. 
`yarn unlink <pkg>` be substituted for the `rm -rf node_modules/<pkg>` step. Now, everything has been done via the package manager and we have still managed to end up in this state.
One would expect the missing dependencies to be fulfilled simply by running `yarn` (node_modules state does not match lockfile after all), not by having to `--force` install all dependencies.
