### ISSUE TITLE
"invalid tar file"

### ISSUE THREAD

**Issue by dangreen** [yarnpkg/yarn#1182]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
`package.json`:
```
...
"lib": " https://USER:KEY@github.com/Elksimo/lib.git"
...
```
```
error https://dangreen:KEY@github.com/Elksimo/lib.git: invalid tar file
    at Extract.Parse._startEntry (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
    at Extract.Parse._process (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
    at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
    at emitOne (events.js:96:13)
    at BlockStream.emit (events.js:188:7)
    at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.flush (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
    at BlockStream.end (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
    at Extract.Parse.end (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
    at UnpackStream.onend (_stream_readable.js:512:10)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add https://USER:KEY@github.com/PRIVATE/REPO.git`
**Please mention your node.js, yarn and operating system version.**
```
$ yarn -V
0.15.1
$ node -v                                                                                      
v6.3.0
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12 (16A323)
      Kernel Version: Darwin 16.0.0
```

**Comment by dangreen** [comment]
In `0.16.0` this fixed

**Comment by rkurbatov** [comment]
yarn 0.16.1, node v6.9.1, Linux. Having the same issue with private npm repo.

**Comment by landonpoch** [comment]
yarn 0.16.1, node v5.12.0, mac osx. Having the same issue with private repo also.  We're using artifactory.

**Comment by rkurbatov** [comment]
I had to do some cleaning and yarn/npm login/logout to fix that problem

**Comment by landonpoch** [comment]
I did a npm logout/login
npm cache clean
yarn cache clean

Still seeing the invalid tar file issue.

@rkurbatov Do you recall any other details that you may have had to do?

**Comment by rkurbatov** [comment]
@landonpoch try to remove .npm and all .yarn* folders at your home folder and .npmrc file

**Comment by robinbullocks4rb** [comment]
@rkurbatov @landonpoch don't know if this helps or hinders, but I have the same problem using NPM-hosted private packages on both Heroku (not with Docker) and Docker running locally, both clean environments. For reasons I can't determine though, I don't get the problem on my local, non-Dockerised Mac OS environment.

**Comment by gijsroge** [comment]
Just published a package with yarn 'swiper-thumbnails' and tried to add it in a project and fails.

`Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add swiper-thumbnails

PATH: 
  /usr/local/php5/bin:/Users/gijs.roge/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  0.16.1

Node version: 
  7.0.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "itr-theme-js",
    "dependencies": {
      "fg-loadcss": "1.2.0",
      "jquery": "3.1.1",
      "jquery-sticky": "1.0.4",
      "jquery.spinner": "git+https://github.com/vsn4ik/jquery.spinner.git",
      "offscreen.js": "^1.0.0",
      "photoswipe": "^4.1.1",
      "swiper": "^3.4.0",
      "typekit-cache": "git+https://github.com/morris/typekit-cache.git"
    }
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  amdefine@>=0.0.4:
    version "1.0.1"
    resolved "https://registry.yarnpkg.com/amdefine/-/amdefine-1.0.1.tgz#4a5282ac164729e93619bcfd3ad151f817ce91f5"
  
  async@~0.2.6:
    version "0.2.10"
    resolved "https://registry.yarnpkg.com/async/-/async-0.2.10.tgz#b6bbe0b0674b9d719708ca38de8c237cb526c3d1"
  
  fg-loadcss:
    version "1.2.0"
    resolved "https://registry.yarnpkg.com/fg-loadcss/-/fg-loadcss-1.2.0.tgz#d4e35c809dd1501e4d51bdb803413afa2e7c42a2"
  
  jquery-sticky@1.0.4:
    version "1.0.4"
    resolved "https://registry.yarnpkg.com/jquery-sticky/-/jquery-sticky-1.0.4.tgz#2fe8d03dc904685340daa12cbdd1ca0c921b09ac"
    dependencies:
      jquery "*"
  
  "jquery.spinner@git+https://github.com/vsn4ik/jquery.spinner.git":
    version "0.2.1"
    resolved "git+https://github.com/vsn4ik/jquery.spinner.git#ab71d9af3bf4921e2a7aedb061822f7b5ea59ad3"
  
  jquery@*, jquery@3.1.1:
    version "3.1.1"
    resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.1.1.tgz#347c1c21c7e004115e0a4da32cece041fad3c8a3"
  
  offscreen.js@^1.0.0:
    version "1.0.1"
    resolved "https://registry.yarnpkg.com/offscreen.js/-/offscreen.js-1.0.1.tgz#0598b2586b5b49379816fe23a1df6ca0ef1ad50a"
  
  photoswipe:
    version "4.1.1"
    resolved "https://registry.yarnpkg.com/photoswipe/-/photoswipe-4.1.1.tgz#41b756a2387e220c286598945503014bf622bba9"
  
  source-map@0.1.34:
    version "0.1.34"
    resolved "https://registry.yarnpkg.com/source-map/-/source-map-0.1.34.tgz#a7cfe89aec7b1682c3b198d0acfb47d7d090566b"
    dependencies:
      amdefine ">=0.0.4"
  
  swiper:
    version "3.4.0"
    resolved "https://registry.yarnpkg.com/swiper/-/swiper-3.4.0.tgz#a3ada344ab36fdcbc2369223585393269a39c8c5"
  
  "typekit-cache@git+https://github.com/morris/typekit-cache.git":
    version "1.13.0"
    resolved "git+https://github.com/morris/typekit-cache.git#d2dd4f48b43ba8d7e9c8906024a2273afc9fa72b"
    dependencies:
      uglifyjs "^2.4.10"
  
  uglify-to-browserify@~1.0.0:
    version "1.0.2"
    resolved "https://registry.yarnpkg.com/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz#6e0924d6bda6b5afe349e39a6d632850a0f882b7"
  
  uglifyjs@^2.4.10:
    version "2.4.10"
    resolved "https://registry.yarnpkg.com/uglifyjs/-/uglifyjs-2.4.10.tgz#632927319fa6a3da3fc91f9773ac27bfe6c3ee92"
    dependencies:
      async "~0.2.6"
      source-map "0.1.34"
      uglify-to-browserify "~1.0.0"
      yargs "~1.3.3"
  
  yargs@~1.3.3:
    version "1.3.3"
    resolved "https://registry.yarnpkg.com/yargs/-/yargs-1.3.3.tgz#054de8b61f22eefdb7207059eaef9d6b83fb931a"

Trace: 
  Error: https://registry.yarnpkg.com/swiper-thumbnails/-/swiper-thumbnails-1.0.0.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.resume (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:58:15)
      at Extract.Reader.resume (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/fstream/lib/reader.js:249:34)
      at Entry.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:261:8)
      at emitNone (events.js:86:13)
`

**Comment by aspirisen** [comment]
Have the same

```
[2/4] Fetching packages...
error http://privaterepo/fsevents/-/fsevents-1.0.15.tgz: invalid tar file
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, open 'C:\\Users\\***\\AppData\\Local\\Yarn\\cache\\npm-fsevents-1.0.15-fa63f590f3c2ad91275e4972a6cea545fb0aae44\\.yarn-metadata.json'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\projects\\**\\**\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by lior-a** [comment]
yarn 0.16.1 mac - have this issue with private npm registry (with token etc..)

**Comment by LinusU** [comment]
Same problem on Ubuntu Linux, Yarn 0.17.10

**Comment by TrustNik** [comment]
@lior-a 
>yarn 0.16.1 mac - have this issue with private npm registry (with token etc..).


I think that it is related https://github.com/yarnpkg/yarn/issues/547

**Comment by throrin19** [comment]
Same problem on OSX, Yarn 0.17.10 and custom registry (private sinopia)

**Comment by oshalygin** [comment]
same issue as @landonpoch while using Artifactory.  No issues on my local machine but fails all over the place during the travis build.

**Comment by balanceiskey** [comment]
After some tooling around I've cornered the issue down a little more. I was using `yarn publish` to publish a scoped package. Attempts to then `yarn add` or `npm install` that package would result in the `cb` error. I switched back to the class `npm publish` and things appear to be A-OK. I don't have additional details on what might be causing issues during `yarn publish` but if anyone's got tips on how to debug that, happy to help out.

**Comment by oshalygin** [comment]
Should we re-open this issue?  Why was it closed?

**Comment by deecewan** [comment]
having this same issue.  `yarn publish` seems to work correctly.  `yarn install` in another location results in 
`error An unexpected error occurred: "https://registry.yarnpkg.com/translation-io/-/translation-io-0.0.4.tgz: invalid tar file"`

I took a look inside the tarballs, extracted using the built in utility on macOS Sierra
in `0.0.4` (as above), the `lib/` and `src/` folders are both empty, however there is a valid-looking `package.json`, `LICENCE` and `README.md`.

LInks to tarballs:
- 0.0.4 (broken): https://registry.yarnpkg.com/translation-io/-/translation-io-0.0.4.tgz
- 0.0.5 (working): https://registry.yarnpkg.com/translation-io/-/translation-io-0.0.5.tgz

The repo is public.  [you can take a look here](https://github.com/deecewan/translation-io).  If I publish using `npm publish`, everything works, so you can see that there is a problem with how yarn is packaging the tarball or shipping it to NPM.

I'll also note that when using `yarn publish`, I used the CLI to update the `package.json` version, rather than when using NPM where I updated it myself.

**Comment by divyanshu013** [comment]
This could be an issue with `yarn publish`. I tried installing a package published by `yarn` but got the same error. Then I unpublished my package from npm and published it again this time using `npm publish`. Now it seems to be working fine.

I'm on yarn v0.21.3 on a Linux machine.

**Comment by danny-andrews** [comment]
I'm still having this issue on yarn v0.20.3 with a scoped package.
