### ISSUE TITLE
`npm run` vs `yarn run`

### ISSUE THREAD

**Issue by dangreen** [yarnpkg/yarn#1185]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
`package.json`:
```
...
"scripts": {
  "build": "gulp build"
}
...
```
**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn run build`
```
...
sh: 1: gulp: not found
```
**Please mention your node.js, yarn and operating system version.**
```
$ yarn -V
0.15.1
$ node -v                                                                                      
v6.3.0
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12 (16A323)
      Kernel Version: Darwin 16.0.0
```

**Comment by jonnitto** [comment]
Do you have a solution?

**Comment by dangreen** [comment]
@jonnitto it's not a bug, `NODE_ENV` was setted to `production` and yarn install only `dependencies` without `devDependencies`
