### ISSUE TITLE
self-update errors on authentication

### ISSUE THREAD

**Issue by thibmaek** [yarnpkg/yarn#1187]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Running `yarn self-update` outputs the following error:
![screen shot 2016-10-18 at 11 31 40](https://cloud.githubusercontent.com/assets/6213695/19472183/74bd1b6e-9526-11e6-823c-053c50edff7d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn self-update` with yarn installed trough piped shell script

**What is the expected behavior?**
No error when running `self-update`

**Please mention your node.js, yarn and operating system version.**
v.6.8.0, v0.15.1, macOS Sierra

**Comment by kukac7** [comment]
me too.
it was installed by brew.

**Comment by mbeaudru** [comment]
Same here, installed via npm on a Windows machine 👍

**Comment by andreaswachowski** [comment]
I had the same error with v0.15.1, and could just now (a minute ago) perform `brew update; brew upgrade` to install yarn 0.16.0, and now it seems to work:

```
$ yarn self-update
yarn self-update v0.16.0
success Yarn is already using the latest version.
✨  Done in 0.61s.
```

**Comment by kukac7** [comment]
after `brew update`, `brew upgrade`:

```
MacBook ~> yarn self-update
yarn self-update v0.16.0
success Yarn is already using the latest version.
✨  Done in 0.92s.

**Comment by mbeaudru** [comment]
I can't do that on Windows. Any leads ? Should I install yarn all over again to update ? 😕

**Comment by troglotit** [comment]
The identical bug was already files #612 and already fixed #676 
`npm install -g yarn --update` updated yarn for me to v0.16.1 and it seems be fixed. Mine was installed using npm :)

**Comment by mateoKaradza** [comment]
@mbeaudru I had the same issue, in case you installed Yarn via MSI, remove it and everything should work fine.

**Comment by kittens** [comment]
We'll be removing `self-update` in the future, please use the update mechanism provided by your installation method.
