### ISSUE TITLE
yarn add <npm-package> rewrites bower.json even though nothing was added.

### ISSUE THREAD

**Issue by kitsunde** [yarnpkg/yarn#1193]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If I have a `bower.json` that isn't ordered. Like:

```json
{
  "name": "patontheback",
  "dependencies": {
    "animate.css": "3.5.2",
    "Faker": "3.1.0"
  }
}
```

Then do:

```bash
yarn add node-sass
```

It will rewrite `bower.json` into being ordered:

```json
{
  "name": "patontheback",
  "dependencies": {
    "Faker": "3.1.0",
    "animate.css": "3.5.2"
  }
}
```

**What is the expected behavior?**

If it's not doing stuff to bower.json it should probably just leave it alone.

**Please mention your node.js, yarn and operating system version.**

```bash
$ yarn --version
0.15.1
$ node --version
v6.8.1
$ sw_vers -productVersion
10.12
```

**Comment by hawkrives** [comment]
> If I have a bower.json that isn't ordered.

If you have that file, what does Yarn do to it after you run `yarn add node-sass`?

**Comment by kitsunde** [comment]
Sorry hit enter too soon. I've edited it. `bower.json` gets resaved as an ordered file despite not having any changes.

```json
{
  "name": "patontheback",
  "dependencies": {
    "Faker": "3.1.0",
    "animate.css": "3.5.2"
  }
}
```

**Comment by hawkrives** [comment]
I assume that it does the same thing to a `package.json` file? Just trying to figure out if it's a `bower.json` specific thing or not.

**Comment by kitsunde** [comment]
@hawkrives Same thing happens with `package.json` yeah.

**Comment by kittens** [comment]
We've removed support for Bower, see #1441.
