### ISSUE TITLE
yarn.lock contains an extra new line at the end

### ISSUE THREAD

**Issue by lzilioli** [yarnpkg/yarn#1199]
After running `yarn install`, my yarn.lock file contains two new line characters at the end of the file. It only needs to contain one. In particular, my repo has a pre-push hook that checks for whitespace issues using `git diff --check origin/master..head` and fails if that command exits with a non-zero exit code. The extra new line generated in yarn.lock causes this check to fail.

**Comment by brokentone** [comment]
You likely should not be linting other people's config or generated files at all.

**Comment by lzilioli** [comment]
This is not "other people's files" it's the yarn.lock file I just added on the branch. 

Either way, even for autogenerated files I don't think it's unreasonable to expect them to pass a simple git white space check.
