### ISSUE TITLE
The homebrew packages is outdated.

### ISSUE THREAD

**Issue by chiedo** [yarnpkg/yarn#1201]
0.16.0 is not available on Homebrew.

The latest package available on Homebrew is 0.15.1

Can you please update?

**Comment by Daniel15** [comment]
I think this URL and sha256 need to be updated: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb#L6-L12

https://yarnpkg.com/downloads/0.16.0/yarn-v0.16.0.tar.gz is the right URL to use.

Unfortunately I'm not on a Mac so I can't test it :(

**Comment by chiedo** [comment]
Well today, I learned how Homebrew actually works @Daniel15  haha

Just submitted a PR here https://github.com/Homebrew/homebrew-core/pull/6060

**Comment by chiedo** [comment]
Not sure how long everything will take but if it's taking too long for them to merge it into Homebrew you can get 0.16.0 by doing the following.

**Run this:**

`brew edit yarn`

**Replace the content in that file with this:**

```
require "language/node"

class Yarn < Formula
  desc "Javascript package manager"
  homepage "https://yarnpkg.com/"
  url "https://yarnpkg.com/downloads/0.16.0/yarn-v0.16.0.tar.gz"
  sha256 "cd1d7eeb8eb2518441d99c914e5fd18b68e2759743d212dfd8f00574a1de6da8"
  head "https://github.com/yarnpkg/yarn.git"

  bottle do
    cellar :any_skip_relocation
    sha256 "04d5fe5e5667d77b40a882a1bdbe08625bd52e0d228af7aa925455760bafd58f" => :sierra
    sha256 "291ad03475ea4770f357559dc9116309796bf1af83c13644cafcd00163283bce" => :el_capitan
    sha256 "84a717ce964d4ec5cd69ae6336a79db27fa7580cee1c978e33e310e4eb8e36a3" => :yosemite
  end

  depends_on "node"

  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    (testpath/"package.json").write('{"name": "test"}')
    system bin/"yarn", "add", "jquery"
  end
end
```

**Run this**
`brew upgrade yarn`
