### ISSUE TITLE
Environment variables are not replaced in .npmrc files

### ISSUE THREAD

**Issue by carlansley** [yarnpkg/yarn#1206]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

An .npmrc file like this:

//registry.npmjs.org/:_authToken=${NPM_TOKEN}

Yarn does not replace ${NPM_TOKEN} with the value of environment variable NPM_TOKEN.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

Per https://docs.npmjs.com/files/npmrc, environment variable substitution is a feature expected to be used when parsing an .npmrc file by the client.

**Please mention your node.js, yarn and operating system version.**

yarn: 0.16.0
node: 6.9.0
os: Mac OS 10.12 (16A323)

**Comment by maybeec** [comment]
Just a question, as I am not totally sure and there is no documentation. Will .rpmrc registry config override yarn registry config in both cases?

1. yarn registry not set (defaults to https://registry.yarnpkg.com) and .npmrc registry set to a custom value
2. yarn registry set to custom value and .npmrc registry set to custom value

I would think of case 1 npm config overriding yarn default config and in case 2 yarn config overriding npm config, right?

**Comment by maybeec** [comment]
Just observed, after upgrading from yarn 0.15.x to 0.16.0 configured with case 2:
You will get an exception e.g. on `yarn add` which states, that the .npmrc URI of the registry could not be parsed. However, this would mean, that in case 2 above, the `.rpmrc` file takes precedence.

Here the stack trace:

```
Trace: 
  Error: $%7BSOME_ENV_VAR%7D/yarn: Invalid URI "$%7BSOME_ENV_VAR%7D/yarn"
      at Request.init (C:\Program Files (x86)\Yarn\node_modules\request\request.js:275:31)
      at new Request (C:\Program Files (x86)\Yarn\node_modules\request\request.js:129:8)
      at request (C:\Program Files (x86)\Yarn\node_modules\request\index.js:55:10)
      at RequestManager.execute (C:\Program Files (x86)\Yarn\lib\util\request-manager.js:327:17)
      at RequestManager.shiftQueue (C:\Program Files (x86)\Yarn\lib\util\request-manager.js:353:10)
      at Promise (C:\Program Files (x86)\Yarn\lib\util\request-manager.js:150:12)
      at RequestManager.request (C:\Program Files (x86)\Yarn\lib\util\request-manager.js:148:21)
      at NpmRegistry.request (C:\Program Files (x86)\Yarn\lib\registries\npm-registry.js:97:32)
      at C:\Program Files (x86)\Yarn\lib\resolvers\registries\npm-resolver.js:86:54
      at next (native)
```

**Comment by poida** [comment]
+1

This also fails for me using v0.16.1 when trying to install scoped packages from a private (sinopia) repo. The package is installed successfully by npm and by yarn if the actual token is in the `.npmrc` file. Otherwise I get:

```
$ cat ~/.npmrc 
@poida:registry=http://localhost:4873/
//localhost:4873/:_authToken=${NPM_AUTH_TOKEN}

$ echo $NPM_AUTH_TOKEN
there-is-a-real-token-here==

$ yarn add @poida/test
yarn add v0.16.1
[1/4] Resolving packages...
error An unexpected error occured

$ cat yarn-error.log
Error: http://localhost:4873/@poida%2ftest: unregistered users are not allowed to access package @poida/test
      at Request.params.callback [as _callback] (/home/poida/.nvm/v6.7.0/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
```

And from my sinopia logs:
> http  <-- 403, user: undefined, req: 'GET /@poida%2ftest', error: unregistered users are not allowed to access package @poida/test

**Comment by mrfelton** [comment]
I'm having the same problem - installation of provate scroped packages from registry.npmjs.org works if I have a plain text token included in .npmrc, but not with the `NPM_TOKEN` variable.

eg, the following .npmrc file works for both npm and yarn:


```
//registry.npmjs.org/:_authToken=my-actual-token
save-exact=true
```

Whilst the following only works for npm:

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
save-exact=true
```

**Comment by TeChn4K** [comment]
How did you manage this issue guys?

**Comment by blast-hardcheese** [comment]
I thought I had this issue, turns out it was because the interpolated variable wasn't `export`'ed in my `.bash_profile`. You can confirm [the logic](https://github.com/yarnpkg/yarn/blob/master/src/util/env-replace.js#L15) via

```shell
$ FOO=busted
$ export BAR=abc123
$ npx node
Welcome to Node.js ...
Type ".help" for more information.
> process.env['FOO']
undefined
> process.env['BAR']
'abc123'
```
