### ISSUE TITLE
Update chocolatey package

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#1216]
The [current choco](https://chocolatey.org/packages/yarn) package is 0.15.0.

Related to #1201.

**Comment by Daniel15** [comment]
Working on it, sorry for the delay. The package was submitted earlier today when we released 0.16.0, the Chocolatey team take a few days to review packages though (similar to turnaround on Homebrew packages)

![](http://ss.dan.cx/2016/10/chrome_18-21.19.54.png)

**Comment by Daniel15** [comment]
Package was approved :)
