### ISSUE TITLE
"yarn version" should have an option to not commit to Git

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1228]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`yarn version --new-version 1.2.3` always commits to Git. There's an ugly workaround: You can set the `YARN_VERSION_GIT_TAG` environment variable to an empty string:
```
YARN_VERSION_GIT_TAG='' yarn version --new-version 1.2.3
```

This is because [version.js](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/version.js#L110) uses `Boolean(config.getOption('version-git-tag'))`, and [base-registry.js](https://github.com/yarnpkg/yarn/blob/master/src/registries/base-registry.js#L92) populates overrides for these config options from the environment variables. Since it uses the `Boolean` function and all environment variables are strings, the only value that works to disable it is an empty string.

**What is the expected behavior?**
A `--no-commit` or `--no-git-tag-version` flag: Something like `yarn version --new-version 1.2.3 --no-commit` should update the version number without committing it. [npm calls this --no-git-tag-version](https://docs.npmjs.com/cli/version).

**Comment by karanjthakkar** [comment]
@Daniel15 I'll give this a shot today!

**Comment by kylecombes** [comment]
Does this still work the same way as it did after #1243 was merged? Using `--no-git-tag-version` doesn't seem to be working for me...
