### ISSUE TITLE
Syntax error in package.json yields unhelpful error message

### ISSUE THREAD

**Issue by mnpenner** [yarnpkg/yarn#1229]
**Do you want to request a *feature* or report a *bug*?**

Feature (enhancement)

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a syntax error in your package.json, such as leaving a trailing comma:

```
{
  "name": "yarntest",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "webpack": "^1.13.2"
  },
  "scripts": {
    "build": "webpack --progress"
  },
}
```

Run `yarn`.

**What is the current behavior?**

You get this error message:

> error An unexpected error occured, please open a bug report with the information provided in "C:\\Users\\Mark\\PhpstormProjects\\yarntest\\yarn-error.log".

If you open that log file and scroll all the way to the bottom you can see the real error. I don't think the yarn team wants me reporting every syntax error I make 😄 So instead, I'm reporting the error message about syntax error I made!

**What is the expected behavior?**

Improved error message. Something like:

> Syntax error in package.json: unexpected token } at <line>:<column>

Stack trace isn't necessary. Let's keep this brief for common mistakes!

**Please mention your node.js, yarn and operating system version.**

Node: v6.3.1
Yarn: 0.16.0
OS: Win10 Anniversary

**Comment by swapnilmishra** [comment]
I could see this behaviour(to show exact error) being there in v0.15.0 but has been modified to fix #1097 via https://github.com/yarnpkg/yarn/commit/8ebc3c2ea8aa26a41b6aaa0be9b0469eb3aaa04b in v0.16.0. In this commit only outputting the error stack trace to **yarn-error.log** was added, so it seems to be an intended behaviour.

**Comment by mnpenner** [comment]
@swapnilmishra 

>  In this commit only outputting the error stack trace to yarn-error.log was added, so it seems to be an intended behaviour.

Showing the stack only in yarn-error.log is good, but *not* showing any kind of human-readable error for trivial mistakes is bad.

That ticket talks about catching any errors that make it to the "top of the process" and dumping them to a file. I think that's great, but I think this particular error should be caught and *not* make it to the top of the process. It should be handled as a special case because I suspect it is a common scenario and not a bug in yarn as the message suggests.

**Comment by kittens** [comment]
Created #1424 to fix this, pending approval.
