### ISSUE TITLE
Yarn doesn't install all dependencies of a lib

### ISSUE THREAD

**Issue by salztorte** [yarnpkg/yarn#1236]
hey
i use react with the react-router but everytime i try to install the react-router with yarn the "history"-lib in the dependencies isn't in node_node_modules.

I checked out that history is in the dependencies of react-router.

Windos 8.1
node v5.5.0
yarn 0.16.0

**Comment by pheuter** [comment]
My issue had to do with running `$ yarn clean`, which generated a `.yarnclean` file and caused certain modules to be removed.

Once I removed that file yarn was able to install `history`.

**Comment by salztorte** [comment]
thanks that workaround works.

**Comment by marzepani** [comment]
You can add exclude rules to `.yarnclean`.
[Example Gist](https://gist.github.com/marzepani/4e4f3334960945722eca458fe112c21a)

**Comment by salztorte** [comment]
i tryed this but than yarn clean doesn't work anymore.

**Comment by marzepani** [comment]
A [pull request with a fix](https://github.com/yarnpkg/yarn/pull/1252) was accepted already.
(Sorry, I failed with my first attempt to fix it, but it will be repaired in the next release.)

**Comment by salztorte** [comment]
Ok. 
Thanks for the help.

**Comment by salztorte** [comment]
Fix: #1252
