### ISSUE TITLE
Option to choose to install bower, npm components, or both

### ISSUE THREAD

**Issue by vlamic** [yarnpkg/yarn#1247]
**Do you want to request a *feature* or report a *bug*?**
*Feature*

**What is the current behavior?**
Installs both bower and npm components (when the issue #616 is fixed)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would expect to have an option if I want to install both bower and npm, or only one of them

**Please mention your node.js, yarn and operating system version.**

**Comment by kittens** [comment]
We've removed support for Bower, see #1441.
