### ISSUE TITLE
Add "Package Type" to yarn outdated

### ISSUE THREAD

**Issue by wavded** [yarnpkg/yarn#1254]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the expected behavior?**

`yarn outdated` doesn't have a flag like `-l` in npm where you can see what `Package Type` a particular dependency comes from like:

<img width="622" alt="screen shot 2016-10-19 at 9 50 44 am" src="https://cloud.githubusercontent.com/assets/26638/19523893/8765d06a-95e1-11e6-9b7b-dd5b32360c3a.png">

I would recommend adding this and **not** putting it under a flag.  Personally, I always run npm outdated this way so I know which list to save to when updating a package.

**Please mention your node.js, yarn and operating system version.**

node 6.8.0, yarn 0.16.0, macOS 10.12

**Comment by thejameskyle** [comment]
Yeah, I would prefer this just always appear, I don't know why it's behind a flag in npm
