### ISSUE TITLE
Do not report **unexpected error** during fetch timeout

### ISSUE THREAD

**Issue by Jimexist** [yarnpkg/yarn#1255]
**Do you want to request a _feature_ or report a _bug_?**

_bug_

**What is the current behavior?**

During a fetch timeout, it printed `error An unexpected error occured, please open a bug report with the information provided in "/path/yarn-error.log".` instead of justing reporting fetch timeout.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just fetch with a slower network e.g.

**What is the expected behavior?**

The packager should print more explicit information for a fetch timeout, so the user can simply investigate and retry if applicable. The current instruction guides user to fire a bug report - in this case it was not a bug.

**Please mention your node.js, yarn and operating system version.**
- node v6.9.0
- yarn version v0.16.0
- OS 16.0.0 Darwin Kernel Version 16.0.0 root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

**Comment by thejameskyle** [comment]
Yup, we should improve the error here

**Comment by mpash** [comment]
I just got this on my first install with Yarn. I also thought it a bit erroneous to report a timeout.

**Comment by jouni-kantola** [comment]
We've got a private registry (with Artifactory) setup. I forgot to init the VPN client I use. This exact error message is displayed in this case as well. It didn't take long to figure out what was wrong, but still the error message could've been more helpful.

CLI log (yarn v0.16.0, Windows 10):
```
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occured, please open a bug report with the information provided in "yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by jshwei** [comment]
Also, it would be very helpful to use a dedicated error code so that the caller can retry on timeout

**Comment by merceyz** [comment]
Closing as Yarn has been reporting network specific error on timeouts for a while now
