### ISSUE TITLE
Add shorthand aliases to yarn add

### ISSUE THREAD

**Issue by mateeyow** [yarnpkg/yarn#1257]
**Do you want to request a _feature_ or report a _bug_?**

_feature_

**What is the expected behavior?**
Add shorthand for `--save --save-exact` and `--save-dev --save-exact` like `-SE` and `-DE`

**Please mention your node.js, yarn and operating system version.**

Yarn Version: `0.16.0`
OS: `Elementary OS`
Node Version: `v6.2.2`

**Comment by thejameskyle** [comment]
These flags don't exist, those are `npm install` flags, Yarn has:

```sh
yarn add [package]                 # equiv of --save
yarn add [package] --dev           # equiv of --save-dev
yarn add [package] --peer          # equiv of --save-peer
yarn add [package] --optional      # equiv of --save-optional
yarn add [package] --exact         # equiv of --save-exact
yarn add [package] --tilde
```

I could see allowing these flags:

```sh
yarn add [package] -D
yarn add [package] -P
yarn add [package] -O
yarn add [package] -E
yarn add [package] -T
```

And a new alias for add `a`

```sh
yarn a [package]
```

**Comment by olingern** [comment]
@thejameskyle Is it okay if I give this one a go?

**Comment by thejameskyle** [comment]
Of course, open a PR

**Comment by olingern** [comment]
@thejameskyle Awesome. A couple of questions.

1) Tests are pending, and I looked through existing tests, but didn't see a good way to test `yarn a [package name]` invokes `yarn add [package name]`. Really, I only should test that the shorthand command issued is being overwritten by its actual command. So, breaking [this conditional](https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L108) into its own function and validating its output should be the only thing necessary. I wanted to ask before refactoring, though.

2) Alias previously said, "did you mean yarn [command]?"
Was there a reason for this, or was it just to provide support who thought the aliases were already there?

**Comment by kittens** [comment]
I don't think we want an alias for `add`. It's literally 3 characters and ambiguity is already rife with random commands like `npm i -d <PACKGE>`.

**Comment by olingern** [comment]
@kittens Alright. Well, nevertheless, my tests pass locally and on circle ci, but fail on appveyor / travis-ci. No need to merge in, but if you have any insight into getting more detailed logs - that be really helpful.

https://circleci.com/gh/yarnpkg/yarn/1667?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://travis-ci.org/yarnpkg/yarn/jobs/170360170
https://ci.appveyor.com/project/kittens/yarn/build/1.0.367

**Comment by wyze** [comment]
Alias for the flags were added in #1618 and #1653. Will be available in the next release!
