### ISSUE TITLE
yarn fails to install public scoped packages

### ISSUE THREAD

**Issue by Offirmo** [yarnpkg/yarn#1260]
Related but not exactly the same as #825, and most likely related to #991, #1234

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Trying to install a free, scoped package
```
yarn add --dev @offirmo/cli-toolbox
yarn add v0.16.0
[1/4] Resolving packages...
error Couldn't find package "@offirmo/cli-toolbox" on the "npm" registry.
```
However, this fine module is public and available on npm https://www.npmjs.com/package/@offirmo/cli-toolbox

**What is the expected behavior?**
It should find the module in the npm registry and install it

**Please mention your node.js, yarn and operating system version.**
* node 6.9.0
* yarn 0.16.0
* Ubuntu 16.04 latest

**Comment by Offirmo** [comment]
Thanks for yarn, this tool is very promising !

**Comment by jsynowiec** [comment]
Are you using any registry proxy or something similar? I've just successfully installed this package.

```
$ yarn add --dev @offirmo/cli-toolbox
yarn add v0.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 233 new dependencies.
├─ @offirmo/cli-toolbox@0.0.4
├─ ansi-256-colors@1.1.0
(...)
```

**Comment by Offirmo** [comment]
@jsynowiec I'm indeed accessing npm through my company's npm proxy.

I'll disable it and recheck.

**Comment by Offirmo** [comment]
@jsynowiec confirmed: removing the npm proxy solves the error.

I'll report it to the proxy maker.

Sorry for the trouble.
