### ISSUE TITLE
Upgrading a devDependency dupes the new in "dependencies"

### ISSUE THREAD

**Issue by burabure** [yarnpkg/yarn#1262]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

when trying to upgrade a dependency listed on devDependencies yarn adds the new version as a duplicate in dependencies

example output after `yarn upgrade babel-eslint`

``` sh
"dependencies" has dependency "babel-eslint" with range "^7.0.0" that collides with a dependency in "devDependencies" of the same name with version "^6.1.0"
```

**If the current behavior is a bug, please provide the steps to reproduce.**

have some dep (i.e. 'foo') on devDependecies then:

``` sh
yarn upgrade foo
```

**What is the expected behavior?**

version range should be updated on the existing listed dep 

**Please mention your node.js, yarn and operating system version.**

``` sh
node -v && yarn --version && lsb_release -a
v5.3.0
0.16.0
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```

**Comment by thejameskyle** [comment]
Interestingly this doesn't even respect the `--dev` flag when you run it.

**Comment by wyze** [comment]
Same as #1458 and pending PR #1620 to fix this.
