### ISSUE TITLE
nested dependencies with relative paths fails

### ISSUE THREAD

**Issue by chandlerprall** [yarnpkg/yarn#1263]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn is unable to locate sub-dependency referenced via relative file paths

**If the current behavior is a bug, please provide the steps to reproduce.**
Created [a gist](https://gist.github.com/chandlerprall/5c5e83df5e1e2281289366c8b01ea21e) with three package.json files (underscores in file names represent path separators). The folder structure is:

`pkg-a/package.json`
`pkg-b/package.json`
`subdir/pkg-c/package.json`

Each package depends on the previous one (`a` has no dependency, `b` depends on `a`, and `c` depends on `b`)

`cd`ing into `pkg-b` and running `yarn` works as expected. However, `cd`ing into`subdir/pkg-c` and running `yarn` gives the following error:

`error "/Users/chandler.prall/yarntest/subdir/pkg-a" doesn't exist.` as it resolves `pkg-b`'s dependency `file:../pkg-a` relative to `subdir/pkg-c` instead of `pkg-b`

`npm install` handles this case correctly

**What is the expected behavior?**
Running `yarn` inside `subdir/pkg-c` should follow nested relative path dependencies correctly and resolve `file:pkg-a` from `pkg-b` path.

**Please mention your node.js, yarn and operating system version.**
node.js v6.7.0
yarn v0.16.1
OS X 10.9.4

**Comment by hawkrives** [comment]
Can you give an example of your `package.json`, please?

**Comment by chandlerprall** [comment]
the three `package.json` files are at https://gist.github.com/chandlerprall/5c5e83df5e1e2281289366c8b01ea21e

**Comment by turnbullm** [comment]
Looks like a duplicate of #815 ?

**Comment by chandlerprall** [comment]
I agree, issue 815 is the same problem.
