### ISSUE TITLE
Yarn install fails, private modules?

### ISSUE THREAD

**Issue by fyockm** [yarnpkg/yarn#1266]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Run `yarn` on existing project with private module dependencies.

**If the current behavior is a bug, please provide the steps to reproduce.**
Arguments: 
  /Users/drew/.nvm/versions/node/v6.6.0/bin/node /Users/drew/.nvm/versions/node/v6.6.0/bin/yarn

PATH: 
  /usr/local/heroku/bin:/Users/drew/.nvm/versions/node/v6.6.0/bin:/Users/drew/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Yarn version: 
  0.16.1

Node version: 
  6.6.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "voyant-assets",
    "description": "Asset manager",
    "version": "0.5.1",
    "author": "Bessemer Alliance",
    "dependencies": {
      "@voyant/auth": "^1.0.0",
      "@voyant/config": "^1.0.0",
      "@voyant/crypt": "^1.0.0",
      "@voyant/mailer": "^2.0.0",
      "@voyant/models": "^1.2.3",
      "@voyant/session": "^1.1.0",
      "async": "^2.0.0",
      "aws-sdk": "^2.2.15",
      "body-parser": "^1.14.2",
      "boom": "^3.0.0",
      "compression": "^1.6.0",
      "cors": "^2.7.1",
      "express": "^4.13.3",
      "knox": "^0.9.2",
      "lodash": "^4.13.1",
      "mime-types": "^2.1.7",
      "modify-filename": "^1.1.0",
      "moment": "^2.11.2",
      "mongoose": "4.5.5",
      "multer": "^1.1.0",
      "multer-s3": "sabymike/multer-s3",
      "passport": "^0.3.0",
      "request": "^2.67.0",
      "s3-streams": "BessemerAlliance/s3-streams",
      "speechmatics": "^1.0.0",
      "throng": "^4.0.0",
      "type-is": "^1.6.10",
      "validator": "^5.4.0",
      "winston": "^2.1.1"
    },
    "devDependencies": {
      "aws-sdk-mock": "^1.5.0",
      "buffertools": "^2.1.3",
      "eslint": "^2.9.0",
      "eslint-config-airbnb-base": "^3.0.1",
      "eslint-plugin-import": "^1.6.1",
      "hawk": "^4.0.1",
      "istanbul": "^0.4.0",
      "mime": "^1.3.4",
      "mocha": "^2.3.3",
      "nodemon": "^1.8.1",
      "randomstring": "^1.1.3",
      "should": "^10.0.0",
      "sinon": "^1.17.2",
      "supertest": "^1.1.0"
    },
    "engines": {
      "node": "6"
    },
    "homepage": "https://github.com/BessemerAlliance/voyant-assets#readme",
    "license": "ISC",
    "main": "index.js",
    "optionalDependencies": {
      "newrelic": "^1.23.1",
      "winston-loggly": "^1.2.0"
    },
    "private": true,
    "repository": {
      "type": "git",
      "url": "git+https://github.com/BessemerAlliance/voyant-assets.git"
    },
    "scripts": {
      "coverage": "istanbul check-coverage --statement 100 --branch 100 --function 100",
      "dev": "nodemon .",
      "lint": "eslint --fix --ignore-path .gitignore .",
      "spec": "NODE_ENV=test istanbul cover _mocha -- test/**/*Spec.js -t 30000",
      "start": "node .",
      "test": "npm run lint && npm run spec && npm run coverage"
    }
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  TypeError: Cannot use 'in' operator to search for '^1.1.0' in undefined
      at /Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:62:24
      at next (native)
      at step (/Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at Promise.F (/Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/core-js/library/modules/_export.js:35:28)
      at /Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at Function.findVersionInRegistryResponse (/Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:72:7)
      at /Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:89:34
      at next (native)
      at step (/Users/drew/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
 

**What is the expected behavior?**
`$ yarn` actually installs the dependencies 

**Please mention your node.js, yarn and operating system version.**
node: v6.6.0
yarn: v0.16.1
OSX: 10.11.6

**Comment by hawkrives** [comment]
Which dependencies are the private ones?

**Comment by hawkrives** [comment]
You'll be interested in following https://github.com/yarnpkg/yarn/issues/620 and https://github.com/yarnpkg/yarn/issues/698. I would say also https://github.com/yarnpkg/yarn/issues/825, but that seems to have been resolved with `yarn@0.16.0`, which you already have… so you might also look at https://github.com/yarnpkg/yarn/issues/1260 (although that's public scoped packages, not private ones.)

**Comment by wyze** [comment]
The error message looks to be when there is a malformed response from the registry. #1356 was opened to better handle that message. If it is an issue with the scoped/private packages you can follow the issues @hawkrives mentioned in the above comment.
