### ISSUE TITLE
Space character allowed in the project name in the "yarn init" wizard

### ISSUE THREAD

**Issue by baptistelebail** [yarnpkg/yarn#1268]
When doing a `yarn init`:
Putting a space in the project name when the wizard asks for it, like "My Project" works, but then Yarn issues an error when doing a `yarn add`:
"error My Project@0.1: Name contains illegal characters"

**Comment by torifat** [comment]
I'm working on it.

**Comment by olingern** [comment]
Oh, I just wrapped this up!

**Comment by torifat** [comment]
@olingern ok, no problem. But, please comment before start working. It will save someone else from doing the same thing.
