### ISSUE TITLE
yarn publish creates wrong tar content

### ISSUE THREAD

**Issue by danez** [yarnpkg/yarn#1269]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
Published tarball contains invalid data (namely the folders `dist`, `node_modules`, `package` and the file `.eslintignore`)
I unpublished already, but unpkg.com has already some stuff cached:
https://unpkg.com/react-tabs@0.8.1/ (Done with yarn)
https://registry.npmjs.org/react-tabs/-/react-tabs-0.8.1.tgz

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn version` and entered 0.8.1

`yarn publish` and did not enter a version but just pressed enter on the version prompt.

**What is the expected behavior?**
https://unpkg.com/react-tabs@0.8.2/ (Done with npm)
The tarball should be similar with both clients.
**Please mention your node.js, yarn and operating system version.**

node 6.9, yarn 0.16.0, macOS 10.12

The repository is https://github.com/reactjs/react-tabs

**Comment by adambiggs** [comment]
I published a scoped package with `$ yarn publish`, but when I try to install it I get:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@my-scope/my-pkg/-/my-pkg-1.0.0.tgz: invalid tar file"
```

**Comment by BYK** [comment]
Is this still happening?

**Comment by danez** [comment]
As I cannot reproduce this anymore I'm closing this.
