### ISSUE TITLE
Installation Problem: Running yarn install seems to compile native modules for wrong version of node

### ISSUE THREAD

**Issue by richtera** [yarnpkg/yarn#1271]
**Which operating system are you using:**
Mac OS X Sierra with nvm and node 6. And tested on cloud9 with the same problems.

``` sh
$ node -v
v6.7.0
$ npm -v
3.10.3
```

**Please describe the steps you took when trying to install Yarn and what went wrong:**
Using yarn install is really nice and fast, but running the installed packages causes node bindings version errors. I had to revert so I don't have the actual error ready, but it could be related with nvm where it might be looking for node in the path instead of asking nvm.

**Comment by thejameskyle** [comment]
You'll need to include information about the error in order for this to be actionable

**Comment by torifat** [comment]
Closing due to no response.
