### ISSUE TITLE
Forked packages use the same entry as upstream

### ISSUE THREAD

**Issue by panrafal** [yarnpkg/yarn#1278]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Packages that are resolved to different sources, use the same cache entry - source fetched first will be used for every package with the same name and version.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Run `yarn add babel-plugin-typecheck`
- It will be resolved to: `https://registry.yarnpkg.com/babel-plugin-typecheck/-/babel-plugin-typecheck-3.9.0.tgz#0edac7573ae24ee58c6f91319f574bc5124b0f0f`
- Run `yarn add panrafal/babel-plugin-typecheck#base-master` <- this is the forked repo with some changes, same version number
- _Bug#1_ - Yarn will essentially ignore me, keeping the original version in yarn.lock, but will update package.json - npm resolves the current SHA and updates both package.json and shwirnkwrap
- Run `yarn upgrade`
- Yarn will resolve the package to `https://codeload.github.com/panrafal/babel-plugin-typecheck/tar.gz/4fe4e904ae081a47e6221449c27183338999bac0`
- _Bug#2_ - The actual contents will be the same as the original babel-plugin-typecheck - npm fetches package from the repository

I guess this is because yarn caches packages by `<MANAGER>-<PACKAGE>-<VERSION>` instead of the resolved url

**What is the expected behavior?**
Same as NPM - install packages as resolved in yarn.lock

**Please mention your node.js, yarn and operating system version.**
Node 6.5, Yarn 0.16, OSX

**Comment by kittens** [comment]
Fixed via #1641.

**Comment by bestander** [comment]
Should be fixed now #2074
