### ISSUE TITLE
yarn upgrade not upgrading package based on git url

### ISSUE THREAD

**Issue by mgutz** [yarnpkg/yarn#1280]
I added a dependency `yarn add dalicious@mgutz/dalicious#matcherino`. That branch was subsequently updated on github. I ran `yarn upgrade dalicious@mgutz/dalicious#matcherino`. The package in node_modules did not upgrade; however, the lock file was updated and correctly references the updated commit. I download and expanded the resolved URL tarball to verify.

I completely removed the node_modules directory and ran `yarn install`. The older version was still in use.

Expected yarn to upgrade the package.

yarn v0.16.1 on Ubuntu 16.04

**Comment by panrafal** [comment]
This is a similar issue to #1278 
Try removing `~/.yarn-cache` and run `yarn` afterwards - it should be updated

**Comment by bestander** [comment]
Should be fixed now #2074
