### ISSUE TITLE
Self-update reports latest version but it's not

### ISSUE THREAD

**Issue by torifat** [yarnpkg/yarn#1283]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn self-update` v0.16.0 reports `Yarn is already using the latest version.`

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install yarn v0.16.0
- `yarn self-update`

**What is the expected behavior?**
It should self update.

**Please mention your node.js, yarn and operating system version.**
- node v6.9.1
- yarn v0.16.0
- macOS v10.12

**Comment by torifat** [comment]
I have found the reason. https://yarnpkg.com/latest-version still returns `0.16.0`

**Comment by adambuczynski** [comment]
I still bumped into this today.

```
> yarn self-update
> yarn self-update v0.16.1
> success Yarn is already using the latest version.
> ✨  Done in 0.66s.
> npm install -g yarn
> ...
> yarn@0.17.2 
```

**Comment by torifat** [comment]
@adambuczynski it's because `yarnpkg/website` repo isn't updated yet. https://yarnpkg.com/latest-version

cc @Daniel15

**Comment by Daniel15** [comment]
This is intentional, we're holding off on 0.17.x until a few more changes land (see #1859)

**Comment by adambuczynski** [comment]
Yes I got that from the contents of this issue, but as it was resolved as fixed 22 days ago, I assumed it wouldn't be happening anymore.

@Daniel15 ah ok, that makes sense then. But when I installed yarn on a new device, it did install 0.17.0 (which was rather buggy). So maybe those versions shouldn't be pushed to npm at all if they are not ready to be released publicly.

**Comment by torifat** [comment]
Yes, we had to revert it. https://github.com/yarnpkg/website/pull/264
