### ISSUE TITLE
Fetching packages hung forever.

### ISSUE THREAD

**Issue by huangyingjie** [yarnpkg/yarn#1289]
**Do you want to request a _feature_ or report a _bug_?**
Report a _bug_

**What is the current behavior?**
Fetching packages hung forever, waiting 30min+

``` js
$ yarn install
yarn install v0.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning mapbox-gl-shaders > brfs > static-module > through2 > xtend > object-keys@0.4.0:
[2/4] 🚚  Fetching packages...
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 976/977
```

**If the current behavior is a bug, please provide the steps to reproduce.**
$ git clone https://github.com/mapbox/mapbox-gl-js.git && cd mapbox-gl-js
$ yarn install
**What is the expected behavior?**
Install success, or show the detailed blocking info, like `npm install --verbose`.
**Please mention your node.js, yarn and operating system version.**
node v4.4.1
Mac OSX EI 10.11.6

**Comment by rask** [comment]
Same issue here. A WordPress theme with various Gulp packages refuses to fetch the last package for some reason. Yarn version 0.16.0, Node version 6+, npm version 3+. Running on Ubuntu 14.04.

**Comment by TekSiDoT** [comment]
I can confirm this behavior with the following setup:
node v6.9.1
Windows 10 1607 (build 14393.0)

hangs on:
```warning electron-prebuilt > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0```

Might thus be related to object-keys@0.4.0

**Comment by petermikitsh** [comment]
Also experiencing this :(

**Comment by petermikitsh** [comment]
The issue for me was resolved by switching to npm semantic versioned releases in `package.json`  instead of using `git+https` urls and `https://github.com/user/repo#tag`.

**Comment by strife25** [comment]
I encountered a similar issue w/ yarn hanging. Could this issue be related to SSH key passwords? https://github.com/yarnpkg/yarn/issues/2702

**Comment by kirs** [comment]
I fixed the issue in #2950. There's been a missing timeout (literally one line fix).

**Comment by TimvdLippe** [comment]
#2950 has been merged, but did not reference this issue properly. It can now be closed.

**Comment by dpurrington** [comment]
This is still happening in version v0.23.2
