### ISSUE TITLE
yarn install fails  ubuntu 14.04

### ISSUE THREAD

**Issue by vTNT** [yarnpkg/yarn#1290]
my system version: ubuntu 14.04 
nodejs version: v0.10.37

if i run:  apt-get install yarn:
The following packages will be REMOVED:
  nodejs
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 1 to remove and 21 not upgraded

so  how to solve it

**Comment by Baira** [comment]
why did you close this ? I'm getting the same problem !

**Comment by joscha** [comment]
Same problem here. Our build machines still run trusty - currently we install via `npm install -g yarn` but that is now deprecated. Upgrading the build machines for this is not an option - @vTNT did you solve this or just upgraded your ubuntu?

**Comment by SonnyRajagopalan** [comment]
I cannot install yarn on my 14.04 x86_64 system either. Fails for 

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package yarn

After following the install instructions.

**Comment by jyotirmaybanerjee** [comment]
+1

**Comment by lvtu0316** [comment]
I'm getting the same problem !

**Comment by robrecord** [comment]
Please reopen this. Happening for me too.

**Comment by tmsajin** [comment]
me too

**Comment by MBcdailey** [comment]
Same here:
apt-get update
apt-get install npm
apt-get install nodejs
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
apt-key adv --keyserver keys.gnupg.net --recv-keys A4EBAC6667697DD2 \
apt-get update
apt-get install yarn
=====================
The following packages will be REMOVED:
nodejs
The following NEW packages will be installed:
yarn

**Comment by Mukarram09** [comment]
i'm getting the same problem !

**Comment by xiaohe920** [comment]
@

> Same here:
> apt-get update
> apt-get install npm
> apt-get install nodejs
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
> echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list 
> apt-key adv --keyserver keys.gnupg.net --recv-keys A4EBAC6667697DD2 
> apt-get update
> apt-get install yarn
> ...
> The following packages will be REMOVED:
> nodejs
> The following NEW packages will be installed:
> yarn

so good
