### ISSUE TITLE
Documentation: For which programming languages is yarn?

### ISSUE THREAD

**Issue by hediet** [yarnpkg/yarn#1291]
The documentation at [https://yarnpkg.com/en/docs/getting-started](https://yarnpkg.com/en/docs/getting-started) reads:

> Yarn is a package manager for your code. It allows you to use and share code with other developers from around the world. Yarn does this quickly, securely, and reliably so you don’t ever have to worry.
> 
> Yarn allows you to use other developers’ solutions to different problems, making it easier for you to develop your software. If you have problems, you can report issues or contribute back, and when the problem is fixed, you can use Yarn to keep it all up to date.
> 
> Code is shared through something called a package (sometimes referred to as a module). A package contains all the code being shared as well as a package.json file which describes the package.

But I didn't find _any_ single hint in the whole documentation which programming languages are supported by yarn - this is very, very sad, especially for an project of this size. Am I right that yarn only supports js and uses the existing npm package infrastructure?
(Ok, I just found the blog now that finally clarifies that it is an javascript package manager - but such crucial information should not be hidden solely in a blog!)

For non-js people who stumbled upon this repository on github and read all the advantages of this package manager, such missing details are a complete waste of their time.
Such things make me raging - it's like advertising an awesome product but not mentioning that it only runs on e.g. FreeNOS (never heard of this OS? Me too!). Or like selling tickets to a indoor swimming pool without mentioning that there is no water at all.

Please fix that!

**Comment by simonbuchan** [comment]
As a replacement for npm, yarn is very focused on javascript, but it also inherits people's (ab)use of the npm repository for non-javascript content, [though it's mostly used for HTML and CSS](https://github.com/thomaspark/bootswatch) and [node bindings to C++](https://github.com/kapouer/node-webkitgtk)

In theory you could use it for anything you don't mind being put into a `node_modules' directory.

**Comment by gsklee** [comment]
@bestander close

I'd say Yarn is an _"npm-package"_ manager; it manages whatever the `npm` registry would accept as valid packages.

**Comment by hediet** [comment]
The front page still does not say that. And just saying 'Yarn is an "npm-package"' is not really helpful if you didn't use npm before.

**Comment by gsklee** [comment]
@hediet That probably means most people are adequately okay with the current wording. In that case I'd suggest you submit a PR directly to further specify the wordings you're looking to change in order to facilitate further improvement.

**Comment by bestander** [comment]
npm registry is more than just JavaScript and Yarn works primarily with npm but it also can work with Github hosted packages.
I think the current broad definition is not confusing but rather removing the limits for what it can be used.

**Comment by hediet** [comment]
So yarn is intended to be an php package manager?

**Comment by bestander** [comment]
Any reasons for not to be?

**Comment by hediet** [comment]
Yeah, php's namespace structure is completely incompatible with how yarn manages dependencies. In php, you need a proper constraint solver, since packages can be installed at most once (even if they have different versions).
I am sure that other languages have similar restrictions.

**Comment by wolf99** [comment]
So this is still a problem 3 years later. Just stumbled on the Yarn website and spent a while looking through the pages to see what languages it supports or what language even is expected and used for the code snippets (e.g. when mentioning `require`... require what, who, when, from where? 🙄 )

While I can now see from the above discussion that, theoretically, it can be used for other languages, the fact that it is not mentioned up front that a user would at least have to know JS to be able to make use it for those other languages, is pretty boneheaded.

**Comment by bitdancer** [comment]
Count me as another interested party sad to discover that yarn was focused on javascript but that fact wasn't mentioned in any of the docs I spent a half hour perusing.  It doesn't really matter that it can *theoretically* be used for other languages if in practice no one is doing that.  And if the core is indeed npm, then it should say that fairly prominently too, because *that* might actually be useful to me at some point :)

**Comment by DudeWithAHat** [comment]
Not only do I have to agree with the comments above, but I was almost misled by the documentation to believing that Yarn supported other languages.

It states in the README on github that Yarn was 'inspired by Bundler, Cargo, and npm' - while NPM appears to be JS-oriented, Cargo is a Rust package manager, and Bundler appears to be related to Ruby. This led me to believe that Yarn was attempting to fulfill the roles of Cargo and Bundler, when it appears to only be a replacement for NPM upon further inspection.

Additional information would be appreciated.
