### ISSUE TITLE
Yarn fails to install stormpath

### ISSUE THREAD

**Issue by Rhernandez513** [yarnpkg/yarn#1295]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After `[3/4] Linking dependencies`

`error an unexpected error occured`

error log provided at the bottom of this post

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn add stormpath`

**What is the expected behavior?**

Normal installation into node_modules and package.json

**Please mention your node.js, yarn and operating system version.**

node v6.7.0

yarn v0.16.0

ubuntu 16.04 xenial, linux x86_64 4.4.0-43-generic

[yarn-error.txt](https://github.com/yarnpkg/yarn/files/541350/yarn-error.txt)

**Comment by torifat** [comment]
It worked for me. The log shows you have permission problem in your `/home/robert/Software/NGHT/RNNghtApp/node_modules/react-native-maps/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/9.4.0/AndroidManifest.xml`

Can you fix your file permission? Or, alternatively you can just remove your `node_modules` folder and try again.

**Comment by Rhernandez513** [comment]
@torifat thank you I appreciate it.  I should have tried that first, it worked fine.
