### ISSUE TITLE
yarn run doesn't work, but npm run

### ISSUE THREAD

**Issue by Tiendq** [yarnpkg/yarn#1298]
- Run successfully from Terminal: `webpack --progress --colors --watch`
- Run successfully with `npm run start`
- Got "command not found" with `yarn run start`

Webpack is installed globally.

My package.json like this:

`"scripts": {
    "dist": "webpack -p",
    "lint": "eslint *.js",
    "start": "webpack --progress --colors --watch"
  }`

I think it's a bug.

yarn v0.15.1, node 6.5.0, OSX 10.11.6

**Comment by victornoel** [comment]
@Tiendq which error is returned when calling `yarn run start`?

**Comment by Tiendq** [comment]
@victornoel Here you are

`YOSEMITE:react-todo-list tiendq$ yarn run start
yarn run v0.15.1
$ "webpack --progress --colors --watch" 
sh: webpack --progress --colors --watch: command not found
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by victornoel** [comment]
Thanks, I have the same problem then :)

it seems like the whole `webpack --progress --colors --watch` is considered as one binary to be called by sh and not webpack followed by parameters!

**Comment by michaelsanford** [comment]
@victornoel  Agreed. That's odd, though, because _execute-lifecycle-script_ is adding the `-c` flag to the command from the `package.json`:
https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js#L130

That flag shoud cause the shell to [should correctly parse arguments found within the original command string](http://unix.stackexchange.com/questions/144514/add-arguments-to-bash-c), e.g.,:
```
$ sh "ls -a"
sh: ls -a: No such file or directory
```
_vs_
```
$ sh -c "ls -a"
.  ..  .idea gulpfile.js  node_modules  package.json  src  systemjs.config.js  tsconfig.json  tslint.json  yarn.lock
```

@Tiendq @victornoel Out of curiosity, what happens if you just `yarn start` (omitting `run`)?

**Comment by Tiendq** [comment]
@michaelsanford The same error.

**Comment by calvinl** [comment]
This is a duplicate of #733, and should be fixed via #809, which is included in `0.16.0`.

**Comment by Tiendq** [comment]
I just updated yarn 0.16.1, and `yarn run` works well now. Thank you.

**Comment by bradleyfindeis** [comment]
Just happened to me but I realized that I hadn't run 'yarn' after I added some new files from a co-worker. After I ran 'yarn', 'yarn start' fired right up!

**Comment by bilalmajeed64** [comment]
I'm on 'yarn run v1.12.3' this version, help me to fix this issue
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by carlkentor** [comment]
Same issue in **1.22.4.** Can execute it via npm but unable to do so with yarn.   
`yarn run v1.22.4
$ webpack --config webpack.config.dev.js --color --verbose --progress --watch
/usr/bin/bash: /d: No such file or directory
Visit [1mhttps://yarnpkg.com/en/docs/cli/run[22m for documentation about this command.`

Webpack isnt installed globally however, tried to target the binary located in node_modules/.bin/webpack directly, but without any success.
