### ISSUE TITLE
Add: strg +c and other termination codes support

### ISSUE THREAD

**Issue by frank-dspeed** [yarnpkg/yarn#1300]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
should exit with code :dagger: 
**Please mention your node.js, yarn and operating system version.**
all newst

**Comment by frank-dspeed** [comment]
sorry was npm that made the problem not yarn :dancer:

**Comment by Daniel15** [comment]
Hey @frank-dspeed - There's not enough information in this task in order for us to understand the problem you're encountering :) I'm going to close the task, but please feel free to reopen it and add more details if you're still having issues. Thanks for trying Yarn! 😄
