### ISSUE TITLE
Proposal: package suites

### ISSUE THREAD

**Issue by inikulin** [yarnpkg/yarn#1301]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
I find myself installing the same set of packages other and other again. E.g. if I need babel I do:

``` sh
yarn add babel babel-preset-es2015 babel-plugin-transform-runtime babel-preset-stage-2
```

if I do testing I need to install:

``` sh
yarn add mocha chai
```

and so on..
**What is the expected behavior?**
It would be nice if I'll be able to create lists of packages and install them all via one command, e.g.

``` sh
yarn suite create "babel" babel babel-preset-es2015 babel-plugin-transform-runtime babel-preset-stage-2
```

Then it can be used like this:

``` sh
yarn suite add babel
```

**Comment by gsklee** [comment]
@bestander close

The scale of this feature request means that it needs to go through the [proper RFC process](https://github.com/yarnpkg/rfcs).

**Comment by bestander** [comment]
From first sight, this looks like an unnecessary complication but feel free to send RFC to discuss use cases
