### ISSUE TITLE
[breaking change] [0.16.0] --force-single-instance 

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#1303]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**
```
node ~/Downloads/yarn-0.16.1.js install --force-single-instance
error: unknown option `--force-single-instance'
```

**What is the expected behavior?**

-  `unknown option`s should be allowed to make yarn forwards compatible (add test)
- where did `force-single-instance` go?

**Please mention your node.js, yarn and operating system version.**
node 6
yarn 0.16.1

**Comment by hawkrives** [comment]
Relevant: https://github.com/yarnpkg/yarn/pull/496 and https://github.com/yarnpkg/yarn/pull/777.

**Comment by kittens** [comment]
> where did force-single-instance go?

```
$ yarn --mutex file
$ yarn --mutex network
$ yarn --mutex file:specifiy-custom-file
$ yarn --mutex network:custom-port
```

> unknown options should be allowed to make yarn forwards compatible (add test)

We've already had a lot of issues about our old behaviour of ignoring unknown flags. No other CLI tools really work like this.
