### ISSUE TITLE
Yarn installs bad package version if dash in version number

### ISSUE THREAD

**Issue by Kirill89** [yarnpkg/yarn#1304]
If package.json looks like this:

```
"dependencies": {
    "bootstrap-multiselect": "^0.9.13-1"
  }
```

yarn installs bootstrap-multiselect of version `0.9.13` instead of `0.9.13-1`.

But if i try to remove `^` from version, yarn works fine.

With npm 3.10.8 both cases works fine.
On mac os x 10.11.6, node v6.8.0.

**Comment by jiripospisil** [comment]
The difference in behavior is probably something to look into but keep in mind that `0.9.13` satisfies `^0.9.13-1` as well so it's not that yarn installs an incorrect package but rather different.

**Comment by jsynowiec** [comment]
Pre-release versions have a lower precedence than the associated normal version [[1][semver-9]]. Considering semver spec, I would say that Yarn is right and NPM wrong(?) if it installs the pre-release version.

[semver-9]: http://semver.org/#spec-item-9

**Comment by puzrin** [comment]
We don't mean yarn/npm are good or bad. We just try to replace npm with yarn and report problems been found.

PS. Also package author was asked to use pure semver without dashes in patch numbers.

**Comment by jsynowiec** [comment]
I think it's related to https://github.com/npm/npm/issues/13248 and tagging pre-release versions as latest in the registry when publishing. NPM is installing the [latest version](https://github.com/npm/npm/blob/8fa75cd0313e3cea8459f89b79208461e54b033b/doc/cli/npm-install.md#description) specified in the registry and not the *latest* semver (stable) version. If you run `npm outdated` then it's properly reported as outdated:

```
$ npm outdated                                                                                                                                                         
Package                 Current  Wanted    Latest  Location                                                                                                            
bootstrap-multiselect  0.9.13-1  0.9.13  0.9.13-1  semver-test  
```

and when you `npm upgrade` the package, it gets upgraded to `0.9.13`

```
$ npm upgrade                                                                                                                                                          
semver-test@0.0.0 /Users/jakub/Projekty/tests                                                                                                                          
└── bootstrap-multiselect@0.9.13  
```

**Comment by gsklee** [comment]
@Kirill89 This is exactly how [node-semver](https://github.com/npm/node-semver) works. If you believe that it should work in another way, you should raise this issue there.
