### ISSUE TITLE
The package protocol is dropped from package.json

### ISSUE THREAD

**Issue by FredyC** [yarnpkg/yarn#1312]
**Do you want to request a _feature_ or report a _bug_?**
Reporting a bug

**What is the current behavior?**

> Couldn't find any versions for stampit that matches github.com/stampit-org/stampit.git. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn init
yarn add git+ssh://git@github.com/stampit-org/stampit.git
yarn ls
```

**What is the expected behavior?**
To display list of installed packages.

**Please mention your node.js, yarn and operating system version.**
Node v6.7.0, yarn 0.16.1, Windows 10 x64

**Additional information**
Since `yarn.lock` contains records together with a protocol, this should be either stripped from there or kept in package.json. Otherwise it's probably not possible to find a match.

I've already mentioned it [in this comment](https://github.com/yarnpkg/yarn/issues/513#issuecomment-255094324), but feels like a different issue.

**Comment by vinnymac** [comment]
Although it definitely does drop the protocol when using links like `git+ssh://git@github.com/org/repo.git`, if you need to get past this you can simply replace the link added to the package.json with the one you initially tried to add via `yarn add`. After this I can successfully run `yarn` without it complaining.

**Comment by FredyC** [comment]
@vinnymac Yea I guess that might work, but I doubt it's intended behavior :)

**Comment by wyze** [comment]
I've checked on `master` and this seems to be working now. Are you still able to reproduce this @FredyC?

**Comment by FredyC** [comment]
@wyze I would love to check that. Is there some other supporter way of installing master? I did try `npm i -g yarnpkg/yarn`, but that is failing. Do I have to clone whole repo and build by myself?

**Comment by wyze** [comment]
That is how I currently test, yes.

**Comment by FredyC** [comment]
Alright, I went ahead I did it like that and it is indeed working. Looking forward for a new release :) Could be happening more often franky. I am too excited to use Yarn properly at last :)

```bash
D:\workspace\test>yarn\bin\yarn.cmd add git+ssh://git@github.com/stampit-org/stampit.git
yarn add v0.16.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ stampit@3.0.6
Done in 14.71s.

D:\workspace\test>yarn\bin\yarn.cmd ls
yarn ls v0.16.2
└─ stampit@3.0.6
Done in 8.91s.
```

Thanks!
