### ISSUE TITLE
yarn pack puts everything in tgz

### ISSUE THREAD

**Issue by ptrstpp950** [yarnpkg/yarn#1314]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
After running yarn pack tgz file contains everything, including source, images, etc. Even files marked as gitignore.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run yarn pack

**What is the expected behavior?**
According to  documentation it should create file only with dependencies https://yarnpkg.com/en/docs/cli/pack

**Please mention your node.js, yarn and operating system version.**
yarn 16.1 
node 6.5.0
windows 10

**Comment by DenisGorbachev** [comment]
Related to #2047 ?

**Comment by SimenB** [comment]
It now just includes stuff forcefully included (https://github.com/yarnpkg/yarn/blob/1e7249966890c22df0c1564660a21a54ce17370b/src/cli/commands/pack.js#L44-L47) not everything else. So not really a dupe @torifat (although this issue can be closed, as it's not the case anymore)

**Comment by SimenB** [comment]
Although my issue is just with `node_modules`, while this seems to be with everything.

I can't reproduce it though, so do what seems best!
