### ISSUE TITLE
yarn restore only npm dependencies when package.json is side by side with bower.json

### ISSUE THREAD

**Issue by ptrstpp950** [yarnpkg/yarn#1315]
**Do you want to request a *feature* or report a *bug*?**
A bug.
**What is the current behavior?**
when I run yarn install only dependencies form package.json are restored. Bower.json dependencies are ignored. When I manually delete package.json, yarn discovers bower.json
**If the current behavior is a bug, please provide the steps to reproduce.**
Create simple repo with package.json and bower,json. You can clone my https://github.com/ptrstpp950/http2AndWebPerf
**What is the expected behavior?**
Restore npm dependencies and bower dependencies.
**Please mention your node.js, yarn and operating system version.**
yarn 16.1
node 6.5.0
windows 10

**Comment by nsams** [comment]
see #616 and #1247

**Comment by kittens** [comment]
Bower is no more, see #1441.
