### ISSUE TITLE
possibility to specify cache-folder in yarnrc

### ISSUE THREAD

**Issue by ptrstpp950** [yarnpkg/yarn#1316]
**Do you want to request a _feature_ or report a _bug_?**
A feature
**What is the current behavior?**
I don't know how to specify cache-folder in yarnrc. It is possible form CLI using --cache-folder option
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
An option in config
**Please mention your node.js, yarn and operating system version.**
yarn 16.1
node 6.5.0
windows 10

**Comment by mmerickel** [comment]
I think this is a duplicate of #1211.

**Comment by victornoel** [comment]
Would be a great feature!

**Comment by valscion** [comment]
I suppose that yarn 0.18.0 released with PR #2046 makes this issue fixed, and this could be closed?

**Comment by wyze** [comment]
Yup, thanks @valscion.
