### ISSUE TITLE
Slashes in .npmrc

### ISSUE THREAD

**Issue by fb55** [yarnpkg/yarn#1317]
When setting options for private registries, slashes at the end of the name are taken into consideration (which breaks compatibility with npm). This does not work:

```
@test:registry=https://npm.example.com
//npm.example.com/:always-auth=true
                 ^ (the offending slash)
```

while this does:

```
@test:registry=https://npm.example.com
//npm.example.com:always-auth=true
```

cc @devongovett I guess :)

**Comment by paul-soporan** [comment]
Closing as in v2 we completely stopped reading `.npmrc` files.

https://yarnpkg.com/getting-started/migration
