### ISSUE TITLE
[Question] How to generate a lockfile with only production deps

### ISSUE THREAD

**Issue by luanmuniz** [yarnpkg/yarn#1320]
**Do you want to request a *feature* or report a *bug*?**
Make a question

**What is the current behavior?**
If i run `yarn` it will generate the lockfile but it will include the devDeps in the list

**What is the expected behavior?**
I want to generate a lockfile without the devDeps

**Please mention your node.js, yarn and operating system version.**
Node v6.9.0
Yarn version v0.16.0

**Comment by thejameskyle** [comment]
Why would you not want to have devDeps in your lockfile?

**Comment by luanmuniz** [comment]
For production environments. I don't need `mocha` or `hot-reload` on production for example.

**Comment by thejameskyle** [comment]
Then just run [`yarn install --production`](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production).

**Comment by luanmuniz** [comment]
Understood. I tested and the speed really worked.
I didn't know that it would still use the lockfile.

How does that work? You look on the `package.json` for the production modules and get the structure and versions from the lockfile?

**Comment by thejameskyle** [comment]
The tree _should_ be identical except for the devDeps being removed

When dep-1 and dev-dep-2 depend on different versions of transitive-dep:

```diff
+ - dep-1@1.0.0
+   - transitive-dep@1.0.0
- - dev-dep-2@1.0.0
-   - transitive-dep@2.0.0
```

When both dep-1 and dev-dep-2 depend on a compatible version of transitive-dep:

```diff
+ - dep-1@1.0.0
+ - transitive-dep@1.0.0
- - dev-dep-2@1.0.0
```
