### ISSUE TITLE
Is Yarn slower on Windows?

### ISSUE THREAD

**Issue by rui-infotrack** [yarnpkg/yarn#1341]
Same project, same checkout point, ran `rm -rf node_modules`, `yarn install` on both Macbook and Windows laptop.

For Mac: it took only 19s
For Windows: it took 39s. Also, I had to turn off the crappy 'windows defender', otherwise it's even way slower.

My windows laptop actually has faster CPU than Macbook. So I'm wondering: is it expected behavior that yarn currently runs faster on Mac than on windows?

**Comment by samccone** [comment]
dup #990
