### ISSUE TITLE
yarn add error

### ISSUE THREAD

**Issue by griffinmichl** [yarnpkg/yarn#1348]
```
Trace: 
  TypeError: Cannot use 'in' operator to search for 'latest' in undefined
      at /Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:62:24
      at next (native)
      at step (/Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at Promise.F (/Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/core-js/library/modules/_export.js:35:28)
      at /Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at Function.findVersionInRegistryResponse (/Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:72:7)
      at /Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:89:34
      at next (native)
      at step (/Users/griffin.michl/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

Cannot install any new packages via `yarn add`. Always throws this error. No issues install existing dependencies.

**Comment by kwelch** [comment]
Based on [this tweet](https://twitter.com/thejameskyle/status/789566636130906112) connection to registry should be restored.

**Comment by thejameskyle** [comment]
registry.yarnpkg.com is now bypassing DNS to registry.npmjs.org so this should no longer be a problem

**Comment by kwelch** [comment]
There was also a good workaround posted in [another related issue](https://github.com/yarnpkg/yarn/issues/1354#issuecomment-255457481)

@tuures:
> `# .npmrc
registry = https://registry.npmjs.org/`

**Comment by rivertam** [comment]
@thejameskyle what happens if both are down?

**Comment by thejameskyle** [comment]
@rivertam not sure what you mean

**Comment by rivertam** [comment]
@thejameskyle I'm not sure what "bypassing DNS to registry.npmjs.org" means (I assume you mean the IP is hard-coded or something), but what happens if the entire system (npm, yarn, the whole shebang) is down?

**Comment by thejameskyle** [comment]
> I'm not sure what "bypassing DNS to registry.npmjs.org" means (I assume you mean the IP is hard-coded or something)

Yeah we moved from a CNAME to registry.npmjs.org to an A record with a hardcoded IP for now on registry.yarnpkg.com. It'll be slower for non-us users but we can switch back once Dyn has resolved their issues

> but what happens if the entire system (npm, yarn, the whole shebang) is down?

Well if everything goes down there's not much we can do.

You can hopefully just use what you have in your cache or setup an offline mirror using the `yarn-offline-mirror` field. @bestander is working on a blog post for this.

**Comment by rivertam** [comment]
Yeah what I mean is -- will this still result in a cryptic error or will it give a more meaningful error message? I don't mean to sound entitled as I'm clearly not contributing code yet, but this felt bad to see as an error when really it should have been something like "Can't connect to yarn/npm". That's all I'm saying. =)

**Comment by thejameskyle** [comment]
Please do contribute back improvements to error messages, that is very useful

**Comment by dobesv** [comment]
npmjs is down, too.
