### ISSUE TITLE
Yarn Install Error, tunneling socket could not be established

### ISSUE THREAD

**Issue by BagelTheKid** [yarnpkg/yarn#1351]
I'm running into the following error when running yarn install

> 
> Trace: 
>   Error: https://registry.yarnpkg.com/moment-timezone/-/moment-timezone-0.5.6.tgz: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
>   
>       at ClientRequest.onError (C:\Program Files (x86)\Yarn\node_modules\tunnel-agent\index.js:176:17)
>       at ClientRequest.g (events.js:291:16)
>       at emitOne (events.js:96:13)
>       at ClientRequest.emit (events.js:188:7)
>       at TLSSocket.socketErrorListener (_http_client.js:310:9)
>       at emitOne (events.js:96:13)
>       at TLSSocket.emit (events.js:188:7)
>       at onwriteError (_stream_writable.js:345:10)
>       at onwrite (_stream_writable.js:363:5)
>       at WritableState.onwrite (_stream_writable.js:89:5)

Any ideas as to what is causing this?

**Comment by thejameskyle** [comment]
This was almost certainly related to a DDoS event for npm's DNS provider Dyn.

registry.yarnpkg.com is now bypassing DNS to registry.npmjs.org so this should no longer be a problem
