### ISSUE TITLE
yarn docs

### ISSUE THREAD

**Issue by slavaGanzin** [yarnpkg/yarn#1353]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
```error Command "docs" not found.```

**What is the expected behavior?**
Same as npm: open package documentation page

**Please mention your node.js, yarn and operating system version.**
```
yarn --version                                                            (develop|✔)
0.15.1

node --version                                                               (develop|✔)
v6.9.0

 uname -a                                                                     (develop|✔)
Linux z 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux
```

**Comment by wyze** [comment]
I think this goes along with #778 and #897. Where they won't be adding commands like this. See the reasoning in this comment: https://github.com/yarnpkg/yarn/issues/897#issuecomment-253996508

**Comment by slavaGanzin** [comment]
@kittens knows what "would be better for everyone". and I know what I want - forget about this dictator's project.
