### ISSUE TITLE
How to create a private registry?

### ISSUE THREAD

**Issue by ccorcos** [yarnpkg/yarn#1355]
I see that Yarn works with private npm registries -- does this just mean private npm packages? or is there an open source npm registry I can host myself on a close network?

**Comment by Daniel15** [comment]
>  is there an open source npm registry I can host myself on a close network?

[Sinopia](https://github.com/rlidwka/sinopia) or its more well-maintained fork [Verdaccio](https://github.com/verdaccio/verdaccio) will do that for you. They handle hosting private packages as well as proxying the official npm repository. Sonatype Nexus also supports npm packages.

**Comment by samccone** [comment]
(closing as this is a non-issue but rather just a question) feel free to continue the covo here.
