### ISSUE TITLE
Yarn add --exact <github tarball url> installs latest npm version instead of code at url

### ISSUE THREAD

**Issue by reallistic** [yarnpkg/yarn#1366]
**Do you want to request a *feature* or report a *bug*?**
Report bug

**What is the current behavior?**
`yarn add --exact https://github.com/henrylilei/react-native-userdefaults-ios/tarball/214b49c2ab7e139ab692c30633a2690977a6b20b/react-native-userdefaults-ios.tar.gz` installs latest npm version instead of the specified commit and fork.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn add --exact https://github.com/henrylilei/react-native-userdefaults-ios/tarball/214b49c2ab7e139ab692c30633a2690977a6b20b/react-native-userdefaults-ios.tar.gz

grep suite node_modules/react-native-userdefaults-ios/READMD.md # shouldn't be empty
```

**What is the expected behavior?**
`yarn add --exact https://github.com/henrylilei/react-native-userdefaults-ios/tarball/214b49c2ab7e139ab692c30633a2690977a6b20b/react-native-userdefaults-ios.tar.gz`
Should install the code at the specified commit

**Please mention your node.js, yarn and operating system version.**
yarn --version # 0.16.0
npm --version # 3.8.3
node --version # v5.10.1
OS: Mac Os X sierra

I also tried:
```
yarn add dsibiski/react-native-userdefaults-ios\#7/head
yarn add dsibiski/react-native-userdefaults-ios\#7/merge
```

Neither of which installed the code from Pull Request # 7.

**Comment by samccone** [comment]
This is fixed on master :) thanks for the report!

**Comment by reallistic** [comment]
@samccone is there a commit I could follow to see when this makes it into a release?
