### ISSUE TITLE
yarn should show currently installed versions of modules on the system

### ISSUE THREAD

**Issue by NonPolynomial** [yarnpkg/yarn#1369]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

yarn has no command to show information about the currently installed versions of node etc.

**What is the expected behavior?**

I expect that yarn has a command which shows information / versions of installed node like `npm version`

maybe `yarn versions` because `yarn version` has another purpose.

***expected output***:
```bash
$ npm version
{
  npm: '3.10.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' 
}

$ yarn versions
{
  yarn: '0.16.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' 
}
```

**Please mention your node.js, yarn and operating system version.**
Node: 6.3.0
Yarn: 0.16.0
OS: Win 8.1

**Comment by pshkrjshnde** [comment]
`yarn ls` does that for you.

```
$ yarn ls
yarn ls v0.16.0
├─ accepts@1.3.3
│  ├─ mime-types@~2.1.11
│  └─ negotiator@0.6.1
├─ array-flatten@1.1.1
├─ content-disposition@0.5.1
├─ content-type@1.0.2
├─ cookie-signature@1.0.6
├─ cookie@0.3.1
├─ debug@2.2.0
│  └─ ms@0.7.1
├─ depd@1.1.0
├─ destroy@1.0.4
├─ ee-first@1.1.1
├─ encodeurl@1.0.1
├─ escape-html@1.0.3
├─ etag@1.7.0
├─ express@4.14.0
│  ├─ accepts@~1.3.3
│  ├─ array-flatten@1.1.1
│  ├─ content-disposition@0.5.1
│  ├─ content-type@~1.0.2
│  ├─ cookie-signature@1.0.6
│  ├─ cookie@0.3.1
│  ├─ debug@~2.2.0
│  ├─ depd@~1.1.0
│  ├─ encodeurl@~1.0.1
│  ├─ escape-html@~1.0.3
│  ├─ etag@~1.7.0
│  ├─ finalhandler@0.5.0
│  ├─ fresh@0.3.0
│  ├─ merge-descriptors@1.0.1
│  ├─ methods@~1.1.2
│  ├─ on-finished@~2.3.0
│  ├─ parseurl@~1.3.1
│  ├─ path-to-regexp@0.1.7
│  ├─ proxy-addr@~1.1.2
│  ├─ qs@6.2.0
│  ├─ range-parser@~1.2.0
│  ├─ send@0.14.1
│  ├─ serve-static@~1.11.1
│  ├─ type-is@~1.6.13
│  ├─ utils-merge@1.0.0
│  └─ vary@~1.1.0
├─ finalhandler@0.5.0
│  ├─ debug@~2.2.0
│  ├─ escape-html@~1.0.3
│  ├─ on-finished@~2.3.0
│  ├─ statuses@~1.3.0
│  └─ unpipe@~1.0.0
├─ forwarded@0.1.0
├─ fresh@0.3.0
├─ http-errors@1.5.0
│  ├─ inherits@2.0.1
│  ├─ setprototypeof@1.0.1
│  └─ statuses@>= 1.3.0 < 2
├─ inherits@2.0.1
├─ ipaddr.js@1.1.1
├─ media-typer@0.3.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.24.0
├─ mime-types@2.1.12
│  └─ mime-db@~1.24.0
├─ mime@1.3.4
├─ ms@0.7.1
├─ negotiator@0.6.1
├─ on-finished@2.3.0
│  └─ ee-first@1.1.1
├─ parseurl@1.3.1
├─ path-to-regexp@0.1.7
├─ proxy-addr@1.1.2
│  ├─ forwarded@~0.1.0
│  └─ ipaddr.js@1.1.1
├─ qs@6.2.0
├─ range-parser@1.2.0
├─ send@0.14.1
│  ├─ debug@~2.2.0
│  ├─ depd@~1.1.0
│  ├─ destroy@~1.0.4
│  ├─ encodeurl@~1.0.1
│  ├─ escape-html@~1.0.3
│  ├─ etag@~1.7.0
│  ├─ fresh@0.3.0
│  ├─ http-errors@~1.5.0
│  ├─ mime@1.3.4
│  ├─ ms@0.7.1
│  ├─ on-finished@~2.3.0
│  ├─ range-parser@~1.2.0
│  └─ statuses@~1.3.0
├─ serve-static@1.11.1
│  ├─ encodeurl@~1.0.1
│  ├─ escape-html@~1.0.3
│  ├─ parseurl@~1.3.1
│  └─ send@0.14.1
├─ setprototypeof@1.0.1
├─ statuses@1.3.0
├─ type-is@1.6.13
│  ├─ media-typer@0.3.0
│  └─ mime-types@~2.1.11
├─ unpipe@1.0.0
├─ utils-merge@1.0.0
└─ vary@1.1.0
Done in 0.10s.
```

**Comment by kittens** [comment]
Created #1423 to fix this, pending approval.

**Comment by NonPolynomial** [comment]
no, thats the same to `npm ls`.
`npm version` instead shows the installed versions of e.g. Node and NPM.

changed the title of that issue


Am 23.10.2016 um 09:39 schrieb Pushkaraj Shinde:
> `yarn ls` does that for you.
>
> ```
> $ yarn ls
> yarn ls v0.16.0
> ├─ accepts@1.3.3
> │  ├─ mime-types@~2.1.11
> │  └─ negotiator@0.6.1
> ├─ array-flatten@1.1.1
> ├─ content-disposition@0.5.1
> ├─ content-type@1.0.2
> ├─ cookie-signature@1.0.6
> ├─ cookie@0.3.1
> ├─ debug@2.2.0
> │  └─ ms@0.7.1
> ├─ depd@1.1.0
> ├─ destroy@1.0.4
> ├─ ee-first@1.1.1
> ├─ encodeurl@1.0.1
> ├─ escape-html@1.0.3
> ├─ etag@1.7.0
> ├─ express@4.14.0
> │  ├─ accepts@~1.3.3
> │  ├─ array-flatten@1.1.1
> │  ├─ content-disposition@0.5.1
> │  ├─ content-type@~1.0.2
> │  ├─ cookie-signature@1.0.6
> │  ├─ cookie@0.3.1
> │  ├─ debug@~2.2.0
> │  ├─ depd@~1.1.0
> │  ├─ encodeurl@~1.0.1
> │  ├─ escape-html@~1.0.3
> │  ├─ etag@~1.7.0
> │  ├─ finalhandler@0.5.0
> │  ├─ fresh@0.3.0
> │  ├─ merge-descriptors@1.0.1
> │  ├─ methods@~1.1.2
> │  ├─ on-finished@~2.3.0
> │  ├─ parseurl@~1.3.1
> │  ├─ path-to-regexp@0.1.7
> │  ├─ proxy-addr@~1.1.2
> │  ├─ qs@6.2.0
> │  ├─ range-parser@~1.2.0
> │  ├─ send@0.14.1
> │  ├─ serve-static@~1.11.1
> │  ├─ type-is@~1.6.13
> │  ├─ utils-merge@1.0.0
> │  └─ vary@~1.1.0
> ├─ finalhandler@0.5.0
> │  ├─ debug@~2.2.0
> │  ├─ escape-html@~1.0.3
> │  ├─ on-finished@~2.3.0
> │  ├─ statuses@~1.3.0
> │  └─ unpipe@~1.0.0
> ├─ forwarded@0.1.0
> ├─ fresh@0.3.0
> ├─ http-errors@1.5.0
> │  ├─ inherits@2.0.1
> │  ├─ setprototypeof@1.0.1
> │  └─ statuses@>= 1.3.0 < 2
> ├─ inherits@2.0.1
> ├─ ipaddr.js@1.1.1
> ├─ media-typer@0.3.0
> ├─ merge-descriptors@1.0.1
> ├─ methods@1.1.2
> ├─ mime-db@1.24.0
> ├─ mime-types@2.1.12
> │  └─ mime-db@~1.24.0
> ├─ mime@1.3.4
> ├─ ms@0.7.1
> ├─ negotiator@0.6.1
> ├─ on-finished@2.3.0
> │  └─ ee-first@1.1.1
> ├─ parseurl@1.3.1
> ├─ path-to-regexp@0.1.7
> ├─ proxy-addr@1.1.2
> │  ├─ forwarded@~0.1.0
> │  └─ ipaddr.js@1.1.1
> ├─ qs@6.2.0
> ├─ range-parser@1.2.0
> ├─ send@0.14.1
> │  ├─ debug@~2.2.0
> │  ├─ depd@~1.1.0
> │  ├─ destroy@~1.0.4
> │  ├─ encodeurl@~1.0.1
> │  ├─ escape-html@~1.0.3
> │  ├─ etag@~1.7.0
> │  ├─ fresh@0.3.0
> │  ├─ http-errors@~1.5.0
> │  ├─ mime@1.3.4
> │  ├─ ms@0.7.1
> │  ├─ on-finished@~2.3.0
> │  ├─ range-parser@~1.2.0
> │  └─ statuses@~1.3.0
> ├─ serve-static@1.11.1
> │  ├─ encodeurl@~1.0.1
> │  ├─ escape-html@~1.0.3
> │  ├─ parseurl@~1.3.1
> │  └─ send@0.14.1
> ├─ setprototypeof@1.0.1
> ├─ statuses@1.3.0
> ├─ type-is@1.6.13
> │  ├─ media-typer@0.3.0
> │  └─ mime-types@~2.1.11
> ├─ unpipe@1.0.0
> ├─ utils-merge@1.0.0
> └─ vary@1.1.0
> Done in 0.10s.
> ```
>


---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by piotr-cz** [comment]
Command is called now `yarn list`
