### ISSUE TITLE
error missing dependent module (@sindresorhus\df)

### ISSUE THREAD

**Issue by yegor-sytnyk** [yarnpkg/yarn#1378]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Cannot add dependencies, because one of dependant modules is not installed

**If the current behavior is a bug, please provide the steps to reproduce.**
 
yarn init
yarn add vbuild
yarn add lodash (can be any other module) fails

---> Error (from error-log)
...
Trace: 
  Error: ENOENT: no such file or directory, open 'd:\Projects\temp\vbuild_test\node_modules\@sindresorhus\df\index.js'
      at Error (native)

**What is the expected behavior?**

should be able to add new dependencies

**Please mention your node.js, yarn and operating system version.**

Node: 6.5.0
Yarn: 0.16.1
OS: Windows 10 64x

**Comment by samccone** [comment]
The root issue here is fixed `@sindresorhus\df`
