### ISSUE TITLE
yarn init : error

### ISSUE THREAD

**Issue by Pashtunzoy** [yarnpkg/yarn#1382]
**Do you want to request a *feature* or report a *bug*?**

Can't seem to execute `yarn init`.
This is the error I get: 
```
yarn init v0.16.1
error Command failed.
Exit code: 1
Command: git
Arguments: config user.name
Directory: /Users/user/Desktop/project
Output:

info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
```
**Please mention your node.js, yarn and operating system version.**
`Node version: v6.8.1 | Yarn version: v0.16.1 | Operating System:  macOS Sierra

**Comment by wyze** [comment]
What happens when you run `git config --get user.name`?

**Comment by samccone** [comment]
When config values are unset. `git` raises a 1 exit code which causes things to crash :fire: .

![image](https://cloud.githubusercontent.com/assets/883126/19650955/e05a8a44-99bf-11e6-9856-ec7f578aa994.png)

Seems like there is an opportunity to handle this better.
https://github.com/yarnpkg/yarn/blob/f04b157a0162114de7252b682ecf4b66895d7e87/src/cli/commands/init.js#L39

**Comment by jpoo90** [comment]
Hi @samccone I can try solving this one. Should we request the values [name, email] if an error is returned from the git verification ? or Do we want to show a more rich error to tell the user to configure his/her git ?

**Comment by samccone** [comment]
I think just requesting the email / un in a prompt would work :)

**Comment by Pashtunzoy** [comment]
So what's the fix for this?
