### ISSUE TITLE
Yarn is 10x slower than NPM

### ISSUE THREAD

**Issue by jonrimmer** [yarnpkg/yarn#1385]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn is around 10x slower than NPM at doing basic operations like adding or removing packages.

**If the current behavior is a bug, please provide the steps to reproduce.**

Init a new package, and start installing Webpack and some loaders. E.g.

```
mkdir yarn-test
cd yarn-test
yarn init -y
yarn add webpack
yarn add json-loader
yarn add raw-loader
```

Adding webpack takes ~15 seconds.
Adding json-loader takes ~11 seconds.
Adding raw-loader takes ~10 seconds.

Most of the time is spend in the "linking dependencies" stage, running through about 4000 dependencies each time.

Now try it with npm:

```
mkdir npm-test
cd npm-test
npm init -y
npm install webpack --save-dev
npm install json-loader --save-dev
npm install raw-loader --save-dev
```

Installing webpack takes ~10 seconds.
Installing json-loader takes ~1 second
Installing raw-loader takes ~ 1 second

**What is the expected behavior?**

Yarn should be as fast, or faster, than NPM.

**Please mention your node.js, yarn and operating system version.**

Node: v6.9.1
Yarn: 0.16.0
OS: Windows 10

**Comment by samccone** [comment]
Dupe #990

**Comment by gitsutos** [comment]
same in linux

**Comment by maiorano84** [comment]
Same in OSX and every operating system. We've since abandoned Yarn in favor of NPM, since the package maintainers simply mark these types of things as completed with no explanation, or "can't fix / won't fix".
