### ISSUE TITLE
Update Errors with hard-coded strings to use reporter.lang

### ISSUE THREAD

**Issue by thejameskyle** [yarnpkg/yarn#1387]
**Do you want to request a _feature_ or report a _bug_?** Bug

**What is the current behavior?**

There are at least a few strings not using `this.reporter.lang` which will make them impossible to translate later on. Such as this one: https://github.com/yarnpkg/yarn/blob/master/src/resolvers/registries/npm-resolver.js#L36-L37

**What is the expected behavior?**

Need to update these to use, `this.reporter.lang`, search the code base for that for examples.

This is a good issue for people wanting to contribute for the first time to take on

**Comment by msaglietto** [comment]
Sure, I can give it a try .. I would love to contribute

**Comment by msaglietto** [comment]
I think most of the usage have been converted  .. if there is any other let me know ..

**Comment by kamilogorek** [comment]
This issue has been resolved as well.
