### ISSUE TITLE
Installation Problem: invalid path

### ISSUE THREAD

**Issue by PROFITVenchurs** [yarnpkg/yarn#1388]
Invalid path to yarn after installing it using brew on Mac OS: `export PATH="$PATH:$HOME/.yarn/bin"`, must be `export PATH="$PATH:/usr/local/Cellar/yarn/0.16.1/bin"`

**Comment by MatthiasWinkelmann** [comment]
I ran into the same issue. It would report ```success Installed [elm@0.17.1] with binaries:...``` yet I could not find them. I believe I eventually fixed it by deleting ```~/.yarn-config```.

Configuration:  El Capitan & fish shell

**Comment by wordofchristian** [comment]
Same issue here. Removing `~/.yarn-config` and reinstalling yarn didn't solve it for me either.  `yarn global bin` would always report it's location as `/usr/local/Cellar/node/7.1.0/bin
`.  I finally fixed it by adding `export PATH="$PATH:$(yarn global bin)"` to my profile.

**Comment by olingern** [comment]
@PROFITVenchurs can you confirm if this is still an issue? If not, I'd like to close.
