### ISSUE TITLE
Why npm and yarn do not merge together.

### ISSUE THREAD

**Issue by crper** [yarnpkg/yarn#1395]
Why npm and yarn do not merge together. . Yarn global cache is very useful, there are some features; and although historical burden of npm, but wins in the use of more ecological circle perfect. Solve; just like the original node and io.js merger, why not?

**Comment by kittens** [comment]
node and iojs were forks. Yarn was written from scratch and has a much different workflow that isn't compatible with the existing status quo for npm.
