### ISSUE TITLE
Timeout Bug

### ISSUE THREAD

**Issue by ghost** [yarnpkg/yarn#1400]
Bug: Installing with Yarn on Windows yields timeout.

Running Yarn for the first time in my project stops halfway through the [1/4] part of the install command.

[yarn-error.log](https://github.com/yarnpkg/yarn/files/547906/yarn-error.log.txt)

Yarn should be installing all dependencies, or be giving more verbose information about where it failed and why.

NodeJs v6.8.1
Yarn v0.16.0
Windows 10 v1607

**Comment by kash-raman** [comment]
Im also having similar issue. Yarn is failing with connection timeout. But the failure reason is not  not self explanatory on which package is failing. Any thoughts? 
[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/548516/yarn-error.log.txt)

**Comment by mpash** [comment]
Any update on the timeout bug? This issue has persisted to ver 19.

**Comment by KidkArolis** [comment]
The user that posted this issue has been deleted. Not sure we will be able to reproduce this issue. Shall we close?

**Comment by tthef** [comment]
I see this often, yarn doesn't work well on slowish Internet connections, it times out too fast.

**Comment by paul-soporan** [comment]
Closing this as fixed in the v2, where the timeout logic has greatly improved and such issues don't happen.

https://yarnpkg.com/getting-started/migration
