### ISSUE TITLE
Yarn not installing nested binaries

### ISSUE THREAD

**Issue by tjbenton** [yarnpkg/yarn#1401]
All nested binaries are getting ignored when a package is installed.

**What is the current behavior?**
currently when I try to install a package for my company that holds all our lint rules for JS and our Styles all the binaries are being ignored for it.

```shell
mkdir yarn-nested-binaries-test
cd yarn-nested-binaries-test
yarn init --yes
yarn add ma-shop/lint-rules --dev # https://github.com/ma-shop/lint-rules
```

When I check for the binaries that where installed it shows that none where installed.

```shell
[tylerbenton:~/yarn-nested-binaries-test]$ ls node_modules/.bin
gls: cannot access 'node_modules/.bin': No such file or directory
```

When I remove the `node_modules` folder and reinstall using npm.

```shell
rm -rf node_modules
npm install
```

I get several binaries that were added to the `node_modules/.bin` folder, and the 2 binaries that I was looking for which is `eslint` and `stylelint`

```shell
[tylerbenton:~/yarn-nested-binaries-test]$ ls node_modules/.bin
JSONStream  babylon       colorguard       doiuse  esparse     js-yaml     loose-envify  rimraf  shjs         strip-indent         stylehacks  window-size
acorn       browserslist  css-rule-stream  eslint  esvalidate  jsonfilter  mkdirp        semver  specificity  strip-json-comments  stylelint
```

Versions: 
mac: macOS Sierra 10.12
yarn: 0.16.1
node: 6.9.1
npm: 3.10.8

**Comment by wyze** [comment]
This looks like what is being discussed in #1210.

**Comment by wyze** [comment]
Close in favor of #1210.
