### ISSUE TITLE
`yarn global add mocha` on Windows 10 x64 Professional fails

### ISSUE THREAD

**Issue by CalmBit** [yarnpkg/yarn#1407]
**Do you want to request a _feature_ or report a _bug_?**

Bug.

**What is the current behavior?**

Yarn gets through most of the install process for a global package, `mocha`, until it errors out:

```
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success: Installed mocha@3.1.2 with binaries:
    - mocha
    - _mocha
error: An unexpected error occurred, please open a bug report... [snipped]
```

`yarn-error.log` has the following error message inside of it:

```
Trace: 
  Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\mocha'
      at Error (native)
```

After this, it will concede the same "installation success" message as before, without an error, but the binary doesn't seem to be installed or accessible.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install Yarn from the .msi installer (with Node.JS + NPM present)
2. `yarn global add mocha`

**What is the expected behavior?**

Installation of `mocha` binary globally.

**Please mention your node.js, yarn and operating system version.**

Windows 10, x64 "Professional", yarn v.0.16.0, Node.JS v.6.4.0

**Comment by bvangraafeiland** [comment]
Having the same issue here, a workaround is to start the command prompt as administrator.

**Comment by CalmBit** [comment]
They are indeed installed into that path for me! Thanks for the pointer!

**Comment by Daniel15** [comment]
This was fixed.
