### ISSUE TITLE
How do you plan to better support native modules

### ISSUE THREAD

**Issue by alexhultman** [yarnpkg/yarn#1414]
In what way does yarn better the distribution of binary addons compared to NPM? NPM has shown no interest in improving this whatsoever and they do not listen to their users.

It would help a lot if packages could have per-architecture, per-OS and per-bitness content so that we could pre-compile addons for many platforms and have them downloaded by the correct platform/node version, instead of having to package everything in one single mega package.

**Comment by samccone** [comment]
Mind opening this here?
https://github.com/yarnpkg/rfcs

Thanks!
