### ISSUE TITLE
socket error on Resolving packages 

### ISSUE THREAD

**Issue by arpit1997** [yarnpkg/yarn#1428]
using latest version of yarn
**Do you want to request a _feature_ or report a _bug_?**
bug report
**What is the current behavior?**
unexpected behaviour
**If the current behavior is a bug, please provide the steps to reproduce.**
Most of the times i get socket Hangup error
`
yarn install v0.15.0
info No lockfile found.
[1/4] Resolving packages...
warning babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
error https://registry.yarnpkg.com/multiline: socket hang up
    at createHangUpError (_http_client.js:213:15)
    at TLSSocket.socketCloseListener (_http_client.js:245:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
`
**Please mention your node.js, yarn and operating system version.**
Ubuntu 14.04, others latest

**Comment by kittens** [comment]
Is this an intermittent issue or does it work on a second attempt?

**Comment by arpit1997** [comment]
I have to give it 6-7 tries to get it working. I googled this error and found from [stackoverflow](http://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean)

> When you, as a client, send a request to a remote server, and receive no timely response. Your socket is ended which thrown this error. You should catch this error and decide how to handle it: whether retry the request, queue it for later, etc.

I guess retries for the request are not enough that is why it quits soearly

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where the timeout and retry logic has improved a lot.

https://yarnpkg.com/getting-started/migration
