### ISSUE TITLE
[FEATURE] custom dependency types

### ISSUE THREAD

**Issue by creynders** [yarnpkg/yarn#1431]
**Do you want to request a *feature* or report a *bug*?**
FEATURE
**What is the current behavior?**
There's a limited number of dependency types
**What is the requested behavior?**
Having a limited number of dependency types does not make sense in today's development process. If I look at a typical project of mine I have many various stages and environments in development and deployment. 

It would be awesome to be able to declare them as such, e.g.:

```
dependencies: {
  dev: {
    babel: 'v0.0.0'
  },
  uitest: {
    nightwatch: 'v0.0.0'
  },
  unittest: {
    mocha: 'v0.0.0'
  },
  core: {
    express: 'v0.0.0'
  }
}
```

Installation could be as easy as `yarn install --core --uitest --dev` i.e. just specifying which dependency types you want to install.
This would allow us to install only what's really necessary on each machine: local dev, QA, testing, staging, production

**Comment by wyze** [comment]
Would you mind opening this up over at [yarnpkg/rfcs](https://github.com/yarnpkg/rfcs)?

Thanks!

**Comment by creynders** [comment]
Sure, thanks @wyze
