### ISSUE TITLE
Yarn pack output is not parseable

### ISSUE THREAD

**Issue by sheerun** [yarnpkg/yarn#1432]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
yarn pack results in following non-parseable outputs:

``` bash
# yarn pack v0.16.2
success Wrote tarball to "/Users/sheerun/Source/yarn/yarn-v0.16.2.tgz".
✨  Done in 222.09s
```

```
# yarn pack --json
{"type":"success","data":"Wrote tarball to \"/Users/sheerun/Source/yarn/yarn-v0.16.2.tgz\"."}
{"type":"finished","data":213390}
```

**What is the expected behavior?**
Compare it to parseable npm outputs:

```
# npm pack
yarn-0.16.2.tgz
```

```
npm pack --json
yarn-0.16.2.tgz
```

My goal is to extract generated filename from yarn output, but currently it's not possible without magic regexps. Ii suggest adding extra field in json output with absolute output path.

**Comment by gsklee** [comment]
@bestander close

* This is not a bug and is not specific to `yarn pack`; it's the current behavior of adding the `--json` flag to any Yarn command

* The non-parsable claim appears to be a subjective one; the output follows an open data format called [NDJSON](http://specs.okfnlabs.org/ndjson/) which is designed exactly to make JSON streaming parsing a friendly task
