### ISSUE TITLE
Cannot resolve module after clean install

### ISSUE THREAD

**Issue by zaalbarxx** [yarnpkg/yarn#1434]
**Do you want to request a _feature_ or report a _bug_?**

BUG

**What is the current behavior?**

After running clean `yarn` at least one of the packages does not work (Angulartics). The behavior is strange because the package itself gets downloaded and exists in `node_modules`, but it cannot be resolved by Webpack (import). Running clean `npm install` works (no `cannot resolve module` error).

Tried adding package manually with `yarn add angulartics`. It worked once, but since we got the same error when building the app, I cleared the `node_modules` and ran `yarn` once again (even following with `yarn add angulartics`) but this time it did not work.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
"dependencies": {
    "angular": "^1.5.8",
    "angular-animate": "^1.5.8",
    "angular-aria": "^1.5.8",
    "angular-async-await": "https://github.com/zaalbarxx/angular-async-await/tarball/master",
    "angular-cookies": "^1.5.8",
    "angular-jwt": "0.1.3",
    "angular-localforage": "^1.3.1",
    "angular-material": "^1.1.1",
    "angular-messages": "^1.5.8",
    "angular-resource": "^1.5.8",
    "angular-sanitize": "^1.5.8",
    "angular-storage": "0.0.15",
    "angular-ui-router": "^0.2.18",
    "angularjs-color-picker": "2.5.0",
    "angulartics": "^1.2.1",
    "angulartics-google-analytics": "^0.2.0",
    "d3": "^3.5.17",
    "dateformat": "^1.0.12",
    "fix-outline": "^0.1.1",
    "highcharts": "^5.0.0",
    "highcharts-ng": "0.0.13",
    "json-loader": "^0.5.4",
    "lodash": "^4.11.2",
    "moment": "^2.14.1",
    "ng-async": "^1.1.0",
    "ramda": "^0.21.0",
    "snake-case": "^2.1.0",
    "tinycolor2": "^1.4.1"
  },
```

**What is the expected behavior?**

The error from Webpack should not happen.

**Please mention your node.js, yarn and operating system version.**

yarn v0.16.1
Windows 10
node 6.5.0

**Comment by hpurmann** [comment]
Hi @zaalbarxx! Can you create a public repository containing the necessary webpack config? This would help a lot when trying to reproduce your case.

**Comment by wcj3** [comment]
Having a similar issue as well. Webpack cannot resolve a module installed as a nested dependency by Yarn but if I delete node_modules and do npm install, it works.

**Comment by ivoba** [comment]
I ran in this issue as well when using yarn 1.1.0 with a fresh `yarn install`.
Before with yarn 0.27.5-1 webpack could resolve all dependencies.
Now webpack cant resolve a nested dependecy:

> ERROR in ./~/react-select-plus/lib/Select.js
> Module not found: Error: Cannot resolve module 'react-input-autosize' in 

The lock file was created with an older version of yarn, not sure if this is a problem?

**Comment by BYK** [comment]
>The lock file was created with an older version of yarn, not sure if this is a problem?

Yup, that would do it.

Closing due to lack of response from the original author.

**Comment by jeremyfrancis** [comment]
> Having a similar issue as well. Webpack cannot resolve a module installed as a nested dependency by Yarn but if I delete node_modules and do npm install, it works.

Yes this is exactly the same for us. We really need to get back to yarn though for our server side integrations to work. Hope someone can help us here.

**Comment by AlexYuleUSDS** [comment]
We are running into this also with `@uswds` in a new nextjs project. Npm works fine but with yarn, nextjs can't resolve the modules
