### ISSUE TITLE
yarn run <script> error

### ISSUE THREAD

**Issue by boazblake** [yarnpkg/yarn#1445]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
not running scripts
**If the current behavior is a bug, please provide the steps to reproduce.**

see error response to reproduce

**What is the expected behavior?**

run the script

**Please mention your node.js, yarn and operating system version.**
windows 7, node 6.5.0, yarn 0.6.1
![image](https://cloud.githubusercontent.com/assets/3834931/19693756/3e831248-9aa2-11e6-9544-33434e840452.png)
![image](https://cloud.githubusercontent.com/assets/3834931/19693934/068385fc-9aa3-11e6-9b3c-af87f25a63ca.png)

**Comment by Daniel15** [comment]
Could you please provide your `package.json`?

**Comment by boazblake** [comment]
```
{
  "name": "purescript-falcor-test-server.",
  "version": "1.0.0",
  "description": "purescript-falcor test server.",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "./node_modules/.bin/nodemon server.js"
  },
  "repository": {
    "type": "git"
  },
  "author": "bblake <bblake@goempyrean.com>",
  "license": "ISC",
  "dependencies": {
    "app-module-path": "^1.0.6",
    "bluebird": "^3.2.2",
    "body-parser": "^1.14.2",
    "cors": "^2.7.1",
    "daggy": "0.0.1",
    "data.maybe": "^1.2.1",
    "data.task": "^3.0.0",
    "express": "^4.13.4",
    "falcor": "^0.1.16",
    "falcor-express": "^0.1.2",
    "falcor-http-datasource": "^0.1.3",
    "falcor-json-graph": "^1.1.7",
    "falcor-router": "^0.2.12",
    "graceful-fs": "^4.1.9",
    "memoize-promise": "^0.2.2",
    "node-uuid": "^1.4.7",
    "nodemon": "^1.11.0",
    "pointfree-fantasy": "^0.1.3",
    "ramda": "^0.19.1",
    "request": "^2.69.0",
    "request-promise": "^2.0.0",
    "winston": "^2.2.0",
    "winston-redis": "^1.0.0",
    "yarn": "^0.16.1"
  },
  "engines": {
    "node": ">=6.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.0.4",
    "eslint": "^2.11.0"
  }
}
```

**Comment by Daniel15** [comment]
Change this:
```
"dev": "./node_modules/.bin/nodemon server.js"
```

To this:
```
"dev": "nodemon server.js"
```

And it should work (unless Yarn has a bug)

You can run the executable for any installed Node.js module just by using its name (`nodemon`) rather than the full path (`./node_modules/.bin/nodemon`).

**Comment by boazblake** [comment]
It works - thank you for helping me (and the info on running node mods) out I appreciate your time.

**Comment by Daniel15** [comment]
Glad to help!
