### ISSUE TITLE
Install trouble on macOS Siera

### ISSUE THREAD

**Issue by ericelliott** [yarnpkg/yarn#1447]
**Do you want to request a *feature* or report a *bug*?**
Documentation bug (IMO)

**What is the current behavior?**
Just took a stab at installing Yarn. Brew was busted because of the macOS Sierra upgrade. After fixing that, Yarn tried to install its own Node (I use nvm). 

Homebrew install lists Node as a dependency, so installs Node with Homebrew, which screws up the default Node and/or nvm installs.

Brew then failed to properly link yarn, so when I tried to run it, it wasn't found.

In other words, the documented install steps left my Node install broken.

After uninstalling and cleaning up the mess, I tried an alternative approach: `npm install -g yarn`.

Boom. Magically worked as I expected. Didn't mess with my Node config. `yarn --version` reports `0.16.1`.

**What is the expected behavior?**
Maybe suggest `npm install -g yarn` as the default in the documentation for a smoother install experience for people who already have Node installed using a method other than homebrew? Or at least mention its existence in the docs?

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v6.6.0
$ yarn --version
0.16.1
```

macOS Sierra 10.12

**Comment by Daniel15** [comment]
Hello @ericelliott!  I think this is a duplicate of #1116. The Homebrew script is maintained over in their repo, so that's where it should be updated. Here's my reply from #1116:

> I feel like this issue should go to the Homebrew repo rather than this repo. The solution should not be specific to Yarn, as it'd affect **any** app installed via Homebrew that requires Node.js. Ideally Homebrew itself should have some way of allowing apps to specify that they need a "node.js-ish environment", and have both Node.js and nvm fulfill that requirement.

> Given that, I'm going to close this issue and kindly suggest that you ask the Homebrew maintainers about it. However, if you disagree with me, please let me know and I'd be more than happy to reopen this issue. 

> Maybe suggest npm install -g yarn as the default in the documentation

It's mentioned on the "alternatives" page as generally we want to discourage people from installing via npm.

Thank you for trying Yarn! 😄

**Comment by ericelliott** [comment]
> It's mentioned on the "alternatives" page as generally we want to discourage people from installing via npm.

Why? Is there a good reason not to install from npm, and if so, why is it even an option? Is that mentioned in the docs somewhere?

 _**Side note:** frankly, if npm install was not an option, I would not have bothered to continue._

**Comment by hawkrives** [comment]
@ericelliott You might be interested in the discussion in https://github.com/yarnpkg/yarn/issues/1082, specifically @Daniel15's comment therein: https://github.com/yarnpkg/yarn/issues/1082#issuecomment-254026649.

**Comment by Daniel15** [comment]
I think I'll write a blog post to cover this eventually 😛 npm is not ideal for system-wide apps. Here's my comment @hawkrives mentioned:
> Advantages of using the system's native package manager rather than something like `npm install -g yarn`:
> 
> - Upgrades are handled the same way as all other software on your system (`apt-get upgrade`). It's not a special snowflake.
> - All the security problems with npm (eg. packages not being signed) make it less than ideal for anything installed system wide. apt-get gives you proper GPG signature verification.
> - Using npm means you're tightly-coupled to npm. If you later want to have a better installation solution, you need to have this awkward transition period where you try to get users to switch to the newer installation method.
> - The setup instructions need the whole weird "*install Node.js first, then ensure npm is up-to-date, then install Yarn*" thing. That'd be like telling people to manually install their npm dependencies 😆 . With a proper package management system, the Yarn package would simply have a dependency on the Node.js package, and "apt-get install yarn" would install both.
> 
> If we want to appeal to people that have limited Node.js experience, we shouldn't make any assumptions that they know anything about the Node.js ecosystem or what "npm" even is.

**Comment by twome** [comment]
Whether the responsibility lies with the Homebrew maintainers or not, the macOS `brew` instructions currently up on the site are still messing with pre-existing Node installations. Until the `brew` method is solid and dependable, can you please replace the macOS instructions with the installation script method? 

Also, the current wording is confusing:
> This will also install Node.js if it is not already installed.
This isn't technically true - it will install the Node.js **homebrew package** if the Node.js **homebrew package** is not already installed. That's an important difference.

**Comment by Daniel15** [comment]
> Until the brew method is solid and dependable, can you please replace the macOS instructions with the installation script method?

I don't think we'd want to replace them, however we can show the installation script instructions in addition to the Homebrew instructions instead of just showing those instructions on the "alternatives" tab. Would you like to send a pull request to do that?
