### ISSUE TITLE
Yarn doesn't set NODE_ENV for `yarn --prod`

### ISSUE THREAD

**Issue by jkrems** [yarnpkg/yarn#1450]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

When running lifecycle scripts during `yarn --prod`, `yarn` doesn't set `NODE_ENV=production`.

**If the current behavior is a bug, please provide the steps to reproduce.**

With the following `package.json`:

``` json
{
  "name": "yarn-scripts",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "preinstall": "echo 'preinstall:' ${NODE_ENV}",
    "postinstall": "echo 'postinstall:' ${NODE_ENV}"
  },
  "license": "MIT"
}
```

`yarn` doesn't set NODE_ENV:

```
> yarn --prod
yarn install v0.16.1
info No lockfile found.
$ echo 'preinstall:' ${NODE_ENV}
preinstall:
success Nothing to install.
$ echo 'postinstall:' ${NODE_ENV}
postinstall:
✨  Done in 0.11s.
```

**What is the expected behavior?**

Match what `npm` is doing:

```
> npm i --silent --production
preinstall: production
postinstall: production
```

**Please mention your node.js, yarn and operating system version.**
- node: 6.9.1
- yarn: 0.16.1
- npm: 3.10.8
- OS: macOS 10.12.1

**Comment by samccone** [comment]
Thanks for the issue good catch and easy fix. PR opened.

**Comment by jkrems** [comment]
Thanks for the quick fix! :)
