### ISSUE TITLE
Yarn fails and doesn't provide information when running inside Docker

### ISSUE THREAD

**Issue by felixsanz** [yarnpkg/yarn#1460]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

> An unexpected error occured, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't know, I can't check the error :)

**What is the expected behavior?**

**It should print errors directly to stdout/stderr**. I'm trying to build a Docker image and it fails. But since this happens inside the container (and destroyed on the error step), I can't check that yarn-error.log because it doesn't exist anymore.

**Please mention your node.js, yarn and operating system version.**

Yarn 0.16.1 using Docker

**Comment by Daniel15** [comment]
Hi @felixsanz! Is that happening when you run `yarn install` in the Docker container? You could try `cat` the log file when the error occurs, and see what it contains. I recently wrote some end-to-end tests for Yarn using Docker (#1391) and this is what I did:

```
#!/bin/bash
# Executed within a fresh Docker container to test execution of Yarn.
# Should be executed after Yarn has been installed.
set -ex

fail_with_log() {
  # Include the yarn-error.log file in the output, if available
  exitcode=$?
  if [ -s yarn-error.log ]; then
    cat yarn-error.log
  fi;
  exit $exitcode
}

cd /tmp
mkdir yarntest
cd yarntest
yarn add react || fail_with_log
```

Is your container running Ubuntu by any chance? If so, you'll need to install the `ca-certificates` package in order for TLS/SSL to work from Node.js. That's the issue I encountered when trying to run Yarn in Docker 😄

**Comment by Daniel15** [comment]
The other alternative is to mount a directory (`-v` flag to `docker run`) and run Yarn in that directory. Then you'll be able to look at the log file on your host machine.

**Comment by felixsanz** [comment]
I'm gonna close this because deleting the yarn.lock file fixed the issue and i don't get the error anymore. Probably it was messed up while i was trying builds. If happens again i'll try your suggestions and comment here again. Thanks!

**Comment by JoshuaKGoldberg** [comment]
I'm in a similar situation with VSTS build machines. @Daniel15 your suggested steps are great 😊 thanks!

I resolved the problem by adding a cmd task that runs if a previous task has failed and prints the contents of `yarn-error.log` if it exists:

```cmd
if exist yarn-error.log echo "Found error output in yarn-error.log:" && type yarn-error.log && del yarn-error.log
```
