### ISSUE TITLE
Installation Problem: I can not install hexo-cli with yarn

### ISSUE THREAD

**Issue by mouyong** [yarnpkg/yarn#1465]
## This is my command
yarn blobal add hexo-cli

## But I get the following error

yarn global v0.16.1
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed hexo-cli@1.0.2 with binaries:
      - hexo
Done in 2.45s.

**Comment by samccone** [comment]
marking as a dup of #1321 .. we have several of these issues around global installs.

Thanks for the issue
