### ISSUE TITLE
--save with tag saves the tag, not the version range

### ISSUE THREAD

**Issue by rstacruz** [yarnpkg/yarn#1468]
**Do you want to request a *feature* or report a *bug*?**

Sort of a bug, depending on how you look at it.

**What is the current behavior?**

Running `yarn add left-pad@latest` saves the tag to your package.json:

```js
// yarn add left-pad@latest

"dependencies": {
  "left-pad": "latest"
}
```

Whereas npm will instead save the version range, given `npm install left-pad@latest --save`:

```js
// npm install left-pad@latest --save

"dependencies" {
  "left-pad": "^1.1.3"
}
```

**What is the expected behavior?**

I don't really know which is correct here, I'll leave that to your judgement!

Personally I'm leaning on the side of npm's behavior here; `yarn add x@latest` doesn't mean "I always want to have the latest version", it usually means "I want the latest right now".

**Please mention your node.js, yarn and operating system version.**

- Node 6.3.0
- macOS Sierra

**Comment by samccone** [comment]
dup or #1306 your help is welcome :)
