### ISSUE TITLE
Installation Problem: What happened to ~/.node_modules/bin/ ?

### ISSUE THREAD

**Issue by kaihendry** [yarnpkg/yarn#1469]
I'm using Archlinux, but I am not using the AUR package

```
~$ yarn global add psi
yarn global v0.15.1
warning No license field
[1/4] Resolving packages...
warning psi > googleapis > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed psi@2.0.4 with binaries:
      - psi
error EACCES: permission denied, symlink '../../home/hendry/.yarn-cache/.global/node_modules/.bin/psi' -> '/usr/bin/psi'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/global for documentation about this command.
~$ psi
-bash: psi: command not found
~$ cd
~$ cd .node_modules/bin/
~/.node_modules/bin$ ls
chrome-debug  create-react-app  critical  eslint  gatsby  gulp  hs  http-server  jscs  lighthouse  npm-check  svgo  vue  yarn
```

Firstly, how do I configure it to link at `/usr/local/bin` and not `/usr/bin`?

Secondly... in the past I've happily used:

    PATH="$HOME/.node_modules/bin:$PATH"

But in order to get things to "work", I've had to update that to a very cryptic and error ridden:

    PATH="$HOME/.yarn-cache/.global/node_modules/yarn/bin:$PATH"

**Comment by samccone** [comment]
Dup of #872 thanks for the report

**Comment by kaihendry** [comment]
Er, don't see how that issue address `/usr/bin` issue or the PATH confusion. :confused:

**Comment by samccone** [comment]
The install install in your log is from
error EACCES: permission denied, symlink '../../home/hendry/.yarn-cache/.global/node_modules/.bin/psi' -> '/usr/bin/psi'

The bin link issue os a separate issue
