### ISSUE TITLE
Improve resolver test coverage

### ISSUE THREAD

**Issue by olingern** [yarnpkg/yarn#1471]
**Do you want to request a *feature* or report a *bug*?**
n/a

**What is the current behavior?**
Resolvers lack significant coverage.

<img width="789" alt="screen shot 2016-10-26 at 12 45 19 am" src="https://cloud.githubusercontent.com/assets/1470297/19713629/9d920032-9b15-11e6-897e-8c5b20457479.png">

PR for issue: #1470

**Comment by samccone** [comment]
Thanks we will continue this in #1470
