### ISSUE TITLE
yarn global install jekyll-gen on Windows 10 x64

### ISSUE THREAD

**Issue by lgh06** [yarnpkg/yarn#1476]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
install a package globally on windows.
**If the current behavior is a bug, please provide the steps to reproduce.**
 npm i -g yarn.yarn installed successfully.
yarn global add jekyll-gen,reported error.
**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
nodejs 4.4.7 npm 2.15.8,windows 10 x64 professional.

log:
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\DELL\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js global add jekyll-gen

PATH: 
  C:\Users\DELL\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\DELL\bin;C:\Python27;C:\Python27\Scripts;C:\tools\ruby23\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\nodejs;D:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\WinSCP;D:\Program Files\ctags58;D:\xampp\php;D:\xampp\mysql\bin;C:\ProgramData\chocolatey\bin;C:\tools\DevKit2\bin;C:\ProgramData\ComposerSetup\bin;C:\Users\DELL\AppData\Roaming\npm;C:\Users\DELL\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

Yarn version: 
  0.16.1

Node version: 
  4.4.7

Platform: 
  win32 x64

npm manifest: 
  {
    "dependencies": {
      "jekyll-gen": "^1.0.7"
    }
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  commander@^2.9.0:
    version "2.9.0"
    resolved "https://registry.yarnpkg.com/commander/-/commander-2.9.0.tgz#9c99094176e12240cb22d6c5146098400fe0f7d4"
    dependencies:
      graceful-readlink ">= 1.0.0"
  
  "graceful-readlink@>= 1.0.0":
    version "1.0.1"
    resolved "https://registry.yarnpkg.com/graceful-readlink/-/graceful-readlink-1.0.1.tgz#4cafad76bc62f02fa039b2f94e9a3dd3a391a725"
  
  jekyll-gen:
    version "1.0.7"
    resolved "https://registry.yarnpkg.com/jekyll-gen/-/jekyll-gen-1.0.7.tgz#ea95ba5bf82f589dcbd54e75ddd89851078360fe"
    dependencies:
      commander "^2.9.0"
      moment "^2.15.2"
  
  moment@^2.15.2:
    version "2.15.2"
    resolved "https://registry.yarnpkg.com/moment/-/moment-2.15.2.tgz#1bfdedf6a6e345f322fe956d5df5bd08a8ce84dc"

Trace: 
  Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\jg.cmd'
      at Error (native)

**Comment by samccone** [comment]
dup #992

**Comment by lgh06** [comment]
worked for me.thx.
