### ISSUE TITLE
--prefer-offline cannot resolve modules in private npm repositories

### ISSUE THREAD

**Issue by zerovox** [yarnpkg/yarn#1482]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
`yarn --prefer-offline` does not use private NPM registry. We only publish scoped modules to our private repository, so I have only tested with scoped modules.

```
[1/4] 🔍  Resolving packages...
error Couldn't find package "@scope-in-private-registry/package-in-private-regsitry" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Set a private repository in a `.npmrc` file, add a private dependency (one that is not resolvable locally) to a `package.json` and run `yarn --prefer-offline`

**What is the expected behavior?**
The module should be resolved correctly.

**Please mention your node.js, yarn and operating system version.**
node 6.7.0, OSX EL Capitan, yarn 0.16.1

**Comment by pyros2097** [comment]
Any progress on this? I have a huge package.json and would like to cache the dependencies for docker.. but it seems my private packages and causing this to fail.

**Comment by danpalmer** [comment]
Any progress? This happens to me for a namespaced but public repository as well.

```
verbose 2.206 Error: Couldn't find package "@kadira/storybook" on the "npm" registry.
    at /usr/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:209:15
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
error Couldn't find package "@kadira/storybook" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by pyros2097** [comment]
Yeah this is not going to get fixed any time soon.

**Comment by bestander** [comment]
`yarn install --prefer-offline` with `@kadira/storybook` in package.json works successfully in 0.25
