### ISSUE TITLE
Yarn publish doesn't work

### ISSUE THREAD

**Issue by VladShcherbin** [yarnpkg/yarn#1494]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn publish asks the release version and then hungs until `ctrl-c`

```
yarn publish v0.16.1
[1/4] Bumping version...
info Current version: 0.2.2
question New version: 0.2.3
info New version: 0.2.3
[2/4] Logging in...
[3/4] Publishing...
^C
```

**Please mention your node.js, yarn and operating system version.**

node 6.7.0
npm 3.10.3
yarn 0.16.1
macOS 10.12

Similar issues [here](https://github.com/yarnpkg/yarn/issues/610), last messages.

**Comment by samccone** [comment]
marking as a dup of #610

**Comment by VladShcherbin** [comment]
@samccone not sure if it's a duplicate as #610 is an **enhancement** while this one is a **bug report** and has higher priority in my opinion.

Anyway, I hope it'll get fixed as currently it's not working at all.

**Comment by w3apps** [comment]
Yarn publish hangs on the [3/4] Publishing... part as well (using a private registry).

**Comment by damonmaria** [comment]
This is different to the complaints about publish hogging 100% cpu and taking a lot of time (#1114). For me (and I gather others above) publish never gets past 3/4. I hooked up the node debugger but when the CPU dies down and I break in there aren't any frames. So no idea what it's up to. I left it overnight and it was still 3/4 in the morning publishing a tiny package.
