### ISSUE TITLE
yarn clean removes a required file

### ISSUE THREAD

**Issue by DenJohX** [yarnpkg/yarn#1501]
**Do you want to request a *feature* or report a *bug*?**
bug, but it could be a feature request

**What is the current behavior?**
When running `yarn clean` a seemingly empty .js file gets removed, but it was a required one.

**If the current behavior is a bug, please provide the steps to reproduce.**
I experienced this in a fresh `react-native` installation. Steps to reproduce:

```bash
$ react-native init someProject
$ cd someProject
$ rm -rf node_modules
$ yarn install
$ yarn clean
$ # then we try to start the react-native development server
$ react-native start
```

it crashes with the error: 
```
Error: Cannot find module './assets/empty-module.js'
```

The problem is with the file `/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/ResolutionRequest.js` which requires `/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/assets/empty-module.js` (an "empty" .js file, as it only contains commented text)

see the required file [here](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/node-haste/DependencyGraph/assets/empty-module.js) 
and the requiring file [here](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/node-haste/DependencyGraph/ResolutionRequest.js)

**What is the expected behavior?**
It should not erase the file, as it was required in another file.

**Please mention your node.js, yarn and operating system version.**
`Debian Testing GNU/Linux` distribution
`yarn 0.16.1`
`node v4.6.0`

**Comment by kittens** [comment]
With #1430 you can customise the default filters in which case you can just remove the `assets` one.
