### ISSUE TITLE
Support npm userconfig / npm_config_userconfig

### ISSUE THREAD

**Issue by timdp** [yarnpkg/yarn#1512]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

`npm_config_userconfig` is ignored.

**What is the expected behavior?**

npm lets you [override the path to `.npmrc`](https://docs.npmjs.com/misc/config#userconfig) through the config API. Yarn provides [other ways](https://github.com/yarnpkg/yarn/blob/5e2fbe6d1d86d2f1420b66c6351f765300ddde79/src/registries/npm-registry.js#L92) of using alternative `.npmrc` paths but not `userconfig`.

**Comment by kittens** [comment]
Created #1519 to fix this, pending approval.

**Comment by jblayneyXpanxion** [comment]
@sebmck does this work via command line in yarn?

Equivalent for npm:

`npm install --userconfig ./.npmrc`
