### ISSUE TITLE
Yarn prune should return exit code of zero

### ISSUE THREAD

**Issue by patcoll** [yarnpkg/yarn#1525]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Output:

```
error The prune command isn't necessary. `yarn install` will prune extraneous packages.
```

Exit code of `1` (one).

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn prune` in a folder with a valid `yarn.lock` file.

**What is the expected behavior?**

I would expect `yarn prune` to do nothing and return a success exit code of `0` (zero).

**Please mention your node.js, yarn and operating system version.**
- Node 6.9.0
- Yarn 0.16.1
- macOS 10.10.5

**Comment by kittens** [comment]
The exit code is correct here, you're executing an invalid command. It's not clear why you'd expect a success exit code?

**Comment by patcoll** [comment]
`npm prune` with nothing to do simply does nothing and returns success. If yarn is truly a drop-in replacement for npm, then my expectation would be that it would exhibit the same behavior.

**Comment by torifat** [comment]
@patcoll `yarn` is not a drop-in replacement.

https://yarnpkg.com/en/docs/migrating-from-npm#cli-commands-comparison-a-classtoc-idtoc-cli-commands-comparison-hreftoc-cli-commands-comparisona

**Comment by kurtbartholomew** [comment]
No movement in the last 2 years. Seems like maintainers have said the exit code is correct.

@kittens or @bestander, is it possible to close this issue or is there still no consensus on if the exit code is correct?

(Just trying to clean up old issues. Thanks.)

**Comment by Gudahtt** [comment]
Thanks @kurtbartholomew

This should be safe to close. As @torifat said, Yarn is not a drop-in replacement nor is it aspiring to be. The non-zero exit code in this case is an intentional deterrent to using this command, which is invalid.

If someone does have a compelling reason for introducing a `prune` command, opening an RFC to discuss it would be encouraged.
