### ISSUE TITLE
Importent: Bug in Current Master

### ISSUE THREAD

**Issue by frank-dspeed** [yarnpkg/yarn#1528]
0.16.2 Current Master
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
```
Error on yarn run 
yarn [ 'run', 'release:patch' ]
module.js:457
    throw err;
    ^

Error: Cannot find module '../lib-legacy/constants'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/frank/.yarn-config/global/node_modules/yarn/bin/yarn.js:9:17)

    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

```
# Whole Section in /bin/yarn.js Invalid there is no lib-legacy who ever has this should push it fast 

var mkdirp = require('mkdirp');
var constants = require('../lib-legacy/constants');
mkdirp.sync(constants.GLOBAL_INSTALL_DIRECTORY);
var roadrunner = require('roadrunner');
roadrunner.load(constants.CACHE_FILENAME);
roadrunner.setup(constants.CACHE_FILENAME);

```

**If the current behavior is a bug, please provide the steps to reproduce.**
simply do yarn run any
**What is the expected behavior?**
running the script
**Please mention your node.js, yarn and operating system version.**

**Comment by Daniel15** [comment]
When running the master version of Yarn, you need to build it yourself (run `npm install` then `npm run build`). We'll have prebuilt nightly releases available very soon! Thank you for trying Yarn! 😄

**Comment by RachelSatoyama** [comment]
`npm run build` fails though. Just wonder why this is not done during install, what's the reasoning behind this?

**Comment by Daniel15** [comment]
> npm run build fails though. 

What's the error?

Also, we have prebuilt nightly releases now - Docs will be added to the website soon.
