### ISSUE TITLE
`yarn why` fails for scoped packages

### ISSUE THREAD

**Issue by JKillian** [yarnpkg/yarn#1529]
**Type**: Bug

**What is the current behavior?**
Running `yarn why @someScope/somePackage` gives back `error We couldn't find a match!` even when the package is installed and depended upon.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `yarn init`
2. `yarn add @types/lodash`
3. `yarn why @types/lodash` or `yarn why "@types/lodash"`

**What is the expected behavior?**
Yarn should be able to provide its normal "why" output. Perhaps it's trying to treat the package name as a path?

**Please mention your node.js, yarn and operating system version.**
Yarn: 0.16.1
OS: OSx

**Comment by kittens** [comment]
Created #1593 to fix this, pending approval.
