### ISSUE TITLE
Replace npm with Yarn for build and deployment commands

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#153]
We still use npm for:
- installing node_modules for CI testing
- building bundle in Makefile
- tagging releases in RELEASING.md

**Comment by lholmquist** [comment]
Also, the instructions in [Contributing.md](https://github.com/yarnpkg/yarn/blob/master/CONTRIBUTING.md#building) still say to use `npm`

**Comment by OmgImAlexis** [comment]
- [ ] [appveyor.yml](https://github.com/yarnpkg/yarn/blob/master/appveyor.yml#L22)
- [ ] [circle.yml](https://github.com/yarnpkg/yarn/blob/master/circle.yml#L52)
- [ ] [build-dist-debug.sh](https://github.com/yarnpkg/yarn/blob/3af60cf9c1df2e70bb688111ce4c88c134e43b19/scripts/build-dist-debug.sh#L9)
- [ ] [check-lockfile.sh](https://github.com/yarnpkg/yarn/blob/0f1db96846badbbe3b43c470c05196eb29437fb4/scripts/check-lockfile.sh#L8)
- [ ] [package.json](https://github.com/yarnpkg/yarn/blob/08974574710ae11499ed1544b3d292cff815963c/package.json#L87)
- [ ] [trim-mirror-test-packages.js](https://github.com/yarnpkg/yarn/blob/0f1db96846badbbe3b43c470c05196eb29437fb4/scripts/trim-mirror-test-packages.js#L27)
- [ ] [This can't really be changed](https://github.com/yarnpkg/yarn/blob/13c8bcae318855b5ce9d72c6357ba0e7c778cbef/src/cli/commands/install.js#L87)

Can't find anything else that still uses npm.
