### ISSUE TITLE
self-update fails due to missing rimraf dependency

### ISSUE THREAD

**Issue by ZebraFlesh** [yarnpkg/yarn#1542]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
`yarn self-update` fails with the following log message:

```
Trace:
  Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\AppData\Roaming\nvm\v4.4.0\node_modules\yarn\node_modules\ri
mraf\rimraf.js'
      at Error (native)
      at Object.fs.openSync (fs.js:549:18)
      at Object.fs.readFileSync (fs.js:397:15)
      at Object.Module._extensions..js (module.js:415:20)
      at Module.load (module.js:343:32)
      at Function.Module._load (module.js:300:12)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\nvm\v4.4.0\node_modules\yarn\lib-legacy\util\fs.js:471:80)
      at Module._compile (module.js:409:26)
```

rimraf is clearly missing from yarn\node_modules; uninstalling and reinstalling the same version of yarn gives me the missing rimraf dependency

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute `yarn self-update` command from a command shell

**What is the expected behavior?**
Yarn updates from 0.16.0 to 0.16.1

**Please mention your node.js, yarn and operating system version.**
node: 4.4.0 (installed via nvm-windows)
npm: 2.14.20
yarn: 0.16.0 (installed via `npm install -g yarn`)
OS: Windows 7 Professional SP1

**Comment by Daniel15** [comment]
This is odd because rimraf is definitely listed in the dependencies: https://github.com/yarnpkg/yarn/blob/master/package.json#L34

**Comment by ZebraFlesh** [comment]
I agree. I'm not sure how it could have been installed without a dependency. The possible choices are: 

1. Something went wrong during installation with that version of npm (which is a less common variant, but is what we currently use in our dev environment -- trying to get to node 6.9 + yarn)
2. My local installation was somehow damaged
3. The initial 0.16.0 package on the npmjs registry was bad and later got updated to the right one

2 is the most likely, but I don't see how it could have it happened. I thought it might be 1, but I couldn't recreate the damaged installation. (My initial theory was that because I had the rimraf package installed globally, npm somehow thought it could satisfy yarn's rimraf dep with a sibling package. But like I said, I couldn't recreate.)

**Comment by wyze** [comment]
The `self-update` command was removed in https://github.com/yarnpkg/yarn/commit/15d011274eabe89a5fe8d5d32a966ba48c92755e so I think this issue is no longer valid.
