### ISSUE TITLE
Will the yarn add refresh the node_modules folder ?

### ISSUE THREAD

**Issue by monkindey** [yarnpkg/yarn#1546]
### **Do you want to request a _feature_ or report a _bug_?**

Maybe **Bug**
### **What is the current behavior?**

yarn add --dev `<someModule>` and lead to my local module(didn't store in yarn.lock) gone
### **If the current behavior is a bug, please provide the steps to reproduce.**
1. create the module folder in **node_modules** (this module didn't install by yarn or npm, just a local module)
2. run the yarn command 

``` javascript
yarn add --dev `<someModule>`
```
### **What is the expected behavior?**

my local module will exist
### **Please mention your node.js, yarn and operating system version.**

**node.js**: 4.5.0
**yarn**: 0.16.1
**system**: MacOSX 10.11.6

Sorry for not yet figure out the add command how to work

Thanks

**Comment by kittens** [comment]
This is correct behaviour, whenever you run a yarn command that modifies or installs the dependency graph we will make sure `node_modules` is up to date so anything you previously had in there that shouldn't have been is removed.
