### ISSUE TITLE
Feature Request: yarn --without-lock-file

### ISSUE THREAD

**Issue by mesaugat** [yarnpkg/yarn#1549]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
There should be an option to not create a `yarn.lock` file when installing the dependencies using `yarn` or `yarn add`. I did not find any option to do so.

I understand the use cases of `yarn.lock` but I think adding this option will do no harm. For instance, we may just want to install the dependencies using yarn for some project that doesn't have a `yarn.lock` and use npm instead.

Something like `yarn --without-lock-file` would be sleek.

**Comment by rockingskier** [comment]
You have two options, [`yarn install --no-lockfile`](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-no-lockfile) and [`yarn install --pure-lockfile`](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-pure-lockfile)

**Comment by mesaugat** [comment]
@rockingskier I didn't check this: `yarn install --help`. Stupid me, thanks.
