### ISSUE TITLE
yarn not installing package correctly in dev dependencies

### ISSUE THREAD

**Issue by laumair** [yarnpkg/yarn#1551]
**bug**

So I have been trying to install this package `redux-immutable-state-invariant` with yarn. 
I am using `yarn add redux-immutable-state-invariant --dev`. So, it correctly installs it in the dev dependencies but the issue is that when I import it in the file it gives me an error that says it can't resolve the path for the package. 

So, looking into the issue myself I figured out that I am getting two different builds when I install it with `yarn` and with `npm` directly. 

Also, be noted that when I install it with `npm` it works fine and doesn't give me a path issue. I am attaching screenshots for both directories in the `node_modules` package after installation. 

**With Yarn**
![screenshot from 2016-10-29 22-40-32](https://cloud.githubusercontent.com/assets/20437468/19831660/25c4816c-9e29-11e6-94cc-5fd76e3a22a0.png)
See, no `dist` directory

**With npm**
![screenshot from 2016-10-29 22-39-08](https://cloud.githubusercontent.com/assets/20437468/19831663/32188de6-9e29-11e6-8bc5-162a02133b44.png)

**Comment by torifat** [comment]
`yarn add redux-immutable-state-invariant --dev` 😕 

<img width="388" alt="screenshot 2016-10-30 12 50 21" src="https://cloud.githubusercontent.com/assets/208544/19834939/6fa74dd4-9e9f-11e6-8f76-1a7223c30d2e.png">

BTW, please try to follow the issue template. It will make life easier for everyone.

**Please mention your node.js, yarn and operating system version.**

**Comment by laumair** [comment]
Ah, sorry about the issue template. I'll be surely strict about that in future. 

I am still having this issue though. 

**node.js version:** 6.9.1
**OS:** ubuntu 16
**yarn:** 0.16.1

Did you try this out on OSX? Because it works fine there for me as well.

**Comment by torifat** [comment]
@laumair yeah, I tried in macOS.

**Comment by laumair** [comment]
@torifat Hmmm. Not sure what the issue is then.

**Comment by torifat** [comment]
I just tried in `Ubuntu 16.04`. And, it's working as expected.

<img width="569" alt="screenshot 2016-10-31 10 44 22" src="https://cloud.githubusercontent.com/assets/208544/19844458/4766baae-9f57-11e6-8e2a-4adc88e7b2d8.png">

Can you `yarn cache clean` and try again?

**Comment by laumair** [comment]
@torifat after cleaning cache it works smooth. Thanks for testing it on your end as well and clearing out the issue. :+1:
