### ISSUE TITLE
Question: Yarn and node version manager

### ISSUE THREAD

**Issue by nitrajka** [yarnpkg/yarn#1566]
Hello,
this is more a question than reporting a bug or requesting a feature.

I would like to install yarn. I'm using OSX El Captain v10.11.5. 
In <a href="https://yarnpkg.com/en/docs/install#mac-tab">the installation tutorial</a> was written: 

> `brew install yarn`
> This will also install Node.js if it is not already installed.

For managing node versions I'm using <a href="https://github.com/tj/n">n -node manager</a>. It does a useful job for me. If I change the node version, it will automatically choose a suitable npm version and change to it.

I wanted to ask, whether yarn is compatible (or will be in the future) with `n` node manager. Or does it have some own node manager? 

Thank you

**Comment by wyze** [comment]
Hi @nitrajka, you can see the discussion about Homebrew here: #1116
