### ISSUE TITLE
Allow to install packages from git monorepos

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#1570]
It would be nice if yarn allowed to install packages from hosted git monorepos.

```
"@cycle/dom": "github:cyclejs/cyclejs/dom#123CH"
```

here: `cyclejs/cyclejs` is github monorepo path, `dom` is package folder inside monorepo, `123CH` is commit hash  (maybe it should be `cyclejs/cyclejs#123CH/dom` if with commit hash)

**Comment by jiripospisil** [comment]
Related https://github.com/yarnpkg/rfcs/issues/15

**Comment by kittens** [comment]
Closing in favor of the RFC @jiripospisil linked.

**Comment by whitecolor** [comment]
@jiripospisil is there an RFC I can not find it, wasn't it implement yet?

**Comment by Budry** [comment]
This would be very useful...Any progress or any next info about this?

**Comment by mattbrunetti** [comment]
This would add a lot of flexibility to how we use monorepos ... (+1) 

@jiripospisil Any idea what happened to that issue? It's disappeared! And I thought Github issues could not be removed :face_with_head_bandage:

**Comment by jiripospisil** [comment]
@whitecolor @mattbrunetti I'm not really sure, I cannot find it either. I think the only way an issue can be removed is either when a GitHub admin deletes it or the user gets banned / blocked.

**Comment by mattbrunetti** [comment]
@kittens Since the RFC is gone should we reopen this?

**Comment by mattwiller** [comment]
@mattbrunetti @kittens This would be useful for us as well; +1 to reopening

**Comment by whitecolor** [comment]
[This things called yalc](https://github.com/whitecolor/yalc) maybe useful who work with multiple self-authored packages in development, it simplifies workflow of package usage in the project before package is properly published, better than `npm link` or installing from git.

**Comment by AlexxNica** [comment]
@whitecolor I think [yall](https://github.com/whitecolor/yall) would be a better call for this problem. Even though I think this should be fixed/added to the package manager itself, this seems like a good workaround for now.

**Comment by whitecolor** [comment]
Well, `yall` is a tool for mainly installing dependencies TO monorepo not FROM) anyway installing from git often doesn't work as now packages require build step, so not sure if the original issue is really actual.

**Comment by juanca** [comment]
This would be ideal for https://github.com/yarnpkg/e2e-test-repo/issues/2

**Comment by nomi9995** [comment]
Try https://gitpkg.now.sh/

```shell
yarn add https://gitpkg.now.sh/<user>/<repo>/<subdir>[?<branch>]
```
OR
```
"@react-native-community/cli-platform-ios":"https://gitpkg.now.sh/nomi9995/cli/packages/platform-ios?fix-ios-getProductName-regex"
```

**Comment by Riki1312** [comment]
This worked well for me:

```
yarn add @name/package-name@https://github.com/user/repo#workspace=@name/package-name
```

**Comment by zbyte64** [comment]
The RFC linked is now missing. I don't know how this got "fixed", are we expected to use an external service like gitpkg?

**Comment by mir3z** [comment]
Any update on this?

**Comment by skyFabioCozz** [comment]
Updates?

**Comment by Pixelik** [comment]
updates?
