### ISSUE TITLE
Manually editing yarn.lock file

### ISSUE THREAD

**Issue by krasimir** [yarnpkg/yarn#1571]
**Do you want to request a *feature* or report a *bug*?**
It's more like a feature.

**What is the current behavior?**
Well, I think the behavior of Yarn is correct. Let's say that I have a dependency A and dependency B. B also has A listed under `dependencies`. However, in my `package.json` file I require 0.6.1 version of A but B has `0.x`. So what happens is that I end up with the following:
```
node_modules
  A (0.6.1)
  B
    node_modules
      A (0.8.2)
```
And B uses 0.8.2, not 0.6.1 which leads to a broken build. 

**If the current behavior is a bug, please provide the steps to reproduce.**
It's not a bug.

**What is the expected behavior?**
It is possible that I go to `yarn.lock` and explicitly say that B depends on `0.6.1` and not `0.x`. That way I'm getting proper versions and the build is successful. However, I know that I shouldn't be modifying `yarn.lock` on my own. Dependencies A and B are not in my control. For sure I can file an issue there but what if the maintainer don't want to update that `0.x`.

My questions are:
* In which cases I'm getting `yarn.lock` file updated and when Yarn will bring that `0.x` again into `yarn.lock` file? Is that a process that runs when I run `yarn add`? The so called `linking dependencies` maybe?
* Is there any way to **really** lock a dependency and say no matter what this is the dependencies that you'll use.

**Please mention your node.js, yarn and operating system version.**
Node: v6.7.0
Yarn: 0.16.1
OS X 10.11.5

**Comment by kittens** [comment]
As the header in `yarn.lock` says you shouldn't be modifying it at all as we rely on all the data structures being in tact and it's really easy to break Yarn if you start messing with it and don't properly link it up.

To answer your questions:

> * In which cases I'm getting yarn.lock file updated and when Yarn will bring that 0.x again into yarn.lock file? Is that a process that runs when I run yarn add? The so called linking dependencies maybe?

We'll update the lockfile when we're adding or removing dependencies. Whenever something's in `package.json` that we don't have in `yarn.lock` we regenerate it.

> * Is there any way to really lock a dependency and say no matter what this is the dependencies that you'll use.

Not really, you can't modify these constraints and add replacements. I've previously discussed with @wycats on adding replacements (ala Cargo) but we'll need to flesh them out more before we even start implementing it.

**Comment by krasimir** [comment]
Thanks for the answer @kittens.
