### ISSUE TITLE
[install] don't write lockfile when yarn.lock is the source of truth

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#1576]
**Do you want to request a *feature* or report a *bug*?**

Bug/feature fix

**What is the current behavior?**

yarn.lock is overwritten on every `yarn install` unless `--pure-lockfile` option is used.
I think it is unnecessary to write yarn.lock if there are no substantial changes to be made.

**What is the expected behavior?**

From #570 by @wycats:

> To be more precise, the expected semantics, in my opinion, are:
> 
> - if package.json has not changed since the last time yarn.lock changed, yarn.lock is the source of truth and should not be updated.
> - if package.json has changed since the last time, yarn.lock changed, update yarn.lock so it satisfies package.json and update node_modules.
> - if yarn update is run, re-resolve all dependencies and get the latest version of everything that satisfies the package.json.

> This means that when a repository is first cloned on a machine, if the yarn.lock was checked in, yarn should always treat it as the source of truth, not generate updates to the yarn.lock, and jump directly to the fetch step.

**Please mention your node.js, yarn and operating system version.**
yarn 0.16.0

**Comment by bestander** [comment]
@kittens as for #364, I reviewed the PR and thanks for getting it up quick because without that option we would not be able to proceed with updating Yarn internally at all.

However `--pure-lockfile` should be redundant for situations when you are sure that lockfile is the source of truth.

**Comment by kittens** [comment]
> yarn.lock is overwritten on every `yarn install`

This isn't the current behaviour at all, we follow those heuristics. Have you tried this on `master`? These are the steps I'm following to attempt to reproduce:

```sh
$ mkdir temp
$ cd temp
$ yarn init --yes
$ yarn add lodash
$ echo "# retain comment" >yarn.lock
$ yarn install --force
$ cat yarn.lock | grep "retain"
```

**Comment by mattslocum** [comment]
I'm experiencing the same problem. 
`yarn install` changes the yarn.lock file unless I add --pure-lockfile

```
$ yarn --version
0.16.1
```

**Comment by mmun** [comment]
I'm seeing this behaviour too. I believe it is related to the second bug @wycats listed at the bottom of https://github.com/yarnpkg/yarn/issues/570#issuecomment-257190341. E.g.
```bash
$ mkdir temp
$ cd temp
$ yarn init --yes
$ yarn add https://github.com/lodash/lodash.git
yarn add v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency
└─ lodash@4.16.7-pre
✨  Done in 13.16s.
$ rm -rf node_modules
$ yarn install
yarn install v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.       <--------------   Should this be happening?
✨  Done in 1.65s.
```

**Comment by domoritz** [comment]
This issues still seems to be present in verision 0.17.4.

<img width="565" alt="screen shot 2016-11-17 at 17 10 51" src="https://cloud.githubusercontent.com/assets/589034/20409771/de8bcf0c-ace8-11e6-86ef-78ac51bb2c72.png">

**Comment by bestander** [comment]
@domoritz, could you open a new issue with a gist of steps to reproduce?

**Comment by robations** [comment]
Sorry about issue-necromancy, but I've seen this problem when working with different versions of yarn. Build server had got stuck on 0.24.5, developer copies (generating lock file) were 0.27.x. Every time running `yarn install` on the server it modified the lock file.

**Comment by bestander** [comment]
@robations, yeah, we had this bug between 0.24 - 0.27.
Does it work for you now with 0.27.5?

**Comment by robations** [comment]
Yes yes, seems like I don't have the issue with 0.27.5 (unless the cause is more complicated). I got lost in the trail of related issues/PRs and wasn't aware this was officially fixed, so that's good news :)

**Comment by cpxPratik** [comment]
I am on yarn version 0.27.5. When doing `yarn install` on a 3 weeks old project (which already has yarn.lock but generated with old version of yarn, i  updated yarn this week), it installs dependencies but there is rather large git diff with the lock file, which i expect would not be changed. Hope it is rare case. Or `yarn install` changes lock file, is it norm?

**Comment by cpxPratik** [comment]
@robations 

> On the other hand, I think I saw this bug several times in the past but I just assumed someone had installed a package using npm meaning the lock file got out of date.

You mean if `node_modules ` contains new versions of dependencies than the lock file (after doing `npm install`), `yarn install` updates lock file based on dependencies  on node_modules?

**Comment by robations** [comment]
@cpxPratik More like this:

```
// package.json says:
xyz-dep: ^2.5.1

// yarn.lock says:
xyz-dep: 2.4.3
```

`yarn.lock` is not compatible with the spec for `xyz-dep` in `package.json`, so instead it installs the best version to match `package.json` and writes a new `yarn.lock`.

The most common ways I've found this to happen are:

- using npm instead of yarn to install/uninstall a dependency
- editing package.json (e.g. delete unwanted package) and committing the result without running install/upgrade (actually had this happen today).

I'm going to start using the option `--frozen-lockfile` in build scripts to highlight when there is a problem with this.
