### ISSUE TITLE
[Question] Official Docker image Yarn+Nodejs

### ISSUE THREAD

**Issue by ericrange** [yarnpkg/yarn#1577]
Hey,

is there an official supported docker image with yarn and nodejs preinstalled that i can use for CI?

**Comment by goenning** [comment]
Not official, but I found this one https://hub.docker.com/r/kkarczmarczyk/node-yarn/

Anyway, it's pretty easy to setup one if you need a specific node version.

```Dockerfile
FROM node:6.9.1
RUN npm install -g yarn

...
```

**Comment by Daniel15** [comment]
Note that installing Yarn through npm (as @goenning suggested above) requires you to have npm installed. If you use a minimal Docker container as a base, you may only have Node.js installed, not npm (particularly if you're using Debian or Ubuntu, as npm is packaged separately to Node.js). In those cases, the Debian repo should work 😄

**Comment by goenning** [comment]
Oh, that's new to me. I thought that all Node.js packages came with NPM. 👍

**Comment by Daniel15** [comment]
Now available as `yarnpkg/node-yarn` in the Docker Hub: https://hub.docker.com/r/yarnpkg/node-yarn/

```
C:\src\yarn> docker run -it --rm yarnpkg/node-yarn:latest /bin/bash
root@13ead647da12:/# yarn --version
0.20.3
```

**Comment by Daniel15** [comment]
I discontinued it as Node.js now include Yarn in their official images.

**Comment by OliverJAsh** [comment]
Oh wow, I had no idea! Thanks @Daniel15
