### ISSUE TITLE
500 InternalError when trying to install clean

### ISSUE THREAD

**Issue by smitt04** [yarnpkg/yarn#1594]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to run yarn on a new system without cache i get a 500 server error for some packages.

```
yarn install v0.16.1
warning stats@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://registry.yarnpkg.com/co/-/co-4.6.0.tgz /home/ksmithson/.yarn-cache/.tmp/69cad75c35bdb7bf53ed23b89c3051bd
Directory: /srv/stats/stats/current
Output:
Cloning into '/home/ksmithson/.yarn-cache/.tmp/69cad75c35bdb7bf53ed23b89c3051bd'...
fatal: unable to access 'https://registry.yarnpkg.com/co/-/co-4.6.0.tgz/': The requested URL returned error: 500
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Going to the `co` url also results in a 500 https://registry.yarnpkg.com/co/-/co-4.6.0.tgz/

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run `yarn` on a clean system

**What is the expected behavior?**
To install successfully

**Please mention your node.js, yarn and operating system version.**
node: 6.9.1
yarn: 0.16.1
centos 6.8

**Comment by joshthecoder** [comment]
Looks like the "/" at the end of the URL is causing the 500. If you drop that the request goes through just fine.

I'm seeing the same issue for "cheerio" package.

**Comment by timoxley** [comment]
Anyone encountering this issue, `yarn` seems to work correctly once there's something in the cache so a workaround is to just add something globally first e.g.

```
yarn global add co
yarn
```

**Comment by timoxley** [comment]
I couldn't create a minimal repro for this, simply running `yarn cache clean` then running `yarn` on a package with something in `"dependencies"` (with or without a `yarn.lock`) doesn't trigger the bug.

**Comment by terribleplan** [comment]
I ran into this moments ago after upgrading to the most recent version. Removing the `yarn.lock` file seems to work, though is less than ideal considering that maintaining locked versions is the primary value proposition of yarn.

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
