### ISSUE TITLE
Windows: Can't install global package; error log included

### ISSUE THREAD

**Issue by dheerajbhaskar** [yarnpkg/yarn#1600]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
1. do yarn global add angular-cli
2. `ng` installs successfully but is not available on PATH

**If the current behavior is a bug, please provide the steps to reproduce.**
1. do yarn global add angular-cli
2. `ng` installs successfully but is not available on PATH

**What is the expected behavior?**
you should be able to run `ng` in the current `cmd` after installation or in a new `cmd` instance

**Please mention your node.js, yarn and operating system version.**
C:\my-home\WebStormProjects\ng-test>node --version
v6.4.0
C:\my-home\WebStormProjects\ng-test>yarn --version
0.16.1

Windows version:
![Screenshot of  winver](https://cloud.githubusercontent.com/assets/2944909/19900513/c7f2d788-a089-11e6-95df-d810c0c19b52.png)

Yarn Error log:
https://gist.github.com/dheerajbhaskar/d41589b8d74dd2b817b8e5f0ddb3bf37

Possible issues:
- Permission issues (based on cursory look at the error log)
  - I installed yarn for current user using the windows installer (not via npm, if that's even possible), could this be an issue?

**Comment by ArthurMauricioDelgadillo** [comment]
Same problem here...

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/yarnpkg/yarn/issues/859

**Comment by voxsim** [comment]
@bestander we can close this because it is a duplicate
