### ISSUE TITLE
Yarn populates 'version' field with blank in lock file without inferring; breaks unless manually entered

### ISSUE THREAD

**Issue by brokenalarms** [yarnpkg/yarn#1602]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Installing some packages with missing version in package.json causes a breaking error requiring manual intervention (even if the version is missing from the original, these are some major packages like d3, and this works somehow in npm).

**If the current behavior is a bug, please provide the steps to reproduce.**
Add dependency d3@~3.5.6 or lodash@~3.10.0 (or others without version in package.json). 
Package json reads: 

```
dependencies: {
  "d3": "3.5.17",
  "lodash": "^3.10.1"
}
```

lock file then has:

```
d3@~3.5.6:
  version ""
  resolved "https://github.com/mbostock-bower/d3-bower.git#7a826d211d5067867debf9ce24a9987e0cb02b6e"
  registry bower

lodash@~3.10.0:
  version ""
  resolved "https://github.com/lodash/lodash.git#dfbd78f71de0550068fc82ce6e013d443e5037d7"
  registry bower
```

Both will then cause any future `yarn` operation to say: 

```
error Package "lodash@" doesn't have a "version".
```

...but this works on npm so I guess it infers it somehow?

You can temporarily manually correct it by just filling in the correct version, but then any subsequent run of `yarn` or `yarn install` overwrite this fix, so it's blocking use atm.

**What is the expected behavior?**
Package continues to work or infers version from that supplied, as works fine with the same package.json with npm.
**Please mention your node.js, yarn and operating system version.**
Node - 6.9
Yarn - 0.16.1
OS - MacOS 10.12.1

**Comment by kittens** [comment]
We've removed Bower support so this should be fixed in `master`.

**Comment by DrSensor** [comment]
I have the same problem when adding from Github repos that don't have version in package.json

Node - 8.9.3
Yarn - 1.2.1
OS - Ubuntu 16.04.3
