### ISSUE TITLE
An Unexpected error occured while processing yarn install [Appveyor, Windows]

### ISSUE THREAD

**Issue by pumano** [yarnpkg/yarn#1604]
0.16.1

**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

An unexpected error occured while processing yarn install under windows appveyor VM
**If the current behavior is a bug, please provide the steps to reproduce.**
```
npm install yarn
./node_modules/.bin/yarn install
```
**What is the expected behavior?**

all packages should be installed properly without errors (as works proper as in linux travis ci environment)

**Please mention your node.js, yarn and operating system version.**

**node.js** : error under 4.0 to 6.1 (check link to appveyor: https://ci.appveyor.com/project/pumano/test-storage/build/80)
**yarn**: 0.16.1
Also I mark appveyor for caching node_modules (maybe it can cause some issues)
detailed installation log: https://ci.appveyor.com/project/pumano/test-storage/build/80/job/pugb2vnwq0areoid

So I can't to get that error log file from appveyor, but problem can be reproduced

**Comment by pumano** [comment]
I try that with Windows 10 and got error:  
```
ENOENT: no such file or directory, open 'C:\Repository\test-storage\node_modules\@types\node\index.d.ts'
      at Error (native)
```


[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/565169/yarn-error.log.txt)

**Comment by pumano** [comment]
It was reproduced by Appveyor team member with different types of installing (without cache):

1) with global yarn install
2) with local ./node_modules/.bin/yarn install

https://ci.appveyor.com/project/FeodorFitsner/test-storage/history

looks like it caused by https://github.com/yarnpkg/yarn/issues/1606 issue

**Comment by Daniel15** [comment]
Please use Chocolatey to install Yarn on AppVeyor, rather than npm. For example:
```
install:
  - ps: Install-Product node $env:node_version
  - choco install -i yarn
```

This might resolve your issue.

**Comment by Daniel15** [comment]
Yarn is now preinstalled on AppVeyor and I haven't seen this issue occur with the preinstalled version, so I'm going to close this issue.  Remove "npm install yarn" from your AppVeyor script and it should work fine :)

**Comment by pumano** [comment]
only yarn install:
https://ci.appveyor.com/project/FeodorFitsner/test-storage/build/2

but it caused by https://github.com/yarnpkg/yarn/issues/1606 issue
