### ISSUE TITLE
yarn gets stuck on `Fetching packages`

### ISSUE THREAD

**Issue by jmlopez-rod** [yarnpkg/yarn#1605]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

yarn keeps getting stuck on Fetching packages

**If the current behavior is a bug, please provide the steps to reproduce.**

Try the following package.json file:

```
{
  "name": "yarnTest",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
		"ts-publish": "https://github.com/iOffice/ts-publish.git#9fce0573c3388ea7b376cdf9779efc50c6eaa58f"
  },
  "resolutions": {
    "once": "1.4.0",
    "readable-stream": "2.1.5",
    "assert-plus": "0.2.0"
  }
}
```

![screen shot 2016-11-01 at 5 49 14 pm](https://cloud.githubusercontent.com/assets/1810397/19910553/bf549266-a05b-11e6-90b2-be1128c5873f.png)

Somehow if I stop the process with control + c and try again, many many times it somehow does it but I can never tell when it will do it. Is there any way to know what is happening?

**What is the expected behavior?**

![screen shot 2016-11-01 at 5 57 55 pm](https://cloud.githubusercontent.com/assets/1810397/19910706/c5b6c380-a05c-11e6-828b-888f7110964b.png)

The above screenshot shows the state in which it gets stuck and it also shows that I had to cancel a lot. If I try this with `npm` it works on the first attempt. 

**Please mention your node.js, yarn and operating system version.**

```
jmlopez in ~/yarnTest$ node --version
v6.0.0
jmlopez in ~/yarnTest$ yarn --version
0.16.1
jmlopez in ~/yarnTest$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12 (16A323)
      Kernel Version: Darwin 16.0.0
```

**Comment by AaronW** [comment]
I'm unable to install that package.json using either NPM@4 or Yarn@0.16.1 on Windows 7.

Yarn install attempt floods my console with "ts-publish" steps but doesn't succeed.

`? ts-publish@https://github.com/iOffice/ts-publish.git#9fce0573c3388ea7b376cdf97`

NPM throws an error adding the remote Git origin url.

> c:\Users\username\Downloads\yarn_test>npm install
> npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
> -get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
> npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:1
> 1)
> npm WARN addRemoteGit     at emitOne (events.js:96:13)
> npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
> npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:493:12)
> npm WARN addRemoteGit  git+https://github.com/iOffice/ts-publish.git#9fce0573c33
> 88ea7b376cdf9779efc50c6eaa58f resetting remote C:\Users\username\AppData\Roami
> ng\npm-cache\_git-remotes\git-https-github-com-iOffice-ts-publish-git-9fce0573c3
> 388ea7b376cdf9779efc50c6eaa58f-380f7e82 because of error: { Error: Command faile
> d: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
> npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:1
> 1)
> npm WARN addRemoteGit     at emitOne (events.js:96:13)
> npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
> npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:493:12)
> npm WARN addRemoteGit   killed: false,
> npm WARN addRemoteGit   code: 1,
> npm WARN addRemoteGit   signal: null,
> npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
> gin.url' }
> Terminate batch job (Y/N)? y

```
Windows 7 Enterprise SP1
Node 6.5.0
NPM 4.0.0
yarn 0.16.1
```

**Comment by torifat** [comment]
It's working fine for me. Give it some time to finish.

**Comment by jmlopez-rod** [comment]
@torifat I just found something interesting. I changed the commit hash several times and it worked flawlessly. So here are the steps I have tried right now:

- I made new commits in master
- updated the commit hash in package.json
- tried yarn
- it was a success

I changed the commit hash several times and yarn had no problems updating the package.

Now here is the interesting bit:

- Switch to the `pre-release` branch: `git checkout pre-release`.
- `git fetch --prune`
- `git reset --hard origin/master`
- Create a commit
- push it
- set the package.json to the latest commit in the `pre-release` branch
- yarn gets stuck

Is this related to the fact that I'm modifying the pre-release branch to mirror the contents of master and yarn gets stuck at this step?

**Comment by torifat** [comment]
What you mean by `yarn gets stuck`? How long did you wait before `Ctrl+C`?

**Comment by jmlopez-rod** [comment]
See the following screen shot

<img width="602" alt="screen shot 2016-11-03 at 3 20 26 pm" src="https://cloud.githubusercontent.com/assets/1810397/19983760/48456b12-a1d9-11e6-8027-a3761f70e9cd.png">

It has been at least 3 minutes since I gave the last command and nothing is happening yet.

**Comment by jmlopez-rod** [comment]
Can you try with this hash: 66c3682d1d3c609b6dc57f62f9b8d6fb03447c50 since it is still not working for me here.

**Comment by torifat** [comment]
<img width="256" alt="screenshot 2016-11-04 02 27 22" src="https://cloud.githubusercontent.com/assets/208544/19983928/3ba2ce24-a236-11e6-873b-abf19ca7cc2a.png">

**Comment by jmlopez-rod** [comment]
🤕 What is going on? Is it my git version?

```
jmlopez in ~/yarnTest$ git --version
git version 2.8.1
```

Which one do you have?

**Comment by torifat** [comment]
`git version 2.10.2`

**Comment by jmlopez-rod** [comment]
ok, I'm going to try updating git and see if anything changes

**Comment by jmlopez-rod** [comment]
The problem I'm having may be due to the way in which I was making the git commit, in particular, I was modifying the history in the branch:

```
git fetch --prune
git reset --hard origin/master
```

I changed the build phase to be roughly like [leaflets](https://github.com/Leaflet/Leaflet/blob/master/build/publish.sh) and it now works.
