### ISSUE TITLE
yarn not resolve POSIX path for postinstall, test and other commands in Windows

### ISSUE THREAD

**Issue by pumano** [yarnpkg/yarn#1606]
0.16.1
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

POSIX path not resolved properly on Windows when preinstall or test or another command contains POSIX path. 
Example: 
```
./node_modules/.bin/mocha ./test/ --recursive --check-leaks
```
can't be resolved properly and executed on Windows environment as NPM can do.

**If the current behavior is a bug, please provide the steps to reproduce.**

use POSIX path for mocha run tests as provided previously

**What is the expected behavior?**

POSIX path from postinstall, test, preinstall and other commands should be resolved properly for executing on Windows

**Please mention your node.js, yarn and operating system version.**
nodejs: 4.4.5
yarn: 0.16.1
OS: Windows 10

![yarn](https://cloud.githubusercontent.com/assets/17675259/19911659/ef013e20-a0a5-11e6-963a-410f4589a478.jpg)

**Comment by DavidBadura** [comment]
Colleagues of mine have the same problem with windows

```
C:\xampp\htdocs\x>yarn start
yarn start v0.16.1
$ ./node_modules/.bin/gulp watch
Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed with exit code 1.
```

Nodejs: 6.9.1
yarn: 0.16.1
OS: Windows 7

under Linux (Ubuntu) and MacOS works fine!

**Comment by DavidBadura** [comment]
my workaround https://github.com/yarnpkg/yarn/issues/1657#issuecomment-258315617

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
