### ISSUE TITLE
yarn looks for wrong package when yarn and npm's registry configs differ

### ISSUE THREAD

**Issue by nam-kim** [yarnpkg/yarn#1612]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Occurs when yarn's registry config is set to a private address and npm's is registry.npmjs.org
When a private package sharing names with a package on registry.npmjs.org is a dependency, yarn tries to fetch the public package.

**If the current behavior is a bug, please provide the steps to reproduce.**
- yarn directed to private registry using `yarn config set registry`
- `yarn install` with dependency 'omelet' in package.json

Yarn returns an error
```
error Couldn't find any versions for omelet that matches 1.0.34. Possible versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7
```

ditto for private package named 'nose'
```
error Couldn't find any versions for nose that matches 0.1.6. Possible versions: 0.1.0
```

Installation succeeds when the package versions are set to what yarn suggests, but with the wrong (public) packages.

**What is the expected behavior?**
Installation works fine when both yarn and npm's registry configs are set to the private address. Unless this behaviour is intentional I'm assuming yarn should only look at its own registry config.

**Please mention your node.js, yarn and operating system version.**
yarn 0.16.1
nodejs 6.4.0
Win 10 x64

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where we only read a single config - `.yarnrc.yml`.

https://yarnpkg.com/getting-started/migration
