### ISSUE TITLE
postman-collection fails to install

### ISSUE THREAD

**Issue by DaleJefferson** [yarnpkg/yarn#1614]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Attempting to install postman-collection results in an error

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn add --dev postman-collection

// Trace: 
//  Error: ENOENT: no such file or directory, scandir '/Users/dale/.yarn-cache/npm-postman-collection-0.5.5/bin'
//     at Error (native)
```

**What is the expected behavior?**
```
npm install --save-dev postman-collection
// No error
```

**Please mention your node.js, yarn and operating system version.**
```
yarn --version // 0.16.1
node --version // v6.9.1
npm --version // 3.10.8
OS // MacOS 10.11.6
```

**Comment by rodrigogs** [comment]
+1

**Comment by KidkArolis** [comment]
Tried reproducing, but it installs fine for me. @DaleJefferson can you try again with `yarn@latest`?

```
yarn 0.17.6
node v6.9.1
MacOS 10.12.1
```

**Comment by rodrigogs** [comment]
Still not working for me

>yarn add --dev postman-collection

````
yarn 0.17.6
node 7.1.0
Windows 10
```


[Error log](http://pastebin.com/Qus2ykvF)

**Comment by torifat** [comment]
@rodrigogs Can you please try again after a `yarn cache clean`?

**Comment by rodrigogs** [comment]
@torifat Same error

**Comment by torifat** [comment]
@rodrigogs Thanks for the confirmation.

**Comment by DaleJefferson** [comment]
I can confirm that Yarn 0.18.0 fixes this issue.

```
npm install -g yarn@0.18.0

yarn add --dev postman-collection
```

I believe this is the PR that fixes this https://github.com/yarnpkg/yarn/pull/1663

**Comment by DaleJefferson** [comment]
I will close this issue since it will be fixed in the next release and is a duplicate of #1614
