### ISSUE TITLE
Add -v shorthand for --version flag

### ISSUE THREAD

**Issue by strarsis** [yarnpkg/yarn#1621]
**Do you want to request a *feature* or report a *bug*?**
Request a feature. 
This would improve consistency as node and npm both accept -v shorthand for --version flag.
**What is the current behavior?**
````
error: unknown option `-v'
````
**If the current behavior is a bug, please provide the steps to reproduce.**
````
$ yarn -v
````
**What is the expected behavior?**
Show yarn vresion as with --version switch:
````
0.16.1
````
**Please mention your node.js, yarn and operating system version.**
node: v6.7.0
yarn: 0.16.1

**Comment by niteshsarode** [comment]
shorthand -v is given for 'info' :(

**Comment by kittens** [comment]
We have `yarn -V`. The `-v` flag is often used to mean verbose so I don't think it's a good idea to have this shorthand given it's ambiguity.
