### ISSUE TITLE
The yarn.lock file should be placed into node_modules

### ISSUE THREAD

**Issue by cnyyk** [yarnpkg/yarn#1633]
The `yarn.lock` file should be placed into node_modules.
Or SourceTree or WebStorm will prompt to add it to cvs.
And I metioned a `.yarn-integrity` file existed in node_modules, and place the `yarn.lock` into it should be also OK?

**Comment by maybeec** [comment]
Why not committing yarn.lock file? Basically, this will assure to have a deterministic and reproducable build. I am aware of the bad thing, that yarn.lock also stores URLs, which I would like to see parameterized over any env variable.
However, this is the only way to be totally sure, that the build will run on any machine with the same result.

**Comment by ljharb** [comment]
@cnyyk `node_modules` is typically gitignored. Project config files, like a lock file, are typically at the root of a repo. `yarn.lock` should be committed, that's the whole point.

**Comment by kittens** [comment]
You're supposed to commit `yarn.lock`. See #1067 for more discussion on this.

**Comment by cnyyk** [comment]
Got. Thanks so much.
