### ISSUE TITLE
Cache folder in home folder is getting backed up on macOS

### ISSUE THREAD

**Issue by pornel** [yarnpkg/yarn#1637]
Feature request

**What is the current behavior?**

yarn creates `~/.yarn-cache/` folder, which is getting backed up automatically by macOS's Time Machine, which unnecessarily bloats the backups.

**What is the expected behavior?**

Yarn could use `~/Library/Caches/…` to store its cache. This is the usual location for caches on macOS, and the system avoids unnecessarily backing it up.

**Please mention your node.js, yarn and operating system version.**

 yarn 0.16.1, node v6.9.0, macOS 10.11.6

**Comment by kittens** [comment]
Created #1638 to fix this, pending approval.

**Comment by pornel** [comment]
Thank you!
