### ISSUE TITLE
yarn install --pure-lockfile fails without package.json (or bower.json)

### ISSUE THREAD

**Issue by hontas** [yarnpkg/yarn#1639]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
running `yarn install --pure-lockfile` fails with `error Couldn't find a package.json (or bower.json) file in [path]` when there is no package.json (or bower.json)

**What is the expected behavior?**
running `yarn install --pure-lockfile` should install dependencies mentioned in `yarn.lock` and not bother with package.json (or bower.json).

**Please mention your node.js, yarn and operating system version.**
Node 6.2.0, yarn 0.16.1 and Mac OSX 10.10.5

**Comment by kittens** [comment]
We can't do this since `yarn.lock` needs to have a corresponding manifest. We seed the package resolver with the patterns in `package.json`. This is necessary as there are different dependency types and `yarn.lock` is flat so it's impossible to distinguish the entry points.
