### ISSUE TITLE
`yarn outdated` can't find @types modules (Typescript .d.ts files)

### ISSUE THREAD

**Issue by DogPawHat** [yarnpkg/yarn#1640]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When running `yarn outdated`, it returns a couldn't find error if you have any of the TypeScript @types type definition modules installed e.g `couldn't find @types/react-redux`
**If the current behavior is a bug, please provide the steps to reproduce.**
In an empty directory:
```
yarn init
yarn add @types/react //or any type definition module
yarn outdated
```
**What is the expected behavior?**
Print out a list of outdated modules, including those belonging to @types
**Please mention your node.js, yarn and operating system version.**
Node: v6.9.1
Yarn: v0.16.1
OS: Windows 10 Enterprise v1607 build 14393.351

[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/568690/yarn-error.log.txt)

**Comment by kittens** [comment]
Fixed by #1276.
