### ISSUE TITLE
Yarn panics when there's a network error

### ISSUE THREAD

**Issue by dortamur** [yarnpkg/yarn#1645]
When running Yarn, I got this ominous message:

```
error An unexpected error occured, please open a bug report with the information provided in "/home/tphillips/Projects/Web/Wishlists/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Upon checking the mentioned log file, I saw the error was:

```
Trace:
  Error: connect ENETUNREACH 104.16.59.173:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

Sure enough, I couldn't route to the IP listed - the problem was networking related, and not really a Yarn bug.

Wouldn't it be better to recognise ENETUNREACH and print a more appropriate error message along the lines of "Hey! There's a net connection problem! Try again later."

Node.js version is v6.9.1
Yarn version is 0.16.0
OS is Debian 8.6
Internet provider is unreliable

**Comment by jakehm** [comment]
Same issue when running `yard add --dev babel-preset-latest` 
Entered the same command again, and it worked.

`Trace:
  Error: connect ENETUNREACH 2400:cb00:2048:1::6810:3dad:443 - Local (:::0)
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at connect (net.js:879:16)
      at net.js:1008:7
      at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
`

**Comment by sidgujrathi** [comment]
Just try with running commands as root  `sudo yarn install` or `yarn add --dev `. This solution have solved my problem.

**Comment by felixsanz** [comment]
Yarn have a lot of problems with the network in the registry, some of my pipelines fails just because of this :/

error An unexpected error occurred: "https://registry.yarnpkg.com/koa-bodyparser/-/koa-bodyparser-3.2.0.tgz: connect ENETUNREACH 2400:cb00:2048:1::6810:3dad:443 - Local (:::0)".

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.

**Comment by surattana-cs22** [comment]
@olingern Still get the error when the command run on Team City linux agent 
![image](https://user-images.githubusercontent.com/65814817/82730501-69f3e400-9d2a-11ea-8629-cecaff5102a7.png)

**Comment by surattana-cs22** [comment]
@olingern We've solved this problem by passing proxy settings to the container, thank you so much for looking into this.
