### ISSUE TITLE
Support downloading packages from arbitrary URLs

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#1646]
**Do you want to request a *feature* or report a *bug*?**
Request feature

**What is the current behavior?**
You can't cownload arbitrary js files and store them appropriately.

**What is the expected behavior?**
I'd like to be able to take a URL like "https://example.com/path/to/random/jsfile.js" and put the content into `node_modules/some-module-name/index.js`

I currently use a tiny little bower.json to download just those external packages:

```json
{
  "name": "abc",
  "version": "1.0.0",
  "description": "xyz",
  "dependencies": {
    "some-module-name":"https://example.com/path/to/random/jsfile.js"
  }
}
```

**Please mention your node.js, yarn and operating system version.**

**Comment by kittens** [comment]
Please use [yarnpkg/rfcs](https://github.com/yarnpkg/rfcs) for substantial feature requests.

**Comment by graingert** [comment]
@kittens ah woops, thanks for pointing that out.

**Comment by graingert** [comment]
@kittens here's a PR to stop this mistake happening: https://github.com/yarnpkg/yarn/pull/1650
