### ISSUE TITLE
Installation Problem: chocolatey error messages unclear

### ISSUE THREAD

**Issue by innerspirit** [yarnpkg/yarn#1647]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The chocolatey installer's error message is not helpful in solving installation problems.

**If the current behavior is a bug, please provide the steps to reproduce.**
I type `choco install yarn` in an elevated shell, and get an error. **_Turns out I already had yarn installed, but the error did not tell me this, I just realized it later._**

**What is the expected behavior?**
It should warn you that yarn is already installed, or overwrite the previous version.

**Please mention your node.js, yarn and operating system version.**
Node.js v7, yarn latest version, OS is Windows 10 Pro.

**Error message**
```
 Hashes match.
 Installing yarn...
 [ERROR] Running msiexec with /i "C:\Users\CHRIST~1\AppData\Local\Temp\chocolatey\yarn\0.16.0\yarnInstall.msi" /qn /norestart
 /l*v "C:\Users\CHRIST~1\AppData\Local\Temp\chocolatey\yarn\yarn.MsiInstall.log"  was not successful. Exit code was '1603' Error
 Message:
 .
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:92 char:5
 +     throw $errorMessage
 +     ~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: ([ERROR] Running...or Message: .:String) [], RuntimeException
     + FullyQualifiedErrorId : [ERROR] Running msiexec with /i "C:\Users\CHRIST~1\AppData\Local\Temp\chocolatey\yarn\0.16.0\yarnInstall.msi" /qn /norestart /l*v "C:\Users\CHRIST~1\AppData\Local\Temp\chocolatey\yarn\yarn.MsiInstall.log"  was not successful. Exit code was '1603' Error Message:
 .
The install of yarn was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\yarn\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - yarn
```

**Comment by Daniel15** [comment]
1603 simply means there was a fatal error during installation, it doesn't give us much info :( Maybe there's a different flag we could provide to msiexec that would help here. 

> Turns out I already had yarn installed

The same version, or a different version? Installing a newer version should upgrade the older one.

**Comment by innerspirit** [comment]
I installed 0.16.0 by downloading the MSI manually a month ago, and today I tried the chocolatey installer (forgot I already had yarn). I think that also has 0.16.0.

**Comment by Daniel15** [comment]
@innerspirit  - Could you please provide the contents of the log file (`%TEMP%\chocolatey\yarn\yarn.MsiInstall.log`)?

**Comment by innerspirit** [comment]
Here you go: http://wikisend.com/download/650480/yarn.MsiInstall.log

**Comment by Daniel15** [comment]
It's likely this installation failed because you already had the same version installed. I'm not quite sure how to handle that, as technically it *is* an installation error. I suspect the same thing would happen for any other software that installs an MSI via Chocolatey.

**Comment by ostadsaleh** [comment]
C:\WINDOWS\system32>choco install nodejs-lts -y
Chocolatey v0.10.11
Installing the following packages:
nodejs-lts
By installing you accept licenses for the packages.
Progress: Downloading nodejs-lts 10.13.0... 100%

nodejs-lts v10.13.0 [Approved]
nodejs-lts package files install completed. Performing other installation steps.
Installing 64 bit version
Installing nodejs-lts...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\nodejs-lts_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\nodejs-lts\tools\node-v10.13.0-x64.msi" /qn /norestart /l*v "C:\Users\ostadsaleh\AppData\Local\Temp\chocolatey\nodejs-lts.10.13.0.MsiInstall.log" ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\nodejs-lts_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of nodejs-lts was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\nodejs-lts\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - nodejs-lts (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\nodejs-lts\tools\chocolateyinstall.ps1'.
 See log for details.


can anyone help me please?

**Comment by ostadsaleh** [comment]
3109 verbose unlock done using C:\Users\user\AppData\Roaming\npm-cache\_locks\staging-59ebc56cc4b805ab.lock for C:\Users\user\AppData\Roaming\npm\node_modules\.staging
3110 timing stage:rollbackFailedOptional Completed in 39ms
3111 timing stage:runTopLevelLifecycles Completed in 55708ms
3112 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\nativescript\node_modules\fsevents):
3113 warn optional SKIPPING OPTIONAL DEPENDENCY: EBUSY: resource busy or locked, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\.staging\fsevents-7e994b47\node_modules\chownr' -> 'C:\Users\user\AppData\Roaming\npm\node_modules\.staging\chownr-c4547de6'
3114 verbose stack Error: EBUSY: resource busy or locked, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\nativescript\node_modules\.unzip.DELETE\node_modules\isarray' -> 'C:\Users\user\AppData\Roaming\npm\node_modules\nativescript\node_modules\unzip\node_modules\isarray'
3115 verbose cwd C:\Users\user\AppData\Local\NativeScriptSidekick\app-1.13.0-v20181052
3116 verbose Windows_NT 10.0.17134
3117 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript@latest" "--ignore-scripts"
3118 verbose node v10.13.0
3119 verbose npm  v6.4.1
3120 error path C:\Users\user\AppData\Roaming\npm\node_modules\nativescript\node_modules\.unzip.DELETE\node_modules\isarray
3121 error code EBUSY
3122 error errno -4082
3123 error syscall rename
3124 error EBUSY: resource busy or locked, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\nativescript\node_modules\.unzip.DELETE\node_modules\isarray' -> 'C:\Users\user\AppData\Roaming\npm\node_modules\nativescript\node_modules\unzip\node_modules\isarray'
3125 verbose exit [ -4082, true ]

**Comment by Daniel15** [comment]
@ostadsaleh  Please file a separate issue, and attach the contents of the log file (`%TEMP%\chocolatey\yarn\yarn.MsiInstall.log`)

**Comment by ostadsaleh** [comment]
thank you so much you well done the installation was done

    On Sunday, November 25, 2018, 12:37:19 PM GMT+3:30, Daniel Lo Nigro <notifications@github.com> wrote:  
 
 
@ostadsaleh Please file a separate issue, and attach the contents of the log file (%TEMP%\chocolatey\yarn\yarn.MsiInstall.log)

**Comment by TrollSherlock13** [comment]
I have the same issue but i'm not sure how to do this step-by-step

**Comment by bnthomason** [comment]
I have this problem too. It's debilitating!

**Comment by RickyMartin12** [comment]
Good Morning 

When I was to installed node js version 19 on choco i got the same error than @ostadsaleh

![image](https://github.com/yarnpkg/yarn/assets/9846274/36c93285-8d8d-4b9d-8233-80d26d277dcd)

I dont know how can fix it
