### ISSUE TITLE
please make yarnpkg the only binary yarn installs in /usr/bin

### ISSUE THREAD

**Issue by simevo** [yarnpkg/yarn#1656]
Re. #1305, please note that we can't create an **official Debian package** that installs a `/usr/bin/yarn` binary, because there is already one such binary in Debian: https://packages.debian.org/search?suite=sid&searchon=contents&keywords=yarn

For details, please see the discussion in the **RFP** here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843021

I see yarn already installs a `/usr/bin/yarnpkg` binary, can you just drop the `/usr/bin/yarn` one ?

As yarn is quite young (only 3 weeks have passed from the announcement on 2016-10-11) by renaming it now you'll hurt only the early adopters, and make it much easier for everybody in the medium term.

Also note that the name "yarn" conflicts with Hadoop YARN and with several other projects called "yarn" on github. You might as well rename the tool altogether, perhaps to yarnpkg as the main website ...

If you take no action, since on Debian and its derivatives we'll not ship **your** `/usr/bin/yarn`, users will have to invoke it in a different way w.r.t. other OSs, i.e. `yarnpkg`; if they'll invoke `yarn`, something different will happen ! Although this can be documented, it is certainly confusing.

Thanks, Paolo

**Comment by kittens** [comment]
We don't have any intentions of using the `yarnpkg` binary as the sole one. There's prior art here with Node.js using `node` instead of `nodejs` even though there's already a Debian package called `node`. See #673 for more information.
