### ISSUE TITLE
Yarn run doesn't pass flags

### ISSUE THREAD

**Issue by joallard** [yarnpkg/yarn#1667]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn run doesn't pass flags to bin script.

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure how to put together a more agnostic case, but here's what I have:

1. `$ yarn run browserify -o foo.js dependencies.js`
2. Actual: `$ ".../node_modules/.bin/browserify" dependencies.js`

Command is passed without flags.

**What is the expected behavior?**
Command is passed with flags.

**Please mention your node.js, yarn and operating system version.**
Nodejs v6.7.0; Yarn 0.16.1; macOS 10.11.

**Comment by kittens** [comment]
On `master` (and the latest release) the following works:

```sh
$ yarn run browserify -- -o foo.js dependencies.js
```

**Comment by joallard** [comment]
It was in the docs, sorry about that!

**Comment by joallard** [comment]
Should we warn the user when this happens?
