### ISSUE TITLE
please, replace ~/.yarn-cache folder to ~/.cache/yarn

### ISSUE THREAD

**Issue by r105m** [yarnpkg/yarn#1672]
I dont think, that yarn should have individual cache folder in linux systems

**Comment by kittens** [comment]
Created #1679 to fix this, pending approval.

**Comment by thesbros** [comment]
`bin/yarn.js` still creates `GLOBAL_INSTALL_DIRECTORY -> .yarn`, which doesn't seem to actually be used for anything.
