### ISSUE TITLE
Feature Request: 'yarn i' shortcut for 'yarn install'

### ISSUE THREAD

**Issue by smith64fx** [yarnpkg/yarn#1683]
Hey guys,
In npm I really got used to the shorthand "npm i", could you also make this possible for yarn?

**Comment by richardsantos** [comment]
@smith64fx I think `yarn` is a shortcut to `yarn install`

**Comment by kittens** [comment]
What @richardsantos said. We aren't adding any other aliases as they're confusing and redundant.
