### ISSUE TITLE
Some Yarn output not compatible with a Solarized Dark theme

### ISSUE THREAD

**Issue by tribou** [yarnpkg/yarn#1699]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Some of the default yarn output colors are not compatible with the popular Solarized Dark theme.

![screen shot 2016-11-05 at 10 02 16 am](https://cloud.githubusercontent.com/assets/1641390/20031098/4d608218-a340-11e6-94a9-93076f42c1f4.png)

(Highlighting reveals the hidden output)
![screen shot 2016-11-05 at 10 02 30 am](https://cloud.githubusercontent.com/assets/1641390/20031100/514c80d4-a340-11e6-9486-0b288eceb0a9.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. [Install the Solarized Dark them for iTerm2](https://github.com/altercation/solarized/tree/5e1fc7b2740d7317b3932cb60833c49316af362f/iterm2-colors-solarized#installation)
2. Use `yarn` to install/sync new packages in any given project.

**What is the expected behavior?**
I should be able to read all of the yarn output easily by default when using a Solarized Dark theme.

**Please mention your node.js, yarn and operating system version.**
OSX 10.11.6
Node v6.9.1
Yarn v0.16.1

npm/npm#12843 is a good reference for how this issue was resolved for `npm`. 😄 

[This chalk issue](https://github.com/chalk/chalk/issues/40#issuecomment-50975475) recommends using `dim` instead of `grey` for coloring. I can try my luck with a PR to see if that works.

**Comment by wyze** [comment]
Sure @tribou, send a PR!

**Comment by Daniel15** [comment]
This sounds like a bug with Solarized Dark rather than with Yarn, but nonetheless thanks for the pull request! 😄

**Comment by tribou** [comment]
@Daniel15 You are definitely correct! Unfortunately, the infamous issue altercation/solarized#220 from September of 2012 is evidence that this may not be resolved on the solarized side any time soon. ☹️   This has been an issue with so many projects over the years (mochajs/mocha#802, expressjs/express#1700, yeoman/generator#397, chalk/chalk#40, npm/npm#12843, gulpjs/gulp#654, hapijs/lab#592... just a quick survey 😄 ).

There was talk of forking the solarized project lately in altercation/solarized#355, so we'll see if anything else happens soon...

**Comment by Daniel15** [comment]
Thanks for the very thorough comment, @tribou! I appreciate the insight :) Hopefully someone forks Solarized and fixes it... It seems silly for every single project to have to adjust their colours just because one theme is not configured properly.
