### ISSUE TITLE
Yarn postinstall scripts cannot resolve packages

### ISSUE THREAD

**Issue by wouterverweirder** [yarnpkg/yarn#1710]
Using yarn 0.16.1

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn adds fail on postinstall scripts that require dependencies, such as node-gyp.
When adding one of those modules, yarn will fail on the postinstall script, saying that it cannot resolve a module used in that postinstall script. However, when viewing the node_modules folder, the module in question is there. Some cases where I've seen this happening are modules which are compiling native code with nan through node-gyp, yarn will not find node-gyp.

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add pty.js` or `yarn add electron-rebuild`

**What is the expected behavior?**
Installs complete successfully, postinstall script of these modules runs successfully.

**Please mention your node.js, yarn and operating system version.**
node v6.8.0
yarn 0.16.1
OSX 10.12.1 Sierra

**Comment by duivvv** [comment]
![gif](https://cl.ly/450z1r390P34)

**Comment by wouterverweirder** [comment]
![yarn-install-electron-rebuild](https://cloud.githubusercontent.com/assets/1126343/20040891/2aed1f2c-a460-11e6-9eed-db61ae457063.gif)

**Comment by wouterverweirder** [comment]
removed & reinstalled node and yarn, issue seems resolved.
