### ISSUE TITLE
problems installing @types

### ISSUE THREAD

**Issue by robstoll** [yarnpkg/yarn#1711]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
- I try to update dependencies with yarn (dependencies were initially installed with npm) with `yarn install` -> the lock file is the following https://github.com/robstoll/angular-seed/blob/master/yarn.lock
- I get the following error (in the log file):
```
Trace: 
  Error: ENOENT: no such file or directory, open '...\node_modules\@types\async\index.d.ts'
      at Error (native)
```
And I can confirm, there is not even a folder called @types in node_modules
When I hit  `yarn install` again I get the following error:
```
Trace: 
  Error: ENOENT: no such file or directory, open '...\node_modules\protractor\node_modules\@types\selenium-webdriver\index.d.ts'
      at Error (native)
```
In this case the folder node_modules\@types is created including subfolders (in contrast to the previous attempt)
When I hit `yarn install` again, then I get the first error again as mentioned above

**What is the expected behavior?**
install all dependencies

**Please mention your node.js, yarn and operating system version.**
node: 4.5.0
yarn: 0.16.1
OS: Windows 7

**Comment by robstoll** [comment]
Could resolve the problem by myself by deleting the node_modules folder. I leave the issue open in case the information above is helpful. Feel free to close it at any time

**Comment by whitecolor** [comment]
Yeah met this on some projects with `@types` in Windows 10, need to run yarn commands twice before they work.

**Comment by wyze** [comment]
Duplicate #919.
