### ISSUE TITLE
ignore-scripts does not prevent all scripts from running

### ISSUE THREAD

**Issue by ForbesLindesay** [yarnpkg/yarn#1713]
**Do you want to request a *feature* or report a *bug*?**

I think this is a bug.

**What is the current behavior?**

When I run yarn with `ignore-scripts: true` it still runs the local scripts.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. run `yarn config set ignore-scripts`
2. create a package.json with `{"scripts": {"postinstall": "echo FAIL"}}` in it
3. run `yarn` in that folder
4. Observe that "FAIL" is echoed as part of the output.

**What is the expected behavior?**

I expected the postinstall step to not be run.  Was I wrong to expect this?

**Please mention your node.js, yarn and operating system version.**

OSX

yarn: '0.16.1',
npm: '3.10.3',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '57.1',
modules: '48',
node: '6.4.0',
openssl: '1.0.2h',
uv: '1.9.1',
v8: '5.0.71.60',
zlib: '1.2.8'

I am attempting to generate a `yarn.lock` file for the latest versions that match a given un-trusted package.json.  It is therefore very important that scripts don't run.  It would be great to know if there's an easier way of achieving what I'm attempting.

**Comment by wyze** [comment]
I'm wondering if this only works from the flag for the CLI and not read in from the config file.

**Comment by ForbesLindesay** [comment]
I didn't find any docs that said this was an option you could pass via the CLI.  That's interesting.

**Comment by wyze** [comment]
You're right, looks like we need to get docs updated.

**Comment by kittens** [comment]
Already fixed on `master`.

**Comment by ForbesLindesay** [comment]
For future reference, #1422 was the pull request that fixed it.

**Comment by alexilyaev** [comment]
@kittens I don't see `--ignore-scripts` documented in https://yarnpkg.com/en/docs/cli/
Or any of the other `--` flags.

The CLI help description is not clear enough "don't run lifecycle scripts".  
Does that mean it won't run my own lifecycle scripts or also the installed package's scripts?
