### ISSUE TITLE
ENOENT packing a scoped package

### ISSUE THREAD

**Issue by maybeec** [yarnpkg/yarn#1714]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you want to `yarn pack` a scoped package, you will get an 

```
Error: ENOENT: no such file or directory, open 'D:\XXX\.build\@scope\package.tgz'
    at Error (native)
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a scoped package. E.g. `"name": "@scope/package"` and run `yarn pack`

**What is the expected behavior?**
It should pack a .tgz... somehow... :)

**Please mention your node.js, yarn and operating system version.**
node v6.9.1
yarn v0.16.1
Win7 x64 (regardless whether in cmd, git-bash, etc)

**Comment by razor-x** [comment]
Just ran into this. Want to bump this since I feel being unable to publish scoped packages is a pretty critical issue.
