### ISSUE TITLE
Installation Problem: Error installing on OSX El Capitan

### ISSUE THREAD

**Issue by OmerHerera** [yarnpkg/yarn#1715]
**Which operating system are you using:**
`OSX El Capitan Version 10.11.6 (15G1108)`

**Which NodeJS and NPM are you using:**
`v4.4.7`
`3.10.9`

**Please describe the steps you took when trying to install Yarn and what went wrong:**

1. `sudo npm install --global yarn`
2. `yarn --version`

* Result: 

`Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/yarn/node_modules/chalk/node_modules/escape-string-regexp/index.js'`

Here is the screen shot of my steps:
![yarn_install](https://cloud.githubusercontent.com/assets/5514007/20048964/c087e20c-a4c8-11e6-9fd2-586e245ca700.png)

**Comment by palmerj3** [comment]
Why are you installing with sudo? This would likely have the effect of putting it in root's path but not your users. Try without sudo and let me know if that fixes things.

**Comment by eisisig** [comment]
If you are having sudo problems do `sudo chown -R "$USER":admin /usr/local` to fix persmissions on /usr/local path...

http://stackoverflow.com/a/16450503/331927

**Comment by Daniel15** [comment]
Also please try using Homebrew or the installation script, I've seen weird issues when installing Yarn through npm that just don't occur when using other installation methods.

**Comment by OmerHerera** [comment]
Using without `sudo` also is not working.
My issue was fix using brew, but seem that installing using `npm` is not fully working.
I'm closing the issue, if someone thinks otherwise can re-open it.
