### ISSUE TITLE
Yarn overrides linked dependencies

### ISSUE THREAD

**Issue by robinvdvleuten** [yarnpkg/yarn#1718]
Hi there,

I have linked a (private) dependency through the command `yarn link @org/depname`. Now everytime I run another yarn command (link yarn add for example), the code inside the linked directory is overridden with the published version mentioned in the lock file. I expect that yarn skips this directory. 

BWT I use version 0.16.1

**Comment by whitecolor** [comment]
I'm too experience problems with within liking. For me it is still not completely clear how linking should work not to create big hassle for developer.

If one link package to the project one probably expects all the dependencies from linked package be available to the project where it is linked, as it would be installed normally (with `yarn add/install`), or not? 

Currently `link` just makes a symlink of the linked package in project's node_modules replacing if there this package was installed normally, but leaving its dependencies (of normally installed version) in place. I wonder what it should do with the dependencies of the linked package?

**Issues tag**:
Btw, as linking packages is very important topic for dev process I think yarn repo should have separate tag for issues related to it.

**Comment by robinvdvleuten** [comment]
Maybe I've the issue incorrectly, the issue is with the linked package itself not its dependencies;

```
-project1
--node_modules
---project2 (symlinked through "yarn link")

-project2
--node_modules
```

Now everytime I run any yarn command inside __project1__'s directory, any code belonging to __project2__ will be overridden with the version as described in yarn.lock. I expect that yarn just leaves this symlinked directory alone.

I noticed it as project2 is a git repository and after running yarn in project1's directory, it changes the files belonging to project2 to an older version.

**Comment by whitecolor** [comment]
There is seem to be an issue for this https://github.com/yarnpkg/yarn/issues/1214

**Comment by robinvdvleuten** [comment]
Yups that's exactly the same, this can be closed.
