### ISSUE TITLE
postinstall lifecycle hook not executed

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#1719]
**Do you want to request a *feature* or report a *bug*?**
bug, this could be missing feature though.

**What is the current behavior?**
yarn install does not also call the script in `{ "scripts": { "postinstall": "do something" } }`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
yarn install should also call the script in `{ "scripts": { "postinstall": "do something" } }`

**Please mention your node.js, yarn and operating system version.**
node.js v7.0.0
yarn 0.15.1

**Comment by wyze** [comment]
This was fixed in the latest release, 0.16.1.

**Comment by evan-scott-zocdoc** [comment]
Sorry to necro this issue, but could we run postinstall after `yarn upgrade|upgrade-interactive` as well? @wyze

**Comment by nikolay** [comment]
@wyze Why `update` and `postupdate` hooks are not fired during an `yarn upgrade`?

**Comment by wyze** [comment]
I would bring these up as new bugs/features in a separate issue than comment on and old closed issue.
