### ISSUE TITLE
incorrect yarn upgrade devDependency

### ISSUE THREAD

**Issue by maybeec** [yarnpkg/yarn#1720]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
the `upgrade` command duplicates a dependency to `dependencies` no matter, where it has been defined beforehand.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. declare any previous version of `systemjs-builder` prior to 0.15.33 in `devDependencies`
2. run `yarn upgrade systemjs-builder@0.15.33` or also tried `yarn upgrade systemjs-builder@0.15.33 --dev`

**What is the expected behavior?**
`yarn upgrade systemjs-builder@0.15.33` should upgrade the dependency just in place, no matter whether it has been declared in `dependencies` or `devDependencies`.

**Please mention your node.js, yarn and operating system version.**
yarn 0.16.1
node 6.9.1
win7 x64

**Comment by wyze** [comment]
Duplicate #1458 and fixed via #1620. This is working on master.
