### ISSUE TITLE
Informing users of changes between package versions

### ISSUE THREAD

**Issue by timoxley** [yarnpkg/yarn#1726]
Currently it's very difficult to know exactly what changed between different versions of packages without manually checking each package's git history, which of course most users don't have the time or patience for.

Would be good if both `yarn` & `npm` could agree on some metadata format or process for gathering and communicating changes between releases in packages, and optionally printing what would/did change before/after a successful update.

I suggest either a `history.md/.json` file or or perhaps a `"history"` key in `package.json`. If users don't opt-in to manually writing these, it could be easily retroactively autogenerated from git history on `prepublish` (or whatever it's called now). 

Another perhaps simpler alternative could be to generate these dynamically based on mapping versions to tags on github ala the https://www.npmjs.com/package/changelog package, though I think it's important for users to be able to write human-readable changelog summaries that don't necessarily map directly to commits.

I opened a similar issue on npm a few years back about this https://github.com/npm/npm/issues/5851#issuecomment-50892069 and @othiym23 seemed not against the concept.

**Comment by wyze** [comment]
I think this issue would be better suited for [yarnpkg/rfcs](https://github.com/yarnpkg/rfcs). Would you mind opening this up over there?

**Comment by timoxley** [comment]
@wyze No problem. Done https://github.com/yarnpkg/rfcs/issues/19
