### ISSUE TITLE
Publicise current version number somewhere prominent

### ISSUE THREAD

**Issue by glenjamin** [yarnpkg/yarn#1730]
**Do you want to request a *feature* or report a *bug*?**
feature, I guess

**What is the current behavior?**
Appears to be non-trivial to figure out what the latest version of yarn is from the github project page or website

**If the current behavior is a bug, please provide the steps to reproduce.**
Try and find out what the current yarn version is to see if you're running the latest version or if you need to upgrade.

**What is the expected behavior?**
Current version of yarn should be written somewhere prominent, or easy to check via the cli.

While poking around I did discover `self-update` is a thing, but didn't see any references to this on the project site either.

**Please mention your node.js, yarn and operating system version.**
yarn 0.16.1

**Comment by kittens** [comment]
> Appears to be non-trivial to figure out what the latest version of yarn is from the github project page

I'm confused by this, we have the [releases](https://github.com/yarnpkg/yarn/releases) page which prominently displays this?

> or website

I agree, can you open an issue on the [yarnpkg/website](https://github.com/yarnpkg/website) to add this please.

**Comment by glenjamin** [comment]
> I'm confused by this, we have the releases page which prominently displays this?

Good point, I always forget this feature exists.

> I agree, can you open an issue on the yarnpkg/website to add this please.

on it.
