### ISSUE TITLE
Windows + Angular CLI fail

### ISSUE THREAD

**Issue by stevemasta34** [yarnpkg/yarn#1731]
**Do you want to request a *feature* or report a *bug*?**

Report a  bug

**What is the current behavior?**
Failure to install packages. Then an error report
**If the current behavior is a bug, please provide the steps to reproduce.**

0. choco install yarn
1. npm install -g angular-cli
2. ng new some-dir
3. cd some-dir && yarn install

**What is the expected behavior?**
Yarn installs packages in the package.json, creating a lock file. Afterwards, I intended to run a `yarn upgrade` to bump the outdated packages brought in from angular-cli. Couldn't reach this step because of failures in the previous steps.

**Please mention your node.js, yarn and operating system version.**
Yarn version:
  0.16.0

Node version:
  7.0.0

Platform:
  win32 x64

**Comment by wyze** [comment]
Duplicate #859.
