### ISSUE TITLE
`yarn upgrade` <package> installs that package in production from dev

### ISSUE THREAD

**Issue by awilkins** [yarnpkg/yarn#1734]
**What is the current behavior?**

For a package in devDependencies, doing yarn upgrade will copy that (upgraded) dependency to dependencies.

**What is the expected behavior?**

The dependency is upgraded in-situ in devDependencies

**Please mention your node.js, yarn and operating system version.**
node 6.9.1
yarn 0.16.1
Ubuntu 16.04.1

**Comment by wyze** [comment]
Duplicate #1458. This is fixed on master and will be in the next release.
