### ISSUE TITLE
Packages on 'dl.yarnpkg.com' not distributed over HTTPS

### ISSUE THREAD

**Issue by adamchainz** [yarnpkg/yarn#1735]
**Do you want to request a *feature* or report a *bug*?**

Bug, I guess - lower security than expected.

**What is the current behavior?**

http://dl.yarnpkg.com/debian

**If the current behavior is a bug, please provide the steps to reproduce.**

It's on HTTP

**What is the expected behavior?**

https://dl.yarnpkg.com/debian

**Please mention your node.js, yarn and operating system version.**

Doesn't matter

**Comment by Daniel15** [comment]
https://github.com/yarnpkg/website/pull/237 covers this. I need to retest on old Ubuntu (12.04 and 14.04). The old SSL cert we had was a shared CloudFlare cert, which Ubuntu didn't like (see #607).

> lower security than expected.

The packages are all GPG signed, so serving them over HTTP shouldn't have any major security impact.

**Comment by adamchainz** [comment]
> The packages are all GPG signed

With the key fetched over HTTP from the same domain...

**Comment by Daniel15** [comment]
GPG doesn't support fetching keys using HTTP out-of-the-box :(

> gpgkeys: protocol 'https' not supported
> gpg: no handler for keyserver scheme 'https'
> gpg: WARNING: unable to fetch URI https://dl.yarnpkg.com/debian/pubkey.gpg: keyserver error

We did used to use a keyserver to load the key (pgp.mit.edu) but it had sporadic outages

Alternatively we could load the key over HTTPS by `wget`ting or `curl`ing it.

**Comment by adamchainz** [comment]
There's always https://github.com/yarnpkg/releases/raw/gh-pages/debian/pubkey.gpg

**Comment by Daniel15** [comment]
That has the same issue (and pulling from a Github URL is not as good as pulling from a URL we control)

I might change it to use HTTPS for the public key via `curl` rather than relying on `gpg` to fetch it.

**Comment by Daniel15** [comment]
This was resolved!

**Comment by adamchainz** [comment]
http doesn't redirect to https

**Comment by Daniel15** [comment]
Currently there's no redirect just in case (eg. if some super old version of Ubuntu starts disliking the cert again). Given the packages are all GPG signed, it shouldn't be any less secure to load them over HTTP, as long as the GPG public key itself is downloaded over a secure connection. All of our instructions show HTTPS URLs now, so I can reimplement the redirect once we confirm that no breakages are occurring as a result.

**Comment by adamchainz** [comment]
Coolio, good to know it has been thought of
