### ISSUE TITLE
"Unexpected error occured" when running "yarn add @types/jquery"

### ISSUE THREAD

**Issue by nfriend** [yarnpkg/yarn#1736]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `yarn add @types/jquery`, the command fails with `An unexpected error occured, please open a bug report...`  See error log below for full details.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create a new directory
- Navigate to this directory in `cmd`
- Run `yarn add @types/jquery`
  - The command should succeed
- Run `yarn add @types/jquery` again
  - or: add a different package instead, like `@types/angular`
  - The command should fail
- Running the same command a third time will succeed.

**What is the expected behavior?**
The command should not fail.

**Please mention your node.js, yarn and operating system version.**
Node version:  6.7.0
Yarn version: 0.16.1
OS: Windows 10 x64

**yarn-error.log**:

```
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\yarn\bin\yarn.js add @types/jquery

PATH: 
  C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Users\nfriend\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\cygwin64\bin;C:\Program Files (x86)\Borland\StarTeam SDK 10.0\Lib;C:\Program Files (x86)\Borland\StarTeam SDK 10.0\Bin;C:\Program Files (x86)\Borland\CaliberRM SDK 2008\lib;C:\Users\nfriend\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\nfriend\AppData\Local\atom\bin

Yarn version: 
  0.16.1

Node version: 
  6.7.0

Platform: 
  win32 x64

npm manifest: 
  {
    "dependencies": {
      "@types/jquery": "^2.0.34"
    }
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  "@types/jquery":
    version "2.0.34"
    resolved "https://registry.yarnpkg.com/@types/jquery/-/jquery-2.0.34.tgz#27615b369f30e572336126514e74672dda6e3d04"

Trace: 
  Error: ENOENT: no such file or directory, open 'C:\temp\yarntest\node_modules\@types\jquery\index.d.ts'
      at Error (native)

```

**Comment by wyze** [comment]
Duplicate #919.
