### ISSUE TITLE
yarn with an incorrect package.json crashes

### ISSUE THREAD

**Issue by reem** [yarnpkg/yarn#1745]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Crashes.

**If the current behavior is a bug, please provide the steps to reproduce.**
Break package.json to not be json. Call `yarn`.

**What is the expected behavior?**
Errors with informative message

**Please mention your node.js, yarn and operating system version.**
node v7.0.0
yarn v0.16.1
OS X 10.11.6

Here's the log that the crash included: https://gist.github.com/reem/58448fae9c8250364e5e2a9018295a97

**Comment by reem** [comment]
Oh, actually looks like this was just caused by me making package.json not actually json. Anyway, that probably should still not crash, but fail with an informative error.

**Comment by wyze** [comment]
This is fixed on master, so it will not crash in the next release!
