### ISSUE TITLE
Yarn add always failed

### ISSUE THREAD

**Issue by rkusuma** [yarnpkg/yarn#1746]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn add failed with error
```
Trace: 
  Error: ENOENT: no such file or directory, open 'D:\xxx\node_modules\@types\jasmine\index.d.ts'
      at Error (native)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
- run `yarn` command
- all dependencies installed (@types installed too)
- run `yarn add lodash`
- error and `@types` removed in `node_modules`
```
Trace: 
  Error: ENOENT: no such file or directory, open 'D:\xxx\node_modules\@types\jasmine\index.d.ts'
      at Error (native)
```
**What is the expected behavior?**
lodash added to dependecies and `package.json`

**Please mention your node.js, yarn and operating system version.**
```
node: 6.5.0
yarn: 0.16.1
os: Windows 8.1
```

**Comment by wyze** [comment]
Duplicate #919.
