### ISSUE TITLE
"yarn remove XXX --ignore-engines" doesn't

### ISSUE THREAD

**Issue by haf** [yarnpkg/yarn#1752]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
Not ignoring engines

**If the current behavior is a bug, please provide the steps to reproduce.**
See title

**What is the expected behavior?**
Ignoring engines

**Please mention your node.js, yarn and operating system version.**
latest LTS of node and of yarn at time of writing

**Comment by wyze** [comment]
This is fixed on master and will be in the next release.
