### ISSUE TITLE
flag "-E" cannot be handled properly

### ISSUE THREAD

**Issue by dobre-robert-marius** [yarnpkg/yarn#1753]
**Do you want to request a *feature* or report a *bug*?**

**bug**

**What is the current behavior?**
"yarn add -E [package]" throws "error: unknown option `-E'"
"yarn add [package] -E" adds the package, but not the exact version
"--exact" (the long version) works properly

**If the current behavior is a bug, please provide the steps to reproduce.**
I just did in the current behavior

**What is the expected behavior?**
flag "-E" should have the same behavior as "--exact"

**Please mention your node.js, yarn and operating system version.**
node js v7.1.0
yarn 0.16.1
windows 8

**Comment by wyze** [comment]
This is available on master and will be in the next release.
