### ISSUE TITLE
"yarn add --dev" not adding to dev deps

### ISSUE THREAD

**Issue by skevy** [yarnpkg/yarn#1758]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `yarn add --dev` it does not add the dependency to dev deps.

**If the current behavior is a bug, please provide the steps to reproduce.**

a) Create a new project with `yarn init -y`.
b) Run `yarn add --dev babel-core`
c) Observe that `babel-core` was added to dependencies, not devDependencies in package.json.

**What is the expected behavior?**

`babel-core` should have been added to devDependencies

**Please mention your node.js, yarn and operating system version.**

Node version: 6.9.1
Yarn: master
OS: macOS 10.12.1

**Comment by skevy** [comment]
cc @ide

**Comment by wyze** [comment]
I just pulled the latest master and I am not able to reproduce this. Same OS and my node is at 6.7.0.

**Comment by skevy** [comment]
You're right @wyze, my master copy was actually 3 days old (unintentionally). This was fixed by #1701. Thanks for looking into it and sorry for the false alarm!
