### ISSUE TITLE
Allow upgrade for local/git packages by used name

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#1762]
If I have local package  with package.json name: 'my-local-package'

if I do `yarn add file:./path/to/my/local/package` it will add in projects package.json
```
"my-local-package": "file:./path/to/my/local/package"
```
and will place (copy) it in `node_modules/my-local-package`

But I can also manually add in project's package.json
```
"my-local-package-custom-name": "file:./path/to/my/local/package"
```

and run `yarn` and it will place local package in `node_modules/my-local-package-custom-name`

The same is valid for git repo sources. I think this is a good feature, but **npm doesn't allow such thing**, it will in any case place installed package in the canonical name `node_modules/my-local-package` if we have `my-local-package-custom-name` in package.json (it won't modify package.json though).

So the problem is that if `yarn` is still going to allow this feature with custom dest package folder name, it is not possible make targeted upgrade by name `my-local-package` or by `my-local-package-custom-name` only by `file:./path/to/my/local/package`.

https://github.com/yarnpkg/rfcs/issues/23

**Comment by whitecolor** [comment]
Though it seems that it can be already done:

`yarn upgrade my-local-package-custom-name@file:./path/to/my/local/package`

Will close it.

**Comment by yched** [comment]
Regardless of canonical name vs. used name, 

`yarn upgrade my-local-package@file:./path/to/my/local/package` 

doesn't seem to catch new package version in the local folder ?

Opened #2939, since this issue here is closed
