### ISSUE TITLE
Bad behavior under a bad network connection

### ISSUE THREAD

**Issue by Jack-Works** [yarnpkg/yarn#1763]
Arguments: 
node.exe yarn.js global add angular-cli --proxy http://127.0.0.1:1080

Yarn version: 0.16.1

Node version: 6.9.1

Platform: win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/bower/-/bower-1.8.0.tgz: unexpected end of file
      at Zlib._handle.onerror (zlib.js:370:17)

Yarn will fail if the download file is broken instead of re-download it

**Comment by Blaccexican** [comment]
https://registry.yarnpkg.com/bower/-/bower-1.8.0.tgz

**Comment by Daniel15** [comment]
Probably a duplicate of #746?

**Comment by wyze** [comment]
I'll agree with that @Daniel15.
