### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Blaccexican** [yarnpkg/yarn#1765]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by Blaccexican** [comment]
shaybody89@gmail.com

**Comment by Blaccexican** [comment]
package.json

**Comment by wyze** [comment]
Can you edit the main issue and answer the questions given?
