### ISSUE TITLE
[bug] Issues installing dev dependencies

### ISSUE THREAD

**Issue by CodeJjang** [yarnpkg/yarn#1770]
Yarn version: 0.16.1
Node version: 4.4.2
OS: Ubuntu 14.04 LTS

I was trying to install several packages to dev dependencies.  
Running:
```
yarn add -D nock supertest mocha chai
```
Did not update my package.json file at all.
Then I tried:
```
yarn add nock supertest mocha chai -D
```
And all the packages were installed as regular dependencies (not dev).  
At least, when I tried:
```
yarn add nock supertest mocha chai --dev
```
Everything worked.

Expected behavior: I'd expect the outcome to be consistent whether I use -D or --dev, as well as being indifference to whether it comes first or last (just like `npm`).  

Thanks :)

**Comment by wyze** [comment]
This is fixed on master and will be in the next release.
