### ISSUE TITLE
`yarn upgrade pkg` does not properly save dependencies 

### ISSUE THREAD

**Issue by IOAyman** [yarnpkg/yarn#1773]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn upgrade`ing a package in `devDependencies` results in a new duplicate in `devDependencies`

**How to reproduce**

```bash
$ mkdir test && cd test
$ yarn init
$ yarn add --dev ts-node@^1.6.0   # latest version is 1.7.0
$ yarn upgrade ts-node
$ cat package.json
"devDependencies": {
  "ts-node": "^1.6.0" 
},
"dependencies": {
  "ts-node": "^1.7.0"
}
```
**_Note_** that the old version is kept in `devDependencies` and the new one is saved to `dependencies` as well

**What is the expected behavior?**
```json
"devDependencies": {
  "ts-node": "^1.7.0"
}
```

**Please mention your node.js, yarn and operating system version.**
yarn: v0.16.1
node: v6.9.1
os: Linux

- - -
This references #1620 
/cc @wyze

**Comment by IOAyman** [comment]
I've just realized that `master` has not been published to npm registry yet!
When is it going to be published,  please?

**Comment by wyze** [comment]
I'm not sure when the next stable release will be out, but you could give the nightly build a shot.

```
wget https://yarnpkg.com/install.sh
chmod +x install.sh
./install.sh --nightly
```

**Comment by IOAyman** [comment]
Thank you :)
