### ISSUE TITLE
Cannot use package globally via yarn global add

### ISSUE THREAD

**Issue by Elliot-Evans-95** [yarnpkg/yarn#1779]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Trying to globally install grunt. If I use yarn global add command, it will be allow me to use 'grunt' as a cli name. If I install grunt globally via npm, I can use grunt as a cli name
**If the current behavior is a bug, please provide the steps to reproduce.**
1. install a npm package globally (yarn global add grunt)
2. package successfully installs.
3. restarted terminal for changes.
4. type grunt in to terminal. 
5. errors: **zsh: command not found: grunt**
note: I have added export PATH="$PATH:$HOME/.yarn/bin" to my .zshrc file, still cannot find 'grunt'
**What is the expected behavior?**
grunt can be used on the command line.
**Please mention your node.js, yarn and operating system version.**
Mac OS X El capitain
Installed via homebrew
iterm2 with zsh

**Comment by wyze** [comment]
Duplicate #1321.
