### ISSUE TITLE
Allow comments in package.json

### ISSUE THREAD

**Issue by sebmck** [yarnpkg/yarn#178]

**Comment by danielbayley** [comment]
Supporting `package.cson` would solve this for free.

**Comment by ljharb** [comment]
@danielbayley assuming yarn doesn't wish to break the npm ecosystem, it wouldn't be entirely free because it'd have to be converted to a proper `package.json` prepublish.

**Comment by tombh** [comment]
Just some inspiration on this topic:

A dependency manifest (and even more so `package.json`) is a remarkably comprehensive, accessibly concise, syntactically enforced and implicitly maintained piece of _humanly_ consumable documentation. It is the doorway into understanding a new project. That comments are not supported is not merely a minor omission but an existential misrepresentation.

But of course I appreciate the rabbit hole of technical hurdles. Nevertheless I don't think the above point is made clear often off.

**Comment by ljharb** [comment]
JSON already supports comments:
```json
{
  "foo": "this field is for the version of foo",
  "foo": "^1.2.3"
}
```

Be as humane as you like! Don't forget to file bugs on tools that inadvertently destroy these duplicate keys (`npm install --save`, for example).

**Comment by tombh** [comment]
Yarn is really our only morsel of hope. Npm is resolute in its intention not to include comments: https://github.com/npm/npm/issues/4482

I'm not going to keep rehashing the same arguments. The point here is, the lack of comments in Javascript's canonical configuration specification is indicative of the broader critiques often levelled at the language. Yarn, taking the burden of initiative, is a commendable response to such critiques such that it contributes to an overall iterative improvement to the language and ecosystem as a whole. Considering this, is it appropriate that the community look to Yarn to, at the very least, explore the ultimate ideals of dependency management and the manifest document that defines it?

@ljharb somewhat ironically, even Yarn itself will not fix key deduplication: https://github.com/yarnpkg/yarn/issues/1669

**Comment by jcrben** [comment]
Duplicate request: https://github.com/yarnpkg/yarn/issues/3959

**Comment by httpJunkie** [comment]
Why not just allow for a `package.json.comments` file that is constantly watched and strips out the comments and outputs to `package.json`?

This is obviously something that could be setup as part of a webpack configuration. Not sure if this has anything to do with yarn though...

Kind of covered how to do this here: 
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/265#issuecomment-252325142

**Comment by kajmagnus** [comment]
Not being able to easily add comments is to some degree, a security issue.

Recently there was this `event-stream` vulnerability: https://github.com/dominictarr/event-stream/issues/116  — and then it's imporant (I think) with a comment in package.json that tells people to not upgade past v3.3.4. When it's not obvious & simple to add comments (instead, the hacky workarounds mentioned above are required), some people won't add any comment about this security vuln, resulting in possibly accidental upgrades later on, to the compromised higher version numbers.

**Comment by ljharb** [comment]
That’s already achieved with npm depreciations and a semver range that doesn’t include the problem versions; nobody would read that comment since npm install/yarn add commands alter package.json without any human editing.

**Comment by kajmagnus** [comment]
@ljharb Thanks for the reply.  Hmm, what I had in mind, is people editing the `package.json` file in a text editor, and changing the semver range, without knowing that that brings in a vulnerability. Not everyone updates dependencies via the command line tools — sometimes peolpe edit the files directly, well at least I do sometimes.  Then to me it seems like useful with a comment, to prevent people from accidentally editing the semver range to something dangerous.

That no one reads that comment isn't totally true — I look at `package.json` files of libs I think about using (because if they bring in crazily many dependencies, I wouldn't like that), and I would think some percentage of other developers, do too.  In my own projcects, I'm going to prevent Yarn and Npm from removing the comments I now added to my `package.json`, by looking at the Git diff during code review and undoing any deletions.

Anyway, never mind, barely matters.

**Comment by ljharb** [comment]
Fair, I was being hyperbolic - I think not enough people would read the comment for that to be a useful argument in favor of package.json comments.

**Comment by jcrben** [comment]
Most projects are missing a handy "why do I have this dependency and how did we vet it" comment, which could just be a pointer to the vetting ticket. Admittedly, git blame can sometimes help for that. Also, for those who really care (myself included): https://github.com/wiredmax/npm-json5 - altho I discovered it doesn't work with npm 4 or 5 https://github.com/wiredmax/npm-json5/pull/2 much less yarn.

There are of course a variety of tools which will read package.json and provide reports, but that's not exactly lightweight...

**Comment by nick4fake** [comment]
@sebmck 

````
Going to punt this to later.
````

7 years have passed, so just to recheck, is it something what is still postponed?

**Comment by VelocityPulse** [comment]
I still don't see any evolution...

**Comment by ojboj** [comment]
Can we not just support `package.jsonc` files and the [jsonc standard](https://jsonc.org/)? This keeps the existing behaviour of syntax erorring out if a `package.json` file has comments but if its a `package.jsonc` file, we can have comments!

This keeps the abillity for those that want to use JSON.parse with `package.json` safely and the `package.jsonc` file can be stripped of comments when needed to be understood as a JSON file.

Would be awesome to get this functionality, nearly a decade later
