### ISSUE TITLE
"bin" symlink missing on some case.

### ISSUE THREAD

**Issue by garbin** [yarnpkg/yarn#1780]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**

the dependencies tree below

- PROJECT_ROOT
   - koapi
      - knex (that have a bin symlink 'knex')
      - ava (that have a bin symlink 'ava')

with npm, the 'bin' symlink knex and ava will be found at PROJECT_ROOT/node_modules/.bin

- PROJECT_ROOT
   ./node_modules/.bin/knex
   ./node_modules/.bin/ava

but yarn, there are missing. they only can be found in the package that direct dependent them.
{PROJECT_ROOT}/node_modules/koapi/node_modules/.bin

- koapp
      - koapi
      ./node_modules/.bin/knex
      ./node_modules/.bin/ava

**If the current behavior is a bug, please provide the steps to reproduce.**

mkdir /tmp/test
cd /tmp/test
yarn add koapi

**What is the expected behavior?**

/tmp/test/node_modules/.bin/knex /tmp/test/node_modules/.bin/ava should be created.

**Please mention your node.js, yarn and operating system version.**

Node.js 7.1.0
yarn 0.16.1
macOS Sierra

**Comment by wyze** [comment]
Duplicate #760 and was fixed by #1210.
