### ISSUE TITLE
Error: connect ETIMEDOUT 192.30.253.113:443

### ISSUE THREAD

**Issue by PrismPrince** [yarnpkg/yarn#1781]
**Which operating system are you using:**
Windows 10 x64

**Please describe the steps you took when trying to install Yarn and what went wrong:**
===from log file of yarn===

Trace: 
  Error: connect ETIMEDOUT 192.30.253.113:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

**Comment by wyze** [comment]
Duplicate #944.

**Comment by monsterooo** [comment]
npm config set proxy http://127.0.0.1:1080
npm i node-sass

# delete proxy
npm config delete proxy

> It solves the problem

**Comment by a1018875550** [comment]
@monsterooo .It's work for me

**Comment by vinay0458** [comment]
it didn't work for me

**Comment by kiran4848** [comment]
hi 
@vinay0458 did you got any answer for that?this error

**Comment by Menuka5** [comment]
I got the same kind of error.

> Error: connect ETIMEDOUT 151.101.240.133:443

In my case it was company firewall was blocking the connection. First, use an open wifi connection to check whether company proxy is the problem?

**Comment by rashmimilan** [comment]
Follow the steps at:
https://docs.cloudfoundry.org/cf-cli/http-proxy.html
and most importantly, reboot  your machine. Then try command "pkg . "
It worked!

**Comment by wanmaoor** [comment]
> ```js
> npm config set proxy http://127.0.0.1:1080
> npm i node-sass
> 
> // delete proxy
> npm config delete proxy
> ```
> 
> It solves the problem

it works for me! Thanks
