### ISSUE TITLE
Please release a new version of yarn

### ISSUE THREAD

**Issue by alanhogan** [yarnpkg/yarn#1784]
Some rather important fixes have landed in master, such as improving compatibility with private git repositories as module sources. By releasing a new version of yarn, you will immediately allow more teams to switch over and collectively save uncounted many hours of trouble :)

**Comment by IOAyman** [comment]
Problems such as #1773 as well!

:+1:

**Comment by develar** [comment]
BTW, `yarn run [script] [-- <args>]` (#1749) is broken in the nightly builds :(

**Comment by kittens** [comment]
We're still in the process of getting our releases automated. Right now there's a lot of manual churn to get Yarn released. For example we have installers for Windows that need to be signed and the team is currently split across timezones which means that coordinating these is particularly tricky. The next release will either be today or Monday.

**Comment by FredyC** [comment]
Just found out about nightly builds available. It's really well hidden on the site :) If anyone is interested trying how new stuff, go ahead ! https://yarnpkg.com/en/docs/nightly

**Comment by Daniel15** [comment]
> It's really well hidden on the site

Let us know if you have a better idea of how to make the nightly builds more obvious 😄

**Comment by alanhogan** [comment]
Hey… there hasn't been a new release, has there? I don’t see a change log or a release date on the website.

**Comment by alanhogan** [comment]
Sorry, I just checked NPM and saw 0.17.2 was released just 6 hrs ago. That’s what I get for checking the wrong source :)

**Comment by Daniel15** [comment]
There's a few bugs in 0.17.x so we're holding off "officially" releasing it for now. Right now it's only really listed on npm - the main installation methods are still installing 0.16.1. #1859 tracks the fixes required for the 0.17.x branch.
