### ISSUE TITLE
"yarn add -D" doesn't install as dev dependencies

### ISSUE THREAD

**Issue by gonzoyumo** [yarnpkg/yarn#1786]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
`yarn add pkg -D` install pkg as production dependency instead of dev Dependency

**If the current behavior is a bug, please provide the steps to reproduce.**
* `yarn add pkg -D`
* Look at package.json

**What is the expected behavior?**
`yarn add pkg -D` should add pkg to devDependencies instead of production dependencies

FYI: `yarn add pkg --dev`  works perfectly, only the `-D` alias is affected

**Please mention your node.js, yarn and operating system version.**
node 5.5.0
yarn 0.16.1

**Comment by kittens** [comment]
This is fixed in `master`.
