### ISSUE TITLE
ssh:// prefix is not removed from URLs passed to git CLI

### ISSUE THREAD

**Issue by pornel** [yarnpkg/yarn#1796]
Bug in v0.17.0. Still in v0.20.3.

**What is the current behavior?**

URL in the format `git+ssh://host_alias:path.git` is given to git clone as `ssh://host_alias:path.git`. This is not compatible with npm, which clones `host_alias:path.git` (without the `ssh://` prefix). This changes the meaning of the URL in `git`.

(By `host_alias` I mean a name given in `Host` setting in `~/.ssh/config`. I'm using git URLs in such format, because it allows me to configure specific SSH deployment keys for private github repos.)

**What is the expected behavior?**

`ssh://` prefix should be stripped from URLs given to `git` CLI.

**Please mention your node.js, yarn and operating system version.**

yarn v0.17.0-20161111.1922. Tested again in v0.20.3.

#513 says git+ssh support is fixed, but this particular case still doesn't work for me in today's nightly.

**Comment by Gastonite** [comment]
I've the same bug in yarn version v0.23.0-20170314.1919
