### ISSUE TITLE
BUG: yarn ls --depth=0

### ISSUE THREAD

**Issue by TotallyInformation** [yarnpkg/yarn#1800]
Windows 10, Node v0.6, Yarn v0.16.1

    yarn ls --depth=0

Does not work:
    
    > yarn ls --depth=0
       error: unknown option `--depth'

The docs say it should work, it works on npm.

**Comment by jvhoven** [comment]
Hi! This seems to be fixed in master :smiley:. You could use the [nightly version](https://nightly.yarnpkg.com/) if you really wanted to use this feature right now.

**Comment by wyze** [comment]
This is only available on master, but will be in the next release.

**Comment by TotallyInformation** [comment]
That's great, thanks.
