### ISSUE TITLE
`github:` defines fetcher type as tallbar

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#1802]
Dependency `github:someuser/somerepo` while fetcher type is set as `tallbar` not `git`. Not sure how it should be but it is strange to me.

If replace dep location with: `ssh://git@github.com/someuser/somerepo` it fetcher type will be `git`

**Comment by kittens** [comment]
This is intentional. We use GitHub APIs when resolving/fetching GitHub repos as it's more efficient.
