### ISSUE TITLE
`yarn global add package` does not update packages to a newer version

### ISSUE THREAD

**Issue by thibmaek** [yarnpkg/yarn#1803]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
Running `yarn global add now` does not update the globally installed package
**If the current behavior is a bug, please provide the steps to reproduce.**
Install an older version of a package (eg. now) globally and try to update it with `yarn global add <pkg>`
**What is the expected behavior?**
It updates the package to the latest version
**Please mention your node.js, yarn and operating system version.**
v7.0.0, 0.16.1, macOS Sierra 10.12.1

Screenshot: https://www.dropbox.com/s/iadtz3psodr972h/Screenshot%202016-11-13%2018.19.57.png?dl=0

**Comment by wyze** [comment]
Duplicate #1321. Seems it installs successful, but not in the correct path.
