### ISSUE TITLE
`yarn bin` path incorrect

### ISSUE THREAD

**Issue by shnhrrsn** [yarnpkg/yarn#1804]
Running `yarn bin` in subdirs of the main project dir is reporting an incorrect path:

```bash
$ pwd
/apps/api/build/bin
$ yarn bin
/apps/api/build/bin/node_modules/.bin
$ npm bin
/apps/api/node_modules/.bin
```

I don’t have a `node_modules` dir in `/apps/api/build/bin`, the root `package.json` file and main `node_modules` dir is located in `/apps/api`.

`npm bin` correctly finds the root dir and outputs it, where as it appears `yarn bin` just takes the current dir and appends `node_modules/.bin`

**Comment by hpurmann** [comment]
I'm working on this.

**Comment by paul-soporan** [comment]
Closing as I *think* it's also been fixed in v1 but if not it's definitely fixed in v2 (https://yarnpkg.com/getting-started/migration).
