### ISSUE TITLE
Add commitizen and semantic release for automatic versioning and NPM releasing.

### ISSUE THREAD

**Issue by stoffern** [yarnpkg/yarn#1805]
https://github.com/commitizen/cz-cli
https://github.com/semantic-release/semantic-release

more info here
https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release

**Comment by kittens** [comment]
Please write up an RFC and submit it in the [yarnpkg/rfcs](https://github.com/yarnpkg/rfcs) repo.
