### ISSUE TITLE
After yarn add. Command -> System cannot find the path specified. WINDOWS 10

### ISSUE THREAD

**Issue by Alonski** [yarnpkg/yarn#1807]
**Do you want to request a *feature* or report a *bug*?**

Bug Report
**What is the current behavior?**
After installing with Yarn I type into my cmd:
ember.
I get back: 

```
"$basedir/../../Users/owner/AppData/Local/Yarn/config/global/node_modules/.bin/ember.cmd"   "$@"
The system cannot find the path specified.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Installed Yarn using Chocolatey via: choco install yarn
2. Installed ember-cli@1.13.0 via: yarn global add ember-cli@1.13.0
3. Install finished.
4. Restart CMD
5. Insert "ember" into cmd. Hit Enter. CMD closes...
6. Restart CMD.
7. Run cmd /k
8. Run ember
9. Get error:
```
"$basedir/../../Users/owner/AppData/Local/Yarn/config/global/node_modules/.bin/ember.cmd"   "$@"
The system cannot find the path specified.
```
**What is the expected behavior?**
ember-cli works. 
**Please mention your node.js, yarn and operating system version.**
Operating system: Windows 10 64x
Yarn: 0.16.1
Node: 7.1.0
npm: 3.10.9

**Comment by wyze** [comment]
Duplicate #859.

**Comment by Alonski** [comment]
This is not the same issue...

**Comment by wyze** [comment]
Maybe not exactly, but there are plenty of issues about `yarn global add` on Windows.

Possibly #1324

**Comment by Alonski** [comment]
From the error message it seems that the problem isn't with global add but with the pathing afterwards.
