### ISSUE TITLE
SERIOUS BUG: package.json "name" parsing with spaces

### ISSUE THREAD

**Issue by izelnakri** [yarnpkg/yarn#1812]
Yarn version: 0.16.1 (LATEST)

if my project name contains spaces yarn cannot parse/download packages with ```yarn add packageName```

example my package.json:
```json
{
  "name": "Izel Nakri",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT"
}
```
"name" has spaces.

Then one cannot install any package or use yarn with ```yarn add``` !!

**Comment by wyze** [comment]
For comparison npm just warns:

```sh
$ npm install --save left-pad
/Users/nkist/Projects/yarn-example
└── left-pad@1.1.3

npm WARN Invalid name: "Izel Nakri"
npm WARN yarn-example No description
npm WARN yarn-example No repository field.
npm WARN yarn-example No README data
npm WARN yarn-example No license field.
```

**Comment by izelnakri** [comment]
yes thanks, apparently there should never be spaces in package.json. yarn could give a better warning.

**Comment by kittens** [comment]
The error message is correct, your `name` is invalid. We need this error or else we'll attempt to publish packages with incorrect names and all sorts of miscellaneous bugs.
