### ISSUE TITLE
How to know number of downloads of a package with yarn ?

### ISSUE THREAD

**Issue by didierfranc** [yarnpkg/yarn#1815]
Hi I'm doing that to count the numbers of download on npm for my company projects : 

<img width="581" alt="capture d ecran 2016-11-14 a 17 38 49" src="https://cloud.githubusercontent.com/assets/14132464/20274173/f9a08a8c-aa93-11e6-88b3-d91152d83b87.png">  

So, now that yarn is becoming the first package manager for node, packages are downloaded from https://registry.yarnpkg.com/  is there some api route to get that information with yarn? 🤔

**Comment by Daniel15** [comment]
registry.yarnpkg.com is just a caching proxy over the npm repository, hosted by Cloudflare. It doesn't currently have any additional functionality nor does it expose any statistics.

**Comment by finom** [comment]
@kittens @Daniel15 can you re-open this issue because Yarn definitely needs to store downloads statistics.

**Comment by Daniel15** [comment]
@finom - Since registry.yarnpkg.com currently does no additional caching, you should use npm's API to get stats. We don't currently have any custom stats logging for registry.yarnpkg.com.

**Comment by finom** [comment]
The key word is "currently". I hope the team is going to listen the community and add new features.

**Comment by aalexgabi** [comment]
Maybe this is what you're looking for: https://stats.yarnpkg.com/

**Comment by jjangga0214** [comment]
@Daniel15 I think @finom 's opinion makes sense. I also hope yarn provides an API for cache hit.

**Comment by merceyz** [comment]
Please don't bump really old issues.

Yarn can't provide any stats, see https://yarnpkg.com/getting-started/qa/#why-registryyarnpkgcom-does-facebook-track-us
