### ISSUE TITLE
[0.17.0] Cannot add dependency in org/repo format

### ISSUE THREAD

**Issue by FredyC** [yarnpkg/yarn#1818]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
[Error log](https://gist.github.com/FredyC/6f5abf2676aac300c36d51e7c8a5c35f#file-yarn-error-log)

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn cache clean`
`yarn init`
`yarn add blackdice/errorception`

**What is the expected behavior?**
To install dependency

**Please mention your node.js, yarn and operating system version.**
Node 6.9.1, Windows 10 x64, Yarn 0.17.0

**Comment by scholtzm** [comment]
I was just about to report this.

Adding the same dependency with v0.16.1 works flawlessly though.

**Comment by scothis** [comment]
Digging into the yarn cache, the dependency is saved to disk without a sha, the read from the cache is looking with the sha.

**Comment by bestander** [comment]
Anyone wants to submit a PR?

**Comment by bestander** [comment]
Is this bug the same as #1834?

**Comment by wyze** [comment]
@bestander Yes it is. If I apply the fix in #1871 this works fine.

**Comment by bestander** [comment]
Let's close it then
