### ISSUE TITLE
Cannot globally install any package: "expected manifest"

### ISSUE THREAD

**Issue by basvdwollenberg** [yarnpkg/yarn#1824]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Output when trying to install `create-react-app` as it's the example [here](https://yarnpkg.com/en/docs/cli/global).
```
yarn global v0.17.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error An unexpected error occurred: "expected manifest".
info If you think this is a bug, please open a bug report with the information provided in "/home/bas/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
From the log:
```
Trace:
  Invariant Violation: expected manifest
      at invariant (/home/bas/n/lib/node_modules/yarn/node_modules/invariant/invariant.js:42:15)
      at PackageResolver.getStrictResolvedPattern (/home/bas/n/lib/node_modules/yarn/lib/package-resolver.js:401:5)
      at GlobalAdd.maybeOutputSaveTree (/home/bas/n/lib/node_modules/yarn/lib/cli/commands/global.js:185:38)
      at /home/bas/n/lib/node_modules/yarn/lib/cli/commands/add.js:162:19
      at Generator.next (<anonymous>)
      at step (/home/bas/n/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/bas/n/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Try to globally install any package (e.g.: `yarn global add create-react-app`)

**What is the expected behavior?**
Should globally install the package.

**Please mention your node.js, yarn and operating system version.**
Node: 7.1.0
Yarn: 0.17.0
OS: Antergos Linux release 16.6 (ISO-Rolling), Linux version 4.8.7-1-ARCH

**Comment by eisisig** [comment]
Same error with jscodeshift

`yarn global add jscodeshift`

Node: 7.1.0
yarn: 0.17.0
macOS 10.12.2

**Comment by vitorgalvao** [comment]
> Please mention your node.js, yarn and operating system version.
> Node: 7.1.0
> Yarn: 0.17.0
> OS: Antergos Linux release 16.6 (ISO-Rolling), Linux version 4.8.7-1-ARCH

Can confirm on macOS `10.11.6` as well (same versions for everything else).

**Comment by onemen** [comment]
Fix Invariant Violation: expected manifest from GlobalAdd (regressed by #1757)
```
diff --git a/src/cli/commands/global.js b/src/cli/commands/global.js
--- a/src/cli/commands/global.js
+++ b/src/cli/commands/global.js
@@ -17,7 +17,7 @@ import * as fs from '../../util/fs.js';
 
 class GlobalAdd extends Add {
   maybeOutputSaveTree(): Promise<void> {
-    for (const pattern of this.args) {
+    for (const pattern of this.addedPatterns) {
       const manifest = this.resolver.getStrictResolvedPattern(pattern);
       ls(manifest, this.reporter, true);
     }
```

**Comment by willyb321** [comment]
Can't install any package globally here either. macOS 10.12.1.

**Comment by mDibyo** [comment]
Same problem on Ubuntu (as expected from the macOS reports above)

**Comment by RobAWilkinson** [comment]
having the exact same issue here, on our travis builds

**Comment by calebeby** [comment]
Same thing here. `yarn global add coffee-script`

**Comment by domino14** [comment]
`yarn global add gulp-cli` doesn't work on circleCI

**Comment by calebeby** [comment]
OK. Was on node `4.6.1`, with `nvm`, and switched to `7.1.0` and now it works

**Comment by Repox** [comment]
Also confirming the issue.

**Comment by flemming-steinson** [comment]
Same issue here

**Comment by timoxley** [comment]
If you want a workaround right now for installing global packages, use `@latest` after the package name, e.g.

```
yarn global add webpack@latest
```

This works with any exact `version` or `dist-tag` e.g. 

```
yarn global add webpack@latest
yarn global add webpack@beta
yarn global add webpack@2.1.0-beta.26
yarn global add webpack@1.13.3
```

You can get list of `dist-tags` for a package with `yarn info webpack dist-tags` e.g.

```
> yarn info webpack dist-tags
yarn info v0.17.0
{ latest: '1.13.3',
  beta: '2.1.0-beta.26' }
✨  Done in 0.54s.
```

Also works with `yarn info webpack versions` for explicit versions that aren't currently tagged, though note this output can be very long.

**Comment by iraklisg** [comment]
same issue

**Comment by VincentChataignier** [comment]
Same issue, but if I install grunt-cli package with `yarn global add grunt-cli@latest`, the command `grunt` was not found and not linked in `/usr/bin` folder.

**Comment by arxpoetica** [comment]
nodemon is also not linked using `@latest`

**Comment by simonas-notcat** [comment]
Same issue with `yarn global add code-push-cli `

**Comment by arxpoetica** [comment]
For anyone who needs to rollback while waiting for this fix, just do:

```
npm i -g yarn@0.16.1
```

Make sure to uninstall and then reinstall global dependencies to include bin linking. yarn global remove ... and yarn global add ...

**Comment by iraklisg** [comment]
@arxpoetica could you please provide more details about the following?

> Make sure to uninstall and then reinstall global dependencies to include bin linking.
> yarn global remove ...
> yarn global add ...

because after doing a rollback to yarn 0.16.1, I get the following error when running `yarn`

```
/usr/local/lib/node_modules/yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/yarn/updates/0.17.0/lib/cli/index.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.Module._extensions..js (module.js:581:20)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/yarn/bin/yarn.js:39:22)
    at Module._compile (module.js:573:32)
```

**Comment by arxpoetica** [comment]
@iraklisg I'm not sure I'll be much help, but good news, they've releases a fix in `0.17.2`, so you can install the latest version of Yarn, and should be good to go.

https://github.com/yarnpkg/yarn/releases/tag/v0.17.2

**Comment by iraklisg** [comment]
@arxpoetica, indeed, I have updated yarn to  `v0.17.3` and everything seems to work fine thus far

**Comment by shuiRong** [comment]
like https://github.com/yarnpkg/yarn/issues/1824#issuecomment-260577864 said.
I can run this `yarn global add webpack@latest` well, but not this `yarn global add npm@latest`
