### ISSUE TITLE
userHome can get overridden even if process UID is not root

### ISSUE THREAD

**Issue by mattlqx** [yarnpkg/yarn#1827]
**Do you want to request a *feature* or report a *bug*?**
Bug under a certain use-case.

**What is the current behavior?**
When running Yarn from another process like Chef that can specify UID and doesn't spawn under a new shell, userHome gets overridden even though the effective UID of Yarn is not root. This can lead to Yarn trying to create directories in `/usr/local/share` even though it may not have permissions to do so.

Result of https://github.com/yarnpkg/yarn/pull/1344

This is pretty easy to workaround by simply specifying a USER environment variable (instead of letting it be `root`, which Chef runs as) in the `execute` statement, but I think the conditional to override userHome could be improved.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run `yarn` in a Chef `execute` statement with a non-root `user` attribute.

This will fail because the non-root user likely won't have permissions to write to `/usr/local/share`.

**What is the expected behavior?**
Run normally and with the user home dir specified by the HOME variable.

**Please mention your node.js, yarn and operating system version.**
6.9.1, 0.17.0, Ubuntu 16.04

**Comment by kittens** [comment]
We don't do this detection ourselves, we use the `user-home` package. Source is [here](https://github.com/sindresorhus/os-homedir/blob/master/index.js). I'd recommend opening an issue over there.

**Comment by mattlqx** [comment]
It actually is overridden somewhat by Yarn here: https://github.com/lucaskatayama/yarn/blob/91267dcb2faa46147af9699c5d3c20bfb3b64ada/src/constants.js#L4-L6

That's where the issue stems from.
