### ISSUE TITLE
`yarn` skips dev dependencies if NODE_ENV is set to "production"

### ISSUE THREAD

**Issue by kilianc** [yarnpkg/yarn#1830]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
calling `yarn` now skips dev dependencies

**If the current behavior is a bug, please provide the steps to reproduce.**

    $ NODE_ENV=production yarn ls | grep mocha # nothing
    $ NODE_ENV=development yarn ls | grep mocha # correct behavior

**What is the expected behavior?**
previous versions of yarn used to install all dependencies even with `NODE_ENV=production`. The [documentation](https://yarnpkg.com/en/docs/installing-dependencies#toc-installing-options) also explains the use of `--production` which makes this a little bit counterintuitive.

**Please mention your node.js, yarn and operating system version.**
* yarn `0.17.0`
* node `v6.9.1`
* os `debian:jessie` running on docker

**Comment by allcentury** [comment]
The behavior you've outlined matches [the docs](https://yarnpkg.com/en/docs/cli/install)

> yarn install --production

>>> Using the --production flag, or when the NODE_ENV environment variable is set to production, Yarn will not install any package listed in devDependencies

**Comment by kilianc** [comment]
@allcentury I see, you are indeed correct, I just missed that part. What threw me off is the difference between `0.16.0` and `0.17.0`.

How do I install my dev packages then ?

**Comment by allcentury** [comment]
If you need your dev packages in production promote them to the `dependencies` group.

**Comment by kilianc** [comment]
@allcentury that sounds like a workaround. I want to install my deps with the production flag on and then run the test suite.

Ideally I would build my container with `NODE_ENV=production` and then `docker run yarn --dev && ./test.sh` or something similar.

**Comment by kittens** [comment]
```sh
$ NODE_ENV=development yarn install
```

will do the equivalent of what you want. Subsequent shell commands will have the previous value of `NODE_ENV` too.

**Comment by jraoult** [comment]
If anyone is interested you can also use `.yarnrc` to override this behaviour. I did this to fix my heroku builds without having to force `NODE_ENV` to development

```
--install.production false
```

**Comment by jkerys-halo** [comment]
Finding this as bad behavior, dev dependencies are required for building application, which happens during deployments.
As a side note, Heroku is clever for this case, it installs with dev dependencies, and after running build script is pruning dev dependencies.

**Comment by w0o** [comment]
Another way to go at it is make your test command include dotenv with optionally the right config file and you can still keep dotenv as a dev dependency. Note that you will need to add the test environment variables to your pipeline (as you should).
Here's an example (from package.json/scripts):
`    "test": "DOTENV_CONFIG_PATH=.env.test NODE_ENV=test jest --config application/jest.config.js --ci",
"dev": "DOTENV_CONFIG_PATH=.env.development NODE_ENV=development node -r dotenv/config application/src/lib/app.ts"
`
works like charm and gives you flexibility to have test and dev .env files too.
