### ISSUE TITLE
"No such file file or directory, lstat" for Yarn cache during package install on Windows

### ISSUE THREAD

**Issue by AntJanus** [yarnpkg/yarn#1834]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I'm on Windows 10, Node v6.9.1, and Yarn 0.17.0

I'm running `yarn` to install packages for a [personal project](https://github.com/AntJanus/omen/blob/master/package.json) and during installation, I get the error: 

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat 'C:\\Users\\[my username]\\AppData\\Local\\Yarn\\cache\\npm-gulp-4.0.0-alpha.2-58ae6d972ff84fa07ba9cc30cf7d13d9bc646f39'".
```

I'm guessing yarn is not a big fan of the Gulp version `"github:gulpjs/gulp#4.0"` which causes it to have the above issue. Running `yarn cache clean` and redoing the install doesn't help. 

**What is the expected behavior?**

Installation without errors. Running `npm install` with npm version 3.10.8 works without a hitch.

**Please mention your node.js, yarn and operating system version.**

- Windows 10 Anniversary
- Node v 6.9.1
- Yarn 0.17.0

**Comment by adrai** [comment]
same on ubuntu

**Comment by eltuza** [comment]
same on macOs Sierra 10.12.1

**Comment by bestander** [comment]
I can confirm, this is a regression after 0.16.1

**Comment by thomaschaaf** [comment]
I tried finding the reason and could nail it down to: https://github.com/yarnpkg/yarn/blob/master/src/resolvers/exotics/hosted-git-resolver.js#L140 missing the hash attribute. This results in the package being created in the cache folder with a name without the hash (https://github.com/yarnpkg/yarn/blob/master/src/config.js#L265). After it is downloaded however the hash is set here: https://github.com/yarnpkg/yarn/blob/master/src/package-fetcher.js#L91 removing this assignment fixes the problem.

**Comment by bestander** [comment]
@thomaschaaf, would you try sending a PR with a unit test?

**Comment by thomaschaaf** [comment]
@bestander the better option would be to get the hash in https://github.com/yarnpkg/yarn/blob/master/src/resolvers/exotics/hosted-git-resolver.js#L140 here. 
Removing the hash updating seems nasty. Or we could not add a hash if a hash was not set until that point.

I am still trying to navigate through the code but can't figure out how it was done before.

**Comment by thomaschaaf** [comment]
@bestander I am sorry I can't create a unit test at the moment - as I have to be up early in the morning.

The PR should fix the problem :)

**Comment by AntJanus** [comment]
Wow that was quick! Thanks everyone! :)

**Comment by hustcer** [comment]
Same here, with yarn@0.17.0, node@7.1.0, macOS10.12.1
```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/hustcer/Library/Caches/Yarn/npm-gulp-4.0.0-alpha.2-947491601cd7d5959a48d2f305d96ef44d94b047'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/hustcer/github/swift-quant/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by warent** [comment]
Experiencing this problem in `yarn v0.17.2` on Arch Linux `4.8.7-1-ARCH`

**Comment by warent** [comment]
Interestingly, when I updated my npm prefix, per: https://docs.npmjs.com/getting-started/fixing-npm-permissions

and then I ran yarn v0.17.2, it worked fine

**Comment by webia1** [comment]
Today, same problem, windows 7, yarn 0.17.9, node 6.8.1, npm 4.0.3

**Comment by soywod** [comment]
I had the same error using `yarn@0.20.3` (but no problem with `yarn@0.19.1`)
Here my repo where I reproduced it : https://github.com/soywod/yarn-bug-1834

Main error : `Error: ENOENT: no such file or directory, lstat '/Users/clementdouin/Documents/yarn-bug-1834/node_modules/chai-fs/test/fixtures/non-existing.txt'`

Uname -a : `Darwin MAC164 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64`

Node@7.5.0

**Comment by joscha** [comment]
I am still seeing this error with `0.20.3`:

```
 ✘ joscha@canvabox  ~/dev/canva/web/ui   master  yarn cache clean
yarn cache v0.20.3
success Cleared cache.
✨  Done in 3.99s.
 joscha@canvabox  ~/dev/canva/web/ui   master  yarn install
yarn install v0.20.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/joscha/Library/Caches/web'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/joscha/dev/canva/web/ui/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by czyin** [comment]
I had the similar error with `yarn@0.21.3`, 

Arguments: 
`  /usr/local/bin/node /usr/local/bin/yarn cache ls`

Yarn version: 
 ` 0.21.3`

Node version: 
`  7.7.1`

Platform: 
`  darwin x64`

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
`  Error: ENOTDIR: not a directory, scandir '/Users/**/Library/Caches/Yarn/npm-engine.io-1.8.3-8de7f97895d20d39b85f88eeee777b2bd42b13d4/package.json'`

**Comment by bestander** [comment]
The lstat error is investigated in https://github.com/yarnpkg/yarn/issues/2629

**Comment by andrey-shostik** [comment]
```
@asus ➜  TicTacToe  npm start      
> react-native@0.35.0 start /home/andrey/react-native-0.35-stable       
> /usr/bin/env bash -c './packager/packager.sh "$@" || true' --  


ENOENT: no such file or directory, lstat '/home/andrey/vimfiles/ackrc'                                                                  
```

who can help me, i don't know that i made wrong i need run `npm start `because i have `could not connect to development server.`

**Comment by noyobo** [comment]
```
➜ dynamic-form $ yarn install
yarn install v0.21.3
warning dynamic-form: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "http://registry.npm.alibaba-inc.com/@ali/ice/download/@ali/ice-2.1.4.tgz: ENOENT: no such file or directory, utime '/Users/noyobo/Library/Caches/Yarn/npm-@ali/ice-2.1.4-b40ce1ae635f3d447053213965dabff442275dbd/lib/_components/@alife/next-dropdown/lib/index.scss'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/noyobo/home/gitlab/ice-assets/dynamic-form/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

same problem

**Comment by kellyrmilligan** [comment]
same issue here as well, os x sierra, node 6.9.2, latest yarn

**Comment by tortilaman** [comment]
Still seeing this error with github based packages on yarn `V0.27.5`

**Comment by GeeWee** [comment]
Yep - a pulling a package from github completely broke our yarn as well.

**Comment by vtno** [comment]
I have this issue with yarn 1.6.0 node v9.11.1. Are there a way to fix this without reverting to older version?

**Comment by idandrd** [comment]
same problem, yarn 1.7.0 on mac

**Comment by odragora** [comment]
Same problem, on Windows 10 WSL

**Comment by nerdofthunder** [comment]
Same problem on Ubuntu 18.04

**Comment by marcus-sa** [comment]
This keeps happening all the time, which is extremely annoying.
Clearing the cache doesn't help either.

**Comment by andsmi97** [comment]
Got the same problem while running create-react-app.
Node -v v10.7.0
yarn --version 1.12.1

**Comment by figo38** [comment]
Same issue on linux subsystem Ubuntu 18.04 for windows 10, trying to `yarn global add create-react-app`
yarn --version 1.12.3
node --version 8.12.0

**Comment by johannesschobel** [comment]
i recently ran into the same issue on windows 10 and windows 8.1 .. however, when looking for the file that was mentioned in the error description, i found out, that the **file exist but cannot be read** ... (e.g., if i try to open the file with a notepad).

When i than ran a `check disk` tool from windows it stated, that the disk had errors and needs to be repaired - which i did when i restarted the computer.

Then, the issue was resolved..

Buuuuuuuuuuuuuuuuuuuut - it emerged some weeks later again.. so i re-repaired the disk and so on, and now it works again..

Any solution for this? Because i don't think my disk is broken - it is quite new!
Thanks for your help and suggestions!

**Comment by johannesschobel** [comment]
i managed to solve the issue with running

```
yarn cache clear
rm ./yarn.lock
yarn install
``` 

This process, however, takes ages, because it downloads all packages again because you a) don't have a cache any more and your lock file has been removed.

**Comment by gitowiec** [comment]
@andsmi97 I don't know any flag but I use this script to run `yarn install` in a loop:
```
#!/bin/bash
set -x #echo on

until
    yarn install --check-files --frozen-lockfile;
do
    echo "Surprise, surprise. Let's try again..."
done
```
It is Linux script (could run on Windows WSL or MacOS, I don't know)
Put it in a file like this `yarn-install-in-loop.sh` and call it with `./yarn-install-in-loop.sh`

**Comment by gregory** [comment]
> @andsmi97 I don't know any flag but I use this script to run `yarn install` in a loop:
> 
> ```
> #!/bin/bash
> set -x #echo on
> 
> until
>     yarn install --check-files --frozen-lockfile;
> do
>     echo "Surprise, surprise. Let's try again..."
> done
> ```
> 
> It is Linux script (could run on Windows WSL or MacOS, I don't know)
> Put it in a file like this `yarn-install-in-loop.sh` and call it with `./yarn-install-in-loop.sh`

funny just found the exact same snippet here: https://github.com/yarnpkg/yarn/issues/4563#issuecomment-443375674 :)

**Comment by tombh** [comment]
I was getting this same frustrating and hard to debug error. The problem in my case seemed to be `yarn workspace` behaviour caused by different versions of the same dependency in different packages (specifically `ava` versions 2 and 3). Only once I'd upgraded all occurrences of `ava` to their latest did I stop getting this error.

**Comment by smac89** [comment]
I've noticed that this error only started occurring when I used the `--link-duplicates` option for `yarn install`

**Comment by mseyfayi** [comment]
In my case removing node_modules and installing again wirked
