### ISSUE TITLE
upgrade-interactive prompt to choose packages to update but there's none

### ISSUE THREAD

**Issue by miduga** [yarnpkg/yarn#1843]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It's showing the prompt yo choose a package when there's none to update.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Update to latest yarn version.
2. Update all packages to latest version.
3. Execute `yarn upgrade-interactive`
4. You will be prompted to choose which package to update but the list is empty.

![nov-15-2016 09-48-41](https://cloud.githubusercontent.com/assets/1561955/20298930/c41dcdc2-ab18-11e6-9058-bf9ad2a9ebfb.gif)

**What is the expected behavior?**
Show that there's no packages to update.

**Please mention your node.js, yarn and operating system version.**
node 6.9.1
yarn 0.17.0
OSX El Capitan 10.11.6

**Comment by kittens** [comment]
Created #1846 to fix this, pending approval.

**Comment by miduga** [comment]
Great! Thanks! ;)
