### ISSUE TITLE
Error: ENOENT: no such file or directory...

### ISSUE THREAD

**Issue by wellyshen** [yarnpkg/yarn#1850]
Hi, I install yarn (0.17.0) through npm (4.0.2), and my node.js (7.1.0) was installed through nvm, when I finish my yarn installing (I also setup the PATH in .zshrc) I try `yarn --version` then I get the following error message, does anyone know how to solve it?

<img width="935" alt="2016-11-15 11 17 54" src="https://cloud.githubusercontent.com/assets/21308003/20311330/5249ee34-ab8a-11e6-9233-ffedeb14da4d.png">

**Comment by wyze** [comment]
Duplicate #1724.
