### ISSUE TITLE
[0.17.0] Error while linking dependencies

### ISSUE THREAD

**Issue by shahmirn** [yarnpkg/yarn#1853]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
After running yarn install, during the linking dependencies... stage, I get the following error:

[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, chmod 'C:\\dev\
\RO.View.Dashboard.Copy\\View\\Slb.Prism.RO.View.Dashboard\\node_modules\\.bin\\html-minifier'".

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Dependencies are linked successfully

**Please mention your node.js, yarn and operating system version.**

Yarn version: 
  0.17.0

Node version: 
  6.9.1

Platform: 
  win32 x64

**Comment by bestander** [comment]
@shahmirn, can you provide a package.json which reproduces this?

**Comment by wyze** [comment]
Duplicate #1823.
