### ISSUE TITLE
Add --version flag to install script 

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1856]
Add a --version flag to allow the user to install a specific version via the installation script.

**Comment by hpurmann** [comment]
Which installation script do you mean?

If the package is up-to-date in the `apt-get` repository (which 0.17.0 is _not_ btw), you can just specify it with `apt-get install -y yarn=0.17.0`.

**Comment by Daniel15** [comment]
@hpurmann This one: https://yarnpkg.com/install.sh. It's an alternative method of installing Yarn. It currently supports a `--nightly` flag to install the latest nightly build, we should add something like `--version` too 😄

**Comment by Daniel15** [comment]
Fixed by #1928
