### ISSUE TITLE
`yarn help add` missing "short help" for --ignore-optional

### ISSUE THREAD

**Issue by markstos** [yarnpkg/yarn#1857]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`yarn help add` shows no documentation for `--ignore-optional`

**What is the expected behavior?**

`yarn help add` should show documentation for `--ignore-optional`

**Please mention your node.js, yarn and operating system version.**

Node.js 4.4.2.

**Comment by kittens** [comment]
Fixed by #1868.
