### ISSUE TITLE
yarn global add bower --prefix /usr/local should add binary or link in /usr/local/bin

### ISSUE THREAD

**Issue by dev-jpctrade** [yarnpkg/yarn#1877]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
yarn global add bower --prefix /usr/local does nothing in /usr/local/bin folder

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Have binary or link in /usr/local/bin

**Please mention your node.js, yarn and operating system version.**
7.1.0, 0.17.2, debian/8

PS: close if this is a dup, couldn't find exact one.

**Comment by vega-wong** [comment]
I have the same problem.  I can't find the link in the path which print from  'yarn global bin' after i run 'yarn global  add pm2'. How can i resolve it?

**Comment by vitorgalvao** [comment]
Confirmed on macOS `10.11.6` as well.

**Comment by colkito** [comment]
same issue!
macOS sierra, node 7.1.0, yarn 0.17.2

**Comment by RickyLin** [comment]
Same issue. 
Mac OS Sierra 10.12.1, node 7.1.0, yarn 0.17.2
Node and Yarn are installed via brew.

**Comment by akloeber** [comment]
Confirmed on Ubuntu 14.04.5 LTS, node 4.6.2 LTS, yarn v0.17.2 after installing pm2 globally which logs:
```
root@vagrant-ubuntu-trusty-64:~# yarn global add pm2
yarn global v0.17.2
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
⠁
⠁
⠁
⠁
error Error running install script for optional dependency: "/usr/local/share/.config/yarn/global/node_modulessuccess Installed pm2@2.1.5 with binaries:
      - pm2
      - rundev
      - pm2-dev
      - pm2-docker
Done in 8.79s.
```
No pm2 binary has been linked at `/usr/bin/pm2` (`yarn global bin` returns `/usr/bin`).

**Comment by dev-jpctrade** [comment]
looks like it fixed on 0.17.3 with additional parameters, closing

`
yarn global add bower --prefix=/usr/local --global-folder /usr/local/lib/node_modules
`

**Comment by akloeber** [comment]
With yarn v0.17.3 after running  
`# yarn global add pm2 --prefix /usr/local --global-folder /usr/local/lib/node_modules`

linking of binaries into the `bin` folder seems to be working but a folder `/usr/local/lib/node_modules/node_modules` gets created with the node modules inside.

This causes additional errors which I suppose are related to this directory structure:
```
# pm2 version
module.js:327
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node_modules/pm2/constants.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Furthermore IMHO installation of global modules via `yarn global add` without any special requirements should just work on any platform without having to define additional parameters. Otherwise I suppose this will cause trouble for lots of users.

**Comment by akloeber** [comment]
When using `yarn global add pm2 --prefix /usr/local --global-folder /usr/local` instead pm2 is working as expected but the resulting folder structure with having modules directly under `/usr/local/node_modules` (should be `/usr/local/lib/node_modules`) and `package.json`/`yarn.lock` directly under `/usr/local`  is kind of sub-optimal.

**Comment by dev-jpctrade** [comment]
ok, reopened, my original post was a feature request, but this become bug report.

**Comment by torifat** [comment]
Please open a new issue reporting the `--global-folder` bug. This is not a `--prefix` bug.

And, try `yarn global add pm2 --prefix /usr/local`

your don't need `--global-folder /usr/local` to install in `/usr/local/bin`

**Comment by torifat** [comment]
If anyone else having trouble with `--prefix /usr/local` then please first remove the package `yarn global remove <package>`, and then try `yarn global add <package> --prefix /usr/local`. If it still doesn't work then report, we will reopen this issue.

**Comment by nragaz** [comment]
@torifat  I'm still not seeing the correct behaviour after e.g.:

```
$ yarn global remove bower
$ yarn global add bower --prefix /usr/local
$ bower
-bash: /usr/local/bin/bower: No such file or directory
```

**Comment by torifat** [comment]
@nragaz what is your yarn version?

**Comment by jonnybarnes** [comment]
For me `yarn global add --prefix /usr/local <package>` worked, and the binary was sym-linked to `/usr/local/bin` properly. Does `--prefix /usr/local` need to be added to `yarn global upgrade` going forward?

**Comment by colkito** [comment]
what is your yarn version and OS? @jonnybarnes

**Comment by jonnybarnes** [comment]
yarn `v0.17.8` running on Arch Linux. yarn was installed from the AUR: https://aur.archlinux.org/packages/yarn/
