### ISSUE TITLE
Does not upgrade tagged packages

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#1884]
Example of installing tagged version: 
```
yarn add typescript@next
```

it installs last version with tag `next` (i.e `typescript@2.2.0-dev.20161101`) and adds to `package.json` (which is **not compatible with NPM** I think):
```
"typescript": "next"
```

Few days later version is updated: but `yarn upgrade typescript`, `yarn add typescript@next` or something doesn't upgrade this version to the last have to remove package and add it again.

**Comment by JakeGinnivan** [comment]
This is related to #2788 I think, really annoying issue as I have to remove and re-add the dependency which causes all transitive dependencies to bump at the same time causing much more churn than I would like.

**Comment by rally25rs** [comment]
Going to close this as a duplicate #2788 (even though this issue was filed first, but the other has a more detailed summary)
