### ISSUE TITLE
[regression] [0.17.2] Yarn global add doesn't add the binary nor warn

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#1886]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If I do `yarn global add angular-cli` as a user, the binary is nowhere to be found.

**What is the expected behavior?**

Either yarn should warn me that it cannot link the binary to /usr/bin or at least there should be, like before, a `.bin` directory inside `~/.config/yarn/global/node_modules`.

**Please mention your node.js, yarn and operating system version.**
yarn 0.17.2

**Comment by victornoel** [comment]
Actually, even if the prefix is set to something like `~/.config/yarn/bin`:
```
➜  ~ yarn global bin
/home/vnoel/.config/yarn/bin
```

The binary does not seem to be present there!

**Comment by VincentChataignier** [comment]
Same issue (v0.17.2) with `yarn global add grunt-cli` in debian. Command `grunt` is not found.
