### ISSUE TITLE
Not deduping

### ISSUE THREAD

**Issue by OliverJAsh** [yarnpkg/yarn#1890]
Given `package.json`

``` json
{
  "name": "yarn-dedupe-test",
  "private": true,
  "dependencies": {
    "tsify": "0.16.0",
    "typescript": "1.8.7"
  }
}
```

If I `npm install && npm ls typescript` I get

```
❯ npm ls typescript
yarn-dedupe-test@1.0.0 /Users/OliverJAsh/Development/temp/yarn-dedupe-test
├── UNMET PEER DEPENDENCY browserify@>= 6.x
└── typescript@1.8.7
```

Notice there is only one version of TypeScript.

If I instead run `yarn` I get:

```
❯ yarn ls
…
├─ tsify@0.16.0
│  ├─ commondir@^1.0.1
│  ├─ convert-source-map@^1.1.0
│  ├─ through2@^2.0.0
│  ├─ tsconfig@^2.2.0
│  ├─ typescript@~1.8.7
│  └─ typescript@1.8.10
├─ typescript@1.8.7
…
```

Notice there are two versions of TypeScript, even though the specified 1.8.7 should satsify the requirements of tsify.

**Comment by wyze** [comment]
Which version are you using? My output on `0.17.2`/`master`:

```sh
$ yarn ls
...
├─ tsify@0.16.0
│  ├─ commondir@^1.0.1
│  ├─ convert-source-map@^1.1.0
│  ├─ through2@^2.0.0
│  ├─ tsconfig@^2.2.0
│  └─ typescript@~1.8.7
├─ typescript@1.8.7
...
```

**Comment by OliverJAsh** [comment]
0.16.1. I will try updating.

**Comment by olingern** [comment]
@wyze I belive @OliverJAsh is speaking to the second level typescript dependency of tsify. Perhaps the question is: "If a root dependency already appears on the tree, should it also appear in children if version is the same?"

I've actually wondered about this, too.

**Comment by wyze** [comment]
@olingern, his output is different though, and actually list typescript 3 times, whereas ours only listed it twice.

I know there is the issue open on the website project to clarify what `yarn ls` is actually showing though.

**Comment by olingern** [comment]
> his output is different though, and actually list typescript 3 times, whereas ours only listed it twice.
@wyze Overlooked that! 

> I know there is the issue open on the website project to clarify what yarn ls is actually showing though.
I see. npm seems to not display packages that are parents as children ( typescript in this case ), which I'm not sure I agree with because it's misleading. The current yarn functionality seems more accurate.

**Comment by OliverJAsh** [comment]
I can confirm my issue has gone in 0.17.2:

```
❯ ls node_modules/tsify/node_modules/
```

Empty dir, which is good :-) It's sharing TypeScript with the parent module
