### ISSUE TITLE
Private repositories as dependencies don't work in FreeBSD 10.2

### ISSUE THREAD

**Issue by martynchamberlin** [yarnpkg/yarn#1892]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unable to use Yarn in a FreeBSD VM

**If the current behavior is a bug, please provide the steps to reproduce.**
We are migrating from using NPM to Yarn. 

When I run `yarn`, I get this output: 

```
yarn install v0.17.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
████████████████████████████████████████████████████████████████████████████ 1111/1112
```

It locks up at this 99% mark of Step 2. The process is idling, `I+`, doing nothing. 

When I run the exact same command outside the VM in the same directory, the command executes just fine (my host is macOS Sierra). Something is seemingly locking up in the VM and I'm not sure what it is. 

I'm using Unison to synchronize files back and forth between my host and VM, although file synchronization shouldn't have any bearing on this issue, I don't think. 

**What is the expected behavior?**
To be able to install yarn within FreeBSD. 

**Please mention your node.js, yarn and operating system version.**

- node v6.1.0
- yarn 0.17.2
- FreeBSD 10.2

**Comment by bestander** [comment]
@martynchamberlin, can you narrow it down to what packages can't be installed this way?

**Comment by martynchamberlin** [comment]
@bestander Oh, you know what. It's a custom one. I narrowed it down to this entry:

```
"our-repo": "git+ssh://git@github.com/AccountName/our-repo.git#56f3954",
```

Interestingly, two others of our custom ones work fine, but this one doesn't for some reason in FreeBSD (but it does just fine in macOS).

**Comment by martynchamberlin** [comment]
After doing more digging, I narrowed it down to that specific ##56f3954 sha that was causing grief. Other shas would cause it to work just fine. It was specifically the #56f3954 sha that was causing it to lock up. 

After doing a bunch of troubleshooting trying to figure out what might be the problem specifically with this sha, the problem went away. Vanished. Now I can't replicate it, even with the #56f3954 sha.

Super weird. I guess we can close this.

**Comment by bestander** [comment]
It is weird.
Please try clearing caches on your FreeBSD system and check again.
If problem persists reopen the issue with details how to reproduce.
Thanks for the report.

**Comment by martynchamberlin** [comment]
Yeah. As I think about it, I ran a command to refresh the VM and that might have been the turning point when it started working.

**Comment by martynchamberlin** [comment]
@bestander All right, I've got more information on this, and I think I know what the problem is. 

Let's say our package.json has 2 private repo dependencies. We'll call them A and B. Now, let's say that repo B has its own package.json dependencies. One of them is repo A. Maybe a visual will help clarify what I mean: 

```
Main Repo
│
├── Dependency A, sha #7608556
│
└── Dependency B
    └── Dependency A, sha #e3f4712
```

This is what caused us to get to 99% of Step 2 of `yarn` and then stop. The SHAs we'd specified 

The way we fixed it is we manually removed the folders for Dependency A and Dependency B from our `node_modules` directory and then re-ran `yarn`. Worked like a charm. 

Perhaps if a package needs another package that's part of the main package list, it breaks yarn unless you start from scratch, because npm and yarn have different ways of resolving those? Just a theory. 

Anyway, I can't re-open this issue since you closed it. Want me to create a new issue, or modify the description of this one, or how is best to proceed here?

**Comment by bestander** [comment]
@martynchamberlin, can you open the new issue with all the specifics to what you have found?
Otherwise the first comments will be misleading for people.

**Comment by martynchamberlin** [comment]
@bestander Looks like all of our problems with this have gone away with upgrading to Node 6.9.1. Unless you're interested in making this compatible with an outdated version of node (I doubt I would!) then let's blow this off.

**Comment by bestander** [comment]
Wow, very odd, thanks for letting us know, @martynchamberlin
