### ISSUE TITLE
yarn --version triggers ENOENT error before first install

### ISSUE THREAD

**Issue by akloeber** [yarnpkg/yarn#1894]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When requesting the version of yarn after installation the following error is thrown:
```
root@vagrant-ubuntu-trusty-64:~# yarn --version
0.17.2
/usr/share/yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/usr/local/share/.cache/yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at /usr/share/yarn/node_modules/roadrunner/index.js:25:6
    at /usr/share/yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at processEmit [as emit] (/usr/share/yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (node.js:766:17)
    at Command.<anonymous> (/usr/share/yarn/node_modules/commander/index.js:825:13)
```

After installing any global module `/usr/local/share/.cache/yarn/.roadrunner.json` is present and `yarn version` gives the correct output:
```
root@vagrant-ubuntu-trusty-64:~# yarn global add pm2
...
root@vagrant-ubuntu-trusty-64:~# yarn --version
0.17.2
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- install via `dpkg -i yarn_0.17.2_all.deb`
- run `yarn --version`

**What is the expected behavior?**
yarn should only print version number `0.17.2`.

**Please mention your node.js, yarn and operating system version.**
node 4.6.2
yarn 0.17.2
Ubuntu 14.04.5 LTS

**Comment by lyushenko** [comment]
Having the same issue on MacOS with yarn 0.17.3 installed via npm.

**Comment by wyze** [comment]
Duplicate #1724.
