### ISSUE TITLE
Dockerfile/Vagrantfile for developing on Yarn

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1903]
Inspired by (although somewhat tangential to) this Twitter thread: https://twitter.com/Daniel15/status/799044089035440141

We should add a Dockerfile or Vagrantfile for people that want to develop on Yarn itself, such that there's a consistent development environment and it's easy for people to get started.  There's already third-party Dockerfiles for using Yarn, but nothing for actually developing on Yarn itself.

Maybe Ubuntu or Debian based.

**Comment by torifat** [comment]
I can work on it. I already use one for testing bug 😄

**Comment by torifat** [comment]
@Daniel15 need your suggestion. Currently we have a chicken egg problem in the first run.

**Comment by Daniel15** [comment]
> Currently we have a chicken egg problem in the first run

Is the issue that you need Yarn to install its dependencies? You can install a stable version of Yarn within the Docker container to deal with that, something like this:
```
RUN apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install yarn -y
```

Then you'll have a stable version of Yarn installed, then you can do `yarn install` to install dependencies for the dev version of Yarn. 👍

**Comment by torifat** [comment]
@Daniel15 yeah, I was thinking something similar 😄. Instead of installing it directly I wanted to extract it in `/opt/yarn-stable`. And, I'm linking the development folder to `/opt/yarn`.

**Comment by viztastic** [comment]
Any luck with this? I'd love to help with testing etc.

**Comment by Daniel15** [comment]
I'm going to be moving Yarn to CircleCI 2.0, which uses Docker. I'm going to try creating a Dockerfile for that purpose, and perhaps it could be reused for development as well. The CircleCI team have already created a Dockerfile for this purpose (https://raw.githubusercontent.com/ryanwohara/yarn/circleci-2.0/Dockerfile), I might reuse parts of their Docerfile.

**Comment by Daniel15** [comment]
https://github.com/yarnpkg/yarn/pull/2628

**Comment by Daniel15** [comment]
Pushed to Docker Hub: https://hub.docker.com/r/yarnpkg/dev/
