### ISSUE TITLE
yarn upgrade - weird behaviour

### ISSUE THREAD

**Issue by tomitrescak** [yarnpkg/yarn#1904]
**What is the current behavior?**

Yarn does not upgrade the package when requested with `yarn upgrade apollo-mantra`

1. In my package json version of the package is: `"apollo-mantra": "^1.3.0"`
2. I modify the package and publish a new version to npm, with new version "1.3.1:"
3. I perform `yarn upgrade apollo-mantra` and I get 0 updated dependencies

This is in my lock file:

```
apollo-mantra:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/apollo-mantra/-/apollo-mantra-1.3.0.tgz#e68598296b7bee259c3194d44c6b2158829627c8"
```

Also, after every attempt, yarn adds the reference into main dependencies.

**Comment by torifat** [comment]
Please don't ignore issue template.

**Please mention your node.js, yarn and operating system version.**

**Comment by torifat** [comment]
I couldn't reproduce it.

```
$ yarn add apollo-mantra@1.3.0
$ yarn upgrade apollo-mantra
$ yarn ls
yarn ls v0.18.0-0
warning No license field
└─ apollo-mantra@1.3.2
✨  Done in 0.07s. 
```

**Comment by tomitrescak** [comment]
It's MAC OS, node 6.3.1

It's different to reproduce as your way works for me as well:

1. Install a `package` at version 1.2.0
2. Bump `package` on npm to 1.2.1
3. yarn upgrade `package` **WORKS**
4. Bump `package` on npm to 1.2.2
5. yarn upgrade `package` **DOES NOT WORK**

The only way to upgrade at this moment is yarn upgrade `package@1.2.2`

**Comment by torifat** [comment]
I have tested it. It seems like a caching thing. Yarn registry takes about 5mins to catchup after publishing a new version in `npm`.

**Comment by tomitrescak** [comment]
So, I guess the only way is to use upgrade to a specific version. I guess we can close it then.
