### ISSUE TITLE
set cache-path did not change yarn cache dir

### ISSUE THREAD

**Issue by Tomyail** [yarnpkg/yarn#1905]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

set cache-path did not change yarn cache dir.

` yarn cache dir`  **always** return `/Users/username/Library/Caches/Yarn`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `yarn config set cache-path /my/own/yarn/cache/path`
2. `yarn cache dir`

**What is the expected behavior?**

`yarn cache dir` should return `/my/own/yarn/cache/path`. and use `yarn add package` should download cache to `/my/own/yarn/cache/path`.

**Please mention your node.js, yarn and operating system version.**
1. yarn 0.17.3
2. node v5.5.0
3. npm 3.3.12
4. os  macOS 10.12.2 Beta

**Comment by kevin-smets** [comment]
Between v0.17.6 and v0.17.9 it has moved to `/Users/kevin/Library/Caches/Yarn`. Changing it still does not work though.

**Comment by Tomyail** [comment]
close this issue because #2046  add this feature 😄

**Comment by kevin-smets** [comment]
Hmmm, does not seem to be resolved, according to the changelog #2046 has landed in v0.18.0 (https://github.com/yarnpkg/yarn/releases/tag/v0.18.0), but my output is the following:

```
yarn cache dir
yarn cache v0.18.0
/Users/kevin/Library/Caches/Yarn

yarn config set cache-path /Users/kevin/Development/git/.yarn-cache
yarn config v0.18.0
success Set "cache-path" to "/Users/kevin/Development/git/.yarn-cache".

yarn cache dir
yarn cache v0.18.0
/Users/kevin/Library/Caches/Yarn
```

That does not seem right to me. And it's not like it's just the reporter that is wrong, after an install:

```
cd /Users/kevin/Development/git/.yarn-cache
zsh: no such file or directory: /Users/kevin/Development/git/.yarn-cache
```

The cache is still being populated @ /Users/kevin/Library/Caches/Yarn.

**Comment by superxp1412** [comment]
@kevin-smets 
Please use "cache-folder" instead of "cache-path" for the configurations.

The documentations haven't been updated. I'm trying to figure out a way to update documents.

**Comment by kevin-smets** [comment]
Aha, awesome. A bit confusing those two terms.

That seems to work as intended, thanks a lot!
