### ISSUE TITLE
Support relative paths for local packages

### ISSUE THREAD

**Issue by csvan** [yarnpkg/yarn#1907]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Does not support local paths

**What is the expected behavior?**
Would be nice if it did

**Please mention your node.js, yarn and operating system version.**
Node 6.9.1, Yarn 0.17.3, Windows 7 Enterprise

Say I have a local package in my project root which is also in the NPM registry (e.g. `angular-fullscreen` in our case), located at `./locals/angular-fullscreen`. I add it to my `package.json` as follows:

```
    "angular-fullscreen": "./locals/angular-fullscreen,
```

NPM finds and installs it just fine, but Yarn yields:

```
error Couldn't find any versions for "angular-fullscreen" that matches "./locals/angular-fullscreen". 
```

However, it does work if I instead specify the full path and protocol:

```
    "angular-fullscreen": "file://fullpath/locals/angular-fullscreen,
```

I know (or think?) that Yarn is not supposed to be a drop-in replacement for NPM, but it would be nice if this worked out of the box.

**Comment by wyze** [comment]
Duplicate #1698.

**Comment by wyze** [comment]
Could you please add your information there. The issue is the same, but your relative path is different than the one mentioned in the other issue.
