### ISSUE TITLE
inconsistent state of package.json/yarn.lock on execution error

### ISSUE THREAD

**Issue by maybeec** [yarnpkg/yarn#1912]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In case of errors like #1861, yarn may finish in an invalid state. It happened to me while removing a dependency, which has been removed from the package.json, but not from the yarn.lock. Subsequent executions of the command resulted in 

```
$ yarn remove bootstrap-css-only
yarn remove v0.17.3
[1/2] Removing module bootstrap-css-only...
error This module isn't specified in a manifest.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
As try to remove some dependencies while having scoped packages in you build as well. As #1861 is not determinitic, you may have to do it some times to reproduce.

**What is the expected behavior?**
When failing, yarn should preserve the consistency of package.json and yarn.lock

**Please mention your node.js, yarn and operating system version.**
yarn 0.17.3
win7 64bit
node 6.9.1

**Comment by bestander** [comment]
Agree, I think we silence errors in build phase, this should not happen

**Comment by bestander** [comment]
Please send a PR and test

**Comment by paul-soporan** [comment]
In case this hasn't already been fixed in v1, it's definitely fixed in v2 (https://yarnpkg.com/getting-started/migration), so closing.
