### ISSUE TITLE
Ability to link global binaries directly to prefix folder

### ISSUE THREAD

**Issue by soredake** [yarnpkg/yarn#1913]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
My prefix folder is ~/ybin
Yarn links binaries to ybin/bin

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Ability to link directly to ~/ybin

**Please mention your node.js, yarn and operating system version.**

**Comment by S-YOU** [comment]
Thats not how Unix/Linux systems works, has to be different name other than `prefix`
