### ISSUE TITLE
Wrong dependency installed for React Router 4

### ISSUE THREAD

**Issue by steida** [yarnpkg/yarn#1922]
'npm install' installs history 4.4.0, while yarn for some reason installs 4.3.0

![screen shot 2016-11-17 at 23 54 31](https://cloud.githubusercontent.com/assets/66249/20411366/7e228dfc-ad21-11e6-8fc2-d06f2bb296ea.png)

**Comment by hpurmann** [comment]
Can't reproduce locally. I installed `react-router@^4.0.0-alpha.5` both with `npm` and `yarn` and `history` is always at `4.4.0`.

**Comment by steida** [comment]
I will try to reset cache.

**Comment by steida** [comment]
Hmm, still "version": "4.3.0". Can you please check this package json?https://github.com/este/este/blob/d5232784a94be7eda6218f3ba1f1749f7f969ef8/package.json

**Comment by hpurmann** [comment]
Ok this seems indeed like a weird bug in `yarn`. Very interesting case you got here.

Steps to reproduce:
1. Clone [este](https://github.com/este/este/) and do a checkout on [`d5232784a94be7eda6218f3ba1f1749f7f969ef8`](https://github.com/este/este/blob/d5232784a94be7eda6218f3ba1f1749f7f969ef8/package.json)
1. Do a `yarn install` (tried with current `master`, `b84fde34`).

**Comment by torifat** [comment]
I just tried with the `package.json` he provided. And, I'm getting `4.4.0` with latest `master`.

```
❯ cat node_modules/history/package.json | jq '.version'
"4.4.0"
```

@hpurmann Can you please try once after `yarn cache clean`

**Comment by torifat** [comment]
Sorry, my bad.

**Comment by hpurmann** [comment]
You have to `cat node_modules/react-router/node_modules/history/package.json` 😜

**Comment by torifat** [comment]
`yarn add react-router@4.0.0-alpha.5` produces the same thing for me.

**Comment by torifat** [comment]
https://registry.yarnpkg.com/react-router/-/react-router-4.0.0-alpha.5.tgz#9d80514f9bbbec040dffbd4f9cf241da2830e318 has `history` `4.3.0` inside the `node_modules` folder. 😄

**Comment by torifat** [comment]
Or, to be precise https://registry.npmjs.org/react-router/-/react-router-4.0.0-alpha.5.tgz

Since this is an `alpha` release of `react-router` I don't find any reason to report it. But, if you guys feel like you can.

**Comment by steida** [comment]
But why `npm i` works while yarn not?

**Comment by hpurmann** [comment]
Oh ok, that's rare that a package publishes its `node_modules` folder.

How can this happen though? I thought that npm ignores `node_modules` by default when publishing.

Btw @torifat you are right of course, `yarn add react-router@4.0.0-alpha.5` is sufficient to reproduce. I apparently made the same mistake in the beginning and looked into the root `node_modules`.

@steida: It seems that `npm` does some extra work to remove the `node_modules` folder inside of the downloaded package. It should be there in the first place. I don't think `yarn` should do this as well. So far, yarn gives the impression of trying to _not_ be defensive (for reference, see the explanation on shrinkwrap files not being taken into account (which I like by the way)).

**Comment by timdorr** [comment]
(Router dev here)

Oh, that's a bad push on our part then. I have no idea why that was included (maybe the tarball was manually constructed?). It's certainly not the norm. We have a number of things outstanding on master that haven't been pushed, so I'll see about getting another version pushed and unpublishing that version.
