### ISSUE TITLE
GPG sign Yarn release tarballs

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1923]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Yarn's release tarballs (eg. https://yarnpkg.com/latest.tar.gz) are not GPG signed

**What is the expected behavior?**
Tarballs should be GPG signed, and the installer should verify the signature. This will increase the security to match that of the Debian repo.

Install script should not fail if GPG is not installed.

**Comment by hpurmann** [comment]
That would be really nice indeed!
