### ISSUE TITLE
Yarn Rebuild Fails w/ Multiple Node Versions + Cache

### ISSUE THREAD

**Issue by hnryjms** [yarnpkg/yarn#1937]
When using NVM or some other type of version manager for Node.js, the new location for caches in `0.17`, which is shared between NVM installations, is reused between the different Yarn installations in the individual NVM version's global package path. This causes errors with modules like [`bcrypt`](https://github.com/kelektiv/node.bcrypt.js), which must be built uniquely for specific Node versions at install time.

```sh
echo '{}' > package.json
nvm install 6
npm install -g yarn
yarn add bcrypt
node -e "require('bcrypt')"

rm -rf node_modules

nvm install 7
npm install -g yarn
yarn install
node -e "require('bcrypt')"
```

The second time you run the `yarn install` command, the installation will copy the pre-built binary of `bcrypt` from Node.js v6 for use in Node.js v7, and any script trying to `require('bcrypt')` will fail with a similar error to below:

```
Error: Module version mismatch. Expected 46, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/Users/Hank/Developer/sample-bug/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/Hank/Developer/sample-bug/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

The current workaround is to run `yarn cache clean` before install, which then slows the install because all packages must be re-fetched.

I have tested and reproduced this will all versions of `yarn@0.17.x` using either macOS and Linux.

**Comment by hpurmann** [comment]
Thanks for reporting this. Found out about this yesterday as well and didn't take the time yet to report it in detail.

**Comment by bestander** [comment]
Related to https://github.com/yarnpkg/yarn/issues/2035.
I think cache should be invalidated based on yarn and node version

**Comment by bestander** [comment]
With Yarn 0.24.3 on MacOS this works fine
