### ISSUE TITLE
Error with yarn global upgrade

### ISSUE THREAD

**Issue by kalch** [yarnpkg/yarn#1946]
**What is the current behavior?**

See trace in the yarn error log below.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.  Make sure your system has zero yarn global packages.
2. yarn global upgrade

**What is the expected behavior?**

No error.

**Please mention your node.js, yarn and operating system version.**

'cat /Users/mfk/.config/yarn/global/yarn-error.log'

Arguments:
  /usr/local/Cellar/node/7.1.0/bin/node /usr/local/bin/yarn global upgrade

PATH:
  /Users/mfk/bin:/usr/local/bin:/Users/mfk/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/mfk/.yarn/bin:/Users/mfk/.yarn-config/global/node_modules/.bin:/Users/mfk/.npm-packages/bin

Yarn version:
  0.17.4

Node version:
  7.1.0

Platform:
  darwin x64

npm manifest:
  No manifest

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: ENOENT: no such file or directory, open '/Users/mfk/.config/yarn/global/node_modules/.yarn-integrity'

**Comment by pshkrjshnde** [comment]
Happens on `$ yarn upgrade` too, if no package is installed

**Comment by bmonty** [comment]
I had this same problem.  After upgrading to yarn 0.17.6, I deleted all of the .yarn* directories in my home directory and reinstalled my global packages.  The ENOENT error went away.

**Comment by kalch** [comment]
Did what you did Benjamin.  All good now.  Thanks!
