### ISSUE TITLE
Invalid tar file (error occurred)

### ISSUE THREAD

**Issue by pumano** [yarnpkg/yarn#1948]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

error An unexpected error occurred: "https://registry.yarnpkg.com/@types/node/-/node-6.0.48.tgz: invalid tar file".

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ npm install yarn
$ ./node_modules/.bin/yarn install
yarn install v0.17.6
info No lockfile found.
warning test-storage@0.2.38: Dependency "path" listed in "dependencies" is the name of a built-in module
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types/node/-/node-6.0.48.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/pumano/test-storage/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "./node_modules/.bin/yarn install" failed and exited with 1 during .
```

**What is the expected behavior?**

Proper installation without errors

**Please mention your node.js, yarn and operating system version.**
node : 4.6.2
npm  : 2.15.11
nvm  : 0.32.0
yarn  : 0.17.6
**Additional details**
https://travis-ci.org/pumano/test-storage/jobs/177194468

**Comment by wyze** [comment]
Duplicate #1619.
