### ISSUE TITLE
package dependencies are hoisted as parents

### ISSUE THREAD

**Issue by olingern** [yarnpkg/yarn#1953]
**Do you want to request a *feature* or report a *bug*?**
Question / Bug

**What is the current behavior?**
Currently, yarn hoists child dependencies on the "root" level. It's been apart of the [codebase for a while](https://github.com/yarnpkg/yarn/blob/246e2085d79f3439ea62eb1944b07bf76e60ab40/src/package-hoister.js#L161), so I'm wondering if it's by design. 

If it _is_, then my next question would be: doesn't this pollute output / show unnecessary duplicates?

**If the current behavior is a bug, please provide the steps to reproduce.**  
1. Create an empty project
2. `yarn add jquery right-pad url`
3. `yarn ls`
3. Dependencies _punycode_ and _querystring_ are duplicated:
<img width="198" alt="screen shot 2016-11-19 at 4 10 55 pm" src="https://cloud.githubusercontent.com/assets/1470297/20458420/d9398a5e-ae72-11e6-8a5a-776d7b09585b.png">

**What is the expected behavior?**
1. Duplicates shouldn't be shown
2. Needs clarification, but: _children shouldn't appear on root level_

**Related**
I'm currently working through #1845, if this is a bug - I can send a PR 😃

**Comment by olingern** [comment]
ping @wyze @bestander   ... Any thoughts on this? I'd like to keep hacking away at #1845

**Comment by bestander** [comment]
I think light grey shows that packages are physically located there.
And light grey shows where they should have been if they were not deduped.
Looks correct to me

**Comment by olingern** [comment]
@bestander So, all children should be flattened and appear at their root level _and_ under their parent? It seems difficult to track down where children are installed in larger projects, i.e. are they required by my project or a package that my project requires?

**Comment by bestander** [comment]
That is how npm@3 works - it flattens the tree as much as possible.
This has a few advantages:
- shorter file paths, especially useful for Windows limitations
- a subdependency that is reused a lot will be installed only once.

**Comment by olingern** [comment]
I see. Thanks, all makes sense now. 

I could see some value in a `--unflatten` command, but issue for another time. Maybe I'll make a PR to the [`ls` documentation](https://yarnpkg.com/en/docs/cli/ls) that explains this. I think understanding the implicit motivations behind flattening provides a small 'aha' moment.

**Comment by olingern** [comment]
Closing this as a non-issue
