### ISSUE TITLE
`ENOENT: no such file or directory` error when upgrading Yarn.

### ISSUE THREAD

**Issue by skevy** [yarnpkg/yarn#1960]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When upgrading Yarn from 0.17.0 to 0.17.6, I get this error upon running Yarn:

```
Error: ENOENT: no such file or directory, open '/Users/adam/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/node_modules/bl/node_modules/readable-stream/duple
x.js'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Upgrade Yarn, run any `yarn` command.

**What is the expected behavior?**

It should not error.

**Please mention your node.js, yarn and operating system version.**

Node 6.9.1
Yarn 0.17.6
macOS 10.12.1

**Comment by skevy** [comment]
After further investigation, I was able to determine this had to do with the `roadrunner` package (https://github.com/kittens/roadrunner).

It seems that roadrunner.json had an out of date package cache. Upon deleting the roadrunner.json file, Yarn began working as expected.

I think this should stay open, however, as this broke on all of my coworkers machines upon our upgrade of Yarn, + it also broke on our CI machines.

**Comment by bestander** [comment]
I think this is a related problem https://github.com/yarnpkg/yarn/issues/1854
