### ISSUE TITLE
Module build failed jpegtran-bin

### ISSUE THREAD

**Issue by xiehurricane** [yarnpkg/yarn#1963]
There is a error i can't fix it.

project : https://github.com/ipselon/react-boilerplate
I use yarn install dependencies;
I found a error  When visit localhost:3000:
________________
```
JadedeMacBook-Pro:codegen_yarn jadexie$ yarn start
yarn start v0.17.6
$ cross-env NODE_ENV=development node server
Server started ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.0.106:3000
-----------------------------------
Press CTRL-C to stop

webpack built 7354d9bcf2f3f2ddd382 in 4185ms

ERROR in ./app/components/Header/banner.jpg
Module build failed: Error: spawn /Users/jadexie/Desktop/Hxgy/Frontend/codegen_yarn/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./app/components/Header/index.js 47:0-34
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi main
Child html-webpack-plugin for "index.html":
```

_________________
`npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8'
yarn:v0.17.6`

btw:npm works.

**Comment by hpurmann** [comment]
I can't reproduce this here. Can you clean your cache with `yarn cache clean` and try again?

macOS Sierra `10.12.1`, node `6.9.1`, yarn `0.17.6`

**Comment by xiehurricane** [comment]
Thank you all the same.
Today, i can't reproduce this too.囧

**Comment by vimal1083** [comment]
I am not sure, what the exact issue but below resolved mine.

mv ./app/components/Header/banner.jpg ./app/components/Header/banner.jpg_
touch ./app/components/Header/banner.jpg

**Comment by jnaklaas** [comment]
Rebuilding jpegtran-bin did it for me:
```
yarn add --force jpegtran-bin
```
