### ISSUE TITLE
yarn self-update loses globally installed packages

### ISSUE THREAD

**Issue by mickeyvip** [yarnpkg/yarn#1966]
I have several packages added globally and they are listed when running

```
$ yarn global ls
yarn global v0.16.1
info package1@0.1.0 has binaries:
    - package1
info package2@0.1.0 has binaries:
    - package2
✨  Done in 2.04s.
```

after running

```
$ yarn self-update
```

there are no packages:

```
$ yarn global ls
yarn global v0.17.6
✨  Done in 0.06s.
```

While the binaries are left untouched and I can run them in command line.

Steps to reproduce:

1. Install a global package(s) and see them when running `yarn global ls`.
2. Upgrade Yarn
3. Run `yarn global ls`

There is nothing shown.

Is this the expected behavior?

Node.js `6.9.1`
Yarn `0.16.1` -> `0.17.6`
macOS Sierra `10.12.1`

**Comment by bestander** [comment]
We removed self-update becuase it was a poorly designed feature.
Better rely on the other installation mechanisms

**Comment by mickeyvip** [comment]
@bestander, the same loss of global installations happened when upgrading with `homebrew`.
