### ISSUE TITLE
Test run modifies __tests__/fixtures/request-cache/GET/localhost/.bin

### ISSUE THREAD

**Issue by hpurmann** [yarnpkg/yarn#1967]
After running `yarn test-only` in this project, `__tests__/fixtures/request-cache/GET/localhost/.bin` is modified. It updates the "Date" field. I think a test run should never modify files checked in to version control.

Checked-in version:
```
HTTP/1.1 200 OK
Date: Wed, 16 Nov 2016 15:06:25 GMT
Connection: close
Content-Length: 2

ok
```

Version after test run:
```
HTTP/1.1 200 OK
Date: Mon, 21 Nov 2016 12:49:34 GMT
Connection: close
Content-Length: 2

ok
```
node `7.1.0`, yarn `0.17.6`

**Comment by torifat** [comment]
Why are you getting this? It's in `.gitignore`.

**Comment by hpurmann** [comment]
Oh yeah that's right! I think this can be an issue if it was tracked before and later added to the ignore.

For reference, I solved this with
```
git update-index --assume-unchanged __tests__/fixtures/request-cache/GET/localhost/.bin
```

**Comment by torifat** [comment]
https://github.com/yarnpkg/yarn/pull/1865#issuecomment-261029014
