### ISSUE TITLE
Adding a local package with tilde (~) in filename doesn't work

### ISSUE THREAD

**Issue by magikMaker** [yarnpkg/yarn#1969]
**What is the current behavior?**
When [adding](https://yarnpkg.com/en/docs/cli/add#toc-adding-dependencies) a local package with `yarn add file:/path/to/directory/`

**If the current behavior is a bug, please provide the steps to reproduce.**
Add a new, local package using a tilde in the file path:
`yarn add file:~/projects/myPackage/` this does not work (autocomplete using tab does work).
`yarn add file:/Users/userName/projects/myPackage` does work, so the package is there and is functional (has a package.json in the root folder)

**What is the expected behavior?**
The `myPackage` package should be added normally

**Please mention your node.js, yarn and operating system version.**
yarn version: 0.17.2
node version: 6.6.0
OS: MacOS 10.12.1 (Sierra)

**Comment by kittens** [comment]
Is this a thing that works in npm? `~` is super shell-specific.

**Comment by magikMaker** [comment]
I just double checked on my (new) machine (see below for specs) and yes, it does work with npm:

`$ npm install --save ~/projects/somePackage/` 

works just as fine as

`$ npm install --save /Users/userName/projects/somePackage/` 

MacBook 2016 with macOS 10.12.1 - Sierra
node version: 7.1.0
npm version: 3.10.9

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
