### ISSUE TITLE
Unable to add package tar.gz

### ISSUE THREAD

**Issue by bvklingeren** [yarnpkg/yarn#1973]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Install fails with message:
```
error "tar.gz": Tarball is not in network and can not be located in cache ("/Users/bvanklingeren/Development/workspace/source/iba/info-barista/tar.gz")
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute `yarn add tar.gz` or `yarn add --dev tar.gz`

**What is the expected behavior?**
That the NPM package https://www.npmjs.com/package/tar.gz is downloaded and installed.

**Please mention your node.js, yarn and operating system version.**
node v5.10.1
yarn v0.17.6
os darwin x64

**Comment by hpurmann** [comment]
Looks easy to fix, I'm on it.
