### ISSUE TITLE
devDependencies are not installed when both `NODE_ENV=production` and `NPM_CONFIG_PRODUCTION=false` are set

### ISSUE THREAD

**Issue by joeyespo** [yarnpkg/yarn#1975]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

`NODE_ENV` seems to be taking precedence over `NPM_CONFIG_PRODUCTION` (and `YARN_PRODUCTION`).

In npm, it's the opposite.

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
$ yarn init -y
$ yarn add Base64
$ yarn add --dev blob
$ rm -rf node_modules
$ NODE_ENV=production NPM_CONFIG_PRODUCTION=false yarn
```

This doesn't install `blob`.

**What is the expected behavior?**

It should install `devDependencies` like npm does:

```bash
$ yarn init -y
$ yarn add Base64
$ yarn add --dev blob
$ rm -rf node_modules
$ NODE_ENV=production NPM_CONFIG_PRODUCTION=false npm install
```

This *does* install `blob`.

**Please mention your node.js, yarn and operating system version.**

```bash
$ node -v
v6.3.1

$ npm -v
3.10.3

$ yarn -V
0.17.8
```

Windows 10

**Comment by adamreisnz** [comment]
@joeyespo 

>  (and YARN_PRODUCTION)

Is that a real thing? I didn't come across it in any documentation, and Googling for it is nearly impossible due to the articles about yarn production that show up...

**Comment by joeyespo** [comment]
@adamreisnz Yeah, it's the same deal with `NPM_CONFIG_`. It's a prefix that you can use to specify any of the npm options. `YARN_` is the Yarn-equivalent, with `NPM_CONFIG_` for backwards-compatibility. So it doesn't really show up in any searches. (I figured this out after digging around a while.)

**Comment by adamreisnz** [comment]
Ok thanks, I'll give it a go. Might be useful for my issue where I want to install *only* prod dependencies, yet have `NODE_ENV` set to something else, like `staging`.

**Comment by bestander** [comment]
BTW a PR for the docs change is welcome

**Comment by itaysabato** [comment]
This issue is blocking me from migrating to yarn. When can we expect a release including the fix?
