### ISSUE TITLE
Yarn doesn't work with Babel

### ISSUE THREAD

**Issue by vnenkpet** [yarnpkg/yarn#1982]
When running `yarn run bild`
in
```
package.json
...
  "scripts": {
    "build": "babel app -d build",
...
```
I get
```
yarn run v0.17.8
$ babel app -d build 
sh: 1: babel: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This works with NPM (all si transpiled as supposed) but doesn't work with Yarn.
`babel` is **NOT** installed globally in either scenario...

babel.rc looks like
```
{
  "presets": ["es2015-node5"],
  "plugins": [
    "transform-async-to-generator",
    "syntax-async-functions"
  ]
}
```
and the installed babel packages are 
```
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-systemjs": "0.0.1",
    "babel-plugin-transform-async-to-generator": "^6.8.0",
    "babel-preset-es2015-node5": "^1.2.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.14.0",
    "babel-eslint": "^6.1.2",
```

**yarn** version is `0.17.8`
**node** version is `v6.6.0`, npm `3.10.7`
OS is Ubuntu `14.04.1`

**Comment by torifat** [comment]
Please try not to skip issue template.

**Please mention your node.js, yarn and operating system version.**

**Comment by vnenkpet** [comment]
Sorry! Appended that information to the orignal post.

**Comment by torifat** [comment]
Packages you listed none of them come with `babel` binary. So, the current behavior is expected.

Do you have `babel-cli` in your `package.json`?

**Comment by vnenkpet** [comment]
Yeah, I see now that the problem is actually related to npm-shrinkwrap. It's somehow not synced with package.json.
