### ISSUE TITLE
Yarn install is stuck for no reason on v0.17.8

### ISSUE THREAD

**Issue by tristanbes** [yarnpkg/yarn#1985]
**Possible Bug**

**What is the current behavior?**
Yarn (0.17.8) is getting stuck at "Fetching packages..." [1074/1075].
I deploy my application to 2 exact same servers (same versions of everything). One server has this problem, one has not.
I fixed the problem by removing `.yarn-cache` and `.yarn-config`

![1__yprox_morgana___var_www_yproximite_releases_20161122151957__ssh_](https://cloud.githubusercontent.com/assets/346010/20527728/bf67f6a2-b0c9-11e6-8ab8-99f763231a94.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn install` and watch it getting stuck before finishing. Since I deleted the cache, there's no way I reproduce it for you, sorry guys. My report sucks.

**What is the expected behavior?**
`yarn install` finishes without problems

**Please mention your node.js, yarn and operating system version.**
Node v6.2.1 
Linux Debian Jessie

**Comment by torifat** [comment]
@tristanbes Seriously, one software engineer to another. If I assign this issue to you. How will you go about it?

**Comment by tristanbes** [comment]
Like really really sad. If that helps you, I really wondered myself if I should opened it "as is"

But I choose to report it as for log this into internet if other users will encounter this and have more information to share OR maybe my fix will interest them.

**Comment by tristanbes** [comment]
PS: Even if you close this issue because it does not contains enough information, this still can help other and I won't get mad about it. // cc @torifat

**Comment by torifat** [comment]
@tristanbes I'm not closing it right away. Just wanted to know your thought process 😄

**Comment by bestander** [comment]
0.17.9 has --verbose flag, you can now see which download gets stuck.
This looks like a network issue, and could be resolved with a retry.
@tristanbes, how many times did you try and got this problem before fixing it with clearing caches?

**Comment by tristanbes** [comment]
It was 2/3 times as far as I recall 

Envoyé de mon iPhone

**Comment by bestander** [comment]
@tristanbes, 2/3 times as 66% of all times or just 2 or 3 times?
Can you repro this with --verbose flag?

**Comment by tristanbes** [comment]
It didn't occured to us since this report. If it happens to us again, we'll use the verbose flag to post a better bug report ;-)

Thanks.

**Comment by bestander** [comment]
Thanks, let's close this one and open a new one if it happens again
