### ISSUE TITLE
node-gyp rebuild of bufferutil fails with yarn, works with npm

### ISSUE THREAD

**Issue by scjody** [yarnpkg/yarn#1986]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`yarn add bufferutil@1.2.1` (in an empty directory) runs `sh -c node-gyp rebuild`, which fails. This works with npm.

Build output:

```
yarn add v0.17.8
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠂ bufferutil:     at bootstrap_node.js:509:3
[-/1] ⠂ waiting...
error /home/vagrant/yarn/node_modules/bufferutil: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /home/vagrant/yarn/node_modules/bufferutil
Output:
module.js:457
    throw err;
    ^

Error: Cannot find module '/usr/local/share/.config/yarn/global/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn add bufferutil@1.2.1` (in an empty directory, to avoid interference from an existing node_modules directory)

**What is the expected behavior?**

The package is installed successfully. With npm:

```
$ npm install bufferutil@1.2.1

> bufferutil@1.2.1 install /home/vagrant/npm/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/vagrant/npm/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/home/vagrant/npm/node_modules/bufferutil/build'
/home/vagrant/npm
└─┬ bufferutil@1.2.1 
  ├── bindings@1.2.1 
  └── nan@2.4.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
```

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v6.7.0
$ yarn --version
0.17.8
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by rodrigogs** [comment]
+1

**Comment by glasser** [comment]
Happens with heapdump too.

**Comment by glasser** [comment]
Specifically, running `yarn add heapdump` in an empty directory fails with 0.17.10 *if I'm using the single-file JS build* (legacy or not).  If I install it normally it works fine.  I guess this isn't too surprising.

**Comment by Daniel15** [comment]
@scjody

It looks like you've installed Yarn via Yarn itself, based on the path in your error:

> /usr/local/share/.config/yarn/global/node_modules/yarn/

This is not a supported installation method at the moment. Could you please try Yarn either via the Debian/Ubuntu package,  via the installation script, or via npm, and see if it works then?

**Comment by scjody** [comment]
@Daniel15 That works for me, thanks.

**Comment by artscloud-developer** [comment]
> npm install -g node-gyp
