### ISSUE TITLE
Adding a package via Git URL fails when using @ instead of # to define commit-ish to resolve

### ISSUE THREAD

**Issue by Harrisonbro** [yarnpkg/yarn#1988]
**What is the current behavior?**
On a project with an existing `package.json` file and populated `node_modules` directory, running `yarn add <git-url>@<commit-ish>` throws the error below, whereas `yarn add <git-url>#<commit-ish>` (i.e. don't specify a commit or tag) installs fine.

```
es6-symbol@3(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
```

(See full [`yarn-error.log`](https://github.com/yarnpkg/yarn/files/606954/yarn-error.log.txt))

**If the current behavior is a bug, please provide the steps to reproduce.**
- Clone https://bitbucket.org/hbrown/npm-test-project at [`a6ab9c4`](https://bitbucket.org/hbrown/npm-test-project/commits/a6ab9c425e6dc45e4790d550911231e219fc2113)
- Run `yarn` to install dependencies defined in `package.json`
- Run `yarn add https://hbrown@bitbucket.org/hbrown/npm-test.git@1.4.0` ← this step fails for me

**What is the expected behavior?**
The [docs for `yarn add`](https://yarnpkg.com/en/docs/cli/add) make it sound like you should be able to use `yarn add <git-url>@<commit-ish>` as well as `yarn add <git-url>#<commit-ish>` so I'm not sure if this is actually a bug, but it certainly feels as though the former option should work.

If the former option should not work then do the [`yarn add` docs](https://yarnpkg.com/en/docs/cli/add) need updating to make it clear that you cannot define a Git commit or tag with `@` but rather have to use `#`?

**Please mention your node.js, yarn and operating system version.**
Node v6.9.1
Yarn v0.17.8

**Comment by DenisGorbachev** [comment]
Indeed, `@` is reserved for versions & tags. Please use `#` with `<commit-ish>` (also, see https://github.com/yarnpkg/website/pull/288)

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
