### ISSUE TITLE
yarn doesn't remove packages in non-empty namespace

### ISSUE THREAD

**Issue by marzelin** [yarnpkg/yarn#1992]
**Bug**

**What is the current behavior?**
When removing package that is installed with a namespace while there is at least one other package in that namespace, package directory won't be removed
 
**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn add @types/chai
yarn add @types/lodash
yarn remove @types/chai
ls node_modules/@types \\ output: chai/  lodash/
```

**What is the expected behavior?**
package directory should be removed from namespace folder:
`ls node_modules/@types \\ output: lodash/`

**node.js, yarn and operating system version.**
yarn version: v0.17.8 (as global package)
os: ubuntu 16.10 64-bit
node: v7.1.0

**Comment by FDiskas** [comment]
:full_moon_with_face:

**Comment by FDiskas** [comment]
Same problem then the files is not removed from node_modules directory on Failed install
