### ISSUE TITLE
'flat' Package from npm cannot be installed - naming collision?

### ISSUE THREAD

**Issue by derpoho** [yarnpkg/yarn#1995]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn add flat`
throws: `error Missing list of packages to add to your project.`

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add flat`

**What is the expected behavior?**
install flat package. https://www.npmjs.com/package/flat

**Please mention your node.js, yarn and operating system version.**
Yarn 0.17.8
Node 6.3.1
MacOS Latest

**Comment by wyze** [comment]
Duplicate #1609.
