### ISSUE TITLE
Yarn not compiling contextify.node

### ISSUE THREAD

**Issue by palmerj3** [yarnpkg/yarn#1998]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When you add contextify to a project no *.node file is generated. But NPM does create this file.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. yarn init -> follow steps to create blank project
2. yarn add contextify
3. find node_modules/contextify/ -name *.node -> no results

Try the same with NPM:

1. npm init -> follow steps to create blank project
2. npm install --save contextify
3. find node_modules/contextify/ -name *.node -> node_modules/contextify//build/Release/contextify.node

**What is the expected behavior?**

node_modules/contextify//build/Release/contextify.node should be created because a binding.gyp file exists and there is no "install" script already specified in contextify.

**Please mention your node.js, yarn and operating system version.**
Node: 6.9.1
Yarn: 0.17.3
OS: OS X 10.12.1

**Comment by palmerj3** [comment]
After running "yarn cache clean" and re-doing these steps I get the following result:

```
$ yarn add contextify
yarn add v0.17.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠂ contextify
[-/1] ⠂ waiting...
error /Users/jpalmer/Desktop/test/node_modules/contextify: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/jpalmer/Desktop/test/node_modules/contextify
Output:
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/jpalmer/.yarn-config/global/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by palmerj3** [comment]
On my system it appears that the node-gyp bin it's looking for is in: 

/Users/jpalmer/.yarn-config/global/node_modules/node-gyp/bin not 

Not:

/Users/jpalmer/.yarn-config/global/node_modules/yarn/node_modules/node-gyp/bin/

**Comment by palmerj3** [comment]
My apologies for all the responses to this thread.

I have some more information here.

I have found that if I upgrade yarn WITH YARN then this bug is manifested. But if I install/upgrade yarn WITH NPM then it works fine.

So if I do:

```yarn global add yarn@0.17.8```

Then follow the steps above, I have a problem.

But if I do:

```npm install -g yarn@0.17.8```

Then follow the steps above, it works as expected.

Hope this helps

**Comment by palmerj3** [comment]
Last comment for the night - again, my apologies.

I have found that if you do:

```yarn self-update``` to upgrade then things work fine (or if you install globally with npm)

It's when you do:

```yarn global add yarn@0.17.8``` (or presumably any version) that this problem occurs.

**Comment by Daniel15** [comment]
I don't think installing Yarn via Yarn is a supported use-case at the moment, so I'm not surprised that there's issues with that. Installing Yarn via npm often has weird issues too, so please test via one of the regular installation methods (Debian/Ubuntu Linux package, Windows installer, Homebrew or tarball / install script, depending on your platform) and see if the issue still occurs there. If the issue only occurs when Yarn is installed via Yarn (or installed via npm), this will be a relatively low-priority bugfix.

**Comment by wyze** [comment]
The initial bug being reported was fixed in a later version of Yarn than what was being used. Going to close this issue out as it is resolved in the latest version.

**Comment by palmerj3** [comment]
@wyze I can reproduce this on 0.17.8. Are you meaning it's closed in 0.18.0?

**Comment by wyze** [comment]
Sorry, I think I got confused when you were mentioning about upgrading yarn issues.

**Comment by palmerj3** [comment]
That's ok :) It's my fault for making so many follow-up comments with more details.

**Comment by Daniel15** [comment]
Perhaps we should close this given installing yarn via Yarn is not a supported use case at the moment. We could revisit it if/when we make Yarn self-hosting (I don't know if we'll actually do this, as Yarn is designed mainly to manage project-level dependencies).

**Comment by wyze** [comment]
@Daniel15 there is still the issue of contextify not installing. I installed latest yarn via Homebrew and can confirm the error.

**Comment by Daniel15** [comment]
Interesting... My interpretation of this task was that it only breaks when Yarn is installed via Yarn, but perhaps I'm wrong :D

**Comment by palmerj3** [comment]
@Daniel15 that's what happens for me anyway so I think we share the interpretation :)

Curious though.. you say it's not supported to install yarn via yarn and there is weirdness when installing via NPM. Totally understandable - but if they aren't supported methods right now then it seems wrong to list them on yarnpkg.com documentation..

Either way thanks for all the hard work! Easily my favorite project on github :)

**Comment by Daniel15** [comment]
> but if they aren't supported methods right now then it seems wrong to list them on yarnpkg.com documentation

Yarn-via-Yarn is not listed anywhere 😛 and npm is hiding on the "alternatives" tab. I've been meaning to add some more text to that page explaining the disadvantages of installing via npm (it's slower, integrity is not checked as npm has no way to do GPG signing, and sometimes weird things happen with the dependencies).

**Comment by palmerj3** [comment]
> Yarn-via-Yarn is not listed anywhere 

Sure it is:

https://yarnpkg.com/en/docs/cli/self-update

**Comment by Daniel15** [comment]
Self-update doesn't actually install Yarn using Yarn, it uses the tarball
(same as the installer script does). In the future it will use the same
installation method you originally used to install Yarn.

Using "yarn global add" is what I mean by "Yarn in Yarn".

**Comment by palmerj3** [comment]
Aha ok cool thanks for clarifying!

**Comment by pedroabreu** [comment]
Still having this issue on v0.21.3

```
1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/9] ⡀ contextify: make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
[2/9] ⡀ test/helium: bower bourbon#^4.2.7          validate 4.3.3 against https://github.com/thoughtbot/bourbon.git#^4.2.7
[9/9] ⡀ phantomjs-prebuilt
[4/9] ⡀ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-51_binding.node
error /Users/Pedro/Documents/test/node_modules/contextify: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/Pedro/Documents/test/node_modules/contextify
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.6.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Pedro/Documents/test/node_modules/contextify/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Pedro/.node-gyp/7.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Pedro/.node-gyp/7.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Pedro/Documents/test/node_modules/contextify',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/Pedro/.node-gyp/7.6.0/include/node/v8.h:3662:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/Pedro/.node-gyp/7.6.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/Pedro/.node-gyp/7.6.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/Pedro/.node-gyp/7.6.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/yarn/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/lib/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Pedro/Documents/test/node_modules/contextify
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
```

Using node v7.6.0
yarn v0.21.3
OSX 10.11.6

**Comment by Daniel15** [comment]
@pedroabreu That looks like a compilation error with the package... I don't think it's a Yarn issue. You should ask the developers of that package.

**Comment by bestander** [comment]
As @Daniel15 commented
