### ISSUE TITLE
Offline install does not work (cannot build) if node-gyp is required

### ISSUE THREAD

**Issue by MrJohz** [yarnpkg/yarn#2001]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It doesn't appear possible to do an offline install for packages requiring a `node-gyp` install step.  As far as I can tell, when running under Yarn, `node-gyp` requires downloading the node headers every time it runs.  This is different to the NPM tool, which seems to be able to cache those headers somehow, or otherwise do without downloading them.

**If the current behavior is a bug, please provide the steps to reproduce.**

With internet connection turned off and all necessary packages stored in cache:

```sh
$ ls
package.json
$ cat package.json
{
  "name": "offline-test",
  "version": "1.0.0",
  "dependencies": {
    "contextify": "^0.1.15"
  }
}
$ yarn
yarn install v0.17.8
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠈ contextify: not ok
[-/1] ⠈ waiting...
error <current-dir>\node_modules\contextify: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: <current-dir>\node_modules\contextify
Output:
<current-dir>\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | win32 | x64
gyp http GET https://nodejs.org/download/release/v4.6.1/node-v4.6.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\install.js:193:21)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestError (C:\Program Files (x86)\Yarn\node_modules\request\request.js:845:8)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:269:9)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at TLSSocket.emit (events.js:169:7)
gyp ERR! stack     at connectErrorNT (net.js:1012:8)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\4.6.1\\node.exe" "C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd <current-dir>\node_modules\contextify
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

This appears to be reproducible with other packages that require `node-gyp`, e.g. oracledb.

**What is the expected behavior?**

NPM is able to install this package successfully without an internet connection (assuming it has already cached the package .tar or has had it provided via shrinkpack).

**Please mention your node.js, yarn and operating system version.**

Windows 7 Enterprise

```
$ nodist --version
0.8.6
$ node --version
4.6.1
$ yarn --version
0.17.8
```

**Comment by JamieMason** [comment]
Related: https://github.com/nodejs/node-gyp/issues/665

**Comment by bestander** [comment]
This is caused by node-gyp needing to download headers.
There is a workaround as @JamieMason posted.

I don't think Yarn can do anything about this issue because building phase is out of Yarn's control here.

**Comment by amtlib-dot-dll** [comment]
Sorry, but how to make `node-gyp` use local tarballs by passing parameters to `yarn`? `yarn install --tarball nodejs.tar` doesn't seem to work. The only way seems to be modifying the `package.json` file?

**Comment by maludwig** [comment]
I found this when attempting to use "sqlite3" offline. Dear reader, if you're having the same trouble with sqlite, look at https://github.com/DenisCarriere/sqlite3-offline .

If you need to hook it into KnexJS, I did this and it works great!
```js

const SqliteDialect = require(`knex/lib/dialects/sqlite3/index.js`);
const sqlite_offline = require('sqlite3-offline');
class SqliteOfflineDialect extends SqliteDialect {
    _driver() {
        return sqlite_offline;
    }
}

module.exports = {
    db: {
        sqlite: {
            client: SqliteOfflineDialect,
            connection: {
                filename: './db.sqlite',
            },
            useNullAsDefault: true,
        },
    },
};
```
