### ISSUE TITLE
`yarn info`: field value only

### ISSUE THREAD

**Issue by mbana** [yarnpkg/yarn#2003]
hello, All,
is there way to get just the data without extra information attached to it, ideally, just a string without all the progress info and the version of yarn:

```sh
$ yarn -V
0.17.8
$ yarn info . name
yarn info v0.17.8
vscode-languageserver-types
✨  Done in 0.36s.
$ yarn info . name --json
{"type":"inspect","data":"vscode-languageserver-types"}
{"type":"finished","data":300}
```

i can't find how to turn off the verbose output, especially the command that was just run, e.g., `yarn info v...`.

**Comment by wyze** [comment]
Duplicate #1332.
