### ISSUE TITLE
Remove read-only flags when installing on Windows

### ISSUE THREAD

**Issue by FredyC** [yarnpkg/yarn#2006]
**Do you want to request a *feature* or report a *bug*?**
Both (kinda)

**What is the current behavior?**
Installing package on Windows that was published with read-only flags, keeps those flags and this prevents and further use of Yarn.

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add firebase`
`yarn add debug`
_(on Windows)_

**What is the expected behavior?**
Apparently NPM is removing read-only flags when installing package. Yarn should follow similar footsteps.

**Additional information**
This is coming from the #992 and I wanted to summarize the actual issue here and what needs to be done. I think that issue should be closed now.

Windows 10 x64, Yarn 0.17.7, Node 6.9.1

**Comment by Daniel15** [comment]
I don't think this is specific to Windows (I feel like #872 is the same issue)

**Comment by FredyC** [comment]
I see, might be true. Either way it apparently needs to be solved on Yarn side by fixing those permissions instead of trusting that they are correctly set within the package.

**Comment by FredyC** [comment]
Nevermind here, apparently this is a duplicate of #961
