### ISSUE TITLE
yarn add global yarn@0.17.8: config.maybeReadManifest is not a function

### ISSUE THREAD

**Issue by appsforartists** [yarnpkg/yarn#2015]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
https://gist.github.com/appsforartists/71aa9c12cb32927daba62c488a923659

**If the current behavior is a bug, please provide the steps to reproduce.**
yarn global add yarn@0.17.8

**Please mention your node.js, yarn and operating system version.**
yarn@0.16.1
node@6.2.1
macOS@10.11.6

**Comment by appsforartists** [comment]
Incidentally, re-running `yarn global add yarn@0.17.8` (now that yarn appears to have upgraded) seems to work fine.

**Comment by Daniel15** [comment]
Installing Yarn via Yarn is not a supported use case at the moment (also see my comments on #1998)

**Comment by Daniel15** [comment]
The correct way to upgrade Yarn using Yarn is to use the `self-update` command (https://yarnpkg.com/en/docs/cli/self-update), but I don't think it's fully-functional yet.

**Comment by Daniel15** [comment]
The correct way to upgrade Yarn using Yarn is to use the `self-update` command (https://yarnpkg.com/en/docs/cli/self-update), but I don't think it's fully-functional yet. Eventually it will upgrade Yarn using the same installation method you originally used (varies based on platform)

**Comment by BYK** [comment]
Closing since this issue seems to be quite stale. Also, we do not support installing yarn from npm as @Daniel15 mentioned earlier.

**Comment by appsforartists** [comment]
Are the plans for `self-update` to ever work, or is Homebrew the only supported upgrade path?

**Comment by Daniel15** [comment]
There are plans to reimplement self-update, however it'll just update using
the same installation method. For example, if you install Yarn via
Homebrew, it'll update using Homebrew.
