### ISSUE TITLE
yarn add firebase-tools crashes on README; yarn bin now missing

### ISSUE THREAD

**Issue by appsforartists** [yarnpkg/yarn#2016]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn add firebase-tools` crashes:

```
error An unexpected error occured, please open a bug report with the information provided in "~/Projects/material-motion-js/packages/demos/yarn-error.log".

Error: EACCES: permission denied, open '~/Projects/material-motion-js/packages/demos/node_modules/firebase/README.md'
```

Incidentally, running `open '~/Projects/material-motion-js/packages/demos/node_modules/firebase/README.md'` from the command line works fine.

**What is the expected behavior?**
`yarn` shouldn't crash if opening a README fails.  `ls $( yarn bin)` fails now; presumably because yarn is now in an indeterminate state:

```
ls: ~/Projects/material-motion-js/packages/demos/node_modules/.bin: No such file or directory
```

**Please mention your node.js, yarn and operating system version.**
yarn@0.17.8
node@6.2.1
macOS@10.11.6

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
