### ISSUE TITLE
yarn 0.17.8 stops respecting $PREFIX

### ISSUE THREAD

**Issue by appsforartists** [yarnpkg/yarn#2017]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn is installing all binaries into the npm config's prefix.  It is ignoring `$PREFIX`, which worked in 0.16.1.  Additionally, `yarn config set prefix $PREFIX` makes `yarn global bin` return the right path, but `yarn global add` and `yarn global ls` still use the NPM prefix.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
> PREFIX=~/.yarn-global/
> yarn global bin
~/.npm_packages/bin
> yarn config set prefix $PREFIX
yarn config v0.17.8
success Set "prefix" to "~/.yarn-global/".
> yarn global bin
/Users/brentons/.yarn-global/bin
> yarn global ls
// contents of ~/.npm_packages
```

**What is the expected behavior?**
Easily configurable global paths, and a deprecation notice with upgrade instructions if $PREFIX is no longer the supported way to do that.

**Please mention your node.js, yarn and operating system version.**
macOS@10.11.6
yarn@0.17.8
node@6.2.1

**Comment by ljharb** [comment]
`npm` itself should be reading from `$PREFIX` - when it's set, what does `npm config get prefix` return?

**Comment by appsforartists** [comment]
```
$ npm config get prefix
~/.npm_packages

$ echo $PREFIX
~/.yarn-global/

$ npm config list
; cli configs
user-agent = "npm/3.9.3 node/v6.2.1 darwin x64"

; userconfig ~/.npmrc
prefix = "~/.npm_packages"

; node bin location = /usr/local/bin/node
; cwd = ~/Projects/cycle-drag-test
; HOME = ~
; "npm config ls -l" to show all defaults.
```

With my actual home directory replaced with `~` for privacy.

**Comment by ljharb** [comment]
aha, so `~/.npmrc` trumps `$PREFIX` for `npm` - and `yarn` should hopefully do the same, prioritizing `~/.yarnrc` over `~/.npmrc` of course.

In other words, if you want `$PREFIX` to work, I'd recommend removing the setting from your `~/.npmrc` file.

**Comment by Daniel15** [comment]
>  so ~/.npmrc trumps $PREFIX for npm

Does this actually make sense though? I guess it makes sense for compatibility, but generally environment variables override config.

**Comment by ljharb** [comment]
I think $NPM_CONFIG_PREFIX might override it, but I think the PREFIX env var might be legacy. I don't know for certain the history there - npm has tons of ways to configure the prefix, including accepting every capitalization of every env var, iirc.

**Comment by olingern** [comment]
Closing this one. Let me know if there's interest in reopening
