### ISSUE TITLE
yarn global upgrade-interactive

### ISSUE THREAD

**Issue by aouaki** [yarnpkg/yarn#2021]
Hello guys,

I don't see any reason why `upgrade-interactive` shouldn't work for `yarn global` and it would be terrific. What do you think?

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`yarn update-interactive` is awesome but it doesn't work for globally installed packages

**What is the expected behavior?**
`yarn global update-interactive` should do the same as `yarn update-interactive` for globally installed packages

Thanks,
Arthur

**Comment by victornoel** [comment]
Any news on that @Daniel15? I think it completely defeat the purpose of a global repository if the only way to update packages in it is to go to `~/.config/yarn/cache` and run `yarn upgrade-interactive` by hand there…

This is the command I use the most in the global repository…

**Comment by Daniel15** [comment]
No news at the moment. Pull requests are appreciated 😃

**Comment by victornoel** [comment]
@Daniel15 here it is #2689 :)

It was even easier than I thought!

**Comment by Daniel15** [comment]
Thank you so much! 😃
