### ISSUE TITLE
error when install ng-sementic

### ISSUE THREAD

**Issue by iamdenny** [yarnpkg/yarn#2028]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
```yarn add ng-sementic```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

I'm using node v6.3.1
and I tried to install ng-semantic with yarn v0.17.8
The result is
```
error ng-semantic@1.1.11: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 < 6".
```
https://github.com/vladotesanovic/ngSemantic/blob/master/package.json#L23
even my node version is 6, there is an error.
If I install with npm, no problem.

Please check this out.

Thanks.

**Comment by S-YOU** [comment]
< 6 means less than 6, exclusive. suprised that npm does not follow it.

**Comment by wyze** [comment]
You would need to add with `--ignore-engines` flag.
