### ISSUE TITLE
Typing 'yarn' doesn't list sub-commands

### ISSUE THREAD

**Issue by adamchainz** [yarnpkg/yarn#2032]
**Do you want to request a *feature* or report a *bug*?**

Unexpected behaviour

**What is the current behavior?**

Typing `yarn` invokes `yarn install` which then goes about fiddling with your `node_modules`. It succeeds even if you don't have a `package.json`! This was the first thing I did after installation.

**What is the expected behavior?**

Most commands with sub commands, e.g. `npm`, `git`, list their subcommands when you invoke them, to help discovery. `yarn`'s behaviour is thus out of line with this de-facto standard, and can cause problems for those moving from `npm` to `yarn`. For example on my first run it ran `install` and touched my `node_modules` without me "asking" to do so.

**Please mention your node.js, yarn and operating system version.**

yarn 0.16.1

**Comment by adamchainz** [comment]
Also this seems at odds with the policy "no aliases" as per https://github.com/yarnpkg/yarn/issues/1628#issuecomment-258114498

**Comment by kittens** [comment]
This is intentional, see #304.

**Comment by adamchainz** [comment]
I didn't think it was done accidentally but I still find it counter intuitive
