### ISSUE TITLE
yarn uses global(?) cache when running with `--cache-folder` option

### ISSUE THREAD

**Issue by dmitry-mukhin** [yarnpkg/yarn#2037]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn does not respect `--cache-folder` option

**If the current behavior is a bug, please provide the steps to reproduce.**
run under non-root user

`yarn install --production --no-progress --no-emoji --cache-folder /path/to/cache/`

get

`EACCES: permission denied, open '/usr/local/share/.cache/yarn/.roadrunner.json'".`

**What is the expected behavior?**

yarns install everything from `package.json` successfully, using requested cache folder.

**Please mention your node.js, yarn and operating system version.**

```
Ubuntu 14.04.5 LTS
> yarn -V
0.17.8
> nodejs --version
v6.9.1
```

**Comment by wyze** [comment]
This is due to yarn setting up roadrunner before it gets into commander to parse the arguments sent.

**Comment by brysgo** [comment]
Not sure if this is the same or a related bug, but if I configure the cache folder to have a local cache of the deps, any dependencies that are cached globally on the machine are not added to the local cache.

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
