### ISSUE TITLE
yarn check --production is checking for presence of devDependencies 

### ISSUE THREAD

**Issue by martynchamberlin** [yarnpkg/yarn#2038]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**
Currently running `yarn check --production` is not checking for only `dependencies`. It's also checking `devDependencies`. This means that if you wanted to use `yarn check` during a deploy, you couldn't, it would always fail. We'd love to be able to use this on deploys. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Have some `dependencies` and some `devDependencies` specified in `package.json`. Manually remove one of the `devDependencies` from the `node_modules` folder. Run `yarn check --production`, and it will fail. It should not fail, should it? 

**What is the expected behavior?**
For yarn to only look at the `dependencies` when running `yarn check`. 

**Please mention your node.js, yarn and operating system version.**

- v6.1.0
- yarn: MC/fix-yarn-probs
- os: macOS Sierra

**Comment by wyze** [comment]
Yarn doesn't have a `match` command.

**Comment by martynchamberlin** [comment]
Sorry I meant check! https://yarnpkg.com/en/docs/cli/check

**Comment by kittens** [comment]
Fixed via #2116. Notably, [this](https://github.com/yarnpkg/yarn/pull/2116/files#diff-d14f7375c6a059d2b2ed31247fe52519R43) line.

**Comment by martynchamberlin** [comment]
Thanks @kittens!
