### ISSUE TITLE
yarn outdated do not show new beta versions

### ISSUE THREAD

**Issue by farwayer** [yarnpkg/yarn#2048]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`yarn outdated` do not show package new beta  versions.

```
$ yarn outdated                                                                                                     
yarn outdated v0.17.9
Done in 2.10s.

$ npm outdated                                                                                                      
Package                            Current         Wanted  Latest
webpack-dev-server           2.1.0-beta.11  2.1.0-beta.12  1.16.2
```

package.json
```
...
"devDependencies": {
  "webpack-dev-server": "^2.1.0-beta.11",
}
```

**What is the expected behavior?**

Yarn should show outdated beta versions.

**Comment by torifat** [comment]
@farwayer please read this: https://www.npmjs.com/package/semver#prerelease-tags

**Comment by farwayer** [comment]
What do you mean? `2.1.0-beta.12` satisfies range. So package should be marked as outdated.
```
$ semver -r ^2.1.0-beta.11  2.1.0-beta.12                                                                              
2.1.0-beta.12
```

**Comment by torifat** [comment]
@farwayer My bad. You are right. We check if the dependency is old. Where as we should check if it satisfies.

**Comment by DenisGorbachev** [comment]
Seems like it's already fixed. @farwayer Could you please try the `master` version - does it work correctly?

**Comment by torifat** [comment]
@DenisGorbachev You are correct. Fixed in latest master.

**Comment by farwayer** [comment]
Works like a charm!
