### ISSUE TITLE
Where does yarn store global packages (lib not bin)

### ISSUE THREAD

**Issue by Nikki1993** [yarnpkg/yarn#2049]
Hello everyone,

I am sorry if this question has been answered already, but I searched through google and github and couldn't find anything relevant. Where does  `yarn global add` Installs packages? For instance, I have typescript installed through NPM and the tsserver is located in `Users/kononnik/.nvm/versions/node/v7.2.0/lib/node_modules/typescript/lib` but where is the node_modules packages for global npm packages installed through yarn?

**Comment by TheLudd** [comment]
On linux they are stored in `~/.config/yarn/global`

**Comment by msegado** [comment]
The logic determining this is in `src/constants.js`; you can start at [line 56](https://github.com/yarnpkg/yarn/blob/ac90c23be2766229e46b177f9f7f80916ee3e663/src/constants.js#L56) and work your way back from there. Currently it works out to:
- `%LOCALAPPDATA%/Yarn/global` on Windows
-  `~/.config/yarn/global` on OSX and non-root Linux
- `/usr/local/share/.config/yarn/global` on Linux if logged in as root

**Comment by onemen** [comment]
on Windows is `%LOCALAPPDATA%/Yarn/config/global`

**Comment by Nikki1993** [comment]
Thanks everyone :)

**Comment by omouse** [comment]
is this documented on the website, docs or command line help?

**Comment by kyleholzinger** [comment]
Adding a message to say where the package is installed would be exceedingly useful

**Comment by HaleTom** [comment]
Ask yarn itself to tell you (as config `prefix` may set a different location):

```
yarn global dir
```

**Comment by omouse** [comment]
@HaleTom awesome thanks!

is that documented somewhere on the website or docs? seems non-obvious and too useful not to call out somewhere else

**Comment by HaleTom** [comment]
@omouse
I documented it at [Where does yarn keep global packages?](https://stackoverflow.com/q/46829339/5353461), but you could help out by having it officially documented (it is missing from [here](https://yarnpkg.com/lang/en/docs/cli/global/)) either directly or by raising an issue.

**Comment by bochen2014** [comment]
the real problem is `yarn global dir` is not part of node search path by default. 

only `npm i -g ` ones are included. Shell this be documented? what is the official way to add yarn global dir to node search path?

**Comment by bochen2014** [comment]
```
require(X) from module at path Y

LOAD_NODE_MODULES(X, dirname(Y))


LOAD_NODE_MODULES(X, START)
1. let DIRS=NODE_MODULES_PATHS(START)
2. for each DIR in DIRS:
   a. LOAD_AS_FILE(DIR/X)
   b. LOAD_AS_DIRECTORY(DIR/X)



NODE_MODULES_PATHS(START)
1. let PARTS = path split(START)
2. let I = count of PARTS - 1
3. let DIRS = []
4. while I >= 0,
   a. if PARTS[I] = "node_modules" CONTINUE
   b. DIR = path join(PARTS[0 .. I] + "node_modules")
   c. DIRS = DIRS + DIR
   d. let I = I - 1
5. return DIRS
```

seems `npm i -g ` modules aren't in node search path either.

**Comment by khalid-elabbadi** [comment]
can we change this location ?

**Comment by gera2ld** [comment]
Is there a way to get this path dynamically? It seems that yarn v1.5.1+ has changed the path on Windows.

**Comment by toupeira** [comment]
@gera2ld as explained above you can use `yarn global dir` to get the location, and also `yarn global bin` to get the binary path (`~/.yarn/bin` on Linux).

@khalid-elabbadi see `yarn config current`

@bochen2014 you can add the location to `$NODE_PATH`

**Comment by fousu** [comment]
@HaleTom ,Thanks.

**Comment by farzadso** [comment]
@toupeira This is the answer I was looking for since I was working with various Docker images that had different configs.

**Comment by farzadso** [comment]
@AlecRust I guess that's the case. That's kind of my question too.

**Comment by AlecRust** [comment]
@farzadso I'm fairly confident after some investigation.

`brew install yarn` installs a Homebrew Node dependency, so `/usr/local/yarn` and `/usr/local/node` which a lot of things will use by default. This is bad if you use NVM and want both your Node and Yarn scoped to the correct NVM Node version.

After `brew uninstall yarn && brew uninstall node && brew list` to check I have no Homebrew Node or Homebrew Yarn installed, some things started failing for me. Shell scripts that depended on Node started to fail as `/usr/local/node` no longer existed, and my Husky pre-commit hooks started failing because no `yarn` was available.

In both these cases I now simply source NVM before calling binaries such as `yarn`. Husky has [docs on this](https://typicode.github.io/husky/#/?id=command-not-found). Im quite happy with my NVM/Node/Yarn/npm setup now, all in [my dotfiles](https://github.com/AlecRust/dotfiles) if interested.

**Comment by farzadso** [comment]
@AlecRust I tested it and can confirm.
