### ISSUE TITLE
Question about custom init.js

### ISSUE THREAD

**Issue by helio-frota** [yarnpkg/yarn#2056]
Hi,

If I'm not wrong, yarn uses this script 
`/usr/lib/node_modules/yarn/lib/cli/commands/init.js` 
Is possible to have something like ~/.yarn-init.js similar to ~/.npm-init.js ?
To be able to create a _custom init script_ ?

**Comment by markstos** [comment]
The `init.js` file you found is the source code for the [yarn init](https://yarnpkg.com/en/docs/cli/init) command. As it's docs say, "command walks you through an interactive session to create a package.json file. ".    You are not required to use it to create your package.json. If you are like how `npm init` works, you can use that to create your `package.json`, and then use `yarn` to manage managing your dependencies after that. 

Although they are not well-documented, yarn supports the following config variables which can customize the the init process:

 * init-author-name
 * init-author-email
 * init-author-url
 * init-version
 * init-license

What else did you want to set a custom default for in `package.json` files you generate?

**Comment by markstos** [comment]
I submitted a pull request to surface that these config variables affect yarn init: https://github.com/yarnpkg/website/pull/289

**Comment by helio-frota** [comment]
@markstos thanks for all the info.

We have this file with some custom things: https://github.com/bucharest-gold/entente/blob/master/npm-init.js 

like devDependencies, license, things that you mentioned, etc... so when we copy/past this file ^ to `user home` with the name `.npm-init.js` , and when we run `npm init -y` we get all the custom things.

I did a small test by doing copy/past and change the yarn `init.js` file to `user home` and to `~/.yarn` directory, also creating a `.yarn-init.js` in both home and ~/.yarn directories, but with no results.

**Comment by helio-frota** [comment]
Maybe this is a feature request ?

**Comment by markstos** [comment]
Yes, it is a feature request. Nothing in the current `init` source code or documentation  indicates that it's trying to load `.npm-init.js` or `.yarn-init.js`.

**Comment by helio-frota** [comment]
@markstos thanks for the info

**Comment by orinokai** [comment]
I would be interested in the feature too. I am trying to establish consistent dev practices across our organisation and it would be very useful to have every new project bootstrapped with a standard setup when running `yarn init`. For example, I'd like to inject some scripts into package.json, add some packages to devDependencies, create and configure workspaces, add a .gitignore, etc.

**Comment by helio-frota** [comment]
hi, I'm closing as I'm not working in this domain area anymore and also to cleanup the open issues.
feel free to reopen or better to create a new one in case needed :+1:
