### ISSUE TITLE
Installation script fails if ~/.yarn exists but does not contain a Yarn installation

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2061]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The installation script fails if ~/.yarn exists but does not contain a Yarn installation.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
rm -rf ~/.yarn
mkdir ~/.yarn
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.17.9
```
Results in:
```
Installing Yarn!
./install.sh: line 164: yarn: command not found
```

**What is the expected behavior?**
Installation script should work and install Yarn

**Comment by petebacondarwin** [comment]
It seems to me that this check:

```
if [ -n `which yarn` ]; then
```

is not failing as expected since `which yarn` is returning something that is not-`null` even if there is no `yarn` in the current path.
