### ISSUE TITLE
Bug or feature?: dist-tag is placed in package.json

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#2078]
**Do you want to request a *feature* or report a *bug*?**
Dunno ¯\_(ツ)_/¯

**What is the current behavior?**

Say I have:

```json
{
  "name": "yarn-next",
  "version": "1.0.0",
  "private": true
}
````

Than I `$ yarn add npm@next`. Now I have:

```json
{
  "name": "yarn-next",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "npm": "next"
  }
}
````

**What is the expected behavior?**

When I do `$ npm install --save npm@next` I get:

```json
{
  "name": "yarn-next",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "npm": "^4.0.3"
  }
}
````

I'm not sure, if yarns behaviour is a bug or intended. In my current experience I typically would prefer npm's behaviour, because I also like to see to _what_ version`@next` actually points to.

**Please mention your node.js, yarn and operating system version.**
yarn: v0.17.8
node: v6.9.1
npm: 3.10.8

**Comment by wyze** [comment]
Duplicate #1306.
