### ISSUE TITLE
Wrong upgrade behaviour for local moules

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#2079]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Given this `package.json` (and that `component-a` is a valid node module which is also published to npm):

```json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "component-a": "file:../component-a"
  }
}
```

Now I call `$ yarn install` and `component-a` is installed correctly.

Now I run `$ yarn upgrade component-a` and my `package.json` becomes (given `1.0.0` is the latest published version of `component-a`):

```json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "component-a": "^1.0.0"
  }
}
```

**What is the expected behavior?**

I'd expect to get the newest files from `../component-a` instead of a published version.

Note that calling only `yarn upgrade` behaves differently. This one doesn't replace my `../component-a/` with `^1.0.0`. That only happens when I call `$ yarn upgrade component-a`.

**Please mention your node.js, yarn and operating system version.**
yarn: v0.17.8
node: v6.9.1

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
