### ISSUE TITLE
Can't install "tar.gz" npm package. Weird edge case.

### ISSUE THREAD

**Issue by felixsanz** [yarnpkg/yarn#2081]
Can't install https://www.npmjs.com/package/tar.gz, probably because it looks like an extension xD

`yarn add tar.gz`
> yarn add v0.17.9
> [1/4] Resolving packages...
> error "tar.gz": Tarball is not in network and can not be located in cache ("/home/felixsanz/Desktop/test/tar.gz")

**Comment by hpurmann** [comment]
This is [already fixed](https://github.com/yarnpkg/yarn/pull/1974) but not yet released.
