### ISSUE TITLE
yarn self-update crashes in windows because of no permissions

### ISSUE THREAD

**Issue by dheerajbhaskar** [yarnpkg/yarn#2084]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Yarn self-update is broken (i.e. it does not work)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. open run->cmd
2. type `yarn self-update`

Also see the screenshot below:
![screenshot 29](https://cloud.githubusercontent.com/assets/2944909/20751591/90791b00-b722-11e6-9a89-a51581d31e6a.png)

**What is the expected behavior?**
yarn should update its current version to the latest one available

**Please mention your node.js, yarn and operating system version.**
node: v6.4.0
yarn version v0.17.8
windows version: win 10 pro x64

**Comment by dheerajbhaskar** [comment]
This works when done in an elevated command prompt. See screenshot below.

![screenshot 30](https://cloud.githubusercontent.com/assets/2944909/20752983/28a82e28-b72a-11e6-8a0b-c57a8188dd1f.png)

**Comment by wyze** [comment]
This feature has been removed and no longer supported. The removal hasn't landed in a release, but will be in the next one.

**Comment by dheerajbhaskar** [comment]
Honestly, I wish it wasn't deprecated, because given the fast release cadence of yarn, downloading a file and doing setup seems like a lot of work
