### ISSUE TITLE
Front page doesn't describe purpose of Yarn

### ISSUE THREAD

**Issue by HakimCassimallyBBC** [yarnpkg/yarn#2085]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I navigate to https://yarnpkg.com/
I read the description, "FAST, RELIABLE, AND SECURE DEPENDENCY MANAGEMENT", and wonder what the packages are *for*.

**If the current behavior is a bug, please provide the steps to reproduce.**
See https://yarnpkg.com/

**What is the expected behavior?**
I'd expect key words like "Javascript" to be mentioned somewhere prominently on the page, to explain what the project is.

**Please mention your node.js, yarn and operating system version.**
n/a

**Comment by wyze** [comment]
Duplicate #1291.
