### ISSUE TITLE
Upgrade does not work for private repo packages

### ISSUE THREAD

**Issue by claughlin-r7** [yarnpkg/yarn#2086]
**Bug

**What is the current behavior?**
When running `yarn upgrade <package name>` private repo packages (when you have a repo added to your .npmrc) are not upgraded. This does work as expected when upgrading a public package like react etc.  

**What is the expected behavior?**
Should upgrade the package and update the version in the package json.
**Please mention your node.js, yarn and operating system version.**
node v6.4.0
yarn 0.17.9
mac osx

**Comment by shaunc** [comment]
still an issue with yarn 0.19.1

**Comment by claughlin-r7** [comment]
tested on 0.20.3 and no longer seeing the issue
