### ISSUE TITLE
How get package a repository?

### ISSUE THREAD

**Issue by webmarkelov** [yarnpkg/yarn#2087]
With npm work and I see your commit:
`npm install <github url#master>`

with [yarn](https://yarnpkg.com/en/docs/cli/add) tired everything it is impossible to get the latest update

**Comment by webmarkelov** [comment]
when you add yarn package is always checked against the registry NPM? if so how can it get around?

**Comment by wyze** [comment]
Please follow the issue template. Something like `yarn add jquery/jquery` would work.

**Comment by webmarkelov** [comment]
I added pull request and its took but Release not updated and when added package I not see my commits.
What to do?

**Comment by wyze** [comment]
I would recommend opening a new issue and following the issue template. We would need exact steps to reproduce and specifics, not something vague like `npm install <github url#master>`.
