### ISSUE TITLE
Linking fails in .config is symlinked

### ISSUE THREAD

**Issue by davewasmer** [yarnpkg/yarn#2096]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn link foo` fails if `~/.config` is a symlink.

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh
$ ln -s ~/some/other/path/.config ~/.config
$ brew install yarn

$ cd foo && yarn link
yarn link v0.17.9
success Registered "foo".
info You can now run `yarn link "foo"` in the projects where you want to use this module and it will be used instead.
✨  Done in 0.07s.

$ cd ../bar && yarn link foo
yarn link v0.17.9
error No registered module found called "foo".
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.
```

**What is the expected behavior?**
The final command above should succeed in linking `foo` into `bar`. Or, if symlinking `.config` is not supported, it should warn on install or when the command runs.

**Please mention your node.js, yarn and operating system version.**
`yarn 0.17.9`
`node 6.6.0`
`OS X 10.11.6`

----

The problem seems to stem from the fact that `utils/fs.js` [favors relative paths for symlinks when possible](https://github.com/yarnpkg/yarn/blob/099e76dc075763427605a6a63906127402370bb2/src/util/fs.js). This means that the symlink created in `~/.config/yarn/link/foo` is a relative path, i.e. `../../../foo`.

When the OS resolves this relative path though, it does so based on the real location of the symlink file itself. So rather than resolving relative to `~/.config/yarn/link`, it resolves it relative to `~/some/other/path/.config` (which is where the `~/.config` symlink points to). This means the relative path is invalid. And Node's `fs.exists()` (used to [detect if the link exists when running `yarn link <pkg>`](https://github.com/yarnpkg/yarn/blob/099e76dc075763427605a6a63906127402370bb2/src/cli/commands/link.js#L34)) returns false if the file is a symlink whose destination does not exist.

Not sure if there are other benefits to keeping the symlink relative (the code I linked to above mentions something about maintaining links when things move). If the answer is simply that symlinked `.config` dirs are not supported, it would be nice if the install or link command at least warned that this will break yarn.

**Comment by stefanpenner** [comment]
I believe making all symlinks via the `lib/utils/fs`  abstraction relative is problematic, there are work arounds. But it is quite unexpected, and not without issues/caveats.

Although the `link` can now survive some moves, the process of "making relative" forces disk location to be eagerly reified.

IMHO https://github.com/yarnpkg/yarn/issues/94 should likely have been addressed in a targeted way, not making all symlinks relative.

An alternative may be to `realpath` the paths before constructing the `relativePath` https://github.com/yarnpkg/yarn/pull/2454
