### ISSUE TITLE
Add pattern matching to `ls` lookup

### ISSUE THREAD

**Issue by lukeed** [yarnpkg/yarn#2098]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Yarn returns exact matches.

Ideally, an expression could be passed to list all matching values.

```bash
# current
yarn ls gulp
└── gulp@3.9.1
✨  Done

yarn ls gulp*
✨  Done

# improvement
yarn ls gulp*
└── gulp@3.9.1
└── gulp-rev@7.1.2
└── gulp-xo@0.14.0
✨  Done
```

Continued from #1599

**Comment by kittens** [comment]
`*` is expanded by various shells as it's interpreted as a glob so something else would need to be used.

**Comment by lleaff** [comment]
`yarn ls "gulp*"` ?

Consistent with use of UNIX utilities such as `find -iname "myfile*"`

**Comment by lukeed** [comment]
@lleaff works for me 👍
