### ISSUE TITLE
Yarn --version return wrong version number

### ISSUE THREAD

**Issue by lednhatkhanh** [yarnpkg/yarn#2099]
On windows 10, I uninstall my old yarn (0.17.6) and download the installer to install yarn 0.17.9. But yarn --version still return 0.17.6

**Comment by kittens** [comment]
That'd be because you're actually using an older version of Yarn. Ensure that the yarn binary is in your `PATH` or try hard coding the executable path and it should return the correct value since it's the actual version/binary.
