### ISSUE TITLE
Yarn so slow in windows 10

### ISSUE THREAD

**Issue by dean992008** [yarnpkg/yarn#2100]
Yarn on windose very slow, my package installs more than 300 seconds, similar packages on Linux Mind ustanavlivayutsya for 7 - 15 seconds. I installed version 0.17.9. I use gitbash, I tried to CMD and CMD bash.

**Comment by kittens** [comment]
There's nothing immediately actionable from this issue as it's extremely vague and broad. If you can identify specific things that are slow then please feel free to open an issue with exact instructions to reproduce, otherwise there's not much we can do.
