### ISSUE TITLE
Trying to add the 'progress' package fails

### ISSUE THREAD

**Issue by magikMaker** [yarnpkg/yarn#2101]
**Do you want to request a *feature* or report a *bug*?**
report a **bug**

**What is the current behavior?**
When trying to install the 'progress' npm package, it fails with yarn (works with npm install)
https://www.npmjs.com/package/progress

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to install the 'progress' package using yarn:
`$ yarn add progress`
`yarn add v0.17.8`
`error Missing list of packages to add to your project.`
`info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**What is the expected behavior?**
It should be possible to install any npm package, including 'progress'
https://www.npmjs.com/package/progress

**Please mention your node.js, yarn and operating system version.**
OS: macOS 10.12.1
Node: 7.1.0
yarn: 0.17.8
npm: 4.0.3

**Comment by wyze** [comment]
Duplicate #1609.
