### ISSUE TITLE
Upgrade-interactive exact argument 

### ISSUE THREAD

**Issue by maxime1992** [yarnpkg/yarn#2102]
```
$ yarn --version
0.17.9

$ node -v
v6.8.0
```

**Do you want to request a *feature* or report a *bug*?**

feature (improvement)

**What is the current behavior?**
When running `yarn upgrade-interactive` I cannot have **exact** version.

**What is the expected behavior?**
When running `yarn upgrade-interactive` I'd like to avoid `^` in my `package.json` (also in `yarn.lock`).

It's possible when doing a `yarn add someLib` by adding the `-E` or `--exact` argument.

**Comment by torifat** [comment]
There's already an open PR (https://github.com/yarnpkg/yarn/pull/1858). I have to write tests to merge it.
