### ISSUE TITLE
yarn lifecycle version

### ISSUE THREAD

**Issue by rtfpessoa** [yarnpkg/yarn#2105]
Hi,

I just noticed that the yarn cli `version` command is different from npm version.
It does not seem to run the lifecycle "version" command, only runs the "preversion" and "postversion".

My use case is that I need to update some files before release, like compiling etc.
And ideally I would like to do this after the version number is updated in the package.json file.

Am I doing something wrong? How can I have the same behavior in yarn?

As an example: https://github.com/rtfpessoa/diff2html/blob/master/package.json#L48

**Comment by rtfpessoa** [comment]
@Daniel15 just created a pr #2128

Like https://github.com/npm/npm/blob/latest/lib/version.js#L102 after package.json is changed and before the commit is created I added the lifecycle call here https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/version.js#L126

What do you think?

**Comment by searls** [comment]
Safe to close since #2128 was merged?

**Comment by rtfpessoa** [comment]
Yup, you are right.
