### ISSUE TITLE
can not add `lockfile` package

### ISSUE THREAD

**Issue by lili21** [yarnpkg/yarn#2112]
<img width="566" alt="2016-12-02 2 34 53" src="https://cloud.githubusercontent.com/assets/4456380/20825015/3a0aafb0-b89c-11e6-9c4e-40e562075b46.png">

[lockfile](https://www.npmjs.com/package/lockfile).

nodejs: v6.9.1
os: macOS Sierra 10.12

**Comment by tuures** [comment]
workaround: https://github.com/yarnpkg/yarn/issues/2220#issuecomment-266847731

**Comment by iredchuk** [comment]
Caused by this (very old) bug from commander.js: https://github.com/tj/commander.js/issues/346
