### ISSUE TITLE
Does not respect settings from the local .npmrc

### ISSUE THREAD

**Issue by okonet** [yarnpkg/yarn#2118]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Having `.npmrc` with the `save-prefix` in the local working copy and running `yarn add` still uses `^` in `package.json`.

Although this is what `yarn config list ` prints:

```
$ yarn config list 
yarn config v0.17.6
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/0.17.6 npm/? node/v6.7.0 darwin x64' }
info npm config
{ 'save-prefix': '~',
  progress: true,
  'init-author-email': 'andrey@okonet.ru',
  'init-author-name': 'Andrey Okonetchnikov',
  username: 'okonet' }
```

So, clearly, yarn can read this setting. I _guess_ it is still taking the globally defined setting from `~/.yarnrc`

**If the current behavior is a bug, please provide the steps to reproduce.**

Create `.npmrc` with `save-prefix= "~"` inside. Ensure yarn config has `'save-prefix': '^'` or any different value. Run `yarn add <package name>`. This will still add it to package.json with `^` and not `~` prefix.

**What is the expected behavior?**

Installed dependency should appear in package.json with `~` prefix.

**Please mention your node.js, yarn and operating system version.**
 OSX 10.11.3
node v6.7.0
yarn v0.17.6

**Comment by sarbbottam** [comment]
Is there any update on this issue?

**Comment by bestander** [comment]
Yarn reads .npmrc recursively https://github.com/yarnpkg/yarn/blob/master/src/registries/npm-registry.js#L132

**Comment by bestander** [comment]
But Yarn does not support all npm configurations.
Feel free to send a PR to support any specific configuration that you thing Yarn should support as well.
