### ISSUE TITLE
Error running Yarn due to new `node-emoji` entry point

### ISSUE THREAD

**Issue by pdhoopr** [yarnpkg/yarn#2119]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I use `npm i -g yarn` to install and upgrade Yarn. When I ran this command today, then tried to use the Yarn CLI, I received the following error:

```
...
Error: ENOENT: no such file or directory, open 'GLOBAL_NODE_MODULES_PATH/yarn/node_modules/node-emoji/index.js'
...
```

It looks like the `node-emoji` package restructured its entry point in [this commit](https://github.com/omnidan/node-emoji/commit/6b2379d2869bb58818f4d731aaff2ac71c3648df) and then released that in version 1.4.2 earlier today. However, Yarn still seems to be looking for `index.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `npm i -g yarn`
2. `yarn ...`

**What is the expected behavior?**
Yarn should work as normal, e.g. `yarn` or `yarn install` should run without a `node-emoji` error.

**Please mention your node.js, yarn and operating system version.**
Node v7.2.0
Yarn v0.17.10
macOS Sierra v10.12.1

**Comment by dbashford** [comment]
Mentioned this in #2072, likely related?

**Comment by LasaleFamine** [comment]
+1 here, same problem just 20 minutes ago.

**Comment by mandragorn** [comment]
I'm also getting this across at least 3 machines.  Upgrading to yarn 0.17.10 helped to get past the initial issue, but then gulp fails for other reasons (probably unrelated?):
```
[INFO] [09:59:11] Error: task completion callback called too many times
[INFO]     at finish (/home/jyoung/dev/ps-frontend/node_modules/orchestrator/lib/runTask.js:15:10)
[INFO]     at cb (/home/jyoung/dev/ps-frontend/node_modules/orchestrator/lib/runTask.js:29:3)
[INFO]     at browserifyCompleteFn (/home/jyoung/dev/ps-frontend/node_modules/quick-sip/tasks/build.js:15:11)
[INFO]     at finish (/home/jyoung/dev/ps-frontend/node_modules/run-sequence/index.js:53:5)
[INFO]     at Gulp.onError (/home/jyoung/dev/ps-frontend/node_modules/run-sequence/index.js:60:4)
[INFO]     at emitOne (events.js:82:20)
[INFO]     at Gulp.emit (events.js:169:7)
[INFO]     at Gulp.Orchestrator._emitTaskDone (/home/jyoung/dev/ps-frontend/node_modules/orchestrator/index.js:264:8)
[INFO]     at /home/jyoung/dev/ps-frontend/node_modules/orchestrator/index.js:275:23
[INFO]     at finish (/home/jyoung/dev/ps-frontend/node_modules/orchestrator/lib/runTask.js:21:8)
```

**Comment by dbashford** [comment]
FWIW, I uninstalled yarn, blew away the yarn cache, blew away the npm cache, reinstalled via npm and it seems to be ok now.

Possibly some sort of yarn cache issue?

**Comment by kittens** [comment]
This is a known issue, I added a cache breaker in #1965 which should be in latest, if it's not then it'll be in the next release. The fix here is to remove the Yarn cache, one of the following commands should work:

```sh
# OSX
$ rm -rf ~/Library/Caches/Yarn

# Linux
$ rm -rf ~/.cache/yarn

# Windows
$ del %LOCALAPPDATA%/Yarn/cache
```

**Comment by pdhoopr** [comment]
Cool, works for me. Thank you!
