### ISSUE TITLE
Cannot install specific version with install.sh as per website install docs

### ISSUE THREAD

**Issue by dbashford** [yarnpkg/yarn#2120]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Providing a version like this:

`curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.17.8`

...gives grep error and then complains version format is incorrect

![image](https://cloud.githubusercontent.com/assets/581127/20838712/bfee40da-b877-11e6-9e5d-0dba3dfdcfb6.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

`curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.17.8`

**What is the expected behavior?**

Install occurs.

**Please mention your node.js, yarn and operating system version.**
OSX 10.11.4

**Comment by olingern** [comment]
@kittens The hosted install script [https://yarnpkg.com/install.sh](https://yarnpkg.com/install.sh) is referencing an invalid argument for version. 
`curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.17.8`

You can fix this by running the following:

`curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- --version 0.17.8`

Adding an additional argument will allow the version to match `$2` in `install.sh`. I could make a PR to the docs, if needed.

```
    # Validate that the version matches MAJOR.MINOR.PATCH to avoid garbage-in/garbage-out behavior
    version=$2
    if echo $version | grep -qP "^\d+\.\d+\.\d+$"; then
      url="https://yarnpkg.com/downloads/$version/yarn-v$version.tar.gz"
    else
      printf "$red> Version number must match MAJOR.MINOR.PATCH.$reset\n"
      exit 1;
    fi
```

**Comment by Daniel15** [comment]
Could you please try it again? https://github.com/yarnpkg/website/pull/300 should fix this for Mac OS.

**Comment by Daniel15** [comment]
Should be fixed by https://github.com/yarnpkg/website/pull/300, please reopen if this is still an issue. Thanks!
