### ISSUE TITLE
[Docker/Busybox] mktemp: invalid argument in install.sh

### ISSUE THREAD

**Issue by gitawego** [yarnpkg/yarn#2122]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
when install in docker with alpine, it throws error.
**If the current behavior is a bug, please provide the steps to reproduce.**

try to install yarn in a dockerfile with ``curl -o- -L https://yarnpkg.com/install.sh | bash``, using alpine as base image
**What is the expected behavior?**
it should install correctly the yarn. 

after checking the error, it seems ``mktemp`` has different usage:

```
Create a temporary file with name based on TEMPLATE and print its name.
TEMPLATE must end with XXXXXX (e.g. [/dir/]nameXXXXXX).
Without TEMPLATE, -t tmp.XXXXXX is assumed.

        -d      Make directory, not file
        -q      Fail silently on errors
        -t      Prepend base directory name to TEMPLATE
        -p DIR  Use DIR as a base directory (implies -t)
        -u      Do not create anything; print a name

Base directory is: -p DIR, else $TMPDIR, else /tmp
```
the template must end with XXXXXXX

but in the install.sh, it's
```
mktemp -t yarn.XXXXXXXXXX.tar.gz
```

I don't know if there is a way to be compatible with alpine.

**Please mention your node.js, yarn and operating system version.**
node: 7.1.0 yarn 0.17.0 ubuntu 16.10

**Comment by Daniel15** [comment]
That's strange, sounds like Alpine doesn't use the standard GNU mktemp (https://www.gnu.org/software/autogen/mktemp.html). Looks like it's using busybox mktemp. I guess we'll have to update the installation script to handle this.
