### ISSUE TITLE
Fails to install full-icu

### ISSUE THREAD

**Issue by jamieholliday** [yarnpkg/yarn#2124]
Yarn fails to install full-icu package

I get this error output:

```
 Building fresh packages...
[1/6] ⠁ fsevents: http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v48-darwin-x64.tar.gz
[2/6] ⠁ full-icu: npm install icu4c-data@57l (Node 6.8.0 and small-icu 57.1) -> icudt57l.dat
[3/6] ⠁ phantomjs-prebuilt
[4/6] ⠁ phantomjs
error /Users/peterfox/Documents/mjm3-frontend/node_modules/full-icu: Command failed.
Exit code: 1
Command: sh
Arguments: -c node postinstall.js
Directory: /Users/peterfox/Documents/mjm3-frontend/node_modules/full-icu
Output:
npm install icu4c-data@57l (Node 6.8.0 and small-icu 57.1) -> icudt57l.dat
yarn install v0.17.10
info No lockfile found.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add icu4c-data@57l" instead.
/Users/peterfox/Documents/mjm3-frontend/node_modules/full-icu/install-spawn.js:36
		throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
		^
Error: /usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js install icu4c-data@57l --> status 1
    at Error (native)
    at npmInstallNpm (/Users/peterfox/Documents/mjm3-frontend/node_modules/full-icu/install-spawn.js:36:9)
    at Object.<anonymous> (/Users/peterfox/Documents/mjm3-frontend/node_modules/full-icu/postinstall.js:62:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

```"full-icu": "^1.0.3",```

Node: v6.8.0
Yarn: 0.17.10
Mac OS X - 10.11.6

**Comment by jamieholliday** [comment]
After looking into this a bit more this issue is not with Yarn but that the full-icu package is calling npm directly which is why it is failing

**Comment by shouze** [comment]
@jamieholliday I've reported the issue here: https://github.com/unicode-org/full-icu-npm/issues/9

How did you managed to get icu data installed in your node app?

**Comment by jamieholliday** [comment]
So far I have gone with the option of using the Intl polyfil. We were using this anyways to support safari on the client side of our universal app so I just used for node too.

https://www.npmjs.com/package/intl

I've not tested this extensively to see if it solves all our issues, maybe I'm doing this wrong but seems to be working for our use case so far.

Our current version of our app only needs to support en-US (which is included with node) and en-GB
My backup plan if this fails is to go with installing a full version of node which includes all the locale stuff: https://github.com/nodejs/node/wiki/Intl

**Comment by shouze** [comment]
@jamieholliday yes this is what we've done in such containers https://github.com/rezzza/docker-node/blob/master/6/Dockerfile#L48

**Comment by srl295** [comment]
@jamieholliday as I said in the full-icu issue linked above, i'm not sure what I should do when called from `yarn`
