### ISSUE TITLE
`yarn add global` different from `yarn global add`

### ISSUE THREAD

**Issue by vfonic** [yarnpkg/yarn#2130]
**What is the current behavior?**
`yarn add global {pkg_name}` adds package locally

**What is the expected behavior?**
Install the package globally, or at least report some error, or try to install the package with the name `global`

**Please mention your node.js, yarn and operating system version.**
Node v7.2.0
yarn v0.17.10
macOS Sierra 10.12.1

**Comment by wyze** [comment]
This is the syntax to install multiple packages at once. Considering `global` is a package on npm, there is nothing we could do here.
