### ISSUE TITLE
Provide information on how to mitigate problem of installing yarn first then everything else

### ISSUE THREAD

**Issue by ORESoftware** [yarnpkg/yarn#2134]
On latest version -

one conundrum for a package manager as an installation from another package manager is that we have to install yarn on a machine, and then run installs 

so before it was

```console
$ cd <project> && npm install
```

now it is

```console
$ npm install -g yarn
$ cd <project> && yarn
```

this nullifies some of the speed advantages of yarn

is the goal of yarn to get bundled with Node.js?

if not, how to mitigate the above issue?

**Comment by kittens** [comment]
We offer Yarn from a variety of different package managers and installation methods. It's already bundled on CircleCI, TravisCI and a bunch of other providers. We aren't currently pursuing Node bundling but it may be an option in the future. You can see our [docs](https://yarnpkg.com/en/docs/install) for installation methods.

**Comment by ORESoftware** [comment]
Ok sure, do the yarn docs explain how this bundling works with Travis and
CircleCI? Is it just part of the Docker image?

"It" being

npm install -g yarn
