### ISSUE TITLE
Enhancement Request: Ability to define custom cli command aliases...

### ISSUE THREAD

**Issue by emveeoh** [yarnpkg/yarn#2138]
I understand that the Yarn Team doesn't want many of the extra aliases that are found in the NPM cli. However, I really miss using:
i for install
-g for global
-S for save
-D for save-dev, etc...

Maybe, you could give us the ability to define custom aliases so I can have my cake back. I'm hungry...

Thank you very much for your consideration!

**Comment by wyze** [comment]
`npm i` vs `yarn`, so we win there. You could always create your own aliases for your shell. But, I'll leave this open to see what others think.

**Comment by emveeoh** [comment]
You know what... nevermind... you guys have better things to worry about. @wyze is right, I can just add the alias to .zsh shell and be done with it.
