### ISSUE TITLE
Fixes to cherry-pick in [0.18-stable]

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2140]
- [x] v0.18.0 postinstall missing dependencies #2142 (fix #2279)
- [x] Fix an issue with cache config tests modifying actual config (fix #2144 + #2157)

**Comment by Daniel15** [comment]
@bestander  - We could probably track this using milestones rather than an issue 😃

**Comment by valscion** [comment]
I really loved the last issue tracking the fixes to cherry-pick.

Having an issue allows the first post to have structure (e.g. **Headings**) and it is easier to see what issues are resolved and what are still open. It made it easy for me to keep track of upcoming changes.

Milestones are also more short-lived than issues — if milestones wouldn't be deleted at some point in the future, the UI would get messy.

So a :+1: for having these kinds of issues, and a :-1: for using a milestone.
