### ISSUE TITLE
Safeguard against parallel installs

### ISSUE THREAD

**Issue by ORESoftware** [yarnpkg/yarn#2146]
On latest version 

Just wondering if Yarn will safeguard against this, make sure it's keeping something like this in mind

https://github.com/npm/npm/issues/15137

I assume NPM is, but never known for sure. Probably good for Yarn to safeguard against this as well.

Obviously just replace the code in the npm issue with "yarn add x" instead of "npm install x"

**Comment by bestander** [comment]
Yes, you can do
```
yarn install --mutex network & 
yarn install --mutex network &
yarn install --mutex network &
yarn install --mutex network & 
wait
```

And it would execute yarn in sequence using a dummy webserver to ensure only one command is active at a time

**Comment by ORESoftware** [comment]
@bestander thanks, is there some Yarn documentation WRT the dummy webserver you mentioned?

**Comment by ORESoftware** [comment]
@bestander I wrote some code to solve this problem with NPM parallel installs, the way I did it is that each call would write to a persistent queue (a queue with no duplicate commands, duplicates were removed). In this way, only one worker would read from the queue, if the worker had the lock on the queue. If a new worker is started that can't get access to the lock, then the worker just dies, assuming that the existing worker will take care of the job. The problem with my approach, is that I then cannot block on a call to install a dependency, meaning if I run my postintall script and the worker finishes/dies, it does not mean that the dependency has already been installed. So I think your approach is better :)

**Comment by bestander** [comment]
> @bestander thanks, is there some Yarn documentation WRT the dummy webserver you mentioned?

No, sorry, we just needed this feature for one particular case where yarn is used in high concurrency and we could not mutex it externally.
The code is here https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L246-L316, it should be quite possible to get ones hand around it.
Would you be willing to send a PR for the website docs if you have a chance?

**Comment by ORESoftware** [comment]
@bestander are you taking about the yarn website docs for this mutex feature?

**Comment by bestander** [comment]
Actually nevermind, there is a doc already https://yarnpkg.com/en/docs/cli/#toc-concurrency-and-mutex

**Comment by ORESoftware** [comment]
ok sure np, maybe I will contribute later once i use yarn more

**Comment by jiaweihli** [comment]
I ran into this issue last week.  I tried `npm install` just now, and it seems to do this automatically - trying to execute concurrent installs will actually execute them serially.

This seems like a sane default, since there's no use case for broken concurrent yarn installs.

**Comment by ORESoftware** [comment]
right, but what happens if two install commands are run concurrently and the user forgets to use `--mutex`?

**Comment by jiaweihli** [comment]
To be clear, I meant automatically using a mutex is a sane default.

**Comment by bestander** [comment]
BTW, you can add `--install.mutex network` to your .yarnrc to have this setting on by default.
See https://github.com/yarnpkg/yarn/pull/3033

**Comment by ORESoftware** [comment]
@jiaweihli  LOL yes "no use case for broken concurrent yarn installs"
