### ISSUE TITLE
Yarn refused to download react

### ISSUE THREAD

**Issue by Kitanga** [yarnpkg/yarn#2148]
I installed (and removed) yarn yesterday. It couldn't install react. I wanted to install an app using create-react-app but whenever it reached the react package it would stop. I sadly don't remember the error that was given, but it was something about a yarn-metadata.json file not being read correctly. And when I opened this file it had nothing inside.

**Comment by bestander** [comment]
Can't repro
```
$ mkdir react
$ cd react/
$ yarn add react
Using globally installed version of Yarn
yarn add v0.17.8
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 15 new dependencies.
├─ asap@2.0.5
├─ core-js@1.2.7
├─ encoding@0.1.12
├─ fbjs@0.8.6
├─ iconv-lite@0.4.15
├─ is-stream@1.1.0
├─ isomorphic-fetch@2.2.1
├─ js-tokens@2.0.0
├─ loose-envify@1.3.0
├─ node-fetch@1.6.3
├─ object-assign@4.1.0
├─ promise@7.1.1
├─ react@15.4.1
├─ ua-parser-js@0.7.12
└─ whatwg-fetch@2.0.1
✨  Done in 2.14s.
```

**Comment by Kitanga** [comment]
Then it must be my internet. Been having a lot of issues with it of late.
