### ISSUE TITLE
Deal with lockfile merge conflicts in some way

### ISSUE THREAD

**Issue by hkrutzer** [yarnpkg/yarn#2155]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
So I just had to merge two branches that had diverged a bit in `package.json` but a whole lot in the lockfile, causing 93 merge conflicted according to my mergetool. One branch had removed some dependencies, the other had upgraded some. For some of these conflicts I had no idea which version to pick, and I had to throw away the lockfile, defeating the purpose of having a lockfile.

**What is the expected behavior?**
I am unsure how Yarn should handle this. I don't expect it to include a mergetool, but right now merging the lockfile is not really doable, leading to people putting the lockfile in gitignore as seen here https://github.com/yarnpkg/yarn/issues/1776#issuecomment-264209697.

**Comment by neiker** [comment]
I hate this
`rm -rf node_modules yarn.lock && yarn && git add yarn.lock && git rebase --continue`

**Comment by wizardzloy** [comment]
This appears to be a recipe and could be scripted I believe
 
https://github.com/yarnpkg/yarn/issues/1776#issuecomment-269539948

**Comment by caesarsol** [comment]
I have a proposal: `yarn install` could detect for common merge-conflict markers (i.e. `<<<<<<<` for git) and give a hint!

@neiker command is what I do now, but it has a problem: it updates all packages minor version, and this is not what yarn wants.

**Comment by neiker** [comment]
@caesarsol yes, I have all my dependencies fixed, but my dependencies dependencies aren't. So it's a problem. @IanVS solution is the best at the moment.

**Comment by andrienko** [comment]
Maybe, mark it as binary in gitattributes? This will make git ignore conflicts and line endings, like if file was binary. Just create `.gitattributes` file in root and add `yarn.lock binary` to it.

**Comment by graingert** [comment]
see https://github.com/yarnpkg/yarn/pull/3544

**Comment by caesarsol** [comment]
@adrienko that is a pretty smart and clean idea! does it work smoothly even in rebase cases?

**Comment by piggyslasher** [comment]
@caesarsol commit the `.gitattributes` once. After that, you're home free. Works.

**Comment by tricoder42** [comment]
Hello,
https://github.com/yarnpkg/yarn/pull/3544 seems to be merged, but it doesn't seem to work. First I resolved conflicts in `package.json`.

Then I run `run` to resolve merge conflicts in yarn.lock:

![snimek obrazovky 2017-09-06 v 15 34 56](https://user-images.githubusercontent.com/827862/30114787-193d1ebe-9319-11e7-8d8c-1934cb68905a.png)

but `yarn` fails with error:

```
error An unexpected error occurred: "Unknown token 1876:1
```

Line 1876 is the merge conflict:

```
<<<<<<< HEAD
create-react-class@15.x, create-react-class@^15.5.2, create-react-class@^15.5.x, create-react-class@^15.6.0:
  version "15.6.0"
  resolved "https://registry.yarnpkg.com/create-react-class/-/create-react-class-15.6.0.tgz#ab448497c26566e1e29413e883207d57cfe7bed4"
=======
create-react-class@^15.5.1, create-react-class@^15.6.0:
  version "15.6.0"
  resolved "https://registry.yarnpkg.com/create-react-class/-/create-react-class-15.6.0.tgz#ab448497c26566e1e29413e883207d57cfe7bed4"
  dependencies:
    fbjs "^0.8.9"
    loose-envify "^1.3.1"
    object-assign "^4.1.1"

create-react-class@^15.5.2:
  version "15.5.2"
  resolved "https://registry.yarnpkg.com/create-react-class/-/create-react-class-15.5.2.tgz#6a8758348df660b88326a0e764d569f274aad681"
>>>>>>> master
```

**Comment by aPlana** [comment]
@tricoder42 in case you haven't seen it already, that feature has been included in the 1.0.0 release that happened yesterday. Update Yarn and running `yarn install` should fix the conflicts for you.
I just tried and worked like charm!

**Comment by tricoder42** [comment]
Ah, sorry! Great stuff, thank you!

**Comment by AndrewRayCode** [comment]
(spam) this is an approach we use to deal with files like the lockfile: https://blog.andrewray.me/dealing-with-compiled-files-in-git/

**Comment by Slapbox** [comment]
Was this reverted? `1.22.19` just complains about merge conflict characters being invalid JSON.

**Comment by studentIvan** [comment]
For anybody who faced with this problem - check twice that you patching the correct yarn.lock file - you can have multiple in your project folder
