### ISSUE TITLE
yarn cache dir

### ISSUE THREAD

**Issue by philtay** [yarnpkg/yarn#2158]
**Do you want to request a *feature* or report a *bug*?**
semi-bug / annoyance

**What is the current behavior?**
`yarn cache dir` prints:

```
yarn cache v0.18.0
/root/.cache/yarn
Done in 0.04s.
```

**What is the expected behavior?**
`yarn cache dir` command should print only the directory (in this case /root/.cache/yarn) without other useless info. Currently it can't be used in any script. e.g. forget about `export YARN_CACHE=$(yarn cache dir)` and similar. In this case `npm` does the right thing. `npm config get cache` prints just the directory.

**Comment by vjpr** [comment]
`yarn cache dir --verbose` for existing behaviour perhaps.

**Comment by philtay** [comment]
Another thing: this is somewhat related to https://github.com/yarnpkg/yarn/issues/986. If I want to remove the cache during a Docker build, a clean way would be `yarn install && rm -rf $(yarn cache dir)`.

**Comment by paul-soporan** [comment]
Closing as in v2 `yarn config get cacheFolder` (the equivalent of `yarn cache dir`) only prints the path.

https://yarnpkg.com/getting-started/migration
