### ISSUE TITLE
Can't parse yarn install --production=false

### ISSUE THREAD

**Issue by chadly** [yarnpkg/yarn#2167]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

With the `NODE_ENV` set to _production_, running this command

```
yarn install --production=false
```

I expect it to install all dependencies (including `devDependencies`) the same way that npm does. See npm/npm#6803 ([this comment specifically](https://github.com/npm/npm/issues/6803#issuecomment-75621914)) for reference.

Instead yarn errors out because it can't parse the command:

```
yarn install v0.18.0
error `install` has been replaced with `add` to add new dependencies. Run "yarn add false" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Please mention your node.js, yarn and operating system version.**
Node: v7.0.0
Yarn: 0.18.0
OS: Windows 10

**Comment by chadly** [comment]
It seems a work around for this issue would be to set `YARN_PRODUCTION` to `false`, but that won't work either due to #1975

**Comment by bestander** [comment]
A PR is very much welcome.
