### ISSUE TITLE
yarn info doesn't support field paths

### ISSUE THREAD

**Issue by mgol** [yarnpkg/yarn#2175]
**Do you want to request a *feature* or report a *bug*?**

Request a feature.

**What is the current behavior?**

`yarn info` doesn't support the "dot notation" to access deeply nested fields. To see that, invoke:
```
yarn info angular-cli dist-tags.latest
```
and see that it returns undefined. Compare that to the `npm` output:
```
npm info angular-cli dist-tags.latest
```
which returns `1.0.0-beta.22-1`. Without using the dot notation, both look similar (although yarn introduces some authentication noise that erroneously goes to stdout instead of stderr).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

It should behave as npm

**Please mention your node.js, yarn and operating system version.**

Node 6.9.2, yarn 0.18.0, macOS 10.12.1 (16B2555)

**Comment by dxu429** [comment]
I'd like to work on this.

**Comment by dxu429** [comment]
I can work on this if its an enhancement you guys want

**Comment by iredchuk** [comment]
@dxu429 Sorry also started on that, noticed your comment after I pushed my changes...
