### ISSUE TITLE
What is `.yarn` folder purpose?

### ISSUE THREAD

**Issue by jpetitcolas** [yarnpkg/yarn#2177]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**

Yarn needs a `.yarn` folder in order to run. Yet, it doesn't seem to create anything in it? 

Is it an artefact from a previous development or is it really useful?

Moreover, it would be great to get some informations about the three folders used by Yarn in documentation (`.yarn`, `.config` and `.cache`). At least, if they don't already exist. :)

PS: sorry if this question has already been asked, but looking for ".yarn" returns all instances of "yarn". :)

**Please mention your node.js, yarn and operating system version.**

Yarn 0.18.0
Node 6.9.1
Debian Linux

**Comment by jambonrose** [comment]
This was also noted by @thesbros at the end of #1672.

Yarn creates the `.yarn` folder on [line 30 of `bin/yarn.js`](https://github.com/yarnpkg/yarn/blob/5ee3721c08dc9a052cbce1b1f7c40663a1a14184/bin/yarn.js#L30).

```
mkdirp.sync(constants.GLOBAL_INSTALL_DIRECTORY);
```

The constant is defined on [line 52 of `src/constants.js`](https://github.com/yarnpkg/yarn/blob/24ce6397f01ee18fb5e55523eb1b3b2431f2b648/src/constants.js#L52).

```
export const GLOBAL_INSTALL_DIRECTORY = path.join(userHome, '.yarn');
```
If you [search for the `GLOBAL_INSTALL_DIRECTORY` constant](https://github.com/yarnpkg/yarn/search?q=GLOBAL_INSTALL_DIRECTORY&type=Code&utf8=%E2%9C%93), the two instances above appear to be the only places where the constant is used.

Given the use of `~/.config/yarn` and `~/.cache/yarn` the `.yarn` directory should no longer be used, and I believe that it is safe to remove the two lines of code above.

**Comment by tommedema** [comment]
`yarn policies set-version 1.17.3` creates a `.yarn` folder in my package's repository; should this be committed to version control?

**Comment by borisdiakur** [comment]
@tommedema
See https://classic.yarnpkg.com/en/docs/cli/policies/ or https://next.yarnpkg.com/cli/set/version
__TLDR__: add it to version control.

**Comment by Pointotech** [comment]
@borisdiakur The link you posted has two different sections: `If you're using Zero-Installs` and `If you're not using Zero-Installs`. As a person just using Yarn, I don't know what "Zero-Installs" is, or whether I'm using it. Any idea how to find out? Seems like this documentation page should explain that.

**Comment by Pointotech** [comment]
Looks like it's an optional Yarn feature https://yarnpkg.com/features/zero-installs and I haven't intentionally opted into it, so I'm going to assume that I don't have it.
