### ISSUE TITLE
very important xmas command is missing

### ISSUE THREAD

**Issue by blakek** [yarnpkg/yarn#2180]
**Do you want to request a *feature* or report a *bug*?**
Requesting a *feature*.  This command is very important to our workflow and morale

**What is the current behavior?**

```bash
$ yarn xmas
```

outputs:

```
error Command "xmas" not found.
```

This makes our users very sad.

**What is the expected behavior?**

```bash
$ yarn xmas
```

should output something similarly festive:

```
﻿﻿﻿﻿
                     ★
                    ／＼
                   ／  ＼
                  ／⁂ ⸮&＼
                 ／⁂ ⸮｡ ⸛＼
                ／⁂ ｡&   ⸛＼
               ／   ｡      ＼
              ／        ⁂  i＼
             ／｡ ⸛  &     i  ＼
            ／   i @i ⸛ ｡  ｡ @＼
           ／⁂    ⸛ @ ⁂  ⁂i｡   ＼
          ／i ⸛   ｡@ ⸛⸮    @⁂ ⁂⸛＼
         ／@  ⸛@  @    ⸛@ ｡      ＼
        ／ ⸛   ii   @  && ⸛   @&  ＼
       ／   ⸛   &@  @    ⸮  ⸛⸮  i⸮ ＼
      ／⸛        ｡@ ⸛  i  @@   &    ＼
     ／ ⁂ ⸛       @&@  @       ⁂&    ＼
    ／ ⸮    ⸛   &  ⸮⸛i ⸮｡@ @   ⸛    & ＼
   ／&⸮        i&⁂    i⸛  @ @⸛ &｡  ⸮ ⸮ ＼
  ／ ⁂ ⸮  ⸮   ⸮⁂&i &  ⁂⁂@@ ⸛   ｡     ⁂⁂ ＼
 ／  i  i  ｡ ⸮   ⁂   i ⸮  @ ⸛@ ⸛i  &⸛    ＼
 ^^^^^^^^^^^^^^^^^^^|  |^^^^^^^^^^^^^^^^^^^
                    |  |                   

Happy Xmas from the yarn team
```

**Comment by halvves** [comment]
@blakek ilu

**Comment by Daniel15** [comment]
Pull requests implementing this extremely important feature would be highly appreciated!

**Comment by ljharb** [comment]
Don't forget the xmas tree colors, and `npm substack`, and `npm visnup` :-)

**Comment by blakek** [comment]
We like emojis, right?  How about something along these lines:
```
           🌟
           🎄
          🎄🎄
         🎄🔵🎄
        🎄🎄🎄🎄
       🎄🎄🔴🎄🎄
      🎄🔴🎄⚪🎄🎄
     🎄🎄🎄🎄🎄🔵🎄
    🎄🎄⚪🎄🔵🎄🎄🎄
   🎄🎄🎄🎄🎄🎄🎄🎄🎄
  🎄🎄🎄🎄🎄🎄🔴🎄🎄🎄
 🎄🎄🔵🎄🎄🎄🎄⚪🎄🎄🎄
🎄🎄🎄⚪🎄🎄🎄🎄🔴🎄🎄🎄
           🎄🎄
           🎄🎄

🎅 Merry Xmas from the yarn team!
```

**Comment by kittens** [comment]
This is cool but we deliberately didn't add all the frivolous command that npm has. I wanted to add a `fieri` command that output an ASCII guy fieri but these types of things just bloat the codebase and are unnecessary. I understand that I'm being the big bad guy here and ruining all the fun but I really don't see the point of this.
