### ISSUE TITLE
Update chocolatey package

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#2185]
The current release is 0.17.9 but should be 0.17.10 or 0.18.0.

**Comment by jdalton** [comment]
Ah I see 0.17.10 was submitted yesterday but not yet approved.

**Comment by Daniel15** [comment]
Yeah I'm going to ask the Chocolatey team about whether we can make Yarn a "trusted package", which would mean updated packages are posted as soon as we publish them and they pass the automated verification testing.

> From the looks of things (homebrew and npm) the 0.18.0 was a pre-release.
> Do you know if chocolatey has a way to include those as well?

0.18.0 is essentially considered a release candidate at the moment, I don't think we publish those anywhere right now. We'll work on improving that in the future. I think Chocolatey supports prereleases (I know that NuGet does)
