### ISSUE TITLE
github links in package.json

### ISSUE THREAD

**Issue by ORESoftware** [yarnpkg/yarn#2186]
Reporting a bug! Assuming yarn will support github links in package.json. AFAICT, the following was not honored:

```
"devDependencies": {
   "suman": "github:oresoftware/suman#dev
} 
```

It installed suman, but not sure if it picked it up from the dev branch or if it pulled from master, _seemed to pull from master, not dev branch._

**Comment by torifat** [comment]
Currently this syntax `<registry>:<owner>/<repo>#<branch>` doesn't work but `<registry>:<owner>/<repo>` will. Or you can try https. For e.g: `https://github.com/<owner>/<repo>.git#<branch>`.

**Comment by ORESoftware** [comment]
Okay thanks

**Comment by torifat** [comment]
Both works now.
