### ISSUE TITLE
always fail with slow internet, while npm does work

### ISSUE THREAD

**Issue by ankibalyan** [yarnpkg/yarn#2191]
Hi folks, I ran out of my bandwidth and Internet speed reduces around 50KBps, yarn fails to install its components, while npm does work finally a little slower but it work.

    Trace: 
       Error: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443
         at Object.exports._errnoException (util.js:1026:11)
         at errnoException (dns.js:33:15)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Let me know if any further input needed.

**Comment by jas99** [comment]
+1

**Comment by torifat** [comment]
@jas99 Please don't post `+1` comment. 👍 in the main post is enough.

**Comment by trodrigues** [comment]
Just to add some detail: I had the same issue recently and after researching the error above it seems to be related to DNS resolution issues.

As the original reporter stated, npm seems to get around it and it shows some messages that it got the same error and it's trying to recover by retrying to fetch the packages.

**Comment by viztastic** [comment]
I also experience the same issue, this is a screenshot of a recent occurrance:

![image](https://cloud.githubusercontent.com/assets/8556736/21482952/e8d4f326-cbce-11e6-84df-0e170457937a.png)


It seems to be somewhat intermittent (almost 60% probability of happening).

This is my docker file:



```Dockerfile
WORKDIR /opt/app

RUN mkdir -p /opt
ADD yarn-v0.18.1.tar.gz /opt/
RUN mv /opt/dist /opt/yarn
ENV PATH "$PATH:/opt/yarn/bin"

ADD package.json yarn.lock /tmp/
RUN cd /tmp && yarn
RUN mkdir -p /opt/app && cd /opt/app && ln -s /tmp/node_modules
ADD . /opt/app
RUN cd /opt/app && yarn run gulp
RUN cd /opt/app && yarn run start
```

**Comment by buz-zard** [comment]
I'm havin the same error, though it has nothing to do with slow internet.

yarn-error.log - http://pastebin.com/WqCtY3Jr

**Comment by ankibalyan** [comment]
this seems like dns resolutions error only, but again yarn is using the same repositories as npm.

**Comment by ankibalyan** [comment]
@trodrigues most of the time yarn works but only sometime it sucks, and error is like, if it has to resolve 500 dependencies, it resolves around ~388/ ~400 / ~ 490 dependencies and  then it sucks. I've tried couple of time, even by clearing cache and force options, no luck.   
While it worked well with one npm install command, but the download was slow as of my internet.

**Comment by trodrigues** [comment]
Yep. Like I mentioned, the bug to me seems to be yarn failing to recover from these issues (which npm does fine).

**Comment by patrickd-** [comment]
```
yarn install v0.15.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error getaddrinfo EAI_AGAIN registry.yarnpkg.com:443
    at Object.exports._errnoException (util.js:1023:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
happening again all the time today

**Comment by schacki** [comment]
Any updates on this issue? I do have the same problem

**Comment by roccomuso** [comment]
Same problem.

**Comment by perchten** [comment]
Same error, slightly different line numbers, possibly different version.

```
error getaddrinfo EAI_AGAIN registry.yarnpkg.com:443
    at Object.exports._errnoException (util.js:1036:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

```
$ yarn --version
0.21.3
```

**Comment by dagoss** [comment]
I experienced this problem too. I ran yarn, got the error ([yarn-error.log here](https://pastebin.com/PxhKjNJb)), then immediately ran yarn again without changing anything and it worked.

Note that I was running `yarn install` on an empty project, not adding a package to an existing project.

**Comment by vsimko** [comment]
I experienced it too, but setting the network-concurrency parameter to 1 solved it in my case:
```
yarn install --network-concurrency 1
```

**Comment by NAlexPear** [comment]
I had this same issue running yarn in a docker container on Ubuntu 17.04, and found that, in my case, running `dnsmasq` as a service (for an unrelated project) was causing the containerized `yarn install` to throw this error. Stopping `dnsmasq` solved the issue.

**Comment by Vespira** [comment]
I had this issue when doing a yarn install into the Docker base image alexsuch/angular-cli (1.2.1). I figured out that deleting local Docker image and restarting Docker solved the problem.

I suspect yarn keep failing because of the DNS record not found from the Docker image, for some reason (long Docker exec on my dev laptop can lead to little unwanted behaviours like these).

**Comment by avsd** [comment]
A quick & dirty fix is to add following line to your `/etc/hosts` file (*nix) or `C:\Windows\System32\drivers\etc\` file (Windows):

```
AAA.BB.CC.DDD registry.yarnpkg.com
```

where `AAA.BB.CC.DDD` is the IP address currently mapped to the `registry.yarnpkg.com` domain. At the moment it's  `104.16.63.173` but may change. You can get it from here for example: https://www.ultratools.com/tools/pingResult?hostName=registry.yarnpkg.com

**Comment by ryancastle** [comment]
`docker-machine restart` solved it in my instance.

**Comment by alexsasharegan** [comment]
Found that I received this message at a point when my internet connection went down. Maybe it's worth a connectivity check to display a more useful error?

**Comment by leandrosilvaferreira** [comment]
This problem happen when you change your network, maybe from a wifi network to another one.
All you need to do is restart the docker service:
`sudo systemctl restart docker`

**Comment by derakhshanfar** [comment]
Same issue for me in docker. but outside the docker it works.

**Comment by michelts** [comment]
In my case, the solution was just restart docker, as suggested by @ryancastle and @leandrosilvaferreira.

**Comment by webOS101** [comment]
Some sort of retry option would be very helpful for this issue.

**Comment by agibalov** [comment]
`--network-concurrency 1` didn't work for me, here's the workaround inspired by @avsd:
```
apt-get install -y bind9-host
registryYarnpkgComIpAddress=$(host registry.yarnpkg.com | awk '/has address/ { print $4 }' | head -n1)
echo "${registryYarnpkgComIpAddress} registry.yarnpkg.com" >> /etc/hosts
```

**Comment by merceyz** [comment]
Closing as fixed in v2 where failed requests are automatically retried

https://yarnpkg.com/getting-started/migration

**Comment by qrilka** [comment]
Closed 3.5 month ago and no release with the fix yet?

**Comment by AlexWayfer** [comment]
> Closed 3.5 month ago and no release with the fix yet?

v2 released many months ago.

**Comment by qrilka** [comment]
https://github.com/yarnpkg/yarn/releases show no v2

**Comment by qrilka** [comment]
Oh, I see there's now  https://github.com/yarnpkg/berry
I guess it's obvious to somebody that for a new version you need to find some other repo.

**Comment by AlexWayfer** [comment]
> Oh, I see there's now https://github.com/yarnpkg/berry
> I guess it's obvious to somebody that for a new version you need to find some other repo.

Yes, the release of 2nd version was a mess (with repo, docs site, tags; in my opinion), and I wanted to direct you to this repo, but I'm glad you found it by yourself. There is betas for 3rd version BTW. And v1 received little patches, but I think kind of security updates.

**Comment by merceyz** [comment]
> I guess it's obvious to somebody that for a new version you need to find some other repo.

@qrilka The "about" section for the repo points to https://github.com/yarnpkg/berry
