### ISSUE TITLE
should output build logs in verbose mode

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2204]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the expected behavior?**

Sometimes something goes wrong when dependencies are installed and --verbose mode helps to identify problems.
Quite a few problems with Yarn are related to binary dependencies builds.

In verbose mode Yarn should output stdout of install lifecycle scripts instead of
```
[4/4] 📃  Building fresh packages...
[1/2] ⡀ dtrace-provider
[-/2] ⡀ waiting...
[-/2] ⡀ waiting...
[-/2] ⢀ waiting...
[-/2] ⢀ waiting...
```

**Comment by xdissent** [comment]
Any guidance on what the output should look like? Something like this might be a quick and easy win:

```diff
--- a/src/package-install-scripts.js
+++ b/src/package-install-scripts.js
@@ -101,7 +101,8 @@ export default class PackageInstallScripts {
 
     try {
       for (const [stage, cmd] of cmds) {
-        await executeLifecycleScript(stage, this.config, loc, cmd, spinner);
+        const {stdout} = await executeLifecycleScript(stage, this.config, loc, cmd, spinner);
+        this.reporter.verbose(stdout);
       }
     } catch (err) {
       err.message = `${loc}: ${err.message}`;
```

But longer term I wonder if there's a format that would handle big builds better.

**Comment by bestander** [comment]
Yeah, I think reporter.verbose could be a good solution.
There may be edge cases of course.
Send a PR and let's see it in action :)

**Comment by manuq** [comment]
Shouldn't this be closed now that #2994 was merged?

**Comment by bestander** [comment]
Thanks!

**Comment by Myrmod** [comment]
As reference for Version 3 it's `yarn install --inline-builds`
