### ISSUE TITLE
Calling yarn in a script stops execution

### ISSUE THREAD

**Issue by bartosz-oczujda** [yarnpkg/yarn#2205]
**Do you want to request a *feature* or report a *bug*?**

This is a bug

**What is the current behavior?**

I have a following script in my package.json

```
"scripts": {
    "link": "yarn link ggs-toolbox"
  }
```

Calling `yarn run link` does basically nothing, the process just hangs.
Calling `npm run link` executes the script properly
Calling `yarn link ggs-toolbox` properly links the module in my project

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a script in `package.json` that executes `yarn` (look at my example) call `yarn run your-script` to execute that script from command line.

**What is the expected behavior?**
A script which calls `yarn` (look at the example) is properly executed.

**Please mention your node.js, yarn and operating system version.**
Node - v.6.5.0
Yarn - 0.18.0
OS - Win 7

**Comment by dandv** [comment]
Is there another way to call a yarn script from a yarn script?

For example I want to run `prepare` before `test`.

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where script execution has been revamped and no hangs have been reported so far.

https://yarnpkg.com/getting-started/migration
