### ISSUE TITLE
Yarn cannot install `immutable-ext` on Node 6.9.1 but npm works fine

### ISSUE THREAD

**Issue by dmitriz** [yarnpkg/yarn#2208]
**Do you want to request a *feature* or report a *bug*?**

Reporting Bug.

**What is the current behavior?**

Attempt to install package generates error:
```
✗ yarn add immutable-ext     
yarn add v0.17.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error immutable-ext@1.0.6: The engine "node" is incompatible with this module. Expected version "6.2.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn add immutable-ext` on Node 6.9.1

**What is the expected behavior?**

Expected to install the package, like `npm` does:

```
npm i immutable-ext -S
/Users/zaitsev/Desktop/dr-frisbe-course/examples
└── immutable-ext@1.0.6 

npm WARN examples No description
npm WARN examples No repository field.
npm WARN examples No license field.
```

**Please mention your node.js, yarn and operating system version.**

Node 6.9.1, yarn 0.17.4

**Comment by torifat** [comment]
`npm` doc states:

> ### engines
> ...
> Note that, unless the user has set the **engine-strict** config flag, this field is advisory only.

> ### engineStrict
> **This feature was deprecated with npm 3.0.0**

So, we are treating engines strictly.

`immutable-ext` has:
```json
{
    "engines": {
      "node": "6.2.0"
    },
}
```

So, I think the current behavior is safer and correct.

If you need to install it anyways then use `yarn add --ignore-engines immutable-ext`

**Comment by torifat** [comment]
@dmitriz I requested drboolean to update the `engines` and he was kind enough to update it so quickly. You can now install it without `--ignore-engines`.

<img width="188" alt="screenshot 2016-12-10 20 50 22" src="https://cloud.githubusercontent.com/assets/208544/21074119/6e11b068-bf1a-11e6-81ff-044d31a09b45.png">

**Comment by dmitriz** [comment]
Many thanks, I personally would disagree the yarn's approach is better than npm, as in 95% cases the strict restriction does not really matter, like e.g. in this case, and a simple warning would suffice. 

What is worse, the error message of `yarn` gives absolutely no help how to solve the problem, like adding `--ignore-engines` as you mention.

**Comment by torifat** [comment]
> 95% cases the strict restriction does not really matter

Can you provide the source please?

> What is worse, the error message of yarn gives absolutely no help how to solve the problem, like adding --ignore-engines as you mention. Greatly appreciate your explanation and time it took to write it, but having that inside the error message would have removed the need in first place.

Yes. I agree. We should add it to the error message.

**Comment by dmitriz** [comment]
It is my humble estimate ;) 
Confirmed by this particular case too.

But seriously, it is not like there are daily complaints about `npm` being "unsafe" by letting people install some old packages that  were marked for a strict version for reasons that likely no longer valid by now. People are used to packages being broken for many other reasons and in most cases just want to quickly try something and are mostly capable of fixing them if needed or ask for help.

In my view, it is completely unnecessary to play a "babysitter" for the people guarding their safety. At least most users are grown ups and a friendly warning should more than do sufficient job for them. When there are actual problems, they are probably clearly mentioned in the README, or else, if that really matters, people get back to author who in that case would deserve it ;-). As opposed to the `yarn` maintainers who I imagine like to spend their time dealing with more serious problems.

Further, deviating from the standard `npm` behavior creates a nightmare situation for the author, who now has no idea which packager the user will be using. I personally would not even touch that declaration for precisely that reason, but now it makes me worried what other deviations are there that may affect my users.

**Comment by alejandroiglesias** [comment]
@dmitriz guarding people's safety by deviating from the standard npm behavior is one of the main reasons for Yarn to exist, according to my understanding.

Regarding if it should be an error that cancels package install or just a warning, I don't know and people who know more about the purpose and behavior of Yarn will tell. But for sure I needed to be notified in the error about the `--ignore-engines` parameter. I guess adding something like this could work:
>If you are sure you want to proceed, use the --ignore-engines parameter.

**Comment by dmitriz** [comment]
@alejandroiglesias Thank you for taking time to comment! For me personally, the main reason to use Yarn *by far* is its speed.  

The rest of my experience with Yarn is actually annoying: 

- Why not let people `yarn i` instead of `yarn install`?

- Why `yarn add` instead of `yarn install`?

- And even then, why not let me shorten to `yarn a ...`?

- Why `yarn global` instead of `yarn -g`?

The latter option style has nothing to do with `npm` or safety, it has been battle tested in Unix since many years, so what is the reason to force this new verbose syntax?

And, speaking about safety...

```
yarn install -g
yarn install v0.17.10
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.17s.
```

The option `-g` was silently ignored, the unintended local install was run and success reported!

So here we go -- the classical gorilla-banana problem :(
The speed is the legend. But the UX has room for improvement, unfortunately.

Hope it doesn't feel like complaining but more a constructive feedback with honest desire to improve it for everyone.
