### ISSUE TITLE
yarn can't global add pack in home folder

### ISSUE THREAD

**Issue by nodece** [yarnpkg/yarn#2210]
env： 
Ubuntu 16.04
node 7.0
yarn 0.17.10

problem：
when i  exec yarn global add packname，hava a error **error We don't have permissions to touch the file "/usr/bin/eslint".**， if i exec yarn global add packname，This is possible。but i no hope ，But I don't want to use that. This will cause other anomalies。I hope there is a good way to solve the problem.

![problem image](https://cloud.githubusercontent.com/assets/16235121/21071014/453c699a-bece-11e6-874c-c97c3a98c278.png)

**Comment by torifat** [comment]
Sorry, I didn't understand what you are trying to say 😞

**Comment by nodece** [comment]
i no hope use sudo yarn ， i hope use yarn.

**Comment by jamon** [comment]
@nodece 

https://github.com/yarnpkg/yarn/issues/2108 walks through how to do this

**Comment by nodece** [comment]
@jamon very good , thanks
