### ISSUE TITLE
Run brunch b --production 

### ISSUE THREAD

**Issue by solisoft** [yarnpkg/yarn#2222]
Hi, 

I have installed brunch like that : `yarn global add brunch`

And now I want to compile my assets for production : `yarn run brunch b --production`

brunch simply ignore my --production argument

How to fix it?

**Comment by SimenB** [comment]
`yarn run brunch b -- --production`

https://yarnpkg.com/en/docs/cli/run#toc-yarn-run-script

**Comment by solisoft** [comment]
Ok Thanks
