### ISSUE TITLE
Provide a way to fallback to cached version when installing latest offline

### ISSUE THREAD

**Issue by gaearon** [yarnpkg/yarn#2225]
Not sure if it's worth an RFC.
Yarn integration in Create React App is a bit disappointing, and there is a feature that could really help us out.

Create React App installs a package called `react-scripts` every time you run it. The idea is that this is the package with the “guts” of Create React App, and thus anytime you create a new project, you get the latest version of it. So people who don’t update the CLI still get new features.

However it doesn’t work offline. So if you’re in an airplane, you can’t create a React project. This is frustrating.

Ideally we’d like a way to tell Yarn that it should try installing latest version of a package **but** if that’s impossible, we’re fine falling back to the latest version that exists in the cache.

Note that I tried using `--offline` for this and it didn't work because it requested `latest` whereas we only have a specific version in cache (for example `0.8.4`). I wish there was a way to "agree" to use whatever local version we have if there is no network connection.

I think this was mentioned as last paragraph in https://github.com/yarnpkg/yarn/pull/1277#issue-184089258 so it’s not exactly a new idea.

**Comment by voxsim** [comment]
We should use --prefer-offline but it still does not work properly, this is a memo for the future :)
