### ISSUE TITLE
`npm_config_argv` is not set properly in yarn scripts

### ISSUE THREAD

**Issue by dotcs** [yarnpkg/yarn#2226]
**Do you want to request a *feature* or report a *bug*?**

Not clear. To be compatible with npm I guess it's a bug.

**What is the current behavior?**
Environment variables are not set correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

    // File: env-test.js
    console.log(process.env);

and

    // File: package.json
    {
      "scripts": {
        "env-test": "node ./test.js"
      }
    }

**What is the expected behavior?**

`npm_config_argv` should be set in `process.env`, as well as the`npm_config_demo_arg` in this case.

    $ npm run env-test --demo-arg="abc" | grep 'abc'`
    # output:
    # npm_config_argv: '{"remain":[],"cooked":["run","env","--demo-arg","abc"],"original":["run","env","--demo-arg=abc"]}',
    # npm_config_demo_arg: 'abc',

    $ npm run env-test --demo-arg="abc" | grep 'abc'`
    # output is empty

**Please mention your node.js, yarn and operating system version.**

    $ node --version
    # output: v7.2.0
    $ yarn --version
    # output: 0.18.0
    $ uname -a
    # output: Darwin name.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
    # (it's Mac OS X El Capitan 10.11.6 (15G1108))

**Comment by dotcs** [comment]
Found this issue which seems linked with the env variables: https://github.com/yarnpkg/yarn/issues/684

**Comment by indiescripter** [comment]
It's an issue that I've encountered & been bitten by.

Say you type
`npm run foobar` then `npm_config_argv` will show "run" and "foobar" in the both the cookked & original arguments arrays.

However if you type
`yarn foobar` then `npm_config_argv` will show only "foobar" in the both the cookked & original arguments arrays, that is, leaving out "run".

So that's a genuine compatibility issue that actually arisen for me.

**Comment by BYK** [comment]
@indiescripter submitted #4479. Hope it helps you a bit?

**Comment by indiescripter** [comment]
@BYK Thanks I'll check your #4479 out.
