### ISSUE TITLE
Install On Windows Not Recognized

### ISSUE THREAD

**Issue by paulxtiseo** [yarnpkg/yarn#2228]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Installed on Win10-64 from MSI downloaded from site. Post-install, the execution of `yarn --version` from the command-line results in the message:
```
> yarn --version
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```
This is typically a PATH issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
May be system-specific. Uninstall and re-install leads to the same issue.

**What is the expected behavior?**
No PATH issue.

**Please mention your node.js, yarn and operating system version.**
nodejs v7.2.1, yarn v0.17.10 and win10-64

**Comment by paulxtiseo** [comment]
Advice on what to do next? Not sure what the MSI intends to do...SHould I add the bin to the P{ATH, or maybe do an `npm link`?

**Comment by charpeni** [comment]
Yarn should be added to the path variable automatically by the installer.

Did you restart your console after the installation to reload Environment Variables ?

**Comment by paulxtiseo** [comment]
Nvm. I did restart the console. However, a system restart (after installing another piece of software requiring it) seemed to make Yarn available on the path.
