### ISSUE TITLE
NPM dependencies added with "yarn add" are added with a "+deprecated" suffix. Is this expected behaviour?

### ISSUE THREAD

**Issue by sgarcia-dev** [yarnpkg/yarn#2231]
After running `yarn add phantomjs --dev --exact` I got my dependency added with a "**+deprecated**" suffix, is this normal? Here is the output inside my `package.json` file;

```
"devDependencies": {
    "phantomjs": "2.1.7+deprecated"
  }
```

I'm using yarn v0.16.0 on node v6.2.1 on Windows 10 x64 bit. Forgive me if this is a dumb question, I checked through open issues and the docs on yarn and NPM and found nothing about this "**+deprecated**" suffix, and doing `npm install --save-dev --exact phantomjs` didn't add that extra "**+deprecated**" flag

**Comment by starwed** [comment]
Since [phantomjs](https://www.npmjs.com/package/phantomjs) *is* [deprecated](https://docs.npmjs.com/cli/deprecate), I assume that it's just an indication of that, and not something that gets added to every package added that way.  :)

**Comment by torifat** [comment]
Yes, it's normal.
