### ISSUE TITLE
yarn global add typings not executable directly from CLI

### ISSUE THREAD

**Issue by akrueger** [yarnpkg/yarn#2233]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn global add typings` command installs `typings` package and creates the following link: `typings -> ../typings/dist/bin.js` in the directory: `~/.config/yarn/global/node_modules/.bin`

However executing `typings` in the CLI results in: `zsh: command not found: typings`

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn global add typings`
`typings`

**What is the expected behavior?**
To reference the `.bin` link: `../typings/dist/bin.js`. When this path is executed directly typings works as expected

**Please mention your node.js, yarn and operating system version.**
Node 7.2.1
Yarn 0.17.10
macOS 10.12.1

**Comment by plessbd** [comment]
I believe this would be related to #2310 which is not having the right PATH

On mac the fix that I have found so far is to add to your path `$HOME/.config/yarn/global/node_modules/.bin`
So iin zshrc I have
```
export PATH="$PATH:`yarn global bin`:$HOME/.config/yarn/global/node_modules/.bin"
```

This at least fixes it temporarily

```
yarn --version
0.18.1

node --version 
v7.3.0

brew --version
Homebrew 1.1.5
Homebrew/homebrew-core (git revision c1ee; last commit 2016-12-23)

uname -a
Darwin **** 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

**Comment by akrueger** [comment]
Yes! I should have closed this. The confusion was because I still had some global modules from when yarn was installed under npm. Thus the links for those were still through the PATH related to npm. When I reinstalled Yarn through Homebrew, the first global I installed didn't work because I hadn't added Yarn to the PATH, but my previous globals did. That was my confusion.

Thanks!
