### ISSUE TITLE
Idempotent installs

### ISSUE THREAD

**Issue by CrabDude** [yarnpkg/yarn#2241]
**Summary**
Remove stateful dependency of `yarn install` on existing `node_modules`.**

**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Unknown / Undocumented.

**Background**
Presently, a major headache with `npm` / binary `node_modules` (e.g., `heapdump`) is the need to manually run `npm rebuild` when upgrading node. Communicating this preemptively to developers prior to an upgrade is logistically very manual, leading to "Why is this broken for me?" when errors are not obvious (e.g., `Error: Cannot find module '../build/Debug/addon'`).

Since `yarn install` is near instant when dependencies are unchanged, having developers run `yarn install` after a `git pull` is no big deal. However, having developers regularly run `yarn install --force` with many dependencies is a non-starter (1s vs 100s).

**Goal**
Ideally, `yarn install` would ensure the resulting `node_modules` is identical regardless of whether there is an existing `node_modules` or not. If this is not an explicit goal of the yarn project, it at least seems very inline with the spirit of deterministic builds (same `node_modules` independent of whether `node_modules` exists or the version of node that generated it).

Path A (`node_modules` dne, node@X):
- `yarn install` => binaries for node@X

Path B: (`node_modules` built for node@X, node@Y)
- **Current, non-ideal**: `yarn install` => binaries for node@X
- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Ideal**: `yarn install` => binaries for **node@Y**

**Conclusion**
IOW, ideally, the result of `yarn install` **would not be statefully dependent** on the state of the existing `node_modules`. Alternatively, a flag would work as a weaker solution (e.g., `yarn install --strong`), that would be settable in `.yarnrc`.

**Comment by SimenB** [comment]
I'd like for running dedupe to be unecesarry, so a `--force` without a rebuild. Especially when upgrading deps, the tree isn't deduped, and running `yarn dedupe` tells me yarn does it by default, which is a lie, as running `yarn --force` dedupes, while just `yarn` tells me everything is up to date

**Comment by CrabDude** [comment]
Discussion moved to https://github.com/yarnpkg/rfcs/pull/37
