### ISSUE TITLE
Why isn't 0.18 installable from the npm registry?

### ISSUE THREAD

**Issue by zeke** [yarnpkg/yarn#2244]
0.18 is among the versions published to the npm registry:

```
❯ npm show yarn versions
 
[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.15.1',
  '0.16.0',
  '0.16.1',
  '0.17.0',
  '0.17.2',
  '0.17.3',
  '0.17.4',
  '0.17.5',
  '0.17.6',
  '0.17.7',
  '0.17.8',
  '0.17.9',
  '0.17.10',
  '0.18.0' ]
```

but npm installs an older version with a deprecation warning:

```
❯ npm i -g yarn
npm http request GET https://registry.npmjs.org/yarn
npm http 304 https://registry.npmjs.org/yarn
npm WARN deprecated yarn@0.17.10: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
```

I assume this means `npm install`ing the yarn CLI will no longer be supported. Is that a correct assumption?

**Comment by newoga** [comment]
@zeke `0.18.0` is a pre-release. `npm install` will install the version specified at the `latest` tag which currently is `0.17.10`. I'm sure once `0.18.0` is stable they'll update the `latest` tag to `0.18.0`.

```bash
$ npm dist-tag ls yarn
latest: 0.17.10
rc: 0.18.0
```

**Comment by Daniel15** [comment]
Yes, @newoga is right! 0.18.0 is essentially a release candidate. We do need to do a much better job of handling RCs - That'll be covered by #2161. 

I'm going to close this issue since your question was answered. Thanks for trying Yarn! 😃

**Comment by zeke** [comment]
`npm install -g yarn@rc` did the trick. Thanks.
