### ISSUE TITLE
"Error: TODO" when installing from a private GitHub repository

### ISSUE THREAD

**Issue by kaicataldo** [yarnpkg/yarn#2246]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
Unhelpful (unfinished) error message when installing from a private GitHub repository with a dependency in the following format.

Would be great to make this a more helpful error! I'm up for helping to implement if this is amenable to the team.

**If the current behavior is a bug, please provide the steps to reproduce.**

package.json:
```json
{
  "dependencies": {
    "pkg-name": "org-name/pkg-name#v3.0.0"
  }
}
```
I'm seeing the following error:
```
~/Code/test/yarn-test
❯ yarn
yarn install v0.17.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "TODO".
info If you think this is a bug, please open a bug report with the information provided in "/Users/cataldo/Code/test/yarn-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

And here's the stack trace from the yarn-error.log file:
```
Trace: 
  Error: TODO
      at /usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/lib/resolvers/exotics/hosted-git-resolver.js:135:15
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
**What is the expected behavior?**
A more helpful error message. Took some digging to understand what the cause was.

**Please mention your node.js, yarn and operating system version.**
Node: v7.2.1
npm: 4.0.3
yarn: 0.17.10

**Comment by wyze** [comment]
Duplicate #1921.

**Comment by kaicataldo** [comment]
Ah, sorry about that. Thanks.
