### ISSUE TITLE
Installation Problem: Brew yarn behind npm yarn version

### ISSUE THREAD

**Issue by chasm** [yarnpkg/yarn#2247]
Using brew, the version I get is 0.17.10. But my coworkers who install via npm are on 0.18, which I note is stable. I saw a message that said that we should be installing yarn using brew (or equivalent), but this creates a problem as I need to be on the same version as my coworkers, and convincing them to back up a version is difficult. Also, some are on Windows, so these need to be consistent, too.

Is there a way to change the yarn version when using brew to install that I missed?

**Comment by zephraph** [comment]
@chasm have you tried running `yarn self-update`?

**Comment by chasm** [comment]
$ yarn self-update
yarn self-update v0.17.10
error An unexpected error occurred: "https://yarnpkg.com/latest-version: SSL Error: SELF_SIGNED_CERT_IN_CHAIN"

**Comment by newoga** [comment]
@chasm It'd probably be best to have you and your coworkers all agree to use the latest stable version and not install from `npm`. It's possible that your coworkers installed from npm before the package managers applied the `latest` was changed back to `0.17.10` from `0.18.0`.

Assuming they are going to continue installing yarn from `npm`. The quickest fix for them would be to reinstall it globally now `npm install -g yarn` and it should reinstall `0.17.10` for them.

**Comment by chasm** [comment]
OK, so the package managers should keep up with the latest stable versions, and we're assuming that 0.18 is no longer marked stable. Thanks!

**Comment by Daniel15** [comment]
Yeah 0.18.0 is essentially a release candidate. 0.17.10 is considered the latest stable version. You can use 0.18.0 if you like, it just hasn't undergone extensive testing yet.

#2161 tracks improving the RC process so we'll have properly labelled RC releases in the future.

I'm going to close this out since I think your questions have been answered. Thanks! :D
