### ISSUE TITLE
Couldn't find documentation about single-file build or what "legacy" means

### ISSUE THREAD

**Issue by glasser** [yarnpkg/yarn#2248]
**Do you want to request a *feature* or report a *bug*?**

Documentation issue

**What is the current behavior?**

Yarn publishes (in GitHub releases) a "modern" and "legacy" single-file JavaScript build.

This build doesn't seem to be documented anywhere other than in [a random section in a blog post](https://yarnpkg.com/blog/2016/11/24/offline-mirror).

It also takes a fair amount of poking around (not inside the files themselves!) to learn that "legacy" means Node 4 and "non-legacy" means Node 5.

These builds (which are useful!) should be documented, maybe in https://yarnpkg.com/en/docs/install#alternatives-tab , maybe in the release notes themselves.

Perhaps one could even change the build process to add a simple explanatory output (including required Node versions) to the top of the files.

**Please mention your node.js, yarn and operating system version.**

Just looking at https://github.com/yarnpkg/yarn/releases as of 0.18.0

**Comment by glasser** [comment]
Also perhaps worth documenting that if you use this version, you won't have `node-gyp` on your PATH, which will break some modules. See https://github.com/yarnpkg/yarn/issues/1986

**Comment by Daniel15** [comment]
Hey, that's a good idea! Since this is a documentation issue, I'm going to move it to the website repo.

**Comment by Daniel15** [comment]
This issue was moved to yarnpkg/website#311
