### ISSUE TITLE
Option or command to maintain a minimal yarn-offline-mirror

### ISSUE THREAD

**Issue by glasser** [yarnpkg/yarn#2251]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Yarn provides a yarn-offline-mirror feature which saves tarballs of the modules that are used to a specified directory. This can be shared across projects or just used for one project

Yarn only writes to this directory. It never deletes from the directory.

If you are only using the directory for one project and are checking it into git, you may wish to only keep files in the offline mirror for packages currently being used by the project.  This is the behavior of the npm "shrinkpack" utility.  It would be nice to have an easy way to delete files from the offline mirror directory that aren't used any more, either with a new cleanup command, or a yarnrc config option that says to delete unused tarballs after installing.

**Comment by mkxml** [comment]
If I'm not wrong this issue has been addressed with [yarn-offline-mirror-pruning](https://yarnpkg.com/en/docs/prune-offline-mirror). Can this issue be closed?
