### ISSUE TITLE
~/.yarn-cache vs ~/.cache/yarn

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#2255]
It seemed that previously yarn cache was located by default in `~/.yarn-cache` and now I see it in the `~/.cache/yarn`, has it changed?

**Comment by torifat** [comment]
Yes, use ` yarn cache dir`. It uses system cache dir now. In `Ubuntu` it's `~/.cache/yarn` and in `macOS` `/Library/Caches/Yarn`.
