### ISSUE TITLE
More detailed "incorrect peer dependency" message

### ISSUE THREAD

**Issue by knowbody** [yarnpkg/yarn#2258]
**Do you want to request a *feature* or report a *bug*?**

- feature

**What is the current behavior?**

At the moment the warning message looks something like:
> Incorrect peer dependency "react-native@>=0.38.0".

**What is the expected behavior?**

Wouldn't it be useful to show which module is not satisfied?

```
Incorrect peer dependency "react-native@>=0.38.0" for module "exponent".
```

**Comment by wyze** [comment]
Duplicate #1556 and fixed via #2207.
