### ISSUE TITLE
Incomplete installation of sass-lint package

### ISSUE THREAD

**Issue by damonsmith** [yarnpkg/yarn#2259]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

I ran yarn for the first time on a large project. The `yarn` command completed successfully but my build fails because it can't find node_modules/sass-lint/lib/config/sass-lint.yml

Sass-lint is a dependency of gulp-sass-lint and it installed most of the files from the package but not that one in config. Running in verbose mode gives  me:

```
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/.editorconfig" to "/Users/damon/Work/project/node_modules/sass-lint/.editorconfig".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/.eslintrc" to "/Users/damon/Work/project/node_modules/sass-lint/.eslintrc".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/.npmignore" to "/Users/damon/Work/project/node_modules/sass-lint/.npmignore".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/.nvmrc" to "/Users/damon/Work/project/node_modules/sass-lint/.nvmrc".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/.travis.yml" to "/Users/damon/Work/project/node_modules/sass-lint/.travis.yml".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/CHANGELOG.md" to "/Users/damon/Work/project/node_modules/sass-lint/CHANGELOG.md".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/CONTRIBUTING.md" to "/Users/damon/Work/project/node_modules/sass-lint/CONTRIBUTING.md".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/CODE_OF_CONDUCT.md" to "/Users/damon/Work/project/node_modules/sass-lint/CODE_OF_CONDUCT.md".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/LICENSE" to "/Users/damon/Work/project/node_modules/sass-lint/LICENSE".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/README.md" to "/Users/damon/Work/project/node_modules/sass-lint/README.md".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/appveyor.yml" to "/Users/damon/Work/project/node_modules/sass-lint/appveyor.yml".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/index.js" to "/Users/damon/Work/project/node_modules/sass-lint/index.js".
verbose Copying "/Users/damon/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/package.json" to "/Users/damon/Work/project/node_modules/sass-lint/package.json".
```

Looking inside the cache directory I can see:
```
ls ~/Library/Caches/Yarn/npm-sass-lint-1.10.2-825bd6b0da79ddd36a42ffae5b6d44ac4922502b/lib/config/
property-sort-orders/ sass-lint.yml
```

So the file exists but for some reason Yarn is choosing not to copy the yml files from lib/config across to my project. (It also doesn't copy the files in lib/config/property-sort-orders)

Running a `yarn cache clean` fixes the problem and now I can't reproduce. There is another reporter of this same bug in the sass-lint issues page though so it seems intermittent.

Other developers on the same project didn't see the error at all either, it only affected me.

Also, running a `yarn add sass-lint` to add sass-lint as a top level dependency, then deleting node_modules and running `yarn` again didn't fix the problem. It did the same partial copy many, many times.

**What is the expected behavior?**
I'd expect it to just copy all of the files in the module across. Not sure what the decision process is for which files to copy.

**Please mention your node.js, yarn and operating system version.**
yarn: 0.17.10
node v6.3.1
os: MacOS 10.11.5

**Comment by angrypepsi** [comment]
I have same problem.
Is there anyone have solved it?

**Comment by fjoesne** [comment]
I have a similar issue, however I'm being told that the target directory is being created and the files are copied, while in reality that doesn't happen. Manually doing the step that is indicated by the verbose log works, so the file exists in the cache and there is nothing else hindering the package from being copied to the correct location.

The package I'm having problems with (as far as I know) is clean-css@2.2.23 as a dependency of browserify-css. 

Adding clean-css directly produces the same result. Again I'm being told the directory is created and that its content are being copied without it actually happening.

macOS: 10.12.3
Node: v7.7.2
yarn: 0.21.3

**Comment by bestander** [comment]
Can't reproduce 
```
ls node_modules/sass-lint/lib/config/property-sort-orders/
concentric.yml	recess.yml	smacss.yml
```
