### ISSUE TITLE
Failing test due to platform ident bug

### ISSUE THREAD

**Issue by polizz** [yarnpkg/yarn#2261]
**Bug**
/__tests__/commands/run.js (handles bin scripts) fails due to escaping issue.

**Reproduce**
1. Fork repo and run tests.

**What is the expected behavior?**
Mac (Darwin) should not receive Windows backslash path transformation.

**Platform**
Node 6.9.1, 7.2.1
Mac 10.12.1

Fix incoming.

**Comment by Daniel15** [comment]
#2262 should fix this.
