### ISSUE TITLE
--modules-folder could be specified in .yarnrc?

### ISSUE THREAD

**Issue by shouze** [yarnpkg/yarn#2264]
For good reasons (containerization) we decided to put installed node_modules in a directory outside of our repository source code.

So when we build our container the build step uses the `--modules-folder` option. I wanted to know if it would be specified in .yarnrc but it seems that no?

Is there any reason for that? I can open an RFC if needed when I'll know more about that ;)

**Comment by typoworx-de** [comment]
I also vote for any option to specify custom-folder just like bower does using .bowerrc. For neither npm nor yarn are a real option until one can define the paths to their own needs!

**Comment by joubertredrat** [comment]
Bump for this, for me that use [Symfony](https://symfony.com/) and need yarn only to download assets like [jQuery](https://jquery.com/) and [Semantic UI](https://semantic-ui.com/) and put on my `web` folder, if I can to set this on config file is best.

On bower I make this on `.bowerrc` file with this config.
```json
{
  "directory": "web/assets/vendor/"
}
```

**Comment by rally25rs** [comment]
You can specify it in `.yarnrc` like this:

```
--*.modules-folder "./wwwroot/lib"
```

The `--*.` will make the flag apply to all commands (install, add, etc)
