### ISSUE TITLE
node-gyp builds fail on bundled yarn

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2266]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**

```
bestander-mbp:bignum bestander$ node ~/work/yarn/artifacts/yarn-0.17.10.js add base85
yarn add v0.17.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
⠁
⠁
⠁
⠁
error /Users/bestander/work/temp/bignum/node_modules/bignum: Command failed.
Exit code: 127
Command: sh
Arguments: -c node-gyp configure build
Directory: /Users/bestander/work/temp/bignum/node_modules/bignum
Output:
sh: node-gyp: command not found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Please mention your node.js, yarn and operating system version.**

Node 6.9.1, Yarn 0.17.10

**Comment by bestander** [comment]
Reason - we use `path.join(__dirname, '..', '..', 'bin', 'node-gyp-bin'))` in source.
When everything is bundled in one file __dirname is incorrect.

**Comment by bestander** [comment]
+ needed tests to prevent from __dirname breaking bundled builds later

**Comment by wyattjoh** [comment]
This is currently causing issues for our build, anything I can do to assist?

**Comment by terribleplan** [comment]
Our build has been broken since docker started including this and we stopped running `npm install -g yarn`. I understand that it is not recommended, but at least it actually worked.

Paging @Daniel15 since he seems like a cool guy ;)

**Comment by bestander** [comment]
Thanks the team is in the loop, we'll figure something out

**Comment by terribleplan** [comment]
Cool, just wanted to make sure. We have a workaround in place, but it was pretty bad/interesting/weird/fun to have our build and dev workflow break when it wasn't our fault.

**Comment by Daniel15** [comment]
Based on https://github.com/nodejs/docker-node/issues/346, it sounds like running `yarn install -g node-gyp` is a viable workaround for now.

> Paging @Daniel15 since he seems like a cool guy ;)

😊

**Comment by Daniel15** [comment]
Based on https://github.com/nodejs/docker-node/issues/346, it sounds like running `yarn global add node-gyp` is a viable workaround for now.

> Paging @Daniel15 since he seems like a cool guy ;)

😊

**Comment by terribleplan** [comment]
```
 RUN rm -rf node_modules/

+# This line should be removed when the included version of yarn in the container
+# is no longer broken https://github.com/yarnpkg/yarn/issues/2266
+RUN yarn global add node-gyp
+
 RUN yarn
```

**Comment by bestander** [comment]
The bundled build could include a small bootstrap section that would do `yarn global add node-gyp` and also generate [node-gyp-bin](https://github.com/yarnpkg/yarn/tree/master/bin/node-gyp-bin) folder

**Comment by bestander** [comment]
Oh, and as always, this could be a cool contribution to send a PR for!
