### ISSUE TITLE
optional dependencies that fail builds should be removed from node_modules

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2274]
**Do you want to request a *feature* or report a *bug*?**

feature/bug

**What is the current behavior?**

Optional Dependencies are first linked (files are copied from cache to node_modules) and then their install scripts are executed.
If install script fails this is considered OK but node_modules then has a half built folder.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created test `optional dependency that fails build should still be installed` in integration.js that covers current behavior but I think it should be changed.

**What is the expected behavior?**

I think Yarn should remove failed to install optional modules from node_modules.

**Please mention your node.js, yarn and operating system version.**

Yarn 0.18.0

**Comment by bestander** [comment]
On the other hand if a dependency has `os` field incompatible with the current OS then yarn won't even try to install it.

**Comment by MarshallOfSound** [comment]
I reported this and it was marked as fixed #1328 

Haven't tested the situation in latest nightlies yet thoguh as I wrote a `postinstall` script to clean up those dead folders for me.

**Comment by bestander** [comment]
Yeah, looks like it has not been fixed after all.
The test refers to this issue id, so let's keep this one open.
Thanks for opening it earlier.
