### ISSUE TITLE
Don't auto clean .yml files.

### ISSUE THREAD

**Issue by aj0strow** [yarnpkg/yarn#2276]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Related to https://github.com/yarnpkg/yarn/issues/1051. Right now `yarn clean` produces a clean file that removes `.yml` files. 

```
.*.yml
*.yml
```

**What is the expected behavior?**

It's too aggressive to auto delete config files. You wouldn't auto delete `.toml` or `.json` files, so also shouldn't auto delete `.yml` files. 

It would be more appropriate to remove specific well known configs, like `circle.yml` etc. 

**Please mention your node.js, yarn and operating system version.**

```
$ node -v
v5.6.0

$ yarn version
yarn version v0.17.10

$ m info
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108
```

**Comment by lili21** [comment]
??

**Comment by quirkyshop** [comment]
still get a problem when exec yarn clean, such as .svgo.yml problem reproduce everytime.

yarn version: v0.23.4

**Comment by tjormola** [comment]
+1

**Comment by MartinHaeusler** [comment]
This issue just bit me as well. I'm by no means an expert in this field, but why do you even bother to selectively delete/keep files? On `yarn clean`, I would expect something like
    
    rm -rf node_modules
    yarn install

... or similar.

**Comment by rally25rs** [comment]
I'm actually curious what the use case is for even running `yarn clean`? The docs basically say "don't use this" so why even make the command available?

I can only venture to guess that the intent was to remove files that _probably_ weren't needed for a production deployment to run, saving some HD space, but it doesn't seem like the `clean` command should ever be run under a development environment.

I would think a lot of issues could be avoided by just removing this command, or do what NPM5 did with `cache clear` and have it do nothing unless you pass a `--force` flag, preventing accidental running of the command.

**Comment by twothe** [comment]
Just fell into the same trap. Why exactly is there a function that as a result will permanently destroy your builds until you deactivate it?

**Comment by BYK** [comment]
>It would be more appropriate to remove specific well known configs, like circle.yml etc.

+1 to this. PR's welcome everyone :D
