### ISSUE TITLE
How to install only production dependencies when NODE_ENV is not production and no control over CLI args

### ISSUE THREAD

**Issue by adamreisnz** [yarnpkg/yarn#2283]
### Use case
We have several production-*like* environments, e.g. `staging` or `demo`, which don't need to have `devDependencies` installed.

The `NODE_ENV` setting is used to distinguish between those environments, and causes the app to load configuration specific for that environment.

We are deploying on services like Heroku or Netlify, where you don't get to control the command used to *install* or build an app. E.g. Heroku simply runs `npm install`. As such, the only means of control we have are environment variables.

### Question
How do we force `yarn` to install **only** production dependencies given the constraints presented above? 

I've seen a `YARN_PRODUCTION` flag mentioned here and there, but I'm not sure if it's an actual thing and I can't Google for it due to the false results I get for that search query.

**Comment by adamreisnz** [comment]
I've resorted to dropping our app's dependency on `NODE_ENV` and introduced an `APP_ENV` instead. This way, configuration etc. can use the `APP_ENV` setting, while the build process can use the dedicated `NODE_ENV`.

Not ideal, but given the various constraints this was the best solution I could come up with. If anyone has other idea's I'd love to hear them.

**Comment by Daniel15** [comment]
> We are deploying on services like Heroku or Netlify, where you don't get to control the command used to install or build an app. 

Tangential to this issue, but you can change the build command on Netlify.

**Comment by adamreisnz** [comment]
Yep, but this is not possible on Heroku I'm afraid. But I'm actually quite happy with our solution. It gives us more flexibility and control over the build process.

**Comment by vernak2539** [comment]
Has anyone figured out a solution for heroku?

All of the following still results in installation of all dependencies

```
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        YARN_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
```
