### ISSUE TITLE
`yarn self-update` doesn't run on 0.18.1

### ISSUE THREAD

**Issue by ewhitebloom** [yarnpkg/yarn#2300]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
> yarn self-update
error Command "self-update" not found.

the "yarn self-update" command is not found, despite being in the current docs, and I've run this command before on previous releases.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
Node: 6.9.2, Yarn: 0.18.1, OS: macOS Sierra 10.12.2

**Comment by Daniel15** [comment]
The old version of `yarn self-update` wasn't implemented correctly - #1139 tracks improvements to it. Closing this issue in favour of #1139. Thanks!
