### ISSUE TITLE
Include link to release notes in Chocolatey package

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2301]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The Yarn Chocolatey package does not have a `<releaseNotes>` section in the nupkg

> Release Notes (releaseNotes) are a short description of changes in each version of a package. Please include releasenotes in the nuspec. NOTE: To prevent the need to continually update this field, providing a URL to an external list of Release Notes is perfectly acceptable. 

**What is the expected behavior?**
The Chocolatey package should include a link to the GitHub release, which includes the release notes. URL should be like `https://github.com/yarnpkg/yarn/releases/tag/v{VERSION}` (eg. https://github.com/yarnpkg/yarn/releases/tag/v0.18.1)

**Comment by polizz** [comment]
https://github.com/yarnpkg/yarn/pull/2302

**Comment by Daniel15** [comment]
Fixed by #2302, thanks @polizz!
