### ISSUE TITLE
There are still references to `yarn self-update`

### ISSUE THREAD

**Issue by wagenet** [yarnpkg/yarn#2308]
https://github.com/yarnpkg/yarn/blob/6e7d396451ed7622a92f4a25d9370e5724c54635/src/lockfile/parse.js#L180

**Comment by meta-meta** [comment]
also in the docs https://yarnpkg.com/en/docs/cli/self-update

**Comment by Daniel15** [comment]
We do want to have self-update working again at some point, #1139 tracks that.

**Comment by wagenet** [comment]
Seems like it would make sense to keep the command around then and just have it issue a notice that it's currently not working.

**Comment by BYK** [comment]
Closing this since we want to add the command back and now that issue is triaged as high priority.
