### ISSUE TITLE
Yarn unusually slow (slower than NPM) on MacOS Sierra, CRA-based project

### ISSUE THREAD

**Issue by Connorelsea** [yarnpkg/yarn#2330]
Firstly: Thank you all for your work on Yarn! I appreciate it. I just have a small issue and am wondering if I am doing something wrong.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Yarn runs unusually slow (when installing `yarn add ...` new packages and when running `yarn` after `rm -rf node_modules`

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my Yarn output:
![image](https://cloud.githubusercontent.com/assets/1844458/21441520/fc572d3e-c85d-11e6-8887-4cd885ca7117.png)

This is my package.json (which shows my dependencies): https://gist.github.com/Connorelsea/91438f391215830dc32ac44b48bcb388

Runtime:
Yarn runs from 15:32:19 to 15:34:37
NPM runs from 15:35:30 to 15:36:48

**What is the expected behavior?**

For yarn to run faster. I just want to know if I am doing something incorrect here. I have installed all these packages before and assume they should be cached.

**Please mention your node.js, yarn and operating system version.**

MacOS: Sierra 10.12
Node: v6.5.0
Yarn: 0.16.1
NPM: 3.10.3

Just tried this again with yarn 0.18.1 and got similar behavior.

![image](https://cloud.githubusercontent.com/assets/1844458/21441960/a0398a58-c860-11e6-9c40-26f7ecad5d47.png)

**Comment by janpieterz** [comment]
I have very similar, extremely slow, speed behavior on Windows with Yarn 0.18.1, on an already installed project simply adding one package.

It took 382.68s !

Os: Windows 10 Anniversary +
Node: v7.2.0
Yarn: 0.18.1

**Comment by Connorelsea** [comment]
Though I could be wrong, I saw some issues when searching with Windows specific problems, which may be the issue you are having @janpieterz . I am on MacOS Sierra

**Comment by Huynt-dev** [comment]
Sorry a bit unrelated, but your terminal is very nice. Can you tell me how to get it? Thanks :D
