### ISSUE TITLE
Cannot run Yarn command after updating by using Windows Installer

### ISSUE THREAD

**Issue by cokencode** [yarnpkg/yarn#2332]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I ran `yarn` command, I got an error below.
```
C:\Program Files (x86)\Yarn\bin\yarn.js:62
      throw err;
      ^

Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Yarn\updates\0.17.10\lib\cli\index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\bin\yarn.js:54:22)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
I uninstalled the previous version(0.17.10) of Yarn and delete Yarn folder.
Then I installed the latest version(0.18.1) using Yarn installer(.msi).

**Please mention your node.js, yarn and operating system version.**
OS: Windows 10 Home
node: 6.9.1
yarn:  0.18.1

**Comment by Daniel15** [comment]
The path in the error has 0.17.10 in it... It sounds like you might still have old files hanging around. Try uninstalling Yarn, deleting the directory, then reinstalling it.

**Comment by cokencode** [comment]
@Daniel15 I reinstalledYarn again, then it works now. I probably missed somthing before... Thank you for your help :D

**Comment by corydeppen** [comment]
I have the same issue - the error mentions the `\updates\0.17.10` directory, which doesn't exist now that I uninstalled and removed the `Yarn` directory. At this point, I can't even run Yarn after performing a clean install. I hope someone has another idea.

**Comment by corydeppen** [comment]
The `yarn.js` script adds paths, including the nonexistent `updates` directory, to the list of possible paths. Unfortunately, the logic inside the `catch` is only looking for `err.code === 'MODULE_NOT_FOUND'`. It seems like this should also check for the `ENOENT` code as well to handle cases where the `updates` directory doesn't exist. As long as there are possibles left to check, the logic should continue.

```js
if (semver.satisfies(ver, '>=5.0.0')) {
  possibles.push('../updates/current/lib/cli/index.js');
  possibles.push('../lib/cli/index.js');
} else if (semver.satisfies(ver, '>=4.0.0')) {
  possibles.push('../updates/current/lib-legacy/cli/index.js');
  possibles.push('../lib-legacy/cli/index.js');
} else {
  console.log(require('chalk').red('Node version ' + ver + ' is not supported, please use Node.js 4.0 or higher.'));
  process.exit(1);
}
```

**Comment by kaskazurek** [comment]
**My workaround**

Remove manually:
- `C:\Users\[user_name]\AppData\Local\Yarn`
- `C:\Program Files (x86)\Yarn`
- from PATH environment variable: `C:\Users\[user_name]\AppData\Local\Yarn\.bin` (for user) and `C:\Program Files (x86)\Yarn\bin` (for system)

Then install Yarn again and everything should work properly.

**Comment by Daniel15** [comment]
I removed that `updates` logic in #2720
