### ISSUE TITLE
yarn install goes to infinite loop

### ISSUE THREAD

**Issue by anton-kabysh** [yarnpkg/yarn#2335]
When running `yarn install` it goes to infinite loop.
Yarn installed globally.
Node v7.1.0

![image](https://cloud.githubusercontent.com/assets/809822/21453235/42dbc506-c91e-11e6-8550-042af133df1e.png)

**Comment by hawkrives** [comment]
Do you have anything defined in the `scripts` section of your `package.json`?

**Comment by anton-kabysh** [comment]
Yes. 
```
"scripts": {
        "install": "yarn install",
        "task": "./node_modules/.bin/gulp --gulpfile ./config/tasks.js --cwd .",
        "clean": "./node_modules/.bin/gulp --gulpfile ./config/tasks.js --cwd . clean",
        "webpack": "webpack"
    }
```
I call `npm run install` from other build system (sbt) to install js deps when resolving dependencies for main project. 
If I remove `"install": "yarn install"` -- everything is OK. Hmm, where is the problem here? I can't use `install` name for npm script?

**Comment by CaffeinatedCM** [comment]
You can use `install `as the name for npm scripts, but if you look at the [docs](https://docs.npmjs.com/misc/scripts) you'll see that `install` is just an alias for post install. What's happening here is yarn installs the packages, then the `install` script (or `postinstall`) gets called. Which does the same thing. 

You really don't need a script that says `yarn install` since you could just type that with yarn installed globally.

**Comment by trusktr** [comment]
I have a `postinstall` script that calls `yarn install`. I am trying to migrate from npm. I had this before:

```
    "postinstall": "npm install --no-save grpc@1.7.3 --runtime=electron --target=1.7.9"
```

which works great: `npm install` is followed by the install of `grpc` then everything is done, no infinite loop.

I change it to:

```
    "postinstall": "yarn install --no-save grpc@1.7.3 --runtime=electron --target=1.7.9"
```

and then `yarn install` goes to an infinite loop, unlike `npm`.

So, after `yarn install` is finished, how do I automatically run another install?

**Comment by HannanShaikYara** [comment]
@trusktr did you manage to workaround this issue? I am facing the same error.

**Comment by debugmaster** [comment]
If anyone still encounters this issue, I was able to fix it with `--ignore-scripts`:
```json
    "scripts": {
        "postinstall": "yarn install --ignore-scripts"
    },
```

Yarn version is `1.15.2`
