### ISSUE TITLE
"stable" version specification for "node" engine is not supported

### ISSUE THREAD

**Issue by DUBANGARCIA** [yarnpkg/yarn#2342]
**What is the current behavior?**

When I try to install generator-ng-fullstack globally, getting this error message.

![error](https://cloud.githubusercontent.com/assets/17387158/21482315/2f88ca48-cb40-11e6-872c-550015a89ea2.PNG)

yarn version:  0.18.1
node version: 6.9.2
operating sytem version: Windows 10 Pro 64 Bits

But if I install it with npm if it works

**Comment by gsklee** [comment]
@bestander close

This is by design; see [this discussion](https://github.com/yarnpkg/rfcs/pull/69).
