### ISSUE TITLE
debian gpg key eems to be invalid

### ISSUE THREAD

**Issue by tpetry** [yarnpkg/yarn#2343]
```
root@0fbb642c0f83:/# curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_get_keyblock failed: Value not found
gpg: [don't know]: invalid packet (ctb=2d)
gpg: /tmp/tmp.fbFdCGxBbz/pubring.gpg: copy to '/tmp/tmp.fbFdCGxBbz/pubring.gpg.tmp' failed: Invalid packet
gpg: error writing keyring '/tmp/tmp.fbFdCGxBbz/pubring.gpg': Invalid packet
gpg: [don't know]: invalid packet (ctb=2d)
gpg: error reading '-': Invalid packet
gpg: import from '-' failed: Invalid packet
```

executed in actual `ubuntu:16.10` docker image

**Comment by Daniel15** [comment]
Hmm, strange... Try running `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg` by itself and see what you get? We have nightly regression tests running Ubuntu 12.04, 14.04 and 16.04 and they're all fine with the GPG key. Maybe we should add 16.10 to the test suite.

**Comment by tpetry** [comment]
closing, everything is working correct. The `Dockerfile` was by itself adding the `pubkey.gpg` to `/etc/apt/trusted.gpg.d/` which somehow prevented the `apt-key add` operation
