### ISSUE TITLE
;,:$4µ

### ISSUE THREAD

**Issue by vinz243** [yarnpkg/yarn#2352]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by vinz243** [comment]
wtf happened to my issue ?

**Comment by wyze** [comment]
I'm not sure what happened with this issue, but it just posted the template.

**Comment by vinz243** [comment]
I might have miscliked x) real issue still here

**Comment by wyze** [comment]
Okay, no worries!
