### ISSUE TITLE
`yarn global list` is not applied. `yarn global ls` is remained

### ISSUE THREAD

**Issue by namhong2001** [yarnpkg/yarn#2354]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
error message with `yarn global list` cli command

```
yarn global v0.18.1
error Invalid subcommand. Try "add, bin, ls, remove, upgrade"
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

type `yarn global list` in terminal

**What is the expected behavior?**
show globally installed packages

**Please mention your node.js, yarn and operating system version.**
node v6.9.1
yarn v0.18.1 

I think this was dropped with #1940  

Thanks :)

**Comment by bestander** [comment]
Should be fixed https://github.com/yarnpkg/yarn/pull/3308

**Comment by AlphaJuliettOmega** [comment]
@bestander there's a `yarn list` that seems to work, but if `yarn global list` only returns the Yarn Version, does that mean I have 0 global packages installed?
