### ISSUE TITLE
flattening dependencies results in require loading wrong module inside of a nested app

### ISSUE THREAD

**Issue by boblauer** [yarnpkg/yarn#2357]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Imagine I have the following folder structure:

```
root
├─┬ app.js
├─┬ node_modules
│ └── this-module-is-the-problem@7.7.77777
├─┬ sub-app
│ └─ subapp.js
│ └─┬ node_modules
│   └─┬ some-module@1.0.0
│     └── this-module-is-the-problem@5.5.55555
│   └─┬ some-other-module@1.0.0
│     └── this-module-is-the-problem@5.5.55555
```

Inside of `sub-app`, we have 2 top-level modules: `some-module` and `some-other-module`.  Both of these modules share a common dependency, `this-module-is-the-problem@5.5.5555`.  

Given this folder structure, while inside of `subapp.js`, if I did `require('this-module-is-the-problem`), I would correctly get back `this-module-is-the-problem@7.7.77777`.

However, as of `npm@3.x`/`yarn`, `this-module-is-the-problem@5.5.5555` will be moved up a level, resulting in this:

```
root
├─┬ app.js
├─┬ node_modules
│ └── this-module-is-the-problem@7.7.77777
├─┬ sub-app
│ └─ subapp.js
│ └─┬ node_modules
│   └─ some-module@1.0.0
│   └─ some-other-module@1.0.0
│   └─ this-module-is-the-problem@5.5.55555
```

With this folder structure, `require('this-module-is-the-problem')` inside of `subapp.js` will return `this-module-is-the-problem@5.5.55555`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Download and extract the attached zip.
`yarn install` inside of the root folder as well as inside the `sub-app` folder.

run the following commands from the root folder, and observe the following output:

```
npm-bug $ node index.js
1.1.0
npm-bug $ node sub-app/index.js
5.0.15
```

**What is the expected behavior?**

In the attached example, it is reasonable to expect `glob 1.1.0` to be required inside of `sub-app`, since it is not listed as a dependency anywhere in the sub-app's `package.json`.  Which version of a package is returned via `require` should never change depending on which (seemingly) unrelated other packages you have installed.

**Please mention your node.js, yarn and operating system version.**

Node: 4.3.0
Yarn: 0.18.1
OS: Darwin MacBook-Pro-5.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep 1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

**Comment by benmvp** [comment]
If I'm understanding your situation correctly, `sub-app` is depending on `this-module-is-the-problem` (v7.7777) coming from the parent app? And given the folder structure you showed, it has dependencies on `some-module` & `some-other-module` so I'm assuming that `sub-app` actually has a `package.json` file.

How NPM3 & Yarn are working is expected behavior, not a bug. I think instead you need to explicitly include the specific version of `this-module-is-the-problem` you want w/in `sub-app`'s `package.json` and then you'll get the version you want.

**Comment by Daniel15** [comment]
Yeah, this sounds like expected behaviour to me. If `sub-app` depends on `this-module-is-the-problem`, it should explicitly state that in its package.json file.
