### ISSUE TITLE
web project get yarn error

### ISSUE THREAD

**Issue by codingwesley** [yarnpkg/yarn#2358]
git@github.com:ctrlplusb/react-universally.git

web project
os: mac 10.12.2
yarn: v0.17.4

![image](https://cloud.githubusercontent.com/assets/8223607/21558451/3aee5866-ce75-11e6-8bd7-03b1c52db86f.png)

i use npm, resolve it

**Comment by paul-soporan** [comment]
Closing as external, your screenshot shows that this is an issue with npm.
