### ISSUE TITLE
Yarn, gulp and gulp-imagemin: ENOENT

### ISSUE THREAD

**Issue by TJProgrammer** [yarnpkg/yarn#2359]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
After change to yarn package manager, I have got the following error in:
```
[12:39:57] Using gulpfile ~/Web/tp/gulpfile.js
[12:39:57] Starting 'img'...
[12:39:58] gulp-imagemin ERROR spawn ...../tp/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
[12:39:58] Finished 'img' after 734 ms
[12:39:59] gulp-imagemin: ✔ logo/logo-marca.svg (saved 5.32 kB - 61.9%)
[12:39:59] gulp-imagemin: ✔ logo/logo-texto.svg (saved 14.2 kB - 50.1%)
[12:39:59] gulp-imagemin: Minified 2 images (saved 19.5 kB - 52.9%)
```
And the .jpeg minified images don't appear in the folder.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create a gulp script for get some images of different types and minify them with `gulp-imagemin`.
- Run the script.

If helps:
```
gulp.task("img", function() {
  return gulp.src(paths.sources.img)
    .pipe(g.plumber({
      errorHandler: alert
    }))
    .pipe(g.cached('img'))
    .pipe(g.imagemin({
      optimizationLevel: 3,
      progressive: true,
      interlaced: true,
      verbose: stage < 0
    }))
    .pipe(g.rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest(getPath() + 'img'));
});
```

**What is the expected behavior?**
All images types minified with no errors.

**Please mention your node.js, yarn and operating system version.**
node v6.9.2
yarn 0.18.1
Fedora 25

**Comment by TJProgrammer** [comment]
I reinstalled the package and now it is working.
May be this is a transition to yarn bug...

**Comment by joaogarin** [comment]
I have this same issue exactly..It works with npm but for some reason with yarn this fails.

**Comment by TJProgrammer** [comment]
In my case I have to remove this package and reinstall it with yarn --dev
comand.
