### ISSUE TITLE
feature req: --quiet option on yarn install

### ISSUE THREAD

**Issue by jcollum** [yarnpkg/yarn#2368]
```
$ yarn --version
0.17.10
```

Just would be nice to have the option to suppress output if nothing fails. Sometimes you don't need the text saying "all good".

**Comment by jarijokinen** [comment]
I have added --quiet option to my local fork: https://github.com/jarijokinen/yarn/commit/b8591c10b758a9b1d40985914e894c5b219c80fc

Missing tests and not sure if that's best way to implement it anyway.

**Comment by danherd** [comment]
This is a duplicate of #788

**Comment by bestander** [comment]
We have --silent now
