### ISSUE TITLE
Passing slashes in start params are stripped

### ISSUE THREAD

**Issue by raybooysen** [yarnpkg/yarn#2385]
Bug

**What is the current behavior?**
You are able, in NPM to pass in parameters to the script:
```
yarn start -- -U DOMAIN\\username
```

When doing this in NPM, the value of `process.argv` will be:
```
[ '/somepath',
  '.',
  '-U',
  'DOMAIN\username' ]
```

In Yarn however, the value of `process.argv` is:
```
[ '/somepath',
  '.',
  '-U',
  'DOMAINusername' ]
```
In yarn, the slash is missing.

**Please mention your node.js, yarn and operating system version.**
node: 6.9.1
yarn: 0.18.1
OS: Ubuntu 16.10

**Comment by BYK** [comment]
This should be fixed by #3627. Can you upgrade to the latest version of `yarn` and verify it is fixed?

**Comment by BYK** [comment]
@raybooysen can you verify this is solved in yarn 0.27?

If I don't hear back in a few days I'm just gonna assume this is fixed and close the issue. Feel free to reopen if you see my message afterwards and the issue persists.

**Comment by raybooysen** [comment]
@BYK I'm busy moving country at the moment so unlikely I'll be able to test for the next few weeks.  Happy to have it closed and test retrospectively

**Comment by BYK** [comment]
@raybooysen thanks for the response and good luck with the move!

I'll go ahead and close but as agreed, please feel free to reopen if you discover it is not resolved.
