### ISSUE TITLE
file: dependency cache problem

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2403]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

[Needs better repro steps]

If there is a `file:` dependency, e.g.    
```
"eslint-plugin-jest": "file:packages/eslint-plugin-jest",
```
Looks like caches from other installs can affect each other. 
Based on observations of `yarn install` in Jest repo with @cpojer

**Comment by eTorAken** [comment]
May be related to #2165

**Comment by bestander** [comment]
Yes, thanks
