### ISSUE TITLE
https://yarnpkg.com/install.sh failure, returned html and not bash script

### ISSUE THREAD

**Issue by JamesKyburz** [yarnpkg/yarn#2405]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Running `curl -o- -L https://yarnpkg.com/install.sh | bash` failed

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

It seemed to return html and not a bash script.

See https://hub.docker.com/r/jameskyburz/server-base/builds/bifakfqqlrmfakmdshzz8ae/ for proof

or https://gist.github.com/JamesKyburz/17ce714452ac82939325b6a537bcc62f/raw incase dockerhub purges....

The failure was `bash: line 1: syntax error near unexpected token `newline'`

Unfortunately running the script again worked so I don't know what the failure was.

Probably some cloudflare-nginx failure.

**Comment by Daniel15** [comment]
I'm guessing this was either a Cloudflare issue or a Netlify issue. It would be helpful to have the actual text that was returned, but I guess that won't be in the logs :/
