### ISSUE TITLE
The engine "node" is incompatible with this module, for >=0.8

### ISSUE THREAD

**Issue by ivoba** [yarnpkg/yarn#2414]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
I run: 
`yarn add elastic`
and get this error:
`elastic@0.1.10: The engine "node" is incompatible with this module. Expected version "0.8.x".`

the elastic module requires:
```
"engines": {
    "node": ">=0.8"
  }
```
https://github.com/elastic/elasticsearch-js/blob/master/package.json#L114

**If the current behavior is a bug, please provide the steps to reproduce.**

see above
**What is the expected behavior?**
as i am on node 7.4 this error should not appear.

**Please mention your node.js, yarn and operating system version.**
yarn v0.18.1  
on  
node 7.4  in docker container: node:7.4.0 on ubuntu host

**Comment by SimenB** [comment]
You're installing https://www.npmjs.com/package/elastic, but linking to https://www.npmjs.com/package/elasticsearch

```sh-session
$ npm show elastic engines
{ node: '0.8.x', npm: '1.1.x' }
```

**Comment by ivoba** [comment]
yes you are right, sorry
the correct link is https://github.com/LDEngine/elastic/blob/master/package.json#L5
and then its obvious why i receive the error :man_facepalming: 
it expclicitly says `"node": "0.8.x"`
