### ISSUE TITLE
git+ssh installs fail with GitHub URLs with colon separators

### ISSUE THREAD

**Issue by epmatsw** [yarnpkg/yarn#2416]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
When installing from a git url (after having the fix in https://github.com/yarnpkg/yarn/pull/2384), the install fails with:
```
yarn install v0.19.0-20170106.1725
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://git@github.com:githubuser/repo.git /Users/username/Library/Caches/Yarn/.tmp/bff4d24c292f2c5f1a876330de56ef81
Directory: /Users/username/project
Output:
Cloning into '/Users/username/Library/Caches/Yarn/.tmp/bff4d24c292f2c5f1a876330de56ef81'...
ssh: Could not resolve hostname github.com:githubuser: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

It appears that any git url that uses `:` rather than `/` for the separator between the url and github user/org still fails even with the fix.

See comments in https://github.com/yarnpkg/yarn/pull/2384 [1](https://github.com/yarnpkg/yarn/pull/2384#issuecomment-271043591) [2](https://github.com/yarnpkg/yarn/pull/2384#issuecomment-271234287) [3](https://github.com/yarnpkg/yarn/pull/2384#issuecomment-271268246)

**What is the expected behavior?**
The install succeeds without errors.

**Please mention your node.js, yarn and operating system version.**
Node 7.4.0, yarn 0.19.0, macOS 10.12.2

**Comment by chrisirhc** [comment]
Related to https://github.com/yarnpkg/yarn/issues/573#issuecomment-270959845 . Seems that a custom resolver needs to be set up to handle the `:` behavior.
