### ISSUE TITLE
yarn install fails with git archive failure on travis

### ISSUE THREAD

**Issue by doug-wade** [yarnpkg/yarn#2428]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
> GPG signature looks good
> Extracting to ~/.yarn...
> Adding to $PATH...
> We've added the following to your /home/travis/.bashrc
> If this isn't the profile of your current shell then please add the following to your correct profile:
   
export PATH="$HOME/.yarn/bin:$PATH"
> Successfully installed Yarn 0.18.1! Please open another terminal where the `yarn` command will now be available.
Setting up $PATH
$ export PATH=$HOME/.yarn/bin:$PATH
9.58s$ yarn
yarn install v0.18.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: archive 78d589f19519c87ba1549492f5c9d09da4609183
Directory: /home/travis/.cache/yarn/.tmp/749720ec53a1a00c21f4e78688f87cb4
Output:
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn" failed. Retrying, 2 of 3.
yarn install v0.18.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: archive 78d589f19519c87ba1549492f5c9d09da4609183
Directory: /home/travis/.cache/yarn/.tmp/749720ec53a1a00c21f4e78688f87cb4
Output:
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn" failed. Retrying, 3 of 3.
yarn install v0.18.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: archive 78d589f19519c87ba1549492f5c9d09da4609183
Directory: /home/travis/.cache/yarn/.tmp/749720ec53a1a00c21f4e78688f87cb4
Output:
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn" failed 3 times.
The command "yarn" failed and exited with 1 during .
Your build has been stopped.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/indeedeng/react-link-to-inbox/pull/3
https://travis-ci.org/indeedeng/react-link-to-inbox/builds/190781614

**What is the expected behavior?**
Build succeeds

**Please mention your node.js, yarn and operating system version.**
node 7.4.0
ubuntu 12.04.5
yarn 0.18.1

**Comment by doug-wade** [comment]
Note that this also repros on appveyor: https://ci.appveyor.com/project/doug-wade/react-link-to-inbox-ottk4/build/1.0.4

**Comment by mattcolman** [comment]
@doug-wade did you find a work around for this? I'm experiencing the same error :(

**Comment by doug-wade** [comment]
I did -- I use npm.  Yarn has a lot of potential, but right now I just don't think its ready for production.

**Comment by mattcolman** [comment]
😿  that may be the best option. Thanks!

**Comment by mattcolman** [comment]
actually I just ran `yarn upgrade` on prod and then redeployed and it worked. Still...I'm scared to deploy again, not convinced it will work :/

**Comment by Globegitter** [comment]
Just running into a similar issue on gitlab ci.

**Comment by Globegitter** [comment]
Somehow managed to get it to work. I copied around the `.git/config` in a docker container. Turns out I did not need to do that and that also seems like it was the thing that broke yarn.

**Comment by levithomason** [comment]
Also on CircleCI, however, updating to yarn `0.27.5` seems to have solved it.  CircleCI 2 ships with `0.24.6` at the time of writing.

A working `run` step looks like this:

```yaml
- run:
    name: update yarn
    command: |
      # remove default yarn
      sudo rm -rf $(dirname $(which yarn))/yarn*
      # download latest
      rm -rf ~/.yarn
      curl -o- -L https://yarnpkg.com/install.sh | sh
      echo 'export PATH="${PATH}:${HOME}/.yarn/bin"' >> $BASH_ENV
```

**Comment by BYK** [comment]
Closing since this seems to be resolved on latest master. Feel free to reopen if it is not.

**Comment by atherdon** [comment]
@BYK i still experience a similar issue(at travis ci builds):
```
The command "eval yarn " failed. Retrying ...
```

**Comment by lifeiscontent** [comment]
@BYK same here

**Comment by nebrelbug** [comment]
Me too

**Comment by cburkhardtBB** [comment]
Me three

**Comment by AlexandreBonneau** [comment]
I see that happening on node 6 (but not on node 8, 10 or 12) (see the [travis log here](https://travis-ci.org/autoNumeric/autoNumeric/builds/598026587)).

Could somebody please re-open that issue ?

**Comment by kopax** [comment]
I am in Gitlab-CI and I am running `[[ $(which yarn) = "" ]] && curl -o- -L https://yarnpkg.com/install.sh | bash`, and later I am running `cd server && [ ! -d node_modules ] && yarn || true` and it gives me `sh: 1: yarn: not found` 

I am trying now to reset my path with `export PATH=$HOME/.yarn/bin:$PATH`

It's strange that this is not done automatically.
