### ISSUE TITLE
Disallow caching local modules

### ISSUE THREAD

**Issue by kripod** [yarnpkg/yarn#2433]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Modules specified by a local path in `package.json` get cached.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run `yarn install` from the directory of [a qualifying `package.json` file](https://github.com/kripod/material-components-react/blob/f76fa4eea82c64c99786da95a3fa80a487b44d59/demo/package.json#L12)
2. Change the source file(s) of [the locally specified package](https://github.com/kripod/material-components-react/blob/f76fa4eea82c64c99786da95a3fa80a487b44d59/packages/button/src/index.jsx)
3. Run `yarn install` from the same directory as in step 1

**What is the expected behavior?**
Local modules shall not be cached, but installed straight from their given path.

**Please mention your node.js, yarn and operating system version.**
Node.js: v7.3.0
Yarn: v0.18.1
OS: Win10 x64

**Comment by eTorAken** [comment]
Seems to be a duplicate of #2165.

**Comment by kripod** [comment]
@eTorAken Sorry, I was searching but could not find that specific issue about the case. I'm closing this to move further conversation over #2165.
