### ISSUE TITLE
Install from Git-repo with a specific tag

### ISSUE THREAD

**Issue by stefannikolei** [yarnpkg/yarn#2436]
I try to switch from npm to yarn, but got a problem with my private gitlab repos.

In npm i had it like that:

"package": "git+http://gitlab.private.de/privategroup/privaterepo.git#tag1",

With yarn it wants me to point to a specific commit hash.

**Comment by jacobq** [comment]
Do you get something like `error Couldn't find package "private-package" on the "npm" registry.` in the output? (I'm curious if this is this is related to the problem I am having.)
