### ISSUE TITLE
yarn publish in a script requires user interaction

### ISSUE THREAD

**Issue by jnfingerle** [yarnpkg/yarn#2445]
`yarn publish` (0.18.1, node 6.3.1, Windows) is no drop in replacement for `npm publish` when used in a script: Using an auth token in my `.npmrc`, `npm publish` runs without user interaction, `yarn publish` asks for a new version number. It would be greate to have a way to publish without interaction.

To answer the questions not yet asked: It's our in house sinopia and publishing is restricted to our build bot. Therefore the new version number is always checked in before publishing.

**Comment by vvo** [comment]
I too would like to have a way to publish on npm using yarn, I already manage the version number bump in my scripts.

As a side note, `npm publish` inside a `yarn release` command that runs some shell script will fail on the auth part, only `npm publish` not run from a yarn subshell will work.

**Comment by destroyerofbuilds** [comment]
Carrying on the conversation from #722, `yarn publish` prompts for a version, which means it can't be used as a drop in replacement for `npm publish`.

`npm publish` behavior is to use the value of the `version` field in `package.json`.

**Comment by destroyerofbuilds** [comment]
Related to #2430

**Comment by rally25rs** [comment]
Closing as a dup of #610 since the longer conversation is held there.

**Comment by lehni** [comment]
@rally25rs I don't see any mention of this particular problem in #610, so was this perhaps closed in error? I am still facing this issue, in conjunction with https://github.com/lerna/lerna/issues/1200

**Comment by rally25rs** [comment]
@lehni the original post states

> yarn publish asks for a new version number. It would be greate to have a way to publish without interaction.

which is mentioned in comment https://github.com/yarnpkg/yarn/issues/610#issuecomment-298116487 which is why I closed it as a duplicate.

If you could add a comment to #610 for the password issue, it would be helpful. Thanks!
