### ISSUE TITLE
Change title to know that this is package manager for javascript

### ISSUE THREAD

**Issue by offlinehacker** [yarnpkg/yarn#2450]
Current title for yarn is misleading, as it does not provide information what yarn is packaging, i think it should be: "Fast, reliable, and secure dependency management **for javascript**". This is important for distro package maintainers, that copy paste titles, also `package.json` is missing description.

**Comment by Daniel15** [comment]
It's not actually specific to JavaScript, though. That's just one of the use cases.

**Comment by bestander** [comment]
As @Daniel15 said, Yarn as well as npm is not only for JavaScript.
