### ISSUE TITLE
Yarn installation takes more time on Windows 10

### ISSUE THREAD

**Issue by bboysathish** [yarnpkg/yarn#2458]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?**

Yarn takes more time on adding a single package.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/bboysathish/react-boilerplate/tree/react-redux-router-hot-css

This repo uses yarn, try installing a single package and it takes 886.92s. (This is completely more compared to npm)

![image](https://cloud.githubusercontent.com/assets/8023447/21977354/d78421e0-dbfb-11e6-97ce-f1184fcc2005.png)

**What is the expected behavior?**

It should be fast and should not take this much time for every package addition.

**Please mention your node.js, yarn and operating system version.**

Node.js - 6.9.4
Yarn.js - 0.18.1
OS - Windows 10 - 32 Bit
RAM - 4GB

**Comment by torifat** [comment]
Dupe #990

**Comment by bboysathish** [comment]
@torifat May I know the solution ???? If windows is not supported we should add a note / banner saying Windows is not supported due to Antivirus and optimization problems.

**Comment by torifat** [comment]
Goto https://yarnpkg.com/en/docs/install#windows-tab then scroll down to read the **Notice** section.

**Comment by bboysathish** [comment]
@torifat I see #990 is closed. But still the issue exists.

**Comment by bboysathish** [comment]
@torifat i have excluded the `node.exe` and `Yarn Cache` folder from the Windows Defender scanning, i don't have any other anti-virus running now.

![image](https://cloud.githubusercontent.com/assets/8023447/21984831/dae7c8b0-dc1d-11e6-9f4f-033077e7e841.png)

`Still it takes 544s. `
i think there is no definitive solution for this problem. 
Can you please reopen this issue, so that people facing same issue like me can post their thoughts ?

For you reference you have already closed one another issue today (https://github.com/yarnpkg/yarn/issues/2460).

**Comment by torifat** [comment]
https://github.com/yarnpkg/yarn/issues/2100#issuecomment-264161870

**Comment by torifat** [comment]
Ok, I will test it in my Windows 10 setup.

**Comment by bboysathish** [comment]
Thanks @torifat 

i have provided the sample repo above.

Steps would be

1. `Yarn install`
2. After installation happened, then try to install one another module to package E.g try `yarn add extract-text-webpack-plugin@1.0,1 -D -E`

**Comment by bboysathish** [comment]
Umbrella of issues regarding the Same windows performance Problem

- [ ]  https://github.com/yarnpkg/yarn/issues/2330
- [ ] https://github.com/yarnpkg/yarn/issues/2100
- [ ] https://github.com/yarnpkg/yarn/issues/1496
- [ ] https://github.com/yarnpkg/yarn/issues/1385
- [ ] https://github.com/yarnpkg/yarn/issues/1341
- [ ] https://github.com/yarnpkg/yarn/issues/990
- [ ] https://github.com/yarnpkg/yarn/issues/2460
- [ ] https://github.com/yarnpkg/yarn/issues/2270

**Comment by kumarharsh** [comment]
If someone needs to reproduce the bug, they can use this repo: https://github.com/kumarharsh/yarn-bug. Just run `yarn install`, and then `yarn add <any-repo>`.

**Comment by bboysathish** [comment]
@torifat Any update ? Have you able to reproduce the issue ?
