### ISSUE TITLE
yarn add or yarn remove take too long on Windows

### ISSUE THREAD

**Issue by kumarharsh** [yarnpkg/yarn#2460]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**
Running `yarn add` on my project (with about 120 dependencies) takes close to 20 minutes on Windows systems, but finishes rather quickly on Linux systems. On Windows, it seems to copy/install about 120k+ packages, as shown in the screenshot below. This happens on every yarn add/remove.

![image](https://cloud.githubusercontent.com/assets/760112/21977382/f16f36da-dbfb-11e6-8f71-a296d3117f11.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Please clone this repo: https://github.com/kumarharsh/yarn-bug, and run `yarn install`, and then `yarn add react-helmet`. On Windows, it takes ages to install/copy the package, and it happens everytime I run that command.

**What is the expected behavior?**

Yarn shouldn't take 20 minutes on every `yarn add`/`yarn remove`. `npm install` takes like 10 seconds.

**Please mention your node.js, yarn and operating system version.**
NodeJS: 6.9.2
Yarn: 0.18.1
OS: Windows 10 64-bit

**Comment by torifat** [comment]
Dupe #990

**Comment by kumarharsh** [comment]
@torifat thank you, I didn't see that issue earlier.

I'm still getting very bad performance on installation, and it's consistently bad. If the other issue (#990) was closed, and the performance problems remain, then what is the solution?

**Comment by bboysathish** [comment]
@kumarharsh Refer this issue (https://github.com/yarnpkg/yarn/issues/2458), that i have opened for the same. Post your thoughts there.

**Comment by kumarharsh** [comment]
@bboysathish okay, will do.
