### ISSUE TITLE
yarn upgrade gives different lock file randomly

### ISSUE THREAD

**Issue by blixt** [yarnpkg/yarn#2467]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If I run `yarn upgrade` repeatedly, I sometimes get the result that one dependency changed (correct behavior), sometimes I get a lot of dependencies removed (not expected).

**If the current behavior is a bug, please provide the steps to reproduce.**

I've put the two states in this gist: https://gist.github.com/blixt/364ab638488560c87c4348f3bc4b35ca

The files in the gist are `attempt1.diff`, `attempt1.lock`, `attempt2.diff` and `attempt2.lock`. I put the diffs in there for making it easier to see the difference. They're the diff from the state of my repo from last time dependencies changed. Only one dependency really changed (`object-assign`) but as you can see in `attempt1.diff` it removed a bunch of dependencies.

**What is the expected behavior?**

The same result every time I run `yarn upgrade` (assuming external dependencies weren't changed in the meantime).

**Please mention your node.js, yarn and operating system version.**

* Node.js 7.4.0
* Yarn 0.18.1
* macOS 10.12.2 (16C67)

**Comment by blixt** [comment]
I just retested this with 0.19.1 and in about 1/10 times I get the following diff after running `yarn upgrade` (the other times I get a clean diff because no dependencies really changed):

https://gist.github.com/blixt/ccfbc8ebea437e3d6109bc28ea8059cb

**Comment by paul-soporan** [comment]
Closing as fixed in the v2.

https://yarnpkg.com/getting-started/migration
