### ISSUE TITLE
"feed" module cannot be installed on OS X.

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#2470]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
* `yarn add feed` doesn't work

**If the current behavior is a bug, please provide the steps to reproduce.**
* Clone https://github.com/facebook/jest
* `cd website`
* `yarn`

**What is the expected behavior?**
* Works with npm

**Please mention your node.js, yarn and operating system version.**
*node 7, yarn 0.17.8, latest mac OS Sierra

**Comment by Daniel15** [comment]
Probably this: https://github.com/jpmonette/feed/pull/43

The currently released version has
```
  "os": [],
  "cpu": [],
```

npm treats that the same as if it wasn't specified, whereas Yarn treats it as if no OS or CPU architecture is compatible

**Comment by bestander** [comment]
feed@0.3.1 was released.
I submitted a PR to fix Yarn anyway #2490
