### ISSUE TITLE
Global installed package with wrong startup script

### ISSUE THREAD

**Issue by wenris** [yarnpkg/yarn#2474]
I installed my Node.JS in _D:\Node\v6.9.1_ , then I use Yarn install the global package successfully:

`yarn install webpack`

However, when I run it:

`λ webpack`
`The filename, directory name, or volume label syntax is incorrect.`

I discovered that Yarn install global package at _C:\Users\Wenris\AppData\Local\Yarn\config\global_ instead of _C:\Users\Wenris\AppData\Roaming\npm_ , where my NPM choose.

That's all right, but Yarn installed a wrong startup script _webpack.cmd_ in my Node.JS root dir:

`λ cat webpack.cmd`
`@"%~dp0\C:\Users\Wenris\AppData\Local\Yarn\config\global\node_modules\.bin\webpack.cmd"   %*`

So?

**Comment by wenris** [comment]
If I changed the script to:

`echo @"%~dp0\C:\Users\Wenris\AppData\Local\Yarn\config\global\node_modules\.bin\webpack.cmd"   %*`

Then i got:

`λ webpack`
`@"D:\Node\v6.9.1\\C:\Users\Wenris\AppData\Local\Yarn\config\global\node_modules\.bin\webpack.cmd"`

**Comment by anjia0532** [comment]
https://github.com/yarnpkg/yarn/issues/2630

**Comment by Daniel15** [comment]
This is a bug with `cmd-shim`: https://github.com/ForbesLindesay/cmd-shim/issues/21. It should be fixed in cmd-shim. Once a new version is available, we can update the dependency in Yarn.
