### ISSUE TITLE
Inconsistent yarn.lock file with the same repo on windows and macOS 

### ISSUE THREAD

**Issue by gertjvr** [yarnpkg/yarn#2476]
**Do you want to request a feature or report a bug?** 
Reporting a bug

**What is the current behavior?**
After following the yarn offline [guide](https://yarnpkg.com/blog/2016/11/24/offline-mirror) and setting up a repo to use yarn offline mirror generating the lock file on windows I can see all the packages resolving from local cache folder but after adding or regenerating the yarn.lock file on macOS not all the packages resolve from cache folder anymore.

**If the current behavior is a bug, please provide the steps to reproduce.**
`repo> rm -rf node_modules/ yarn.lock`
`repo> yarn install`

_examples of the yarn.lock on windows and macOS_
- [gist: windows](https://gist.github.com/gertjvr/b857fa8dc72330705745ff29d730ccf0#file-windows-yarn-lock)
- [gist: macOS](https://gist.github.com/gertjvr/b857fa8dc72330705745ff29d730ccf0#file-macos-yarn-lock) 

**What is the expected behavior?**
That the yarn.lock file should match between environments

**Please mention your node.js, yarn and operating system version.**
node v4.3.2
node v6.9.4
node v7.4.0

yarn v0.18.1
yarn v0.19.1

windows 10
macOS Sierra v10.12.2

**Comment by wvankuipers** [comment]
This is still an issue in yarn 0.23.4 (running on Node 7.10.0)

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
