### ISSUE TITLE
yarn.lock file changing due to non-deterministic generation while adding dependency

### ISSUE THREAD

**Issue by ertrzyiks** [yarnpkg/yarn#2477]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
The yarn.lock file has unrelated changes when adding a new dependency. Mostly they seem to be ordering differences. It has been reported once for cases when we just install new dependencies.
in #1168 

The discussion about it still being a problem when using `yarn add` starts here: https://github.com/yarnpkg/yarn/issues/1168#issuecomment-268429310

To be clear, I experience this issue even for package with no dependencies and no other packages depend on it like this: `https://github.com/ertrzyiks/test-package`.

The diff is full of things like:
```diff
-accepts@~1.3.3, accepts@1.3.3:
+accepts@1.3.3, accepts@~1.3.3:
```
or
```diff
+ansi-regex@2, ansi-regex@^2.0.0:
+  version "2.0.0"
+  resolved "https://registry.yarnpkg.com/ansi-regex/-/ansi-regex-2.0.0.tgz#c5061b6e0ef8a81775e50f5d66151bf6bf371107"
+
ansi-regex@^0.2.0, ansi-regex@^0.2.1:
  version "0.2.1"
  resolved "https://registry.yarnpkg.com/ansi-regex/-/ansi-regex-0.2.1.tgz#0d8e946967a3d8143f93e24e298525fc1b2235f9"
- 
-ansi-regex@^2.0.0, ansi-regex@2:
-  version "2.0.0"
-  resolved "https://registry.yarnpkg.com/ansi-regex/-/ansi-regex-2.0.0.tgz#c5061b6e0ef8a81775e50f5d66151bf6bf371107"
```

**If the current behavior is a bug, please provide the steps to reproduce.**

 - Check yarn.lock file into source repository.
 - Some time later add a new dependency
 - Diff of lock file is full of unrelated changes

**What is the expected behavior?**
Add a lock entry for new dependency

**Please mention your node.js, yarn and operating system version.**
yarn 0.17.10
yarn 0.18.1
yarn 0.19.1
node 6.9.1
OSX 10.11.5

**Comment by bestander** [comment]
That is odd, I was sure we fixed it in 0.17 https://github.com/yarnpkg/yarn/blob/master/src/lockfile/stringify.js#L77

**Comment by ertrzyiks** [comment]
@bestander so it would be possible if old lock is generated by v0.16? and then when adding a new package with v0.17 it is normal to have such diff?

**Comment by bestander** [comment]
Yeah, if the lockfile is old, then 0.17 version would rewrite it once and should not do change sanymore

**Comment by ertrzyiks** [comment]
Ok, all subsequent installs produce pretty diff 👍 so, I guess it's not a problem
