### ISSUE TITLE
Document --freeze-lockfile

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#2478]
It would be great to have a documentation of what `--freeze-lockfile` exactly do and how it differs from `--pure-lockfile` :)

Thanks!

**Comment by hbetts** [comment]
@victornoel documentation for `--frozen-lockfile` does exist in the `yarn` CLI tool - https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L66

If you meant that there is no documentation on the website, can you please re-file this issue against the `website` repository?

**Comment by victornoel** [comment]
@hbetts will do, thanks!
