### ISSUE TITLE
yarn doesn't recognize absolute path from npm's package.json

### ISSUE THREAD

**Issue by itsnotvalid** [yarnpkg/yarn#2482]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn install v0.19.1
[1/4] Resolving packages...
error "///e:\\my\\path\\to\\local\\package" doesn't exist.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
should install correctly.

**Please mention your node.js, yarn and operating system version.**
node.js: v6.9.3
yarn: 0.19.1
os: Microsoft Windows [Version 10.0.14393]

I work on a project which the local dependency was added by npm 4.0.5 (bundled  with node.js v6.9.3) and the line would have appeared as "package": "file:e:///e:\\my\\path\\to\\local\\package", however yarn is unable to load that.

**Comment by ArtemBernatskyy** [comment]
hm, seems no one there +1
