### ISSUE TITLE
[0.19.1] timeout during yarn install, not happening with 0.18.1!

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#2483]
I am experiencing a strange thing with yarn 0.19.1

Basically, on the same project (`https://gitlab.com/victornoel/petals-cockpit/`, in the frontend directory), calling `yarn --frozen-lockfile` with 0.19.1 or `yarn --pure-lockfile` with 0.18.1 yields different behaviours!

With yarn 0.19.1 I get the following error:
```
error An unexpected error occurred: "https://github.com/arthurc/karma-clear-screen-reporter/tarball/master: connect ETIMEDOUT 192.30.253.120:443".
```

With yarn 0.18.1, everything is ok.

I know it seems strange, but I tried many times and every time it gave me the same result!
This is happening on my CI system also.

**Comment by bestander** [comment]
There were some changes to git resolution.
Can you run 
`yarn install --verbose`?
Can you bisect which exactly dependency is to blame?
This is a recent commit that may be related https://github.com/yarnpkg/yarn/commit/e48275dd4d550dabe94e34d98faae76793d02649

**Comment by victornoel** [comment]
I can't reproduce it anymore, I may have been a bit eager when opening the issue, I guess it was gitlab's CI infrastructure that was having problems… sorry @bestander, I will reopen in case it becomes a problem again and I can reproduce it :)
