### ISSUE TITLE
The --no-color flag causes weird progress bar behaviour

### ISSUE THREAD

**Issue by IgorAufricht** [yarnpkg/yarn#2486]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When using `--no-color` flag, the progress bar behaviour is quite weird:
![yarn-no-color-output](https://cloud.githubusercontent.com/assets/13379857/22059978/4e84b024-dd6f-11e6-851d-b6236ded037b.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn --no-color`.

**What is the expected behavior?**
I would expect:
* if the `--no-color` flag is supported: no color is shown in the output and the progress bar behaves correctly (and the flag is mentioned in the docs/help)
* if the `--no-color` flag is not supported: it does not alter the output

**Please mention your node.js, yarn and operating system version.**
node.js v6.3.0
yarn v0.19.1
Windows 7 x64

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
