### ISSUE TITLE
Yarn global upgrade fails with "save-prefix" in .yarnrc

### ISSUE THREAD

**Issue by iovis9** [yarnpkg/yarn#2487]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `yarn global upgrade` with the `save-prefix` configuration set it doesn't recognise properly its own version number.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn config set save-prefix /usr/local
yarn global add csslint
yarn global upgrade
```
![screen shot 2017-01-18 at 12 50 34](https://cloud.githubusercontent.com/assets/6660202/22062981/bf8ae0b0-dd7c-11e6-83b8-5fff9260e53e.png)

**What is the expected behavior?**
It properly determines the version of the package.

**Please mention your node.js, yarn and operating system version.**
node v7.4.0, yarn v0.19.1, macOS 10.12.2

**Comment by soenkekluth** [comment]
@iovis9 you misunderstood what save-prefix is https://docs.npmjs.com/misc/config#save-prefix

**Comment by iovis9** [comment]
You're absolutely right.
