### ISSUE TITLE
Failing optional dependency halts installation

### ISSUE THREAD

**Issue by dkoontz** [yarnpkg/yarn#2489]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Installing a platform-specific optional dependency (grunt-appdmg) causes the installation process to fail on platforms that don't support it.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a repro case and steps here https://github.com/dkoontz/yarn-optional-dependency-repro

This sounds like https://github.com/yarnpkg/yarn/issues/1059 but that issue is marked closed.

**What is the expected behavior?**
The optional dependency of `grunt-appdmg` should be skipped on Linux and Windows.

**Please mention your node.js, yarn and operating system version.**
node.js 6.6.0
yarn 0.19.1
Ubuntu 16.04

**Comment by biiiipy** [comment]
Seeing a similar thing with fsevents on windows. I use ``--ignore-optional`` flag and yarn still complains:
``
##[error]warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
``
Functionaly everything works, but it writes an error to console and my CI marks that as partialy failed build, which is not great.

**Comment by bendemboski** [comment]
Isn't this a dup of #1435 ?

**Comment by bestander** [comment]
Please confirm if it is fixed in yarn@0.23+
https://github.com/yarnpkg/yarn/pull/2811
