### ISSUE TITLE
Warn when installing Yarn globally via Yarn itself

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2495]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
`yarn global add yarn` works

**What is the expected behavior?**
It should disallow it, or at least warn. By definition, installing Yarn via Yarn will result in you having two separate versions of Yarn installed at the same time. This can cause all sorts of weird issues (for example, see #2480, and also #2015 and #2371). It also has all the same drawbacks as installing Yarn via npm (documented on the Yarn site at https://yarnpkg.com/en/docs/install#alternatives-tab)

**Comment by ljharb** [comment]
What if a project actually has yarn as a dependency? Shouldn't this be permitted?

**Comment by ljharb** [comment]
If you're only talking about installing it as a global, then ignore my comment :-)

**Comment by Daniel15** [comment]
Good point @ljharb! I think that should be fine, it's just installing globally that's problematic

**Comment by samjacobclift** [comment]
Created a new PR based on the original PR from mnsn, made sure the linting looked good. It has latest master in it too so CI should all be good. We can close my PR if you like and we can wait for mnsn to finish his one, I don't mind 😄
