### ISSUE TITLE
Files inside directories aren't included when running pack

### ISSUE THREAD

**Issue by squiddy** [yarnpkg/yarn#2498]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Package built with `yarn pack` doesn't include files inside directories.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ yarn init
$ mkdir a
$ touch a/b
```

Edit `package.json` and add `files` setting:

```js
{
  "name": "tmp_package",
  "version": "1.0.0",
  "main": "index.js",
  "repository": {},
  "license": "MIT",
  "files": [
	  "a/"
  ]
}
```

```
$ yarn pack
$ tar --list -zf tmp_package-v1.0.0.tgz
package
package/a
package/package.json
```

**What is the expected behavior?**

The package includes file `a/b`.
```
$ tar --list -zf tmp_package-v1.0.0.tgz
package
package/a/b
package/package.json
```

When running `npm pack` the file is included.

Perhaps this is merely an documentation issue:

>  If you name a folder in the array, then it will also include the files inside that folder. (Unless they would be ignored by another rule.)

https://docs.npmjs.com/files/package.json#files

> You can specify single files, whole directories or [...]
https://yarnpkg.com/en/docs/package-json#toc-files

**Please mention your node.js, yarn and operating system version.**

```
node: 6.6.0
yarn: 0.19.1
os: Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

**Comment by squiddy** [comment]
On a related note, packages built with `yarn pack` that include directories in the `files` setting aren't installable.

Trying to install the package I build in the steps above results in this error:
```
$ yarn add file:/tmp/tmp_package/tmp_package-v1.0.0.tgz                                                                                                                                                                                [11:57]
yarn add v0.19.1
[1/4] Resolving packages...
error An unexpected error occurred: "invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/tmp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Same error as in #1253

**Comment by majgis** [comment]
We are seeing this issue too.  Replacing "foldername/" with "foldername/**/*" appears to be a workaround.

**Comment by jamiewinder** [comment]
I've just encountered this too, but the workaround @majgis posted doesn't seem to work either:
```json
  "files": [
    "dist/",
    "dist/*",
    "dist/**/*",
    (...)
  ]
```
Doesn't include anything from 'dist'. Tried every combination of these I can think of, and only the 'dist' directory is included, but never the contents.

**Comment by faassen** [comment]
I ran into this too. To @jamiewinder -- it worked for me but I didn't include "dist/" itself, just "dist/*" and "dist/**/*". And then a lot of struggling due to the old situation being in the yarn cache after installation.

**Comment by fvgs** [comment]
I encountered this same issue and found `"files": ["dirName/**"]` to be the cleanest workaround. Based on my tests, yarn will include all contents of the `dirName/` directory.
