### ISSUE TITLE
'yarn' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rhtpandeyIN** [yarnpkg/yarn#2504]
nodejs version: 7.4.0
OS: Windows 7

I installed yarn by using yarn.msi file, and it installed successfully. But when I tried to check yarn version on my system I got following error:
'yarn' is not recognized as an internal or external command,
operable program or batch file.

At first glance I thought it may issue of incorrect PATH or may be PATH is not set by msi. Then I checked my system PATH and I found correct PATH is already there. 

Solution: the problem was one extra "\\" was missing after bin.
before : C:\Program Files (x86)\Yarn\bin  (Not working) 
After :  C:\Program Files (x86)\Yarn\bin\  (Working) 

Please look into the issue. Thanks.

**Comment by woateng** [comment]
nodejs version: 6.5.0 and 7.4.0

Got the same problem,
now the default path was:   C:\Program Files (x86)\Yarn\.bin
Tried without dot and with/without slash, didn't work.

**Comment by yfain** [comment]
I don't use Windows, but if you install yarn locally, you should run its local version:
./node_modules/.bin/yarn

**Comment by rhtpandeyIN** [comment]
@yfain , I installed yarn through .msi (windows installer) file, and as per my understanding it should install globally by that, because it also got registered into the system path automatically. Hence it should recognize as a external command. Although when I changed path like above mentioned way, it got worked.

**Comment by locorocorolling** [comment]
Same issue as @rhtpandeyIN on windows 7 with node 6.9.1, fixed with same solution

**Comment by OutsourcedGuru** [comment]
Same issue as @rhtpandeyIN on Windows 7 Professional with node v6.9.5.  Opened new command shell hoping that path would have been added—it wasn't.  Manually added path to each invocation and it seems to work.  I would expect an MSI to update the global path for a Windows install.

**Comment by jameswilson281** [comment]
Same issue as @rhtpandeyIN on Windows 8.1 with node v7.7.1

**Comment by kazijosh** [comment]
Same issue as @rhtpandeyIN on Windows 7 Ultimate x64 with node v6.9.5. Solved with the same solution.

**Comment by trondstroemme** [comment]
Same issue as @rhtpandeyIN on Win 10 Pro 64-bit. resolved as per @lubojanski 's last comment.

**Comment by 1j01** [comment]
Is it possible the solution of adding a backslash is working (for some people) merely by triggering some sort of update? (That the installer isn't?) I see a lot of entries in PATH that leave off the backslash including git, nvm, nodejs, and Windows system paths. Does it still work if you change it back?

**Comment by ctcoulter** [comment]
posted this on the other read.. if anyone else is running into this issue, might help:

> I was bashing my head against this one for a while. Hopefully this helps someone out.

> The problem I had was that the installer placed the Yarn files in two locations that were both in my path. > The wrong one was being picked up when trying to execute.

> C:\Program Files\nodejs\yarn.cmd
> C:\Program Files (x86)\Yarn\bin\yarn.cmd

> I just moved the files out of my nodejs directory and it worked. The error message about the path not > being found is most likely due to the %~dp0 from the nodejs directory not being in the right location.

**Comment by Daniel15** [comment]
Hmmm... This is very strange... The trailing backslash shouldn't matter, and the current MSI has worked fine on various VMs I've tested it on, as well as on my Windows build server (which is running Windows Server 2012).

**Comment by rodrigoBerlochi** [comment]
I see also the same issue after installing Yarn  v0.24.6 
Node v6.9.0
'yarn' is not recognized as internal or external  command :(
I used the msi installer for Windows.

**Comment by Daniel15** [comment]
@rodrigoBerlochi Can you please check your path and ensure `c:\Program Files (x86)\Yarn\bin` was added to it?

**Comment by TrevorScrews** [comment]
I'm getting this error when trying to run yarn in powershell.  The path that was added is to my AppData folder.  I changed it to the `c:\Program Files (x86)\Yarn\bin` and still got this error.  When running from the command line, it works.  I didn't try from command line until the path was changed, so I'm not sure if it would have worked with the other path or not.

Node: 6.8.0
Yarn: 0.27.5

**Comment by rodrigoBerlochi** [comment]
Hi @Daniel15 Yes, it was. That was the weird point. We tried installing it using NPM. And then it worked. But I've read it isn't the recommended approach. 
Thanks for your answer

**Comment by chhonmeily** [comment]
For window 10 user please follow these article:
1. https://yarnpkg.com/en/docs/install#windows-tab
2. https://yarnpkg.com/en/docs/install#alternatives-tab
finally got it working. DAMN IT. Fuck me.

**Comment by arcanis** [comment]
When your PATH is modified, the currently opened `cmd` windows aren't affected, you need to close them and reopen them. Could that be your issue?

**Comment by tamj0rd2** [comment]
The MSI installer didn't update my path. I had to do it manually...

**Comment by tamj0rd2** [comment]
Yarn is in my PATH but I'm still not able to use it in cmd or powershell. I have restarted both of them several times

**Comment by BYK** [comment]
Anyone sees anything we can do on the Yarn side for this or can we close the issue?

**Comment by duycoder** [comment]
I have the same problem when i install yarn the 1st time, but then i restart my windows 7 computer.  It's worked. I use chocolately and run the cmd : "choco install yarn --version ...". Don't know about the other OS

**Comment by BYK** [comment]
@duycoder see @arcanis' answer right above: https://github.com/yarnpkg/yarn/issues/2504#issuecomment-320648293

**Comment by BYK** [comment]
Closing due to inability to act on this ticket.

**Comment by TrueFocus** [comment]
@Daniel15 had the right solution for me, changing PATH from "C:\Users\Johnny\AppData\Local\Yarn\bin" to "C:\Program Files (x86)\Yarn\bin" fixed it.

**Comment by porkopek** [comment]
Like @arcanis said, closing cmd window and opening again, and yarn seems to be installed properly

**Comment by vantisDev** [comment]
Just installed yarn. I had the Path correctly pointing to "C:\Program Files (x86)\Yarn\bin" and had closed and reopened my cmder, and still having the issue. 
Did two things, not sure which one worked:
1.Moved the Yarn folder out of Program Files(x86) (modifying path accordingly).
2.Opened directly yarn.cmd file.

**Comment by kalpeshbadgujar3** [comment]
Please try by **restarting** IDE after installing yarn using **.msi.**
This might solve your problem.
Success!

**Comment by hassannomani** [comment]
Closing cmd and reopening solved the issue. Thanks  @arcanis

**Comment by cuse** [comment]
You can try this and it solved the problem to me.

**_npm install yarn -g_**

Thanks

**Comment by mkasina** [comment]
This worked like a charm for me..

**npm install yarn -g**

Thanks @cuse

**Comment by SSP17SCM05A** [comment]
Thanks, @cuse.Yes, It worked for me as well with 👍 
npm install yarn -g

**Comment by ptumuluri8** [comment]
I installed yarn using chocolatey but not globally (didn't mention -g) yarn was installed but not found in cmd. After setting the path C:\Program Files (x86)\Yarn\bin\yarn.cmd it started working. 

Thanks for the group.

**Comment by snarun** [comment]
Thank you! Setting the path in environment variable as well as yarn global installation solves both the problems.

**Comment by PriyankaVrma** [comment]
<img width="592" alt="yarn test" src="https://user-images.githubusercontent.com/39528291/41280478-f59c2812-6e26-11e8-9a82-fe2d3aff072d.png">

Can you please help me with the solution for this one

**Comment by jd6503** [comment]
**For windows follow the below step** 

- Installed  yarn by using **yarn.msi** file.

- Check  correct the environment variable path.

	C:\Program Files (x86)\Yarn\bin\

- Run command **npm install yarn -g**

**Comment by WarungLive19** [comment]
it work!

C:\Users\you>npm install yarn -g
C:\Users\you\AppData\Roaming\npm\yarn -> C:\Users\you\AppData\Roaming\npm\node
_modules\yarn\bin\yarn.js
C:\Users\you\AppData\Roaming\npm\yarnpkg -> C:\Users\you\AppData\Roaming\npm\n
ode_modules\yarn\bin\yarn.js
+ yarn@1.9.4
added 1 package in 1.312s

C:\Users\you>yarn -v
1.9.4

**Comment by yakupad** [comment]
I try Windows PowerShell

Worked for me :)

**Comment by lgloredana** [comment]
I've got the same issue today after installing yarn via msi. 
For me the solution was to open a new console, yarn --version worked.
I've tried yarn --version an a console already opened before installing and it didn't worked.

**Comment by tcope25** [comment]
Restart PowerShell and it should work

**Comment by waleedshkt** [comment]
For all experiencing the issue of Windows Command Prompt not recognizing `yarn`, the reason behind this error being windows unable to detect `PATH` to the yarn's executable file.

To solve this, simply edit a `PATH` key under system **Environment Variables** and add a new path pointing to `yarn`. For me it's:

`C:\Users\YourUserAccountName\AppData\Roaming\npm\node_modules\yarn\bin`

If you go to the above path, you'll find a single file called `yarn`. This is what gets executed when you call yarn from your Windows Command Prompt.

And that's it! I hope it solves the aforementioned problem all of you are currently experiencing 😃

**Comment by CelticParser** [comment]
> Please try by **restarting** IDE after installing yarn using **.msi.**
> This might solve your problem.
> Success!

This worked for vsCode

**Comment by Daniel15** [comment]
>Install it in Program Files (x86) only. This solves the problem.
>But raises a question why only in this folder why not in "Program Files"-
>Is "yarn" only applicable for 32-bit operating systems? Don't know just saying.

@Chirag5528 - It's just how the installer is built. To install into `C:\Program Files`, we'd need to have two separate installers: One for 32-bit, and one for 64-bit. That's a bit of a hassle. Having one single installer is more convenient, but it means the installer runs in 32-bit mode. 

Yarn itself is written with Node.js and thus it is platform-insensitive.

**Comment by Daniel15** [comment]
I'm going to lock this since a lot of unrelated conversations are happening here. If you have any new issues, please create a **new** issue. Thanks!
