### ISSUE TITLE
Provide Mirror for Yarn MSI Package

### ISSUE THREAD

**Issue by OllieJennings** [yarnpkg/yarn#2512]
I work at an Investment Bank, so our internet is heavily locked down (but we can access things like github for development etc).

However AWS links through Amazon are completely blocked, so we cannot download and install the yarn.msi package, and using Chocolatey is not an option either.

Is it possible to provide a mirror so we can install this on our infrastructure?

**Comment by Daniel15** [comment]
You can grab a nightly build from the site at https://yarnpkg.com/en/docs/nightly - These are hosted on my server rather than GitHub, so they should work for you :)

**Comment by OllieJennings** [comment]
@Daniel15 Thanks a lot!

**Comment by RashadSaleh** [comment]
I have the same problem. Is there a way to install a stable build instead of nightly? I also see that the nightly builds are not signed.
