### ISSUE TITLE
Yarn fails to install public scoped packages when _auth is defined in .npmrc

### ISSUE THREAD

**Issue by AzGoalie** [yarnpkg/yarn#2515]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn fails to find scoped packages when `_auth` is defined in `.npmrc`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Sample repository located: https://github.com/AzGoalie/public-scope-yarn-install-failure
Create a project with a `package.json` and `.npmrc`
Add `"@turf/turf": "3.4.1"` to dependencies in package.json
Add `always-auth=false` and `_auth=fake-auth-token` to `.npmrc`
Run `yarn install`

**What is the expected behavior?**
Yarn should install the scoped package.

**Please mention your node.js, yarn and operating system version.**
```
Yarn version: 
  0.18.1

Node version: 
  7.4.0

Platform: 
  win32 x64
```

**Comment by enriquecaballero** [comment]
I have the exact same thing happening to me with the exact same package.

**Comment by enriquecaballero** [comment]
I was able to fix this by setting `always-auth` to `true`

**Comment by tautvilas** [comment]
I have same issue. If I have _auth token in .npmrc I can not successfully excecute `create-react-native-app`. yarn fails with 403 on expo dependencies/users.

**Comment by paul-soporan** [comment]
Closing as we stopped reading `.npmrc` files in v2.

https://yarnpkg.com/getting-started/migration
