### ISSUE TITLE
Yarn's recommended upgrade method doesn't work if you originally installed yarn with brew

### ISSUE THREAD

**Issue by callumlocke** [yarnpkg/yarn#2517]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I had Yarn 0.18.1, which I originally installed with brew, as the website [recommends](https://yarnpkg.com/en/docs/install).

I ran `yarn` just now, and it notified me that v0.19.1 is out, and I should update by running `curl -o- -L https://yarnpkg.com/install.sh | bash`

I did as instructed, but now I seem two have two yarns on my system. The original brew-installed yarn is still there (and `$ yarn` still points at the old version, because my PATH prioritises brew's bins).

**If the current behavior is a bug, please provide the steps to reproduce.**
Difficult to reproduce, because you would need to wait for yarn to release a new version. Hopefully the explanation above is clear enough.

**What is the expected behavior?**
It would be better if either:
- the yarn update notifcation could detect I'm running a brew-installed yarn, and recommend running `brew update && brew upgrade yarn` instead of curling the install script; OR
- the install script could be made smarter to behave differently if there already exists a brew-installed yarn on the system.

**Please mention your node.js, yarn and operating system version.**
- node – 7.4.0
- yarn – upgrading from 0.18.1 to 0.19.1
- OS – OS X 10.11.6 (El Capitan)

**Comment by Daniel15** [comment]
> the yarn update notifcation could detect I'm running a brew-installed yarn

This is a good idea. See [getUpdateCommand](https://github.com/yarnpkg/yarn/blob/24199a0091196144ba373e31afde199dc4e077ac/src/cli/commands/install.js#L76) for the code that determines the command to display.

Basically, Homebrew installations should have the `installationMethod` in Yarn's `package.json` set to something like "brew", and then getUpdateCommand should show the right Homebrew upgrade command.

**Comment by callumlocke** [comment]
@Daniel15 does you mean this is already the intended behaviour, and it's a bug that the `installationMethod` isn't set correctly for homebrew installations?

**Comment by Daniel15** [comment]
>  it's a bug that the installationMethod isn't set correctly for homebrew installations?

Yeah. You'll have to ask someone familiar with Homebrew to update the formula (or do it yourself, given it's all open source :) ). Here's the formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb

**Comment by OmgImAlexis** [comment]
@Daniel15 where is the `package.json` you're talking about?

**Comment by Daniel15** [comment]
@OmgImAlexis It's in the directory where Yarn is installed, alongside the `yarn.js` file. Searching your computer for `yarn.js` should find it.

**Comment by OmgImAlexis** [comment]
Does this sound right? `/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn`

```
➜  ~ cd /usr/local/Cellar/yarn/0.20.3
➜  0.20.3 ls -la
total 40
drwxr-xr-x  8 xo  admin    272 26 Feb 12:32 .
drwxr-xr-x  3 xo  admin    102 26 Feb 12:32 ..
drwxr-xr-x  3 xo  admin    102 15 Feb 07:10 .brew
-rw-r--r--  1 xo  admin  11268 26 Feb 12:32 INSTALL_RECEIPT.json
-rw-r--r--  1 xo  admin   1346 15 Feb 07:10 LICENSE
-rw-r--r--  1 xo  admin   2963 15 Feb 07:10 README.md
drwxr-xr-x  4 xo  admin    136 15 Feb 07:10 bin
drwxr-xr-x  5 xo  admin    170 15 Feb 07:10 libexec
➜  0.20.3 tree bin 
bin
├── yarn -> ../libexec/bin/yarn
└── yarnpkg -> ../libexec/bin/yarnpkg

0 directories, 2 files
➜  0.20.3 ls -la libexec/bin/yarn
lrwxr-xr-x  1 xo  admin  36 15 Feb 07:10 libexec/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js
```

**Comment by Daniel15** [comment]
Yeah I think that should be right - Is there a `package.json` in `/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn`?

**Comment by OmgImAlexis** [comment]
Yes there is. That dir is the yarn npm module so I'm assuming it has to be edited?

Would it not be better for yarn's updater to just check if `which yarn` returns a reference to symlinked file from `/usr/bin/Cellar/....`?

**Comment by Daniel15** [comment]
Making assumptions based on file path isn't always ideal. Two edge cases I can think of:

 - What if someone puts Yarn in a `/usr/local/Cellar` directory but isn't actually using Homebrew?
 - What if someone has multiple versions of Yarn installed? This is a bit silly, but might happen.

We had an issue on Windows where there's **two** methods of installing Yarn: The Windows installer, and Chocolatey. Both end up installing Yarn to `c:\Program Files\Yarn`, so simply checking the file path wasn't enough. That's why `installationMethod` was introduced to Yarn's `package.json`, so it can unambiguously tell which installation method was used.

**Comment by OmgImAlexis** [comment]
@Daniel15 the reason I asked is it's usually bad practise to edit a file within `node_modules` after it's been installed via npm, etc.

I'll see if I can get a patch submitted to Homebrew.

**Comment by Daniel15** [comment]
For the other installation methods of Yarn (Windows installer, Debian package, etc), we edit the `package.json` while building the package. Search the repo for `set-installation-method.js`: https://github.com/yarnpkg/yarn/search?utf8=%E2%9C%93&q=set-installation-method.js

**Comment by ibroadfo** [comment]
This should now be working; we just need to wait for a new release to check! :)

**Comment by SimenB** [comment]
@ibroadfo that brew change broke install for yarn from brew for me. See https://github.com/yarnpkg/yarn/issues/2915#issuecomment-290384809

**Comment by AlexLandau** [comment]
For more context on what @SimenB is seeing, it looks like brew generates new bottles via npm install (per https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb), and for a while npm-based installations were broken due to a bad published version of an upstream dependency: https://github.com/yarnpkg/yarn/issues/2915

(Though I may be misinterpreting what the bottles contain.)

**Comment by SimenB** [comment]
I never noticed that it uses npm install. That's wrong, it should just extract...

**Comment by SimenB** [comment]
Opened a WIP PR over at brew for this: Homebrew/homebrew-core#11881

**Comment by Gudahtt** [comment]
It looks like that PR was merged. Has this issue been resolved?

**Comment by SimenB** [comment]
Yes

**Comment by Daniel15** [comment]
Yeah this is good now. The Homebrew formula sets the installation method to "homebrew":
https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb#L17

Then Yarn picks that up:
https://github.com/yarnpkg/yarn/blob/a7334da31bf783af7a3efab451589fe7ac34c748/src/cli/commands/install.js#L92-L94
