### ISSUE TITLE
Remove NodeJs dependancy for: choco install yarn

### ISSUE THREAD

**Issue by airtonix** [yarnpkg/yarn#2524]
Please don't assume we don't have NodeJs installed.

If yarn won't install without NodeJs present, then throw error message. If a developer doesn't want to use nvmw or nodist, then they explicitly install nodejs along with yarn: `sudo choco install nodejs yarn -Y`

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
choco manifest assumes I don't have node installed or that I'm not using Nodist, a node version manager for windows.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Have nodist installed
2. have choco installed
3. optionally install `scoop`, then `scoop install sudo`
4. `sudo choco install yarn`

**What is the expected behavior?**
Not have yarn install a version of node over the top of nodist...

**Please mention your node.js, yarn and operating system version.**
nodejs: whatever version i want...
os: windows 10.

**Comment by Daniel15** [comment]
The purpose of a package management system like Chocolatey is to manage your dependencies 😛  Yarn would be broken out-of-the-box for lots of users if it didn't specify a dependency on Node.js. You can install Yarn like `choco install yarn --ignore-dependencies` to ignore the Node.js dependency, or just use the Windows installer directly.

**Comment by Daniel15** [comment]
Closing this out as you can use `--ignore-dependencies` if you don't want to install Node via Chocolatey.

**Comment by marsonmao** [comment]
Confirming this is a must do. 

I've tried `choco install nodejs-lts`, got node version 8.9.3, then `choco install yarn`, then choco automatically installs `nodejs.install` for me so i got version 9.3.0...

**Comment by Daniel15** [comment]
Is there a way to make Yarn handle either the LTS Node.js, or the regular
one? I don't want to totally remove the dependency as it'll break the Yarn
out-of-the-box experience for people that don't have Node.js installed.

**Comment by jpierson** [comment]
The ironic thing is that this is the transitive dependency type of problem that tools like Yarn aim to solve in the first place. I also ran into this problem and made a [post in my blog](https://jefuri.wordpress.com/2018/04/25/playing-it-safe-with-the-safe-stack-part-1/) about the pitfall when trying out the SAFE stack which uses Yarn by default.

**Comment by pklapperich** [comment]
The [nodejs package](https://chocolatey.org/packages/nodejs) has a comment that it's a meta package, but that users who want LTS should still install nodejs-lts. Generally I would expect a package like nodejs-lts to declare that it provides nodejs and the package manager would consider dependencies resolved if it's installed.

@ferventcoder maintains the chocolately package for nodejs. Maybe he can give some guidance?
