### ISSUE TITLE
yarm install freezes on is-arrayish@^0.2.1 module

### ISSUE THREAD

**Issue by studio-webb** [yarnpkg/yarn#2528]
<img width="842" alt="screen shot 2017-01-23 at 10 39 51 am" src="https://cloud.githubusercontent.com/assets/2277691/22196945/5d178c78-e158-11e6-94e9-593cc8c26f71.png">

https://gyazo.com/402446e01b7bb0f2b4a0d8e333bdcf9a

**Comment by torifat** [comment]
Please use the issue template.

**Comment by joe-at-startupmedia** [comment]
Have the same issue.

**Comment by brazorf** [comment]
Same here

**Comment by BYK** [comment]
I'd like to quote @torifat here:

>Please use the issue template.

If you'd like to get your issue verified and resolved quickly, please follow our issue template and provide as many details as possible along with an isolated reproduction script.

**Comment by joe-at-startupmedia** [comment]
I found out the issue on my end, it's the convention in which the repository is loaded, so you have to provide a public key to authenticate to git.

`yarn info is-arrayish@0.2.1` 

You'll see 

`git+https://github.com/qix-/node-is-arrayish.git`

Related to issue #513

**Comment by BYK** [comment]
@joe-at-startupmedia it should fail instead of freezing if you are using a recent version of yarn. Can someone please use the issue template which tells you to mention the Node and yarn versions along with some other things so we can diagnose this? :)

**Comment by joe-at-startupmedia** [comment]
@BYK 

Sorry don't know where the issue template is but here is my versioning:

```bash
[git@startup-dev-web cobrandedsites]$ yarn --verison
yarn install v0.27.5
[git@startup-dev-web cobrandedsites]$ node --version
v7.6.0
```

**Comment by BYK** [comment]
@joe-at-startupmedia you can file a new issue and you'll see the template there.
