### ISSUE TITLE
v0.20.0  release 

### ISSUE THREAD

**Issue by kolesnik** [yarnpkg/yarn#2529]
Hi Guys, looks like critical issue with proxy https://github.com/yarnpkg/yarn/commit/cf07f8e9ff7dd581d378d2a31efad5af8d1c4fb5 has been fixed in v0.20.0, could you please release it? or maybe run as "pre-release" ?

**Comment by torifat** [comment]
@bestander can you have a look here?

**Comment by bestander** [comment]
I'll cherry-pick it into 0.19 branch and it will be released in 0.19.2

**Comment by kolesnik** [comment]
You Rock! Thank you

**Comment by bestander** [comment]
Wait a second, it has been released since 0.17 already
<img width="855" alt="screen shot 2017-01-23 at 3 07 23 pm" src="https://cloud.githubusercontent.com/assets/2121048/22209251/b86b5832-e17d-11e6-9c38-cb654ee58bcd.png">

**Comment by torifat** [comment]
Yep, I should have checked it 😞
