### ISSUE TITLE
Support `-S`/`--save` flags for `yarn add`

### ISSUE THREAD

**Issue by avaly** [yarnpkg/yarn#2532]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn add -S` throws an error and does not install a package. This should be supported to ease the transition for `npm` users.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn add -S babel` or `yarn add --save babel`

**Actual output**
```
yarn add v0.19.1
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**
It should install the package and add it to `dependencies` in `package.json`.

**Please mention your node.js, yarn and operating system version.**
node v6.9.4
yarn v0.19.1
Ubuntu 16.04

**Comment by torifat** [comment]
https://yarnpkg.com/en/docs/migrating-from-npm#toc-cli-commands-comparison

**Comment by avaly** [comment]
I still think this flag could be useful to support without such a hard fail.
