### ISSUE TITLE
[npm compat] bundledDependencies in package.json is not considered optional as by npm

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2546]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

```
yarn add tap@0.3.1
yarn add v0.18.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error Couldn't find a package.json file in "/Users/bestander/work/temp/tap/node_modules/tap/node_modules/tap-consumer"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

Npm@3 installs tap-consumer from npm even though it is not in `dependencies` and is missing from the package as described in `bundledDependencies`

Users/bestander/work/temp/tap
└─┬ tap@0.3.1
  ├── buffer-equal@0.0.2
  ├── deep-equal@0.0.0
  ├─┬ difflet@0.2.6
  │ ├── charm@0.1.2
  │ ├── deep-is@0.1.3
  │ └── traverse@0.6.6
  ├── inherits@1.0.0
  ├── mkdirp@0.3.5
  ├─┬ nopt@2.2.1
  │ └── abbrev@1.0.9
  ├─┬ runforcover@0.0.2
  │ └─┬ bunker@0.1.2
  │   └─┬ burrito@0.2.12
  │     ├── traverse@0.5.2
  │     └── uglify-js@1.1.1
  ├── slide@1.1.6
  ├─┬ tap-consumer@0.0.1
  │ ├── inherits@2.0.3
  │ ├─┬ tap-results@0.0.2
  │ │ └── inherits@1.0.2
  │ └── yamlish@0.0.7
  └── yamlish@0.0.5

This is clearly an error in package but we might consider backporting the bug

**Please mention your node.js, yarn and operating system version.**
Node 6
Yarn 0.18+
Mac OS / Linux

**Comment by TrustNik** [comment]
Linked https://github.com/yarnpkg/yarn/issues/886
