### ISSUE TITLE
Improper origin ". stable" used in Release file for debian packages

### ISSUE THREAD

**Issue by hackel** [yarnpkg/yarn#2548]
**Which operating system are you using:** Ubuntu 14.04

**Please describe the steps you took when trying to install Yarn and what went wrong:** Yarn uses "Origin: . stable" in its [release file](https://dl.yarnpkg.com/debian/dists/stable/Release).  This name is meaningless and should be replaced with "yarn".  This is needed to allow automatic upgrading of the yarn package, apt-pinning, etc.

**Comment by Daniel15** [comment]
Sorry about that - It did used to be "yarn", but it looks like it changed when we switched from Reprepro to Aptly: https://github.com/yarnpkg/releases/commit/9e2b1a6eddfe60ed3088b77813e7ab6e011100fc#diff-81d405a895de4f9a07320d1131b24975.

**Comment by Daniel15** [comment]
Should be better now, I updated it to have an origin of `yarn` and a label of `yarn-stable`.
