### ISSUE TITLE
Yarn ignores gulpfile?

### ISSUE THREAD

**Issue by buunguyen** [yarnpkg/yarn#2549]
I try to install `sequalize-cli` with Yarn but ran into a problem: Yarn doesn't add sequelize-cli/lib/gulpfile.js, which is required to run sequalize tasks. Installing with NPM works correctly. It seems like Yarn ignores gulpfile.js. 

Steps to reproduce

1. yarn add sequelize-cli
2. In node_modules/sequelize-cli/lib: there's no gulpfile.js

Repeat with NPM, gulpfile.js is included as expected.

**Comment by bestander** [comment]
Can't reproduce with latest Yarn.
Try `yarn cache clean`, cache might have been broken

**Comment by buunguyen** [comment]
Just tried:
```
yarn cache clean
yarn remove sequelize-cli
yarn add sequelize-cli --dev
```

Still doesn't work: `node_modules/sequelize-cli/lib` still doesn't have `gulpfile.js`

Yarn version: v0.19.1 (latest from Homebrew).

I tried in 2 separate machines. Same result.

**Comment by bestander** [comment]
Works for me:
```
yarn add sequelize-cli --dev
yarn add v0.19.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
ls -al node_modules/sequelize-cli/lib/
total 8
drwxr-xr-x   6 bestander \Domain Users  204 Jan 26 16:07 .
drwxr-xr-x  17 bestander \Domain Users  578 Jan 26 16:07 ..
drwxr-xr-x   5 bestander \Domain Users  170 Jan 26 16:07 assets
-rw-r--r--   1 bestander \Domain Users  698 Nov 21 10:16 gulpfile.js
drwxr-xr-x  16 bestander \Domain Users  544 Jan 26 16:07 helpers
drwxr-xr-x   8 bestander \Domain Users  272 Jan 26 16:07 tasks
```

Try `yarn add sequelize-cli --dev --verbose` and see what files are copied there

**Comment by buunguyen** [comment]
My bad, there's a `.yarnclean` file that removes Gulpfile.js. Thanks a lot for your help!
