### ISSUE TITLE
Wrong bin path on Windows 10

### ISSUE THREAD

**Issue by bogdancar** [yarnpkg/yarn#2565]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On path variable, the path to global bin executables installed by yarn is set to `C:\Users\username\AppData\Local\Yarn\.bin` when it should be `C:\Users\username\AppData\Local\Yarn\config\global\node_modules\.bin`

> 

**If the current behavior is a bug, please provide the steps to reproduce.**
Install yarn, try installing a package globally with `yarn global install bower`, then check the path variable that is set to wrong path.

**What is the expected behavior?**
The correct path where yarn bins are installed is `C:\Users\devBogdan\AppData\Local\Yarn\config\global\node_modules\.bin`
**Please mention your node.js, yarn and operating system version.**
Node 6.9.4, Yarn 0.19.1, Windows 10

**Comment by Daniel15** [comment]
I wonder if Yarn is putting global modules in the wrong directory... It seems strange to put them in the "config" directory 😕

**Comment by bogdancar** [comment]
Seems like it does, for example npm uses `C:\Users\username\AppData\Roaming\npm` on windows.

**Comment by tobymurray** [comment]
Using:
Yarn: 0.21.0-20170202.0141
Node: 7.4.0
NPM: 4.0.2
Windows 10

I run into the same thing. It definitely looks like something is out of sync between the path variables and the directory where global packages are installed.

**Comment by rixrix** [comment]
hello devs,

Just a quick heads up, I've encountered the same issue. 

Here's my dev environment:

- Yarn: 0.21.3
- npm: 3.10.10
- Node: v6.10.0
- Windows: Windows Insider Build Preview: 15025.rs_prerelease

Environment Variables:

- C:\Users\username\AppData\Local\Yarn\.bin
- C:\Users\username\AppData\Roaming\npm

Command: 
- `$> yarn global add create-react-native-app`
- `$> create-react-native-app my-epic-project`

Package Installed in:
- `C:\Users\username\AppData\Local\Yarn\config\global\node_modules`

Expected Behaviour:
- sample react-native project should created

Current Output:
- command not found

What seems to work for me was adding the path `C:\Users\username\AppData\Local\Yarn\config\global\node_modules\.bin` in environment variables. FYI

**Comment by SaschaNaz** [comment]
Just opened #3216 to fix this but by some reason some tests fail :/

**Comment by jas99** [comment]
+1

**Comment by Daniel15** [comment]
@jas99 - How did you install Yarn, and what version are you on?

**Comment by jas99** [comment]
Installed yarn via npm
```
npm version
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.3',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.101',
  zlib: '1.2.11' }
```
```
yarn versions v0.23.4
{ yarn: '0.23.4',
  http_parser: '2.7.0',
  node: '6.10.3',
  v8: '5.1.281.101',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
```

**Comment by Daniel15** [comment]
Try using the Windows installer from https://yarnpkg.com/latest.msi.
There's some limitations with what we can do when Yarn is installed via
npm.

**Comment by jas99** [comment]
Hey @Daniel15 
latest version i.e 1.0.1 from https://yarnpkg.com/latest.msi works great
😄 😄 
Thx

**Comment by ununseptium** [comment]
Well i just installed it via msi package `yarn-1.3.2.msi`. 
Path Entry:
`%APPDATA%\Local\Yarn\bin`

Actual binary location:
`%APPDATA%\Local\Yarn\config\global\node_modules\.bin`

This still seems to be weird from time to time i guess? I mean i simply changed the path to the correct one but i think you may would appreciate this info anyway.

**Comment by jkobylec** [comment]
I had the same experience as @ununseptium using `chocolatey` which in turn appears to use `yarn-1.3.2.msi`. Let us know if we should file a new issue.
