### ISSUE TITLE
Dev dependencies included in `yarn licenses command --production`

### ISSUE THREAD

**Issue by jwbay** [yarnpkg/yarn#2567]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Dependencies of development dependencies are included in `yarn licenses ls --production` and `yarn licenses generate-disclaimer --production`.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/jwbay/yarnbug
Or just:
`> yarn add jest -D`
`> yarn licenses ls --production | grep jest-`

**What is the expected behavior?**
Only production dependencies and their dependency trees are included in `yarn licenses` commands when using the --production flag.

**Please mention your node.js, yarn and operating system version.**
node 6.9.2
yarn 0.19.1
windows 10.0.14393

This seems to have surfaced in yarn 0.18.0. Version 0.17.10 did not have this bug.

**Comment by stevewadsworth** [comment]
Still present in yarn version 0.21.3

**Comment by Sly777** [comment]
Hey @stefanpenner @jwbay , I tested this feature on yarn but It still just exports all dependencies, not prod only.

yarn: 1.19.2
node: 12.12.0
macOSX

**Comment by geevb** [comment]
I'm still facing this same issue while using yarn workspaces.

Running `yarn licenses list --production` still displays modules inside devDependencies.

**Comment by milgner** [comment]
I can confirm that this is still present in yarn 1.22.17
