### ISSUE TITLE
Consider replacing `repeating` with `string.prototype.repeat`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [yarnpkg/yarn#2569]
**Do you want to request a *feature* or report a *bug*?**
I don't think it counts as either.  Reworking internals?

**What is the current behavior?**
The `repeating` package is used to repeat strings.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`string.prototype.repeat` is used to repeat strings.
**Please mention your node.js, yarn and operating system version.**

**Comment by Daniel15** [comment]
Which Node.js versions is `String.prototype.repeat` available in? It might need to be polyfilled in older versions.

**Comment by wtgtybhertgeghgtwtg** [comment]
[According to node.green](http://node.green/#String-prototype-methods), `node>=4.0.0`.

**Comment by bestander** [comment]
Sure, send a PR.
Thanks for working on keeping Yarn lean, @wtgtybhertgeghgtwtg

**Comment by wtgtybhertgeghgtwtg** [comment]
PR #2583.

> Thanks for working on keeping Yarn lean

If it wasn't lean, I think you'd have to call it `rope`.

**Comment by Daniel15** [comment]
Fixed in #2583

**Comment by Daniel15** [comment]
Fixed in #2583, thanks @wtgtybhertgeghgtwtg!

(by the way, how does one pronounce your username? 😛 )

**Comment by wtgtybhertgeghgtwtg** [comment]
Your guess is as good as mine.
