### ISSUE TITLE
Issue Updating / Installing Yarn via Homebrew

### ISSUE THREAD

**Issue by sprjr** [yarnpkg/yarn#2578]
*Before creating an issue please make sure you are using the latest version of yarn.*
✅ I had previously done an `npm i -g yarn` when yarn was released, and knew that before I used it I wanted to update it. I went to the yarn website to see how installation was recommended instead of just updating via npm.

**Do you want to request a *feature* or report a *bug*?**
I believe this is a bug.

**What is the current behavior?**
It appears that `brew install yarn` can cause removal of existing npm installs on a machine.

**If the current behavior is a bug, please provide the steps to reproduce.**
Given `node@6.8.x`, `npm@3.10.8`, `yarn@(i-forget)` were already on my machine, I ran `brew update` and `brew install yarn`, which at the end of install said that it _did_ install but that the _symlink_ failed and that I should `rm` it. Instead of doing the `rm`, I actually tried to do `npm uninstall -g yarn` which failed with a 'command npm not found in PATH' error.

Sure enough, `/usr/local/bin` no longer contained npm.

**What is the expected behavior?**
Ideally this would have just installed yarn leaving me to remove/replace the other npm installed version and symlink.

**Please mention your node.js, yarn and operating system version.**
Node mentioned above, yarn is now at latest, OS is...`Mac OSX 10.11.6`.

This may have just been caused by the steps I took, but I was surprised to have to go download the latest node.js package and reinstall it to get npm back on the machine.

Thanks!

**Comment by arrygoo** [comment]
Same thing happened to me. Ran `brew install yarn` and it removed `npm` :(.

**Comment by Daniel15** [comment]
This sounds like a bug/issue with either Homebrew or the Yarn formula. Please file a task to the Homebrew developers. The Yarn formula is community-maintained and located in their repo: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb
