### ISSUE TITLE
Default repository url is unreadable in `yarn init`

### ISSUE THREAD

**Issue by R3D4C73D** [yarnpkg/yarn#2585]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?**
While running `yarn init`, the default value for repository url isn't readable.  It's printed as `[object Object]`.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ yarn init
yarn init v0.19.1
question name (code): test
question version (1.0.0): 0.1.0
question description: 
question entry point (index.js): 
question repository url ([object Object]): https://test@bitbucket.org/test/test.git
question author: R3D4C73D
question license (MIT): UNLICENSED
success Saved package.json
Done in 53.98s.
```

**What is the expected behavior?**
I expected to see something readable.  `[object Object]` is rather opaque.

**Please mention your node.js, yarn and operating system version.**
Node: v6.9.4
Yarn: 0.19.1
OS: Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bestander** [comment]
This is fixed in 0.20
