### ISSUE TITLE
yarn add fails installing iconv

### ISSUE THREAD

**Issue by dcanning** [yarnpkg/yarn#2586]
**actual behavior**
yarn fails installing iconv package

additionally, adding any packages after iconv is installed also fail.

**steps to reproduce**
yarn add iconv

**expected behavior**
yarn does not fail to compile iconv

**Please mention your node.js, yarn and operating system version.**
running yarn 0.19.1 on Windows 10 anniversary update

[yarn-add.zip](https://github.com/yarnpkg/yarn/files/738142/yarn-add.zip)

**Comment by bestander** [comment]
Works fine on Mac
```
yarn add v0.21.0-0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ iconv@2.2.1
└─ nan@2.5.1
✨  Done in 8.59s.
```

**Comment by bestander** [comment]
```
File "C:\Program Files (x86)\Yarn\updates\0.19.1\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1228, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1

```

This was fixed in https://github.com/yarnpkg/yarn/commit/c3191986dd0c75214441b6c9160019014b1fa34d, please try version 0.20.0
