### ISSUE TITLE
Yarn version regression in 0.19.1

### ISSUE THREAD

**Issue by lcalvy** [yarnpkg/yarn#2589]
# Bug report

**What is the current behavior?**
Yarn version doesn't tag and bump package.json

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ NEW_VERSION=4.104.2
$ yarn version --new-version $NEW_VERSION
yarn version v0.19.1
```

**What is the expected behavior?**
Expected behavior is to increment package.json and create a git tag
```
$ NEW_VERSION=4.104.2
$ yarn version --new-version $NEW_VERSION
yarn version v0.18.1
warning package.json: No license field
info Current version: 4.104.1
info New version: 4.104.2
✨  Done in 0.23s.
```

** Current software version
`NodeJs 6.5.0, Git version 2.11.0, Yarn version 0.19.1, mac os sierra and linux ubuntu`

**Comment by bestander** [comment]
There is an open bug for that

**Comment by spmiller** [comment]
The open bug is https://github.com/yarnpkg/yarn/issues/2491
