### ISSUE TITLE
Consider replacing `user-home` with `os.homedir`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [yarnpkg/yarn#2596]
**Do you want to request a *feature* or report a *bug*?**
I don't think it counts as either. Reworking internals?

**What is the current behavior?**
The `user-home` package is used to get the user home directory.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`os.homedir` is used to get the user home directory.
**Please mention your node.js, yarn and operating system version.**

**Comment by sholladay** [comment]
I'm not sure what versions of Node are supported by Yarn (please put it in `engines` in package.json). But `os.homedir()` was added in Node 4. `user-home` is a cached version of the `os-homedir` package, which is a ponyfill that helps support older versions of Node still in use like 0.10 and 0.12. It does have a fast path for [using the native function](https://github.com/sindresorhus/os-homedir/blob/master/index.js#L24) when available. So the overhead is pretty negligible.

**Comment by wtgtybhertgeghgtwtg** [comment]
`yarn` supports `node>=4`.  The overhead is negligible, but I want to take out dependencies if I can.

**Comment by ljharb** [comment]
Why? Dependencies are a good thing.

(In this case it makes sense to remove, though)

**Comment by wtgtybhertgeghgtwtg** [comment]
Because complex dependency graphs keep me up at night.

**Comment by sholladay** [comment]
> "ponyfill" is a silly word for a polyfill that doesn't self-install

True. But more importantly, it does not _monkeypatch_. I agree it's a bit silly. But hey, it's a meaningful distinction that gets us to laugh.

**Comment by sotayamashita** [comment]
If it can be simple, I think it should be.
