### ISSUE TITLE
Duplicate command names 'yarn' with other packages

### ISSUE THREAD

**Issue by hatai** [yarnpkg/yarn#2597]
https://www.npmjs.com/package/yarnjs

If a package  yarnjs is installed,
the yarn command of yarnpkg can not be executed.

**Comment by sotayamashita** [comment]
Could you elaborate what you did ?

**Comment by ljharb** [comment]
It looks like they renamed from "yarnjs" to "reptar" https://github.com/reptar/reptar/commit/237101880e98994a2322d810b1b3bb9b56ccb131#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Try installing that instead.

**Comment by sotayamashita** [comment]
@ljharb I understood what is problem. thanks
