### ISSUE TITLE
`yarn run` should provide NODE, like `npm run`

### ISSUE THREAD

**Issue by wmertens** [yarnpkg/yarn#2609]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The environment variable `NODE` is not set when running `yarn run anyscript`.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Define script `env: "echo $NODE"`
2. Run `npm run env`
3. Run `yarn run env`

**What is the expected behavior?**
2 and 3 return same value, the path to the node executable

**Please mention your node.js, yarn and operating system version.**
Node 7, Yarn 0.19.1, OS X 10.12.2

**Comment by Daniel15** [comment]
Is this documented in the npm documentation somewhere?

**Comment by wmertens** [comment]
Yes, see https://github.com/npm/npm/blob/latest/doc/cli/npm-run-script.md

> npm run sets the NODE environment variable to the node executable with
which npm is executed

>
>

**Comment by wmertens** [comment]
See also
https://github.com/npm/npm/blob/d081cc6c8d73f2aa698aab36605377c95e916224/lib/utils/lifecycle.js#L75

**Comment by Meligy** [comment]
Worth noting that there's more in the paragraph that documents the behaviour in the run-scripts page:

> npm run sets the NODE environment variable to the node executable with which npm is executed. Also, if the --scripts-prepend-node-path is passed, the directory within which node resides is added to the PATH. If --scripts-prepend-node-path=auto is passed (which has been the default in npm v3), this is only performed when that node executable is not found in the PATH.

It even gives a warning if you call `npm run` with a custom Node binary (say, portable Node on Windows) and you have a global Node installation, and don't provide `--scripts-prepend-node-path`.

On a Windows 8.1 machine with Node 6.9.4 and npm 4.1.1, the warning says:

> npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using D:\path\to\custom\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

**Comment by wmertens** [comment]
Awesome, thank you!
