### ISSUE TITLE
Implement yarn install --no-optional

### ISSUE THREAD

**Issue by callumlocke** [yarnpkg/yarn#2615]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**

`yarn install --no-optional` doesn't seem to exist (or it's not documented).

**What is the expected behavior?**

It should work like [`npm install --no-optional`](https://docs.npmjs.com/cli/install) – i.e. don't even attempt to install `optionalDependencies` (as opposed to just allowing them to fail quietly).

**Please mention your node.js, yarn and operating system version.**

Node v7.5.0
Yarn v0.19.1
OS X El Capitan

**Comment by mourner** [comment]
It's already there but called `--ignore-optional`. The problem is that it's not documented currently on the `yarn install` docs page (along with `--ignore-scripts`).

**Comment by bcomnes** [comment]
`--ignore-optional` doesn't seem to be a work around for https://github.com/yarnpkg/yarn/issues/2437 either.

**Comment by sirlancelot** [comment]
Neither `--no-optional` nor `--ignore-optional` seem to work for me. I have an app with a dependency of `linkifyjs@2.1.4`. LinkifyJs has 3 large `optionalDependencies` which I don't want but Yarn will still install them.

**Comment by bestander** [comment]
merging https://github.com/yarnpkg/yarn/issues/2987
