### ISSUE TITLE
Latest tarball URL points to an old version

### ISSUE THREAD

**Issue by mourner** [yarnpkg/yarn#2616]
https://yarnpkg.com/latest.tar.gz downloads Yarn 0.19.1, while the latest version is 0.20.0. cc @bestander

**Comment by bestander** [comment]
0.20.0 is considered RC for now

**Comment by mourner** [comment]
@bestander oh, I guess I got confused by the [GH release tags](https://github.com/yarnpkg/yarn/releases) (which mark 0.20.0 as `latest`). What's the schedule for its promotion to stable?

**Comment by bestander** [comment]
Thanks, I've corrected the GH release to be pre-release.
The plan is to release RC for a few days and get feedback.
If there are no regressions then RC will be promoted to stable, otherwise a
few fixes will be cherry-picked and stable will be released as one of
patches.
