### ISSUE TITLE
Yarn download URL is 404'ing

### ISSUE THREAD

**Issue by MarshallOfSound** [yarnpkg/yarn#2618]
The download URL used in the install script is 404'ing.

https://yarnpkg.com/downloads/0.18.1/yarn-v0.18.1.tar.gz

This results in all builds failing that attempt to download and use `yarn`

**Comment by colbycheeze** [comment]
I'm having same problem. It looks like the install script added an additional `.` at the end of the download.

![screen shot 2017-02-02 at 5 13 57 pm](https://cloud.githubusercontent.com/assets/8884298/22572761/31264aee-e96b-11e6-8d77-4958baf143bb.png)

**Comment by MarshallOfSound** [comment]
@colbycheeze That's just a full stop at the end of the printf

```bash
printf "$red> Failed to download $url.$reset\n"
```

**Comment by colbycheeze** [comment]
Ah got it. Curious why the page is `404` from the script then. I can copy paste that URL and it downloads for me.

**Comment by MarshallOfSound** [comment]
@colbycheeze You are probably in the same situation as me, that script is running on a build agent somewhere right?

**Comment by colbycheeze** [comment]
@MarshallOfSound Yes, circleci

**Comment by barkerja** [comment]
Everything currently on the site is 404ing for me (including the direct link to the tar.gz)

**Comment by colbycheeze** [comment]
Ah, perhaps they are having some server stability issues. I finally got my build to work after mashing rebuild a couple of times...if you have a critical build waiting maybe try that a bit. Hopefully it's cleared up soon!

**Comment by markstos** [comment]
@MarshallOfSound @colbycheeze for build stability and performance, consider reducing the dependency on third-party resources fetched over the network for every build. CircleCI allows you to use Docker images, where you could pre-bake an base image that already had yarn downloaded and installed into it.

**Comment by colbycheeze** [comment]
Thanks I'll look into it. Not the most experienced with dev ops practiced but I'm learning :)

**Comment by Daniel15** [comment]
Sorry, Netlify were having issues and the site was very broken yesterday (https://github.com/yarnpkg/website/issues/370). It should be fixed now!
