### ISSUE TITLE
yarn version not behaving as documented, version 0.19.1

### ISSUE THREAD

**Issue by zachbradshaw** [yarnpkg/yarn#2624]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

`yarn version` returns the current version of Yarn, it does not return the prompt to update my package's version as documented [here](https://yarnpkg.com/docs/cli/version/#toc-updating-versions)

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn version`

**What is the expected behavior?**
Running `yarn version` should return a prompt similar to:
```
info Current version: 1.0.1
question New version: 1.0.2
info New version: 1.0.2
```
**Please mention your node.js, yarn and operating system version.**
Node 6.0.8, Yarn 0.19.1, Mac OSX 10.11.6

**Comment by kdstew** [comment]
I'm experiencing the same behavior.
Node 6.6.0, Yarn 0.19.1, Mac OSX 10.10.5

**Comment by kdstew** [comment]
https://github.com/yarnpkg/yarn/issues/2491

**Comment by zachbradshaw** [comment]
Ah, thanks! Had just been searching open issues and hadn't seen it. Closing this now.
