### ISSUE TITLE
Every time I use `yarn global add` my version of yarn changes. 

### ISSUE THREAD

**Issue by markstos** [yarnpkg/yarn#2627]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

First, I run: 

       yarn global add file://path/to/my/repo

And yarn reports that `yarn global v0.19.1`  was used.   Then I run the same command again:

       yarn global add file://path/to/my/repo

Now in the output reports that   `yarn global v0.17.1`  was used.  Each time I run `yarn global add`, the version of yarn changes back and forth between these two versions.  There is nothing particularly special about the local package I'm trying to install. It does include a "bin" section in package.json to request a binary be installed, which turns out to be have differently depending of which version of `yarn` ended up running. 

If `yarn` version 0.17.1 happens to be the one run that time, it will report "success" installing the binary, but the binary won't actually be there. If `yarn` version 0.19.1 is used, it will report "success", and the binary will actually be there. 

I found that after I ran `yarn global add` with 0.19.1, it would create a symlink from `/usr/local/bin/yarn` to `/usr/local/share/.config/yarn/global/node_modules/.bin/yarn`. This would cause `yarn 0.17.1` to run the next time.

Then `yarn global add` would run with 0.17.1 and after that command finished, I could see that the symlink at `/usr/local/bin/yarn` had been deleted, causing `yarn` 0.19.1 to run form `/usr/bin/yarn` the next time...

**It appears to be a bug that yarn 0.19.1 running `global add` adds a symlink to a different version of yarn when I'm not running `yarn global add yarn`**

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm not sure exactly what triggers `yarn global add` to act this way, but I did observe that was getting a stable version of `yarn` until I manually deleted the version of the `bin` script that my package installed into `/usr/local/bin`. After that, yarn entered the version changing loop.

The suspect code appears to be `initUpdateBins` in `src/cli/commands/global.js`.  This code appears responsible for deleting and creating symlinks each time that `yarn global add` runs.

**What is the expected behavior?**

I expect the same version of Yarn to run every time I use it.

**Please mention your node.js, yarn and operating system version.**

node v4.4.2
yarn 0.17.1 or 0.19.1, depending on how many times I've run it...
Ubuntu 16.04

**Comment by Daniel15** [comment]
> I found that after I ran yarn global add with 0.19.1, it would create a symlink from /usr/local/bin/yarn to /usr/local/share/.config/yarn/global/node_modules/.bin/yarn. This would cause yarn 0.17.1 to run the next time.

Based on this path, it sounds like you have installed Yarn via Yarn. This is not a supported use-case. Please try running `yarn global remove yarn` and see if that fixes things.

**Comment by markstos** [comment]
@Daniel15, thanks for the reply. I'm aware that I could stop experiencing the issue that eliminating one version of yarn.

_It still seems like a bug that running `yarn global add` adds a symlink to a different version of yarn when I'm not running `yarn global add yarn`._

I've been using software for many years and this is the first time I've run into software which upgrades and downgrades itself repeatedly when I'm not running upgrade/downgrade related commands!

**Comment by paul-soporan** [comment]
Closing because [we stopped supporting the `yarn global` workflow in v2](https://yarnpkg.com/getting-started/migration#use-yarn-dlx-instead-of-yarn-global) and we're not going to rework it in v1 to fix an obscure bug that only happens when using an unsupported workflow (`yarn global add yarn`).
