### ISSUE TITLE
Unable to install Yarn on Raspbian 

### ISSUE THREAD

**Issue by k0mita** [yarnpkg/yarn#2634]
Attempting to use the preferred apt-get method I get the following error after the "apt-get update" command:
```
**W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)**

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Attempting to install with the "curl -o- -L https://yarnpkg.com/install.sh | bash" script I get the following:

```

pi@raspberrypi:/opt $ curl -o- -L https://yarnpkg.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6742    0  6742    0     0  16120      0 --:--:-- --:--:-- --:--:-- 16129
Installing Yarn!
> Downloading tarball...

[1/2]: https://yarnpkg.com/latest.tar.gz --> /tmp/yarn.tar.gz.xTDcvVN2aQ
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    92  100    92    0     0    240      0 --:--:-- --:--:-- --:--:--   241
100   595    0   595    0     0    592      0 --:--:--  0:00:01 --:--:--  2171
100 3416k  100 3416k    0     0  1318k      0  0:00:02  0:00:02 --:--:-- 2834k

[2/2]: https://yarnpkg.com/latest.tar.gz.asc --> /tmp/yarn.tar.gz.xTDcvVN2aQ.asc
100    96  100    96    0     0    719      0 --:--:-- --:--:-- --:--:--     0
100   600    0   600    0     0   2082      0 --:--:-- --:--:-- --:--:--  2082
100   900  100   900    0     0   2692      0 --:--:-- --:--:-- --:--:--  2692
> Verifying integrity...
gpg: keyring `/home/pi/.gnupg/secring.gpg' created
gpg: key 86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: Signature made Mon 16 Jan 2017 23:45:03 UTC using RSA key ID FD2497F5
gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
     Subkey fingerprint: 6A01 0C51 6600 6599 AA17  F081 46C2 130D FD24 97F5
> GPG signature looks good
> Extracting to ~/.yarn...
> Adding to $PATH...
> We've added the following to your /home/pi/.bashrc
> If this isn't the profile of your current shell then please add the following to your correct profile:

export PATH="$HOME/.yarn/bin:$PATH"

**> Yarn was installed, but doesn't seem to be working :(.**
```

_OS DETAILS:
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"_

**Comment by Daniel15** [comment]
> Unable to find expected entry 'main/binary-armhf/Packages' in Release file

We only have amd64 and i386 in the repo... I guess we could add armhf too, especially since there's no native code (it's all JavaScript and shell scripts in the package)

**Comment by k0mita** [comment]
> we could add armhf too

Daniel15, I think that would be very helpful. I'm a bit surprised more people aren't requesting this to be available on raspberry Pi's .. 

Are there any other steps I need to take to promote this issue and advocate for the armhf support?

**Comment by Daniel15** [comment]
It's pretty easy to do, I just need to figure out the right Aptly command to add a new architecture. I originally created the repo by running `aptly repo create -distribution=stable -component=main -architectures=amd64,i386,all yarn`, maybe [aptly repo edit](https://www.aptly.info/doc/aptly/repo/edit/) can add another architecture.

**Comment by Daniel15** [comment]
It's pretty easy to do, I just need to figure out the right Aptly command to add a new architecture. I originally created the repo by running `aptly repo create -distribution=stable -component=main -architectures=amd64,i386,all yarn`, maybe [aptly repo edit](https://www.aptly.info/doc/aptly/repo/edit/) can add another architecture.

The Aptly metadata is over here if you want to try clone the repo and take a look: https://github.com/yarnpkg/releases/tree/gh-pages/debian-source

**Comment by Daniel15** [comment]
I added `armhf` and `arm64` to the repo, so this should be fixed now! Let me know if you still encounter issues :)

**Comment by nickdex** [comment]
Hey Daniel, is it possible to add support for Raspberry pi zero (w). They run on arm6l
```Console
➜ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 000000007cbec410
```

**Comment by JacobMiske** [comment]
I ran into some small bumps because sudo does not identify yarn. "sudo: yarn: command not found". Adding yarn to path in superuser fixed this for me.
