### ISSUE TITLE
Change "Linking dependencies" wording in `yarn add`

### ISSUE THREAD

**Issue by Meligy** [yarnpkg/yarn#2640]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`yarn add` currently writes:

```
[3/4] Linking dependencies...
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just add any package using `yarn add`

**What is the expected behavior?**

`link` as a word has a specific meaning in NPM world, which is creating filesystem links.

Yarn is actually copying files in this case, as per:

[![](https://pbs.twimg.com/media/C3UOVx-WEAAzNIo.jpg)](https://code.facebook.com/posts/1840075619545360)

So, it should use a different word, "extracting" or "copying" or "adding", when it's not creating a filesystem link, as the word "linking" is misleading.

**Please mention your node.js, yarn and operating system version.**

Yarn 0.20.0-20170114.1928

Node and OS not relevant.

**Comment by paul-soporan** [comment]
Hello from the future, we've used "linking" for a long time and it's a term used in many places of the documentation and also in the API. We aren't going to change it.
