### ISSUE TITLE
yarn remove module that doesn't exists in package.json when adding a new module.

### ISSUE THREAD

**Issue by muhammadsayuti** [yarnpkg/yarn#2645]
sometimes this feature is good to make it clean from some module that we don't use, but for me as a developer it's better to keep it there especially when i make node_modules as a seperated modules, usually i only copy the seperated modules into the node_modules folder untill the project is usable and can be published. 
So i just want to make sure if i can disable it ? any specific configuration i must  use ?

**Comment by xc2** [comment]
```sh
yarn add helloworld@file:./node_modules/helloworld
```

**Comment by muhammadsayuti** [comment]
thanks, it work but fail when trying to build , so i decide to publish the dependencies.
