### ISSUE TITLE
Yarn 0.19.1 Error when running yarn install

### ISSUE THREAD

**Issue by larryranches** [yarnpkg/yarn#2647]
I'm getting the error below when running `yarn install` on yarn version 0.19.1

System: macos
node: 7.5.0

Trace: 
  Error: Error connecting to repository. Please, check the url.
      at /usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/lib/resolvers/exotics/hosted-git-resolver.js:162:15
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by larryranches** [comment]
nvm got it fixed

**Comment by lazamar** [comment]
How did you fix it? I'm having the same error.

**Comment by larryranches** [comment]
@lazamar  I think I might have downgraded my version of node to v.6.9.5
