### ISSUE TITLE
Queue changes to improve performance even more?

### ISSUE THREAD

**Issue by FredyC** [yarnpkg/yarn#2665]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I have some set of modules installed. When I decide to replace one package with another one, it means to do `yarn remove` first and then `yarn add`. Both of these will cause linking dependencies process which can be rather slow for a bigger package list. Compared to NPM where removal is almost instantaneous, although leaving some bits and pieces behind.

Another scenario is a need to add production and development dependencies at once. It cannot be batched so I have to wait till one set is ready and then do other set. I am well aware that NPM is not different on this, but that doesn't mean that Yarn cannot be better :)

**Proposal**
I want to propose adding _simple_ command like `yarn queue` which would queue up all following changes from running `add`, `remove`, `upgrade` command and then `yarn queue go` (or similar) would actually apply those changes ending up with a single run of linking dependencies.

Or perhaps adding a flag to those three commands `--queue` to mark that command as queued and then `yarn queue` would actually run all those queued commands.

**Comment by hpurmann** [comment]
This sounds like it drastically increases complexity (and thus could introduce a lot of new bugs) for a speed improvement. I think it's actually not worth it.

**Comment by FredyC** [comment]
Yea, I don't have any insight on inner working of Yarn, so it's very possible it's not fit for something like that. It's merely a suggestion for a future times in case someone would want to hunt a speed even more. Honestly sometimes I feel that Yarn is actually slower on bigger projects.
