### ISSUE TITLE
yarn does not report the correct "wanted" version when using "yarn outdated"

### ISSUE THREAD

**Issue by stewx** [yarnpkg/yarn#2677]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In my package.json I have "node-sass": "^3.10.1" and yarn is telling me I should install version 4.5.0, which does not match this semver.

**If the current behavior is a bug, please provide the steps to reproduce.**

Using "^3.10.1"  means that the most recent version within 3.x.x should be "wanted". When I run `npm outdated`, it tells me this, which is correct:
```
Package                Current  Wanted  Latest
node-sass               3.10.1  3.13.1   4.5.0
```

When I run `yarn outdated`, the line for node-sass looks like this, which is incorrect:
```
Package             Current   Wanted Latest
node-sass           3.10.1    4.5.0  4.5.0
```

**What is the expected behavior?**
3.10.1 should be "wanted".

**Please mention your node.js, yarn and operating system version.**
node v4.7.0
yarn 0.19.1
Mac OS X 10.12.2

**Comment by arcanis** [comment]
This seems to have been fixed, please open a new issue if you're still experiencing this.
