### ISSUE TITLE
404 from yarn server on package

### ISSUE THREAD

**Issue by Matzielab** [yarnpkg/yarn#2679]
Hey guys,

I get a 404 when trying to get a package via running yarn. Our team is expanding and new devs will need it. Do you think you'll make it available again?

error An unexpected error occurred: "https://registry.yarnpkg.com/@kadira/storybook-addon-links/-/stoybook-addon-links-1.0.1.tgz: Request failed \"404 Not Found\"".

Thanks :)

**Comment by Daniel15** [comment]
It looks like there's a typo in the filename - stoybook-addon-links-1.0.1.tgz should be sto**r**ybook-addon-links-1.0.1.tgz. You could try remove this package and then reinstall it.
