### ISSUE TITLE
Does `yarn add --ignore-optional` work?

### ISSUE THREAD

**Issue by kumarharsh** [yarnpkg/yarn#2680]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Even after specifying the `--ignore-optional` flag on yarn add, it tries to install optional dependency.

**If the current behavior is a bug, please provide the steps to reproduce.**
(under windows)
mkdir test && cd test
npm init -y
yarn add paper --ignore-optional

**What is the expected behavior?**
Yarn shouldn't warn about installing the optional `canvas` dependency, when I don't have the tools to build it.

**Please mention your node.js, yarn and operating system version.**
Node: 6.9.2
Yarn: 0.19.1
Windows 10 Home 64bit

**Comment by ianks** [comment]
I am experiencing this same issue. No errors are thrown, and the optional dependencies are still installed and added to `yarn.lock`.

**Comment by OmgImAlexis** [comment]
Isn't the flag `--no-optional`?

**Comment by kumarharsh** [comment]
`yarn add --help` gives me:

![image](https://cloud.githubusercontent.com/assets/760112/25170600/c64c2e44-2508-11e7-87f2-6a62ca64f9ce.png)

**Comment by OmgImAlexis** [comment]
I think that may be wrong since the docs on the site state it's `--no-optional` and that's the flag npm uses.

**Comment by kumarharsh** [comment]
Actually, I can't even find the word `optional` on the website docs here: https://yarnpkg.com/en/docs/cli/install#search. Plus, there is no entry for `no-optional` in the `yarn help` command.

**Comment by bestander** [comment]
merging into https://github.com/yarnpkg/yarn/issues/2666

**Comment by timrs2998** [comment]
This is still an issue with yarn v1.1.0, running `yarn add --help | grep opt` I see:

```
    --ignore-optional                   ignore optional dependencies
    -O, --optional                      save package to your `optionalDependencies`
```

I can find it in the CLI help documentation, but not the yarn website docs. When I do:

```sh
yarn add bunyan@1.8.3
yarn why dtrace-provider
```

I can verify that the optional dtrace-provider dependency is installed anyways. As a result, I can't ignore optional dependencies for a specific package.

**Comment by davidjb** [comment]
Like @timrs2998, I'm seeing the same issue on yarn 1.2.1 (Mac, 10.13).  Comments added to #4665.

**Comment by vleandersson** [comment]
--ignore-optional works in yarn 1.15.2 on MacBookPro12,1 with node 11.13.0

**Comment by RodrigoMattosoSilveira** [comment]
--ignore-optional does works in yarn 1.17.0 on MacBookPro12,1 with node 11.13.0

**Comment by jkassis** [comment]
does not work...

```
[I] jkassis@Jeremys-MBP ~/c/m/a/s/code (wip)> yarn add --ignore-optional rrule                                                                 11.05 07:18
yarn add v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
└─ rrule@2.6.6
info All dependencies
├─ luxon@1.25.0
├─ rrule@2.6.6
└─ tslib@1.14.1
✨  Done in 0.95s.
```

**Comment by taoning2014** [comment]
OMG, this is still broken...

**Comment by niftyminer** [comment]
Why is this issue closed? As far as I can tell, `--ignore-optional` is still ignored...

**Comment by lucasgadams** [comment]
This seems like it still doesnt work?
