### ISSUE TITLE
Publish a sub directory

### ISSUE THREAD

**Issue by blackChef** [yarnpkg/yarn#2697]
Suppose we have a project that has this structure:

```
  UIProject >
    > test
    > demos
    > components
      > dialog
      > buttons
      ...
```
When publishing this project to npm, we want only the `components` folder is published. So that our consumer can use it like this:

```
import dialog from 'UIProject'
import buttons from 'UIProject'
```

Is it possible to accomplish this using yarn ?

**Comment by bestander** [comment]
Currently Yarn has the same capabilities as npm in publishing.
For your case you can put a pakage.json into components folder and publish a new package from the subfolder.
We do similar thing for Jest.
