### ISSUE TITLE
Local test failing

### ISSUE THREAD

**Issue by SamHH** [yarnpkg/yarn#2699]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Run `yarn run test`, and all tests pass except `commands/remove.js`. Here's the CLI output:

```
 FAIL  __tests__/commands/remove.js
  ● Test suite failed to run

    ProcessTerminatedError: cancel after 2 retries!

      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:25)
      at Array.forEach (native)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:75:36)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)

A worker process has quit unexpectedly! Most likely this an initialization error.
```

I'm also seeing some other errors pop up as well, possibly less important:

```
(node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: channel closed
(node:23200) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23202) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: channel closed
(node:23202) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Fork Yarn, optionally run `yarn run build` and then run `yarn run test`.

**What is the expected behavior?**

Tests pass.

**Please mention your node.js, yarn and operating system version.**

Node 7.5.0, Yarn 0.20.3, macOS 10.12.3. This bug was also present under Yarn 0.20.0.

**Comment by bestander** [comment]
I wonder if this is because of Node 7.
Can you try on Node 6?

**Comment by SamHH** [comment]
Good call! No error on 6.9.1.

**Comment by bestander** [comment]
Ok, I'll close this as we can't probably do anything about it
