### ISSUE TITLE
Incorrectly reports an unmet peer dependency upon peer upgrade

### ISSUE THREAD

**Issue by mjswensen** [yarnpkg/yarn#2704]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn incorrectly reports an unmet peer dependency when a satisfactory peer is upgraded.

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone https://github.com/mjswensen/yarn-peer-dependency-bug. I've set up a small repo with two packages there that reproduce this issue with a single command (see [its README](https://github.com/mjswensen/yarn-peer-dependency-bug#readme)).

Here's this gist of what's going on:
* a main package depends on `foo@^2.0.0` and `bar`.
* bar has a peer dependency on `foo@^2.0.0`.
* within main, the user runs `yarn upgrade foo`, upgrading it from `2.0.0` to `2.1.0`.
* Even though `foo@2.1.0` still satisfies bar's peer dependency requirement (which was `foo@^2.0.0`), yarn reports `warning "bar@<version>" has unmet peer dependency "foo@^2.0.0".`

**What is the expected behavior?**
Yarn shouldn't warn when a peer-depended package gets upgraded if the new version still satisfies the peer dependency.

**Please mention your node.js, yarn and operating system version.**

    % yarn --version
    0.20.3

    % node --version
    v7.5.0

macOS Sierra 10.12.3 (16D32)

**Comment by mjswensen** [comment]
I've got a fix for this and will send a pull request within the next few days.

**Comment by hpurmann** [comment]
I guess this can be closed then, @bestander?

**Comment by merriam** [comment]
Just an FYI, this can still be an issue.   

In may case, using yarn 0.21.3, node v7.7.1, I would expect no warning for `eslint-plugin-import` on this command:

> 
> yarn add eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-prefer-object-spread eslint-plugin-react
> yarn add v0.21.3
> warning No license field
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> warning "eslint-config-airbnb-base@11.1.1" has unmet peer dependency "eslint-plugin-import@^2.2.0".
> warning "eslint-config-airbnb@14.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^3.0.2 || ^4.0.0".
> warning "eslint-config-airbnb@14.1.0" has unmet peer dependency "eslint-plugin-import@^2.2.0".
> warning "eslint-config-airbnb@14.1.0" has unmet peer dependency "eslint-plugin-react@^6.9.0".
> [4/4] 📃  Building fresh packages...
> success Saved 5 new dependencies.
> ├─ eslint-config-airbnb@14.1.0
> ├─ eslint-plugin-import@2.2.0
> ├─ eslint-plugin-jsx-a11y@4.0.0
> ├─ eslint-plugin-prefer-object-spread@1.1.0
> └─ eslint-plugin-react@6.10.2
> warning No license field
> ✨  Done in 2.30s.
> 

and a `yarn list` includes:

> ├─ eslint-config-airbnb-base@11.1.1
> ├─ eslint-config-airbnb@14.1.0
> │  └─ eslint-config-airbnb-base@^11.1.0
> ├─ eslint-import-resolver-node@0.2.3
> │  ├─ debug@^2.2.0
> │  ├─ object-assign@^4.0.1
> │  └─ resolve@^1.1.6
> ├─ eslint-module-utils@2.0.0
> │  ├─ debug@2.2.0
> │  ├─ debug@2.2.0
> │  │  └─ ms@0.7.1
> │  ├─ ms@0.7.1
> │  └─ pkg-dir@^1.0.0
> ├─ eslint-plugin-import@2.2.0
> │  ├─ builtin-modules@^1.1.1
> │  ├─ contains-path@^0.1.0
> │  ├─ debug@^2.2.0
> │  ├─ doctrine@1.5.0
> │  ├─ eslint-import-resolver-node@^0.2.0
> │  ├─ eslint-module-utils@^2.0.0
> │  ├─ has@^1.0.1
> │  ├─ lodash.cond@^4.3.0
> │  ├─ minimatch@^3.0.3
> │  └─ pkg-up@^1.0.0
> ├─ eslint-plugin-jsx-a11y@4.0.0
> │  ├─ aria-query@^0.3.0
> │  ├─ ast-types-flow@0.0.7
> │  ├─ damerau-levenshtein@^1.0.0
> │  ├─ emoji-regex@^6.1.0
> │  ├─ jsx-ast-utils@^1.0.0
> │  └─ object-assign@^4.0.1
> ├─ eslint-plugin-prefer-object-spread@1.1.0
> ├─ eslint-plugin-react@6.10.2
> │  ├─ array.prototype.find@^2.0.1
> │  ├─ doctrine@^1.2.2
> │  ├─ has@^1.0.1
> │  ├─ jsx-ast-utils@^1.3.4
> │  └─ object.assign@^4.0.4
> ├─ eslint@3.18.0
> │  ├─ babel-code-frame@^6.16.0
> │...
