### ISSUE TITLE
Yarn 0.20.3 reports as 0.19.1 on Windows using MSI

### ISSUE THREAD

**Issue by patoncrispy** [yarnpkg/yarn#2706]
I thought I was having problems updating Yarn, so I uninstalled the version I had on my machine, installed the new one from the MSI but the version number seems to be incorrect via the CLI.

![yarn](https://cloud.githubusercontent.com/assets/2559414/23027021/ff14e286-f45a-11e6-945a-6f3644bb9a4f.PNG)

**Comment by bestander** [comment]
That is strange.
Could you run self-update at some point?
In that case the self-updated location would override it

**Comment by patoncrispy** [comment]
Command 'self-update' not found. I take it then that the installation is incorrect, or something?

**Comment by bestander** [comment]
Try uninstalling it completely.
And installing again

**Comment by patoncrispy** [comment]
I did. Checked the installation directory and all gone. Wouldn't work from the command line. No installation via NPM. Re-installed via MSI and I got the result in the image attached.

**Comment by patoncrispy** [comment]
Using NPM works fine.

**Comment by bestander** [comment]
Maybe the MSI installer leaves some traces from previous install cc @Daniel15

**Comment by JonathanWolfe** [comment]
I've had this issue since `v0.18.1`. Haven't tried installing via `npm` to see if that fixes it

**Comment by Daniel15** [comment]
I've seen this happen when people install Yarn via Yarn itself. It usually
means there's another Yarn on your PATH. Can you try searching your
computer for "yarn.cmd" and see if one exists outside the Program Files
directory?

**Comment by JonathanWolfe** [comment]
I did find one in the old `self-update` folder that apparently wasn't cleaned up on uninstall. Uninstalling, deleting that folder, and reinstalling fixed the version issue, @Daniel15.

**Comment by bestander** [comment]
We need to sort out this self-update feature

**Comment by Daniel15** [comment]
> We need to sort out this self-update feature

I guess there's code that's looking at the `self-update` folder that should be deleted. Removing that should fix this

**Comment by patoncrispy** [comment]
I used the MSI, not `self-update`, which wasn't available as a command anyway.

**Comment by Daniel15** [comment]
`self-update` is an old feature that doesn't exist any more (it needs to be reimplemented in a more reliable way). However, for people that have ran `self-update` in the past, they might still have old versions around.

**Comment by Daniel15** [comment]
#2720 will fix this.

**Comment by dheerajbhaskar** [comment]
Along with deleting your `Program Files (x86)\Yarn` folder after uninstalling, you need to delete your `Appdata\local\yarn` folder as well.

To find the `Appdata\local\yarn` folder, type %appdata% in the run dialog box (win+R), move up a folder and move into `local` folder there, here you'll find the `yarn` folder to delete

**Comment by Daniel15** [comment]
#2720 removed the self-update-related loading code. The only issue now will be if you install Yarn using Yarn or npm, which is pretty rare.
