### ISSUE TITLE
yarn generate Extraneous dependencies

### ISSUE THREAD

**Issue by JiaLiPassion** [yarnpkg/yarn#2708]
v0.22.0-20170215.1538 , 19.1 is the same behavior
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
yarn generate Extraneous dependencies.
**If the current behavior is a bug, please provide the steps to reproduce.**

I have a middleware repo which package.json is this

```
  "main": "lib/index.ts",
  "typings": "lib/index.ts",
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
   ...
  }
```

It is a middleware library repository and depends on angular 2.2.1

And I have a application repo which depends on middleware and angular , so the package.json looks like 
```
  "main": "lib/index.ts",
  "typings": "lib/index.ts",
  "dependencies" : {
     "middleware": "file:../middleware"
  },
  "devDependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
   ...
  }
```

after the running yarn, the result in app's node_modules become

```
  node_modules/
             @angular/common
             middleware/
                       node_modules/
                                    @angular/common
```

The @angular/common is duplicated, so when compile with tsc, a lot of error occurs, npm will not generate @angular/common under middleware

**What is the expected behavior?**

don't generate duplicate dependencies. 

```
  node_modules/
             @angular/common
             middleware/
                       node_modules/
                                   // no angular common
```
**Please mention your node.js, yarn and operating system version.**
nodejs : 7.0
os : mac os 10.12.3
yarn :v0.22.0-20170215.1538 and 19.1

**Comment by arcanis** [comment]
This issue is related to an old version, so I'm gonna close it - feel free to open a new one if you experience a similar issue on the latest releases!
