### ISSUE TITLE
Unexpected side effect of `yarn -v`: it runs yarn / yarn install

### ISSUE THREAD

**Issue by thomasklein** [yarnpkg/yarn#2710]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn -v`will also run `yarn` / `yarn install` when I only wanted to see the version.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn -v` anywhere. It becomes most apparent in a folder with a package.json file.

**What is the expected behavior?**
Only the version number is shown.

**Please mention your node.js, yarn and operating system version.**
node v6.9.4
yarn 0.20.3
Mac OSX 10.12.3

**Comment by chrisbujok** [comment]
I think it duplicates #2600

**Comment by redstrike** [comment]
I think the command line interface is inconsistent here.
**node -v** => version
**npm -v** => version
**yarn -v** => install ??? and why **yarn -V** ???
