### ISSUE TITLE
nodejs needs to remove for installing yarn

### ISSUE THREAD

**Issue by jishnums** [yarnpkg/yarn#2711]
Inside ubuntu 14.04 nodejs needs to remove while installing yarn

With sudo apt-get install yarn

The output is 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gyp javascript-common libc-ares-dev libctemplate2 libgeos-3.4.2 libgeos-c1
  libhdf4-0-alt libhdf5-7 libjs-node-uuid libnetcdfc7 libodbc1 libpcrecpp0
  libpq5 libssl-dev libssl-doc libtinyxml2.6.2 libv8-3.14-dev libxerces-c3.1
  zlib1g-dev
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  nodejs
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 1 to remove and 774 not upgraded.
Need to get 0 B/1,740 kB of archives.
After this operation, 22.9 MB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by Daniel15** [comment]
Most likely you have an old version of Node.js (before 4.x) installed. Yarn is not compatible with these versions of Node.js. You'll need to install a newer version (eg. through the NodeSource Ubuntu repo).

**Comment by Daniel15** [comment]
Closing this out since we haven't heard back.
