### ISSUE TITLE
status of yarn prepare

### ISSUE THREAD

**Issue by jantimon** [yarnpkg/yarn#2712]
Is there a any planned milestone for the 4 month old npm prepare feature?

Are you planing to keep up with npm features in future in general so it can completely replace npm or is yarn rather a tool for installing and clean dependency locking?

**Comment by timoxley** [comment]
Related:
* https://github.com/yarnpkg/yarn/pull/1499
* https://github.com/yarnpkg/yarn/issues/1323

**Comment by bfirsh** [comment]
Looks like this has been resolved in #3004.

**Comment by bestander** [comment]
thanks for bumping, yes it was done
