### ISSUE TITLE
Install regression between 0.19.1 and 0.20.0

### ISSUE THREAD

**Issue by SomeoneWeird** [yarnpkg/yarn#2714]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Package `skeletron` fails to install.

**If the current behavior is a bug, please provide the steps to reproduce.**

Installation works w/ `0.19.1`
```
➜ yarn --version
0.19.1
➜ yarn add skeletron
yarn add v0.19.1
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
└─ skeletron@0.0.2
warning No license field
✨  Done in 0.72s.
```

Installation fails w/ `0.20.0` (also fails with latest stable `0.20.3` and latest prerelease `0.21.0`)
```
➜ yarn --version
0.20.0
➜ yarn add skeletron
yarn add v0.20.0
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/private/tmp/node_modules/findit/test/symlinks/dir1/does-not-exist'".
info If you think this is a bug, please open a bug report with the information provided in "/private/tmp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

Package skeletron successfully installs.

**Please mention your node.js, yarn and operating system version.**

NodeJS 5/6/7

macOS 10.12.3 / Amazon Linux 2016.09

**Comment by SomeoneWeird** [comment]
Looks like 65e89b5d02e06a15c65f13198c39271684c4f217 is the culprit

**Comment by bestander** [comment]
@SomeoneWeird, thanks for finding the cause, I'll follow up with #2744 now
