### ISSUE TITLE
`yarn help list` links to missing page

### ISSUE THREAD

**Issue by justinbowes** [yarnpkg/yarn#2718]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
`yarn help list` returns a link to online documentation:
```
  --network-concurrency <number>  maximum number of concurrent network requests
    --depth [depth]                 Limit the depth of the shown dependencies

  Visit https://yarnpkg.com/en/docs/cli/list for documentation about this command.
```
However, visiting https://yarnpkg.com/en/docs/cli/list results in a 404.

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn help list`

**What is the expected behavior?**
The URL returned by `yarn help list` should document the command.

**Please mention your node.js, yarn and operating system version.**
v6.9.5; 0.20.3; Mac OS X 10.11.6

**Comment by SgtPooki** [comment]
It looks like the standard is to use the actual command name for the URL, but someone incorrectly set the URL for list as ls: https://yarnpkg.com/en/docs/cli/ls

But you can see from the following aliases, that the urls are not consistent: https://github.com/yarnpkg/yarn/blob/efa1c7a84082589e6f8c375c3fcbc82f07e7a238/src/cli/aliases.js#L6-L10

From the few highlighted shorthand items above:

Correct 404s (shorthand):
- https://yarnpkg.com/en/docs/cli/c
- https://yarnpkg.com/en/docs/cli/i
- https://yarnpkg.com/en/docs/cli/la
- https://yarnpkg.com/en/docs/cli/ll
- https://yarnpkg.com/en/docs/cli/ln
- https://yarnpkg.com/en/docs/cli/r
- https://yarnpkg.com/en/docs/cli/rb
- https://yarnpkg.com/en/docs/cli/rm
- https://yarnpkg.com/en/docs/cli/t
- https://yarnpkg.com/en/docs/cli/tst
- https://yarnpkg.com/en/docs/cli/un
- https://yarnpkg.com/en/docs/cli/up
- https://yarnpkg.com/en/docs/cli/v

Incorrect 200s (shorthand): 
- https://yarnpkg.com/en/docs/cli/ls

Incorrect 404s (non-shorthands):
- https://yarnpkg.com/en/docs/cli/list

Correct 200s (non-shorthands):
- https://yarnpkg.com/en/docs/cli/config
- https://yarnpkg.com/en/docs/cli/install
- https://yarnpkg.com/en/docs/cli/link
- https://yarnpkg.com/en/docs/cli/remove
- https://yarnpkg.com/en/docs/cli/test
- https://yarnpkg.com/en/docs/cli/upgrade
- https://yarnpkg.com/en/docs/cli/version

Missing documentation urls:
- https://yarnpkg.com/en/docs/cli/rebuild

**Comment by sergiorojasa** [comment]
I would like to work on this

**Comment by gsklee** [comment]
@bestander close

The situation has been resolved with the removal of aliases.
