### ISSUE TITLE
Put error logs in cache folder

### ISSUE THREAD

**Issue by tomkel** [yarnpkg/yarn#2719]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
Yarn will store `yarn-error.log` in the current directory.

**What is the expected behavior?**
In [npm v4.2.0](https://github.com/npm/npm/releases/tag/v4.2.0), `npm-debug.log` is no longer placed in the current directory, but in the `(npm config get cache)/_logs` directory. I suggest yarn do something similar with the error logs.

**Comment by liorzisman** [comment]
Hi, can I try working on this?

**Comment by liorzisman** [comment]
@Daniel15 Do you have a suggestion regarding simulating errors in tests that would invoke a log file? Couldn't find anything in the current tests

**Comment by Daniel15** [comment]
> can I try working on this?

Sure :) 

> Do you have a suggestion regarding simulating errors in tests that would invoke a log file? 

Not sure, sorry. You might need to look around the code a bit. Maybe see if there's any existing tests for the log files?

**Comment by liorzisman** [comment]
Thanks for the quick reply. I'll try digging in. So far, no tests related to log files that I could find.
Hopefully will have the PR ready tomorrow.

**Comment by bestander** [comment]
Cache folder does not seem like the best place to store error log.
How about a configurable folder for install metadata, e.g. `.yarn` in the project?
We could put .yarn-integrity an yarn-error.log there if user opted in.

**Comment by BYK** [comment]
I don't think this is worth spending time on so closing. If there is anyone with a concrete suggestion other than placing this file in the cache directory, please file a new issue with as much detail as possible or even better, propose an RFC: https://github.com/yarnpkg/rfcs
