### ISSUE TITLE
stuck in last few packages almost every time

### ISSUE THREAD

**Issue by broven** [yarnpkg/yarn#2729]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
stuck in last few packages almost every time during fetching packages operation
like 934/935     865/866
**If the current behavior is a bug, please provide the steps to reproduce.**

run `yarn` in every project packages bigger than 600 packages
**What is the expected behavior?**
 Fast.   or tell me what you are doing during the stuck time.
**Please mention your node.js, yarn and operating system version.**
node 7.5.0
mac OS 10.12
yarn v0.20.3

**Comment by broven** [comment]
Is yarn have debug mode?

**Comment by hpurmann** [comment]
There is a verbose mode, enabled by adding the `verbose` flag, e.g. `yarn install --verbose`.

**Comment by broven** [comment]
@hpurmann thanks, I'll try it
