### ISSUE TITLE
Always says 'error An unexpected error occurred: "Unknown token 1056:1".'

### ISSUE THREAD

**Issue by jasonlam0619** [yarnpkg/yarn#2730]
I'm using the latest version (v0.20.3) of yarn.

**bug**

**Every yarn command leads to error: `error An unexpected error occurred: "Unknown token 1056:1`. Even `yarn` and `yarn -v` log this error.**

![image](https://cloud.githubusercontent.com/assets/8470477/23115792/29afd080-f782-11e6-9f71-426d3711bd18.png)

I've tried to uninstall and reinstall yarn, but the problem exists still.

**Node version: v7.4.0**

**OS: macOS Sierra 10.12.1**

**Comment by aouaki** [comment]
This is most likely an error in your yarn.lock.
Try deleting it and running `yarn install` again
If this doesn't solve the issue, check the output written in the file `yarn-error.log` as advised by the CLI

**Comment by im-amir** [comment]
For anyone, if the above does'nt solve the issue, just delete the .yarnrc file (C://Users/my_name/.yarnrc).
Then, come back in your project directory, and run "yarn install" again, or whatever yarn command.
Enjoy! :)

**Comment by kvnkarthik02** [comment]
@im-amir hey! I've tried both your solution and the one above yours, but I'm still having the same issue. is there anything else I could try?

**Comment by im-amir** [comment]
@kvnkarthik02 If you tried both above, then you may have issues with your yarn cache OR with your Node version.
For clearing yarn cache:
`yarn cache clean`
If this doesn't work, try updating your node version to the latest, then install yarn.
