### ISSUE TITLE
--link-duplicates error

### ISSUE THREAD

**Issue by STRML** [yarnpkg/yarn#2734]
**Do you want to request a *feature* or report a *bug*?**

This is a bug in the pre-release `0.21.2` version with the `--link-duplicates` flag.

**What is the current behavior?**

Installing a project with `@kadira/storybook` and `webpack@2` results in the following error:

> error An unexpected error occurred: "EEXIST: file already exists, link '/home/git/forks/yarn-link-bug/node_modules/@kadira/storybook/node_modules/enhanced-resolve/node_modules/memory-fs/.npmignore' -> '/home/git/forks/yarn-link-bug/node_modules/babel-loader/node_modules/enhanced-resolve/node_modules/memory-fs/.npmignore'".

**Please mention your node.js, yarn and operating system version.**

Node 6.9.2, Yarn 0.21.2, OSX Sierra.

**Reproduction Repository**

A [reproduction is available](https://github.com/STRML/yarn-link-bug).

Ref: https://github.com/yarnpkg/yarn/pull/2620#issuecomment-281146567 and [this tweet](https://twitter.com/bestander_nz/status/833696608390836224). My preference would be for the feature to remain as it gives us significant (20%) size savings on our frontend project.

**Comment by felixfbecker** [comment]
I am meeting this too, essentially I cannot use the option because it doesn't work reliably.
I need every little speed improvement in the linking phase, since it seems like we will not see a no cache option in the near future (https://github.com/yarnpkg/rfcs/pull/53)

**Comment by bestander** [comment]
Can't fetch a private package IIRC An unexpected error occurred: "https://registry.yarnpkg.com/@kadira/storybook-addon-links/-/storybook-addon-links-1.0.1.tgz: Request failed \"503 Service Unavailable\"".

**Comment by bestander** [comment]
I wonder if the error is related to @ in file path

**Comment by felixfbecker** [comment]
@bestander would it help if I figured out another reproduction case?

**Comment by bestander** [comment]
Of course

**Comment by bestander** [comment]
Even more help would be to find out the cause of the issue, the core linking logic is implemented here https://github.com/yarnpkg/yarn/blob/master/src/util/fs.js#L513 and here https://github.com/yarnpkg/yarn/blob/0ad2bf91639911e49d68024c56df4e03189fd153/src/package-linker.js#L232

**Comment by mlli2** [comment]
Is this issue still being tracked?

**Comment by bestander** [comment]
Afaik no one in the core team is actively working on fixing that, help from the community is expected.

**Comment by navarroaxel** [comment]
With the new webpack@3.0.0 an error appears when I use ``--link-duplicates``. This didn't happen with webpack@2.6.1.

Steps to reproduce:
````bash
mkdir test && cd test
yarn add webpack webpack-stream webpack-dev-middleware --link-duplicates
````
result:

> error An unexpected error occurred: "EEXIST: file already exists, link '/test/node_modules/uglifyjs-webpack-plugin/node_modules/enhanced-resolve/node_modules/memory-fs/.gitattributes' -> '/test/node_modules/webpack-dev-middleware/node_modules/enhanced-resolve/node_modules/memory-fs/.gitattributes'".

I tested it using several version combinations:
node@6.11.0 and node@8.1.2
yarn@0.24.6 and yarn@0.26.1

**Comment by bestander** [comment]
looking into it now
