### ISSUE TITLE
Add Dockerfile for Node.js 6

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2737]
See @SimenB's comments on https://github.com/yarnpkg/yarn/pull/2721

**Comment by SimenB** [comment]
No need to do this since it's included in the official images :smile:

**Comment by Daniel15** [comment]
Yeah, good point. Yarn was added to the Node.js Docker image in https://github.com/nodejs/docker-node/issues/243

I was going to close this task but I couldn't find it. It turns out I was searching for issues containing "Docker" which doesn't match "Dockerfile" - Thanks, GitHub. 😠
