### ISSUE TITLE
*bug* Yarn will not install devDependencies when NODE_ENV=production

### ISSUE THREAD

**Issue by mldangelo** [yarnpkg/yarn#2739]
**Current behavior**
Currently, when `NODE_ENV=production`, yarn will only install dependencies and not devDependencies. This behavior mirrors npm, but isn't reflected anywhere in yarn's [documentation](https://yarnpkg.com/lang/en/docs/cli/install/). and there's no flag to force yarn to all dependencies. The ability to force all dependencies to be installed is useful to me for ci testing. My current workaround is to use `NODE_ENV=development yarn`.

**Proposed solutions**
1. Add a flag which forces all dependencies to be installed `yarn install --all` (?)
2. Update the [documentation](https://github.com/yarnpkg/website) to reflect this shortcoming. 

I'm happy to do either or both if pull requests are welcome.

**node.js, yarn and operating system version.**
* node v7.5.0
* yarn v0.20.3
* Mac OS and Ubuntu 14.04

**Comment by LINKIWI** [comment]
I don't think this is a bug. As you mentioned, `npm` has exactly the same behavior when you set `NODE_ENV=production`. I don't see why `NODE_ENV=production` should *not* only install production dependencies.

**Comment by mldangelo** [comment]
@LINKIWI I've got weird ci configurations that probably need to be refactored. [Here](https://github.com/mldangelo/mldangelo/blob/master/.travis.yml)'s one of them where I run tests (which rely on dev dependencies) with my application in production mode. 

Would either of my suggestions be welcome? Or if this is something that you believe only I experience, I'll happily close the issue.

**Comment by DavidBadura** [comment]
@mldangelo You can install the dev dependencies in `NODE_ENV=production` with `yarn install --production=false`

**Comment by mnpenner** [comment]
Good to know about `--production=false`. I think that should be documented too.

I needed this feature too for CI because I need *all* the packages to build my project, but webpack (and the `react` library in particular) should have `NODE_ENV=production` to create a smaller bundle. After the bundle is built, I actually don't need any node_modules at all in production.

**Comment by rarkins** [comment]
FYI, I seem to have experienced the opposite behaviour in yarn 0.27.5. When NODE_ENV=production is set, yarn is still installing devDependencies, while npm@5.3.0 is not.

**Comment by antoinerousseau** [comment]
https://docs.npmjs.com/misc/config#dev

**Comment by rally25rs** [comment]
As mentioned in other comments, this is the intended behavior. The documentation for the `--production=false` flag to override it is here: https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production

> **yarn install --production[=true|false]**
> Yarn will not install any package listed in devDependencies if the NODE_ENV environment variable is set to production. Use this flag to instruct Yarn to ignore NODE_ENV and take its production-or-not status from this flag instead.

I'm going to mark this issue 'closed' for now, but if you feel there is more to it that needs resolved, let us know and we can re-open it.

**Comment by sir-gon** [comment]
I'm using NODE_ENV=production to produce a "production" build in a CI/CD (docker) environment.
I think, this npm/yarn behavior is not clear at all.

**Comment by cweekly** [comment]
@sir-gon I'm about to help a colleague resolve this same situation. I think I grok the yarn docs cited above; all that should be required is to do `NODE_ENV=production yarn install --production=false`, so node/webpack/etc do their thing for production, but yarn installs everything including devDependencies.

Tangent: seems to me with both yarn and npm there's insufficient distinction between "dependencies needed to **build** the software" and "dependencies needed at **runtime**".

**Comment by SalathielGenese** [comment]
I faced the same issue and thank for you explanations. Here is how I circumvent this under Docker environment https://stackoverflow.com/questions/31889867/docker-compose-not-overriding-dockerfile-environment-variables#answer-53705415

**Comment by aemc** [comment]
Thank goodness for this thread.

**Comment by mrdulin** [comment]
Same issue. Good to know. Thanks.

**Comment by dazlious** [comment]
Thx for this thread! Ran into this issue with docker and it was not very obvious as I migrated from one dockerfile and had quite a lot changed

**Comment by batica81** [comment]
This was a very difficult issue to track down, thank you for this thread!

**Comment by PastaJ36** [comment]
Is there a flag to override this for Yarn V2+? The production flag seems removed, with the equivalent essentially forcing `--production=true`

**Comment by rdimascio** [comment]
6 years later and this thread is still saving jobs.

**Comment by Dema1348** [comment]
> 6 years later and this thread is still saving jobs.

It´s true, this thread saved my life

**Comment by mirupal** [comment]
saved me too. But still 1-2 hours lost to debugging :/
