### ISSUE TITLE
error Couldn't find a package.json during Docker build

### ISSUE THREAD

**Issue by jean-francois-labbe** [yarnpkg/yarn#2741]
Yarn version: 0.21.2
Nodejs version: 6.9 and 4.7

When running yarn locally it works
When running npm install it works
When running yarn install Dockerfile (`docker build .`) it fails with: `error Couldn't find a package.json file in "/root/.cache/yarn/npm-readable-stream-2.2.2-a9e6fec3c7dda85f8bb1b3ba7028604556fc825e"`
I have absolutely no idea why.

```
Step 16 : RUN yarn install
 ---> Running in 917c2b1b57fb
yarn install v0.21.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find a package.json file in "/root/.cache/yarn/npm-readable-stream-2.2.2-a9e6fec3c7dda85f8bb1b3ba7028604556fc825e"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

Yarn is installed this way in the Dockerfile
```
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.2
ENV PATH /root/.yarn/bin:$PATH
```

**Comment by videni** [comment]
how do you resolve this trouble?

**Comment by CorpoScum** [comment]
How was this completed again?
