### ISSUE TITLE
Chinese docs, Install via Chocolatey title not display properly

### ISSUE THREAD

**Issue by xiaohp** [yarnpkg/yarn#2742]
the link is https://yarnpkg.com/zh-Hans/docs/install#windows-tab

#### 用 Chocolatey 安装
display as

`#### 用 Chocolatey 安装`

It should a title

**Comment by bestander** [comment]
Cc @thejameskyle

**Comment by thejameskyle** [comment]
Reported to Crowdin, it's their markdown printer which is broken.

**Comment by xiaohp** [comment]
the bug had fixed
