### ISSUE TITLE
Doesn't work well on Travis CI; invalid tar file

### ISSUE THREAD

**Issue by gsklee** [yarnpkg/yarn#2750]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
https://travis-ci.org/zeit/hyper/jobs/202036801#L378

Relevant discussion: https://github.com/zeit/hyper/commit/70822a31b531d8555db65b1ef9b7e781ac958ed5

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should not break.

**Please mention your node.js, yarn and operating system version.**
See at https://github.com/zeit/hyper

**Comment by bestander** [comment]
Can't reproduce with https://github.com/zeit/hyper/blob/6842e8500a40d4218bd19ad3286ef08db96f5512/package.json.

Sometimes there may be a network response failure, maybe CDN returns error and Yarn can't  unzip the .tgz file.

Maybe this could be mitigated with a retry or switching to npm cdn.

**Comment by bestander** [comment]
How often do you hit this?

**Comment by gsklee** [comment]
@bestander Not very often; guess I'll close it for now. BTW any idea on how do I retry upon failure?
