### ISSUE TITLE
how to install the Yarn dependent package into a custom directory but not into node_modules

### ISSUE THREAD

**Issue by CharlieKaufman** [yarnpkg/yarn#2751]
**Do you want to request a *feature* or report a *bug*?**

request a feature

**What is the current behavior?**

 I want to use Yarn in the project to replace bower, how to install the Yarn dependent package into a custom directory but not into node_modules , similar to `{
    "directory" : "src/lib"
}` of ".bowerrc"
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I can set some packages installed to the node_modules directory, some packages installed to a custom directory
**Please mention your node.js, yarn and operating system version.**
v0.20.3

**Comment by bestander** [comment]
Use `--modules-folder` flag
