### ISSUE TITLE
Scoped packages missing .bin scripts

### ISSUE THREAD

**Issue by chrisblossom** [yarnpkg/yarn#2758]
**What is the current behavior?**
Scoped packages do not place files into node_modules/.bin

Related issues/PRs: https://github.com/yarnpkg/yarn/issues/2004 https://github.com/yarnpkg/yarn/issues/1885 https://github.com/yarnpkg/yarn/pull/2163 https://github.com/yarnpkg/yarn/pull/2313 https://github.com/yarnpkg/yarn/issues/1487 https://github.com/yarnpkg/yarn/issues/2493 https://github.com/yarnpkg/yarn/issues/733 https://github.com/yarnpkg/yarn/issues/735

**If the current behavior is a bug, please provide the steps to reproduce.**

install a scoped npm module that has a dependency such as eslint and look at node_modules/.bin

Example repo:
[https://github.com/chrisblossom/yarn-scoped](https://github.com/chrisblossom/yarn-scoped)

**What is the expected behavior?**
Places all scoped package's dependency .bin files into node_modules/.bin

**Please mention your node.js, yarn and operating system version.**
node v6.9.5
yarn v0.20.3
osx v10.12.3

**Comment by bestander** [comment]
PR welcome

**Comment by mathieutu** [comment]
We can add theses PRs :
https://github.com/yarnpkg/yarn/pull/1210
https://github.com/yarnpkg/yarn/pull/2053

**Comment by Tapppi** [comment]
AFAIK this was actually the "no transitive dependency bin hoisting" bug and has nothing to do with scoped packages. That was fixed in #3310 back in may and it's working for me with v0.27.5 and scoped company packages. Can this be closed?

**Comment by chrisblossom** [comment]
@Tapppi yes it can. I just verified this has been fixed. Thanks for the reminder.
