### ISSUE TITLE
[enhancement] Include prereleases (-beta.1) in peerDep semver ranges

### ISSUE THREAD

**Issue by ide** [yarnpkg/yarn#2760]
**Do you want to request a *feature* or report a *bug*?**
This is a half-feature request, half-bug report.

**What is the current behavior?**
Currently yarn (and npm) does not include prerelease versions of packages to satisfy semver ranges, unless those ranges explicitly ask for a prerelease version. For example, `react@16.0.0-alpha.2` does not satisfy the range `react >= 15` even though 16-dot-anything is greater than 15.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install `react@16.0.0-alpha.2` and another package that has a peerDep on `react >= 15` (`react-helmet` for example). Run `yarn` which prints:
```
warning "react-helmet@4.0.0" has incorrect peer dependency "react@>=15.0.0".
```

**What is the expected behavior?**
With this requested enhancement, when doing peerDep checks, Yarn would consider `X.Y.Z-anything.N` to be a semver string that is greater than `X.Y.{Z-1}` and less than `X.Y.{Z+1}` (and `X.{Y+1}.0` and `{X+1}.0.0`). 

I believe this also addresses an issue that Facebook has been having internally between react and other packages that have a peerDep on react.

The `semver` package doesn't implement this behavior so we'd likely want to write a small module that does a more inclusive version check for peerDeps.

**Please mention your node.js, yarn and operating system version.**

Node 7.6.0
Yarn 0.21.2
macOS 10.12

**Comment by Daniel15** [comment]
> For example, react@16.0.0-alpha.2 does not satisfy the range react >= 15 even though 16-dot-anything is greater than 15.

Isn't this an intentional feature of semver? The [semver spec says](http://semver.org/#spec-item-9):

>  A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

"might not satisfy the intended compatibility requirements" implies that it should not match a version range that would otherwise be matched if it were not a prerelease.

**Comment by ide** [comment]
> "might not satisfy the intended compatibility requirements" implies that it should not match a version range that would otherwise be matched if it were not a prerelease.

This is saying that there may be breaking changes between 16.0.0-alpha and 16.0.0 ("its associated normal version") or breaking changes between 16.1.0-alpha and 16.1.0. However, 16.1.0-alpha is implied to be compatible with `^16.0.0`. It then follows that 16.0.0-alpha satisfies `>= 15.0.0` even if 16.0.0-alpha doesn't satisfy `16.0.0`.

**Comment by bestander** [comment]
Actually +1.
I think `16.0.0-alpha` satisfies `>= 15.0.0` even if semver package had [different opinion](https://github.com/npm/node-semver#prerelease-tags).

I came across a similar issue related to Yarn requirements: https://github.com/yarnpkg/yarn/issues/3029.

Maybe React and Yarn abuse (or use incorrectly) the semver spec but I don't think that semver explanation is intuitive for people.

@ide, would you have time to send a PR to fix that?

**Comment by ide** [comment]
I could try to work on this next weekend, I think it will really improve the feeling of using Yarn with React (and other libraries, but React notably is a common peer dep) for early adopters.
