### ISSUE TITLE
Yarn global is broken after upgrading from 0.20.3 to 0.21.2

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#2766]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I upgraded to yarn 0.21.2 by doing a `yarn global add yarn@0.21.2`
Now when I do `yarn global remove yarn` (for example), I get the following:
```
➜  frontend✗ yarn global remove yarn
/home/vnoel/.config/yarn/global/node_modules/yarn/bin/yarn.js:61
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/home/vnoel/.config/yarn/global/node_modules/bl/node_modules/readable-stream/duplex.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vnoel/.config/yarn/global/node_modules/bl/bl.js:1:82)
```

The same happen if I go to `/home/vnoel/.config/yarn/global/` and call any of the yarn commands.

**Comment by victornoel** [comment]
Note that removing `/home/vnoel/.config/yarn/global/node_modules/` and running yarn in `/home/vnoel/.config/yarn/global/` fixes the problem.

**Comment by simonkberg** [comment]
> I upgraded to yarn 0.21.2 by doing a `yarn global add yarn@0.21.2`

Afaik this is not a supported upgrade path. You should use one of the official installation methods for upgrades: https://yarnpkg.com/en/docs/install

Utilizing the `install.sh` script you can upgrade to the latest RC using:
```sh
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
```

**Comment by victornoel** [comment]
@simonkberg you are right, I didn't think of that… I will use the script in the future!

Still, it's strange that it doesn't work I think…

**Comment by bestander** [comment]
I think there should be warning about `yarn global add yarn` command.

I'll close for now because I don't see an action to do in this case.
