### ISSUE TITLE
yarn add gulpjs/gulp#4.0 ~ ERROR

### ISSUE THREAD

**Issue by TOP-Chao** [yarnpkg/yarn#2772]
error An unexpected error occurred: "https://raw.githubusercontent.com/gulpjs/gulp/3f5aba28718dc19e4bf600fb88f128158ff2ff83/package.json: connect ETIMEDOUT 151.101.100.133:443"

WTF?

**151.101.100.133:443** What is this server address?

**Comment by simonkberg** [comment]
151.101.100.133 is an address to the Fastly CDN network, which is used by npm. Sounds like you encountered a temporary connection issue. Can you still reproduce this error?
