### ISSUE TITLE
Problem with build production bundle in webpack@2

### ISSUE THREAD

**Issue by anagami** [yarnpkg/yarn#2783]
**Do you want to request a *feature* or report a *bug*?**
possible bug

**What is the current behavior?**
When build production bundle with webpack, result bundle.js contain 4 version same library(in my case - lodash)

**What is the expected behavior?**
If delete `node_modules` and all reinstall with `npm i` - problem resolved. In production build only one lodash

**Please mention your node.js, yarn and operating system version.**
webpack@2.2.1/yarn@0.20.3/nodejs@6.9.2/win10

**Comment by bestander** [comment]
Could you explain a bit more please?
How to reproduce the issue?

**Comment by moimikey** [comment]
@anagami i wouldn't necessarily consider this a `yarn` problem or even an `npm` problem for that matter; this is just the state of dealing with nested dependencies. Dependency A may use lodash@3 while Dependency B may use lodash@4, and you happen to pull in both Dependency A and B:

```
Dependency A/
  node_modules/
    lodash@3
DependencyB/
  node_modules/
    lodash@4
```

It may not even be this case, it might even be the same version of lodash. Once again, not a `yarn` or `npm` issue. This is simply the nature of Webpack. You would then benefit from `webpack.optimize.DedupePlugin()`

**Comment by anagami** [comment]
@moimikey you right - different major versions lodash.
i try `yarn install --flat` - in my case this install ask to many questions about which version install 
`webpack.optimize.DedupePlugin()` move inside wp2 and this call depricated
