### ISSUE TITLE
check verify-tree doesn't work with modules-folder

### ISSUE THREAD

**Issue by philtay** [yarnpkg/yarn#2784]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
The `verify-tree` option of the `check` command doesn't take into account the `modules-folder` general option.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ yarn install --modules-folder /my/dir
$ yarn check --verify-tree --modules-folder /my/dir
```

**What is the expected behavior?**
It should just work...

**Please mention your node.js, yarn and operating system version.**
Yarn v0.20.3 on Linux

**Comment by bestander** [comment]
Good point, PR is welcome
