### ISSUE TITLE
yarn publish gets stuck on publishing

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/yarn#2786]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `yarn publish` command gets stuck on the `[3/4] Publishing...` step.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone https://github.com/FezVrasta/popper.js
2. Run `yarn publish`
3. Notice it gets stuck on "publishing"

**What is the expected behavior?**
The publishing process should succeed or throw an error if something went wrong.

**Please mention your node.js, yarn and operating system version.**
```
Node  | v7.5.0
Yarn  | 0.20.3
macOS | 10.12.3
```

**Comment by thibmaek** [comment]
Yeah, same here>

**Comment by creynders** [comment]
Unfortunately `yarn publish --verbose` doesn't add a lot of info:

```
verbose Performing "PUT" request to "https://registry.yarnpkg.com/-/user/org.couchdb.user:creynders".
verbose Request "https://registry.yarnpkg.com/-/user/org.couchdb.user:creynders" finished with status code 201.
```

And then it's stuck

**Comment by creynders** [comment]
Upgraded to yarn v0.21.3, but unfortunately it makes no difference. I'm using the alternative way of installing yarn on mac os x, i.e.:
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```
Maybe it's relevant.

**Comment by lsamayoa** [comment]
Bump

**Comment by tomitrescak** [comment]
Same environment, same problem.

**Comment by mrichins** [comment]
Theres been some debugging done on this https://github.com/yarnpkg/yarn/issues/1694 But no-one has come up with a fix. It doesnt seem to be universal.
Getting the same issues with 0.24.5 and the nightly build.

**Comment by bestander** [comment]
This got fixed in 0.27 https://github.com/yarnpkg/yarn/pull/3646

**Comment by josiahruddell** [comment]
0.27 does fix the hanging issue, however the publish is throwing an exception. The publish appears to have succeeded while the client failed afterward.

```
verbose 13.386 Performing "PUT" request to "https://registry.yarnpkg.com/****".
verbose 13.988 Request "https://registry.yarnpkg.com/*****" finished with status code 200.
verbose 13.989 Error: Couldn't publish package.
    at MessageError (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:138:5)
    at /usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:77664:13
    at next (native)
    at step (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:91:30)
    at /usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:102:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Couldn't publish package.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

**Comment by BYK** [comment]
@josiahruddell can you file a new issue for that?

**Comment by bchoddny** [comment]
Yes, I get the same error as josiahruddell, but the publish have succeeded

**Comment by BYK** [comment]
@bchoddny as mentioned above, let's create a new issue to track the precise problem. That way we can also inform you easily once it's fixed.

**Comment by mrichins** [comment]
@bchoddny & @josiahruddell So this very well could have been with how I implemented checking response codes for different repositories 😢  Are you publishing to NPM or a private registry?

**Comment by josiahruddell** [comment]
Yep, private.

**Comment by bchoddny** [comment]
private registry

**Comment by bchoddny** [comment]
@mrichins, it's a private npm registry hosted in nexus3

**Comment by bchoddny** [comment]
@BYK, created a [bug](https://github.com/yarnpkg/yarn/issues/3939)
