### ISSUE TITLE
Installation Problem: AWS EC2 or Elastic Beanstalk

### ISSUE THREAD

**Issue by sealocal** [yarnpkg/yarn#2794]
**Which operating system are you using:**

Amazon Linux 2016.09 v2.3.1 running Ruby 2.3 (Puma)

**Please describe the steps you took when trying to install Yarn and what went wrong:**

This is not really a problem, but more of a feature request.

I'm attempting to go with the recommended installation methods and avoid installing with npm, so I used the yarn rpm repo.

I want to be able to install an older version of yarn to keep it in synch with local development. Is there a way to install a prior version of yarn, instead of the latest? Or is there a plan to support installing older versions of the rpm repo?

    sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo

**Comment by Daniel15** [comment]
I'm not very familiar with Yum, but see if this helps you: http://unix.stackexchange.com/a/151690

According to that post, you should be able to do something like `yum --showduplicates list yarn | expand` to see a list of available versions, and `sudo yum install yarn-<version>` to install a specific version. Let me know if that doesn't work!

**Comment by sealocal** [comment]
Yes, thank you!

I am also not familiar with Yum - it did not occur to me that all releases could be in the repo.

Limited info in `yarn.repo`:
```console
$ cat /etc/yum.repos.d/yarn.repo
[yarn]
name=Yarn Repository
baseurl=https://dl.yarnpkg.com/rpm/
enabled=1
gpgcheck=1
gpgkey=https://dl.yarnpkg.com/rpm/pubkey.gpg
```

Confirmed:
```console
$ yum --showduplicates list yarn| expand
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
yarn.noarch                           0.21.3-1                             @yarn
Available Packages
yarn.noarch                           0.15.0-1                             yarn 
yarn.noarch                           0.16.0-1                             yarn 
yarn.noarch                           0.16.1-1                             yarn 
yarn.noarch                           0.17.6-1                             yarn 
yarn.noarch                           0.17.8-1                             yarn 
yarn.noarch                           0.17.9-1                             yarn 
yarn.noarch                           0.17.10-1                            yarn 
yarn.noarch                           0.18.1-1                             yarn 
yarn.noarch                           0.19.1-1                             yarn 
yarn.noarch                           0.20.3-1                             yarn 
yarn.noarch                           0.21.3-1                             yarn
# If you have yarn already installed, it must be uninstalled/removed to install an older version
$ sudo yum remove yarn
[...]
$ sudo yum install yarn-0.19.1-1
[...]
```
