### ISSUE TITLE
Homebrew formulae outdated

### ISSUE THREAD

**Issue by Alxandr** [yarnpkg/yarn#2798]
Yarn gives warning that:

    warning Your current version of Yarn is out of date. The latest version is "0.21.3" while you're on "0.20.3".

yet, when I try to update it using homebrew this is the latest version available.

**Comment by Daniel15** [comment]
This needs to be sent to the Homebrew project using the `brew bump-formula-pr` command. Here's an example PR: https://github.com/Homebrew/homebrew-core/pull/9984

**Comment by Alxandr** [comment]
Regardless of how it has to be updated it's still an issue, so I feel closing this is rather premature.

**Comment by Daniel15** [comment]
#2841 tracks automatically updating Homebrew as part of the release process.
