### ISSUE TITLE
Race condition when creating GitHub releases

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2799]
The release scripts for Yarn create a new GitHub release.

 - The script that uploads Linux builds creates the GitHub release if it doesn't exist yet, and always creates it as a prerelease: https://github.com/yarnpkg/yarn/blob/408152960f75536ebad1d001e67fb365bbc0e644/circle.yml#L52
 - The script that uploads Windows builds also creates the GitHub release if it doesn't exist yet, and never creates it as a prerelease: https://github.com/yarnpkg/releases/blob/50076c6b81c698a065e5cc4d00d9ae76d02ece99/nightly/lib/GitHub.php#L35-L54

This results in a race condition like this:
 - If the Windows build finishes before the Linux build, the GitHub release **is not** marked as a prerelease
 - If the Linux build finishes before the Windows build, the GitHub release **is** marked as a prerelease

This is very confusing: Sometimes builds that are prereleases are marked as stable (eg. see https://github.com/Homebrew/homebrew-core/pull/10147), while other times stable releases are marked as prereleases (eg. see https://github.com/nodejs/docker-node/pull/337#discussion_r103314356).

The correct behaviour should be as follows:
 - If the new version number has the same minor version number as the current stable release (as per http://yarnpkg.com/latest-version), mark it as stable. 
 - Otherwise, mark it as prerelease

For example, if we're publishing 0.23.2 and the latest stable is 0.23.1, it should be marked as stable. On the other hand, if we're publishing 0.24.0 and the latest stable is 0.23.1, it should **not** be marked as stable.

To simplify things, I might also unify the Windows and Linux builds so they upload the build artifacts in the same way, and also automatically bump the version numbers on the site.

**Comment by petetnt** [comment]
I just ran into this myself (I think)? I installed some modules and saw a warning that `Your current version of Yarn is out of date. The latest version is "0.21.3" while you're on "0.20.3"`. Went to upgrade it with `brew`, but it wasn't available. Went to check the website and it said that latest version (https://yarnpkg.com/latest-version) is 0.21.3. Clicked the link on the front page that said `Stable: 0.21.3` and it said that it's a pre-release. Checked `package.json` and it was updated recently to `0.22.0-0`. 🤔

**Comment by Daniel15** [comment]
@petetnt  - That's not related, Homebrew is updated separately by the Homebrew community.

> Clicked the link on the front page that said Stable: 0.21.3 and it said that it's a pre-release.

This is related, the GitHub release sometimes incorrectly says it's a prerelease.

> Checked package.json and it was updated recently to 0.22.0-0. 🤔

This is the development version.

**Comment by petetnt** [comment]
@Daniel15 Yeah, the Homebrew part was more of back story (as was the `package.json` part) how this affected me as the enduser. The formula would have been trivial to update, but I just didn't have any clue what was the actual stable version.
