### ISSUE TITLE
Running Yarn engines in package.json are ignore

### ISSUE THREAD

**Issue by OmerHerera** [yarnpkg/yarn#2800]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`engines` in `package.json` are ignore at least for `node`

**If the current behavior is a bug, please provide the steps to reproduce.**

- Add to `package.json`

```
"engines": {
    "node": ">=6.0.0 <7.0.0"
  }
```

- Run `yarn` 

**What is the expected behavior?**
Yarn won't success installing dependencies if `node` version doesn't match criteria

**Please mention your node.js, yarn and operating system version.**

OS: `OS X El Capitan Version 10.11.6`
Node: `v4.4.7`
Yarn: `0.21.3`

**Comment by hpurmann** [comment]
The `engines` field get's only checked for dependencies of your package. So you can specify that your package runs on a range of node versions and other people installing your package will (hopefully) get a warning if they do so with a non-matching node version.

But it doesn't check the current node version against the `engines` field of your application's `package.json` when installing _its dependencies_. I was confused with this as well but that's exactly how `npm` does it.

[Found this blog post](http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html#using-the-engines-configurations)

So if we strive for compatibility with `npm`, then this is currently not a bug. I still think it would be nice if we also checked against our own `engines` field. Don't see why we wouldn't.

**Comment by OmerHerera** [comment]
Ok, now I understand, even this behaviour also in `npm` is a bit confusing.
I'll prefer that before trying to fetch new modules `yarn/npm` will check your installed node (`engines `) against your module and then try to fetch dependencies.

But I if we strive for compatibility with `npm`, this behaviors must stay.

I'll like to behave  like is done for `yarn` in `yarn.js` file that only `node` versions 4/5 are supported in [here](https://github.com/yarnpkg/yarn/blob/master/bin/yarn.js#L14)
Thanks

**Comment by kylemeier** [comment]
npm does now check the engines field for your application (and has since npm 4.4.1, possibly earlier). I'm able to get ```npm install``` to fail on an engine mismatch, but ```yarn install``` works. I'd consider this a bug if yarn is intended to be consistent with npm.

**Comment by gsklee** [comment]
Just checked again with `node` v8.1.1, `yarn` v0.24.6, `npm` v5.0.3:

For both package managers, the `engines` field only concerns itself with dependencies of your module, not your module.

@bestander close; non-issue

**Comment by bennycode** [comment]
@gsklee yarn v1 respects the "engines" field and doesn't execute "yarn install" when your local yarn version doesn't match the version in the "engines" field:

![image](https://user-images.githubusercontent.com/469989/200347033-eaf01906-9406-4a34-bff2-5ea9b41f3e93.png)

However, it seems like yarn v3 doesn't respect this "engines" value which seems to be an issue?

**Comment by jeremy-daley-kr** [comment]
@bestander Sorry, but can you give some detail on why this was closed without any explanation? There's no linked PR, or anything that I can trace back to a reason.
