### ISSUE TITLE
yarn add @next adds "next" as version number

### ISSUE THREAD

**Issue by mschipperheyn** [yarnpkg/yarn#2802]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When you install 
yarn add package@next

package.json
"package": "next",

**What is the expected behavior?**
package.json
"package": "^0.0.2-beta4",

**Please mention your node.js, yarn and operating system version.**
node 6.1.0, yarn 0.21.3, mac osx

**Comment by TimvdLippe** [comment]
This is related to #2582 and a similar issue was fixed in #2471

**Comment by bestander** [comment]
duplicate https://github.com/yarnpkg/yarn/issues/2466
