### ISSUE TITLE
Yarn - typedoc theme assets folder is missing

### ISSUE THREAD

**Issue by sternbel** [yarnpkg/yarn#2803]
operating system: OSX El Capitan 10.11.6
node.js: 6.5.0
yarn version: 0.20.3
typescript: 2.1.6
typedoc: 0.5.7

**I want to report a *bug***

The following works fine with npm and doesn't with yarn.

**What is the current behavior?**

When running yarn install with the following package.json dep (Typedoc latest), assets folder is missing in typedoc-default-themes.

*package.json*
```json
{
  "name": "a",
  "version": "1.0.0",
  "main": "./dist/a.js",
  "types": "./type/a/index.d.ts",
  "devDependencies": {
    "ava": "latest",
    "del-cli": "latest",
    "nyc": "latest",
    "opn-cli": "latest",
    "ts-loader": "latest",
    "typedoc": "^0.5.5",
    "typescript": "latest",
    "webpack": "latest"
  },
  "ava": {
    "files": [
      "dist/test/**/*.spec.js"
    ],
    "source": [
      "src/**/*"
    ]
  },
  "scripts": {
    "clean": "del coverage dist",
    "prebuild": "yarn clean",
    "build": "webpack --config webpack.config.js --progress --display-error-details",
    "build:tsc": "tsc -p tsconfig.json",
    "unit": "yarn run build:tsc && nyc ava",
    "coverage": "yarn run build:tsc && ",
    "docs": "typedoc src/index.ts --excludePrivate --mode file --theme default --out dist/docs && opn dist/docs/index.html"
  }
}
```

**What is the expected behavior?**

./node_modules/typedoc-default-themes/bin/{default,minimal}/assets should be there but is not.

**Comment by sternbel** [comment]
Strange enough `yarn cache clean` and `yarn install` worked...

**Comment by revant** [comment]
`.yarnclean` has following

```
# asset directories
docs
doc
website
images
assets
```
assets got cleaned because of this.

managing `.yarnclean` file solves the problem.
