### ISSUE TITLE
`yarn install` not populating node_modules with downloaded packages.

### ISSUE THREAD

**Issue by spongessuck** [yarnpkg/yarn#2804]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

`yarn install` isn't copying downloaded packages to `node_modules`. It works properly with the `--force` flag (but then has to re-download all dependencies).

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn install` on a project without a `node_modules` folder.

**What is the expected behavior?**

Yarn should populate `node_modules` with dependencies.

**Please mention your node.js, yarn and operating system version.**

Node: 6.10.0
Yarn: 0.21.3
OS: Mac OS X El Capitan

**Comment by arcanis** [comment]
Hi, and thanks for your interest! We need a repro script to help us track down the issue. Please reopen this issue once you have a reproductible testcase.
