### ISSUE TITLE
Store the file size and hash in yarn.lock

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#2805]
A follow up to https://github.com/yarnpkg/yarn/issues/816

Current SHA1 collisions can be mitigated by including the file size of the tar.gz in the yarn.lock and checking both the hash and the file size.

**Comment by Daniel15** [comment]
I think internally at Facebook we have a task to upgrade Yarn to SHA256, which would solve the issue of collisions. @bestander Do you know the status of that?

**Comment by bestander** [comment]
Yeah, it would be easier to implement another sha.
PR is welcome, our workload is high right now.
Probably that would be a breaking change and we would need to bump yarn.lock version

**Comment by graingert** [comment]
@bestander ok, can you close this and re-open https://github.com/yarnpkg/yarn/issues/816
