### ISSUE TITLE
NPM refusing to install yarn globally

### ISSUE THREAD

**Issue by dylanrhysscott** [yarnpkg/yarn#2816]
**Do you want to request a *feature* or report a *bug*?**
Bug Report

**What is the current behavior?**

When trying to install the latest version of YARN via NPM with the global flag the install fails with the error:

```
npm ERR! Refusing to delete /usr/local/bin/yarn: node_modules/npm/bin/npm-cli.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Move it away, and try again.
```

I can install yarn locally without the global flag

**If the current behavior is a bug, please provide the steps to reproduce.**

* Run `npm i -g yarn`

**What is the expected behavior?**

YARN should install globally

**Please mention your node.js, yarn and operating system version.**

I am using Docker on MacOSX with the official node image found here [https://hub.docker.com/_/node/](https://hub.docker.com/_/node/)

NPM: 4.1.2
Node: 7.7.0
YARN: 0.21.3

I appreciate this maybe the domain of NPM / Node but I haven't encountered any issues installing other packages globally.

Thanks

**Comment by dylanrhysscott** [comment]
Here is the full log file

[npm-debug.log.txt](https://github.com/yarnpkg/yarn/files/811963/npm-debug.log.txt)

**Comment by devinus** [comment]
This just started happening to us as well today.

**Comment by dylanrhysscott** [comment]
@devinus Hi @bestander just read through #2744 and saw your comment to ping you in related issues. Could this be a unintended result of the changes made in the latest release? Looking at the error its related to symlinks and I know the above issue made some changes there.

**Comment by devinus** [comment]
What's weird is I was using yarn 0.21.3 just earlier last night perfectly fine. Something changed within the past ~6 hours it seems.

**Comment by bestander** [comment]
Can you install earlier versions of yarn?
Did npm get updated?

**Comment by fishead** [comment]
@dylanrhysscott I found why: the latest docker image already has yarn installed globally.

**Comment by Daniel15** [comment]
The Docker image already has Yarn installed globally. If you want to install your own version, please use the Debian or Alpine Linux package rather than npm, as that will work properly.

**Comment by dylanrhysscott** [comment]
@fishead @Daniel15 Thanks for letting me know about this - I have a question though if yarn is already installed shouldn't NPM either do nothing / upgrade if there is a version available? Thats what happens with other NPM packages why not YARN?

**Comment by Daniel15** [comment]
It's not installed via npm. The Node.js Docker images install Yarn by using the standalone .js file we provide.

**Comment by dylanrhysscott** [comment]
@Daniel15 OK so if the install is done outside of NPM then NPM can't manage it. Is that standard behaviour with all npm packages or something yarn specific?

**Comment by Daniel15** [comment]
Not standard with all npm packages, but pretty common for system-wide apps. Most of the time, you'll want to manage system-wide apps using a native package manager, particularly on Linux (like apt-get on Debian/Ubuntu or yum on CentOS) rather than npm. Some of the rationale for not using npm to install Yarn is documented on https://yarnpkg.com/en/docs/install#alternatives-tab:
> Note: Installation via npm is generally not recommended. npm is non-deterministic, packages are not signed, and npm does not perform any integrity checks other than a basic SHA1 hash, which is a security risk when installing system-wide apps.
> 
> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

**Comment by dylanrhysscott** [comment]
@Daniel15 Thanks for the info that clears everything up! 👍

**Comment by phun-ky** [comment]
@fishead @Daniel15 is this also for node6-slim images? We've encountered the same issue (yarn refuses to be installed) on that image.

**Comment by gvisniuc** [comment]
In case you need to force the installation of the new version you can:
- Delete the symlink target `rm /usr/local/bin/yarn`
- Run `npm install -g yarn`

**Comment by sourabh-kejriwal** [comment]
> In case you need to force the installation of the newest version you can:
> 
> * Delete the symlink target `rm /usr/local/bin/yarn`
> * Run `npm install -g yarn`

Also remove this: `rm /usr/local/bin/yarn`

**Comment by wupmemo** [comment]
Thank you all .. that was really helpful and solved an issue i have been facing for more than 6 hours. AWESOME folks really.

**Comment by humbertosms** [comment]
or use forced
`sudo npm --force  install -g yarn`

**Comment by alextrastero** [comment]
> or use forced `sudo npm --force install -g yarn`

I like to own the global node_modules folder instead of having to write `sudo`:
```
$ npm config get prefix
/usr
$ sudo chown -R $USER /usr/lib/node_modules
```

**Comment by Toufiq2018331084** [comment]
> or use forced `sudo npm --force install -g yarn`

after trying out a lot of different things, all i needed was a little force. hey, could this have any negative effects? why dont use force for all our problems. sorry if the question is stupid. new to this.
