### ISSUE TITLE
'yarn install --production' does not install transitive dependencies if listed as devDependencies in the project

### ISSUE THREAD

**Issue by scinos** [yarnpkg/yarn#2819]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**

In a project A with a dependency on B and B having a dependency on C, `yarn install --production` wont install C if C is listed as a devDependency of A. `npm` does.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.  Create a project with:

```
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "sequelize-cli": "^2.5.1"
  },
  "devDependencies": {
    "gulp": "^3.9.1"
  }
}
```

(note that `sequelize-cli` has a dependency on `gulp`:

```
{
  "dependencies": {
    "gulp": "^3.9.1",
  }
}
```

2. Run `yarn install --production`

3. Try to find `gulp`: `ls node_modules/gulp` returns nothing.

However, if the package is

```
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "sequelize-cli": "^2.5.1"
  }
}
```

`yarn install --production` will install `gulp`

**What is the expected behavior?**

Transitives production dependencies are always installed, even if the project declares them as devDependencies.

**Please mention your node.js, yarn and operating system version.**

* node 7.3.0
* yarn 0.21.3
* OSX 10.12.3 (Sierra)

**Comment by SimenB** [comment]
Is #761 back again?

**Comment by razor-x** [comment]
Just hit this with yarn 0.21.3. I have a logger package (B) that depends on bunyan (C), but bunyan is a devDependency of the main package (A).

**Comment by mapsam** [comment]
Also running 0.21.3 and hitting the same issue as @razor-x

**Comment by patrickd-** [comment]
Same issue here, this just screwed a production build, not good.

**Comment by dgaubert** [comment]
Same here using `--production`: main package (A) requires `redis-mpool` (B) which has `redis` (C) as dependency and main package (A) also defines `redis` (C) as `devDependency`.

**Comment by Jolg42** [comment]
Same here 😖  with latest 0.21.3 installing a lot of devDependecies...

**Comment by SimenB** [comment]
Does `yarn check --verify-tree` report errors?

**Comment by mapsam** [comment]
@SimenB indeed it does:

**Comment by SimenB** [comment]
This is still present in yarn 0.22.0.

Quick one-liner based on OP: `yarn init -y && yarn add sequelize-cli && yarn add gulp --dev && yarn --prod && yarn check --verify-tree --prod` still gives 
```
yarn check v0.22.0
error "sequelize-cli#gulp" not installed
error Found 1 errors.
```

@bestander Could you please check this? There's also an open PR for this, I haven't tested it though #2921

The fact that I can't trust `--prod` erodes my trust in yarn, which is a shame, cuz it's really awesome in so many ways. For now we still install dev dependencies to production to avoid this, which bloats up the package, and slows down the install into a docker container

**Comment by bestander** [comment]
Yeah, looks like the bug is present there.
`warning Integrity check: Patterns don't match` means that quick integrity check does not pass and install should proceed.

I'll investigate now.

**Comment by bestander** [comment]
Apparently the logic here is incorrect https://github.com/yarnpkg/yarn/blob/master/src/package-hoister.js#L147 and does not factor top level devDependencies.
Anyone wants to dig deeper and send a PR?

**Comment by blexrob** [comment]
@bestander - already did that, see #2921

**Comment by bestander** [comment]
Awesome, thanks, @blexrob, sorry for missing this.

**Comment by ecbrodie** [comment]
Just a comment from my point of view, regarding this warning message (as a response to @bestander's comment):

> warning Integrity check: Patterns don't match

When I see this after running a `yarn install` command, I begin to worry that there is either a yarn bug or an issue with one of our yarn files (such as `yarn.lock`). But rather, hearing that this message signifies a normal use case for yarn (in this case, I am running `yarn install` because I have not yet installed packages due to a recent `yarn.lock` or `package.json` change) is a little confusing. I would expect to receive silent output or non-warning output in the case of an expected use case.

If there is a better medium to provide this feedback (new Github issue?), then please let me know.

**Comment by SimenB** [comment]
@ecbrodie That's fixed in #3248

**Comment by ecbrodie** [comment]
@SimenB excellent, thanks for letting me know. Which yarn version will this be released in?

**Comment by SimenB** [comment]
No idea 😄

**Comment by bestander** [comment]
It is in master branch right now
<img width="1127" alt="screen shot 2017-05-02 at 5 01 37 pm" src="https://cloud.githubusercontent.com/assets/2121048/25626957/0ded0002-2f59-11e7-9f2d-f69b4c5d2f66.png">

So will be released in next branch cut, i.e. 0.24 this Thursday

**Comment by artlogic** [comment]
I just experienced this issue again using v0.24.5. Has there been a regression?

**Comment by bestander** [comment]
Please open a new issue with repro steps
