### ISSUE TITLE
Couldn't find a package.json file in <dependency>

### ISSUE THREAD

**Issue by phiresky** [yarnpkg/yarn#2824]
In an empty directory:

**What is the current behavior?**

```
$ yarn add binarykvparser
yarn add v0.21.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error Couldn't find a package.json file in "/tmp/15.51.10/node_modules/binarykvparser/node_modules/long"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

It works, just like

`npm install binarykvparser`

**Please mention your node.js, yarn and operating system version.**

```
yarn --version
0.21.3
node --version
v7.6.0
uname -a
Linux 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
```

This might have something to do with the bundled dependency behaviour because binarykvparser defines `long` as a bundledDependency: https://github.com/DoctorMcKay/node-binarykvparser/blob/master/package.json#L9

**Comment by luislobo** [comment]
Same issue with sqlite3: 

```bash
$ yarn add sqlite3                                                                                                                                                                                                                                                                                       
yarn add v0.21.3
info No lockfile found.
[1/4] Resolving packages...
warning waterline-sqlite3 > knex > liftoff > findup-sync > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
[3/4] Linking dependencies...
error Couldn't find a package.json file in "/home/lobo/dev/petrocloud/nodify/nodify/node_modules/waterline-sqlite3/node_modules/sqlite3/node_modules/node-pre-gyp"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

**Comment by arcanis** [comment]
Both of these packages seem to work fine now. Please reopen if you still have an issue.

**Comment by luislobo** [comment]
Yeah, fixed!

**Comment by YUzhva** [comment]
Got the same issue in v0.24.6 

```bash
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error Couldn't find a package.json file in "/Users/USER_NAME/PROJECT_NAME/node_modules/npm/node_modules/normalize-package-data"
```
¯\_(ツ)_/¯

**Comment by TimonLukas** [comment]
I have this exact same problem with the package `pdf-text` - installing it with npm works correctly, interacting with ANYTHING at all after having that installed will fail horribly:

    λ yarn remove pdf2json
    yarn remove v0.24.6
    [1/2] Removing module pdf2json...
    [2/2] Regenerating lockfile and installing missing dependencies...
    warning There appears to be trouble with your network connection. Retrying...
    error Couldn't find a package.json file in "C:\\Users\\USER\\WebstormProjects\\PROJECT\\node_modules\\pdf3json\\node_modules\\xmldom"
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.`

**Comment by BYK** [comment]
@TimonLukas looks like your `yarn` version is a bit old. Would you mind trying with a newer version?

**Comment by TimonLukas** [comment]
I just tried by upgrading, but it still persists :/

    λ yarn
    yarn install v0.27.5
    info No lockfile found.
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    error Couldn't find a package.json file in "C:\\Users\\TimonLukas\\WebstormProjects\\munich-center-lunch-menus\\node_modules\\pdf3json\\node_modules\\xmldom"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by BYK** [comment]
Well it now prints the following on latest master:
```
warning "pdf3json@0.2.0" is missing a bundled dependency "xmldom". This should be reported to the package maintainer.
```

So, please report to `pdf3json` maintainers. That said `yarn` won't fail for this if you use the latest nightlies thanks to #4046.
