### ISSUE TITLE
YARN Unable to install hapi-level while NPM does it without any problems

### ISSUE THREAD

**Issue by panbhatt** [yarnpkg/yarn#2827]
YARN is unable to build hapi-level on windows 7 with node 6.9.1 , NPM (3.10.8), YARN (0.19.1). 
Here are the logs, are we doing something wrong here. 

C:\Learn\HapiTutorials
> yarn add hapi-level --save
yarn add v0.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠠ leveldown: not ok
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
error C:\Learn\HapiTutorials\node_modules\leveldown: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c prebuild-install || node-gyp rebuild
Directory: C:\Learn\HapiTutorials\node_modules\leveldown
Output:
prebuild-install info begin Prebuild-install version 2.1.1
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Redirection\pbhatt3\AppData\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install WARN install self signed certificate in certificate chain

@ C:\Learn\HapiTutorials\node_modules\leveldown
> if not defined npm_config_node_gyp (node "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.1 | win32 | x64
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Users\\Redirection\\pbhatt3\\AppData\\nvm\\v6.9.1\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\Learn\\HapiTutorials\\node_modules\\leveldown\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Redirection\\pbhatt3\\AppData\\nvm\\v6.9.1\\node_modules\\yarn\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\pbhatt3\\.node-gyp\\6.9.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\pbhatt3\\.node-gyp\\6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Redirection\\pbhatt3\\AppData\\nvm\\v6.9.1\\node_modules\\yarn\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\Learn\\HapiTutorials\\node_modules\\leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\Learn\\HapiTutorials\\node_modules\\leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2778, in Load
    variables, includes, depth, check, True)
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 420, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1217, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1228, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Redirection\pbhatt3\AppData\nvm\v6.9.1\node_modules\yarn\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Redirection\\pbhatt3\\AppData\\nvm\\v6.9.1\\node_modules\\yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Learn\HapiTutorials\node_modules\leveldown
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

 C:\Learn\HapiTutorials
> npm install hapi-level --save

> leveldown@1.6.0 install C:\Learn\HapiTutorials\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.1
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Redirection\pbhatt3\AppData\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\Redirection\pbhatt3\AppData\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v48-win32-x64.tar.gz.8552-393cc8c425ef7.tmp
prebuild-install info renaming to @ C:\Users\Redirection\pbhatt3\AppData\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\Redirection\pbhatt3\AppData\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v48-win32-x64.tar.gz

prebuild-install info unpack resolved to C:\Learn\HapiTutorials\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\Learn\HapiTutorials\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Prebuild successfully installed!
- readable-stream@1.0.34 node_modules\bl\node_modules\readable-stream
- xtend@3.0.0 node_modules\deferred-leveldown\node_modules\xtend
- abstract-leveldown@0.12.4 node_modules\deferred-leveldown\node_modules\abstract-leveldown
- abstract-leveldown@2.4.1 node_modules\level-packager\node_modules\abstract-leveldown
- deferred-leveldown@1.2.1 node_modules\level-packager\node_modules\deferred-leveldown
- prr@1.0.1 node_modules\level-packager\node_modules\prr
- levelup@1.3.5 node_modules\level-packager\node_modules\levelup
- readable-stream@1.0.34 node_modules\levelup\node_modules\readable-stream
- xtend@3.0.0 node_modules\levelup\node_modules\xtend
- bl@1.2.0 node_modules\tar-stream\node_modules\bl
- end-of-stream@1.1.0 node_modules\tar-stream\node_modules\end-of-stream
hapi@0.0.1 C:\Learn\HapiTutorials
`-- hapi-level@5.0.1
  +-- level@1.6.0
  | +-- level-packager@1.2.1
  | | `-- levelup@1.3.5
  | |   +-- deferred-leveldown@1.2.1
  | |   | `-- abstract-leveldown@2.4.1
  | |   +-- level-codec@6.1.0
  | |   +-- level-errors@1.0.4
  | |   +-- level-iterator-stream@1.3.1
  | |   | `-- readable-stream@1.1.14
  | |   `-- prr@1.0.1
  | `-- leveldown@1.6.0
  |   +-- abstract-leveldown@2.6.1
  |   +-- bindings@1.2.1
  |   +-- fast-future@1.0.2
  |   +-- nan@2.5.1
  |   `-- prebuild-install@2.1.1
  |     +-- expand-template@1.0.3
  |     +-- github-from-package@0.0.0
  |     +-- minimist@1.2.0
  |     +-- node-abi@2.0.0
  |     +-- noop-logger@0.1.1
  |     +-- npmlog@4.0.2
  |     | +-- are-we-there-yet@1.1.2
  |     | | `-- delegates@1.0.0
  |     | +-- console-control-strings@1.1.0
  |     | +-- gauge@2.7.3
  |     | | +-- aproba@1.1.1
  |     | | +-- has-unicode@2.0.1
  |     | | +-- object-assign@4.1.1
  |     | | +-- signal-exit@3.0.2
  |     | | +-- string-width@1.0.2
  |     | | | +-- code-point-at@1.1.0
  |     | | | +-- is-fullwidth-code-point@1.0.0
  |     | | | | `-- number-is-nan@1.0.1
  |     | | | `-- strip-ansi@3.0.1
  |     | | |   `-- ansi-regex@2.1.1
  |     | | +-- strip-ansi@3.0.1
  |     | | | `-- ansi-regex@2.1.1
  |     | | `-- wide-align@1.1.0
  |     | `-- set-blocking@2.0.0
  |     +-- os-homedir@1.0.2
  |     +-- rc@1.1.7
  |     | +-- deep-extend@0.4.1
  |     | +-- ini@1.3.4
  |     | +-- minimist@1.2.0
  |     | `-- strip-json-comments@2.0.1
  |     +-- simple-get@1.4.3
  |     | `-- unzip-response@1.0.2
  |     +-- tar-fs@1.15.1
  |     | +-- chownr@1.0.1
  |     | +-- mkdirp@0.5.1
  |     | | `-- minimist@0.0.8
  |     | `-- tar-stream@1.5.2
  |     |   `-- bl@1.2.0
  |     `-- tunnel-agent@0.4.3
  `-- level-sublevel@6.6.1
    +-- bytewise@1.1.0
    | +-- bytewise-core@1.2.3
    | | `-- typewise-core@1.2.0
    | `-- typewise@1.0.3
    +-- levelup@0.19.1
    | +-- bl@0.8.2
    | +-- deferred-leveldown@0.2.0
    | | `-- abstract-leveldown@0.12.4
    | |   `-- xtend@3.0.0
    | +-- errno@0.1.4
    | | `-- prr@0.0.0
    | +-- prr@0.0.0
    | +-- readable-stream@1.0.34
    | | `-- isarray@0.0.1
    | +-- semver@5.1.1
    | `-- xtend@3.0.0
    +-- ltgt@2.1.3
    +-- pull-level@2.0.3
    | +-- level-post@1.0.5
    | +-- pull-cat@1.1.11
    | +-- pull-live@1.0.1
    | +-- pull-pushable@2.0.1
    | +-- pull-window@2.1.4
    | | `-- looper@2.0.0
    | `-- stream-to-pull-stream@1.7.2
    |   `-- looper@3.0.0
    +-- pull-stream@3.5.0
    +-- typewiselite@1.0.0
    `-- xtend@4.0.1

**Comment by arcanis** [comment]
Can you check again on newer releases, and reopen this issue if it still happens?
