### ISSUE TITLE
Yarn add fails because unrelated module is incompatible

### ISSUE THREAD

**Issue by daspr2** [yarnpkg/yarn#2833]
**Do you want to request a *feature* or report a *bug*?**

Bug, (but maybe a misundertanding on my side)

**What is the current behavior?**
The bug is happening when I try to add a new package. There is a module that is incompatible with the platform and it halts the installation. The thing is, the complaining package is totally unrelated to the module I'm trying to add, or any of my existing packages (I think). Furthermore, when I do a `yarn why` with the faulty package, it returns that it found nothing.

When I install my wanted package with npm and then run yarn, there is no error.

**If the current behavior is a bug, please provide the steps to reproduce.**
In this example, the faulty package is `inotify`
```
yarn add dev mochawesome
yarn add v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
error inotify@1.4.1: The platform "win32" is incompatible with this module.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

PS C:\project\> yarn why inotify
yarn why v0.21.3
[1/4] Why do we have the module "inotify"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 0.36s.
```

Here is the output when I install the package with npm and then run yarn
```
npm install --save-dev mochawesome
project@ C:\project\
`-- mochawesome@2.0.4
  +-- fs-extra@2.0.0
  | `-- jsonfile@2.4.0
  +-- mochawesome-report-generator@1.1.0
  | +-- opener@1.4.3
  | +-- react@15.4.2
  | | +-- fbjs@0.8.9
  | | | +-- core-js@1.2.7
  | | | +-- isomorphic-fetch@2.2.1
  | | | | +-- node-fetch@1.6.3
  | | | | | `-- encoding@0.1.12
  | | | | |   `-- iconv-lite@0.4.15
  | | | | `-- whatwg-fetch@2.0.3
  | | | +-- promise@7.1.1
  | | | | `-- asap@2.0.5
  | | | `-- ua-parser-js@0.7.12
  | | `-- loose-envify@1.3.1
  | `-- react-dom@15.4.2
  `-- uuid@3.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

yarn
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 11.33s.
```

**What is the expected behavior?**
Run `yarn add dev mochawesome` successfully

**Please mention your node.js, yarn and operating system version.**
node v6.9.1
yarn v0.21.3
windows 10, x64

**Comment by glebec** [comment]
Interesting — if you do `yarn add mochawesome` (not `--dev`) it also works. Only fails when adding to dev dependencies. Also, it fails on OS X with `error inotify@1.4.1: The platform "darwin" is incompatible with this module.` I cannot say much more as I am not trying to work on this myself, just happened to read this issue looking for info on an unrelated problem.

**Comment by shahankit** [comment]
Any workaround for this error?

**Comment by soutar** [comment]
It looks like you are running `yarn add dev mochawesome` instead of `yarn add --dev mochawesome`

[dev](https://www.npmjs.com/package/dev) is a package which depends on [inotify](https://www.npmjs.com/package/inotify), and inotify's only support Linux [according to its package.json](https://github.com/c4milo/node-inotify/blob/master/package.json#L19-L21)

**Comment by shahankit** [comment]
Ohh yeah @soutar thanks that solved the issue.

**Comment by soutar** [comment]
No problem @shahankit, this got me earlier today too :man_facepalming:

**Comment by glebec** [comment]
But @soutar and co., when I run `yarn add dev mochawesome` I get the following `package.json` and no error (!) now:

```json
{
  "name": "churn",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "mochawesome": "^2.0.4"
  }
}
```

It looks like maybe the current version of yarn tries to save people from the mistake of not using the proper `--dev` flag?

**Comment by soutar** [comment]
@glebec Interesting. What version of yarn do you have?

**Comment by glebec** [comment]
Ah! I realize the issue, I'm on a different computer. X-D

This computer had Yarn 0.17.0. Upgrading to current (0.21.3) causes the error. So it looks like Yarn _used to_ support `dev` as an alias for `--dev` but removed it later.

Case closed, issue can be closed too IMHO.

**Comment by daspr2** [comment]
Yeah thanks everyone for the clarification. Closing.

**Comment by zwhitchcox** [comment]
I moved every package to devDependencies, and I'm still getting this error.

**Comment by kevindavus** [comment]
*This problem is a user error. Don't run `yarn add dev <package>` run `yarn add --dev <package>`*

**Comment by ejoo** [comment]
I am still getting that error. I'm installing for first time on Windows 10.

**Comment by ejoo** [comment]
![image](https://user-images.githubusercontent.com/8073885/52533547-fc02f380-2d56-11e9-9b9f-ee7daf53657c.png)


I'm still getting that error. Installing for the first time on Windows 10.

**Comment by kajmagnus** [comment]
@ejoo Me too, and  ... seems the problem was that I invoked Yarn from different operatign systems (Alpine in Docker, + Ubuntu = my host OS), using the same file directory.  Then fsevents apparently got built, for a different OS. Hereafter I'll use the same OS always.

**details**

I never added `dev`, instead, now for you and me, it's `fsevents`, right. And, looking at `yarn.lock`, the `chokidar ` depends on `fsevents`:

```
chokidar@^2.0.0:
  version "2.1.1"
  resolved "https://registry.yarnpkg.com/chokidar/-/chokidar-2.1.1.tgz#adc39ad55a2adf26548bd2afa048f611091f9184"
  dependencies:
    anymatch "^2.0.0"
    async-each "^1.0.1"
    braces "^2.3.2"
    glob-parent "^3.1.0"
    inherits "^2.0.3"
    is-binary-path "^1.0.0"
    is-glob "^4.0.0"
    normalize-path "^3.0.0"
    path-is-absolute "^1.0.0"
    readdirp "^2.2.1"
    upath "^1.1.0"
  optionalDependencies:
    fsevents "^1.2.7"
```

which is ... what? not compatible with "win32" in your case and not "linux" in my case  o. O

Here's my build output:

```
Attaching to tyd_gulp_1
[3/6] Fetching packages...
[] 0/736(node:10) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.     <———— look
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 5.92s.
```

and after this,  the Gulp `watch` task won't work.  I was working yesterday, before I upgraded.  Anyway, maybe this isn't really Yarn's fault?  I'm thinking it's `fsevents`?

... Turns out that I've been running Yarn both directly on my Ubuntu 16.04, and also in a Docker container with Alpine linux, and I suspect Yarn then built `fsnotify` for my Ubuntu OS, which then wasn't compatible with Alpine Linux.

I now deleted `node_modules` and reinstalled — problem gone.  And hereafter I'll run Yarn in the same way always, ... no more from different OS:es that use the same file system.

/ End details.

**Comment by grabowskidaniel** [comment]
> It looks like you are running `yarn add dev mochawesome` instead of `yarn add --dev mochawesome`
> 
> [dev](https://www.npmjs.com/package/dev) is a package which depends on [inotify](https://www.npmjs.com/package/inotify), and inotify only supports Linux [according to its package.json](https://github.com/c4milo/node-inotify/blob/master/package.json#L19-L21)

This worked for me, thank you so much!

**Comment by huypvw** [comment]
It still error @@
