### ISSUE TITLE
Add updating brew as part of the release process

### ISSUE THREAD

**Issue by SimenB** [yarnpkg/yarn#2841]
(the template doesn't really apply, and rfc seems way overkill. I can do it if you really want one).

I would really appreciate it if a PR to the brew repo was included as part of the release process for stable versions.

It's very easy, just run a single command, and submit the PR. https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#submit-a-version-upgrade-for-the-foo-formula. It'll come out like this: https://github.com/Homebrew/homebrew-core/pull/10432

**Comment by Daniel15** [comment]
Can that command run on Linux? We can add this to our release process as long as it can be done on Linux or Windows.

**Comment by SimenB** [comment]
In theory you should be able to install the Linux fork. I haven't tried it, but hopefully the PR opens against the original homebrew, and not the fork.

https://github.com/Linuxbrew/brew

**Comment by SimenB** [comment]
@Daniel15 I tried, and it _might_ work, but I hit a snag when testing: Linuxbrew/brew#291

One option is to just update the file in the brew repo without the command, all it does is replace the URL, sha, and run the test. Tests are run on CI, so it should be enough to replace the url & sha, then submit the PR 😄

**Comment by Daniel15** [comment]
> One option is to just update the file in the brew repo without the command, all it does is replace the URL, sha, and run the test. Tests are run on CI, so it should be enough to replace the url & sha, then submit the PR 😄

That sounds reasonable! It looks like GitHub's "hub" utility (https://hub.github.com/) supports sending pull requests, see https://github.com/github/hub/issues/1219 for example. We could have a shell script that clones the repo, does the change, pushes it to a fork, then submits a pull request. I can then set up the shell script to automatically run whenever there's a new release 😃

**Comment by Daniel15** [comment]
If you want an example of something similar, you could see how we build the Chocolatey package using a PowerShell script: https://github.com/yarnpkg/yarn/blob/master/scripts/build-chocolatey.ps1

Basically what it does is:
1. Check if Chocolatey is already up-to-date - If it is, exit
2. Download the Windows installer
3. Get a SHA256 hash of the installer, and update a template to include the download URL and hash
4. Build the package
5. Submit it to the Chocolatey repo

A script for Homebrew would be very similar, except cloning their Git repo and performing the change there. Do they have an API we could call to check whether Yarn is already up-to-date in Homebrew?

**Comment by SimenB** [comment]
Sounds perfect!

If I run `brew info yarn`, I get `yarn: stable 0.21.3 (bottled), HEAD` in there, could extract it?

Full output from my docker image from the linuxbrew issue:

```sh-session
$ brew info yarn
/home/newuser/.linuxbrew/Library/Homebrew/brew.sh: line 48: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
yarn: stable 0.21.3 (bottled), HEAD
Javascript package manager
https://yarnpkg.com/
Not installed
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/yarn.rb
==> Dependencies
Required: node ✘
```

**Comment by SimenB** [comment]
If I have yarn installed, this is cleaner:

```sh-session
$ brew list --versions yarn
yarn 0.21.3
```

But that doesn't work if yarn is not installed, so might not help.

**Comment by Daniel15** [comment]
Good catch! Looks like we could just grep `yarn.rb` for the version number.

It sounds like we could have a script that does something like this:
1. Get latest Yarn version from `https://yarnpkg.com/latest-version`
2. Extract latest Yarn version on Homebrew from `https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/yarn.rb`
3. If version numbers are equal, exit the script (so we don't bother updating a clone of Homebrew if the version is already up-to-date)
4. Clone Homebrew repo into a temp directory
5. Update URL and hash in `yarn.rb`
6. Commit the change
7. Push it to a remote somewhere (owned by the user running the script)
8. Send a pull request

Would you like to have an attempt at writing a shell script for that? I wonder if there's bits of `bump-formula-pr` we could use.

**Comment by SimenB** [comment]
That I can do. What's the easiest way the get the sha of the tarball? Actually downloading it and running the `sha` command, or is it available from the site?

**Comment by Daniel15** [comment]
> Actually downloading it and running the sha command,

That's probably the best approach. It's not available on the site at the moment.

**Comment by Daniel15** [comment]
Looks like this will be useful for "Scoop" (https://github.com/yarnpkg/website/pull/425) too. It looks to be very similar to Homebrew - Details about the package are stored in a Git repository.

**Comment by tech4him1** [comment]
Here is Scoop's Yarn manifest: https://raw.githubusercontent.com/lukesampson/scoop/master/bucket/yarn.json.

**Comment by SimenB** [comment]
There are a couple corner cases, see the update I submitted for 0.22.0: https://github.com/Homebrew/homebrew-core/pull/12154/files

It removed `revision`. While we can do the same in our script, I'm actually back at wanting to use `brew bump-formula-pr`. @Daniel15 do you run the release scripts yourself, or does a CI do it?

I tried linuxbrew again, but it doesn't really work for some reason. https://github.com/Linuxbrew/brew/issues/291#issuecomment-292701243

**Comment by Daniel15** [comment]
@SimenB - Release scripts are automatically ran. There's a few steps:
 - Most of the builds (tarball, Debian installer) are performed on CircleCI
 - Windows installer is built on AppVeyor
 - Both the CircleCI and AppVeyor build artifacts are uploaded to the GitHub release via a script in our releases repo (see https://github.com/yarnpkg/releases)
 - Latest version number is manually bumped when we want to publicly release a version

After a new release is out:
 - Chocolatey package is updated by a build job on my server
 - Debian repository is updated by a cronjob on my server

I think ideally I'd run the Homebrew package update in the same way that I'm handling Chocolatey today - As a build job that automatically runs once a new release is available. I've only got Linux and Windows build servers available though, so it's not possible to run a MacOS-specific script.

**Comment by SimenB** [comment]
OK, thanks. I don't _think_ it's macOS specific, it's just ruby: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb

That said, I was able to get Linuxbrew to work, I just had to pass in the sha myself. I'll see if I can't get a script up and running :)

**Comment by SimenB** [comment]
@Daniel15 actually, could you try just running this and see what happens:

```sh-session
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
$ $HOME/.linuxbrew/bin/brew bump-formula-pr --strict yarn --url=https://yarnpkg.com/downloads/0.23.0/yarn-v0.23.0.tar.gz --sha256=8cbd733e6bf253e0f5e2e5db7dbd165311150754b33df7c00bcaec175a3b33c2
```

You'll probably get a prompt for username and password, but that will only happen once.

**Comment by Daniel15** [comment]
That works, somewhat! The only issue is that it sends the PR to the Linuxbrew repo rather than the upstream Homebrew one: https://github.com/Linuxbrew/homebrew-core/pull/2320

It also threw an error about $BROWSER not being set, which makes sense as it's running on a remote server:
```
Please set $BROWSER to a web launcher
Error: Failure while executing: hub pull-request --browse -m yarn\ 0.23.0

Created\ with\ `brew\ bump-formula-pr`.
```

If `bump-formula-pr` can be adjusted to send the PR to the Homebrew repo rather than the Linuxbrew one, I think we can use it!

I noticed that `$HOME/.linuxbrew/Library/Taps/homebrew/homebrew-core` contains the `linuxbrew-core` repo. Could I configure it to tap/clone the upstream homebrew-core one too?

**Comment by SimenB** [comment]
That's great!

Too bad about the browser thing, hopefully they'll change it to work better when headless.

Having Linuxbrew point to homebrew shouldn't be anything more than just doing `git remote set-url origin https://github.com/Homebrew/homebrew-core.git` in `$HOME/.linuxbrew/Library/Taps/homebrew/homebrew-core` should it? As long as it's a "real" server and not a docker container (kind of needed for hub to work anyways) it shouldn't be an issue..

**Comment by Daniel15** [comment]
> Having Linuxbrew point to homebrew shouldn't be anything more than just doing git remote set-url origin https://github.com/Homebrew/homebrew-core.git in $HOME/.linuxbrew/Library/Taps/homebrew/homebrew-core should it? 

Good idea. That makes sense! I'll try that soon 😃 

> As long as it's a "real" server and not a docker container (kind of needed for hub to work anyways) it shouldn't be an issue.

Yeah my build server is running in an [LXC container](https://en.wikipedia.org/wiki/LXC) so it should be fine.

**Comment by SimenB** [comment]
Homebrew might consider passing `-b` option to hub when submitting the PR as well.

```sh-session
$ hub pull-request --help
usage: git pull-request [-f] [-m <MESSAGE>|-F <FILE>|-i <ISSUE>|<ISSUE-URL>] [-o] [-b <BASE>] [-h <HEAD>]

Opens a pull request on GitHub for the project that the "origin" remote
points to. The default head of the pull request is the current branch.
Both base and head of the pull request can be explicitly given in one of
the following formats: "branch", "owner:branch", "owner/repo:branch".
This command will abort operation if it detects that the current topic
branch has local commits that are not yet pushed to its upstream branch
on the remote. To skip this check, use "-f".

Without <MESSAGE> or <FILE>, a text editor will open in which title and body
of the pull request can be entered in the same manner as git commit message.
Pull request message can also be passed via stdin with "-F -".

If instead of normal <TITLE> an issue number is given with "-i", the pull
request will be attached to an existing GitHub issue. Alternatively, instead
of title you can paste a full URL to an issue on GitHub.
```

**Comment by Daniel15** [comment]
Seems to work fine after setting the remote URL. I submitted a pull request: #3083. I'd love to know your thoughts before merging it :D

**Comment by tech4him1** [comment]
Do you want to keep this open for Sccop, or open a new issue for it (https://github.com/yarnpkg/yarn/issues/2841#issuecomment-289243768, https://github.com/yarnpkg/yarn/issues/2841#issuecomment-289479010)?

**Comment by SimenB** [comment]
A separate issue makes sense, as the solution here​ is very brew specific

**Comment by Daniel15** [comment]
I created a separate issue for Scoop: #3135
