### ISSUE TITLE
Ensure Yarn retries on 5xx errors

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2849]
**Do you want to request a *feature* or report a *bug*?**
Both

**What is the current behavior?**
Yarn sometimes shows 5xx errors when installing packages (eg. see #2769)

**What is the expected behavior?**
Yarn is supposed to be resilient to poor network conditions. It sounds like it might not be retrying correctly in some scenarios. We should verify that it does indeed retry on 5xx errors, by using a debugging proxy such as [Fiddler](http://www.telerik.com/fiddler) to intentionally inject 500 errors and see how Yarn reacts.

**Comment by bestander** [comment]
@rally25rs, @gsklee, @torifat would you guys want to give this feature a try?
According to CDN logs a hundred or so times a day we get random 500 responses, they should be fixed by a retry.

**Comment by rally25rs** [comment]
I've been trying to spend my spare time on issue 3603 (reimplementing upgrade and upgrade-interactive), but if no one else has time, I can give it some attention.

**Comment by torifat** [comment]
I will give it a try tonight :) if @rally25rs has not done already.

**Comment by bestander** [comment]
You guys rock!

**Comment by gsklee** [comment]
Guess I can go picking something else then :-p

**Comment by rally25rs** [comment]
Thanks for looking into this @torifat 👍 

If you end up needing a hand, let me know.

**Comment by torifat** [comment]
@rally25rs Setting up Charles Proxy 😂 ...

**Comment by torifat** [comment]
I have spent some time on this. We already have a retry mechanism in `RequestManager`. But, in `TarballFetcher` we are using `process` to leverage `stream`. But, retry in `stream` is not straight forward like `Promise` or `async-await`. We have to end up doing something similar to https://github.com/stephenplusplus/retry-request/

Any suggestion? @bestander @rally25rs

**Comment by bestander** [comment]
Use your best judgement, retry-request code does not look too bad.
