### ISSUE TITLE
yarn pack: directories listed in "files" property are empty

### ISSUE THREAD

**Issue by simonvizzini** [yarnpkg/yarn#2851]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Directories specified in the "files" property of the package.json are empty inside the package produced by ``yarn pack``

**If the current behavior is a bug, please provide the steps to reproduce.**

1. git clone https://github.com/simonvizzini/yarn_pack_bug.git
2. yarn pack

The produced ``yarn_pack-v1.0.0.tgz`` contains an empty "src" folder. ``npm pack`` on the other hand works fine.

**What is the expected behavior?**

Directories specified in "files" should not be empty.

**Please mention your node.js, yarn and operating system version.**

node 7.3.0
yarn 0.21.3
Windows 10 x64

**Comment by alexkrolick** [comment]
Same on Mac OS Sierra, node 7.5.0, yarn 0.23.1
