### ISSUE TITLE
[integrity check broke] Always linking, never "up to date"

### ISSUE THREAD

**Issue by borekb** [yarnpkg/yarn#2859]
Yarn v0.21.3 on Windows 10.

Wild guess:

```
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
```

is causing "linking" dependencies on all runs of `yarn` making it slow.

---

Full details:

On most projects, the first `yarn` is slow as it downloads dependencies but subsequent `yarn`s are fast, something like:

```sh
$ yarn
yarn install v0.21.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.21s.
```

However, on one particular project, `yarn` is always slow, most of the time spent on "linking" dependencies:

```sh
$ yarn
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 103.04s.

$ yarn
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 72.80s.

$ yarn
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 81.77s.
```

Perhaps related report in another issue: https://github.com/yarnpkg/yarn/issues/990#issuecomment-277531063.

**Comment by bestander** [comment]
Need repro steps please

**Comment by mcissel** [comment]
steps to reproduce:

1. create a new package.json in an empty folder
2. yarn add chimp
3. yarn install

You won't get:
```
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.23s.
```

You'll get:
```
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it
from installation.
[3/4] Linking dependencies...
████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2142/14564█
[4/4] Building fresh packages...
Done in 20.30s.
```

**Comment by borekb** [comment]
@mcissel beat me to it :) Sorry for not providing it in the first place.

**Comment by friday** [comment]
Also getting this on Ubuntu with Yarn 0.21.3 and Node v6.9.5

I tried downgrading, but it's happening on versions as old as 0.17.4, and if I go older than that things start failing.

**Comment by bestander** [comment]
I can repro this.
Looks like integrity check is different at the beginning of install operation and at the end.
I'll work on this in the near future

**Comment by bestander** [comment]
The reason is in `cucumber@github:xolvio/cucumber-js#v1.3.0-chimp.2` deeper in the tree, it gets partially initialized between resolve and fetch phases.
I am working on changing the content of integrity file, this should fix it.

**Comment by jackhamburger** [comment]
I am also having this issue on 0.22 and I'm not quite sure how to resolve it

**Comment by bestander** [comment]
0.23.2 should have this fixed

**Comment by SuhairZain** [comment]
@bestander 
I'm seeing this behavior on `0.27.5`. I run `rm -rf node_modules && yarn` and it does it in `28.29s`. Then, if I do `yarn`, instead of showing `Already up to date`, it does the whole fetch/link process, but this time in just `7.56s`. I have other projects in my system, but none of them have this issue. Do you have any pointers as to what could be the problem?

**Comment by KVSocial** [comment]
we updated to latest version  1.13.0 still giving that same error.
