### ISSUE TITLE
yarn should return non-zero status when bad gateway error happens

### ISSUE THREAD

**Issue by daveisfera** [yarnpkg/yarn#2864]
I was just building a Docker container and yarn ran into a bad gateway error with this output:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/fraction.js/-/fraction.js-3.3.1.tgz: Request failed \"502 Bad Gateway\"".
```

yarn needs to return a non-zero status when an error like this happens, because without this error, Docker thinks that everything is correct and caches a corrupted layer that causes a problem with this build and all subsequent builds.

**Comment by daveisfera** [comment]
This happened again. Here's the version info:
```
Yarn version: 
  0.21.3

Node version: 
  6.10.0

Platform: 
  linux x64
```

And here's the trackback from yarn-error.log:
```
Trace: 
  Error: https://registry.yarnpkg.com/packet-reader/-/packet-reader-0.2.0.tgz: Request failed "502 Bad Gateway"
      at Request.handleRequestError (/usr/local/bin/yarn:52412:20)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestResponse (/usr/local/bin/yarn:103602:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:363:20)
      at emitOne (events.js:96:13)
      at TLSSocket.emit (events.js:188:7)
```

**Comment by mattkime** [comment]
@daveisfera I see the same problem on a regular basis _and_ get a non-zero error code. i suspect something else is amiss.

more discussion - https://github.com/yarnpkg/yarn/issues/2769

**Comment by sivabudh** [comment]
We run into this issue about twice a day per project. We build about 8 times a day per project. We have 2 projects.

**Comment by daveisfera** [comment]
@mattkime I think that you're correct. We were previously running:
```
RUN for d in $(ls /usr/src/app/lib/); do\
        echo " = Building lib/${d} ="\
        cd /usr/src/app/lib/${d} && yarn install\
    done
```

So the non-zero exit status of yarn was being ignored by the loop. We switched to this and I believe that the build will fail correctly now:
```
RUN (for d in $(ls /usr/src/app/lib/); do\
        echo " = Building lib/${d} ="\
        cd /usr/src/app/lib/${d} && yarn install || exit\
    done)
```
