### ISSUE TITLE
Problem with har-validator after reinstall

### ISSUE THREAD

**Issue by jamiewinder** [yarnpkg/yarn#2871]
I've just reinstalled yarn 0.21.3 on Windows, and I'm seeing an error when I try to run a `yarn upgrade` on my project...
```bash
> yarn upgrade
yarn upgrade v0.21.3
[1/4] Resolving packages...
error An unexpected error occurred: "ENOENT: no such file or directory, open 'C:\\Users\\(...)\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\har-validator\\lib\\index.js'".
```
Indeed, a file doesn't exist at that path, but the main file for the module (from its package.json) is `lib/node4/promise.js`. If I create an `lib/index.js` file with the content `module.exports = require('./node4/promise.js');` then it all works again. 

Not sure if I should class this as a problem with yarn, or this har-validator module?

**Comment by Ninja-1** [comment]
I had this problem with `yarn@0.21.3` after upgrading to Node 7.7.1. I have no problems with `yarn@0.22.0` on Node 7.7.1, nor `yarn@0.21.3` on Node 6.10.0.

**Comment by jsight** [comment]
It seems to be triggered by upgrading to har-validator 4.x.

**Comment by DevJazz** [comment]
Hi, so I had this issue on Monday morning and it's a Yarn dependency (request/har-validator) that updated over the weekend. Yarn has this dependency as ^2.75.0 so it would of grabbed the latest version, breaking it (for some reason I do not know).

I found this problem mostly with using 'npm install -g yarn'. The only solution that I managed to get around it was by using the 'exe/msi' installer of yarn and it finally worked, if that's of any use.

Using Node 7 and yarn 0.21.3

**Comment by mtpultz** [comment]
I updated to Node 7 and that didn't work by itself.  I also had to update yarn to the release candidate v0.22.0.  Not sure if just updating to `yarn@0.22.0` would do it without the Node update so that might be a better first step.

**Comment by rmoriz** [comment]
We're also affected by this bug. As we have multiple nodejs versions running on one machine (think of nvm) we also want to have a defined yarn version _per nodejs version_. Using the provided packages (e.g. `.deb`) or the  `curl … install.sh` method are incompatible to this approach as they enforce _a single, global yarn version_ to be used.

**Comment by nickeljew** [comment]
I'm wondering why lib/index.js is located by yarn when package.json of har-validator 4.x was updated with new main entry.

In lib/har.js of yarn v0.21.3, 
var validate = require('har-validator')
There is no problem with this code line, but what causes this bizarre issue?

**Comment by twig** [comment]
experiencing the same issue after re-installing yarn via npm install -g on windows.

**Comment by maroy1986** [comment]
I'm on latest Node, which is 7.7.2 and I had that issue. Installing Yarn 0.22.0 RC fixed the issue. Hopefully, they will released that version soon. For those who can't wait, just do the following : 

`npm -g install yarn@0.22.0`

That fixed my problem and everything is now working normally.

**Comment by arcanis** [comment]
Should be fixed by now, I'm going to close this issue. Feel free to reopen it if you still experience this issue.
