### ISSUE TITLE
Install Error: node is incompatible with this module. Expected version "5.3.0".

### ISSUE THREAD

**Issue by abdilahrf** [yarnpkg/yarn#2884]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Can't install yarn

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn`

**What is the expected behavior?**
Success Install

**Please mention your node.js, yarn and operating system version.**
`uname -a` : Linux machine 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`node.js -v` : v4.2.6
`node -v` : v6.10.0
`cat /etc/issue` : Ubuntu 16.04.2 LTS 

![yarn-error-node-incompatible](https://cloud.githubusercontent.com/assets/6015012/23795504/97d3baaa-05c8-11e7-8352-8248b525f20d.png)

**Comment by Daniel15** [comment]
To me this seems like a bug with that package, its package.json says that it's only compatible with Node 5.3.0: https://github.com/tcandens/mapbox-gl-react/blob/master/package.json#L27. I assume they actually meant `>5.3.0`.

However, `npm` seems to be fine with it. Very strange.

**Comment by hbetts** [comment]
@Daniel15 this seems related to #1102.

**Comment by arcanis** [comment]
Closing in favor of #1102 👍
