### ISSUE TITLE
Yarn complains of peer unmet dependency but npm doesn't 

### ISSUE THREAD

**Issue by awebdeveloper** [yarnpkg/yarn#2889]
```
/home/ui $ yarn install
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@ionic/app-scripts@1.1.4" has unmet peer dependency "@angular/tsc-wrapped@*".
[4/4] 📃  Building fresh packages...
✨  Done in 31.49s.
/home/ui $   npm install
/home/ui $ 
```

**Please mention your node.js, yarn and operating system version.**
Mac OS X Yosemite 
yarn : 0.21.3
node : 7.7.2

**Comment by jknight12882** [comment]
+1 on this

**Comment by arcanis** [comment]
Why should we not warn about unmet peer dependencies? That feels like a pretty important issue, something that most users might want to know.

**Comment by awebdeveloper** [comment]
But npm didn't that's where the confusion was

**Comment by CrabDude** [comment]
Dupe: #2886

**Comment by BYK** [comment]
Closing due to lack of reproduction steps. Please reopen with reproduction steps that include at least a `package.json` file if you need this to be fixed.

**Comment by BYK** [comment]
@CrabDude did you mean #2688?

**Comment by CrabDude** [comment]
Yes.
