### ISSUE TITLE
har-validator not found

### ISSUE THREAD

**Issue by phra** [yarnpkg/yarn#2900]
**Do you want to request a *feature* or report a *bug*?**

☑️ BUG

**What is the current behavior?**
after upgrading yarn with `sudo npm i -g yarn@latest`
`yarn install` crashes with `Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/yarn/node_modules/har-validator/lib/index.js'`

**If the current behavior is a bug, please provide the steps to reproduce.**

`cd /tmp && yarn init -y && yarn add is-thirteen`

**What is the expected behavior?**
yarn works fine.

**Please mention your node.js, yarn and operating system version.**
```
╭─phra at debian in /tmp/test
╰─λ cat yarn-error.log                                                                                                                                           0 < 11:02:10
Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add is-thirteen

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

Yarn version: 
  0.21.3

Node version: 
  7.7.2

Platform: 
  linux x64

npm manifest: 
  {
    "name": "test",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/yarn/node_modules/har-validator/lib/index.js'
      at Object.fs.openSync (fs.js:583:18)
      at Object.fs.readFileSync (fs.js:490:33)
      at Object.Module._extensions..js (module.js:579:20)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.require (module.js:498:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/request/lib/har.js:5:16)
      at Module._compile (module.js:571:32)
```

**Comment by epmatsw** [comment]
I was seeing this same issue with a fresh global install of 0.21.3 on node 7.6.0 (installed via nvm). After `npm uninstall -g yarn` and `npm install -g yarn@0.22.0`, it seems to work fine. So I'm not sure if it only happens on some installs (timing issue?) or if 0.22.0 fixed it.

**Comment by phra** [comment]
@epmatsw yeah, v0.22 works!

**Comment by Daniel15** [comment]
Could you please try an installation method other than npm (such as Homebrew on Mac OS)? npm often has strange issues that don't occur when using our better supported installation methods.

**Comment by epmatsw** [comment]
@Daniel15 I don't see the issue with 0.21.3 installed via brew, but I also don't see it now when installing via `npm install -g`. So not sure what's up with that...

**Comment by phra** [comment]
@Daniel15 sorry but I only use linux systems, so someone else has to try on MacOS.

**Comment by Daniel15** [comment]
@phra - We have a Debian/Ubuntu package, an RPM package, and an installer shell script. You can pick the one that works in your environment. They're all documented on the Yarn site 😃

**Comment by IanTaiteAgl** [comment]
I'm getting this error on Windows. I had to downgrade globally installed Yarn to 0.21.2. My setup is node 7.7.2 / npm 3.10.5. installing via "npm install -g yarn" in an admin command prompt.

**Comment by arcanis** [comment]
That should have been fixed, please try one of the latest releases, and open a new issue if it still break. Thanks!

**Comment by amypellegrini** [comment]
If anyone out there happens to re-encounter this problem, you may find some useful information here:

https://github.com/ahmadnassri/node-har-validator/issues/113
https://github.com/ahmadnassri/node-har-validator/issues/112#issuecomment-437378269
