### ISSUE TITLE
Package reset to non-built status after cache clean and install

### ISSUE THREAD

**Issue by blexrob** [yarnpkg/yarn#2903]
**Do you want to request a *feature* or report a *bug*?**
This is a bug, in yarn v0.21.3 (installed in Fedora 25, via yarn repo)

**What is the current behavior?**
The following steps cause the phantomjs-prebuilt to return to non-built state
1. `yarn add phantomjs-prebuilt`
2. `yarn cache clean`
3. Edit package.json, add the following dependency: 
`"dompack": "git://github.com/WebHare/dompack.git#a22f86e72298c73df13b67a0797d2ed2e7a95cc7"`
4. `yarn install`

After that series of steps, the built file `node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs` (and several others) has disappeared. Step 4 causes a build of another package, maybe yarn cache clean doesn't clear the list of built modules, and install assumes that the (newly fetched) cached version has already been built.

Expected is that build results of the module `phantomjs-prebuilt` should still exist.

Using:
Fedora 25
Node v7.7.1
yarn v0.21.3

**Comment by bestander** [comment]
I reckon this is fixed in 0.24 now.
```
yarn add phantomjs-prebuilt
yarn add v0.24.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 90 new dependencies.

yarn cache clean
yarn cache v0.24.1
success Cleared cache.
✨  Done in 0.45s.

bestander-mbp:phantom bestander$ vim package.json
{
  "dependencies": {
    "phantomjs-prebuilt": "^2.1.14",
"dompack": "git://github.com/WebHare/dompack.git#a22f86e72298c73df13b67a0797d2ed2e7a95cc7"
  }
}

$ yarn install
Using Yarn from /Users/bestander/work/yarn/bin/yarn
yarn install v0.24.1
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 3.29s.

ls -al node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
-rwxr-xr-x  1 bestander  THEFACEBOOK\Domain Users  45020592 May 15 13:18 node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
```
