### ISSUE TITLE
Yarn wont install some single character repos

### ISSUE THREAD

**Issue by jamesblack** [yarnpkg/yarn#2904]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When I run the command `yarn add f u` (a coworker and I having a fun battle about yarn vs npm led to this) I get an error the the package u does not exist. When my coworker runs it in NPM, it downloads both packages just fine

**If the current behavior is a bug, please provide the steps to reproduce.**
On the latest yarn (0.21.3 according to brew) just run `yarn add f u` and it should give you the error

*EDIT - It appears the issue is just u, and now Im sad that its not all single character repos.*

[yarn-error.log](https://gist.github.com/jamesblack/6398ab91b538b7f673643a55ab8697ad)

**What is the expected behavior?**
Yarn adds the f library from NPM and the u library from NPM
[f](https://www.npmjs.com/package/f)
[u](https://www.npmjs.com/package/u)

**Please mention your node.js, yarn and operating system**
Node 7.6.0
OSX 10.12.1
Yarn 0.21.3

**Comment by arcanis** [comment]
It's not u, it's me.

...
More seriously, I can't reproduce this issue on the latest release. Can you recheck on your side if you have sone time?
