### ISSUE TITLE
`yarn add` not support git address with branch

### ISSUE THREAD

**Issue by AntSworD** [yarnpkg/yarn#2913]
Node Version: `v7.6.0`
yarn Version: `0.15.1`

In my package.json:
```
 "<node-xxxx>": "github:<gitUserName>/<projectName>#<Branch-not-master>",
```
Got:
```
yarn add v0.15.1
[1/5] 🔍  Resolving packages...
error Couldn't find match for "master" in "v1,v2" for "github:<gitUserName>/<projectName>".
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
It doesn't had master branch.

**Comment by juanca** [comment]
We use `0.17.4` which has support for github package on whatever SHA (branch or commit).

**Comment by AntSworD** [comment]
I updated `v0.21.3`
Got an error `error An unexpected error occurred: "Error connecting to repository. Please, check the url.".`

**Comment by juanca** [comment]
Our github project dependency is also a private repository. The computer has an ssh key with access to the private repository.

**Comment by AntSworD** [comment]
npm work fine

**Comment by AntSworD** [comment]
Cause [HERE](https://github.com/yarnpkg/yarn/blob/master/src/resolvers/exotics/hosted-git-resolver.js#L109)
`Request "https://github.com/<private-project>.git/info/refs?service=git-upload-pack" finished with status code 401.`

**Comment by belohlavek** [comment]
Any walkaround for this?

**Comment by lukeggchapman** [comment]
For me `Yarn add git+ssh://git@github.com/<gitUserName>/<projectName>.git#<Branch>` works when adding, but when running fresh `yarn install` the branch is ignored and it grabs `master`

**Comment by arcanis** [comment]
The following script doesn't repro your issue - can you update it to highlight the problem you have (with the latest release), then create a new issue if it's still there? Thanks!

```
#!/usr/bin/env bash

YARN=${YARN:-yarn}

TEMP="$(mktemp -d)"
trap 'rm -rf "$TEMP"' EXIT

echo $TEMP
cd "$TEMP"

printf '{ "name": "main", "version": "1.0.0", "license": "MIT", "dependencies": {} }' > package.json

$YARN cache clean

$YARN add git+ssh://git@github.com/arcanis/private-pkg.git
$YARN install

$YARN add git+ssh://git@github.com/arcanis/private-pkg.git#branch
$YARN install

ls -l node_modules node_modules/*
```

**Comment by lukeggchapman** [comment]
I wasn't able to reproduce with your script either, I must have been confused somewhere. Thanks!

**Comment by AntSworD** [comment]
About my issue, I finally found out WHY. 

I use `github:<gitUserName>/<projectName>#<Branch-not-master>` as my `git remote url`.
It use `https` protocol fetch data, but `npm` used `git`.

SO, I need provide procotol on the remote url!

@arcanis

**Comment by unshift** [comment]
This is less painful than publishing a namespaced package: 

```
yarn add git+ssh://git@github.com/yargs/yargs.git
```
