### ISSUE TITLE
Option to not prune on install

### ISSUE THREAD

**Issue by thuey** [yarnpkg/yarn#2919]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
Extraneous dependencies are pruned on `yarn install`. This is a problem for my lerna mono-repo when I use `--hoist`. Shared dependencies get hoisted to the root of the mono-repo, and subsequently running `yarn install` prunes them.

**What is the expected behavior?**
I see the value in having `yarn install` prune extraneous dependencies, but it would be great if there was an option to not prune `yarn install --no-prune`.

**Please mention your node.js, yarn and operating system version.**
Node.js: v7.5.0
yarn: 0.21.3
OS: OS X El Capitan

**Comment by bestander** [comment]
Workspaces are available and integrated with Lerna bootstrap
