### ISSUE TITLE
"async-2.1.5.tgz": Tarball is not in network and can not be located in cache

### ISSUE THREAD

**Issue by imthinhvu** [yarnpkg/yarn#2920]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
"async-2.1.5.tgz": Tarball is not in network and can not be located in cache

**If the current behavior is a bug, please provide the steps to reproduce.**

Included async 2.1.5 in package.json and ran yarn `install`

```
[1/4] Resolving packages...
[2/4] Fetching packages...
error "async-2.1.5.tgz": Tarball is not in network and can not be located in cache ("/jenkins/workspace/_feature_remove-launcher-py-LPZWMYFKFHREVEVXUMLULEWE2WB3E3BO4E62QIZZP6F5XC473ASQ/async-2.1.5.tgz")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
script returned exit code 1
```

**What is the expected behavior?**
For the async package to install without issues

**Please mention your node.js, yarn and operating system version.**
Running the following from node:6.9-alpine docker image:
Node 6.9
Yarn 0.21.3
Alpine Linux 3.3

**Comment by marvinhagemeister** [comment]
Same here with a different package:

```bash
$ yarn

[1/4] Resolving packages...
[2/4] Fetching packages...
verbose 1.948 Error: "array.from-1.0.3.tgz": Tarball is not in network and can not be located in cache ("/volume/array.from-1.0.3.tgz")
    at /usr/local/bin/yarn:52358:15
    at Generator.next (<anonymous>)
    at step (/usr/local/bin/yarn:97:30)
    at /usr/local/bin/yarn:108:13
error "array.from-1.0.3.tgz": Tarball is not in network and can not be located in cache ("/volume/array.from-1.0.3.tgz")
```

**Comment by marvinhagemeister** [comment]
After investigating a bit further and only got more questions.

The packages are correctly listed at https://registry.yarnpkg.com/array.from with the correct `tgz` file (https://registry.npmjs.org/array.from/-/array.from-1.0.3.tgz) . A downgrade to `array.from-1.0.2` fixes the issue for me.

**Comment by marvinhagemeister** [comment]
Found the culprit: One of our team members did activate `offline` mode leading to relative paths in the `resolve` field inside `yarn.lock`

**Comment by arcanis** [comment]
I'm going to close this one, since the error is most likely coming from a misconfigured offline mirror.
