### ISSUE TITLE
error messaging typo

### ISSUE THREAD

**Issue by Opticsponge** [yarnpkg/yarn#2927]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

when sending a bad/npm like request like `yarn --global add tslint`

response
> error `install` has been replaced with `add` to add new dependencies. Run "yarn global add add tslint" instead. the word add gets repeated

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn --global add tslint`

**What is the expected behavior?**

remove repeated word `add`

example

> error `install` has been replaced with `add` to add new dependencies. Run "yarn global add tslint" 

**Please mention your node.js, yarn and operating system version.**
node v7.7.2
yarn v0.21.3
mac os 10.12.3

**Comment by charpeni** [comment]
That's not an issue.

`yarn --global add tslint` you're trying to install `add` and `tslint` as global dependencies.

However, `--global` is not a flag like in npm, to install globally `tslint` run the following command : 
```
yarn global add tslint
```

**Comment by Opticsponge** [comment]
ahh that makes sense, thank you for clarification.
