### ISSUE TITLE
yarn -v triggers yarn install

### ISSUE THREAD

**Issue by elwayman02** [yarnpkg/yarn#2928]
**What is the current behavior?**

![1__bash](https://cloud.githubusercontent.com/assets/1325482/23969670/77e207a0-0984-11e7-9bb7-da0baa8df9c5.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Type `yarn -v` in console

**What is the expected behavior?**

yarn -v should just print the version without performing any other tasks

**Please mention your node.js, yarn and operating system version.**

yarn: 0.21.3
node: 7.7.3
OS: macOS Sierra 10.12.3

**Comment by steppefox** [comment]
But in the yarn, `-v` is a wrong key oO `-V` and `--version` are right keys for yarn command

**Comment by elwayman02** [comment]
Yea, I don't see any reason why yarn would not support the industry standard `-v`...

**Comment by arcanis** [comment]
Because `-v` means either `--version` or `--verbose`, depending on the program. It's not an industry standard (or rather, there is two different competing standards :).

As a good rule of thumb, always use `--version`, then if it doesn't work use `-V`, then only if it doesn't work use `-v`.
