### ISSUE TITLE
Upgrade to CircleCI 2.0

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2933]
This is just a tracking task so I don't forget 😄 

Last time I attempted this, I encountered an issue where CircleCI would say that the build succeeded even when it failed. Need to investigate why that happened and fix it.

WIP branch: https://github.com/yarnpkg/yarn/tree/circleci-2

**Comment by charpeni** [comment]
The config from @ryanwohara seems a bit outdated, so I followed the latest documentation from CircleCI 2.0 if you want to take a look in #2947.

**Comment by Daniel15** [comment]
You're right! :)
