### ISSUE TITLE
Sub-dependencies are installed even when dependency is a symlink

### ISSUE THREAD

**Issue by aleclarson** [yarnpkg/yarn#2936]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If `node_modules/foo` is a symlink, its dependencies are still installed by `yarn install`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Add a symlink to `node_modules`.
2. Run `yarn install`.
3. See the dependencies of the symlink are installed in the current package.

**What is the expected behavior?**
Do not install dependencies of a symlink.

**Please mention your node.js, yarn and operating system version.**
node.js v6.9.5
yarn v0.22.0
macOS Sierra v10.12.3

**Comment by arcanis** [comment]
Not sure we'll fix this. The resolution (ie the moment where we detect all the packages we'll need) happens before the packages are actually installed on the filesystem. Maybe this will get fixed with the `link:` proposal.
