### ISSUE TITLE
'yarn upgrade local-package' doesn't grab new package version ('yarn upgrade' does)

### ISSUE THREAD

**Issue by yched** [yarnpkg/yarn#2939]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Using yarn 0.21.3, `yarn upgrade my-local-package@file:./path/to/my/local/package` doesn't seem to catch new versions of the local package.

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn add my-local-package@file:./path/to/my/local/package`

--> OK : correctly adds 'my-local-package', in the version N present in the folder

(... make some change in the local package, bump version number in ./path/to/my/local/package/package.json to N+1)

`yarn upgrade my-local-package@file:./path/to/my/local/package`

--> KO : doesn't grab the changes : 
yarn.lock stays unchanged,  
node_modules/ still contains version N

**What is the expected behavior?**

`yarn upgrade my-local-package@file:./path/to/my/local/package`

--> should copy the new version from ./path/to/my/local/package to node_modules/, and bump the version number in yarn.lock

Note : 

`yarn upgrade`

--> does upgrade *all* modules, including my-local-package to version N+1,
but upgrading all the other modules is not what I want :-)

**Please mention your node.js, yarn and operating system version.**

node 4.7.3, yarn 0.21.3, Ubuntu 16.04,

**Comment by juanca** [comment]
I would think https://github.com/yarnpkg/yarn/pull/2780 fixed this.

It was released in 0.22.0

Do you mind updating and verifying?

**Comment by yched** [comment]
Indeed, `yarn upgrade my-local-package` works perfectly fine in 0.22.0

Thanks for the super quick help @juanca

**Comment by CrabDude** [comment]
FWIW, looks like `"file:"` packages aren't automatically updated when running vanilla `yarn`, which makes sense b/c it's not upgrading automatically by default, but it doesn't make sense b/c `yarn install --force` or `yarn install` without an existing `node_modules` will grab the latest version of the `file:path/to/package`.

**Comment by arcanis** [comment]
I'm going to close this issue, since it appears to have been resolved :)

**Comment by cope** [comment]
Actually, now with yarn version 1.3.2 even yarn upgrade does **not** upgrade my package to the latest version. Even if I manually change the required version number in the package.json file to N+1, and then run yarn upgrade, I still have version N in node_modules...

**Comment by Al-Sharif** [comment]
Same here with version v1.12.1

**Comment by DenisKrasnov** [comment]
Same here with version v1.12.3

**Comment by folex** [comment]
What's the best way to update local (file:/path/to/package) dependency? 

Seems like `yarn upgrade package` will rebuild _all_ dependencies

**Comment by b0nn1e** [comment]
> What's the best way to update local (file:/path/to/package) dependency?
> 
> Seems like `yarn upgrade package` will rebuild _all_ dependencies

I have the same problem
