### ISSUE TITLE
Broken published packages caused by `yarn pack` failing to include entire directories

### ISSUE THREAD

**Issue by fvgs** [yarnpkg/yarn#2942]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn pack`, and thus also `yarn publish`, fail to include the contents of directories specified in the `files` package.json field resulting in broken packages being published to the registry.
e.g.
```javascript
{
  ...

  "files": ["src/"]

  ...
}
```
The directory `src/` itself is included, but its contents are not included (except files named `index.js` as observed in the below example). This differs from the behavior of `npm pack` which includes all of the specified directory's contents. This also contradicts the [documentation of the files field](https://yarnpkg.com/en/docs/package-json#toc-files) which uses a similar example to the one above.

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh
# The `files` field in the express package is appropriate for testing this
git clone https://github.com/expressjs/express
cd express

# Observe the files missing from the lib/ directory
# (Adjust the name of the tarball as appropriate)
yarn pack && tar -xvf express-v4.15.2.tgz && rm -r package

# Observe the correct package contents
# (Also note that npm does not package the examples/ directory while yarn does.
#  But that is not the main issue here)
npm pack && tar -xvf express-v4.15.2.tgz && rm -r package
```

**What is the expected behavior?**
All contents of `src/` should be included in the resulting tarball, matching npm behavior and yarn's own documentation.
Additionally, the `examples/` directory should probably not be included in the tarball, thereby matching npm behavior. But the primary issue is the first one.

**Please mention your node.js, yarn and operating system version.**
node -> 7.7.3
yarn -> 0.21.3
os -> macOS Sierra 10.12.3

For others encountering this issue, I have found the use of `src/**` instead of `src/` in the `files` field to achieve the desired results (i.e. include all contents of the `src/` directory).

**Comment by joshburgess** [comment]
I just experienced this also. A user reported that one of my npm packages had completely empty folders after they installed, causing all imports to break. I quickly republished using npm and the problem was fixed. yarn publish is currently broken...

**Comment by satya164** [comment]
I've faced this issue too. Seems like `yarn publish` is unusable right now.
