### ISSUE TITLE
yarn replace oldpackage --with newpackage

### ISSUE THREAD

**Issue by ibrahimduran** [yarnpkg/yarn#2952]
**Do you want to request a *feature* or report a *bug*?**
Feature

You must run two commands in order to remove packages and install new ones but with replace command you could remove package(s) and install new ones in one command.

Usage proposal: `yarn replace <...packagesToRemove> --with <...packagesToInstall>`

**Comment by torifat** [comment]
You can just write yourself a `bash` function for this, if you need it frequently. But, to me it didn't seem like a feature we should include in the core.

**Comment by arcanis** [comment]
I agree. It seems easier to just write `yarn remove <> && yarn add <>`
