### ISSUE TITLE
tests failing due to timeout errors

### ISSUE THREAD

**Issue by kevinburke** [yarnpkg/yarn#2955]
When running the test suite locally with the latest master, the following tests occasionally fail.

```
  ● install should respect --no-bin-links flag

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)

  ● should not loose dependencies when installing with --production

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

I believe the second test should be "lose dependencies" as well.

**Comment by charpeni** [comment]
Same on CircleCI and Travis.

cc @bestander @Daniel15

**Comment by bestander** [comment]
Yeah, we either need to increase timeouts or maybe split the large tests into a separate file.
If you have a few moments please send a PR, it would be a great help

**Comment by charpeni** [comment]
Unfortunately, this does not seem to be a timeout problem. Although I considerably increase the timeout, the tests never end.

I will try to take a closer look at it.

**Comment by bestander** [comment]
install should respect --no-bin-links flag
 is definitely broken.
We should look into what broke it and maybe disable for a while.

**Comment by bestander** [comment]
I think the issue is in the "choose version" prompt in the beginning.
This might be the fix needed https://github.com/yarnpkg/yarn/blob/master/__tests__/package-resolver.js#L16
