### ISSUE TITLE
yarn can not run in command line ,if I change install directory from c:  to d:  on window7

### ISSUE THREAD

**Issue by gitnewer** [yarnpkg/yarn#2964]
I use window7.  I change install directory when I run install software from c:  to d: .  After install ,  the environment  variable add a path which is "C:\Users\jasonlan\AppData\Local\Yarn\.bin".But , this path is not exist at all.  So, I can not run yarn in command line .  For example ,I can not run "yarn --version".  

I add the install path "D:\Program Files (x86)\Yarn\bin"  to environment  variable ,  then yarn can run .

I don't know why .May some one can explain that ?

Thank you

**Comment by Daniel15** [comment]
`D:\Program Files (x86)\Yarn\bin` should be in the system path, whereas `C:\Users\jasonlan\AppData\Local\Yarn` is in the user path. These are two separate fields in the environment variables editor.

**Comment by gitnewer** [comment]
@Daniel15  you are right .Thank you
