### ISSUE TITLE
Suggestion: yarn scripts

### ISSUE THREAD

**Issue by phaistonian** [yarnpkg/yarn#2965]
It'd be handy to see what scripts are available (defined) in the package.json so that you don't have to go through the file over and over again.

That said, how about `yarn scripts` (or something like that) where you get a listing of 

`script name`: `command`.

ps: It may be implemented already. Sorry for being too lazy to check.

**Comment by Tom-Bonnike** [comment]
Use `yarn run`, just like npm `npm run`

**Comment by phaistonian** [comment]
You can actually omit the `run` part with yarn.

I am not asking about how to run a script, I am suggesting that a way to see what scripts are available in the package (and what they do) should come in handy.

**Comment by Tom-Bonnike** [comment]
… `yarn run`

**Comment by phaistonian** [comment]
oh!

I had no idea - silly me :)

Thank you.
