### ISSUE TITLE
404 not found ,but the tgz is exists,i can dowloand!

### ISSUE THREAD

**Issue by LastKing** [yarnpkg/yarn#2968]
sorry I'm English is very bad.Sorry!
 
yarn version @0.22.0

If i use registry=https://registry.npm.taobao.org/.
I will get **" unexpected error occurred: "http://registry.npm.taobao.org/bytes/download/bytes-2.4.0.tgz: Request failed \"404 Not Found\""**

But, if i use "registry=https://registry.npmjs.org/"  ,  I can successfully get the package.
 
The taobao registry,  i set the HTTPS, why display is http!.

sorry,  I'm just reporting the problem. If you can't understand.  Please ignore me!
Sincere thanks

**Comment by LastKing** [comment]
when i at home,i will generate "resolved "http://registry.npm.taobao.org/commander/download/commander-2.9.0.t"  in yarn.lock  file, but if i in the company, i will create " https://registry.npm.taobao.org/accepts/download/accepts-1.3.3.tgz#c3ca7434938648c3e0d9c1e328dd68b622c284ca" .
I'am use the same  taobao npm  registry, but   why generate two different file, http or  https.
Sincere thanks

**Comment by purplecones** [comment]
I'm getting the same issue with `yarn add log-full`
```
error An unexpected error occurred: "https://registry.yarnpkg.com/log-full/-/log-full-0.1.2.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Volumes/HDD/Projects/SCRATCHPAD/recursiveCrawler/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

However, `npm install -save log-full` works.
```
└── log-full@0.1.2

npm WARN recursiveCrawler No description
npm WARN recursiveCrawler No repository field.
npm WARN recursiveCrawler No license field.
```

**Comment by arcanis** [comment]
`yarn add log-full` seems to work on the latest version. Can you check and reopen or ping me if it doesn't?
