### ISSUE TITLE
Is there a way not to check integrity with yarn install?

### ISSUE THREAD

**Issue by dbalthassat** [yarnpkg/yarn#2979]
I understand the relevance of checking integrity, but in my client context I need to install without checking. I am pretty new to yarn so maybe I am missing something, but if I do not, this question could be a feature.

**Comment by bestander** [comment]
use `--skip-integirty-check` flag

**Comment by dbalthassat** [comment]
What does "run install without checking if node_modules is installed" mean then?
Currently it's not working:

```
$ yarn --skip-integrity-check
yarn install v0.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://[registry-url]/jwt-decode-2.1.0.tgz: Bad hash. Expected "d3079cef1689d82d56bbb7aedcfea28b12f0e36a" but got "5f27150463d8c926e181a66bbd8c91cd221519db"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by bestander** [comment]
try removing yarn.lock and installing it again.
Looks like hashes don't match between when the lock file was generated and
now.

**Comment by wenyanqi** [comment]
@bestander it's not working(1.22.17). can you help to check again?

**Comment by piotrpoliwoda** [comment]
If it's only one or two of your dependencies you can delete only their records in the yarn.lock file. This way once you run yarn install they will be regenerated with the correct integrity checksums without doing a full checksum refresh for all packages

**Comment by oleksandr-danylchenko** [comment]
Seems that `--skip-integrity-check` has no effect when running it with the `yarn@1.22.19` 🤷🏻‍♂️
