### ISSUE TITLE
.npmignore and files are ignored in favor of .gitignore

### ISSUE THREAD

**Issue by TrySound** [yarnpkg/yarn#2986]
**Do you want to request a *feature* or report a *bug*?**

Bug

Dup https://github.com/yarnpkg/yarn/issues/685 and https://github.com/yarnpkg/yarn/issues/754 of just to draw attention because yarn publish command is unusable now.

**What is the current behavior?**

yarn pack looks in .gitignore to skip files even if .npmignore (not so matter caz npm specific) or `files` field are present.

**What is the expected behavior?**

prefer `files` field over .gitignore

**Please mention your node.js, yarn and operating system version.**

yarn0.21.3, node6

**Comment by whitecolor** [comment]
Yes, should not consider .gitignore if there is .npmignore/.yarnignre in place, seem to be kind of broken behaviour.

@bestander

**Comment by arcanis** [comment]
Closing this one, since it's a dupe.

**Comment by BjornMelgaard** [comment]
For everyone who encountered problem with directories with compiled js files not published because they were in gitignore

got working with this `.npmignore`
```
# ignore everything
/*

# except
!es
!lib
```

**Comment by korneel** [comment]
@BjornMelgaard Thanks, I had to use `!lib/*`.

**Comment by jonaskello** [comment]
@BjornMelgaard @korneel Thanks for leaving these notes here. I had to do this to make it work:

```
# ignore everything
*/**

# except
!lib-cjs/**/*
!lib-esm/**/*
```
