### ISSUE TITLE
how to install dependency without optional dependencies?

### ISSUE THREAD

**Issue by tamird** [yarnpkg/yarn#2987]
I depend on [protobuf.js](https://github.com/dcodeIO/protobuf.js) which has [@types/node as an optional dependency](https://github.com/dcodeIO/protobuf.js/blob/c3f0a21/package.json#L60).

Is it possible to not have yarn include this optional dependency? How? I believe it is not possible, so this is a feature request in some sense.

If it is possible, this is a docs issue, since I could not find this answer.

**Comment by voxsim** [comment]
@tamird you should able to do that typing `yarn --ignore-optional` or something similar. I suggest you to see `yarn --help` for more info.

**Comment by tamird** [comment]
@voxsim that ignores first-order optional dependencies, but not optional dependencies-of-dependencies.

**Comment by bestander** [comment]
merging into https://github.com/yarnpkg/yarn/issues/2666
