### ISSUE TITLE
Yarn global only takes ls but not list

### ISSUE THREAD

**Issue by szhongren** [yarnpkg/yarn#3003]
I think this might be a small bug.

`yarn global list` returns `error Invalid subcommand. Try "add, bin, ls, remove, upgrade"`
`yarn global ls` works as expected.

Using yarn 0.21.3 with node 7.6.0 on Windows 10 Pro build 14393.953. I'd be happy to make a PR if someone can point me to instructions on running it from source with a debugger.

**Comment by sapegin** [comment]
Yeah, `yarn global ls` and `yarn list` are inconsistent.

**Comment by bestander** [comment]
I agree, send a PR.
We'll need to support ls for a while though with a warning that it goes away

**Comment by szhongren** [comment]
Are the command line args passed to commander? I'm having trouble tracing it in a debugger.
