### ISSUE TITLE
yarn install ignores absolute paths when resolving local scoped packages

### ISSUE THREAD

**Issue by zyrolasting** [yarnpkg/yarn#3015]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn install` resolves paths to scoped packages on the local filesystem using relative paths even when given an absolute path.

**If the current behavior is a bug, please provide the steps to reproduce.**
Note: Not on 0.23.x due to yum repo offering 0.21.3 as latest. This is observed in an upgrade from 0.16.1 to 0.21.3

Have a package.json like this

    {
      "name": "@scoped/mypackage",
      // <snip>
      "dependencies": {
        // also tried "file:/code/dep"
        "@scoped/dep": "file:///code/dep"
    }

And a file system like this

    /
        code/
            mypackage/
            dep/

yarn install in `mypackage` shows:

    error "/code/mypackage/code/dep" doesn't exist.
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**What is the expected behavior?**

Expecting behavior consistent with 0.16.1, where the absolute path `/code/dep` found in `file:///code/dep` (Note the three slashes) is treated as an absolute path, such that `/code/mypackage` can find package found in `/code/dep` for installation. 

**Please mention your node.js, yarn and operating system version.**
    node 6.9.0
    yarn 0.21.3
    Fedora 25

**Comment by bestander** [comment]
Contribution is welcome

**Comment by BYK** [comment]
No longer happening in the latest version of Yarn so closing.
