### ISSUE TITLE
Yarn in multiple folders at the same time causes error

### ISSUE THREAD

**Issue by zackify** [yarnpkg/yarn#3017]
Running yarn in multiple folders at once can sometimes fail  due to the way cache works:

```yarn --pure-lockfile
yarn install v0.20.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find a package.json file in "/home/deploy/.cache/yarn/npm-extract-text-webpack-plugin-2.1.0-69315b885f876dbf96d3819f6a9f1cca7aebf159"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: 1
```

**What is the expected behavior?**

Be able to run yarn in multiple folders at once that require the same modules

**Please mention your node.js, yarn and operating system version.**

node 7.6 ubuntu 16.04

**Comment by arcanis** [comment]
A fix would probably prevent you from running an install if another one is already running in the same directory, like what apt-get or similar are doing.

**Comment by zackify** [comment]
I'm not running the command in the same directory though. It is a different
directory that has the same dependencies. The reason is multiple sites run
the same codebase with just env changes.

**Comment by arcanis** [comment]
Sure, but they share the same cache. If one yarn process is writing into the cache while another is reading from it, bad things are going to happen, as you've experienced. A workaround that you can use right now is to use different cache paths (for example using `--cache-path`). A better solution would be to avoid running multiple Yarn processes at once :)

**Comment by zackify** [comment]
Thanks, guess I'll have to do that for now.
