### ISSUE TITLE
Machine-wide yarnrc file shouldn't have to live in NodeJS installation directory

### ISSUE THREAD

**Issue by herebebeasties** [yarnpkg/yarn#3021]
We'd like to be able to set the default registry (and other options) globally across all users on a machine. This is on Windows.

It seems this is sort-of supported, but only by dropping it into the NodeJS binary installation directory, which is neither intuitive, not very friendly to things like package managers. It would be great if we could drop this into the directory containing the `yarn.js` file itself.

It looks like this currently works via the `getPossibleConfigLocations` and `getGlobalPrefix` function in `npm-registry.js` which returns the `path.dirname` from `process.execPath` (i.e. node.exe). Could this be tweaked to also include a location alongside the `yarn.js` file?

**Comment by bestander** [comment]
You can put .yarnrc to C:\ drive and it should work.
Please reopen if it does not work
