### ISSUE TITLE
Yarn master (prerelease) version is not compatible with packages that require >= version of Yarn

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3029]
**Do you want to request a *feature* or report a *bug*?**
We cut branches and set current master branch with prerelease tag, e.g. 0.22.0-0.
This makes prevents Yarn from installing packages that have requirements for a min version of Yarn.
E.g. 
```
$ yarn add dgeni-packages@0.16.10
yarn add v0.23.0-0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error dgeni-packages@0.16.10: The engine "yarn" is incompatible with this module. Expected version ">=0.17.9".
```

This is a documented behavior of [semver package](https://github.com/npm/node-semver#prerelease-tags).
Although I think it is not intuitive and does not support our branching/release model so I think we should make this rule ignored.

**What is the expected behavior?**

```
$ yarn add dgeni-packages@0.16.10
yarn add v0.23.0-0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 222 new dependencies.
```

**Please mention your node.js, yarn and operating system version.**
This is a semver check issue in [current Yarn 0.23.0-0](https://github.com/yarnpkg/yarn/blob/master/src/package-compatibility.js#L69)

**Comment by BYK** [comment]
This should be fixed in recent versions so closing. @bestander feel free to reopen if I'm mistaken.
