### ISSUE TITLE
Configuring proxy through environment variables

### ISSUE THREAD

**Issue by felixfbecker** [yarnpkg/yarn#3034]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Proxy cannot be set through environment variables

**If the current behavior is a bug, please provide the steps to reproduce.**

Set environment variables `NPM_CONFIG_PROXY` or `YARN_PROXY` and `_HTTPS_PROXY`, `_STRICT_SSL`, respectively.

**What is the expected behavior?**
yarn should use the proxy

**Please mention your node.js, yarn and operating system version.**
node: 7.7.0
yarn: 0.22.0

**Comment by felixfbecker** [comment]
It appears that no matter what is set as the env var, it even _overrides_ the config file as `undefined`:
```
✔ ~ 
20:28 $ cat ./.yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


https-proxy "http://localhost:8090"
lastUpdateCheck 1491210346143
proxy "http://localhost:8090"
✔ ~ 
20:32 $ yarn config get proxy
http://localhost:8090
✔ ~ 
20:32 $ export YARN_PROXY=http://localhost:8090
✔ ~ 
20:32 $ yarn config get proxy
undefined
```

**Comment by bestander** [comment]
You can set up env variables through .yarnrc now https://github.com/yarnpkg/yarn/pull/3218

**Comment by felixfbecker** [comment]
Maybe I am misunderstanding that feature, but this is about configuring settings like the proxy with env vars _instead of_ .yarnrc, not the other way around

**Comment by bestander** [comment]
And you can do vice versa.

If you pass an env var `yarn_something` then it will configure `something` that is read via `getOption()` in https://github.com/yarnpkg/yarn/blob/master/src/config.js.

This feature needs documentation at https://yarnpkg.com/en/docs/configuration, would be really great if someone sent a PR

**Comment by felixfbecker** [comment]
But that was supposed to be the case before the linked PR, wasn't it?
It doesn't work as expected

**Comment by bestander** [comment]
Seems to work on latest master

```
bestander-mbp:sta bestander$ cat .yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


https-proxy "http://localhost:8090"
lastUpdateCheck 1491210346143
proxy "http://localhost:8090"
bestander-mbp:sta bestander$ yarn config get proxy
http://localhost:8090
bestander-mbp:sta bestander$ yarn_proxy=http://localhost:8091 yarn config get proxy
http://localhost:8091
```

**Comment by felixfbecker** [comment]
👍

**Comment by burkhardr** [comment]
@bestander Am I right in assuming that this wouldn't work for options like `--install.offline true` since `yarn_--offline-cache=true yarn` wouldn't be valid env var syntax?

I want my CI to only use my offline mirror. Any suggestions?

**Comment by felixfbecker** [comment]
@burkhardr I think the env var for that would be `YARN_OFFLINE_CACHE`

**Comment by bestander** [comment]
@burkhardr, I think `--offline` is configured only as a CLI argument.
So `--install.offline true` in .yarnrc should force this flag for you, that should be enough to force offline mirror.

**Comment by burkhardr** [comment]
@felixfbecker I can't find any documentation or code reference for an `offline-cache` option. Where did you find that?

@bestander Yeah, that's what I was doing initially, but I don't want to run this locally (only on CI/heroku), that's why I was looking for an env var solution.

What I've tried so far:

```bash
YARN_OFFLINE_CACHE=true yarn # doesn't do anything
```

```bash
 env "yarn_--install.offline=true" yarn # seems to parse into '--install': { offline: true } }... so close!
```

If it was just on the CI, I could simply append `--install.offline true` to `.yarnrc` during build, but since it also needs to work on heroku (via `git push`), that's unfortunately not an option.

**Comment by bestander** [comment]
It might need a code change then.
This https://github.com/yarnpkg/yarn/blob/master/src/config.js#L305 needs
to be more like this
https://github.com/yarnpkg/yarn/blob/master/src/config.js#L260

**Comment by felixfbecker** [comment]
@burkhardr In your comment 😄 

> since yarn_--offline-cache=true yarn wouldn't be valid env var syntax

**Comment by burkhardr** [comment]
@bestander Just been digging a little further. Without knowing the yarn cache in detail, this looks tricky at the moment because the `this.registry` gets built in https://github.com/yarnpkg/yarn/blob/master/src/config.js#L222, after `_init` is being called.
