### ISSUE TITLE
Publishing a package

### ISSUE THREAD

**Issue by psingl** [yarnpkg/yarn#3036]
While publishing a package on npm through yarn, I am facing the same problem each time. The process just stops at Publishing. I mean to say that it does not show any error or something else but it just keeps on showing me Publishing... When I tried to publish same package through npm it just took seconds. Please check out if there is some issue in yarn.

**Comment by ecbrodie** [comment]
Perhaps related to #1694?

**Comment by gsklee** [comment]
@bestander close

Without further information, it would be hard to actually act upon this issue.
