### ISSUE TITLE
Prompt for github credentials overwritten on yarn install

### ISSUE THREAD

**Issue by adamrmelnyk** [yarnpkg/yarn#3038]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

when using `yarn install` with a private repo included in the package.json yarn prints the status bar over two lines and appears to hang because it's waiting for your github credentials but overwrites the message.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using a private repo in your package json such as:
```
"my-private-repo": "git+https://github.com/myOrg/my-private-repo.git#1.0.0",
```
then yarn install. yarn asks for your github credentials but overwrites this with the status bar then appears to hang on the last package, or however many private packages you have. whenever it hits the private package it prints that it needs your github username and password however it is quickly overwritten by the status bar again. making it difficult to determine what yarn wants you to do.

![yarn_bug](https://cloud.githubusercontent.com/assets/6963287/24664609/beec0e38-1920-11e7-96fc-7e25cc00746e.gif)

It also appears that it is asking you for your github credentials for each private repo listed in your `package.json` which is why you see it printing on a new line twice in the gif.

**What is the expected behavior?**

not to overwrite the messages to the user.

**Please mention your node.js, yarn and operating system version.**
node v4.3.2
yarn 0.21.3
OS X 10.11.6
iTerm 3.0.15

**Comment by matthieuh** [comment]
Use this syntax instead : "git+ssh://git@github.com/xxx/xxx.git"

**Comment by adamrmelnyk** [comment]
@matthieuh we have switched this yes, but that doesn't really resolve the issue.

**Comment by bestander** [comment]
We are tracking all git related issues now

**Comment by BYK** [comment]
We are not planning to allow user prompts during installation so closing.

**Comment by monim67** [comment]
So we cannot add packages from private git repository using yarn???
