### ISSUE TITLE
Syncing Debian Repository http://dl.yarnpkg.com/debian/

### ISSUE THREAD

**Issue by ErikOlufson** [yarnpkg/yarn#3044]
Hi guys,

our developers are using yarn for their daily business and it is standard to mirror remote repositories to minimize traffic and ensure offline availability.

For normal Debian repositories we are using apt-mirror. Those are our connectionstrings:
```
# cat /etc/apt/mirror.list
[...]
deb-amd64 http://dl.yarnpkg.com/debian/ stable main 
deb-i386 http://dl.yarnpkg.com/debian/ stable main
[...]
```

Unfortunately apt-get on our desktop clients reports missing all-binaries.
```
# apt-get update
[...]
E: Fehlschlag beim Holen von http://internalmirror.fqdn.de/mirror/dl.yarnpkg.com/debian/dists/stable/main/binary-all/Packages  404  Not Found
[...]
```
This behavior is already known from other repositories mirrored by us. In those cases we use rsync. But dl.yarnpkg.com does not offer rsync for mirroring. So thats exactly what I ask for. Could you offer rsync for syncing?

Thanks in advance,

Erik

**Comment by Daniel15** [comment]
Are you able to use Git rather than rsync? The entire package repository is available as a Git repo. You can run this command to get a copy of the repo:
```
git clone https://github.com/yarnpkg/releases.git yarn-releases
```

**Comment by Daniel15** [comment]
Are you able to use Git rather than rsync? The Yarn repository is available as a Git repo. You can run this command to get a copy of the repo:
```
git clone https://github.com/yarnpkg/releases.git yarn-releases
```

And then periodically run `git pull` to get the latest changes.

Also for what it's worth, I'm using `apt-cacher-ng` and don't have any issues with hitting the Yarn repo. I have apt-cacher-ng configured as a proxy server.

**Comment by bovi** [comment]
@ErikOlufson I think you should use ```deb-all http://dl.yarnpkg.com/debian/ stable main``` to get binary-all

**Comment by Daniel15** [comment]
Closing issue as it's stale. Let me know if you still need help with this.
