### ISSUE TITLE
Yarn bug with script chaining after third level

### ISSUE THREAD

**Issue by fhewitt** [yarnpkg/yarn#3049]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Yarn script chaining is broken and throw an error as soon as it reach third levels.

> An unexpected error occurred: "Cannot create property '-registry-npmjs-org-' on string '{\"-registry-npmjs-org-\":\"\"}'".

This render the script mechanism nearly useless in any serious project.

**If the current behavior is a bug, please provide the steps to reproduce.**

Simply add these scripts into the package.json, no dependency required
```
"scripts": {
    "play": "yarn run step",
    "step": "yarn run end",
    "end": "echo \"Should be echoed!\""
}
```

- `yarn run end` works correctly
- `yarn run step` works correctly
- `yarn run play` fails with aforementioned error

**What is the expected behavior?**

Yarn should be able to run reasonably long (>10 depth) script chain.

**Please mention your node.js, yarn and operating system version.**
node 6.10.0
yarn 0.21.3
Window 10 Pro, 64 bits
Git Bash 4.3.46(2)-release (x86_64-pc-msys)

**Comment by fhewitt** [comment]
My colleague with essentially the same computer configuration does not encounter the issue. So it's probably something very specific with my npm / node / bash shell installation. I suppose i'm due for a formatting and I close the issue.

**Comment by fhewitt** [comment]
If anyone else encounter the issue and find this ticket, my temporary workaround is to use yarn-run-all (which is by the way an awesome tool).

**Comment by f-roland** [comment]
I have encountered this as well on mac os 10.13, node 8.9.0, yarn 1.2.1

**Comment by electrotype** [comment]
I also encountered this exact error. Windows 10, node 8.9.0, yarn 1.3.2 .

**Comment by James-E-Adams** [comment]
Same here, when spawning a sync command using `cross-spawn`.

**Comment by tcschiller** [comment]
I just ran into this issue and found the problem.

Check your `npm config list`. If you see a property for `registry-npmjs-org`, run `npm config delete registry-npmjs-org`. (Unless you really need it, of course - but I'm guessing you don't).

That cleared up our issue. No clue though how the rogue config property was created in the first place, though.

**Comment by yasinuslu** [comment]
Has anyone found a workaround for this problem besides deleting the registry ? Unfortunately we cannot delete it.

**Comment by muzea** [comment]
Also encountered this problem
node version: v10.15.3
CentOS release 6.8 (Final)
yarn v1.12.3

**Comment by JiangLiruii** [comment]
`npm config list` this command line will show you whether use .npmrc. if use, delete it. typically in user root.

**Comment by light0x00** [comment]
here is my solution:

1.  run `yarn config list`  to check your yarn config,  if it has the wrong format, e.g:

```
{
 '//registry.npm.taobao.org/:username': 'light0x00',
  'scripts-prepend-node-path': true,
}
```

delete the  wrong format configuration, It could be in path `~/.yarnrc` or path `~/.npmrc`.
