### ISSUE TITLE
About colors in `yarn upgrade-interactive`

### ISSUE THREAD

**Issue by xareelee** [yarnpkg/yarn#3054]
I notice that yarn paints the module names with red and yellow colors, but I don't know what it means:

![screen shot 2017-04-06 at 22 47 28](https://cloud.githubusercontent.com/assets/804308/24760718/0f470cf0-1b1c-11e7-9691-fcfa9d8c2c51.png)

I did not find a doc about this. Could you explain the red/yellow meaning?

**Comment by SimenB** [comment]
red you would get with a `yarn upgrade` (because it matches semver range in package.json), while yellow is a semver incompatible upgrade

**Comment by xareelee** [comment]
@SimenB Thanks for your reply.

Is it possible that adding this info in the CLI?

**Comment by jaydp17** [comment]
or should be there in the docs.
https://yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

**Comment by uwuru** [comment]
It is shown at the top of the output when your run `yarn upgrade-interactive --latest`:

<img width="787" alt="Screenshot 2022-01-07 at 18 04 42" src="https://user-images.githubusercontent.com/40305936/148587267-9051e5e4-a386-4a0e-8e53-9df40da0442f.png">
