### ISSUE TITLE
yarn upgrade git devDependency results in rebuilding all packages

### ISSUE THREAD

**Issue by sandlerr** [yarnpkg/yarn#3061]
Hi yarn maintainers,
Thanks for the rapid stream of improvement in this excellent tool, and thanks in advance for reading over this issue!

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Running `yarn upgrade myModule` where myModule is a git devDependency results in `Rebuilding all packages...`

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
mkdir testapp
yarn init # follow the prompts
yarn add -D 'git+https://github.com/jashkenas/underscore.git#master'
yarn add -D phantomjs-prebuilt
yarn upgrade underscore
# see Rebuilding all packages in the output
```

**What is the expected behavior?**
If I understand the intention correctly, only changed packages should be rebuilt.

**Please mention your node.js, yarn and operating system version.**
yarn version: `v0.24.0-20170406.2230`
reproduced on node 7.6.0 and 5.10.1 on macOS current and travis-ci trusty environment

**Comment by sandlerr** [comment]
@Daniel15 could you please take a look over this issue?

**Comment by magiclen** [comment]
I have the same problem. Yarn should not rebuilt the existed modules which are not upgraded this time. It's too waste of time.

**Comment by davidrobin** [comment]
Same issue here, when I do an upgrade, ALL packages are being rebuilt, that is for sure a waste of time and efficiency.

**Comment by pgnd** [comment]
similarly, with a number of git deps,

```
yarn -V
	0.27.2
node -v
	v8.1.3
lsb_release -rd
	Description:    openSUSE Leap 42.2
	Release:        42.2

cd {project}
yarn upgrade
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	[4/4] Rebuilding all packages...
	[-/5] ⠐ waiting...
	[-/5] ⠐ waiting...
	[-/5] ⠐ waiting...
	...
```

'rebuild' occurs on every repetition.

**Comment by somebee** [comment]
This is quite annoying - and still happening on v0.27.5. Any solutions?

**Comment by merceyz** [comment]
Closing as fixed in v2 where the tracking of what needs to be rebuilt has been greatly improved

https://yarnpkg.com/getting-started/migration
