### ISSUE TITLE
yarn upgrade github:user/repo doesn't update yarn.lock commit

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#3066]
1) Install package from github repo:
`$ yarn add github:user/package#branch`
In package.json it will add
`package-name: github:user/package#bracnh..`
In `yarn.lock` it will fixate commit:
`resolved "https://codeload.github.com/user/package/tar.gz/commit123`

2) Then after git repo updated (commits added) want to upgrade this package to latest version:
`$ yarn upgrade github:user/package#some-commit` (or `yarn add` does the same) 
It will install the latest version from git, **but will not change resolved commit in yarn.lock** - so next installation or `yarn --force` will reinstall commit fixed in yarn.lock

3) Workaround for upgrade:
`$ yarn remove package-name`
`$ yarn add github:...`

4) If to run just `yarn upgrade` (without specifying the package) it will install the latest version from git and **will update yarn.lock** (but it is not always need to upgrade all packages)

5) `yarn upgrade package-name` will try to install package from NPM, not git though in current package.json manifect there is `package-name: github:user/package#bracnh..`

Think, those inconsistencies should be fixed, I aso think 5) if you do `yarn upgrade package-name` in this case it should upgrade from git repo, not try to get to NPM.

**Comment by juanca** [comment]
What about `yarn upgrade <...> --force`? 

Also, if you're on v0.22.0+ then you can just `yarn upgrade <package name>` and it will pick up the github URL and add `--force` for ya.

**Comment by whitecolor** [comment]
Ok cool, with 0.22 it works as expected, that is funny I seem to me I upgraded yarn globally from npm before I tested and it was only 0.23.1, now it is 0.22.

**Comment by whitecolor** [comment]
@juanca hm I checked it now and on 0.22 `yarn upgrade package-name` pulls version from npm and replaces it in package.json. does this work for you another way?

**Comment by juanca** [comment]
Commented on your [new issue](https://github.com/yarnpkg/yarn/issues/3095).
