### ISSUE TITLE
Cannot find module './doc/workbook'

### ISSUE THREAD

**Issue by juliocanares** [yarnpkg/yarn#3072]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

While installing exceljs it fails with the following error : Cannot find module './doc/workbook'

**If the current behavior is a bug, please provide the steps to reproduce.**

Try to install using `yarn install` the  [exceljs](https://www.npmjs.com/package/exceljs) package

**What is the expected behavior?**

[exceljs](https://www.npmjs.com/package/exceljs) to be correctly installed

**Please mention your node.js, yarn and operating system version.**

`v7.3.0`

**Comment by svaj** [comment]
Hey @juliocanares, I just noticed that I ran into this issue (though it installed fine, it errored on usage) and was able to resolve it by ensuring .yarnclean did not remove `doc` directories.  You might want to check your .yarnclean file.
