### ISSUE TITLE
yarn install --mutex file:/tmp/.yarn-mutex --production hangs

### ISSUE THREAD

**Issue by majgis** [yarnpkg/yarn#3076]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**
hangs on `yarn install --mutex file:/tmp/.yarn-mutex --production`

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn install --mutex file:/tmp/.yarn-mutex  # This works`
`yarn install --mutex file:/tmp/.yarn-mutex --production # This hangs`

I'm investigating now to boil it down to an example project, but if anyone has tips in the meantime, I'm all ears.

**What is the expected behavior?**
yarn never hangs, it either reports an error or completes normally

**Please mention your node.js, yarn and operating system version.**
centos 6.7
yarn v0.23.0 (v0.21.3 and v0.22.0 also tested)

**Comment by pszalanski** [comment]
I can confirm it is hanging with `--mutex`. It does not matter if it's a file or a network mutex.

At our company we use a custom build script written in Python, which launches a bunch of yarn instances with Popen. Sometimes, the yarn process simply stops its work and nothing happens until the process is killed.

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where the timeout and mutex logic has greatly improved.

https://yarnpkg.com/getting-started/migration
