### ISSUE TITLE
Sub module its not upgraded only the requested module in the command 

### ISSUE THREAD

**Issue by OmerHerera** [yarnpkg/yarn#3082]
Looks like a bug or maybe I'm misunderstanding something

**What is the current behavior?**
* When running `yarn upgrade` in project that have already `yarn.lock`, will upgrade only the module in the command, and not upgrading the sub-modules,

**If the current behavior is a bug, please provide the steps to reproduce.**

Lets say I have `module` lets call it `module-0`and inits `package.json` has
```
"dependencies": {
    "@organization/module-a": "^1.0.0"
  }
```

In the `package.json` for the `module-a` has 
```
"dependencies": {
    "@organization/module-b": "^1.0.0"
  }
```

So the dependencie looks like:
`module-0`->`module-a`->`module-b`

Now lets says that `module-a` and `module-b` have new versions

Now I run `yarn upgrade @organization/module-a`

**What is the expected behavior?**
I expect `module-a` and `module-b` will be upgrade `module-a` because I asked and `module-b` because its the sub-module

**Please mention your node.js, yarn and operating system version.**
`OsX El Capitan 10.11.6`
`node v6.10.0`
`yarn 0.22.0`

**Comment by bestander** [comment]
Yarn may try to optimize the dependency list and sometimes will not force updating subdepdendencies.
These RFC could be interesting https://github.com/yarnpkg/rfcs/pull/71 https://github.com/yarnpkg/rfcs/pull/54
