### ISSUE TITLE
installationMethod not updated properly in master

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#3085]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn's `package.json` contains an `installationMethod` key for determining the installation method that was used to install Yarn. This is used so we know which command to suggest to upgrade Yarn.

This used to work correctly as `package.json` was sitting alongside Yarn itself and it did `require('./package.json')`, but now that the standalone .js file is included in the tarball, `package.json` is bundled into the JS file and thus updating `package.json` doesn't work to update the installationMethod. Potentially Yarn should still load `package.json` (but be careful to not break running the standalone .js file separately.

**Comment by pornel** [comment]
This might be breaking homebrew:

```sh
$ brew install --HEAD yarn
```

> Checking out branch master
> Error: inreplace failed
> /usr/local/Cellar/yarn/HEAD-cd58df8/libexec/package.json:
  expected replacement of "\"installationMethod\": \"tar\"" with "\"installationMethod\": \"homebrew\""

**Comment by Daniel15** [comment]
Might be the case, however we do not make any guarantees about master being
usable/stable, and the current stable branch and current RC branch should
both work at the moment.

Sent from my phone.

On Apr 10, 2017 8:38 AM, "Kornel" <notifications@github.com> wrote:

This might be breaking homebrew:

$ brew install --HEAD yarn

Checking out branch master
Error: inreplace failed
/usr/local/Cellar/yarn/HEAD-cd58df8/libexec/package.json:
expected replacement of ""installationMethod": "tar"" with
""installationMethod": "homebrew""

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/issues/3085#issuecomment-292987924>, or mute
the thread

**Comment by Daniel15** [comment]
@pornel - Thinking about that more, installing from Git (eg. from HEAD) via Homebrew will never work, as it's just the raw code rather than the compiled code. If you want to get the very latest version of Yarn, `https://nightly.yarnpkg.com/latest.tar.gz` will work to get a tarball of the latest master. This tarball is built in exactly the same way as we build stable releases, so it should work with Homebrew too.
