### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by Sudeethar** [yarnpkg/yarn#3087]
**Which operating system are you using:**
win8

**Please describe the steps you took when trying to install Yarn and what went wrong:**
1 step > node.js install (v 6.10.2)
2 step > yarn install (v0.22.0)

wrong > yarn version command not working in command prompt

**Comment by 1j01** [comment]
If `yarn` isn't available as a command, see https://github.com/yarnpkg/yarn/issues/1648

**Comment by bawstudios** [comment]
Ok bro, step 3
Add in environnement variable of your System
name of variable : yarn
content : "C:\Program Files (x86)\Yarn\bin" // path to your installation folder

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
