### ISSUE TITLE
Yarn not install dependencies correctly

### ISSUE THREAD

**Issue by mark86092** [yarnpkg/yarn#3099]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Prepare a `package.json`

```
{
  "dependencies": {
    "request": "^2.81.0"
  },
  "devDependencies": {
    "co": "^4.6.0"
  }
}
```

Run `NODE_ENV=production yarn install`

Expect `co` still install as dependency of `request`, but not

![image](https://cloud.githubusercontent.com/assets/1908007/24889933/86efff2e-1e9f-11e7-914b-0ff14537be72.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Prepare package.json in your folder (only this file)

```
{
  "dependencies": {
    "request": "^2.81.0"
  },
  "devDependencies": {
    "co": "^4.6.0"
  }
}
```
![image](https://cloud.githubusercontent.com/assets/1908007/24889869/32a417e8-1e9f-11e7-853c-099eb8897abc.png)

2. Run `NODE_ENV=production yarn install`

![image](https://cloud.githubusercontent.com/assets/1908007/24889896/5170719e-1e9f-11e7-9ce1-45f7f5ecab6a.png)

3. Run a `node`, and `require('request')` fails

![image](https://cloud.githubusercontent.com/assets/1908007/24889933/86efff2e-1e9f-11e7-914b-0ff14537be72.png)

**What is the expected behavior?**

I install via `NODE_ENV=production npm install`

![image](https://cloud.githubusercontent.com/assets/1908007/24889991/d3bcdbc4-1e9f-11e7-8e3a-f7e9f4c4bc56.png)

Run a `node`, and `require('request')` works

![image](https://cloud.githubusercontent.com/assets/1908007/24889994/dd293cd4-1e9f-11e7-9a78-7bc78e68a354.png)

**Please mention your node.js, yarn and operating system version.**

node: v7.8.0
yarn: 0.22.0
os: mac

and tested on

node: v6.10.0
yarn: 0.21.3
os: linux ubuntu 16.04.2

tested on docker, too

![image](https://cloud.githubusercontent.com/assets/1908007/24890081/5f6f26a4-1ea0-11e7-8c15-a9522c57b418.png)

other information

![image](https://cloud.githubusercontent.com/assets/1908007/24890239/3b2daaf8-1ea1-11e7-855c-fea76b40f05d.png)

I'm not sure whether I misunderstand `NODE_ENV` or not, but the current behavior forces me to move the `co` to my production dependencies

If duplicated, close this

Thanks you for reading

**Comment by hackape** [comment]
This is actually a FEATURE™ not a bug, read [here](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production). But I was preparing to file same issue like you, @mark86092 bro. This is clearly over designed. 

Please, yarn team, consider remove this feature, just keep the `--prod` flag that's enough.

**Comment by vizath** [comment]
Can you try with `0.23.1`? see https://github.com/yarnpkg/yarn/pull/2921

**Comment by mark86092** [comment]
Great, thanks @vizath
