### ISSUE TITLE
ENOENT: no such file or directory (on Docker)

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/yarn#3104]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn fails to install a package dependencies raising:
```
Error: https://registry.yarnpkg.com/babel-cli/-/babel-cli-6.24.0.tgz: ENOENT: no such file or directory, open '/root/.cache/yarn/v1/npm-babel-cli-6.24.0-a05ffd210dca0c288a26d5319c5ac8669a265ad0/.yarn-tarball.tgz'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/FezVrasta/docker-yarn-lerna-bug

**What is the expected behavior?**
The command should work just fine.

**Please mention your node.js, yarn and operating system version.**
node 7.5.0
Yarn 0.20.3 (and 0.24@fb40251c5b10bf3b43eed2daaaab53a1aab86f31)

**Comment by bestander** [comment]
Is it a docker only problem?
Can this be reproduced with lerna only?

**Comment by FezVrasta** [comment]
On lerna side, they fixed it with [this approach](https://github.com/lerna/lerna/issues/752#issuecomment-293313797), but I think Yarn should find a way to allow simultaneous instances to run.

**Comment by BYK** [comment]
Yarn now supports a `--mutex` option to prevent this from happening so closing.
