### ISSUE TITLE
Can't install a single file

### ISSUE THREAD

**Issue by oliveiraev** [yarnpkg/yarn#3107]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I Can't perform an ```yarn add https://code.jquery.com/jquery-%version%.min.js```

**What is the expected behavior?**
I would love to download the built-minified-single-file instead of the full repo and perform an additional step with webpack/gulp/grunt/node/shellscript/flag-semaphore

**Please mention your node.js, yarn and operating system version.**
```
$ yarn --version
0.22.0
$ node --version
v7.8.0
$ uname -a
Linux wheeljack 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
```

**Comment by megamit** [comment]
This kind of behavior is well suited to a post/pre install script which fetches these other dependencies.
You could also use bower for this.

**Comment by oliveiraev** [comment]
Yes, I know about Bower. Bower is recommending Yarn now. And you is recommending Bower, which is kinda frustrating.

I got that Yarn installed packages are intended to be ```require()```d as node modules just like npm packages but, to consider yarn as a Bower replacement, it also needs to provide Bower features and this is a missing one.

**Comment by bestander** [comment]
This is not currently supported.
For a single file you can use a tool like wget or curl, Yarn is not necessary.

**Comment by mig82** [comment]
I have a similar use case. I'm trying to use Yarn to download dependencies into a project that runs Javascript in a mobile app. Keeping those packages small is of the essence. So downloading everything in an NPM package is not a good idea. Instead I'd prefer a single file from the project's Git repo or CDN, in which case a `url:` protocol makes sense —which is not that different from the `file:` protocol that's already supported. Same use case applies to working with Lambdas. In either case you want to keep your dependencies as small as possible.
