### ISSUE TITLE
Yarn should automatically install node-gyp if needed

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#3114]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The bundled .js version of Yarn (which is now used in all the other installers) doesn't include node-gyp, resulting in errors like this:

```
error C:\temp\license-test\node_modules\libalac: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\temp\license-test\node_modules\libalac
Output:
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.
```

This was already an issue with the standalone .js build, but it'll be an issue with other builds now that we use the standalone .js file everywhere.

Rather than bundling node-gyp with Yarn (like we did before), we should probably run `yarn global add node-gyp` to install it when needed.

Repro:
```
yarn init
yarn add nodetunes
```

**Comment by Daniel15** [comment]
@bestander - Looks like we do indeed need `node-gyp` and my original testing (where it worked fine) was wrong somehow. To me, the best solution is to run `yarn global add node-gyp` automatically if needed. What do you think?

Let's get this fixed before the next RC.

**Comment by bestander** [comment]
Yeah, let's do this.

**Comment by Daniel15** [comment]
By the way, I think I worked out why the other package I tested worked with
no error: If a package declares node-gyp as a dependency, it should work
fine. It's just packages that need node-gyp but don't declare it as a
dependency (ie. they implicitly expect it to be available) that break.

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>

**Comment by bestander** [comment]
My only concern if users will be prompted for elevates permissions when
installing node-gyp globally.

**Comment by Daniel15** [comment]
Elevation shouldn't be needed as global packages should always be installed
in a directory they're able to access. I know there's currently a bug on
Windows where it tries to install global packages into the Program
Files\Node.js directory, but that's a bug that needs to be fixed :)

**Comment by bestander** [comment]
What about when people need to install node-gyp globally for another reason?
Could it interfere with Yarn's needs?
What if node-gyp has breaking changes and we need to upgrade it?

I feel uncomfortable with pieces of Yarn being in isolated global places.
