### ISSUE TITLE
Yarn (0.22.0) fails at installing gulp-sass/node-sass in offline environment

### ISSUE THREAD

**Issue by maelgrove** [yarnpkg/yarn#3116]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When attempting to install **gulp-sass** (or **node-sass** respectively) in an environment without internet connection (from tarballs), the installation fails because **node-sass** is unable to fetch the platform binding binaries from the github repo. The **node-sass** install script continues by attempting to build the binaries itself, but this might fail too if certain dependencies are missing (**python** etc.).

This behavior is not directly related to **yarn** itself, but with **npm**, one could simply copy the necessary files from https://github.com/sass/node-sass/releases into `./node_modules/node-sass/vendor/<platform>_<version>` and run `npm install` again.

However, when running `yarn install` again, **yarn** seems to nuke the **node-sass** folder completely, including the manually added file.

I also attempted to set the environment variables both in *.npmrc* and via cmd args as described here: https://github.com/sass/node-sass#binary-configuration-parameters, however **yarn** seems to completely ignore both of them (installer script still attempts to connect to the interwebs etc..)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Init fresh **yarn** project
2. Setup **yarn** offline mirror as described here: https://yarnpkg.com/lang/en/docs/offline-mirror/
3. Install **node-sass** (or **gulp-sass**) 
4. Delete `./node_modules/`
5. Disable internet connection
6. Attempt to install packages again w/ `yarn install`

**What is the expected behavior?**

Either...

* Yarn accepts module specific command line arguments (?)

or...

* Yarn keeps custom changes made to `./node_modules/` when running `yarn install`

**Please mention your node.js, yarn and operating system version.**

    OS:        Windows 10 x64
    Node.js:   6.10.2
    npm:       3.10.10
    yarn:      0.22.0

**Comment by ericberens** [comment]
Not ideal but you could use the `--ignore-scripts` flag

> --ignore-scripts                  don't run lifecycle scripts

`yarn install --ignore-scripts`

then manually copy in the binaries. This may have undesired side effects if you rely on lifecycle events.

**Comment by bestander** [comment]
Caching binary files across projects will cause other problems, e.g. sometimes binaries imprint project paths during compilation, so they can't be shared across projects.

The right way would be to make Yarn work with those gyp/sass packages that need complex install steps and allow them to be configured.
Actually you can pass configs vai .npmrc/.yarnrc to the install scripts https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js#L90, it just needs to be named properly.

**Comment by saper** [comment]
The problem here that packaged .tgz files are not ABI-dependent and there is no way for the binding to say "I have produced those binary artifacts for platform X, please package them in".

**Comment by maelgrove** [comment]
@bestander

Would it be possibilty to provide a flag for `yarn install` for the second option, causing yarn not to remove modified files?

**Comment by bestander** [comment]
@maelgrove, everything is possible.
But adding more flags for more use cases is not the right way to do it, this makes Yarn more complex and harder to maintain.
Feel free to help the project and invest some time to making it right.

**Comment by BYK** [comment]
Closing in favor of #3642.
