### ISSUE TITLE
[0.22] Problem using 'yarn run' on windows in paths with spaces

### ISSUE THREAD

**Issue by mreishus** [yarnpkg/yarn#3119]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

```
C:\Users\myusername\Documents\Visual Studio 2015\Projects\MyProject\SubDir
λ yarn run flow init
yarn run v0.22.0
$ "C:\Users\myusername\Documents\Visual Studio 2015\Projects\MyProject\SubDir\node_modules\.bin\flow" init
'C:\Users\myusername\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

To make it work, I can add this to my package.json file:
`scripts: { "flow": "flow" }`

Unfortunately now I have to use -- to pass arguments, but it works:

```
C:\Users\myusername\Documents\Visual Studio 2015\Projects\MyProject\SubDir
λ yarn run flow -- init
yarn run v0.22.0
$ flow init
Done in 0.93s.
```

**What is the expected behavior?**
`yarn run flow init` works without a "flow" script specified.

**Please mention your node.js, yarn and operating system version.**
yarn: 0.22.0
node: 7.7.4
windows: 7
powershell: 5.0.10514.6

**Comment by BYK** [comment]
I think this is fixed or will be fixed by https://github.com/yarnpkg/yarn/pull/4135

**Comment by mreishus** [comment]
This is fixed now - thanks
