### ISSUE TITLE
Cannot download msi installer - no such file or directory

### ISSUE THREAD

**Issue by crh225** [yarnpkg/yarn#3131]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
Go to this page https://yarnpkg.com/en/docs/install
click download
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
the download works
**Please mention your node.js, yarn and operating system version.**
N/A

**Comment by crh225** [comment]
It cannot find https://github.com/yarnpkg/yarn/releases/download/v0.23.2/yarn-0.23.2.msi

**Comment by jcphlux** [comment]
I am also having this issue.

**Comment by amites** [comment]
there is no msi listed for 0.23.2
https://github.com/yarnpkg/yarn/releases/


latest msi release is 0.23.1
https://github.com/yarnpkg/yarn/releases/download/v0.23.1/yarn-0.23.1.msi

**Comment by twhitbeck** [comment]
Why is 0.23.2 msi missing? Links on the website or broken as well as link in the cli

**Comment by Daniel15** [comment]
Sorry about that, this should be fixed now. The 0.23.2 build failed due to some flaky unit tests, which resulted in the Windows installer not being attached to the release. We're working on making this better.
