### ISSUE TITLE
401 Errors installing packages from Artifactory with v0.23.2

### ISSUE THREAD

**Issue by denniswebb** [yarnpkg/yarn#3136]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Attempting to install packages from Artifactory using v0.23.2 of yarn results in a 401 error being returned from Artifactory.  This error does not occur with v0.22.0 and earlier.

**If the current behavior is a bug, please provide the steps to reproduce.**
Configure ~/.npmrc with the authentication token from Artifactory.
Change the default registry using `yarn config set registry https://<redacted>.jfrog.io/<redacted>/api/npm/npm-virtual -g`
run `yarn --verbose --pure-lockfile`

**What is the expected behavior?**
All packages are downloaded and installed.  This works perfect if ran with yarn v0.22.0

**Please mention your node.js, yarn and operating system version.**
Node 6.95
Yarn v0.23.2
Alpine Docker image

**Comment by briice** [comment]
I can confirm, we have the same issue. We're downgrading to v0.22.0-1 in the meantime.

**Comment by kayneb** [comment]
Can confirm, our builds started breaking inexplicably. A couple of hours of investigation uncovered an unintended version bump to this new version.

**Comment by Daniel15** [comment]
Thanks for the bug report! Would you please be able to do us a favour and try older release candidate versions? We have 0.23.1 and 0.23.0 available. This will help narrow down the range of changes that could have caused this.

If you want to be really awesome, you could bisect and find the exact commit that broke it 😃

**Comment by bestander** [comment]
Could be this https://github.com/yarnpkg/yarn/commit/c92411d8540001f6f4043b17d7d38c58301e9640

**Comment by denniswebb** [comment]
I did try v0.23.0 and it also failed with 401 errors.

**Comment by Daniel15** [comment]
@bestander  - That's likely. The current accept header will fail any requests that can not provide that data type. The accept header can have multiple comma-separated MIME types so you should be able to use `application/vnd.npm.install-v1+json, application/json` or something similar.

**Comment by denniswebb** [comment]
By brute force attempts on Circle artifacts, I have discovered the commit that broke artifactory for us is d093c6cc1d2e28d906e0972b1d9a5ad5cd757bff
I'm running yarn during my docker build process and it runs as root.

**Comment by denniswebb** [comment]
And to elaborate on the fix, moving `.npmrc` from `/root/.npmrc` to `/usr/local/share/.npmrc` or `<PROJECT_DIR>/.npmrc` fixes the 401 errors.
