### ISSUE TITLE
0.23.2 is missing on npm

### ISSUE THREAD

**Issue by xaka** [yarnpkg/yarn#3148]
<img width="358" alt="screen shot 2017-04-14 at 8 26 01 am" src="https://cloud.githubusercontent.com/assets/504813/25047511/021070f0-20ec-11e7-9fe4-91c204b4a795.png">

**Comment by tobymurray** [comment]
Just out of curiosity, where are you seeing this? I went to look and found https://www.npmjs.com/package/yarnpkg has `0.15.1 is the latest of 3 releases`

**Comment by SimenB** [comment]
It's there, just not marked as latest.
```sh-session
$ npm dist-tags ls yarn
latest: 0.22.0
rc: 0.23.2
```

So you can do `npm i -g yarn@rc` to get it. Note that installing from npm is deprecated though, you should use your OS' package manager

**Comment by JayAndCatchFire** [comment]
FWIW, my use case for installing via npm is because that's the only way to do it if you're using nvm to manage your node installations. If you install yarn via your OS package manager, the package manager version of node is set as a dependency, so that clashes with nvm.

**Comment by Daniel15** [comment]
> If you install yarn via your OS package manager, the package manager version of node is set as a dependency, so that clashes with nvm.

Which operating system are you using? On Debian/Ubuntu, you can install Yarn without installing Node.js (ie. use the nvm installed Node.js) by using the `--no-install-recommends` flag to `apt-get`.

**Comment by JayAndCatchFire** [comment]
I didn't know that about Ubuntu.  Thanks for the tip.  However, I use OSX and Homebrew at work.  :slightly_frowning_face:

**Comment by xaka** [comment]
> It's there, just not marked as latest.

That explains the situation. Thanks @SimenB. 

I also found that one of projects specified `yarn` version as `^0.22.0`, which by semver rules would only match patch versions.

**Comment by johnunclesam** [comment]
Why you close this? Why on npmjs is not 0.23 but still 0.22?

**Comment by SimenB** [comment]
@JayAndCatchFire `brew install yarn --ignore-dependencies`.

You might want to resuscitate Homebrew/brew#1408

**Comment by JayAndCatchFire** [comment]
@SimenB Thanks for the tip.  I don't want to insert myself into [that minefield](Homebrew/brew#1408), though.

**Comment by SimenB** [comment]
Haha, fair enough!

**Comment by SimenB** [comment]
Yarn from brew is just an executable js file, so it'll use node on path, so there isn't really any issue here, is it?

**Comment by JayAndCatchFire** [comment]
I'm fine with it. I mean, if it was my project, I'd want the latest version on npm or none at all. I wouldn't want an old version just kicking around over there. But that's just me. I'm no longer personally affected by it at this point.

**Comment by johnunclesam** [comment]
Can you answer why I can't install it with `npm i -g yarn`?
