### ISSUE TITLE
--no-progress Flag Does Not Silence Activity/Progress Output With --json Flag

### ISSUE THREAD

**Issue by alecmerdler** [yarnpkg/yarn#3155]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
The `--no-progress` flag does not silence activity/progress output with the `--json` flags on any command. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Example: `yarn install --no-progress --json` 
Output: 
{"type":"step","data":{"message":"Resolving packages","current":1,"total":4}}
{"type":"activityStart","data":{"id":0}}
{"type":"activityTick","data":{"id":0,"name":"angular@1.6.2"}}
{"type":"activityTick","data":{"id":0,"name":"angular-animate@1.6.2"}}
{"type":"activityTick","data":{"id":0,"name":"angular-cookies@1.6.2"}}
{"type":"activityTick","data":{"id":0,"name":"angular-route@1.6.2"}}
{"type":"activityTick","data":{"id":0,"name":"angular-sanitize@1.6.2"}}
...
{"type":"progressTick","data":{"id":0,"current":715}}
{"type":"progressTick","data":{"id":0,"current":716}}
{"type":"progressTick","data":{"id":0,"current":717}}
{"type":"progressFinish","data":{"id":0}}

**What is the expected behavior?**
No progress output of any kind is produced.

**Please mention your node.js, yarn and operating system version.**
Node: **v7.2.0**
Yarn: **v0.21.3**
OS: **Manjaro Linux v17.0.1**

**Comment by pweaver** [comment]
Shouldn't --json imply --no-progress?

**Comment by sschuberth** [comment]
Looks like the issue has been fixed in Yarn 0.24.
