### ISSUE TITLE
yarn global install overwrites apache yarn alias

### ISSUE THREAD

**Issue by illegalnumbers** [yarnpkg/yarn#3157]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
installing yarn globally overwrites an existing yarn alias on my system for apache yarn. this is not ideal.

**If the current behavior is a bug, please provide the steps to reproduce.**
install apache yarn. install yarnpkg globally.

**What is the expected behavior?**
if yarn is already defined, just use yarnpkg.

**Please mention your node.js, yarn and operating system version.**
node v5.12., mac 10.11.6, yarn 0.22.0

**Comment by gsklee** [comment]
@illegalnumbers Could you please provide some more information? Did you mean that your Bash `alias` were being overridden? Or was it something similar to what was described in #2337?

**Comment by gsklee** [comment]
@bestander close

Without further information, it would be hard to actually act upon this issue.
