### ISSUE TITLE
check --integrity broken on Linux

### ISSUE THREAD

**Issue by vojty** [yarnpkg/yarn#3167]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
`yarn check --integrity` doesnt work on linux, after small investigation it looks like integrity file is never created (https://github.com/yarnpkg/yarn/blob/master/src/integrity-checker.js#L201-L207)

previous v0.22.0 was fine

output: 
```
18:26:20 yarn check v0.23.2
18:26:20 verbose 0.322 current time: 2017-04-17T16:26:20.740Z
18:26:21 error Couldn't find an integrity file
18:26:21 error Integrity check failed
18:26:21 verbose 0.692 Error: Found 2 errors.
18:26:21     at MessageError (/usr/share/yarn/lib-legacy/errors.js:8:10)
18:26:21     at /usr/share/yarn/lib-legacy/cli/commands/check.js:173:13
18:26:21     at next (native)
18:26:21     at step (/usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
18:26:21     at /usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
18:26:21     at run (/usr/share/yarn/node_modules/core-js/library/modules/es6.promise.js:87:22)
18:26:21     at /usr/share/yarn/node_modules/core-js/library/modules/es6.promise.js:100:28
18:26:21     at flush (/usr/share/yarn/node_modules/core-js/library/modules/_microtask.js:18:9)
18:26:21     at nextTickCallbackWith0Args (node.js:420:9)
18:26:21     at process._tickCallback (node.js:349:13)
18:26:21 error Found 2 errors.

```
**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn check --integrity` on previously working project, tried to generate new lock file after yarn upgrade, no success

**What is the expected behavior?**
it should not fail :)
**Please mention your node.js, yarn and operating system version.**
node 6.9.1
os Ubuntu 16.04.02 (failed also on CI which is some kind of RHEL)
yarn v0.23.2

**Comment by originalhat** [comment]
This is a bummer. Costs us several minutes total in CI in total + extra network I/O.
