### ISSUE TITLE
Installation of Local Filesystem tgz Modules Fails in 0.23

### ISSUE THREAD

**Issue by kjbkjb** [yarnpkg/yarn#3168]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Version 0.23 breaks installation of local filesystem tgz files where 0.22 functioned as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
-"dependencies": {
"bell": "^8.6.0",
"local-package-on-fs": "file:.modules/local-package-on-fs-3.0.3.tgz",
```

The above excerpt from a package.json functions in 0.22 but fails in 0.23 as it attempts to find the package by the full name, including tgz on npm with the following error:

```
yarn
yarn install v0.23.2
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm-proxy.fury.io/.../.modules/local-package-on-fs-3.0.3.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**

Yarn should respect `file:` references to `.tgz` files.

**Please mention your node.js, yarn and operating system version.**

- Node: 6.10
- Yarn: 0.23
- Mac OS: 10.12.4

I originally mentioned this issue on this pull request as it was dealing with files:
https://github.com/yarnpkg/yarn/pull/2723

I can provide the full package.json or whatever other information you require.

**Comment by tibdex** [comment]
Hi, I stumbled on this issue too. Here is a script to reproduce it quickly:

```bash
YARN=yarn

rm -rf /tmp/yarntest
mkdir /tmp/yarntest
cd /tmp/yarntest

mkdir a
cd a
echo '{ "name": "a", "version": "1.0.0", "dependencies": { "b": "file:../b-1.0.0.tgz" } }' > package.json

mkdir /tmp/yarntest/b
cd /tmp/yarntest/b
echo '{ "name": "b", "version": "1.0.0" }' > package.json
yarn pack

cd ../a

"$YARN" install
```

**Comment by bestander** [comment]
@voxsim, should we revert #2723 or is there a fix possible?

**Comment by bestander** [comment]
Removed previous comment.
Reverting #2723 does not fix the issue

**Comment by bestander** [comment]
The bug was introduced in #3004.
cc @arcanis, we'll need to fix it and add use case to tests

**Comment by bestander** [comment]
@tibdex, thanks a lot for the repro steps, helped a lot.
There is a bug in a/package.json, I've modified it

**Comment by arcanis** [comment]
The issue doesn't come from this commit. Apparently, when the code reaches [this line](https://github.com/yarnpkg/yarn/blob/master/src/fetchers/tarball-fetcher.js#L41), the tarball isn't available in the cache yet (but I've checked, and it is when the command complete! weird). Will investigate.

**Comment by aversini** [comment]
@bestander I see that you closed this issue but I can still reproduce it 100% of the time with the latest version of Yarn (0.25.2) by simply adding one step to the scenario above: `yarn cache clean`.
With a clean cache and no installed modules, every single time installing a local package tarball fails into a 404 error, trying to fetch it from the registry:
```shell
yarn add file:third/my-file.tgz
yarn add v0.25.2
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "http://registry.npmjs.org/third/myfile.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Any pointers? I can try to see if I can fix it and create a PR if you feel it's still a legit issue. Thanks!

**Comment by bestander** [comment]
Does relative path work?

```
yarn add file:./third/my-file.tgz
```

**Comment by aversini** [comment]
Ah! It does work indeed!
