### ISSUE TITLE
`yarn config set version-git-sign true` doesn't sign git tags

### ISSUE THREAD

**Issue by mikcho** [yarnpkg/yarn#3177]
When I run `git tag -a -s -m "version 1.0.0" v1.0.0`, it can create a tag with signing.

I have configured yarn with:
```shell
yarn config set version-git-sign true
yarn config set version-git-tag true
```

And then run `yarn version`

But yarn create git tags without signing.

**Comment by Rowno** [comment]
Looks like the documentation is incorrect, the code is using [`version-sign-git-tag`](https://github.com/yarnpkg/yarn/blob/v0.27.0/src/cli/commands/version.js#L145).

**Comment by friederbluemle** [comment]
More than two years later, and I just ran into this problem as well. Why is there a useless `version-git-sign` in my Yarn config? Can the unused config value be removed to avoid confusion?
