### ISSUE TITLE
Native module artifacts removed as extraneous: "Cannot find module"

### ISSUE THREAD

**Issue by CrabDude** [yarnpkg/yarn#3180]
*Created for tracking purposes as I learn more & debug.*

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Under certain conditions, build artifacts for native modules are removed as extraneous. (`Removing extraneous file`, `verboseFileRemoveExtraneous`). This 

**If the current behavior is a bug, please provide the steps to reproduce.**

Seems to occur when `yarn.lock` would be altered by running `yarn` against a pre-existing `node_modules` install (off the current `yarn.lock`). The key output is:

```
warning Integrity check: Lock files don't match
```

This consistently reproducible across many circumstances, but not yet in a minimum use case. It has been verified that it is not caused by the respective native module, but will occur with any native `node_modules` given the right triggering circumstances.

**What is the expected behavior?**

Native build artifacts should not be removed in a manner that breaks native dependencies.

**Please mention your node.js, yarn and operating system version.**

node@4.8.2
yarn@0.23, 0.24 (aka master HEAD)
Docker ubuntu12.04

**Related issues:** https://github.com/yarnpkg/yarn/issues/231 https://github.com/yarnpkg/yarn/issues/1955#issuecomment-293728671

**Comment by bestander** [comment]
Should be fixed by #3224 and released in 0.24
