### ISSUE TITLE
Add --ignore-missing option

### ISSUE THREAD

**Issue by xahon** [yarnpkg/yarn#3183]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When installing package it shows error and interrupts

**What is the expected behavior?**
I want non-interrupting behavior when package are not found, only show bold error in console

**Comment by bestander** [comment]
What would you achieve by that?
Seems like you'll get a partial node_modules and your application would likely not work

**Comment by BYK** [comment]
Since there is no response from the author and the original issue description is pretty vague, closing the issue.

**Comment by bonjourbebe** [comment]
Can we re-open? 
Use-case:
I have sensitive node_modules that are hosted privately, 
I would like to use caching however the cache is deemed in-secure
99.99% of the node_modules are public and can get cached.

Workflow:
- `restore_cache`
- clone project without .npmrc file
- `yarn install --ignore-missing`
- `save_cache`
- pull `.npmrx` from some source
- yarn install
(Deploy)

**Comment by lonewarrior556** [comment]
I would like to publish a docker container publicly that has the public modules pre-installed.

**Comment by sielay** [comment]
Another use case - I want to work on github codespace without access to internal package mirror. I don't need all packages to work on the project, but need essential like TS and CRA scripts.
