### ISSUE TITLE
userHomeDir is determined by UID

### ISSUE THREAD

**Issue by AlphaBetaPeter** [yarnpkg/yarn#3184]
**Do you want to request a *feature* or report a *bug*?**

In my use-case its a bug.

**What is the current behavior?**
Pretty much the same as in #1827. The build process is running in a chroot with uid 0 but no actual root permissions. This leads to yarn failing to create `/usr/local/share/.config`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run yarn in a chroot with uid 0 but no actual root privileges. This leads to yarn failing to create `/usr/local/share/.config`. 

**What is the expected behavior?**
Either checking for permissions or using a flag to set userHomeDir or simply using $HOME to set the desired home location.

**Please mention your node.js, yarn and operating system version.**
node 7.9.0, yarn v0.23.2, debian 8

**Comment by Daniel15** [comment]
> Run yarn in a chroot with uid 0 but no actual root privileges. This leads to yarn failing to create /usr/local/share/.config.

If it's a chroot, wouldn't this succeed and create `/usr/local/share/` in the chroot?

Do you have some repro commands?

**Comment by AlphaBetaPeter** [comment]
Under certain circumstances this would be possible, yes. The environment my yarn process runs in doesn't allow that. 
I am not running any specific commands. Simply `yarn (install)`. 
It just felt a bit odd that i can't influence where yarn creates these files.

**Comment by BYK** [comment]
This should be handled by fakeroot detection now. Please reopen if you think it is still an issue.
