### ISSUE TITLE
regression: --frozen-lockfile

### ISSUE THREAD

**Issue by joscha** [yarnpkg/yarn#3185]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn install --frozen-lockfile` does not exit non-zero, but instead updates the yarn lock file.

**If the current behavior is a bug, please provide the steps to reproduce.**
See https://gist.github.com/joscha/9079e5853bce79ee5de2d081188b10b8

Running `./test.sh` should print a non-zero exit code

**What is the expected behavior?**
A non-zero exit from `yarn install`

**Please mention your node.js, yarn and operating system version.**
yarn  v0.23.2
OSX Sierra
Node 7.8.0

references #2538

**Comment by bestander** [comment]
Thanks for repro steps.
I'll add a test and a fix in the next couple of days

**Comment by bestander** [comment]
I think this got fixed with latest version of Yarn
```
yarn install v0.24.0-0
[1/4] 🔍  Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
1
```
