### ISSUE TITLE
Running npm scripts that depend on subdependencies doesn't work

### ISSUE THREAD

**Issue by bensampaio** [yarnpkg/yarn#3186]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
With the following `package.json`:

```json
{
  "name": "my-project",
  "dependencies": {
    "my-other-project": "1.0.0"
  },
  "scripts": {
    "lint:js": "eslint src/**/*.js"
  }
}
```

Assuming that `eslint` is a dependency of `my-other-project`. When I run: `yarn run lint:js` I get `eslint: not found`. However, with `npm` this works fine.

Changing the `lint:js` in the scripts section to `"node_modules/eslint/bin/eslint.js src/**/*.js"` works. But this is not the solution...

**If the current behavior is a bug, please provide the steps to reproduce.**

Just create a project (`my-other-project`) that depends on `eslint` and then create another project (`my-project`) with the `package.json` provided above. Then run `yarn` anf afterwards try `yarn run lint:js`.

**What is the expected behavior?**
For `yarn run lint:js` to not fail.

**Please mention your node.js, yarn and operating system version.**
macOS 10.12.4
Node.js 6.10.2
yarn 0.23.2

**Comment by bestander** [comment]
This should be fixed in > 0.26
