### ISSUE TITLE
Yarn add file:..path takes version from cache not from actual location

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#3188]
Version: 0.22.0

First run `yarn add file:..path/to/my-package` adds package to cache.
After package is modified `yarn add file:..path/to-my-package` and `yarn upgrade my-package` does not place new version to cache and takes old version from cache for adding to project.

😩

**Comment by beworker** [comment]
It appears to be a duplicate of #3187

**Comment by arcanis** [comment]
Indeed, I'll close it. Feel free to reopen it with more details if you think it's a separate issue, @whitecolor!
