### ISSUE TITLE
yarn update-interactive should be an alias for yarn upgrade-interactive

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/yarn#3191]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

```sh
$ yarn update-interactive
yarn update-interactive v0.21.3
error Command "update-interactive" not found.
```

**What is the expected behavior?**

It to mean the same as `upgrade-interactive`.

A similar situation is met in `yarn update`: 

```sh
$ yarn update
yarn update v0.21.3
error Did you mean `yarn upgrade`?
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

For both I'd like it to mean the same, since it's hard to know what's the difference between those two words

**Please mention your node.js, yarn and operating system version.**

node: v7.5.0
yarn: v0.21.3

**Comment by gsklee** [comment]
@bestander close

The consensus seems to be that we're removing aliases from Yarn.
