### ISSUE TITLE
yarn offline mirror behavior is very strange

### ISSUE THREAD

**Issue by agibralter** [yarnpkg/yarn#3194]
### setup

I am using yarn@0.22.0. I am using node v7.9.0 installed with nvm on macOS 10.12.4. yarn is installed as `npm install -g yarn@0.22.0`. I have also tried `brew install yarn`.

This is my repo's `.yarnrc`:
```
$ cat .yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

yarn-offline-mirror "./vendor/npm_cache"
```

### bug
It seems that using yarn@0.22.0 does not consistently record the right value for `"resolved"` in the `yarn.lock` file (down to 0.19.x and up to 0.23.x also seem to have the same strange behavior).

The only way I can get `yarn` to consistently record something like this:

```
react@^15.4.2:
  version "15.5.4"
  resolved react-15.5.4.tgz#fa83eb01506ab237cdc1c8c3b1cea8de012bf047
  dependencies:
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.7"
```

...rather than, e.g., `resolved "https://registry.yarnpkg.com/react/-/react-15.4.2.tgz#41f7991b26185392ba9bae96c8889e7e018397ef"`

is to run something like `rm -rf vendor/npm_cache/ node_modules/ yarn.lock; yarn cache clean; yarn`. If I don't `yarn cache clean`, I can end up with urls instead of `.tgz` references. This behavior is pretty frustrating because I don't consistently get offline mirror versions specified in my yarn.lock.

If you have an offline mirror set up, should it be expected that you'll never see a registry.yarnpkg.com in the yarn.lock file, right?

**Comment by kmmolex** [comment]
I'm experiencing the same issue. I had the correct results in offline mode yesterday. Are you always able to get offline mirrors after using `yarn cache clean`? I'm still getting https://registry.yarnpkg.com

**Comment by agibralter** [comment]
@kmmolex hmm I only get the correct results when I blow away yarn.lock, clean the cache, an "re-yarn." Step-wise yarn-ing does not seem to exhibit consistently reliable behavior for me. I almost always re-yarn from scratch and look at the git diff. 😦

**Comment by griffinmichl** [comment]
I am also seeing this problem in fact, it breaks `yarn-offline-mirror-pruning` because if the install points to https://registry.yarnpkg.com, the value in the name in the offline mirror does not equal the name in the lockfile and yarn deletes necessary packaged from your offline cache.

**Comment by griffinmichl** [comment]
Another potentially related ticket: #3194

**Comment by bestander** [comment]
cc @arcanis

**Comment by jakewisse** [comment]
> If you have an offline mirror set up, should it be expected that you'll never see a registry.yarnpkg.com in the yarn.lock file, right?

Going through the steps outlined in [_Running Yarn offline_](https://yarnpkg.com/blog/2016/11/24/offline-mirror/), I think not. My `yarn.lock` has `resolved` fields pointing at `registry.yarnpkg.com`, yet after running `yarn cache clean`, `rm -rf node_modules`, and disconnecting all network connections, I'm still able to reinstall from the offline mirror.

**Comment by arcanis** [comment]
This issue shouldn't be relevant anymore starting from 0.23, since we now always use expanded registry urls.

**Comment by griffinmichl** [comment]
@arcanis I do not believe that is the case in 0.23. Did you mean 0.24?

**Comment by griffinmichl** [comment]
Nevermind. I was on the wrong nvm version.

**Comment by agibralter** [comment]
I think we can close this ticket... the issue is actually this one: https://github.com/yarnpkg/yarn/issues/3154#issuecomment-299579495
