### ISSUE TITLE
yarn add <package-name> should not run the prepublish hook

### ISSUE THREAD

**Issue by kristenmills** [yarnpkg/yarn#3197]
**Do you want to request a feature or report a bug?**
Report a bug. 

**What is the current behavior?**
Currently when you run `yarn add <package-name>` the prepublish hook is also run. This is not expected behavior as `npm install <package-name>` does not run the prepublish hook. 

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add <any package>`

**What is the expected behavior?**
`yarn add <package-name>` should not run `prepublish`. (`yarn install` should continue to run `prepublish`)

**Please mention your node.js, yarn and operating system version.**
Node 7.5
Yarn 0.23.2
Mac OSX 10.12.2

**Comment by juanca** [comment]
`npm install` does run the publish hook. This is why there is `prepublishOnly` hook.

> IMPORTANT: As of npm@5, prepublish will only be run for npm publish. This will make its behavior identical to prepublishOnly, so npm@6 or later may drop support for the use of prepublishOnly, and then maybe we can all forget this embarrassing thing ever happened.

**Comment by kristenmills** [comment]
`npm install` with no args does. `npm install <a package>` does not.

**Comment by bestander** [comment]
Should be implemented via https://github.com/yarnpkg/rfcs/pull/70
