### ISSUE TITLE
Yarn offline cache is difficult to search

### ISSUE THREAD

**Issue by amcgee** [yarnpkg/yarn#3200]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
`yarn cache ls` is difficult to search.  This makes it tough to confirm that a package exists in the local cache.  For instance:

```shell
$ yarn cache ls | wc -l
  241
```
(requires manually looking for the package since `yarn cache ls | grep <name>` doesn't work - this is probably a separate bug.)

A workaround is to use an intermediate file and grep -
```shell
$ yarn cache ls > yarncache.txt
$ grep "immutable" yarncache.txt
  immutable                                               3.8.1        npm      https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz#200807f11ab0f72710ea485542de088075f68cd2
```

For local dependancies `yarn list <name>` does the trick, but this is not implemented for `yarn cache ls`

**What is the expected behavior?**
```shell
$ yarn cache ls immutable
  yarn cache v0.23.2
  Name        Version      Registry Resolved      
  immutable   3.8.1        npm      https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz#200807f11ab0f72710ea485542de088075f68cd2
```
**Please mention your node.js, yarn and operating system version.**
```shell
$ node -v
  v7.9.0
$ yarn --version
  0.23.2
$ system_profiler SPSoftwareDataType | grep "System Version"
  System Version: macOS 10.12.4 (16E195)
```

**Comment by bestander** [comment]
Nice idea, send a PR

**Comment by bestander** [comment]
similar to https://github.com/yarnpkg/yarn/pull/3734

**Comment by bestander** [comment]
cc @helloandre do you want to do this one too? :)

**Comment by amcgee** [comment]
@helloandre if you want to tackle this be my guest, otherwise I'm happy to take a stab at it.

**Comment by bestander** [comment]
The rules of dibs work here, don't wait, @amcgee, send a PR :)

**Comment by philquinn** [comment]
@amcgee @bestander I put a PR for this. I hope that is okay.

**Comment by amcgee** [comment]
+1 thanks @philquinn I got sidetracked
