### ISSUE TITLE
Environment variable for yarn cache directory location

### ISSUE THREAD

**Issue by colinodell** [yarnpkg/yarn#3208]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Cache location can only be configured via the `cache-folder` config option.

**What is the expected behavior?**
Being able to configure the cache location using an environment variable.

Other prominent package managers offer this functionality:

 - Composer: `COMPOSER_CACHE_DIR`
 - npm: `NPM_CONFIG_CACHE`
 - RubyGems: `GEM_SPEC_CACHE`
 - bower: `bower_storage__packages` (unconfirmed)
 - pip: `PIP_DOWNLOAD_CACHE` (unconfirmed)

This is extremely useful for continuous integration - you may want jobs to use a shared cache, but each individual job may not know (or perhaps shouldn't know) where that global cache exists.  Additionally, if that global cache directory changes, it's much easier to update a single environment variable in the CI system than updating the `yarn` commands in every individual project.

I therefore propose using an envvar like `YARN_CONFIG_CACHE_FOLDER`.  If defined, this would take precedence over the default cache directory.  (However, it would not take precedence over any `cache-folder` option used on the command line.)

**Comment by zurawiki** [comment]
Sounds like a good first bug @colinodell 

Can I take take a look and try to send in a PR?

**Comment by colinodell** [comment]
Yeah absolutely!

**Comment by zurawiki** [comment]
This feature already seems to exist. The env variable name is `YARN_CACHE_FOLDER`

```sh
$ YARN_CACHE_FOLDER="foo" ./bin/yarn cache dir
foo/v1
```

**Comment by bestander** [comment]
Yes, actually Yarn converts all environment variables into 
[YarnRegistry.config](https://github.com/yarnpkg/yarn/blob/master/src/registries/yarn-registry.js#L60) if they have `yarn_` prefix.

That is not a widely known fact, do you want to write start a doc on the [website](https://yarnpkg.com/en/docs/configuration) for that, @zurawiki ?

**Comment by glensc** [comment]
@bestander never link to branches! now, what line you had in mind?


🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)
