### ISSUE TITLE
skip license check for private:true modules?

### ISSUE THREAD

**Issue by ianstormtaylor** [yarnpkg/yarn#3211]
**What is the current behavior?**

If you have a module that is marked `"private": true`, it still checks and prints a warning for `warning No license field`.

**What is the expected behavior?**

I think it should skip the check for private modules?

**Please mention your node.js, yarn and operating system version.**

```
$ node -v
v6.9.5
$ yarn -V
0.22.0
```

**Comment by arcanis** [comment]
I've tried with Yarn 0.24.3, and I didn't see this warning when using `"private": true`. Please reopen this issue if you think I'm mistaken, thanks!
