### ISSUE TITLE
Feature: Add license to lock file

### ISSUE THREAD

**Issue by steven10172** [yarnpkg/yarn#3212]
Due to the nature of the `yarn.lock` file and being in a user readable format it would be useful to include the license for each specific version of that package. Having the license in the `yarn.lock` would allow users to quickly see what versions and licenses will be used in the application. Allowing the user to quickly read the file will allow security reviews to easily check to make sure that the current licenses are allowed without having to install everything.

We can currently run `yarn licenses ls`, but that command had to do a dry run and requires network access. Having the license information in `yarn.lock` will allow the licenses command to work in offline mode without the package being in the cache.

**Comment by Daniel15** [comment]
`yarn.lock` is just supposed to be a simple lockfile, it's not for storage of other metadata. Because of this, I doubt we'd add the licenses to it.

**Comment by hamman3223** [comment]
@Daniel15 I could argue with you about necessity of license metadata for dependencies. For example, when you work with SBOM files, it includes component licenses in its final json/xml and then in the context of CI/CD this file supplied to some platform that works with Cyclonedx SBOM (Dependency Track in our case), then get policy violations on these licenses. As a result we get metrics about violated licenses, which very important for vendor companies

This issue caught my Application Security Team, when one of our products migrate from npm to yarn :(

**Comment by Daniel15** [comment]
@hamman3223 I don't disagree, but I also don't think a lock file is the correct place for license metadata. 

There's no guarantee that all the installed software is even used in the final product. Are you interested in the licenses of software used in the final product, or the licenses of all installed software regardless of if/how it's used? People are usually concerned about the former, in which case (for JavaScript at least) most bundlers can output a LICENSE.TXT file containing all the licenses.

**Comment by hamman3223** [comment]
> @hamman3223 I don't disagree, but I also don't think a lock file is the correct place for license metadata. 
> 
> 
> 
> There's no guarantee that all the installed software is even used in the final product. Are you interested in the licenses of software used in the final product, or the licenses of all installed software regardless of if/how it's used? People are usually concerned about the former, in which case (for JavaScript at least) most bundlers can output a LICENSE.TXT file containing all the licenses. 

Answering your question about which dependencies I am interesting on. I considered production dependencies :)

This logic (I mean extraction prod dependencies from .lock) should be implemented by third party tools. For example cyclonedx-sbom-npm implements logic of mapping installed packages from "node_modules" with lock file. Thus, user can install dependencies by using NODE_ENV=production, then the above mentioned tool do mapping. In result you will get SBOM file included only production dependencies

I think, that your argument doesn't relate to non-compliance with license metadatas. Is is standard that the most modern package managers support. It would be cool if yarn supported it too
