### ISSUE TITLE
`yarn add package@typo` adds the typo to `package.json` and `yarn.lock`

### ISSUE THREAD

**Issue by taylorham** [yarnpkg/yarn#3214]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
  
When using `yarn add` to add a specific version of a package to dependencies (or --dev), a typo in the version number yields a prompt that allows the user to select an existing, valid version.

The selected valid version is installed, but `package.json` reads `"package": "typo"`, and `yarn.lock` is even more confusing with `package@typo: version "selected valid version"`.

Everything works fine because the correct package was installed, and any reinstalls with `yarn` will also work because of the additional information in the lockfile, but if a coworker were to `npm install`, they would get yelled at like this: `npm ERR! notarget No compatible version found: react@typo`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a new directory, `yarn init (--yes)`, and run `yarn add react@typo`. Select `16.0.0-alpha.10` from the provided options.

Terminal output after running `yarn add react@typo` and selecting `16.0.0-alpha.10` from the prompt:

```bash
$ yarn add react@typo
yarn add v0.23.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "react" that matches "typo"
? Please choose a version of "react" from this list: 16.0.0-alpha.10
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 18 new dependencies.
├─ asap@2.0.5
├─ core-js@1.2.7
├─ create-react-class@15.5.2
├─ encoding@0.1.12
├─ fbjs@0.8.12
├─ iconv-lite@0.4.15
├─ is-stream@1.1.0
├─ isomorphic-fetch@2.2.1
├─ js-tokens@3.0.1
├─ loose-envify@1.3.1
├─ node-fetch@1.6.3
├─ object-assign@4.1.1
├─ promise@7.1.1
├─ prop-types@15.5.8
├─ react@16.0.0-alpha.10
├─ setimmediate@1.0.5
├─ ua-parser-js@0.7.12
└─ whatwg-fetch@2.0.3
✨  Done in 10.39s.
```

`package.json` dependencies:
```javascript
"dependencies": {
  "react": "typo"
}
```

`yarn.lock` react version:
```
react@typo:
  version "16.0.0-alpha.10"
  resolved "https://registry.yarnpkg.com/react/-/react-16.0.0-alpha.10.tgz#dcdafa9f84437d2c7e06b234b86782d316298882"
  dependencies:
    create-react-class "^15.5.2"
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.6"
```

**What is the expected behavior?**
I expect `package.json` to have the version number I selected from the CLI prompt when attempting to install a nonexistent version, and for the `yarn.lock` file to also have the correct version number in place of the typo.

**Please mention your node.js, yarn and operating system version.**
node@6.10.1
yarn@0.23.2
macOS@10.12.4 (Sierra)

**Comment by bestander** [comment]
duplicate https://github.com/yarnpkg/yarn/issues/2466
