### ISSUE TITLE
yarn install should not report `warning Integrity check: Flags don't match`

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3215]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Reported by @SimenB at #3067

yarn init -y && yarn add sequelize-cli && yarn add gulp --dev && yarn --prod && yarn check --verify-tree --prod

I find the 2 last commands interesting

yarn install v0.23.2
[1/4] 🔍  Resolving packages...
warning Integrity check: Flags don't match
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 2.09s.
yarn check v0.23.2
success Folder in sync.
✨  Done in 1.01s.

**What is the expected behavior?**
integrity-checker.js should not do warning outputs, those should happen in check.js command level.

**Please mention your node.js, yarn and operating system version.**
yarn 0.23

**Comment by bestander** [comment]
Up for grabs, a simple restructure

**Comment by voxsim** [comment]
@bestander we can close this :D
