### ISSUE TITLE
Yarn is not generating integrity file when installing with --pure-lockfile

### ISSUE THREAD

**Issue by betalb** [yarnpkg/yarn#3217]
**Do you want to request a *feature* or report a *bug*?**: bug

**What is the current behavior?**
when I do `yarn install --pure-lockfile` `.yarn-integrity` file is not generated in `node_modules`

**What is the expected behavior?**
`.yarn-integrity` file should be generated. Yarn v0.22.0 was generating this file during insall with pure-lockfile flag

**Please mention your node.js, yarn and operating system version.**
yarn: 0.23.2
node: v7.9.0
OS: Microsoft Windows [Version 10.0.15063]

**Comment by bestander** [comment]
Fixing in #3506
