### ISSUE TITLE
Yarn package disappeared from AUR

### ISSUE THREAD

**Issue by AnatolyRugalev** [yarnpkg/yarn#3220]
I can't install yarn because the package does not exist in AUR:

https://aur.archlinux.org/pkgbase/yarn/

But it was [cached by Google](https://webcache.googleusercontent.com/search?q=cache:FSDuU-1QT7wJ:https://aur.archlinux.org/pkgbase/yarn/%3Fcomments%3Dall+&cd=2&hl=ru&ct=clnk&gl=ru)

BTW it does exist in aur-dev repository, but I don't know how to install it from there

I can't find any information about that.

**Comment by Daniel15** [comment]
It's in the regular community repo now: https://www.archlinux.org/packages/community/any/yarn/
