### ISSUE TITLE
Document how to install yarn when you use nvm

### ISSUE THREAD

**Issue by binarykitchen** [yarnpkg/yarn#3255]
I have a mess here on my both machines, running on Ubuntu and Mac OS. Both have the same problem: how to install yarn properly when you use nvm?

nvm, as you know, is an isolated nodejs manager. But when you do `brew install yarn` or `sudo apt-get install yarn`, then a system-wide nodejs version is installed (as a dependency)

This nodejs dependency is breaking a lot on my machines. This isn't working well. Ideally it would be good if we still can install and upgrade yarn through npm; or at least make brew + apt-get smarter, not installing the nodejs dependency when nvm already exist.

Looking at older issues, I see this has been discussed but there are too many comments to process. Can we agree to an official solution to the above and document this on the installation page?

**Comment by Daniel15** [comment]
On Debian-based distros (including Ubuntu), you install Yarn this way:

```
apt-get install --no-install-recommends yarn
```

Homebrew has a similar flag, but I can't remember it off the top of my head.

The install script will also work:
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```

**Comment by rally25rs** [comment]
@bestander triage; label: [documentation] (which doesn't seem to be an existing label... perhaps worth making?)

**Comment by bestander** [comment]
now we have :)

**Comment by binarykitchen** [comment]
thanks for that - yeah, please document.

and `curl -o- -L https://yarnpkg.com/install.sh | bash` is not an option for me because it does not get automatically updates like apt-get and brew do.

**Comment by bestander** [comment]
This is a community project, we hope that people who need this would step in and help each other, e.g. send a PR for documentation.

**Comment by binarykitchen** [comment]
alright, i ll do a PR next week. can you confirm the curl command installs only but doesn't update?

**Comment by bestander** [comment]
That script should update

**Comment by ntwb** [comment]
> Quoting @Daniel15 https://github.com/yarnpkg/yarn/issues/3255#issuecomment-297908242:
> _"...Homebrew has a similar flag, but I can't remember it off the top of my head."_

I don't see that option in the formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb, I've opened https://github.com/Homebrew/homebrew-core/issues/14026 for this to be added to the Yarn Homebrew package.

**Comment by Daniel15** [comment]
I think there's a `--skip-dependencies` flag.

**Comment by Daniel15** [comment]
I think there's an `--ignore-dependencies` flag

Sent from my phone.

**Comment by ntwb** [comment]
I created https://github.com/yarnpkg/website/pull/516 per the above

**Comment by app** [comment]
@Daniel15 
> `apt-get install --no-install-recommends yarn`
Thanks. It works! 
And what about next time I run `sudo apt upgrade` ? Will new version of `yarn` install nodejs?

**Comment by andrewhavens** [comment]
Just an update for anyone who comes across this issue via Google search...Yarn documentation now says that Yarn can be installed on a Mac, via Homebrew, without node, like this:
```bash
brew install yarn --without-node
```

**Comment by idkjs** [comment]
@andrewhavens your note timestamp is right on time. TY

**Comment by chris-orchard** [comment]
> 

> @Daniel15
> 
> apt-get install --no-install-recommends yarn
> Thanks. It works!
> And what about next time I run sudo apt upgrade ? Will new version of yarn install nodejs?

Was there an answer to this? If I `apt-get install --no-install-recommends yarn` will nodejs be installed when I upgrade or not?

**Comment by Daniel15** [comment]
Sorry I didn't answer that! It shouldn't - AFAIK Debian only looks at "recommended" packages on initial installation, not on upgrades.

**Comment by stevecj** [comment]
What about installing on CentOS/Fedora using nvm?
Yes, this is something that I actually need to do.

**Comment by stevecj** [comment]
Yum says the following…
```
===========================================================================================================================================================================
 Package                                Arch                                   Version                                          Repository                            Size
===========================================================================================================================================================================
Installing:
 yarn                                   noarch                                 1.6.0-1                                          yarn                                 916 k
Installing for dependencies:
 libuv                                  x86_64                                 1:0.10.34-1.el6                                  epel                                  57 k
 nodejs                                 x86_64                                 0.10.48-3.el6                                    epel                                 2.1 M

Transaction Summary
===========================================================================================================================================================================
Install       3 Package(s)

Total download size: 3.0 M
Installed size: 11 M
Is this ok [y/N]:
```
I presume I want to install yarn and libuv but not nodejs. Correct?

**Comment by devxpy** [comment]
Anyone know how to do this on Solus?

**Comment by devxpy** [comment]
`sudo eopkg install yarn --ignore-dependency`

**Comment by jcollum** [comment]
@binarykitchen can you add @andrewhavens [comment](https://github.com/yarnpkg/yarn/issues/3255#issuecomment-334247437) to your initial comment as an edit? it would be very helpful to have that at the top of the page for people who come here from google.

**Comment by ivanovv** [comment]
```
brew install yarn --without-node
```

still wants to install `node`:

```
$> brew install yarn --without-node
==> Installing dependencies for yarn: python, sphinx-doc, python@2, icu4c and node
```

I guess it is because of this commit https://github.com/Homebrew/homebrew-core/commit/a34c721586fece6d36d9b60fec5760e1b3361f11 but I'm not 100% sure as I have little knowledge of Homebrew.

**Comment by wadkar** [comment]
Following @andrewhavens comment in the thread, another update for anyone who comes across this issue via Google search.

Yarn documentation currently says to install using `brew install yarn` and mentions that it'll pull in the `node` dependency (and transitively pull `python2`, `icu4c`).

Point being, homebrew devs are essentially saying that you must install node from homebrew because homebrew [doesn't support installation options anymore](https://github.com/Homebrew/homebrew-core/issues/31510) (warning long thread, lots of heated discussion). And because yarn cannot work without node, obviously, they will install a system wide node for you.

If you still don't want to install node from homebrew simply do `brew install yarn --ignore-dependencies`. Make sure your `$PATH` is sorted properly as mentioned in the docs.

**Comment by alexraileanu** [comment]
if anyone else comes across this issue from google and has the following setup like me: node installed from nvm, path correctly updated to include nvm's binary path but brew will still refuse to use that node version, you can try the following:

you can use `brew edit yarn` to temporarily comment out the `depends_on "node"` line and yarn will be installed without the node dependency. worked great for me. again, make sure that you have a node version present in your `$PATH`

**Comment by wadkar** [comment]
@alexraileanu `brew install --ignore-dependencies yarn` does exactly that (yours is a precise way of excluding the `node` as dependency), but you'll have brew complaining next time yarn formula gets updated.

**Comment by alexraileanu** [comment]
@wadkar yeah tho in my case, for whatever reason, brew would not find the node binary in my path so when i ran with `--ignore-dependencies` it would try to execute node from `/usr/local` which i didn't have

**Comment by AlecRust** [comment]
It now [seems](https://classic.yarnpkg.com/en/docs/install/) the recommended way to install yarn is via npm.

So if you're using nvm, Homebrew should not be used for Node (to avoid an extra Homebrew Node being installed) or yarn (to avoid yarn being installed outside of nvm).

nvm [will use](https://github.com/nvm-sh/nvm#default-global-packages-from-file-while-installing) `$NVM_DIR/default-packages` file if it exists to install global Node packages, via npm. So this is how I now install yarn ([dotfiles example](https://github.com/AlecRust/dotfiles/blob/master/dotfiles/default-packages#L1)).

Glad to be corrected, but this seems to be the most up-to-date way of installing yarn when using nvm.

Interestingly, this does seem to mean that sometimes `which yarn` returns a function, and sometimes a path to the `yarn` binary within nvm.
