### ISSUE TITLE
npm list flag private repo packages that are in dependencies as extraneous

### ISSUE THREAD

**Issue by Sunyang730** [yarnpkg/yarn#3259]
**Do you want to request a *feature* or report a *bug*?**

bug (maybe?)

**What is the current behavior?**
after yarn install, the private repo packages that are listed under dependencies are flag as extraneous when you do npm list.

**If the current behavior is a bug, please provide the steps to reproduce.**

yarn install some private repo packages and do npm list

**What is the expected behavior?**

Expecting the npm list to not flag private repo packages that were installed by yarn as extraneous so when npm prune is run, it won't remove them.

**Please mention your node.js, yarn and operating system version.**
node.js v7.9.0, OSX v10.11.6

**Comment by Sunyang730** [comment]
So I have notice, when you do npm install, it adds a few meta data to the package.json file. Yarn doesn't do that, so npm list can't parse the info?

**Comment by Sunyang730** [comment]
After spending more time debugging, it seems like the _requested field that got added by npm is the one to define if it is valid or not. Yarn install does not add that field to the package json, therefore it will list as extraneous when you do npm list

**Comment by bestander** [comment]
We don't expect npm commands to work with yarn installation and vice versa
