### ISSUE TITLE
 yarn add global react react-native have errors

### ISSUE THREAD

**Issue by fedwatch** [yarnpkg/yarn#3262]
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js add global react react-native

PATH: 
  C:\Users\Administrator\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_72\bin;C:\Program Files\Java\jdk1.8.0_72\jre\bin;C:\Program Files\nodejs;C:\windows\system32;C:\windowsSystem32\Wbem;C:\Program Files (x86)\Heroku\bin;D:\apache-maven-3.3.9\bin;C:\Program Files\Git\;C:\Program Files\TortoiseSVN\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files (x86)\Java\jre1.8.0_71\bin;C:\Program Files\nodejs;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

Yarn version: 
  0.22.0

Node version: 
  5.3.0

Platform: 
  win32 x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/react-native/-/react-native-0.43.4.tgz: unexpected end of file
      at Zlib._handle.onerror (zlib.js:363:17)

**Comment by bestander** [comment]
It is probably a one-off network issue
