### ISSUE TITLE
Scoped packages install failed on first install (without yarn.lock)

### ISSUE THREAD

**Issue by kenan2002** [yarnpkg/yarn#3264]
**Do you want to request a *feature* or report a *bug*?**
I want to report a BUG.

**What is the current behavior?**
I'm migrating my project from npm to yarn following [this guide](https://yarnpkg.com/lang/en/docs/migrating-from-npm/). However the `yarn` command report the following error:
```
[1/4] Resolving packages...
error Couldn't find package "@scope/package" on the "npm" registry.
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
But when I delete the scoped packages from package.json, yarn installs and generates yarn.lock normally. Then I add the scoped packages back, these packages are installed normally out of surprise.

Additionally, my .npmrc config is like:
```
@scope:registry=http://x.x.x.x:8081/artifactory/api/npm/npm/
```
in which x.x.x.x is the server running jfrog artifactory.

**If the current behavior is a bug, please provide the steps to reproduce.**
Steps are provided above.

**What is the expected behavior?**
Yarn installs all packages including scoped without error and generates yarn.lock.

**Please mention your node.js, yarn and operating system version.**
node: v7.5.0
yarn: v0.23.2
os: Windows 10 64bit

**Comment by jakedahm** [comment]
I am experiencing the same issue on CentOS, but not MacOS. I have verified that I can install my scoped packages with npm. I started seeing this error only when I upgraded to yarn@0.23.2

node: 6.10.1
yarn: 0.23.2
os: CentOS 7.3

**Comment by gugahoi** [comment]
Experiencing same problem on OS X, yarn version 0.23.4. Any scoped package fails to download because it searches for them in `yarnpkg` or `npm` but not in the proper repository configured in `.npmrc`.

**Comment by bestander** [comment]
I think people were fixing it via .yarnrc settigns same as npmrc

**Comment by BYK** [comment]
This shouldn't be an issue in recent versions of Yarn so closing. Feel free to reopen if you think there's still work to do.
