### ISSUE TITLE
yarn add doesn't add carrot or tilde to package.json

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/yarn#3270]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`yarn add jest@^18.0.0` adds to package.json: `"jest":"18.0.0"` (missing the carrot)

**If the current behavior is a bug, please provide the steps to reproduce.**

Execute `yarn add jest@^18.0.0` and `npm install jest@^18.0.0 --save` and observe package.json changes.

**What is the expected behavior?**

In NPM, if you `npm install jest@^18.0.0 --save` it:

* Adds to package.json: `"jest":"^18.0.0" (with the carrot)
* installs jest 18.0.0 (the version specified, ignoring the carrot)

I would expect Yarn to:

* Add `"jest":"^18.0.0"` to package.json
* Add jest 18.0.0 to yarn.lock
* install jest 18.0.0

This would be consistent with what NPM does.

**Please mention your node.js, yarn and operating system version.**

Yarn 0.23.2

**Comment by rally25rs** [comment]
The plot thickens.... This seems to ONLY happen on Windows.

No `dependencies` section in `package.json` (from a clean `yarn init`)
No `yarn.lock` file yet
No `node_modules` folder yet

On OSX after `yarn add jest@^18.0.0`:
* version 18.1.0 is installed (greatest version matching "^18.0")
* `"jest": "^18.0.0"` is in the `package.json`

On Windows after `yarn add jest@^18.0.0`:
* version 18.0.0 is installed
* `"jest": "18.0.0"` is in the `package.json` (no carrot)

I suspect this is a problem with the carrot being something special and needing escaped on the command line... From a quick search I'm seeing other people mention the same behavior while trying to use git and `HEAD^`

So I'm going to close this can chalk it up to "because windows..."

**Comment by centigrade-thomas-becker** [comment]
Why close the issue if it is not resolved?

I have the same problem when trying to add a **caret** on Windows 10. Executing `yarn add nodegit@^0.16.0` will result in `nodegit@0.16.0` in package.json and yarn.lock.

**Comment by rally25rs** [comment]
I closed this because `^` is a special character on windows. The command prompt does not pass it directly to commands. You should be able to escape it with another caret before it `nodegit@^^0.16.0` or possibly putting it in double quotes (I don't have a Win machine in front of me right now to try it).

Reference: https://msdn.microsoft.com/en-us/library/c785s0kz.aspx

> A caret (^) character in a command line means that the character immediately following it is interpreted literally, rather than as a control character.

Git has/had the same issue: https://github.com/msysgit/msysgit/issues/36 but it's hard to tell from the discussion in that issue if they actually fixed it or just closed it because that's how Windows works.

**Comment by centigrade-thomas-becker** [comment]
Thanks for clearing this up

**Comment by waynebloss** [comment]
Double quoting the argument works in plain old *cmd.exe* on Windows 10 x64 with yarnv1.1.0.

Example:

`yarn add react@15.6.2 react-dom@15.6.2 "prop-types@^15.5.0" react-bootstrap@0.31.3 react-sidebar@2.3.2`

**Comment by StevenLiekens** [comment]
This is still a problem in yarn 1.5.1 and the suggested workaround (quoting the args) does not work in powershell...

**Comment by kmc059000** [comment]
@StevenLiekens in powershell, its a bit ridiculous but you need to use 4 carets instead of 2 to escape it properly. This led me there: https://stackoverflow.com/questions/9600549/using-a-caret-when-using-git-for-windows-in-powershell

`yarn add some-package@^^^^1.2.3`

**Comment by StevenLiekens** [comment]
That is pretty stupid. 💩

**Comment by waynebloss** [comment]
Maybe you can open an issue with the Microsoft PowerShell team.

**Comment by GuilhermeTraact** [comment]
The following command works as expected for me on windows on cmd:

```
yarn add "@react-native-community/eslint-config@^2.0.0"
```
