### ISSUE TITLE
An error occurred that means the file name, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by jay763190097** [yarnpkg/yarn#3271]
windows platform:
i use this commond
`yarn config set prefix "D:\Program Files (x86)\Yarn\node-global"`
and add "D:\Program Files (x86)\Yarn\node-global" to PATH.
then 
'yarn global add express-generator'
it add supervisor.cmd this file in "D:\Program Files (x86)\Yarn\node-global",
but when i use 
`express -V`
An error occurred that means the file name, directory name, or volume label syntax is incorrect.

**Comment by jay763190097** [comment]
but when i
`cd C:\Users\Administrator\AppData\Local\Yarn\config\global\node_modules\.bin`
then 
`express -v`
it did work

**Comment by Dragas** [comment]
Can confirm. This issue comes up on windows after updating to 0.27.5 from 0.25.2. For example, in this case in particular.
```
C:\Users\Mantas\Desktop\Projects\Ruby\local-delivery-2-electric-boogaloo>ruby "bin/webpack-dev-server" 
yarn run v0.27.5
$ "C:\Users\Mantas\Desktop\Projects\Ruby\foobar\node_modules\.bin\webpack-dev-server" "--progress" "--color" "--config" C:/Users/Mantas/Desktop/Projects/Ruby/foobar/config/webpack/development.js"
The filename, directory name, or volume label syntax is incorrect.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Mantas\Desktop\Projects\Ruby\foobar>webpack-dev-server.bat

C:\Users\Mantas\Desktop\Projects\Ruby\foobar>ruby "bin/webpack-dev-server" 
yarn run v0.25.2
$ "C:\Users\Mantas\Desktop\Projects\Ruby\foobar\node_modules\.bin\webpack-dev-server" --progress --color --config C:/Users/Mantas/Desktop/Projects/Ruby/foobar/config/webpack/development.js
 10% building modules 2/2 modules 0 activeGenerating SSL Certificate               
```
Apparently the difference between the two is that 0.27.5 wraps all arguments with `""` on windows, for what ever reason, hence the cause for this issue.

**Comment by tom-sherman** [comment]
@Dragas I don't suppose you have found a temporary fix?

**Comment by Dragas** [comment]
I just downgraded to 0.25.2 and called it a day.

**Comment by BYK** [comment]
I think you should be including `D:\Program Files (x86)\Yarn\node-global\.bin` in your `PATH` instead?

**Comment by jay763190097** [comment]
@BYK 
There is no .bin directory under the directory D:\Program Files (x86)\Yarn\node-global.
cmd files are in D:\Program Files (x86)\Yarn\node-global

**Comment by sghobbs** [comment]
Same issue. Trying to use Yarn with the rails Webpacker gem, and it's not working due to Yarn wrapping the cmd arguments in quotes.

Running `ruby bin\webpack` (as instructed in Webpacker docs) outputs the following:
```
yarn run v0.27.5
$ "C:\path\to\node_modules\.bin\webpack" "--config" "C:/path/to/webpack/development.js"
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by BYK** [comment]
Can you try upgrading to a more recent version of Yarn and try again? There were some fixes and changes regarding these parts.

**Comment by BYK** [comment]
Closing due to lack of response. Also, I think adding the result of `yarn global bin` should fix this issue.
