### ISSUE TITLE
Error: ENOENT: no such file or directory, symlink '' -> ...

### ISSUE THREAD

**Issue by slester** [yarnpkg/yarn#3276]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**
When running `yarn`, I receive the following error: 
```Trace:
  Error: ENOENT: no such file or directory, symlink '' -> '/var/www/x/node_modules/browserify/test/symlink_dedupe/one/dir'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn` with browserify in the `package.json` (perhaps others)

**What is the expected behavior?**
For it not to try to create empty symlinks.

**Please mention your node.js, yarn and operating system version.**
node v7.9.0, yarn v0.23.2, `Linux x 4.10.10-1-ARCH #1 SMP PREEMPT Wed Apr 12 18:50:28 CEST 2017 x86_64 GNU/Linux`

**Comment by bestander** [comment]
I'll need a package.json to verify if the fix works but I've put up a PR with a possible fix.

**Comment by slester** [comment]
This issue still occurs with 0.24.5; node v7.10.0, same OS.

`Trace:
  Error: ENOENT: no such file or directory, symlink '' -> '/var/www/ba/node_modules/browserify/test/symlink_dedupe/one/dir'`

**Comment by bestander** [comment]
Thanks, @slester.
Could you add steps to reproduce the issue please

**Comment by slester** [comment]
I am running `yarn` on a `package.json` with a GitHub `username/repo` flag instead of a version number in `devDependencies`. What sort of other information would be helpful besides what I posted in the original issue?

**Comment by bestander** [comment]
Unless there is an easy way to reproduce the issue it is unlikely that anyone will prioritize on fixing it over the other ones that have easy to repeat scenario.

The `ENOENT: no such file or directory, symlink` error looks very specific to the dependencies you have.
Thanks for reporting it, @slester, but your help to isolate the issue would be needed.
Ideally a shell script that would bootstrap a project with the error.

**Comment by slester** [comment]
@bestander Here's a small script that will reproduce the issue. It seems to show up only if you're installing something from GitHub:

```mkdir yarn-ex && cd yarn-ex
echo '{"name":"yarn-ex", "dependencies": {"browserify": "substack/node-browserify"}, "version": "1.0.0"}' > package.json
yarn```

**Comment by bestander** [comment]
Thanks, @slester, I can repro this.
