### ISSUE TITLE
yarn global add raises args.includes is not a function error

### ISSUE THREAD

**Issue by n8agrin** [yarnpkg/yarn#3279]
v0.23.2

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The following error is thrown:

```
> yarn global add phantomjs
yarn global v0.23.2
error An unexpected error occurred: "args.includes is not a function".
info If you think this is a bug, please open a bug report with the information provided in "<...>/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
````

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Try to add a global package with the following command: `yarn global add phantomjs`.
2. 💥 error listed above is produced.

**What is the expected behavior?**
Package is installed in the global yarn directory

**Please mention your node.js, yarn and operating system version.**
node v4.7.0
yarn v0.23.2
macOS 10.12.4

**Comment by SimenB** [comment]
Update yarn to latest: https://github.com/yarnpkg/yarn/releases/tag/v0.23.3

**Comment by n8agrin** [comment]
@SimenB 👍 fixed it for me. Thank you.
