### ISSUE TITLE
Default argumenst for yarn in package.json or .yarnrc

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#3282]
At least I didn't found if it is possible now.
The case: in package json there is a dependency that required old node version (though it actually work ok), so need to use `--ignore-engines` flag, it would be nice if ti would be possible to specify for example in `pakcage.json`: 

```json
"yarn": {
  "args": ["ignore-engines"]
}
```

Or use `.yarnrc` for specifying this.

**Comment by bstro** [comment]
+1 I work in an organization where the `ignore-engines` default behavior is super unpractical.

**Comment by whitecolor** [comment]
BTW https://github.com/whitecolor/yall supports this you can add to package.json:
```
"yarn": {
   args: ["--ignore-engines"]
}
```

**Comment by gsklee** [comment]
@bestander close

Forcing developers to pass the `--ignore-engines` flag explicitly is by design; see [this comment](https://github.com/yarnpkg/rfcs/pull/69#issuecomment-308567694).

**Comment by whitecolor** [comment]
This issue actually has nothing to dot with implicitness/explicitness of particular arguments (`--ignore-engines`), but simplier management of the process of deps installations.

**Comment by gsklee** [comment]
@whitecolor Regarding the proposal of adding or modifying `package.json`/`.yarnrc`, the current rule is that you need to submit the feature request through the [RFC process](https://github.com/yarnpkg/rfcs).

**Comment by tp4k** [comment]
In `.yarnrc` `--install.ignore-engines true`

**Comment by ken0x0a** [comment]
for `global add`
`--global.ignore-engines true`

**Comment by IlyaSemenov** [comment]
FWIW, I'm using `alias yarn='yarn --ignore-engines'`

**Comment by felipecrs** [comment]
For me the following is enough:

```sh-session
$ cat .yarnrc
--ignore-engines true
```

https://github.com/microsoft/vscode-generator-code/issues/223
