### ISSUE TITLE
Yarn clobbers local-only node_module

### ISSUE THREAD

**Issue by wonkodsane** [yarnpkg/yarn#3289]
I couldn't find clear confirmation of expected behavior here or in npm for this.

Scenario:

Prepping a new project -
1. create package.json
2. include a few npm projects as dependencies in package.json
3. also copy in a full local project into node_module that I know I will need but that doesn't exist in npm, purely local (use case - eventually I will create an npm package, but no time today, too busy)
4. I've only created a shell index.js, no requires in it, yet
5. run yarn or yarn install
6. yarn clobbers that node_module's folder completely, poof!

So, is this expected behavior? Should I have put it into /lib until I pushed the module up into npm?

IMHO an overwrite warning is called for even if this is expected behavior...and if this is expected behavior, I couldn't find solid documentation on it anywhere. 

If this is a question of needing to use bundledDependencies and tarballing the module with pack, understood, but again it should be documented, called out, or warned that the folder will be blown away. 

No work lost, but easy to see how it could happen.

yarn v0.23.3
node v6.10.2

**Comment by bestander** [comment]
Yes, this is expected behavior, Yarn owns node_modules folder and cleans it up during installation.
However you can refer projects locally via `file:` and `link:` specifiers
