### ISSUE TITLE
Chocolatey/Homebrew scripts need to check if version is RC before pushing

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#3295]
`scripts/build-chocolatey.ps1` and `scripts/update-homebrew.sh` can take a `YARN_VERSION` environment variable from Jenkins, but it should also take `YARN_RC` and exit if an RC is being published.

In the future, we could probably post RCs to Chocolatey.

**Comment by Daniel15** [comment]
@bestander You're not going to push an RC today, right? I can fix this tonight, I just need to make sure we don't publish any RC releases in the meantime 😛

**Comment by bestander** [comment]
Nope :)

**Comment by Daniel15** [comment]
This was done
