### ISSUE TITLE
"resolutions" do not provide enough granularity when using git 

### ISSUE THREAD

**Issue by chrishyle** [yarnpkg/yarn#3296]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
We are using yarn with git urls for some dependencies, including occasionally using branches of those urls. Assume a tree like this:

<pre>
project
└ dep1: git+ssh://…dep1url…#feature1  (@1.0.0)
└ dep2: git+ssh://…dep2url…
    └ dep1: git+ssh://…dep1url…#master (@1.0.0)
</pre>

Note that in this example, the feature1 branch has the same version number as master (…which is probably incorrect, but happens pretty frequently in our experience, as version numbers usually only bump on landing).

When running `yarn install --flat`, Yarn will correctly detect the versioning issue here and ask which version you'd like to resolve with. The prompt will contain the full git url of each choice. Unfortunately, yarn will only record the version number (1.0.0) of the choice into the `"resolutions"` hash in package.json. Worse, the lockfile will always contain the same "resolved" url (which has the exact sha in it) regardless of which choice you made (it seems to pick the top-level branch as the winner, in this case, feature1). And still worse, depending on which one you picked, the actual dependency which has been installed may be the total opposite from your choice. 

Further compounding the issue is that versions on git branches can change. For example, assume you selected feature1 during the resolution prompt, and got lucky that it was the one which was recorded into the lockfile, so things appear to be working (package.json still says resolve to "1.0.0").  Later, you realize your feature branch needs a new version number, so you bump it to 1.0.1. If you delete your lockfile (or if you are using `--no-lockfile`) and re-run `yarn install --flat`; suddenly and silently the master branch version is being installed. If you do not delete your lockfile, you will not get the new version (but that's probably somewhat expected behavior, since your lockfile has "locked" to 1.0.0).

**If the current behavior is a bug, please provide the steps to reproduce.**

(My apologies, we use private repos where we are seeing this.)

1. Setup a git-url based dependency tree such as described above, with one dependency pointed to different branches with different commits, but the same version number
2. Run `yarn install --flat` and select the sub-dependency's branch during the resolution prompt
3. Check which version got installed, and the sha that was recorded in the lockfile (possibly the wrong one, if not, start over and pick the other dependency during the resolution prompt)
4. Check what was written to package.json's "resolutions" hash– only the version number.

**What is the expected behavior?**
First and foremost, yarn should install and record to the lockfile the dependency that *I actually picked* during the resolution prompt.

Secondly, yarn should record more detailed information in the "resolutions" section of package.json, so that my pick (which could best be described as "which branch did I pick") can be resolved properly on subsequent runs. Possibly something like:
```json
"resolutions": {
    "my-package": "git+ssh://…giturl…#feature1"
}
```
**Please mention your node.js, yarn and operating system version.**
Node v7.5.0; yarn 0.24.0 (installed from source; issue also occurs in 0.23.3 release); macOS 10.12

**Comment by bestander** [comment]
@chrishyle to better understand what you want it would be great if you could set up a few public git repos with the setup you describe.

**Comment by aij** [comment]
I created a small example at https://github.com/aij/yarn-issue-3296/blob/master/package.json , using only  public git repo and NPM.

This could also be seen as an example of #3780 depending on whether you think it should or shouldn't be seen as a version conflict.

**Comment by bestander** [comment]
I think this makes sense.
The team is busy with fixing hi pri issues right now so it will be some time till anyone could look at this proposal.
If anyone is interested to send a PR or lead the discussion here then please do.

**Comment by BYK** [comment]
I have a suspicion that this may be resolved with #3836. What do you think @bestander and @aij?

To see if this is fixed or not, you can try the nightly builds @aij. I'll get back to this soon since I think it is quite important. That said it is a bit of an edge case and there are a few more pressing bugs we are working on right now.

**Comment by aij** [comment]
@BYK Huh, that works for my specific use case -- in that it does what I want without even acknowledging the conflict. I'm not sure whether to be happy or scared. :confused:

**Comment by BYK** [comment]
@aij the new system is pretty smart about picking up intention from conventions. I think it is fine as it is unless you disagree :)

Closing the ticket as the original issue is resolved. We can discuss any further improvements or fixes in new issues.
