### ISSUE TITLE
Adding new packages on Ubuntu 16.04 (on Windows 10) using Yarn 0.23.3 fails with "Error: ENOTEMPTY"

### ISSUE THREAD

**Issue by jannisg** [yarnpkg/yarn#3298]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to install a dependency with yarn using `yarn add {dep}` the install fails with `ENOTEMPTY` error when trying to *delete* the `node_modules/.bin` directory.

The bug is:
1. it should install the dependency but does not.
2. it surely shouldn't delete the entire `.bin` folder right?

**If the current behavior is a bug, please provide the steps to reproduce.**
Prerequisite: 
1. Run on the Ubuntu 16.04 (Bash on Windows) subsystem
2. Install Node and Yarn using `apt-get`

To then produce this error run:
1. `yarn global add create-react-app`
2. `create-react-app client` to scaffold out the fresh app
3. (within the `client/` folder) `yarn add react-router`
4. See [yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/969438/yarn-error.log.txt) for exact details but install fails with:
```
error An unexpected error occurred: "ENOTEMPTY: directory not empty, rmdir '/mnt/c/Users/janni_000/Projects/PUBGMap/client/node_modules/.bin'".
```

**NOTE:** The bug isn't package specific, `react-router` in the steps above can be any valid package and produces the same error.

**What is the expected behavior?**
- `react-router` should have been installed, a symlink being created in `node_modules/.bin` and the `package.json` updated with the new dependency.

**Please mention your node.js, yarn and operating system version.**

**OS**:
- Windows 10 Version 1703 Build 15063.138 includes the "Creator's Update"
- This command was running within the Window's Linux subsystem (Ubuntu 16.04)

**Yarn**: 0.23.3
**Node**: 7.9.0

**Yarn Error Log File**
[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/969438/yarn-error.log.txt)

**Comment by BYK** [comment]
This should be fixed in the more recent releases so closing.
