### ISSUE TITLE
Install stalls on private packages that have private packages as a dependency.

### ISSUE THREAD

**Issue by joeycadle** [yarnpkg/yarn#3302]
yarn install consistently fails by either stalling indefinitely, or producing an ssh connection reset error when attempting to install a private package that has a private package as a dependency. Removing those dependencies allows the install to go through fine, which gives me cause to think private package-ception is the problem.

**Comment by bestander** [comment]
Thanks for reporting but we can't act on this description.
Any chance you could set up a repro scenario?
