### ISSUE TITLE
Removing a git package from package.json and running `yarn` does not update yarn.lock

### ISSUE THREAD

**Issue by jbinto** [yarnpkg/yarn#3306]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**

For a regular package, things work fine:

```
yarn add express
# yarn.lock is edited to add express.

# Now edit package.json and remove express.
vi package.json

# Run `yarn` again.
yarn

# yarn.lock has been changed to remove express, as expected
```

But for git packages, this doesn't work:

```
yarn add git+https://github.com/jbinto/yup
# yarn.lock is edited to add the yup git repo.

# Now edit package.json and remove yup.
vi package.json

# Run `yarn` again.
yarn

# yarn.lock has NOT been changed to remove yup (not expected)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See above. I also have a small repro repo, just read through the commits, it's fairly apparent what's happening:

https://github.com/jbinto/yarn-repro/commits/master

**What is the expected behavior?**

Removing a `git` package from `package.json` and then running `yarn` should update the `yarn.lock`.

To work around this I'd have to either:
a) update `yarn.lock` by hand (which is not advised),
b) delete `yarn.lock` and regenerate, but then lose track of which dependencies I'm currently locked at

**Please mention your node.js, yarn and operating system version.**

yarn 0.23.4, node v7.9.0, OS X 10.12.4

**Comment by bestander** [comment]
Thanks for repro steps, I confirm it happens

**Comment by aracarie** [comment]
I'm actually having this issue for regular packages too - Yarn 0.24.6 / Node.js v6.10.3.

I can work on this if you'd like?

**Comment by bestander** [comment]
Of course, @aracarie, please do
