### ISSUE TITLE
yarn install --prod installs many more packages than npm install --prod

### ISSUE THREAD

**Issue by coreyfarrell** [yarnpkg/yarn#3312]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn install --prod` installs many packages that are not requested by package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Download minimist - https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz
* Extract and enter folder.
* Run `npm install --prod`
* Note that no modules are installed (minimist has no production deps).
* Run `yarn install --prod` (no yarn.lock exists before this command)
* Not that many modules are installed.

**What is the expected behavior?**
Extra modules should not be installed.

**Please mention your node.js, yarn and operating system version.**
node.js: v7.9.0
yarn: 0.23.4
CentOS 7
npm: 4.2.0

**Comment by bestander** [comment]
Yeah, I suppose there is no need to download and unzip the tarballs that are dev only dependencies.
Send a PR

**Comment by pichouk** [comment]
@bestander said in #3577 that it was fix in master, so I guess it can be closed.
