### ISSUE TITLE
"yarn install --production" downloads/caches all dev dependencies

### ISSUE THREAD

**Issue by Codelica** [yarnpkg/yarn#3323]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`yarn install --production` downloads and caches (in ~/.cache/..) all devDependencies found in package.json rather then just the production dependencies.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn install --production` with any package containing devDependencies and you will see them being downloaded and placed in ~/.cache/.. along with production dependencies.

**What is the expected behavior?**

When run with `--production` only production dependencies would be downloaded and cached.

**Please mention your node.js, yarn and operating system version.**

Node 7.10.0
Yarn 0.23.2
Ubuntu 16.0.4.2 LTS

**Comment by soulne4ny** [comment]
As well when there is git url in devDependencies it requires git installed even when running with `--prod`.

**Comment by belozer** [comment]
https://github.com/yarnpkg/yarn/issues/3312
