### ISSUE TITLE
[Feature request] Clean named package from local cache

### ISSUE THREAD

**Issue by kslimani** [yarnpkg/yarn#3324]
> **Do you want to request a *feature* or report a *bug*?**

It is a request feature. 

> **What is the current behavior?**

Current behaviour is `yarn cache clean` will clean all cached package from local cache.

> **If the current behavior is a bug, please provide the steps to reproduce.**

Current behaviour is not a bug.

> **What is the expected behavior?**

I think i could be a nice addition to have a feature to remove a "named package" from local cache. *(an alternative from removing all by default)*

For example :

```shell
$ yarn cache clean <PACKAGE_NAME>
```

*This syntax is just a proposition, there may be a better syntax to achieve this.*

What do you guys think about this ?

**Comment by bestander** [comment]
Nice feature, send a PR

**Comment by kslimani** [comment]
I close the issue, as #3523 is merged.
