### ISSUE TITLE
Software Architecture analysis of Yarn

### ISSUE THREAD

**Issue by TimvdLippe** [yarnpkg/yarn#3326]
Dear Yarn developers/community,

You might recognize our names, but we are @clanghout, @gijsweterings, @keraito and @timvdlippe. For the last couple of months, Yarn was our subject project for the Software Architecture course at the Delft University of Technology.

For this course, we wrote a detailed chapter of our analysis of the architecture of Yarn and investigated any potential deficiencies. For example, we investigated the internal package dependencies as well as potential instances of technical debt. 

Our whole analysis is summarized in a chapter of the book written by all students participating in the course. You can find our chapter at https://delftswa.gitbooks.io/desosa-2017/content/yarn/chapter.html

Thank you for this amazing project and hopefully our feedback is useful for future development. Please let us know what you think or if you have any questions!

Regards,
team-yarn

**Comment by cpojer** [comment]
wow, this is awesome! I hope your project was successful and that you'll pop up with pull requests to Yarn – we'd love to see you contribute more to Yarn in the future :)

**Comment by cpojer** [comment]
@TimvdLippe I'm managing the JavaScript Tools team at Facebook. Would you mind sending me your email addresses to cpojer@fb.com? I'd love to get in touch.

**Comment by TimvdLippe** [comment]
@cpojer You have got mail 😄

**Comment by stryju** [comment]
this is so cool!

**Comment by Daniel15** [comment]
This is awesome! Great work.

I just wanted to mention that in addition to Travis, CircleCI and AppVeyor, we're also using Jenkins (https://build.dan.cx/view/Yarn/) for a few tasks. We've got a nightly end-to-end test run that spins up a new Ubuntu Docker container, installs the nightly build of Yarn via `apt-get`, and does a  simple `yarn add` to ensure it's working as expected. Most of the release infrastructure for publishing new versions runs through Jenkins too.

**Comment by clanghout** [comment]
Thanks a lot for all the great reactions! Even more motivation to keep looking into yarn!
