### ISSUE TITLE
yarn install issue  unexpected error found

### ISSUE THREAD

**Issue by taileshrbamankar** [yarnpkg/yarn#3328]
Hi,

I am facing issue to install yarn in jhipster. yarn install command fails how be below error. I tried to install yarn from project and from globally also. 

on fire of yarn install command on cmd 
yarn install v0.23.4
[1/4] Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/bower: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.co
m:443".
info If you think this is a bug, please open a bug report with the information provided in "D:\\blog\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

OS : 7 
node : v6.10.3
yarn : v0.23.4

**Comment by rally25rs** [comment]
The address "https://registry.yarnpkg.com/bower" seems to be responding at the moment. Are you still having this problem? If so, could you just try opening "https://registry.yarnpkg.com/bower" in your web browser and see if you get a response?

**Comment by taileshrbamankar** [comment]
Still Facing same issue

**Comment by bestander** [comment]
There are no steps to reproduce on the issue.
Please provide a package.json/yarn.lock how to get this issue reproduced.

**Comment by wangtao0101** [comment]
+1

**Comment by NorbertPiskorz** [comment]
I am encountering the same issue with another package that is accessible through a normal request in the browser. https://registry.yarnpkg.com/mobx.

```
% yarn add mobx mobx-react
yarn add v0.19.1
[1/4] 🔍  Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/mobx: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/Applications/XAMPP/xamppfiles/htdocs/oneminute/yarn-error.log".
```

node v6.9.5
yarn 0.19.1
mac

**Comment by vinhhrv** [comment]
Same issue

```
> Successfully installed Yarn 1.9.4! Please open another terminal where the `yarn` command will now be available.
$ yarn global add json-merge-cli
yarn global v1.6.0
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/json-merge-cli: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by avallbona** [comment]
Hi,
it seems there are some dns issues
https://status.npmjs.org/incidents/v22ffls5cd6h

**Comment by jirichmiel** [comment]
Thanks. Rewrite of DNS records by /etc/hosts helped me.
