### ISSUE TITLE
Creating yarn.lock file after running "yarn -v"

### ISSUE THREAD

**Issue by g-plane** [yarnpkg/yarn#3329]
**Do you want to request a *feature* or report a *bug*?**

Feature request

**What is the current behavior?**
After I ran `yarn -v`, it will generate `yarn.lock` in a non-yarn project directory.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn -v` in a non-yarn project directory which does not include `yarn.lock` file.

**What is the expected behavior?**
Just show the version of yarn in CLI without creating `yarn.lock` file if I run `yarn -v`.

**Please mention your node.js, yarn and operating system version.**
node.js: v7.9.0
OS: Windows 10 x64

**Comment by rally25rs** [comment]
Verified on Yarn 0.23.4

I suspect that this happens because the "default" `yarn` command does an `install`. A `yarn install -v` would create a lock file. Probably need to add a check for no explicit command, and the only option is `-v`.

**Comment by rally25rs** [comment]
@bestander triage: Duplicate of #2710

**Comment by g-plane** [comment]
In fact, to display version of Yarn we must run `yarn -V` or `yarn --version`. But in most of the time, we are used to using `-v` to do that.

**Comment by bestander** [comment]
I agree, this is annoying behavior

**Comment by bestander** [comment]
Send a PR for Yarn `install` to not create a yarn.lock if there is no package.json in the folder.
Also maybe send a PR to make -v -and -V to be the same, I get confused all the time. But that one may be debatable because of some unix CMD standarfds

**Comment by g-plane** [comment]
Personally, I prefer to making `-v` and `-V` to be the same. May I send a PR?

**Comment by bestander** [comment]
Please do
