### ISSUE TITLE
uninstall Yarn when using Windows Installer?

### ISSUE THREAD

**Issue by Sensiblemnd** [yarnpkg/yarn#3331]
How do you actually uninstall yarn when installed by the windows installer???

**Comment by Daniel15** [comment]
Same as any other Windows app. Go to "Add or remove programs" in control panel (or open the start menu and search for "remove program")

![](http://ss.dan.cx/2017/05/Program_Manager_05-22.25.08.png)

Then search for Yarn and click "uninstall"
![](http://ss.dan.cx/2017/05/Settings_05-22.26.20.png)

**Comment by PlutoCA** [comment]
![image](https://user-images.githubusercontent.com/31099607/68099295-abdb4b00-fefc-11e9-9fcc-bd3aa31f7d7a.png)
I did, but it still works

**Comment by algorithmhash** [comment]
Do you have chocolatey installed and did you install it that way? Or did you manually install it from Yarn @PlutoCA ?

**Comment by Daniel15** [comment]
> I did, but it still works

Did you install Yarn via a different method (eg. Chocolatey or npm)? Can you try find where the `yarn.cmd` file is located on your hard drive?

**Comment by EduVencovsky** [comment]
If you are using [nvm](https://github.com/coreybutler/nvm-windows), try [this ](https://stackoverflow.com/a/63340369/9119186). I had the same problem as @PlutoCA .

**Comment by mena234** [comment]
> If you are using [nvm](https://github.com/coreybutler/nvm-windows), try [this ](https://stackoverflow.com/a/63340369/9119186). I had the same problem as @PlutoCA .

This solved my issue, thanks a lot.
