### ISSUE TITLE
Yarn install folder name different from npm install

### ISSUE THREAD

**Issue by davidpicarra** [yarnpkg/yarn#3333]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
Repository created to show this bug: https://github.com/davidpicarra/yarn-bug

1. have a ```package.json``` with a dependency where the key is different than the name inside the imported dependency, for example:
```"fake-vue": "git+https://github.com/vuejs/vue.git#b977c77"```
2. execute ```yarn```
3. check ```node_modules/fake-vue``` exists and ```node_modules/vue``` doesn't exist
4. delete ```node_modules```
5. execute ```npm install```
6. check only ```node_modules/vue``` exists

**What is the expected behavior?**
It should generate the same folder output in both cases, was expecting the folder ```node_modules/vue``` to exist when installing packages via ```yarn```

**Please mention your node.js, yarn and operating system version.**
→ yarn --version
0.23.4

→ node --version
v7.10.0

→ npm --version
4.2.0

macOS Sierra 10.12.4

**Comment by Daniel15** [comment]
Is there a use case for the key in package.json differing from the package name?

**Comment by davidpicarra** [comment]
Working with a private repository where the owner changed the name of the package when there was a migration from gitlab to github.

All references in my project changed to the new private repository except the key in the ```package.json``` to keep a reference to the old private repo name. Just wondering if this is expected behaviour when it's different from npm install.

**Comment by bestander** [comment]
PR welcome :)

**Comment by davidpicarra** [comment]
NPM 5.0.3 doesn't seem to install anything now. It appears since the key `fake-vue` doesn't match the name of the repo/package-name `vue` then it just doesn't install it. If I change the key to the correct one it will install normally.

Not sure what to take out of this new NPM version, is it worth investigating this yarn issue still? I've been trying to get it sorted out but taking way longer than I expected.

This comment and findings were done with the following versions:
```
→ yarn --version
0.24.6

→ node --version
v8.0.0

→ npm --version
5.0.3
```

**Comment by bestander** [comment]
After thinking about it a bit more I think Yarn does it right here.

**Comment by BYK** [comment]
I don't think we are going to address this so closing. Thanks for bringing it up.
