### ISSUE TITLE
yarn pack does not honor globs in "files" option of package.json

### ISSUE THREAD

**Issue by jrop** [yarnpkg/yarn#3336]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

My package.json "files" option specifies globs as entries:

```txt
  "files": [
    "config/**/*.js",
    "lib/**/*.js"
  ]
```

When I run `yarn pack` it produces a `.tgz` file with the following entries:

```txt
package
package/.gitignore
package/config/.gitignore
package/files/.gitignore
package/package.json
```

However, when I run `npm pack`, it packs the following files instead:

```txt
package/package.json
package/lib/file1.js
package/lib/file2.js
package/lib/index.js
package/config/index.js
package/config/config1.js
package/config/config2.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
See the `npm pack` output

**Please mention your node.js, yarn and operating system version.**
node: v7.7.3
yarn: v0.23.4
OS: macOS Sierra 10.12.2

**Comment by jrop** [comment]
Keeping notes for myself:

yarn pack eventually calls: [this line](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/pack.js#L119) with the following filters:

```js
[ { base: '.',
    isNegation: true,
    regex: /^(?:\/(?=.)package\.json)$/i },
  { base: '.',
    isNegation: true,
    regex: /^(?:\/(?=.)readme[^\/]*?)$/i },
  { base: '.',
    isNegation: true,
    regex: /^(?:\/(?!\.)(?=.)(?:license|licence)+[^\/]*?)$/i },
  { base: '.',
    isNegation: true,
    regex: /^(?:\/(?!\.)(?=.)(?:changes|changelog|history)+[^\/]*?)$/i },
  { base: '.',
    isNegation: false,
    regex: /^(?:(?!\.)(?=.)[^\/]*?)$/i },
  { base: '.', isNegation: false, regex: /^(?:(?=.)\.[^\/]*?)$/i },
  { base: '.',
    isNegation: true,
    regex: /^(?:(?=.)config\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?\.js)$/i },
  { base: '.',
    isNegation: true,
    regex: /^(?:(?=.)lib\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?\.js)$/i },
  { base: '.',
    isNegation: false,
    regex: /^(?:\/(?=.)node_modules)$/i },
  { base: 'files',
    isNegation: true,
    regex: /^(?:(?=.)\.gitignore)$/i },
  { base: 'files',
    isNegation: false,
    regex: /^(?:(?!\.)(?=.)[^\/]*?)$/i } ]
```

**Comment by jrop** [comment]
More notes: it ends up calling to [here](https://github.com/yarnpkg/yarn/blob/master/src/util/filter.js#L101) with the following context:

```js
filter = { base: '.',
  isNegation: true,
  regex: /^(?:(?=.)lib\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?\.js)$/i }
basename = 'myfile.js'
loc = 'lib/myfile.js'
// matchesFilter(...) returns false in this case
```

**Comment by jrop** [comment]
So this is effectively console.logging `filters` from pack.js:

Ignore list:
```txt
!/package.json
!/readme*
!/+(license|licence)*
!/+(changes|changelog|history)*
*
.*
!config/**/*.js
!lib/**/*.js
/lib/
/node_modules/
!.gitignore
```

**Comment by jrop** [comment]
Interesting:

```js
const mm = require('minimatch')
const loc = 'lib/sftp.js'
const re = mm.makeRe('lib/**/*.js', {nocase: true})

re.test(loc) // => false
mm(loc, 'lib/**/*.js', {nocase: true}) // => true
```

minimatch version: 3.0.3

**Comment by jrop** [comment]
See this line (#648) in [minimatch.js](https://github.com/isaacs/minimatch/blob/master/minimatch.js#L648)

**Comment by bestander** [comment]
Send a PR with tests please :)

**Comment by jrop** [comment]
@bestander I have a PR here: yarnpkg/yarn/pull/3339, and per your request I have added a fixture + a test that tests this.  I am having trouble getting the tests to pass: sometimes an async timeout error is thrown.  Is that normal?

**Comment by bestander** [comment]
Yeah, I am ashamed that our tests are flaky sometimes.
Just don't have time to make them more robust.

**Comment by bestander** [comment]
@jrop when to expect the PR?
I'd like to cut 0.25 release
