### ISSUE TITLE
Problème yarn with shoutem please

### ISSUE THREAD

**Issue by ridz7** [yarnpkg/yarn#3340]
i copy the problem
Thank if you can help me
I have the problemat the end 👍 

yarn install v0.23.4
info No lockfile found.
[1/4] Resolving packages...
error Refusing to download the git repo {"protocol":"https:","hostname":"bitbucket.org","repository":"https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git"} over HTTPS without a commit hash - possible certificate error?
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

D:\Dev\React\RestauCoApp-master\RestauCoApp-master>shoutem run-android
? Select your app Small business app (6540)
@shoutem/app-build-script@0.0.1-alpha.5 C:\Users\Rdz\.shoutem\production\client\6540\scripts
+-- command-line-args@2.1.6
| +-- array-back@1.0.4
| | `-- typical@2.6.0  deduped
| +-- command-line-usage@2.0.5
| | +-- ansi-escape-sequences@2.2.2
| | | +-- array-back@1.0.4  deduped
| | | `-- collect-all@0.2.1
| | |   +-- stream-connect@1.0.2
| | |   | `-- array-back@1.0.4  deduped
| | |   +-- stream-via@0.1.1
| | |   `-- typical@2.6.0  deduped
| | +-- array-back@1.0.4  deduped
| | +-- column-layout@2.1.4
| | | +-- ansi-escape-sequences@2.2.2  deduped
| | | +-- array-back@1.0.4  deduped
| | | +-- collect-json@1.0.8
| | | | +-- collect-all@1.0.2
| | | | | +-- stream-connect@1.0.2  deduped
| | | | | `-- stream-via@1.0.3  deduped
| | | | +-- stream-connect@1.0.2  deduped
| | | | `-- stream-via@1.0.3
| | | +-- command-line-args@2.1.6  deduped
| | | +-- core-js@2.4.1  deduped
| | | +-- deep-extend@0.4.1
| | | +-- feature-detect-es6@1.3.1  deduped
| | | +-- object-tools@2.0.6
| | | | +-- array-back@1.0.4  deduped
| | | | +-- collect-json@1.0.8  deduped
| | | | +-- object-get@2.1.0
| | | | +-- test-value@1.1.0
| | | | | +-- array-back@1.0.4  deduped
| | | | | `-- typical@2.6.0  deduped
| | | | `-- typical@2.6.0  deduped
| | | +-- typical@2.6.0  deduped
| | | `-- wordwrapjs@1.2.1  deduped
| | +-- feature-detect-es6@1.3.1  deduped
| | +-- typical@2.6.0  deduped
| | `-- wordwrapjs@1.2.1
| |   +-- array-back@1.0.4  deduped
| |   `-- typical@2.6.0  deduped
| +-- core-js@2.4.1
| +-- feature-detect-es6@1.3.1
| | `-- array-back@1.0.4  deduped
| +-- find-replace@1.0.3
| | +-- array-back@1.0.4  deduped
| | `-- test-value@2.1.0
| |   +-- array-back@1.0.4  deduped
| |   `-- typical@2.6.0  deduped
| `-- typical@2.6.0
+-- es6-symbol@3.1.1
| +-- d@1.0.0
| | `-- es5-ext@0.10.15  deduped
| `-- es5-ext@0.10.15
|   +-- es6-iterator@2.0.1
|   | +-- d@1.0.0  deduped
|   | +-- es5-ext@0.10.15  deduped
|   | `-- es6-symbol@3.1.1  deduped
|   `-- es6-symbol@3.1.1  deduped
+-- fs-extra@1.0.0
| +-- graceful-fs@4.1.11
| +-- jsonfile@2.4.0
| | `-- graceful-fs@4.1.11  deduped
| `-- klaw@1.3.1
|   `-- graceful-fs@4.1.11  deduped
+-- glob@7.1.1
| +-- fs.realpath@1.0.0
| +-- inflight@1.0.6
| | +-- once@1.4.0  deduped
| | `-- wrappy@1.0.2
| +-- inherits@2.0.3
| +-- minimatch@3.0.3
| | `-- brace-expansion@1.1.7
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| +-- once@1.4.0
| | `-- wrappy@1.0.2  deduped
| `-- path-is-absolute@1.0.1
+-- glob-to-regexp@0.3.0
+-- jimp@0.2.27
| +-- bignumber.js@2.4.0
| +-- bmp-js@0.0.1
| +-- es6-promise@3.3.1
| +-- exif-parser@0.1.9
| +-- file-type@3.9.0
| +-- jpeg-js@0.2.0
| +-- load-bmfont@1.3.0
| | +-- buffer-equal@0.0.1
| | +-- mime@1.3.4  deduped
| | +-- parse-bmfont-ascii@1.0.6
| | +-- parse-bmfont-binary@1.0.6
| | +-- parse-bmfont-xml@1.1.3
| | | +-- xml-parse-from-string@1.0.0
| | | `-- xml2js@0.4.17
| | |   +-- sax@1.2.2
| | |   `-- xmlbuilder@4.2.1
| | |     `-- lodash@4.17.4  deduped
| | +-- xhr@2.4.0
| | | +-- global@4.3.2
| | | | +-- min-document@2.19.0
| | | | | `-- dom-walk@0.1.1
| | | | `-- process@0.5.2
| | | +-- is-function@1.0.1
| | | +-- parse-headers@2.0.1
| | | | +-- for-each@0.3.2
| | | | | `-- is-function@1.0.1  deduped
| | | | `-- trim@0.0.1
| | | `-- xtend@4.0.1  deduped
| | `-- xtend@4.0.1
| +-- mime@1.3.4
| +-- pixelmatch@4.0.2
| | `-- pngjs@3.2.0  deduped
| +-- pngjs@3.2.0
| +-- read-chunk@1.0.1
| +-- request@2.81.0  deduped
| +-- stream-to-buffer@0.1.0
| | `-- stream-to@0.2.2
| +-- tinycolor2@1.4.1
| `-- url-regex@3.2.0
|   `-- ip-regex@1.0.3
+-- lodash@4.17.4
+-- node-watch@0.3.5
+-- parse-gitignore@0.3.1
| +-- array-unique@0.2.1
| `-- is-glob@2.0.1
|   `-- is-extglob@1.0.0
+-- plist@2.1.0
| +-- base64-js@1.2.0
| +-- xmlbuilder@8.2.2
| `-- xmldom@0.1.27
+-- ps-node@0.1.6
| `-- table-parser@0.1.3
|   `-- connected-domain@1.0.0
+-- request@2.81.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.6.0
| +-- caseless@0.12.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.1
| +-- forever-agent@0.6.1
| +-- form-data@2.1.4
| | +-- asynckit@0.4.0
| | +-- combined-stream@1.0.5  deduped
| | `-- mime-types@2.1.15  deduped
| +-- har-validator@4.2.1
| | +-- ajv@4.11.8
| | | +-- co@4.6.0
| | | `-- json-stable-stringify@1.0.1
| | |   `-- jsonify@0.0.0
| | `-- har-schema@1.0.5
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | | `-- hoek@2.16.3  deduped
| | +-- cryptiles@2.0.5
| | | `-- boom@2.10.1  deduped
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| |   `-- hoek@2.16.3  deduped
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.4.0
| | | +-- assert-plus@1.0.0
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.3
| | | `-- verror@1.3.6
| | |   `-- extsprintf@1.0.2  deduped
| | `-- sshpk@1.13.0
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- bcrypt-pbkdf@1.0.1
| |   | `-- tweetnacl@0.14.5  deduped
| |   +-- dashdash@1.14.1
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   | `-- jsbn@0.1.1  deduped
| |   +-- getpass@0.1.7
| |   | `-- assert-plus@1.0.0
| |   +-- jodid25519@1.0.2
| |   | `-- jsbn@0.1.1  deduped
| |   +-- jsbn@0.1.1
| |   `-- tweetnacl@0.14.5
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.15
| | `-- mime-db@1.27.0
| +-- oauth-sign@0.8.2
| +-- performance-now@0.2.0
| +-- qs@6.4.0
| +-- safe-buffer@5.0.1
| +-- stringstream@0.0.5
| +-- tough-cookie@2.3.2
| | `-- punycode@1.4.1
| +-- tunnel-agent@0.6.0
| | `-- safe-buffer@5.0.1  deduped
| `-- uuid@3.0.1
+-- rimraf@2.6.1
| `-- glob@7.1.1  deduped
+-- shelljs@0.7.7
| +-- glob@7.1.1  deduped
| +-- interpret@1.0.3
| `-- rechoir@0.6.2
|   `-- resolve@1.3.3
|     `-- path-parse@1.0.5
+-- superspawn@0.1.0
| +-- q@1.5.0
| `-- which@1.2.14
|   `-- isexe@2.0.0
`-- xcode@0.9.3
  +-- pegjs@0.10.0
  +-- simple-plist@0.2.1
  | +-- bplist-creator@0.0.7
  | | `-- stream-buffers@2.2.0
  | +-- bplist-parser@0.1.1
  | | `-- big-integer@1.6.22
  | `-- plist@2.0.1
  |   +-- base64-js@1.1.2
  |   +-- xmlbuilder@8.2.2
  |   `-- xmldom@0.1.27  deduped
  `-- uuid@3.0.1  deduped

npm WARN @shoutem/app-build-script@0.0.1-alpha.5 No description
npm WARN @shoutem/app-build-script@0.0.1-alpha.5 No repository field.
npm WARN @shoutem/app-build-script@0.0.1-alpha.5 No license field.

> @shoutem/mobile-app@0.56.0 configure C:\Users\Rdz\.shoutem\production\client\6540
> node scripts/configure

starting build for app 6540
cleaning temp files: 10.065ms
download configuration: 1077.348ms
Load local extensions: 0.052ms
Installing dependencies:
{
  "@shoutem/animation": "^0.10.2",
  "@shoutem/core": "0.0.48",
  "@shoutem/redux-composers": "0.1.0-beta.4",
  "@shoutem/redux-io": "1.0.4",
  "@shoutem/theme": "^0.9.0",
  "@shoutem/ui": "0.11.1-support.3",
  "@shoutem/ui-addons": "0.0.13",
  "lodash": "^4.10.1",
  "moment": "^2.13.0",
  "whatwg-fetch": "1.0.0",
  "react": "15.4.0",
  "react-native": "0.39.2",
  "react-native-browser-polyfill": "^0.1.1",
  "react-native-calendar-manager": "git+https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git",
  "react-native-code-push": "^1.16.1-beta",
  "react-native-fbsdk": "0.4.0",
  "react-native-google-analytics-bridge": "4.0.3",
  "react-native-restart": "0.0.1",
  "react-native-share": "1.0.13",
  "react-native-vector-icons": "^2.0.3",
  "react-native-maps": "git+https://github.com/5minutes/react-native-maps.git#google-play-dependency-fix",
  "react-native-video": "^0.8.0",
  "react-redux": "^5.0.2",
  "redux": "^3.3.1",
  "redux-action-buffer": "^1.0.1",
  "redux-persist": "4.1.0",
  "redux-api-middleware": "2.0.0-beta.1",
  "redux-logger": "2.6.1",
  "redux-thunk": "^2.0.0",
  "shoutem.about": "https://extensions.static.shoutem.com/shoutem/about/0.9.8/app.tgz?timestamp=1491464876144",
  "shoutem.analytics": "https://extensions.static.shoutem.com/shoutem/analytics/0.1.9/app.tgz?timestamp=1488546454968",
  "shoutem.application": "https://extensions.static.shoutem.com/shoutem/application/0.2.11/app.tgz?timestamp=1491134153289",
  "shoutem.arno-theme": "https://extensions.static.shoutem.com/shoutem/arno-theme/0.0.52/app.tgz?timestamp=1491464891213",
  "shoutem.auth": "https://extensions.static.shoutem.com/shoutem/auth/0.6.4/app.tgz?timestamp=1491246106362",
  "shoutem.books": "https://extensions.static.shoutem.com/shoutem/books/0.2.15/app.tgz?timestamp=1488546486187",
  "shoutem.cms": "https://extensions.static.shoutem.com/shoutem/cms/0.10.12/app.tgz?timestamp=1491134263898",
  "shoutem.events": "https://extensions.static.shoutem.com/shoutem/events/0.9.15/app.tgz?timestamp=1491464920296",
  "shoutem.favorites": "https://extensions.static.shoutem.com/shoutem/favorites/0.1.9/app.tgz?timestamp=1488546514662",
  "shoutem.google-analytics": "https://extensions.static.shoutem.com/shoutem/google-analytics/0.1.10/app.tgz?timestamp=1488546536359",
  "shoutem.layouts": "https://extensions.static.shoutem.com/shoutem/layouts/0.1.16/app.tgz?timestamp=1491294133439",
  "shoutem.menu": "https://extensions.static.shoutem.com/shoutem/menu/0.10.12/app.tgz?timestamp=1488546554846",
  "shoutem.navigation": "https://extensions.static.shoutem.com/shoutem/navigation/0.5.29/app.tgz?timestamp=1491134356159",
  "shoutem.news": "https://extensions.static.shoutem.com/shoutem/news/0.9.16/app.tgz?timestamp=1491251998512",
  "shoutem.people": "https://extensions.static.shoutem.com/shoutem/people/0.10.14/app.tgz?timestamp=1490114177545",
  "shoutem.persist": "https://extensions.static.shoutem.com/shoutem/persist/0.1.8/app.tgz?timestamp=1488546585427",
  "shoutem.photos": "https://extensions.static.shoutem.com/shoutem/photos/0.9.6/app.tgz?timestamp=1491134419096",
  "shoutem.places": "https://extensions.static.shoutem.com/shoutem/places/0.9.17/app.tgz?timestamp=1491464975377",
  "shoutem.platform-analytics": "https://extensions.static.shoutem.com/shoutem/platform-analytics/0.1.9/app.tgz?timestamp=1488546597902",
  "shoutem.preview": "https://extensions.static.shoutem.com/shoutem/preview/0.1.8/app.tgz?timestamp=1488546601636",
  "shoutem.products": "https://extensions.static.shoutem.com/shoutem/products/0.9.16/app.tgz?timestamp=1488546606139",
  "shoutem.push-notifications": "https://extensions.static.shoutem.com/shoutem/push-notifications/0.1.12/app.tgz?timestamp=1490114200900",
  "shoutem.rss": "https://extensions.static.shoutem.com/shoutem/rss/0.2.13/app.tgz?timestamp=1490114214416",
  "shoutem.rss-news": "https://extensions.static.shoutem.com/shoutem/rss-news/0.9.14/app.tgz?timestamp=1490114219595",
  "shoutem.rss-photos": "https://extensions.static.shoutem.com/shoutem/rss-photos/0.9.6/app.tgz?timestamp=1491134467416",
  "shoutem.rss-videos": "https://extensions.static.shoutem.com/shoutem/rss-videos/0.10.11/app.tgz?timestamp=1488546638820",
  "shoutem.rubicon-noir-theme": "https://extensions.static.shoutem.com/shoutem/rubicon-noir-theme/0.0.17/app.tgz?timestamp=1491246214506",
  "shoutem.rubicon-rose-theme": "https://extensions.static.shoutem.com/shoutem/rubicon-rose-theme/0.0.17/app.tgz?timestamp=1491246220261",
  "shoutem.rubicon-theme": "https://extensions.static.shoutem.com/shoutem/rubicon-theme/0.1.50/app.tgz?timestamp=1491465044533",
  "shoutem.shopify": "https://extensions.static.shoutem.com/shoutem/shopify/0.1.9/app.tgz?timestamp=1490974747036",
  "shoutem.sub-navigation": "https://extensions.static.shoutem.com/shoutem/sub-navigation/0.1.1/app.tgz?timestamp=1488546693122",
  "shoutem.theme": "https://extensions.static.shoutem.com/shoutem/theme/0.1.7/app.tgz?timestamp=1487859791935",
  "shoutem.video": "https://extensions.static.shoutem.com/shoutem/video/0.10.12/app.tgz?timestamp=1488546697219",
  "shoutem.web-view": "https://extensions.static.shoutem.com/shoutem/web-view/0.9.6/app.tgz?timestamp=1490974764904"
}
yarn install v0.23.4
info No lockfile found.
[1/4] Resolving packages...
error Refusing to download the git repo {"protocol":"https:","hostname":"bitbucket.org","repository":"https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git"} over HTTPS without a commit hash - possible certificate error?
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
{ Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\Rdz\.shoutem\production\client\6540\scripts\node_modules\superspawn\lib\index.js:172:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) code: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shoutem/mobile-app@0.56.0 configure: `node scripts/configure`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shoutem/mobile-app@0.56.0 configure script 'node scripts/configure'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @shoutem/mobile-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/configure
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @shoutem/mobile-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @shoutem/mobile-app
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rdz\AppData\Roaming\npm-cache\_logs\2017-05-06T18_43_10_673Z-debug.log
`npm run configure` failed with code 1

If you think this error is caused by bug in the shoutem command, you can report the issue here: https://github.com/shoutem/cli/issues
Make sure to include the information printed using the `shoutem last-error` command

**Comment by rally25rs** [comment]
From a quick look at the Yarn code, that error message would seem to indicate that the command

```
git ls-remote -t https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git
```

returned a non-0 result code.

However if I run that command myself, I get a 0 result code, which would indicate success.
Perhaps you can try this from your command line?

```
~/test : git ls-remote -t https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git
~/test : echo $?
0
```

**Comment by bestander** [comment]
Please provide a package.json for us to reproduce.

From the error message this looks quite actionable 
{"protocol":"https:","hostname":"bitbucket.org","repository":"https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git"} over HTTPS without a commit hash - possible certificate error?
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
