### ISSUE TITLE
Cannot install global binaries

### ISSUE THREAD

**Issue by trevorwang** [yarnpkg/yarn#3345]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**

```
➜  ~ yarn global add create-react-app --prefix /usr/local
yarn global v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "create-react-app@1.3.0" with binaries:
      - create-react-app
warning No license field
✨  Done in 10.23s.
➜  ~ which create-react-app
create-react-app not found
```
**What is the expected behavior?**
`create-react-app` can be installed at `/usr/local/bin`
**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn global add create-react-app --prefix /usr/local`
**Please mention your node.js, yarn and operating system version.**
yarn v0.23.4
nodes v7.10.0
macOS v10.12.4

**Comment by Deathis** [comment]
At website https://yarnpkg.com/en/docs/install,the infomation of `Path Setup`:
`Add export PATH="$PATH:`yarn global bin`" to your profile (this may be in your .profile, .bashrc, .zshrc, etc.)`;
I did `export PATH="$PATH:`yarn global bin`"` , it dosn't work;
The right way is ` export PATH="$PATH:$(yarn global bin)"  `.


**# Add export PATH="$PATH:$(yarn global bin)" to your profile (this may be in your .profile, .bashrc, .zshrc, etc.)`**

**Comment by Daniel15** [comment]
Are you running as root? Normally regular users don't have permission to create files in `/usr/local`.

**Comment by trevorwang** [comment]
@Deathis I have set this in my .zshrc file

**Comment by trevorwang** [comment]
@Daniel15 I am sure that I have the permission for `/usr/local`
It doesn't work for `~/.local` folder.
```
➜  ~ yarn global add bower --prefix ~/.local
yarn global v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "bower@1.8.0" with binaries:
      - bower
warning No license field
✨  Done in 9.35s.
```

**Comment by voxsim** [comment]
@trevorwang could please update your version or yarn and see if there are still problems?

**Comment by trevorwang** [comment]
@voxsim 
I have already updated to the latest 0.23.4 by `brew`. The same issue exists.
```
➜  ~ yarn --version
0.23.4
➜  ~ yarn global bin
/usr/local/Cellar/node/7.10.0/bin
➜  ~ yarn global add bower
yarn global v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "bower@1.8.0" with binaries:
      - bower
warning No license field
✨  Done in 9.42s.
➜  ~ ls /usr/local/Cellar/node/7.10.0/bin/bower
ls: /usr/local/Cellar/node/7.10.0/bin/bower: No such file or directory
➜  ~ yarn global add bower --prefix ~/.local
yarn global v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "bower@1.8.0" with binaries:
      - bower
warning No license field
✨  Done in 9.08s.
➜  ~ ls ~/.local/bin/bower
ls: /Users/trevor/.local/bin/bower: No such file or directory
```

**Comment by georgeedwards** [comment]
I am seeing the exact same issue on Windows, yarn v23.4 - previously working but updates with the `.msi`
node version 6.10.3

**Comment by qinly** [comment]
Note: your profile may be in your .profile, .bash_profile, .bashrc, .zshrc, etc.

1. Add this to your profile: 
```
export PATH="$YARN_BUG:$NGINX:$PATH:$HOME/.config/yarn/global/node_modules/.bin"
```
2. In the terminal, log in and log out for the changes to take effect

**Comment by trevorwang** [comment]
@qinly Thanks. It works for me.

But it really strange that `yarn global bin` equals `/usr/local/Cellar/node/7.10.0/bin` instead of `$HOME/.config/yarn/global/node_modules/.bin`

**Comment by Daniel15** [comment]
That is probably similar to a bug we had on Windows where Yarn tries to
install executables for global packages into the Node.js directory (which
most users won't have write access to without superuser permissions)
 rather than the proper Yarn bin directory.

**Comment by BYK** [comment]
This should be fixed in recent releases so closing.
