### ISSUE TITLE
Corrupted node_modules/.bin/gulp.cmd after `yarn install`

### ISSUE THREAD

**Issue by farrago** [yarnpkg/yarn#3350]
**What is the current behavior?**

`yarn install` with https://github.com/zurb/foundation-emails-template ends up with garbage characters in `node_modules/.bin/gulp.cmd`.

This appears to be exactly as described in #828.
#828 was *closed fixed* based on [PR2795](https://github.com/yarnpkg/yarn/pull/2795), but in the comments on that PR you can find a number of comments that this does not entirely fix the problem.  In that thread of comments [PR3097](https://github.com/yarnpkg/yarn/pull/3097) is proposed as a solution but hasn't been merged yet.

**If the current behavior is a bug, please provide the steps to reproduce.**
See #828 or
1. Clone https://github.com/zurb/foundation-emails-template
2. `yarn install`
3. `gulp` <-- fails

View `node_modules/.bin/gulp.cmd` and see corruption as described in #828 

**What is the expected behavior?**
It should not corrupt gulp.cmd

**Please mention your node.js, yarn and operating system version.**
* node.js: v4.8.1
* yarn: 0.23.4
* OS: Windows 10

**Comment by Bosek** [comment]
Same here with (https://github.com/Bosek/gametracker)[https://github.com/Bosek/gametracker/tree/9746e95d182e070c87db139686c0518a2c56e3e5]

![image](https://user-images.githubusercontent.com/6001235/27387470-1c269d10-5699-11e7-8d2e-779abcb96534.png)

**Comment by OwnerOfThisIsle** [comment]
Same here with yarn 0.24.6.
After freshly installing **karma** the binary karma.cmd ends with garbage characters.
Not every time, but roughly every forth time, my CI is really unstable that way..


OS: Windows 7

**Comment by BrianVallelunga** [comment]
We're also seeing this behavior on AppVeyor with build 0.24.6 and it is extremely annoying. Is there a temporary workaround that anyone has found?

**Comment by stogle** [comment]
The simplest workaround is to `npm install` the corrupted package.

**Comment by farrago** [comment]
To be honest, since NPM 5 introduced package-lock.json, my "workaround" has just been to move back to npm completely.  It is still slightly slower, but now has broadly equivalent capabilities and most importantly it consistently works.

**Comment by BYK** [comment]
This was fixed in a recent version of Yarn so closing.

**Comment by BYK** [comment]
Also, @farrago, that is not really a useful comment for this issue. I'm happy that you are happy with NPM 5 since it has gotten much better but these kinds of comments neither help NPM nor helps us resolving the issue.

**Comment by farrago** [comment]
Hi @BYK, glad it's fixed and look forward to testing it.

My comment was simply aimed at helping @BrianVallelunga who specifically asked for a workaround (to the issue that I had opened).  If someone had provided a workaround within Yarn then I obviously wouldn't have commented regarding using npm.  Sadly, I don't believe there was a workaround within yarn at the time.

For the future, do you have a code of conduct or similar which includes what is or isn't recommended for including in comments on this project?  I know OS maintenance is a thankless task, so I'm thankful for all the effort people put into it, and I'm happy to only add comments in a way that the team feels is helpful.

**Comment by BrianVallelunga** [comment]
Well, I'm happy it is closed. What release is this fixed in?
