### ISSUE TITLE
Detect outdated yarn.lock before commit

### ISSUE THREAD

**Issue by geuis** [yarnpkg/yarn#3352]
**Do you want to request a *feature* or report a *bug*?**
Prevent commits when yarn.lock differs from package.json

**What is the current behavior?**
yarn.lock state is entirely dependent on a user to `yarn install` after changing `package.json`.

Our team switched to using yarn a couple of weeks ago. One issue that persistently reoccurs is when someone changes `package.json`, does `yarn install` and has a working local build but, for some reasons we haven't tracked down yet, `yarn.lock` is then outdated and subsequent builds will fail for other users. This then requires another commit of running `yarn install` and committing the changed yarn.lock.

It would be fantastic if their was a mechanism to prevent this.

**Comment by patrick-mcdougle** [comment]
There is, when adding dependencies run `yarn add <package-name>` and don't update the package.json file manually.

**Comment by mysterycommand** [comment]
This sounds related to https://github.com/yarnpkg/yarn/issues/3363 … I am experiencing this too, `yarn add package-name` updates `package.json` and `yarn.lock`, but then `rm -rf node_modules/ && yarn install` (or when a co-working runs `yarn install` on a fresh clone) updates the `yarn.lock` again/differently.

**Comment by bestander** [comment]
`--frozen-lockfile` argument will notify if yarn.lock is outdated
