### ISSUE TITLE
Bad hash error when running 'yarn install' using private nexus registry

### ISSUE THREAD

**Issue by syntactic-salt** [yarnpkg/yarn#3354]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
I have the registry set to a private registry in my .npmrc file. When running 'yarn install' yarn throws the following error:
```
verbose 128.287 Error: http://{domain}/content/groups/npm-all/eslint-loader/-/eslint-loader-1.6.1.tgz: Bad hash. Expected "96c47c812772eeb077e3a81681818e671a2cabf5" but got "8378944c943e0e476314c087d44389739cd1d78d"
    at MessageError (C:\Program Files (x86)\Yarn\lib\errors.js:8:5)
    at SecurityError (C:\Program Files (x86)\Yarn\lib\errors.js:15:1)
    at Extract.extractorStream.pipe.on.on (C:\Program Files (x86)\Yarn\lib\fetchers\tarball-fetcher.js:144:16)
    at emitNone (events.js:91:20)
    at Extract.emit (events.js:185:7)
    at finishMaybe (C:\Program Files (x86)\Yarn\node_modules\readable-stream\lib\_stream_writable.js:504:14)
    at afterWrite (C:\Program Files (x86)\Yarn\node_modules\readable-stream\lib\_stream_writable.js:386:3)
    at onwrite (C:\Program Files (x86)\Yarn\node_modules\readable-stream\lib\_stream_writable.js:377:7)
    at WritableState.onwrite (C:\Program Files (x86)\Yarn\node_modules\readable-stream\lib\_stream_writable.js:119:5)
    at Extract._continue (C:\Program Files (x86)\Yarn\node_modules\tar-stream\extract.js:208:8)
error http://{domain}/content/groups/npm-all/eslint-loader/-/eslint-loader-1.6.1.tgz: Bad hash. Expected "96c47c812772eeb077e3a81681818e671a2cabf5" but got "8378944c943e0e476314c087d44389739cd1d78d"
```
If I remove the registry config and remove the packages from that registry from my package.json, yarn installs the public packages successfully.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set the registry to a private nexus registry in .npmrc
2. Run 'yarn install'

**What is the expected behavior?**
With the registry set in .npmrc NPM behaves properly and installs all the packages, public packages as well as the ones hosted on the private registry. I expect yarn to do the same.

**Please mention your node.js, yarn and operating system version.**
node version: 6.9.5
yarn version: 0.23.4
os: windows 7

**Comment by syntactic-salt** [comment]
Some additional information on this issue. If I remove all the public packages from my package.json and leave the packages from the private registry, I still get a bad hash error.

Does yarn work with private registries?

**Comment by bestander** [comment]
Does regenerating yarn.lock help?

**Comment by syntactic-salt** [comment]
@bestander I'm unable to generate a yarn.lock file because 'yarn install' fails with a bad hash error. This is an existing project that I'm trying to integrate yarn into, so I already have a package.json full of dependencies.

**Comment by bestander** [comment]
Can you share package.json?
Is it failing only when using private registry?

Could it be that the nexus registry is returning a changed tarball vs npm?

**Comment by syntactic-salt** [comment]
@bestander here's my package.json
```json
{
  "name": "hmm12-learner",
  "version": "1.10.0",
  "scripts": {
    "build": "bower install && webpack -p --progress",
    "dep-check": "npm run ncu && npm run ncu -- -m bower",
    "dev": "webpack --watch",
    "ncu": "ncu",
    "test": "karma start"
  },
  "devDependencies": {
    "babel-core": "6.22.1",
    "babel-loader": "6.2.10",
    "babel-plugin-add-module-exports": "0.2.1",
    "babel-preset-es2015": "6.22.0",
    "bower": "1.8.0",
    "clean-webpack-plugin": "0.1.15",
    "css-loader": "0.26.1",
    "eslint": "3.15.0",
    "eslint-config-corporate-learning": "1.0.1",
    "eslint-loader": "1.6.1",
    "exports-loader": "0.6.3",
    "extract-text-webpack-plugin": "2.0.0-rc.3",
    "file-loader": "0.10.0",
    "html-webpack-plugin": "2.28.0",
    "imports-loader": "0.7.0",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "2.5.2",
    "karma": "1.4.1",
    "karma-coverage": "1.1.1",
    "karma-coverage-istanbul-reporter": "0.2.2",
    "karma-jasmine": "1.1.0",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.2",
    "less": "2.7.2",
    "less-loader": "2.2.3",
    "ng-annotate-loader": "0.2.0",
    "npm-check-updates": "2.10.0",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "2.2.1"
  }
}
```

What's the best way to test if the tarball is modified?

**Comment by syntactic-salt** [comment]
And yes, this only fails when using the private registry. If I use the default npm registry and remove my internal dependencies from the manifest, 'yarn install' is successful.

**Comment by bestander** [comment]
The registry returns sha1 for each dependency and a link to download the .tgz file.

Try running `yarn install --verbose` to see the links it downloads.
Then download open the link eslint-loader metadata, e.g. `verbose 0.667 Request "https://registry.yarnpkg.com/left-pad" finished with status code 200.`
Download the .tgz file `eslint-loader-1.6.1.tgz` and check if shasum matches the actual file.

**Comment by syntactic-salt** [comment]
I just did some testing and it looks like a problem with the registry or a bug with nexus. The tgz I'm getting through nexus isn't even compressed like the one the one you get from npm. Which is weird because nexus  is supposed to just proxy to the npm registry. Even weirder is that nexus seems to just be misrepresenting the file. The hash of the .tar I extract from the npm tgz has the same hash as the tgz that nexus returns.

I'll have to take this up with nexus. If anyone has any ideas though, I welcome them.

@bestander thanks for the help.

**Comment by syntactic-salt** [comment]
@bestander do you know if there is an option to disable the hash check while I work through this issue?

**Comment by bestander** [comment]
No, only in the code in tarball-fetcher.js

**Comment by syntactic-salt** [comment]
I've confirmed this issue is due to bad files being served up by my nexus repository. Closing this issue.

**Comment by balanceiskey** [comment]
@syntactic-salt any chance you're using the [Offline Mirror](https://yarnpkg.com/blog/2016/11/24/offline-mirror/) functionality with `yarn`?
