### ISSUE TITLE
How to install and use optipng node module

### ISSUE THREAD

**Issue by FDiskas** [yarnpkg/yarn#3370]
**Do you want to request a *feature* or report a *bug*?**
*BUG*

**What is the current behavior?**
Missing executable file
```ssh
sh: optipng: command not found
error Command failed with exit code 127.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `yarn init -y`
1. `yarn add optipng`
1. add script to *package.json* `"scripts": { "test": "optipng img/*" },`
1. `yarn run test`
**What is the expected behavior?**
yarn should not ignore https://docs.npmjs.com/files/package.json#bin

**Please mention your node.js, yarn and operating system version.**
```
node: v6.9.2
yarn: v0.23.4
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
```

**Comment by FDiskas** [comment]
Used as alternative `optipng-bin` for now

**Comment by BYK** [comment]
No longer an issue.

**Comment by FDiskas** [comment]
Thanks :+1:
