### ISSUE TITLE
--dev/-D flag ignored if package is already listed under dependencies

### ISSUE THREAD

**Issue by calvinhuang** [yarnpkg/yarn#3376]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a package has already been added as a dependency, running `yarn add <pkg> -D` does not add it to `devDependencies`. The `-D` switch is ignored with no indication to the user that it's still only listed as a regular dependency.

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
yarn add <pkg>
cat package.json | less
yarn add <pkg> -D
cat package.json | less
```

**What is the expected behavior?**
I would expect the package to be either listed only under `devDependencies` or in both `dependencies` and `devDependencies`.

**Please mention your node.js, yarn and operating system version.**
node v7.7.4
yarn 0.23.4
OS X 10.11.6

**Comment by bestander** [comment]
Not sure which is better.
I think Yarn should definitely warn that this dep is already present.

**Comment by calvinhuang** [comment]
Yea, I'm not sure if there's actually any use case for it being in both. A warning would certainly be nice and avoid any confusion that might be caused by the current behavior.

**Comment by davidmason** [comment]
What is the workaround here? Is it fine just to cut and paste the deps in `package.json` or would that put it out of sync with `yarn.lock`? If the latter, I guess `yarn remove <pkg> && yarn add -D <pkg>` would be the way to go.

**Comment by davidmason** [comment]
If I `yarn remove <pkg> && yarn add -D <pkg>` there is no change in `yarn.lock`, so it looks safe to just move dependencies by hand in `package.json` (if you have a steady hand :ok_hand:

**Comment by bestander** [comment]
Yeah, it is safe to modify package,Jason manually

**Comment by BYK** [comment]
This is a very confusing and potentially dangerous usability issue so marking as high-priority. Contributions welcome.
