### ISSUE TITLE
Feature Request - mutex option with cache clean

### ISSUE THREAD

**Issue by jamesongithub** [yarnpkg/yarn#3381]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
yarn clean act independently of yarn install

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
We clean our yarn cache often on our build servers. These happen at the same as our yarn installs. Sometimes we get strange errors, like missing files during builds. Would be nice if these worked together.

**Please mention your node.js, yarn and operating system version.**
```
yarn --version
0.21.3
node --version
v6.9.2
cat /proc/version
Linux version 3.13.0-96-generic (buildd@lcy01-09) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016
```

**Comment by bestander** [comment]
I like the idea!
Want to send a PR?

**Comment by olingern** [comment]
@bestander I'd like to jump back in and tackle this and #1845.

**Comment by bestander** [comment]
Thanks, @olingern, please do!

**Comment by olingern** [comment]
Looking over `install.js`'s `init` function, I could add a flag to disable cleaning.

Something like `yarn clean && yarn install --noClean` seems like it takes care of this use case.

Thoughts @bestander @jamesongithub ?

**Comment by bestander** [comment]
I think the clean in install is different, that one cleans node_modules from files like README and tests.

This is more like calling `cache clean` command at the start of install, before resolution maybe.

After thinking about it I think you can solve this for your CI needs another way.
Just provide a unique (temp) folder for caches via `--cache-folder` argument.
Then caches won't be interfering with each other.

**Comment by jamesongithub** [comment]
so we already have multiple cache folders on our build servers (one / build slot). this issue is how do clean these while installs are running and using the cache?

**Comment by bestander** [comment]
Do you want to clean cache after the install to save disk space for eample?

**Comment by jamesongithub** [comment]
we moved to multiple cache folders since running concurrent yarns with mutex was causing waiting times from 20-30 minutes

**Comment by jamesongithub** [comment]
yeah. after some time, builds servers will run out of space. since we're using 16 cache dirs. it fills up fast.

**Comment by jamesongithub** [comment]
what would be nice is per package installs and have those shared across yarn installs. you could lock individually on those instead. then we wouldn't have to have multiple cache dirs. space would also be less of an issue.

**Comment by bestander** [comment]
Yeah, it would be great to make Yarn resilient to concurrent installs and lock individual cache folders.
Then the problem would be solved for many.
That could be a bit complex but you could build something on top of the current locking solution we use in install

**Comment by jamesongithub** [comment]
when you say "individual cache folders" you mean "individual modules"?

**Comment by jamesongithub** [comment]
"individual module locking / shared modules across installs" would solve most of these problems i think

**Comment by bestander** [comment]
I mean if a process wants to build a download a package `leftpad@0.0.1` it could lock the folder at
`/Users/bestander/Library/Caches/Yarn/v1/npm-leftpad-0.0.1-86b1a4de4face180ac545a83f1503523d8fed115` when it explodes the .tgz file in there.
Then no other Yarn process can read from or write to this folder until the first one finishes.

Our `--mutex` feature is built on top of a basic socket server https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L219, it should not be too hard to make the master/children to communicate on what folder is getting locked.

**Comment by jamesongithub** [comment]
i see, so back to the original issue. it seem it's still would happen with package locking. just would happen less, since one would presumably clean less.

**Comment by bestander** [comment]
Yes, I assume that then you don't need cleanup because cache can be reused.

Still there might be a valid use case when we want to automatically call
clean after install.
Maybe a setting 'clean-after' and invoke cache clean at the end of install?

**Comment by jamesongithub** [comment]
running them serially doesn't seem it will be a problem. id say clean and install should be mutex aware, just lower priority than package/folder locking if that will happen

**Comment by BYK** [comment]
Although this is a good suggestion, I think a more generic approach is not using the cache at all: https://github.com/yarnpkg/rfcs/pull/53

I'm closing this in favor of the mentioned RFC to consolidate efforts. Feel free to keep the discussion open if you think this approach provides more value than the RFC alone.
