### ISSUE TITLE
[Windows] New lines are created for progressive update after Creators Update

### ISSUE THREAD

**Issue by gluons** [yarnpkg/yarn#3383]
I face zeit/hyper#1732 but I also see it on Windows **PowerShell** and **CMD**. It maybe Yarn issue?

---

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** New lines are created for progressive update

- **On PowerShell:**

  <img width="793" alt="1" src="https://cloud.githubusercontent.com/assets/4688092/25980299/d3c6bc14-36f7-11e7-811c-8e9918b05097.PNG">

  <img width="780" alt="2" src="https://cloud.githubusercontent.com/assets/4688092/25980301/d81fd836-36f7-11e7-8d71-28449231fc4f.PNG">

- **On CMD:**

  <img width="828" alt="3" src="https://cloud.githubusercontent.com/assets/4688092/25980342/1554bbcc-36f8-11e7-8780-2a6af9b7043b.PNG">

  <img width="826" alt="4" src="https://cloud.githubusercontent.com/assets/4688092/25980352/26d051f4-36f8-11e7-9900-3168a342f9f8.PNG">

**If the current behavior is a bug, please provide the steps to reproduce.**

- Use Yarn on Windows with Creator Update.

**What is the expected behavior?** Proper progress bar.

**Please mention your node.js, yarn and operating system version.**
- **Node:** v6.10.3
- **Yarn:** v0.23.4
- **OS:** Windows 10 Pro 64bits - Creators Update version 1703 build 15063.0

**Comment by bestander** [comment]
There is a duplicate somewhere

**Comment by gluons** [comment]
@bestander I've tried to search it before. I can't find it. 😅

You can close if you found duplicate. (And please tell me, I'll subscribe.)

**Comment by bestander** [comment]
https://github.com/yarnpkg/yarn/issues/2530
