### ISSUE TITLE
Yarn suggests using deprecated verb `install` on calling `yarn i`

### ISSUE THREAD

**Issue by skfd** [yarnpkg/yarn#3398]
### Steps
1. Run `yarn i example`.
2. Follow the suggestion and run `yarn install example`.
### Expected
Yarn would infer that we're trying to call `install` and remind that we should use `add`.

### Actual
Yarn bamboozles us by suggesting to use deprecated `yarn install`:
`error Did you mean 'yarn install'?`

### Versions
yarn: `0.24.4`
node: `v6.9.1`

**Comment by rally25rs** [comment]
`install` isn't really deprecated. `yarn install` is still a valid command to install the dependencies in `package.json`.

Really it just isn't smart enough to count the number of parameters and realize install with a package name after it should recommend `add` instead of `install`.

But `yarn i` should still recommend `yarn install`.

**Comment by skfd** [comment]
It fails installation with error, so it's pretty deprecated.

    $ yarn install example
    error `install` has been replaced with `add` to add new dependencies.
    Run "yarn add example" instead.

I think for `yarn i example` it should write the combination of two errors:
> error Did you mean `yarn install`? `install` has been replaced with `add` to add new dependencies.

**Comment by bestander** [comment]
Looks quite straightforward to me.
```
bestander-mbp:efer bestander$ yarn i leftpad
yarn i v0.24.3
error Did you mean `yarn install`?
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

bestander-mbp:efer bestander$ yarn install leftpad
yarn install v0.24.3
error `install` has been replaced with `add` to add new dependencies. Run "yarn add leftpad" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by bestander** [comment]
If you send a PR that would address `i + <package>` case in one error message, that would be great.
I'll close the issue.

**Comment by cozzbie** [comment]
So how do I install items from package.json since `yarn install` is deprecated and `yard add` needs flags?
