### ISSUE TITLE
tar jxvf instead of tar -jxvf wtf???

### ISSUE THREAD

**Issue by maxcr** [yarnpkg/yarn#3400]
```
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2              
```

Notice the lack of dash for indicating flag. Is this a yarn problem, or a phantomjs-prebuilt problem?

**Comment by Daniel15** [comment]
> Notice the lack of dash for indicating flag.

Dashes are optional for `tar`.

This looks like a bug in phantomjs - This error seems to be coming from Phantom rather than from Yarn. Please feel free to reopen this issue if you can confirm that it's a Yarn bug.
