### ISSUE TITLE
yarn does not handle case-only filename change on case insensitive OS

### ISSUE THREAD

**Issue by damonmaria** [yarnpkg/yarn#3404]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

1. Publish a package (I used npm to publish)
2. `yarn add` the package to a project
2. Rename a file in the package **only changing the case of the filename**
3. Publish again (using npm again)
4. `yarn upgrade` the package in the project
5. The renamed file will be missing from the installed package in `node_modules`

**If the current behavior is a bug, please provide the steps to reproduce.**
As above.

**What is the expected behavior?**
The files should not be missing.

**Please mention your node.js, yarn and operating system version.**
```
$ node --version
v7.10.0
$ yarn --version
0.24.4
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
```

**Comment by BYK** [comment]
This is fixed around 1.0.0 so closing.
