### ISSUE TITLE
yarn SyntaxError

### ISSUE THREAD

**Issue by Bamieh** [yarnpkg/yarn#3405]
im trying to run a pm2 node server through yarn by running the command `pm2 start yarn -- start`. this command works completely fine when replacing `yarn` with `npm`

after lookig at the log file,  it seems that its a yarn bug

```
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

yarn version: 0.24.4

**Comment by Daniel15** [comment]
It looks like it's trying to execute `yarn`'s shell script as a JavaScript file 😛  That won't work.

Try `pm2 start yarn.js -- start` instead and see if that works?

**Comment by Bamieh** [comment]
you are right :D it worked.

**Comment by 7rulnik** [comment]
@DanBuild but for me it works

**Comment by leodutra** [comment]
Yarn still does not work inside pm2 ecosystem... even with `.js`
```js
{
       name: 'getfit',
       script: 'yarn.js',
       args: 'run routine-x',
// ...
```
This is totally fine with npm

**Comment by Joey-Wong** [comment]
Try `pm2 start "yarn start"` instead and see if that works?

**Comment by RaphaelHGarcia** [comment]
`module.exports = {
  apps: [
    {
      name: 'your-app',
      cwd: './path/your-app',
      script: 'yarn',
      args: 'start',
      interpreter: '/bin/bash'
    }
  ]
}
`

**Comment by gox-ai** [comment]
@Joey-Wong running as `pm2 start "yarn start"` works, but only in fork mode and not as cluster.

**Comment by samuelterra22** [comment]
Thanks @gox-ai , this is the only possible explanation. I looked for a solution to this problem, and in my case it was no longer using cluster mode.

**Comment by zeeshanaligold** [comment]
Try

**Comment by zeeshanaligold** [comment]
Try with "yarn start"

```
module.exports = {
  apps: [
    {
      name: 'your-app',
      script: 'yarn start',
    }
  ]
}
```

**Comment by har2008preet** [comment]
This solved my issue: https://stackoverflow.com/a/51902772/3001746
