### ISSUE TITLE
Use yargs npm project for the command line

### ISSUE THREAD

**Issue by voxsim** [yarnpkg/yarn#3408]
I took some time to study some cli npm packages. We did many hacks and tricks to adopt commander.js and I think we should move to yargs (https://github.com/yargs/yargs). It seems promising and it is quite active.

Pro:
- It has support for sub commands
- We can have one file for each command or sub-command
- it has support for alias

Cons:
- It has not native support `yarn help`, but it has native support for `yarn --help/-h`
- For some command we still can't force some flags (like we do for the global commands), but maybe we can resolved this with https://github.com/yargs/yargs#coerce.

Do someone see any other reasons why we should not move to this? Please let me know :)

**Comment by kittens** [comment]
The cons you've described are pretty significant. We've already got support for all the pros you listed so there's zero benefits to switching.

**Comment by voxsim** [comment]
Hey @kittens ! Yep you are right, but we do a lot of custom choices, we just use commander.js just for the options/flags part. Adopting yargs would mean reducing a lot the codebase and the number of hacks in yarn.

**Comment by bestander** [comment]
@voxsim, feel free to give it a try and check if the code becomes more readable.
Would be great if there is a way around the CONS

**Comment by dhruvdutt** [comment]
@voxsim Any updates?

**Comment by paul-soporan** [comment]
Hello from the future, we're using https://github.com/arcanis/clipanion in Yarn 2+ and we're very satisfied with it.

https://yarnpkg.com/getting-started/migration
