### ISSUE TITLE
Add/install confusion for global install

### ISSUE THREAD

**Issue by mcfedr** [yarnpkg/yarn#3419]
**What is the current behavior?**

    $ yarn -g add nodemon
    yarn install v0.24.5
    error `install` has been replaced with `add` to add new dependencies. Run "yarn global add add nodemon" instead.
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**What is the expected behavior?**

Yarn installs `nodemon` globally

**Please mention your node.js, yarn and operating system version.**

* yarn 0.24.5 (via brew)
* macos 10.12.4
* node 7.10.0 (via brew)

**Comment by rally25rs** [comment]
The only bug I see here is that the message duplicates the word "add":

> Run "yarn global add add nodemon" instead.

Otherwise, the output message explains that "install -g" is not a Yarn command and points you to the documentation.

You should run `yarn global add nodemon` instead. This is the Yarn equivalent of `npm install -g nodemon`

**Comment by mcfedr** [comment]
There are two bugs:

1. Duplicate word "add"
2. The command I ran is `add` - Its telling me not to use `install` when I ran `add`.
    Maybe yarn doesnt support using `-g` for global, in which case that should be the error.

**Comment by bestander** [comment]
I think the error message is quite explicit, there is a package add https://yarnpkg.com/en/package/add so it might be a user's intention

Feel free to send a PR to improve.
