### ISSUE TITLE
frozen-lockfile does not fail when lockfile is autocorrected because of incorrect entries

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#3420]
Since #3106, yarn autocorrect the lockfile in some cases.

I was expecting that using `--frozen-lockfile` would fail in that case, since it means modifying the lockfile.

I suppose that check should fail too, as well as `--pure-lockfile`…

**Comment by victornoel** [comment]
By the way, there is a typo (ignoring) in the warning message:
```
warning Lockfile has incorrect entry for "typescript@>=2.0.0 <2.3.0". Ingoring it.
```

**Comment by bestander** [comment]
duplicate https://github.com/yarnpkg/yarn/issues/3313
