### ISSUE TITLE
[BUG, REPORT] Yarn does not download the newest node_module

### ISSUE THREAD

**Issue by ChrisShen93** [yarnpkg/yarn#3428]
I was using yarn install my dependencies from npm.org and a private gitlab

Once there was a bug in the private module called A from the private gitlab. After I fixed it and I run 
'yarn' again to install the newest one.
Unfortunately, I still get the old one.

I have tried 'yarn cache clean' and then 'yarn', but still get the previous release.

nodejs: 6.10.2
npm: 3.10.10
yarn: 0.25.2
OS: windows 10 pro

**Comment by bestander** [comment]
Sorry, with this description I can't reproduce the issue.
Maybe you need to remove yarn.lock as well.
