### ISSUE TITLE
yarn install for git dependency does not 'pack'

### ISSUE THREAD

**Issue by bengeorge** [yarnpkg/yarn#3429]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce.**
```
  "dependencies": {
    "foo": "git+https://foo.git#1.0.0"
  }
```

`yarn install`

Results in entire contents of the foo repo in the `node_modules/foo` folder.   I should note the same occurs when refering to a file location eg: a dependency of `"foo": "../foo"`

**What is the expected behavior?**
Should behave like npm.  The `node_modules/foo` should only contain the files that would be contained if you did a `$/dev/foo>yarn pack` (ie: obey the .gitignore, .npmignore rules etc. etc.).

**Please mention your node.js, yarn and operating system version.**
windows 7 + yarn 0.24.4 + v6.10.0

**Comment by bestander** [comment]
knit is an RFC that addresses a similar problem https://github.com/yarnpkg/rfcs/pull/41.
Currently Yarn does not have a feature that it would pack a folder before installing it automatically.
Sounds like a good opportunity to send an RFC, I'll close the issue as there is no action I can make right now.
