### ISSUE TITLE
yarn install incompatible module

### ISSUE THREAD

**Issue by jmjpro** [yarnpkg/yarn#3430]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I receive the following error when running `yarn install`. I also tried running `yarn install --verbose` but it didn't shed any light on the problem. _npm install works fine._
```
error xmlbuilder@9.0.0: The engine "node" is incompatible with this module. Expected version ">=6.0".
error Found incompatible module
```
From package.json:

```
"dependencies": {
		"restangular": "~1.3.1",
		"jquery": "~2.1.4",
		"d3": "~3.4.6",
		"moment": "~2.10.0",
		"bootstrap": "~3.1.1",
		"angular": "1.4.7",
		"angular-bootstrap-npm": "0.14.3",
		"angular-animate": "1.4.7",
		"angular-ui-router": "~0.2.9",
		"nx-popover": "~0.6.12",
		"elasticsearch": "~8.2.0",
		"elasticsearch-watcher": "~1.0.1",
		"angular-schema-form": "~0.8.12",
		"lodash": "2.4.2",
		"angular-sanitize": "1.3.20",
		"angular-ui-mask": "*",
		"ui-select": "*",
		"angular-moment": "*",
		"bootstrap-ui-datetime-picker": "2.5.4",
		"signature_pad": "*",
		"node-paginate-anything": "1.0.0",
		"angular-ui-sortable": "0.13.4",
		"ng-dialog": "*",
		"angular-svg-pan-zoom": "*",
		"grunt-aws": "0.6.0",
		"grunt-invalidate-cloudfront": "^0.1.5"
	},
	"devDependencies": {
		"karma": "1",
		"grunt": "~0.4.1",
		"grunt-contrib-clean": "~0.4.1",
		"grunt-contrib-less": "~0.11.0",
		"grunt-contrib-copy": "~0.4.1",
		"grunt-contrib-jshint": "~0.4.3",
		"grunt-contrib-concat": "~0.3.0",
		"grunt-contrib-watch": "~0.4.0",
		"grunt-contrib-uglify": "~0.2.0",
		"grunt-ngmin": "0.0.2",
		"grunt-protractor-runner": "^2.1.2",
		"protractor-jasmine2-html-reporter": "0.0.6",
		"grunt-html2js": "~0.1.3",
		"grunt-contrib-coffee": "~0.7.0",
		"grunt-coffeelint": "0.0.6",
		"grunt-conventional-changelog": "~0.1.1",
		"grunt-bump": "0.0.6"
	},
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
No incompatible module error and installation of xmlbuilder v8.2.2

**Please mention your node.js, yarn and operating system version.**
Node v4.8.3, yarn v0.24.4, mac os x 10.12.4 sierra

**Comment by jmjpro** [comment]
After further investigation I removed "grunt-protractor-runner": "^2.1.2" and "protractor-jasmine2-html-reporter": "0.0.6" from my devDependencies. There is still a difference in behavior between yarn and npm that should be understood.

**Comment by rally25rs** [comment]
That is interesting...

xmlbuilder@9.0.0 specifies in it's package.json that it requires Node >= 6
https://github.com/oozcitak/xmlbuilder-js/blob/v9.0.0/package.json

You are using Node v4, so this does seem like a reasonable error (xmlbuilder is not compatible with your version of Node).

I wonder if NPM doesn't actually check the node version for transient dependencies?

**Comment by rally25rs** [comment]
It seems NPM stopped bothering to error on `engines` violations in v3:

Quote from: https://github.com/npm/npm/releases/tag/v3.0.0

_(emphasis mine)_

> The rarely-used package.json option engineStrict has been deprecated for several months, producing warnings when it was used. Starting with npm@3, the value of the field is ignored, and **engine violations will only produce warnings**. If you, as a user, want strict engines field enforcement, just run npm config set engine-strict true.

Real nice 😕

**Comment by klouskingsley** [comment]
try `yarn --ignore-engines`

**Comment by bestander** [comment]
If anyone wants `--ignore-engines` to be default in Yarn as well then open an RFC

**Comment by gsklee** [comment]
@bestander Looks like it's by design: https://github.com/yarnpkg/rfcs/pull/69

**Comment by arled** [comment]
What's all this above lol all you have to is upgrade node!! **Done deal.**
`sudo n stable` upgrade to lastest version.
and please do not and I repeat DO NOT use `--ignore-engines` you're better than that

**Comment by arled** [comment]
> try `yarn --ignore-engines`

NO!

**Comment by Safarali** [comment]
> sudo n stable

sudo n stable gives error ```sudo: n: command not found ```

**Comment by IlkhamGaysin** [comment]
@Safarali you need to install that package `sudo npm install -g n`

**Comment by odykyi** [comment]
> yarn --ignore-engines

**Comment by martijnimhoff** [comment]
:thinking: 
![image](https://user-images.githubusercontent.com/5647089/60723057-ea530000-9f32-11e9-9a89-99a48c9265d6.png)

**Comment by MrCoder** [comment]
> If anyone wants `--ignore-engines` to be default in Yarn as well then open an RFC

At least add a help message like 'use `--ignore-engines` to bypass engine check'.
