### ISSUE TITLE
yarn-offline-mirror-pruning also removes .git file

### ISSUE THREAD

**Issue by pmorch** [yarnpkg/yarn#3435]
**Do you want to request a *feature* or report a *bug*?**
An improvement suggestion or a bug. You decide.
This is a minor issue for us, I just thought I'd report it. See workaround below.

**What is the current behavior?**
The current behavior is that yarn-offline-mirror-pruning (apparently) removes every single file in the folder that is not a current tarball.

**If the current behavior is a bug, please provide the steps to reproduce.**
See [Pruning an Offline Mirror | Yarn](https://yarnpkg.com/en/docs/prune-offline-mirror) but create e.g. a `.git` file in the folder first before pruning.

**What is the expected behavior?**
My expectation is that yarn pruning should remove all non-current _tarballs_ (i.e. `*.tgz` files?) that aren't current, but leave my `.git` file alone.

My expectation is fuelled by [Pruning an Offline Mirror | Yarn](https://yarnpkg.com/en/docs/prune-offline-mirror) that describes that:
> However, it does not automatically remove tarballs that are no longer referenced in yarn.lock. For example, if you $ yarn remove a dependency, the tarball will remain in the mirror, even if no other dependencies have it as a sub-dependency. This behavior can be desirable in a setting where many projects share the same mirror, but when that is not the case, you may want to have Yarn remove unnecessary tarballs.

So this isn't life and death. The workaround for us is to put all the tarballs in a `cache/` sub-directory, and let yarn prune there instead. But this extra directory is a little ugly.

Thanks for giving us yarn-offline-mirror-pruning to begin with!

**Please mention your node.js, yarn and operating system version.**
```
> node --version
v7.10.0
> yarn --version
0.23.4
> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie
```

**Comment by pichouk** [comment]
Ping @bestander. I guess this issue was fixed by #3467 and can be closed.

**Comment by bestander** [comment]
thanks

**Comment by pmorch** [comment]
Wonderful! Thanks!
