### ISSUE TITLE
yarn issues warnings when cordova plugins are defined in `package.json`

### ISSUE THREAD

**Issue by fiznool** [yarnpkg/yarn#3437]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The latest version of the cordova CLI (7.0.0) adds cordova plugins to `package.json` when running `cordova plugin add <plugin-name>`. The spec for Cordova plugins [states that you can manage cordova version dependencies using the `engines.cordovaDependencies` property](https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/#specifying-cordova-dependencies). Unfortunately, yarn does not like this non-standard definition property and issues a warning when running `yarn` with the freshly included cordova plugins in `package.json`.

The warning resembles:
```
warning cordova-plugin-camera@2.4.0: The engine "cordovaDependencies" appears to be invalid.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

You don't need to use the Cordova CLI to replicate the bug. The following is enough:

``` bash
mkdir yarn-cordova && cd $_
yarn init -y
yarn add cordova-plugin-camera
```

**What is the expected behavior?**

A warning not to be issued.

**Please mention your node.js, yarn and operating system version.**

- node v6.10.3
- yarn v0.24.4
- macOS Sierra 10.12.4

**Comment by bestander** [comment]
@fiznool I suppose you can send a PR to add cordova to exclusions https://github.com/yarnpkg/yarn/blob/master/src/package-compatibility.js#L48.
A slightly better approach could be to make this field configurable.

**Comment by edwardpayton** [comment]
+1
