### ISSUE TITLE
yarn add human-readable-ids crashes app at runtime.

### ISSUE THREAD

**Issue by arthuranderson3** [yarnpkg/yarn#3443]
## yarn 0.24.4

 `yarn add human-readable-ids`
-- removes the assets and test directories under node_modules/human-readable-ids, which causes the code to crash.

if I install with` npm install human-readable-ids` the package is runnable and does not crash.

Is there a flag I can use or something in the package.json that tells yarn to not remove these other directories? Would like to pass this information along to the human-readable-ids-js folk.
Thanks

**Comment by bestander** [comment]
Did you run `yarn clean` by any chance?
If you have a .yarnclean, remove it and try again.
We are in progress of renaming this command.
