### ISSUE TITLE
Yarn Registry does not return abbreviated response if package name ends with .js

### ISSUE THREAD

**Issue by devoto13** [yarnpkg/yarn#3444]
**Do you want to request a *feature* or report a *bug*?**

Bug

It's about registry, not about the client.
https://registry.yarnpkg.com seems to obey `Accept` header to return abbreviated response as described [here](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md). But not when package name ends with `.js`.

Found it accidentally, while investigating #3441.

**What is the current behavior?**

Returns abbreviated response as expected:

    $ http https://registry.yarnpkg.com/yarn 'Accept:application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*'
    $ http https://registry.yarnpkg.com/left-pad 'Accept:application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*'

Returns full response despite same header being present:

    $ http https://registry.yarnpkg.com/zone.js 'Accept:application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*'
    $ http https://registry.yarnpkg.com/chart.js 'Accept:application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*'

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

Packages with names ending in `.js` should return abbreviated response, when header is present.

**Please mention your node.js, yarn and operating system version.**

Not relevant.

**Comment by rally25rs** [comment]
I seem to just get inconsistent results. I plugged the URL and accept header into Postman and keep requesting it with and without the header, or change URLs a few times then try a `.js` one again...

Sometimes I get the abbreviated response, sometimes I don't.

Making the same requests to `registry.npmjs.org` seemed to always reply correctly though.
Maybe the Yarn proxy is caching previous requests by URL but not taking the header into account?

**Comment by BYK** [comment]
@rally25rs is this still an issue?

**Comment by rally25rs** [comment]
Seems to be working OK now. Let's close this for now. If we see it happen again we can reopen.
