### ISSUE TITLE
Manually selecting a version during `yarn add` edits `package.json` incorrectly

### ISSUE THREAD

**Issue by kumar303** [yarnpkg/yarn#3451]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`yarn add` edits `package.json` incorrectly when you select a manual version of a package

**If the current behavior is a bug, please provide the steps to reproduce.**

* Install a version of a package just like you normally would. Example:
````
yarn add react-redux-loading-bar@2.9.0 --prod
````
I used an exact version here only to make it reproducible. This updates package.json with:
````
"react-redux-loading-bar": "2.9.0",
````

* Next, downgrade to a non-existent version of a package as if you were making a typo. Example:
````
yarn add react-redux-loading-bar@28.2
````

* Yarn will prompt you to select a correct version
* I chose `2.8.2` but Yarn added `28.2` to my `package.json` like:

````
"react-redux-loading-bar": "28.2",
````

**What is the expected behavior?**

Yarn should add `2.8.2` to my `package.json`

**Please mention your node.js, yarn and operating system version.**
````
$ node --version
v6.10.3
$ yarn --version
0.24.5
````
Mac OS X 10.12.4

**Comment by bestander** [comment]
Duplicate https://github.com/yarnpkg/yarn/issues/3214

**Comment by TaekwanMin** [comment]
> Duplicate #3214

it's Triplicate
