### ISSUE TITLE
"yarn clean cache" should show progress bar

### ISSUE THREAD

**Issue by OmgImAlexis** [yarnpkg/yarn#3452]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
```
➜  api git:(master) ✗ yarn cache clean
yarn cache v0.24.5
success Cleared cache.
✨  Done in 77.97s.
```

**What is the expected behavior?**
Either a progress bar to be shown or some kind of indication that the command is still running.

**Other**
The main issue is if your cache is large enough there's no indication at all that anything is still running and that the command hasn't frozen.

**Comment by rally25rs** [comment]
`cache clean` just uses `rimraf` https://www.npmjs.com/package/rimraf to delete the cache directory (equivalent to doing an `rm -rf`) so it doesn't have any way to report actual progress with a status bar.

We can put a "spinner" up during the deletion. This is what is used during the resolving of packages too.

I'll submit a PR in a bit...
