### ISSUE TITLE
Add legend to colors in upgrade-iteractive

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3454]
**Do you want to request a *feature* or report a *bug*?**
improvement

**What is the current behavior?**

![18555248_478165102527699_1583036487_n](https://cloud.githubusercontent.com/assets/2121048/26242026/db755420-3c7e-11e7-87a1-0f65edf57374.png)

Would be nice to explain what read and yellow colors mean

**Comment by mohitgarg** [comment]
I would like to help with this issue.

**Comment by bestander** [comment]
Awesome! Send a PR and cc me

**Comment by mohitgarg** [comment]
I am a beginner in OSS. I understood the issue but can you walk me through the files and point me in the right direction. I would really appreciate it!

**Comment by bestander** [comment]
Sure, are you comfortable making changes to Yarn source code, building it and running any command?
The code for upgrade-interactive is here https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/upgrade-interactive.js

**Comment by clarenced** [comment]
Hi @bestander, can I contribute to this issue?

**Comment by bestander** [comment]
You don't need to ask for a permission:)
Just send a PR

**Comment by clarenced** [comment]
Hi @bestander , do you have any idea what message to display for explaining the legend colors? My correction will put a key in `src/reporters/lang/en.js` to displa the content of the message.

**Comment by bestander** [comment]
I don't have an opinion here :)
Use your best judgement and let's see how it looks

**Comment by clarenced** [comment]
Hi @bestander, here is the PR #3561

**Comment by pichouk** [comment]
Just read this issue and seems it can be closed since PR where merged ;)

**Comment by bestander** [comment]
Thanks for the ping
