### ISSUE TITLE
sha256 for a set of dependencies

### ISSUE THREAD

**Issue by pcj** [yarnpkg/yarn#3457]
I'd like to derive a sha256 hash for a set of yarn dependencies.

Can I take the sha256 of the yarn.lock file itself?  Is it naive to assume the sequence of bytes in the yarn.lock file will be identical across different environments for the same set of deps?

Is there another way to derive this hash?

**Comment by bestander** [comment]
Currently yarn.lock contains sha-1 hashes, we plan to change to sha-512 as npm registry now supports it.
If you need to derive sha256 then download the .tgz files using offline mirror https://yarnpkg.com/blog/2016/11/24/offline-mirror/ and then generate it for all the .tgz files in the folder
