### ISSUE TITLE
yarn create razzle

### ISSUE THREAD

**Issue by jhabdas** [yarnpkg/yarn#3459]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
https://github.com/jaredpalmer/razzle

**Please mention your node.js, yarn and operating system version.**

**Comment by Daniel15** [comment]
Looks like a pull request was sent for this: https://github.com/jaredpalmer/razzle/pull/267

**Comment by jaredpalmer** [comment]
Continued this PR in jaredpalmer/razzle#273
