### ISSUE TITLE
"Bad hash" error when using kpm with tarball cache in Docker

### ISSUE THREAD

**Issue by skevy** [yarnpkg/yarn#346]
Note: I don't know what's causing this, and am in the middle of fixing a critical bug in our code so can't investigate deeper at the moment...will try to later.

I did a typical `kpm i` (on my mac) with a node_module cache that's stored in our monorepo. Saw node_modules get updated, etc. In my Docker image, I am using a docker volume to be able to see my node_module cache inside the image when I do a `kpm i`. Running `kpm i` on my mac works fine, but running `kpm i` inside the image (with the same tarball cache) returns:

```
error Bad hash. Expected 208df8fb8bbc74acb7d3e41568249eba0dab55f7 but got ed74b477a2ee9369f75efee2f08d5915e52a42e8
    at SecurityError (/root/fbkpm/lib/errors.js:17:1)
    at Extract.tar.Extract.on.on (/root/fbkpm/lib/fetchers/tarball-fetcher.js:123:16)
    at emitNone (events.js:91:20)
    at Extract.emit (events.js:185:7)
    at DirWriter.<anonymous> (/root/fbkpm/node_modules/tar/lib/extract.js:82:8)
    at emitNone (events.js:91:20)
    at DirWriter.emit (events.js:185:7)
    at end (/root/fbkpm/node_modules/fstream/lib/writer.js:324:14)
    at /root/fbkpm/node_modules/fstream/lib/writer.js:314:34
    at endUtimes (/root/fbkpm/node_modules/fstream/lib/writer.js:238:46)
```

I'm not sure why a SHA1 hash would be different between OS's, and fwiw this problem just started happening after I updated from 0.12.0 to 0.13.0.

Curious if anyone has thoughts here, or if I'm doing something stupid or missing something obvious.

**Comment by alansouzati** [comment]
I'm still facing this issue with both 0.16.1 and 0.17.2. Any ideas what to do to fix it ?

**Comment by alansouzati** [comment]
My problem was that I had manually copied the yarn.lock with my `COPY` command in docker. I added the `yarn.lock` to my .dockerignore and everything works fine now.

**Comment by SimenB** [comment]
Hitting this now, using 0.17.8.

Why would I not copy over `yarn.lock`, I want to ensure I get the same deps?

**Comment by SimenB** [comment]
Hmm, seems to have been a caching error, blowing away the cache on travis (containing `node_modules`) seems to have fixed it
