### ISSUE TITLE
yarn won't update from 0.24.4 to 0.24.5

### ISSUE THREAD

**Issue by apertureless** [yarnpkg/yarn#3470]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Installing / updating yarn over `npm i -g yarn installs always 0.24.4 

**If the current behavior is a bug, please provide the steps to reproduce.**
- Tried to use `npm-check -u -g` to update my global packages. However yarn does not get listed there. 
- Tried to `npm i -g yarn` but this also installs only 0.24.4
- Tried to uninstall and reinstall yarn, but same here

**What is the expected behavior?**
Install current 0.24.5 version

**Please mention your node.js, yarn and operating system version.**
- `yarn - v0.24.4`
- `node - 7.10.0`
- `MacOS 10.12.4`

**Comment by rally25rs** [comment]
"latest" is still set to 0.24.4:

```
$ npm info yarn

{ name: 'yarn',
  description: '📦🐈 Fast, reliable, and secure dependency management.',
  'dist-tags': { latest: '0.24.4', rc: '0.25.2' },
```

Not sure if this is intentional or just a release oversight...

**Comment by apertureless** [comment]
Ok weird. I've got an info message, that my yarn is outdated and I should update. Seems that the npm package got the wrong dist-tag. However the homebrew version is at `0.25.5`

**Comment by erwinw** [comment]
Same here. Hope this isn't intentional? The (yarn installation page](https://yarnpkg.com/en/docs/install#alternatives-tab) does indicate npm installation isn't recommended, but in order for yarn to play with nvm it's by far the easiest (only?) solution....

**Comment by bestander** [comment]
0.24.5 marked as latest now, thanks

**Comment by apertureless** [comment]
@erwinw yeah thats the reason why I installed it over npm. I am using [n](https://github.com/tj/n) to manage my node versions. But if I install yarn over homebrew, the node dependency also get installed which pollutes the system and I don't need multiple duplicated node versions :D

@bestander thanks! it works now.
