### ISSUE TITLE
Downloads unexpected dependencies

### ISSUE THREAD

**Issue by jhabdas** [yarnpkg/yarn#3473]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`camelcase` included in `node_modules` in addition to `fetch-inject`

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add fetch-inject --production`

**What is the expected behavior?**
only the `fetch-inject` is added

**Please mention your node.js, yarn and operating system version.**
System Version: macOS 10.12.4 (16E195)
yarn -v && node -v
yarn install v0.24.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.05s.
v6.3.1

**Comment by bestander** [comment]
Can't repro
```
yarn add fetch-inject --production
Using Yarn from /Users/bestander/work/yarn/bin/yarn
yarn add v0.26.0-0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ fetch-inject@1.6.12
Done in 0.85s.
bestander-mbp:fetch bestander$ cat package.json
{
  "dependencies": {
    "fetch-inject": "^1.6.12"
  }
}
bestander-mbp:fetch bestander$ cat yarn.lock
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
# yarn v0.26.0-0
# node v6.9.1


fetch-inject@^1.6.12:
  version "1.6.12"
  resolved "https://registry.yarnpkg.com/fetch-inject/-/fetch-inject-1.6.12.tgz#0d821edca143bea17ee266ea110581a70de6f06c"
bestander-mbp:fetch bestander$ ls node_modules/
fetch-inject
```

**Comment by jhabdas** [comment]
NPM package registry shows: `'dist-tags': { latest: '0.24.5', rc: '0.25.2' }`.

**Comment by bestander** [comment]
0.26.0-0 is master branch

**Comment by jhabdas** [comment]
Right, so I wouldn't close this until it's released, yeah?

**Comment by bestander** [comment]
Sorry for being a bit proactive on closing issues right now.
We are in a bug crunch mode and trying to reduce our debt issue-wise.
As I can't reproduce this issue on the latest Yarn I'll just close it now,
otherwise I will just forget to do it later.

Your help to test this on latest master branch is very much appreciated.

**Comment by jhabdas** [comment]
> Sorry for being a bit proactive on closing issues right now.
> We are in a bug crunch mode and trying to reduce our debt issue-wise.

Neither of those reasons justifies you just closed a valid bug in your current release.

> Your help to test this on latest master branch is very much appreciated.

You've already tested it. Why duplicate the effort?

**Comment by jhabdas** [comment]
Okie dokie then. But let me tell explain you cannot go fast until you know what's actually happening. And as it stands what seems to be happening seems to be a sign of a mismanaged release process. Given the nature of this bug that does not make me feel comfortable using your product.

**Comment by bestander** [comment]
Sorry that you have that experience, Josh, I did not intend to make you
feel bad about it.

From my point of view the bug can't be reproduced on the latest master
branch that is soon to be released, so I decided to not spend more time
looking into the issue.
The project belongs to the community and everyone has a chance to step in
and help to manage it better.

**Comment by jhabdas** [comment]
Hence my feedback.

**Comment by rally25rs** [comment]
Kinda late to this already-closed issue, but I can't repro it in 0.24.4 either

```
$ yarn --version
0.24.4

$ yarn add fetch-inject --production
yarn add v0.24.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "0.24.6" while you're on "0.24.4".
success Saved 1 new dependency.
└─ fetch-inject@1.7.2
✨  Done in 0.67s.

$ ls node_modules/
fetch-inject

$ yarn list
yarn list v0.24.4
└─ fetch-inject@1.7.2
✨  Done in 0.11s.
```

I'm not sure where `camelcase` would have even come from, as it isn't even a devDependency of fetch-inject.

**Comment by jhabdas** [comment]
> I'm not sure where `camelcase` would have even come from, as it isn't even a devDependency of fetch-inject.

Exactly. There are no `devDependencies`. Out of intrigue and extreme curiosity, @rally25rs, are you running a Node LTS?

**Comment by jhabdas** [comment]
Please note also I validated using a file system search, and not the `yarn list` command when I saw the unexpected dependency in `0.24.4`. (And thanks for checking.)
