### ISSUE TITLE
MAY 22 - JUNE 1 TRIAGE SESSION

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3474]
Similar to https://github.com/yarnpkg/yarn/issues/3258 we are going to triage Yarn bugs.

We need to add some order to the issues and are going to triage ALL open issues in the project.

Goals:
- Reduce the number of duplicated issues by grouping them by category first
- Close non actionable issues
- Prioritize important issues over the rest

What we are planning to do:
- categorize by issue type (bug, discussion)
- categorize bugs by phase (configuration, resolution, fetching, linking, scripts)
- label high priority issues
- assign highest priority issues and feature request to Yarn 1.0 milestone
- label issues good for beginners
- close issues with no steps to reproduce them. Too many issues, too little time developers can spend on each, with no repro steps the issue will hang there for a long time

Below I'll post a few templates that we can use to keep the tone positive.

We can use this issue for coordination, I'll be moderating it to remove outdated comments.
Also we can coordinate in the chat https://discordapp.com/invite/yarnpkg (does not require registration)

**Comment by bestander** [comment]
Ok, GitHub is not really great at permissions granularity and so this is what we can do this time.

Mention me in a comment and I'll do the trick, e.g.

@bestander label bug, bug-resolution
@bestander duplicate #xxxx

We want to categorize issues by the phase of Yarn installation, increase visibility of high priority issues and increase visibility of good issues for beginners.

Also we want to close duplicates and incentivize the community members to provide steps to reproduce issues.

These are the tags we want to use
<img width="276" alt="screen shot 2017-04-28 at 3 38 09 pm" src="https://cloud.githubusercontent.com/assets/2121048/25533500/b7212bf0-2c28-11e7-97be-6a44bf63a770.png">
<img width="164" alt="screen shot 2017-04-28 at 3 37 22 pm" src="https://cloud.githubusercontent.com/assets/2121048/25533504/b871b5e2-2c28-11e7-8d8d-7f8320295e47.png">

**Comment by gsklee** [comment]
So this might be a little bit different than the proposed methodology; I'm using some keywords and tags to find out issues that can be safely deduced as non-actionable items and thus swiftly closed.

**Non-actionable issues:**

#1170 #1172 #1291 #1301 #1335 #1628 #2675 #2718 #3191

**Comment by gsklee** [comment]
How do you wanna see related issues being categorized? For example, #521 is the original issue about private package support, with a few other highly-related issues here and there (eg. #3433). Do you wanna see these related issues being tagged inside #521, or, would you rather like to see a new overarching parent issue being created with an up-to-date summary, with all related issues big or small added as action items that we can cross out one by one as we try to fix it?

**Comment by bestander** [comment]
@gsklee, huge thanks for helping out.

IMHO the most important is to get `yarn install` (and add/remove/upgrade) working for everyone reliably before we can say Yarn is 1.0 (https://github.com/yarnpkg/yarn/issues/3371).

For that I'd like to categorize the issues by install phase when the issues are taking place:
- configuration (before install starts, something at system level)
- resolving (when Yarn resolves dependency semvers to the exact tarballs that need to be fetched)
- fetching (download and unzip)
- linking (copy from cache folder to node_modules)
- scripts (node-gyp compilations and such)

While parsing through the issues we can close duplicates, redirect feature requests to RFC process, close non issues and prioritize the ones that bloc people.

You can follow this scenario but you are welcome to choose/propose any other tactic that will get us  in control of the issues.

**Comment by bestander** [comment]
Claiming #3424 - #3475

**Comment by bestander** [comment]
To look for issues I filter by open issues that don't have `triaged` tag https://github.com/yarnpkg/yarn/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20-label%3Atriaged%20.

On May 23 we started with 650 untriaged open issues.

**Comment by bestander** [comment]
Claiming #541 - #786

**Comment by bestander** [comment]
claiming #3298 - #3483

**Comment by bestander** [comment]
claiming #792 - #1143

**Comment by gsklee** [comment]
This is a note-to-myself for issues that lack information:

#3036 #3157

**Comment by bestander** [comment]
I'll close this one and start another one this week.
Thanks a lot for everyone who helped
