### ISSUE TITLE
Implement a lifecycle hook which gets called each time node_modules is re-built

### ISSUE THREAD

**Issue by ds300** [yarnpkg/yarn#3475]
## Rationale

Unlike NPM, when you run `yarn`, `yarn add`, or `yarn remove`, yarn will completely replace the node_modules folder. As a tooling author, I would like to know whenever this happens without having a daemon watch the filesystem. In other words, I would like a new lifecycle hook.

My use case is singular: to make [patch-package](https://github.com/ds300/patch-package) hack-free.

patch-package applies user-created patches to packages in node_modules whenever the user runs `yarn`, `yarn add`, or `yarn remove`. The idea is for application authors to be able to rapidly and temporarily fix broken dependencies without forking them, and without waiting for upstream PRs to be merged and published.

However, it currently does this with the npm `prepare` lifecycle hook, which yarn only runs for `yarn` and `yarn add`, and not for `yarn remove`. So patch-package actually patches a project-local `yarn` to make it run the `prepare` hook after a `yarn remove`. This is a nasty nasty hack and I'd love to be able to get rid of it.

## Proposed approaches

1. Just run the 'prepare' lifecycle hook after `yarn remove`.

    In a way, this breaks compatibility with npm, which does not run the hook after `npm uninstall`. However that compatibility is already broken since yarn runs the hook after `yarn add <package>` but npm does not run the hook after `npm install <package>`, only after arg-free `npm install`. 

    However again, it's questionable whether yarn even needs to maintain compatibility in this respect since `yarn add <package>` is only superficially similar to `npm install <package>`. It's more like 

        rm -rf node_modules && [ add <package> to package.json#dependencies ] && npm install

    or something. In that respect yarn doesn't break compatibility with npm, and neither would executing the `prepare` hook after a `yarn remove`.

2. @bestander [recently commented](https://github.com/yarnpkg/yarn/issues/3209) that he'd like to see a more fleshed-out api for hooking into lifecycle events. I have no idea what kind of scope he was thinking of, but would be happy to contribute brainpower and/or code to the problem if people think it's worth pursuing.

**Comment by bestander** [comment]
Thanks for bringing this up, @ds300.
Would you start it as RFC https://github.com/yarnpkg/rfcs/blob/master/README.md?

From my perspective we need API to execute JavaScript based on installation events: lock file updated, install finished, install skipped because integrity check passes, running post install scripts skipped because they were cached, etc.

We could come up with a solution when discussing it there.
Your help will be very much appreciated as the core team is all busy with multiple projects and we just can't focus on every issue we have.

I'll close this issue.
