### ISSUE TITLE
Anyone know how to do a manual installation of yarn ???

### ISSUE THREAD

**Issue by kakumei12** [yarnpkg/yarn#3491]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by bestander** [comment]
The most manual is download a .js file from releases https://github.com/yarnpkg/yarn/releases.
Or the installer.
Otherwise here https://yarnpkg.com/en/docs/install#alternatives-tab
