### ISSUE TITLE
Problem running production task

### ISSUE THREAD

**Issue by jirehstudios** [yarnpkg/yarn#3493]
I am using Laravel 5.4 with the default package.json except I removed some dependencies. When I run `yarn run dev` there is no issue, but `yarn run production` produces the following:

    undefined:1625
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
    SyntaxError: Unexpected token: punc ())
    at JS_Parse_Error.get (eval at <anonymous> (/home/marcos/Repos/ada-app/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I noticed that I need to use the `.babel([...])` webpack/mix method to avoid this error; using `.scripts([...])` is what produces the error. I have ES2015 code in the file that's causing the error; am I required to use babel anyway? I figured it'd be optional. It's an internal app and everyone is forced to use the latest Chrome.

The file that's causing the error (the arrow function):

    $(document).ready(() => {
        // Activate mobile menu
        $('#mobileMenuCollapse').sideNav();
    });

**Comment by bestander** [comment]
Hi, could you please create a repro scenario on github?
I.e. a project with a guide how to reproduce the issue?
I'll close but feel free to reopen with repro steps.
