### ISSUE TITLE
Error 500 on registry.yarnpkg.com while installing a package

### ISSUE THREAD

**Issue by psaussure** [yarnpkg/yarn#3494]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Our CI, trying to install packages on an Angular solution, fails with an Error 500.

> An unexpected error occurred: "https://registry.yarnpkg.com/@types/q/-/q-0.0.32.tgz: Request failed \"500 Internal Server Error\"".

Running `npm install` instead of `yarn install` works perfectly.

**Please note**: this is intermittent bug. Sometimes the install go through complete process without 500 Error.

**What is the expected behavior?**
No 500 Error

**Please mention your node.js, yarn and operating system version.**
Node 7.8.0
Win 10
Yarn 0.24.5

**Comment by blackholegalaxy** [comment]
Similar problem today
`error An unexpected error occurred: "https://registry.yarnpkg.com/@types/node/-/node-6.0.68.tgz: Request failed \"500 Internal Server Error\"".`

**Comment by BYK** [comment]
I think this was a transient error so closing.
