### ISSUE TITLE
Installation Problem: Arch Linux – invalid PGP signature

### ISSUE THREAD

**Issue by sindrenm** [yarnpkg/yarn#3495]
**Which operating system are you using:**

Arch Linux

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Tried installing from the official repositories:
```
sudo pacman -S yarn
```

Firstly, I'm getting a ton of 404s from several mirrors:
```
error: ... from mirror.f4st.host : ... 404
error: ... from ftp.nluug.nl : ... 404
error: ... from ftp.myrveln.se : ... 404
error: ... from mirror.hactar.xyz : ... 404
error: ... from archlinux.dynamict.se : ... 404
error: ... from archlinux.mirror.ba : ... 404
error: ... from mirror.tyborek.pl : ... 404
error: ... from mirrors.uni-plovdiv.net : ... 404

...
```
(Truncated for brevity, can post full errors if needed.)

Then I'm finally able to resolve one package, but the signature seems to be off:

```
error: yarn: signature from "Sven-Hendrik Haase <svenstaro@gmail.com>" is invalid
```

The file in question is _yarn-0.24.5-1-any.pkg.tar.xz_.

**Comment by EugeneHlushko** [comment]
More to say, 0.24.6-1 is not available

**Comment by Daniel15** [comment]
Please contact the maintainer of the Arch Linux package. It's not maintained by the Yarn team. cc @svenstaro - Looks like that's your email address in the GPG signature 😃

**Comment by sindrenm** [comment]
Ahh, sorry about that, @Daniel15. Since it was documented in the README, I figured it was also maintained by the maintainers of Yarn. And I thought it'd be nice to have installation issues in one place for others with the same problem. :smile:

**Comment by sindrenm** [comment]
Hmm … I just tried installing it on another machine (also running Arch) and I had no issues there. Was the package updated? If not, then perhaps there's something wrong with my setup on the first computer I tried it on when I opened this issue. Strange. Feel free to close unless you wish, as it does seem to work on this laptop, so I guess the package is probably fine. :+1:

**Comment by Subzidion** [comment]
Make sure that your [system is up to date](https://wiki.archlinux.org/index.php/System_maintenance#Upgrading_the_system). Can you install packages other than yarn?

**Comment by svenstaro** [comment]
Arch does not support partial updates. Always use -Syu when installing a package.

**Comment by sindrenm** [comment]
Yeah, my system is up to date and I'm able to install other packages. I just managed to install it using the exact same command I tried with two days ago. Strange. :stuck_out_tongue: 

Thanks for the quick responses, guys. :smile:
