### ISSUE TITLE
Typo in warning message

### ISSUE THREAD

**Issue by JasonEtco** [yarnpkg/yarn#3496]
**Do you want to request a *feature* or report a *bug*?**
It's a lil' ol' typo bug

**What is the current behavior?**
There's a typo in the `Lockfile has incorrect entry` warning message. `Ingoring` instead of `Ignoring`

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/yarnpkg/yarn/blob/8ede3c41cfb389ee408ae1094503649dc11b11cc/src/reporters/lang/en.js#L97

**Please mention your node.js, yarn and operating system version.**
I'm on Node 7.6.0, yarn 0.24.5 but I've verified in the master branch that this is still the case.

**Comment by bestander** [comment]
Thanks, would you send a PR please?

**Comment by JasonEtco** [comment]
Thanks @ppsmirnov for getting to it before I could 🥇
