### ISSUE TITLE
"command not found" when executing globally installed package

### ISSUE THREAD

**Issue by EekoS** [yarnpkg/yarn#3498]
Hi,

I'm trying to install Angular CLI globally with yarn, but I can't seem to get it to work (`ng -v` doesn't work).

I get the following warning, and `ng -v` doesn't work - not on the same terminal window, not on a new terminal window, and not after closing this terminal window and opening a new one :(

```
$ cat /etc/centos-release
CentOS release 6.5 (Final)
$ node -v
v6.10.3
$ yarn -v
yarn install v0.25.2
```

```
$ yarn global add @angular/cli
yarn global v0.25.2
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@angular/cli@1.0.5" with binaries:
      - ng
warning No license field
Done in 7.46s.
```

```
$ ng -v
bash: ng: command not found
```

I saw a [similar issue](https://github.com/yarnpkg/yarn/issues/1285) but it was supposedly fixed a long time ago.

Does anyone know what to do please?

**Comment by Daniel15** [comment]
Try running `yarn global bin` and check that the directory it prints out is on your `PATH`.

Also try with `sudo` (ie. `sudo yarn global add @angular/cli`) as there may  still be an issue with Yarn incorrectly using the Node.js installation directory as the executable directory, which is not writable by normal users.

**Comment by epicallan** [comment]
I am having a similar error on a travis build

**Comment by Daniel15** [comment]
@epicallan - Do you mean the "fsevents" thing? The `fsevents` warning can be ignored - fsevents is only for Mac OS, so it will fail to install on all other platforms.

Or do you mean the "command not found" after installing a global module?

**Comment by epicallan** [comment]
I am having an error with "fsevents" thing
with yarn v0.24.5
<details>
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
</details>

**Comment by epicallan** [comment]
@Daniel15 I have realized the "fsevents" thing was being introduced by one particular dev dependency install that i don't even need for my builds, removed it  and everything works fine.

**Comment by bestander** [comment]
similar to https://github.com/yarnpkg/yarn/issues/3685
