### ISSUE TITLE
Yarn upgrade-interactive check should ignore exact or subversion dependencies

### ISSUE THREAD

**Issue by matt3224** [yarnpkg/yarn#3500]
**What is the current behavior?**

Currently if you have something like this in your dev dependencies:
`"clean-css": "~3.4.26"` or `"clean-css": "=3.4.26"`
it will still offer an update to 4.x.x

**What is the expected behavior?**

I would expect yarn upgrade-interactive to not offer the update at all if i have set `=` and only offer subversion updates if i supply `~`

**Please mention your node.js, yarn and operating system version.**
node v6.10.3
yarn v0.24.6
macOS 10.12.5

**Comment by rally25rs** [comment]
The docs aren't entirely clear, but `upgrade-interactive` has always ignored the package.json specified version ranges.

IMO it's been the most confusing part of Yarn;

* `yarn upgrade` - uses package.json version range
* `yarn upgrade <package>` - ignores package.json version range
* `yarn upgrade-interactive` - ignores package.json version range

-----

Perhaps this should be a feature request; upgrade-interactive should have a mode/flag for using or ignoring the version range in package.json.

**Comment by matt3224** [comment]
Okay good to know, it should watch the package.json range by default IMO, don't think I can label though so we shall leave it to the pro's

**Comment by bestander** [comment]
Should be resolved in https://github.com/yarnpkg/rfcs/pull/71
