### ISSUE TITLE
yarn upgrade-interactive doesn't show links to READMEs any more

### ISSUE THREAD

**Issue by BendingBender** [yarnpkg/yarn#3503]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Yarn used to show links to packages' README files in a third column next to the packages' old and new versions. This was very convenient as one could navigate directly to the projects' pages to look at what has changed before doing an upgrade.

**If the current behavior is a bug, please provide the steps to reproduce.**

Simply run `yarn upgrade-interactive` with some outdated packages in package.json.

**What is the expected behavior?**
I think that there is some value in showing the links to packages' README files. I used to use them a lot to look up the changes done in the new version.

**Please mention your node.js, yarn and operating system version.**
node: 6.10.3
yarn: 0.24.5
OS: Ubuntu Linux 16.04.1

**Comment by truckingsim** [comment]
This also happens with `yarn outdated`

**Comment by bestander** [comment]
Looks fixed now
<img width="705" alt="screen shot 2017-06-21 at 8 01 07 pm" src="https://user-images.githubusercontent.com/2121048/27415559-6d72fc9a-56bc-11e7-89a2-6c87b5b68f2e.png">
