### ISSUE TITLE
Trace:    Error: ENOENT: no such file or directory, symlink '../gulp/bin/gulp.js' -> '/app/node_modules/.bin/gulp'

### ISSUE THREAD

**Issue by aios** [yarnpkg/yarn#3508]
Arguments: 
  /usr/bin/nodejs /usr/share/yarn/bin/yarn.js install

PATH: 
  /composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  0.26.0-20170525.2353

Node version: 
  7.10.0

Platform: 
  linux x64

npm manifest: 
```
  {
    "private": true,
    "scripts": {
      "dev": "npm run development",
      "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "watch-poll": "npm run watch -- --watch-poll",
      "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
      "prod": "npm run build",
      "build": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
      "animate.scss": "^0.0.6",
      "axios": "^0.15.3",
      "bootstrap-sass": "^3.3.7",
      "cross-env": "^3.2.3",
      "gulp": "^3.9.1",
      "jquery": "^3.1.1",
      "laravel-mix": "0.11.4",
      "lodash": "^4.17.4",
      "vue": "^2.3.3"
    },
    "dependencies": {
      "acorn": "^4.0.13",
      "moment": "^2.18.1"
    }
  }
```

After answer in #1961 just that trace
`
Trace: 
  Error: ENOENT: no such file or directory, symlink '../gulp/bin/gulp.js' -> '/app/node_modules/.bin/gulp'
`
But in docker build installs fine.

**Comment by bestander** [comment]
@aios, how do I repro the ENOENT error with this package.json?

**Comment by aios** [comment]
need docker container with yarn 0.26.0 and volume to this package.json with something_name
docker-compose run --rm something_name yarn install
profit...)

@bestander

**Comment by bestander** [comment]
I know almost nothing about docker.
If you could set up a script to get everything bootstrapped then someone could have a look how to debug this issue :)

**Comment by aios** [comment]
@bestander need some time. i will make that today)

**Comment by BYK** [comment]
This should be resolved in recent versions. Also, no response from the author in a long time so assuming fixed :)
