### ISSUE TITLE
yarn is not syncing scoped packages with the offline mirror when automatic pruning is enabled

### ISSUE THREAD

**Issue by mkxml** [yarnpkg/yarn#3509]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using and offline mirror and setting `yarn-offline-mirror-pruning` to `true` the offline mirror does not sync scoped packages.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've put up a [repo](https://github.com/mkxml/yarn-scoped-offline-bug) reproducing the bug from scratch. This seems to be closely related to #3154.

The steps to reproduce are simple, you can use an existing `yarn`-powered project:

1) Make sure `yarn-offline-mirror` is configured and `yarn-offline-mirror-pruning` is set to `true` in local `.yarnrc`.
1) Run `yarn add @kadira/storybook`.

The package for storybook will not be in the offline mirror directory. It's worth noting that it's underlying dependencies will be added, but the main module won't.

Both `package.json` and `yarn.lock` syncing will work as usual, the offline mirror will fail silently.

**What is the expected behavior?**

It's expected that the offline mirror will be synced with `yarn.lock` for all packages, including scoped packages.

**Please mention your node.js, yarn and operating system version.**

Yarn v0.24.6
Node v7.2.2
macOS 10.12.5

**Comment by xealot** [comment]
This post enabled me to fix my issue, but excluding `yarn-offline-mirror-pruning true` from my `.yarnrc` file.

**Comment by mkxml** [comment]
Yes, I can confirm that without setting `yarn-offline-mirror-pruning` to `true` the problem does not appear.

**Comment by bestander** [comment]
PR with a fix is welcome

**Comment by bestander** [comment]
pruneOfflineMirror is just a function in install.js, should be a straight forward fix.
cc @dguo

**Comment by brianhorst** [comment]
I tried offline pruning true with scoped packages on the 0.27.3 RC and it is working as expected. I don't know exactly what changed, but it was probably something for #3154. This can probably be closed.

**Comment by dguo** [comment]
Thanks for the update. I was planning to look into this issue today, but I'm glad to hear it appears to be fixed already.

**Comment by bestander** [comment]
Thanks for reporting
