### ISSUE TITLE
Locally installed binaries not working when package directory contains colon

### ISSUE THREAD

**Issue by chrisdothtml** [yarnpkg/yarn#3515]
I originally thought this was caused by having a nested package, but it turns out if the package directory has a `:` in it, local binaries stop working.

Once I changed the directory name from `project:dev` to `project-dev`, the local binaries started working again.

---

**node**: v7.10.0
**yarn**: v0.24.6
**OS**: macOS Sierra v10.12.5

**Comment by bestander** [comment]
Is `/` allowed to be in directory names?

**Comment by chrisdothtml** [comment]
@bestander apparently I had it backwards. Finder represents`:` in dir names as`/`. So when you create a dir in Finder with `/`, it's actually a `:`. I'll update the title based on that.

I also setup a [test repo](https://github.com/chrisdothtml/yarn-3515) for replication

**Comment by chrisdothtml** [comment]
I've been debugging this, and yarn seems to be populating the PATH correctly, so now I'm wondering if it's a child.spawn issue

**Comment by foucdeg** [comment]
@chrisdothtml see my referencing issue: the problem is that the system cannot parse a PATH with directories with`:` in them, because the `:` is the separator of PATH.

**Comment by chrisdothtml** [comment]
@foucdeg Ah that makes sense
