### ISSUE TITLE
yarn --help shows same command twice

### ISSUE THREAD

**Issue by mesaugat** [yarnpkg/yarn#3518]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn --help` shows some commands twice.

- generate-lock-entry
- run-script
- upgrade-interactive

<img width="330" alt="screen shot 2017-05-29 at 1 13 06 pm" src="https://cloud.githubusercontent.com/assets/4240991/26540489/6920a834-4471-11e7-9567-afae5bdf18b2.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn --help`

**What is the expected behavior?**
Should show the same command with same spelling not more than once.

**Please mention your node.js, yarn and operating system version.**
yarn 0.24.6
node 7.7.4
macOS Sierra 10.12.5

**Comment by mesaugat** [comment]
I quickly looked into the code and found this.

The `run-script` is appearing twice from here: https://github.com/yarnpkg/yarn/blob/master/src/cli/unsupported-aliases.js#L27-L28

For the other two commands`generate-lock-entry` and `upgrade-interactive`. It is coming from https://github.com/yarnpkg/yarn/blob/master/src/cli/aliases.js

While exporting `commands` the aliases get repeated because the commands already has `generateLockEntry` and `upgradeInteractive`: https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/index.js#L99-L102

So, these lines are probably not required. If I am correct, I can send in a pull request.

Thanks!

**Comment by bestander** [comment]
Same as https://github.com/yarnpkg/yarn/issues/3559.
PR with a fix is welcome
