### ISSUE TITLE
YARN :: called from CMD disable choosing version

### ISSUE THREAD

**Issue by bys92** [yarnpkg/yarn#3521]
**What is the current behavior?**
Currently Yarn tries to resolve the dependencies.
During this it's detecting conflicts and want that the user solve them by choosing one of the suggested version.

**What is the expected behavior?**
There should be a mode to disable this.
_Reason_:
Your Jenkins tries to build a project where some module versions conflicting.
Then Yarn want's that a user entering the version.
Jenkins can't do this. 
This could happen for every automated process.

A parameter like 
`yarn install --disable-input`
could disable this and change the ERRORLEVEL of the process to sth. > 0 so that every automated process could check and build logic depenend on that.

**Please mention your node.js, yarn and operating system version.**
yarn 0.23.4

**Comment by joha91** [comment]
Similar to that one: #2770

**Comment by bys92** [comment]
Already solved with flag 
--non-interactive

but the official yarn documentation is not adjusted.
