### ISSUE TITLE
Child process is exited prematurely when running a info command

### ISSUE THREAD

**Issue by ncuillery** [yarnpkg/yarn#3524]
When running the info command in the child process, the child process exits right after the reception of the first chunk of data:

```javascript
const exec = require('child_process').exec;

const child = exec('yarn info react-native@latest');

child.stdout.on('data', data => {
  console.log('DATA', data.length);
});

child.stderr.on('data', data => {
  console.log('ERROR', data);
});

child.on('exit', code => {
  console.log('EXIT', code);
});
```

Output: 
```
$ node debug-exec.js 
DATA 18
DATA 8192
EXIT 0
```

The first chunk of data contains `yarn info v0.24.5` (first line of the output). Then, the second chunk contains the first 8192b of the info command output. Then the process is closed properly (error code 0).

This bug has been discovered by using NPM 5.0.0. I investigated and I reproduced the same bug with yarn, so I report the issue here too.

- Original issue on React Native: https://github.com/facebook/react-native/issues/14239
- NPM issue I created after my investigation: https://github.com/npm/npm/issues/16780

**Comment by bestander** [comment]
Thanks for reporting.
According to npm fix process.stdout.write need to have a callback, should Yarn do the same?
Help welcome

**Comment by bestander** [comment]
I'll raise the priority to get keep it on radar.

**Comment by BYK** [comment]
I'll look into console reporter to see how hard this is to fix. Aiming for the 1.0 release for now.
