### ISSUE TITLE
yarn --production install devDependencies of dependencies

### ISSUE THREAD

**Issue by taylor1791** [yarnpkg/yarn#3525]
**Current Behavior**
When a dependency has devDependencies, those devDependencies are installed when using `yarn --production`.

**Expected Behavior**
When a dependency has devDependencies, those devDependencies are _not_ installed when using `yarn --production`.

**System Information**
$ yarn --version
0.24.6
$ node --version
v7.8.0

I can reproduce this on both macOS Sierra and Ubuntu

**Steps to Reproduce**
1. Use the package.json below
2. `yarn --production`
3. `node_modules/react` should not exist, but it does.
4. Running `npm prune --production` removes `node_modules/react`

```
$ npm prune --production
- react@15.5.4 node_modules/react
```

**package.json**
```json
{
  "devDependencies": {
    "react": "^15.5.4"
  },
  "peerDependencies": {
    "react": "^15.5.4"
  },
  "dependencies": {
    "react-select": "^1.0.0-rc.5"
  }
}
```

Notice that react-select has a devDependency (and peerDependency) of `react`.

**yarn.lock**
https://pastebin.com/VuQh3ZYB

**Comment by pichouk** [comment]
Duplicate #3312

**Comment by pichouk** [comment]
@bestander said in #3577 that it was fix in master, so I guess it can be closed.
