### ISSUE TITLE
eslint problem

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3535]
from https://github.com/eslint/eslint/issues/8547#issuecomment-304878486

This is not a react-scripts issue, but seemingly a Yarn bug.
In https://github.com/cmoesel/eslint-8547, run:
```
readlink `which ./node_modules/.bin/eslint`
```
It prints:

`../react-scripts/node_modules/eslint-plugin-react/node_modules/eslint/bin/eslint.js`
In other words, despite there being a top-level ESLint dependency, Yarn links `./node_modules/.bin/eslint to an inner ./node_modules/react-scripts/node_modules/eslint-plugin-react/node_modules/eslint/bin/eslint.js` (?!) rather than expected ./node_modules/eslint/bin/eslint.js.

If Yarn fixes the issue, the problem should go away.

**Comment by bestander** [comment]
Could this cause the issue https://github.com/yarnpkg/yarn/pull/3310?

**Comment by cmoesel** [comment]
This is just a continuation of the story already documented in #3332.  But... this issue immediately gets down to what is likely the real root of the problem!

**Comment by bestander** [comment]
With the [repro](https://github.com/cmoesel/eslint-8547) package I can confirm that eslint link in .bin is incorrect
```
 eslint -> ../react-scripts/node_modules/eslint-plugin-react/node_modules/eslint/bin/eslint.js
```

Should be 
```
eslint -> ../eslint/bin/eslint.js
```

Thanks @cmoesel!
Reverting https://github.com/yarnpkg/yarn/pull/3310 does not really fix it.

I'll look deeper tomorrow and prepare a patch for 0.25

**Comment by ColCh** [comment]
@bestander in which version of yarn is this issue fixed?

I'm using `yarn@0.27.5` and `eslint` link is broken for me
```
~/D/W/L/l/app-data-viewer (324-rn-47|✚5) $ ls -la node_modules/.bin/eslint
lrwxr-xr-x  1 colch  staff  23  3 сен 16:22 node_modules/.bin/eslint -> ../eslint/bin/eslint.js
~/D/W/L/l/app-data-viewer (324-rn-47|✚5) $ yarn --version
0.27.5
```
