### ISSUE TITLE
Yarn website down?

### ISSUE THREAD

**Issue by besarthoxhaj** [yarnpkg/yarn#3549]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
bug

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `curl -o- -L https://yarnpkg.com/install.sh | bash`.
Check also https://travis-ci.org/yarnpkg/yarn/jobs/237976249

**What is the expected behavior?**
Should install yarn correctly

**Please mention your node.js, yarn and operating system version.**
All of them?

**Comment by destroyerofbuilds** [comment]
Duplicate of yarnpkg/website/issues/519

**Comment by Sibiraj-S** [comment]
Site is up now...

**Comment by besarthoxhaj** [comment]
Panic is over people:) As mention site is up. Closing
