### ISSUE TITLE
Not creating bin files when installing globally

### ISSUE THREAD

**Issue by welkie** [yarnpkg/yarn#3551]
Unfortunately, I can't try it with the latest version of Yarn because the latest version is not yet in the Kubuntu repositories. I am using version 0.24.5.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Installing a package globally seems to work, there are no error messages when specifying a --prefix (like the /usr/local example [here](https://yarnpkg.com/en/docs/cli/global). However, no binary files are in the folder specified after the installation completes.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run ```yarn global add <package-name> --prefix <directory-in-directory-you-own>``` and then try to run the command. Or, perform an ```ls``` of the directory specified, and you'll see the **bin** folder was never created in it.

**What is the expected behavior?**
The package install completes and the command is able to be used, or at least the binary file is there.

**Please mention your node.js, yarn and operating system version.**

Kubuntu 17.04

```
$ node -v && yarn --version
v7.10.0
0.24.5
```

**Comment by BYK** [comment]
I think this is resolved in recent versions so closing.
