### ISSUE TITLE
Migrating from NPM to Yarn when package.json is incorrect

### ISSUE THREAD

**Issue by owenauch** [yarnpkg/yarn#3554]
Hello,

I recently started working on a pre-existing react-native project, and upon setup I encountered a lot of dependency and versioning errors. The versions on package.json are incorrect for our project, and it caused errors when I ran it until we finally decided to just copy the node_modules folder into my repository from another team member's working repo instead of using `npm install`.

We'd like to migrate the project to Yarn so that this doesn't continue to happen, but when I try to create a yarn.lock file using either `yarn install` or `yarn install --check-files`, I end up with wrong versions and a broken project. Is there any way to generate a yarn.lock file, and potentially a new package.json, based on the versions that are in the node_modules directory?

**Comment by solocommand** [comment]
@owenauch Check out [`yarn import`](https://yarnpkg.com/lang/en/docs/cli/import/).

`yarn install` is designed to update your `node_modules` folder with the contents specified in your `yarn.lock` file or `package.json` if you don't have a lockfile yet.

`yarn install` is designed for your use case, migrating to `yarn` from `npm` or `npm-shrinkwrap`. Check to make sure that your installed versions actually match what your `package.json` defines though, or the import command won't complete successfully. You can verify package versions by using `npm ls` -- it will display errors if you have versions installed that don't match your `package.json`.

**Comment by arcanis** [comment]
As @solocommand said, `yarn import` should be the way to go 👍
