### ISSUE TITLE
yarn.lock sometimes not created despite success Saved lockfile message

### ISSUE THREAD

**Issue by jharris4** [yarnpkg/yarn#3555]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

yarn.lock is not created even though yarn cli reports that it was.

**If the current behavior is a bug, please provide the steps to reproduce.**

rm -rf node_modules
rm yarn.lock
yarn install
ls yarn.lock

**What is the expected behavior?**
The lock file should always be created

**Please mention your node.js, yarn and operating system version.**
MacOS 10.12.5
Node 8.0.0
Yarn 0.24.6

I've been seeing this issue intermittently for quite some time. Was sort of surprised to not (easily) find a duplicate issue. I'm pretty sure this is not related to Node 8 since I was seeing it intermittently with Node v7.

**Comment by jharris4** [comment]
ok, its happening much more frequently now. Perhaps it's aggravated by node 8 somehow.

**Comment by jharris4** [comment]
Here's the output from it just happening again. The first time, no lock file was generated but the second time it was.

```
$ yarn install
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning socket.io-client > socket.io-parser > isarray@2.0.1: Just use Array.isArray directly
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/3] ⠂ fsevents
[1/3] ⠄ fsevents
[2/3] ⠄ node-sass
[1/3] ⡀ fsevents
[1/3] ⠐ fsevents: node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
[1/3] ⠠ fsevents: node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
[2/3] ⠠ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-57_binding.node
[3/3] ⠠ uws
[-/3] ⠠ waiting...
success Saved lockfile.
✨  Done in 22.18s.

$ yarn install
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning socket.io-client > socket.io-parser > isarray@2.0.1: Just use Array.isArray directly
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 25.60s.

```

**Comment by xmlking** [comment]
same thing for me here.
Node 8.0.0 and yarn v0.24.6
https://github.com/xmlking/hub/tree/master/server
I also have `socket.io-client`  warning

**Comment by arcanis** [comment]
I haven't been able to reproduce it yet, and I've ran Yarn a lot of time :(

**Comment by jharris4** [comment]
It's happening on every project I am currently working with at least 50% of the time for me right now.

I don't know if it has any effect, but all the projects have some git dependencies of the style `git+https://domain.com/r/repo.git#semver`, and those git urls have their own dependencies in their respective package.json files.

**Comment by junosw** [comment]
Just had this start happening on a project I'm working on today. Same exact specs as OP:
MacOS 10.12.5
Node 8.0.0
Yarn 0.24.6

Can't get the yarn.lock to generate even though console output says it does.  Additional piece of info - I discovered this issue when adding a new package and noticed that package.json was not being updated either.

**Comment by jharris4** [comment]
Just happened for me on a project without git dependencies, so definitely not related to that. Must be related to having upgraded to Node 8.

**Comment by junosw** [comment]
@jharris4 I suspect that is the case.  I rolled back to 7.10 and it started working fine.

**Comment by jharris4** [comment]
Just tried with the newly realeased Node 8.1 and still having the issue.

**Comment by jharris4** [comment]
Just noticed that if `node_modules` are present, the lock file is reliably created. If `node_modules` are absent, the lock file is never properly created. I can reproduce this 100% of the time. Not sure how I can help someone else reproduce though.

**Comment by jharris4** [comment]
This bug has been driving me nuts, so I just finally put together a reliably reproducible example.

Copy the attached `package.json` file to an empty directory. Then do:

**Comment by jharris4** [comment]
@arcanis Can you let me know if you can now reproduce this issue? (I'm currently running Node 8.1.2 and Yarn 0.24.6)

**Comment by domoritz** [comment]
Can confirm

<img width="1034" alt="screen shot 2017-06-18 at 19 09 48" src="https://user-images.githubusercontent.com/589034/27266936-bf7c9eac-5459-11e7-81ea-c66a1513c3c9.png">

**Comment by domoritz** [comment]
@rally25rs, I could reproduce the error with @jharris4 script.

**Comment by jharris4** [comment]
I've spent some time narrowing it down. It is the `socket.io` package that is causing the lock file not to be created. The following package.json is reliably reproducing the issue for me:

```
{
  "name": "yarn-lock-bug",
  "version": "1.0.0",
  "description": "repro bug with yarn not creating lock file",
  "author": "jharris4",
  "license": "MIT",
  "devDependencies": {
    "socket.io": "^2.0.3"
  }
}

```

**Comment by jharris4** [comment]
Ok, it's the `optionalDependencies` section in `engine.io` package that's causing this bug. I've filed a new issue to draw attention to the specific details about the bug. https://github.com/yarnpkg/yarn/issues/3728

**Comment by jharris4** [comment]
`npm install -g node-gyp` seems to resolve this issue with Node 8.

**Comment by BYK** [comment]
@jharris4 shall we close this one in favor of #3728?

**Comment by jharris4** [comment]
@BYK sure, no need to have more than one issue open.

The main thing is that the issue seems to be related to `node-gyp` ...

**Comment by BYK** [comment]
Alright, thank you :)
