### ISSUE TITLE
Error 403 Forbidden when adding bootstrap

### ISSUE THREAD

**Issue by sefo** [yarnpkg/yarn#3557]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Running yarn add bootstrap returns a 403 error.
"An unexpected error occurred: "https://registry.yarnpkg.com/bootstrap: Req
uest \"https://registry.yarnpkg.com/bootstrap\" returned a 403".

The issue seems to be similar to this https://github.com/yarnpkg/yarn/issues/2793 but with the add command.

**Comment by arcanis** [comment]
I can't reproduce this on my side - do you have a particular configuration, like in the issue you've mentionned, where they had a custom registry url?

**Comment by sefo** [comment]
No I use the default configuration. I tried changing the registry from https to http but it didn't help.
Manually accessing https://registry.yarnpkg.com works.
I also tried setting strict-ssl to false

The company I work for has strict network rules. That has to do with my issue. (npm on the same package file does work though)

**Comment by bestander** [comment]
The issue is probably in your internet proxy configuration.
Yarn has a setting for that.
