### ISSUE TITLE
Yarn does not canonicalize repository URLs when setting `npm_package_repository_url` env var

### ISSUE THREAD

**Issue by jasonkarns** [yarnpkg/yarn#3565]
**Do you want to request a *feature* or report a *bug*?**: Bug

**What is the current behavior?**
Npm normalizes package repository URLs to a canonical form before setting the corresponding env var (`npm_package_repository_url`). Yarn does not normalize the URLs but instead sets the value of the env var as it exists in the package.json. This leads to an inconsistency between the environments in which a package script or node process is run by yarn or npm.

package.json:
```json
"repository": {
  "url": "https://github.com/testdouble/testdouble.js.git"
}
```

npm yields:
```
npm_package_repository_url=git+https://github.com/testdouble/testdouble.js.git
```

yarn yields:
```
npm_package_repository_url=https://github.com/testdouble/testdouble.js.git
```

It's worth noting that npm and yarn both normalize the `repository` string into the object: `{ url, type }`. So at least some normalization already occurs within yarn that matches npm. It just doesn't seem to normalize the URL value itself.

**Steps to reproduce.**

Within the following repo+branch: 
https://github.com/jasonkarns/testdouble.js/tree/npm-vs-yarn

`npm run repository`
`yarn run repository`

**What is the expected behavior?**
Expected behavior that the variables introduced by yarn match those introduced by npm, to allow scripts to be cross-compatible between npm and yarn.

**Please mention your node.js, yarn and operating system version.**
- node 8.0
- npm 4.2 (same with 5.0)
- yarn 0.24.5
- macOS Sierra 10.12.5

**Comment by olingern** [comment]
@jasonkarns I cloned your repo, and ran both commands. Both produce the same output.

<img width="778" alt="screen shot 2017-08-18 at 9 47 29 pm" src="https://user-images.githubusercontent.com/1470297/29482420-e2f51f3c-845e-11e7-96f6-497e7c7ff98c.png">
<img width="535" alt="screen shot 2017-08-18 at 9 47 41 pm" src="https://user-images.githubusercontent.com/1470297/29482421-e2f5f2d6-845e-11e7-8242-93bf1d343b0e.png">

My system settings:
- node 8.1.4
- yarn 0.27.5

**Comment by jasonkarns** [comment]
Still manifests for me:

```
$ node -v && npm --version && yarn --version
v8.4.0
5.3.0
0.27.5

$ diff <(yarn run repository | head -4 | tail -2) <(npm run repository 2>/dev/null | tail -2)
1c1
< npm_package_repository_url=https://github.com/testdouble/testdouble.js.git
---
> npm_package_repository_url=git+https://github.com/testdouble/testdouble.js.git
```

**Comment by BYK** [comment]
I was able to verify this with the latest version of Yarn. However, I don't think this is important enough to put resources in so closing the issue.

Feel free to come up with a PR that doesn't impact the performance too much. Seems like Yarn already detects the repo type properly so it shouldn't be too hard to do this if you really want the feature :)
