### ISSUE TITLE
Yarn does not support `yarn run env` as npm does

### ISSUE THREAD

**Issue by jasonkarns** [yarnpkg/yarn#3566]
**Do you want to request a *feature* or report a *bug*?** inconsistency with npm

**What is the current behavior?**
One can run `npm run env` in any package and it will print the environment under which package scripts would run. It is in essence as if the script `"env": "printenv"` existed in the package.

Yarn, however, does not do this.

```
$ yarn run env
yarn run v0.24.5
error Command "env" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ npm run env

> testdouble@2.1.2 env /Users/jasonkarns/Projects/td/testdouble.js
> env

[... env var dump ...]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn run env` from any package that doesn't already have an "env" script.

**What is the expected behavior?**
If it is desired to match npm-cli behavior, the expected output would be a `printenv` call from within the context of a package script.

**Please mention your node.js, yarn and operating system version.**
- node 8.0
- npm 4.2 (same with 5.0)
- yarn 0.24.5
- macOS Sierra 10.12.5

**Comment by arcanis** [comment]
TIL. It would be nice to have this feature, I myself often typed `"env": "env"` in my scripts to have the same behavior. Would you be willing to make a PR?

**Comment by jasonkarns** [comment]
@arcanis I don't have the time to PR this. Though as an aside, I would recommend you use `printenv` as the command for your "env" script, because `env` does more than just print the environment.

**Comment by bestander** [comment]
Done

**Comment by jasonkarns** [comment]
This seems buggy. Just tested on 0.27.5 and the `yarn run env` command doesn't include any of the `npm_package_*` env vars that are present from a yarn/npm script.

```
$ npm run env | ag npm_package | wc -l
      88
$ yarn run env | ag npm_package | wc -l
       0
```

Since this has been released, should I open this bug as a separate issue?
