### ISSUE TITLE
Confusion while running using yarn why and yarn remove

### ISSUE THREAD

**Issue by rogovdm** [yarnpkg/yarn#3568]
Running `yarn why kerberos` displayed that is exist only in package.json.
````
yarn why v0.24.6
[1/4] 🤔  Why do we have the module "kerberos"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "kerberos"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "1.28MB"
info Disk size with unique dependencies: "1.73MB"
info Disk size with transitive dependencies: "1.73MB"
info Number of shared dependencies: 1
✨  Done in 1.78s.
````

My expectation was that is was an unused module.

Running `yarn remove kerberos` got me to
````
[1/2] Removing module kerberos...
[2/2] Regenerating lockfile and installing missing dependencies...
warning "mongodb-core@1.2.31" has unmet peer dependency "kerberos@~0.0".
````

I expected that kerberos was an unused dep and it was safe to remove. But during removal turned out that it is used by mongodb-core.

yarn 0.24.6
mongodb: "^2.2.27"
kerberos: "^0.0.23"

**Comment by rally25rs** [comment]
I think I remember seeing a bug somewhere that `why` only prints the first dependency that it finds, not all of them. Might be related to #3228

**Comment by arcanis** [comment]
Yep! I'll close this in favor of #3228 :) If someone wants to make a PR to fix this, I'll gladly merge it.
