### ISSUE TITLE
Upgrade Problem: Stuck at version 0.24.5-1

### ISSUE THREAD

**Issue by brandiqa** [yarnpkg/yarn#3570]
**Which operating system are you using:**
Linux Mint 18.1 Serena 64-bit, Kernel Linux 4.4.0-53-generic x86_64

**Please describe the steps you took when trying to upgrade Yarn and what went wrong:**

I keep getting the warning:
warning Your current version of Yarn is out of date. The latest version is "0.24.6" while you're on "0.24.5".

So I tried to upgrade

```bash
 sudo apt-get update && sudo apt-get install yarn
....
$ yarn --version
0.24.5
```

The version still remains at v0.24.5. I've also noticed https://www.npmjs.com/package/yarn is not up-to-date too.

**Comment by brandiqa** [comment]
This issue has now been fixed.

**Comment by code-by** [comment]
$ cd /
$ sudo apt-get update && sudo apt-get install yarn
yarn is already the newest version (1.0.1-1).
$ yarn --version
0.24.4
o_O...

**Comment by arcanis** [comment]
```
$ which yarn
```
?

**Comment by code-by** [comment]
/home/user_name/.yarn/bin/yarn

**Comment by code-by** [comment]
removed, now is ok )
