### ISSUE TITLE
Yarn how to upgrade version

### ISSUE THREAD

**Issue by adamostrogorski** [yarnpkg/yarn#3574]
I have Yarn version 0.22. I must upgrade Yarn to version 0.23.4 (at least).

I try with commends from Yarn doc:

    sudo apt-get update && sudo apt-get install yarn

    yarn upgrade v0.23.4

but I still have version 0.22.

How can I upgrade Yarn?

[I need Yarn to install gulp, beacuse in Yarn version 0.22 some packages of gulp  not install]

**Comment by crh225** [comment]
https://github.com/yarnpkg/yarn/releases
has a tar.gz or a deb package

or you can try yarn upgrade

**Comment by jhabdas** [comment]
@adamostrogorski you may need to find a mirror with a more current version of the package. all you should need to do is `apt-get remove yarn && apt-get update && apt-get yarn` again.

**Comment by Daniel15** [comment]
Check that `/etc/apt/sources.list.d/yarn.list` exists. If not, create it with this text:
```
deb https://dl.yarnpkg.com/debian/ stable main
```

Then `apt-get update && apt-get install yarn` will give you the latest Yarn. This repo should always have the latest version of Yarn.

Please let me know if this doesn't work for you :)

**Comment by cpxPratik** [comment]
Use alternative method to update yarn https://yarnpkg.com/en/docs/install#alternatives-tab
Run this on cli, `curl -o- -L https://yarnpkg.com/install.sh | bash`

**Comment by johnantoni** [comment]
here's what works for me...

    npm i -g yarn

**Comment by sotownsend** [comment]
Mac users with homebrew can run `brew upgrade yarn`

**Comment by xgqfrms** [comment]
# install is more easy than upgrade

```sh
$ curl -o- -L https://yarnpkg.com/install.sh | bash
```

```sh
$ brew upgrade yarn

```
