### ISSUE TITLE
Yarn can’t install `tap-prettify`

### ISSUE THREAD

**Issue by davidaurelio** [yarnpkg/yarn#3582]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn fails with

```
error Couldn't find a package.json file in ".../node_modules/tap/node_modules/tap-consumer"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add tap-prettify`

**What is the expected behavior?**
Installation without failure

**Please mention your node.js, yarn and operating system version.**
v8.0.0, v0.24.6, macOS

**Comment by arcanis** [comment]
Apparently `tap-consumer` is a bundled dependency of `tap`, but it isn't available in `tap`'s node_modules - either because it never got copied there during the linking, or because it got somehow removed, possibly when linking its non-bundled dependencies.

**Comment by bestander** [comment]
merging https://github.com/yarnpkg/yarn/issues/886

**Comment by bestander** [comment]
PR to fix is welcome.
Otherwise it is actually a bug in the package.
