### ISSUE TITLE
cmd-shim using octal without `o`

### ISSUE THREAD

**Issue by rufman** [yarnpkg/yarn#3583]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Running `yarn test` through `nyc` fails because strict mode does not allow the usage of octals without `o` (which cmd-shim does). The error produced is `Invalid number`

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project with nyc being used for code coverage

**What is the expected behavior?**
yarn shouldn't fail because of a babel transform

**Please mention your node.js, yarn and operating system version.**
yarn: 0.24.6
node: 
os: Mac OS 10.12.5

**Comment by Daniel15** [comment]
If the error is in cmd-shim, please file an issue for the cmd-shim project.

**Comment by bestander** [comment]
It is not clear if the issue is in Yarn.
Please provide a repro script and reopen the issue
