### ISSUE TITLE
Running `yarn add PACKAGE` doesn't add the package to `packages.json`

### ISSUE THREAD

**Issue by cbrwizard** [yarnpkg/yarn#3586]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
Running `yarn add PACKAGE` doesn't add the package to `packages.json`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. cd to a folder with yarn.lock, package.json
2. run `yarn add koa-helmet` (or any other package)
3. It outputs 
```
success Saved lockfile.
success Saved 1 new dependency.
```
4. No updates in package.json

**What is the expected behavior?**
Expect package.json to be updated with 
```
    "koa-helmet": "^3.2.0",
```

**Please mention your node.js, yarn and operating system version.**
```
❯ node -v
v8.0.0
❯ yarn -V
0.24.6
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.5
BuildVersion:   16F73
```

The funny thing is that running `npm i -S koa-helmet` from the exact same folder worked as expected: it added a new line to `package.json`.

Noticed today, spent some time trying to understand why didn't my Node couldn't find a package even though I have installed it hehe.
My theory is that it might be linked with a node upgrade, which I did yesterday.
Tried with reinstalling yarn using brew, got the same result.

**Comment by cbrwizard** [comment]
Tried with reinstalling yarn using brew, got the same result.

**Comment by arcanis** [comment]
Cannot reproduce :(

```
❯ [mael-mbp?] /Users/mael/test ❯ rm -rf package.json node_modules && echo '{}' > package.json && yarn && yarn add koa-helmet && cat package.json

yarn install v0.23.4
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Saved lockfile.
✨  Done in 0.05s.
yarn add v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 33 new dependencies.
warning No license field
✨  Done in 1.30s.
{
  "dependencies": {
    "koa-helmet": "^3.2.0"
  }
}
```

**Comment by cbrwizard** [comment]
Just wanted to add that now this works as expected for me. I don't know what caused this (a theory is that Docker's volume prevented package.json from being updated, but I don't want to check it now)

**Comment by bestander** [comment]
Thanks for a follow-up, @cbrwizard

**Comment by cmawhorter** [comment]
I think I figured out the problem here: node-gyp.  If your package.json has a dep that requires node-gyp and node-gyp doesn't exist, yarn will say it worked -- but doesn't -- and package.json won't be updated.

In my case, this dep was canvas-prebuilt.  

In the yarn output, yarn was complaining about `node-gyp command not found` when running with my hombrew-installed-nodejs.  No idea why no node-gyp, but switching to nvm use 8 (8.0.0) resolved the problem.

Yarn finds node-gyp and all is once again right with the world.

**Comment by laugri** [comment]
I had the same issue as @cmawhorter. Updating node from `v8.6.0` to `v8.9.4` fixed it for me.

**Comment by tlaak** [comment]
I just noticed the same issue with node 9.5.0.

**Comment by hckrmoon** [comment]
When I use node version v9.8.0, I noticed yarn does not add any info in package.json. 
So I change node version to v8.10.0 and it just works.

**Comment by aguynamedben** [comment]
Just noticed this using Node v10.2.0 and node-sqlcipher, a library that also depends on node-gyp. Everything looked fine, but node_modules/<package> was not added, and the package was not added to package.json.

Seems like a bug with node-gyp. Once I added node-gyp as a dev dependency myself, in my own project, everything started working (i.e. `yarn add --dev node-gyp`).

**Comment by saibaneer** [comment]
Hi Guys, I have this same issue. The weirdest thing is, there's no ```package-json.lock``` file. 
I have checked all other files, there's no hidden node_modules.
![grasp](https://user-images.githubusercontent.com/10155781/173810547-0859380f-9922-45b6-90fa-421699873668.png)

**Comment by faceyacc** [comment]
> Hi Guys, I have this same issue. The weirdest thing is, there's no `package-json.lock` file. I have checked all other files, there's no hidden node_modules. ![grasp](https://user-images.githubusercontent.com/10155781/173810547-0859380f-9922-45b6-90fa-421699873668.png)

I believe you are following Patrick's course on Blockchain. A quick workaround is to manually add his `package.json` file and run `npm install`. Once that is done run `yarn install` and you should be good to go.
