### ISSUE TITLE
Permission denied for package after using yarn link

### ISSUE THREAD

**Issue by MtDalPizzol** [yarnpkg/yarn#3587]
I have a package where I ran **yarn link**. Then, I ran **yarn link my-package** at another folder.
Then, when I ran **my-package** I got:

`bash: /home/myuser/.npm-global/bin/my-package: Permission denied`
 
I had not the same problem with **npm link**.

Seems like Yarn isn't linking binaries the same way as NPM.

Node: 6.10.3
Yarn: 0.24.5
OS: Linux Mint 18 Cinnamon 64-bit

**Comment by jharris4** [comment]
Just hit the exact same issue. Seems to have worked at first, but then I started getting `permission denied`. I tried deleting the symlink and recreating manually, but no luck.

Node 8.1.2
Yarn 0.24.6
MacOS 10.12.5

**Comment by jharris4** [comment]
Fixed it by doing `chmod +x` on the linked bin file

**Comment by chrisdothtml** [comment]
> Fixed it by doing chmod +x on the linked bin file

Fixed it for me as well, but why is this happening now? Never used to be an issue for me

**Comment by jharris4** [comment]
The file I had to use `chmod +x` on did have a `.js` extension

**Comment by farism** [comment]
In npm they [always ensure that bins are executable](https://github.com/npm/npm/blob/24ec9f2dd4dcd4f25622dff3a502d4e86a025c0d/lib/build.js#L186) during the build phase.

Should yarn be doing the same?

**Comment by BYK** [comment]
I think this is the case now so closing. If not, please reopen and provide more details like your Yarn version etc.

**Comment by batjko** [comment]
I'm getting this issue.
I use yarn link, then execute the package's binary file and get the permission error.
Of course I can make the bin executable, but every time I change the executable, it becomes non-executable again.

How can I do that automatically?

node 8.8.1
yarn 1.2.1

**Comment by allotrop3** [comment]
I am also getting this issue and the `chmod +x` fix above works for me as well. However, every time I run yarn at the root (of my monorepo i.e. build triggered in each package) I get the same old error again. I'm using Lerna with Yarn workspaces enabled. Is there any fix coming for this?

**Comment by monoclesociety** [comment]
we're getting it too over here:

Node: 9.5.0
Yarn: 1.3.2

**Comment by baconmania** [comment]
Also seeing this. Seems pretty janky to use `yarn` for most of my operations, but then be stuck with `npm link` for this one.

**Comment by nileshgulia1** [comment]
I'm having this error too. Also changed permission of my global /bin/sh file but still an error. @allotrop3 @jharris4 How did you fix this? Can you please help me on it.
``
/bin/sh: 1: plone-react: Permission denied
``
Here `plone-react` is symlinked package.

**Comment by jasonkuhrt** [comment]
This is still an issue with yarn `1.19.1`. Why is this this issue closed?

**Comment by carlesnunez** [comment]
It still being an issue to me too

**Comment by cyrilchapon** [comment]
Still an issue

**Comment by aprilandjan** [comment]
Yeah it is still an issue with yarn `1.19.1`.

**Comment by baob** [comment]
Still an issue with  yarn 1.21.1

**Comment by Sebdevar** [comment]
Almost 3 years later, still an issue and closed for whatever reason.

**Comment by tongy** [comment]
Still an issue with yarn 1.22.4

**Comment by remorses** [comment]
Still an issue, yarn should make the binaries executables before linking

**Comment by mattvb91** [comment]
Experiencing this issue currently

**Comment by shekari-ah** [comment]
I had the same issue, and I fix it with `chmod +x`.
apparently, yarn makes the link with wrong permissions. and the problem only happens on Linux, since I test it with windows.

**Comment by sulthan-ahmed** [comment]
I still have this issue 🤷‍♂️

**Comment by jking6884** [comment]
I'm still seeing the same issue as well.  @kevin-ashton workaround worked for me:

```Also getting it. Maybe worth noting that if I do an npm link, npm unlink, and then yarn link it seems to work. But if I do a yarn link from the beginning I get the permission issue.```

Node: 14.17.0
Yarn: 1.22.10
