### ISSUE TITLE
Workspaces creates self-references

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#3598]
I tried workspaces on Jest and the symlinks it created referred to itself:

<img width="962" alt="screen shot 2017-06-07 at 1 52 22 pm" src="https://user-images.githubusercontent.com/13352/26879313-8bc319ee-4b88-11e7-8a05-99948f612f15.png">

I could repo this two out of three times.

**Comment by arcanis** [comment]
Seems like the inter-dependency files are generated inside the source rather than inside the node_modules :/

**Comment by bestander** [comment]
Looking into in this Friday
