### ISSUE TITLE
yarn upgrade --latest doesn't preserve range specifier

### ISSUE THREAD

**Issue by develar** [yarnpkg/yarn#3609]
https://github.com/yarnpkg/yarn/pull/3510#issuecomment-307064171

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`yarn upgrade --latest` doesn't preserve range specifier.

**If the current behavior is a bug, please provide the steps to reproduce.**

`"electron-osx-sign": "0.4.6"` 

changed after `yarn upgrade --latest` to 

`"electron-osx-sign": "^0.4.6"`

i.e. package not upgraded, but range specifier changed.

https://github.com/electron-userland/electron-builder/blob/master/package.json

**What is the expected behavior?**

range specifier must be preserved.

**Please mention your node.js, yarn and operating system version.**

Nightly yarn, node 8, macOS.

**Comment by develar** [comment]
Related to #2367.

BTW — Yarn FTW! This flag will allow me to get rid of npm-check-updates module and rely only on Yarn. Thanks a lot.

**Comment by arcanis** [comment]
Thanks @develar ! If you don't mind I'll merge this issue with #2367 (my bad, I forgot this issue was already opened) 😃
