### ISSUE TITLE
Yarn Version returns fatal

### ISSUE THREAD

**Issue by khaosdoctor** [yarnpkg/yarn#3610]
**What is the current behavior?**
Running `yarn version` works ok until it executes `git add <thefullpathtomyrepo>`, then I get a "Fatal: <thefullpathtomyrepo>/package.json is outside repository"

Line: https://github.com/yarnpkg/yarn/blob/c1fe8a16c6c66d4c0fe7a0955b8432aa01a01587/src/cli/commands/version.js#L150

**If the current behavior is a bug, please provide the steps to reproduce.**
Checkout a repo, go into it, run `yarn version`

**What is the expected behavior?**

- Update version
- Create commit
- Commit
- Tag

**Please mention your node.js, yarn and operating system version.**
Node 8
NPM 5
Yarn 0.24
MacOSX Sierra

**Comment by BYK** [comment]
I'm assuming your repo doesn't have a `package.json` file in it?

**Comment by khaosdoctor** [comment]
No, it has. When I run the install command it works just fine

**Comment by rally25rs** [comment]
If you manually run `git add <thefullpathtomyrepo>` then I would expect Git to output the same error message. What is `<thefullpathtomyrepo>`? Is your Git repo set up in some non-standard way?

**Comment by khaosdoctor** [comment]
Let me give a more customized example.

I usually set all my repos on `~/Documents/Repositories`, so I created a new folder called `personal` inside it and then cloned one of my repos called `knoblr`, so the full path is `~/Documents/Repositories/Personal/knoblr`.

When I run `yarn version` (or `npm version`) it gives me this error. If I run `git add /Users/myuser/Documents/Repositories/Personal/knoblr/package.json` it outputs me the same error. I have to manually do `git add package.json` and things flow smoothly.

I think this is because git treats things relatively, so I think it would be better to run just `git add package.json` (or some relative path to it).

**Comment by BYK** [comment]
I couldn't find any git documentation around absolute paths and `add` but I think your assessment is correct.

So the solution then would be normalizing the path according to the git root and seems like we can get that easily by running `git rev-parse --show-toplevel`.

Sounds good? //cc @arcanis @bestander

**Comment by BYK** [comment]
@khaosdoctor can you let us know if you can run `git rev-parse --show-toplevel` and if #4038 fixes the problem for you"?

**Comment by khaosdoctor** [comment]
I tested it here, ran `git add $(git rev-parse --show-toplevel)/package.json` and got the same error. Tried again with Yarn 0.27 and same error too.

**Comment by BYK** [comment]
@khakulov that's not I meant :)

I meant just running `git rev-parse --show-toplevel` to see if it is supported by your git version. Seems like it is. And testing the PR meant actually checking out that version of yarn and trying it since it is not yet been merged.

That patch gets the git root and makes your `package.json` file path relative to that so it should work. Once @arcanis reviews it, I'll merge and you can test in the next Yarn release.

**Comment by khakulov** [comment]
@khaosdoctor

**Comment by BYK** [comment]
Hah, sorry @khakulov :)
