### ISSUE TITLE
Registry settings on .npmrc file being ignored

### ISSUE THREAD

**Issue by franzrecinos** [yarnpkg/yarn#3612]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Yarn fails to use registry specified in `.npmrc`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a project with a `package.json` and `.npmrc`
Add `@troveng/turbokit@0.3.31` to dependencies in `package.json`

Run yarn install

**What is the expected behavior?**
Yarn should install and use the registry settings from `.npmrc`.

**Please mention your node.js, yarn and operating system version.**
node = 6.9.5
yarn = 0.24.6
MacOS Sierra

We have some private repos. When doing `yarn install` some packages are not found because yarn is using the yarn registry and not npm's specified in the `.npmrc`. We can fix it via `yarn config set` commands. Is the expected behavior to have yarn config itself via `.npmrc` or we have to explicitly do it via cli?

**Comment by jhabdas** [comment]
@franzrecinos have you found any workarounds for this?

**Comment by franzrecinos** [comment]
@jhabdas We had to manually set the config already set on `.npmrc` like so:
`yarn config set registry https://registry.npmjs.org/`
`yarn config set @troveng:registry https://registry.npmjs.org/`
If yo do a `yarn config list` before and after you would see the change.

**Comment by lehni** [comment]
For the record: For those struggling with lerna and yarn, here is how I changed the registry for my organization scope:
```sh
yarn config set @SCOPE:registry https://registry.npmjs.org/
```

**Comment by paul-soporan** [comment]
Closing as in v2 we completely stopped reading `.npmrc` files.

https://yarnpkg.com/getting-started/migration
