### ISSUE TITLE
registry.yarnpkg.com returns 503

### ISSUE THREAD

**Issue by web-padawan** [yarnpkg/yarn#3615]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

```
yarn install v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types/node/-/node-4.2.6.tgz: Request failed \"503 Service Unavailable\"".
```
**Please mention your node.js, yarn and operating system version.**
```
node 6.11.0
yarn 0.24.6

**Comment by jotatoledo** [comment]
maybe related to #17117 in the npm repo

**Comment by web-padawan** [comment]
@jotatoledo I supposed so but was not suree. Thanks for explaration! Anyway, I think this should be closed now.
