### ISSUE TITLE
install fails - can't tell why

### ISSUE THREAD

**Issue by black-snow** [yarnpkg/yarn#3616]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
`yarn` will fail to install my deps, output:

```
Der Befehl "install-app-deps" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed with exit code 1.
```

(`install-app-deps` is a binary from [electron-builder](https://github.com/electron-userland/electron-builder) - all `bins` are missing 'cept for `semver` - see dev deps below)

**If the current behavior is a bug, please provide the steps to reproduce.**

Use a blank `package.json` and add those `devDependencies`, then run `yarn`:

```
"devDependencies": {
    "chai": "4.0.2",
    "devtron": "1.4.0",
    "electron": "1.6.10",
    "electron-builder": "18.6.2",
    "electron-devtools-installer": "2.2.0",
    "electron-mocha": "3.4.0",
    "gulp": "3.9.1",
    "gulp-batch": "1.0.5",
    "gulp-less": "3.3.0",
    "gulp-plumber": "1.1.0",
    "gulp-util": "3.0.8",
    "gulp-watch": "4.3.11",
    "istanbul": "0.4.5",
    "minimist": "1.2.0",
    "mocha": "3.4.2",
    "npm-check": "^5.4.4",
    "rollup": "0.42.0",
    "rollup-plugin-istanbul": "1.1.0",
    "source-map-support": "0.4.15",
    "spectron": "3.7.1"
  }
```

 -- note that it works when only having `electron-builder` as devDep --
 -- also note that `npm i --dev` runs just fine --

**What is the expected behavior?**
Dependencies should be installed correctly (with binaries).

**Please mention your node.js, yarn and operating system version.**
node v8.1.0
yarn 0.24.6
OS Win10 x64 Creators Update

**Comment by rally25rs** [comment]
Is there any error listed in the error log? 

This installs successfully for me on:

Yarn 0.24.6
Node 8.0.0
OSX Sierra

Unfortunately I don't have my Win10 Creators machine with me, but I can try it on there later. My guess is that it has something to do with building native dependencies.

**Comment by black-snow** [comment]
Works on my mac, too.

There's no additional error. Might be an misconfiguration in my PowerShell, though (NODE_ENV) - gonna give it another shot and report back.

**Comment by black-snow** [comment]
Alright. Since my console plugin in atom switched from `cmd` to `PowerShell` `NODE_ENV` wasn't set to `development` and thus most of my deps were missing.

**Comment by develar** [comment]
Yarn FTW. electron-builder will warn you if you still use unreliable, buggy and slow npm.
