### ISSUE TITLE
"yarn install --flat" freezes on nodejs 8

### ISSUE THREAD

**Issue by alexkieling** [yarnpkg/yarn#3618]
Bug found on yarn v0.26.1, node.js v8.1.0, and Fedora 25.

The `yarn install --flat` command freezes in the second question to choose a package version.

package.json attached.
[package.json.zip](https://github.com/yarnpkg/yarn/files/1064818/package.json.zip)

**Comment by alexkieling** [comment]
The same command works fine on node.js v6.11.0.

**Comment by bestander** [comment]
Should be fixed by latest Node https://github.com/yarnpkg/yarn/issues/3613
