### ISSUE TITLE
'yarn add' with a local node build fails to recognize node version

### ISSUE THREAD

**Issue by AnnaMag** [yarnpkg/yarn#3623]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
I built node from current master and experience issues installing dependencies with this '-pre' build.  Local executable is in the $PATH tagged as v9.0.0-pre. I set npm nodedir to the local build dir and, when installed via npm, dependencies are installed correctly. However, e.g.
```yarn add babel-eslint``` gives an error:
```error babel-eslint@7.1.1: The engine "node" is incompatible with this module. Expected version ">=4"```.
```yarn config list``` points correctly to the build dir and node/v9.0.0-pre.

babel-eslint is just an example, there are other libraries that fail.

**If the current behavior is a bug, please provide the steps to reproduce.**
build node from current master (e.g. ```make -j8```)
add executable to the $PATH
export npm_config_nodedir=... (local node build dir)
yarn add babel-eslint@7.1.1

**What is the expected behavior?**
Same as ```npm install babel-eslint```- recognizing node version correctly (e.g. >=4) for a local build of node, which is not one of the officially tagged releases.
**Please mention your node.js, yarn and operating system version.**
node: current master, yarn: 0.24.6, system: macOS Sierra

**Comment by rally25rs** [comment]
This is due to the way that npm-semver determines the match https://github.com/npm/node-semver

```
$ node
> const s = require('semver');
undefined
> s.satisfies('v9.0.0-pre', '>=4', false)
false
```

So according to semver, `9.0.0-pre` does not satisfy `>=4`.

From the docs here: https://github.com/npm/node-semver#prerelease-tags 

> ... prerelease versions frequently are updated very quickly, and contain many breaking changes that are (by the author's design) not yet fit for public consumption. Therefore, by default, they are excluded from range matching semantics.

-----

As a workaround, you can use the `--ignore-engines` flag.
