### ISSUE TITLE
`yarn remove package` doesn't trigger `preuninstall` and  `postuninstall` scripts

### ISSUE THREAD

**Issue by springuper** [yarnpkg/yarn#3628]
**What is the current behavior?**
there is a  `preuninstall` and `postuninstall` in my package.json:

```js
"scripts": {
  "preuninstall": "echo 'pre uninstall'",
  "postuninstall": "echo 'post uninstall'"
}
```

but `yarn remove package` doesn't trigger them:

```bash
$ yarn remove ignore-loader
yarn remove v0.26.1
[1/2] Removing module ignore-loader...
[2/2] Regenerating lockfile and installing missing dependencies...
warning "chai-enzyme@0.4.2" has incorrect peer dependency "cheerio@0.19.x || 0.20.x".
success Uninstalled packages.
Done in 33.05s.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

reproduce steps:

1. config `preuninstall` and `postuninstall` scripts in package.json
2. run `yarn remove package`
3. check stdout

**What is the expected behavior?**

`preuninstall` and `postuninstall` should be triggered like `yarn add package` triggers `preinstall` and `postinstall`.

**Please mention your node.js, yarn and operating system version.**

- nodejs: v6.9.1
- os: Mac OSX 10.12.4
- yarn: v0.26.1

**Comment by bestander** [comment]
It should be running those https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/remove.js#L68

**Comment by kaylieEB** [comment]
The scripts are relative to the package, so if I understand the original issue correctly, `yarn remove ignore-loader` should trigger the scripts for `ignore-loader` package, not the ones on your own `package.json`--those get triggered when your package gets removed. So I think this already works as expected.

**Comment by bestander** [comment]
Yeah, seems right

**Comment by stigi** [comment]
There's a workaround via the [postinstall-postinstall](https://www.npmjs.com/package/postinstall-postinstall) package, in case anyone stumbles across this years later... ;)

**Comment by kangax** [comment]
@stigi that package doesn't seem to work for me (using yarn 1.16.0); postuninstall is never triggered

**Comment by stigi** [comment]
@kangax True, only works for post install. It's called `postinstall-postinstall` not `postuninstall-postuninstall` 🤷‍♂️

But maybe this is a good pointer if you want to hack something together yourself: https://github.com/ds300/postinstall-postinstall/blob/master/run.js#L13

**Comment by kangax** [comment]
@stigi good point, I guess I'll just whip up postuninstall-postuninstall then 🙃

**Comment by jlurena** [comment]
> @kangax True, only works to call `postinstall` after `add` or `remove`. It's called `postinstall-postinstall` not `postuninstall-postuninstall` after all 🤷‍♂️

it doesn't work for `yarn remove` either
