### ISSUE TITLE
Child concurrency format not consistent with documentation

### ISSUE THREAD

**Issue by mohseenrm** [yarnpkg/yarn#3632]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Want to use three thread for installing dependencies
contents of current .yarnrc
```
child-concurrency 3
```
uses 3 threads. It shouldn't.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Create .yarnrc with given config
2) yarn install
3) Three threads run, installing dependencies.

**What is the expected behavior?**
Expected config for .yarnrc, according to docs [.yarnrc](https://yarnpkg.com/en/docs/yarnrc)
```
CHILD_CONCURRENCY 3
```
should use 3 threads. But it uses one.

**Please mention your node.js, yarn and operating system version.**
node@6.10.3
yarn@0.24.5
Mac OSX@10.12.5

**Comment by bestander** [comment]
CHILD_CONCURRENCY is the env variable that we support as well.
I think documentation needs to be updated.
@mohseenrm would you send a PR?

**Comment by mohseenrm** [comment]
Alright, I'll create a PR, just for clarity, I'll add 
```
child-concurrency #NUMBER#
```
as an optional config, right?

**Comment by bestander** [comment]
Yeah, just lower case it in the .yarnrc doc please.
Env var doc has a correct upper case notation.
