### ISSUE TITLE
Generate yarn.lock programmatically from package.json

### ISSUE THREAD

**Issue by rarkins** [yarnpkg/yarn#3634]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

It is necessary to run `yarn install` and download all packages in order to generate a `yarn.lock` file.

**What is the expected behavior?**

`yarn` can be required as a lib, with a function to return a `yarn.lock` if provided a `package.json`

**Please mention your node.js, yarn and operating system version.**

Flexible.

This is desirable for the [renovate](https://github.com/singapore/renovate) open source tool which is used to maintain and update `yarn.lock` files whenever npm dependencies are upgraded.

**Comment by rally25rs** [comment]
Duplicate #2465
