### ISSUE TITLE
yarn doesn't create all expected symlinks to bin

### ISSUE THREAD

**Issue by evilj0e** [yarnpkg/yarn#3641]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Installing of dependencies doesn't create symlinks to .bin for all dependencies with bin property in package.json

**If the current behavior is a bug, please provide the steps to reproduce.**
For example, install [eslint-plugin-react](https://github.com/evilj0e/eslint-plugin-react). It depends from eslint. Symlink for eslint should be created in .bin.

**What is the expected behavior?**
Symlinks for all dependecies with bin property in package.json should be created in bin.

**Please mention your node.js, yarn and operating system version.**
yarn v0.26.1
node v6.10.2

**Comment by evilj0e** [comment]
Feat @denchistyakov

**Comment by rally25rs** [comment]
`eslint-plugin-react` has a peerDependency on `eslint` but peer deps are not installed automatically

```
yarn install v0.26.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "eslint-plugin-react@7.1.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
Done in 0.73s.
```

Do you have `eslint` added to your project some other way? (does node_modules/eslint exist?)

**Comment by rally25rs** [comment]
@evilj0e I'm going to close this issue for now, since Yarn exhibits the same behavior as NPM (at least as far as I can tell).
If you have additional comments or still believe this is an issue, please comment with additional info and we can re-open this issue if needed.
Thanks!
