### ISSUE TITLE
Yarn doesn't create lockfile although it said it did

### ISSUE THREAD

**Issue by domoritz** [yarnpkg/yarn#3643]
Although yarn says that it saved a lockfile, it didn't. 

```
>>>> yarn
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
stuff
[2/4] 🚚  Fetching packages...
more stuff
success Saved lockfile.
✨  Done in 18.40s.
>>>> cat yarn.lock                                                                                                                                                                                           18.7s
cat: yarn.lock: No such file or directory
```

OS X 10.12.6
Node v8.1.2
NPM 5.0.3

**Comment by domoritz** [comment]
It's happening for example in https://github.com/vega/vega

**Comment by rally25rs** [comment]
I'm on OSX Sierra, Node 8.1.2, Yarn 0.24.6, tried to reproduce.

Since the `yarn.lock` file is already in your repo, I had to delete it after clone.

I end up getting an error in one of your tests:

```
$ yarn clone git@github.com:vega/vega.git
Cloning into 'vega'...
remote: Counting objects: 15571, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 15571 (delta 10), reused 13 (delta 3), pack-reused 15539
Receiving objects: 100% (15571/15571), 44.29 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (10772/10772), done.

$ cd vega/

$ rm yarn.lock

$ yarn
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning vega-loader > topojson > d3-geo-projection > brfs > static-module > through2 > xtend > object-keys@0.4.0:
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⡀ canvas: CXX(target) Release/obj.target/canvas/src/Canvas.o
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
warning Error running install script for optional dependency: "/Users/me/Projects/vega/node_modules/canvas: Command failed.\nExit code: 1
... more output omitted ...
success Saved lockfile.
$ npm run test && npm run build
... more output omitted ...
# tests 219
# pass  218
# fail  1
```

However the yarn.lock file is created for me:

```
$ head yarn.lock
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


acorn-jsx@^3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/acorn-jsx/-/acorn-jsx-3.0.1.tgz#afdf9488fb1ecefc8348f6fb22f464e32a58b36b"
  dependencies:
    acorn "^3.0.4"
```

-----

I'm curious if removing your `prebuild`, `build` and `postbuild` scripts from package.json fixes the issue for you. Maybe there is some weird issue with the way those scripts run? It's the only thing I can think of that is outside the ordinary.

**Comment by domoritz** [comment]
@rally25rs Thank you so much for looking into this. I just tried it again after temporarily removing all scripts from my `package.json`. Running yarn with `--verbose` didn't show anything useful. 

Btw, I'm seeing the same issue in a repo that depends on vega: https://github.com/vega/vega-lite.

**Comment by rally25rs** [comment]
Hmm, it always seems to work for me, which unfortunately puts me in the position of not being able to help debug it. Perhaps someone else can reproduce it in their environment.

If you have the time and motivation, you could also clone Yarn and use it to run your install and help debug into it. (I can give you the list of commands to build and run yarn from the cloned repo if you want).

**Comment by jharris4** [comment]
This is a duplicate of #3555

**Comment by domoritz** [comment]
Yes! Thank you @jharris4 for reproducing the issue.

**Comment by jharris4** [comment]
@domoritz I'm curious, are you able to reproduce it with the example package.json I attached?
