### ISSUE TITLE
yarn link: Couldn't find package "package-name" on the "npm" registry

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3645]
As reported in https://github.com/yarnpkg/yarn/issues/1214#issuecomment-303832748

I'm getting this issue on version 0.24.5.
I have some packages that i developed and they are not published on any server, they are just linked. 
My projects uses this linked packages and some published packages like express or bluebird.
when I try to run "yarn" to install all or a specific package it returns the error:
> error Couldn't find package "package-name" on the "npm" registry

steps to reproduce:

cd path/to/a-dev-package
yarn link
cd path/to/a/project
yarn link a-dev-package
yarn add bluebird
it returns : 
error Couldn't find package "a-dev-package" on the "npm" registry

**Comment by simonkberg** [comment]
Seems to be a dupe of this: https://github.com/yarnpkg/yarn/issues/2611

**Comment by bestander** [comment]
https://github.com/yarnpkg/yarn/issues/2611
