### ISSUE TITLE
Getting ECONNREFUSED and ETIMEOUT from yarn registry

### ISSUE THREAD

**Issue by thedrow** [yarnpkg/yarn#3647]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When I `yarn install` I consistently get ECONNECTIONREFUSED and ETIMEOUT from the registry.
**What is the expected behavior?**
I should be able to install packages using yarn
**Please mention your node.js, yarn and operating system version.**
node v8.1.0 and Ubuntu 17,04

**Comment by csvan** [comment]
Are you behind a proxy?

**Comment by thedrow** [comment]
No, I am not. This happened on multiple wifis. I can no longer reproduce it.
I thought I'd report this because something was wrong with either a CDN node (I'm from Israel) or the service itself.

When this happens, yarn stops at the 1st stage of the installation. I think there should be a retry logic instead.

**Comment by rally25rs** [comment]
Related: #2849

**Comment by bestander** [comment]
Thanks, @thedrow.
I don't think we can follow up with this one right now, probably it was a temporary network issue.

**Comment by thedrow** [comment]
No you probably can't. But #2849 should help with this.
