### ISSUE TITLE
how to hide the unuseful info

### ISSUE THREAD

**Issue by txiaocao** [yarnpkg/yarn#3649]
![image](https://user-images.githubusercontent.com/3929991/27220267-289f23b8-52b7-11e7-9926-25d0e6bee195.png)

**Comment by csvan** [comment]
This looks like an issue with your console, not yarn.

That said, you are probably looking for the `--silent` flag, see https://github.com/yarnpkg/yarn/pull/2420

Also please note that this is an issue tracker, not a support forum. Use StackOverflow for that, there is a `yarn`tag there.

**Comment by rally25rs** [comment]
Please fill out the issue template when submitting issues.
What version of Yarn, what OS, and what console are you using? We can't reproduce the issue unless we know what environment causes it.
Thanks for any additional info!
