### ISSUE TITLE
How did I get global install lists?

### ISSUE THREAD

**Issue by hangyangws** [yarnpkg/yarn#3651]
I can use `npm list -g` get the global npm list?

Due to yarn document, I use  `yarn global ls` ,but no use.
And `yarn list` just get packages in current file path ..

**Comment by csvan** [comment]
Dup: https://github.com/yarnpkg/yarn/issues/3142

**Comment by rally25rs** [comment]
What version of Yarn? (`yarn --version`)
`yarn global ls` should be fixed as of 0.24.2

**Comment by n06rin** [comment]
In my case, I need to type sudo -E before yarn command.
for example:
`$ sudo -E yarn global ls --depth=0`

**Comment by ahtashamabbasse** [comment]
`yarn global ls` is deprecated you can go with  `yarn global list`
