### ISSUE TITLE
postinstall doesn't trigger when running yarn again

### ISSUE THREAD

**Issue by tp4k** [yarnpkg/yarn#3653]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
when i run `yarn` first time postinstall executes, after this it does not
i have a dev dependency for `gulp-imagemin` it depends on `gifsicle` and `optipng-bin`
they got postinstall scripts and they are not found on the second time and later
got the same problem for `hogan-browser`
**If the current behavior is a bug, please provide the steps to reproduce.**
$ rm -rf node_modules && yarn
$ ls node_modules/optipng-bin/vendor/
optipng
$ yarn
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 6.54s.
$ ls node_modules/optipng-bin/vendor/
ls: node_modules/optipng-bin/vendor/: No such file or directory

**What is the expected behavior?**
run postinstall after each run
npm acts pretty fine
**Please mention your node.js, yarn and operating system version.**
$ node -v
v6.11.0
$ yarn --version
0.24.6
$ npm -v
3.10.10

**Comment by BYK** [comment]
I don't thinks this is still an issue so closing.
