### ISSUE TITLE
Display current Node.js version

### ISSUE THREAD

**Issue by crazy-max** [yarnpkg/yarn#3659]
Hi,

It would be nice to diplay the current Node.js version used by Yarn when we use the option `-V`.

Example:

```
$ yarn -V
yarn: 0.24.6
node.js: 6.11.0
```

Thanks!

**Comment by jhabdas** [comment]
Why would that be nice?

**Comment by crazy-max** [comment]
@jhabdas If several tools like [n](https://github.com/tj/n) are used to install multi version of Node.js and since Yarn requires Node.js, i think it would be interesting to have the version of Node.js for info.

**Comment by jhabdas** [comment]
What if Yarn didn't require Node?

**Comment by crazy-max** [comment]
@jhabdas It is ?

**Comment by jhabdas** [comment]
Heh. What does Node require? Should we print that too?

**Comment by crazy-max** [comment]
Ok forget it...

**Comment by jhabdas** [comment]
@crazy-max Just trying to understand the value of adding a feature that would cause individuals to have to parse the output of the `-V` flag. The reason I ask what seems like an obvious question above is because I've seen projects build on Node and then remove the Node dep entirely once they got on their feet. YMMV

**Comment by crazy-max** [comment]
@jhabdas Oh ok, thanks for this clarification, now it seems legit ;)

**Comment by jhabdas** [comment]
Thanks, hoss. 

> Btw, i don't know if there is a compatibility table with Node.js ?

Not sure. But since this project is still not at a 1.0 anything goes, really.

BTW looked at some of your repos. Cool stuff. Makes me want to do some gaming. 🎮
