### ISSUE TITLE
How can I disable emojis output by default ?

### ISSUE THREAD

**Issue by nodeyu** [yarnpkg/yarn#3660]
I am using:
macOS Sierra 10.12.5
node v8.1.2
yarn v0.24.5

When I pass '--no-emoji' flag to a command explicitly, it works.
![image](https://user-images.githubusercontent.com/16318438/27257644-97ed2882-5410-11e7-88d5-1cedd96c6fc6.png)

Then I tried config a default setting to my global `.yarnrc` file.
![image](https://user-images.githubusercontent.com/16318438/27257649-0a3ccff0-5411-11e7-91c1-144c11c85d6e.png)

But it doesn't works.
![image](https://user-images.githubusercontent.com/16318438/27257653-386ee43a-5411-11e7-8e21-65cb37bb1748.png)

So how can I disable emojis output by default setting ?

**Comment by jhabdas** [comment]
Perform an IoC on the CLI and pass flags every time.

**Comment by deecewan** [comment]
you could do `alias yarn="yarn --no-emoji"` in your `.profile`/`.bashrc`/`.zshrc`

**Comment by arcanis** [comment]
Or you can add `--no-emoji true` (or `--emoji false`) to your `.yarnrc` file.

**Comment by FDiskas** [comment]
@arcanis on old yarn version this will fail https://github.com/yarnpkg/yarn/issues/2009#issuecomment-327184993

**Comment by BYK** [comment]
@FDiskas we don't support this on older versions of yarn.

**Comment by FDiskas** [comment]
Newest version (Stable: v1.0.1) on windows looks like same error :o:

**Comment by BYK** [comment]
Looks like a missing feature to me: `yarn config set emoji false` 

Would you be interested in adding this in a PR?

**Comment by FDiskas** [comment]
For me it would be cool

**Comment by BYK** [comment]
If anyone is interested in a PR, I'd be more than happy to support the effort.

**Comment by olingern** [comment]
@BYK looks related to #4457 

I don't see disabling emoji support anywhere atm, so would you see this being:
- A global config
- flag
- both

?

**Comment by courajs** [comment]
@olingern thanks for pairing and showing me some yarn internals!

I think that precedence looks right.

There's one main hard part to this feature. The Reporter is what needs to know whether to show emoji or not, but it's instantiated before configuration is loaded ([here][reporter-init]), and actually is required for instantiating the `Config` object.
So we probably need to a) decouple these more somehow, b) do some state wrangling to update the reporter with emoji info after it's created, or c) read config info via some other mechanism for this option only.

There's also a small wrinkle in that right now commander is defaulting the emoji flag to true, unless `--emoji false` or `--no-emoji` are passed - we can't tell just from `commander.emoji` whether the user passed `--emoji true` or didn't specify the flag at all. I think it's pretty important to use the flag if it's passed, but fall back to config if not specified.

[reporter-init]: https://github.com/yarnpkg/yarn/blob/2c2b23eb546cfbc899401d29556d5de192e9ee4f/src/cli/index.js#L194

**Comment by BYK** [comment]
This should be fine on master now (latest nightlies or v1.1.0). Commander is pretty tricky so right now the "proper" way to do this is to pass `--emoji false` or `--emoji 0` either on the command line or in `.yarnrc`.
