### ISSUE TITLE
Cannot install the package named "optional" in offline mode

### ISSUE THREAD

**Issue by mchro** [yarnpkg/yarn#3661]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`yarn install --offline` with the package "optional" in the cache fails with
`error Can't make a request in offline mode`

**If the current behavior is a bug, please provide the steps to reproduce.**

In an empty new NPM project (`npm init`):
```
root@163d90d60c10:~/hest# yarn cache ls
yarn cache v0.24.5
Name Version Registry Resolved
Done in 0.07s.
root@163d90d60c10:~/hest# yarn add optional
yarn add v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
└─ optional@v0.1.3
Done in 1.39s.
root@163d90d60c10:~/hest# yarn list
yarn list v0.24.5
└─ optional@v0.1.3
Done in 0.29s.
root@163d90d60c10:~/hest# yarn cache ls
yarn cache v0.24.5
Name     Version Registry Resolved                                                                                           
optional v0.1.3  npm      https://registry.yarnpkg.com/optional/-/optional-0.1.3.tgz#f87537517b59a5e732cfd8f18e4f7eea7ab4761e
Done in 0.25s.
root@163d90d60c10:~/hest# rm -rf node_modules/
root@163d90d60c10:~/hest# yarn install --offline
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error Can't make a request in offline mode
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**
That `optional` is installed from the cache. This works for e.g. `async` on the same setup.

**Please mention your node.js, yarn and operating system version.**
Ubuntu 16.04, with Node installed from apt (version 4.2.6), Yarn installed by NPM (version 0.24.5).
Also reproducible with Node v6.11.0.

**Comment by mchro** [comment]
Debugging a bit further, the issue seems to be the "v" in the version field of `optional`'s package.json: "v0.1.3".

**Comment by jhabdas** [comment]
https://github.com/sindresorhus/semver-regex/issues/7#issuecomment-264404109

> `semver` package [clean() method](https://github.com/npm/node-semver/blob/d21444a0658224b152ce54965d02dbe0856afb84/semver.js#L265-L268) remove all equal and v characters on its regexp.

**Comment by bestander** [comment]
I think we could clean version when reading the manifest.
PR is welcome
