### ISSUE TITLE
'yarn add' fails to install from remote git#master, OK from git#(numbered branch or tag)

### ISSUE THREAD

**Issue by pgnd** [yarnpkg/yarn#3664]
**Before creating an issue please make sure you are using the latest version of yarn.**

@ https://github.com/yarnpkg/yarn/releases
	-> v0.26.1

```
yarn --version
	0.26.1
```

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

yarn fails to install from git master branch; ok with numbered branch/tag

**What is the expected behavior?**

yarn successful @ installing from git master branch

**If the current behavior is a bug, please provide the steps to reproduce.**
**Please mention your node.js, yarn and operating system version.**

```
node -v
	v8.1.2
yarn --version
	0.26.1
lsb_release -rd
	Description:    openSUSE Leap 42.2
	Release:        42.2
uname -rm
	4.11.6-2.ge566a4a-default x86_64
```

I'm attempting to install latest gulp via yarn.

Per https://yarnpkg.com/lang/en/docs/cli/add/

```
yarn add <git remote url>#<branch/commit/tag> installs a package from a remote git repository at specific git branch, git commit or git tag.
```

Exec fails to install master branch,

```
yarn add --dev  https://github.com/gulpjs/gulp.git#master
	yarn add v0.26.1
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
	info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	success Saved 1 new dependency.
	└─ gulp@3.9.1
	Done in 5.85s.
```

but works fine for older "4.0" branch/tag,

```
yarn add --dev  https://github.com/gulpjs/gulp.git#4.0
	yarn add v0.26.1
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
	info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	success Saved 1 new dependency.
	└─ gulp@4.0.0-alpha.2
	Done in 6.18s.
```

verifying

```
git clone https://github.com/gulpjs/gulp.git
cd gulp/
git branch -a
	* master
	  remotes/origin/4.0
	  remotes/origin/HEAD -> origin/master
	  remotes/origin/gfs-eval
	  remotes/origin/master
	  remotes/origin/new-docs

git tag
	3.4
	3.5
	3.7
	3.8
	v3.8.1
	v3.8.10
	v3.8.11
	v3.8.3
	v3.8.4
	v3.8.5
	v3.8.6
	v3.8.7
	v3.8.8
	v3.8.9
	v3.9.0
	v3.9.1
```

**Comment by arcanis** [comment]
I'm not sure I understand. 3.9.1 [is the version currently available on master](https://github.com/gulpjs/gulp/blob/master/package.json#L4), what is failing?

**Comment by pgnd** [comment]
ugh!  that explains it ...

I assumed -- wrongly -- that after 'all this time' that master WAS already >=4.0 branch.

my bad :-(
