### ISSUE TITLE
hide packages not listed in package.json from node_modules?

### ISSUE THREAD

**Issue by calidion** [yarnpkg/yarn#3668]
**Do you want to request a *feature* or report a *bug*?**
feature.

**What is the current behavior?**

node_modules is filled with numerous non direct dependent packages which make it very hard to locate packages.

**What is the expected behavior?**

node_modules only shows packages listed in package.json at the root directory.

**Please mention your node.js, yarn and operating system version.**

all versions.

**Comment by arcanis** [comment]
We can't really do that, that's the deduplication algorithm. If we remove it, you'll end up with the same package being copied a lot of time inside your dependency tree (could be an option, true).
