### ISSUE TITLE
Unable to find sdk tools in my android studio 2.3

### ISSUE THREAD

**Issue by anudeepr28** [yarnpkg/yarn#3669]
![screen shot 2017-06-19 at 5 08 33 pm](https://user-images.githubusercontent.com/8909945/27283461-08127214-5512-11e7-8d92-9289c81115b5.png)

**Comment by anudeepr28** [comment]
And in edit configuration...
![screen shot 2017-06-19 at 5 09 58 pm](https://user-images.githubusercontent.com/8909945/27283492-315edc70-5512-11e7-97e0-57a6ab690d75.png)

**Comment by arcanis** [comment]
Is this issue related to Yarn?
