### ISSUE TITLE
Yarn doesn't print script output when it contains yarn command

### ISSUE THREAD

**Issue by EddiG** [yarnpkg/yarn#3671]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If the `yarn` executes another `yarn` command in the script, then it does not print output of the executed `yarn` command.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/EddiG/issue-yarn-quiet.git
cd issue-yarn-quiet
yarn install
yarn run test
```
![screenshot from 2017-06-19 18-59-53](https://user-images.githubusercontent.com/4124316/27288881-8d77a6c2-5521-11e7-8217-9468533bc7bd.png)

**What is the expected behavior?**

Yarn should print the output like the `npm run test` does

![screenshot from 2017-06-19 19-00-08](https://user-images.githubusercontent.com/4124316/27288892-9514dd28-5521-11e7-983c-902696dfe3c3.png)

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v8.1.2

$ npm -v
5.0.1

$ yarn --version
0.26.1

$ lsb_release -d
Description:	Ubuntu 16.04.2 LTS
```

**In real life script would be like this**
```
scripts: {
"outdated:all": "lerna exec -- 'yarn outdated || true'"
}
```
This execute the `yarn outdated || true` command in each package of the monorepo package.

**Comment by arcanis** [comment]
Probably caused by #3536 - @kittens is there a way to force-disable the quiet mode?

**Comment by EddiG** [comment]
Thanks for guess @arcanis. 
```
  "scripts": {
    "test": "YARN_SILENT=0 yarn outdated || true"
  } 
```
With `YARN_SILENT=0` works as expected.
