### ISSUE TITLE
JUNE 20 ISSUES TRIAGE SESSION

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3676]
We'll use this task to coordinate triage session this Tuesday (20.06.2017).
See our previous session https://github.com/yarnpkg/yarn/issues/3258.

We need to add some order to the issues and are going to do our first group triage session.

Goals:
- Reduce the number of duplicated issues by grouping them by category first
- Close non actionable issues
- Prioritize important issues over the rest

What we are planning to do:
- categorize by issue type (bug, discussion)
- categorize bugs by phase (configuration, resolution, fetching, linking, scripts)
- label high priority issues
- label issues good for beginners
- close issues with no steps to reproduce them. Too many issues, too little time developers can spend on each, with no repro steps the issue will hang there for a long time

Below I'll post a few templates that we can use to keep the tone positive.

We can use this issue for coordination, I'll be moderating it to remove outdated comments.
Also we can coordinate in the chat https://discordapp.com/invite/yarnpkg (does not require registration)

**Comment by bestander** [comment]
Ok, GitHub is not really great at permissions granularity and so this is what we can do this time.

Mention me in a comment and I'll do the trick, e.g.

@bestander label bug, bug-resolution
@bestander duplicate #xxxx

We want to categorize issues by the phase of Yarn installation, increase visibility of high priority issues and increase visibility of good issues for beginners.

Also we want to close duplicates and incentivize the community members to provide steps to reproduce issues.

These are the tags we want to use
<img width="276" alt="screen shot 2017-04-28 at 3 38 09 pm" src="https://cloud.githubusercontent.com/assets/2121048/25533500/b7212bf0-2c28-11e7-97be-6a44bf63a770.png">
<img width="164" alt="screen shot 2017-04-28 at 3 37 22 pm" src="https://cloud.githubusercontent.com/assets/2121048/25533504/b871b5e2-2c28-11e7-8d8d-7f8320295e47.png">

**Comment by bestander** [comment]
Inviting everyone new as well as our regulars: @rally25rs, @gsklee, @torifat, @BYK, @arcanis.
Anyone who has time to give issue some developer eyes and understand if it is a duplicate or requires repro steps please join.

I'll start morning PDT.

**Comment by rally25rs** [comment]
Also if you hit any [bug-high-priority] bugs, consider adding them to the v1 project.

**Comment by rally25rs** [comment]
I'll try to triage page 12. Not sure how much time I'll have today though...

**Comment by bestander** [comment]
claiming #3612 - #3679

**Comment by bestander** [comment]
claiming #3566 - #3670

**Comment by bestander** [comment]
claiming #3488 - #3689

**Comment by bestander** [comment]
Good results - no more untriaged issues in May - June.
