### ISSUE TITLE
Extract loadConfig from YarnRegistry/NpmRegistry responsibility (reading .npmrc/.yarnrc configs)

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3683]
**Do you want to request a *feature* or report a *bug*?**
code improvement

YarnRegistry extends NpmRegistry.
YarnRegistry reads .yarnrc into config object and NpmRegistry reads .npmrc into config object.

In some cases YarnRegistry is used for requests in other NpmRegistry.
This makes it confusing to track down when settings are used from .npmrc and when from .yarnrc and this causes issues like https://github.com/yarnpkg/yarn/issues/3612

**Comment by bestander** [comment]
BTW if you want to make Yarn work better with .npmrc speak up and send a PR.

**Comment by yyjazsf** [comment]
I think:  when use yarn
`project's  .yarnrc` > `project's .npmrc` > `global .yarnrc` > `global .npmrc`

**Comment by yyjazsf** [comment]
This is also worth considering.
yarn only use .yarnc.
npm only use .npmrc
if someone use yarn, they should use yarn's file.  It's no friendly

**Comment by paul-soporan** [comment]
Closing as in v2 we've decided to only read `.yarnrc.yml` files.

https://yarnpkg.com/getting-started/migration
