### ISSUE TITLE
Add a `yarn browse pkg` command

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/yarn#3696]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

To go to a package detail page, you’d have to manually enter `open https://yarnpkg.com/en/package/whatever` instead of being able to do `yarn browse whatever`

**What is the expected behavior?**

`yarn browse whatever` opens <https://yarnpkg.com/en/package/whatever>  in your default browser.

**Comment by bestander** [comment]
This feature can be done by a standalone tool.
I think Yarn should focus on package management.

**Comment by Haroenv** [comment]
fish: 

```fish
function yarn-browse
  open https://yarnpkg.com/en/package/$argv[1]
end
```

bash: 

```bash
function yarn-browse { 
  open https://yarnpkg.com/en/package/$1
}
```

You can add these to you respective .profile

(for future reference)

**Comment by Daniel15** [comment]
For what it's worth, I think this would be a useful feature.

I registered a short domain for these - https://yarn.fyi/ will redirect (eg. https://yarn.fyi/react)

**Comment by neoziro** [comment]
This package does the job: https://github.com/sindresorhus/npm-home

**Comment by Daniel15** [comment]
@neoziro  - That will open the npm detail page, not the Yarn one.

**Comment by neoziro** [comment]
https://github.com/sindresorhus/npm-home/pull/3
