### ISSUE TITLE
webdriverio with phantomjs works fine with modules installed by `npm` not with yarn.

### ISSUE THREAD

**Issue by rycastaneda** [yarnpkg/yarn#3707]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
webdriverio with phantomjs works fine with modules installed by `npm` not with yarn.
I am running `./node_modules/.bin/wdio wdio.conf.js --suite sanity`

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a wdio conf and a normal spec file and begin testing with yarn and npm

**What is the expected behavior?**
should work with yarn modules
**Please mention your node.js, yarn and operating system version.**
nodejs: 6.10.2
yarn: 0.26.1
ubuntu

**Comment by bestander** [comment]
Thanks for reporting but it is not clear how to reproduce the issue.
Please describe the steps how to get the error.
I'll close the issue for now as I can't act on it.
