### ISSUE TITLE
Overriding Node LTS version when installing with Choco

### ISSUE THREAD

**Issue by nicostuhlfauth** [yarnpkg/yarn#3716]
I am running a Windows system with Node LTS version installed. Yesterday, I downloaded yarn using the choco package manager.

What happend?
Choco has overridden my existing nodejs installation and replaced it with node v8.

Expected behavior:
Recognize LTS version, do not override existing system without asking.

**Comment by Daniel15** [comment]
Did you install Node.js via Chocolatey or via some other mechanism?

**Comment by nicostuhlfauth** [comment]
@Daniel15 First I installed it using Chocolatey. The install itself worked, but my node LTS version has been replaced with node v8. So I needed to reinstall node LTS. Installing yarn with its default installer works pretty well. The Chocolatey installer seems not to be recognizing the already installed LTS version...

**Comment by nicostuhlfauth** [comment]
@Daniel15 Node.js has been installed using Chocolatey.

**Comment by ChrisStayte** [comment]
@nicostuhlfauth  Did  you find  a solution to this

**Comment by luy19** [comment]
Maybe it will help you.
`choco install yarn --ignore-dependencies`

**Comment by BYK** [comment]
Closing since this is not a Yarn issue.
