### ISSUE TITLE
Typo in .yarn-integrity property: "topLevelPatters"

### ISSUE THREAD

**Issue by uasi** [yarnpkg/yarn#3722]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**

- Run `yarn install` in an arbitrary project
- See `node_modules/.yarn-integrity`
- It is JSON and contains "topLevelPatters" property

**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone git@github.com:stevemao/left-pad.git
cd left-pad
yarn install
grep topLevelPatters node_modules/.yarn-integrity
```
**What is the expected behavior?**

`node_modules/.yarn-integrity` contains topLevelPatter<ins>n</ins>s property

**Please mention your node.js, yarn and operating system version.**

- yarn 0.24.6, yarn 0.27.0
- node 6.9.1
- macOS 10.12.5 (16F73)

**Comment by uasi** [comment]
I'm not absolutely sure but it seems that the property is not read anywhere, so it could be fixed by simply replacing `topLevelPatters` with `topLevelPatterns` in src/integrity-checker.js.

**Comment by bestander** [comment]
That is embarrassing :)
Thanks, sending a PR
