### ISSUE TITLE
not able to install current version of yarn

### ISSUE THREAD

**Issue by SDhalor** [yarnpkg/yarn#3725]
Somehow I am only getting 0.10 version of yarn after the installation though the current version is 0.24.5
And it does not even work properly.
I am using ubuntu 14.4 and node 6.10.2

**Comment by bestander** [comment]
Try other methods of installing Yarn https://yarnpkg.com/en/docs/install#linux-tab

**Comment by SDhalor** [comment]
This is exactly what i followed. I even tried npm install but nothing helps

**Comment by bestander** [comment]
Please copy the logs of installation from your console here
