### ISSUE TITLE
Consistency issue: why diff command -> ls in global and list in normal mode

### ISSUE THREAD

**Issue by sakivks** [yarnpkg/yarn#3727]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by bestander** [comment]
We are going away from shorthand commands.
Should be list everywhere

**Comment by sakivks** [comment]
That was the issue 
shorthand(ls) works but list doesn't work in global
![screen shot 2017-06-27 at 12 49 40 am](https://user-images.githubusercontent.com/9475630/27556336-cac9d368-5ad2-11e7-84e9-c7f10c617bd0.png)

**Comment by bestander** [comment]
This should be fixed in 0.26 https://github.com/yarnpkg/yarn/pull/3308
