### ISSUE TITLE
Latest tag is missing release versions (v0.26.0)

### ISSUE THREAD

**Issue by jaygorrell** [yarnpkg/yarn#3730]
We have builds scripts that pull the `latest` release .tar.gz but this started failing when v0.26.0 was promoted to latest with only an msi available. Any idea what happened here? I see that the new pre-releases have the .tar.gz files back so it seems only this version is missing them.

![screen shot 2017-06-26 at 10 51 52 am](https://user-images.githubusercontent.com/12174604/27545480-edcecad2-5a5d-11e7-862b-d8d88680bca7.png)

**Comment by bestander** [comment]
Thanks for reporting, I marked 0.26.0 as pre-release.

Looks like 0.26.0 was unsuccessful and it was fixed in 0.26.1.
We decided to fix a bunch of bugs and are going to make 0.27.1 as next stable.

**Comment by Daniel15** [comment]
@jaygorrell - If you want the latest version, please pull `https://yarnpkg.com/latest.tar.gz` in your scripts, rather than relying on the GitHub releases :)
