### ISSUE TITLE
`yarn install` fails on local .tgz dependencies.

### ISSUE THREAD

**Issue by madilks** [yarnpkg/yarn#3732]
Currently, when `yarn install` is run in a directory with a package.json that has a dependency on a local .tgz file, it fails to install. Instead of using the local file, it tries to get a remote version from registry.yarnpkg.com, even though one may not exist. Yarn should use the local .tgz file instead.

I was able to reproduce this bug with the following steps:

1. Create a new directory.
2. Create a package.json file inside this directory.
3. Inside the package.json, list a local .tgz dependency. (ie. "file:lib/abus-0.3.1.tgz")
4. Make sure the local .tgz file is at the correct relative path. (ie. newDirectory/lib/abus-0.3.1.tgz)
5. Open a command prompt at the new directory and run `yarn install`.

The expected behavior is that it finds the local .tgz file instead of trying to get a remote version from registry.yarnpkg.com. This is a regression and was working in older versions including yarn v0.19.1.

This issue was observed using the following:
Node version: 7.5.0
Platform: win32 x64
Yarn Version: 0.24.6 and 0.27.0 (it works fine on 0.19.1)

[yarn-error.txt](https://github.com/yarnpkg/yarn/files/1103177/yarn-error.txt)

**Comment by bestander** [comment]
This just got fixed yesterday https://github.com/yarnpkg/yarn/pull/3709.
Meanwhile try `file:./lib/abus-0.3.1.tgz`

**Comment by madilks** [comment]
Thanks for the fix. As you suggested, I pre-pended the .tgz path with "./" and it successfully found the file locally.
