### ISSUE TITLE
Yarn add fails with scoped packages

### ISSUE THREAD

**Issue by gergelyke** [yarnpkg/yarn#3736]
### Steps to reproduce

```bash
yarn add @risingstack/trace
```

It fails with:

```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error Couldn't find a package.json file in "/Users/gergelyke/Development/risingstack/trace/yarn-test/node_modules/@risingstack/event-loop-stats/node_modules/node-pre-gyp"
```

### Test environment

Node.js 8.1.2
Yarn 0.24.5
OSX Sierra

**Comment by jhabdas** [comment]
https://github.com/RisingStack/trace-nodejs/issues/144

**Comment by jhabdas** [comment]
Simplifying the problem, `yarn add node-pre-gyp` results in the dependency coming down without a `package.json` file and an unexpected, empty `node_modules` directory inside the installed package.

**Comment by jhabdas** [comment]
@gergelyke Thanks for open issues and cross-linking them. I'm seeing lots of upvotes already on the `trace` package. Have you been able to do any additional debugging?

**Note to triage:** Issue replicated under `yarn@0.27.0` as well.

**Comment by bestander** [comment]
Is it because `event-loop-stats` has a bundledDependency without a package.json?

**Comment by bestander** [comment]
Can repro this with 
```
yarn add @risingstack/event-loop-stats
```

**Comment by bestander** [comment]
Merging into https://github.com/yarnpkg/yarn/issues/886
