### ISSUE TITLE
Yarn does not install dependencies correctly for package 

### ISSUE THREAD

**Issue by evancarter-iex** [yarnpkg/yarn#3737]
**Do you want to request a *feature* or report a *bug*?**

Bug Report

**What is the current behavior?**

Yarn does not handle the dependencies for the Jade package properly.  It does not install "uglify-js" despite it clearly being listed in the dependencies section of the package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/pugjs/pug/tree/v1.x.x is the jade package. 

1) Add jade to your dependencies (yarn add jade)
2) Run yarn, yarn install --production
3) Notice that uglify-js is not included

**What is the expected behavior?**
Based on the dependencies listed here, https://github.com/pugjs/pug/blob/v1.x.x/package.json it uglify-js should be included in production

**Comment by jhabdas** [comment]
Under `0.27.0` ran `yarn add jade --production` and had no issues installing package.

**Comment by bestander** [comment]
Yep, can't repro either.
