### ISSUE TITLE
Yum repos and GPG keys not available

### ISSUE THREAD

**Issue by dschep** [yarnpkg/yarn#3746]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**
https://dl.yarnpkg.com/rpm/yarn.repo
and
https://dl.yarnpkg.com/rpm/pubkey.gpg

are intermittently returning 503 errors now, making yarn imposible to use in CI builds & deploys. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
curl https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo && yum install -y yarn
```

**What is the expected behavior?**
200 status with the real content

**Please mention your node.js, yarn and operating system version.**
```
[:~] $ node -v
v6.10.3
[:~] $ yarn --version
0.24.6
[:~] $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

seemed like releases or release-infra might make more sense for this issue, but they're disabled there.

**Comment by dschep** [comment]
Well, it works now. But maybe there should be a status.yarnpkg.org since yarn also provides a lot of infrastructure, not just a local piece of software.

**Comment by bestander** [comment]
cc @Daniel15, the master of GPG keys and stat pages

**Comment by Daniel15** [comment]
Hmm that's strange. It's likely that either GitHub Pages or CloudFlare were encountering issues. If you do see 503 errors again, it would be good to get the exact text of the error so we can report it to our providers.

> Well, it works now. But maybe there should be a status.yarnpkg.org since yarn also provides a lot of infrastructure, not just a local piece of software.

We do have https://status.yarnpkg.com/, however there are no known issues at the moment.

**Comment by Daniel15** [comment]
Wait, why are you using the RPM repo on Ubuntu?

**Comment by dschep** [comment]
doh. sorry that was from my box but the error was in CI which is running amazon linux, a rh derivative

**Comment by Daniel15** [comment]
Are you still seeing issues here, or can this be closed out?

**Comment by dschep** [comment]
Nope, issue is resolved. Thanks for the info, tho I would like to point out that the status page didn't' reflect this outage, which would be nice (we've added the RSS feed for it to our slack notifications).
