### ISSUE TITLE
a stable release?

### ISSUE THREAD

**Issue by bukzor** [yarnpkg/yarn#3748]
Currently yarn has six pre-release versions spanning three minor bumps.

 * v0.27.1 -- pre-release -- a day ago
 * v0.27.0 -- pre-release -- 5 days ago
 * v0.26.1 -- pre-release -- 21 days ago
 * v0.26.0 -- pre-release -- 22 days ago
 * v0.25.4 -- pre-release -- 27 days ago
 * v0.25.3 -- pre-release -- 32 days ago
 * v0.24.6 -- latest stable -- 36 days ago

Are these all *intended* to not be available via `yarn add` except with an explicit `yarn@v0.27.1`?
I see that there's a `pre-release` tag on the project, but `yarn add yarn@pre-release` gives the same behavior as `yarn add yarn@nonsense`.

If this isn't intentional, please mark some/all of these as stable releases.
If it is, what's the syntax to install the latest pre-release?

**Comment by bukzor** [comment]
These are stable releases as far as the yarn debian repository is concerned:
https://github.com/yarnpkg/releases/tree/gh-pages/debian/pool/main/y/yarn

So either the git releases are wrong or the debian packaging is.

**Comment by mridgway** [comment]
The tag for yarn in the npm registry is `rc`, not `pre-release`: `yarn add yarn@rc`.

**Comment by bukzor** [comment]
@mridgway: `yarn add yarn@rc` gives the same behavior as `yarn add yarn@nonsense`; it brings up a list of versions for me to choose among.

**Comment by bestander** [comment]
thanks

**Comment by bestander** [comment]
Thanks for raising, @bukzor.
Between 0.24.6 and 0.27.1 we have seen a few regressions that made us a bit cautious and not to promote them to stable yet.
Just give us 1-2 days to fix the last couple of regressions and make a 0.27.x stable release
