### ISSUE TITLE
Remove "yarn <command> <version>" and "Done in X" by default.

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#3754]
I believe there is little value in printing both of these lines by default, for every single Yarn command.

Could we hide them behind a `--verbose` flag?

**Comment by jdalton** [comment]
The `Done in X` feels out of place with commands like `yarn node`.

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
