### ISSUE TITLE
Cleanup release artifacts from having dist folder

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#3758]

**Comment by Daniel15** [comment]
I thought we already had a task for this, but I can't find it now.

**Comment by BYK** [comment]
Can we have more details about this? I'm gonna remove it from 1.0 blockers for now.

**Comment by Daniel15** [comment]
It means renaming the `dist` directory in the tarball to something more usable, like `yarn-v0.99.99`.

**Comment by BYK** [comment]
@Daniel15 do you wanna work on this still or are you okay if I take this on?

**Comment by Daniel15** [comment]
You can work on it if you like! Should be pretty simple.
