### ISSUE TITLE
💩💩💩💩 EMOJI STOPPED WORKING 💩💩💩💩

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3764]
caused by https://github.com/yarnpkg/yarn/pull/3126

<img width="291" alt="screen shot 2017-06-29 at 3 26 57 pm" src="https://user-images.githubusercontent.com/2121048/27713220-6bf30c6a-5cdf-11e7-8ccb-f8adfc875768.png">

**Comment by elyobo** [comment]
Sorry, was after emojis for all, not blocking them for darwin!
