### ISSUE TITLE
Running jest via `yarn run` breaks jest

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3767]
After updating to 0.27.3 Travis started failing tests https://travis-ci.org/yarnpkg/yarn/jobs/248542037.

This can be reproduced locally:

- install yarn@0.27.3
- yarn run jest

However running jest directly works

- ./node_modules/.bin/jest

**Comment by bestander** [comment]
Issue was introduced between 0.26 and 0.27

**Comment by bestander** [comment]
This PR broke the tests https://github.com/yarnpkg/yarn/pull/3536

**Comment by betalb** [comment]
Is it breaking only jest run? I have the same issue with grunt. Grunt is not referenced in script section of package json and I launch it using following command `yarn run -- <task name>`, it worked find in 0.24.6

**Comment by bestander** [comment]
If you add YARN_SILENT=0 in package.json similar to https://github.com/yarnpkg/yarn/issues/3770, does it fix for you?
Otherwise please share how exactly grunt got broken

**Comment by betalb** [comment]
Actually my issue is not solved be env variable, steps to reproduce below

* yarn init
* yarn add grunt
* yarn run grunt -- --version

**Expected result:**
```
yarn run v0.24.6
$ "C:\work\repos\repo\node_modules\.bin\grunt" --version
grunt-cli v1.2.0
grunt v1.0.1
Done in 0.51s.
```

**Actual result:**
```
yarn run v0.27.3
$ "C:\work\repos\repo\node_modules\.bin\grunt" "--version"
'C:\work\repos\repo\node_modules\.bin\grunt" "--version' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

adding dummy record to scripts, fixes the problem
```
"scripts": {
    "grunt": "grunt"
}
```

**Comment by bestander** [comment]
Looks like a Windows related bug, can't repro on Mac.
I don't think it is related to this task.
Could you please raise another issue?

**Comment by betalb** [comment]
sure
