### ISSUE TITLE
yarn --flat sees a version conflict where there is none

### ISSUE THREAD

**Issue by mxmul** [yarnpkg/yarn#3780]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn --flat` sees a version conflict where there is none (in >=0.27.0).

If I have package A that requires 'left-pad@>=1.0.1" and package B that requires both A and "left-pad@1.1.1", and install package B with `yarn --flat` there is a conflict.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/mxmul/yarn_flat_regression

**What is the expected behavior?**
yarn would choose the one version that satisfies the version constraints (1.1.1)

**Please mention your node.js, yarn and operating system version.**
`yarn@0.27.1` `node@5.11.0` `ubuntu@10.04`

**Comment by bestander** [comment]
Related to https://github.com/yarnpkg/yarn/issues/3778 and https://github.com/yarnpkg/rfcs/pull/68

**Comment by aij** [comment]
Yarn can see a conflict even when both dependencies resolve to the same version number:

`
info Unable to find a suitable version for "history", please choose one by typing one of the numbers below:
  1) "history@^3.0.0" which resolved to "3.3.0"
  2) "history@ccap/history#3.3.0-ccap1" which resolved to "3.3.0"
Answer?: 
`

Of course the code is actually different depending on whether it is fetched from NPM or from Gitlab.

In our case, NPM will happily use the Gitlab version to satisfy both dependencies. Should Yarn do the same?

Admittedly, this is a hacky way to get NPM to use our patched version of `history` within an unpatched `react-router`. The new `resolutions` feature in Yarn seems like a cleaner way to accomplish the same, albeit incompatible with NPM.

**Comment by aij** [comment]
Ugh, that's actually worse than I realized. Even though it's prompting, the answer is effectively ignored in my above example, since the call to `reporter.select` returns just the string `3.3.0` in either case.
