### ISSUE TITLE
`yarn list` shows devDependencies on a production install. 

### ISSUE THREAD

**Issue by pixelpax** [yarnpkg/yarn#3788]
I boot a production version of my container with a Dockerfile that includes commands

**Do you want to request a *feature* or report a *bug*?**
I believe this is a bug as I receive misleading information. 

**What is the current behavior?**
I have a container built from an image with the following in its Dockerfile
```
ENV NODE_ENV=production
COPY package.json .
RUN yarn install --quiet
```

I am expecting it to be building in production and ignoring devDependencies. It does so, and I can confirm this with `ls node_modules` however, when I do `yarn ls` I see devDependencies listed alongside. 

**If the current behavior is a bug, please provide the steps to reproduce.**
In your package.json: 
```
  "dependencies": {
    "express": "^4.15.3"
  },
  "devDependencies": {
    "nodemon": "^1.11.0"
  }

```
then do
`NODE_ENV=production; yarn; yarn list | grep nodemon;`
and note that nodemon is present in list, but not present in `node_modules`
**What is the expected behavior?**
In this way, yarn is showing me a list of packages which I don't actually have stored on my machine. Perhaps this is intentional because I also see a list of packages _before_ executing `yarn` to install my `package.json`. I would expect to look in my package.json if I wanted to see what packages _should_ be installed and to use `yarn list` to see what packages are _actually_ installed. This is also what I'm used to with `npm`.

**Please mention your node.js, yarn and operating system version.**
Using yarn v0.24.6 within a docker container (from node:6.11 official)

**Comment by gowthamgts** [comment]
@pixelpax Thanks for reporting this, I'm able to reproduce this in my local environment. Working on this.

**Comment by bestander** [comment]
@gowthamgts, that is great.
Go ahead, the list command source is here https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/list.js

**Comment by reznord** [comment]
Is this still open for a commit? If so, I'd like to take this and push a PR for this issue.

**Comment by gowthamgts** [comment]
Yes @reznord, I'm caught up with work, so would be great if you take this up.

**Comment by olingern** [comment]
Jumped in on this one, hope that's okay @reznord

**Comment by reznord** [comment]
It's fine :)
