### ISSUE TITLE
Installation Problem: Don't install node6 if node already installed

### ISSUE THREAD

**Issue by mattbishop** [yarnpkg/yarn#3799]
**Which operating system are you using:**
MacOS 10.12.5

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I am using MacPorts to install yarn. I also use NodeJS 8. I do not want to use node6.

However, yarn installs node6 even though `node` is on the path. Please consider searching for an existing `node` before installing one.

**Comment by Daniel15** [comment]
MacPorts is community maintained; it's not maintained by the Yarn team. You'll need to contact whoever maintains the Portfile for Yarn to make this change. See https://github.com/macports/macports-ports/blob/master/devel/yarn/Portfile
