### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by TheDeadCode** [yarnpkg/yarn#3802]
Using brew on macos latest

Error 525 Ray ID: 37846989ce13185e • 2017-07-02 20:39:03 UTC
SSL handshake failed

Seems to happen on certain edges
https://check-host.net/check-report/3424ac1kb5e

![CF](https://i.imgur.com/k20ZgHb.png)

```==> Upgrading yarn
==> Downloading https://yarnpkg.com/downloads/0.27.5/yarn-v0.27.5.tar.gz

curl: (22) The requested URL returned error: 525 Origin SSL Handshake Error
Error: Failed to download resource "yarn"
Download failed: https://yarnpkg.com/downloads/0.27.5/yarn-v0.27.5.tar.gz
```

**Comment by Daniel15** [comment]
That's strange... Looks like it's not happening any more. Have you seen this again?

**Comment by TheDeadCode** [comment]
Took a few hours to work again; Works now.
