### ISSUE TITLE
Add https://github.com/prettier/eslint-config-prettier to avoid future conflicts in eslint rules

### ISSUE THREAD

**Issue by voxsim** [yarnpkg/yarn#3808]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If we add an eslint rules that conflicts with prettier we need to turn off it.

**What is the expected behavior?**
Add https://github.com/prettier/eslint-config-prettier and forget about that :D 
When I tried the cli tool [prettier/eslint-config-prettier#cli-helper-tool](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) there are some problems: every yarn command put `yarn run v<version>` on top of the result of each command.. when I try to pipe with `eslint-config-prettier-check` it does not work as expected.

Just for info after adding https://github.com/prettier/eslint-config-prettier, i run it:

```
yarn run --json eslint -- --print-config .eslintrc | yarn run eslint-config-prettier-check
```

and the response is:
```
Failed to parse JSON:
Unexpected token { in JSON at position 120
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

because when I type

```
yarn run --json eslint -- --print-config .eslintrc
```

this is the result:

```
{"type":"command","data":"\"/Users/user/Projects/open-source/yarn/node_modules/.bin/eslint\" --print-config .eslintrc"}
{
  "globals": {
    "Array": false,
    "ArrayBuffer": false,
    "Boolean": false,
...
}
```

**Please mention your node.js, yarn and operating system version.**
Every version of yarn

Maybe this issue is trivial because I forget about one flag that can turn off the head.

**Comment by BYK** [comment]
Closing since this has been fixed with #3796.
