### ISSUE TITLE
Missing .bin folder as of 0.25.4

### ISSUE THREAD

**Issue by jleclanche** [yarnpkg/yarn#3812]
I use the following command to install some application (on vagrant):

`yarn install --modules-folder "$NODE_MODULES" --pure-lockfile --no-progress`

Where $NODE_MODULES is a couple of folders up.

This command no longer creates a .bin directory. After doing a regression test, it looks like it's being created just fine in **0.25.3**, but breaks in **0.25.4**.

If I am to believe the 0.25-stable branch, this is the only commit between the two versions:

https://github.com/yarnpkg/yarn/commit/0a104ee2deaaf27338f83543992026aa19935889

**Comment by domoritz** [comment]
Could that be related to https://github.com/yarnpkg/yarn/issues/3801?

**Comment by BYK** [comment]
I think #3792 would solve this. What do you think @domoritz and @jleclanche?

**Comment by BYK** [comment]
Merging into #3724. LMK if you think that's not the correct action.
