### ISSUE TITLE
error publishing scoped packages on windows

### ISSUE THREAD

**Issue by zackschuster** [yarnpkg/yarn#3813]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn publish throws an error for a scoped package. the package still publishes correctly (as far as i can tell), but creating a version commit/tag is left undone (and maybe other things i'm not aware of).

this was first observed after upgrading to 0.27.3 from 0.24.6, continuing through 0.27.5.

**If the current behavior is a bug, please provide the steps to reproduce.**
attempt to publish an already-published package (the codebase in question can be found [here](https://github.com/zackschuster/ng-app)).

**What is the expected behavior?**
no errors.

**Please mention your node.js, yarn and operating system version.**
node v8.1.3
yarn 0.27.5
windows 10

**Comment by zackschuster** [comment]
@bestander since you added the private registries label, i should note this is affecting a public scoped package on the npm registry, not a private one.

**Comment by bestander** [comment]
we use the same level related to scoped and private packages, but thanks for clarifying

**Comment by zackschuster** [comment]
this issue appears to be resolved with yarn@0.28.1.
