### ISSUE TITLE
Syncing Debian Repository http://dl.yarnpkg.com/debian/ 

### ISSUE THREAD

**Issue by maxdwit** [yarnpkg/yarn#3816]
**What is the current behavior?**
As in https://github.com/yarnpkg/yarn/issues/3044 the debian repo is not providing any files.
Sadly I couldn't see any fix in the triage chat that was attached.

```
 curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg
-----BEGIN PGP PUBLIC KEY BLOCK-----
```
Any request to the repo gives:
```
Fehl:9 https://dl.yarnpkg.com/debian stable InRelease
  Failed to connect to dl.yarnpkg.com port 443: Verbindungsaufbau abgelehnt
```
HTTP Error 403 

Tried both:  direct Internet access /  with a proxy.

**What is the expected behavior?**
No Error 403, but providing the content of the repository.

**Please mention your node.js, yarn and operating system version.**
Ubuntu 16.04 or debian 8 ( error persistent on both )

**Comment by Daniel15** [comment]
Hmm, it's working fine for me:
![](http://ss.dan.cx/2017/07/ConEmu_04-11.24.07.png)

Are you using a proxy at all? If so, maybe your proxy is throwing the error.

**Comment by maxdwit** [comment]
You are right. Put the machine into the void of the internet without a
proxy and it worked. Will verify what happend there. Thank you for your
help.

2017-07-04 20:25 GMT+02:00 Daniel Lo Nigro <notifications@github.com>:

**Comment by Daniel15** [comment]
No problem, feel free to let us know if you do see any other issues with Yarn in the future 😃 

Is it possible your proxy is blocking all SSL connections? Try accessing some other server that uses SSL via the proxy and see  if it works. As a workaround, you could use `http://dl.yarnpkg.com/` instead of `https`.
