### ISSUE TITLE
Save selected version from version prompt to package.json

### ISSUE THREAD

**Issue by Ionaru** [yarnpkg/yarn#3817]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn saves the entered version number to package.json, even if it did not exist and another version was selected from a list. This will make yarn prompt the user with the version list each time `yarn` is ran.

Example:
I run `yarn add typescript@99`. Version 99 does not exist, so Yarn will prompt me with a list of versions to choose from.
When I select 2.4.1 and hit enter, version 2.4.1 will be installed.
Yarn then outputs this message:
```
success Saved 1 new dependency.
└─ typescript@2.4.1
```
But yarn actually saved `"typescript": "99"` to package.json.

**What is the expected behavior?**
Yarn saves the selected version from the version prompt list to package.json.

**Please mention your node.js, yarn and operating system version.**
Node 6.11.0
Yarn 0.27.5
Kubuntu 17.04

**Comment by BYK** [comment]
I think this is a bug. Are you willing to submit a PR? :)

**Comment by Ionaru** [comment]
Willing, yes. Able, no.

I'm not familiar with the working and codebase of yarn, I did spent a few hours trying to work something out but I couldn't find a way to implement it without breaking the saving of git URLs and version patterns in the package.json file.

**Comment by BYK** [comment]
@Ionaru - no worries. I think I've found the place so gonna submit a PR. Thanks for the help!
