### ISSUE TITLE
Entries from 'yarn help' do not work

### ISSUE THREAD

**Issue by Ionaru** [yarnpkg/yarn#3819]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`yarn help` returns a list of commands, of which a few do not function.
Among them are `c`, `i`, `la`, `ll`, `r`, `t` and `v`

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn help`
Try `yarn <command>`, enter one of the commands mentioned above.

**What is the expected behavior?**
Either the commands work or they should be removed from the commands list.

**Please mention your node.js, yarn and operating system version.**
Node 6.11.0
Yarn 0.27.5
Kubuntu 17.04

**Comment by GAumala** [comment]
This was fixed a few days ago in #3706. I just tested latest commit from master and aliases like `c`, `i`, `la`, `ll`, `r`, `t`, and `v` are no longer listed.

**Comment by Ionaru** [comment]
Glad to hear it!
