### ISSUE TITLE
Can't able to deploy react native ios app to app store

### ISSUE THREAD

**Issue by anudeepr28** [yarnpkg/yarn#3828]
![screen shot 2017-07-05 at 11 07 00 am](https://user-images.githubusercontent.com/8909945/27850443-516a899e-6172-11e7-8dcd-004c07e33197.png)

**Comment by BYK** [comment]
Are you sure this is related to yarn?

If so, can you please provide more details about your project, package.json file and other details such as your yarn and node versions etc.

**Comment by BYK** [comment]
Closing due to lack of response.
