### ISSUE TITLE
Each time I try to publish it says I am not logged in??

### ISSUE THREAD

**Issue by binarykitchen** [yarnpkg/yarn#3830]
Happens on yarn v0.27.5 - each time I run a release procedure which has this command

$ yarn publish --new-version $VERSION

it prints following error

```
Logging to npm ...
Publishing to npm ...
error An unexpected error occurred: "https://registry.yarnpkg.com/videomail-client: You must be logged in to publish packages".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I don't understand. Why does it say I have to be logged in when that bash script just ran `yarn login` successfully before?

For reference, this is the release script I am using
https://github.com/binarykitchen/videomail-client/blob/develop/bin/release.sh

(as you can see, have commented out all yarn commands and am switching back to npm)

Any clues?

**Comment by BYK** [comment]
Merging into #3831. Sorry about the trouble :(
