### ISSUE TITLE
`406 Not Acceptable` when npm succeeds 

### ISSUE THREAD

**Issue by gatimus** [yarnpkg/yarn#3833]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn add http://prerelease.componentone.com/wijmo5/npm-images/C1Wijmo-Enterprise-Eval-System-5.20172.328.tgz`
results in
```
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "http://prerelease.componentone.com/wijmo5/npm-images/C1Wijmo-Enterprise-Eval-System-5.20172.328.tgz: Request failed \"406 Not Acceptable\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\User\\Source\\yarn-test\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add http://prerelease.componentone.com/wijmo5/npm-images/C1Wijmo-Enterprise-Eval-System-5.20172.328.tgz`

**What is the expected behavior?**
install wijmo package like

`npm install http://prerelease.componentone.com/wijmo5/npm-images/C1Wijmo-Enterprise-Eval-System-5.20172.328.tgz`
```
npm notice created a lockfile as package-lock.json. You should commit this file.
+ wijmo@5.20172.328
added 1 package in 0.883s
```

**Please mention your node.js, yarn and operating system version.**
Yarn version: 
  0.27.5

Node version: 
  8.1.3

Platform: 
  win32 x64

**Comment by Daniel15** [comment]
It'd be worth trying this out with a debugging proxy to see what the difference between npm and Yarn is. It's possible the server is discriminating based on User-Agent and blocking Yarn for some reason.

**Comment by gatimus** [comment]
I can't seem to get Fiddler to proxy `npm` but here are the results of the yarn attempt.

Request
```
GET http://prerelease.componentone.com/wijmo5/npm-images/C1Wijmo-Enterprise-Eval-System-5.20172.328.tgz HTTP/1.1
User-Agent: yarn/0.27.5 npm/? node/v8.1.3 win32 x64
Accept: application/octet-stream
Accept-Encoding: gzip
host: prerelease.componentone.com
Connection: keep-alive


```

Response
```
HTTP/1.1 406 Not Acceptable
Content-Length: 1713
Content-Type: text/html
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
Date: Wed, 05 Jul 2017 22:39:38 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>The resource cannot be displayed</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<STYLE type="text/css">
  BODY { font: 8pt/12pt verdana }
  H1 { font: 13pt/15pt verdana }
  H2 { font: 8pt/12pt verdana }
  A:link { color: red }
  A:visited { color: maroon }
</STYLE>
</HEAD><BODY><TABLE width=500 border=0 cellspacing=10><TR><TD>

<h1>The resource cannot be displayed</h1>
The page you are looking for cannot be opened by your browser because it has a file name extension that your browser does not accept.
<hr>
<p>Please try the following:</p>
<ul>
<li>Change the Multipurpose Internet Mail Extensions (MIME) or security settings of your browser to accept the file name extension of the requested page. Note that your browser might currently be configured in a highly secure mode that protects your computer. Please read the Help for your browser before changing any settings.</li>
</ul>
<h2>HTTP Error 406 - Client browser does not accept the MIME type of the requested page.<br>Internet Information Services (IIS)</h2>
<hr>
<p>Technical Information (for support personnel)</p>
<ul>
<li>Go to <a href="http://go.microsoft.com/fwlink/?linkid=8180">Microsoft Product Support Services</a> and perform a title search for the words <b>HTTP</b> and <b>406</b>.</li>
<li>Open <b>IIS Help</b>, which is accessible in IIS Manager (inetmgr),
 and search for topics titled <b>Setting Application Mappings</b>, <b>Securing Your Site with Web Site Permissions</b>, and <b>About Custom Error Messages</b>.</li>
</ul>

</TD></TR></TABLE></BODY></HTML>

```

**Comment by Daniel15** [comment]
Looks like it's the `Accept: application/octet-stream` header that's doing it. It works fine if I remove that header, or if I change it to `Accept: application/octet-stream, application/x-tar`. It'd be worth seeing what npm is sending for the `Accept` header.

**Comment by gatimus** [comment]
I agree it'd be worth seeing what npm sets for the `Accept` header but I'm having trouble getting FIddler to debug npm traffic currently. 

I did some searching and it seems there are many MIME types for tarballs so the request header could be along the lines of `Accept: application/octet-stream, application/gzip, application/x-gzip, application/x-gtar, application/x-tgz, application/tar, application/x-tar, application/x-compressed`

**Comment by Daniel15** [comment]
@bestander Do you know why we even have an `Accept: application/octet-stream` header? I don't think we really need to discriminate based on content-type. We might be able to just remove that header altogether.

**Comment by bestander** [comment]
Nope, that dates before Sep 2016 https://github.com/yarnpkg/yarn/commit/5300b482c851e2578ac1f3aa4908be4d0289dca8

**Comment by ddeath** [comment]
I am getting the same error with https://github.com/mjmlio/mjml/tree/4.0.0-alpha.3

**Comment by buu700** [comment]
I'm getting this in Yarn 1.0 from the package.json dependency `"webrtcsupport": "https://github.com/buu700/webrtcsupport"`.

**Comment by BYK** [comment]
>I'm getting this in Yarn 1.0 from the package.json dependency "webrtcsupport": "https://github.com/buu700/webrtcsupport".

I can't reproduce this one. The original issue is still there though.
