### ISSUE TITLE
Yarn outdated fails when workspaces enabled

### ISSUE THREAD

**Issue by LukeTillman** [yarnpkg/yarn#3859]
**Do you want to request a *feature* or report a *bug*?**
Bug. I didn't see anything in the existing plan for rolling out the workspaces feature that talked about the `outdated` command, so I'm going to assume this is a bug and not a "plan to support in a later stage".

**What is the current behavior?**
In a repository with the new workspaces feature enabled, `yarn outdated` always exits with the error message:  _Outdated lockfile. Please run `yarn install` and try again._

```
λ yarn outdated
yarn outdated v0.27.5
error Outdated lockfile. Please run `yarn install` and try again.
info Visit https://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a minimal repository for reproducing here:

https://github.com/LukeTillman/yarn-outdated-bug

It doesn't require any dependencies be installed in any of the `package.json` files in order to trigger the error.

**What is the expected behavior?**
Yarn should list outdated packages.

**Please mention your node.js, yarn and operating system version.**
Node.js 8.1.2, Yarn 0.27.5, Windows 10

I'm pretty sure this is similar to #3841 and related to the virtual manifest dependency that's part of the workspaces code.

**Comment by Bnaya** [comment]
FYI: `yarn why` is also failing with the same error

**Comment by ericanderson** [comment]
@arcanis @byk this seems to be a problem for me on 1.0.0

**Comment by BYK** [comment]
@ericanderson can you file a new issue with some more details so we can investigate?

**Comment by BYK** [comment]
>@ericanderson can you file a new issue with some more details so we can investigate?

Requesting this since I can't reproduce the original error.

**Comment by BYK** [comment]
Oh, nvm, just saw #4328.
