### ISSUE TITLE
Yarn cannot install socket.io but npm succeeds

### ISSUE THREAD

**Issue by SrihariThalla** [yarnpkg/yarn#3867]
### **Do you want to report a *bug*?**
Yes, it's an issue and might be a bug. Thanks!

### **What is the current behavior?**
Yarn get stuck while installing `socket.io`. But it succeeds with npm!

It downloads `node-sass` and then is stuck with indefinite lines with "waiting..." stays on the screen.

```
[1/4] ⠂ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-48_binding.node
```

### **If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add socket.io` is just the command.

### **Please mention your node.js, yarn and operating system version.**

- Node v6.11.0
- npm 5.0.3
- Yarn v0.27.5
- System Version: macOS 10.12.5 (16F73)
- Kernel Version: Darwin 16.6.0

Thanks again!

**Comment by arcanis** [comment]
Hey @SrihariThalla!

Small remark, `node-sass` (a CSS-like language) isn't related to `socket.io` (a networking library).

Anyway, the line you've quoted (`Downloading binary ...`) is printed by node-sass itself, when it downloads its own binaries from github. If this command hangs, Yarn itself is not responsible, your network probably is.

**Comment by SrihariThalla** [comment]
Hi, @arcanis!

Yes, I've tried multiple times for the past few days and the installation hangs right after this download!

I'll post the issue on `socket.io` and will try to get more info about it.

Thanks for the help!
