### ISSUE TITLE
install phantomjs-prebuilt too long

### ISSUE THREAD

**Issue by Hal-pan** [yarnpkg/yarn#3878]
yarn :0.27.5
node: 8.1.3
npm:5.1.0
macOS:10.12.5 
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**

> yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/2] ⡀ waiting...
[2/2] ⡀ phantomjs-prebuilt: Receiving...
[-/2] ⡀ waiting...
[-/2] ⡀ waiting...
[-/2] ⡀ waiting...

One morning, still no installation finished

**Comment by arcanis** [comment]
PhantomJS downloads itself, Yarn is not involved into fetching these binaries.
