### ISSUE TITLE
Bug: linking at different directory depths causes broken links

### ISSUE THREAD

**Issue by bryanlarsen** [yarnpkg/yarn#3888]
yarn 0.27.5
node 8.1.3
Ubuntu 16.04

I'm trying to use the new "link:" type.   It fails for me when modules are attached at different depths in the directory tree.

To reproduce:

```sh
mkdir hub
mkdir hub/a
cd hub/a/
yarn init -y
cd ..
mkdir foo
cd foo
yarn init -y
yarn add a@link:../a
cd ../..
mkdir th
cd th
yarn init -y
yarn add foo@link:../hub/foo
```

Notice now that th/node_modules/a is a broken link

So let's try creating an explicit dependency first

```sh
mkdir hub
mkdir hub/z
cd hub/z/
yarn init -y
cd ..
mkdir foo
cd foo
yarn init -y
yarn add z@link:../z
cd ../..
mkdir th
cd th
yarn init -y
yarn add z@link:../z
yarn add foo@link:../hub/foo
```

th/node_modules/z is a broken link.  Note that behaviour is different if you use package name 'a' rather than 'z'.   I suspect that's because ../a sorts before ../hub/a and ../z sorts after ../hub/z in yarn.lock.

**Comment by bryanlarsen** [comment]
Sorry for reporting against 0.27.5; I started this on Friday.   Testing against 0.28.1, the first clause appears to work but the second one still fails.

**Comment by arcanis** [comment]
Hi @bryanlarsen!

I've used the following testcase, which is essentially yours with some reformatting to make it easier to keep track of the current working directory:

```bash
LETTER=a

(
    mkdir -p hub/$LETTER && cd hub/$LETTER
    ~/yarn/bin/yarn init -y
)

(
    mkdir hub/foo && cd hub/foo
    ~/yarn/bin/yarn init -y
    ~/yarn/bin/yarn add $LETTER@link:../$LETTER
)

(
    mkdir -p th && cd th
    ~/yarn/bin/yarn init -y
    ~/yarn/bin/yarn add $LETTER@link:../$LETTER
    ~/yarn/bin/yarn add foo@link:../hub/foo
)

ls -l --color=always th/node_modules
stat -L th/node_modules/$LETTER

rm -rf hub th
```

However, I'm not sure I see what's wrong in the output: the `th/node_modules/z` symlink is indeed broken, but only because you're referencing `../z` instead of `../hub/z` (like you do in the final line of your testcase). If you fix this, everything seems to be fine.

I might have misunderstood your issue so please feel free to correct me :)

**Comment by arcanis** [comment]
Ping?

**Comment by bryanlarsen** [comment]
Hmm, yes, I suspect you're right.   I don't have the original code I extracted the test case from any more.   We bit the bullet and switched to workspaces so that we only have a single node_modules tree and that seems to have cleaned up some of these niggling issues we've been having.
