### ISSUE TITLE
Yarn does not turns last published verison latest

### ISSUE THREAD

**Issue by Gozala** [yarnpkg/yarn#3908]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

Currently if I make a minor update say change package version from `0.2.0 -> 0.2.1` and then do `yarn publish` I expect that latest version of my package will appear to be `0.2.1` but instead it appears to be `0.2.0` even though `0.2.1` is listed under versions:

![image](https://user-images.githubusercontent.com/21236/28081440-1c2e840e-6624-11e7-90fc-2e0732124409.png)

If I do same thing with npm latest version appears to be as expected `0.2.1`.

**Please mention your node.js, yarn and operating system version.**

```sh
> yarn --version
0.24.6
> node --version
v7.10.0
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G23a
```

**Comment by BYK** [comment]
This may be a caching thing on yarnpkg/website

@Daniel15, thoughts?

**Comment by Daniel15** [comment]
This data all comes from Algolia's index, maybe there's a bit of a lag before it updates? cc @Haroenv

**Comment by Haroenv** [comment]
That's odd, I didn't see this kind of change before. The weird thing is that the "versions" is updated on the website, but the current version wasn't. In any case, it has 0.3.0 as its version now, there aren't really any tools for me to see the history except logs, so I'm not sure what the cause of that is, and if it affects other libraries...

**Comment by Haroenv** [comment]
Can’t replicate this. Would love to see a reproducible example if this happens again. If that happens please open an issue on https://github.com/yarnpkg/website
