### ISSUE TITLE
yarn check reports errors after install succeeds

### ISSUE THREAD

**Issue by haines** [yarnpkg/yarn#3916]
**Do you want to request a *feature* or report a *bug*?**
Report a bug 🐛 

**What is the current behavior?**
`yarn check` reports errors after a fresh and seemingly correct install.

**If the current behavior is a bug, please provide the steps to reproduce.**
Distilled from webpack/webpack#5262:

``` console
$ yarn init --yes
$ yarn add eslint@3.19.0 webpack@3.2.0
$ yarn check
yarn check v0.27.5
error "ajv" is wrong version: expected "4.11.8", got "5.2.2"
error "webpack#ajv" not installed
warning "chokidar#fsevents#node-pre-gyp@^0.6.36" could be deduped from "0.6.36" to "node-pre-gyp@0.6.36"
error Found 2 errors.
```

**What is the expected behavior?**
`yarn check` does not report errors.

It appears the problem is that `webpack@3.2.0` depends on `ajv@^5.1.5` and transitively on `ajv@^4.9.1`, while `eslint@3.19.0` transitively depends on `ajv@^4.7.0`.

```console
$ yarn why ajv
info Has been hoisted to "ajv"
info Reasons this module exists
   - "eslint#table" depends on it
   - "webpack#watchpack#chokidar#fsevents#node-pre-gyp#request#har-validator" depends on it
```

The install appears correct, though; yarn.lock contains two resolved versions for ajv:

```
ajv@^4.7.0, ajv@^4.9.1:
  version "4.11.8"

ajv@^5.1.5:
  version "5.2.2"
```

`ajv@5.2.2` is installed in `node_modules`:

```console
$ jq .version node_modules/ajv/package.json
"5.2.2"
```

`ajv@4.11.8` is installed in `node_modules/har-validator/node_modules` and `node_modules/table/node_modules`:

```console
$ jq .version node_modules/har-validator/node_modules/ajv/package.json
"4.11.8"
$ jq .version node_modules/table/node_modules/ajv/package.json
"4.11.8"
```

The transitive aspect appears to be key,
```console
$ yarn add table@3.8.3 webpack@3.2.0
```
does not cause this error; interestingly, it installs `ajv@4.11.8` to `node_modules` and `ajv@5.2.2` to `node_modules/webpack/node_modules`.

**Please mention your node.js, yarn and operating system version.**
Node 6.10.3
Yarn 0.27.5
Mac OS X 10.12.5

**Comment by CrabDude** [comment]
Recommend closing this in favor of #3933, which contains a generalized reproduction (not specific to `webpack`) and a lengthy explanation of the rationale for treating `peerDependencies` as `npm` does.

**Comment by haines** [comment]
Closing in favour of #3933
