### ISSUE TITLE
"yarn run watch" stops watching

### ISSUE THREAD

**Issue by jirehstudios** [yarnpkg/yarn#3918]
I am using Laravel 5.4 with the included webpack setup and Yarn 0.27.5.

My issue is that when I run `yarn run watch` it only watches the file once. If I make a change on a JS file and save it I can see the change right away after I refresh the browser. But after that, any new changes don't get compiled so it renders watch useless and instead I might as well run `yarn run dev` continously. I get the same issue whether I use `.babel()` or `.scripts()` in my `webpack` file.

**EDIT:** I am running the web app in a Docker container but the same issue happens whether I run the command inside or outside (on the host) the container.

**Comment by Rubemlrm** [comment]
That happens with npm too , i think this is related with the modue that watch changes in the windows filesytem and not relatd to yarn or npm.

**Comment by jirehstudios** [comment]
@Rubemlrm I am running this on my Xubuntu 16.04 laptop, not Windows. running the command inside a docker container and outside does the same thing.

**Comment by Rubemlrm** [comment]
@jirehstudios can you try run the watch-poll ? just to check what happens. In a few hours i can try on my home laptop to check if this happens with debian system too. But this is a know issue on Windows and npm/webmix.

**Comment by jirehstudios** [comment]
@Rubemlrm Using `watch-poll` didn't help either. Am I just gonna have to live with it?

**Comment by Rubemlrm** [comment]
I think you should report this on webpack or laravel-mix repository.since this problem happens with npm/yarn. And i saw other People report the same problem on stackoverflow 

_Sent from my HUAWEI HONOR-7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jirehstudios** [comment]
@Rubemlrm Will do, thanks.

**Comment by sbarbosa115** [comment]
To me yarn run watch-poll worked pretty well.
