### ISSUE TITLE
manually inserting tar.gz to offline repo?

### ISSUE THREAD

**Issue by gotenxds** [yarnpkg/yarn#3919]
Hi, My team and I are in an isolated network and we can only insert new data via dok or discs so I cant use 
`yarn add` to add new files to the offline repo, I tried just putting a new file in the offline repo directory but yarn does not recognize it...

for example I had a package named `x` in version 1.2 in the offline repo dir.
having it in the package.json and using `yarn install` works

Now I inserted a new version via dok, lets say 1.3.
I've moved it to the offline repo dir, right next to the 1.2 file.

changed the package.json file to use the new version.
using `yarn upgrade` just gives me an error "offline cache does not have an 1.3 version"
I figured yarn upgrade does not work with the offline repo, so I removed node_modules and the yarn.lock file

`yarn install` same error.
I tried to remove the local cache using `yarn cache clean` and the `yarn install` same error.

Am I doing something wrong ?

**Comment by BYK** [comment]
This is because the resolutions cannot be added to the lockfile. I think the best course of action would be to place the packages in yarn's cache directory and use the `--offline` flag when installing.

Closing the issue now but please reopen if this doesn't work.
