### ISSUE TITLE
yarn doesn't use .npmrc from $HOME when run as root

### ISSUE THREAD

**Issue by also** [yarnpkg/yarn#3920]
**Do you want to request a *feature* or report a *bug*?**

Bug; incompatibility with npm.

**What is the current behavior?**

When run as  the `root` user on Linux, yarn does not use `$HOME/.npmrc` but uses `/usr/local/share/.npmrc` instead.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/yarnpkg/yarn/blob/v0.28.2/src/util/user-home-dir.js#L8
https://github.com/yarnpkg/yarn/blob/v0.28.2/src/registries/npm-registry.js#L132

Run `yarn config list --verbose` as root on Linux (while not in any subdirectory of`$HOME`) and observe that yarn looks for `.npmrc` first in the current directory, then in `/usr/local/share/`, but never in `$HOME` (`/root`).

**What is the expected behavior?**

Yarn defaults to `$HOME/.npmrc` as [documented by npm](https://docs.npmjs.com/files/npmrc#per-user-config-file).

A module named `user-home-dir` doesn't export a string which isn't the user's home directory.

**Please mention your node.js, yarn and operating system version.**

yarn v0.27.5
node v8.1.3

**Comment by dylanfoster** [comment]
It looks it doesn't use `./.npmrc` either. I had to downgrade to get it to work

**Comment by vinicius73** [comment]
Same problem here

![image](https://user-images.githubusercontent.com/1561347/28141208-f9015fec-6731-11e7-8e62-90d13d275143.png)

**Comment by BYK** [comment]
Thanks for reporting. Anyone willing to submit a PR for this?

**Comment by BYK** [comment]
@kaylieEB still working on this?

**Comment by kaylieEB** [comment]
hey @BYK sorry for the delay, here it is :) https://github.com/yarnpkg/yarn/pull/4047

**Comment by BYK** [comment]
@kaylieEB no worries, just wanted to make sure to avoid duplicate work :)

**Comment by Jessevanbekkum** [comment]
We also had this problem, and we were able to solve it by placing the `.npmrc` in the directory next to the git repository (one directory up from the source dir). Then yarn was able to pick up the `.npmrc`. Not a pretty solution, but it worked

**Comment by BYK** [comment]
Oh, looks like we forgot to close this. This is fixed on master.
