### ISSUE TITLE
Yarn publish package failed

### ISSUE THREAD

**Issue by bchoddny** [yarnpkg/yarn#3927]
Reporting a bug. I'm trying to publish a new package, that doesn't exist in private npm registry. When publishing package to our private nexus registry, getting an error

$ yarn publish --new-version 2.0.1 --verbose

**What is the current behavior?**
.....
verbose 6.241 Request <url> finished with status code 201.
success Logged in.
[3/4] Publishing...
verbose 6.578 Performing "PUT" request to <url>.
verbose 14.607 Request  <url> finished with status code 502.
verbose 14.609 Error: Couldn't publish package.
    at MessageError (/Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/errors.js:8:5)
    at /Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/cli/commands/publish.js:96:13
    at next (native)
    at step (/Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
error Couldn't publish package.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the command 
$yarn publish --new-version 2.0.1 --verbose

**What is the expected behavior?**
Successfully publish package
**Please mention your node.js, yarn and operating system version.**
node 6.9.4
yarn 0.27.2
mac os x EL Captain 10.11.3
NPM Registry: Nexus 3 NPM Registy
Using .yarnrc file for registry setting

**Comment by bchoddny** [comment]
My fault, I was try to publish the package to hosted nexus group repository instead of private repository.

**Comment by gouzhiyuan** [comment]
@bchoddny  how to set nexus repository?
