### ISSUE TITLE
Cannot install packages due to node engine error

### ISSUE THREAD

**Issue by mrchief** [yarnpkg/yarn#3930]
**Do you want to request a *feature* or report a *bug*?**

*bug*
**What is the current behavior?**
installation fails with error:

```
λ yarn add koa-webpack-hot-middleware
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error koa-static@4.0.1: The engine "node" is incompatible with this module. Expected version ">= 7.6.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
λ yarn add koa-static
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error koa-send@4.1.0: The engine "node" is incompatible with this module. Expected version ">= 7.6.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Simply try `yarn add koa-static` or `yarn add koa-webpack-hot-middleware` to any repo.

**What is the expected behavior?**
install should succeed with no errors.

**Please mention your node.js, yarn and operating system version.**
Node: 8.1.3
yarn: 0.27.5
OS: Windows 7 x64

**Comment by arcanis** [comment]
I can't reproduce this on my side

**Comment by mrchief** [comment]
@arcanis  I'm using Nodist on my end. I'll give a try without it. Are you on Windows?

**Comment by mrchief** [comment]
nodist had global node version set to 7.2.1. After setting `nodist global 8.x`, this error goes away. Closing this as a non issue.
