### ISSUE TITLE
Yarn package publish succeeded but responded with error

### ISSUE THREAD

**Issue by bchoddny** [yarnpkg/yarn#3939]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When running yarn publish command, the package is successfully published but the command response says publishing failed
**If the current behavior is a bug, please provide the steps to reproduce.**

$ yarn publish --new-version 2.0.1 --verbose
....
verbose 1.892 Error: Couldn't publish package.
    at MessageError (/Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/errors.js:8:5)
    at /Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/cli/commands/publish.js:98:13
    at next (native)
    at step (/Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/testuser/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)

**What is the expected behavior?**
No error response if package successfully published.
**Please mention your node.js, yarn and operating system version.**
node 6.9.4
yarn 0.27.2
mac 10.11.3
repo nexus3 private npm repository

**Comment by onurtemizkan** [comment]
This issue seems to be fixed by #3861

**Comment by olingern** [comment]
@BYK potentially closeable

**Comment by BYK** [comment]
@olingern thanks!
