### ISSUE TITLE
Hashes don't match for `bytes`

### ISSUE THREAD

**Issue by marvinhagemeister** [yarnpkg/yarn#3948]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

```bash
error Hashes don't match when extracting file "https://registry.yarnpkg.com/bytes/-/bytes-2.4.0.tgz". Expected "7d97196f9d5baf7f6935e25985549edd2a6c2339" but got "da39a3ee5e6b4b0d3255bfef95601890afd80709"
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `yarn init && yarn add koa-logger`

**What is the expected behavior?**
Hashes should match

**Please mention your node.js, yarn and operating system version.**
- yarn 0.27.5
- Node 8.1.4
- MacOS Sierra

**Comment by rally25rs** [comment]
Seems to work for me:

```
~/Projects/yarn-test : yarn init && yarn add koa-logger
yarn init v0.27.5
question name (yarn-test):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
success Saved package.json
Done in 4.29s.
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 11 new dependencies.
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ bytes@2.5.0
├─ chalk@1.1.3
├─ escape-string-regexp@1.0.5
├─ has-ansi@2.0.0
├─ humanize-number@0.0.2
├─ koa-logger@3.0.1
├─ passthrough-counter@1.0.0
├─ strip-ansi@3.0.1
└─ supports-color@2.0.0
Done in 0.89s.
```

Possibly the registry somehow returned the wrong data, or the download was corrupted, or some proxy server is giving you back something else? `7d97196f9d5baf7f6935e25985549edd2a6c2339` is the correct hash according the the metadata for that package.

**Comment by marvinhagemeister** [comment]
Indeed, it is fixed now. Seems like it was a problem with the npm registry itself...
