### ISSUE TITLE
An unexpected error occurred: "EACCES: permission denied

### ISSUE THREAD

**Issue by valeriashpiner** [yarnpkg/yarn#3949]
Yarn 0.27.5

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
An unexpected error occurred: "EACCES: permission denied, mkdir '/Users/lera/Library/Caches/Yarn/v1'".

**If the current behavior is a bug, please provide the steps to reproduce.**

I tried to re-install brew, yarn, node and npm. 
Tried to install it with sudo, but it had conflict with brew.
Tried to clean cache.

**What is the expected behavior?**
I need to launch my project with command `yarn install`.

**Please mention your node.js, yarn and operating system version.**
Node 8.1.4.
Yarn 0.27.5
macOS Sierra 10.12.4

**Comment by BYK** [comment]
Looks like you don't have the correct permissions for one of the directories in the ` /Users/lera/Library/Caches/Yarn` chain. So may be a `sudo chown -R lera /Users/lera/Library/Caches` would fix it?

Nevertheless, this doesn't look like a Yarn bug.

**Comment by emcpadden** [comment]
FWIW, I had a similar problem.  I upgraded Yarn on my mac:
`brew upgrade yarn`
And that fixed the problem.

**Comment by smilexu** [comment]
brew upgrade yarn is the best answer for me

**Comment by hevyweb** [comment]
Are you kidding me? You do updates and don't even think what causes the issue?

**Comment by mtavano** [comment]
@hevyweb I think that you should think in the following: **why this didn't happen yesterday, but today it seems like a nuke?**

I like your approach, but suddenly these weird issues come up

**Comment by shubhamkakkar** [comment]
I am using ubuntu 18.04 and using sudo before the command solved the issue for me.
ie - say the command is yarn add react yarn add react-router-hash-link
using it like this solved the issue
sudo yarn add react-router-hash-link

**Comment by JackieLs** [comment]
I've run `chmod 751 yarn` and `chmod 751 yarnpkg`.Remove the old `node_modules`.Then reinstall the pkg again.It worked.I think it's just because the authority of yarn is not enough.

**Comment by mateusmoura** [comment]
Use: 
`sudo yarn add .....`

✌️
