### ISSUE TITLE
yarn installs binaries for dependencies after a global add

### ISSUE THREAD

**Issue by emazv72** [yarnpkg/yarn#3950]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

yarn 0.27.5 installs binaries for dependencies after a global add. 

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn global add @angular/cli && tsc --version`

`Version 2.3.4`

**What is the expected behavior?**

tsc binary is a dependency and shouldn't be installed globally.

**Please mention your node.js, yarn and operating system version.**

Windows 10
node v6.11.0

**Comment by phelma** [comment]
for me, doing `yarn global add foundation-cli` added npm@^2.1.12 who's binary was then added to my path (frustratingly before my regular npm@5 install)

**Comment by BYK** [comment]
Duplicate of #3824.
