### ISSUE TITLE
Breaking: rename every `yarn <command> rm` to `yarn <command> remove`

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#3952]
Spun off from https://github.com/yarnpkg/yarn/pull/3898#issuecomment-315584833

For the sake of consistency and clarity, we need to rename the `rm` command to `remove` and add a deprecation warning for `rm`.

**Comment by voxsim** [comment]
@BYK I will rename the task and add 'help-wanted' and 'good-first-contribution' label

**Comment by tpina** [comment]
Hello,

I'd love to help with this. This would be my first ever contribution so I'll probably need some guidance.

**Comment by tpina** [comment]
@BYK 

> For the sake of consistency and clarity, we need to rename the rm command to `rename`and add a deprecation warning for rm.

I presume you mean: ... we need to rename the rm command to `remove` right?

**Comment by BYK** [comment]
@tpina haha, yeah sorry about that. Updated the description. Thanks for the heads up!

**Comment by BYK** [comment]
Also, you can check out #3898 for an example PR. If you need help, feel free to ping us here or in Discord!

**Comment by tpina** [comment]
@BYK - I'll take a crack at it. I'll update you ASAP.

**Comment by tpina** [comment]
@BYK  I need some guidance.
I've seen #3898 but one thing I've noticed is that every command with `rm` requires a login. Coincidentally, and if I am not mistaken, none of the commands that implements `rm` has tests ( `owner`,  `tag`, `team`).

I'd like to add tests for those but I can't seem to make a mock login to work... any suggestions?

Thanks in advance

**Comment by tpina** [comment]
@BYK The code is pretty much done but as I said in the comment above, I have no tests :(
Can I please have some guidance?

I also noticed that `yarn team ls` as not been deprecated and changed to `list` should I do it as part of this issue?

**Comment by voxsim** [comment]
@tpina please open the pr and starts to see and discuss the code. And for `yarn team ls` yes, please do in another pull request.

**Comment by BYK** [comment]
@tpina hey, sorry for not getting back to you sooner but looks like with the nidge from @voxsim you figured it all out. Great job, thanks!

**Comment by tpina** [comment]
@BYK Not a problem! I'll create another issue for the `yarn team ls` command that is still there and I'll send the PR as soon as possible. Thank you guys for helping me through my very first PR/contribution!
Can I still pick up `good-first-contribution` issues until I'm more comfortable with the code base?

Looking forward for more.

**Comment by BYK** [comment]
>Can I still pick up good-first-contribution issues until I'm more comfortable with the code base?

Of course! That said I'd start leaving them to less experienced folks once you get more used to the code base :)

**Comment by Sheeo** [comment]
Just stopping by to drop my two cents: `ls` and `rm` are extremely widely used aliases throughout the unix ecosystem.

This breaks tools that interact with the yarn CLI for a seemingly pointless reason, forcing maintainers to do needless work.

**Comment by BYK** [comment]
Hi @Sheeo, thanks for the ping. Although I understand this will cause some pain in the near term, we as a team think clarity beats traditional in the long term and helps everyone.

We are aware that it will require changes in the tools that interact with yarn and that's why we deprecate them first instead of removing and also, marking this as a breaking change.

Trivia: [Why Unix Has Short Command Names?](https://youtu.be/h5-DRLfzqD0)

**Comment by olingern** [comment]
@BYK Looks like this can be closed, too :)

**Comment by kaylieEB** [comment]
woohoo!
