### ISSUE TITLE
--non-interactive flag is not documented

### ISSUE THREAD

**Issue by ahmehri** [yarnpkg/yarn#3956]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**
No documentation for `--not-interactive` flag which has been added in #2770.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Documentation for the flag is available.

**Please mention your node.js, yarn and operating system version.**
Node.js version: 8.1.0
yarn version: 0.27.5

**Comment by kaylieEB** [comment]
Hi @ahmehri! Can you move this to https://github.com/yarnpkg/website where the documentation lives?

**Comment by ahmehri** [comment]
@kaylieEB yes sorry I wasn't aware of the existence of https://github.com/yarnpkg/website.
Issue (yarnpkg/website#579) has been created.

**Comment by BYK** [comment]
Thanks @ahmehri and @kaylieEB!
