### ISSUE TITLE
Support for package.json5

### ISSUE THREAD

**Issue by JosefJezek** [yarnpkg/yarn#3959]
Could you add support for `package.json5`? We need comments and other features of JSON5. ;-)

> JSON5 officially supports Node.js v4 LTS and v5

https://github.com/json5/json5/releases/tag/v0.5.0

**Comment by BYK** [comment]
I would be hesitant TBH. @yarnpkg/core, thoughts?

**Comment by cpojer** [comment]
I don't think this is necessary at this point in time.

**Comment by arcanis** [comment]
Yeah .. it would also open another slew of issue, the first of which being: "my comments are being removed when I run `yarn add`"

**Comment by patarapolw** [comment]
My thought about this is not about comments, but multiple line scripts...

Although, `package.yaml` would be more ideal.

**Comment by BYK** [comment]
Locking this convo as I don't see anyone implementing this realistically.
