### ISSUE TITLE
Yarn fail to install faker.js-2.0.0

### ISSUE THREAD

**Issue by pkuczynski** [yarnpkg/yarn#3961]
When running

`yarn add --dev faker.js`

I receive output

`error An unexpected error occurred: "https://registry.yarnpkg.com/faker.js/-/faker.js-2.0.0.tgz: Request failed \"404 Not Found\"".`

The same package installs with `npm` without any issue.

Node: 7.10.0
Yarn: 0.27.5
OS: macOS Sierra 10.12.5

**Comment by arcanis** [comment]
That's weird. It seems to be an issue on the npm registry, tho:

https://registry.npmjs.org/faker.js

<img width="776" alt="screen shot 2017-07-19 at 1 16 41 pm" src="https://user-images.githubusercontent.com/1037931/28366419-891b4366-6c84-11e7-9a2d-bc2c57b7e249.png">

https://registry.npmjs.org/faker.js/-/faker.js-2.0.0.tgz

<img width="616" alt="screen shot 2017-07-19 at 1 17 05 pm" src="https://user-images.githubusercontent.com/1037931/28366431-99517d04-6c84-11e7-811f-5768163b6f01.png">

**Comment by pkuczynski** [comment]
Hmm, looks like it works now. Maybe it was a temporary npm issue?
