### ISSUE TITLE
yarn using latest release instead given git branch

### ISSUE THREAD

**Issue by buncismamen** [yarnpkg/yarn#3964]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
yarn using latest release instead given git branch

**If the current behavior is a bug, please provide the steps to reproduce.**
add the git repository
`yarn add https://github.com/aksonov/react-native-router-flux.git#master`

but it only use latest release instead given branch/commit
```
success Saved lockfile.
success Saved 14 new dependencies.
├─ clamp@1.0.1
├─ mobx-react@4.2.2
├─ mobx@3.2.1
├─ opencollective@1.0.3
├─ path-to-regexp@1.7.0
├─ react-native-button@2.1.0
├─ react-native-dismiss-keyboard@1.0.0
├─ react-native-drawer-layout-polyfill@1.3.2
├─ react-native-drawer-layout@1.3.2
├─ react-native-router-flux@4.0.0-beta.12
├─ react-native-tab-view@0.0.65
├─ react-navigation@1.0.0-beta.11
├─ rx@4.1.0
└─ websql@0.4.4
Done in 30.26s.
```

and when I run yarn start
then I get this warning
```
 Warning: Installed version 4.0.0-beta.12 of 'react-native-router-flux' does not satisfy required version https://github.com/aksonov/react-native-router-flux.git#master

If there is an issue running your project, please run `npm install` in /home/user1/myproject and restart.
```

I've also use another url like using #commitID 
`yarn add https://github.com/aksonov/react-native-router-flux.git#d4fff5036653e723a697f8ab28d0ce9ee387ffb8`
or
`yarn add git+ssh://git@github.com/aksonov/react-native-router-flux.git#master`
or
`yarn add github:aksonov/react-native-router-flux#master`
but the problem is persist
**What is the expected behavior?**
it should use the given branch/commitID/tag
**Please mention your node.js, yarn and operating system version.**
yarn v0.27.5
node v6.10.3
ubuntu 17.04

**Comment by BYK** [comment]
It does install it from GitHub. The package version on GitHub is set to `4.0.0-beta.12`: https://github.com/aksonov/react-native-router-flux/blob/master/package.json#L3

**Comment by buncismamen** [comment]
@byk yeah it is now, becaus the owner of repo just[ released it ](https://github.com/aksonov/react-native-router-flux/releases)

also I still got this warning is ok?


```
8:55:45 PM: Warning: Installed version 4.0.0-beta.12 of 'react-native-router-flux' does not satisfy required version https://github.com/aksonov/react-native-router-flux.git#master

If there is an issue running your project, please run `npm install` in /home/user1/myproject and restart.
```

**Comment by BYK** [comment]
>also I still got this warning, is it ok?

I can't really comment on that until I understand where that warning is coming from. It doesn't seem to be coming from `yarn` to me but may be I'm missing something.

**Comment by reidlai** [comment]
same problem here

**Comment by VitorLuizC** [comment]
Same is happening here.
```Installed version 0.2.0 of 'react-native-components' does not satisfy required version git+ssh://git@github.com/A2Lab-Team/react-native-components.git```

**Comment by timri** [comment]
I have the same problem trying to install master-branch of https://github.com/joeferraro/react-native-cookies (for webKit-Support, which is not released yet)
