### ISSUE TITLE
yarn upgrade executes dependancy's postinstall

### ISSUE THREAD

**Issue by r00ger** [yarnpkg/yarn#3969]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn upgrade foo@...` executes `foo`'s `postinstall` script
https://github.com/evolution-gaming/yarn-upgrade-issue

**What is the expected behavior?**
`foo`'s `postinstall` is not executed

yarn 0.27.5 (reproduces on 0.24.6 as well)
node v7.10.0

**Comment by rally25rs** [comment]
Is this related to #3865 ?

**Comment by r00ger** [comment]
Oh, right, thanks. Didn't manage to find the issue. I suppose mine is to be closed
