### ISSUE TITLE
Conflict in different versions of a package and the binary in .bin directory

### ISSUE THREAD

**Issue by sassanh** [yarnpkg/yarn#3975]
Uglify-es is one of my project's dependencies but there are lots of other dependencies and some of those depend on Uglify-js or even Uglifyjs, the problem is after `yarn install`, `node_modules/.bin/uglifyjs` doesn't refer to Uglify-es, it refers to Uglifyjs. I know I can run it by absolute path, but maybe yarn should always prefer newer version or the one that's in `package.json` of the root module (not in dependencies of dependencies) (any of these solves the problem.)

**Comment by SpainTrain** [comment]
>  the one that's in package.json of the root module

This is the most reasonable option IMO.  We are encountering this exact issue with webpack, which is a dev dependency specifically for the purpose of running in npm/yarn scripts.

**Comment by sassanh** [comment]
Unfortunately Yarn v0.28.1 is not released in homebrew yet. I'll close this issue as soon as it's released and I can check it.
@SpainTrain thanks for info.

**Comment by sassanh** [comment]
> I'll close this issue as soon as it's released and I can check it.

or that.

**Comment by BYK** [comment]
@sassanh oops, sorry. I skipped that last sentence 😃

**Comment by dschep** [comment]
So.. there's mentions of closing this when released, but the debian repo is still on 0.27.5. Any chance of a debian release with this fix before 1.0 is stable?

**Comment by BYK** [comment]
>So.. there's mentions of closing this when released, but the debian repo is still on 0.27.5. Any chance of a debian release with this fix before 1.0 is stable?

Very soon :)

**Comment by sassanh** [comment]
I'm done with this. It's working for me in 1.0.1. Thanks for keeping it open. I don't close in case you have still things to do about Debian release.

**Comment by dschep** [comment]
Debian release stable is on 1.0.1 now too :+1:

**Comment by BYK** [comment]
🎉 ❤️
