### ISSUE TITLE
ambiguous install behaviour of workspace projects with the same name as published packages

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#3979]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

- The local package in `./packages/a` is overridden with the content of the published package [`a@1.0.2`](https://yarnpkg.com/en/package/a).
- The published package [`a@1.0.2`](https://yarnpkg.com/en/package/a) is installed inside `./node_modules/a`.

**If the current behavior is a bug, please provide the steps to reproduce.**

0. `$ git clone git@github.com:pedronauck/yarn-workspaces-example.git`
0. `$ cd yarn-workspaces-example/packages/b`
0. `$ yarn add react`

**What is the expected behavior?**

- adds `react` as a dependency in `./packages/b/package.json`
- updates `./yarn.lock`
- updates `./node_modules/`
- does **not** change the content inside `./packages/a`
- install the `./packages/a` to `./node_modules/a`

**Please mention your node.js, yarn and operating system version.**

- Node v6.9.1
- yarn v0.27.5
- Mac OS X

--- 

Workspaces look great so far! ♥

Note: When I call `$ yarn install` in the root of the project the local `a` is used correctly and `./packages/a` will be installed to `./node_modules/a`.

---

**Update**

When I change `a` to `adflkfdsmlkfmsd` (a name which is not used by a published package) and run this:

0. `$ git clone git@github.com:pedronauck/yarn-workspaces-example.git`
0. `$ cd yarn-workspaces-example/packages/b`
0. `$ yarn add react`

I get:

```
$ yarn add react
yarn add v0.27.5
[1/4] Resolving packages...
error Couldn't find package "adflkfdsmlkfmsd" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I'd expect this to work, just like a call to `$ yarn` in the root of the project works.

**Comment by bestander** [comment]
Can't repro this in 0.28.1.
packages/a is not touched by `yarn add react`

**Comment by donaldpipowitch** [comment]
Thank you. I can check this in a week when I'm back home.

Different question: what is your recommended way to switch between multiple yarn versions and nightly? Can brew install yarn nightly?

**Comment by bestander** [comment]
@donaldpipowitch, that is an interesting question, I think the installation script would fit best for you https://yarnpkg.com/en/docs/install#alternatives-tab https://yarnpkg.com/en/docs/nightly.

But it may be a hassle if you want to switch often.
At FB we check in yarn.js with ability to configure it per project.

**Comment by bestander** [comment]
I'll close the task, let's reopen this if you can repro the bug.

**Comment by donaldpipowitch** [comment]
Tried it with `v1.0.0-20170807.1537` and it works 👍
