### ISSUE TITLE
Unexpected install behaviour in workspace based project

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#3980]
**Do you want to request a *feature* or report a *bug*?**

*bug*?

**What is the current behavior?**

- `react@15.0.1` is installed at `./node_modules/react`
- `react@15.6.1` is installed at `./packages/b/node_modules/react`

**If the current behavior is a bug, please provide the steps to reproduce.**

0. `$ git clone git@github.com:pedronauck/yarn-workspaces-example.git`
0. add `"react": "15.0.1"` to `dependencies` inside `./packages/a`
0. add `"react": "^15.0.1"` to `dependencies` inside `./packages/b`
0. run `$ yarn` in the root of the project

**What is the expected behavior?**

- **only** `react@15.0.1` is installed at `./node_modules/react` (because `b` accepts `15.0.1`, too) (I'd expect this to be the default behaviour)

**Please mention your node.js, yarn and operating system version.**

- Node v6.9.1
- yarn v0.27.5
- Mac OS X

--- 

Workspaces look great so far! ♥

---

**Question**

I'm not certain if `resolutions` is already implemented. I saw this in several issues, but not in any docs. Given it is implemented, should this issue be _workaround_ by adding this part to `./package.json`?:

```
"resolutions": {
  "react": "15.0.1"
}
```

I don't want to install _everything_ flat (not if some lib wants `^1.0.0` and another lib wants `^2.0.0` from a certain dep), but I do want to install it as flat as possible, if versions fit into a range (like in this case, because `15.0.1` fits into `^15.0.1`).

**Comment by bestander** [comment]
I think this is not directly workspace related, it is inefficiency of our resolution algorithm.
We need to make it smarter, see this issues for details https://github.com/yarnpkg/yarn/issues/3778

help is welcome

**Comment by donaldpipowitch** [comment]
Thank you!
