### ISSUE TITLE
Wrong environment path when installing windows .msi 

### ISSUE THREAD

**Issue by pikax** [yarnpkg/yarn#3982]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Setting the path to `%LOCALAPPDATA%\Yarn\bin` when installing from the [installer](https://yarnpkg.com/en/docs/install#windows-tab) even if we use the Program files folder.

**If the current behavior is a bug, please provide the steps to reproduce.**
Plain install from following (windows installation guide)[https://yarnpkg.com/en/docs/install#windows-tab]

**What is the expected behavior?**
It should update %PATH% variable to the installation chosen path.

**Please mention your node.js, yarn and operating system version.**
node: v8.2.1
yarn: v0.27.5
windows: windows 10

**Comment by BYK** [comment]
//cc @Daniel15

**Comment by Daniel15** [comment]
The LocalAppData path is for global packages you install via Yarn itself.
The installer also adds the Program Files directory to the path. Note that
you need to restart processes for them to see the new path.

**Comment by pikax** [comment]
> The installer also adds the Program Files directory to the path. Note that
you need to restart processes for them to see the new path.

After installing I started a new console and command `yarn` didn't work(program not found), I needed to go to `Environment Variables` and append `C:\Program Files (x86)\Yarn\bin` to the `%PATH`, it after installing yarn it only added `C:\Users\username\AppData\Local\Yarn\bin`.

**Comment by Daniel15** [comment]
It adds ``C:\Users\username\AppData\Local\Yarn\bin` to your user path, and `C:\Program Files (x86)\Yarn\bin` to the **system** path. They're two separate settings.
