### ISSUE TITLE
Wildcard upgrades

### ISSUE THREAD

**Issue by pronebird** [yarnpkg/yarn#3984]
Hi,

I use a myriad of `babel-*` packages and would love to update all of them to the latest alpha.

Running  `yarn upgrade babel-*@next` throws an error. 

> no matches found: babel-*@next

It would be awesome if yarn supported wildcard expressions.

**Comment by Daniel15** [comment]
I usually use [npm-check-updates](https://yarnpkg.com/en/package/npm-check-updates) for this
```
npm-check-updates -u -a --packageFile ./package.json /babel\-/
```

It would be good to support this in Yarn though!

**Comment by fcastilloec** [comment]
+1

**Comment by BYK** [comment]
Nice! We accept PR as a currency if anyone wants to take a stab at this :)

**Comment by arcanis** [comment]
It's partially supported by the `-S` option, which upgrades all the packages that belong to the same scope. Might be nice to have an improved support for wildcards, tho.

**Comment by noahbenham** [comment]
I'm able to do `yarn upgrade -P /babel-/`. Should this be closed?

**Comment by kaylieEB** [comment]
Closing this via https://github.com/yarnpkg/yarn/pull/4610
