### ISSUE TITLE
Installing alpha version

### ISSUE THREAD

**Issue by salarmehr** [yarnpkg/yarn#3993]
while using `npm install 'gulpjs/gulp.git#4.0' --save-dev` I can install version 4 of gulp, running ` yarn global add gulp@4 ` does not work and ask to select an older version.

**Comment by aij** [comment]
Why would you expect that to work? `npm install gulp@4` doesn't work either:

```
npm ERR! notarget No compatible version found: gulp@4
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.9.1, 3.9.0, 3.8.11, 3.8.10, 3.8.9, 3.8.8, 3.8.7, 3.8.6, 3.8.5, 3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.0, 3.6.2, 3.6.1, 3.6.0, 3.5.6, 3.5.5, 3.5.2, 3.5.1, 3.5.0, 3.4.0, 3.3.4, 3.3.2, 3.3.1, 3.3.0, 3.2.5, 3.2.4, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.0.0, 2.7.0, 2.6.1, 2.6.0, 2.4.1, 2.4.0, 2.3.0, 2.2.0, 2.1.0, 2.0.1, 2.0.0, 1.2.1, 1.2.0, 1.1.0, 1.0.0, 0.2.0, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
```

Presumably because the new version hasn't been published to the registry yet. You can still install from github though if you use `'gulpjs/gulp.git#4.0'` instead of `gulp@4`.

**Comment by BYK** [comment]
Yup, that's because 4.0 is not published yet: https://yarnpkg.com/en/package/gulp
