### ISSUE TITLE
Yarn build script ignored whenever prebuild is installed

### ISSUE THREAD

**Issue by liujimj** [yarnpkg/yarn#3994]
**Do you want to request a *feature* or report a *bug*?**
bug / request clarification

**What is the current behavior?**
When `prebuild` is installed, `yarn build` always runs prebuild regardless of whether there's a `build` script already defined.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn init
yarn add prebuild
```

then add the following block to `package.json`:

```
  "scripts": {
    "build": "echo foo"
  }
```

then run `yarn run build`.

**What is the expected behavior?**

I expect to see `foo`. Instead `prebuild` is run.

Would like clarification here, as [Yarn documentation](https://yarnpkg.com/lang/en/docs/cli/run/) doesn't mention that npm packages can override scripts, nor that there are default behaviors. [NPM docs](https://docs.npmjs.com/misc/scripts) have more extensive discussion, but again do not suggest this behavior.

**Please mention your node.js, yarn and operating system version.**
yarn 0.27.5, Mac OS Sierra 10.12.5, node v8.1.3

This bug is not present on yarn 0.24.6. I have not tested any other versions.

**Comment by liujimj** [comment]
Output with `prebuild` installed:

```
```
) yarn build
yarn build v0.27.5
$ "/Users/liujimj/yarn-build-wtf/node_modules/.bin/prebuild"
prebuild info begin Prebuild version 6.2.1
prebuild info build Preparing to prebuild yarn-build-wtf@1.0.0 for node 8.1.3 on darwin-x64 using node-gyp
prebuild info spawn /usr/local/bin/python2
prebuild info spawn args [ '/Users/liujimj/yarn-build-wtf/node_modules/node-gyp/gyp/gyp_main.py',
prebuild info spawn args   'binding.gyp',
prebuild info spawn args   '-f',
prebuild info spawn args   'make',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/liujimj/yarn-build-wtf/build/config.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/liujimj/yarn-build-wtf/node_modules/node-gyp/addon.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/liujimj/.node-gyp/8.1.3/include/node/common.gypi',
prebuild info spawn args   '-Dlibrary=shared_library',
prebuild info spawn args   '-Dvisibility=default',
prebuild info spawn args   '-Dnode_root_dir=/Users/liujimj/.node-gyp/8.1.3',
prebuild info spawn args   '-Dnode_gyp_dir=/Users/liujimj/yarn-build-wtf/node_modules/node-gyp',
prebuild info spawn args   '-Dnode_lib_file=/Users/liujimj/.node-gyp/8.1.3/<(target_arch)/node.lib',
prebuild info spawn args   '-Dmodule_root_dir=/Users/liujimj/yarn-build-wtf',
prebuild info spawn args   '-Dnode_engine=v8',
prebuild info spawn args   '--depth=.',
prebuild info spawn args   '--no-parallel',
prebuild info spawn args   '--generator-output',
prebuild info spawn args   'build',
prebuild info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/liujimj/yarn-build-wtf) while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/Users/liujimj/yarn-build-wtf/node_modules/node-gyp/lib/configure.js:336:16)
prebuild ERR! stack     at emitTwo (events.js:125:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:213:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/Users/liujimj/yarn-build-wtf/node_modules/node-gyp/lib/configure.js:336:16)
prebuild ERR! build     at emitTwo (events.js:125:13)
prebuild ERR! build     at ChildProcess.emit (events.js:213:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
error Command failed with exit code 2.
-> [1]
```

and without:

```
) yarn remove prebuild
yarn remove v0.27.5
[1/2] Removing module prebuild...
[2/2] Regenerating lockfile and installing missing dependencies...
success Uninstalled packages.
Done in 0.60s.
) yarn build
yarn build v0.27.5
$ echo foo
foo
Done in 0.09s.
```

**Comment by aracarie** [comment]
Since `yarn run` let's you run scripts from `node_modules/.bin` like `prebuild` I'd imagine the correct behavior would be to only check for the `pre-` and `post-` action hooks from the scripts defined in the `package.json` file.

It also looks like right now the `pre-` and `post-` actions would also be run for binary scripts. They should probably only be run for scripts defined in the `package.json` file.
