### ISSUE TITLE
Hashes don't match when extracting file

### ISSUE THREAD

**Issue by BrendanBall** [yarnpkg/yarn#4004]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behavior?**
yarn fails to install the dependency angular2-notifications. So far it's only breaking for this dependency.
it breaks after cleaning the yarn cache in a new empty project, as well as when trying to run `yarn install` where the package is in the `yarn.lock` file.
```
➜  /home/brendan/Development/projects/yarntest yarn cache clean
yarn cache v0.27.5
success Cleared cache.
Done in 0.08s.
➜  /home/brendan/Development/projects/yarntest yarn init
yarn init v0.27.5
question name (yarntest): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
success Saved package.json
Done in 2.73s.
➜  /home/brendan/Development/projects/yarntest yarn add angular2-notifications
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error Hashes don't match when extracting file "https://registry.yarnpkg.com/angular2-notifications/-/angular2-notifications-0.7.4.tgz". Expected "edc4782fd47bdb68d9516d48127284b63330c34e" but got "da39a3ee5e6b4b0d3255bfef95601890afd80709"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I cannot reproduce it, it's working fine on colleagues' machines. It also works fine inside a docker container using the same node and yarn version. I haven't been able to fix it in my dev environment though.

**What is the expected behavior?**
```
root@953fc9c8f6bf:/# yarn add angular2-notifications
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "angular2-notifications@0.7.4" has unmet peer dependency "@angular/core@^4.0.1".
warning "angular2-notifications@0.7.4" has unmet peer dependency "@angular/common@^4.0.1".
warning "angular2-notifications@0.7.4" has unmet peer dependency "@angular/platform-browser@^4.0.0".
warning "angular2-notifications@0.7.4" has unmet peer dependency "@angular/animations@^4.0.1".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ angular2-notifications@0.7.4
Done in 1.04s.
```

**Please mention your node.js, yarn and operating system version.**
yarn v0.27.5
node v8.2.1
Linux 4.11.9-1-ARCH

**Comment by tetyanagimgina** [comment]
Have exactly the same issue:
error Hashes don't match when extracting file "https://registry.yarnpkg.com/classnames/-/classnames-2.2.5.tgz". Expected
 "fb3801d453467649ef3603c7d61a02bd129bde6d" but got "01573c346bf574b763a8a684197a0eebeaccd6aa"

yarn v0.27.5
node v6.11.0
Windows 7

**Comment by kjbkjb** [comment]
Ditto here
I've re-packed our own gemfury-hosted items using yarn, then suddenly the same error happened to another package.

`yarn cache clean` and then the problem pops up on yet another package. The suspicious symptom is that the "but got sha" was the same for all the errors

 Hashes don't match when extracting file "https://npm.fury.io/sportngin/global-session/-/3.0.3.tgz?auth=Up97EjxiNexkaesDEnU1". Expected "2f6a2fcbe857a1df5d222c7a539c022d9bd2e771" but got "**da39a3ee5e6b4b0d3255bfef95601890afd80709**"

Hashes don't match when extracting file "https://registry.yarnpkg.com/good-json-console/-/good-json-console-1.0.0.tgz". Expected "ace2b9bcf90c9aeeb68d7a22dba789ab112d421c" but got "**da39a3ee5e6b4b0d3255bfef95601890afd80709**"

 `yarn cache clean && yarn install`
Hashes don't match when extracting file "https://npm.fury.io/sportngin/feature-toggles/-/3.0.3.tgz?auth=Up97EjxiNexkaesDEnU1". Expected "05ed21e475d44c62db4477bf35d73b3657f22b43" but got "**da39a3ee5e6b4b0d3255bfef95601890afd80709**"

**Comment by BrendanBall** [comment]
Well I'm glad I'm not the only one. Other than clearing the yarn cache and reinstalling yarn I've got no idea what's different between my dev environment and a docker container so I've got no idea how to fix my dev environment to make yarn work again.

**Comment by aij** [comment]
> da39a3ee5e6b4b0d3255bfef95601890afd80709

I think I've seen that SHA1 before.

```
$ sha1sum /dev/null 
da39a3ee5e6b4b0d3255bfef95601890afd80709  /dev/null
```

So, you appear to be getting empty files somehow (which is bad) and yarn is detecting them as wrong (which is good). 

I would suggest trying to track down the source of the empty files. Perhaps server/proxy/connectivity issues? Is yarn ignoring error codes when the download fails? Are you out of disk/quota?

**Comment by marvinhagemeister** [comment]
@actra-gschuster  Deleting `yarn.lock` and recreating it fixed one hash mismatch, but now I'm stuck with a mismatch for another package.

@aij that's a nice observation! Can confirm that I have the same hash whenever a mismatch is reported.

**Comment by joncursi** [comment]
I just started getting the same type of error on my CI systems (Circle CI):

```
yarn
yarn install v0.27.5
[1/5] Resolving packages...
⠁ ⠂ kebab-case@^1.0.0⠄ ret@~0.1.10⡀ ua-parser-js@^0.7.9⢀ is-stream@^1.0.1[2/5] Fetching packages...
error Hashes don't match when extracting file "https://registry.yarnpkg.com/babel-eslint/-/babel-eslint-7.2.3.tgz". Expected "b2fe2d80126470f5c19442dc757253a897710827" but got "cd37e9d2cf6f73e4724c28984d615e8512ce1dfb"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn returned exit code 1

Action failed: yarn
```

**Comment by shajith** [comment]
I'm seeing this on the 0.27.5 (current stable version), with the `da39a3ee5e6b4b0d3255bfef95601890afd80709` hash. I use the offline mirror feature, and I can see that yarn has a 0-byte tarball in the mirror folder for the package that I get this error for. Help?

**Comment by merceyz** [comment]
Closing as fixed in v2 where the cache has been improved a lot

https://yarnpkg.com/getting-started/migration
