### ISSUE TITLE
Yarn: error: no such option: --dev

### ISSUE THREAD

**Issue by aqeelcodeenterprises** [yarnpkg/yarn#4005]
Following [this article](https://tighten.co/blog/adding-react-components-to-a-laravel-app) I am trying to add react environment in my fresh Laravel application.

When I run `yarn add --dev react react-dom` It gives me the following error:

> Usage: yarn [options]
> 
> yarn: error: no such option: --dev

I am using Ubuntu latest OS.
Please help me to get ride of this problem.

Thank you

**Comment by fussinatto** [comment]
Can you please state yarn and node versions? 
Just to make sure, your Ubuntu is 17.04 right?

**Comment by rally25rs** [comment]
Closing this issue since the original creator has not provided any additional version information in 2 weeks. It also seems to work fine in current Yarn versions, so I suspect they just have a really old version. We can re-open this is a specific version is added to the bug description.

**Comment by wangai** [comment]
You probably installed yarn using this:
 `$ apt install cmdtest`
Use this instead:
 `$ npm install --global yarn`

**Comment by aqeelcodeenterprises** [comment]
Hi first of all, thanks everybody,

I have updated the question, please can you check now.

**Comment by roddypratt** [comment]
@aqeelcodeenterprises - as @rally25rs says "I suspect they just have a really old version"

0.16 is almost a year old. not old for a car, but old for software :)

" *Before creating an issue please make sure you are using the latest version of yarn.*"

**Comment by momilc** [comment]
This works too. Assuming you have yarn installed globally like @wangai.
 In Terminal instead of using 
```
yarn [something]
```
use the command like this
```
/usr/local/bin/yarn [something]
```

**Comment by maotoledos** [comment]
I don't see any helpfull to use `/usr/local/bin/yarn` 

You just need to use `sudo`  before the command line.

**Comment by the-einstein** [comment]
> npm install --global yarn

I used this, but nothing has changed

**Comment by SSSangha90** [comment]
same as above, no change using npm install --global yarn
