### ISSUE TITLE
yarn init doesn't understand repo shortcuts 

### ISSUE THREAD

**Issue by mohsen1** [yarnpkg/yarn#4006]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
when providing org/repo to yarn init repo section it remains as is. Example: 
https://github.com/mohsen1/universal-async-component/blob/master/package.json#L6
**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn init
// accept accept...
repo: org/repo
```

**What is the expected behavior?**

it should resolve the shortcut to proper GitHub repo URL

**Please mention your node.js, yarn and operating system version.**
yarn v0.23.3 node 8

**Comment by FrederickGeek8** [comment]
The commit referenced in this Github issue should provide the functionality you are asking for. I'm going to see if I can't setup some tests and then I'll submit a PR.

**Comment by olingern** [comment]
@BYK Looks like this can be closed?

**Comment by BYK** [comment]
@olingern, yup. Thanks for the heads up! :)
