### ISSUE TITLE
`brew install yarn`always installed node v8.2.1 even I've installed node@6 with HomeBrew on MacOS

### ISSUE THREAD

**Issue by imzhengfei** [yarnpkg/yarn#4007]
**MacOS**: v10.12.5
**HomeBrew**: v1.2.4
**Yarn**: v0.27.5

**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
* `brew install yarn` always installed node v8.2.1 even I've installed node@6 with HomeBrew on MacOS
* That command also installed `icu4c`, what's and why `icu4c`?
**If the current behavior is a bug, please provide the steps to reproduce.**

Steps:
* Open iTerm2
* Run `brew ls` to make sure I've installed `node@6`
* Run ` node -v` to make sure my node version is `v6.10.2`
* Run `brew install yarn` to install `yarn`
* When completed, run `brew ls` and I saw `node node@6 yarn icu4c ...`

**What is the expected behavior?**
* No installing `node v8.2.1`
* No installing `icu4c`

**Please mention your node.js, yarn and operating system version.**

**Comment by cebor** [comment]
Issue should be created here: https://github.com/Homebrew/homebrew-core/issues

**Comment by imzhengfei** [comment]
OK, I've created there.
Thx.

**Comment by htulipe** [comment]
For back reference: https://github.com/Homebrew/homebrew-core/issues/16019

**Comment by Verma-Pooja** [comment]
try - brew install yarn --without-node
