### ISSUE TITLE
Because of package hoisting accounting for popular, linking phase takes over 15 minutes

### ISSUE THREAD

**Issue by kenotron** [yarnpkg/yarn#4008]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Since #2676, the package hoister now accounts for the popularity of a package pattern to determine which version to hoist. This requires a complete traversal of the graph. Given our dependency graph, somehow this bit of code takes an unexpectedly long amount of time (>30 minutes).

I've verified that this occurs on a Mac or Windows box.

**If the current behavior is a bug, please provide the steps to reproduce.**
Given that this bug is caused by our internal packages, it is difficult to replicate in a bug. 

**What is the expected behavior?**
I worked around this problem with a hack to stop the prepass from going through more than one occurrence of a pattern temporarily and saw that time to install drop from >30 minutes down to 40 seconds. There should be an option in Yarn to allow for this popularity prepass to be turned off in a config.

**Please mention your node.js, yarn and operating system version.**
node.js 8.1.4
yarn 0.27.5
os Windows 10 / OS X 10.12

**Comment by rally25rs** [comment]
Can you add your `package.json`?

**Comment by kenotron** [comment]
Not sure at the moment what the root cause is: installation is slow even for 0.21.3 before that checkin went into place.

**Comment by kenotron** [comment]
Okay confirmed that the 0.20.4 is fast. Somehow the release notes indicates that 0.21.x didn't have the hoisting fix, but it does.

**Comment by kenotron** [comment]
I have a fix for the slow hoisting issue - please take a look at this #4222

**Comment by kenotron** [comment]
Seeing as this is merged, I'm marking this closed. Thanks @arcanis!
