### ISSUE TITLE
isntall?

### ISSUE THREAD

**Issue by KyleWMiller** [yarnpkg/yarn#4010]
Just a heads up there is a "isntall" option under `$ yarn help`

**Comment by pichouk** [comment]
Seems that the `help` command also generate non-working aliases commands...

**Comment by pichouk** [comment]
For me, `0.27.5`

**Comment by KyleWMiller** [comment]
I found It in version 0.24.6

**Comment by pichouk** [comment]
PR https://github.com/yarnpkg/yarn/pull/3706 should solve this issue I gues

**Comment by BYK** [comment]
Seems like it (at least fixed on master).

**Comment by pichouk** [comment]
Fixed in next release `0.28.x`

**Comment by KyleWMiller** [comment]
I looked at the 0.28.4 release page and I didn't see a release date. Do they post that anywhere?

**Comment by KyleWMiller** [comment]
Also, they say that Yarn 1 && Create is coming soon.
