### ISSUE TITLE
Yarn workspace commands running in wrong location

### ISSUE THREAD

**Issue by JKillian** [yarnpkg/yarn#4021]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn workspace my-package upgrade classnames` changes the `package.json` at the top-level instead of the one at `./packages/my-package/package.json`

**Please mention your node.js, yarn and operating system version.**
Yarn v0.27.5
Node v7.1.0

**Comment by bestander** [comment]
Hey @arcanis, this feature seems to have broken e2e but afaik we have tests covering it

**Comment by arcanis** [comment]
Will be fixed by #4080
