### ISSUE TITLE
New versions of Yarn aren't published to npm

### ISSUE THREAD

**Issue by Vanuan** [yarnpkg/yarn#4022]
https://www.npmjs.com/package/yarn
0.27.5 is the latest of 55 releases

Could you please publish the newest version? The way I install yarn is this:

npm install yarn -g

Isn't that supported anymore?

**Comment by simonkberg** [comment]
0.27.5 is the latest stable release. Seems like the RC version is lagging behind though (v0.28.1 i the latest on npm).

You can install the latest published RC versions using `npm i -g yarn@rc`, though installing via npm is discuraged:

> Note: Installation of Yarn via npm is generally not recommended. When installing Yarn with Node-based package managers, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps.
>
> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

Source: https://yarnpkg.com/en/docs/install#alternatives-tab

**Comment by Daniel15** [comment]
Yeah, 0.27.5 is the latest stable release, so it is installing the correct version.

**Comment by Daniel15** [comment]
I didn't configure the npm publishing correctly. The next RC release will be published to npm with the `rc` tag.
