### ISSUE TITLE
Status bar logged to console after completion message

### ISSUE THREAD

**Issue by aracarie** [yarnpkg/yarn#4023]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Status bar logged to console after completion message is printed.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use latest yarn from master for this:
```
yarn add express
```

You'll see items being logged after the completion message "Done in Xs" is printed. I think it's related to commit 61e402b where `process.exit()` was changed out for `process.exitCode`;

![screenshot](https://user-images.githubusercontent.com/20537648/28596358-1c8bac18-7166-11e7-94c1-a5ce0c074c80.png)

**What is the expected behavior?**
Completion message is the final thing printed.

**Please mention your node.js, yarn and operating system version.**
Node.js v6.11.0 / Yarn latest commit

**Comment by BYK** [comment]
Can this be the solution: https://github.com/yarnpkg/yarn/pull/4067

**Comment by aracarie** [comment]
Just tried with the latest commit from master and it's still showing the additional output.

**Comment by BYK** [comment]
Alright, will check again tomorrow and see if I can repro.

**Comment by BYK** [comment]
@aracarie - Looks like this was an existing issue, masked by the previously used `process.exit()` which cut the output before it can be completed. I'm working on a fix. Thanks for bringing this up!
