### ISSUE TITLE
yarn automatically installs newer versions and updates yarn.lock without warning

### ISSUE THREAD

**Issue by calidion** [yarnpkg/yarn#4037]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
yarn automatically installs newer versions and updates yarn.lock without warning

**If the current behavior is a bug, please provide the steps to reproduce.**

1. yarn install

2. yarn add package@newer-version

3. git reset --hard origin/master

4. yarn install

5. new-version will be installed

6. yarn.lock will be updated with the newer-version

**What is the expected behavior?**

step 5, 6 should not be made.

**Please mention your node.js, yarn and operating system version.**

node: v6.11.0
yarn: 0.24.5
os: ubuntu 16.04

**Comment by BYK** [comment]
@calidion you seem to be using an old version of `yarn`. Can you try this with the latest version and also provide us sample `package.json` and `yarn.lock` files so we can reproduce locally.

**Comment by calidion** [comment]
@BYK 

sorry.
it seems due to the inconsistency between package.json and yarn.lock.
