### ISSUE TITLE
yarn why - couldn't find package workspace-aggregator-[UUID]

### ISSUE THREAD

**Issue by martin-css** [yarnpkg/yarn#4041]
**Do you want to request a *feature* or report a *bug*?**
I think this is a bug - *only applies with the experimental yarn workspaces enabled*.

I was attempting to get the new experimental Yarn workspaces working in my mono repo and discovered `yarn why` isn't working. Issue  #3841 referred to `yarn list` which is working. I wonder if further updates are required for `why` (and possibly any other relevant commands).

**What is the current behavior?**

Running `yarn why` fails with the error below:
 
```
error Couldn't find package "workspace-aggregator-2e092624-1b04-4de1-9847-260953ff91b5" on the "npm" registry.
```
The v4  UUID is random and will change each time.

**If the current behavior is a bug, please provide the steps to reproduce.**

The shell steps below will create a contrived simple repo that reproduces the problem.

```
rm -rf repo
mkdir repo
cd repo
mkdir -p packages/p1
echo '{"name":"repo", "private":true, "workspaces":["packages/*"]}' >package.json
echo '{"name":"p1", "version": "0.0.1"}' >packages/p1/package.json
yarn install
yarn why p1
```

**What is the expected behavior?**

Yarn should show information on why package is installed (i.e. it is package present in the workspace). It should not fail with an error.

**Please mention your node.js, yarn and operating system version.**

Component | Version
--------------- | ---------
Node.JS | v8.2.1
Yarn | v0.28.4
OS | Docker container  `node:8.2.1`

**Comment by cpojer** [comment]
I'm also getting this on Jest. What is this package? cc @bestander

**Comment by arcanis** [comment]
It's a "fake" package that is created during the internal workspace resolution. It should never be publicly visible, but we need to add barriers in some places :)

**Comment by BYK** [comment]
Closed by #4304.

**Comment by levrik** [comment]
Just saw this when doing a `yarn install`:

![image](https://user-images.githubusercontent.com/9491603/34960027-6d309690-fa39-11e7-96e1-c05708ab0896.png)

**Comment by sabrehagen** [comment]
And again on `v1.12.3`

![image](https://user-images.githubusercontent.com/1094600/50371275-a7bb7d00-060b-11e9-9e9d-a4a825490246.png)
