### ISSUE TITLE
Disable emojis if terminal isn't a TTY

### ISSUE THREAD

**Issue by sebmck** [yarnpkg/yarn#405]
No fun allowed.

**Comment by arutkowski00** [comment]
@kittens What about Linux? I want the emoji there...

**Comment by DRSDavidSoft** [comment]
On windows this should be definitely supported:
https://github.com/Microsoft/console/issues/190

**Comment by Daniel15** [comment]
@DRSDavidSoft Based on that thread, it sounds like Windows support isn't fully complete yet.

**Comment by DRSDavidSoft** [comment]
@Daniel15 After eight years in 2024 we can finally (I hope) say that emojis can be used with a good terminal on Windows:

![image](https://github.com/yarnpkg/yarn/assets/4673812/4f33b7b7-918f-4d17-b8fb-8cb050c6bcb3)

Sidenote: In your [original comment](https://github.com/yarnpkg/yarn/issues/405#issuecomment-248804346), Cmder is using [ConEmu](https://conemu.github.io/) which is a great console emulator, albeit it displays emojis in that white color, still it's better than the old `conhost.exe` on Windows.

Of course, [Windows Terminal + Cmder](https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration) trumps all of them!
