### ISSUE TITLE
Single bundle builds are broken

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#4057]
Currently, our single-file, standalone builds are broken. See https://github.com/yarnpkg/yarn/pull/3955#issuecomment-318846631

**Comment by Daniel15** [comment]
Doesn't that mean that every build is broken? All releases use the single-bundle build 😛

**Comment by BYK** [comment]
@Daniel15 the single-file builds do not work as standalone executable files. I edited the description :)
