### ISSUE TITLE
'SyntaxError: missing ) after argument list' running tests on Windows 10

### ISSUE THREAD

**Issue by BurtHarris** [yarnpkg/yarn#4059]
This looks similar to closed issue #3405, its trying to run a shell script as javascript.   Probably because my default shell is PowerShell on Windows.   No shbang support!  Any notes on yarn development on Windows?

**What is the current behavior?**
Running `yarn test` in yarnpkg/yarn on Windows 10 generating failure:

```
C:\code\yarn\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
error Command failed with exit code 1.
error Command failed with exit code 1.
PS C:\code\yarn>
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Public repro yarnpkg/yarn@v0.28.0-53-g5e1eee74

```
yarn
yarn build
yarn test
```

**What is the expected behavior?**
Tests run...

**Please mention your node.js, yarn and operating system version.**

```
PS C:\code\yarn> cmd ver
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.
PS C:\code\yarn> yarn versions
yarn versions v0.27.5
{ yarn: '0.28.0',
  http_parser: '2.7.0',
  node: '6.11.1',
  v8: '5.1.281.103',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
Done in 0.24s.
```

**Comment by bestander** [comment]
Seems related to Jest https://github.com/facebook/jest/issues/3750.
Any ideas how to fix it in Yarn?

I think Jest will fix it and no action would be necessary on Yarn side.

**Comment by BurtHarris** [comment]
@bestander, thanks.   It looks like facebook/jest#3750 has been closed without a fix.   Not knowing anything about jest I'm not sure if that's a good choice or not, but it seems like with both issues closed, it may not get any attention.

**Comment by bestander** [comment]
Fair point, let's bug Jest people. 
I'll comment there

**Comment by BurtHarris** [comment]
👍 P.S> I tried inserting the extra '.js' in yarn's 'test-only' script, after which the errors changed, it looks like the errors have changed.   I now see this from lint:

```
C:\code\yarn\artifacts\yarn-0.28.0.js
  85009:16  error  Parsing error: Invalid number

  85007 | function chmodShim (to, cb) {
  85008 |   var then = times(2, cb, cb)
> 85009 |   fs.chmod(to, 0755, then)
        |                ^
  85010 |   fs.chmod(to + ".cmd", 0755, then)
  85011 | }
  85012 |

C:\code\yarn\artifacts\yarn-legacy-0.28.0.js
  86505:16  error  Parsing error: Invalid number

  86503 | function chmodShim (to, cb) {
  86504 |   var then = times(2, cb, cb)
> 86505 |   fs.chmod(to, 0755, then)
        |                ^
  86506 |   fs.chmod(to + ".cmd", 0755, then)
  86507 | }
  86508 |
```

Earlier I thought all the lint messages were warnings.

**Comment by BurtHarris** [comment]
Oh, I see, the above files must be generated code.

**Comment by BurtHarris** [comment]
I think a fix might be to have yarn's __test-only__ script invoke `node_modules/.bin/jest ...`, allowing the shell to choose between .cmd or shell script.   I'll dig on that a bit and let you know.

**Comment by BurtHarris** [comment]
Progress by using the following command in the __test-only__ script: `node_modules/.bin/jest  --coverage --verbose`.    I haven't figured out yet how to include the `--max_old_space_size=4096`.

Some failures, but it hasn't finished yet.   How long does it normally take for these tests to run?

**Comment by BurtHarris** [comment]
@bestander: it seems like yarn's package file can fix this by replacing the `test-only` line with:

```
    "test-only": "cross-env NODE_OPTIONS=--max_old_space_size=4096 node_modules/.bin/jest  --coverage --verbose",

```

Of course that requires adding the `cross-env` package as a devDependency too.   

But, this doesn't get me to a clean build/test cycle, there are still a lot of test failures.   Some of them are timeouts that seem unreasonable, for example:

 ```
FAIL  __tests__\integration.js (101.485s)
  ● yarn add https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
```
I can open another bug for these

**Comment by BYK** [comment]
>👍 P.S> I tried inserting the extra '.js' in yarn's 'test-only' script, after which the errors changed. I now see this from lint:

`artifacts` folder should have been ignored by lint but forgotten. This is now fixed on latest master.

>@bestander: it seems like yarn's package file can fix this by replacing the test-only line with:

I really don't want to add `cross-env` only for this.

>But, this doesn't get me to a clean build/test cycle, there are still a lot of test failures. Some of them are timeouts that seem unreasonable, for example:

Seems like you are using `yarn` 0.18.1 which is quite old, may be a newer version will fix things?

For the resolution of this issue, I think the following would work:

`"test-only": "node --max_old_space_size=4096 ./node_modules/jest-cli/bin/jest.js --coverage --verbose",`
