### ISSUE TITLE
Wrong location of bin files

### ISSUE THREAD

**Issue by bobahvas** [yarnpkg/yarn#4069]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If  I use `--modules-folder` flag, then modules will be in new folder, but bin files still in node_modules

**Please mention your node.js, yarn and operating system version.**
Win10, node 6.11.2, 0.27.5

**Comment by rally25rs** [comment]
Duplicate of #3724 fixed by #3792
