### ISSUE TITLE
yarn 0.27 doesn't support private repos with passworded ssh keys

### ISSUE THREAD

**Issue by ariabuckles** [yarnpkg/yarn#4079]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
yarn upgrade v0.27.5
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://classjourney@vault.phacility.com/source/artemis.git /Users/aria/Library/Caches/Yarn/v1/.tmp/c457b3a8aae89b5e05178b8f1adeebe7
Directory: /Users/aria/classjourney/universe
Output:
Cloning into '/Users/aria/Library/Caches/Yarn/v1/.tmp/c457b3a8aae89b5e05178b8f1adeebe7'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Add a private repo that is accessible by a passworded ssh key to package.json and run `yarn upgrade`

**What is the expected behavior?**
On a previous version of yarn (I was on 0.24.5) `yarn upgrade` would prompt me to enter the ssh key password (however, the prompt was not done well and interleaved with other output, but it worked). 0.24.5's output looks like:

```
yarn upgrade v0.24.5
[1/4] 🔍  Resolving packages...
⠄ esprima@~3.0.0🔑
```
where 🔑 is the OS X key prompt

**Please mention your node.js, yarn and operating system version.**
```
yarn versions v0.27.5
{ http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.8.283.41',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
Done in 0.04s.
```

**Comment by BYK** [comment]
This is expected. Since yarn normally installs everything in the background, it doesn't allow users to interact with subprocesses (ssh/git in this case). You need to use SSH_AGENT or similar means to avoid password prompts during installation.

**Comment by ariabuckles** [comment]
Understood; I'll look deeper into how to fix my ssh-agent setup, thanks.
