### ISSUE TITLE
Using yarn workspace  with multiple Ember apps doesn't work ?

### ISSUE THREAD

**Issue by asvny** [yarnpkg/yarn#4081]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
 I have enabled workspace feature
 In a repo , I have two ember-cli generated apps say 'a' and 'b' , when I run yarn ... it gets hoisted to root level .. but when navigate to 'a' directory and run 'yarn start' .. it says some packages need to be installed

To reproduce ..
 - git clone https://github.com/asvny/yarn-workspace.git
 - Run yarn install
 - cd a
 - yarn start
 - Error -  It says missing packages

**What is the expected behavior?**
 When running yarn start , the ember-cli should start serving the app , with local dev server

**Please mention your node.js, yarn and operating system version.**
Node - 7.2.1
Yarn - 0.27.5
OS - MacBook Pro (v 10.12.5)

Note: Not really sure ... whether this is because of yarn (or) ember-cli .

**Comment by BYK** [comment]
Hey, thanks for trying out yarn woskpaces. This experimental feature is only available after 0.28.4 AFAIK so can you please try that?

Even better if you try one of our nightlies since we have landed a few important fixes onto master after 0.28.4 released.

**Comment by BYK** [comment]
Closing the issue since this seems to be just due to using an older version of yarn. Feel free to reopen if it turns out otherwise.

**Comment by asvny** [comment]
Thanks ! ... let me get back to u ... after trying beta version

**Comment by asvny** [comment]
I tried with  `Yarn-1.0.0-20170807.1054` ... but I get same issue

**Comment by BYK** [comment]
I think this is an issue with `ember-dependency-checker` and workspaces' hoisting feature because all of the modules it complains about are actually installed in `./node_modules`, just not in `./a/node_modules`. I think `ember-dependency-checker` should mimic the resolution algorithm of `node` instead of simply looking at the working directory or project root.

**Comment by BYK** [comment]
There's a discussion going on about something similar in #3294 so you may wanna follow that.

**Comment by asvny** [comment]
Thanks a lot !

**Comment by bsvipas** [comment]
Same happens for me! All other things works fine, but Ember doesn't, because it's say package is missing.
