### ISSUE TITLE
"undefined is not a function" While Linking bundledDependencies

### ISSUE THREAD

**Issue by epmatsw** [yarnpkg/yarn#4083]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When installing `bundledDependencies`, yarn crashes with:

```
TypeError: undefined is not a function
      at /Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:46638:34
      at Generator.next (<anonymous>)
      at step (/Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:91:30)
      at /Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:109:14
      at Promise (<anonymous>)
      at F (/Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:29587:28)
      at /Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:88:12
      at PackageLinker.linkBinDependencies (/Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:46661:7)
      at /Users/willstamper/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/yarn-cli.js:46914:26
      at Generator.next (<anonymous>)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

This appears to be a bug when linking `bundledDependencies`.

The bug seems to be in `package-linker.js`, [here](https://github.com/yarnpkg/yarn/blob/9099ad4fbc13ea4ceb52a31559327b18ad42a0cb/src/package-linker.js#L100). `pkg.bundleDependencies` is an Object rather than an Array, so that needs to be a `for...in` loop instead of a `for...of`.

**What is the expected behavior?**
No crash.
**Please mention your node.js, yarn and operating system version.**
node 8.2.1, yarn 0.28.1, macOS 10.12

**Comment by arcanis** [comment]
Hm `bundleDependencies` is [an array](https://docs.npmjs.com/files/package.json#bundleddependencies), not an object. It wouldn't make much sense to store version range for a dependency that is bundled. What package causes the issue?

**Comment by epmatsw** [comment]
Ah, good call. PEBKAC. Npm silently ignores a non-Array `bundledDependencies`, which made me think the yarn behavior was unexpected. A nicer error message would be good, but npm’s behavior is probably worse :/

**Comment by BYK** [comment]
May be we can introduce `package.json` schema validation and check that as the first thing?
