### ISSUE TITLE
Cannot pass arguments or options to installed package command

### ISSUE THREAD

**Issue by NonPolynomial** [yarnpkg/yarn#4091]
**Do you want to request a *feature* or report a *bug*?**
This is a *bug* report for version `0.27.5`.

**What is the current behavior?**
If run a NPM script with yarn, commands cannot be found.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using `nuxt` in this example.

Initialize project:
```
$ yarn init -y
$ yarn add nuxt
$ yarn nuxt
... work ...
$ yarn nuxt -- --port 1337
... doesn't work, because the command cannot be found ...
```
*Notice, that I did'nt added a NPM script to `package.json`!*

**What is the expected behavior?**
- command can be found
- command gets passed arguments and options

***The expected behavior can be seen in yarn version `0.24.6`.***

**Please mention your node.js, yarn and operating system version.**
Win 10
`yarn versions`:
```
{ yarn: '0.27.5',
  http_parser: '2.7.0',
  node: '7.0.0',
  v8: '5.4.500.36',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '51',
  openssl: '1.0.2j' }
```

---

I know that I could just add a NPM script to package.json, but this is a bug, which causes problems with backwards compatibility to older yarn versions.

**Comment by kaylieEB** [comment]
Hmm, I'm not having any luck reproducing the issue :( I was able to run the same commands on both latest master and 0.27.5.

**Comment by NonPolynomial** [comment]
Seems to be fixed in newer versions!
