### ISSUE TITLE
No way to opt out of post-install only

### ISSUE THREAD

**Issue by dziamid** [yarnpkg/yarn#4100]
While `yarn install --ignore-scripts` ignores post-install scripts, it also prevents the _Building fresh packages..._ stage of the install.

How do I ignore post-install while keeping the _building of fresh packages_  ?
Or how do I invoke _building of fresh packages_ manually? I haven't found a command that does that.

**Comment by phra** [comment]
still no way to do that?

**Comment by twang2218** [comment]
I have the same issue here, my use case is for Dockerfile. Here is the Dockerfile:

```Dockerfile
FROM node:8 as builder

## Prepare dependencies
WORKDIR /app/
COPY package.json /app/
COPY yarn.lock /app/
RUN yarn --ignore-scripts

## Build
COPY . /app/
RUN yarn build
```

I want to install the dependencies as a layer, then build the package later as another layer, just followed the Dockerfile best practice. And I don't want to execute `postinstall` script in current package for the dependencies installation layer, but I definitely do not want to stop the dependencies building.

I tried `--ignore-scripts` as above, then all the dependencies building process are stopped as well.

For my case, I have `pngquant-bin` in my dependencies tree (not even in package.json of my package), and it has a `postinstall` script:

```json
  "scripts": {
    "postinstall": "node lib/install.js",
    "test": "xo && mocha"
  },
```

So, what can I do if I just want to stop `postinstall` script defined in my `package.json`?

**Comment by anhkind** [comment]
My solution for this is to add a condition to `postinstall` script to make it run just when I need it. 

```
"postinstall": "if [ ! -z \"$NODE_ENV\" ]; then npm run start; else exit 0; fi"
```

The script will run on my app server (with valid `$NODE_ENV`) and totally ignore on my local server (no `$NODE_ENV`)

Hope it'll help.

**Comment by ipmb** [comment]
Here's a workaround:

```json
  "postinstall": "test -n \"$NOYARNPOSTINSTALL\" || yarn run build"
```

You can now optionally prevent the postinstall script from running with:

```bash
$ NOYARNPOSTINSTALL=1 yarn install
```

**Comment by KenEucker** [comment]
I also wish that there was a flag to signal that you do not want to run the postinstall on an entire project just by installing or upgrading a dependency.

In the case of using this package: https://github.com/tylerlong/yarn-upgrade-all/ any project with postinstall scripts will have that postinstall run on every upgrade, which is not ideal. My current workaround is to delete the postinstall script before running yarn-upgrade-all, but a simple flag allowing the user to ignore postinstall would be very handy.

**Comment by johannesjo** [comment]
No update on this? It has been over two years now...

**Comment by akoidan** [comment]
@ipmb  so we drop cross-platform support? I guess windows-base OSes don't have `test`

**Comment by rajivshah3** [comment]
I needed a cross-platform way to do this as well, so I made [skip-postinstall](https://github.com/rajivshah3/skip-postinstall)

```json
{
    "scripts": {
        "postinstall": "skip-postinstall || node-gyp rebuild"
    }
}
```

```shell
SKIP_POSTINSTALL=1 yarn install
```

**Comment by merceyz** [comment]
Closing as fixed in v2 where you can run `yarn install --skip-builds` then later do `yarn rebuild` to trigger them

https://yarnpkg.com/getting-started/migration
https://yarnpkg.com/cli/install#options-skip-builds
https://yarnpkg.com/cli/rebuild

**Comment by leikoilja** [comment]
@merceyz, there is no even an option of `skip-builds` in the latest docs :/

**Comment by merceyz** [comment]
It was renamed to `--mode skip-build`, I've updated my comment

**Comment by oliverlockwood** [comment]
@rajivshah3 I've been making use of your lightweight `skip-postinstall` package for a few months now (very helpful, thanks!), but now I get warnings and https://www.npmjs.com/package/skip-postinstall says it's deprecated.
I raised issue https://github.com/rajivshah3/skip-postinstall/issues/1 on your project. Are you planning to resolve this or are you considering the mini-project to be abandoned?

**Comment by bluehymn** [comment]
I check the environment by INIT_CWD in my install script
if (process.env.INIT_CWD !== process.cwd()) {
   doSomethingPostInstall()
}

**Comment by cwtuan** [comment]
I want to disable a specific dependency's `postinstall`. Is that possible?

**Comment by devthejo** [comment]
Here is my workaround:
https://github.com/devthejo/yarn-plugin-fetch/tree/master#production

**Comment by andrew-aladjev** [comment]
From my point of view `postinstall` script will be launched 2 times: during `yarn install` in current project context and during `yarn install` in different context (dependency installation). So you have to somehow separate this 2 cases. Also you need to allow user to stop this script. So I've provided the following solution:

```sh
"postinstall-script": "sh -c 'if [ -f ./dist/postinstall.js ]; then node ./dist/postinstall.js; fi'",
"postinstall": "sh -c 'if [ ! \"$<PROJECT_NAME>_NO_POST_INSTALL\" ]; then yarn postinstall-script; fi'"
```

It depends on `bash`, but today `bash` installation is not a big deal for Windows and OSX.

**Comment by leaftail1880** [comment]
Easiest cross-platform way:
```json
"postinstall": "node -e \"process.env.NO_POSTINSTALL===1&&process.exit(1)\" || your-script"
```
