### ISSUE TITLE
yarn init --private

### ISSUE THREAD

**Issue by pierreneter** [yarnpkg/yarn#4113]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Should we add the option to use `yarn init` to create a private project?
Like:
```
yarn init -p
yarn init --private
yarn init -yp
yarn init --yes --private
```
Every time I want to create a private project, I have to edit `package.json`. Very time consuming.
This feature also is not available in the `npm`.
One day I have to create a lot of private projects to test and it goes on and on

**What is the expected behavior?**
Create a `package.json` file with format:
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true
}
```

**Comment by kaylieEB** [comment]
I like the idea :) The code is here: https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/init.js if you want to submit a PR

**Comment by nikshepsvn** [comment]
Hey @kaylieEB, this would be my first open source contribution -- mind if I give it a go?

**Comment by kaylieEB** [comment]
Hey @nikshepsvn! It looks like @pierreneter has a PR for this that's been open for some time https://github.com/yarnpkg/yarn/pull/4165. You can either comment on the PR if you want to pick up where he left off or we also have other issues tagged with `good-first-contribution` here https://github.com/yarnpkg/yarn/labels/good-first-contribution
