### ISSUE TITLE
Add the yarn re-route feature to .yarnc

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#4115]
The way we use Yarn at Facebook is by specifying a path in the `.yarnc` file that points to a single file bundle or entry point of Yarn. If the global version of Yarn is executed in a folder (or parent folder) with a `.yarnrc` with that setting, it should use that version of Yarn instead. This ensures that the same version of Yarn is used for the same project.

Beware of infinite re-directs.

**Comment by arcanis** [comment]
So the plan is:

- first we try to execute the file as a Javascript file with `child_process.fork`
- then if it failed, we try to execute it via `child_process.spawn`

**Comment by cpojer** [comment]
Instead of running it in a child process, is there any way we could require the file, if it's JS?

**Comment by arcanis** [comment]
We could, but I'm not completely sure what would be the possible side effects, for example regarding `process.argv[1]`.

**Comment by arcanis** [comment]
Implemented by #4204
