### ISSUE TITLE
globs are handled differently

### ISSUE THREAD

**Issue by edgarjs** [yarnpkg/yarn#4118]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- My test command declared in `package.json` is `NODE_ENV=test mocha --compilers js:babel-register --recursive ./test/**/*.test.js`; which if a run directly, it runs the tests for all my files including one directly under `./test/digestor.test.js`, but when I run it via `yarn test`, it only executes the test files that are at a second level of depth (in other words, it doesn't run `./test/digestor.test.js`).

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone repository at https://github.com/edgarjs/yarn-bug
2. Install the dependencies.
3. Run `yarn test` and see results.
4. Run `NODE_ENV=test mocha --compilers js:babel-register --recursive ./test/**/*.test.js` and compare results from step 3.

**What is the expected behavior?**
Step 3 should run the same tests as step 4.

**Please mention your node.js, yarn and operating system version.**
OS: macOS Sierra 10.12.6
Node: 6.11.1
Yarn: 0.27.5

---

![yarn-bug 2017-08-08 3hnqr](https://user-images.githubusercontent.com/12443/29073787-8a78a15c-7c12-11e7-9b0f-c23d873c86aa.png)

**Comment by mitermayer** [comment]
looks like yarn is not respecting the globstar flag. @edgarjs  in the meantime you can do this workaround on your package.json

```javascript
  "scripts": {
     "foo":  "shopt -s globstar && bar **/src/**/*.js",
  }
```

**Comment by BYK** [comment]
Yarn doesn't do anything with globs at all. It simply passes these to `bin/sh` on Unix systems. Either you had a global mocha installed which was supporting globstar where as your package-specific mocha was not supporting it, or sh/bash was not handling globstar properly.

We've changed the way we invoke scripts slightly so you may wanna give 1.0.2 a shot to see if it fixes your issue. If it doesn't I'd try running the following to see if all behave the same way:
```
NODE_ENV=test mocha --compilers js:babel-register --recursive ./test/**/*.test.js
NODE_ENV=test yarn mocha --compilers js:babel-register --recursive ./test/**/*.test.js
NODE_ENV=test ./node_modues/.bin/mocha --compilers js:babel-register --recursive ./test/**/*.test.js
```

**Comment by rally25rs** [comment]
You are probably using `zsh`, aren't you? `zsh` uses different globbing rules than standard `sh`, and by default npm and yarn spawn commands in `sh`

**Comment by edgarjs** [comment]
Yes I’m using zsh. Thanks

**Comment by rally25rs** [comment]
Going to close this as it's a shell implementation difference (zsh vs sh).
