### ISSUE TITLE
Version 0.28.4 not posted to npm

### ISSUE THREAD

**Issue by elderfo** [yarnpkg/yarn#4126]
**Do you want to request a *feature* or report a *bug*?**
Not really a bug

**What is the current behavior?**
When using [gradle-node-plugin](https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md), it uses npm to get specific versions of yarn for installing. Version `0.28.4` is not posted.

Verified with:
```bash
$ npm view yarn dist-tags versions
dist-tags = { latest: '0.27.5', rc: '0.28.1' }
versions =  
[ '0.1.0',
...
  '0.27.5',
  '0.28.1' ]
```

**What is the expected behavior?**
The public RC should be available on the npm registry

**Comment by ddtramp** [comment]
will be fix in 0.28

**Comment by Daniel15** [comment]
Oops, good catch! Not sure how that happened. I'll see what we can do.

**Comment by Daniel15** [comment]
Should be fixed now.

**Comment by elderfo** [comment]
Thank you!
