### ISSUE TITLE
Upgraded from 21.x to 27.5

### ISSUE THREAD

**Issue by Slapbox** [yarnpkg/yarn#4127]
Adding any package now results in the following:

    Error: EISDIR: illegal operation on a directory, open 'C:\Users\Username\AppData\Local\Yarn\cache\v1\npm-d-0.0.0-eb074530-5898-4c57-9692-2e51c2d26981-1502232609442'

Each package gets its own unique failure path, but always the same message.

    Error: EISDIR: illegal operation on a directory, open 'C:\Users\Username\AppData\Local\Yarn\cache\v1\npm-d-0.0.0-525aa498-417d-4e54-b1e5-8dd4c989b2ac-1502232991967'

**Comment by Slapbox** [comment]
After updating to the 28.4 RC I get:

    error An unexpected error occurred: "ENOTDIR: not a directory, scandir 'C:\\Users\\Username\\AppData\\Local\\Yarn\\cache\\v1\\npm-domelementtype-0.0.0-7b886c5c-5eeb-46d1-bb93-6fe82ed55906-1502252724009'"

**Comment by Slapbox** [comment]
I have tried clearing cache and rebooting the machine. I am running the terminal as admin. I get identical errors in `cmd` and `babun` on Windows 7.

**Comment by Slapbox** [comment]
Reinstalled 21.3 and have no issues at all.

**Comment by BYK** [comment]
Can you stick to the issue template and provide us concrete reproduction steps please?

**Comment by BYK** [comment]
Also I'd suggest trying one of the nightlies to see if this is already resolved on master.

**Comment by Slapbox** [comment]
Node version is 7.7.3.
OS is Windows 7 Professional x64.

I can't provide a repo or any steps besides `yarn add [packagename]`

This fails locally and globally with the errors I included above, no matter what package. That's it. This issue occurs on any and all `add` operations in those versions on `Yarn`. No issues with 21.3 though.

**Comment by BYK** [comment]
>I can't provide a repo or any steps besides yarn add [packagename]

Without anything more, I'm afraid we cannot help since we cannot debug your system. My assumption is a permissions or file system issue specific to your system but you need to figure that out and report back here.

If you can provide more details, I'm more than happy to help but with this very limited information, I'm inclined to close the ticket because it is not actionable.

Will wait for you to try out the nightlies and may be do some more digging on your end before closing tho.

**Comment by Slapbox** [comment]
Go ahead and close it then. I already did all the usual folder permissions troubleshooting prior to posting, cleared my caches, tried a full uninstall and reinstall, etc... I'll just use 21.3 I guess.
