### ISSUE TITLE
Running yarn in workspace dir, complains that packages are not on NPM registry

### ISSUE THREAD

**Issue by houshuang** [yarnpkg/yarn#4137]
Using Yarn 0.28.4, I create a yarn workspace with two directories, `blue` and `red`. `red` depends on blue. Everything works fine, I can open node in `red`, and require `blue`, and it resolves. However, when I try `yarn add` in `red`, it tells me that it cannot find `blue` in the npm registry (since I have not published the package).

It should see that `blue` is provided by the workspace, and not try to install it from the registry. 

Example repo: https://github.com/houshuang/yarntest

**Comment by BYK** [comment]
Can't reproduce this on master. Can you try the nightlies to see if it is fixed? We've just landed a few fixes today and yesterday so they may be relevant too.

**Comment by houshuang** [comment]
Fixed in nightly.
