### ISSUE TITLE
html-webpack-plugin fails to install

### ISSUE THREAD

**Issue by tehlordvortex** [yarnpkg/yarn#4156]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn add html-webpack-plugin` fails:
```

yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\
\Users\\Vortex\\Documents\\Coding\\Electron\\iplan-vue\\node_modules\\.bin\\acor
n'".
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\Users\\Vortex\\Documents\\Coding\\Electron\\iplan-vue\\yarn-erro
r.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this comm
and.
```

[yarn-error.txt](https://github.com/yarnpkg/yarn/files/1219300/yarn-error.txt)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn add webpack
yarn add vue
yarn add electron@1.6.11
yarn add vue-material
yarn add vue-router
yarn add style-loader css-loader
yarn add file-loader
yarn add html-webpack-plugin
```

**What is the expected behavior?**
html-webpack-plugin should be installed

**Please mention your node.js, yarn and operating system version.**
Node 8.3.0, yarn 0.27.5, Windows 8.1

**Comment by arcanis** [comment]
> error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\
\Users\\Vortex\\Documents\\Coding\\Electron\\iplan-vue\\node_modules\\.bin\\acor
n'".

That doesn't look like a Yarn error. It seems like your OS is preventing it to delete a file. Either there's something wrong in your permissions scheme, or you have an antivirus that might be a bit overprotective.

**Comment by Daniel15** [comment]
I've sometimes seen this when some app has locked the file. Unfortunately Node.js throws extremely generic error messages, which doesn't help. Try running [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to find what's holding onto the file: Click Find &rarr; Find Handle or DLL, enter a part of the locked file name (eg. `iplan-vue\node_modules\.bin\acorn`) and click "Search".

**Comment by arcanis** [comment]
I'm going to close this one, it unfortunately doesn't look actionable on our side.
