### ISSUE TITLE
Install Script Warnings/Errors output without Line Breaks

### ISSUE THREAD

**Issue by tolgabalci** [yarnpkg/yarn#4158]
**Do you want to request a *feature* or report a *bug*?**
Bug (likely a Windows only bug)

**What is the current behavior?**
Warnings/Errors from install scripts do not contain line breaks (line returns), making them almost impossible to read.

**If the current behavior is a bug, please provide the steps to reproduce.**
I ran in to this with the current version of Firebase Tools which seems to have an issue:
yarn global add firebase-tools

**What is the expected behavior?**
The Warning/Error is correct to show here (there is a legitimate issue), however the output should have line breaks, making it readable.  Running npm install -g firebase-tools results in the same Warning/Error, but with proper line breaks.

**Please mention your node.js, yarn and operating system version.**
Windows 7 SP1 Enterprise
Node v8.3.0
Yarn 0.27.5
Powershell 5.0 and Cmd.exe (Yarn outputs Warnings/Errors without line breaks on both)

**EXAMPLE OUTPUT WITH LINE BREAKS MISSING**
[1/1] ⡀ node-zopfli: '-Goutput_dir=.' ]
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
warning Error running install script for optional dependency: "C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-zopfli: Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c node-pre-gyp install --fallback-to-build\nDirectory: C:\\User
s\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-zopfli\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.36\nnode-pre-gyp info using node@8.3.0 | win32 | x64\nnode-pre-gyp info check checked for \"C:\\Users\\tbalci\\AppData\\Local\
\Yarn\\config\\global\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node\" (not found)\nnode-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v57-win32-x64.tar.gz\nnode-pre-gyp http 403 https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-
node-v57-win32-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v57-win32-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@8.3.0 (node-v57 ABI) (falling back to source compile with node-gyp
) \nnode-pre-gyp http 403 status code downloading tarball https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v57-win32-x64.tar.gz \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.3.0 | win32 | x64\ngyp info ok \ngyp info it worked if it ends
with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.3.0 | win32 | x64\ngyp info spawn C:\\Users\\tbalci\\.windows-build-tools\\python27\\python.exe\ngyp info spawn args [ 'C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.p
y',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=2017',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\
\node_modules\\\\node-zopfli\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\tbalci\\\\
.node-gyp\\\\8.3.0\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\tbalci\\\\.node-gyp\\\\8.3.0',\ngyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\tbalci\
\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\tbalci\\\\.node-gyp\\\\8.3.0\\\\<(target_arch)\\\\node.lib',\ngyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\g
lobal\\\\node_modules\\\\node-zopfli',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\
node_modules\\\\node-zopfli\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\nTraceback (most recent call last):\r\n  File \"C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\gyp_main.py\", line 16, in <module>\r\n    sys.exit(gyp.script_main())\r\n  File \"C:
\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 545, in script_main\r\n    return main(sys.argv[1:])\r\n  File \"C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 5
38, in main\r\n    return gyp_main(args)\r\n  File \"C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 514, in gyp_main\r\n    options.duplicate_basename_check)\r\n  File \"C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\no
de_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 98, in Load\r\n    generator.CalculateVariables(default_variables, params)\r\n  File \"C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1916, in CalculateVariables\r
\n    generator_flags.get('msvs_version', 'auto'))\r\n  File \"C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\MSVSVersion.py\", line 434, in SelectVisualStudioVersion\r\n    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version
)\r\nKeyError: '2017'\r\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\lib\\configure.js:336:16)\ngyp ERR! stack     at emitTwo (events.js:
125:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:213:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)\ngyp ERR! System Windows_NT 6.1.7601\ngyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\tbalci\\\\AppData\\\\
Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-zopfli\\\\lib\\\\binding\\\\node-v57-win32-x64\\\\zopfli.node\" \"--mod
ule_name=zopfli\" \"--module_path=C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-zopfli\\\\lib\\\\binding\\\\node-v57-win32-x64\" \"--msvs_version=2017\"\ngyp ERR! cwd C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-zopfli\ng
yp ERR! node -v v8.3.0\ngyp ERR! node-gyp -v v3.6.2\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'C:\\Program Files\\nodejs\\node.exe C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\bin\\node-gyp.js configure --f
allback-to-build --module=C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node --module_name=zopfli --module_path=C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-zopfli\\lib\\binding\\node-v57-wi
n32-x64 --msvs_version=2017' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-pre-gyp\\lib\\util\\compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:125:13)\nnode-pre-gyp ERR! stack     at Chil
dProcess.emit (events.js:213:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)\nnode-pre-gyp ERR! System Windows_NT 6.1.7601\nnode-pre-gyp ERR! command \"C:\\\\Program
 Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\tbalci\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd C:\\Users\\tbalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-zopfl
success Installed "firebase-tools@3.9.2" with binaries:
      - firebase
warning No license field
Done in 79.65s.

**Comment by knz** [comment]
Not only windows. FreeBSD too.
