### ISSUE TITLE
Can't install glob-fs

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/yarn#4168]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I run `yarn add glob-fs` I get:

```
error An unexpected error occurred: "https://codeload.github.com/jonschlinkert/micromatch/tar.gz/5017fd78202e04c684cc31d3c2fb1f469ea222ff: Request failed \"404 Not Found\"".
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just run `yarn add glob-fs`

**What is the expected behavior?**

The dependency should get installed properly.

**Please mention your node.js, yarn and operating system version.**
```
❯ node -v
v8.1.2

❯ yarn --version
0.27.5

❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29
```

**Additional informations.**

`npm i glob-fs` works just fine, if I manually open the URL in the browser, it downloads the tar.gz correctly.

**Comment by arcanis** [comment]
Hm, it works for me :/ We'll need a more detailed reproduction script. It might be related to your package.json and/or your lockfile as well.

**Comment by FezVrasta** [comment]
I get it consistently:

```

❯ cd /tmp


❯ mkdir test


❯ cd test
/tmp/test


❯ yarn add glob-fs
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/jonschlinkert/micromatch/tar.gz/5017fd78202e04c684cc31d3c2fb1f469ea222ff: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/private/tmp/test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by arcanis** [comment]
That's really weird. I follow the same step as you, but I don't have any error, and I don't see what could cause a different behavior. Can you try with the [nightly build](https://yarnpkg.com/en/docs/nightly)?

**Comment by FezVrasta** [comment]
it does work with the nightly :-(

**Comment by BYK** [comment]
>it does work with the nightly :-(

Why the sad face? It means it is fixed and you'll be able to use the fixed version soon! (or now if you are okay using nightlies, which should be safe)

**Comment by FezVrasta** [comment]
I'm sad because:

1. I did nothing weird to get the stable version (that we use in production) to fail this way
2. Re-installing the stable version, I don't get the error anymore

This means that the stable version is not reliable...

**Comment by FezVrasta** [comment]
Aaaand.. wait wait wait...

I did something "weird", I did enabled the workspaces:

```
yarn config set workspaces-experimental true
```

Enabling workspaces in stable I get the error, enabling them in nightly everything works.

**Comment by arcanis** [comment]
By any chance, do you have the always-auth option somewhere in your npmrc or yarnrc? I think we fixed something related to this some time ago.

**Comment by FezVrasta** [comment]
Yes I have it in my global `npmrc` to make Artifactory work

**Comment by arcanis** [comment]
That's probably it then :) Just use the currently nightly, it should be stable enough anyway for most purposes.
