### ISSUE TITLE
yarn list with resolutions gives "expected manifest" error

### ISSUE THREAD

**Issue by magnushiie** [yarnpkg/yarn#4178]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A package using the resolutions feature from #4105 causes `yarn list` to error out:

```log
yarn list v1.0.0-20170815.1354
warning package.json: No license field
warning No license field
warning Resolution field "react@16.0.0-beta.5" is incompatible with requested version "react@16.0.0-alpha.4"
error An unexpected error occurred: "expected manifest".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Temp\\resolutions\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/list for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
package.json:
```js
{
  "resolutions": {
    "@react-pdf/core/react": "16.0.0-beta.5"
  },
  "dependencies": {
    "@react-pdf/core": "^0.4.1",
    "react": "^16.0.0-beta.5",
    "yoga-layout": "^1.6.0"
  }
}
```

```sh
yarn install
yarn list react
```

**What is the expected behavior?**
No error

**Please mention your node.js, yarn and operating system version.**
- node.js: 8.1.1
- yarn: nightly (v1.0.0-20170815.1354)
- OS: Windows 10.0.15063

**Comment by kaylieEB** [comment]
thanks for reporting! I'll look into this.
