### ISSUE TITLE
The 0.27.5 version does not support offline installation

### ISSUE THREAD

**Issue by dkvirus** [yarnpkg/yarn#4184]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
i want to test offline installation function ,but failed.

**If the current behavior is a bug, please provide the steps to reproduce.**

- step1: create a project named yarn-demo;
- step2: `$ npm install yarn -g`
- step3: install express package use yarn cli `$ yarn add express`
- step4: Delete the node_modules from the root directory
- step5: Disconnect network
- step6: `$ yarn`
- step7: The terminal error message is as follows：
```
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
```

**What is the expected behavior?**

The 0.15.0 version test can be used, but the 0.27.5 test fails

**Please mention your node.js, yarn and operating system version.**
- nodejs version: 6.9.0
- yarn version:0.27.5
- operating system:Window 7

**Comment by BYK** [comment]
I can't replicate this on the latest master. Also Facebook uses this feature for thousands of times a day so it is very likely that you have a configuration error. I'd suggest checking your `yarn-offline-mirror` config key in your `.yarnrc` file.

Also my suggestion is to use the `--offline` flag to use the offline mirror feature.
