### ISSUE TITLE
'Yarn' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by duycoder** [yarnpkg/yarn#4199]
- Using nodeJS v8.2.1
- Yarn 0.15.0 ( the lattest version in this time )
I installed yarn on my windows 7 computer by Chocolately. The installation was success but then i write this command to test : "yarn --version", the cmd said : 'Yarn' is not recognized as an internal or external command, operable program or batch file. Anyone know how to solve this problem ?

**Comment by Daniel15** [comment]
Yarn 0.15.0 is very old now 😄  please try v0.27.5 which is the latest stable version.

**Comment by duycoder** [comment]
Tks Daniel15 :)

**Comment by vishrantgupta** [comment]
If you are using windows check if `C:\Program Files (x86)\Yarn\bin` is in your `path` variable. If not after adding in `path` variable open new `cmd`

**Comment by MaungC** [comment]
Try like this
```npm install yarn -g

**Comment by SaqibAltaf** [comment]
You might be able to install Yarn locally with

npm i -S yarn and then
add it to your path SET PATH=%PATH%;c:\to\your\project\node_modules\.bin\yarn
Now in the same terminal window you can use it with yarn install ..

**Comment by RITUait** [comment]
After installing by .msi file , if not recognized in command prompt then in your environment variables path add C:\Program Files (x86)\Yarn\bin .  C:\Users\Ritu\AppData\Local\Yarn\bin; was added  in environment variable path by .msi file itself while installation, in addition to that i added C:\Program Files (x86)\Yarn\bin also . I am not sure why it is happening, even in latest versions also.

windows 10
npm version : 6.5.0
node version : 8.12.0
yarn version : 1.13.0

**Comment by EliotCao** [comment]
> After installing by .msi file , if not recognized in command prompt then in your environment variables path add C:\Program Files (x86)\Yarn\bin . C:\Users\Ritu\AppData\Local\Yarn\bin; was added in environment variable path by .msi file itself while installation, in addition to that i added C:\Program Files (x86)\Yarn\bin also . I am not sure why it is happening, even in latest versions also.
> 
> windows 10
> npm version : 6.5.0
> node version : 8.12.0
> yarn version : 1.13.0

may be helpful for you
https://github.com/yarnpkg/yarn/issues/2504#issue-201894785

**Comment by egemenakturk** [comment]
> Try like this
> `npm install yarn -g`

this solution makes a yarn path specified. This was the solution to my problem.

**Comment by Rajnikantlodhi** [comment]
If you are facing this error yarn : The term 'yarn' is not recognized as the name of a cmdlet, function, script file, or operable program. then Just run this command
`npm install -g  yarn`

**Comment by mostafakhavari** [comment]
> Try like this
> `npm install yarn -g`

this code is worked for me thanks
