### ISSUE TITLE
"Sparse" workspaces

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#4207]
Running `yarn install` inside a workspace installs the dependency for all the workspaces (because we effectively go to the root of the workspace and run `yarn install` from there). This should be improved in such a way that running `yarn install` inside a workspace will only install this workspace's dependencies (plus those required by any other workspace that we depend on).

Subtlety: we should be careful and preserve the file hierarchy, even if it's a partial install (ie. we should apply the hoisting process before cutting unneeded dependencies from the tree). Otherwise, we might have disparities in which modules are required when doing sparse installs vs full installs.

**Comment by BYK** [comment]
Similar #4219 (definitely not the same)

**Comment by cappslock** [comment]
Just got bit by this, which unfortunately is requiring me to use Lerna instead. So yeah, +1.

**Comment by tamlyn** [comment]
Is this just a performance optimisation when working with large workspaces? I don't think the current default behavior should change as being able to run yarn from anywhere in the project is one of the nice improvements over lerna.

**Comment by cappslock** [comment]
As far as I can tell that's the main/only use case. I like the default behavior, but being able to opt in to scoping installs to a workspace and its dependencies would be very helpful for this sort of use case.

**Comment by RyanMcDonald** [comment]
I also just ran into this. I have been using yarn workspaces to manage a repository of lambda functions. Workspaces allow me to share code between the lambda functions, so the shared code gets bundled as a dependency before uploading to AWS.

In my case, I was using `--modules-folder` to have a fresh install of one function's dependencies, but that folder ended up including all dependencies from every workspace because of this issue. 😞

**Comment by denkristoffer** [comment]
This could bring big improvements to CI runs for our monorepo, so it would be a welcome addition 👍

**Comment by arcanis** [comment]
I believe sparse checkouts are a false solution. What I believe matter are fast install times and increased stability - the way it's implemented doesn't matter per se.

The way I'm working on that is through [zero-installs](https://github.com/yarnpkg/berry/blob/master/docs/zero-install-cis.md) which will come starting from the v2.

**Comment by cappslock** [comment]
@arcanis I think you're correct for many cases, but keep in mind that total bundle size can be relevant.

**Comment by robchristian** [comment]
This is definitely needed. If we have a repo where the dependencies in ProjectA are failing to install correctly for certain team members (perhaps platform issues), those members will be blocked even if they aren't working on ProjectA. Being able to install only the dependencies for ProjectB and not ProjectA would likely unblock them (assuming ProjectB doesn't share the same failing dependencies).

Aside from that, it also just saves people a lot of time if ProjectA dependencies take much more time to install than ProjectB.

**Comment by aleclarson** [comment]
This would be great for making small contributions to monorepos. For me, it took 8 minutes to install all of Jest's dependencies, when I only wanted to work on a specific package of theirs. This feature would help reduce barrier to entry for contributors at least a little bit. :)

**Comment by arcanis** [comment]
This behavior is implemented in Yarn 2+ via `yarn workspaces focus`, and the fix will not be backported in 1.x. Please check the [Migration guide](https://yarnpkg.com/getting-started/migration#step-by-step) and continue from there.
