### ISSUE TITLE
don't always assume `yarn install`

### ISSUE THREAD

**Issue by championswimmer** [yarnpkg/yarn#4216]
If you type `yarn --verison` (notice spelling mistake, instead of _version_ ), it finds that there are no valid flags and simply starts `install` script. 

If I was just trying to check yarn version, I end up with a yarn.lock file in my directory, if my flag has a typo. 

I recommend, if there are any flags, then do not simply assume `yarn install`. Yarn just keeps polluting random spaces with yarn.lock files this way.

**Comment by arcanis** [comment]
Problem is that `install` accepts flags, so we would have to make the distinction between install flags and the others. Improving the command line to allow this kind of things is on the long term plans, but no ETA yet.

**Comment by deecewan** [comment]
could you check and see if there are options, but they're not valid install options, error?

**Comment by paul-soporan** [comment]
Closing as this has been fixed in v2.

https://yarnpkg.com/getting-started/migration
