### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by haf** [yarnpkg/yarn#4217]
```
$ yarn install 
error An unexpected error occurred: "https://registry.yarnpkg.com/stack-generator/-/stack-generator-2.0.2.tgz: Request failed \"500 Internal Server Error\"".

yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in ...
```

(That information is on a build-server docker container, and it doesn't reproduce locally.)

yarn.lock

[yarn.lock.zip](https://github.com/yarnpkg/yarn/files/1238804/yarn.lock.zip)

 that crashes when running `yarn install`.

**Comment by arcanis** [comment]
Not sure there's anything actionnable here, since it's a 500 error, and it can come from the yarn registry as well as the npm registry. Just retry, and it should work.

**Comment by haf** [comment]
It's failed three times, on different packages... Where can I file the issue about the internal server error? Or is a transient error, you think?

**Comment by BYK** [comment]
I think this was a transient error so closing the issue. Reopen if you are still having the issue with more details, please.
