### ISSUE TITLE
Publish lockfile parser as @yarnpkg/lockfile

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#4221]
What the title says.

**Comment by Daniel15** [comment]
PR to rename package to `@yarnpkg/lockfile`: https://github.com/yarnpkg/yarn/pull/4215

**Comment by Daniel15** [comment]
Published: https://yarn.pm/@yarnpkg/lockfile

**Comment by wmhilton** [comment]
@Daniel15 Quick question: going forward the `@yarnpkg/lockfile` module's exports will be a public-facing API. Should `implodeEntry` and `explodeEntry` be part of that? A quick grep shows `implodeEntry` is only used once, in `cli/commands/generate-lock-entry.js` and `explodeEntry` is never used outside of `lockfile/index.js`. It's a minor thing, but keeping the surface area of the API small might help prevent accidental breakage in the future.

```
> node                                       
> yarn = require('@yarnpkg/lockfile')        
{ parse: [Getter],                           
  stringify: [Getter],                       
  implodeEntry: [Function: implodeEntry],    
  explodeEntry: [Function: explodeEntry],    
  default: [Function: Lockfile] }            
>                                            
```

**Comment by Daniel15** [comment]
That sounds reasonable to me. Feel free to submit a pull request if you like!

**Comment by wmhilton** [comment]
I'll see if I can get around to it... I've got a lot of TODOs today
