### ISSUE TITLE
Using yarn to install datatables-buttons breaks the package

### ISSUE THREAD

**Issue by krve** [yarnpkg/yarn#4223]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When installing `datatables-buttons` via yarn and requiring the `buttons.colVis.js` file the package breaks , but installing via `npm install` works. The compilation is done using webpack, specifically laravel-mix.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install the following packages using `yarn`
- jquery
- datatables.net
- datatables.net-bs
- datatables.net-select
- datatables.net-buttons
- datatables.net-buttons-bs

2. Setup a source JS file
```javascript
require('jquery');
require('datatables.net');
require('datatables.net-bs');
require('datatables.net-select');
require('datatables.net-buttons');
require('datatables.net-buttons-bs');
require('datatables.net-buttons/js/buttons.colVis.js');

var table = $('#example').DataTable({
    buttons: ['colvis']
});

table.buttons().container()
    .appendTo( '#example_wrapper .col-sm-6:eq(0)' );
```

3. Create a `<table>` and give it an id of `#example`

4. Compile the source file using webpack (I used laravel-mix) and open the site.

5. The error should be `Uncaught Unknown button type: colvis`.

**What is the expected behavior?**
A button should be shown saying `Column visibility` that should look like a bootstrap button

**Please mention your node.js, yarn and operating system version.**
Ubuntu 16.04, Yarn v0.27.5, Node v6.10.0

I've created a repo with reproduceable code.
https://github.com/krve/dtbs

**Comment by mnpenner** [comment]
I think you're missing a couple repro steps.

1. `git clone https://github.com/krve/dtbs.git`
2. `cd dtbs`
2. Run `npm i` to install the dependencies
3. Run `npm run production` to make a production build
4. `cd dist`
5. `npx http-server` (won't work just by double-clicking index.html)

Looks like this with npm:

![image](https://user-images.githubusercontent.com/1112998/29575671-16651daa-871a-11e7-947d-3e1db8b30f32.png)

------

With yarn:

1. `git clone https://github.com/krve/dtbs.git`
2. `cd dtbs`
2. `yarn`
3. `yarn production`
4. `cd dist`
5. `npx http-server` (won't work just by double-clicking index.html)

And.... it actually looks identical to me.

Tested with

- yarn 0.27.5
- npm 5.3.0
- node v7.10.1
- Ubuntu 16.04

Could you list your steps if you did something different? How did you serve the files?

**Comment by krve** [comment]
I used `php -S localhost:8000` in the dist folder, so basically the same as you.

Just tried following your steps, with a clean codebase for both yarn and npm. With npm it works, but I still get the following issue when using yarn

![image](https://user-images.githubusercontent.com/5139119/29577639-732bc9d8-876c-11e7-9635-738f83e22370.png)

I also just tried on another computer with:
* yarn 0.27.5
* npm 5.3.0
* node v6.11.2
* Ubuntu 16.04

Same issue.

**Comment by krve** [comment]
I just checked the compiled code when using `npm i` vs `yarn` and the compiled JS seems to be different. Yarn has the code *reversed* compared to npm. I'm guessing this is intended?

**Comment by mnpenner** [comment]
Our versions are identical aside from Node. That couldn't be the culprit, could it?

AFAIK yarn is supposed to be deterministic -- it always installs the packages the same way -- whereas npm, I'm not sure if they fixed it yet, but it might resolve a bit differently each time.

You've got a `yarn.lock` file in there too. It should have came out the same for both of us. Weird.

**Comment by krve** [comment]
I just tried with node v8.4.0, but still no change. I also tried removing the extraction into a `vendor.js` file, but that didn't do anything either.

Could you perhaps try zipping the folder when installed using yarn and sending it to me? I'd like to see if it is the installation part that breaks at my end.

**Comment by mnpenner** [comment]
@krve Weird. Just tried it again and I'm seeing the same error you are now. https://transfer.sh/RkPIq/dtbs.tar.gz

Did it twice with yarn, got the same error both times.

... But I'm also seeing the error with npm now.

I have no idea what's going on.

**Comment by krve** [comment]
@mnpenner NPM still works for me.

Just to be sure we're doing the same.

**Case 1**
- `npm i`
- `npm run production` OR `yarn production` (This doesn't seem to matter on my end)
- `cd dist`
- `npx http-server`
- The buttons works and looks like a bootstrap button

**Case 2**
- `yarn`
- `npm run production` OR `yarn production` (This doesn't seem to matter on my end)
- `cd dist`
- `npx http-server`
- The console throws and error message about the colvis button not being defined

And between these two tests I remove the `rm -rf node_nodules` to make sure i start from a clean slate.

Now from what I can see, the problem lies somewhere in the way npm and yarn handles installing the packages, since it works with either `npm run production` or `yarn production`.

I'll keep trying different things to see if I can't pin down the issue.

**Comment by krve** [comment]
I got it to work with yarn. If I install with the `--flat` option and just choose the first version of every package it works. From what I can see the issue is because that `datatables.net-buttons` installs it's own version of `datatables.net` inside the folder, where as npm does not.

![image](https://user-images.githubusercontent.com/5139119/29679233-83f9b7c0-8901-11e7-8624-80420e78fc0d.png)

But by using `--flat` it doesn't add that folder and that seems to fix it. Though the `--flat` option is not something I can do on the project I'm using this on.

Is there any way to not install the required package just for some specific packages? (e.g. datatables.net-buttons)

**Comment by krve** [comment]
In case anyone ever finds this thread - The issue seemed to fix itself. A week went by and suddenly it just worked. Perhaps a node-version upgrade or something. Sorry I can't be more helpful.

For now, I'm closing this issue.

**Comment by webernir** [comment]
I still get the same error. npm works fine, yarn breaks. Does anyone have an idea of the actual cause?

**Comment by krve** [comment]
What version of Yarn are you using? And what version of node?

So you have some reproduceable code or did you use my repo?  I'll see if it works using my repo tomorrow.

**Comment by webernir** [comment]
thanks @krve 
npm: 5.5.1
yarn: 1.3.2
node: v8.8.1

with @mnpenner project it does work.
i wonder if it's related to the way i'm requiring the modules (AMD require):
```javascript
define(["datatables.net", "ColumnFilterWidgets"], function () {
    ...
```
or it's a webpack configuration thing (i'm using webpack 1.12.6) with:
```
const providePlugin = new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    jquery: 'jquery'
});
```

what *does* work for me is requiring like the following:
```javascript
const $ = require('jquery')
require('imports?define=>false!datatables.net')(window, $)
require('ColumnFilterWidgets')
```

any insights?

**Comment by krve** [comment]
Hmm.. I just tested my repo and I actually still get the same issue. Installing with yarn, breaks the package while installing using npm works just fine. The `--flat` modifier also still works, though isn't really a solution.

What errors do you get when using your config?

The weird thing is I have a production site that runs using pretty much the same setup, and that works fine. Could you give my repo a try and follow the instructions here? https://github.com/yarnpkg/yarn/issues/4223#issuecomment-324699168

Repo: https://github.com/krve/dtbs

**Comment by webernir** [comment]
i did try your repo. and it worked with both yarn and npm.
i get an error that `$.fn.dataTables` is `undefined`, when instantiating the ColumnFilterWidgets plugin.
again, with npm it does work.

**Comment by krve** [comment]
What OS are you using?

Could you perhaps create a repo with your code? Or extract it so I could test it.

**Comment by webernir** [comment]
i'm on Windows 10.

sadly it's a enterprise inner project and cannot be shared.
i'll try extracting the relevant parts and share...
