### ISSUE TITLE
Command line revamp

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#4225]
The current codebase uses Commander. Problem is that we have a lot of [custom hacks](https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L77-L163) to support constructs not supported natively by Commander. It degrades the user experience since our hacks don't support all the constructs they should. Some examples:

```
# Command doesn't support nested subcommands, so we implement it manually
$> yarn global add 

# Yarn thinks this is an install command because the command name isn't the first parameter
$> yarn -v add <pkg> 

# The '--opt' option is parsed as being part of the 'run' command instead of being forwarded
$> yarn run <pkg> --opt
```

It would be nice to change our parser to something that would prevent us from having to write such hacks inside Yarn. Some options (I haven't made research on all of them yet):

  - [yargs](https://github.com/yargs/yargs)
  - [minimist](https://github.com/substack/minimist)
  - [concierge](https://github.com/manaflair/concierge)

I'm kinda partial to the last one, in no small part because I wrote it 😄 It would allow us to quickly contribute changes and make releases if we want to support new features, rather than implementing them inside Yarn like we did with commander. It also should support most features we need (promises tolerant, re-entrant, nested subcommands, options forwarding, default help message).

**Comment by Haroenv** [comment]
I'd love to have yarn search be a real command but it was a bit tricky when I tried to do as-you-type autocomplete in terminal. Is this something we see as possible with?

**Comment by arcanis** [comment]
I think Yargs supports automatic completion of bash options. Concierge doesn't yet, but it could be easily adapted.

**Comment by Haroenv** [comment]
I meant a full autocomplete like on the yarn website, but then in terminal

**Comment by arcanis** [comment]
Oh - that's something that would require an actual UI, right? I think that would be easily doable with [mylittledom](https://github.com/manaflair/mylittledom), but it might be too heavy to be a default command. Here's [an example](https://manaflair.github.io/mylittledom/demo/#custom:import%20%7B%20render%20%7D%20%20%20from%20'%40manaflair%2Fmylittledom%2Fterm%2Freact'%3B%0Aimport%20%7B%20autobind%20%7D%20from%20'core-decorators'%3B%0A%0Aclass%20Application%20extends%20React.PureComponent%20%7B%0A%20%20%0A%20%20state%20%3D%20%7B%0A%20%20%20%20%0A%20%20%20%20data%3A%20null%0A%20%20%20%20%0A%20%20%7D%3B%0A%0A%20%20query(string)%20%7B%0A%20%20%20%20%0A%20%20%20%20let%20encodedQuery%20%3D%20encodeURIComponent(string)%3B%0A%20%20%20%20%0A%20%20%20%20let%20url%20%3D%20'https%3A%2F%2Fofcncog2cu-3.algolianet.com%2F1%2Findexes%2F*%2Fqueries%3Fx-algolia-agent%3DAlgolia%2520for%2520vanilla%2520JavaScript%2520(lite)%25203.24.3%253Breact-instantsearch%25204.0.10%253BJS%2520Helper%25202.19.0%26x-algolia-application-id%3DOFCNCOG2CU%26x-algolia-api-key%3Df54e21fa3a2a0160595bb058179bfb1e'%3B%0A%20%20%20%20let%20body%20%3D%20JSON.stringify(%7B%22requests%22%3A%5B%7B%22indexName%22%3A%22npm-search%22%2C%22params%22%3A%22query%3D%22%20%2B%20encodedQuery%20%2B%20%22%26optionalFacetFilters%3DconcatenatedName%253Areac%26hitsPerPage%3D5%26maxValuesPerFacet%3D10%26page%3D0%26attributesToRetrieve%3D%255B%2522deprecated%2522%252C%2522description%2522%252C%2522downloadsLast30Days%2522%252C%2522githubRepo%2522%252C%2522homepage%2522%252C%2522humanDownloadsLast30Days%2522%252C%2522keywords%2522%252C%2522license%2522%252C%2522modified%2522%252C%2522name%2522%252C%2522owner%2522%252C%2522version%2522%255D%26highlightPreTag%3D%253Cais-highlight-1503493316616%253E%26highlightPostTag%3D%253C%252Fais-highlight-1503493316616%253E%26facets%3D%255B%2522keywords%2522%252C%2522keywords%2522%255D%26tagFilters%3D%22%7D%5D%7D)%3B%0A%0A%20%20%20%20fetch(url%2C%20%7B%20method%3A%20'POST'%2C%20body%20%7D).then(res%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20res.json()%3B%0A%09%7D).then(data%20%3D%3E%20%7B%0A%09%20%20this.setState(%7B%20data%20%7D)%3B%0A%09%7D)%3B%0A%20%20%20%20%0A%20%20%7D%0A%0A%20%20%40autobind%20handleChange(e)%20%7B%0A%20%20%20%20%0A%20%20%20%20this.query(e.target.value)%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20render()%20%7B%0A%20%20%20%20%0A%20%20%20%20let%20results%20%3D%20this.state.data%20%3F%20this.state.data.results%5B0%5D%20%3A%20null%3B%0A%20%20%20%20%0A%20%20%20%20return%20%3Cdiv%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%3Cinput%20onChange%3D%7Bthis.handleChange%7D%20%2F%3E%0A%20%20%20%20%0A%20%20%20%20%20%20%7B!results%20%26%26%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20Type%20a%20string%20to%20search%20a%20package%0A%20%20%20%20%20%20%3C%2Fdiv%3E%20%7C%7C%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%7B%60Found%20%24%7Bresults.nbHits%7D%20package(s)%20in%20%24%7Bresults.processingTimeMS%7Dms%60%7D%20%0A%20%20%20%20%20%20%3C%2Fdiv%3E%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%7Bthis.state.data%20%26%26%20this.state.data.results%5B0%5D.hits.map(entry%20%3D%3E%20%3Cdiv%20style%3D%7B%7BmarginTop%3A%201%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bentry.name%7D%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cdiv%20style%3D%7B%7Bcolor%3A%20'lightgrey'%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bentry.description%20%7C%7C%20'%3Cno%20description%3E'%7D%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E)%7D%0A%20%20%20%20%0A%20%20%20%20%3C%2Fdiv%3E%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%7D%0A%0Arender(%3CApplication%20%2F%3E%2C%20screen)%3B%0A).

**Comment by shadowspawn** [comment]
Commander supports nested subcommands from v5.

**Comment by arcanis** [comment]
Fwiw we have since then started to use [Clipanion](https://github.com/arcanis/clipanion).
