### ISSUE TITLE
fix es6 usage of @yarnpkg/lockfile

### ISSUE THREAD

**Issue by modosc** [yarnpkg/yarn#4231]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

this works:

```
const fs = require('fs')
const path = require('path')
const yarnLock = fs.readFileSync(path.resolve('yarn.lock'), 'utf8')
const lockfile = require('@yarnpkg/lockfile')
lockfile.parse(yarnLock)
```

this doesn't
```
import lockfile from '@yarnpkg/lockfile'
import fs from 'fs'
import path from 'path'
const yarnLock = fs.readFileSync(path.resolve('yarn.lock'), 'utf8')
lockfile.parse(yarnLock)
```
```
TypeError: _lockfile2.default.parse is not a function
```

this does work:
```
import { parse } from '@yarnpkg/lockfile'
parse(yarnLock)
```
**What is the expected behavior?**
both `import  lockfile from '@yarnpkg/lockfile'` and `const lockfile = require('@yarnpkg/lockfile')` should behave the same.

alternately please add an es6 example to the docs?
**Please mention your node.js, yarn and operating system version.**

**Comment by arcanis** [comment]
> both `import lockfile from '@yarnpkg/lockfile'` and `const lockfile = require('@yarnpkg/lockfile')` should behave the same.

That's the default behavior of babel import. Default imports try to access the `default` key of the module, which doesn't work since we don't export any. If you want a similar behavior, you can use:

```js
import * as lockfile from '@yarnpkg/lockfile';
```

> alternately please add an es6 example to the docs?

This would be great! Would you like to open a PR on [the website repository](https://github.com/yarnpkg/website)?

**Comment by modosc** [comment]
i think it has to be here - the docs i'm referring to are:

https://github.com/yarnpkg/yarn/tree/master/packages/lockfile

and yes, i'll open a pr.

**Comment by arcanis** [comment]
Thanks! 😃

**Comment by modosc** [comment]
https://github.com/yarnpkg/yarn/pull/4232

**Comment by BYK** [comment]
So we can close this? :)
