### ISSUE TITLE
Release newer version of yarn

### ISSUE THREAD

**Issue by csentis** [yarnpkg/yarn#4233]
Since yarn's release into the wild, the current period is one of the longest without a yarn release: the current version is "older" than a month.

With (as of today) 98 commits since the last tag, it is safe to assume that many people are waiting features which have been realized in the meantime.
As an example, all Windows users are likely to wait for a version > 0.28.4 as it has an issue with lifecycle script arguments (#3773) that keeps them from using it.

Would you kindly consider to release a newer version soon?
I know it will be worth looking forward ;-)

**Comment by BYK** [comment]
Hi @csentis we are working towards Yarn 1.0 and it is very very close. You can follow the progress from https://github.com/yarnpkg/yarn/projects/3

Sorry for the wait! :)
