### ISSUE TITLE
Facing issue while yarn install in terminal

### ISSUE THREAD

**Issue by AndrewCena** [yarnpkg/yarn#4234]
I have set the environmental variable and installed yarn through .msi and also from install -g yarn but still facing an error of yarn is not recognised as an internal or external command.

system path: C:\Program Files (x86)\Yarn\bin\
user path: C:\Users\Andrew_Cena\AppData\Local\Yarn\.bin\

**Comment by BYK** [comment]
Hey there! We need a concrete, reproducible scenario so we can investigate the issue and hopefully fix it. Can you at least share the error you are getting and the versions of Yarn and Node you are using?

**Comment by BYK** [comment]
Closing due to lack of response by the author.
