### ISSUE TITLE
Rotate Debian GPG signing key before October

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#4253]
Signing key expires on 5th October:
```
sub   4096R/9D41F3C3 2016-10-05 [expires: 2017-10-05]
```

We'll need to rotate it and add a new signing key before it expires.

In theory we could make a key that never expires, but I initially made it expire after a year for security reasons.

**Comment by BYK** [comment]
>In theory we could make a key that never expires, but I initially made it expire after a year for security reasons.

I think having an expiry is a best practice for certificates. Is 1 year too short?

**Comment by Daniel15** [comment]
New subkey added, expires 2019-01-01:
```
ssb  rsa4096/E074D16EB6FF4DE3
     created: 2017-09-10  expires: 2019-01-01  usage: S
```

**Comment by gbrusella** [comment]
Getting an error... Pub key should be updated again?

**Comment by Daniel15** [comment]
Yep, sorry, I'll do that tonight.

**Comment by Daniel15** [comment]
Should be fixed now... New key expires 2020-02-02 and I'll set up monitoring so we catch any issues next time.

**Comment by zypA13510** [comment]
I've updated the key a few days ago, now it says NO_PUBKEY again. And after updating the signing key (again), I get two keys both with expiration set to 2020-02-02:
```
pub   rsa4096 2016-10-05 [SC]
      72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
uid           [ unknown] Yarn Packaging <yarn@dan.cx>
sub   rsa4096 2016-10-05 [E]
sub   rsa4096 2019-01-02 [S] [expires: 2020-02-02]
sub   rsa4096 2019-01-11 [S] [expires: 2020-02-02]
```
Is the key being updated (again) or is it just me?

**Comment by Daniel15** [comment]
@zypA13510 Yeah there's an issue with how the repo is signed. The second key is supposed to only be for the nightly repo, but it's being accidentally used for the stable repo. This is being tracked in #6916

**Comment by zypA13510** [comment]
Also,
> Is 1 year too short?

I believe Google is using signing keys with expiration of 3 years:
```
pub   rsa4096 2016-04-12 [SC]
      EB4C 1BFD 4F04 2F6D DDCC  EC91 7721 F63B D38B 4796
uid           [ unknown] Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
sub   rsa4096 2016-04-12 [S] [expires: 2019-04-12]
sub   rsa4096 2017-01-24 [S] [expires: 2020-01-24]
```

**Comment by Daniel15** [comment]
Ha, I hope Google remember about their key that expires in April this year :)

Interesting... Maybe we should change the Yarn keys to be valid for three years instead of one.
