### ISSUE TITLE
how can I stop cache in the local?My space is too small

### ISSUE THREAD

**Issue by linjson** [yarnpkg/yarn#4255]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by BYK** [comment]
Please follow https://github.com/yarnpkg/rfcs/pull/53

This is not supported yet but we want to get it implemented sometime soon.
