### ISSUE TITLE
Adding too many package `bin`s to my global `bin` folder

### ISSUE THREAD

**Issue by retrixe** [yarnpkg/yarn#4258]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
On installing any package, let's say, `create-react-app`, it also adds the `bin`s of its dependencies to my global folder.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Run `sudo yarn global add electron-forge`
- Watch your global bin folder get populated with extra packages.

**What is the expected behavior?**
It only adds the `bin` for the package selected individually for installation and not for its dependencies.

**Please mention your node.js, yarn and operating system version.**
Node 8.4.0 with tj/n
Yarn v1.0.0-20170824.2019
Ubuntu 17.04

P.S. This behaviour did not happen before but now I can repro it with Yarn 0.27.5 as well?

**Comment by retrixe** [comment]
Oh wait, found this #3824

Can we get a fix soon?

**Comment by arcanis** [comment]
Working on it :)
