### ISSUE TITLE
`yarn update` -- did you mean "upgrade"?

### ISSUE THREAD

**Issue by adamreisnz** [yarnpkg/yarn#4270]
So Yarn is pretty clever when it comes to scripts. As such, I rarely need to type out `yarn run somescriptname`, instead I can just just `yarn somescriptname` and it will check the scripts and run the appropriate script.

This works great most of the time, except for `yarn update`. I have a script called `update`, but Yarn won't run it, instead it nags me and asks if I meant `yarn upgrade`.

Can Yarn check if there is a script called `update` and run it normally, when you type `yarn update`? The warning can still be displayed if there is no such script and Yarn doesn't know what to do with the command.

It's funny though, that for other commands Yarn has no suggestions. Like typing `yarn outdate` doesn't provide the suggestions for `yarn outdated`.

**Comment by kaylieEB** [comment]
This should be fixed - can you verify on the nightly builds? :)

**Comment by adamreisnz** [comment]
Thanks @kaylieEB , I'll check when it's released into production!

**Comment by kaylieEB** [comment]
Verified on master, closing.

**Comment by adamreisnz** [comment]
Thanks, I can confirm it's indeed working now!
