### ISSUE TITLE
Command failed with exit code 130

### ISSUE THREAD

**Issue by adamreisnz** [yarnpkg/yarn#4274]
Not sure if this is addressed somewhere, but I noticed on my Raspberry Pi when I exit out of a script (SIGINT / CTRL-C) it shows an error:

```
error Command failed with exit code 130.
```

Exit code 130 apparently corresponds to SIGINT, so this shouldn't result in an error just a successful termination of the script?

**Comment by GAumala** [comment]
Have you tried running the script in a regular PC? Does it show the same error?

Also, unless the script intentionally handles SIGINT to exit with code 0, it **does result in an error**.

**Comment by adamreisnz** [comment]
I don't have a regular PC, and to be honest I fail to see what the point is. 

On Mac, pressing CTRL-C results in Yarn being quiet about it and just terminates the script. On the Raspberry Pi (which simply runs Debian/Jessie), the same script and the same CTRL-C command causes Yarn to output the exit code 130 warning.

This seems like a discrepancy worth investigating?

**Comment by GAumala** [comment]
And if you run the script on the Pi without yarn and terminate it with CTRL-C, does it show the same error message?

**Comment by adamreisnz** [comment]
I'll check

**Comment by adamreisnz** [comment]
I suspect the problem might lie with the command being propagated through a proxy tty, so I'll probably implement a SIGINIT listener and handle it there with exit code 0. Closing this.
