### ISSUE TITLE
Cannot remove dependency from workspace with yarn

### ISSUE THREAD

**Issue by yacinehmito** [yarnpkg/yarn#4276]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Install a new dependency in a workspace, then try to uninstall it with `yarn remove`. You'll have the following output:

```
yarn remove v0.28.4
error No lockfile in this directory. Run `yarn install` to generate one.
```

It is however perfectly normal for a workspace to not have a lock file.

Removing from the root folder doesn't work either (which is expected).

**What is the expected behavior?**

There shouldn't be an error message. Like the normal case, yarn should:

- Remove the dependency from the workspace's `package.json`
- Link dependencies to trim the root folder's `yarn.lock`
- Delete the appropriate packages from the relevant `node_modules` folders

The RFC [briefly documents](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-workspaces-install-phase-1.md#running-yarn-install-in-workspaces-folders) the expected behaviour.

**Environment**

- yarn v0.28.4
- node v8.3.0
- Linux v4.9.44 (NixOS unstable distro)

**Comment by arcanis** [comment]
Can you try the [nightly builds](http://nightly.yarnpkg.com/)?

**Comment by yacinehmito** [comment]
Sure. I got the same error:

```
yarn remove v1.0.0-20170825.2124
error No lockfile in this directory. Run `yarn install` to generate one.
```

The slight difference is that this time the process doesn't exit, so the shell effectively hangs. This is however unrelated to this current issue.

**Comment by yacinehmito** [comment]
I am currently writing a test and will submit a PR once I'm done.

**Comment by yacinehmito** [comment]
Test submitted in #4277.

It doesn't fail, which means the problem is unrelated to the removing functionality itself. I don't know enough about the yarn codebase to keep investigating but my bet is that there's a check somewhere for the lock file that we need to modify. Instead of checking the current folder for a `yarn.lock` file, it should walk up the folder hierarchy.

**Comment by kaylieEB** [comment]
FWIW I don't think it's specific to workspaces. The command seems to hang in a normal package without a lockfile.

**Comment by arcanis** [comment]
Investigated a bit - the problem comes from https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L193-L197 (the same issue occurs if you type `yarn import foobar`, because the same kind of code is used at https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L175-L180. I suspect this is caused by the recent switch from `process.exit()` to `process.exitCode = ...`. A listener must be alive somewhere and prevent the process from exiting.

**Comment by yacinehmito** [comment]
I don't think this issue deserves to be closed. See my comment in #4283.
The remark I made about the process not closing and to which @kaylieEB answered to was just made in passing. The issue originally raised has to do with the inability to use `yarn remove`inside a workspace.

**Comment by yacinehmito** [comment]
I just saw #4334, giving credit to my initial complaint. Can someone reopen this issue or acknowledge #4334?

Yarn 1.0 has just been announced and the first feature described in the announcement was Yarn workspaces. As the documentation clearly indicates the expected behaviour of `yarn remove` in a workspace, this may need careful attention.

Paging @arcanis.

**Comment by BYK** [comment]
@yacinehmito acknowledged the references issue. You can track it from there.

**Comment by yacinehmito** [comment]
Thanks 😄
