### ISSUE TITLE
Errors when checking git remotes result in confusing error messages

### ISSUE THREAD

**Issue by sth** [yarnpkg/yarn#4287]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I tried to deploy some repository on a new machine that didn't have git installed (Debian).

```
$ yarn install --frozen-lockfile
yarn install v0.27.5
[1/5] Resolving packages...
error Refusing to download the git repo {"hostname":"github.com","protocol":"https:","repository":"https://github.com/pocketjoso/css.git"} over HTTPS without a commit hash - possible certificate error?
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It is of course completely reasonably that the installation fails, but the given error message is misleading and unrelated to the real problem. The problem wasn't a missing commit hash or bad certificate, but the missing `git` binary.

**What is the expected behavior?**
The installation should fail with a message like "Couldn't find the binary `git`".

**Details**
At the point where the new git process is spawned, the problem is handled correctly and a useful error is generated:
https://github.com/yarnpkg/yarn/blob/67dfc7af80bad0034a1f23e9ef4da8c696e134c7/src/util/child.js#L53-L59

Later in `remoteExists()` this information is lost and all errors are treated as "remote doesn't exist":
https://github.com/yarnpkg/yarn/blob/67dfc7af80bad0034a1f23e9ef4da8c696e134c7/src/util/git.js#L108-L115

Then for any such "not existing" remote the "Refusing to download" message is generated
https://github.com/yarnpkg/yarn/blob/67dfc7af80bad0034a1f23e9ef4da8c696e134c7/src/util/git.js#L156-L162

So it seems that all kinds of errors when checking remotes will lead to the "Refusing to download" error message.

The error message should be improved to better reflect what error occurred.

**Comment by Daniel15** [comment]
Fantastic analysis, @sth! Would you like to try and submit a fix for this? I suspect `yarn/src/util/child.js` should throw a more specific subclass of `Error` (maybe create a new `BinaryDoesNotExistError`), then `yarn/src/util/git.js` should rethrow that if it catches it (eg. do an `instanceof` check), and then `yarn/src/util/git.js` should also rethrow it.

**Comment by swellingt0n** [comment]
This error is happening for me with the latest release, 1.3.2, even though I definitely have git installed on my machine (OSX, via homebrew).
