### ISSUE TITLE
wrong version module linked to node_modules/.bin

### ISSUE THREAD

**Issue by Brooooooklyn** [yarnpkg/yarn#4290]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
https://github.com/Brooooooklyn/yarn-bug

**Please mention your node.js, yarn and operating system version.**
- node@8.4.0
- yarn@0.27.5
- macOS@10.12.6

**Comment by dbushong** [comment]
This is a regression of a bug reported fixed a few versions back.  Put in simple words "sub-dependencies' bin scripts are being chosen over the toplevel dependencies' version"

**Comment by BYK** [comment]
Don't think this is a regression since the reported Yarn version is 0.27.5

Can you try 1.0.2 or one of the nightlies: https://yarnpkg.com/en/docs/nightly

**Comment by dbushong** [comment]
Definitely still happens in 1.0.2.  I'll try a nightly.

**Comment by dbushong** [comment]
Still happens with latest nightly.  Here's a simple repro:
```
$ mkdir x && cd x && yarn init
<whatever, we just want a package.json>
$ yarn add coffee-script
$ yarn add grunt-coffee-redux
$ ls -l node_modules/.bin.coffee
lrwxrwxrwx 1 dbushong dbushong 33 Sep 16 15:10 node_modules/.bin/coffee -> ../coffee-script-redux/bin/coffee
# ^^^ should be coffee-script's not redux, since redux is only a sub-dep
$ rm -rf node_modules
$ yarn
$ ls -l node_modules/.bin/coffee
(same result)
```

**Comment by Brooooooklyn** [comment]
in this repo: https://github.com/Brooooooklyn/yarn-bug, this bug doesn't appear with yarn@1.0.2, so I'll close this issue for now.

**Comment by dbushong** [comment]
Still happens in 1.0.2 for me: https://github.com/dbushong/yarn-bug

**Comment by haquezameer** [comment]
anyone knows the reason for this behaviour? I am facing a similar issue wherein the `prettier` from my subdependency is preferred over the `prettier` of my direct dependency.

Any other issues on the same topic would help too.

I am on `yarn@1.22.17` and `node@14.18.0`
