### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#4300]
- [x] Generate change log
 - [x] Resolve https://github.com/yarnpkg/website/issues/372 (@BYK)
 - [x] Tag 1.0
 - [x] Add change log to blog post (@arcanis)
 - [x] Publish to npm
 - [x] Publish RPMs and MSIs
 - [x] Document workspaces (@arcanis)
 - [x] Document selective version resolutions (https://github.com/yarnpkg/website/issues/605) (@BYK)
 - [x] Publish blog post
 - [x] Publish blog post on website (@BYK)
 - [x] Tweet the blog post (@cpojer)
 - [x] Post on HN (@cpojer)
 - [x] Monitor public channels for possible bug reports

**Comment by Daniel15** [comment]
The publishing (npm, RPMs, MSIs) is all automated based on tags, as long as the build succeeds.
