### ISSUE TITLE
If .yarnrc is hidden on Windows, yarn add [package] fails

### ISSUE THREAD

**Issue by ssimon92** [yarnpkg/yarn#4306]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
The command `yarn add vue` fails with the error message 

> Error: EPERM: operation not permitted, open 'C:\\Users\\**username-obfuscated**\\.yarnrc'
    at Error (native)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Mark .yarnrc as a hidden file on Windows.
2. Call command `yarn add vue`
3. Package installs successfully, but at the end of the yarn installation output, the error is received.

**What is the expected behavior?**
Yarn should recognize that .yarnrc exists, even if it a hidden file.

**Please mention your node.js, yarn and operating system version.**
Node.js version 6.11.2, yarn version 0.27.5, operating system Windows 10 Home, version 1703, build 15063.483

**Comment by arcanis** [comment]
If we can't read this file, not sure we can't do much

**Comment by Muukuro** [comment]
I had this issue too. Manually unhiding and rehiding ~\.yarnrc in Explorer fixed it for me.
Not sure, but it would almost seem like Yarn creates this file in a non-standard 'hidden' way, making it invisible or unavailable for applications.

**Comment by royalaid** [comment]
Just want to say that I had to `touch ~/.yarnrc` then hide and unhide the file like the comment above this.

**Comment by joalcava** [comment]
Why is this closed? The issue still exists. If you hide .yarnrc every add will end with error: EPERM. This also causes creat-react-app and other bootstrappers to fail.

**Comment by arcanis** [comment]
> Why is this closed? The issue still exists

Because it's not a problem Yarn can fix as far as I know. If I'm incorrect, then a PR will go a long way into fixing this 🙂

**Comment by joalcava** [comment]
@arcanis Thanks for your response, I don't know much about the yarn's internals but I was supposing this was concerning to yarn since most applications does not have problems with hidding its dot files in windows.

**Comment by robross0606** [comment]
I don't understand why node.js developers have a mental block on this type of a problem.  A hidden files is NOT a read-only file.  Nor is it a non-existent file.  Technically, all Unix files that start with "." are hidden.  On Windows it is a separate flag, but the behavior should be the same.  The file is available.  Visibility settings are not the same as permissions.  This is a BUG and should not have been closed.

**Comment by dstaley** [comment]
I'm willing to take a stab at this! Leaving this note here so that I can come back to it in a few days.

On Windows, opening a file in `w` mode will throw `EPERM` if the file has the hidden attribute. Instead, we should open the file in `r+`. However, in order to do this, we need to ensure that the file exists. So, I think the easiest implementation would be to update [this function](https://github.com/yarnpkg/yarn/blob/master/src/util/fs.js#L784) to create the file if it doesn't exist, then open it in `r+` mode, and the write the data to the file. Since it's using a promisified version of `fs.writeFile`, we could in theory update `writeFile` to have this behavior. That'll be what I'll investigate.

**Comment by alidavodii** [comment]
hi my friends , go to c:/users/{pc name}/
show hidden file
properties .yarnrc
hidden uncheck
good luck
![Annotation 2019-12-11 102530](https://user-images.githubusercontent.com/52744305/70598774-d659ab80-1c00-11ea-8445-5ac66ea81d6b.png)

**Comment by stephtr** [comment]
Sorry for being slightly off-topic, but why does the yarnrc file on Windows gets saved to the user's folder instead of %APP_DATA%? If the latter would be the case, there would be in my opinion no need to manually hide the file.

**Comment by karlhorky** [comment]
Seems like you can also fix this on the command line:

```
attrib -h C:\Users\<your username>\.yarnrc
```

Or, of you're using Git Bash:

```
attrib -h /c/Users/<your username>/.yarnrc
```

**Comment by Lschulzes** [comment]
> hi my friends , go to c:/users/{pc name}/
> show hidden file
> properties .yarnrc
> hidden uncheck
> good luck
> ![Annotation 2019-12-11 102530](https://user-images.githubusercontent.com/52744305/70598774-d659ab80-1c00-11ea-8445-5ac66ea81d6b.png)

That worked for me, thanks bro!

**Comment by zevsap** [comment]
Ok. I’m try to do it, I hope I can 


Отправлено из Yahoo Почты на iPhone


Пользователь понедельник, сентября 13, 2021, 2:12 PM написал Lucas Schulze ***@***.***>:





hi my friends , go to c:/users/{pc name}/
show hidden file
properties .yarnrc
hidden uncheck
good luck



That worked for me, thanks bro!

**Comment by sryze** [comment]
Has this been fixed?

**Comment by lul-star** [comment]
> 

Nope
