### ISSUE TITLE
yarn global add fails due to prepack incompatible node version

### ISSUE THREAD

**Issue by heroandtn3** [yarnpkg/yarn#4308]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Cannot install package globally with `yarn global add <package>` command.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn global add bower    
yarn global v0.28.4
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
warning bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
[2/4] Fetching packages...
error prepack@0.2.1: The engine "node" is incompatible with this module. Expected version ">=6.1.0 <8.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**What is the expected behavior?**

It should install the package sucessfully.

**Please mention your node.js, yarn and operating system version.**
node.js 8.2.1
yarn v0.28.4
Arch Linux

**Comment by BYK** [comment]
Why do you think this is a bug? The package clearly states it wants node.js < 8.0.0 and you are using 8.2.1.

**Comment by heroandtn3** [comment]
Hello, I tried with some packages, none of them is successfully installed, all of them have the same error message like the one I posted above. It works normally when I use `npm i -g <package>`, obviously the bug comes from Yarn.

**Comment by BYK** [comment]
@heroandtn3 this is by design. npm doesn't treat those fields as strict requirements whereas yarn does. You either need to change your node.js version or find packages that don't are compatible with the version of node you are using. If you think packages' engine requirements are not valid, please file an issue with the package repos.

**Comment by heroandtn3** [comment]
@BYK I tried `yarn add bower grunt-cli`, it worked perfectly. Obviously, the problem does not come from the package itself, those packages do not require `prepack` in its dependencies.

```
➜  test yarn add bower
yarn add v0.28.4
info No lockfile found.
[1/4] Resolving packages...
warning bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ bower@1.8.0
Done in 2.17s.
➜  test yarn add grunt-cli
yarn add v0.28.4
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 16 new dependencies.
├─ abbrev@1.1.0
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.8
├─ concat-map@0.0.1
├─ findup-sync@0.3.0
├─ glob@5.0.15
├─ grunt-cli@1.2.0
├─ grunt-known-options@1.1.0
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ minimatch@3.0.4
├─ nopt@3.0.6
├─ once@1.4.0
├─ path-is-absolute@1.0.1
├─ resolve@1.1.7
└─ wrappy@1.0.2
warning No license field
Done in 1.70s.
➜  test yarn list prepack
yarn list v0.28.4
warning package.json: No license field
warning No license field
Done in 0.11s.
```

**Comment by BYK** [comment]
>@BYK I tried yarn add bower grunt-cli, it worked perfectly. Obviously, the problem does not come from the package itself, those packages do not require prepack in its dependencies.

I would refrain from using words like "obvious" or "obviously" since if things were obvious, we wouldn't be discussing things. Either you would come up with a fix or I'd say "oh yeah, obviously this is the problem".

As mentioned earlier, you are using `prepack` somewhere which requires a node version, not compatible with what you have currently. I'd check any other global packages you've installed earlier, including prepack to see if that's the culprit.

you can try `yarn global list` to see all your global packages.
