### ISSUE TITLE
build-dist creates tarball with "dist" directory - Expected?

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#431]
Is it expected that `scripts/build-dist.sh` creates a tarball with a `dist` directory rather than something like `yarn-0.13.0`? The normal approach with Linux tarballs is to have the app name and version number in both the file name and the directory name (ie. `yarn-0.13.0.tar.gz` which extracts a `yarn-0.13.0` directory). This makes it easier to deal with extracting the tarball (eg. extracting two versions of Yarn in the same directory won't both write `dist` directories that overwrite each other).

Happy to fix it, but I was wondering if there was a reason it's configured that way.

**Comment by bestander** [comment]
I think it is resolved now now
