### ISSUE TITLE
Packages installed w/o manifest cannot be removed via command line: 'yarn remove'

### ISSUE THREAD

**Issue by cristian-spiescu** [yarnpkg/yarn#4310]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot remove a package that was installed w/o manifest (cf. #3624)

**If the current behavior is a bug, please provide the steps to reproduce.**
Install a package w/o manifest, e.g.
``yarn add https://github.com/pbakaus/scroller.git``

Then try to remove it:
``yarn remove scroller``

And the system complains:

```
error Couldn't find a package.json file in "...\\node_modules\\scroller"
```

**What is the expected behavior?**
The package should have been removed

**Please mention your node.js, yarn and operating system version.**
yarn v0.28.4, npm v5.3.0, Windows 7

**Comment by BYK** [comment]
I was able to replicate this locally. Thanks for the report!

**Comment by romariolopezc** [comment]
```bash
~ readlink `which elm-format`
../../../Users/romario/.config/yarn/global/node_modules/elm-format/bin/elm-format

~ yarn global remove elm-format
yarn global v1.6.0
[1/2] 🗑  Removing module elm-format...
error This module isn't specified in a manifest.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

```

Is this supposed to be working?

**Comment by xiaodeaux** [comment]
Also still having problems
```
yarn global remove @vue/cli@latest
yarn global v1.12.3
[1/2] Removing module @vue/cli@latest...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by yurayko** [comment]
Still broken.

yarn global remove @vue/cli@3.2.1
yarn global v1.15.2
[1/2] Removing module @vue/cli@3.2.1...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

Thanks for solution. :)
