### ISSUE TITLE
yarn upgrade @package@next not work

### ISSUE THREAD

**Issue by juanha** [yarnpkg/yarn#4311]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
i hava a package, the package  add a tag named  'next' for a specific version, example 4.1, then, i update the package tag 'next' version is 4.2,
but, when  ``yarn upgrade @package@next``, the package version still is 4.1

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by paul-soporan** [comment]
Closing as fixed in v2 (where the command is now called `yarn up`).

https://yarnpkg.com/getting-started/migration
