### ISSUE TITLE
yarn global add doesn't install "ng" binary, installing it manually leads to error

### ISSUE THREAD

**Issue by codethief** [yarnpkg/yarn#4315]
**Do you want to request a *feature* or report a *bug*?** A bug

**What is the current behavior?** 

After installing Angular CLI using yarn, the "ng" binary is not available.

**If the current behavior is a bug, please provide the steps to reproduce.**

Having installed node.js, follow https://yarnpkg.com/en/docs/install to install yarn on Ubuntu 17.04. Then install the Angular CLI:
```
$ yarn global add --ignore-engines @angular/cli
```
(I had to add --ignore-engines because it wouldn't install otherwise. Also make sure that on Ubuntu 17.04 there actually is a binary called "node" linking to nodejs, otherwise this will cause additional errors.)

Then try to use the Angular CLI:
```
$ ng
```
…and the command line will tell you that there is no command `ng`.

Now I did try to find the binary myself and located it at `~/.config/yarn/global/node_modules/@angular/cli/bin/ng`. So I created a symlink to it in `/usr/local/bin` and again tried to run `$ ng` which, this time, resulted in:

```
/home/<user>/.config/yarn/global/node_modules/@angular/cli/models/config/config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/<user>/.config/yarn/global/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**What is the expected behavior?**

That the `ng` binary is found in the path and ready to be used after installing it using yarn.

**Please mention your node.js, yarn and operating system version.**

- Operating system: Ubuntu 17.04 (brand-new installation, in particular I never had node or yarn installed on it before)
- node.js version: 4.7.2
- yarn version: 0.27.5-1

**Comment by codethief** [comment]
I just noticed that the node.js version available in the Ubuntu 17.04 repositories is completely out-of-date and has to be installed manually. I assume this is the reason for the issues I'm experiencing, so I'm going to close this.

**Comment by maoueh** [comment]
I also experiencing related issues, using lerna.

* OS: Mac OS X (10.11.6)
* Node: v8.4.0
* Yarn: 0.27.5, 0.28.1 and 1.0.0

```
$ yarn config get bin-path
/Users/mvachon/.yarn/bin

$ yarn global add lerna
...
success Installed "lerna@2.1.2" with binaries:
      - lerna
warning No license field
✨  Done in 3.15s.

$ which lerna
lerna not found

$ ls -al  /Users/mvachon/.yarn/bin
total 0

$ file ~/.config/yarn/global/node_modules/.bin/lerna
/Users/mvachon/.config/yarn/global/node_modules/.bin/lerna: a node script text executable
```

Not sure what is the issue as it was working at some point in before and it's not anymore. I had installed other global tools before and they were working great. Not sure what happen exactly on my compute to disrupt that.

**Comment by eragon11** [comment]
yarn just reduced the fetching time...... but not really installing the packages
but npm installing all packages but fetching time will little bit more compared to yarn..........

**Comment by khacbinh** [comment]
I tried with npm and it said `permission denied`.
So i prefixed the comand with `sudo` and it worked, so did yarn!

**Comment by brmi** [comment]
I am in the folder that ng is located in and I still cannot run ng without getting the command not found error ???
