### ISSUE TITLE
Regarding license issue

### ISSUE THREAD

**Issue by thatsk** [yarnpkg/yarn#4319]
https://www.theregister.co.uk/2017/07/17/apache_says_no_to_facebook_code_libraries/

**Comment by BYK** [comment]
Yarn is neither owned by Facebook nor has the BSD+Patents license so this doesn't apply.

Also see https://twitter.com/sebmck/status/898963855841341442

you may also simply read the license file itself here: https://github.com/yarnpkg/yarn/blob/master/LICENSE

**Comment by thatsk** [comment]
thanks for quick reply
