### ISSUE TITLE
yarn install fails with hash errors when using scoped packages like @types

### ISSUE THREAD

**Issue by sliebner** [yarnpkg/yarn#4324]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
yarn install responds with hash errors when you use scoped packages (e.g. `@types/blabla)`

**If the current behavior is a bug, please provide the steps to reproduce.**

Example from our project:
`$ yarn install
yarn install v0.27.5
...
[1/4] Resolving packages...
[2/4] Fetching packages...
error Hashes don't match when extracting file 
"http://xxx.xxx.xx:8080/nexus/repository/registry.npmjs.org/react-test-renderer/-/react-test-renderer-15.5.4.tgz". 
Expected "d4ebb23f613d685ea8f5390109c2d20fbf7c83bc" but got "1f579bc615231f3cc3f1b0a25b88940d4c85f925"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 `
The files are from our local nexus registry. They are all right. What we can see is, that in the yarn-cache folder, there is no destinction between the real module file and the type file for that module. There is no extra folder `@types` like you see in npm cache or node modules folders. 

Thus both files come under the same name and they have differing hashes and what is in the filesystem afterwards is random. We are on Linux/Win7/Win10. Pretty similar behavior on all machines. 

**What is the expected behavior?**
No hash error, scoped packages get into their scoped folders like npm does it.

**Please mention your node.js, yarn and operating system version.**
yarn 0.27.5
node 6.11.0
Linux/Win7/Win10

**Comment by BYK** [comment]
From your report, what I understand is a clash between packages from different registries, is that correct?

If so, I'm a bit confused since I think we do separate caches for different registries. Right @arcanis?

Are you using a custom registry or jsut a proxy in front of the requests that answers from local?

**Comment by sliebner** [comment]
We are using an internal sonatype nexus 3 which proxies all request to external registries. No direct external access possible. So from our internal view we are connecting to just one single registry.

I put together a mini project:
 
package.json

> {
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "keywords": [
    "yarn-test"
  ],
  "devDependencies": {
    "@types/react-test-renderer": "15.5.4",
    "react-test-renderer": "15.5.4"
  }
}

 
.npmrc
 

> registry = http://yyy.yyy.yy:8080/nexus/repository/registry.npmjs.org/
_auth = blablabla
always-auth=true
shrinkwrap=false
http-proxy=null
https-proxy=null
strict-ssl=false
fetch-retries=0
ca=null
cafile=null

 
.yarnrc
 

> registry "http://yyy.yyy.yy:8080/nexus/repository/registry.npmjs.org/" 
yarn-offline-mirror "C:\\project\\yarn-test\\yarn-mirror-test"


If I run yarn install in this configuration, I see an `@types` folder in node_modules and just one real-test-renderer-15.5.4.tgz file in yarn-mirror-test which is in my case the smaller type file.

Access is direct, no proxy in between.

**Comment by BYK** [comment]
Okay, now I understand the problem.

I tried to replicate this locally with the latest master and I see the correctly prefixed `@types-` file in my offline mirror. Can you try with the latest 1.0 RC and see if it is fixed there?

**Comment by sliebner** [comment]
I just installed the 1.0.0 using the msi installer.
yarn ..version shows 1.0.0
Same outcome, the yarn-mirror-test folder contains no prefixed files or new folders.

**Comment by sliebner** [comment]
Update:

From an internet connected machine it works like you said:


> $ ls -al
> total 2176
> drwxr-xr-x  20 xxxxx  staff     680  7 Sep 13:03 .
> drwxr-xr-x   7 xxxxx  staff     238  7 Sep 13:03 ..
> -rw-r--r--   1 xxxxx  staff   31647 30 Aug 13:59 @types-react-16.0.5.tgz
> -rw-r--r--   1 xxxxx  staff    2087  7 Sep 13:03 @types-react-test-renderer-15.5.4.tgz
> -rw-r--r--   1 xxxxx  staff   11403 28 Jul 14:55 asap-2.0.6.tgz
> -rw-r--r--   1 xxxxx  staff  364791 30 Nov  2016 core-js-1.2.7.tgz
> -rw-r--r--   1 xxxxx  staff    3441 30 Nov  2016 encoding-0.1.12.tgz
> -rw-r--r--   1 xxxxx  staff  128184 28 Jul 14:55 fbjs-0.8.14.tgz
> -rw-r--r--   1 xxxxx  staff  186295 28 Jul 14:55 iconv-lite-0.4.18.tgz
> -rw-r--r--   1 xxxxx  staff    1616 30 Nov  2016 is-stream-1.1.0.tgz
> -rw-r--r--   1 xxxxx  staff    3308 30 Nov  2016 isomorphic-fetch-2.2.1.tgz
> -rw-r--r--   1 xxxxx  staff    5991 28 Jul 14:55 js-tokens-3.0.2.tgz
> -rw-r--r--   1 xxxxx  staff    2932 17 Jan  2017 loose-envify-1.3.1.tgz
> -rw-r--r--   1 xxxxx  staff   27137 22 Aug 22:48 node-fetch-1.7.2.tgz
> -rw-r--r--   1 xxxxx  staff    2675 17 Jan  2017 object-assign-4.1.1.tgz
> -rw-r--r--   1 xxxxx  staff   16490 11 Aug 11:16 promise-7.3.1.tgz
> -rw-r--r--   1 xxxxx  staff  244374  7 Sep 13:03 react-test-renderer-15.5.4.tgz
> -rw-r--r--   1 xxxxx  staff    3255  3 Jan  2017 setimmediate-1.0.5.tgz
> -rw-r--r--   1 xxxxx  staff   39016 28 Jul 14:55 ua-parser-js-0.7.14.tgz
> -rw-r--r--   1 xxxxx  staff    7656 29 Mai 18:14 whatwg-fetch-2.0.3.tgz


yarn lock on that machine:

```
"@types/react-test-renderer@15.5.4":
  version "15.5.4"
  resolved "@types-react-test-renderer-15.5.4.tgz#1f579bc615231f3cc3f1b0a25b88940d4c85f925"
  dependencies:
    "@types/react" "*"

"@types/react@*":
  version "16.0.5"
  resolved "@types-react-16.0.5.tgz#d713cf67cc211dea20463d2a0b66005c22070c4b"

```

yarn lock on the internal machine:

```
"@types/react-test-renderer@15.5.4":
  version "15.5.4"
  resolved "http://xxx.xxx.xx:8080/nexus/repository/registry.npmjs.org/@types/react-test-renderer/-/react-test-renderer-15.5.4.tgz#1f579bc615231f3cc3f1b0a25b88940d4c85f925"
  dependencies:
    "@types/react" "*"

"@types/react@*":
  version "16.0.5"
  resolved "http://xxx.xxx.xx:8080/nexus/repository/registry.npmjs.org/@types/react/-/react-16.0.5.tgz#d713cf67cc211dea20463d2a0b66005c22070c4b"
```

Does this help you to figure out, why with our single internal repo there is no proper prefixing?

**Comment by sliebner** [comment]
Has anyone got an update on this one? NPM works fine and we had do. go back to that to continue work...

**Comment by BYK** [comment]
@sliebner sorry, not yet. If this is important for you and you're willing to try submitting a PR I can assist you in the process.

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
