### ISSUE TITLE
Latest yarn of the website only has 0.27.5

### ISSUE THREAD

**Issue by TimvdLippe** [yarnpkg/yarn#4327]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Version 0.27.5 is the latest version on the website.
**If the current behavior is a bug, please provide the steps to reproduce.**
`curl -o- -L https://yarnpkg.com/install.sh | bash`
**What is the expected behavior?**
A newer version should be available, preferably v1.0.0 from https://github.com/yarnpkg/yarn/releases
**Please mention your node.js, yarn and operating system version.**
node: 8.1.4
yarn: 0.27.5
os: ubuntu

**Comment by Daniel15** [comment]
1.0.0 has not been released as a stable version yet. Coming soon! 😉 

Currently, 0.27.5 is the latest stable release. To get 1.0, you need to pass the `--rc` flag to the install script:
```
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
```

**Comment by TimvdLippe** [comment]
Ah, I was too enthusiastic about 1.0.0 then :) Nonetheless, the releases page shows that 0.28.4 is tagged as latest release. Is this then also incorrect?

**Comment by Daniel15** [comment]
Oops! You're right. It's fixed now.

The version number displayed on the Yarn site at https://yarnpkg.com/ is the source of truth. You can get the version number from https://yarnpkg.com/latest-version

**Comment by TimvdLippe** [comment]
Ah I see. Thanks for the speedy replies and good luck tinkering out the last few bugs for 1!
