### ISSUE TITLE
yarn outdated not working w/workspaces

### ISSUE THREAD

**Issue by ericanderson** [yarnpkg/yarn#4328]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In a project work workspaces, `yarn outdated` claims everything is up to date. (The root project has no dependences). `yarn workspace api outdated` errors with the following:

```
yarn workspace v1.0.0
yarn outdated v1.0.0
error No lockfile in this directory. Run `yarn install` to generate one.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/8.4.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.0.0_1/libexec/lib/cli.js outdated
Directory: /Volumes/git/project/packages/api
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I expect it to tell me the outdated modules.

**Please mention your node.js, yarn and operating system version.**

yarn 1.0.0

**Comment by pedronauck** [comment]
This error also happens with the `yarn workspace <name> remove <pkg>`

**Comment by milesj** [comment]
Same issue here.

**Comment by BYK** [comment]
I think this is a general issue with `yarn workspace` command. @arcanis any quick solutions off the top of your head?

**Comment by mribichich** [comment]
I don't use workspace and `yarn outdated` claims everything is up to date

**Comment by bertho-zero** [comment]
I have this issue with yarn v1.12.3
