### ISSUE TITLE
Difference between yarn workspaces' and lerna's use of symlinks?

### ISSUE THREAD

**Issue by azz** [yarnpkg/yarn#4329]
Note: unfortunately this issue occurs across the use of three tools: yarn workspaces, lerna and TypeScript. I am raising it here first.

**Do you want to request a *feature* or report a *bug*?**

Bug (maybe).

**What is the current behavior?**

The TypeScript compiler causes Node.js to run out of memory while compiling a project symlinked with yarn workspaces. This could be a bug in yarn or TypeScript, but since this issue did not occur before I switched lerna to `useWorkspaces`, I think it might be the prior.

<details>
<summary>Node.js crash (note the hasOwnProperty key)</summary>
<pre>
<--- Last few GCs --->

[19200:00000297663FA890]   355672 ms: Mark-sweep 1400.8 (1441.3) -> 1400.8 (1440.3) MB, 650.3 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start
 of marking 650 ms) last resort
[19200:00000297663FA890]   356269 ms: Mark-sweep 1400.8 (1440.3) -> 1400.8 (1440.3) MB, 596.1 / 0.0 ms  last resort

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000086E1C1BA89 <JS Object>
    1: hasOwnProperty(this=0000028B75BD4AE1 <an Object with map 000002269FE9E769>,0000023A5FF82FC1 <String[256]: C:\path\to\project\node_modules\\@company\dep-a\node_modules\\@company\dep-b\node_modules\\@company\dep-c\node_modules\\@company\dep-d\path\to\file.js>)
    2: _readdir [C:\path...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
</pre>
</details>

Note that the path `<rootDir>/packages/node_modules/dep-a/node_modules/dep-b/node_modules/dep-c` is not being resolved back to `<rootDir>/packages/node_modules/dep-c`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Unfortunately this was on closed source code, but the steps involve having a large (41 package) TypeScript monorepo and running the TypeScript compiler on it.

**What is the expected behavior?**

Node.js not to run out of memory :wink:

The question I have is **how does yarn's workspace feature differ from lerna in its use of symlinks on Windows?**

**Please mention your Node.js, yarn and operating system version.**

* Node v8.1.4
* Yarn v1.0.0
* Windows 10 Enterprise v10.0.14393
* Lerna v2.1.2

**Comment by Ciantic** [comment]
Out of interest did you run lerna with --hoist flag previously? I think yarn works out of the bag as hoisted.

**Comment by azz** [comment]
No, I do not use hoist.

**Comment by BYK** [comment]
This issue now may be fixed with the latest version of yarn

**Comment by azz** [comment]
Awesome. I'll try to reproduce on Monday.

**Comment by merceyz** [comment]
I'll assume everything went well on that Monday and close this
