### ISSUE TITLE
"yarn remove" inside workspace fails

### ISSUE THREAD

**Issue by jgoz** [yarnpkg/yarn#4334]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

Attempting to remove a package from inside a workspace fails with:

```
error No lockfile in this directory. Run `yarn install` to generate one
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
$ cd packages/some-package
$ yarn remove some-dependency
yarn remove v1.0.1
error No lockfile in this directory. Run `yarn install` to generate one
```

**What is the expected behavior?**

The package should be removed and the root lockfile should be updated.

**Please mention your node.js, yarn and operating system version.**

Node 8.4.0
Yarn 1.0.1
Mac OS 10.12

Possibly related to #4328.

**Comment by BYK** [comment]
Out of curiosity, do you have a lockfile in the workspace root?

**Comment by jgoz** [comment]
> Out of curiosity, do you have a lockfile in the workspace root?

Yes, and it's the only lockfile in the project.

**Comment by jgoz** [comment]
Note that this also fails in the same way if I run:

```sh
$ yarn workspace some-package remove some-dependency
```

**Comment by ericanderson** [comment]
@byk This is similar to #4328 if not the same root cause (yarn outdated).

Same for me. yarn.lock in root, no yarn.lock in either workspace.

**Comment by jgoz** [comment]
@BYK, @arcanis I created a repro project at https://github.com/jgoz/yarn-workspace-issue.

**Comment by BYK** [comment]
@jgoz thanks a lot for the awesome repro repo. I easily reproduced this and was able to confirm. @arcanis may have a solution off the top of his head for these.

If not, I'll investigate.
