### ISSUE TITLE
"registry" now requires a trailing slash to work correctly

### ISSUE THREAD

**Issue by pselden** [yarnpkg/yarn#4339]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using the "registry" parameter in .npmrc and .yarnrc, you must now use a trailing slash. Otherwise it will fail with an error "Couldn't find package "<package-name>" on the "npm" registry."

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create .yarnrc with the following contents:
```
registry "https://my-private-repo.com/artifactory/npm"
```
2) yarn add react --verbose
3) See the following:
```
verbose 0.59 Performing "GET" request to "https://my-private-repo.com/artifactory/react".
```
Note -- there is no /npm on the end

**What is the expected behavior?**
Should make a get request to "https://my-private-repo.com/artifactory/npm/react"

**Please mention your node.js, yarn and operating system version.**
yarn 1.0.1
node 8.4.0
OSX Sierra

Note -- this can be worked around by adding a trailing slash -- but this was working correctly in v0.27.5

**Comment by nynexman4464** [comment]
Just ran into this.  Can confirm adding the `/` fixed it, but was really confused for a while why I couldn't install something that seemed to be in the registry.

**Comment by arosenthal-r7** [comment]
yea can also confirm that this used to work fine without a trailing slash in my `.npmrc`, and now i need the trailing slash...

**Comment by BYK** [comment]
Sorry @kaylieEB, took this on since I'm hoping to release 1.0.2 with this fixed.

**Comment by kaylieEB** [comment]
no worries at all! I was just seeing this bug in prod too, thanks for fixing it quickly!
