### ISSUE TITLE
Yarn install --frozen-lockfile generates a lockfile

### ISSUE THREAD

**Issue by epmatsw** [yarnpkg/yarn#4344]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
If you run `yarn install --help`, the description of `--frozen-lockfile` is "don't generate a lockfile and fail if an update is needed". If you run `yarn install --frozen-lockfile` in a project without a yarn.lock, it generates a new yarn.lock.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to a project without a yarn.lock
2. Run `yarn install --frozen-lockfile`.

**What is the expected behavior?**
No lockfile should be generated.

**Please mention your node.js, yarn and operating system version.**
Node 8.4.0, yarn 1.0.0, macOS 10.12.

**Comment by BYK** [comment]
Hey, thanks for the report! Sure this is an edge case we've overlooked and it is annoying. Will fix soon!
