### ISSUE TITLE
Yarn v1.0.1 not working with node 6.11.3

### ISSUE THREAD

**Issue by DerTieran** [yarnpkg/yarn#4352]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Yarn not working with `node v6.11.3` (LTS)

**What is the expected behavior?**
Yarn should work with the latest LTS versions

**Please mention your node.js, yarn and operating system version.**
node.js: v6.11.3
yarn: v1.0.1
OS: Arch Linux

I installed `yarn 1.0.1-1` from [AUR](https://www.archlinux.org/packages/community/any/yarn/).
```shell
➜ pacman -Qs yarn                      
local/yarn 1.0.1-1
    Fast, reliable, and secure dependency management
```

Running yarn with `node v6.11.2` works:
```shell
➜ nvm exec 6.11.2 yarn
Running node v6.11.2 (npm v3.10.10)
yarn install v1.0.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.79s.
```
but running it with `node v6.11.3` (the latest LTS version) fails:
```shell
➜ nvm exec --lts yarn
Running node latest LTS -> v6.11.3 (npm v3.10.10)
yarn install v1.0.1
[1/5] Validating package.json...
error zenkit@1.0.0: The engine "node" is incompatible with this module. Expected version "6.11.2".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by georeith** [comment]
`yarn --ignore-engines`
The issue is that one of your modules (`zenkit`) claims to be not compatible with your version of node. This is not a bug at all.
```error zenkit@1.0.0: The engine "node" is incompatible with this module. Expected version "6.11.2".```

**Comment by DerTieran** [comment]
Oh yea just realized it myself, totally over read this.
Closing.
