### ISSUE TITLE
[ bug ] yarn install fails

### ISSUE THREAD

**Issue by TheWolfNL** [yarnpkg/yarn#4358]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `yarn install` using `yarn 1.0.1` I get:
> yarn install v1.0.1
$ node scripts/use-yarn.js
This project uses yarn instead of npm. Please upgrade!
See https://yarnpkg.com.
To install dependencies:
$ yarn install
To install a new package (also adds to package.json):
$ yarn add [packagename]
To upgrade a package:
$ yarn upgrade [packagename]
For more help, see https://yarnpkg.com/en/docs/usage.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**If the current behavior is a bug, please provide the steps to reproduce.**
install 
> curl -o- -L https://yarnpkg.com/install.sh | sh
and run
> yarn install

**What is the expected behavior?**
that the dependencies get installed.

>yarn versions v1.0.1
{ http_parser: '2.7.0',
  node: '7.7.1',
  v8: '5.5.372.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
✨  Done in 0.04s.

**Comment by TheWolfNL** [comment]
Installing the previous version works for me now.
> curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.0

**Comment by BYK** [comment]
I think the project or environment you are working in is trying to determine if you are using `npm` or `yarn` and thinks the new version of yarn is actually `npm`. That's not something Yarn can fix :)

But if you can give more details about your environment, I may give you hints about how to get it resolved.

**Comment by TheWolfNL** [comment]
Found the problem, indeed we had a script checking whether we were using yarn.
So yarn 1.0.1 is using `npm_lifecycle_script` underneath?

**Comment by BYK** [comment]
#4330 was just merged after 1.0.0 that added support for this, yeah.
