### ISSUE TITLE
Error thrown from globally installed command (in Windows 10)

### ISSUE THREAD

**Issue by jkr2255** [yarnpkg/yarn#4373]
**Do you want to request a *feature* or report a *bug*?**: bug

**What is the current behavior?**

Command installed with `yarn global add` cannot work because of seeing other `node_modules` folder than Yarn's.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
C:\Users\username>yarn global add riot
yarn global v1.0.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "ajv-keywords@2.1.0" has incorrect peer dependency "ajv@>=5.0.0".
[4/4] Building fresh packages...
success Installed "riot@3.7.0" with binaries:
      - riot
Done in 6.53s.

C:\Users\username>riot -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\username\AppData\Roaming\npm\node_modules\riot\node_modules\riot-cli\lib\index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
```

I tried setting `NODE_PATH` to Yarn's `node_modules` folder, but nothing solved.

**What is the expected behavior?**

showing Riot version information.

**Please mention your node.js, yarn and operating system version.**

* yarn v1.0.1
* Node v6.11.3
* Windows 10 Home 1703 (Creators Update) 15063.540 x64

**Comment by BYK** [comment]
Please try running `yarn global bin` and adding that directory to your `PATH`. Then restart your terminal and try again.

Let us know if this doesn't solve the issue. If it does, please close the ticket :)

**Comment by jkr2255** [comment]
@BYK Sorry, I've had many mistakes.

* Riot command is in `riot-cli` package, not `riot`.
* Previously npm-installed executables remained.

So, the problem was in my local environment and tthoughts. thanks!

**Comment by BYK** [comment]
@jkr2255 thanks a lot for taking the time to come back here and share the details. Very much appreciated!
