### ISSUE TITLE
Flat dependencies but deep devDependencies

### ISSUE THREAD

**Issue by johnknoop** [yarnpkg/yarn#4380]
Hi

In my web project, I use yarn to resolve dependencies both for web application, in which case I want flat dependencies because the browser can only load one version of a package. However, I also use devDependencies for varies nodejs packages that I use in my build setup. When I use `"flat": true` I get to pick a specific version for a lot of different subdependencies to my nodejs dependencies. I don't really want to do that, as it isn't necessary. Is there any way to enable flat dependencies for just the dependencies, and leave the devDependencies deep?

**Comment by BYK** [comment]
I don't think this is possible since for a consistent dependency structure, all dependency types need to be considered holistically. This means you can't really separate `devDependencies` from `dependencies` when calculating the final tree.

Sorry :(

**Comment by BYK** [comment]
@arcanis @bestander @kittens LMK if I'm missing something.

**Comment by bestander** [comment]
Yeah, afaik flat works across all dependencies.

My first reaction would be to use different package.json files for client and server and use an application level script to ensure those are in sync.
It depends of course on how often they change and how many dependencies are in common.
Maybe the common part could be moved to a workspace.

**Comment by johnknoop** [comment]
Thanks guys for your answers

**Comment by BYK** [comment]
@johnknoop you're most welcome!

Are these useful enough to close the issue or would you like to keep the discussion open for any other potential solutions?

**Comment by johnknoop** [comment]
@BYK I'm satisfied with the answer. Closing...
