### ISSUE TITLE
Bug: silent mode through `--silent` not working with `yarn run`

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#4383]
#788 added a `--silent` mode for `yarn run` but it is not working anymore after 1.0

Culprit: #4152.

**Comment by alexraileanu** [comment]
@BYK this is still happening in 1.3.2. adding --silent doesn't do anything. do you have any updates regarding this?

**Comment by BYK** [comment]
@alexraileanu please file a new issue with the details since as far as this particular issue is concerned, it is fixed. Yours is probably different and we need all the details around it to be able to debug.
