### ISSUE TITLE
Windows: The engine "yarn" is incompatible with this module

### ISSUE THREAD

**Issue by rafalradomski** [yarnpkg/yarn#4396]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

`error ...@1.0.0: The engine "yarn" is incompatible with this module. Expected version "0.27.5".
error Found incompatible module`

**If the current behavior is a bug, please provide the steps to reproduce.**

Windows [installer always installs the latest version](https://yarnpkg.com/en/docs/install)

**What is the expected behavior?**

How I can switch yarn version on windows? 

**Please mention your node.js, yarn and operating system version.**

**Comment by BYK** [comment]
This is not a bug. Please refer to https://yarnpkg.com/en/docs/install#windows-tab

**Comment by Offirmo** [comment]
For fellow googlers, the required yarn version is given in package.json "engine" section, this is what is causing this warning

**Comment by BYK** [comment]
@Offirmo thanks for taking the time to help others :) Just to clear things up tho - the original ticket was about Windows installer not installing the latest version of Yarn, which was not correct (it was but there was another yarn in the PATH preventing the system from using the latest, installed version).

The way @rafalradomski expressed it was through the warning you mention. That said the warning/error is a desired thing if the yarn version doesn't match. Hope this clears it a bit more both for you and for anyone visiting this issue in the future.
