### ISSUE TITLE
Clarify whether npm can or should not be used to install yarn.

### ISSUE THREAD

**Issue by mikemaccana** [yarnpkg/yarn#4398]
Per #1648. On https://yarnpkg.com/en/docs/install#windows-tab:  it would be nice for the install page to clarify either: 

 - That npm can be used to install yarn (and how)

OR

 - That npm should not be used to install yarn (and why)

**Comment by BYK** [comment]
There's a section about npm on https://yarnpkg.com/en/docs/install#alternatives-tab

Is that not enough?

**Comment by mikemaccana** [comment]
The content is perfect and exactly answers my question:

> Note: Installation of Yarn via npm is generally not recommended...

Thanks Burak!

It's just in the wrong place in 'Alternatives'. These instructions are
presented as a peer for Windows, Mac and Linux. Users will only see them
they're not running Windows, Mac or Linux

**Comment by mikemaccana** [comment]
@arcanis Why was this closed?

**Comment by BYK** [comment]
@mikemaccana I think @arcanis closed this since your original question was answered. We can keep this open but since your follow-up question/suggestion is related to the website, I'd encourage you to file an issue there: https://github.com/yarnpkg/website/issues/new

**Comment by mikemaccana** [comment]
Thanks and done https://github.com/yarnpkg/website/issues/650
