### ISSUE TITLE
`yarn config set workspaces-experimental true` doesn't work, copying `.yarnrc` does

### ISSUE THREAD

**Issue by mikemaccana** [yarnpkg/yarn#4405]
yarn 1.0.1 on a Debian 8 LTS box (being run via Circle CI):

    #!/bin/bash -eo pipefail
    yarn config set workspaces-experimental true
    yarn config v0.27.5
    error The workspace feature is currently experimental and needs to be manually enabled - please add "workspaces-experimental true" to your .yarnrc file.
    info Visit https://yarnpkg.com/en/docs/cli/config for documentation about this command.
    Exited with code 1

Doesn't `yarn config set workspaces-experimental true` count as manually enabling the feature? Copying `.yarnrc` works fine as a workaround.

**Comment by BYK** [comment]
Looks like you're using an old version of yarn: `yarn config v0.27.5`

Workspaces are enabled by default in 1.0.0+

**Comment by mikemaccana** [comment]
Looks like the Debian packages in the install page are out of date. Should I file a separate issue?

**Comment by mikemaccana** [comment]
See #4407
