### ISSUE TITLE
Error: unexpected end of file while fetching packages during yarn install

### ISSUE THREAD

**Issue by MaxCCC** [yarnpkg/yarn#4412]
On our Jenkins on Linux (we use version 1.4 of the frontend-maven-plugin)
```
[INFO] yarn install v0.23.4
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[ERROR] error An unexpected error occurred: "https://url/artifactory/api/npm/npm/rxjs/-/rxjs-5.4.0.tgz: unexpected end of file".
```

We get this error in 50% of our run's of the job. So sometimes it's working. The unexpected end of file is always on another file so it has nothing to do with that.

Is it a network 'issue'? Sometimes a network warning appears during the fetch. Can we extend some timeout of give jenkins more time to fetch the right packages?

**Comment by BYK** [comment]
That looks like a network or system issue. Also, your yarn version looks a bit old. If you switch to a newer version, you may get a more informative error message helping you diagnose the problem.

**Comment by MaxCCC** [comment]
@BYK I've upgraded to 0.28.4 (1.0.1  has some different folder settings). But I'm still facing the same issue/log. We just connect with our own artifactory (which we also do from our local machines where we never have this issue). The log isn't clear.

**Comment by BYK** [comment]
@MaxCCC can you elaborate on why you cannot use 1.0.1 since there are many fixes on it. Actually, I'd highly recommend using one of the latest nightlies since they have even more fixes.

**Comment by BYK** [comment]
>We just connect with our own artifactory (which we also do from our local machines where we never have this issue). 

May be it is reporting an incorrect `Content-Length` header that confuses our requests module or Yarn itself?

**Comment by MaxCCC** [comment]
Because when I use 1.0.1 I got

` [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:yarn Cannot run program "/xxx/mum-frontend-angular/target/node/yarn/dist/bin/yarn" (in directory "/srv/autobuild/workspace/xxx-frontend-angular"): error=2, No such file or directory
`
And for now we need this plugin version.

I don't know. Even with -e or -X options it's not telling me anything more. I don't know much about the content-length header

**Comment by BYK** [comment]
@MaxCCC 

Which version of Node are you using? That sounds like due to an older version of Node not supporting a new option we are using in yarn. Node 4.8, or 5.7+ should be fine for 1.0

For the issue you are experiencing, if you can find a way for us to replicate it, I'd be more than happy to help. Right now I really don't know how or why it happens. If you can switch to 1.0, then I may be able to add more tracing or get you a specific build with more logging for debug.

**Comment by MaxCCC** [comment]
@BYK I"ll try to provide some more info. (To upgrade to 1.0 I have to ask/speak with some other people first).
We use the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin#installing-node-and-yarn). The URL will redirect you to how we configure our node and yarn setup for this plugin. We also use node and npm where everything works fine.

Our properties>
    <nodeVersion>v7.10.0</nodeVersion>
    <npmVersion>3.10.10</npmVersion>
    <yarnVersion>v0.23.4</yarnVersion> (and tested with v0.28.4)
  </properties>
```
The command which we are executing is `mvn clean source:jar install -Pyarn -DSkipTests`.
Often the first time doesn't work and starting a new run immediately after the failed run is most of the time successful. To install Yarn we use our own Artifactory where we have some local yarn repository. 

```
[INFO] Running 'yarn install --https-proxy=http://proxystuff:80 --proxy=http://proxystuff:80' in workspace/..
[INFO] yarn install v0.28.4
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages... (fail)
```
The dependencies are coming from our registry 
`[ERROR] error An unexpected error occurred: "https:/xxx/artifactory/api/npm/npm/@angular/router/-/router-4.1.2.tgz: unexpected end of file".`

**Comment by MaxCCC** [comment]
@BYK adding `--verbose` to the yarn install gives a bit more output:
```
unexpected end of file
[INFO]     at Zlib._handle.onerror (zlib.js:355:17)
```

It's maybe a duplicate of https://github.com/react-community/create-react-native-app/issues/120 but I don't know how to debug this network issue? We use our own artifactory, for npm it's working fine (always). The GET URL's provide an expected output with the URL of our repo on artifactory.

**Comment by MaxCCC** [comment]
@BYK Now we try to connect to our registry without https.
Now we see in the logs: GET https:/xxx/artifactory/... but in our pom, .npmrc, .yarnrc etc we're all specyfing: http://xxx/artifactory:port and some _auth token + strict ssl false etc etc. but we still see this https://URL inside our logs during the GET.

**Comment by BYK** [comment]
May I ask why you are setting `--https-proxy` to an HTTP address? That looks fishy. Also what do you have in your `yarn.lock` file as the URL for these packages?

**Comment by MaxCCC** [comment]
@BYK Yes that's for testing purposes now. Well the yarn.lock contains indeed the `https://url/artifactory/api/npm/npm/@dependecie...` for every package. This yarn.lock is inside our git. It's autogenerated. It seems not to use` .npmrc` or `.yarnrc` to find the registry URL. I don't know where it's finding the https://url/artifactory URL. Based on which files or input is it is generated? Thanks

**Comment by MaxCCC** [comment]
@BYK The problem seems to be the yarn.lock which is slower over https than over http. We keep everything internal so we can use http inside our CI. But for our developers we want to keep https. This means the registries inside our yarn.lock will be different for devs and for the CI server.
Is there a way to force a regeneration of this yarn.lock? I read you have to keep it in Git (like we do) but when I delete the file and execte our` mvn clean install -Pyarn ` it will regenerate the yarn.lock based on the `.yarnrc `. I'm now a bit facing the 'issue' of best practice (keep yarn.lock in git) and our own 'solution' to regenerate yarn.lock on the CI server with another registry URL

**Comment by MaxCCC** [comment]
@BYK Now it seems that when I delete the `yarn.lock` it will recreate it but again with the https URL. The resolve of packages happens on `http://:` and the fetch happens on `https://`. Isn't it created based on our .yarnrc or .npmrc which both only contain the `http://`:
