### ISSUE TITLE
yarn 1.x 404's on private packages

### ISSUE THREAD

**Issue by jquense** [yarnpkg/yarn#4422]
private packages fail to install in CI. It should be noted that this repo is using workspaces, but I cannot confirm that that it works in a non-workspaces case.

**What is the current behavior?**

```sh
yarn install v1.0.1-20170912.1314
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@mycompany/sunburst/-/sunburst-0.2.2.tgz: Request failed \"404 Not Found\"".
```
**If the current behavior is a bug, please provide the steps to reproduce.**

This happens in a Docker container on Circle CI where the previous step is to 

```
echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
mkdir -p ~/yarn-cache
yarn install --cache-folder ~/yarn-cache
```
This works on yarn 0.28.x

**Please mention your node.js, yarn and operating system version.**

docker/node:8
yarn latest nightly

**Comment by BYK** [comment]
>yarn install v1.0.1-20170912.1314

This is not the latest nightly. Can you try the actual latest one: https://nightly.yarnpkg.com/yarn-1.0.1-20170912.1621.js

This should include #4367 which should be the final fix regarding auth and scoped packages.

**Comment by jquense** [comment]
gladly! i'm not sure how to do that tho we used: `curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly` and that's what came down

**Comment by BYK** [comment]
@jquense it is probably because I've merged it quite recently and then buids take some time. Sorry for the repeated work and thanks a lot for hleping!

**Comment by jquense** [comment]
np thanks for all the speedy work. I'm pulling it down now and trying

**Comment by jquense** [comment]
🌈 🌈 ⭐️  🎉 🎉 That did it! Sorry for the noise. THANKS!

**Comment by BYK** [comment]
>That did it! Sorry for the noise. THANKS!

No worries, thanks for helping!

**Comment by darkobits** [comment]
Also experiencing this issue after upgrading to `1.x`.

Any idea when this fix will be officially released?

**Comment by BYK** [comment]
>Any idea when this fix will be officially released?

In a few days. In the meantime you can use the nightlies: https://yarnpkg.com/en/docs/nightly

**Comment by jedwards1211** [comment]
@BYK the fix was released in 1.0.2?  I think I'm still seeing issues

**Comment by jedwards1211** [comment]
@BYK for some reason it fails when I use yarn 1.0.2 in docker, but not on my local machine...

```Dockerfile
FROM node:8.5
MAINTAINER Andy Edwards

RUN npm install --global yarn@^1.0.2

WORKDIR /usr/app/build

ARG NPM_TOKEN

RUN echo $NPM_TOKEN

# Project uses private NPM modules. Pass in NPM token externally.
# Tell NPM to use the token from the environment variable
RUN echo "registry=https://registry.npmjs.org/" > /usr/app/build/.npmrc
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /usr/app/build/.npmrc
RUN echo 'registry "https://registry.npmjs.org"' > /usr/app/build/.yarnrc

ARG NODE_ENV=production
ARG TARGET=""
ARG BUILD_DIR=build

ENV NODE_ENV=$NODE_ENV \
    TARGET=$TARGET

COPY package.json yarn.lock /usr/app/build/

RUN yarn --pure-lockfile
```

...
```
Step 17/22 : RUN yarn --pure-lockfile
 ---> Running in 4cbf8ef83d66
yarn install v1.0.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.npmjs.org/@jcoreio/gridutil/-/gridutil-1.0.10.tgz: Request failed \"404 Not Found\"".
```

**Comment by yonbeastie** [comment]
@BYK any update on this? It looks like this problem still persists with v1.0.2.

For context, running yarn@1.0.2 on circleci and getting 404 for private packages in the same way others have reported with docker. Thanks!

**Comment by darkobits** [comment]
I can confirm this is still an issue (with Docker in Jenkins, in my case) in `1.0.2`.

**Comment by xogeny** [comment]
Have the issues with Docker + `1.0.2` been resolved?  If not, shouldn't this be re-opened?

**Comment by jedwards1211** [comment]
With 1.3.2 at least, I'm not seeing this error anymore.

Additionally, there was a bug in my Dockerfile above.  One of my echo commands overwrites the other:
```
RUN echo "registry=https://registry.npmjs.org/" > /usr/app/build/.npmrc
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /usr/app/build/.npmrc
```
The second command should use `>>` instead of `>`.

**Comment by sundowndev** [comment]
I had the same issue with a 503 error, adding `registry=https://registry.npmjs.org/` to `.npmrc` fixed it.
