### ISSUE TITLE
Yarn sets terminal color to white 

### ISSUE THREAD

**Issue by pfgithub** [yarnpkg/yarn#4424]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After running a yarn command (such as --help or installing something) if the terminal color changes to white it stays white after finishing running yarn

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `color` in cmd
Run `yarn --help`
Notice how the color of the command line prompt has become white instead of staying gray

**What is the expected behavior?**
The terminal color should stay what it was before after running a yarn command (gray on windows, but if it was set to red, it should end red)

**Please mention your node.js, yarn and operating system version.**
Node v7.9.0, Windows 10, npm 5.4.1, Yarn 1.0.1

**Comment by BYK** [comment]
Yup, it indeed does this. I think this is a bug in `chalk`. We are using 1.1.3 and 2.0.0 is out so may be an upgrade would fix it. There are not too many breaking changes.

**Comment by 1jerry** [comment]
Still | again happening.  Node 7.9 | 8.7, Windows 10, yarn 1.2.1.
Every yarn command (except yarn -v) changes the screen to white letters.
