### ISSUE TITLE
Outdated error message about global command

### ISSUE THREAD

**Issue by Persola** [yarnpkg/yarn#4426]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

An npm user, I naively tried:
```
$ yarn install -g node@8.4.0
yarn install v1.0.1
error `--global` has been deprecated. Please run "yarn global node@8.4.0" instead.
```
Great that it provides a suggestion! But when I tried that command:
```
$ yarn global node@8.4.0
yarn global v1.0.1
error Invalid subcommand. Try "add, bin, ls, list, remove, upgrade, upgrade-interactive"
```
So it prompted me to use an invalid command.

**What is the expected behavior?**

It doesn't prompt the user the use an invalid command. Ideally, it provides the correct command.

**Please mention your node.js, yarn and operating system version.**

node 8.3.0
yarn 1.0.1
macOS 10.12.5

**Comment by kamthamc** [comment]
@Persola i think the suggestion is missing add
i think it should be `yarn global add node@8.4.0`

**Comment by BYK** [comment]
PR? :)

**Comment by kamthamc** [comment]
@BYK #4449 should resolve it

**Comment by Persola** [comment]
Thanks!
