### ISSUE TITLE
Bug: ENOENT No such file or directory in Yarn 1.0.1

### ISSUE THREAD

**Issue by sampsonjoliver** [yarnpkg/yarn#4427]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`error An unexpected error occurred: "https://registry.yarnpkg.com/canned/-/canned-0.3.9.tgz: ENOENT: no such file or directory, open 'C:\\Users\\samjo\\AppData\\Local\\Yarn\\cache\\v1\\npm-canned-0.3.9-b0bfdeffdc595dd5c0055730b808d5c26b4caa02\\spec\\test_responses\\_a?name=Batman&age=30.get.html'".`

**If the current behavior is a bug, please provide the steps to reproduce.**
Running `yarn add` or in fact any `yarn` invocation after adding `"canned": "^0.3.10"` as a dev dependency to my package.json results in the error. All other packages (that I've used in this project so far) resolve without issue.

True to what the error suggests, the directory does not exist.

I have tried deleting my node_modules folder, removing the yarn.lock file, using a different version of canned (`0.3.9` produces the same behaviour), clearing the yarn cache, uninstalling yarn and cleaning all cache folders then reinstalling - all to no success. Rolling back yarn to `0.27.0` however has resolved the issue.

**What is the expected behavior?**
Correctly fetching the package from its repository.

**Please mention your node.js, yarn and operating system version.**
node v6.9.1, yarn v1.0.1, Windows 10 Pro Insider Preview Build 16278.rs3_release.170825-1441

**Comment by BYK** [comment]
I can reliably reproduce this.

**Comment by BYK** [comment]
Well, this is noy Yarn's fault but a problem with the package itself. That file has `?` in its name and that character is not allowed in file or folder names on Windows: https://support.microsoft.com/en-us/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names--fo
