### ISSUE TITLE
Remove *.gz from default .yarnclean

### ISSUE THREAD

**Issue by nkbt** [yarnpkg/yarn#4450]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`autoclean` command has `*.gz` in default `.yarnclean` file.
https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/autoclean.js#L56

Problem: some packages are coming with `gz` to reduce package size

I reckon it is quite a minor issue, but not obvious why required files are missing.

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh
docker run -it mhart/alpine-node:8
# then
rm -rf /test
mkdir /test
cd /test
cat > package.json <<- EOM
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "left-pad": "*"
  }
}
EOM
yarn install
yarn autoclean --init
yarn remove left-pad
yarn add @std/esm
find .
```

Result:
```sh
/test # find .
.
./package.json
./.yarnclean
./node_modules
./node_modules/.yarn-integrity
./node_modules/@std
./node_modules/@std/esm
./node_modules/@std/esm/package.json
./node_modules/@std/esm/LICENSE
./node_modules/@std/esm/index.js
./yarn.lock
/test #
```

Running same code but omitting `yarn autoclean --init` line:
```sh
/test # find .
.
./package.json
./node_modules
./node_modules/.yarn-integrity
./node_modules/@std
./node_modules/@std/esm
./node_modules/@std/esm/README.md
./node_modules/@std/esm/package.json
./node_modules/@std/esm/LICENSE
./node_modules/@std/esm/index.js
./node_modules/@std/esm/esm.js.gz
./yarn.lock
```

**What is the expected behavior?**
`gz` should stay

**Please mention your node.js, yarn and operating system version.**
```sh
#OS: mhart/alpine-node:8

/ # node -v
v8.5.0
/ # yarn -v
1.0.1
/ #
```

**Comment by BYK** [comment]
Sounds fair. Would you like to submit a PR?

**Comment by BYK** [comment]
That said, this would be a breaking change for people relying on this behavior.

**Comment by nkbt** [comment]
Sure, will do a PR.

This is only a default value for cleanup. Just removing `*.gz` might be a one solution.

Alternatively (or in addition) - maybe worth giving some note to user if some files were cleaned up. Like basic stats. For example:

> X files matched by .yarnclean and were automatically removed, Y Mb space saved

In this case it will be both helpful and will act as an indication/reminder that there is an auto-cleaning process in place.

**Comment by BYK** [comment]
The thing with `autoclean` is, it doesn't run automatically unless you set it up with a `.yarnclean` file. And when you do, you can override this list in that file so not sure showing a list of files is that useful. What do you think?

**Comment by nkbt** [comment]
Tge thing is, I personally set up autoclean couple of months ago and completely forgot about it, because it is 'auto'. Showing list of files would be too heavy, I was more thinking about one line stats/reminder that there are *some* files deleted by autoclean. This way it would be impossible to forget about it.

Regarding pr it may be not as simple as removing one line. I ran tests yesterday with gz removed and got like 30 trsts failing. Reverted to master and still had about 7 test failing. This is strange since I could see tests pass on circleci. I am on the latest macbook pro and tests run for over 2 minutes. Will have to dig a bit more to figure out why tests may fail on master branch first.

**Comment by jdalton** [comment]
Just a heads up, Lodash v5 will ship with `gz` modules.

**Comment by BYK** [comment]
I think it is reasonable to remove `.gz` from the default list then. I also think @nkbt's idea of informing the user about what is being deleted or what was deleted after the fact is a good idea.

That means 2 PRs. Anyone up for it? They should be fairly simple.

**Comment by nbarray** [comment]
Not sure if @nkbt is working on the one line reminder. If not, I can give it a try. I will start by removing the .gz from the default list too :)

**Comment by nbarray** [comment]
I just made a PR to remove the *.gz line from the default filters used to generate the default .yarnclean file (PR #4601)

I'll prepare something for the one-line reminder in the meantime.

**Comment by nbarray** [comment]
It looks like that number of file remove + the saved space is already reported a info after a `yarn autoclean --force`. (#659 for the freed space size)

I think it matches what @nkbt wanted.
