### ISSUE TITLE
An unexpected error occurred: "write EIO"

### ISSUE THREAD

**Issue by vp2177** [yarnpkg/yarn#4455]
Yarn v1.0.2

**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

- `yarn install` now fails (worked previously in same folder)
- Output: <details><summary>&gt; yarn install</summary>
<pre>
yarn install v1.0.2
[1/4] Resolving packages...
error An unexpected error occurred: "write EIO".
info If you think this is a bug, please open a bug report with the information provided in "D:\".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
</pre>
</details>

**If the current behavior is a bug, please provide the steps to reproduce.**

- `yarn install`

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
Node v8.5.0
Yarn v1.0.2
Windows 7 (Build 7601)

[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/1302621/yarn-error.log.txt)

**Comment by BYK** [comment]
This looks more like a problem with your system: https://stackoverflow.com/a/21184384

**Comment by BYK** [comment]
That said we have changed the progress bar characters after 1.0.2 so the latest nightly may just work for you: https://yarnpkg.com/en/docs/nightly

**Comment by vp2177** [comment]
I think it is a bug in Node, not only `yarn` but other Node apps are failing as well.
Older (much older) version of Node works.

**Comment by BYK** [comment]
@vp2177 I'm on Windows 10 with Node 8.5 and yarn works fine for me. May be it is a Win 7 thing?

**Comment by ddimass** [comment]
You must change codepage in command prompt by:
"chcp 866" - its for Russian example

**Comment by pahan35** [comment]
@ddimass your advice really helps me.
![image](https://user-images.githubusercontent.com/13823215/48499872-202b6300-e842-11e8-97a8-e44aa019727b.png)

For making it clearer: in my case problem happens on Windows Server 2012
When I run `yarn` I got an error `error An unexpected error occurred: "write EIO"`
Then I run `chcp 866` (I guess there is an English interface)
Then run `yarn` completed successfully
