### ISSUE TITLE
Registry URL in .npmrc is only used during resolving of packages

### ISSUE THREAD

**Issue by MaxCCC** [yarnpkg/yarn#4460]
Yarn version: `v0.28.4`
We define in our .npmrc the following URL:
`registry=http://url:8081/artifactory`

During `yarn install --no-lockfile` we see:
```
[INFO] [1/4] Resolving packages...
[INFO] verbose 0.92 Performing "GET" request to "http://url:8081/artifactory/api/npm/npm/@angular%2fcore".
But the second step:
[INFO] [2/4] Fetching packages...
[INFO] verbose 1.401 Performing "GET" request to "https://url/artifactory/api/npm/npm/@angular/core/-/core-4.1.2.tgz".

```

We ignore the lock-file because we want to go over http instead of https (which is in the lockfile). It's a temporary workaround but we need it now.
But as you can see the fetch of packages is still going over https.

The problem is that the URL which is in` .npmrc` is only used in the first step to resolve the packages. In the second step it's using the URL which is provided as Custom Base URL inside our Artifactory. We can't change this URL to http because there would be to much impact. 

Is there a possibility in Yarn to keep the URL which is provided in `.npmrc` during the full install instead of taking the Artifactory Custom Base URL in the next steps?

**Comment by BYK** [comment]
I don't think this is possible since the core logic is to favor the lockfile. Why do you need this again? Is it not possible for you to edit the lockfile to replace the URLs if this is an edge case?

**Comment by MaxCCC** [comment]
@BYK We have troubles to go over https (unexpected end of files). This is not happening when we go over http. This should be possible because everything is internal on our own network. Maybe we can replace the https url's with http in the lockfile but we we're afraid for issues because we aren't supposed to edit that file manually.

**Comment by paul-soporan** [comment]
Closing as in v2 we completely stopped reading `.npmrc` files.

https://yarnpkg.com/getting-started/migration
