### ISSUE TITLE
How to run scripts for all packages under a workspace?

### ISSUE THREAD

**Issue by giridharangm** [yarnpkg/yarn#4467]
I'm not sure whether this qualify as a bug or feature. I couldn't find anything related to this.  

By using workspaces, can we run a common script command from the root directory, and it'll execute that script in all packages under that workspace.? (Just like how `lerna` does. When we run `lerna run test` from the root directory, it'll execute the `test` script for all the packages under that repo).  

This would help a lot for CI/CD stuff.

**Comment by Alexter-progs** [comment]
Well, idk if there is something like lerna in yarn, but as workround you can try to create scripts in root package calling scripts in your packages

`"scripts": {
 "test": "yarn test-package1 && yarn test-package2"
"test-package1": "cd package1 && yarn test",
"test-package2": "cd package2 && yarn test"
}`

Though this won't work if test script runs forever until you manually shut that down (for example starting server), but i'm sure you can hack it :)

**Comment by giridharangm** [comment]
This was the first way that came to my mind. But this run scripts will eventually grow. (The one that I'm currently working has 8 packages, and I can't even think of adding a specific run script to each package 😬 ).  

On the other hand lerna handles this beautifully. I know yarn doesn't replace lerna, but the workspaces feature is a tempting one, and it'd be cool to have it as a built-in feature 😇

**Comment by Alexter-progs** [comment]
Ye, adding scripts to more then 2 packages is tedious. Having that feature in yarn would be nice, totally agree :)

**Comment by giridharangm** [comment]
![image](https://user-images.githubusercontent.com/2258588/30645876-bdec2d58-9e34-11e7-8358-65112a305c1b.png)
^ This sentence makes me sad

**Comment by BYK** [comment]
Then let's come up with a solution in the form of an RFC? Here are some ideas I see that can work:

 - Have a `yarn workspaces list` command so people can get the resolved workspaces to iterate on them with bash or whatever
 - Have a `yarn workspaces run` command that runs a script in each workspace and errors out when one is not found

I'm sure you guys can come up with more and better solutions though :)

**Comment by giridharangm** [comment]
+1 for the `list` command. I guess the `workspaces` sub-command will reduce a lot of overhead in the CLI.

**Comment by BYK** [comment]
@giridharangm would you like to give sketching out a fuller picture in an RFC so someone can implement it?

**Comment by giridharangm** [comment]
@BYK yeah, sure!. I haven't done any RFCs before, so, 😇

**Comment by BYK** [comment]
Closing this in favor of the RFC. Let's continue the discussion there.

**Comment by jonaskello** [comment]
There is the [wsrun](https://www.npmjs.com/package/wsrun) package that runs commands in multiple packages in a yarn workspeces mono repo. It would be great to have the same functionality in yarn itself. I'm just thinking it might be worth to look at how wsrun works today and what options it has etc. in order to gather info for the RFC.

**Comment by jrschumacher** [comment]
This can also be achieved via this command, but requires jq.

`COMMAND=build yarn workspaces info | awk 'NR>2 {print last} {last=$0}' | jq -r 'keys[]' | while IFS=$'\n' read -r workspace; do yarn workspace "$workspace" "$COMMAND"; done`

**Comment by cancerberoSgx** [comment]
Just in case, in the root folder, what I did was: 
```
yarn add wsrun --dev
```
then in package.json added this script: 
```
    "run-all": "yarn run wsrun",
```
so now I can run commands in all workspaces like this: 
```
yarn run-all test
```
Although I agree with one of the contributors that yarn shouldn't be waiting time in this kind of high level features and probably this should be tackled by companion extensions / tools like this wsrun, I think this particular one is very easy to implement and very useful for large workspaces. Couldn't believe yarn don support it out of the box. I won't do PR cause probably will be rejected and this works fine. 

my two cents.

**Comment by eps1lon** [comment]
This was added with #6244 and released in `yarn@1.10.0`.

You can now do `yarn workspaces run script`

**Comment by alexindigo** [comment]
@BYK any plans on implementing `--parallel` flag? Current way makes our tests super slow and developers sad.

**Comment by Pranit-Harekar** [comment]
I think the original question was about running a script (like `test`) on all the packages in a workspace? @eps1lon  right? I don't think `yarn workspaces run script` achieves that.

**Comment by eps1lon** [comment]
> I think the original question was about running a script (like `test`) on all the packages in a workspace? @eps1lon right? I don't think `yarn workspaces run script` achieves that.

@Pranit-Harekar 
From the context
> (Just like how `lerna` does. When we run `lerna run test` from the root directory, it'll execute the `test` script for all the packages under that repo).

it was pretty clear that 
`yarn workspaces run test` should be equivalent to `yarn workspace workspaceA test && yarn workspace workspaceB test`. It seems like that you think it should run a given script foreach workspace where `cwd` is the workspace directory? That is not how lerna works.

**Comment by zhenwenc** [comment]
Thanks a lot for adding `workspaces run`! I can almost get rid of lerna now!

One missing piece, Is it possible to skip a package if no such script defined? For example, one package may not have "test" script defined in it's `package.json`. At the moment, yarn will fail with:

```
yarn run v1.13.0
error Command "test" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

Thanks in advance!

**Comment by else** [comment]
It's the same behavior with `lerna` IIRC. You can simply add `"test": "exit 0"`.

**Comment by Yzrsah** [comment]
@zhenwenc I agree, this is a problem.

We have to add empty scripts to every workspaces for all commands. Some workspaces don't require build, but they always need an empty build script. These packages should not have code unrelated to their functionality.

**Comment by Yzrsah** [comment]
@zhenwenc I agree, this is a problem.

We have to add empty scripts to every workspaces for all commands. Some workspaces don't require build, but they always need an empty build script. These packages should not have code unrelated to their own functionality.

**Comment by Yzrsah** [comment]
@zhenwenc I agree, this is a problem.

We have to add empty scripts to every workspaces for all commands. Some workspaces don't require build, but they always need an empty build script. These packages should not have code unrelated to their own functionality.

> Dear upstream maintainer, can you please add `"build": "",` script to every subpackage's `package.json`'s so that `workspaces run build` will work at the root?
>> No

**Comment by Yzrsah** [comment]
@zhenwenc A new issue was created and referenced here: https://github.com/yarnpkg/yarn/issues/7121

**Comment by wise-introvert** [comment]
Is it possible to run an npx or bash(for globally installed npm packages) command using this new feature(`yarn workspaces run script`)?

**Comment by merceyz** [comment]
In v2 you can run `yarn workspaces foreach exec <anything here>`

**Comment by wise-introvert** [comment]
@merceyz thanks!

**Comment by merceyz** [comment]
Yeah, as you can see from the output you're running v1.22.5, it's a command added in v2.0 - https://yarnpkg.com/getting-started/migration

**Comment by wise-introvert** [comment]
Oh. I feel so stupid now 😅. Thanks!

**Comment by jcollum-nutrien** [comment]
We use Turbo to run the same script in all workspaces that have that script name in the package.json.

**Comment by kopax** [comment]
my macos/linux solution on yarn < 2 to run tsc in a monorepo 

`$ find . -maxdepth 3 -name tsconfig.json -not -path '*/node_modules/*' | sed -r 's|/[^/]+$||' | xargs -I {} yarn tsc --project {}`
