### ISSUE TITLE
Yarn 1.0.2 skipping deps installation (minimist)

### ISSUE THREAD

**Issue by Blackening999** [yarnpkg/yarn#4491]
Yarn 1.0.2
BUG

**What is the current behavior?**
Yarn is missing minimist dependency  for mkdirp and other dependencies during installation

Error:
```
Cannot find module '/Users/NAME/Work/My_Projects/PROJECTNAME/node_modules/mkdirp/node_modules/minimist//package.json'
```

```
├─┬ ember-browserify@1.2.0
│ └─┬ mkdirp@0.5.1
│   └── minimist@0.0.8 
```

Add the ember-browserify as a dependency or any library that uses mkdirp, minimatch..
-

-
what it should do - is install deps, right now the hack is to use ```npm install```

**Please mention your node.js, yarn and operating system version.**
OS X 10.12.3
Node: 6.11.2
npm: 3.10.10

**Comment by rommsen** [comment]
We have the same problem with  the `debug` library use by ava for example.

```
ava specs/ --require babel-register

module.js:529
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:527:15)
```
We went back to 0.27.5. Everything works fine there

**Comment by Blackening999** [comment]
well, I don't think it's a good solution to jump to 0.27.5 :) you'd better do npm install and keep the latest version
But for sure it's a big issue that requires attention

**Comment by rommsen** [comment]
Well our build scripts do use yarn for production releases. No use in changing those scripts when we have a working version available.

**Comment by BYK** [comment]
This may be due to a bug in resolving `peerDependencies` which is fixed on master. Can you try the latest nightly to see if it fixes the issue: https://yarnpkg.com/en/docs/nightly

**Comment by ShadowMen** [comment]
The newest nightly worked for me! Thank you 👍

**Comment by BYK** [comment]
@ShadowMen nice! Since this is fixed on master, closing the ticket. Will release a new version soon!
