### ISSUE TITLE
Report line number and column for syntax errors

### ISSUE THREAD

**Issue by Pajn** [yarnpkg/yarn#4493]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
```
error An unexpected error occurred: "/path/to/package.json: Unexpected string in JSON at position 23"
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a syntax error in your package.json, for example remove or add a comma.

**What is the expected behavior?**
Yarn should report line and column number instead of position.

**Please mention your node.js, yarn and operating system version.**
```
❯ yarn --version
1.0.1
```

**Comment by BYK** [comment]
We are using the built-in `JSON.parse()` method which throws this error. You may have better luck talking to Node people about why the exception doesn't have a line number.

**Comment by Pajn** [comment]
Hmm. One could argue that an exception message and a user message have different purposes.
Knowing the position might be interesting in the exception case where you can use .slice to know what the character at that position is but a message towards an user should show what the text editor shows (which is line and column number).

**Comment by BYK** [comment]
@Pajn I understand what you're saying. That said there is no easy way to get the line number without using a custom parser which would be overkill for this.

**Comment by bdwain** [comment]
If I'm having trouble finding the error I usually just plug my package.json into an online json linter, which will find the syntax error quickly.

**Comment by BYK** [comment]
@Pajn I'm inclined to close this issue since it is not really actionable on our side. Are you okay with that?

**Comment by Pajn** [comment]
I would rather have it fixed, maybe with a workaround to work out the line/column from the position if that's the only possible way. But I do understand your side. Close it if you prefer.

**Comment by BYK** [comment]
@Pajn I understand and agree with it but I don't see a good solution except for using a separate JSON parser for this which would possibly slow yarn down and increase its bundle size.

If you have a strong alternative in mind, please submit a PR and I'd gladly review it. Until then, closing the issue. Again, feel free to reopen it if you have things in mind to discuss.

**Comment by HaleTom** [comment]
@BYK I'd be happy to raise this problem with JSON.parse(). What is the repo link to do it in?

**Comment by eliemichel** [comment]
As this is really annoying, what about a quick and dirty workaround that reads the offset from the exception message? Would simplify the life of many people I believe:

```JavaScript
// Return value, error message
function tryParseJson(x) {
    try {
        return { value: JSON.parse(x), error: null };
    } catch(e) {
        const offset = parseInt(e.message.substring(e.message.lastIndexOf(' ')));
        const prefix = x.substring(0, offset);
        const line = prefix.split("\n").length;
        const column = prefix.length - prefix.lastIndexOf("\n");
        return { value: null, error: `At line ${line}, column ${column}: ${e.message}` };
    }
}
```

**Comment by broofa** [comment]
FYI, node@21 fixes this.  See https://github.com/nodejs/node/issues/24361#issuecomment-1937994382
