### ISSUE TITLE
Can't use list command inside a package within a workspace-based project

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#4494]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

```
$ yarn list
yarn list v1.0.2
error No lockfile in this directory. Run `yarn install` to generate one.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

0. `$ git clone git@github.com:pedronauck/yarn-workspaces-example.git`
0. `$ cd yarn-workspaces-example/packages/a`
0. `$ yarn`
0. `$ yarn list`

**What is the expected behavior?**

```
$ yarn list
yarn list v1.0.2
├─ a@1.0.0
└─ b@1.0.0
   └─ a@^1.0.0
✨  Done in 0.15s.
```

Or maybe just this... (not the whole workspace)?

```
$ yarn list
yarn list v1.0.2
└─ a@1.0.0
✨  Done in 0.15s.
```

**Please mention your node.js, yarn and operating system version.**

- Node v6.9.1
- yarn v1.0.2
- Mac OS X

--- 

Workspaces look great so far! ♥

**Comment by donaldpipowitch** [comment]
Note. I think there are more broken commands. It looks like I can't use `$ yarn upgrade-interactive` inside a specific package either (and there is no point to do it in the workspace root?)

**Comment by SukantGujar** [comment]
The upgrade command should also have the same behavior as the install command even if run from the root context. It should show possible upgrades for all the workspace packages in that case.

**Comment by donaldpipowitch** [comment]
Probably a duplicate of  https://github.com/yarnpkg/yarn/issues/4469. I'll close my issue.
