### ISSUE TITLE
yarn global upgrade-interactive doesn't work

### ISSUE THREAD

**Issue by dhcmrlchtdj** [yarnpkg/yarn#4500]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
`global upgrade` and `global upgrade-interactive` seem not work.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn global add prettier@1.6.1
$ yarn global upgrade-interactive --latest
```

**What is the expected behavior?**
Yarn should report that prettier can be upgraded to 1.7.

**Please mention your node.js, yarn and operating system version.**
node v8.5.0
yarn 1.0.2
macOS 10.12.6

**Comment by publicarray** [comment]
This is probably due to #4443 and #4390

**Comment by amannn** [comment]
Seems like this is by intention: https://github.com/yarnpkg/yarn/issues/4439#issuecomment-330325134

`yarn upgrade-interactive --latest` works for me.

**Comment by dhcmrlchtdj** [comment]
> passing the -L/--latest flag will tell upgrade-interactive to ignore the package.json specified range and use the latest as specified by the registry

The `--latest` flag works for `update / upgrade-interactive` but not `global update`.

https://github.com/yarnpkg/yarn/blob/v1.0.2/src/cli/commands/global.js#L282
https://github.com/yarnpkg/yarn/blob/v1.0.2/src/cli/commands/upgrade-interactive.js#L15
https://github.com/yarnpkg/yarn/blob/v1.0.2/src/cli/commands/_build-sub-commands.js#L26

**Comment by jmsmrgn** [comment]
@dhcmrlchtdj having same issue, flag not working with global

**Comment by dwiyatci** [comment]
I too can confirm this bug on yarn v1.2.1.

`yarn global upgrade-interactive --latest` doesn't work,
`yarn upgrade-interactive --latest` does.

🤷‍♂️

**Comment by ringrid** [comment]
I use yarn v1.3.2, same to me.

**Comment by dertuerke** [comment]
same here
`yarn global upgrade-interactive` not working 

```
yarn global v1.3.2
error Outdated lockfile. Please run `yarn install` and try again.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
