### ISSUE TITLE
APT repository is failing

### ISSUE THREAD

**Issue by stof** [yarnpkg/yarn#4508]
Yarn just warned me that 1.0.2 is out and I should run `sudo apt-get update && sudo apt-get install yarn` to get it.

But `sudo apt-get update` fails saying there is a GPG error

```
Impossible de récupérer https://dl.yarnpkg.com/debian/dists/stable/InRelease  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY E074D16EB6FF4DE3
```

**Comment by BYK** [comment]
The key has changed: #4253

**Comment by stof** [comment]
would be great to make an announcement for this rather than relying on people finding a closed issue

**Comment by BYK** [comment]
@stof Twitter may be? What do you think a good medium for the announcement would be?

**Comment by Daniel15** [comment]
Sorry about this! I'm not sure how to improve the process at the moment. The best practice is to rotate your signing keys periodically (eg. every year, or every two years), but I might need to get advice from other people that maintain package repositories to see how they handle it. Debian and Ubuntu both rotate their keys on each release, but that works well for those projects as they have a separate repo per release.
