### ISSUE TITLE
Install deps from `yarn.lock` rather than `package.json`?

### ISSUE THREAD

**Issue by pcj** [yarnpkg/yarn#4509]
I'm writing a tool that sits on top of yarn for the bazel build tool.  In this scenario, I'm interested in invoking `yarn install yarn.lock` rather than `yarn install package.json`.  Is this possible?

Why?  Assume I only had access to one file: either the package.json file, or the yarn.lock, but not both.  As the yarn.lock is the better source of truth, I want to mirror the content from it, and not the package.json.

**Comment by BYK** [comment]
Unfortunately `yarn.lock` is not the better source of the truth. Both files are needed for a deterministic tree:

https://yarnpkg.com/blog/2017/05/31/determinism/
>But there’s one key piece of information that the yarn lockfile doesn’t contain and that’s the hoisting and location of each dependency in the tree. For example, given a yarn.lock it’s impossible to determine what are the top level dependencies unless you have it’s accompanying package.json. Even knowing the top level packages, we still cannot infer what hoisting position packages should be in.

**Comment by pcj** [comment]
Thanks @BYK for highlighting the passage in the referenced blog post.  I'm still not clear on hoisting and/or the rules surrounding that, but I'll try to look around a bit and study up.
