### ISSUE TITLE
using an incorrect package name with yarn add installs everything

### ISSUE THREAD

**Issue by SingingBush** [yarnpkg/yarn#4512]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
using an incorrect package name with yarn add installs everything

**If the current behavior is a bug, please provide the steps to reproduce.**
run `yarn add popper` (instead of popper.js) results in 418 dependencies being installed:

```
$ yarn add popper
yarn add v1.0.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 418 new dependencies.
```

**What is the expected behavior?**
just tell me that no popper module found

**Please mention your node.js, yarn and operating system version.**
node 6.11.2
Fedora 26 
yarn 1.0.2

**Comment by BYK** [comment]
There is a package called `popper`: https://yarnpkg.com/en/package/popper

That's why it installed it happily.
