### ISSUE TITLE
Using yarn as a library

### ISSUE THREAD

**Issue by hmarr** [yarnpkg/yarn#4514]
**Background**
Prior to yarn 1.0, the packaged version of yarn made it possible to access yarn's internals programmatically. This is useful for projects like [Dependabot](https://dependabot.com/), which effectively [use yarn as a library](https://github.com/dependabot/dependabot-core/tree/343088c0c068e1c84a564da575f9be843ed5abe4/helpers/javascript/lib).

Specifically,
- We use yarn for [loading the manifest and lockfile](https://github.com/dependabot/dependabot-core/blob/343088c0c068e1c84a564da575f9be843ed5abe4/helpers/javascript/lib/parser.js). This could mostly be reimplemented by manually loading the manifest, and using the new @yarnpkg/lockfile package, but we also use a few other bits of yarn's internals (e.g. filtering out packages that use exotic resolvers).
- We [inherit from the Add command](https://github.com/dependabot/dependabot-core/blob/343088c0c068e1c84a564da575f9be843ed5abe4/helpers/javascript/lib/updater.js) to perform a "lightweight" update - that is, an update that generates a new lockfile without actually downloading the packages.

Since yarn is now distributed as a single file (`cli.js`), accessing internals is no longer possible.

Shelling out to yarn's CLI would get us some of the way there. But for tools that integrate deeply with yarn (such as Dependabot), having access to the internals means we can build a far more robust integration.

There are a couple of options that could enable this:

1. Moving back to distributing multiple sources files in the main package
2. Splitting out the bulk of yarn into a "yarn-core" package, which is designed to be used as a library, and keeping "yarn" purely as a thin CLI wrapper around "yarn-core".

I'm also aware of #3397, which seems to be what triggered the creation of @yarnpkg/lockfile.

I'd love to hear your thoughts!

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
You can no longer `require` yarn internals (e.g. `const { Install } = require("yarn/lib/cli/commands/install");`), so yarn can't be used as a library.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`const { Install } = require("yarn/lib/cli/commands/install");` works.

**Please mention your node.js, yarn and operating system version.**
Node 8.2, macOS Sierra.

**Comment by nodesocket** [comment]
I'm also wondering if I can access `yarn` programmatically. For example:

```javascript
const fs = require('fs');
const yarn = require('yarn');
yarn.install(sh.pwd());
```

**Comment by CanRau** [comment]
would love to use it programmatically from within electron 👍 😁

**Comment by imolorhe** [comment]
Any progress on this?

**Comment by sarpik** [comment]
bump. see also https://github.com/yarnpkg/yarn/issues/906

**Comment by CanRau** [comment]
Yarn 2 core will be usable as API
https://github.com/yarnpkg/berry/blob/master/README.md#generic-packages

**Comment by paul-soporan** [comment]
Closing as v2 exposes [an API](https://yarnpkg.com/api/) via multiple packages that can be used programatically.

https://yarnpkg.com/getting-started/migration

**Comment by xinkule** [comment]
> Closing as v2 exposes [an API](https://yarnpkg.com/api/) via multiple packages that can be used programatically.
> 
> https://yarnpkg.com/getting-started/migration

Thanks for your work.

Is there any chance you could write some comprehensible docs to explain how to use these apis ? For most developers, these exposed apis are too low-level to manipulate. For example, if I want to implement "yarn add xxx" or "yarn remove xxx", I have no idea how to do based on these apis.

**Comment by tinkerborg** [comment]
> Is there any chance you could write some comprehensible docs to explain how to use these apis ? For most developers, these exposed apis are too low-level to manipulate. For example, if I want to implement "yarn add xxx" or "yarn remove xxx", I have no idea how to do based on these apis.

I was trying to work this out as well and didn't find any such docs but managed to work it out. For anyone still struggling with this, here's an example: https://gist.github.com/tinkerborg/e6acb6f7d09d724ab9328781d3e3e52f
