### ISSUE TITLE
--production flag installs devDependencies into node_modules/

### ISSUE THREAD

**Issue by btilford** [yarnpkg/yarn#4517]
Using v 1.0.1 and any previous version dev dependencies are installed into node_modules.

**Comment by olingern** [comment]
Most likely a duplicate of #3630

**Comment by btilford** [comment]
It sort of makes sense to resolve the dev dependencies so that Dev and prod have the same versions etc. Just add long as dev doesn't end up in node_modules.

**Comment by BYK** [comment]
@btilford please provide reproduction steps.

**Comment by btilford** [comment]
Ended up tracking down a transitive dependency that didn't have dev dependencies in the write slot. Everything works like I'd expect.
