### ISSUE TITLE
Console font color is changed and not reset on Windows PowerShell

### ISSUE THREAD

**Issue by ryo-a** [yarnpkg/yarn#4529]
When I run `yarn init`, font color on PowerShell is changed to yellow.
Even after completion of yarn process, font color isn't reset. 
![image](https://user-images.githubusercontent.com/26864545/30775823-7b0a2be4-a0d6-11e7-9fa8-1ddbd4b83c3f.png)

`console.log('\u001b[0m');` can reset the color.
![image](https://user-images.githubusercontent.com/26864545/30776062-87ab226e-a0da-11e7-9dac-c93dcec53596.png)

Same problem is occured on any other yarn commands (e.g. `yarn add`, `yarn run` and so on)

cmd.exe doesn't have problem
![image](https://user-images.githubusercontent.com/26864545/30775906-cb1b8a46-a0d7-11e7-9269-3ff2e52f8d13.png)

**version**
Node.js: v8.1.4
yarn:1.0.2
Windows: 10.0.15063
(PowerShell: 5.1.15063.608)

**Comment by BYK** [comment]
Should be fixed on master. Can you try the latest nightly? Also, this will be fixed with 1.1.0.

**Comment by kumarharsh** [comment]
Already tracked in https://github.com/yarnpkg/yarn/issues/2724

**Comment by BYK** [comment]
Closing in favor of #2724.
