### ISSUE TITLE
One sub-dependency is not installed in combination with another dependecy (eslint-plugin-flowtype-errors)

### ISSUE THREAD

**Issue by lydell** [yarnpkg/yarn#4535]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
One sub-dependency is not installed.

**If the current behavior is a bug, please provide the steps to reproduce.**
See below

**What is the expected behavior?**
All sub-dependencies are installed.

**Please mention your node.js, yarn and operating system version.**
Node.js: 8.3.0
yarn: 1.0.1 as well as latest master as of 2017-09-24: commit 332b0dd7f6fe5c862074922897880cca8a7572ed
OS: Ubuntu 16.04

## Steps to reproduce

[eslint-config-bliss](https://github.com/amilajack/eslint-config-bliss/) depends on [eslint-plugin-flowtype-errors](https://github.com/amilajack/eslint-plugin-flowtype-errors): https://github.com/amilajack/eslint-config-bliss/blob/8562b76f40b132eae50e51453a75e22aa75dc725/package.json#L32

So if I install eslint-config-bliss, eslint-plugin-flowtype-errors should also be installed. So far so good.

The problem arises when depending on [flow-bin](https://www.npmjs.com/package/flow-bin) at the same time.

Then, suddenly eslint-plugin-flowtype-errors isn't installed anymore.

### Real-world

1. Clone this repo: https://github.com/amilajack/eslint-plugin-flowtype-errors
   I've tested with latest master as of 2017-09-24: https://github.com/amilajack/eslint-plugin-flowtype-errors/commit/90a594c4de534e38b608586afa70d1256b6f9f67

2. Run `yarn`.

3. Run `yarn lint`.

Expected: ESLint runs without problems.

Actual:
```
yarn lint v1.0.1
$ eslint --cache --format=node_modules/eslint-formatter-pretty .

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-flowtype-errors". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-flowtype-errors is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-flowtype-errors@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

error Command failed with exit code 1.
```

### Reduced case 1

1. Create a new directory and add this package.json:

   ```json
   {
     "devDependencies": {
       "eslint-config-bliss": "^1.0.13",
       "flow-bin": "^0.50.0"
     }
   }
   ```

2. Run `yarn`.

3. Run `ls node_modules/eslint-plugin-flowtype-errors`.

Expected: The directory exists.

Actual: `ls: cannot access 'node_modules/eslint-plugin-flowtype-errors': No such file or directory`

### Reduced case 2

1. Run `yarn add -D eslint-config-bliss`. Note how eslint-plugin-flowtype-errors is installed as expected.
1. Run `yarn add -D flow-bin`. Note how eslint-plugin-flowtype-errors is suddenly gone.

<details>
<summary>Console session</summary>
<pre>
~/bugs/yarn  
❯ echo '{"private": true}' > package.json

~/bugs/yarn  
❯ ~/forks/yarn/bin/yarn add -D eslint-config-bliss
yarn add v1.1.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "eslint-plugin-flowtype@2.35.1" has unmet peer dependency "eslint@>=2.0.0".
warning "eslint-plugin-jest@20.0.3" has unmet peer dependency "eslint@>=3.6".
warning "eslint-config-airbnb-base@11.3.2" has unmet peer dependency "eslint@^3.19.0 || ^4.5.0".
warning "eslint-plugin-flowtype-errors@3.3.1" has unmet peer dependency "eslint@>=3.0.0".
warning "eslint-plugin-compat@1.0.4" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0".
warning "eslint-plugin-fp@2.3.0" has unmet peer dependency "eslint@>=3".
warning "eslint-plugin-import@2.7.0" has unmet peer dependency "eslint@2.x - 4.x".
warning "eslint-config-bliss@1.0.13" has unmet peer dependency "eslint@^3.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 91 new dependencies.
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ babel-code-frame@6.26.0
├─ babel-eslint@7.2.3
├─ babel-messages@6.23.0
├─ babel-runtime@6.26.0
├─ babel-traverse@6.26.0
├─ babel-types@6.26.0
├─ babylon@6.18.0
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.8
├─ browserslist@2.1.4
├─ builtin-modules@1.1.1
├─ caniuse-db@1.0.30000671
├─ caniuse-lite@1.0.30000737
├─ chalk@1.1.3
├─ concat-map@0.0.1
├─ contains-path@0.1.0
├─ core-js@2.5.1
├─ create-eslint-index@1.0.0
├─ debug@2.6.9
├─ doctrine@1.5.0
├─ electron-to-chromium@1.3.22
├─ error-ex@1.3.1
├─ escape-string-regexp@1.0.5
├─ eslint-ast-utils@1.0.0
├─ eslint-config-airbnb-base@11.3.2
├─ eslint-config-bliss@1.0.13
├─ eslint-import-resolver-node@0.3.1
├─ eslint-module-utils@2.1.1
├─ eslint-plugin-compat@1.0.4
├─ eslint-plugin-flowtype-errors@3.3.1
├─ eslint-plugin-flowtype@2.35.1
├─ eslint-plugin-fp@2.3.0
├─ eslint-plugin-import@2.7.0
├─ eslint-plugin-jest@20.0.3
├─ eslint-plugin-prettier@2.3.1
├─ eslint-plugin-promise@3.5.0
├─ eslint-restricted-globals@0.1.1
├─ esutils@2.0.2
├─ fast-diff@1.1.2
├─ find-up@2.1.0
├─ flow-bin@0.53.1
├─ function-bind@1.1.1
├─ globals@9.18.0
├─ graceful-fs@4.1.11
├─ has-ansi@2.0.0
├─ has@1.0.1
├─ hosted-git-info@2.5.0
├─ invariant@2.2.2
├─ is-arrayish@0.2.1
├─ is-builtin-module@1.0.0
├─ isarray@1.0.0
├─ jest-docblock@21.1.0
├─ js-tokens@3.0.2
├─ load-json-file@2.0.0
├─ locate-path@2.0.0
├─ lodash.cond@4.5.2
├─ lodash.get@4.4.2
├─ lodash@4.17.4
├─ loose-envify@1.3.1
├─ minimatch@3.0.4
├─ ms@2.0.0
├─ normalize-package-data@2.4.0
├─ p-limit@1.1.0
├─ p-locate@2.0.0
├─ parse-json@2.2.0
├─ path-exists@2.1.0
├─ path-parse@1.0.5
├─ path-type@2.0.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ pkg-dir@1.0.0
├─ prettier@1.7.0
├─ read-pkg-up@2.0.0
├─ read-pkg@2.0.0
├─ regenerator-runtime@0.11.0
├─ req-all@0.1.0
├─ requireindex@1.1.0
├─ resolve@1.4.0
├─ semver@5.4.1
├─ slash@1.0.0
├─ spdx-correct@1.0.2
├─ spdx-expression-parse@1.0.4
├─ spdx-license-ids@1.2.2
├─ strip-ansi@3.0.1
├─ strip-bom@3.0.0
├─ supports-color@2.0.0
├─ to-fast-properties@1.0.3
└─ validate-npm-package-license@3.0.1
Done in 1.95s.

~/bugs/yarn  
❯ ls node_modules/eslint-plugin-flowtype-errors
CHANGELOG.md  dist/  index.js  LICENSE  node_modules/  package.json  readme.md

~/bugs/yarn  
❯ ~/forks/yarn/bin/yarn add -D flow-bin
yarn add v1.1.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "eslint-config-bliss@1.0.13" has unmet peer dependency "eslint@^3.0.0".
warning "eslint-config-airbnb-base@11.3.2" has unmet peer dependency "eslint@^3.19.0 || ^4.5.0".
warning "eslint-plugin-compat@1.0.4" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0".
warning "eslint-plugin-flowtype@2.35.1" has unmet peer dependency "eslint@>=2.0.0".
warning "eslint-plugin-flowtype-errors@3.3.1" has unmet peer dependency "eslint@>=3.0.0".
warning "eslint-plugin-fp@2.3.0" has unmet peer dependency "eslint@>=3".
warning "eslint-plugin-import@2.7.0" has unmet peer dependency "eslint@2.x - 4.x".
warning "eslint-plugin-jest@20.0.3" has unmet peer dependency "eslint@>=3.6".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ flow-bin@0.55.0
Done in 1.05s.

~/bugs/yarn  
❯ ls node_modules/eslint-plugin-flowtype-errors
ls: cannot access 'node_modules/eslint-plugin-flowtype-errors': No such file or directory
</pre>
</details>

**Comment by BYK** [comment]
This package is listed as a dependency of `eslint-config-bliss` and is correctly placed under it. Why do you expect it to be hoisted at all times when it is not listed as a peer dependency?

**Comment by lydell** [comment]
> Why do you expect it to be hoisted at all times when it is not listed as a peer dependency?

I don’t, that was just my attempt to reduce the problem :) As long as the “Real-world“ example above (with ESLint) works I’m happy.

**Comment by lydell** [comment]
Ok, I found the problem. Seems not to be an issue with yarn at all. Sorry for wasting your time!

What happens is this:

- eslint-config-bliss depends on several eslint plugins.
- yarn hoists all those eslint plugins
- until you install flow-bin: Then yarn has to move eslint-plugin-flowtype-errors into eslint-config-bliss/node_modules/ because of conflicting flow-bin versions.
- then ESLint can’t find eslint-plugin-flowtype-errors anymore.

When thinking about it, don’t ESLint configs usually tell people to install all the needed eslint plugins manually, and only list them as peer dependencies? I guess a reason for that is to make sure that eslint can always `require` all plugins from the top level. There’s probably a closed issue about this in the eslint issue tracker.

So yarn seems to be doing everything correctly.

**Comment by mzalazar** [comment]
Please check my answer in stackoverflow:
https://stackoverflow.com/questions/44824216/eslint-with-prettier-issues-on-yarn-global-install/49427117#49427117
It could be helpful to solve this kind of problems.
