### ISSUE TITLE
why yarn is called yarn?

### ISSUE THREAD

**Issue by zzzgit** [yarnpkg/yarn#4536]
why yarn is called yarn?

**Comment by zjh65204** [comment]
Your avatar is fucking funny, I love U, man!

**Comment by zzzgit** [comment]
i have a gf to fuck already man,don't love me

**Comment by kmoe** [comment]
https://twitter.com/sebmck/status/902899559705272320?lang=en

This doesn't really belong on the GitHub issue tracker though...

**Comment by bestander** [comment]
The answer is correct, thanks for asking
