### ISSUE TITLE
Bug or expected behavior with the transitive dependency "reusing"?

### ISSUE THREAD

**Issue by vkrol** [yarnpkg/yarn#4537]
Hello. I found some strange behavior. Is this a bug or is it an expected behavior?

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Please see below.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have the following package.json:
```
{
  "name": "pm-playground",
  "private": true,
  "dependencies": {
    "babel-cli": "6.26.0",
    "core-js": "2.4.1"
  }
}
```
I run yarn install and now I have the following directories hierarchy in node_modules:
```
node_modules
    …
    babel-runtime@6.26.0
        node_modules
            core-js@2.5.1
    core-js@2.4.1
    …
```
babel-cli has babel-runtime^6.26.0 in the dependencies. babel-runtime has core-js@^2.4.0 in the dependencies, so top-level core-js@2.4.1 should satisfy babel-runtime requirement, but Yarn installed core-js@2.5.1 instead of "reusing" the top-level core-js@2.4.1.

**What is the expected behavior?**
I expect the following node_modules directory structure:
```
node_modules
    …
    babel-runtime@6.26.0
    core-js@2.4.1
    …
```
npm@5.3.0 is "reusing" the top-level core-js@2.4.1 and does not install core-js@2.5.1.

**Please mention your node.js, yarn and operating system version.**
Node.js - 8.5.0
Yarn - 1.1.0
OS - Win 10

**Comment by simonkberg** [comment]
Seeing the same issue for multiple packages across different repos after updating to v1.1.0. Removing the lock-file and re-creating it seems to resolve it.

**Comment by vkrol** [comment]
@simonkberg in my case this issue is not resolved after re-creating yarn.lock.

**Comment by BYK** [comment]
Unless they are listed as peerDependencies there is no expectation that they would be resolved to the same dependency. That's the "ideal" case but not a given, so this behavior is not a bug.

**Comment by vkrol** [comment]
@BYK thank you for the information! I think that I can close this issue now. But maybe we need to document this somewhere? What do you think about it? I am not sure, but it can confuse someone else.

**Comment by BYK** [comment]
@vkrol maybe we can create an FAQ page for this since it has been brought up so many times recently.

**Comment by BYK** [comment]
@vkrol yup. I'd create an issue in the website repo and ping @arcanis about it. We may also try adding a check about possible duplicates in the tree and show people an `info` message about this.
