### ISSUE TITLE
[Release Note] Remove code block from v1.1.0

### ISSUE THREAD

**Issue by gluons** [yarnpkg/yarn#4541]
Please remove code block from [v1.1.0 release note](https://github.com/yarnpkg/yarn/releases/tag/v1.1.0).

![screenshot-2017-9-25 yarnpkg yarn](https://user-images.githubusercontent.com/4688092/30812138-307c733e-a234-11e7-99e2-fd885d3321b9.png)

**Comment by greggb** [comment]
Anywhere else we can see the changelog?

**Comment by gluons** [comment]
@greggb So, it can be ignored?

I think it doesn't seem right anyway. 😕

**Comment by greggb** [comment]
No, I just want to read it

**Comment by gluons** [comment]
Yeah. It can be read. But it's still weird. 😅

**Comment by gluons** [comment]
Just want more friendly note for everyone.

> Changelogs are for humans, not machines.
   http://keepachangelog.com/en/1.0.0/

**Comment by devoto13** [comment]
See https://github.com/yarnpkg/yarn/issues/4528#issuecomment-331834186 regarding changelogs.

**Comment by gluons** [comment]
Thank you. 👍

**Comment by BYK** [comment]
Done.
