### ISSUE TITLE
feature: Ability for `yarn list` to display only dependencies or devDependencies

### ISSUE THREAD

**Issue by genu** [yarnpkg/yarn#4542]
**Do you want to request a *feature* or report a *bug*?**

**Feature Request**

**What is the current behavior?**
All the dependencies are listed 

**Please mention your node.js, yarn and operating system version.**
yarn 1.0.2
node 6.11.0
Windows 7

**Comment by benma** [comment]
👍 

I thought the `--prod` flag would do that, but it doesn't seem to have any impact.

**Comment by guillaume-d** [comment]
Listing only dependencies is possible with ENV NODE_ENV=production (since #3788 got fixed).

**Comment by otroboe** [comment]
Maybe close the issue ? It's working with `NODE_ENV=production`

Example:
```bash
yarn list | wc -l
#3647

NODE_ENV=production yarn list | wc -l
#108
```

**Comment by kaylieEB** [comment]
Thanks @otroboe ! --prod flag also seems to work now, so closing
```
➜  test git:(master) ✗ yarn list | wc -l
     502
➜  test git:(master) ✗ NODE_ENV=production yarn list | wc -l
       2
➜  test git:(master) ✗ yarn list --prod | wc -l
       2
