### ISSUE TITLE
PeerDependency not satisfied with workspaces.

### ISSUE THREAD

**Issue by bryzaguy** [yarnpkg/yarn#4544]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
When I run yarn using workspaces I get warnings that I'm missing peer dependencies for packages managed by the repository (which are symlinked) are not satisfied (even though they there).

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a workspace with two packages (package1 and package2).
2. Add the first package1 as a devDependency of the package2.
3. Add the first package1 as a peerDependency of the package2.
4. Run `yarn` and notice the warning `warning "package2@0.0.1" has incorrect peer dependency "package1@^0.0.1"`

**What is the expected behavior?**
No warning occurs because peer dependencies are satisfied.

**Please mention your node.js, yarn and operating system version.**
node.js v8.1.4, yarn 1.0.2, MacOS Sierra 10.12.6

**Comment by BYK** [comment]
Does this happen with Yarn 1.1.0 too?

**Comment by bryzaguy** [comment]
Appears to be fixed with 1.1.0!
