### ISSUE TITLE
yarn tries to access https over http-proxy which doesn't support https

### ISSUE THREAD

**Issue by TauPan** [yarnpkg/yarn#4546]
This is a feature request. I've tested this with current yarn (1.1 and master).

I'm behind a corporate http proxy which won't allow https connections for security reasons (https directly must be allowed). (Security reasons involve tunneling arbitrary connections via https, see e.g. https://github.com/proxytunnel/proxytunnel.)

I'd like to be able to set https-proxy to null explicitly to prevent this (this is supported in current npm).

I've tried to create a pull request for this, https://github.com/yarnpkg/yarn/compare/master...TauPan:patch-1 but apparently I don't understand how options work. If I test this with my branch, yarn apparently still tries to access the http-proxy even if I set https-proxy to null.

**Comment by rally25rs** [comment]
You should be able to just set your `https-proxy` to an http URL.

```
proxy=http://fwdproxy:8080/
https-proxy=http://fwdproxy:8080
```

Then all HTTPS-intended requests will use that http:// URL as the prefix, so won't actually use HTTPS.

**Comment by TauPan** [comment]
You misunderstood. The proxy url is always http, it's never https. The problem is that the proxy does not allow accessing https urls, so all requests fail. Direct connections to https urls (i.e. not over the proxy) are allowed.

To clarify: Requests to https urls over a proxy (e.g. squid) always use plain http for the connection to the proxy itself, but the outgoing connection from the proxy to the server will be https. (I understand that some corporate proxies will hijack/mitm the  https connection, but others simply disallow it.)

The solution is to not use the proxy for https-request, which is what setting https-proxy to null accomplishes in npm.

**Comment by rally25rs** [comment]
Ah I see, sorry for the misunderstanding. I was thinking you could just leave `https-proxy` unset and it would not use a proxy for the https requests, but it looks like it will just fall back to http-proxy if it is missing.

In `request-manager.js`:
```
    let proxy = this.httpProxy;
    if (params.url.startsWith('https:')) {
      proxy = this.httpsProxy || proxy;
    }
```

Yeah I agree with you that there should be a way to use a proxy for one kind of request and not the other. I'll play around with it and see if we can get the options to differentiate between an unset/unpassed option and one explicitly set to null. Your patch seems like a good start.

**Comment by rally25rs** [comment]
@TauPan I put together PR #4614 for this. Could you give it a try and see if it behaves how you expect?

**Comment by TauPan** [comment]
I'd like to reopen because it doesn't work  - See https://github.com/yarnpkg/yarn/pull/4614#issuecomment-336079861

**Comment by rally25rs** [comment]
On vacation and don't have computer. Trying to reply from phone email...

I think the env var set too empty string might override the yarnrc. If you remove the env var does it work?

**Comment by TauPan** [comment]
> On vacation and don't have computer. Trying to reply from phone email...

I appreciate this, but there's no urgency. I would just like to try out yarn. ;)

> I think the env var set too empty string might override the yarnrc. If you remove the env var does it work?

Nope.

`unset https_proxy; export https_proxy` has no effect.

`npm config set https_proxy false` also has no effect (so now both configs have https_proxy false instead of null.

`npm config delete https_proxy` also doesn't help.

All lead to `info There appears to be trouble with your network connection. Retrying...`

Sorry!
I just tried running yarn under node --inspect and I noticed that both http_proxy and https_proxy (also capitalized) are taken from process.env.

So I need to unset `http_proxy` as well, and then it works.

I think the following lines in cli.js (in the bundle) are the reason:
```
  if (uri.protocol === 'https:') {
    return process.env.HTTPS_PROXY ||
           process.env.https_proxy ||
           process.env.HTTP_PROXY  ||
           process.env.http_proxy  || null
  }

```

However they're not part of the yarn source code, apparently.

**Comment by rally25rs** [comment]
OK so Yarn is using this [request](https://github.com/request/request) package to perform its network calls.

It looks like that package itself falls back to `HTTP_PROXY` if it is set in the environment. https://github.com/request/request/blob/master/lib/getProxyFromURI.js#L66

Not sure what the best solution would be here... do you have the env vars defined for a reason? Can you just unset them? Or are they being set by some part of your Yarn process?

**Comment by rally25rs** [comment]
@TauPan could you give this PR ☝️  a try and see if it works for you?

**Comment by TauPan** [comment]
> OK so Yarn is using this request package to perform its network calls.

> It looks like that package itself falls back to HTTP_PROXY if it is set in the environment. https://github.com/request/request/blob/master/lib/getProxyFromURI.js#L66

That is clearly wrong behaviour in the request package. I feel that the appropriate course of action would be to file an issue against it.

There were similar bugs in npm, pip and I think ruby gems (and probably the python requests package as well).

I need the proxy settings in the environment so other tools, such as curl or wget, or even lynx/w3m/links work properly.

I can try the PR but last time I tried I had problems building yarn from source. Maybe it works this time if I use yarn itself to fetch the packages (by simply unsetting the proxy settings in the environment).

**Comment by TauPan** [comment]
Ok, I was able to build yarn with yarn (so the dependency on rx.lite which npm could not resolve was not a problem).

The resulting yarn works correctly over my proxy with `https_proxy: false` and *with* all my proxy settings in the environment.

Many thanks and best regards!
