### ISSUE TITLE
can't seem to install request@^2.82.0 and request-promise-native@^1.0.5 together

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#4550]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Having an issue installing request@^2.82.0 I suspect it's to do with webdriverio pinning request@~2.81.0

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/graingert/yarn-request-strange
(remove the yarn.lock file, and run yarn install)

 request is still outdated, and I get a peerdep warning on install.

**What is the expected behavior?**
 request is updated, and no peerdep warning, webdriverio gets a nested request@~2.81.0

**Please mention your node.js, yarn and operating system version.**
node: v8.5.0
uname -a: Linux fester 4.13.0-11-generic #12-Ubuntu SMP Tue Sep 12 16:03:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a: No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful
yarn: 1.1.0

**Comment by graingert** [comment]
I suspect this will go away when https://github.com/webdriverio/webdriverio/pull/2318 and https://github.com/Medium/phantomjs/pull/742 are merged. But I'd like to know what's up.

**Comment by BYK** [comment]
Which Yarn version are you using?

**Comment by graingert** [comment]
@BYK 1.1.0

**Comment by viatsko** [comment]
Looks like it caused by 4020ccd0a3304239877562b776f2aff27ebf2ede
