### ISSUE TITLE
Performance issue with preinstall and postinstall scripts

### ISSUE THREAD

**Issue by vkrol** [yarnpkg/yarn#4551]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
Create the following package.json:
```
{
  "name": "yarn-playground",
  "private": true,
  "scripts": {
    "preinstall": "echo 1",
    "postinstall": "echo 1"
  }
}
```
Run `Measure-Command { yarn }` in PowerShell:
```
TotalSeconds      : 5,4693932
```
If the package.json does not contain preinstall OR postinstall script then the duration will be:
```
TotalSeconds      : 0,471668
```

**What is the expected behavior?**
I do not understand why the ```yarn``` takes so much time if both scripts are present.

**Please mention your node.js, yarn and operating system version.**
Node.js 8.5.0
Yarn 1.1.0
OS Windows 10

**Comment by vkrol** [comment]
I think that there is the problem with this timeout https://github.com/yarnpkg/yarn/blob/25890c8cf90ff23c3230ab7b8debe73ef9a80b34/src/util/blocking-queue.js#L47

**Comment by BYK** [comment]
@vkrol great find! Would you like to submit a fix? I'd do the following two:

1. Add `this.stucktimer.unref()` right after that line so it wouldn't block exiting.
2. Add `clearTimeout(this.stuckTimer)` right after https://github.com/yarnpkg/yarn/blob/25890c8cf90ff23c3230ab7b8debe73ef9a80b34/src/util/blocking-queue.js#L81

What do you think? Also /cc @arcanis

**Comment by vkrol** [comment]
@BYK thanks! I will create the fix. Do I need to create some test for it?

**Comment by vkrol** [comment]
@BYK I found some confusing behavior in Jest. The fake Timer implementation does not have unref method in Node environment so blocking-queue.js test will fail with an error:
```
this.stuckTimer.unref is not a function
```
I asked a question about this in Discord chate.

**Comment by BYK** [comment]
@vkrol sorry, I couldn't find your message on Discord :( Ping me directly there?

I think instead of using fake timers you can make sure the timer gets released in tests then? `unref` is node-specific and not really documented anywhere I guess so no surprise Jest doesn't support it. We can summon @cpojer to see if he has any idea tho?

**Comment by cpojer** [comment]
Yeah, Jest doesn't support it at this time. You'll need to guard it for Jest, like `fakeTimer.unref && fakeTimer.unref()` to make it work in the test for now.

**Comment by vkrol** [comment]
@BYK 
> sorry, I couldn't find your message on Discord :(
Sorry for the confusion: I am asked in Jest Discord chat.

> unref is node-specific and not really documented anywhere I guess so no surprise Jest doesn't support it.
Unref is documented in Node.js documentation https://nodejs.org/api/timers.html#timers_timeout_unref

> We can summon @cpojer to see if he has any idea tho?
I created the issue in Jest repository https://github.com/facebook/jest/issues/4559

**Comment by vkrol** [comment]
@BYK 
> I think instead of using fake timers you can make sure the timer gets released in tests then?
Fake timers already used there https://github.com/yarnpkg/yarn/blob/08411a05a4f2a722d51c7fc0bb69d51702781b91/__tests__/util/blocking-queue.js#L6

**Comment by BYK** [comment]
>Unref is documented in Node.js documentation https://nodejs.org/api/timers.html#timers_timeout_unref

TIL. Sorry :)

>Fake timers already used there

Then how about we go with @cpojer's suggestion and checking for it?

**Comment by vkrol** [comment]
@BYK do you think that we need to add the following line of code to the BlockingQueue implementation?
```
this.stuckTimer && this.stuckTimer.unref()
```
I think that it is somewhat hacky, but if you approve this, then ok :)

**Comment by BYK** [comment]
It should be `this.stuckTimer.unref && this.stuckTimer.unref()`. With a comment that points to the Jest issue, I think it's fine.

**Comment by vkrol** [comment]
> It should be this.stuckTimer.unref && this.stuckTimer.unref()

Yes, sure. Sorry.

> With a comment that points to the Jest issue, I think it's fine.

Thanks. I will do it.
