### ISSUE TITLE
BUG? package does not exist yet....

### ISSUE THREAD

**Issue by achun** [yarnpkg/yarn#4554]
see this

https://yarnpkg.com/en/package/powjs

Whoa, powjs does not exist yet

but, the content exists on

https://registry.yarnpkg.com/powjs and https://www.npmjs.com/package/powjs

**Comment by arcanis** [comment]
The website uses Algolia to power its search. It's likely the index hasn't been updated yet if you've just pushed your package.

**Comment by BYK** [comment]
Please reopen this in https://github.com/yarnpkg/website/issues/ if it is not resolved by tomorrow.
