### ISSUE TITLE
--production=false flag not being honored on install

### ISSUE THREAD

**Issue by mliszewski** [yarnpkg/yarn#4557]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When passing `--production=false` with `NODE_ENV=production` devDependencies are not installed. Prior to v1.1.0 this worked correctly. 

**If the current behavior is a bug, please provide the steps to reproduce.**
`NODE_ENV=production yarn install --production=false`

**What is the expected behavior?**
devDependencies are installed despite `NODE_ENV` being set to `production`

**Please mention your node.js, yarn and operating system version.**
Node: 6.10.3
Yarn: 1.1.0
OS: MacOS 10.12.6

**Comment by viossat** [comment]
Related to #4498, `--no-prod[uction]` has no effect.

**Comment by BYK** [comment]
Yup, sorry about this. There was additional logic in `config.js` assuming a string value for this flag.
