### ISSUE TITLE
Security issue? Ubuntu package untrusted

### ISSUE THREAD

**Issue by dandv** [yarnpkg/yarn#4560]
When attempting to upgrade from 1.0.2-1 to 1.1.0-1 in Ubuntu 16.04.1, I got a

```
WARNING: The following packages cannot be authenticated!
  yarn
Install these packages without verification?
``` 

`/etc/apt/sources.list.d/yarn.list` lists `deb https://dl.yarnpkg.com/debian/ stable main`

I had to add the public key again per https://yarnpkg.com/lang/en/docs/install/. Did this key change recently? I have seen this error once, when upgrading to 1.0.2-1, but not before.

**Comment by BYK** [comment]
I don't think Debian key was changed again after 1.0.2 @Daniel15?

**Comment by Daniel15** [comment]
The key changed on 10th September as part of #4253, but it shouldn't have changed between 1.0.2 and 1.1.0. Hmm.

Does readding the key work?

**Comment by dandv** [comment]
> The key changed on 10th September as part of #4253, but it shouldn't have changed between 1.0.2 and 1.1.0. Hmm.

I saw this error when upgrading to 1.0.2-1, so that must've been due to the Sep 10 change. Glad to learn there's no security issue. Re-adding the key worked.
