### ISSUE TITLE
yarn bin yields warnings

### ISSUE THREAD

**Issue by kossnocorp** [yarnpkg/yarn#4567]
**Do you want to request a *feature* or report a *bug*?**

I believe that it's a bug.

**What is the current behavior?**

When a user runs `yarn bin` it yields warnings:

<img width="390" alt="screen shot 2017-09-28 at 17 28 36" src="https://user-images.githubusercontent.com/52201/30959390-8d23cbce-a472-11e7-98d8-28f7313cbeaf.png">

**What is the expected behavior?**

`yarn bin` outputs **only** the path, so commands that rely on this would not break, i.e.:

<img width="433" alt="screen shot 2017-09-28 at 17 28 56" src="https://user-images.githubusercontent.com/52201/30959398-94c977e8-a472-11e7-855a-cb34228ea824.png">

**Please mention your node.js, yarn and operating system version.**

- Node.js 8.6.0
- Yarn 1.1.0
- macOS Sierra 10.12.6

Thank you for the great project! ❤️

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
