### ISSUE TITLE
Better default value for $prefix

### ISSUE THREAD

**Issue by julien-f** [yarnpkg/yarn#4574]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It seems `$prefix` default to `/usr/local` (at least on Linux).

**If the current behavior is a bug, please provide the steps to reproduce.**

- Install Node with [`n-install`](https://github.com/mklement0/n-install/#n-install--introduction)
- DIsplay npm's prefix: `npm config get prefix`
- Install Yarn with npm: `npm i -g yarn`
- Install any global package and note that it's not correctly linked in `~/n/bin` (e.g. `yarn global add rimraf`)

**What is the expected behavior?**

As stated in [npm's documentation](https://docs.npmjs.com/files/folders#prefix-configuration), `prefix`'s default location is where Node is installed.

Therefore, Yarn should add link in `~/n/bin`.

**Please mention your node.js, yarn and operating system version.**

```
yarn versions v1.1.0
{ http_parser: '2.7.0',
  node: '8.4.0',
  v8: '6.0.286.52',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.22.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

On Fedora 26.

**Comment by BYK** [comment]
Please check out #3721 and referred PRs and issues. There were very long discussions around this and it was decided that what npm doing was not safe, thus the change.

I'll close the issue for now since this is intended but after reading those conversations, feel free to reopen if you disagree or see a way forward.

**Comment by julien-f** [comment]
As a workaround, explicitly setting the npm configuration works but it feels clumsy.

```
npm config set prefix '~/n'
```

**Comment by julien-f** [comment]
@BYK Thanks for your answer, I'll take a look.

**Comment by julien-f** [comment]
The problem is that a lot of tools (like nvm) relies on this behavior and the work around I gave is not always possible (for instance, in the case of nvm, the prefix should change each time a new Node version is selected).

Maybe there could be a config option to opt-in for this behavior?

@BYK FYI, because I'm not a maintainer of this repo, I can comment but not reopen issue.
