### ISSUE TITLE
yarn 1.1.0 "Cannot find module" with install --ignore-optional

### ISSUE THREAD

**Issue by cout** [yarnpkg/yarn#4576]
Using the following package.json:

    {
      "name": "test", "version": "0.0.1", "private": true,
      "dependencies": {
        "ldapjs": "^1.0.1",
        "sqlite3": "3.1.4"
      },
      "devDependencies": {
        "node-sass": "^4.5.0"
      }
    }

I run the following command:

    npm_config_build_from_source=true yarn install --ignore-optional

and get the following error when sqlite3 is built:

    gyp ERR! stack Error: Cannot find module 'brace-expansion'
    gyp ERR! stack     at Function.Module._resolveFilename (module.js:469:15)
    gyp ERR! stack     at Function.Module._load (module.js:417:25)
    gyp ERR! stack     at Module.require (module.js:497:17)
    gyp ERR! stack     at require (internal/module.js:20:19)
    gyp ERR! stack     at Object.<anonymous> (/home/pbrannan/tmp/test/node_modules/minimatch/minimatch.js:10:14)
    gyp ERR! stack     at Module._compile (module.js:570:32)
    gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
    gyp ERR! stack     at Module.load (module.js:487:32)
    gyp ERR! stack     at tryModuleLoad (module.js:446:12)
    gyp ERR! stack     at Function.Module._load (module.js:438:3)

It appears minimatch was hoisted, but brace-expansion (which minimatch depends on) was not:

     $ ls -ld node_modules/minimatch node_modules/brace-expansion
    ls: cannot access node_modules/brace-expansion: No such file or directory
    drwxr-xr-x 2 pbrannan shell-dev-servers 4096 Sep 28 13:53 node_modules/minimatch

"Yarn why" seems to believe that brace-expansion should be installed:

    yarn why v1.1.0
    [1/4] Why do we have the module "brace-expansion"...?
    [2/4] Initialising dependency graph...
    [3/4] Finding dependency...
    [4/4] Calculating file sizes...
    info This module exists because "ldapjs#bunyan#mv#rimraf#glob#minimatch" depends on it.
    Done in 0.41s.

This is similar to #4340, but with a different set of modules necessary to reproduce.  Yarn 1.1.0 still succeeds with the package.json from #4340.

**Comment by Grawl** [comment]
the same with `node-sass` but module not found is `are-we-there-yet`

**Comment by melfa** [comment]
Still can reproduce in 1.5.1.

**Comment by ratson** [comment]
I hit the same problem, upgrade to v1.6.0 fix the problem.

**Comment by BYK** [comment]
@melfa  - Yeah this is fixed in 1.6.0 which was released quite recently.

**Comment by Grawl** [comment]
yay!
