### ISSUE TITLE
Installing yarn 1.1.0 doesn't seem to work

### ISSUE THREAD

**Issue by Sean-Brown** [yarnpkg/yarn#4580]
- I did a complete uninstall of yarn
- I downloaded the 1.1.0 windows installer
- I ran the installer
- It claims to have run successfully and in add/remove programs it shows yarn 1.1.0 as being installed
- I run `yarn --version` and it returns `0.24.5`
- I open `C:\Program Files (x86)\Yarn\package.json` and it says it's version 1.1.0

Why is `yarn --version` reporting `0.24.5`?

**Comment by BYK** [comment]
Something in your path (possibly npm's bin folder?) is after Yarn's own path or you forgot to restart your terminal.

**Comment by Sean-Brown** [comment]
oh wow you're right, I must have done `npm install -g yarn` at some point because the 0.24.5 version is there in the global npm packages. thanks for the hint
