### ISSUE TITLE
Bug in selective resolution of nested packages?

### ISSUE THREAD

**Issue by TomiS** [yarnpkg/yarn#4585]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Resolutions defined in a direct dependency of the app are not respected even if they are not in any conflict with app dependencies.

**If the current behavior is a bug, please provide the steps to reproduce.**

See this example repository that represents accurately a real life problem:
https://github.com/TomiS/yarn-selective-resolution-bug
- Root package.json is an example of an "app" that utilizes so-called "platform" with multiple dependencies
- Platform has multiple dependencies exactly defined (in this example only react-virtualized-select and react-virtualized)
- App itself does not have other dependencies than the platform
- Clone repository and run yarn install in the root folder AND in the platform folder to get lock files for app and platform
- In real life, platform would be another repository, but that does not affect the behaviour.

**What is the expected behavior?**

- App gets near identical lock file with same deps as platform
- This is what I'd expect in the app lock file: [Platform yarn.lock](https://github.com/TomiS/yarn-selective-resolution-bug/blob/master/platform/yarn.lock#L132-L140)
- This is what I get: [App (root) yarn.lock](https://github.com/TomiS/yarn-selective-resolution-bug/blob/master/yarn.lock#L138-L156)
- This happens even if plaform contains this resolution: [Resolution line in platform](https://github.com/TomiS/yarn-selective-resolution-bug/blob/master/platform/package.json#L14)

- Current workaround is to define exact resolutions also in app package.json but this is very unsatisfying solution as there can be hundreds of apps using the same platform and duplication of those resolutions is not something what we want. I know this is not the most common way to manage deps with Yarn nor the simplest use case but I also wouldn't expect we are unique with this approach. So this report is mainly to raise discussion if this is intended behaviour.

**Please mention your node.js, yarn and operating system version.**

Node: 6.9.4
Yarn: 1.1.0
OSX

ps. Selective resolutions is an awesome feature and Yarn is great in general. Thanks for that.

**Comment by BYK** [comment]
Hey @kaylieEB can you look at this?

**Comment by kaylieEB** [comment]
@BYK yup, i'll work on this during the weekend.

**Comment by kaylieEB** [comment]
Well actually thinking about this, I think the intended use case wasn't for selective resolutions to be respected for nested dependencies and only used at the project level. We theoretically could do something like use the resolution of each dependency level then override them again at the project level, but this seems like adding a lot of complexity. Thoughts @cpojer @yarnpkg/core ?

**Comment by cpojer** [comment]
Yep, resolutions are only meant to work within a project, just like yarn.lock files. I think that's the right design decision and this feature is meant to give control to the user of a project rather than the library authors.

**Comment by kaylieEB** [comment]
thanks for clarifying @cpojer 

 @TomiS closing this for now as you mentioned 

> `Current workaround is to define exact resolutions also in app package.json` 

is the intended use of selective resolutions

**Comment by TomiS** [comment]
Fair enough. We'll just need to find another approach. Thanks for clarification. :)
