### ISSUE TITLE
Invalid dependencies inside nested node_modules

### ISSUE THREAD

**Issue by alansouzati** [yarnpkg/yarn#4590]
This is my package.json:

```json
{
  "dependencies": {
    "grommet-icons": "^0.9.0",
    "enzyme": "^3.0.0",
    "enzyme-adapter-react-16": "^1.0.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-test-renderer": "^16.0.0"
  }
}
```

`grommet-icons` library still uses React 15.X, while `enzyme` and `enzyme-adapter-react-16` uses React 16. `enzyme-adapter-react-16` has a dependency on `enzyme-adapter-utils` which has the following values for [peerDependencies](https://github.com/airbnb/enzyme/blob/718d160397f559ceae4843830ef898aa5f5eb198/packages/enzyme-adapter-utils/package.json#L38):

```json
  "peerDependencies": {
    "react": "0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0"
  },
```

When I run `npm install` I have the following structure inside my node_modules:

```
- node_modules
  - grommet-icons
    - node_modules
      - react (version 15)
      - react-dom (version 15)
  - enzyme-adapter-utils (**no node_modules folder**)
  - enzyme-adapter-react16
  - react
  - react-dom
```

This feels right to me and I can run my application tests without any problems.

On the other hand, when I run `yarn install` I get a different output:

```
- node_modules
  - grommet-icons
    - node_modules
      - react (version 15)
      - react-dom (version 15)
  - enzyme-adapter-utils
    - node_modules
      - react (version 15)
  - enzyme-adapter-react16
  - react
  - react-dom
```

This is breaking enzyme with the following output:

> this.updater.enqueueCallback is not a function

Manually removing the `enzyme-adapter-utils/node_modules/react` resolves the problem. 

I believe Yarn is resolving peerDependencies differently than NPM.  It seems to me that YARN finds the first match anywhere in the dependency tree (notice that React 15 is **NOT** a peerDependency of enzyme-adapter-utils).

**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Yarn uses React 15 as a peerDependency of `enzyme-adapter-utils`

**What is the expected behavior?**

Yarn should not use React 15 as a peerDependency of `enzyme-adapter-utils`

To reproduce this problem just run `npm install` and check the content of `node_modules/enzyme-adapter-utils`. You can see that there is no node_modules folder. When running `yarn install` this folder will be present with `react` 15 inside it.

**Please mention your node.js, yarn and operating system version.**

Node: 6.11.x
Yarn: 1.1.0
OSx 10

**Comment by IanVS** [comment]
I can confirm similar behavior beginning in yarn `1.10.0`.  

I am using:

- `react@15.4.2` in my own application
- `flow-coverage-report` which depends on `react@15.3.1`
- `react-router-dom` which has a peerDependency on `react@>=15`

I find that with yarn `1.0.2`, there is no `react` in the node_modules of `react-router-dom`, but when using yarn `1.1.0`, then `react@15.3.1` ends up in its node_modules, which causes my application to crash (only in dev, luckily) saying there are more than one react versions loaded.

**Comment by IanVS** [comment]
This seems to be related to (a duplicate of?) #4539

**Comment by karak** [comment]
I met similar problem using  \@types packages, type definition files of TypeScript.
Minimum set is [HERE](https://github.com/karak/yarn-upgrade-inconsistency).

This behavior is harmful and so confusing.

**Comment by IanVS** [comment]
I think this can be closed now that yarn 1.2.1 is released.  It has fixed the problem in my case at least.

**Comment by karak** [comment]
@IanVS Then, I simply need another issue. Yarn 1.2.1 don't resolve my issue.  You can reproduce that within a few minutes from my link.

**Comment by IanVS** [comment]
@karak, yeah, I'd recommend opening another issue, because I don't think it's related to this one.

**Comment by karak** [comment]
@IanVS I did it, thank you.

**Comment by alansouzati** [comment]
updating to 1.2.1 does fix the issue.
