### ISSUE TITLE
yarn upgrade-interactive doesn't show new versions for private npm packages

### ISSUE THREAD

**Issue by a-golovanov** [yarnpkg/yarn#4592]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn upgrade-interactive` doesn't show new versions for private npm packages

**If the current behavior is a bug, please provide the steps to reproduce.**
1. publish a private package to npm
2. `yarn add` the private package to any project
3. publish new version of the private package
4. run `yarn upgrade-interactive` in the project where the package was added -> new version is not shown (BUG)
5. run `yarn add` on the same private package -> a new version is installed, i.e. the new version is accessible

**What is the expected behavior?**
`yarn upgrade-interactive` should show new versions for private packages

**Please mention your node.js, yarn and operating system version.**
yarn: 1.1.0
node: 7.10.0
os: macOS 10.13

**Comment by Bnaya** [comment]
@a-golovanov try to run it with the --latest flag
Dose it make any difference?

**Comment by a-golovanov** [comment]
Yes, it does. Running `yarn upgrade-latest --latest` shows all packages, thanks!
