### ISSUE TITLE
Suggestion: command to check unmet peer dependencies

### ISSUE THREAD

**Issue by OliverJAsh** [yarnpkg/yarn#4594]
I get unmet peer dependency warnings when running `yarn`, but only sometimes.

I want a command to reliably check unmet peer dependencies. I had hoped `yarn check` would do this, but it seems not.

**Comment by Hoten** [comment]
How can this be done? I currently delete `node_modules/` and then do a `yarn install`. Better way?

**Comment by stefanKuijers** [comment]
I do the same :D

**Comment by SirUppyPancakes** [comment]
I currently run `yarn upgrade`, seems to be faster than `yarn install`. This works well in combination with `yarn outdated` to easily assert my packages are up to date and not missing any dependencies.

**Comment by galvarez421** [comment]
@Hoten I think one easier workaround is to change the version of a single package in `package.json`, e.g., change Bootstrap from 3.3.5 to 3.3.7 and then run `yarn`. This should cause Yarn to link dependencies and display incorrect and unmet peer dependencies. Then just revert the version and run `yarn` again.

**Comment by dimitarnestorov** [comment]
Here are my two workarounds:
1. `yarn install --check-files`
2. `rm node_modules/.yarn-integrity && yarn`

Both reinstall all packages and trigger postinstall

**Comment by Jelledb** [comment]
In the end, I only have to run `yarn install --check-files`. I can do this multiple times in sequence and it still works every time.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the peer dependency warnings are always printed on install

https://yarnpkg.com/getting-started/migration

**Comment by fzyzcjy** [comment]
> In the end, I only have to run yarn install --check-files. I can do this multiple times in sequence and it still works every time.

does not work for me :( the second time running it reports zero problems (though there are some)

**Comment by ColmBhandal** [comment]
> @hoten I think one easier workaround is to change the version of a single package in `package.json`

This is the only thing that works for me so far out of what I've tried. If you have any dependencies with versions starting with the hat "^" it suffices to remove the hat e.g. you could change this:

`"typescript": "^4.3.5"`

To this:

`"typescript": "4.3.5"`

And then revert. Or if you don't have a hat, you could add a hat. And then revert.

**Comment by mxdvl** [comment]
> > In the end, I only have to run yarn install --check-files. I can do this multiple times in sequence and it still works every time.
> 
> does not work for me :( the second time running it reports zero problems (though there are some)

I’ve had good success with [`yarn --force`](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-force)!
