### ISSUE TITLE
Feature: skip checking engine field

### ISSUE THREAD

**Issue by sheerun** [yarnpkg/yarn#4604]
I'm trying to create [bower2yarn](https://github.com/sheerun/bower2yarn) script that allows one to switch from bower to yarn, but there's one blocker: when installing legacy projects with Yarn, some bower modules list legacy node versions in their engine fields. Yarn has strict checking for these and fails installation, instead of just issuing a warning. Here's an example:

error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".

Is it possible to skip this check, or change error to warning, at least for dependencies?

**Comment by sheerun** [comment]
Never mind, `--ignore-engines` seems to help.

**Comment by publicocean0** [comment]
it is very stressing ... another package manager .... and either bower either yarm are bad designed. 
If i find time in future i will realize mime packager because it is impossible to work so.
