### ISSUE TITLE
[Question] Possible to always run yarn with --ignore-optional?

### ISSUE THREAD

**Issue by Nxt3** [yarnpkg/yarn#4616]
Currently, I'm using `npm` and having to run `npm install --no-optional`.

Is it possible to do away with the `--no-optional` with `npm` using `yarn`? I didn't know if it was possible to specify stuff like that in `yarn.lock` file or `.yarnrc`.

Ideally, I'd like to be able to run `yarn` or and it works as if I had run it with the `--ignore-optional` parameter.

**Comment by kaylieEB** [comment]
Yup, you can save it to your .yarnrc https://yarnpkg.com/en/docs/yarnrc#toc-cli-arguments.
