### ISSUE TITLE
yarn v1.1.0 upgrade does not respect caret version specifier

### ISSUE THREAD

**Issue by mwpastore** [yarnpkg/yarn#4620]
I have this in my package.json:

```json
"devDependencies": {
  "ember-chrome-devtools": "^0.1.1"
}
```

ember-chrome-devtools v0.1.3 is installed. ember-chrome-devtools v0.2.0 is available:

```console
$ yarn info ember-chrome-devtools
yarn info v1.1.0
{ name: 'ember-chrome-devtools',
  description: 'Chrome DevTools addon for Ember.js',
  'dist-tags': 
   { latest: '0.2.0' },
  versions: 
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.2.0' ],
```

The version specifier "^x.y.z" means "take the latest x with any y and z," correct? So I would expect `yarn upgrade` to install ember-chrome-devtools v0.2.0 in this case, since it is available. However, **it does not**. After a `yarn upgrade`, ember-chrome-devtools v0.1.3 is still installed:

```console
$ grep ember-chrome-devtools yarn.lock
ember-chrome-devtools@^0.1.1:
  resolved "https://registry.yarnpkg.com/ember-chrome-devtools/-/ember-chrome-devtools-0.1.3.tgz#ae9ce774860f0ff0d905c5897b21a80438ca5f89"
$ yarn outdated
yarn outdated v1.1.0
Package                            Current Wanted Latest Package Type    URL                                                          
ember-chrome-devtools              0.1.3   0.1.3  0.2.0  devDependencies https://github.com/dwickern/ember-chrome-devtools            
```

I've confirmed that there is no other dependency in my tree restricting yarn's ability to install v0.2.0 of this module:

```console
$ yarn list ember-chrome-devtools
yarn list v1.1.0
└─ ember-chrome-devtools@0.1.3
✨  Done in 1.00s.
```

Here is my system information:

```console
$ yarn --version
1.1.0
$ node --version
v8.6.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

**Comment by artursvonda** [comment]
Actually, it's correct behaviour. You can read the specifics here https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by Daniel15** [comment]
As @artursvonda mentioned, this is expected behaviour for prerelease versions. Please see the semver docs linked in his comment for more information.

**Comment by mwpastore** [comment]
I learn something new every day! Thank you both for explaining this little quirk, and my apologies for the noise.

**Comment by Daniel15** [comment]
>  my apologies for the noise.

No problem at all! 😄
