### ISSUE TITLE
Installing Yarn via npm does not set installationMethod in its package.json correctly

### ISSUE THREAD

**Issue by pungggi** [yarnpkg/yarn#4624]
I get a warning:
warning Your current version of Yarn is out of date. The latest version is "1.1.0" while you're on "1.0.2".
info To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash

For me as a windows user this doesnt really help ;)

**Comment by Daniel15** [comment]
lolwut.

How did you install Yarn? It should suggest downloading the installer (https://yarnpkg.com/latest.msi) or using Chocolatey (`choco install yarn`) depending on how you installed Yarn.

**Comment by pungggi** [comment]
Aaaah yes i used npm to install yarn

Am 04.10.2017 1:37 nachm. schrieb "Daniel Lo Nigro" <
notifications@github.com>:

**Comment by Daniel15** [comment]
Good catch, I think #3866 broke this. It should be suggesting to use `npm install --global yarn` if you installed Yarn via npm. I'll adjust the title of this issue to reflect the problem.

**Comment by pungggi** [comment]
closed as of lack of interest
