### ISSUE TITLE
Error when installing over curl (did not happen 24 hours ago)

### ISSUE THREAD

**Issue by BorntraegerMarc** [yarnpkg/yarn#4626]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
The following error get thrown when installing yarn on linux via curl:
```
Fetched 5,119 kB in 4s (1,073 kB/s)
W: GPG error: http://repo.mysql.com trusty InRelease: The following signatures were invalid: KEYEXPIRED 1487236823 KEYEXPIRED 1487236823 KEYEXPIRED 1487236823
W: Failed to fetch http://us-east1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://us-east1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Exited with code 100
```
**If the current behavior is a bug, please provide the steps to reproduce.**

Run:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn=1.1.0-1
```
**What is the expected behavior?**
The installation does not fail. This used to work 24 hours ago...

**Please mention your node.js, yarn and operating system version.**
yarn: 1.1.0
OS: Ubuntu 14

**Comment by Daniel15** [comment]
The errors in your output are for other repos (repo.mysql.com and us-east1.gce.archive.ubuntu.com), not for the Yarn repo.

**Comment by BorntraegerMarc** [comment]
and it's working again anyhow... thanks!
