### ISSUE TITLE
`yarn add` is losing workspace symlinks

### ISSUE THREAD

**Issue by zyklus** [yarnpkg/yarn#4635]
Using yarn 1.1.0, node 8.3.0:

```sh
ls node_modules # includes several symlinks from workspace modules
yarn add --dev jest
ls node_modules # symlinks are gone
```

There are no errors during the `yarn add`, it just seems to blow away workspace links.  Running `yarn` again restores them.

**Comment by TxHawks** [comment]
I can confirm being bitten by this as well
