### ISSUE TITLE
yarn add file.tar.gz does not work anymore since version 0.23

### ISSUE THREAD

**Issue by edi9999** [yarnpkg/yarn#4639]
**What is the current behavior?**

When I do `yarn add build/my-super-module.tar.gz`, I get : 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/build/my-super-module.tar.gz: Request failed \"404 Not Found\""."
```

**What is the expected behavior?**

It should install the module, it is working on yarn version 0.22.0

nodejs version : 8.6.0
yarn-version-with-bug : 0.23.0, 1.1.0, probably every version after 0.23
yarn-version-without-bug: 0.22.0

**Comment by edi9999** [comment]
I think I found that you have to use "file:my-super-module.tar.gz" (found in the docs), it seems to work.

**Comment by edi9999** [comment]
Could you put this kind of information in CHANGELOG.md ?

**Comment by kaylieEB** [comment]
Thanks for reporting. Will close this for now since this in the docs: https://yarnpkg.com/en/docs/cli/add
