### ISSUE TITLE
Yarn ignores scoped package registry

### ISSUE THREAD

**Issue by unRob** [yarnpkg/yarn#4645]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Given a .npmrc that specifies a registry for the organization scope, `yarn` tries to fetch the restricted org package from `https://registry.yarnpkg.org and fails with

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@example/package-a/-/package-a-0.0.1.tgz: Request failed \"404 Not Found\"".
``` 

**If the current behavior is a bug, please provide the steps to reproduce.**

Start with yarn v1.1.0 from `npm install --global yarn`

```js
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.1.0 npm/? node/v8.6.0 darwin x64',
  lastUpdateCheck: 1507229372825 }
info npm config
{ progress: true,
  'save-exact': true,
  'always-auth': true,
  '@example:registry': 'http://registry.npmjs.org/',
  '//registry.npmjs.org/:_authToken': 'sometoken' }
```

This `package.json`:

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "scripts": {},
  "devDependencies": {
    "@example/package-a": "0.0.1"
  },
  "author": "test",
  "license": "ISC"
}
```

and this `.npmrc`

```ini
progress=true
save-exact=true
always-auth=true
@example=http://registry.npmjs.org/
//registry.npmjs.org/:_authToken=sometoken
```

**What is the expected behavior?**

`yarn` fetches restricted org packages from npm and installs them.

**Please mention your node.js, yarn and operating system version.**

- node v8.6.0 through nvm
- yarn v1.1.0
- mac os 10.12.6 (16G29)

**Comment by derekwsgray** [comment]
Were you able to resolve? Someone in my office, on Mac having similar issue.

**Comment by ibratoev** [comment]
I have the same problem. FYI, the workaround i found is to use a separate .npmrc file for yarn, something like that:
```
@example:registry=http://registry.npmjs.org/
progress=true
save-exact=true
always-auth=true
_authToken=sometoken
```

**Comment by prabirshrestha** [comment]
We are also having the same issue. Our build machines blocks access to yarnpkg.com and npmjs.org so it is impossible to download `@types/react`.

````
registry=https://company.pkgs.visualstudio.com/_packaging/Team/npm/registry/
@types/registry=https://company.pkgs.visualstudio.com/_packaging/Team/npm/registry/
always-auth=true
````

We run [vsts-npm-auth](https://www.npmjs.com/package/vsts-npm-auth) which saves the token in npmrc file.

**Comment by mthielmann** [comment]
Is there any solution for this? I have the same issue
