### ISSUE TITLE
Progress bar prints each update on a new line

### ISSUE THREAD

**Issue by mmoreaux** [yarnpkg/yarn#4647]
Note that this bug is not fixed by #4317, it has a different cause.

The erratic behaviour, on Yarn 1.1.0, NodeJS v6.11.4, Debian 9.1, rxvt terminal emulator (`TERM=rxvt`):

![yarn_progressbar](https://user-images.githubusercontent.com/7665839/31271656-9793aa4a-aa88-11e7-8fc8-b75dde9dcc1d.png)

Strace shows that Yarn prints the progress bar without any control characters such as `\r` (in fact, not even `\n`, so technically all updates are on one huge line...):

```
22145 write(2, "[--------------------------------------------------------------------------------------------------------------------------] 0/1138", 131) = 131
22145 write(2, "[--------------------------------------------------------------------------------------------------------------------------] 3/1138", 131) = 131
22145 write(2, "[#-------------------------------------------------------------------------------------------------------------------------] 5/1138", 131) = 131
22145 write(2, "[#-------------------------------------------------------------------------------------------------------------------------] 7/1138", 131 <unfinished ...>
```

After some prodding and poking, I found out that Yarn _does_ print the progress bar properly when the `COLORTERM` environment variable is set:

![yarn_progressbar2](https://user-images.githubusercontent.com/7665839/31272157-4669db42-aa8a-11e7-8875-fea94c4a935d.png)

Strace reveals that in this case, Yarn _is_ emitting control characters, in a separate write (why not simply `\r` instead of `^[[1G`? Ehh...):

```
22401 write(2, "[--------------------------------------------------------------------------------------------------------------------------] 0/1138", 131) = 131
22401 write(2, "\33[1G", 4)             = 4
22401 write(2, "[--------------------------------------------------------------------------------------------------------------------------] 3/1138", 131) = 131
22401 write(2, "\33[1G", 4 <unfinished ...>
22401 write(2, "[#-------------------------------------------------------------------------------------------------------------------------] 5/1138", 131) = 131
22401 write(2, "\33[1G", 4)             = 4
22401 write(2, "[#-------------------------------------------------------------------------------------------------------------------------] 7/1138", 131) = 131
22401 write(2, "\33[1G", 4)             = 4
```

But this environment variable is both optional and [obsolete](https://github.com/GNOME/gnome-terminal/commit/1d5c1b6ca6373c1301494edbc9e43c3e6a9c9aaf), so Yarn should not rely on it.

**Comment by BYK** [comment]
Ah, great find! Would you like to submit a PR and get your name in the commit history for both discovering and fixing this annoyance? :)

**Comment by mmoreaux** [comment]
Hehe, nwholloway beat me to it :)

His fix works for me!

**Comment by arcanis** [comment]
Thanks anyway for letting us know :)
