### ISSUE TITLE
yarn rebuild v1.0.1    error Command "rebuild" not found.

### ISSUE THREAD

**Issue by jpca999** [yarnpkg/yarn#4656]
![image](https://user-images.githubusercontent.com/1026325/31303843-de7869fa-aae2-11e7-8d22-a1a9dce3e5ee.png)

![image](https://user-images.githubusercontent.com/1026325/31303845-e549ac8a-aae2-11e7-9f2b-53f140e2304a.png)

![image](https://user-images.githubusercontent.com/1026325/31303849-eea74616-aae2-11e7-921f-8704e00cfa46.png)

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by BYK** [comment]
Yarn does not have a `rebuild` command. I guess this is related to your project.

**Comment by jpca999** [comment]
remove all the node_modules and do it again,, will fix it.

**Comment by jayarjo** [comment]
@BYK what do you mean - yarn doesn't have rebuild command?

https://yarnpkg.com/cli/rebuild

**Comment by Kocal** [comment]
@jayarjo the page is for Yarn 2, which has been released some monthes ago. It's not for Yarn 1.

**Comment by appsparkler** [comment]
@jayarjo ,

```bash
npm i -g yarn@berry
#OR
sudo npm i -g yarn@berry
```

will install Yarn 2.

Good Luck...

**Comment by appsparkler** [comment]
@merceyz , 

Thanks for letting me know.  I've deleted the comment.
