### ISSUE TITLE
yarn global add not behaving correctly

### ISSUE THREAD

**Issue by phrazed** [yarnpkg/yarn#4666]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Adding a package with the following command

`yarn global add react-create-app`
 
seems to install the package, but later neither running 

`create-react-app `

nor 

`which create-react-app `

finds the command. Running 

`yarn global bin `

returns an empty directory. However, running

`yarn global list`

gives the following result, which seems correct

```
info "create-react-app@1.4.1" has binaries:
   - create-react-app
info "jest@20.0.4" has binaries:
   - jest
```
 
**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn global add react-create-app`

`create-react-app`

**What is the expected behavior?**
the create-react-app is installed

**Please mention your node.js, yarn and operating system version.**
node: 8.6.0
yarn: 1.1.0
os: Windows 10

**Comment by alexkrolick** [comment]
Confirmed on MacOS Sierra

**Comment by delanni** [comment]
You all might be a bit confused.
You're mentioning `yarn global add react-create-app` for 'react-create-app' then looking for 'create-react-app' - note that these are two different packages.
Try `yarn global add create-react-app` and then look for your binary. Or use `yarn create react-app` for short.

**Comment by phrazed** [comment]
You're quite right. Thanks @delanni
