### ISSUE TITLE
Feature Request: New option to ignore package.json and just use the lock file.

### ISSUE THREAD

**Issue by gandazgul** [yarnpkg/yarn#4668]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
yarn --frozen-lockfile exits if an update is needed

**What is the expected behavior?**
I would like for --frozen-lockfile to say what the needed updates are. 

AND/OR

I would like a new command-line option to ignore package.json and just use the lock file. This way we can have fully reproducible dependencies. In my case I need to archive old builds and would like to store only the build config and the yarn.lock file generated at the time of the build.

**Comment by BYK** [comment]
It is not possible to build a tree without the package.json file. You can read more about this here: https://yarnpkg.com/blog/2017/05/31/determinism/

**Comment by BYK** [comment]
>I would like for --frozen-lockfile to say what the needed updates are.

This may be an interesting feature. What do you think @arcanis?
