### ISSUE TITLE
`yarn create` doesn't appear to pass parameters

### ISSUE THREAD

**Issue by jpdriver** [yarnpkg/yarn#4670]
**Do you want to request a *feature* or report a *bug*?**

### Bug

---

**What is the current behavior?**
### Parameters do not appear to be passed through when using yarn create

- using `create-react-app my-app --scripts-version custom-react-scripts`

<img width="424" alt="screen shot 2017-10-10 at 9 35 04 am" src="https://user-images.githubusercontent.com/2393035/31376921-5a3986d8-ad9e-11e7-97c0-970da90d4052.png">

- using `yarn create react-app my-app --scripts-version custom-react-scripts`

<img width="442" alt="screen shot 2017-10-10 at 9 26 50 am" src="https://user-images.githubusercontent.com/2393035/31376733-d14c7182-ad9d-11e7-91f2-690855b0c7f3.png">

---

**If the current behavior is a bug, please provide the steps to reproduce.**

- Run a `yarn create ...` command that includes parameters e.g. `--scripts-version` above

---

**What is the expected behavior?**

- running `yarn create ...` and running `create-...` using the globally installed package should produce the same output

---

**Please mention your node.js, yarn and operating system version.**

Software|Version
---|---
NodeJS|7.10.1
Yarn|1.2.0
macOS|10.12.6

**Comment by JimmyLv** [comment]
Yep, I think actually it's quite easy to support this feature, please add it as soon as possible. ::D
