### ISSUE TITLE
strange peer-dep resolution

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#4674]
yep: 1.2.0

**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
strange issue with enzyme and react-faux-dom, enzyme-adapter-utils gets react 15 nested under it. Even though it should peer dep with enzyme-adapter-react-16's react@^16 dep.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/graingert/enzyme-wtf
**What is the expected behavior?**
react-faux-dom gets react 15 nested under it.

**Please mention your node.js, yarn and operating system version.**
Yarn: 1.2.0
Node: 8.6.0
OS: Ubuntu 17.10

**Comment by graingert** [comment]
of course with:

```sh
yarn add react@^16.0.0 react-dom@^16.0.0 react-test-renderer@^16.0.0 enzyme@^3.0.0 enzyme-adapter-react-16@^1.0.1 react-faux-dom@^4.0.4
```

everything is fine.

**Comment by BYK** [comment]
I think this was an issue with `react-faux-dom` and was resolved with https://github.com/Olical/react-faux-dom/pull/114/files

**Comment by BYK** [comment]
Yeah, I've just verified that this is not an issue with `react-faux-dom@^4.0.4`

**Comment by graingert** [comment]
@BYK sure, but yarn should not have resolved the tree as it did.

**Comment by graingert** [comment]
enzyme-adapter-utils should never have got react 15. It should have gone under react-faux-dom
