### ISSUE TITLE
Underscore prefixed config (_auth) provided by env var is converted to dash (-auth)

### ISSUE THREAD

**Issue by krmcbride** [yarnpkg/yarn#4682]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
npm config that have a `_` prefix (`_auth`, `_authToken`, `_password`), when provided as environment variables (`export npm_config__auth=blah`) have their `_` prefix converted to `-` (`-auth` instead of `_auth` for example).

**If the current behavior is a bug, please provide the steps to reproduce.**
```
npm_config__auth=abc yarn config get _auth
undefined

npm_config__auth=abc yarn config list | grep abc
  '-auth': 'abc' }
```

**What is the expected behavior?**
The npm config which start with `_` have their prefix untouched (`npm_config__auth` -> `_auth`)

**Please mention your node.js, yarn and operating system version.**
yarn 1.1.0 and 1.2.0
node 6.11.4
debian jessie

**Comment by NicholasBoll** [comment]
I found the line that is doing this: https://github.com/yarnpkg/yarn/blob/723fc3ef7fb36e01bf0c9ccd713979fac87796cc/src/registries/base-registry.js#L174
