### ISSUE TITLE
Error while trying to run coverage with yarn (npm works)

### ISSUE THREAD

**Issue by nschurmann** [yarnpkg/yarn#4699]
Hello, i'm using yarn version 1.2.0. After upgrading from 0.27.5 the following error occurs:

```
SyntaxError: /Users/nicolas/.yarn/lib/cli.js: Invalid number (91618:15)
  91616 | function chmodShim (to, cb) {
  91617 |   var then = times(2, cb, cb)
> 91618 |   fs.chmod(to, 0755, then)
        |                ^
  91619 |   fs.chmod(to + ".cmd", 0755, then)
  91620 | }
  91621 |
    at Parser.pp$5.raise (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:4454:13)
    at Parser.readNumber (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:1268:12)
    at Parser.getTokenFromCode (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:1102:21)
    at Parser.readToken (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:776:19)
    at Parser.nextToken (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:766:19)
    at Parser.next (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:691:10)
    at Parser.eat (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:698:12)
    at Parser.pp.expect (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:1749:15)
    at Parser.pp$3.parseCallExpressionArguments (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:3564:12)
    at Parser.pp$3.parseSubscripts (/Users/nicolas/dashboard/node_modules/babylon/lib/index.js:3533:31)
```

This happens when i try to run coverage with yarn, but if i use npm it works correctly

This is my script values in my package.json

```
"scripts": {
    "start": "npm run sass && babel-node server/index.js",
    "dev": "export NODE_ENV=development && npm run sass && babel-node server/index.js",
    "prebuild": "rm -rf ./dist && ./node_modules/babel-cli/bin/babel.js server -d dist/server --ignore spec.js,integration.js",
    "build": "yarn sass && webpack",
    "postbuild": "node-sass --include-path ./node_modules --include-path ./client/public client/sass/main.scss dist/client/css/main.css && blessc -f dist/client/css/main.css",
    "sass": "node-sass --include-path ./node_modules --include-path ./client/public client/sass/main.scss client/css/main.css && blessc -f client/css/main.css",
    "tdd": "export NODE_ENV=test && mocha --compilers js:babel-core/register --require babel-polyfill -R spec --watch",
    "test": "npm run sass && cross-env NODE_ENV=test mocha --timeout 20000 --recursive --compilers js:babel-core/register $(find server -path '*integration*') $(find server -path '*spec*') $(find client -path '*spec*') webpack.make.spec.js",
    "units": "mocha -- --compilers js:babel-core/register --require babel-polyfill -R spec --recursive $(find server -path '*spec*') webpack.make.spec.js",
    "integration": "mocha -- --recursive --compilers js:babel-core/register -R spec $(find server -path '*integration*')",
    "precoverage": "rm -rf ./coverage",
    "coverage": "cross-env NODE_ENV=test nyc --reporter=lcov --reporter=text npm test",
    "postcoverage": "open coverage/lcov-report/index.html",
    "serve": "node dist/server/index.js"
  },
```

**Comment by BYK** [comment]
Looks like something is trying to parse Yarn's source. We need more details than this to investigate the issue.

**Comment by peteringram0** [comment]
Im getting the exact same as this. Did you find a solution please?

**Comment by GeorgeTaveras1231** [comment]
I ran into this same issue. My problem was that I was running a yarn script and I was using the `NODE_OPTIONS` to pass options to the underlying node process. I'm also using `babel-register` to use esm syntax in node. So my command looked something like `NODE_OPTIONS="-r babel-register" yarn my-command`. This was causing `babel-register` to try and parse yarn's source code (as @BYK suggested). I fixed this by making `babel-register` ignore the location of yarn's source: 

```js
require('babel-register')({ ignore: [ /* Omitted */ ] })
```

**Comment by simon-ohara** [comment]
I also had this exact problem after upgrading from `yarn@1.2.1` to `1.5.1`. However, I do not think the version of yarn is the problem, but the way it is installed. My `1.2.1` had been a global `npm` install, whereas the `1.5.1` was an upgrade using the `install.sh` file. I followed the instructions from the yarn warning itself which I think comes from [here](https://github.com/yarnpkg/yarn/blob/66a0143a753cd4ade1a0fffee2174890d564c129/src/cli/commands/install.js#L88).

I had also run `npm remove yarn -g`.

I dont think the use `babel-register` is the problem as I was able to run the underlying test suite fine which uses it:

```json
"test": "mocha --colors --require babel-register --require test/globals test/setup 'test/**/*-spec.js' test/teardown",
```

It was specifically when this was wrapped with `nyc`:

```json
"test-coverage": "nyc yarn test",
```

After having the problems and not finding any suitable solution, even using some [excludes](https://github.com/istanbuljs/nyc#excluding-files) for `nyc` in my `package.json`, I decided to install yarn using npm again. So still using `yarn@1.5.1` and guess what - no crazy error! :smile_cat:

**Comment by fmatoss** [comment]
This error is because `babel` runs `yarn/lib/cli.js` in strict-mode and throws a `SyntaxError` when using a [deprecated feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_octal), octal numbers must be prefixed with `0o` to work in strict-mode.

**Comment by merceyz** [comment]
Closing as this has been fixed some time ago, the file now uses `0o755`
