### ISSUE TITLE
yarn upgrade rebuilding all packages regardless if outdated

### ISSUE THREAD

**Issue by rockchalkwushock** [yarnpkg/yarn#4703]
First I want to say great job with all the updates and feature that have been added to `yarn` since its creation. It has been very cool to see how far this project has come 👍 

**Do you want to request a *feature* or report a *bug*?**

I searched through the issues and did not find anything similar; to be honest I'm not sure if it's an issue or the way `yarn upgrade` is suppose to handle _upgrading_ the dependencies. When running `yarn upgrade` the entire dependency tree is being rebuilt instead of **only** the outdated packages (and there dependencies).

**What is the current behavior?**

When running `yarn outdated`:

![screen shot 2017-10-13 at 05 50 33](https://user-images.githubusercontent.com/19720404/31543343-3a706b16-afdb-11e7-8024-0cde7553d85d.png)

When running `yarn upgrade`:

![screen shot 2017-10-13 at 05 50 48](https://user-images.githubusercontent.com/19720404/31543356-47ae7912-afdb-11e7-9374-5721579c53cc.png)

Should `yarn upgrade` be _rebuilding_ **all** dependencies again? I did not include the very very long output from the terminal that showed _all_ 616 dependencies. I realize there is `yarn upgrade-interactive` in which I can choose what to upgrade, but it seems that either command should not rebuild _all_ packages but _only_ those needing to be upgraded as well as their dependencies.

**What is the expected behavior?**

That `yarn` will rebuild only the packages that are outdated & their dependencies **not** the entire dependency tree.

**Please mention your node.js, yarn and operating system version.**

| Tech            | Version |
|-----------------|---------|
| `node`          |   8.6.0      |
| `yarn` |   1.2.1      |
| macOS              |   10.13      |

**Comment by simonkberg** [comment]
Note that `yarn upgrade` also upgrades transitive dependencies, so I'm pretty sure it has to traverse the entire dependency tree and upgrade each dependency individually. If you want to limit the scope to one or more packages you can pass them as arguments to the command `yarn upgrade foo bar`.

**Comment by rockchalkwushock** [comment]
@simonkberg 

Ah I see. I was not sure if what I was seeing was _normal_ behavior or not. I'd been on vacation for 3 weeks so everything looked new & different to me. Plus I'd upgraded from `0.27.5` to the `latest`. Thank you for the information, learn something new every 10 minutes! 😄 

Feel free to close.

**Comment by OmgImAlexis** [comment]
@rockchalkwushock I think this should stay open as I've noticed doing `yarn upgrade medusa-lib@latest` is causing other deps to be rebuilt that aren't deps of `medusa-lib`.

This not only installed `medusa-lib` but also rebuilt `protagonist` which is an optional dep of drafter which dredd uses. I have dredd added as a devDep in this project so there's no reason the upgrade should have touched that module.

```
➜  Medusa git:(js-2017) ✗ yarn add medusa-lib@latest
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ medusa-lib@0.0.9
✨  Done in 191.96s.
```

**Comment by rockchalkwushock** [comment]
Has this been fixed? I am not seeing the issue with `yarn@1.5.1`.

**Comment by tlycken** [comment]
@rockchalkwushock I'm still seeing this with `yarn@1.6.0` so it seems it hasn't been fixed.

**Comment by stevemarksd** [comment]
Any news on this? I'm upgrading my local library from 1.0.1 to 1.0.2 and rebuild all modules... that is insane...

**Comment by nick-delirium** [comment]
same stuff 1.22.19
