### ISSUE TITLE
Inconsistent versions are assigned in nested packages.

### ISSUE THREAD

**Issue by karak** [yarnpkg/yarn#4705]
`yarn install` assigns different version of one package between the package itself and nested packages.  In my case, this behavior caused compile errors in TypeScript, and it may introduce many other troubles.

Minimum reproducing project is [HERE](https://github.com/karak/yarn-upgrade-inconsistency).

Should `yarn install` assign consistent versions and keep the consistency after `yarn upgrade` in the future?

My environment is macOS Sierra & node 8.6.0, but same in 6.10.

**Comment by BYK** [comment]
Please provide the Yarn version you are having issues with.

**Comment by karak** [comment]
@BYK yarn 1.2.1 reproduced this.

**Comment by edmorley** [comment]
Hi! The STR are a bit unclear at the moment, since they don't include a before-upgrade state. Could you expand them slightly?

Running `yarn install` from that repo, `yarn list` then shows:
```
...
├─ @types/react-dom@16.0.1
│  ├─ @types/node@*
│  ├─ @types/react@*
│  └─ @types/react@16.0.10
├─ @types/react@16.0.7
```

...whereas if I `rm -rf yarn.lock node_modules && yarn install`, I then get:
```
...
├─ @types/react-dom@16.0.2
│  ├─ @types/node@*
│  └─ @types/react@*
├─ @types/react@16.0.18
```

I'm presuming after the `yarn upgrade` you were expected the latter (the versions to be consolidated)?

**Comment by edmorley** [comment]
Though I guess this is a dupe of #3951 / #4136 - ie: `@types/react-dom` should fix it's version ranges or start using `peerDependencies`?

**Comment by BYK** [comment]
@edmorley sounds like it. Shall we close this issue?

**Comment by karak** [comment]
@edmorley 
> Hi! The STR are a bit unclear at the moment, since they don't include a before-upgrade state. Could you expand them slightly?

Oh, I can't remember that clearly, but it include some iterative yarn upgrade, and may include removing node_modules and reinstalling to try to fix.  In addition to that, I found the order of arguments of yarn install affects to their versions.

> Though I guess this is a dupe of #3951 / #4136 - ie: @types/react-dom should fix its version ranges or start using peerDependencies?

I agree you about the compile errors.

However, I still suspect why their versions differ by upgrading. Now, both of `yarn upgrade @types/react` and `yarn upgrade @types/react @types/react-dom` never update the "@types/react@*" entry in yarn.lock as bellow: 

Before:

```
"@types/react@*":
  version "16.0.10"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.0.10.tgz#a24b630f5f1f170866a148a147d4fc8636ea88e0"

"@types/react@^16.0.7":
  version "16.0.7"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.0.7.tgz#f85b6c33c988a1631e2f32fedae71ec6d9718a0d"

```

After:
```
"@types/react@*":
  version "16.0.10"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.0.10.tgz#a24b630f5f1f170866a148a147d4fc8636ea88e0"

"@types/react@^16.0.7":
  version "16.0.18"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.0.18.tgz#c08eea79ada55bf10b5353e18c21797dd17afa23"

```

**Comment by karak** [comment]
@BYK OK to close. Yarn doesn't matter this anyway.
