### ISSUE TITLE
Differing React dependencies

### ISSUE THREAD

**Issue by benbrandt** [yarnpkg/yarn#4707]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
It is separating the following dependencies like so:
```
react@15.6.2:
  version "15.6.2"
  resolved "https://registry.yarnpkg.com/react/-/react-15.6.2.tgz#dba0434ab439cfe82f108f0f511663908179aa72"
  dependencies:
    create-react-class "^15.6.0"
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.10"

"react@^15 || ^16":
  version "16.0.0"
  resolved "https://registry.yarnpkg.com/react/-/react-16.0.0.tgz#ce7df8f1941b036f02b2cca9dbd0cb1f0e855e2d"
  dependencies:
    fbjs "^0.8.16"
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
    prop-types "^15.6.0"
```

**If the current behavior is a bug, please provide the steps to reproduce.**

in package.json `"react": "15.6.2"` is in `dependencies`
`"react-error-overlay": "2.0.2"` is in `devDependencies`

**What is the expected behavior?**
```
react@15.6.2, "react@^15 || ^16":
  version "15.6.2"
  resolved "https://registry.yarnpkg.com/react/-/react-15.6.2.tgz#dba0434ab439cfe82f108f0f511663908179aa72"
  dependencies:
    create-react-class "^15.6.0"
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.10"
```

**Please mention your node.js, yarn and operating system version.**
Node: 8.7.0
Yarn: 1.2.1
OS: Mac OS X 10.12.6

**Comment by BYK** [comment]
@arcanis I remember us having an issue about improving deduplication/hoister. Do you think this falls into that?

**Comment by BYK** [comment]
Found it #3778
