### ISSUE TITLE
Docs: --ignore-workspace-root-check is not documented

### ISSUE THREAD

**Issue by customcommander** [yarnpkg/yarn#4711]
Hi,

I'm using `1.2.1` and I have the workspace feature flag enabled.

I'd like to install `lerna` as a "root" dependency:

```
yarn add lerna --dev
yarn add v1.2.1
error Running this command will add the dependency to the workspace root rather than workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
The error message is probably enough to be honest. The problem imho is that the info message suggests you can get more info at the doc page which isn't the case.

**Comment by BYK** [comment]
Moved to https://github.com/yarnpkg/website/issues/681
