### ISSUE TITLE
strange latency with yarn install

### ISSUE THREAD

**Issue by e-cloud** [yarnpkg/yarn#4718]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/5255354/31599214-fded6684-b283-11e7-9256-e7a397560b3a.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
no clear step to reproduce. It occur only after upgrading to v1.2.1. It might related to my network condition.

**What is the expected behavior?**
yarn exit immediately after done ouput?

**Please mention your node.js, yarn and operating system version.**
node v8.7.0. ubuntu 17.04

**Comment by BYK** [comment]
That's quite odd. Looks like when there is a network issue, Yarn keeps trying.

**Comment by BYK** [comment]
Is it possible for you to run `yarn --verbose` and share the output?

**Comment by e-cloud** [comment]
@BYK thanks for timely response. The fact is when I switch off my vpn, yarn exits itself quickly.

I can't reproduce it for now. Sorry.

Looks like yarn's network handling is separated from install logic? Otherwise even network is slow, it should  terminate the network request, or wait util network request succeed then continue installation.

**Comment by BYK** [comment]
I think the retry timers are lingering around even after things settle. Shouldn't be too hard to fix.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic has been improved

https://yarnpkg.com/getting-started/migration
