### ISSUE TITLE
yarn version [version]

### ISSUE THREAD

**Issue by jamiebuilds** [yarnpkg/yarn#472]
**Do you want to request a _feature_ or report a _bug_?** Feature

**What is the current behavior?**

When you enter `yarn version` it opens up a prompt to enter a new version. This is hard for scripts to deal with.

**What is the expected behavior?**

The following should create a new version without prompting the user:

``` sh
yarn version [1.0.0,major,minor,patch,etc]
```

See: https://docs.npmjs.com/cli/version

**Comment by adamreisnz** [comment]
Sorry to dig this up, but this doesn't seem to work without specifying the `--new-version` flag which is rather annoying. It's so ingrained in me to type `npm version patch`, why do we need to include this very verbose flag to get the same result with yarn?

Can't the `version` command check if the parameter passed after the command matches a valid version identifier and update it accordingly, e.g. `[1.0.0,major,minor,patch,etc]`?
