### ISSUE TITLE
NO_PUBKEY error on Linux Ubuntu, when apt-get install yarn

### ISSUE THREAD

**Issue by ThomasVuillaume** [yarnpkg/yarn#4727]
Hello everyone !

I'm trying to install yarn up to the latest version on my Ubuntu server ( Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)), but I'm stuck on 1.0.1 because when I hit the command line with apt-get install yarn, I'm getting this error (in French, sorry):

> W: Une erreur s'est produite lors du contrôle de la signature. Le dépôt n'est pas mis à jour et les fichiers d'index précédents seront utilisés. Erreur de GPG : https://dl.yarnpkg.com stable InRelease : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY E074D16EB6FF4DE3
> 
> W: Impossible de récupérer https://dl.yarnpkg.com/debian/dists/stable/InRelease
> 
> W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

But basically, it says that PGP keys are not OK because there are no public key available to check this "https://dl.yarnpkg.com/debian/dists/stable/InRelease"

Anyone has the same here ?

**Comment by Daniel15** [comment]
Did you add the key?
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

**Comment by ThomasVuillaume** [comment]
Woops, sorry I thought I did, but must have been on my other VM ...

Thanks for the answer !

Closed
