### ISSUE TITLE
Global upgrade-interactive leaves behind package.json and yarn.lock

### ISSUE THREAD

**Issue by TimvdLippe** [yarnpkg/yarn#4728]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn global upgrade-interactive` creates a `package.json` and `yarn.lock` in the folder that you invoke the command
**If the current behavior is a bug, please provide the steps to reproduce.**
* Have some globally installed outdated packages
* Go to a folder
* Invoke `yarn global upgrade-interactive`

**What is the expected behavior?**
No `yarn.lock` and `package.json` are generated if `upgrade-interactive` is invoked with the `global` property
**Please mention your node.js, yarn and operating system version.**
Node: 8.6.0
Yarn: 1.2.1
OS: Ubuntu 16.04

**Comment by 4cm4k1** [comment]
I duplicate this; also, the global binaries all end up being unlinked to my set prefix (`/usr/local`) and therefore not in my `$PATH`. The packages listed in the `package.json` are only the ones that were upgraded.

* Node: 8.7.0
* Yarn: 1.2.1
* OS: macOS 10.13.1 Beta 2

Temporary workaround: run `yarn global add` to get everything back in `$PATH` and `rm -rf node_modules package.json yarn.lock` in the working directory.
