### ISSUE TITLE
Can't install package over git+ssh with non-standard port when using plink on Windows

### ISSUE THREAD

**Issue by theGrue** [yarnpkg/yarn#4729]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A `plink: unknown option "-p"` error is shown.

```
λ yarn add git+ssh://git@github.com:22/substack/node-mkdirp.git
yarn add v1.2.1
info No lockfile found.
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com:22/substack/node-mkdirp.git
Directory: C:\yarn-issue
Output:
plink: unknown option "-p"
fatal: Could not read from remote repository.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Attempt to install a package over git+ssh, specifying a port number, on Windows with Git configured to use plink.

When researching other git+ssh issues, I found this command, which works: 
`yarn add git+ssh://git@github.com/substack/node-mkdirp.git`

But, when specifying a port number, it does not: 
`yarn add git+ssh://git@github.com:22/substack/node-mkdirp.git`

My company uses a private BitBucket server that runs over a non-standard port, so I'm not able to use Yarn with our private dependencies like I can with NPM, at least on Windows/plink.

Plink's documentation (https://the.earth.li/~sgtatham/putty/0.60/htmldoc/Chapter7.html) specifies that ports are specified by `-P`. If Yarn is using lowercase `-p` instead, that would explain the error.

**What is the expected behavior?**
Private dependencies on non-standard ports should be able to be installed with Windows/plink.

**Please mention your node.js, yarn and operating system version.**
Node v6.9.5, Yarn 1.2.1, Windows 10

**Comment by BYK** [comment]
I think I know why. It is this line: https://github.com/yarnpkg/yarn/blob/6b185c23d8d7770a3dc7a9b872c18ad25a98a20c/src/util/git/git-spawn.js#L17

I know we needed lower-case for something but I need to look around more. If you're interested you can try this yourself and submit a PR :)

**Comment by theGrue** [comment]
Upgraded to Yarn 1.3.2 today and I'm still receiving the `plink: unknown option "-p"` error.

**Comment by neonowy** [comment]
@theGrue Could you check your local Git version? You must have at least version 2.13.0 installed.

**Comment by theGrue** [comment]
Aha, that did the trick! Thanks for the quick reply.
