### ISSUE TITLE
`upgrade-interactive --latest` suggests to downgrade dependency 

### ISSUE THREAD

**Issue by ipanasenko** [yarnpkg/yarn#4735]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
when running `yarn upgrade-interactive --latest` it suggests to install version 1.0.1

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn add react-refetch@1.0.3-0
yarn upgrade-interactive --latest
```

**What is the expected behavior?**
I think it shouldn't suggest to downgrade 

**Please mention your node.js, yarn and operating system version.**
mac os high sierra
node 8.7.0
yarn 1.2.1

**Comment by edmorley** [comment]
The most recent stable release of `react-refetch` is 1.0.1, with the `1.0.3-0` release being on the `beta` tag:
```
$ npm view react-refetch dist-tags
{ latest: '1.0.1', beta: '1.0.3-0' }
```

Whilst it seems logical for `upgrade-interactive --latest` to not suggest upgrading to the beta release (if one is on an older release), I agree that perhaps it should not **downgrade** if already on the higher version beta.

**Comment by rally25rs** [comment]
I think this was my fault; I had some code in `getOutdatedPackages` that would ignore filtering out packages that actually needed an upgrade, and just return them all when not upgrading a specific package. I believe that code is no longer needed and can be removed. I'll make a PR...
