### ISSUE TITLE
yarn async tests timeout on mac

### ISSUE THREAD

**Issue by connectdotz** [yarnpkg/yarn#4738]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
cloned the yarn repository
yarn build
yarn test

tests run painfully slow, followed by timeout errors for some async tests, for example: 
```
__tests__/integration.js (453.613s)
   ● yarn add https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at ontimeout (timers.js:469:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:264:5)

  ● yarn add react-scripts@1.0.13

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at ontimeout (timers.js:469:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:264:5)

  ● --registry option › --registry option with non-exiting registry and show an error

    expect(received).toMatch(expected)
    
    Expected value to match:
      /getaddrinfo ENOTFOUND example-registry-doesnt-exist\.com/g
    Received:
      "Command failed: /bin/sh -c /Users/vsun/ConnectDotz/External/yarn/bin/yarn add is-array --registry https://example-registry-doesnt-exist.com
    error An unexpected error occurred: \"https://example-registry-doesnt-exist.com/is-array: ETIMEDOUT\".
    
    "
      
      at Object.<anonymous> (__tests__/integration.js:197:39)
          at Generator.throw (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

```
 

**If the current behavior is a bug, please provide the steps to reproduce.**

see above

**What is the expected behavior?**

Looks like the master should be stable since all CI indicators are green, hence expect all tests should pass...

**Please mention your node.js, yarn and operating system version.**
node.js: 8.4.0
yarn: master branch
os: macOS 10.12.6

**Comment by connectdotz** [comment]
looking at one of the failed test of `__tests__/integration.js: --registry option with non-exiting registry and show an error`: it is trying to match a pretty explicit string that looks like could be platform or node dependent... 

I could fix that but was just wondering if these tests suppose to pass on mac or only on specific linux/node combination (looks like the circle test is setup for debian only)? Should I even bother to run them on mac?

**Comment by merceyz** [comment]
Closing as an external issue, ref https://github.com/yarnpkg/yarn/pull/6211
