### ISSUE TITLE
Remove RC GPG key with no expiration date

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#4739]
From @KwadroNaut on https://github.com/yarnpkg/website/issues/664

> sub rsa4096 2016-10-30 [S]
> It has a subkey capable of signing without an expiration date? This sounds like a super bad idea asking people to trust such a key for all their packages on their OS.

I agree with this. This key is only used for RC releases. To fix this, I'll either create a new subkey with an expiration date, or I'll create a totally separate key for signing RC releases.

**Comment by KwadroNaut** [comment]
You could also revoke it, or edit it by adding an expiry. Only creating a new subkey wouldn't make the original one invalid.

**Comment by Daniel15** [comment]
Oh I didn't realise I could simply edit it and add an expiry. If so, that's easy :) 

> Only creating a new subkey wouldn't make the original one invalid.

Of course, by "create a new subkey" I also meant to say "and revoke the old one". I don't think many people would be using the RC repository.

**Comment by webmaster128** [comment]
Any news here? The non-expiring signing key is still in https://dl.yarnpkg.com/debian/pubkey.gpg

**Comment by Daniel15** [comment]
Thanks for the reminder, this fell off my radar. Currently busy with other stuff so open-source work isn't as high a priority for me at the moment.

Added an expiry date to the RC signing key in https://github.com/yarnpkg/releases/pull/1. Confirmed that the repo still works.
