### ISSUE TITLE
Allow shell variables in `.yarnrc`

### ISSUE THREAD

**Issue by HaleTom** [yarnpkg/yarn#4740]
### **Feature** (supported by `npm`)

**Current behavior**

`npm` allows in the `.npmrc`:

```
prefix=${XDG_DATA_HOME}/npm
```

However, when I type in my shell:
```
yarn config set prefix '${XDG_DATA_HOME}/npm'
```

I see this in my `~/.yarnrc`:
```
prefix "/home/ravi/.local/share/npm"
```

**What is the expected behavior?**
.yarnrc contains:
```
prefix "${XDG_DATA_HOME}/npm"
```

**Please mention your node.js, yarn and operating system version.**
```
$ node --version
v8.5.0
$ yarn --version
1.1.0
$ uname -a
Linux svelte 4.9.52-1-MANJARO #1 SMP PREEMPT Wed Sep 27 16:40:38 UTC 2017 x86_64 GNU/Linux
```

**Comment by HaleTom** [comment]
Will likely be required in conjunction with #2334.

**Comment by paul-soporan** [comment]
Closing as v2 allows environment variables to be used in `.yarnrc.yml` files.

https://yarnpkg.com/getting-started/migration
