### ISSUE TITLE
Running version with --no-git-tag-version skips script hook

### ISSUE THREAD

**Issue by am** [yarnpkg/yarn#4744]
**What is the current behavior?**
Running `yarn version  --no-git-tag-version` does not run the script hook `version`.

**Steps to reproduce**

1. Init the project:

```shell
mkdir yarn-bug && cd yarn-bug && yarn init --yes && git init && git add package.json && git commit -m "Init"
```

2. Change `package.json` to include a script version hook:

```json
{
  "name": "yarn-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "version": "echo 'version script hook'"
  }
}
```
3. Now bump the version:

```shell
yarn version  --no-git-tag-version
# yarn version v1.2.1
# info Current version: 1.0.0
# question New version: 1.0.1
# info New version: 1.0.1
# ✨  Done in 9.49s.
```

**What is the expected behavior?**
Run `yarn version  --no-git-tag-version` should run the script hook `version`.

The output should have been the same as when running without a flag:

```shell
yarn version
# yarn version v1.2.1
# info Current version: 1.0.1
# question New version: 1.0.2
# info New version: 1.0.2
# $ echo 'version script hook'
# version script hook
# ✨  Done in 6.05s.
```

**Please mention your node.js, yarn and operating system version.**

```shell
node --version
v6.11.3
yarn --version
1.2.1
```

**Comment by edmorley** [comment]
It looks like the `version` lifecycle call here:
https://github.com/yarnpkg/yarn/blob/v1.2.1/src/cli/commands/version.js#L139

...should be moved before the early return here:
https://github.com/yarnpkg/yarn/blob/v1.2.1/src/cli/commands/version.js#L118-L122

(Given that [the npm docs](https://docs.npmjs.com/misc/scripts) say "version: Run AFTER bumping the package version, but BEFORE commit.". Presumably `postversion` should still be skipped?)
