### ISSUE TITLE
[DOC] Installing yarn on docker images

### ISSUE THREAD

**Issue by andreawyss** [yarnpkg/yarn#4752]
Add language in the installation instruction to be aware to first remove existing versions of yarn installed. This is a common problem when installing the latest version of yarn with apt-get on a docker image such as the docket hub 'node:6.11.4'. 

This 2 command are required before installing yarn with apt-get
#### Remove yarn: symbolic links and binary that where installed as part of the node image
RUN rm /usr/local/bin/yarn && rm /usr/local/bin/yarnpkg
RUN rm -rf /opt/yarn

app-get will install the latest version of yarn in /usr/bin but if the old version is present in /usr/local/bin then this will be used instead.

**Comment by Daniel15** [comment]
Feel free to submit a pull request adding this to the site, if you like :)

**Comment by Daniel15** [comment]
This issue was moved to yarnpkg/website#706
