### ISSUE TITLE
the "resolutions" block of package.json is not documented

### ISSUE THREAD

**Issue by IgorMinar** [yarnpkg/yarn#4754]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
no docs for `resolutions` anywhere in the yarn docs. Specifically I'd expect to see a documentation block as part of the `package.json` document: https://yarnpkg.com/en/docs/package-json

The only info about this feature that I could find is in the PR and RFC:
- https://github.com/yarnpkg/yarn/pull/4105
- https://github.com/yarnpkg/rfcs/pull/68/files

**Comment by kaylieEB** [comment]
@IgorMinar thanks for the issue! Would you be open to submitting a pr in the website repo? 
The file is here: https://github.com/yarnpkg/website/blob/master/lang/en/docs/package-json.md

**Comment by IgorMinar** [comment]
@kaylieEB done

**Comment by IgorMinar** [comment]
https://github.com/yarnpkg/website/pull/687

**Comment by schickling** [comment]
Probably the wrong place to ask, but does anyone know whether this feature is planned to be adopted by `npm` and other tools working with `node_modules` such as `now`?
