### ISSUE TITLE
`yarn outdated` output not visible in powershell

### ISSUE THREAD

**Issue by pdeva** [yarnpkg/yarn#4758]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The `latest version` column is invisible in powershell.

Screenshot 1:
![image](https://user-images.githubusercontent.com/3190176/31872386-61360f66-b770-11e7-8eb6-f68a5eca0a6c.png)

Screenshot 2 (with selection):
![image](https://user-images.githubusercontent.com/3190176/31872392-6b8182c0-b770-11e7-8782-54c23f28717a.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Open Windows Powershell, and type `yarn outdated`.

**What is the expected behavior?**

The column should be visible in powershell

**Please mention your node.js, yarn and operating system version.**

Yarn 1.2.1
Windows 10
Node 6.9.5

**Comment by ThisWillDoIt** [comment]
@pdeva Did you by any chance install the Windows Fall Creators Update (1709 / 16299.19) already?  


I am pretty sure nothing changed on one of my projects (not the yarn version, not the node version, nor any package.json file) since last week when it still worked perfectly fine.

**Comment by pdeva** [comment]
My version of windows:

```
Version	10.0.15063 Build 15063
```

**Comment by Sylphony** [comment]
I don't have this issue but I am on Windows 7.  Chances are it is a Windows 10 Powershell version issue.

![image](https://user-images.githubusercontent.com/1796078/31910838-9a36a6a8-b7f3-11e7-8445-f5e14da89f76.png)

**Comment by Antaris** [comment]
@ThisWillDoIt I'm also having issues with yarn since installing 1709. I don't want to hijack this issue, but what issues have you encountered since updating?

**Comment by vebaspect** [comment]
I have the same problem.

_Windows_: 10.0.15063 Build 15063
_Yarn_: 1.3.2
_Node_: 8.9.1

**Comment by excelsior97** [comment]
I will submit a pull request on this in a few days
