### ISSUE TITLE
Running yarn link unlinks any modules linked via yarn link.

### ISSUE THREAD

**Issue by chaddjohnson** [yarnpkg/yarn#4770]
Yarn version 1.2.1.

**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Running `yarn add [package-name]` unlinks any linked modules. Here is a screenshot showing this:

<img width="874" alt="screen shot 2017-10-24 at 10 18 15 am" src="https://user-images.githubusercontent.com/676134/31951841-beefaa06-b8a4-11e7-9152-a3ce297b3658.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

`cd app`
`ls -l node_modules | grep sequential` --> shows that the module is not linked
`yarn link sequential-ids`
`ls -l node_modules | grep sequential` --> shows that the module is now linked
`yarn add lodash`
`ls -l node_modules | grep sequential` --> shows that the module is now unlinked

**What is the expected behavior?**

`yarn add [package-name]` should never cause linked packages to become unlinked.

**Please mention your node.js, yarn and operating system version.**

Node 8.6.0.

macOS High Sierra. This also happened on Sierra.

**Comment by whitecolor** [comment]
Right, before v1 `yarn` didn't touch symlinks in `node_modules`, but now when it performs some actions in `node_modles` it removes the symlinks of deps folders if it is not `link:` dependency.

**Comment by bestander** [comment]
@arcanis @BYK, raising this to your attention, looks like a noticeable regression.

**Comment by AlastairTaft** [comment]
Would be really useful for me if this one was fixed.

**Comment by chaddjohnson** [comment]
I understand this is fixed. Thank you. How can we test?

**Comment by whitecolor** [comment]
> I understand this is fixed. Thank you. How can we test?

Clone master and build it, install using `npm link`, or wait for a release)
