### ISSUE TITLE
Received malformed response from registry for undefined. When adding proxy to yarn config file

### ISSUE THREAD

**Issue by aimad-majdou** [yarnpkg/yarn#4771]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

I moved from using bower to yarn, and in my `.bowerrc` file I had as following:

```
{
    "directory": "src/main/webapp/bower_components",
    "proxy": "http://webdefence.global.blackspider.com:80",
    "https-proxy": "http://webdefence.global.blackspider.com:80"
}
```

And in `.npmrc` file I had as following : 

```
save-prefix = ~
proprietary-attribs = false
registry = http://abc-pic:8081/nexus/content/repositories/npmjs/
```

So I removed these two files and I run the following commands : 

```
yarn config set https-proxy http://webdefence.global.blackspider.com:80
yarn config set proxy http://webdefence.global.blackspider.com:80
yarn set registry http://abc-pic:8081/nexus/content/repositories/npmjs/
yarn config set proprietary-attribs false
yarn config set save-prefix ~
```

And then I run the following command : 

`yarn install --force --flat --production --modules-folder src/main/webapp/bower_components`

But then I receive this error : 

`error Received malformed response from registry for undefined. The registry may be down.`

**Yarn config list**

```
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '~',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'http://abc-pic:8081/nexus/content/repositories/npmjs/',
  'strict-ssl': true,
  'user-agent': 'yarn/1.2.1 npm/? node/v5.1.0 win32 x64',
  'https-proxy': 'http://webdefence.global.blackspider.com:80',
  lastUpdateCheck: 1508835683941,
  'modules-folder': 'src/main/webapp/bower_components',
  'proprietary-attribs': false,
  'proproprietary-attribs': false,
  proxy: 'http://webdefence.global.blackspider.com:80' }
info npm config
{}
```

**What is the expected behavior?**

yarn install works.

**Please mention your node.js, yarn and operating system version.**

OS : windows 7 win32 x64 
node version : 5.1.0
yarn version : 1.2.1
npm version : 3.3.12

**Comment by rally25rs** [comment]
Could you also add the flag `--verbose` and get the output? Hopefully that will indicate what URL it is trying to hit when it reports this error.

**Comment by aimad-majdou** [comment]
This is what I got running the install with the flag `--verbose` : 

```
[1/4] Resolving packages...
verbose 0.709 Performing "GET" request to "http://abc-pic:8081/nexus/content/repositories/npmjs/angular".
verbose 0.969 Request "http://abc-pic:8081/nexus/content/repositories/npmjs/angular" finished with status code 503.
verbose 0.979 Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError (C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:138:26)
    at C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:48854:15
    at next (native)
    at step (C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:92:30)
    at C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:110:14
    at new Promise (C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:93019:7)
    at C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:89:12
    at Function.findVersionInRegistryResponse (C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:48885:7)
    at C:\Dev\Workspace\ABC\webapps\rhweb\node\node_modules\yarn\lib\cli.js:48902:28
    at next (native)
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by rally25rs** [comment]
> ... finished with status code 503

looks like your registry is throwing an error. Try opening that URL http://abc-pic:8081/nexus/content/repositories/npmjs/angular in your browser and see what it returns?

**Comment by rally25rs** [comment]
> ... finished with status code 503
makes it sound like the registry might be throwing an error when Yarn hits it.

**Comment by aimad-majdou** [comment]
@rally25rs I noticed that this behavior only occurs when I set proxy and `https-proxy` to  `http://webdefence.global.blackspider.com:80` which I used in .bowerrc

**Comment by Vall3y** [comment]
This is not a solution for your bug, but you also get an error like that if you have an illegal package name (such as an empty string `" ": "1.0.0"`)

**Comment by joshunger** [comment]
This also happens if you have a registry that can't be accessed (like only via VPN) but your cable provide still provides an HTML page. :)

**Comment by knoxcard** [comment]
I just encountered this bug for the first time today.  `yarn upgrade` would always be flawless.  Shouldn't the default behavior error out to the console log but move on to process everything else that is available?

**Comment by flewid-cd** [comment]
+1

**Comment by tahv0** [comment]
+1 Having this issue right now

**Comment by echoulen** [comment]
Now is very slow without `.yarnrc` and `yarn.lock`

**Comment by philipjc** [comment]
Getting this issue using create-react-app

**Comment by technobia** [comment]
It back to normal currently :)

**Comment by zaiz91** [comment]
+1

**Comment by nadzic** [comment]
Still down :>

**Comment by glennreyes** [comment]
Same here!

**Comment by technobia** [comment]
Work for me yarn@1.5.1.

**Comment by izaikapdffiller** [comment]
+1

**Comment by knoxcard** [comment]
I am really rooting for you guys, don't want to go back to that stone age package manager....NPM

**Comment by echoulen** [comment]
npm is very slow too

**Comment by flewid-cd** [comment]
yes npm is also downish.

**Comment by flewid-cd** [comment]
so maybe not a yarn issue.

**Comment by EJIqpEP** [comment]
It's for sure npm issue because https://registry.npmjs.org/ is 503.

**Comment by vrajau** [comment]
Working again now!

**Comment by philipjc** [comment]
I just had a successful, create-react-app

**Comment by knoxcard** [comment]
So NPM is the cause?  NPM is still causing problems even though I've switched to Yarn? Interesting...

**Comment by flewid-cd** [comment]
@knoxcard yarn is on top of npm.

**Comment by DmitryAstafyev** [comment]
Amazing. So many things depend on one service and there is no quick way around :/ Something is wrong definitely. 
Works again, but unit next malfunction I guess.

**Comment by vrajau** [comment]
The day npm is definitely down, we are all doomed.

**Comment by flewid-cd** [comment]
Down again.

**Comment by echoulen** [comment]
Down again +1

**Comment by flewid-cd** [comment]
https://github.com/npm/registry/issues/324

**Comment by knoxcard** [comment]
@flewid-cd Yarn should get beneath NPM and then rise like a Phoenix.

**Comment by brisqqltd** [comment]
https://github.com/yarnpkg/yarn/issues/5885

**Comment by SupremeTechnopriest** [comment]
`Error: Received malformed response from registry for undefined. The registry may be down.`

**Comment by yarindeoh** [comment]
+1

**Comment by Rud156** [comment]
Down Again.

**Comment by daveconnis** [comment]
Yeah. Was getting the same error for a `yarn add`, but I tried it again and we're golden. What is technology, even.

**Comment by BYK** [comment]
I closed this issue since it diverged from the original description quite a lot. @rally25rs feel free to create a new one to track the original issue.

**Comment by missMHWGO** [comment]
> This also happens if you have a registry that can't be accessed (like only via VPN) but your internet provider returns a backup HTML page.  If you want a PR let me know what you specifically want fixed.
> 
> Here is my `.npmrc` -
> <img alt="image" width="438" src="https://user-images.githubusercontent.com/2301847/37642621-6f164c94-2be3-11e8-84bf-985b5496874f.png">
> 
> Here is `curl -v` -
> <img alt="image" width="709" src="https://user-images.githubusercontent.com/2301847/37642677-b844120c-2be3-11e8-9f5c-a5423b3fdf66.png">
> 
> `yarn add prop-types --verbose`
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/2301847/37642743-ef71ee7a-2be3-11e8-9a53-51e035ea26d3.png">

@joshunger Could you please tell me how to have such a cute and lovely terminal prompt？Wo~~~I like it~~~
<img width="709" alt="37642677-b844120c-2be3-11e8-9f5c-a5423b3fdf66" src="https://user-images.githubusercontent.com/14312158/65851204-aa11eb00-e384-11e9-9cd0-992ebeabc6d8.png">

**Comment by hayelom123** [comment]
yeahh the same here

**Comment by webprogrammierer** [comment]
I have this errors using my Ubuntu VM (Drupal VM) to install packages or to run 'yarn install' and other command.
I have this errors since I have installed Docker & WSL 2 on my Windows 10 Pro.

How can those network issues be solved?

**Comment by km4dlpx** [comment]
Error: Received malformed response from registry for "webpack". The registry may be down.

I am getting this again and again, how we can solve it?

**Comment by joshuaebowling** [comment]
For anyone else who may be having this problem... for me, it turned out that a package I had installed had an empty name " ". Once I removed that reference, the packages started to flow again :)

**Comment by shadowctrl** [comment]
deleted .yarn-lock solved my issue
