### ISSUE TITLE
Using yarn on Windows leaves terminal font in bold/bright mode

### ISSUE THREAD

**Issue by jesseschalken** [yarnpkg/yarn#4775]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Usage of Yarn on Windows, either via `cmd.exe` or PowerShell leaves the terminal font in a "bright/bold" mode.

![image](https://user-images.githubusercontent.com/1559204/31978056-52263452-b98b-11e7-9742-68944aebb8a9.png)

![image](https://user-images.githubusercontent.com/1559204/31978090-735034b6-b98b-11e7-8e22-294c92679fa1.png)

![image](https://user-images.githubusercontent.com/1559204/31978153-b47c182e-b98b-11e7-9bb9-2ab00e7655db.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Install yarn globally with `npm install -g yarn@latest`. Then run any `yarn` command on a `cmd.exe` or PowerShell command prompt.

**What is the expected behavior?**

Terminal font is returned the "normal" state after the command finishes.

**Please mention your node.js, yarn and operating system version.**

Node.js: 8.7.0
NPM: 5.4.2
Yarn: 1.2.1
Operating System: Windows 10 10.0.15063 Build 15063

**Comment by roger2hk** [comment]
Possibly related to #2724

**Comment by jesseschalken** [comment]
Can confirm this is fixed in the Windows 10 Fall Creators Update (see https://github.com/Microsoft/WSL/issues/2174#issuecomment-308570925)

![image](https://user-images.githubusercontent.com/1559204/34191307-1e8d5342-e59a-11e7-84bb-ac75aca0f497.png)
