### ISSUE TITLE
Defining multiple registries and proxies

### ISSUE THREAD

**Issue by aimad-majdou** [yarnpkg/yarn#4777]
I want to migrate from using bower to yarn, the bower dependencies are installed from the bower registry, and npm modules are installed in our private registry, when I moved to Yarn I defined the bower dependencies inside `dependencies`  and the npm modules inside 'devDependencies', so I need to install the dependencies using the npm registry, and the devDependencies using our private registry.

Another issue I faced, is that in bower the dependencies were installed using a proxy, but when defining this proxy to yarn, it fails to get dev dependencies in our private registry.

How can I solve this ?

**Please mention your node.js, yarn and operating system version.**

'yarn/1.2.1 npm/? node/v8.2.1 win32 x64'

**Comment by pauldraper** [comment]
Duplicate of #547
