### ISSUE TITLE
Gatsby build fails with lastest version of yarn, but succeeds with old yarn or npm

### ISSUE THREAD

**Issue by ybbarng** [yarnpkg/yarn#4799]
Hello, I am afraid to contribute to create a flood of bug reports.
I have some errors on building [gatsby](https://www.gatsbyjs.org/), an static site generator, but I have to suspect yarn because the build succeeds with npm, but not with yarn. [An issue thread of gatsby-starter-lumen](https://github.com/alxshelepenok/gatsby-starter-lumen/issues/41) says that old version of yarn also worked, but latest version fails. Therefore I decided to write this issue in here, to get rid of the bug from something, from yarn or other packages.

Because npm is working well but yarn is not, I uploaded the packages lists of both that they installed in [here](https://github.com/ybbarng/netlify-test/tree/build-bug/package_list). I can't compare those becuase their structures are very different, but I hope it will help figure out the bug.

Thank you for reading my report.

**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**
gatsby build fails when using latest yarn, but succeeds when using old version of yarn or npm.
[gatsby-starter-lumen #41](https://github.com/alxshelepenok/gatsby-starter-lumen/issues/41) says that it succeeds with old version of yarn.

When I run gatsby build, I got two errors:
The first one: `node_modules/url/url.js?{"limit":10000,"name":"static/[name].[hash:8].[ext]"} didn't return a function`
The second one: `Error: Cannot find module "../../pages/photo.jpg"`

I thought the first error was raised because of the latter one, so I checked the second one.
The error was from [this import](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/components/Sidebar/index.jsx#L7) in `src/components/Sidebar/index.jsx` and [the photo.jpg is exist in right place](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/pages/photo.jpg), `src/pages/photo.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**

I created the repository, [ybbarng/netlify-test and branch: build-bug](https://github.com/ybbarng/netlify-test/tree/build-bug)

1. Checkout that repository with branch: build-bug
`git clone -b build-bug https://github.com/ybbarng/netlify-test.git`

2. Move to the directory
`cd netlify-test`

3.  Install the dependencies with yarn
`yarn install`

4. Build the project
`yarn build`
--> TypeError will be occurred. Because of [this bug on gatsbyjs](https://github.com/gatsbyjs/gatsby/issues/2501).

5. Remove the dependencies
`rm -rf node_modules`

6. Install the dependencies with npm
`npm install`

7. Build the project
`yarn build`
--> success

**What is the expected behavior?**
The build have to be succeeded with something like this output:
```
yarn run v1.2.1
$ gatsby build
success delete html files from previous builds — 0.139 s
success open and validate gatsby-config.js — 0.010 s
success copy gatsby files — 0.066 s
success onPreBootstrap — 0.018 s
success source and transform nodes — 0.428 s
success building schema — 1.109 s
success createLayouts — 0.014 s
success createPages — 0.150 s
success createPagesStatefully — 0.043 s
success onPreExtractQueries — 0.003 s
success extract queries from components — 0.524 s
success run graphql queries — 0.236 s
success write out page data — 0.010 s
success write out redirect data — 0.001 s
success update schema — 0.425 s
success onPostBootstrap — 0.003 s

info bootstrap finished - 9.364 s

success Building CSS — 14.497 s
success Building production JavaScript bundles — 23.516 s
success Building static HTML for pages — 7.810 s
Total precache size is about 767 kB for 5 resources.
info Done building in 55.288 sec
```

**Please mention your node.js, yarn and operating system version.**
* OS: Ubuntu 16.04 32 bit
* node.js: v8.8.1
* yarn: 1.2.1
* npm: 5.5.1

The build of same code with yarn version 0.18.1 on [netlify](https://www.netlify.com/) is succeeded.

**Comment by ybbarng** [comment]
When `url-loader` package is added, the bug has gone.

**Comment by BYK** [comment]
Did you get any warnings or errors during `yarn install`. Also we'd need a `package.json` file at the very least to be able to investigate the issue.

**Comment by ybbarng** [comment]
Hello, you can check the [package.json from here](https://github.com/ybbarng/netlify-test/blob/build-bug/package.json).
The output of `yarn install` is following:
```
yarn install v1.2.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning "sass-loader@4.1.1" has unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
warning "react-helmet@5.2.0" has unmet peer dependency "react@>=15.0.0".
[4/4] Building fresh packages...
Done in 88.59s.
```

**Comment by rally25rs** [comment]
Closing this issue because the linked issue has been closed from gatsbyjs, so I think this is fixed now, or was not a Yarn bug.
