### ISSUE TITLE
root binaries not installed

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/yarn#4801]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
I have a project which uses workspaces, on the root package.json I have some `devDependencies` such as `lerna`.

When I run `yarn install`, I correctly see the `.bin` folder created in `packages/**/node_modules/.bin` for the binaries needed by the sub-packages. But on the root `/node_modules` I can't find any `.bin` folder (which should contain `lerna`).

This worked fine with 1.0.1 but doesn't with latest version

**If the current behavior is a bug, please provide the steps to reproduce.**

Just create a `package.json` with `lerna` as `devDependencies` and workspaces enabled. Then create a sub-package with in its `package.json` a dependency such as `flow-bin`.

Run `yarn install` and you should see `flow` in `packages/sub-pkg/node_modules/.bin`, but nothing in `/node_modules/.bin`

**What is the expected behavior?**
I would expect the binaries of the root package to be available.

**Please mention your node.js, yarn and operating system version.**
```
❯ node -v
v8.4.0
❯ yarn -v
1.2.1
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13
BuildVersion:   17A405
```

**Comment by rally25rs** [comment]
Just ran into the same issue in v1.2.1.

The `lerna` bin specified in the root package.json ends up being created in all the sub-repos `packages/pkg1/node_modules/.bin/lerna`

**Comment by FezVrasta** [comment]
I just found out the problem is the `lerna bootstrap` hook I had on `postinstall` 🙄
