### ISSUE TITLE
registry.yarnpkg.com has bad cache of react-is-deprecated-0.1.2.tgz

### ISSUE THREAD

**Issue by alanhogan** [yarnpkg/yarn#4807]
**Do you want to request a *feature* or report a *bug*?**
Bug! 🐞 

**What is the current behavior?**
https://registry.yarnpkg.com/react-is-deprecated-0.1.2.tgz returns a cached 404 page from npmjs.org instead of a the `tgz` file. Notably that file used to exist (?) as it is in our dependencies and it should still exist as that is still a valid release of that package.

**If the current behavior is a bug, please provide the steps to reproduce.**
Without yarn's offline cache(s), install react-is-deprecated@0.1.2, or just visit the URL https://registry.yarnpkg.com/react-is-deprecated-0.1.2.tgz

**What is the expected behavior?**
It should return a valid package archive

**Please mention your node.js, yarn and operating system version.**
Node 8.0.0, Yarn 1.20, MacOS Sierra

**Note Also**
This has been happening for at least a week

**Comment by BYK** [comment]
I don't think this is a bug. https://registry.npmjs.org/react-is-deprecated-0.1.2.tgz also returns a 404 and that URL looks broken to me anyway. The package seems to be there so somehow you got an invalid resolution URL: https://yarnpkg.com/en/package/react-is-deprecated
