### ISSUE TITLE
yarn website seems to be not updated

### ISSUE THREAD

**Issue by killanaca** [yarnpkg/yarn#4821]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
According to the website https://yarnpkg.com/en/package/asn1.js there is a 4.10.0 version for asn1.js package but if I try to install it with
`yarn add asn1.js@4.10.0`
I get 
```
-mbp:~-$ yarn add asn1.js@4.10.0
yarn add v1.2.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "asn1.js" that matches "4.10.0"
? Please choose a version of "asn1.js" from this list: (Use arrow keys)
❯ 5.0.0
  4.9.2
  4.9.1
  4.9.0
```
**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add asn1.js@4.10.0`

**What is the expected behavior?**
to install the specific version

**Please mention your node.js, yarn and operating system version.**
yarn 1.2.1
node 8.5.0

<img width="387" alt="screen shot 2017-11-01 at 16 10 45" src="https://user-images.githubusercontent.com/157641/32284692-ef3c63b2-bf1f-11e7-99b5-e0177fcfacfe.png">

**Comment by BYK** [comment]
I think 4.10.0 is pulled back or something since https://registry.npmjs.org/asn1.js does not list that version there.

**Comment by jiripudil** [comment]
@BYK I guess you can close this, 4.10.0 was indeed "unpublished": indutny/asn1.js#95
