### ISSUE TITLE
yarn check does not respect resolutions

### ISSUE THREAD

**Issue by dreyks** [yarnpkg/yarn#4825]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Issue: `backbone.marionette@1.8.8` states `backbone@1.0.0 - 1.1.2` as its dependency, but I need it to work with `backbone@1.2.3` and it actually **does** work with no issues, so yarn's v1.0 `resolutions` was a life-saver for me.
However `yarn check` still complains `error "backbone.marionette#backbone@1.0.0 - 1.1.2" doesn't satisfy found match of "backbone@1.2.3"`

The `package.json` is as follows
```json
{
  "dependencies": {
    "backbone": "1.2.3",
    "backbone.marionette": "1.8.8"
  },
  "resolutions": {
    "backbone": "1.2.3"
  }
}
```
**What is the expected behavior?**
`yarn check` does not complain about that mismatch, cause it's stated in `resolutions` field

**Please mention your node.js, yarn and operating system version.**
 - yarn 1.2.1
 - node 6.11.2
 - MacOS

**Comment by kaylieEB** [comment]
Hi @dreyks I believe it's actually doing the correct thing per the [selective resolution rfc ](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md#relation-to-the-check-command)

> If you force a version that does not match semver requirements of a package, --verify-tree would throw an error.

You're overriding the nested dependency of `backbone.marionette` outside of its stated range, so it should warn.

**Comment by dreyks** [comment]
But I don't use `--verify-tree`. Should it still be an error then, or should it just warn?

**Comment by kaylieEB** [comment]
I'd say it still should throw a warning because from `yarn check`'s standpoint, it is technically the incorrect resolution

**Comment by dreyks** [comment]
I'm OK with warning but it throws an error

**Comment by kaylieEB** [comment]
Ah I see--yeah it'd be a good addition to change to `warn` if it turns out to be a resolution. Would you like to try submitting a PR? The code is here https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/check.js#L339

**Comment by tvald** [comment]
I would expect default behavior to be that `yarn check` after `yarn install` doesn't error, but I could easily be misunderstanding the command due to lack of documentaiton.

**Comment by dreyks** [comment]
#4835
