### ISSUE TITLE
Unable to install yarn 1.3.0 for Windows from website 

### ISSUE THREAD

**Issue by abenhamdine** [yarnpkg/yarn#4830]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
No windows msi available for yarn 1.3.0 on www.yarn https://yarnpkg.com/en/docs/install
`choco install yarn` also install yarn 1.2.1 instead of yarn 1.3.0

**If the current behavior is a bug, please provide the steps to reproduce.**
Go on https://yarnpkg.com/en/docs/install and click on button "Download installer"
or do `choco install yarn`

**What is the expected behavior?**
Install yarn 1.3.0 with msi file or choco

**Please mention your node.js, yarn and operating system version.**
Windows 10 64 bits
Nodejs 9.0

**Comment by jaromanda** [comment]
Have you tried here https://yarnpkg.com/en/docs/nightly since 1.3.0 doesn't seem to be "release" yet

**Comment by Daniel15** [comment]
This seems okay now. I think there were some build issues.
