### ISSUE TITLE
yarn add should refuse to run with --frozen-lockfile

### ISSUE THREAD

**Issue by hach-que** [yarnpkg/yarn#4836]
**Do you want to request a *feature* or report a *bug*?**
feature?

**What is the current behavior?**
`--frozen-lockfile true` in `.yarnrc`, `yarn add` runs successfully but doesn't update the lockfile, which leads to unexpectedly broken builds.

**What is the expected behavior?**
When you run just `yarn` with `--frozen-lockfile true` to restore packages, it correctly errors out with:

```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

Any operations like `yarn add` or `yarn rm` that would also result in the lockfile changing should also be blocked.

We have `--frozen-lockfile` in the `.yarnrc` file in our repository so that our build servers won't automatically upgrade packages when permitted by version strings. However, the current behaviour means that developers can successfully do `yarn add <somepkg>` on their local machine, everything will run fine locally, and then the frozen lockfile will only fail on the build server. We really want this to be caught on the developers side so they can correctly run `yarn add --update-lockfile <somepkg>` so the lockfile will be updated correctly (if `--update-lockfile` was an option that'd be great, at the moment we have to move `.yarnrc` out of the way first).

**Please mention your node.js, yarn and operating system version.**
yarn: 1.2.1
node: v6.3.0
os: windows 10

**Comment by paul-soporan** [comment]
Closing as v2 only allows `--immutable` (formerly `--frozen-lockfile`) to be used with the `yarn install` command.

https://yarnpkg.com/getting-started/migration
