### ISSUE TITLE
Support for node 9

### ISSUE THREAD

**Issue by pantharshit00** [yarnpkg/yarn#4837]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn throws a warning about node 9.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Install node 9.
Every command you run will have this
Screenshot: https://imgur.com/a/KdQIg

**What is the expected behaviour?**
Yarn should have released support for node 9. Nothing breaks except I have to rebuild some modules but warning should not be there. Node 8 has been now in LTS channel (version 8.9.0) and node 9 adds a new error handling system. Might benefit yarn.

**Please mention your node.js, yarn and operating system version.**
node: 9.0.0
yarn: 1.2.1
OS: Ubuntu 17.10

**Comment by csvan** [comment]
This was fixed in 1.3

**Comment by pantharshit00** [comment]
OK great but you should have added this in release notes of 1.3 in the releases sections. I saw the release notes of 1.3 and I didn't find that node 9 support was added.

**Comment by arcanis** [comment]
We always support new Node releases by default, it's just that our check was a bit too restrictive in this particular case.

**Comment by BYK** [comment]
@pantharshit00 sorry for missing it in the release notes. It is now added. Also 1.3.2 is up and available for download.

**Comment by pantharshit00** [comment]
@BYK thanks for that.

**Comment by yannickl** [comment]
Just for information, the https://yarnpkg.com/lang/en/ does not mention the node v9 support. This is not critical, but you should update the main page.

**Comment by yagudaev** [comment]
getting the warning form yarn about `node v9.0` as well on `yarn v1.3.2`

**Comment by FezVrasta** [comment]
You should update the website
![image](https://user-images.githubusercontent.com/5382443/33795008-96d94cf0-dcd7-11e7-9720-8a83025ddcf1.png)

**Comment by alex-shamshurin** [comment]
Please reopen this issue or CHANGE the header please!

**Comment by arcanis** [comment]
Regarding the website, @yarnpkg/website#784 is up. Regarding Yarn itself, the 1.5 branch which has been released last week won't have the warning referenced in this issue.
