### ISSUE TITLE
Support for globs

### ISSUE THREAD

**Issue by aikar** [yarnpkg/yarn#4838]
**Do you want to request a *feature* or report a *bug*?**
Feature: When using yarn commands that operate on your existing packages (remove, upgrade, ls, etc), glob patterns should be supported, such as:

`yarn upgrade -L -C 'babel-plugin-*'`

This would help when trying to update many packages (but don't want to EVERY package you have)

**Comment by kaylieEB** [comment]
Closed via https://github.com/yarnpkg/yarn/pull/4610
