### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by ide** [yarnpkg/yarn#484]
I was thinking it'd be good to track performance of yarn, mainly to catch any egregious performance regressions and also to notice accumulated regressions over a period of time. This could be as part of CI or nightly, the main idea is to be aware of performance trends.

**Comment by paul-soporan** [comment]
Hello from the future, Yarn now runs [automated benchmarks](https://p.datadoghq.eu/sb/d2wdprp9uki7gfks-c562c42f4dfd0ade4885690fa719c818?from_ts=1609446279466&live=true&theme=dark&to_ts=1609619079466&tv_mode=false) which include all major package managers.
