### ISSUE TITLE
Yarn config to always use offline-mirror

### ISSUE THREAD

**Issue by sagar12861** [yarnpkg/yarn#4859]
**Feature request**
Need a way to force yarn to use only offline-mirror. I should use "yarn install --offline"

I want to set that in a configuration preferably in .yarnrc so doing "yarn install" will behave as same as "yarn install --offline".

Node v6.x
yarn 1.2.1

**Comment by BYK** [comment]
Sorry @sagar12861 but we try to keep the issues section purely focused on bug reports and feature requests with some technical discussion. Please use our online documentation, StackOverflow or our [Discord community](https://discord.gg/yarnpkg) #support channel for help requests like this.

**Comment by sagar12861** [comment]
But actually this is a feature request.

**Comment by BYK** [comment]
If you look carefully you'll see that this is an existing feature 😉

**Comment by sagar12861** [comment]
I'm apologize. that is what I referred [https://yarnpkg.com/en/docs/yarnrc](url)
Could you let me know the configuration that I can set in `.yarnrc` to make `yarn install` works offline by default ?

**Comment by rally25rs** [comment]
https://yarnpkg.com/en/docs/yarnrc#toc-cli-arguments

adding this to .yarnrc should do what you want:

```
--install.offline true
```
