### ISSUE TITLE
ci(circle): Move Regular Debian e2e install tests to CircleCI

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#4863]
@Daniel15 reported this on #4857:

>I wonder if we can eventually move the nightly E2E tests onto CircleCI too. Currently I'm running them on my own server: https://build.dan.cx/job/yarn-e2e/. Basically it installs the Yarn Debian package on fresh Ubuntu 12.04, 14.04 and 16.04 Docker images then installs a package, to ensure that the full out-of-the-box flow works fine on a fresh machine.

>The tricky part is having a Debian repo (the current E2E tests use the nightly repo) but I guess the build could use Aptly or reprepro to create a temporary repository only containing the latest build artifacts, and restore it from cache in all the E2E test jobs.

https://circleci.com/docs/2.0/configuration-reference/#schedule looks like the right thing for us.

**Comment by felicianotech** [comment]
Scheduled Workflows is new at CircleCI and should work well in this scenario. Let me know if you run into any issues or have any questions.

**Comment by Daniel15** [comment]
Oh cool, scheduled workflows look perfect for this! We could just use the nightly repo in that case (http://nightly.yarnpkg.com/debian/), exact same as what we're currently doing.

The current one is just a Jenkins matrix job: https://github.com/yarnpkg/yarn/blob/master/jenkins_jobs.groovy
```groovy
matrixJob('yarn-e2e') {
  displayName 'Yarn End To End'
  description 'Nightly end-to-end tests for Yarn'
  scm {
    github 'yarnpkg/yarn', 'master'
  }
  triggers {
    cron '@midnight'
  }
  axes {
    text 'os', 'ubuntu-16.04', 'ubuntu-14.04', 'ubuntu-12.04'
    label 'label', 'docker' // Only run on build hosts that have Docker
  }
  steps {
    // 192.168.122.1:3142 is apt-cacher-ng on the Docker host
    shell '''
      cd end_to_end_tests
      APT_PROXY=192.168.122.1:3142 ./test-$os.sh
    '''
  }
  publishers {
    gitHubIssueNotifier {
    }
  }
}
```

**Comment by BYK** [comment]
@Daniel15 would you like to give this a shot or are you short on time?

**Comment by Daniel15** [comment]
I'm always short on time 😞  I'd be happy to review a PR for this. Maybe I could work on it but it wouldn't be for a while.
