### ISSUE TITLE
ETIMEDOUT on yarn 1.3.2 behind HTTP proxy

### ISSUE THREAD

**Issue by zicklag** [yarnpkg/yarn#4877]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Running `yarn global add` results in an error:

```
yarn global v1.3.2
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/stylus: ETIMEDOUT".
```

I am also behind an http proxy that requires authentication. I suspect that this is related to the issue. I have my proxy urls for HTTP and HTTPS in environment variables like this: `http_proxy=http://user:password@server:port`. I didn't have any problems when using yarn 1.2.1. This only happened after upgrading to yarn 1.3.2. I also tried to use the commandline options for proxy settings, but the result was the same.

**yarn-error.log**
```
Arguments:
  /home/zicklag/.nvm/versions/node/v8.4.0/bin/node /home/zicklag/.yarn/bin/yarn.js global add stylus

PATH:
  /home/zicklag/.nvm/versions/node/v8.4.0/bin:/home/zicklag/.yarn/bin:/home/zicklag/.gem/ruby/2.3.0/bin:/home/zicklag/.yarn/bin:/home/zicklag/.yarn/bin:/home/zicklag/.gem/ruby/2.3.0/bin:/home/zicklag/.yarn/bin:/home/zicklag/.gem/ruby/2.3.0/bin:/home/zicklag/.yarn/bin:/home/zicklag/.gem/ruby/2.3.0/bin:/home/zicklag/bin:/home/zicklag/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version:
  1.3.2

Node version:
  8.4.0

Platform:
  linux x64

npm manifest:
  No manifest

yarn manifest:
  No manifest

Lockfile:
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

Trace:
  Error: https://registry.yarnpkg.com/stylus: ETIMEDOUT
      at Timeout._onTimeout (/home/zicklag/.yarn/lib/cli.js:123749:19)
      at ontimeout (timers.js:469:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:264:5)
```

**Please mention your node.js, yarn and operating system version.**
node: v8.4.0
yarn: 1.3.2
OS: Ubuntu 16.04

**Comment by torifat** [comment]
> I suspect that this is related to the issue.
Which Issue? Can you please link it?

Is it only happening for `global` command?

**Comment by SaschaDens** [comment]
I have a similar problem after the upgrade towards v1.3.2.
```
Trace:
  Error: https://github.com/paulirish/lighthouse: ETIMEDOUT
      at Timeout._onTimeout (/srv/yarn-1.3.2/bin/yarn:122417:19)
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)
```

Seems like the server environment variables are ignored. I was able to solve this by setting the proxy in NPM with the following command. (https://docs.npmjs.com/misc/config#https-proxy)
```
npm config set https-proxy <proxy>
```

**Comment by torifat** [comment]
Fixed in #4849

**Comment by vcfvct** [comment]
These type of issue is quite annoying. It breaks our Circle CI. have to go back to NPM for now. 
As a widely used package manager, hopefully `yarn` can be more stable in future to get more popular.

**Comment by silverwind** [comment]
The workaround in https://github.com/yarnpkg/yarn/issues/4877#issuecomment-342794413 surprisingly worked for me too. I wouldn't have expected that yarn parses npm's config file.

Would a patch release that includes https://github.com/yarnpkg/yarn/commit/91253c8881fb49abeded4feda92c602ba629f64a be possible? I think this is a pretty serious issue.

**Comment by davidkarlsen** [comment]
How to handle NO_PROXY? yarn does not seem to honor that?

**Comment by El-Mahbub** [comment]
I have a similiar issue with error : connect ETIMEDOUT 151.101.8.162:80

**Comment by maxliesegang** [comment]
> How to handle NO_PROXY? yarn does not seem to honor that?

We were able to get around this issue by using environment variables instead of the config file. We did that with the help of cross-env:
"install:local": "cross-env https_proxy=$yourProxy no_proxy=$domainA,$domainB yarn install"

But with this workaround you are not allowed to define a proxy in the config file, since then the no_proxy entry will be ignored.
