### ISSUE TITLE
Packages with code in docs directory do not get installed properly

### ISSUE THREAD

**Issue by edoloughlin** [yarnpkg/yarn#4882]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Package docs directory is not installed.
[mathjs ](https://github.com/josdejong/mathjs)has code in a docs directory that it requires at runtime. Yarn does not install this directory. 

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn install mathjs` and `npm install mathjs` in another directory. NPM installs the docs directory in node_modules/mathjs/docs. Yarn does not.

**What is the expected behavior?**
The docs directory is installed

**Please mention your node.js, yarn and operating system version.**
Node 6, Yarn 1.3.2, Windows 7.

**Comment by rally25rs** [comment]
Unable to reproduce:

```
$ yarn add mathjs
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "grunt-ui-tasks > proxyquireify@3.2.1" has unmet peer dependency "browserify@>=5.1.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 8 new dependencies.
├─ complex.js@2.0.4
├─ decimal.js@7.2.3
├─ fraction.js@4.0.2
├─ javascript-natural-sort@0.7.1
├─ mathjs@3.16.5
├─ seed-random@2.2.0
├─ tiny-emitter@2.0.0
└─ typed-function@0.10.5
✨  Done in 7.34s.

$ ls node_modules/mathjs/docs/
chaining.md               core                      datatypes                 extension.md              reference
command_line_interface.md core.md                   expressions               getting_started.md        serialization.md
configuration.md          custom_bundling.md        expressions.md            index.md
```

Do you have a` .yarnclean` file in your project, or a script that runs `yarn clean`? The `clean` would by default delete `docs` directory, if that command is being run by something.

**Comment by edoloughlin** [comment]
Hi, yes - there's an autoclean and it has a 'docs' line! I guess mathjs should probably not have code in the docs directory.

**Comment by josdejong** [comment]
>  I guess mathjs should probably not have code in the docs directory.

Just for clarity: there is no code in the `./docs` folder of mathjs, just markdown files. 

@edoloughlin I see no reason not to use a folder like `docs`. yarn autoclean "Cleans and removes unnecessary files from package dependencies". The docs folder _is_ "unnecessary": not needed to keep the library functioning, so it does exactly what you ask for :D.

**Comment by odGit** [comment]
@joaolucasl it is  referred  here https://github.com/josdejong/mathjs/blob/master/lib/expression/function/help.js#L6 within mathjs

**Comment by odGit** [comment]
Removing _docs_ from `.yarnclean`  and installing `mathjs` again solves the problem.
