### ISSUE TITLE
Yarn 1.3.2 incorrectly bypasses HTTP(S)_PROXY

### ISSUE THREAD

**Issue by idoru** [yarnpkg/yarn#4885]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**

1. Set HTTP_PROXY and HTTPS_PROXY environment variables to a valid proxy
2. `yarn install` attempts to access yarnpkg.com on port 443, ignoring the proxy settings

**What is the expected behavior?**

1. Yarn instead makes HTTPS requests via the proxy set in the HTTPS_PROXY environment variable. Yarn 1.2.1 does this correctly.

**Please mention your node.js, yarn and operating system version.**

Node 4.8.5
Yarn 1.3.2
Ubuntu 16.04.1

**Comment by rally25rs** [comment]
Confirmed. My fault. I broke it in a previous PR fixing something else. I thought Yarn picked up that env var and would forward it to the underlying HTTP library, but apparently it does not.

Working on it now...

**Comment by chadlwilson** [comment]
Thanks for looking at this @rally25rs - I guess your fix in #4903 makes #4849 redundant?

**Comment by paolomainardi** [comment]
Hi, are there any updates here ?

**Comment by BYK** [comment]
@paolomainardi this patch is merged so with the next release it will be available.

If you need it right now, you can use the nightly builds.

**Comment by paolomainardi** [comment]
ok thanks @BYK
