### ISSUE TITLE
Chalk pkg 1.1.3 cannot be downloaded from Heroku

### ISSUE THREAD

**Issue by lukeasrodgers** [yarnpkg/yarn#4889]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

version 1.1.3 of the chalk package (https://yarnpkg.com/en/package/chalk) is unavailable when requested from Heroku.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. get a heroku instance (somehow, sorry I can't help with this step)
2. `curl -I https://registry.yarnpkg.com/chalk/-/chalk-1.1.3.tgz`
3. request hangs for a minute or so, then cloudflare returns a 524 origin timeout

```
HTTP/1.1 524 Origin Time-out
Date: Wed, 08 Nov 2017 18:46:59 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d585f8b0fdae9d517983c30e05a4757ae1510166719; expires=Thu, 08-Nov-18 18:45:19 GMT; path=/; domain=.yarnpkg.com; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Server: cloudflare-nginx
CF-RAY: 3baab04e5ae995b0-IAD
```

**What is the expected behavior?**

From everywhere *but* heroku, this works fine. I have tried from my own machine, as well as two different VPS. Furthermore, requesting any different version of the package on the same Heroku machine works fine.

```
curl -I https://registry.yarnpkg.com/chalk/-/chalk-1.1.3.tgz
HTTP/1.1 200 OK
Date: Wed, 08 Nov 2017 18:59:23 GMT
Content-Type: application/octet-stream
Content-Length: 5236
Connection: keep-alive
Set-Cookie: __cfduid=d439d42b9c21105054da37e9ff8c635eb1510167563; expires=Thu, 08-Nov-18 18:59:23 GMT; path=/; domain=.yarnpkg.com; HttpOnly
Last-Modified: Tue, 29 Mar 2016 00:16:44 GMT
ETag: "56f9c96c-1474"
Expires: Thu, 09 Nov 2017 00:59:23 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Accept-Ranges: bytes
Cache-Control: max-age=432000
Accept-Ranges: bytes
Via: 1.1 varnish
X-Served-By: cache-jfk8130-JFK
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1510167564.561435,VS0,VE350
Server: cloudflare-nginx
CF-RAY: 3baac4e8391d91c4-EWR
```

**Please mention your node.js, yarn and operating system version.**

I don't believe these are relevant, but FWIW OS is Ubuntu 16.04.3 LTS.

**Comment by portenez** [comment]
It happens from my local machine as well. I don't think it's only heroku.
curl -I https://registry.yarnpkg.com/chalk/-/chalk-1.1.3.tgz

it never responds. Eventually times out.

**Comment by jprince** [comment]
We're seeing this same error in our circle ci docker builds

**Comment by timwhit** [comment]
I'm seeing the same issue on Bitbucket Pipelines. Works for me locally though.

**Comment by gabroe** [comment]
I'm getting the same

**Comment by DoWhileGeek** [comment]
I'm seeing the same thing on shippable.

**Comment by paulomcnally** [comment]
```
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v0.28.4
remote:        warning package.json: No license field
remote:        warning No license field
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        warning There appears to be trouble with your network connection. Retrying...
remote:        warning There appears to be trouble with your network connection. Retrying...
remote:        warning There appears to be trouble with your network connection. Retrying...
remote:        warning There appears to be trouble with your network connection. Retrying...
remote:        error An unexpected error occurred: "https://registry.yarnpkg.com/chalk/-/chalk-1.1.3.tgz: ESOCKETTIMEDOUT".
remote:        info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_7e497323dc8309328742bbfe7779d8a1/yarn-error.log".
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by arkangle** [comment]
Also, happening on aws, but works locally.

**Comment by recurrence** [comment]
I can curl the endpoint now.  Appears resolved?

**Comment by trriplejay** [comment]
seems like having the request originate from an aws instance might be a common thread among most of these comments. 524 was returned from cloudflare according to OP.

looks like cloudflare had an outage that is resolved now:
https://www.cloudflarestatus.com/

**Comment by DoWhileGeek** [comment]
just retried a build and succeeded. thanks for the closure @trriplejay!

**Comment by arkangle** [comment]
All good here, too
