### ISSUE TITLE
Proxy should be configureable with the standard environment variables

### ISSUE THREAD

**Issue by c33s** [yarnpkg/yarn#4894]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
environment variables are ignored (not the config file from npm or yarn)

**If the current behavior is a bug, please provide the steps to reproduce.**
```
rm ~/.yarnrc
rm ~/.npmrc
export HTTPS_PROXY=http://proxy.example.at:1080
export HTTP_PROXY=http://proxy.example.at:1080
yarn add bootstrap
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/bootstrap: connect EACCES 104.16.60.173:443".
```

**What is the expected behavior?**
auto using the proxy

**Please mention your node.js, yarn and operating system version.**
```
yarn --version
1.3.2
node --version
v8.9.1
windows7x64
```
setting the proxies like this work for many programs like `curl` and `wget` on linux and on windows out of the box.
```
export HTTPS_PROXY=http://proxy.example.at:1080
export HTTP_PROXY=http://proxy.example.at:1080
```
why set something in a config file, which is already set in an widely used environment variable?

related to: #3034

**Comment by torifat** [comment]
Fixed in #4849
