### ISSUE TITLE
npm resolves to the wrong version of a dep due to the node_modules structure

### ISSUE THREAD

**Issue by tomchentw** [yarnpkg/yarn#4897]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When install `imagemin-cli@3.0.0` in the same repo, it has `get-stdin` as a shared dependency but with different versions. One is `@4.0.1` and one is `@5.0.1`.

However, due to the nature of [imagemin-cli][imagemin-cli], when it was run it'll use the `get-stdin@4.0.1` instead of its dependent one `get-stdin@5.0.1` due to **the node_modules structure**. See below for the result of `yarn list --pattern get-stdin`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
yarn add react-scripts@1.0.14
yarn add imagemin-cli@3.0.0
yarn list --pattern get-stdin
# --- And you should see this: ---
# yarn list v1.3.2
# ├─ get-stdin@4.0.1
# └─ imagemin-cli@3.0.0
#    └─ get-stdin@5.0.1
# ✨  Done in 0.74s.
# ---
# yarn why get-stdin
# info Has been hoisted to "get-stdin"
# info Reasons this module exists
#    - "imagemin-cli#meow#redent#strip-indent" depends on it
#    - "imagemin-cli#imagemin-gifsicle#gifsicle#logalot#squeak#lpad-align" depends on it
```

I also put in here:
https://github.com/tomchentw/yarn-dependencies-versions

**What is the expected behavior?**

**I'm not sure**. Either:

```sh
yarn list --pattern get-stdin
# --- And you should see this: ---
# yarn list v1.3.2
# ├─ ……somewhere-down-the-tree of react-scripts……
# │ └─ get-stdin@4.0.1
# └─ imagemin-cli@3.0.0
#    └─ get-stdin@5.0.1
# ✨  Done in 0.74s.
```

Or, should this be fixed by `imagemin-cli` because their `bin` file is single file at the top level of the repo? See:
https://github.com/imagemin/imagemin-cli/blob/v3.0.0/cli.js

**Please mention your node.js, yarn and operating system version.**

* macOS 10.12.6
* xcode-select version 2347. Xcode 9.1
* Homebrew 1.3.6
* node: v8.9.0
* npm: 5.5.1
* yarn: 1.3.2

[imagemin-cli]: https://github.com/imagemin/imagemin-cli/blob/v3.0.0/cli.js

**Comment by BYK** [comment]
I think this is an issue with `imagemin-cli` since the folder structure is correct. If `.bin/imagemin-cli` defers to `cli.js` which is _inside_ the actual `imagemin-cli` directory, node would load the correct dependency per its resolution algorithm.

**Comment by tomchentw** [comment]
Thanks for clarifying this. I'll report there then.
