### ISSUE TITLE
Unable to use yarn create inside workspace repo

### ISSUE THREAD

**Issue by kristinn93** [yarnpkg/yarn#4906]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
Unable to run `yarn create react-app` inside workspaces.
I get the following error: 
```javascript
Aborting installation.
Unexpected error. Please report it as a bug:
{ Error: Cannot find module '/Users/repo/packages/test/node_modules/react-scripts/package.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at checkNodeVersion (/usr/local/lib/node_modules/create-react-app/createReactApp.js:488:23)
    at getPackageName.then.then.then.packageName (/usr/local/lib/node_modules/create-react-app/createReactApp.js:295:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new repo with yarn workspaces
2. Go to the packages folder and run `yarn create react-app test`

**What is the expected behavior?** Should be able to use create-react-app inside workspace to bootstrap a new webproject

**Please mention your node.js, yarn and operating system version.**
node: v8.9.0
yarn: 1.3.2
macOS High Sierra 
Version 10.13.1 (17B48)

**Comment by iansu** [comment]
Does `yarn create` work for you with any other packages? I'm just wondering if this is a Yarn bug or a Create React App bug.

**Comment by kristinn93** [comment]
@iansu This seems to be a [create-react-app](https://github.com/facebook/create-react-app) bug, this worked fine with [create-vue-app](https://github.com/vue-land/create-vue-app)

**Comment by iansu** [comment]
That's what I was afraid of. Can you create a new issue in Create React App so we can look into it?

**Comment by kristinn93** [comment]
Found the same issue there, I'll close this one 👍 

facebook/create-react-app#3031
facebook/create-react-app#3405
