### ISSUE TITLE
FEATURE: workspaces: upgrade all package.json files?

### ISSUE THREAD

**Issue by richburdon** [yarnpkg/yarn#4916]
FEATURE REQUEST.

It would be really nice to have a way to upgrade dependencies and the corresponding package.json files across sub modules.

**Comment by milesj** [comment]
`yarn upgrade-interactive --latest` should do just this.

**Comment by richburdon** [comment]
It doesn't do this for workspaces (ie sub packages in a monorepo).

**Comment by milesj** [comment]
It does. Here's an example commit where I've done it. https://github.com/milesj/interweave/commit/202ab7d349c629912bdb0ab8ec7ccfedb1f0e7e4

Are your workspaces configured correctly?

**Comment by richburdon** [comment]
I must have changed something, because it's now working. Thanks much for the example.

**Comment by Diokuz** [comment]
Have the same issue, `yarn upgrade-interactive --latest` not work for me – only updates dependencies, not crossdeps.

yarn --version === 1.12.3

**Comment by Diokuz** [comment]
@milesj like this https://github.com/yarnpkg/yarn/issues/6809

**Comment by milesj** [comment]
@Diokuz I wouldn't expect that to happen. That's what Lerna is for.

**Comment by Diokuz** [comment]
@milesj we dont use lerna for some reasons.

So, the only way to do that – is to do that manually?
Is that consistent with `yarn upgrade` behavior, which upgrades all versions, except internal packages versions?

**Comment by milesj** [comment]
I'm almost positive `yarn upgrade` (and variants) just update NPM dependencies, not cross package dependencies.

**Comment by tkrotoff** [comment]
I'm using npm-check-updates to upgrade all package.json inside a directory:
`find . -type f -name 'package.json' -not -path './.git/*' -not -path '*/node_modules/*' -execdir ncu --upgrade \;`

See https://github.com/tkrotoff/react-form-with-constraints/blob/v0.14.0/package.json#L22

**Comment by zyf0330** [comment]
yarn up should work

**Comment by sivaraj-v** [comment]
> I'm using npm-check-updates to upgrade all package.json inside a directory: `find . -type f -name 'package.json' -not -path './.git/*' -not -path '*/node_modules/*' -execdir ncu --upgrade \;`
> 
> See https://github.com/tkrotoff/react-form-with-constraints/blob/v0.14.0/package.json#L22

Great
