### ISSUE TITLE
bash: yarn: command not found

### ISSUE THREAD

**Issue by crodier1** [yarnpkg/yarn#4920]
I am trying to install axios. I installed yard. This is what happens in Git Bash:

$ yarn add axios
bash: yarn: command not found

**Comment by rally25rs** [comment]
What method did you use to install Yarn? I assume it isn't in your PATH.

**Comment by chisumo2016** [comment]
'yarn' is not recognized as an internal or external command,
operable program or batch file.
I am using a window  pc

**Comment by rally25rs** [comment]
Closing this as it has been 16 days and the OP has not provided any additional information. Can reopen it if more info is provided.
