### ISSUE TITLE
Yarn progress bars not displaying correctly inside multi-term in Emacs

### ISSUE THREAD

**Issue by duncan-bayne** [yarnpkg/yarn#4927]
**What is the current behavior?**
If I run `yarn install` inside a [multi-term](https://www.emacswiki.org/emacs/MultiTerm) buffer within Emacs, Yarn installs my packages correctly, but displays ... weird ... progress bars while doing so:

![yarn](https://user-images.githubusercontent.com/65949/32805026-4137b650-c9dc-11e7-93de-91fe17efe754.png)

Note that `$TERM` is `eterm-color` inside multi-term, which I think may be confusing Node or Yarn in some way.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Start Emacs.
2. Switch to a multi-term buffer.
3. Change into a project that uses Yarn.
4. Run `yarn install`.

**What is the expected behavior?**
1. I expect Yarn to either (a) display normal progress bars, as it does in other terminal programs like Sakura, or (b) not display progress bars at all.

**Please mention your node.js, yarn and operating system version.**
Yarn 1.2.0
Node v8.6.0
GNU Emacs 25.3.1
multi-term 20160619.233

I've observed this behaviour on multiple versions of Yarn, on multiple versions of Node.

**Comment by duncan-bayne** [comment]
@Daniel15 I can provide SSH access to a FreeBSD box if that will help in any way

**Comment by paralin** [comment]
Yeah this is still broken in this way

**Comment by duncan-bayne** [comment]
Just wanted to repeat the offer of access to a FreeBSD dev box, if that'll help anyone.  Email me and I will set things up (likely turnaround a few days).

**Comment by metareven** [comment]
A workaround for now seems to be setting TERM to something like x10term yourself
`export TERM=x10term`

**Comment by duncan-bayne** [comment]
Thanks @metareven.  By default `TERM` is `eterm-color` inside Emacs.  On FreeBSD 11.1, the following workaround works:

`TERM=vt220 yarn install`
![yarn-workaround](https://user-images.githubusercontent.com/65949/36812123-3305b5b4-1d24-11e8-8fe9-bd71853ed943.png)

**Comment by paralin** [comment]
Can confirm vt220 works.

**Comment by duncan-bayne** [comment]
Possible duplicate of https://github.com/yarnpkg/yarn/issues/2013?

**Comment by duncan-bayne** [comment]
Closing for now; VT220 workaround suffices :)
