### ISSUE TITLE
yarn add simply ignores yarn.lock. this is not right.

### ISSUE THREAD

**Issue by hekod777** [yarnpkg/yarn#4928]
**Is it a bug?**

`yarn add <package name>` now ignores the yarn.lock in the package. this is probably a bug?

**What is the current behavior?**

Now `yarn add <package name>` now ignores the yarn.lock in the package and tries to install the newest version for sub dependencies based on package.json  

**if the current behavior is a bug, please provide the steps to reproduce.**

I created 2 packages and published them to npm for this test. ropublishot and ropublishot2. 

The newest version of ropublishot is 1.0.3

ropublishot2@1.0.3 has a dependency of ropublishot^1.0.2 in its package.json

yarn.lock in ropublishot2 locks the version of ropublishot at 1.0.2 
```
ropublishot@^1.0.2:
   version "1.0.2"
```

npm-shrinkwrap.json in ropublishot2 locks the version of ropublishot at 1.0.2 

`yes, this package has 2 lock files.`

steps:

1. create a new dir `mkdir shrinkwrap-works && cd shrinkwrap-works`

2. `npm init -y`

3. `npm install ropublishot2@1.0.3`  _I am using node.js 8.4.0, no need to have to --save flag_

you can see that the version of ropublishot is 1.0.2. This is what the lock file supposed to do

4. `cd ..`

5. create a new dir `mkdir yarn-lock-not-work && cd yarn-lock-not-work`

6. `npm init -y`

7. `yarn add ropublishot2@1.0.3`

you can see that the version of ropublishot is 1.0.3. yarn.lock was totally ignored by yarn add.

**_This means that yarn will cause more trouble than not if you are making a module or a package used by others._**

**What is the expected behavior?**

yarn add should put yarn.lock into consideration if it's presented in the package and install the correct locked sub dependencies like npm-shrinkwrap.

PS: if I rename npm-shrinkwrap.json to package-lock.json. `npm install ropublishot2@1.0.3` will behave kind of the same as `yarn add ropublishot@1.0.3`

**Please mention your node.js, yarn and operating system version.**
NodeJS: 8.4.0
npm: 5.5.1
operating system: mac 10.12.6

**Comment by aikar** [comment]
I strongly disagree. You're misusing npm-shrinkwrap for one.

That was more for application release. yarn.lock is equivalent to package-lock.json, not shrinkwrap.

What your suggesting would complicate when you want to switch to a specific version, requiring you to yarn remove it first, then yarn add again.

yarn.lock is not designed to block you from changing version numbers, which is what you're asking about.

Don't use yarn add unless you're explicitly trying to change the version number (which you can also use yarn upgrade (-L -C) for too.

If you want to install what is in the lock file, simply run `yarn install`.

**Comment by torifat** [comment]
Thanks @aikar for explaining.

@hekod777 if you need more details then please read https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by hekod777** [comment]
I do understand that yarn ignores the `yarn.lock` in dependency folders. But I think this should only applies to `yarn install`, because `yarn.lock` in the root folder already has all the sub-dependency information. That's why even if it ignores all the `yarn.lock` files in dependencies, it will still install the correct sub-dependencies specified in the root `yarn.lock` file.

However, `yarn add <package name>` is a totally different case. First of all `yarn add` does not rely on the `yarn.lock` file in the root folder, because all it does is to install a new package and update the root `yarn.lock` file based on the package installed. To install the dependencies for this new package and update the `root yarn.lock` file correctly `yarn add` should put the `yarn.lock` file in this package into consideration. 

For example:

Package `abc` has a dependency of `xyz@1.2.0` specified in `abc`'s `yarn.lock` file. and `xyz^1.2.0` in `package.json`.

You do not have a root `yarn.lock` file in your project folder. Then you run  `yarn add abc`. and it installs `abc` with a sub-dependency of `xyz@1.2.8`. and this `xyz@1.2.8` actually has a bug that breaks everything. As a result `yarn add` fails its job to install a working package.


And...


I know you can remove the `^` in `package.json` in a package. But this doesn't do any good. let's say package `abc` has a dependency of `xyz@1.2.0` in it's package. but `xyz` has a its own dependency of `qwe^1.3.0`. even if I specified `xyz@1.2.0` in the `package.json` of `abc`, the sub-dependency `qwe` will still be installed at a incorrect version. This is where `yarn.lock` should come in and help `yarn add abc` to install the correct version of `xyz` and `qwe`.

But `yarn add` is not doing this job at the moment.

That's just not right.
