### ISSUE TITLE
Global binary path symlink not updated on package upgrade

### ISSUE THREAD

**Issue by jamieweavis** [yarnpkg/yarn#4941]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn does not update changed global package binary paths when upgrading a package.

I changed the binary path in my `package.json` from:
```javascript
// v0.2.10
"bin": {
  "dodgem": "index.js"
}
```
to:
```javascript
// v0.2.12
"bin": {
  "dodgem": "src/app.js"
}
```

After upgrading the package, the symlink to the binary is not updated to reflect the new path in `package.json`.

**Steps to reproduce**
```sh
$ yarn global add dodgem@v0.2.10
success Installed "dodgem@0.2.10" with binaries:
      - dodgem
✨  Done in 10.39s.


$ dodgem --version
0.2.10


$ readlink /usr/local/bin/dodgem
../../../Users/jamie/.config/yarn/global/node_modules/dodgem/index.js


$ yarn global upgrade dodgem@latest
success Saved lockfile.
success Saved 1 new dependency.
└─ dodgem@0.2.12
✨  Done in 1.89s.


$ dodgem --version
fish: Unknown command 'dodgem'


$ readlink /usr/local/bin/dodgem
../../../Users/jamie/.config/yarn/global/node_modules/dodgem/index.js
```

Uninstalling and re-installing the package shows the correct symlink:
```sh
$ yarn global remove dodgem
success Uninstalled packages.
✨  Done in 1.67s.


$ yarn global add dodgem
success Installed "dodgem@0.2.12" with binaries:
      - dodgem
✨  Done in 11.32s.


$ readlink /usr/local/bin/dodgem
../../../Users/jamie/.config/yarn/global/node_modules/dodgem/src/app.js
```

**What is the expected behavior?**
For the symlink to be updated to match the changed binary path.

###### Environment Versions
```
Node   8.9.1
Yarn   1.3.2
macOS  10.13.1
```

**Comment by rally25rs** [comment]
Confirmed on 1.3.2.

File `src/cli/commands/global.js` function `initUpdateBins()` has logic to not create bins if they already exist

```
    // add new bins
    for (const src of afterBins) {
      if (beforeBins.has(src)) {
        // already inserted
        continue;
      }
```

**Comment by rally25rs** [comment]
This behavior seems to come from Yarn itself. `src/util/fs.js`

```
    // if destination exists
    if (destStat) {
      const bothSymlinks = srcStat.isSymbolicLink() && destStat.isSymbolicLink();

      ...

      if (bothSymlinks) {
        const srcReallink = await readlink(src);
```

Since this is the case, I think the logic in `src/cli/commands/global.js` to skip update of existing links just needs to be removed.

**Comment by beerzyp** [comment]
Hi, I'm going to try to work on this issue on the next few weeks
