### ISSUE TITLE
yarn-outdated should not call minor updates backward-compatible when major is 0

### ISSUE THREAD

**Issue by Enet4** [yarnpkg/yarn#4942]
I called `yarn outdated` in one of my projects and obtained this output:

![screenshot_2017-11-16_16-53-20](https://user-images.githubusercontent.com/4738426/32904398-2ea02d9c-caef-11e7-97cf-1c50746be824.png)

It is claiming that upgrading `typedoc` would be a minor update with backward-compatible features, but the package is still in major version 0. By the definition of semantic versioning, a zero for the major version is used for less stable APIs, and bumping the `y` in `0.y.z` can be a breaking change. I believe that in these cases, the tool should instead label the package in red.

**Comment by rally25rs** [comment]
I believe currently the code just checks if the `major`, `minor` or `patch` version changed and colors it based on that. We could discuss if the colors/descriptions should be different for `0.x.x` packages.

**Comment by iansu** [comment]
I agree that in `0.x.x` packages bumping the minor version should be considered a (potential) breaking change. I would be happy to implement this if there's a desire for it.
