### ISSUE TITLE
nvm is not compatible in `yarn run <script>`

### ISSUE THREAD

**Issue by linkeo** [yarnpkg/yarn#4944]
**Do you want to request a *feature* or report a *bug*?**

Bug: nvm is not compatible in `yarn run <script>`, because yarn set the environment variable `$PREFIX` during running script.

**What is the current behavior?**

Yarn cannot run this script:
```
yarn run release --prerelease
yarn run v1.3.2
$ standard-version --prerelease
✔ bumping version in package.json from 2.0.1 to 2.0.2-0
✔ outputting changes to CHANGELOG.md
✔ committing package.json and CHANGELOG.md
nvm is not compatible with the "PREFIX" environment variable: currently set to "/usr/local"
Run `unset PREFIX` to unset it.
.git/hooks/pre-commit: line 49: node: command not found
husky > npm run -s precommit (node )

env: node: No such file or directory

husky > pre-commit hook failed (add --no-verify to bypass)

Command failed: git commit CHANGELOG.md package.json -m "chore(release): 2.0.2-0"
nvm is not compatible with the "PREFIX" environment variable: currently set to "/usr/local"
Run `unset PREFIX` to unset it.
.git/hooks/pre-commit: line 49: node: command not found
husky > npm run -s precommit (node )

env: node: No such file or directory

husky > pre-commit hook failed (add --no-verify to bypass)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But npm can:

```
npm run release -- --pre-release

> xxd-backend@2.0.0-alpha.1 release /Users/linkeo/Projects/service/xxd-backend
> standard-version "--pre-release"

✔ bumping version in package.json from 2.0.0-alpha.1 to 2.0.0
✔ outputting changes to CHANGELOG.md
✔ committing package.json and CHANGELOG.md
husky > npm run -s precommit (node v8.9.1)

yarn run v1.3.2
$ bash bin/_internal/lint.sh
 - Lint using eslint (incremental scan)
 - Code not changed, linting is skipped.
Done in 0.27s.
husky > npm run -s commitmsg (node v8.9.1)

⧗   input: chore(release): 2.0.0
✔   found 0 problems, 0 warnings


✔ tagging release 2.0.0
ℹ Run `git push --follow-tags origin master; npm publish` to publish
```

Because `PREFIX` is mentioned above, I run these commands to check env:

```sh
yarn run debug # env
npm run debug # env
```

Comparing the results, I notice yarn add `PREFIX=/local/bin` in `yarn run <script>` command.

**If the current behavior is a bug, please provide the steps to reproduce.**

My project is using `standard-version` to auto-generate CHANGELOG.md, and `husky` to check code style(`eslint`) or commit message(`commitlint`) during commiting.

So you can quickly reproduce by:

Execute:
```sh
mkdir test && cd test
touch package.json index.js .gitignore
```

Edit package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "commitlint": "^4.3.0",
    "eslint": "^4.11.0",
    "husky": "^0.14.3",
    "standard-version": "^4.2.0"
  },
  "scripts": {
    "release": "standard-version",
    "precommit": "eslint .",
    "commitmsg": "commitlint -e $GIT_PARAMS",
    "debug": "env | grep PREFIX"
  }
}
```

Edit index.js
```
This cannot be passed by eslint.
```

Edit .gitignore
```
node_modules
```

Execute:
```sh
git init
git add .
git commit -m 'init'
yarn
yarn run release
```

Then you will get the error above.

**What is the expected behavior?**

`yarn run <script>` should be compatible with nvm.

**Please mention your node.js, yarn and operating system version.**
OS: macOS Sierra 10.12.6
nvm: v0.33.6
yarn: v1.3.2
node: v8.9.1 (managed by nvm)
npm: 5.5.1

**Comment by linkeo** [comment]
Is `PREFIX` necessary inside `yarn run <script>` command?

**Comment by kaylieEB** [comment]
@linkeo it's not necessary and afaik yarn does not automatically set it. I was able to run the command you mentioned above in my computer. Maybe it was set previously in your .yarnrc or shell profile? Can you retry after `yarn config delete prefix`?

**Comment by linkeo** [comment]
Ummm, `yarn config delete prefix` did not work, but `npm config delete prefix` worked for me.

I think this issue can be closed now.
