### ISSUE TITLE
Yarn 1.3.2 on Windows 10, global upgrade-interactive works but update the package.json in directory not the global one.

### ISSUE THREAD

**Issue by johnunclesam** [yarnpkg/yarn#4952]
I installed yarn with npm --global.

I'm on yarn 1.3.2.

Until now everything ok.

Now If I'm in a npm project (with package.json file in root) and try this command: `yarn global upgrade-interactive` it works ok but instead of writing the right `package.json` file in "`C:\Users\John\AppData\Local\Yarn\config\global\package.json`" it writes the one in my folder where I launch the command.

I think this is a dummy bug.

**Comment by zackschuster** [comment]
i can try & take a look into this when i get some time -- here's a ref to where `global upgrade-interactive` is defined: https://github.com/yarnpkg/yarn/blob/8918b6cff99e037f3ab56523ebfde96e0c19cdae/src/cli/commands/global.js#L272
