### ISSUE TITLE
Feature: Improve UX when switching Git branches or similar and node_modules folder changes dramatically.

### ISSUE THREAD

**Issue by silbinarywolf** [yarnpkg/yarn#4958]
**The problem:**
On Windows and Linux machines, when switching between branches, running `yarn install` will not install older versions of a package and you'll get obtuse errors with your JavaScript build tools that can only be remedied by deleting your entire `node_modules` folder and running `yarn`.

This is not something you need to do when using PHP package manager, [Composer](https://github.com/composer/composer). 

**The solution:**
Let's copy what Composer does. When you run `composer install`, if its a fresh install, it generates a file in `vendor/composer/installed.json` that describes what version of each package is currently installed. When you re-run `composer install`, the versions from `composer.lock` are compared against  `vendor/composer/installed.json` and then the actual packages inside `node_modules` are updated accordingly.

It looks like the `node_modules/.yarn-integrity` file already stores this information, but I've still needed to wipe my entire `node_modules` folder in certain cases when switching Git branches

ie. master branch uses Brunch build tooling and another branch uses Laravel Mix + Webpack (with the aim to transition across)

**Comment by aikar** [comment]
Changes in versions actually should trigger the yarn integrity file to be invalid and yarn install should work.

I have git post checkout hooks that runs yarn install anytime yarn.lock changes, and it does kick off version changes for me.

So this looks more like a bug that it's not triggering in your environment

**Comment by StephanBijzitter** [comment]
What about `yarn --force`? This is basically what we do in our `start` script, before the actual script. Makes sure that after switching branches (and you do `yarn start` (`"start": "yarn --force && my-usual-start-script"`)), you don't even need to think of installing again. I haven't had any issues yet, even switching between local and VM environments.

**Comment by silbinarywolf** [comment]
Busy currently, but I'll see if this is fixed in the latest version with a small test sometime in December and let you guys know.

I dont think I want to do `yarn --force` as I assume that'd be expensive disk IO operation. (When working with files, I've found Windows machines to be 8X slower than Linux when writing files in personal Golang applications.

**Comment by silbinarywolf** [comment]
I haven't hit problems with this at all this year, so will close :)
