### ISSUE TITLE
Incorrect filename in ENOENT error message

### ISSUE THREAD

**Issue by alexmcmillan** [yarnpkg/yarn#4959]
Using Node 6.10.3, Yarn v1.3.2 on Windows 10

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error message upon moving a file gives an incorrect filename as the source of an ENOENT error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Consider an app with 2 components:

`Page`
`Clock`

where `Page` contains `import Clock from './clock';`

- yarn start (from `create-react-app`)
- ensure successful build
- move a `clock.js` into a subdirectory
- note error message:

```
./src/components/clock.js
Module build failed: Error: ENOENT: no such file or directory, open 'D:\Repos\Platform\Web\Frontend\App\src\components\clock.js'
    at Error (native)
```

**What is the expected behavior?**

Expected the first line of that error message to be `./src/components/Page.js`.  I have sometimes seen this to be the case, but more often than not it is the name of the moved file (the file repeated on the 2nd line).

**Comment by Daniel15** [comment]
This doesn't seem related to Yarn. Yarn doesn't touch your app's files at all, it just handles dependencies (files in `node_modules`). Sounds like an issue either with create-react-app or one of its dependencies (eg. Webpack).

**Comment by alexmcmillan** [comment]
Sorry, with things like `create-react-app` it can be difficult to determine what tool is responsible for what functionality.
