### ISSUE TITLE
yarn install

### ISSUE THREAD

**Issue by hazasaad** [yarnpkg/yarn#4960]
windows 7 32 bit

on my sylius project

C:\xampp\htdocs\project>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ? node-sass: check python checking for Python executable "python"
[-/1] ? waiting...
[-/1] ? waiting...
[-/1] ? waiting...
error C:\xampp\htdocs\project\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\xampp\htdocs\project\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\project\node_modules\
node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --li
bsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\project\\node_modules\\node-gyp\\bin\\node-gy
p.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.0
gyp info using node@8.9.1 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\project\node_mo
dules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\project\node_modules\which\whi
ch.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\project\node_modules\which\whi
ch.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\project\node_modules\which\which.
js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\project\node_modules\isexe\index.
js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\project\node_modules\isexe\window
s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\project\node_mo
dules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\project\node_modules\which\whi

**Comment by Daniel15** [comment]
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb which failed Error: not found: python2

This looks like a node-gyp error, not a Yarn error. Please try installing Python then trying again. Native Node.js libraries need Python in order to compile them.

Having said that, node-sass does include a prebuilt version for Node.js 8.x on Windows. Perhaps you're referencing a very old version, in which case you should update it :)

**Comment by hazasaad** [comment]
i m using node 8.9.1

**Comment by Daniel15** [comment]
@hazasaad - I meant an old version of `node-sass`. Which version of node-sass do you reference?

**Comment by hazasaad** [comment]
``{
  "name": "sass-graph",
  "version": "2.1.2",
  "description": "Parse sass files and extract a graph of imports",
  "license": "MIT",
  "repository": "xzyfer/sass-graph",
  "author": "xzyfer",
  "main": "sass-graph.js",
  "directories": {
    "bin": "./bin"
  },
  "scripts": {
    "test": "mocha ./test/test*.js"
  },
  "keywords": [
    "sass",
    "graph"
  ],
  "dependencies": {
    "glob": "^7.0.0",
    "lodash": "^4.0.0",
    "yargs": "^4.7.1"
  },
  "devDependencies": {
    "assert": "^1.3.0",
    "mocha": "^2.1.0"
  },
  "files": [
    "bin",
    "parse-imports.js",
    "sass-graph.js"
  ]
}

**Comment by hazasaad** [comment]
C:\xampp\htdocs\sylius>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
error An unexpected error occurred: "write EIO".
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\xampp\\htdocs\\sylius\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

**Comment by BYK** [comment]
@hazasaad I'm closing this issue due to low-quality information provided. It also looks a lot like a problem related to your system or a specific set up. If you can trace it back to Yarn, we are happy to help it but until then, this issue is not very useful to anyone.
