### ISSUE TITLE
Yarn does not validate SemVer range against `latest`

### ISSUE THREAD

**Issue by hansl** [yarnpkg/yarn#4966]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Assuming:
1. two published of package `example` version 1.0 and 1.1
2. `latest` dist-tag points to 1.0
3. `package.json` points to the range `^1.0.0` of the `example` package

Then: `yarn install` will install 1.1, while `npm install` will install 1.0.

**What is the expected behavior?**
Yarn should behave the same as npm. `latest` dist-tag can be used to rollback some faulty published packages and if a user runs `yarn install` it would be a problem.

**Please mention your node.js, yarn and operating system version.**
This was tested on both Linux and OSX.

**Comment by rally25rs** [comment]
This was fixed in v1.3.0 by #4804 
Please make sure you have the latest Yarn installed. If this is still broken in v1.3.2 then let me know and I'll re-open this issue.

Thanks!
