### ISSUE TITLE
"yarn cache list" tries to readdir files

### ISSUE THREAD

**Issue by agoldis** [yarnpkg/yarn#4972]
**Bug**
Running `yarn cache list` throws an error when no `.yarn-metadata` exists in some cached package that is in use by the current project

**To reproduce**
1. Get cache dir location
2. Remove `.yarn-metadata` from one of repos in the cache dir
3. run `yarn cache list`
4. Observer the error, e.g.: 
```
error An unexpected error occurred: "ENOTDIR: not a directory, scandir '/Users/agoldis/Library/Caches/Yarn/v1/npm-get-uri-2.0.1-dbdcacacd8c608a38316869368117697a1631c59/History.md'".
```
**What is the expected behavior?**
To skip / invalidate corrupted cached module

**Please mention your node.js, yarn and operating system version.**
MacOS High Sierra
Yarn 1.3.2
Node 8.9.0

**Comment by misoguy** [comment]
I'd like to try this if no one is on it yet :)
