### ISSUE TITLE
error Couldn't find any versions for "react-native-keyboard-spacer" that matches "3.1"

### ISSUE THREAD

**Issue by loyoliteabid** [yarnpkg/yarn#4988]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by Daniel15** [comment]
There's no such version of `react-native-keyboard-spacer`. The latest version is `0.4.1`: https://yarn.pm/react-native-keyboard-spacer

**Comment by loyoliteabid** [comment]
@Daniel15 , Thanks for your quick response. But whenever i run `yarn` it shows the following warnings `warning Lockfile has incorrect entry for "react-native-keyboard-spacer@3.1". Ignoring it.
Couldn't find any versions for "react-native-keyboard-spacer" that matches "3.1"
? Please choose a version of "react-native-keyboard-spacer" from this list: (Use arrow keys)
❯ 0.4.1 
  0.4.0 
  0.3.1 
  0.3.0 
  0.2.0 
  0.1.6 
  0.1.5 
  0.1.4 
  0.1.3 
  0.1.2 
  0.1.1 
  0.1.0 `

**Comment by Daniel15** [comment]
It means that your lockfile says to install version 3.1, but no such version exists. Maybe you have a bad version in your package.json file.
