### ISSUE TITLE
yarn upgrade-interactive not showing packages to update

### ISSUE THREAD

**Issue by JaKXz** [yarnpkg/yarn#4993]
I think there's a problem with yarn upgrade-interactive, based on the docs: https://yarnpkg.com/en/docs/cli/upgrade-interactive

e.g. You can reproduce this issue with this repo: https://github.com/istanbuljs/append-transform

```
$ yarn upgrade-interactive
yarn upgrade-interactive v1.3.2
success All of your dependencies are up to date.
✨  Done in 0.80s.

$ yarn outdated
yarn outdated v1.3.2
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                    Current Wanted Latest Package Type    URL
ava                        0.14.0  0.14.0 0.23.0 devDependencies https://ava.li
coveralls                  2.13.3  2.13.3 3.0.0  devDependencies https://github.com/nickmerwin/node-coveralls#readme
default-require-extensions 1.0.0   1.0.0  2.0.0  dependencies    https://github.com/avajs/default-require-extensions#readme
nyc                        6.6.1   6.6.1  11.3.0 devDependencies https://github.com/istanbuljs/nyc#readme
xo                         0.15.1  0.15.1 0.18.2 devDependencies https://github.com/sindresorhus/xo#readme
```

This happens on any LTS version of node, and I'm on macOS 10.13.1 [though I'm pretty sure this is not platform specific].

**Comment by rally25rs** [comment]
This is as designed. From the docs:

> Yarn will respect the version ranges in package.json when determining the version to upgrade to.

> --latest : This flag tells yarn to ignore the specified version ranges in package.json and instead use the version tagged latest in the registry.

So if you look at `ava` for example, your `package.json` contains `^0.14.0`. The newest version that fits that range is `0.14.0` which is the same that you have installed. If you run `upgrade-interactive --latest` then it will ignore your specified range and use the `latest` from the registry (`0.23.0`)

-----

If you want to look at it another way, `outdated` is showing you:

* current = what you have installed
* wanted = newest for your specified package.json semver range, which is what `upgrade` and `upgrade-interactive` will upgrade you to by default
* latest = the latest as reported by the registry, which `upgrade` and `upgrade-interactive` will upgrade you to if the `--latest/-L` flag is set

-----

This was to give users more control over package upgrades where major versions shouldn't be jumped. For example in one of my projects I can use any `1.x` version of PhantomJS, but `2.x` causes problems... but I do want to get upgrades to the latest `1.x` versions.
