### ISSUE TITLE
`yarn install` taking longer than usual after upgrade to v1.3.2.

### ISSUE THREAD

**Issue by parkerziegler** [yarnpkg/yarn#5000]
**System Configuration**
`yarn` - **v1.3.2**
`node` - **v8.9.1**
`macOS` - **v10.12** - **Note: I am running on a 2012 MacBook Pro with 8GB RAM - could be hardware related.**

**What is the current behavior?**
I ran a fresh `yarn install` of a React Native app and the download took much longer than usual (a little over a minute and thirty seconds). Previous install took roughly 20 seconds. That being said, it did download **much** faster than `npm` using **v4.6.1** (roughly 5 minutes).

**If the current behavior is a bug, please provide the steps to reproduce.**
[The repository](https://github.com/parkerziegler/react-native-demo) was bootstrapped using `create-react-native-app` and is run with `expo`. Clone the repo and run `yarn install`.

**What is the expected behavior?**
I would expect the `install` process to be much quicker. Previous releases of `yarn` were very fast with this install, roughly 20 seconds. That being said, the `yarn.lock` is very large (5847 lines), and I know `expo` brings along quite a bit with it. It may be a result of upgrading to a newer `expo` SDK.

**Please mention your node.js, yarn and operating system version.**
See above.

**Comment by bestander** [comment]
Thanks for the report, @parkerziegler.

Could you run a benchmark for us with different versions of yarn to see the absolute numbers.

@BYK @arcanis, is it a known problem?

**Comment by parkerziegler** [comment]
@bestander thanks for your help on this! I'm out of town and away from my machine at the moment, but I'll run the benchmark on Sunday and get back to you. Thanks!

**Comment by parkerziegler** [comment]
@bestander I ran it with both `yarn` **v1.3.2** and **v1.2.1**. **v1.3.2** finished in 352.38s and **v1.2.1** finished in 345.56s. So it seems like everything is as normal, I suppose `react-native` apps bootstrapped with `create-react-native-app` just drag along a lot of dependencies – saw linking for over 30000 dependencies. Thanks for taking a look at this, going to go ahead and close the issue.
![screen shot 2017-12-11 at 7 51 10 pm](https://user-images.githubusercontent.com/19421190/33869737-539ae23e-debf-11e7-8b4e-bf33fefc6a8c.png)
![screen shot 2017-12-11 at 10 05 06 pm](https://user-images.githubusercontent.com/19421190/33869739-54d82f3a-debf-11e7-9ab7-abfad169cd28.png)
