### ISSUE TITLE
yarn publish --non-interactive still asks questions

### ISSUE THREAD

**Issue by dmerejkowsky** [yarnpkg/yarn#5002]
yarn 1.3.2
node 9.2.0

# steps to reproduce

```console
$ mkdir hello
$ yarn init
$ yarn publish --non-interactive
```

# actual

yarn stops with:

```
yarn publish v1.3.2
[1/4] Bumping version...
info Current version: 1.0.0
question New version: 
```

# expected

An error message stating that `--non-interactive` must be used with `--new-version` ?

# notes

yarn `--non-interactive` also stops if no npm token is found.

**Comment by bestander** [comment]
Good find!
https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/publish.js needs to respect this flaG!

Good first PR!

**Comment by iansu** [comment]
Is anyone working on this? If not then I'd like to do it.

**Comment by bestander** [comment]
@iansu, go ahead!

**Comment by iansu** [comment]
Will do. Just to confirm, the basic idea is to display an error if `--non-interactive` is specified without `--new-version`? And also just fail with an error if no NPM token is present instead of prompting for it?

**Comment by bestander** [comment]
Yeah, I think it should fail fast if it try to prompt in non interactive
mode

**Comment by stijndepestel** [comment]
Is there an update on this? I want to use yarn in our CI/CD environment since it is faster than npm, however, without this option working we cannot use yarn to automate our release/publish mechanism.

**Comment by bestander** [comment]
The quickest way to get this in is to send a PR.
The code is quite simple

**Comment by iansu** [comment]
I made a PR for this a couple of months ago: https://github.com/yarnpkg/yarn/pull/5108

**Comment by dmerejkowsky** [comment]
@stijndepestel 

>I  want to use yarn in our CI/CD environment since it is faster than npm, however, without this option working we cannot use yarn to automate our release/publish mechanism.

At work we have fully automated CI/CD and we use `yarn` for everything *except* the last call to  `npm publish`.

it works quite well :)
