### ISSUE TITLE
`yarn add` upgrades a dependency if it's the dependency already exists as a different type

### ISSUE THREAD

**Issue by kaylieEB** [yarnpkg/yarn#5003]
**Do you want to request a *feature* or report a *bug*?**

Bugish, discovered from https://github.com/yarnpkg/yarn/issues/4971

**What is the current behavior?**

Running `yarn add` (without a version range) for a different type of dependency upgrades the package but also throws a warning `warning "nock" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".`

I think it's a bit confusing to both warn but also upgrade the dependency. 
```
🍉  [yarn-test] yarn add -D nock@^7.0.0                                                     master  ✱
yarn add v1.3.2
...
├─ nock@7.7.3
✨  Done in 1.10s.
```

```
🍉  [yarn-test] yarn add nock                                                             master  ✭ ✱
yarn add v1.3.2
...
├─ nock@9.1.3
warning "nock" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
✨  Done in 1.09s.
🍉  [yarn-test] cat package.json                                               master  ✭ ✱
{
  "name": "yarn-test",
  "devDependencies": {
    "nock": "^9.1.3"
  }
}
```

cc' @rally25rs 

**What is the expected behavior?**
Warn and not upgrade the dependency, since the flag wasn't respected. Only use `yarn upgrade` to update existing dependencies.
**Please mention your node.js, yarn and operating system version.**
```
🍉  [yarn-test] yarn -v                                                                   master  ✭ ✱
1.3.2
🍉  [yarn-test] node -v                                                                   master  ✭ ✱
v8.4.0
🍉  [yarn-test] sw_vers -productVersion                                                   master  ✭ ✱
10.12.6
```

**Comment by rally25rs** [comment]
Add with no version range will use `latest`. I think I saw somewhere in the code where if no range is specified it tacks on `@latest`, so I'm not completely surprised by the version change.

The warning is pretty poorly worded. I would say it should either _not_ say "do this before that" or be an error that halts the process.

**Comment by kaylieEB** [comment]
This makes sense since upgrade is using add under the hood, but the warning is confusing and should read to be something like `"nock" is already in "devDependencies" and has been updated. If you'd like to 
 add it to "dependencies", please remove existing entry first"`

**Comment by rally25rs** [comment]
yeah that is a much clearer description.

**Comment by kaylieEB** [comment]
cool, i'll update it in a pr!

**Comment by kaylieEB** [comment]
closing this in favor of https://github.com/yarnpkg/yarn/issues/5003
