### ISSUE TITLE
Yarn Linux Mint - Will Not Install

### ISSUE THREAD

**Issue by AnthoniG** [yarnpkg/yarn#5009]
Followed the documents on the website to install (it's a debian based distro, so I followed the Ubuntu install.

Now when I run sudo apt-get install yarn it says unable to find yarn.
Pasted below is my complete output

```
sudo apt-get update && sudo apt-get install yarn
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:2 http://www.mirrorservice.org/sites/packages.linuxmint.com/packages sonya InRelease                            
Hit:3 http://archive.canonical.com/ubuntu xenial InRelease                                                          
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease                                                     
Hit:5 http://www.mirrorservice.org/sites/packages.linuxmint.com/packages sonya Release                              
Hit:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease                                    
Hit:7 https://repo.skype.com/deb stable InRelease                                                    
Hit:8 http://security.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package yarn

```

Any ideas what's going ?

**Comment by AnthoniG** [comment]
Solved it.
It would not add the package list via bash but added in the visual editor for packages then did update and install after that and it worked fine :smiley_cat:

**Comment by GunjanChhablani** [comment]
I think this should be fixed. If not, this should at least be mentioned in the installation guide. Faced the same issue and fixed it using the same method.

**Comment by amvaleh** [comment]
@AnthoniG 
Hi, I have the same problem, but I didn't understand how you solved it, could u please explain more?
tnx

**Comment by AnthoniG** [comment]
@amvaleh 
Where it says to add the package via bash, what I did was add it vie the System sources dialog and it worked then

Not at main computer so cant recall System sources dialog real name is but hopefully you understand?
If not let me know and I will try and get you a screenshot
feal
