### ISSUE TITLE
Yarn Installation  Problem

### ISSUE THREAD

**Issue by chisumo2016** [yarnpkg/yarn#5014]
I am having a problem has shown below .I am using a window machine
C:\laragon\www\blog-forum>yarn  add bulma --dev
'yarn' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rally25rs** [comment]
How did you install Yarn? Check your `PATH` and make sure Yarn is on it.

**Comment by firebaste** [comment]
اواجه مشكله في تاكيد المعامله

**Comment by rally25rs** [comment]
I tried installing on Win10 with the .msi installer from the Yarn website, and it seemed to work fine. Closing for now unless reproduction steps are added.
