### ISSUE TITLE
Get ECONNREFUSED 104.16.62.173:443

### ISSUE THREAD

**Issue by alienlebarge** [yarnpkg/yarn#5015]
## Do you want to request a *feature* or report a *bug*?
bug

## Description
Since a few days, when running `$ yarn` in my projects, I get this error:

```shell
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@frctl/mandelbrot/-/mandelbrot-1.2.0.tgz: connect ECONNREFUSED 104.16.62.173:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/cedricaellen/Projects/foehn/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
If I run several time the command, this not always the same package how is mentionned.
![756ab9498466909b2b7b7a1d44804d5c _image 2017-11-30 at 2 55 28 pm](https://user-images.githubusercontent.com/611234/33434158-b1af8030-d5de-11e7-9875-a4af44bb3c7f.png)

## What is the expected behavior?
The commande should run smoothly.
Last week everything was working 👌 and I have not done any change.

## Versions

- node: v8.9.1
- yarn: 1.3.2
- [`yarn-error.log`](https://gist.github.com/alienlebarge/d7f1ec2edfb8fb7f509115849c14b8c4)

## Investigations

I'm behind a corporate proxy (yeah!).

If I ping 104.16.62.173 I get this
```shell
$ ping 104.16.62.173
PING 104.16.62.173 (104.16.62.173): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
...
```

When I visite http://104.16.62.173
![image 2017-11-30 at 2 48 38 pm](https://user-images.githubusercontent.com/611234/33433752-1f67faf0-d5dd-11e7-9e0d-6926f0f5f8d4.png)

When I visite https://104.16.62.173, I get a `ssl_error_bad_cert_domain` error page
![image 2017-11-30 at 2 50 15 pm](https://user-images.githubusercontent.com/611234/33433808-59859080-d5dd-11e7-8b92-e2c463103842.png)

**Comment by alienlebarge** [comment]
ho! and I forget to mention that `$ npm install` work 👌. (Don't know if it helps)

**Comment by rally25rs** [comment]
I believe the in-browser cert error is because the cert is registered to the domain name, not the IP address, so it will always appear invalid when trying to navigate by IP.

Is this still an issue? I can manually download all those URLs and `yarn add` them

```
~/Projects/yarn-test : yarn add @allmarkedup/fang
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ @allmarkedup/fang@2.0.0
✨  Done in 1.88s.
```

The yarn registry is pretty much just a proxy to the npm registry, but sometimes it falls down for a few minutes.

**Comment by alienlebarge** [comment]
thanks for your help @rally25rs but the problem is still there.
```shell
cedricaellen at imac-de-cedric in ~/Projects/foehn on master [$]
$ yarn
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/anymatch/-/anymatch-1.3.2.tgz: connect ECONNREFUSED 104.16.61.173:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/cedricaellen/Projects/foehn/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by alienlebarge** [comment]
I manage to fix my problem.

As I've said, I'm behind a corporate proxy (💩). So I use a local proxy ([Charles](https://www.charlesproxy.com/)) to connect to the corporate proxy. So, everything is set to `http://localhost:3128`.

We use a Nexus Repository Manager for npm package.
My npm settings are
```shell
# npm config
npm config set registry http://nexus.company.ch/folder1/folder2/
npm config set @types:registry=https://registry.npmjs.org
npm config set //nexus.company.ch/folder1/folder2/:_authToken=xxx
```
Everything was working fine since last week with only this npm config.

To fix my problem, I've set a `proxy` and `https-proxy` config for `yarn`.
```shell
$ yarn config set proxy http://localhost:3128
$ yarn config set https-proxy http://localhost:3128
```
And now, everything work fine again.

---

For me, the problem is fixed and this issue can be closed.

@rally25rs @bestander if you want to investigate more about this problem of `yarn` not following `npm` config, you can keep it open.

**Comment by waleedahmed3045** [comment]
I followed @alienlebarge  but it did work for me and I am getting the same error

**Comment by medmin** [comment]
me too  

My yarn is 1.9.4

**Comment by nimahkh** [comment]
I just change my node version to 12 with  `nvm use 12` and solved it.

**Comment by alihusen99** [comment]
ive found this issue too. and its even more bad.
so. my main connection is from ISP. and u can guess it right. my ISP somehow block the yarn connection :'( .
after change ISP, it run normally.
