### ISSUE TITLE
Does anyone know the history behind the yarn name?

### ISSUE THREAD

**Issue by deder01** [yarnpkg/yarn#5025]
I apologize if this is an inappropriate forum, but I've searched far and wide and cannot find an answer to this question.

I work at a company that uses Apache Hadoop YARN which has been around since at least 2012 (https://en.wikipedia.org/wiki/Apache_Hadoop#Difference_between_Hadoop_1_vs_Hadoop_2_.28YARN.29), and as we start to migrate away from towards using yarn people keep asking me why Facebook decided to name this project yarn, which has honestly sparked my own curiosity.  Thus I'm asking if there are any maintainers who were around at the beginning that might have some insight into why this name was chosen.

So no issue, just a question about the history of the package.  Thanks to anyone who is able/willing to shed some light!

**Comment by kaylieEB** [comment]
Hi @deder01 please see https://github.com/yarnpkg/yarn/issues/4536
