### ISSUE TITLE
Yarn fails to install electron throw ECONNREFUSED

### ISSUE THREAD

**Issue by Josexv1** [yarnpkg/yarn#5029]
I'm trying to install Electron, i had installed it before and everything was ok but now it doesn't install it.
Npm install just fine, but Yarn throws an error about localhost...

Windows 10 x64, no proxy, no firewall, no vpn, no network block. Using mobile data, wifi, and ethernet. Using CMD, and cmdr, or Bash.

Here's the log.

C:\Users\Alien\Documents\WebDirectory\Sankaku>yarn add electron    --- is the same with yarn or yarn install
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠄ electron
[-/1] ⠄ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
error C:\Users\Alien\Documents\WebDirectory\Sankaku\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\Alien\Documents\WebDirectory\Sankaku\node_modules\electron
Output:
C:\Users\Alien\Documents\WebDirectory\Sankaku\node_modules\electron\install.js:48
  throw err
  ^

Error: connect ECONNREFUSED 127.0.0.1:443

C:\Users\Alien\Documents\WebDirectory\Sankaku>npm i

> electron@1.7.8 postinstall C:\Users\Alien\Documents\WebDirectory\Sankaku\node_modules\electron
> node install.js

added 7 packages, removed 5 packages and updated 148 packages in 30.407s

C:\Users\Alien\Documents\WebDirectory\Sankaku>node -v
v9.2.0

C:\Users\Alien\Documents\WebDirectory\Sankaku>npm -v
5.5.1

C:\Users\Alien\Documents\WebDirectory\Sankaku>yarn -v
1.3.2

**Comment by Daniel15** [comment]
>  connect ECONNREFUSED 127.0.0.1:443

Do you have a proxy configured? I wonder why it's trying to connect localhost?

Based on the output you've provided, it sounds like this issue is coming from Electron's install scripts (`node_modules\electron\install.js:48`). Please ask the Electron team about it.

**Comment by BYK** [comment]
Closing since this doesn't seem like a Yarn-related issue.
