### ISSUE TITLE
yarn prune error message links to a non-existent docs page

### ISSUE THREAD

**Issue by iansu** [yarnpkg/yarn#5035]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Running `yarn prune` displays an error message and a link to the docs. Visiting that link gives you a 404 error page.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Run `yarn prune`
* Visit the provided URL (https://yarnpkg.com/en/docs/cli/prune) and see a 404 error page

**What is the expected behavior?**
The page exists and provides details of why `yarn prune` is unnecessary or the link is not displayed with the error message

**Please mention your node.js, yarn and operating system version.**
* Node: 8.9.1
* Yarn: 1.3.2
* OS: Mac OS X 10.13.1

**Comment by rally25rs** [comment]
Closing this issue and moving it over to the 'website' repo: https://github.com/yarnpkg/website/issues/736
