### ISSUE TITLE
yarn install operation has blocked

### ISSUE THREAD

**Issue by xiaochunyong** [yarnpkg/yarn#5036]
[4/4] 📃  Building fresh packages...
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
[4/4] ⠄ electron
[-/4] ⠄ waiting...

**Comment by xiaochunyong** [comment]
yarn version: 1.3.2

**Comment by bestander** [comment]
Try running with `--verbose` flag, it should tell which script is hanging.

**Comment by bestander** [comment]
But without any info I won't be able to help debugging it.
I'll close for now.
