### ISSUE TITLE
Sort options and commands in the help output

### ISSUE THREAD

**Issue by BYK** [yarnpkg/yarn#5050]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently, yarn has a seemingly random order when listing available commands and options. 

**What is the expected behavior?**

Sorting them alphabetically or some other consistent and easy to discover way would probably help people trying to read the help output. (cc @mjesun)

**Please mention your node.js, yarn and operating system version.**

Yarn 1.3.2

**Comment by prabakarviji** [comment]
@BYK But it seems like commands list is already sorted whereas options are unsorted.

**Comment by BYK** [comment]
Well, then only options. And also having a test case for both?

**Comment by Koreris** [comment]
I created a pull request that solves this issue, feedback is welcome anyway :)
