### ISSUE TITLE
Installation Problem: [yarn cannot be built with any available compilers]

### ISSUE THREAD

**Issue by BlaStone** [yarnpkg/yarn#5057]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by Daniel15** [comment]
Can you please elaborate? Which OS are you using, and how are you installing Yarn?

**Comment by mdontula** [comment]
dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
clang: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
clang: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
Error: An exception occurred within a child process:
  CompilerSelectionError: yarn cannot be built with any available compilers.
Install GNU's GCC:
  brew install gcc

Can anyone help me to fix this issue?

**Comment by Daniel15** [comment]
@mdontula  - That error looks specific to Homebrew, so you might want to ask the Homebrew developers about it.
