### ISSUE TITLE
`yarn licenses generate-disclaimer` seems not to include NOTICE files

### ISSUE THREAD

**Issue by holvonixAdvay** [yarnpkg/yarn#5072]
_I am not a lawyer, and none of this is legal advice._

**Do you want to request a *feature* or report a *bug*?**
Bug I think.

**What is the current behavior?**
`yarn licenses generate-disclaimer` seems not to include NOTICE files.

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh
mkdir newpack
cd newpack
yarn init -yy
yarn add json2array # our package has an Apache-2 NOTICE file
cat node_modules/json2array/NOTICE  # it is indeed in the package
yarn licenses generate-disclaimer
```

Note the NOTICE isn't in the final output (what is similar to a NOTICE is in there, but only because we added it to the top of our LICENSE file, due to this bug).

**What is the expected behavior?**
If there is a NOTICE file in the distribution, it seems like it should be included along with the LICENSE in generate-disclaimer.  (See for example, Apache-2 Sec 4-d, but it seems generally useful)

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v8.9.1
$ yarn -v
1.3.2
$ uname -v
Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
```

**Comment by Daniel15** [comment]
I'd say this is a "missing feature" rather than a "bug", as currently it's only built to handle LICENSE files. Should be easy to implement though!
