### ISSUE TITLE
Feature request: Use Renovate for maintaining dependencies in yarnpkg/yarn repository

### ISSUE THREAD

**Issue by rarkins** [yarnpkg/yarn#5073]
I would like to propose the Yarn team consider [Renovate](https://github.com/renovateapp/renovate) for automated dependency updates. It's an open source tool available to run either self-hosted (`yarn global add renovate`) or via a [GitHub App](https://github.com/apps/renovate) that I run for free. The GitHub App supports currently 1000+ projects and already creates hundreds of PRs daily. Installed organizations include [GoogleChromeLabs](https://github.com/GoogleChromeLabs), [mozilla](https://github.com/mozilla), [webcomponents](https://github.com/webcomponents), [algolia](https://github.com/algolia) and [apollographql](https://github.com/apollographql).

Renovate has these capabilities which would benefit Yarn:

- Keeps dependencies in `package.json` files up-to-date with latest versions via Pull Requests
- Extensive configuration/customisation support via JSON configuration file
- Renovate generates its own `yarn.lock` files with the same commit as the related `package.json` files, including for Yarn Workspaces
- Renovate PRs get immediately rebased or regenerated to resolve any git conflicts, such as in `package.json` or `yarn.lock`
- Renovate can be used to regularly "maintain" `yarn.lock` files in a repository. e.g. regenerate them daily or weekly and submit the changes via PR. 
- Known monorepos (e.g. react, babel, etc) are automatically configured to group sibling packages together into one PR
- Custom grouping can be defined to group related dependencies into the same PR to reduce total number of PRs
- Scheduling rules can be used to help tame the PR firehose, e.g. limit to certain hours of the day, or weekends only, or monthly, or whatever. *Example: configure all `eslint` and related packages to update monthly in a single PR, rather than in real-time*.
- Possible to customise templates for PR title, commit message, semantic commit prefix, etc - Renovate can fit into your conventions 
- Renovate App signs all its git commits

I am the author of Renovate and watch the app logs diligently via monitoring, so would also volunteer to triage Yarn's dependency updates too. e.g. looking at any failed Renovate branches to determine if the upstream dependency made a backwards-incompatible change or mistake, or if Yarn needs to update its implementation, etc.

**Comment by edmorley** [comment]
I maintain one of the Mozilla projects that uses Renovate - and have been extremely pleased with it so far (worth noting: the `yarn.lock` support is much better than Greenkeeper's approach).

**Comment by vvo** [comment]
At Algolia we use Renovate pretty much everywhere (from libraries to websites), it's a key part of our developer toolkit.

We activated it because many times we found ourselves willing to use module-x and discovering at the same time that 10 or 20 other modules needs to be updated in order to use module-x effectively. This is a pain and renovate solve it very well by constantly looking for upgrades, bundling them when feasible (eslint-*, babel-*, react-*) while giving us the possibility to reduce the noise such tools can generate (for example pushing patch upgrades directly to the master branch, without any PR).

With it's automatic pining and locking support, renovate also helps us in providing re-producible dev environements for collaborators.

👍

**Comment by bestander** [comment]
Sorry for a delay, @rarkins.
Looks like enough people endorsed it and no one objected really.

@rarkins, what do you need to move forward?

**Comment by rarkins** [comment]
@bestander I suggest:

1. I'll fork the repo in its current state to verify Renovate runs happily on it as-is
2. If needed, I'll ask any questions with comments in this issue, e.g. about your preferences
3. I'll recommend a configuration that suits the project
4. You or another admin can then install the app and apply the configuration if all looks good

**Comment by bestander** [comment]
Sounds fine, go ahead!

**Comment by rarkins** [comment]
I've forked and verified that Renovate runs smoothly on the Yarn source code. I think the best approach is to keep it as minimal impact as possible to begin with, and I can then later make suggestions for ideas to improve workflow (e.g. pinning lint packages so builds don't break from in-range updates).

I therefore recommend this simple Renovate config:
```json
{
  "extends": [
    "config:base",
    ":preserveSemverRanges"
  ]
}
```

This is the default Renovate base settings + one rule which says "Keep using the same type of semver ranges as already exist", i.e. no dependency pinning yet.

Steps:

- [ ] Merge my PR #5175 (I think two of your dependencies have been set to exact versions rather than ranges by accident, so merging this will make things cleaner/more consistent)
- [ ] Someone with admin rights goes to https://github.com/apps/renovate and installs Renovate for this repository
- [ ] Renovate will soon after raise a "Configure Renovate" PR for onboarding
- [ ] Update the default `renovate.json` config to match what I wrote above
- [ ] Merge the PR (i.e. add the `renovate.json` to the repository)
- [ ] Renovate will then begin raising dependency update PRs

You can expect to receive [16 PRs](https://github.com/renovate-tests/yarn/pulls) (13 major version upgrades and three 0.x range bumps) after the last step. 

Any of those upgrades can also be "dismissed" by simply closing the respective PR. Renovate will then add a comment to the PR noting that it is ignoring that major version and won't suggest it again.

**Comment by bestander** [comment]
Done first 2 steps

**Comment by bestander** [comment]
Ping me on next steps

**Comment by rarkins** [comment]
@bestander next step is ready for your action: https://github.com/yarnpkg/yarn/pull/5178/files#r160211369
