### ISSUE TITLE
Install only dist folders ?

### ISSUE THREAD

**Issue by Falseee** [yarnpkg/yarn#5079]
Its possible to install only the dist folders ?
Because i dont need the src etc on production.

**Comment by digigarlab** [comment]
It's not possible AFAIK, since some packages don't follow the convention of having a `dist/` folder.

If you really need to reduce the size of packages in production, you can use [`yarn autoclean`](https://yarnpkg.com/lang/en/docs/cli/autoclean/) (and to run `yarn --prod` to skip devDependencies)

**Comment by rally25rs** [comment]
If this is for local packages, then there is an open issue already: #2822 
If this is for remote packages, then no, but you can use `autoclean` to manually attempt to clean up files that you don't need.
