### ISSUE TITLE
how to reset the author info when `yarn init`?

### ISSUE THREAD

**Issue by udtrokia** [yarnpkg/yarn#5090]
So, I want to change default author info when `yarn init`(it appears as an old old info of mine)
I`ve tried to change my github config and npm account config 
none of them worked

**Comment by Simek** [comment]
Yarn uses his own config so you need to set author info directly thought yarn cli:
`yarn config set init-author-name [username]`
`yarn config set init-author-email [email]`

Commands mentioned above and other related to `init` are listed in docs:
https://yarnpkg.com/lang/en/docs/cli/init/#toc-setting-defaults-for-yarn-init

**Comment by udtrokia** [comment]
it works！thank you very much！@Simek
