### ISSUE TITLE
Yarn fetches (but does not install) devDependencies when using --production

### ISSUE THREAD

**Issue by rluba** [yarnpkg/yarn#5096]
Yarn tries to fetch _at least some_ `devDependencies` when running `yarn install --production`.

I’ve discovered this by accident because our production server does not have access to certain internal `devDependencies` and therefore `yarn install --production` fails when it tries to fetch the git dependency from our GitLab instance:

```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git@<…path…>/eslint-plugin.git
Directory: <current cwd>
Output:
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.
```
The dependency is defined as:
```
…
"devDependencies": {
    …
    "eslint-plugin-xxx": "git+ssh://git@<…path…>/eslint-plugin.git#v1.2.3"
}
```

Tested using yarn v1.3.2 and node v8.9.3 on Ubuntu 16.04 LTS

**Comment by rally25rs** [comment]
duplicate #3630

**Comment by rluba** [comment]
Thanks and sorry for missing #3630 in the first place.
