### ISSUE TITLE
BUG: `yarn list --json --production` chokes if devDependencies is not in package.json

### ISSUE THREAD

**Issue by smotaal** [yarnpkg/yarn#5100]
**Do you want to request a *feature* or report a *bug*?**

Bug: someone forgot to guard against undefined "devDependencies" here:

https://github.com/yarnpkg/yarn/blob/06910374874035a3388c42a6f6403b2b785e9993/src/cli/commands/list.js#L186-L188

**What is the current behavior?**

Missing "devDependencies" chokes `yarn list --json --production` but not `yarn list --json` (ahhh the irony - lol) and throws this:

```yaml
  type: error
  data: "An unexpected error occurred: \"Cannot convert undefined or null to object\"."
```

**If the current behavior is a bug, please provide the steps to reproduce.**

* Using `workspaces-experimental` and have a root without "dependencies" or "devDependencies".

* Script in `packages/who-cares` calls `yarn list --json --production` which *throws!*

* Without `--production` *does not throw* but *is not a solution!*

* Adding `"dependencies": {}` to  root package (seems logical enough) with `--production` still *throws!*

* Then adding `"devDependencies": {}` to  root package (seems completely pointless) with `--production` finally *works as required!*

**Important fact:** Ironically, when I retested by switching the order, ie just added `"devDependencies": {}` first and tested without having a "dependencies" field yarn gladly created that `"dependencies": {}` for me and did not just quit on me with confusing signs of discontent and undeserved retaliation.

**What is the expected behavior?**

* Yarn could handle a missing "devDependencies" the same way it does "dependencies" at a core level.

* Type guard like *this very minimal*:

```js
 export function getDevDeps(manifest: Object): Set<string> { 
   return new Set(Object.keys(Object(manifest.devDependencies)).map(key => `${key}@${manifest.devDependencies[key]}`));
 } 
```

**Please mention your node.js, yarn and operating system version.**

```yaml
  node: 9.3.0
  yarn: 1.3.2
  macOS: whatever the latest beta is
```

**Comment by iansu** [comment]
You don't even need any of the workspace stuff to reproduce this bug. Just create a package that has dependencies but no devDependencies and run `yarn list --production`.
