### ISSUE TITLE
No x64 MSI installer

### ISSUE THREAD

**Issue by gucciferXCIV** [yarnpkg/yarn#5107]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
MSI installs Yarn as 32 bit.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
I'd *like* to have a 64 bit installer as well.

**Please mention your node.js, yarn and operating system version.**

| Name | Version |
|--------|---------|
| nodejs | 9.3.0 |
| os | Windows |
| yarn | 1.3.2 |

**Comment by rally25rs** [comment]
AFAIK Yarn has no native code. It's completely JS, so 32 vs 64 bit shouldn't really matter. The install path might be the only thing different.

**Comment by BYK** [comment]
Hey @Daniel15 any ideas? I'm guessing this is not too hard?

**Comment by BYK** [comment]
The installer source is here: https://github.com/yarnpkg/yarn/blob/master/resources/winsetup/Yarn.wxs

**Comment by rally25rs** [comment]
We would want `ProgramFiles64Folder` on a 64 bit install, but managing 2 MSI installs for nothing but a directory change seems like a lot of work for no gain.

**Comment by Daniel15** [comment]
@rally25rs is right. Windows Installer doesn't officially support using the same installer for both 32- and 64-bit, so we'd need two separate installers to do this. Not sure if it's worth it.

**Comment by BYK** [comment]
I'm closing this ticket for the following reasons then:

 - 32-bit Windows is still a thing and we currently support it. Supporting this does not add any additional overhead
 - Yarn itself is platform independent so it doesn't matter whether the installer is 32-bits or 64-bits
 - All 64-bit Windows support our current 32-bit installer
 - There is nothing we would gain from making this change.

Thanks a lot for bringing this up. When 32-bit Windows becomes history, we can change this to be 64-bit only.

**Comment by Daniel15** [comment]
If anyone can work out a way to handle this with a single installer, please
feel free to send a pull request :)

**Comment by gucciferXCIV** [comment]
Oh no, I would *never* say to get rid of the 32 bit version. Lol I'm just uptight about my directory organization and don't like that all my Node related stuff is in the 64 bit folder, except Yarn. It'd be nice to have them all together, but I'm obviously not going to start mixing 32 and 64 bit programs in the same dir now, when I've always kept them separate in the past.

Anyways, if there's absolutely no benefit to making a 64 bit installer and it'd be, other than things like the name and where it's meant to be run, perfectly identical to the 32 bit version, then I agree, there really is no __need__ to make a 64 bit installer and this should be closed and won't really need to be reconsidered until a time comes where Yarn users are almost entirely using 64 bit processors.

**Comment by Daniel15** [comment]
I originally thought that this was not available, but It looks like Windows now has an environment variable `ProgramW6432` that can be used to get the 64-bit path from a 32-bit app. Previously, there was no way to get the 64-bit Program Files directory from a 32-bit app or installer, so your installer **needed** to be 64-bit to install into the 64-bit Program Files. 

Because this path is available to 32-bit apps, it's likely that the installer could be updated to use it, and we could have one installer that handles both 32-bit and 64-bit Program Files directories. Feel free to submit a pull request :)

**Comment by gucciferXCIV** [comment]
This may be the "previously it wasn't available" that you're (@Daniel15) talking about but [this](https://stackoverflow.com/questions/9712909/windows-setup-installer-project-forcing-installation-into-program-files-not) came up when I searched "make 32 bit installer install in program files" and adding "Programw6432" yielded nothing really useful, and neither did a search for "Programw6432" by itself. If this is simpler than I thought, I may be able to get it done sooner, but as of now, after about an hour of searching/reading, I just can't find anything useful on the topic. I'm guessing I'm just not asking the right question to get the answer I need, and hopefully that's the case, because it means I can easily be pointed in the right direction. Lemme know!
