### ISSUE TITLE
Resolutions-Tag failed when adding bower repositories

### ISSUE THREAD

**Issue by wehrstedt** [yarnpkg/yarn#5118]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
My package.json contains a bower component which referes to a private repository. If I add this component to the resolutions-Property in the package.json, the ```yarn install``` command failed with the following error message:

```
yarn   
yarn install v1.3.2   
[1/5] Validating package.json...   
[2/5] Resolving packages...   
error An unexpected error occurred:  
  "https://registry.yarnpkg.com/@bower_components%2fmyPrivatePackage1: Not found".
info If you think this is a bug, please open a bug report with the information provided in "E:\\contract\\yarn-error.log".   
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create the following package.json
```
{
    .
    .
    .
    "dependencies": {
        "@bower_components/myPrivatePackage1": "<url to my gitlab>#2.6.0",
        "@bower_components/myPrivatePackage2": "<url to my gitlab>#1.0.0"
    },
    "resolutions": {
        "@bower_components/myPrivatePackage1": "2.6.0"
    }
}
```

**What is the expected behavior?**
Yarn should be able to resolve resolutions for private bower components

**Please mention your node.js, yarn and operating system version.**
Node: v8.9.1
Yarn: 1.3.2

**Comment by rally25rs** [comment]
I don't have a test case set up for this, but have you tried putting the private URL in the resolution?

```
    "resolutions": {
        "@bower_components/myPrivatePackage1": "<url to my gitlab>#2.6.0"
    }
```

**Comment by rally25rs** [comment]
Closing this, as I believe this is the correct behavior for the way resolutions work. You are basically telling yarn "if anyone asks for `@bower_components/myPrivatePackage1` then use `2.6.0` from the NPM registry. If you include the private URL (as in my above comment) then it should resolve correctly to your private repo.

**Comment by wehrstedt** [comment]
Sorry, I was on vacation.

1. Including the URL to the private repo as you assumed works fine, thanks!
2. Then the output of ```yarn install --flat``` is not correct. If I run this command and choose the version of the package, yarn adds the resultions-property without the URL.

**Comment by rally25rs** [comment]
> Then the output of yarn install --flat is not correct.

Ah, ok, so the `resolutions` entry is being added when you run with `--flat` and make a version selection. That does feel like a bug 🐞 

Would you mind making a new issue with reproduction steps for that scenario?

**Comment by wehrstedt** [comment]
Done!

**Comment by wehrstedt** [comment]
I (or you) have to reopen this issue. After following your approach, I had the following package.json:
```
 "resolutions": {
        "@bower_components/myPrivatePackage1": "<url to my gitlab>#2.6.0"
    },
   flat: true
```

So I changed the resultions-entry by myself. Now I remove the yarn.lock-file and the node_modules folder and run `yarn install` again.
I expected that yarn would install the package `myPrivatePackage1` with version 2.6.0, because it's the version described in the resolutions-object, instead yarn asks me again which version of the module "myPrivatePackage1" I want to install. If I choose again the version I want to install, yarn changes the resolutions-entry back to
```
 "resolutions": {
        "@bower_components/myPrivatePackage1": "#2.6.0"
    }
```

If you now remove the yarn.lock-file and the node-modules folder and run `yarn install` again, it failes with the error described first:
```
yarn   
yarn install v1.3.2   
[1/5] Validating package.json...   
[2/5] Resolving packages...   
error An unexpected error occurred:  
  "https://registry.yarnpkg.com/@bower_components%2fmyPrivatePackage1: Not found".
info If you think this is a bug, please open a bug report with the information provided in "E:\\contract\\yarn-error.log".   
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
