### ISSUE TITLE
Support semver syntax for git urls

### ISSUE THREAD

**Issue by Fer0x** [yarnpkg/yarn#5126]
With v5.0.0 release NPM supports semver range when using git urls:  https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

Short example:

`
git+ssh://git@github.com:npm/npm#semver:^5.0
`

In NPM this feature was discussed [here](https://github.com/npm/npm/issues/3328)

Are there any chance to implement this in yarn?

**Comment by rally25rs** [comment]
It already works without the `semver:` portion, simply:

> git+ssh://git@github.com:npm/npm#^5.0

However we should probably support that `semver:` keyword for NPM compatibility. Honestly, I never even knew that was a thing that NPM supported until a week or 2 ago.

**Comment by iansu** [comment]
I've fixed a few bugs related to GitHub package patterns recently so I can take a look at this.
