### ISSUE TITLE
version yarn@1.3.2 cannot work under proxy while yarn@1.3.1 is work ok

### ISSUE THREAD

**Issue by anchoretics** [yarnpkg/yarn#5127]
version yarn@1.3.2 cannot work under proxy while yarn@1.3.1 is work ok

**Comment by rally25rs** [comment]
Please explain. What are your proxy settings?

**Comment by anchoretics** [comment]
sorry, i make some mistake that 1.3.1 also cannot work corectly, details:
`~ yarn add teaset`
`yarn add v1.3.2
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://github.com/facebookarchive/react-native-custom-components: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/anchor/workspace/react-native/react-native-app13/yarn-error.log".
`
My yarn config list:
`yarn config v1.3.2`
`info yarn config`
`{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.npm.taobao.org',
  'strict-ssl': true,
  'user-agent': 'yarn/1.3.2 npm/? node/v8.9.3 darwin x64',
  disturl: 'https://npm.taobao.org/dist',
  lastUpdateCheck: 1514470487501 }
info npm config
{ registry: 'https://registry.npm.taobao.org/',
  disturl: 'https://npm.taobao.org/dist' }
`
i dont have many time to test all the versions,but 0.23.4 is ok
(befor i changed the yarn version, i also cleaned yarn cache)

**Comment by anchoretics** [comment]
@rally25rs 
yarn@1.0.1 and yarn@1.3.2
![WX20171228-231001.png](https://i.loli.net/2017/12/28/5a45096d66992.png)
![WX20171228-230928.png](https://i.loli.net/2017/12/28/5a45096eae87d.png)

**Comment by anchoretics** [comment]
@rally25rs http://127.0.0.1:1087 is my shadowsocks's http proxy

**Comment by rally25rs** [comment]
fixed by #4903 but is not yet released. you could use a Yarn [nightly build](https://yarnpkg.com/lang/en/docs/nightly/) until we get the next release out.

**Comment by anchoretics** [comment]
tks.
