### ISSUE TITLE
yarn add `node-sass` never finish

### ISSUE THREAD

**Issue by lili21** [yarnpkg/yarn#5129]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

`yarn add node-sass`
![image](https://user-images.githubusercontent.com/4456380/34405079-30442f18-ebec-11e7-9b15-bb2fcb4bf400.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn add node-sass`

**Please mention your node.js, yarn and operating system version.**

node v9.3.0

npm v5.6.0

yarn v1.3.2

macOS 10.13.1

**Comment by lili21** [comment]
I tried `npm i node-sass` and downgrade to `v0.28.4`. all work as expecting.

**Comment by Simek** [comment]
It took a while (mainly because of node-gyp) but works on my machine.
Are you sure that was not a network or compilation time problem?

Versions: node v9.3.0 | npm v5.6.0 | yarn v1.3.2 | **macOS 10.13.2**

**Comment by Simek** [comment]
It took a while (mainly because of node-gyp) but works on my machine.
Are you sure that was not a network or compilation time problem?

Versions: node v9.3.0 | npm v5.6.0 | yarn v1.3.2 | **macOS 10.13.2**

```
$ yarn add node-sass
yarn add v1.3.2
[1/4] 🔍  Resolving packages…
[2/4] 🚚  Fetching packages…
[3/4] 🔗  Linking dependencies…
warning " > laravel-elixir-vue-2@0.3.0" has unmet peer dependency "vue@^2.1.0".
warning "laravel-elixir-vue-2 > sass-loader@4.1.1" has unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
[4/4] 📃  Building fresh packages…
success Saved lockfile.
success Saved 9 new dependencies.
├─ generate-function@2.0.0
├─ generate-object-property@1.2.0
├─ is-my-json-valid@2.17.1
├─ is-property@1.0.2
├─ jsonpointer@4.0.1
├─ lodash.mergewith@4.6.0
├─ node-sass@4.7.2
├─ stdout-stream@1.4.0
└─ true-case-path@1.0.2
✨  Done in 85.00s.
```

**Comment by jeffhuys** [comment]
On some systems, depending on speed and architecture, installing node-sass can take a long time. It may be compiling from source. @lili21 How long did you wait for the command to complete?

**Comment by lili21** [comment]
morn then ten minutes. It works now. maybe related to `node-gyp` and network.

**Comment by softmarshmallow** [comment]
Need more explanations.
this issue still occurs.

**Comment by moohkooh** [comment]
Same problem. On each yarn run, node-sass starting rebuild. That takes so much time.

**Comment by tobob** [comment]
yes, problem did not occur on npm, yarn rebuild node-sass from scratch

**Comment by tobob** [comment]
```
verbose 174.053 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/darwin-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/darwin-x64-64_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND host host:80

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234
[1/5] ⡀ fsevents
[-/5] ⡀ waiting...
[3/5] ⡀ node-sass
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
```

**Comment by DzonnyDZ** [comment]
I had the same problem. I gave it several hours.
Afterwards I tried
```
npm i node-sass
yarn add node-sass
```
And only then
```
yarn install
```
Now it worked.

**Comment by afsanefda** [comment]
It took more than 10 mins for me!

**Comment by miaozilong** [comment]
the fuck node-sass  
it always ....

**Comment by hktr92** [comment]
I'm having a build system and `yarn install` + node-sass is painfully slow... had to hack the system to actually do `yarn add --dev node-sass` to make the update process faster... we can't afford 10 minutes downtime per project for node-sass to do what it does on `yarn install`... 

so yeah, the only hack for now is to actually `yarn add --dev node-sass` or use node-sass-chokidar (if convenient)

**Comment by pierrealexaline** [comment]
...shit when you update, install ...etc !!! (i finished your phrase)  this seem to be the same for all :)

**Comment by singhvaibhavram** [comment]
So, it's not an error or a bug. I tried this on multiple machines, and worked like a charm on some while took 15-20 minutes on some. Can't do much about this.

**Comment by tgrushka** [comment]
Still a problem > 3 years later:
![image](https://user-images.githubusercontent.com/40548478/113447424-14ab4900-93b7-11eb-980f-f397d35f637f.png)

Yes, it's a bug. Definitely a bug.

My download speed from speedtest.net is > 500 Mbits/sec:
![image](https://user-images.githubusercontent.com/40548478/113447393-01987900-93b7-11eb-873b-ba3b06f4f807.png)

**Comment by 91bananas** [comment]
Still a problem, I sits. I waits. 
<img width="248" alt="Screen Shot 2021-05-14 at 9 29 11 AM" src="https://user-images.githubusercontent.com/1340610/118300496-d9606780-b496-11eb-9f81-c5cfb9ad5bd0.png">

**Comment by rally25rs** [comment]
Yarn executes a child shell process and runs whatever command `node-sass` lists in it's `package.json` then just waits for the process to exit. Yarn is not doing anything but waiting for a process to finish.

The only other thing I can think of that can cause an issue is if something in the `node-sass` build script tries to prompt the user for input. Yarn runs all the build script in parallel in child processes, and the `stdin` is not redirected down to these processes (because there isn't really a way to redirect `stdin` to 5 child processes simultaneously). So if the `node-sass` build script tries to prompt for user input, it might be sitting there waiting for input on `stdin` which it can't get.

You might try running `yarn install --ignore-scripts` to skip all the custom build scripts, then execute the node-sass ones manually to see if there is any additional output:

```sh
yarn install --ignore-scripts
cd node_modules/node-sass/
yarn run install
yarn run postinstall
```

**Comment by Cwejman** [comment]
I've had troubles with node-sass not finishing many times lately, not sure if it actually hung or I was just impatient. I tried the approach mentioned by @rally25rs and it finished after 120 seconds. So for anyone having troubles give it a couple of minutes or try to do the mentioned approach if you like to see it progress.

I'll get back here if I actually catch the install scripts hanging.

**Comment by dh-pt** [comment]
This is still an issue.

**Comment by pierrealexaline** [comment]
issue, bug or whatever you want, it is not developer-friendly, this cost a lost of time to many people and i think it will be good to resolve this after years ! (since 1 year it seems better for me, but i don't know why ! and i can not help ...) ....thanks and good luck !

**Comment by dylanh724** [comment]
There's really nothing we can do? The creators of this magical software can do crazy futuristic things, but not figure out a workaround? I'm a bit skeptical. Like the guy above said, call it what you want, but it's an extreme inconvenience and something (including the possibility of a workaround) should be done.

**Comment by 91bananas** [comment]
At this point I've just abandoned all hope, killed off SASS/SCSS and moved to LESS, it does all the same things with 100% less of the headaches.

**Comment by SwapnilSoni1999** [comment]
with node version 18 its still the same scenario :/
