### ISSUE TITLE
yarn install error Unexpected token } in JSON at position 299"

### ISSUE THREAD

**Issue by fatirjhon** [yarnpkg/yarn#5136]
Windows 7 64 bit

error An unexpected error occurred: "C:\\laragon\\www\\laravel-vue\\package.json: Unexpected token } in JSON at position 299".

package.json file :
`{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "laravel-elixir": "^6.0.0-14",
    "laravel-elixir-vue-2": "^0.3.0",
    "laravel-elixir-webpack-official": "^1.0.2",
  }
}
`

**Comment by Simek** [comment]
You just need to remove comma after last dependency i.e.: `laravel-elixir-webpack-official": "^1.0.2",` and `yarn install` will work fine.

With comma at the end even `npm install` fails. Also note that Yarn supports Node versions which do not include trailing commas in objects feature.

**Comment by rally25rs** [comment]
Closing this as it is an issue with invalid JSON, not a Yarn bug.
