### ISSUE TITLE
Node version not found with make

### ISSUE THREAD

**Issue by dkotrada** [yarnpkg/yarn#5137]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Yarn does not recognise installed nodejs

> Yarn requires Node.js 4.0 or higher to be installed.

**If the current behavior is a bug, please provide the steps to reproduce.**
Running for example Makefile like this:
```
run:
	yarn start

.PHONY: run
```
with `make run`

Produces this message:

> Yarn requires Node.js 4.0 or higher to be installed.

**What is the expected behavior?**

Running `yarn start` in Terminal should be the same as running it via Makefile.

**Please mention your node.js, yarn and operating system version.**
Yarn installed as described here: https://yarnpkg.com/lang/en/docs/install/
Node isn't installed via apt on Ubuntu, but with nvm

```sh
$ yarn env
yarn run v1.3.2
$ echo $NODE
/home/user/.nvm/versions/node/v8.9.3/bin/node
Done in 0.09s.
```

```sh
$ nvm ls
        v6.11.5
->       v8.9.3
default -> 8 (-> v8.9.3)
node -> stable (-> v8.9.3) (default)
stable -> 8.9 (-> v8.9.3) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> v8.9.3)
lts/argon -> v4.8.7 (-> N/A)
lts/boron -> v6.12.2 (-> N/A)
lts/carbon -> v8.9.3
```

```sh
uname -a
Linux t420 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rally25rs** [comment]
The Yarn shell script runs `command -v node` to see if the system knows about a `node` command:

```
~ 🐒   command -v node
/Users/jvalore/.nvm/versions/node/v8.5.0/bin/node
```

and then does `exec node "$basedir/yarn.js" "$@"` to actually run Yarn.

I'm guessing `node` isn't on your `PATH` when running from make?

**Comment by dkotrada** [comment]
Hi when I run in terminal `echo $PATH` I get `/home/alfa/.nvm/versions/node/v8.9.3/bin:` 

and the same as you typed. I get:
```
/home/alfa/.nvm/versions/node/v8.9.3/bin:
```

What do you mean with 
> node isn't on your PATH when running from make

Use make some other path?

**Comment by dkotrada** [comment]
Solved it for me. The problem was not Makefile but in IntelliJ Idea `"Run > Edit Configurations > + > Bash"` For some reason yarn can not be configured there. But this isn't yarn bug. :)

**Comment by oquirozm** [comment]
@dkotrada could you elaborate on how you solved it? I'm having the same issue and don't use IntelliJ at all.

**Comment by oquirozm** [comment]
@dkotrada yeah, I researched the whole thing and I think it has to do with the $PATH that is available when running commands remotely with SSH. So I think is there's no way, actually.
