### ISSUE TITLE
Appear console screen "npm" after running command " yarn run prod"

### ISSUE THREAD

**Issue by HoangBaLinh** [yarnpkg/yarn#5139]
After using  "yarn run prod " to run web production , i see display  the console screen 'npm' about 5-6 second then it turn off.  I remove npm but it still appear again after using yarn run prod.
is this an error with yarn ?

**Comment by rally25rs** [comment]
What does your `prod` script do? Perhaps something in the script is running an `npm` command? Can you share your `package.json` file?
