### ISSUE TITLE
Missing files when "yarn"

### ISSUE THREAD

**Issue by tborychowski** [yarnpkg/yarn#5142]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When installing [sshpk](https://github.com/joyent/node-sshpk) package `yarn` seems to remove a file.

**If the current behavior is a bug, please provide the steps to reproduce.**
- `yarn add sshpk`
- after install completes - the `sshpk` folder does not have this file: [lib/signature.js](https://github.com/joyent/node-sshpk/blob/master/lib/signature.js)

**What is the expected behavior?**
The file should be there :-)
When I run `npm i` - the file is there and everything works.

**Please mention your node.js, yarn and operating system version.**
node@v8.7.0
npm@5.4.2
yarn@1.3.2
macos@10.13.2

**Comment by rally25rs** [comment]
Unable to reproduce:

```
~/Projects/yarn-test 🐒   yarn add sshpk
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 9 new dependencies.
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ bcrypt-pbkdf@1.0.1
├─ dashdash@1.14.1
├─ ecc-jsbn@0.1.1
├─ getpass@0.1.7
├─ jsbn@0.1.1
├─ sshpk@1.13.1
└─ tweetnacl@0.14.5
✨  Done in 0.54s.

~/Projects/yarn-test 🐒   head node_modules/sshpk/lib/signature.js
// Copyright 2015 Joyent, Inc.

module.exports = Signature;

var assert = require('assert-plus');
var algs = require('./algs');
var crypto = require('crypto');
var errs = require('./errors');
var utils = require('./utils');
var asn1 = require('asn1');
```

Not sure why that file wouldn't exist. You could see if the file exists in the cache:

```
~/Projects/yarn-test 🐒   cd `yarn cache dir`

~/Library/Caches/Yarn/v1 🐒   cd npm-sshpk-1.13.1-512df6da6287144316dc4c18fe1cf1d940739be3/

~/Library/Caches/Yarn/v1/npm-sshpk-1.13.1-512df6da6287144316dc4c18fe1cf1d940739be3 🐒   ls lib/
algs.js        dhe.js         errors.js      formats        index.js       private-key.js ssh-buffer.js
certificate.js ed-compat.js   fingerprint.js identity.js    key.js         signature.js   utils.js
```

**Comment by tborychowski** [comment]
This is really strange.
This is what I get when I run `yarn` in my project (sshpk is a dependency of a dependency):
```sh
~/Projects/_playground/filer (master)> yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info 7zip-bin-win@2.1.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/7] ⠠ ref: gyp info using node@8.7.0 | darwin | x64
[2/7] ⠠ ref: gyp info using node@8.7.0 | darwin | x64
[3/7] ⠠ runas: using node@8.7.0 | darwin | x64
[4/7] ⠠ bson
error ~/Projects/_playground/filer/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: ~/Projects/_playground/filer/node_modules/electron
Output:
module.js:529
    throw err;
    ^

Error: Cannot find module './signature'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/Projects/_playground/filer/node_modules/sshpk/lib/certificate.js:9:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

and the cache doesn't have it also:
```sh
~/Library/Caches/Yarn/v1/npm-sshpk-1.13.1-512df6da6287144316dc4c18fe1cf1d940739be3/lib> ls
algs.js        dhe.js         errors.js      formats        index.js       private-key.js utils.js
certificate.js ed-compat.js   fingerprint.js identity.js    key.js         ssh-buffer.js
```

I did however cleaned yarn's cache (thanks for the idea) and removed the `yarn.lock` file and it seems to work now!

Thanks and sorry for reporting a non-issue :-)

**Comment by jedwards1211** [comment]
I ran into a similar issue and realized why: my yarn cache got messed up because I accidentally ran two `yarn install` commands simultaneously.  (I run my server process and webpack dev server process in separate terminals and both run `yarn install` if the `node_modules` are out of date)

**Comment by zhongsp** [comment]
I ran into this issue many times on our Jenkins server. There are maybe several projects are running `yarn install` at the same time on the server machine. And yarn reports packages installation is success, but when building the app (e.g., Angular app), it reports random files are not found error.

Each time this happens, I use `yarn cache clean` to fix it. But till now, I didn't find the root cause about this issue.. @rally25rs 

We're using yarn 1.x

**Comment by lieberlois** [comment]
> I ran into this issue many times on our Jenkins server. There are maybe several projects are running `yarn install` at the same time on the server machine. And yarn reports packages installation is success, but when building the app (e.g., Angular app), it reports random files are not found error.
> 
> Each time this happens, I use `yarn cache clean` to fix it. But till now, I didn't find the root cause about this issue.. @rally25rs
> 
> We're using yarn 1.x

THANK YOU SO MUCH!

I've had this problem for ages now, we're starting a new Node project at work on monday and we're using yarn. I had already given up until i tried yarn cache clean <3
