### ISSUE TITLE
Why yarn don't use symlink?

### ISSUE THREAD

**Issue by jefer94** [yarnpkg/yarn#5155]
**Do you want to request a *feature* or report a *bug*?**

I request a feature.

**What is the current behavior?**

Yarn is good as package manager, but when I'd use yarn add something, it do a integrity test, check the checksums, check package.json and yarn.lock, and resolve de dependencies, for finally do a copy of the cache in node_packages, it's in development environment is unnecesary because only want add a dependencie for my project, this features are great for production environment.

Also in a Celeron with Google Chrome, with Yarn instaling dependencies, my machine is lag, ins't because of Google Chrome, the integrity check with the copy folder instead of used symlinks harms performance, I only want that if I forgot instaled a little dependency like express, do not have to wait for yarn to do all this again, if I forgot other little dependecy the time that i wait multiply by three, it's worrying. 

**If the current behavior is a bug, please provide the steps to reproduce.**

[Choco Algorithm](https://github.com/jefer94/algorithm)

**What is the expected behavior?**

That yarn will have a development mode with symlinks, and a production mode.

**Please mention your node.js, yarn and operating system version.**

| software         | version(s)
| ---------------- | -------
| Node             | 9.2.0
| Yarn              | 1.3.2-20180102.1415
| Operating System | Arch Linux x86_64

**Comment by jefer94** [comment]
If you're reproduce the error, create a .env file with 
```js
NODE_ENV=development
```

**Comment by swrobel** [comment]
See here: https://github.com/yarnpkg/yarn/issues/499

**Comment by BYK** [comment]
To be able to install a deterministic tree, Yarn needs to calculate the whole tree even if you change a single dependency. This would be the same even if we used symlinks everywhere.

If you have a more concrete implementation in mind that wouldn't break our strong guarantees, feel free to submit an RFC here: https://github.com/yarnpkg/rfcs

**Comment by pauldraper** [comment]
See #2125
