### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/gulp-watch/-/gulp-watch-4.3.11.tgz: Request failed \"404 Not Found\""

### ISSUE THREAD

**Issue by pimchest** [yarnpkg/yarn#5163]
**I try to install on Raspberry PI VSCode and use :**

**Input:**
    `sudo ./scripts/npm.sh install --arch=armhf`
**Output:**

**This worked**
_Done in 27.57s.
yarn install v1.3.2
warning package.json: No license field
warning code-oss-dev-smoke-test@0.1.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ tsc
Done in 21.26s._ 
**...but in the end**

```
yarn install v1.3.2
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-watch/-/gulp-watch-4.3.11.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/pi/vscode/build/lib/watch/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
`sudo nano /home/pi/vscode/build/lib/watch/yarn-error.log`

```
wrappy@1:
    version "1.0.2"
    resolved "https://registry.yarnpkg.com/wrappy/-/wrappy-
1.0.2.tgz#b5243d8f3ec1aa35f1364605bc0d1036e30ab69f"
 xtend@~4.0.1:
    version "4.0.1"
    resolved "https://registry.yarnpkg.com/xtend/-/xtend-4.0.1.tgz#a5c6d532be656e23db820efb943a1f04998d63af"

Trace:
  Error: https://registry.yarnpkg.com/gulp-watch/-/gulp-watch-4.3.11.tgz: Request failed "404 Not Found"
      at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:59356:26)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at Request.module.exports.Request.onRequestResponse (/usr/local/lib/node_modules/yarn/lib/cli.js:123971:10)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:563:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:452:20)
      at emitOne (events.js:115:13)
```
Variables
```
pi@raspberrypi:~/vscode $ yarn --version
1.3.2
```
```
pi@raspberrypi:~/vscode $ node --version
v8.0.0
```
**Perhaps it helps:**

```
Raspberry Pi 3 Model B Rev 1.2

cat /etc/issue
Raspbian GNU/Linux 9 \n \l

cat /etc/debian_version
9.3
```

**Comment by wilomgfx** [comment]
Im getting the same error for an other package "An unexpected error occurred: "https://registry.yarnpkg.com/timed-out/-/timed-out-4.0.1.tgz: Request failed \"404 Not Found\""."

**Comment by kyleholzinger** [comment]
Ditto for me on various different packages. 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/capture-stack-trace/-/capture-stack-trace-1.0.0.tgz: Request failed \"404 Not Found\"".
```

```
error An unexpected error occurred: "https://registry.yarnpkg.com/capture-stack-trace/-/capture-stack-trace-1.0.0.tgz: Request failed \"404 Not Found\"".
```

**Comment by nsthorat** [comment]
I'm getting the same thing on different packages:

`error Received malformed response from registry for "timed-out". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Received malformed response from registry for "pinkie-promise". The registry may be down.`

**Comment by hinok** [comment]
https://status.npmjs.org/

<img width="864" alt="zrzut ekranu 2018-01-06 o 21 16 55" src="https://user-images.githubusercontent.com/1313605/34643588-f335ba78-f326-11e7-8b55-9c92085fce67.png">


---

```
21:00 $ yarn add react-popper
yarn add v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/require-from-string/-/require-from-string-1.2.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "...frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
`yarn cache clean` doesn't solve problem.

http://status.yarnpkg.com reports that everything is good. Don't know where to look to solve the issue.

**Comment by nsthorat** [comment]
FYI: https://github.com/npm/registry/issues/255

**Comment by andrewquartey** [comment]
The issue has been resolved now. My app build succeeded now

**Comment by pimchest** [comment]
Worked.

**Comment by givanse** [comment]
I was seeing a similar error because I had a bad `~/.npmrc`.

**Comment by libasoles** [comment]
Today  `yarn cache clean` actually worked for me.

Issue arised after upgrading yarn from 1.9 to 1.12, btw.

**Comment by Mandeepdhundwa** [comment]
Something is wrong with your node installation. You can toggle registry.yarnpkg.com with encrypted.google.com in the above code and it should fail too.
