### ISSUE TITLE
Installation Problem: can not run "yarn install"

### ISSUE THREAD

**Issue by metukan** [yarnpkg/yarn#5179]
**Which operating system are you using:**
Mac OS sierra 10.12.6

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I am follwing the steps on the yarn website installing yarn through brew. But I can not get it to work. I am fairly new to this so bare with me. 

**When running yarn check:**
success Folder in sync.

**When running yarn version:**
yarn version v1.3.2
error Couldn't find a package.json file in "/Users/gustafhard"
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.

**When running yarn open** 
yarn version v1.3.2
error Couldn't find a package.json file in "/Users/gustafhard"
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.

**When running yarn install**
Gustaf123:~ gustafhard$ yarn install
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
info Lockfile not saved, no dependencies.
✨  Done in 0.05s.

**Comment by rally25rs** [comment]
Based on your path I'm guessing you aren't in a directory that contains a project and a `package.json` file.

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
