### ISSUE TITLE
Yarn global add current directory

### ISSUE THREAD

**Issue by ForbesLindesay** [yarnpkg/yarn#5199]
In npm, I can run `npm i -g` to take the package in the current folder and install it globally.  This is really useful when working on CLIs because you can install it globally on your machine and try it out before publishing to npm.  When I run `yarn global add` with no further parameters, it doesn't seem to do anything.  Is there an equivalent command for yarn?

**Comment by lwille** [comment]
Give this a try:

```bash
yarn global add file:$PWD
```
references: 
https://yarnpkg.com/en/docs/cli/add
#2291

**Comment by ForbesLindesay** [comment]
That seems to work, relative path name support would help, as would documentation improvements, but it does seem to work.

**Comment by DanielRuf** [comment]
Well, either I did something wrong or there is a bug. Yarn tries to connect to the npm registry and throws a 405 error.

**Comment by adwher** [comment]
Use the absolute path, cuz the relative path used by `yarn global` is (in Windows case) Appdata, and you have to use the absolute path to specify your project folder to be global.

**Comment by DanielRuf** [comment]
> Use the absolute path, cuz the relative path used by `yarn global` is (in Windows case) Appdata, and you have to use the absolute path to specify your project folder to be global.

I can use pwd in Git Bash so this is not the issue here ;-)

**Comment by adwher** [comment]
I dont use Git bash, I use cmd and for me use the absolute path woking 😄 Greetings

**Comment by jdthorpe** [comment]
This works on Git Bash for Windows: `yarn global add $PWD`
