### ISSUE TITLE
Install a single package from devDependencies when yarn.lock exists?

### ISSUE THREAD

**Issue by eyalzek** [yarnpkg/yarn#5201]
I have a `package.json` that declares a X `dependencies` and Y `devDependencies`. I want to all the dependencies and only several of the the `devDependencies` (using the version which is locked inside `yarn.lock`). Considering I have the following package and lock:
https://gist.github.com/anonymous/78a6a2d2ff68c5a28640e9f6381a1652

I would expect that `yarn add mocha` would install ONLY mocha with the version specified in the lock file. In reality, running this command install ALL of my `dependencies` & `devDependencies`.
This doesn't sound like the correct behavior but I might be wrong, is there a way to achieve that type of behavior?

What I would ideally want to do is:

```
$ yarn install --frozen-lockfile --non-interactive --prod # install dependencies

$ yarn add mocha # install only a single dev dependency using the version from the lock
```

**Comment by BYK** [comment]
To be able to install a deterministic tree, Yarn needs to calculate the whole tree even if you change a single dependency so this is the expected behavior and cannot really change.

Moreover, when you run `yarn add mocha`, you tell Yarn to add mocha as a regular dependency (not dev) and to install its latest version since you don't define a version range.

If your working directory is missing some dependencies that are defined in your lock file, simply running `yarn` would make yarn install them.

**Comment by zyf0330** [comment]
In my situation, I need `tsc` to build. I have added `typescript` into dev deps, and when building I just want to add only `typescript`dev deps and all production deps. Running `yarn` will install all dev deps.
How should I do to just install `typescript` dep which is already in yarn.lock?

**Comment by mattaningram** [comment]
This is an incredibly annoying issue for me. We work with docker so we don't want any of our packages installed locally (that just leads to confusion) since they are all in our docker container. However I need our specific version of `babel-eslint` installed on my machine so my linting works in Atom or VSCode.

Is there seriously no way to ONLY install the version of `babel-eslint` that is already determined in `yarn.lock`? The dependency is already determined, it doesn't need to calculate the whole tree.

**Comment by almir-campos** [comment]
## Update on 2021

Currently you can install a single package with `yarn`. Here's an example from https://jestjs.io/docs/getting-started:

`yarn add --dev jest`

**Comment by stemis** [comment]
I've developed a workaround that grabs your lockfile version and installs only that version.

This is for my docker build in Yarn Classic(v1) to install only a single package.
Make sure not to copy your package.json in.

```sh
COPY yarn.lock .
PACKAGE_NAME='my/package' \
  && LINE_NUMBER=`cat yarn.lock | grep -n "\"$PACKAGE_NAME@.*:" | cut -f1 -d:` \
  && VERSION=`cat yarn.lock | sed -n $((LINE_NUMBER + 1))p | sed 's/.*version \"\(.*\)\"/\1/'` \
  && yarn add ${PACKAGE_NAME}@${VERSION}
```
Replace `PACKAGE_NAME` with your package name

**Comment by glensc** [comment]
@almir-campos your [solution] does not respect `yarn.lock` at all. please edit your comment to outline that.

**Comment by glensc** [comment]
@stemis I believe your [solution](https://github.com/yarnpkg/yarn/issues/5201#issuecomment-868421786) contacts npm registry for finding info for specified package, is it possible to do that without such behavior?

I'm thinking maybe it's possible to move the dependency from "devDependencies" to "dependencies" using some `jq` mastery and then just run `yarn install --production`. this way it won't attempt to do any npm registry lookup to find package version

**Comment by glensc** [comment]
I've leveled up my [previous solution](https://github.com/yarnpkg/yarn/issues/5201#issuecomment-1059988319):
1. `tsc` needs some more `@types/*` packages
2. make installable packages configurable via `tscDependencies` section
3. be compatible with alpine (bashism not allowed)

example `package.json`
```json
...
  "devDependencies": {
    "@tsconfig/node16": "^1.0.2",
    "@types/jest": "^27.4.1",
    "@types/node": "^16",
    "@types/semver": "^7.3.9",
    "husky": "^7.0.4",
    "is-ci": "^3.0.1",
    "jest": "^27.5.1",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.2"
  },
  "tscDependencies": [
    "@tsconfig/node16",
    "@types/node",
    "@types/semver",
    "typescript"
  ],
```

This goes to my `Dockerfile`:

```dockerfile
# syntax = docker/dockerfile:1.3-labs

....

# Only mount files needed for yarn run, for efficient image layer caching
RUN \
  --mount=type=cache,id=yarn,target=/usr/local/share/.cache/yarn \
  --mount=type=bind,source=./package.json,target=./package.orig.json \
  --mount=type=bind,source=./yarn.lock,target=./yarn.lock \
  --mount=type=bind,source=./.yarnrc,target=./.yarnrc \
<<eot
  set -eux

  apk add jq
  cp package.orig.json package.json

  # https://github.com/yarnpkg/yarn/issues/5201#issuecomment-1059988319
  add_dep() {
    local package="$1" version
    version=$(jq -r --arg package "$package" '.devDependencies[$package]' package.json)
    jq --arg package "$package" --arg version "$version" '.dependencies[$package] |= $version' package.json > tmp
    mv -f tmp package.json
  }

  # Install only needed dependencies for tsc
  # Read package names from tscDependencies section
  install_tsc_deps() {
    local package
    set -- $(jq -r '.tscDependencies[]' package.json)
    for package in "$@"; do
     add_dep "$package"
    done
  }

  install_tsc_deps
  yarn install --frozen-lockfile --no-scripts --production
eot
```

**Comment by topolanekmartin** [comment]
> I've developed a workaround that grabs your lockfile version and installs only that version.
> 
> This is for my docker build in Yarn Classic(v1) to install only a single package. Make sure not to copy your package.json in.
> 
> ```shell
> COPY yarn.lock .
> RUN PACKAGE_NAME='my/package' \
>   && LINE_NUMBER=`cat yarn.lock | grep -n "\"$PACKAGE_NAME@.*:" | cut -f1 -d:` \
>   && VERSION=`cat yarn.lock | sed -n $((LINE_NUMBER + 1))p | sed 's/.*version \"\(.*\)\"/\1/'` \
>   && yarn add ${PACKAGE_NAME}@${VERSION}
> ```
> 
> Replace `PACKAGE_NAME` with your package name

Pretty complicated. I think I found more elegenat and more simple way how to find out installed package version:

```Dockerfile
COPY yarn.lock .
RUN PACKAGE_NAME="my/package" \
    && PACKAGE_VERSION=$(yarn list --pattern $PACKAGE_NAME | grep "${PACKAGE_NAME}@" | sed "s/${PACKAGE_NAME}@//g" | sed "s/└─ //g") \
    && yarn add ${PACKAGE_NAME}@${PACKAGE_VERSION}
```

**Comment by glensc** [comment]
elegant version is here:
- https://github.com/yarnpkg/yarn/issues/5201#issuecomment-1098199645

**Comment by topolanekmartin** [comment]
@glensc I am not familiar with this syntax, so probably I am wrong. But do you look up for package version in `package.json`? Because that version doesn't need to match up with installed version.

**Comment by glensc** [comment]
@topolanekmartin the code just moves items listed in tscDependencies from  devDependencies to dependencies. the actual version comes from the lock file.

**Comment by topolanekmartin** [comment]
@glensc Ah, I see. I have slightly different use case. I need for my E2E test install only few packages from my package.json. But I have to admit that I reuse yout idea with custom section in package.json. Thanks for that! :)

**Comment by glensc** [comment]
@topolanekmartin you could clear `"dependencies"`, re-fill it, and then run `yarn install --frozen-lockfile --no-scripts --production`. this way lock file will be used, doing `yarn add` could resolve to a different version that was in lock file. some packages have `"*"` as dependencies, so your build will not be stable with `yarn add package@version` because the sub-dependencies will be resolved again. besides running `yarn add` is slower than running `yarn` once.

**Comment by glensc** [comment]
looking at your code, perhaps it's just easier for you to create `package.json` and `yarn.lock` in `e2e` dir? simple and more straightforward for new developers in your project.

**Comment by glensc** [comment]
@mattaningram: can you update your post to add info on how to do that with npm?
- https://github.com/yarnpkg/yarn/issues/5201#issuecomment-511945863

**Comment by glensc** [comment]
I've created npm package for the script I had [previously written with shell and jq](https://github.com/yarnpkg/yarn/issues/5201#issuecomment-1098199645):
- [yarn-install-dev@0.0.5](https://www.npmjs.com/package/yarn-install-dev/v/0.0.5)

currently supports only passing package names on command line.

quickstart:

**1. add typescript to `devDependencies`** (development)
```
yarn add --dev typescript @types/node
```

**2. at deploy/ci/whatever:**
```sh
npm install -g yarn-install-dev
yarn-install-dev typescript @types/node
```
