### ISSUE TITLE
please use child_process.execFile rather than child_process.exec

### ISSUE THREAD

**Issue by simevo** [yarnpkg/yarn#5208]
Looking at `src/util/child.js`, it appears yarn is launching external commands with [`child_process.exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) which spawns a shell then executes the command within that shell, rather than with the more efficient  **and more secure** [`child_process.execFile`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) which does not spawn a shell, and spawns the specified executable file directly as a new process.

This also means you need `puka` to sanitize the string passed to `child_process.exec`.

Also see http://bonedaddy.net/pabs3/log/2014/02/17/pid-preservation-society/

Thanks !

**Comment by BYK** [comment]
Most of the commands we run expect to be in a shell so it is unlikely that this will change. Thanks for the suggestion.

If you feel strongly about this, I encourage you to submit a PR, demonstrating that existing tests pass and we'll happy to merge it.
