### ISSUE TITLE
Excluding local modules devDependencies

### ISSUE THREAD

**Issue by shqld** [yarnpkg/yarn#5210]
**Do you want to request a *feature* or report a *bug*?**

feature request: Installing local modules without their devDependencies

**What is the current behavior?**
Yarn includes local modules' devDependencies under `node_modules/{local module}/node_modules`.

**What is the expected behavior?**
- Excluding local modules' devDependencies as default
- Or providing options as a CLI argument

**Please mention your node.js, yarn and operating system version.**
- nodejs: 8.7.0
- yarn: 1.3.2
- OS: macOS High Sierra 10.13.1

**Comment by kaylieEB** [comment]
You can use `--production`, right?  https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production-true-false
