### ISSUE TITLE
What is the proper way to update yarn.lock to latest versions?

### ISSUE THREAD

**Issue by akosyakov** [yarnpkg/yarn#5219]
I use `latest` as a version for `@theia/core` dependency. After the first install, `v0.2.3` was locked in `yarn.lock`, which was the latest version by then. Now `latest` is `v0.3.2` and I want to upgrade `yarn.lock` to it. How can I do it?

I've tried `yarn --force` but it does not seem to do anything. Is it expected?

As a workaround, I've deleted `yarn.lock` and run `yarn` again.

**Comment by rally25rs** [comment]
I believe the command `yarn upgrade @theia/core --latest` should be what you want.

That should update `package.json` to point to the latest version number (probably `^0.3.2`) and also update the `yarn.lock` file.

**Comment by armeh429** [comment]
ERR MSG :(Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.)
i hade this error on my project . how can i fix it?
