### ISSUE TITLE
Incorrect order of package versions

### ISSUE THREAD

**Issue by IvanGoncharov** [yarnpkg/yarn#5220]
**Do you want to request a *feature* or report a *bug*?**

🐞 

**What is the current behavior?**

If I specify incorrect package version inside `package.json` and run `yarn` I'm presented with a following:
![image](https://user-images.githubusercontent.com/8336157/34952246-c30724ac-fa21-11e7-91ee-3e0048487682.png)
Order of versions doesn't make any sense and it's very easy to press enter thinking you select the latest version and then spend a lot of time debugging.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Add package with an incorrect version to `package.json`. `@types/react` in my case.
2. Run yarn

**What is the expected behavior?**

Versions sorted according to semantic version spec.

**Please mention your node.js, yarn and operating system version.**

```
$ yarn --version
1.3.2
$ node --version
v9.3.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114
```

This bug is pretty easy to fix it's enough to change this line:
https://github.com/yarnpkg/yarn/blob/dc7057688fd0e8a60653b99bf7a78939a35d7fb4/src/resolvers/registries/npm-resolver.js#L70

Instead of `Array. reverse` it should use [rsort](https://github.com/npm/node-semver/blame/master/semver.js#L586) from `semver` which is [already required](https://github.com/yarnpkg/yarn/blob/master/src/resolvers/registries/npm-resolver.js#L17) in this file.

**Comment by rally25rs** [comment]
It looks like they are currently listed in the order that the registry presented them in, which appears to be the date at which is was published:

```
      ...
     '16.0.32': '2018-01-03T01:49:43.086Z',
     '16.0.33': '2018-01-03T08:21:04.192Z',
     '16.0.34': '2018-01-03T21:21:59.131Z',
     '15.6.11': '2018-01-03T21:22:01.427Z' },
```

**Comment by AlexLandau** [comment]
This also isn't consistent across registry implementations. We have an Artifactory-backed registry where the output looks like this:

```
? Please choose a version of "lodash" from this list: (Use arrow keys)
❯ 1.2.0 
  4.14.1 
  4.14.2 
  4.9.0 
  1.2.1 
  2.4.1 
  2.4.0 
  2.4.2 
  2.0.0 
  3.2.0 
  3.6.0 
  4.4.0 
  0.3.0 
  4.0.1 
  4.0.0 
  4.14.0
(etc.)
```
