### ISSUE TITLE
P: Not all dependencies are met

### ISSUE THREAD

**Issue by Vivalldi** [yarnpkg/yarn#5224]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Missing dependencies for a module installed vis yarn.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn add https://github.com/HiDeoo/intro.js-react#a475b79` only to find that it's dependencies are not installed. If I move into the directory and run `npm install` it's dependencies are then met.

**What is the expected behavior?**
That all dependencies would be met (including the dependencies of the submodule)

**Please mention your node.js, yarn and operating system version.**
Node: v8.9.1
Yarn: 1.3.2
OS: macOS 10.13.2

**Comment by rally25rs** [comment]
Which dependencies are missing?

**Comment by rally25rs** [comment]
The `package.json` in `https://github.com/HiDeoo/intro.js-react` has no `dependencies` so there is nothing to install. `NPM` doesn't install any either:

```
~/Projects/yarn-test 🐒   npm install https://github.com/HiDeoo/intro.js-react#a475b79
npm WARN intro.js-react@0.1.5 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN intro.js-react@0.1.5 requires a peer of intro.js@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN yarn-test@1.0.0 No description
npm WARN yarn-test@1.0.0 No repository field.

+ intro.js-react@0.1.5
updated 1 package in 1.421s

~/Projects/yarn-test 🐒   ls node_modules/
intro.js-react
```

**Comment by Vivalldi** [comment]
I just realized that this is a package issue. For some odd reason when running `npm install` in the package it also runs the build command which is apparently required. Will discuss with repo manager
