### ISSUE TITLE
Something wrong when run under `spawn` subprocess and pass a empty string as argument

### ISSUE THREAD

**Issue by HairyRabbit** [yarnpkg/yarn#5228]
**Do you want to request a *feature* or report a *bug*?**

Bug, maybe :)

**What is the current behavior?**

```sh
error Received malformed response from registry for undefined. The registry may be down.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

some code like: 

```js
const { spawn } = require('child_process')

const yarn = spawn('yarn.cmd', [ 'add', 'jquery', ''])
//-------------------------------------------------^ pass a empty string as arguments

yarn.stdout.on('data', data => console.log(data.toString()))
yarn.stderr.on('data', data => console.log(data.toString()))
yarn.on('close', code => console.log(code))
```

got below output:

![default](https://user-images.githubusercontent.com/5752902/34972420-60e63344-fabc-11e7-80a9-6808c8654801.png)

**Please mention your node.js, yarn and operating system version.**

```sh
os: win10.0.15063
node: v8.5.0
yarn: 1.4.0
```

**Comment by rally25rs** [comment]
I think you can reproduce that on the command line:

```
~/Projects/yarn-test 🐒   yarn add jquery ''
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

but why pass an empty string? It's not really a valid argument.

**Comment by HairyRabbit** [comment]
Humm,,, looks not a bug. I write a lib parse the add flag, e.g --dev to DEV, the default value was a blank string. but same code works with npm: 

```js
spawn('npm.cmd', [ 'add', '', 'jquery', ''])
```
![image](https://user-images.githubusercontent.com/5752902/34998678-b09e2794-fb1a-11e7-8714-9c4a630b45be.png)

By the way, is any way to use yarn as a lib? I want to install modules without use cli. 😘

**Comment by HairyRabbit** [comment]
Yeap, I got it for my own parser. Thanks for your answer. Hope this feature implemented in the future.
