### ISSUE TITLE
Yarn creating not valid yaml yarn.lock file (option to convert to json)

### ISSUE THREAD

**Issue by mrweiland** [yarnpkg/yarn#5246]
**bug**

**What is the current behavior?**
When creating yarn.lock file it creates it but it seems like yaml isnt valid.  (tested with several linters and also try to parse it with powershell tool like powershell-yaml)

Yaml linter - https://codebeautify.org/yaml-validator

**If the current behavior is a bug, please provide the steps to reproduce.**
Create yarn.lock file and then paste it in any yaml linter like https://codebeautify.org/yaml-validator

**What is the expected behavior?**
Creates a valid yaml file that i could use and parse.  I really would like an option to create a JSON file of lock file or it always creates a json lockfile.

Currently its really hard do tooling against yarn.lock file. 👎   

**Please mention your node.js, yarn and operating system version.**
node v8.9.4
yarn 1.3.2

**Comment by rally25rs** [comment]
I'm not sure that the lockfile is actually supposed to be yaml. The yarn code parses it itself, not using a yaml parser.

If you want to translate it to/from JSON, you can use `@yarnpkg/lockfile` to do that: https://www.npmjs.com/package/@yarnpkg/lockfile
