### ISSUE TITLE
yarn pack should not process .npmignore if it already been ignored.

### ISSUE THREAD

**Issue by zerda** [yarnpkg/yarn#5249]
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
`yarn pack` include files which parent directory already been ignored in `.npmignore`, while `npm pack` not.

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
# an package with `.npmignore`, which exclude sub directory `/foo`
$ yarn init -y
$ echo '/foo' > .npmignore

# sub directory `/foo`, with another `.npmignore` inside, which re-include `index.js`
$ mkdir ./foo
$ touch ./foo/index.js
$ echo '!/index.js' > ./foo/.npmignore
```

```bash
$ yarn pack
$ tar tvf test-v1.0.0.tgz
package
package/foo
package/package.json
package/foo/index.js
```

**What is the expected behavior?**
File `/foo/index.js` should be ignored, as the parent directory of that file is excluded, like `npm pack` did.
```bash
$ npm pack
$ tar tvf test-1.0.0.tgz
package/package.json
```

**Please mention your node.js, yarn and operating system version.**
node: v9.4.0
yarn: v1.3.2 (v1.4.0 has same issue)
operating system: macOS 10.12.6

**Comment by GAumala** [comment]
I think yarn's behavior is correct, as opposed to npm.

The npm docs aren't too detailed about how `.npmignore` is used in the `pack` command. It just says that it tries to copy what `.gitignore` does.

> Like git, npm looks for .npmignore and .gitignore files in all subdirectories of your package, not only the root directory. .npmignore files follow the same pattern rules as .gitignore files

I tried to recreate your example with git, and the result is similar to what yarn does.

![screenshot from 2018-01-19 08-50-42](https://user-images.githubusercontent.com/5729175/35153790-f064e30e-fcf5-11e7-81d0-d6c77d9f101b.png)

**Comment by zerda** [comment]
Thank you for explanation, that makes sense.
