### ISSUE TITLE
Use symlinks/hardlinks to optimize disk usage

### ISSUE THREAD

**Issue by KSXGitHub** [yarnpkg/yarn#5266]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What's the feature?**

Instead of creating copies of the same packages over and over again (which wastes disk usage), yarn should create symlinks or hard links in `node_modules` that point to packages stored in a shared directory.

Also, [pnpm](https://github.com/pnpm/pnpm)  was created to solved this.

**Please mention your node.js, yarn and operating system version.**

Node.js: 9.4.0
Yarn: 1.3.2
OS: Arch Linux

**Comment by swrobel** [comment]
Dupe: https://github.com/yarnpkg/yarn/issues/499
