### ISSUE TITLE
yarn rebuild (Feature request)

### ISSUE THREAD

**Issue by ctcpip** [yarnpkg/yarn#5271]
Npm has `npm rebuild` to rebuild compiled packages (eg, node-sass). we need this in yarn for, among other reasons, the need to rebuild packages for cross-platform environments.

#2069 was closed prematurely and calls to reopen it have been ignored.  it was closed after being erroneously marked as a duplicate.  the use case and solution for #756 are quite different, and does not solve the problem.

**Comment by nextmat** [comment]
I'd still love to see this functionality added. 

For anyone who runs across this in the meantime, `npm rebuild --update-binary` appears to be a viable workaround that won't mess with your lock files. /ht @fugroup

**Comment by caseyWebb** [comment]
`yarn rebuild` is still needed for using workspaces. `npm rebuild --update-binary` will only work for the top-level dependencies and not workspace deps.

**Comment by merceyz** [comment]
Closing as fixed in v2 with https://yarnpkg.com/cli/rebuild

https://yarnpkg.com/getting-started/migration
