### ISSUE TITLE
Can't delete http-proxy

### ISSUE THREAD

**Issue by lstrahan** [yarnpkg/yarn#5284]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

When I execute `yarn config delete http-proxy` the `http-proxy` configuration setting is not removed

**If the current behavior is a bug, please provide the steps to reproduce.**
`%>yarn config delete http-proxy`

_But http-proxy is still there..._

```
%>yarn config get http-proxy
http://10.32.11.142:8888
```

**What is the expected behavior?**
`http-proxy` config setting should be removed

**Please mention your node.js, yarn and operating system version.**
node -v 8.9.4
yarn -v 1.3.2
OS = Windows 10

**Comment by gerrychief** [comment]
Apparently u also have to delete the same keys from npm. Had e same issue on my laptop. Had set proxy to be able to run some commands from my work LAN. When I tried to delete the proxy at home, `yarn config get proxy` still showed the proxy value. It only worked after i did both `yarn config delete proxy` and `npm config delete proxy`. Not sure why though, I thought yarn settings and npm settings are supposed to be different.

**Comment by rishavs** [comment]
Unfortunately this did not work for me.
```
C:\Users\Mockingbird\DevSpace\Go\src\github.com\rishavs\integra (master -> origin) (buffalo@1.0.0)
λ yarn config delete proxy
yarn config v1.3.2
success Deleted "proxy".
Done in 0.14s.

C:\Users\Mockingbird\DevSpace\Go\src\github.com\rishavs\integra (master -> origin) (buffalo@1.0.0)
λ yarn config delete https-proxy
yarn config v1.3.2
success Deleted "https-proxy".
Done in 0.17s.

C:\Users\Mockingbird\DevSpace\Go\src\github.com\rishavs\integra (master -> origin) (buffalo@1.0.0)
λ npm config delete proxy

C:\Users\Mockingbird\DevSpace\Go\src\github.com\rishavs\integra (master -> origin) (buffalo@1.0.0)
λ npm config delete https-proxy

C:\Users\Mockingbird\DevSpace\Go\src\github.com\rishavs\integra (master -> origin) (buffalo@1.0.0)
λ yarn config get proxy
192.168.32.2:8080

C:\Users\Mockingbird\DevSpace\Go\src\github.com\rishavs\integra (master -> origin) (buffalo@1.0.0)
λ yarn config get https-proxy
192.168.32.2:8080

```

**Comment by uranio-235** [comment]
```
yarn config delete proxy
yarn config delete https-proxy
```

**Comment by lstrahan** [comment]
uranio-235... Ok. So what is the value of your comment? You are just restating what DOESN'T work.

**Comment by tatendamar** [comment]
I managed to solve this using these commands

yarn config delete https-proxy then::   npm config rm https-proxy

**Comment by tatendamar** [comment]
I managed to solve this using these commands

*yarn config delete http-proxy* 
*npm config rm https-proxy*

**Comment by silveraignacio** [comment]
> I got around this bug with:
> 
> ```shell
> yarn config set proxy ''
> yarn config set https-proxy ''
> ```

This works for me like a charm!!!

**Comment by 734204679** [comment]
> Apparently u also have to delete the same keys from npm. Had e same issue on my laptop. Had set proxy to be able to run some commands from my work LAN. When I tried to delete the proxy at home, `yarn config get proxy` still showed the proxy value. It only worked after i did both `yarn config delete proxy` and `npm config delete proxy`. Not sure why though, I thought yarn settings and npm settings are supposed to be different.

thx!!!!!!
