### ISSUE TITLE
Yarn install on a different folder using --modules-folder clears the default node_modules folder

### ISSUE THREAD

**Issue by njlr** [yarnpkg/yarn#5289]
Yarn install on a different folder using --modules-folder clears the default node_modules folder. 

Full description in this repo: https://github.com/njlr/yarn-is-weird

**Comment by bestander** [comment]
Duplicate of https://github.com/yarnpkg/yarn/issues/1684, this is not on the hi priority list right now but should be relatively easy to fix.
Would be great if someone sent a PR with a fix
