### ISSUE TITLE
Feature request - Add a Docker Yarn Local server.

### ISSUE THREAD

**Issue by MichelDiz** [yarnpkg/yarn#5296]
hi,

Often we have problems with routes, DNS or connection drop. So a local server for Yarn in Docker would come in handy.

It would be very useful for services in which we use Continuous of delivery or Continuous integration.

A local Yarn Local server would maintain a cache and could be linked with microservices to feed them. Or within a company could have an instance to economize bandwidth.

It would solve a series of problems. Like Docker we have the philosophy of killing containers and everything that comes in front of us. Such an instance would save our souls.

Cheers.

**Comment by merceyz** [comment]
Closing as https://verdaccio.org/ is a thing now

**Comment by MichelDiz** [comment]
Is verdaccio part of Yarn team? also, it should be documented if Yarn is supporting it.

**Comment by merceyz** [comment]
No, it's a third party solution to running a local npm registry that caches responses from the actual registry and solves this part of your issue

> Often we have problems with routes, DNS or connection drop. So a local server for Yarn in Docker would come in handy.
>
> A local Yarn Local server would maintain a cache and could be linked with microservices to feed them. Or within a company could have an instance to economize bandwidth.
