### ISSUE TITLE
Yarn keeps all project files ignoring what is defined on package.json's "files" prop

### ISSUE THREAD

**Issue by melloc01** [yarnpkg/yarn#5309]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
`yarn` keeps all the project files when using a git project as dependency. `npm` keeps only the files on the "files" config prop.

**If the current behavior is a bug, please provide the steps to reproduce.**
1 - Use [this repo](https://github.com/melloc01/test-npm-install) as dependency of a project.
2 - Install via yarn
3 - Install via npm

contents on `node_modules` will differ.

**What is the expected behavior?**
As descripted on the [docs](https://docs.npmjs.com/files/package.json#files)

 _""files" field is an array of file patterns that describes the entries to be included when your package is installed as a dependency."_

So it is expected to only have the files listed on the config to be present.

**Please mention your node.js, yarn and operating system version.**
- Deepin Linux@15.5
- yarn@1.3.2
- npm@5.6.0

**Comment by rally25rs** [comment]
duplicate #2822
