### ISSUE TITLE
`yarn ls <package>` is missing.

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#531]
Missing feature, compare with `npm ls once`. Should `yarn why once` be the replacement for it? If so, the dependency graph that it shows seems wrong.

```
[cpojer: ~/Projects/yarn (master)]$ yarn why once
yarn why v0.14.0
[1/3] 🤔  Why do we have the module "once"...?
[2/3] 🚚  Initialising dependency graph...
[3/3] 🔍  Finding dependency...
info Reasons this module exists
   - "node-gyp#glob" depends on it
   - "jest#jest-cli#istanbul-api" depends on it

[cpojer: ~/Projects/yarn (master)]$ npm ls once
yarn@0.14.0 /Users/cpojer/Projects/yarn
├─┬ eslint@3.7.1
│ └─┬ glob@7.1.0
│   └── once@1.4.0
├─┬ gulp@3.9.1
│ └─┬ orchestrator@0.3.7
│   └─┬ end-of-stream@0.1.5
│     └── once@1.3.3
└─┬ tar-stream@1.5.2
  └─┬ end-of-stream@1.1.0
    └── once@1.3.3
```

**Comment by athyuttamre** [comment]
Thoughts on `yarn find once` or `yarn where once`?

**Comment by torifat** [comment]
We have `yarn ls <package>` now 😃

**Comment by cpojer** [comment]
@torifat awesome!!

**Comment by sudo-suhas** [comment]
For anyone who comes here in search of the `ls` command, `yarn list <package>` works on `v1.9.4`(`ls` doesn't work).

**Comment by shaodahong** [comment]
`yarn ls <package>` not found
```bash
❯ yarn ls react     
yarn run v1.19.1
error Command "ls" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jordymeow** [comment]
I have the same issue as @shaodahong on Yarn 1.22.4. Any news about this?

**Comment by virtuoushub** [comment]
> For anyone who comes here in search of the `ls` command, `yarn list <package>` works on `v1.9.4`(`ls` doesn't work).

_for anyone who comes here using yarn@berry (`v2+`):_

> Use the `yarn why` command - https://yarnpkg.com/cli/why
> 
> ```
> yarn why vue
> ```

https://github.com/yarnpkg/berry/issues/720#issuecomment-778043078
