### ISSUE TITLE
Installing unpublished packages results in incorrect "malformed response/registry down" warnings

### ISSUE THREAD

**Issue by rarkins** [yarnpkg/yarn#5311]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Example:
```
$ yarn add x-iterable-tree
yarn add v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Received malformed response from registry for "x-iterable-tree". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

Something that reflects that the package was unpublished and not suggesting the registry might be down.

**Please mention your node.js, yarn and operating system version.**

v1.3.2

**Comment by rally25rs** [comment]
The JSON that comes back from the registry is:

```
{"_id":"x-iterable-tree","_rev":"5-a13c8f7627df1b21d48b5789e76134a6","name":"x-iterable-tree","time":{"modified":"2016-01-28T14:01:26.489Z","created":"2016-01-16T12:44:38.980Z","0.0.0":"2016-01-16T12:44:38.980Z","0.0.1":"2016-01-25T12:10:04.497Z","0.0.2":"2016-01-26T10:44:43.297Z","0.0.3":"2016-01-28T14:01:26.489Z","unpublished":{"name":"khai96_","time":"2016-02-18T05:08:08.128Z","tags":{"latest":"0.0.3"},"maintainers":[{"name":"khai96_","email":"hvksmr1996@gmail.com"}],"versions":["0.0.0","0.0.1","0.0.2","0.0.3"]}},"_attachments":{}}
```

I think at some point yarn looks for a `latest` or a `versions` property or something, and when it doesn't find it, it throws the "malformed" error message. We should first check for `unpublished` and display a proper message.

**Comment by mhchen** [comment]
@rally25rs I can take a look at this if no one else is looking into it

**Comment by mhchen** [comment]
@rally25rs rather than checking for `unpublished`, it looks like the simplest fix is to check the `versions` field of `RegistryResponse` for any valid versions and to throw an error if empty. This appears to be what npm does:

```
$ npm i x-iterable-tree

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for x-iterable-tree
```
Let me know if this makes sense to you and I can send a PR
