### ISSUE TITLE
[Bug] Yarn rebuilds `canvas` package during any change (add/remove)

### ISSUE THREAD

**Issue by soanvig** [yarnpkg/yarn#5312]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After installing [canvas](https://www.npmjs.com/package/canvas) package which needs building, it is builded during any change in node_modules (it means, that it is rebuilded while **any** package is added or removed). Because of that behavior adding/removing packages takes very long time.

This behavior **probably** exists for other packages, which require building (**need confirmation**).

This behaviour **is not** present while using *npm*.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install  [canvas](https://www.npmjs.com/package/canvas) package: `yarn add canvas`
2. (canvas builds)
3. Add any other package (`yarn add npm-dummy-package`)
4. (canvas builds again)

**What is the expected behavior?**
Yarn should (probably) ignore the `canvas` build proccess, if added/removed/updated package is not `canvas` dependency.

**Please mention your node.js, yarn and operating system version.**
node: v8.9.4
yarn: 1.3.2
```
Linux localhost.localdomain 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 27 (Twenty Seven)
Release:	27
Codename:	TwentySeven
```

**Comment by rally25rs** [comment]
Unfortunately this issue has been around for a while. I think at some point someone make only new packages rebuild but it broke something else and got reverted. It looks like a new fix may be in the works though.
duplicate #932
