### ISSUE TITLE
rename "workspaces" to "spaces"?

### ISSUE THREAD

**Issue by ianstormtaylor** [yarnpkg/yarn#5326]
**Do you want to request a *feature* or report a *bug*?**

Improvement.

**What is the current behavior?**

Right now the concept is called "workspaces", which is easy enough to understand. The downside is that the `yarn workspaces` command is really long to type.

**What is the expected behavior?**

It would be nice to just call them "spaces", and be able to do `yarn spaces` instead.

I realize this might be controversial, I don't want to bikeshed, but just wanted to suggest this renaming to make any/all work on workspaces commands in the future easier for people to type/use. Right now things like `yarn workspaces run` are already getting really long, and that's one of the shortest ones 😄 

Although, it might not require renaming, and you could argue that instead we should just add an alias `spaces -> workspaces` instead for convenience.

Just an idea!

**Comment by arcanis** [comment]
Workspaces can't be renamed, they are already known under this name and this ship has sailed :) As for making an alias, I'm not too fond of the idea. It would conflict with scripts named "spaces" (granted, there's not a lot of them), and would just split the ecosystem between those who would use "spaces" and those who use "workspaces".
