### ISSUE TITLE
yarn and npm performance discrepancies

### ISSUE THREAD

**Issue by kittens** [yarnpkg/yarn#533]
Apparently we're slower than npm in two scenarios, dunno why, pretty confident we can beat it.

<img width="1135" alt="screen shot 2016-10-06 at 12 51 28 pm" src="https://cloud.githubusercontent.com/assets/853712/19151258/a13a9980-8bc3-11e6-8bdf-9a5dd4c9aa76.png">

**Comment by arcanis** [comment]
Closing for triage - Is there a way we can run those tests again?
