### ISSUE TITLE
yarn global not linking binaries

### ISSUE THREAD

**Issue by deltaskelta** [yarnpkg/yarn#5330]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I noticed my `prettier` executable wasn't working so I investigated and it looks like it was updates, but the new executable wasn't linked. I manually relinked it (uninstalling and reinstalling didn't help). I just installed `tern` the same way and it too failed to link...

**If the current behavior is a bug, please provide the steps to reproduce.**

for me the process is just `yarn global add <package>`

**What is the expected behavior?**

I expect the binaries to be linked and ready to use, my `yarn global bin` matches where I am looking `/usr/local/bin`

**Please mention your node.js, yarn and operating system version.**

```
node --version
v9.5.0

yarn --version
1.3.2

OSSierra 10.13.3
```

**Comment by deltaskelta** [comment]
I get this error when installing prettier, so I think it may be related to #4182

```
warning Pattern ["prettier@^1.10.2"] is trying to unpack in the same destination "/Users/Jeff/Library/Caches/Yarn/v1/npm-prettier-1.10.2-1af8356d1842276a99a5b5529c82dd9e9ad3cc93" as pattern ["prettier@^1.5.3"]. This could result in a non deterministic behavior, skipping.
```

**Comment by torifat** [comment]
What is the output of `ls -ld /usr/local/bin`? Can you create symlink manually without using `sudo`?

**Comment by kaylieEB** [comment]
I couldn't repro the issue -- was able to install prettier and run it without getting the warning
Can you try `yarn cache clean` then run the global command again?

**Comment by deltaskelta** [comment]
I didn't know about `yarn cache clean`. I deleted the cache manually yesterday and got it to work and it hasn't resurfaced again. That was probably it. I will reopen if it happens again.

**Comment by kaylieEB** [comment]
thanks @deltaskelta !
