### ISSUE TITLE
Error: spawn yarnpkg ENOENT

### ISSUE THREAD

**Issue by yxuchen** [yarnpkg/yarn#5331]
# Version 
```
system：Mac OS high sierra 10.13.3 and Win 7
yarn：1.3.2
node：8.9.3
npm：5.6.0
```
# Reproduction link
# Steps to reproduce

Recently I was using `react` and `vue` scaffold Both [@vue/cli](https://github.com/vuejs/vue-cli) and [create-react-app](https://github.com/facebook/create-react-app) throw this error
```
Creating a new React app in /Users/yxc/code/mycode/react-test.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
# What is expected?

no error

# What is actually happening?

throw error

# How to solve 

```bash
npm uninstall -g yarn
```

**Comment by yxuchen** [comment]
Although it does not throw , i can not use yarn 😕

**Comment by rally25rs** [comment]
Sorry to get to this so long after you posted it, but could you add the commands that you ran?
Were you running `yarn create react-app`?

**Comment by yxuchen** [comment]
i don't know what happened on my computer and this problem has gone 3q you @rally25rs
