### ISSUE TITLE
Cannot install optional deps

### ISSUE THREAD

**Issue by pronebird** [yarnpkg/yarn#5338]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```
yarn add 'git+https://github.com/microsoft/arewethereyet --optional
```

Throws the following error:

>The platform "darwin" is incompatible with this module.

WAT?

**If the current behavior is a bug, please provide the steps to reproduce.**

Add optional package while running the OS that is not covered by the package.

**What is the expected behavior?**

Should add the record to `package.json` if it cannot install the dependency on the current platform.

**Please mention your node.js, yarn and operating system version.**

node 8.9.1
yarn 1.3.2
Darwin elk.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by arcanis** [comment]
Yeah it would make sense to do that. Would you be willing to open a PR and ping me there?

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
