### ISSUE TITLE
yarn upgrade does not respect scope flag correctly

### ISSUE THREAD

**Issue by zerda** [yarnpkg/yarn#5350]
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
`yarn upgrade --scope @angular` has upgrade all dependencies.

**If the current behavior is a bug, please provide the steps to reproduce.**
say `package.json` and `yarn.lock`.
```json
{
  "dependencies": {
    "@angular-mdl/core": "^4.0.0",
    "@angular/core": "^2.4.9",
    "left-pad": "^1.0.0"
  }
}
```
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@angular-mdl/core@^4.0.0":
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/@angular-mdl/core/-/core-4.0.0.tgz#9415a3340cbeeac01739e5777971fec307b13c17"

"@angular/core@^2.4.9":
  version "2.4.9"
  resolved "https://registry.yarnpkg.com/@angular/core/-/core-2.4.9.tgz#85dca2afa4021be91512c97597702ac8d73092e6"

left-pad@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.0.0.tgz#c84e2417581bbb8eaf2b9e3d7a122e572ab1af37"
```

While `@angular` scope upgraded, `@angular-mdl/core` and `left-pad` are also upgraded to latest compatible version.
```bash
$ yarn upgrade --scope @angular
yarn upgrade v1.4.1
...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
├─ @angular-mdl/core@4.0.8
├─ @angular/core@2.4.10
└─ left-pad@1.2.0
info All dependencies
├─ @angular-mdl/core@4.0.8
├─ @angular/core@2.4.10
└─ left-pad@1.2.0
...
```

**What is the expected behavior?**
`yarn upgrade --scope @angular` should only upgrade `@angular/core` dependency, leave `@angular-mdl/core` and `left-pad` not touched.

**Please mention your node.js, yarn and operating system version.**
node: v9.5.0
yarn: v1.3.2 (master has same issue)
operating system: macOS 10.12.6

**Comment by bestander** [comment]
Last change to this feature was here https://github.com/yarnpkg/yarn/pull/4636 cc @rally25rs

**Comment by zerda** [comment]
I am trying to fix this issue. While the solution is straight, it maybe missed some edge case. Feel free to edit/close it.

**Comment by webmutation** [comment]
Is it possible to upgrade multiple scopes... looking at the code this does not seem possible.

for example yarn upgrade -S @angular,@ngrx,@primeng --latest to upgrade to the latest of these packages.
