### ISSUE TITLE
what's the meaning of yarn install --ingore-optional

### ISSUE THREAD

**Issue by FanShiDe** [yarnpkg/yarn#5356]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
I don't know the meaning of  `yarn install --ignore-optional`.
if we have a `package.json` file as below:
```js
dependencies: {
  "hapi": "1.1.1",
},
devDependencies: {
  "xlsx": "1.2.1",
}
```
Will the `dependencies` and `devDependencies` all be installed?

**Comment by DillonGray** [comment]
Yes, it would install your regular and dev dependencies.
`--ignore-optional` would ignore `optionalDependencies`

Reference: https://yarnpkg.com/lang/en/docs/dependency-types/#toc-optionaldependencies

**Comment by rally25rs** [comment]
Closing this issue because @DillonGray answered the question. I'll just add that it also skips installing `optionalDependencies` of transitive dependencies.
