### ISSUE TITLE
Running version with --no-git-tag-version skips postversion script hook

### ISSUE THREAD

**Issue by mikedbreed** [yarnpkg/yarn#5358]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Running `yarn version` with the `--no-git-tag-version` flag skips the script lifecycle hook `postversion`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Init the project
```
mkdir yarn-bug
cd yarn-bug
yarn init --yes
git init
git add package.json
git commit -m "Init"
```
2. Change `package.json` to include a postversion script
```
{
  "name": "yarn-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "UNLICENSED",
  "scripts": {
    "postversion": "echo 'postversion script hook'"
  }
}
```
3. Run yarn version
```
yarn version --no-git-tag-version --new-version patch
```

**What is the expected behavior?**

Running `yarn version` with the `--no-git-tag-version` flag should execute the script lifecycle hook `postversion`

OF NOTE:
Running `npm version --no-git-tag-version patch` will execute the `postversion` script

The NPM documentation on `postversion` is ambiguous, but the behavior of the npm CLI version command is not ambiguous.  Yarn should do the same (principle of least surprise).

This is related to a bug that was recently fixed: https://github.com/yarnpkg/yarn/issues/4744

**Please mention your node.js, yarn and operating system version.**

    Node  v8.7.0
    Yarn  v1.3.2
    OS    MacOS 10.13.3

**Comment by tmchow** [comment]
I just came across this as I was tearing my hair out as to why my `postversion` command wasn't being run. I was surprised to see this issue still open for almost a year!

**Comment by kerryj89** [comment]
FYI for those of you using Lerna with Yarn like I am, the fix here only takes care of the Yarn side of things (as it should) in that it deals with `postversion` in the same package.json that the version command was issued from.  Unfortunately the fix doesn't seem to unblock the execution of `postversion` within other packages which is reached through Lerna https://github.com/lerna/lerna/tree/main/commands/publish#lifecycle-scripts
