### ISSUE TITLE
yarn install --har hangs at "Resolving Packages"

### ISSUE THREAD

**Issue by jeffbcross** [yarnpkg/yarn#536]
Yarn built from 2812f05b300b510cc8c83c26b841f207f3ac9d26

**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

When running `yarn install --har` (with lock file present) the install gets stuck on Resolving packages:

```
$ yarn install --har
yarn install v0.14.0
warning No license field
[1/5] 🔍  Resolving packages...
⠁ is-number@^2.0.2
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install 2 npm packages, `@angular/core` and `angular-cli`.
- Remove the `node_modules` directory.
- `$ yarn install --har`
- Send instant message to @samccone telling him to fix it
- Open Github issue because @samccone said to

Behavior only appears with `--har`, and is consistently reproducible.

**What is the expected behavior?**

Yarn would move past this step.

**Please mention your node.js, yarn and operating system version.**

Node v5.10.1
Macintosh Operating System El Capitan

**Comment by MihaiDamian** [comment]
I'm getting the same problem when running `yarn`. I have just the package.json file and no yarn.lock. I also get stuck at the same library `is-number@^2.0.2`.

**Comment by hbakhtiyor** [comment]
the same issue like @MihaiDamian, i cleaned cache and remove node_modules, but didn't help it

**Comment by steve-taylor** [comment]
Still happens in v0.23.2 which should contain #2995 as it was merged before the release. Specifically, it hangs on `is-number` and `is-arrayish`.

**Comment by mkastner** [comment]
Same on my current target system with v0.24.5 on `is-number`.

**Comment by samccone** [comment]
confirmed, let's reopen.

**Comment by khushkaran** [comment]
Dunno if this will help anyone - I found that after trying a `yarn install` a few times - one time it popped up for a passphrase (as one of my dependencies are stored in git and fetched over SSH)... I couldn't enter my passphrase for some strange reason, so I changed my SSH config to use the keychain (https://superuser.com/questions/1127067/macos-keeps-asking-my-ssh-passphrase-since-i-updated-to-sierra). After that all worked well...

Node v7.9.0
yarn 0.24.6
macOS Sierra

**Comment by MatthiasRMS** [comment]
Have the same problem (hangs when loading is-number@^2.0.2), but without --har

**Comment by rmariuzzo** [comment]
Indeed following the solution posted at: https://superuser.com/a/1158050/133390 “fixed” the issue as mentioned by @khushkaran

**Comment by Daniel15** [comment]
@rmariuzzo  - I'm not sure that's related to this issue. This issue is specifically for the `--har` option.
