### ISSUE TITLE
Yarn install fails with "Lockfile has incorrect entry" error if the package version includes buildno & commit-hash and if we use version range(~, ^) when defining it as a dependency

### ISSUE THREAD

**Issue by pradeepbkkumar** [yarnpkg/yarn#5365]
We are using latest version of yarn (i.e) v1.3.2

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In package.json, We have declared the below dependencies
_"@mss/rectangle": "~0.1",
"@types/core-js": "~0.9",_

With "tilde" (~0.1) in package dependencies version, "yarn install" fails in our module with the error.
 _Lockfile has incorrect entry for "@mss/files@~0.1". Ignoring it._

![image](https://user-images.githubusercontent.com/14543239/36257004-4b1b45d2-127b-11e8-9a7d-2cdae2989964.png)

Interestingly it works fine for other packages. It fails only for our @mss packages.
Looking at the yarn lock file, @mss package has build number, id and commit hash in its version compared to @types package. Is that the reason yarn thinks it has an incorrect entry ?

![image](https://user-images.githubusercontent.com/14543239/36256996-3ba428c6-127b-11e8-90a7-05387691396c.png)

Tried running `yarn install --frozen-lockfile`, Still getting the same error.

So, What are the possible causes when yarn shows this error? How to fix it ?

**What is the expected behavior?**
It should have downloaded the package defined in yarn lock file and install should have been successful without throwing the above error.

**Please mention your node.js, yarn and operating system version.**
node v6.11.3, yarn v1.3.2 and Windows 10

**Comment by rally25rs** [comment]
Do you know how you got it into this state? 🤔 Could you list reproduction steps as a list of commands? Or did this just sort of randomly happen?

**Comment by pradeepbkkumar** [comment]
The issue was because of including a [semver prerelease](https://docs.npmjs.com/misc/semver#prerelease-identifiers) tag in the package patch version. Changed package versioning to use the buildId as the patch component and buildnumber+commit as build metadata using the below code and started working fine. 

`packageVersion = `${majorVersion}.${minorVersion}.${buildId}+BuildNumber-${buildNumber}.Commit-${commitSha}`;`
