### ISSUE TITLE
yarn install --production tries to reach the devDependencies

### ISSUE THREAD

**Issue by maxime1992** [yarnpkg/yarn#5368]
```
yarn -v
1.3.2
```

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
At work we have a `devDependency` pointing to a private repo.
When we're building on CI for prod, we're installing with `yarn install --production` and thus, we do not want to ping/reach our private project (which is not available from CI anyway).

But, it ends up with an error as yarn is still trying to ping or pull that resource.

**If the current behavior is a bug, please provide the steps to reproduce.**
- create a basic package with a yarn.lock
- add a dev dependency that you cannot reach once on CI (hard one probably a way to fake it...)
- run an install on CI (or docker...) with --production, it'll try to install the dependency

**What is the expected behavior?**
Do not try to reach a devDependency with --production argument

Ubuntu 16.10
Node 8.9.4
Yarn 1.3.2

**Comment by rally25rs** [comment]
duplicate #3630
there is some discussion in that issue of what would likely have to change in Yarn to resolve this.
