### ISSUE TITLE
upgrading package causes ETIMEDOUT error

### ISSUE THREAD

**Issue by EvaLok** [yarnpkg/yarn#5377]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
our library ([@convenior/microservice-toolkit](https://www.npmjs.com/package/@convenior/microservice-toolkit)) has been working fine for quite some time. today, we published a minor update and upgraded the version (from `2.0.2` to `2.0.3`). when upgrading the project that's using it via `yarn upgrade` or manually specifying the version (eg: `yarn install` after modifying `package.json`), the installation fails with the following error (this occurs on both `1.4` and `1.3.2`:

```
yarn upgrade v1.4.0
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/depd: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/eva/PhpstormProjects/std-fulfillment/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
Error: https://registry.yarnpkg.com/depd: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/yarn/lib/cli.js:132130:19)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

(note that the package it times out on is not always the same)

interestingly, `npm install` works.

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
# create new directory somewhere
yarn init
yarn add @convenior/microservice-toolkit@2.0.3 

# ..but this works
npm install @convenior/microservice-toolkit@2.0.3 
```

**What is the expected behavior?**
should install dependency correctly

**Please mention your node.js, yarn and operating system version.**
yarn 1.3.2 / 1.4.0

ubuntu 16.04
Linux eva 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

`yarn-error.log`:
```
cat yarn-error.log 
Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add @convenior/microservice-toolkit@2.0.4

PATH: 
  /home/eva/bin:/home/eva/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
  1.4.0

Node version: 
  8.9.0

Platform: 
  linux x64

npm manifest: 
  {
    "name": "blahblah",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "dependencies": {
      "@convenior/microservice-toolkit": "^2.0.4"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/express: ETIMEDOUT
      at Timeout._onTimeout (/usr/local/lib/node_modules/yarn/lib/cli.js:132130:19)
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)

```

@maikelh

**Comment by EvaLok** [comment]
seems like this works:
`yarn add @convenior/microservice-toolkit@2.0.3 --network-timeout 60000`

we tried more aggressive timeouts like `40000`, but no luck (although the dependency it times out on changes)

we are just using the general npm repository, no private stuff involved, so it seems a little strange that this should take so long.

we did some rough timings:
`npm install @convenior/microservice-toolkit@2.0.3`- ~10 seconds
`yarn add @convenior/microservice-toolkit@2.0.3 --network-timeout 60000` - ~40s

**Comment by snekse** [comment]
Just to add some more anecdotal data points... 

I'm also running into this error.  I'm not going through a proxy, but I am using an open wifi provided by the local cable/ISP.

Adding the network timeout resolved the issue for me, but I also saw a speed increase using npm instead of yarn.

**Please mention your node.js, yarn and operating system version.**
yarn 1.7.0
node v10.4.0 & 8.11.2
osx 10.13.4

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
