### ISSUE TITLE
Unformatted json in output when passing --json

### ISSUE THREAD

**Issue by amiralies** [yarnpkg/yarn#5380]
**Do you want to request a *feature* or report a *bug*?**
Feature maybe

**What is the current behavior?**
When passing `--json` it prints an unformatted (no spaces) json in a single line to the terminal.

command:
```
yarn info react dependencies --json
```
output:
```
{"type":"inspect","data":{"fbjs":"^0.8.16","loose-envify":"^1.1.0","object-assign":"^4.1.1","prop-types":"^15.6.0"}}
```

**What is the expected behavior?**
Print a well formatted pretty piece of json

command:
```
yarn info react dependencies --json
```
output:
```
{
  "type": "inspect",
  "data": {
    "fbjs": "^0.8.16",
    "loose-envify": "^1.1.0",
    "object-assign": "^4.1.1",
    "prop-types": "^15.6.0"
  }
}
```
**Please mention your node.js, yarn and operating system version.**
node: `8.9.4`
yarn:  `1.3.2`
OS: Ubuntu 16.04

**Comment by rally25rs** [comment]
The original intent of `--json` output is for integration with other applications, where the formatting wouldn't matter. Perhaps a second `--json-pretty` flag could be added for this.

**Comment by paul-soporan** [comment]
Closing as in the v2 we've standardized that the regular output is supposed to be pretty and readable by humans while the `--json` output is supposed to be parseable by applications and nothing more.
