### ISSUE TITLE
yarn run command --production doesn't set NODE_ENV like npm does

### ISSUE THREAD

**Issue by esprehn** [yarnpkg/yarn#5395]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
yarn run --production foo sets NODE_ENV=production.
yarn run foo --production doesn't set NODE_ENV.

npm run foo --production does set NODE_ENV.
(verified with npm 5.6.0)

**If the current behavior is a bug, please provide the steps to reproduce.**

console.log(process.env.NODE_ENV) inside a script executed with 'run'.

**What is the expected behavior?**
--production should always set NODE_ENV.

**Please mention your node.js, yarn and operating system version.**
OS X 10.13.3, v8.9.4

**Comment by esprehn** [comment]
With package.json
```json
  "scripts": {
    "build": "echo NODE_ENV=$NODE_ENV",
  }
```

I get:
```
$ yarn run --production build
yarn run v1.3.2
$ echo NODE_ENV=$NODE_ENV
NODE_ENV=production
✨  Done in 0.11s.
$ yarn run build --production
yarn run v1.3.2
$ echo NODE_ENV=$NODE_ENV --production
NODE_ENV= --production
```

Which seems wrong, it's setting NODE_ENV to neither development or production, but to the flag value with dashes.

**Comment by hulkish** [comment]
@esprehn 

>Which seems wrong, it's setting NODE_ENV to neither development or production, but to the flag value with dashes 

looks like your line here is the cause: `echo NODE_ENV=$NODE_ENV --production`

**Comment by hulkish** [comment]
@esprehn i couldn't repro this. This sounds like expected environment behavior.. meaning if you wanted `NODE_ENV` value to persist.. you would need to do `export NODE_ENV=production`. Maybe im following the steps in the issue incorrectly?

**Comment by hulkish** [comment]
@esprehn this test should either confirm or deny the bug, right? https://github.com/yarnpkg/yarn/blob/5a24a4df7b4de25088bae7acda1350e6520d5dd0/__tests__/integration.js#L83

**Comment by esprehn** [comment]
Sorry I wasn't clear, the bug is if you have a script that prints NODE_ENV:

npm run my-script --production
npm run --production my-script 

Both set NODE_ENV=production

yarn run my-script --production doesn't.

**Comment by hulkish** [comment]
shouldn't the above test validate this, though,

**Comment by esprehn** [comment]
I don't understand that test, but I don't think so. Now that I'm reading the docs more closely and writing examples this looks like a difference with how yarn and npm take arguments.

https://docs.npmjs.com/cli/run-script
`npm run-script <command> [--silent] [-- <args>...]`

https://yarnpkg.com/lang/en/docs/cli/run/
`yarn run [script] [<args>]`

yarn passes all args following the script name to the script itself, while npm passes them to npm unless you add a `--` delimiter.

So npm is:

```
npm run <args for npm...> <script name> <more args for npm...> -- <args for script...>
```

and yarn is:

```
yarn run <args for yarn...> <script name> <args for script...>
```

So I think this is by design for how yarn takes arguments when running scripts. Maybe this could be mentioned as a difference on https://yarnpkg.com/lang/en/docs/migrating-from-npm/ That would be really great! :)
