### ISSUE TITLE
`yarn workspaces <workspace> add <package> -D` adds to <workspace> `dependencies`

### ISSUE THREAD

**Issue by ghost** [yarnpkg/yarn#5396]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`yarn workspace <workspace> add <package> —dev` adds `<package>` to `<workspace>` `dependencies`.

**If the current behavior is a bug, please provide the steps to reproduce.**
It can be reproduced with the most minimal workspace setup: `package.json` with `private` and `workspaces` correctly setup; a freshly init `packages/<package>`; no root dependencies.

**What is the expected behavior?**
`yarn workspace <workspace> add <package> --dev` adds `<package>` to `<workspace>` `devDependencies`.

**Please mention your node.js, yarn and operating system version.**
`v9.5.0`, `v1.3.2`, `macOS 10.13.3`.

**Comment by gbakernet** [comment]
Dupe https://github.com/yarnpkg/yarn/issues/4971?

**Comment by paul-soporan** [comment]
Closing as this has been fixed in the v2.

https://yarnpkg.com/getting-started/migration
