### ISSUE TITLE
Homebrew release process

### ISSUE THREAD

**Issue by greggb** [yarnpkg/yarn#5402]
**Do you want to request a *feature* or report a *bug*?**

**Bug:**
Seems like CI has issues getting Homebrew updated during each release.

**What is the current behavior?**

1.5.0 was released yesterday, but the Homebrew package can't be updated as the latest [version check](https://yarnpkg.com/latest-version) still points to 1.3.2 due to (I assume) the Appveyor build failure. Seems like 1.3.1 and 1.4.0 had the same issues requiring a patch release.

I'm not able to see the failures in CI, so hard to say where this may be failing.

Another dev opened a PR on homebrew for the updated release, but it was closed due to the above version check still failing.

**What is the expected behavior?**
CI succeeds and automatically opens a PR on Homebrew via `update-homebrew.sh` when a release occurs.

**Comment by Daniel15** [comment]
I think we only have stable releases on Homebrew. 1.5.0 is a RC.

Also, yes, the AppVeyor build is blocking everything. We don't consider a release "complete" until both the AppVeyor and the CircleCI builds are completed.

**Comment by greggb** [comment]
Thanks Daniel. I could have sworn it said `Latest` release yesterday otherwise I wouldn't have expected it on HB at all.

Looks like I'm not the only one - https://github.com/Homebrew/homebrew-core/pull/24471

Maybe just some funkiness.

**Comment by Daniel15** [comment]
The version number on the site is the source of truth. Sometimes the Github
releases do funky things.
