### ISSUE TITLE
Subdirectory's .gitignore ignores root directory files when packaging project

### ISSUE THREAD

**Issue by padarom** [yarnpkg/yarn#5407]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When packaging a project via yarn (for publishing, or just using `yarn pack`), .gitignore globs from subdirectories extend to the root directory.

The file `logs/.gitignore` below contains:
```gitignore
*
!.gitignore
```
For git, this means to ignore every file _within the `logs` directory_, except `.gitignore`. Yarn interprets it as _ignore every file_ (except the ones that are always included). As such, the `src` directory is not included in the package:

```
λ tar -tvf yarn-issue-5407-v1.0.0.tgz
drwxr-xr-x  0 0      0           0 25 Feb 16:29 package
-rw-r--r--  0 0      0         142 23 Jan 18:24 package/README.md
drwxr-xr-x  0 0      0           0 24 Feb 20:47 package/logs
-rw-r--r--  0 0      0        1755 24 Feb 23:13 package/package.json
-rw-r--r--  0 0      0          14 25 Jan 17:08 package/logs/.gitignore
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone this repository: http://github.com/padarom/yarn-issue-5407
2. Run `yarn pack`
3. Run `tar -tvf yarn-issue-5407-v1.0.0.tgz`

**What is the expected behavior?**
```
λ tar -tvf yarn-issue-5407-v1.0.0.tgz
drwxr-xr-x  0 0      0           0 25 Feb 16:29 package
-rw-r--r--  0 0      0        1877 24 Feb 20:11 package/.gitignore
-rw-r--r--  0 0      0         142 23 Jan 18:24 package/README.md
drwxr-xr-x  0 0      0           0 24 Feb 20:47 package/logs
-rw-r--r--  0 0      0        1755 24 Feb 23:13 package/package.json
drwxr-xr-x  0 0      0           0 24 Feb 20:11 package/src
-rw-r--r--  0 0      0          14 25 Jan 17:08 package/logs/.gitignore
-rw-r--r--  0 0      0           0 24 Feb 20:11 package/src/index.js
-rw-r--r--  0 0      0           0 24 Feb 20:11 package/src/a.js
-rw-r--r--  0 0      0           0 24 Feb 20:11 package/src/b.js
```

**Please mention your node.js, yarn and operating system version.**
Node: v9.4.0
Yarn: 1.5.0
OS: macOS 10.13.1 (and reproducible on Ubuntu 16.04)

**Comment by padarom** [comment]
I couldn't actually find a lot of references of people using just the `*` glob to ignore entire directories, but I believe that if yarn parses `.gitignore` files, it should do so consistently with git.

**Comment by padarom** [comment]
I just found that #2603 tracks the exact same issue, so this can likely be closed in favor of the earlier issue.

**Comment by kaylieEB** [comment]
Thanks @padarom! Closing as duplicate.
