### ISSUE TITLE
1.5.0 mispublish?

### ISSUE THREAD

**Issue by KevinGrandon** [yarnpkg/yarn#5415]
Running `npm install -g yarn` results in yarn@1.5.0 being installed.. registry.npmjs.org currently shows v1.5.0 as the "latest" version:
```
'dist-tags': { latest: '1.5.0', rc: '1.5.1' }
```

This seems off as all releases since 1.4.0 have been RCs. Was this a mispublish? Did it happen recently enough that you can unpublish 1.5.0?

**Comment by ryami333** [comment]
Is this why 1.5.X is still not available on Homebrew?

**Comment by dlong500** [comment]
see #5408

**Comment by ryami333** [comment]
Ah, seems 1.5.1 is a pre-release, which is why it has not been published to Homebrew. I was confused because 1.5.0 had not been marked as a pre-release.

**Comment by Daniel15** [comment]
There were some issues with publishing 1.5.0. 1.5.1 should be fine now.
