### ISSUE TITLE
extraneous files always checks/cleans node_modules, ignoring --modules-folder specified folder

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/yarn#5419]
**Do you want to request a *feature* or report a *bug*?**
🐞 

**What is the current behavior?**
Yarn checks for and cleans extraneous files in `node_modules`.

When `yarn install --modules-folder somewhere_else` is run, the root `node_modules` dir is still cleaned instead of `somewhere_else`

**If the current behavior is a bug, please provide the steps to reproduce.**

```
~/Projects/yarn-test 🐒   yarn init -y
yarn init v1.3.2
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
✨  Done in 0.04s.

~/Projects/yarn-test 🐒   yarn add left-pad
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ left-pad@1.2.0
✨  Done in 0.35s.

~/Projects/yarn-test 🐒   ls node_modules/
left-pad

~/Projects/yarn-test 🐒   yarn install --modules-folder ./dist/node_modules
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 0.13s.

~/Projects/yarn-test 🐒   ls node_modules/
<empty>
```

**What is the expected behavior?**

yarn should use the folder specified by `--modules-folder` when checking directories for extraneous files. The previous `node_modules` dir should not be deleted.

**Please mention your node.js, yarn and operating system version.**

yarn v1.3.2

**Research notes**

`PackageLinker` loops over `this.config.registryFolders` to use as folders to check for extraneous files:

```
    const findExtraneousFiles = async basePath => {
      for (const folder of this.config.registryFolders) {
```

however the folder specified by `modulesFolder` is not added to that list.

In `config.js`:

```
  _init(opts: ConfigOptions) {
    ...
    if (this.modulesFolder) {
      this.rootModuleFolders.push(this.modulesFolder);
    }

    ...

    for (const key of Object.keys(registries)) {
      ...

      this.registryFolders.push(registry.folder);
      const rootModuleFolder = path.join(this.cwd, registry.folder);
      if (this.rootModuleFolders.indexOf(rootModuleFolder) < 0) {
        this.rootModuleFolders.push(rootModuleFolder);
      }
    }
```

so `registryFolders` does not contain `modulesFolder` but `rootModuleFolders` does. Also when `modulesFolder` is specified, the basic/default directories specified by the registries should not be considered. We might be able to just set `registryFolders = [modulesFolder]` when that option is specified, else use the registry modules folders.

**Comment by Siyfion** [comment]
I can confirm that this issue also occurs with `yarn@1.5.1`.

Also the only way around it at present (without killing performance) is the following:

`mv node_modules node_modules_tmp && yarn install --production=true --modules-folder ./dist/node_modules && rm -rf node_modules && mv node_modules_tmp node_modules`
