### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by yodacom** [yarnpkg/yarn#5425]
**Which operating system are you using:**
**Please describe the steps you took when trying to install Yarn and what went wrong:**
macOS

After loading a git repository: git clone git@github.com:graphcool/graphql-server-example.git

and then using the repository YARN INSTALL I received a message to update yarn:

warning Your current version of Yarn is out of date. The latest version is "1.5.1" while you're on "1.3.2".
info To upgrade, run the following command:

$ curl -o- -L https://yarnpkg.com/install.sh | bash
=========
THIS IS THE MESSAGE I RECEIVED WHEN I USED THAT COMMAND:
===========

[1/2]: https://yarnpkg.com/latest.tar.gz --> /var/folders/1p/krc5yx0x29q9kds01gzr8tsw0000gn/T/yarn.tar.gz.XXXXXXXXXX.uBf9IkIp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    91  100    91    0     0    361      0 --:--:-- --:--:-- --:--:--   362
100   608    0   608    0     0    845      0 --:--:-- --:--:-- --:--:--  1501
100  914k  100  914k    0     0   466k      0  0:00:01  0:00:01 --:--:-- 1382k

[2/2]: https://yarnpkg.com/latest.tar.gz.asc --> /var/folders/1p/krc5yx0x29q9kds01gzr8tsw0000gn/T/yarn.tar.gz.XXXXXXXXXX.uBf9IkIp.asc
100    95  100    95    0     0    334      0 --:--:-- --:--:-- --:--:--   334
100   612    0   612    0     0   1433      0 --:--:-- --:--:-- --:--:--  597k
100   832  100   832    0     0   1669      0 --:--:-- --:--:-- --:--:--  1669
> Verifying integrity...
gpg: Signature made Mon Feb 26 12:01:19 2018 MST using RSA key ID B6FF4DE3
gpg: Can't check signature: public key not found
> GPG signature for this Yarn release is invalid! **This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.**

**Comment by petegleeson** [comment]
@yodacom I was facing this problem on macOS as well. I was able to get the install to work by manually importing the gpg signature with:

`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import`

This command was lifted from [this line](https://github.com/yarnpkg/website/blob/master/install.sh#L64) in the install script.

**Comment by yodacom** [comment]
Thanks Peter,

Glad you were able to sort through that.

Yeah I put up with it for some time.  It seems the latest versions of Yarn
update more readily using simple homebrew..

I do not remember how I went about getting to a later version on my mac but
I think someone suggested deleting all past versions and then start over
with Homebrew.  Installed  latest yarn using homebrew then used brew
upgrade. That seemed to fix the problem.

I may have also had two installations of yarn which could have gummed
things up as well.

Thanks for reporting your solution!


All the best,

Jeremy

Yoda of  YodaCom
jb@yodacom.com
www.yodacom.com

*Standard Disclosure:*
*YodaCom is a mobile application architect, strategist, and developer.
**“YodaCom
is also a DMTA - Digital Marketing Technology Architect and Advisor. *

**Comment by stephenway** [comment]
![screen shot 2018-03-07 at 11 01 50 am](https://user-images.githubusercontent.com/38894/37112405-27dc83ac-21f7-11e8-8695-99542708e9f6.png)

same issue today

**Comment by Daniel15** [comment]
Sorry about that. You likely have an older version of the GPG key that was imported before December 2017. For security, it's rotated once per year. You can import the latest GPG key to fix it:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import
```

Please let me know if you still see the issue after that.

https://github.com/yarnpkg/website/issues/761 will improve the installation script and update it to ensure the proper subkeys are available. If you'd like to send a PR for that, it'd be great. So far nobody has sent a PR to improve the installation script to handle this.
