### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#543]
Once we actually start translating the CLI, it will be pretty hard for us to troubleshoot and debug output and it will be hard for people to google things in their localized language without error codes.

We should add error codes to `MessageError` or change `MessageError` to directly take a language key and then print the language key as well as the localized message.

Examples:

```
error(123): The right-pad package was not found.
// or:
error(packageNotFound): The right-pad package was not found.
```

**Comment by partizanos** [comment]
Hello I would really like to start contributing to yarn.
Do you think it is a good start? 
I noticed the date of the original issue is a more than a year ago, is it still open intentionally or it is solved?
Is there any roadmap I could follow towards that contribution or a bit more detailed description? 

(@cpojer let me know if you can help me make replicate a scenario for this kind of messages)
(sorry if I am not to submit this comment hear if there is a dedicated slack/IRC/any other channel for this kind of discussions please prompt me there, thanks!)

**Comment by cpojer** [comment]
There is a #development channel on discord: https://discordapp.com/invite/yarnpkg join us there :)

**Comment by viatsko** [comment]
Are you planning to have this matching what npm has or completely independent?

**Comment by BYK** [comment]
@viatsko we may try to match npm as long as things align. Not sure if that's a great idea in the long term though since the projects can diverge.

**Comment by paul-soporan** [comment]
Closing as v2 has proper error codes: https://yarnpkg.com/advanced/error-codes

https://yarnpkg.com/getting-started/migration
