### ISSUE TITLE
yarn install --offline calls "scripts":"build" task inappropriately

### ISSUE THREAD

**Issue by damianb** [yarnpkg/yarn#5431]
**What is the current behavior?**

yarn 1.5.1 is running the "build" task for `node-sass` when using `yarn --offline`, instead of any "install", "postinstall", or other more appropriate scripts.  This, in turn, results in node-sass attempting to build on a system where no build dependencies are present, even when env vars are present pointing to prebuilt bindings.

In contrast, `yarn add` will *not* call the "build" script entry.  If I run `yarn add gulp-sass@^2.3.2`, the node-sass dependency will install successfully (because it skips the build task).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

yarn install should use install/postinstall tasks instead of build tasks, same as `yarn add`.

Note: enabling the experimental new feature for #5314 does not seem to have any effect.

**Please mention your node.js, yarn and operating system version.**

node 6.9.2, yarn 1.5.1, Win10 Pro x64.

**Comment by arcanis** [comment]
There is no build lifecycle. The build script is called because `node-sass` itself runs it:

https://github.com/sass/node-sass/blob/abbc65770ea6f16d2591cfc8046021301ed29d2d/package.json#L32-L32

**Comment by damianb** [comment]
That's not correct. 

What's getting called is this guy: 

https://github.com/sass/node-sass/blob/abbc65770ea6f16d2591cfc8046021301ed29d2d/package.json#L35

Note the difference - both are the same script, but one uses `--force`, and the one using `--force` causes it to ignore environment variables designating where a binding already lives (and to try it first).  What I'm seeing is that it is *immediately* trying to build, which is indicative of it hitting this guy:

https://github.com/sass/node-sass/blob/abbc65770ea6f16d2591cfc8046021301ed29d2d/scripts/build.js#L126-L128

Otherwise, we'd be making it to the sass.hasBinary() call, which when I run the script itself directly (same env vars), detects the correct path - which is evidenced by me seeing [these lines](https://github.com/sass/node-sass/blob/abbc65770ea6f16d2591cfc8046021301ed29d2d/scripts/build.js#L134).

**Comment by arcanis** [comment]
We do not execute any build lifecycle [afaik](https://github.com/yarnpkg/yarn/search?utf8=%E2%9C%93&q=executelifecyclescript&type=). I don't reproduce the behavior you've described myself, so I'll need a repro repository to better understand what happens.

**Comment by damianb** [comment]
Bizarrely, I'm trying to reproduce this on another system (almost 1:1), and I'm not getting the same symptoms.  Best that I can tell is that something is causing the SASS_BINARY_PATH env var to not make it through into dependency scripts when running `yarn --offline`, but...why?  I can't tell.

Going to go ahead and close this for now.  If I manage to work out the root cause, I'll chime back in.
