### ISSUE TITLE
Backslash escape issue in Windows error output

### ISSUE THREAD

**Issue by mjomble** [yarnpkg/yarn#5445]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
On Windows there are sometimes issues with escaping backslashes in the output. For example, the node-gyp error when python is not found looks like this:

```
gyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\\Program Files\
odejs\
ode_modules\
pm\
ode_modules\
ode-gyp\\lib\\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\\Program Files\
odejs\
ode_modules\
pm\
ode_modules\
ode-gyp\\lib\\configure.js:508:16)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a project with a dependency that uses node-gyp (for example `sharp`) and then make your python installation inaccessible globally. I can provide a more specific example if needed.

**What is the expected behavior?**
Instead of double backslashes and line breaks the paths should look like this: `C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js`

**Please mention your node.js, yarn and operating system version.**
Node 8.9.4
Yarn 1.5.1 (the problem was likely introduced after 1.3.2)
Windows 10

**Comment by rally25rs** [comment]
duplicate #5517
