### ISSUE TITLE
There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by telco2011** [yarnpkg/yarn#5447]
**Operating System**: Elementary OS Loki
**Yarn version**: 1.5.1
**node version**: 8.9.4

**PROBLEM**:
After update yarn to version 1.5.1, I can't install my project dependencies because yarn is not able to finish the installation process whereas if I use npm I don't have any problem.

The following message is always shown by yarn: 

> info There appears to be trouble with your network connection. Retrying...

I don't know why but the registry response time is increasing. 

`yarn install --verbose
[...]
verbose 9.127 Request "https://registry.yarnpkg.com/json-stringify-safe" finished with status code 200.
verbose 9.128 Performing "GET" request to "https://registry.yarnpkg.com/yargs".
verbose 9.128 Request "https://registry.yarnpkg.com/oauth-sign" finished with status code 200.
verbose 9.129 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fbody-parser".
verbose 9.875 Request "https://registry.yarnpkg.com/stringstream" finished with status code 200.
verbose 9.878 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fserve-static".
verbose 14.854 Request "https://registry.yarnpkg.com/performance-now" finished with status code 200.
verbose 14.856 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fexpress-serve-static-core".
verbose 16.468 Request "https://registry.yarnpkg.com/tough-cookie" finished with status code 200.
verbose 16.469 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fnode".
verbose 16.47 Request "https://registry.yarnpkg.com/tunnel-agent" finished with status code 200.
verbose 16.471 Performing "GET" request to "https://registry.yarnpkg.com/ansi-regex".
verbose 29.353 Request "https://registry.yarnpkg.com/uuid" finished with status code 200.
verbose 29.354 Performing "GET" request to "https://registry.yarnpkg.com/core-util-is".
verbose 29.359 Request "https://registry.yarnpkg.com/scss-tokenizer" finished with status code 200.
verbose 29.36 Performing "GET" request to "https://registry.yarnpkg.com/isarray".
verbose 51.424 Request "https://registry.yarnpkg.com/@types%2fbody-parser" finished with status code 200.
verbose 51.425 Performing "GET" request to "https://registry.yarnpkg.com/process-nextick-args".
verbose 51.426 Request "https://registry.yarnpkg.com/@types%2fserve-static" finished with status code 200.
verbose 51.426 Performing "GET" request to "https://registry.yarnpkg.com/string_decoder".
verbose 109.597 Request "https://registry.yarnpkg.com/ansi-regex" finished with status code 200.
verbose 109.598 Performing "GET" request to "https://registry.yarnpkg.com/util-deprecate".
verbose 109.599 Request "https://registry.yarnpkg.com/@types%2fexpress-serve-static-core" finished with status code 200.
verbose 109.6 Performing "GET" request to "https://registry.yarnpkg.com/buffer-shims".
info There appears to be trouble with your network connection. Retrying...
verbose 130.299 Request "https://registry.yarnpkg.com/core-util-is" finished with status code 200.
verbose 130.3 Performing "GET" request to "https://registry.yarnpkg.com/pseudomap".
verbose 130.303 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fnode".
info There appears to be trouble with your network connection. Retrying...
[...]`

Any help with this?

**Comment by telco2011** [comment]
I've checked with windows 10 environment as well and it happens the same situation. I can't use yarn to install my project dependencies.

**Comment by Phylu** [comment]
Same Problem here with macOS High Sierra (10.13.3)

**Comment by jschlieber** [comment]
Same probleme here....

**Comment by cwonrails** [comment]
Same issue.

**Comment by waptik** [comment]
is it a common problem for windows 10 users? 'cause i'm facing this same issue for some time now

**Comment by johpol** [comment]
Just want to add that I'm seeing this issue as well with Windows 10.

**Comment by wilfreddenton** [comment]
Try `yarn config delete proxy`. This worked for me. [source](https://github.com/yarnpkg/yarn/issues/4333#issuecomment-328046504)

**Comment by waptik** [comment]
@wilfreddenton it didn't work for me.

**Comment by esetnik** [comment]
I have the same issue

**Comment by SEAPUNK** [comment]
yarnpkg registry is running really slowly right now, occasionally erroring out with `haproxy_service_unavailable`

**Comment by esetnik** [comment]
Confirmed this is a npm outage https://status.npmjs.org/incidents/27bg84btqp7r

**Comment by jschlieber** [comment]
I don't think this issue is or was related to an npm outage...

**Comment by anilshrish** [comment]
This worked for me:

`yarn install --pure-lockfile --proxy http://<proxy-address>:<port>`

**Comment by azatakmyradov** [comment]
@anilshrish That worked for me, too. Thanks.
