### ISSUE TITLE
Failed to download resource "yarn"

### ISSUE THREAD

**Issue by sgm222** [yarnpkg/yarn#5458]
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Operation timed out

**Comment by rally25rs** [comment]
looks like an Amazon problem 😆 

Are you just trying to install yarn, or are you running a yarn command? I suspect AWS is just being flakey if it is timing out.

**Comment by rally25rs** [comment]
Is this still an issue or can we close this?

**Comment by ytt123** [comment]
I have trouble with npm install --global yarn  or  brew install yarn
1.brew install yarn  return this :curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443
2.  npm install --global yarn  return this:
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/yarn failed, reason: connect ETIMEDOUT 104.16.26.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yangtaotao/.npm/_logs/2021-01-05T04_41_28_809Z-debug.log
3.finally I checked my network and It is well

**Comment by merceyz** [comment]
Based on the commands you run that's clearly not an issue with Yarn, you're timing out on making requests to the registry, nothing we can do about that
