### ISSUE TITLE
Execution problem: Each command ends with error

### ISSUE THREAD

**Issue by hurvajs77** [yarnpkg/yarn#5465]
**macOS High Sierra 10.13.3**
**Yarn version: 1.5.1**

Each yarn command after successful execution ends with error.

Some content of log:
```
Arguments: 
  /usr/local/Cellar/node/9.3.0_1/bin/node /Users/hurvajs/.yarn/bin/yarn.js flow

PATH: 
  /Users/hurvajs/.yarn/bin:/Users/hurvajs/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

Yarn version: 
  1.4.1

Node version: 
  9.3.0

Platform: 
  darwin x64



Trace: 
  Error: Command failed.
  Exit code: 2
  Command: sh
  Arguments: -c flow
  Directory: /Users/hurvajs/Sites/XXX
  Output:
  
      at ProcessTermError.MessageError (/Users/hurvajs/.yarn/lib/cli.js:186:110)
      at new ProcessTermError (/Users/hurvajs/.yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/Users/hurvajs/.yarn/lib/cli.js:30822:17)
      at ChildProcess.emit (events.js:159:13)
      at maybeClose (internal/child_process.js:943:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

**Comment by rally25rs** [comment]
Looks like `flow` is exiting with status code `2` which indicates `flow` errored.
Is there any output from flow?

**Comment by hurvajs77** [comment]
yes, it's true. There are some errors. If I check one file, so all is ok. So, there isn't any reason, why stay this issue opened.

BTW, previous versions had another behaviour.

**Comment by rally25rs** [comment]
Yeah there is another issue I saw yesterday that indicated that the yarn-error file is now created if a command fails as well, so I think something changed in how errors were being caught, and now they trigger a full yarn failure as opposed to just being reported in the output. Might need to investigate that a big more. Thanks for the feedback.
