### ISSUE TITLE
`nohoist` struggles with .bin paths (monorepo using yarn workspace)

### ISSUE THREAD

**Issue by zvictor** [yarnpkg/yarn#5487]
**Bug report** for:
yarn v1.5.1
node v8.9.4
system macOS 10.13.3 (17D102)
kernel Darwin 17.4.0

**What is the current behavior?**

While using `nohoist`, some of the  symlinks in the `{PROJECT_PATH}/node_modules/.bin` folders point to **incorrect paths** 🎯

It affects the ".bin" files from the packages listed in the `nohoist` settings .

----

In my tests, if packages `A`, `B` and `C` have a common "non hoisted" dependency `Z` which contains a bin file `z-cli.js`, then:

* `C` (the last package to include `Z`) works properly, including the correct symlink to `z-cli.js`: 
  * `C/node_modules/.bin/z-cli.js -> ../Z/cli.js` ✅

* `A` and `B` have a symlink `z-cli.js` pointing to `C`'s `Z` (*they should point to their own Z instead*):
  * `A/node_modules/.bin/z-cli.js -> ../../../C/Z/cli.js` ⛔️
  * `B/node_modules/.bin/z-cli.js -> ../../../C/Z/cli.js` ⛔️

Interestingly, all packages (A, B and C) contain Z inside their `node_modules`. The only problem is that the ".bin" symlinks are not pointing to it.

**Comment by zvictor** [comment]
@connectdotz This issue might interest you. Do you think your PR #5442 could solve this bug?

**Comment by connectdotz** [comment]
#5442 addressed `-link-duplicates` flag specifically, don't think it will help here. This issue is interesting, I will need to take a deeper look.

**Comment by zvictor** [comment]
it works with yarn 1.6.0.
thanks so much, @connectdotz ! 🍻
