### ISSUE TITLE
Problem installing vscode

### ISSUE THREAD

**Issue by PauloSergioPereira** [yarnpkg/yarn#5490]
**Which operating system are you using:**
Raspberry Pi3 Dasbian

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I follow this VScode installation site:
https://www.gepatto.nl/running-visual-studio-code-on-a-raspberry-pi-3

When i try execute last command "./scripts/npm.sh install --arch=armhf "    I get an error:
########################################################################
pi@raspberrypi:~/Development/vscode $ ./scripts/npm.sh install --arch=armhf
yarn install v1.5.1
info No lockfile found.
$ node build/npm/preinstall.js
/home/pi/Development/vscode/build/npm/preinstall.js:6
let err = false;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node build/npm/preinstall.js
Directory: /home/pi/Development/vscode
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/pi/Development/vscode/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

 #######################################################################

I attached yarn-error-log
[yarn-error.log](https://github.com/yarnpkg/yarn/files/1795207/yarn-error.log)

Thanks in advance,
Paulo

**Comment by rally25rs** [comment]
Looks like you might want to post this to VSCode, since that is where the error happens. My hunch is that their postinstall script contains syntax that isn't supported in node v4. You might need a newer version of node.

I think it's basically this: https://stackoverflow.com/questions/40879777/block-scoped-declaration-let-const-function-class-not-yet-supported-outside-stri
