### ISSUE TITLE
Flags in `.yarnrc` can cause `yarn workspace` commands to fail.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [yarnpkg/yarn#5496]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Running a `yarn workspace` command while a flag is in the `.yarnrc` causes an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a repo with workspaces.
2. Create a `.yarnrc` with a flag included.
3. Run `yarn workspace WORKSPACE_NAME add PACKAGE_NAME`.

Here's a demo repo: https://github.com/wtgtybhertgeghgtwtg/yarnrc-workspace-flag
Run `yarn workspace package-one add react`.

**What is the expected behavior?**
The flag should be parsed and respected as it is for non-`workspace` commands.

**Please mention your node.js, yarn and operating system version.**
```
Yarn version: 
  1.5.1

Node version: 
  9.8.0

Platform: 
  linux x64
```

**Comment by rally25rs** [comment]
confirmed in current `master` (1.6.0-0)

```
~/Projects/yarn-test 🐒   yarn workspace package-one add left-pad
yarn workspace v1.5.1
yarn run v1.5.1
error An unexpected error occurred: "Command \"false\" not found.".
```

This probably has something to do with the way the flags are moved from the cfg file and passed to the `workspace` command. Passing the flag directly from the command line works:

```
yarn workspace package-one add left-pad --emoji=false
```
