### ISSUE TITLE
Unexpected error output when npm scripts failed

### ISSUE THREAD

**Issue by g-plane** [yarnpkg/yarn#5509]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
If I ran a npm script without calling some shell commands and the npm script failed, `yarn-error.log` will be generated.

IMO this is an annoying behavior because I just run unit test such as running `yarn jest` or a npm script like `yarn test`. If the tests failed, the error log will be outputed.

It is common that the unit tests even other non-shell commands failed. However, outputing the log everytime is unexpected.

**If the current behavior is a bug, please provide the steps to reproduce.**
For example, here is `package.json`:
```json
{
  "scripts": {
    "test": "jest"
  }
}
```
If I run `yarn test`, once the unit tests failed, a `yarn-error.log` will be generated.

**What is the expected behavior?**
If the npm script failed, no log will be generated.
If shell commands failed, error log should be generated.

Here is an example:
```json
{
  "scripts": {
    "test": "jest",
    "deploy": "sh deploy.sh"
  }
}
```
If I run `yarn test` and it failed, `yarn-error.log` should not be generated. However, if I run `yarn deploy` and it failed, error log should be generated.

**Please mention your node.js, yarn and operating system version.**
Yarn 1.5.1

**Comment by rally25rs** [comment]
duplicate #5457
