### ISSUE TITLE
Backslashes in output from yarn fail when they match standard escape sequences in Windows

### ISSUE THREAD

**Issue by zhulika** [yarnpkg/yarn#5517]
The error reporting seems to have an escaping issue with folder names that start with 'n' on Windows. For example, when printing an error from the ```yarn start``` command, it outputs the directory :

```
Directory: C:\root\name
```
as:
```
Directory: C:\\root\\
ame
```

This is on Windows 10 and with yarn v1.5.1

**Comment by BYK** [comment]
Relevant code: https://github.com/yarnpkg/yarn/blob/a35a4f97dd7e5f6f029b5e0f855bfd73ef338ca4/src/reporters/base-reporter.js#L46-L49
