### ISSUE TITLE
No Documentation for link: Dependencies

### ISSUE THREAD

**Issue by sth** [yarnpkg/yarn#5527]
**It's a *documentation bug*.**

Yarn seems to supports `link:` dependencies in package.json, but that doesn't seem to be documented anywhere. At least the docs for [dependencies](https://yarnpkg.com/en/docs/dependencies) or [`yarn add`](https://yarnpkg.com/en/docs/cli/add) don't mention it. Google only brings up documentation about the `yarn link` command.

I was able to find the associated [rfc](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-link-dependency-type.md) by investigating a testcase with `git blame`, but it's not exactly obvious.

**What is the current behavior?**
Nobody is told about the feature,

**What is the expected behavior?**
The feature should be mentioned in the documentation. It's a very useful feature, but it's of no use if nobody knows it exists.

**Comment by rally25rs** [comment]
I opened this as an issue in the yarnpkg/website repo, which is where the docs live:
https://github.com/yarnpkg/website/issues/793
