### ISSUE TITLE
yarn pack is confusing and weird

### ISSUE THREAD

**Issue by srcspider** [yarnpkg/yarn#5529]
**Do you want to request a *feature* or report a *bug*?**
BUG?

**What is the current behavior?**
https://yarnpkg.com/en/docs/cli/pack

The documentation is as follows...
>### yarn pack
>Creates a compressed gzip archive of package dependencies.
>### yarn pack --filename <filename>
>Creates a compressed gzip archive of package dependencies and names the file filename.

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
yarn pack
```

**What is the expected behavior?**

This is how I read the documentation as: 
_Packages the `node_modules` with only "dependencies" section into a `.tgz` file._

This is what it actually does:
_Complains about a project with `"private": true` in the package.json file not having name and version. Subsequently doesn't use `name` and `version` for anything. Then archives everything in the current directory in a archive hardcoded with a directory "package" in it, **except for**, `node_modules` (as well as others like `dist` etc)_

If this is correct, whats even the use case? :unamused:

The use case for archiving `node_modules` would be to avoid inode pollution, eg. docker images sitting in system cache would still eat that much inodes even if not running (it adds up fast). There would still be some problems for this use case: no `yarn unpack`, no `yarn pack --autoclean` (or integration with `yarn autoclean`) but that's not really as important as just being able to prune out devDependencies _easier then a re-install_ (re-installs have their own issues, not 100% if it's the exact same dependency).

**Please mention your node.js, yarn and operating system version.**

node v8.9.3, yarn 1.5.1, ubuntu 16.04

**Comment by rally25rs** [comment]
It _should_ do the same thing as [npm pack](https://docs.npmjs.com/cli/pack) for which the docs are also unclear and confusing 😉

**Comment by rally25rs** [comment]
I opened this is a docs issue over in the yarnpkg/website repo:
https://github.com/yarnpkg/website/issues/792
