### ISSUE TITLE
ESOCKETTIMEDOUT on 31 MB package material-design-icons

### ISSUE THREAD

**Issue by dankohn** [yarnpkg/yarn#5540]
**What is the current behavior?**

```
$ yarn
yarn install v1.5.1
$ node tools/nodeVersionCheck.js
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/material-design-icons/-/material-design-icons-3.0.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dan/Dropbox/Documents/dev/landscape/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Repo is open source: https://github.com/cncf/landscape

**What is the expected behavior?**

Expecting `material-design-icons` to correctly download and install. Note that I can fetch `https://registry.yarnpkg.com/material-design-icons/-/material-design-icons-3.0.1.tgz` using my web browser.

I then tried installing that file (which is 32 MB) with:

```
$ yarn add ~/Downloads/material-design-icons-3.0.1.tgz 
yarn add v1.5.1
$ node tools/nodeVersionCheck.js
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning Pattern ["material-design-icons@/Users/dan/Downloads/material-design-icons-3.0.1.tgz"] is trying to unpack in the same destination "/Users/dan/Library/Caches/Yarn/v1/npm-material-design-icons-3.0.1-9a71c48747218ebca51e51a66da682038cdcb7bf" as pattern ["material-design-icons@3.0.1"]. This could result in non-deterministic behavior, skipping.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```
but it again hangs. I also tried `rm -rf /Users/dan/Library/Caches/Yarn/v1/npm-material-design-icons-3.0.1-9a71c48747218ebca51e51a66da682038cdcb7bf` before installing but it didn't make any difference.

Note that `npm install` works.

**Please mention your node.js, yarn and operating system version.**
```
$ yarn -v
1.5.1
$ node -v
v9.8.0
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D102)
      Kernel Version: Darwin 17.4.0
```
I completely uninstalled Homebrew and then reinstalled it, Node and Yarn but got the identical behavior.

**Comment by rally25rs** [comment]
Related: #5055 

https://github.com/google/material-design-icons/issues/133

**Comment by rally25rs** [comment]
I believe we let node or the OS use whatever its default is (normally we don't pass a timeout), but you can override it by adding this line to a `.yarnrc` file in your project root:

```
network-timeout 600000
```

where the number is milliseconds to wait (600000ms = 10min)

**Comment by dankohn** [comment]
@rally25rs Thanks. Adding the `.yarnrc` resolved my issue, and I also appreciate your link to https://github.com/jossef/material-design-icons-iconfont as a much smaller repo.

I'm closing as resolved.

**Comment by sagarpanda19** [comment]
I am getting same error, please help me

[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.3.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "C:\\RHB_1610\\Domus\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by RemeJuan** [comment]
> I am getting same error, please help me

Please scroll up, you will notice a fix was posted over a year ago.

**Comment by yameogosamuel** [comment]
Thank you, I too was able to solve my problem with the .yarnrc file

**Comment by ritik307** [comment]
@rally25rs thankyou so much  adding 
`network-timeout 600000`
in .yarnrnc worked like a charm.

**Comment by fast-and-curious-1910** [comment]
@rally25rs .yarnrc does not work for me! i made the yarnrc file and i get this error.
```bash
SyntaxError: Unknown token: { line: 1, col: 0, type: 'INVALID', value: undefined } 1:0 in E:\Coding Projects\FNB\main\.yarnrc
    at Parser.unexpected (C:\Program Files (x86)\Yarn\lib\cli.js:63442:11)
    at Parser.parse (C:\Program Files (x86)\Yarn\lib\cli.js:63573:14)
    at parse (C:\Program Files (x86)\Yarn\lib\cli.js:63647:21)
    at module.exports.exports.default (C:\Program Files (x86)\Yarn\lib\cli.js:63209:96)
    at loadRcFile (C:\Program Files (x86)\Yarn\lib\cli.js:56943:58)
    at C:\Program Files (x86)\Yarn\lib\cli.js:56917:14
    at C:\Program Files (x86)\Yarn\lib\cli.js:97254:14
    at Array.map (<anonymous>)
    at parseRcPaths (C:\Program Files (x86)\Yarn\lib\cli.js:97252:78)
    at Object.findRc (C:\Program Files (x86)\Yarn\lib\cli.js:97266:10)
```

I am on windows , and copied the yarnrc exactly!

**Comment by apiraino** [comment]
So, if I understand correctly the accepted solution for the network timeout error is to increase the timeout wait?

(I am asking because I can't seem to find other explainations other than this workaround)

**Comment by rally25rs** [comment]
@fast-and-curious-1910 that is odd. I haven't looked at the yarnrc parsing in a while, but maybe it is sensitive to windows vs linux style line endings? That would be my best guess anyway.

**Comment by ChoongLiang** [comment]
> I believe we let node or the OS use whatever its default is (normally we don't pass a timeout), but you can override it by adding this line to a `.yarnrc` file in your project root:
> 
> ```
> network-timeout 600000
> ```
> 
> where the number is milliseconds to wait (600000ms = 10min)
> 
> Please note that even if it doesn't timeout during the download, it's still probably going to take several minutes to un-tar the archive, since it has somewhere close to 90,000 files in it 😞

Works like a charm
