### ISSUE TITLE
yarn does not respect npm globalconfig

### ISSUE THREAD

**Issue by schneidmaster** [yarnpkg/yarn#5543]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. Place an `npmrc` file in the custom location of your choice, e.g. `/var/npmrc`

2. Export an env variable to [tell npm where the global config](https://docs.npmjs.com/misc/config#npmrc-files) is: `export NPM_CONFIG_GLOBALCONFIG="/var/npmrc"`

3. Run `yarn install --verbose` from the project root; you'll see many lines like `Checking for configuration file "/home/zach/.npmrc".` but none checking for the npm global config. As a result, the `yarn install` might fail if e.g. you have the npm authToken in the global config. I am also curious if this might be a partial cause of #4451 (it was in my case).

**What is the expected behavior?**

Yarn checks in `NPM_CONFIG_GLOBALCONFIG` (and/or `npm config get globalconfig`) for configuration.

**Please mention your node.js, yarn and operating system version.**

node v8.9.3
yarn v1.5.1
reproduced on macOS v10.13.3 and ubuntu 14.04

**Comment by alopezsanchez** [comment]
Hello!

Is this issue picked? I'd like to submit a PR. Can you give me any guidance? 😃 
Thank you!

**Comment by dotfold** [comment]
@alopezsanchez Hey! I've just encountered this issue myself, and had a quick look as to where the configs are read in.

It looks like the resolution order for `.npmrc` is here: https://github.com/yarnpkg/yarn/blob/master/src/registries/npm-registry.js#L211 and the respective tests are: https://github.com/yarnpkg/yarn/blob/master/__tests__/registries/npm-registry.js#L703

You can see there that it looks like the env var `NPM_CONFIG_GLOBALCONFIG` is not considered in the possible locations.

If you do pick up this issue, please comment back here with any progress! Good luck 👍

**Comment by paul-soporan** [comment]
Closing as in v2 we completely stopped reading `.npmrc` files.

https://yarnpkg.com/getting-started/migration
