### ISSUE TITLE
The \"path\" argument must be of type string

### ISSUE THREAD

**Issue by empjStang** [yarnpkg/yarn#5545]
Try to add css-purge to my current project.
-> yarn add -D css-purge
 and receiving this error:

Fetching packages...
verbose 5.84 Performing "GET" request to "https://registry.yarnpkg.com/css-purge/-/css-purge-3.0.4.tgz".
verbose 5.977 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:1207:5)
    at module.exports.exports.default (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:95837:16)
    at /usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:52427:63
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:109:13
    at <anonymous>
error An unexpected error occurred: "The \"path\" argument must be of type string".

Not sure if it's a yarn or a css-purge bug.

Can anyone help?

Thanks

**Comment by TrySound** [comment]
Don't put this thing in the title. You broke github markup on mobile.

**Comment by merceyz** [comment]
Most likely the same as https://github.com/yarnpkg/yarn/issues/8331
