### ISSUE TITLE
Yarn fails to install material-design-icons package everytime on appveyor

### ISSUE THREAD

**Issue by sinedied** [yarnpkg/yarn#5546]
**Do you want to request a *feature* or report a *bug*?**
A Bug

**What is the current behavior?**
See https://ci.appveyor.com/project/sinedied/generator-ngx-rocket/build/272/job/i362xiyteu2hplrb

Here is the relevant log:
```
Running yarn install, please wait...
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
warning @biesbjerg/ngx-translate-extract > chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
warning htmlhint > jshint > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning htmlhint > jshint > cli > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
warning karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
warning karma > log4js > nodemailer > mailcomposer@4.0.1: This project is unmaintained
warning karma > log4js > nodemailer > socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning karma > log4js > mailgun-js > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning karma > log4js > nodemailer > mailcomposer > buildmail@4.0.1: This project is unmaintained
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/material-design-icons/-/material-design-icons-3.0.1.tgz: ESOCKETTIMEDOUT".
```

Yarn fails to install the `material-design-icons@3.0.1` package everytime on appveyor.
I can confirm though that installing this package works on my local OSX machine with `yarn@1.5.1`.

Note that the same appveyor build was perfectly some weeks ago.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using appveyor with yarn@1.5.1, try to install an app with the `material-design-icons@3.0.1` dependency.

**What is the expected behavior?**
Installation works fine.

**Please mention your node.js, yarn and operating system version.**
```
OS: default appveyor Windows image
node -v
v9.8.0
npm -v
5.6.0
```

**Comment by neXorianus** [comment]
does not seem to be only material-design-icon related...
see https://github.com/yarnpkg/yarn/issues/2850

**Comment by sinedied** [comment]
Seems that even the Yarn CI itself is broken on Appveyor: https://ci.appveyor.com/project/kittens/yarn/branch/master

And yes it's not limit to one package...

**Comment by rally25rs** [comment]
duplicate #5540

That package is pretty big and it will timeout eventually on a slow connection. Yarn doesn't pass a connection timeout by default to the underlying request library, so the actual timeout might vary by OS or node version. However you can set a `network-timeout {milliseconds}` in your `.yarnrc` file.
