### ISSUE TITLE
peerDependencies duplication - causing fatal errors (e.g. for webpack)

### ISSUE THREAD

**Issue by IgorMinar** [yarnpkg/yarn#555]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

peerDependencies are unexpectedly duplicated during installation.

**If the current behavior is a bug, please provide the steps to reproduce.**

given package.json:

```
{
  "name": "peer-deps-test",
  "version": "1.0.0",
  "devDependencies": {
    "webpack": "beta"
  }
}
```

do `yarn install` to install the dependencies.

then add a webpack plugin that has a `peerDependencies` field containing `webpack`, e.g. `html-webpack-plugin`

```
yarn add html-webpack-plugin --dev
```

the plugin is installed, but so is another copy of webpack:

```
$ ls node_modules/html-webpack-plugin/node_modules/
cliui                crypto-browserify    https-browserify     isarray              os-browserify        ripemd160            stream-browserify    uglify-js            watchpack            window-size          yargs
constants-browserify enhanced-resolve     interpret            node-libs-browser    readable-stream      sha.js               tapable              url                  webpack              wordwrap
```

**What is the expected behavior?**

The already installed version of webpack should have sufficiently meet the peerDep requirement without installing an additional copy.

This kind of duplication for peerDependencies not only wastes time/resources but also causes fatal issues - in this case the webpack build will fail if the plugin is loaded.

Interestingly, if no webpack is installed prior to installation of the html-webpack-plugin (with peerDep on webpack), the `yarn add` will still succeed, installing the webpack automatically, but the webpack version is hoisted to the top level. In many cases this is actually desirable, but it's not how npm works. Is this by design?

**Please mention your node.js, yarn and operating system version.**

node v5.4.1
yarn v0.14.0
os: MacOS X

**Comment by IgorAufricht** [comment]
Shouldn't there be tests to prevent regressions like this?
