### ISSUE TITLE
"yarn install node" seems not provide node in node_modules/.bin

### ISSUE THREAD

**Issue by Bastorx** [yarnpkg/yarn#5552]
v1.5.1

**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
yarn install node doesn't provide node_modules/.bin/node, npm install work

**If the current behavior is a bug, please provide the steps to reproduce.**
Type yarn install node@9.7.0

**What is the expected behavior?**
node binary in node_modules/.bin

**Please mention your node.js, yarn and operating system version.**
node 9.8.0
yarn 1.5.1
OS = Mac OS Sierra

**Comment by Bastorx** [comment]
I'm not really sure, but this issue could be only visible with Mac OS environment. I already tried with Docker Alpine without problem, I have got a node_modules/.bin/node

**Comment by rally25rs** [comment]
possibly related to #3421

**Comment by rally25rs** [comment]
Did some debugging to confirm that this is a duplicate of #3421
Yarn tries to make the link before the node package finishes making the executable.
