### ISSUE TITLE
Consider replacing `fs` calls with a lib that deals with OS specific edge cases.

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/yarn#5554]
There is a fair amount of code in `fs.js` (or `fs-normalized.js` once #5470 is accepted) that deals with oddities in case sensitive, timestamp preservation, file access differences across OSs and Node versions.

We should explore simplifying this by using a 3rd party library instead.
Perhaps https://github.com/jprichardson/node-fs-extra
which seems to do checks for the existance of `fs.copyFile` and timestamp normalization.

Need to evaluate performance on several OS's (OSX, Win, Linux) and node versions (pre and post 8.5.0)

**Comment by arcanis** [comment]
Yep I'd support that. Once advantage of `fs-extra` is that it automatically wraps everything to return promises, which would allow us to remove at least [this part of fs](https://github.com/yarnpkg/yarn/blob/master/src/util/fs.js#L27-L41).

**Comment by paul-soporan** [comment]
Closing this as we now use [`@yarnpkg/fslib`](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-fslib) in the v2 that handles everything in a type-safe way.
