### ISSUE TITLE
set: Warning: $PATH entry "/Users/<me>/.yarn/bin" is not valid (No such file or directory)

### ISSUE THREAD

**Issue by tony-kerz** [yarnpkg/yarn#5555]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
when i start a terminal session, i get:

```
set: Warning: $PATH entry "/Users/tony/.yarn/bin" is not valid (No such file or directory)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- i might have installed `yarn` via `curl` a while back, but have been using `homebrew` for a while

**What is the expected behavior?**

stale/invalid location not on path

**Please mention your node.js, yarn and operating system version.**
node: `9.8.0`
yarn: `1.5.1`
os: osx `10.11.6`

> my main thing now is that i would like to remove that invalid location from my path, but i can't spot where it is being added, not in ~/.bashrc, ~/.bash_profile, ~/.profile, ~/.config/fish/config.fish, any suggestions on steps-to-take/places-to-look to have this non-existent folder not added to my path...?

**Comment by rally25rs** [comment]
Swapped assignees to @Daniel15 who I think knows the most about the install magic...

**Comment by tony-kerz** [comment]
i just stumbled upon a file at `~/.config/fish/fishd.<some-sha>` which had a line in it like:
```
SET fish_user_paths:/Users/tony/Library/Python/3\x2e6/bin\x1e/Users/tony/\x2eyarn/bin
```
so i edited to look like:
```
SET fish_user_paths:/Users/tony/Library/Python/3\x2e6/bin
```
and that did the trick for me. 

leaving solution here for future reference...
