### ISSUE TITLE
'Invalid hosted git fragment' Private NPM package

### ISSUE THREAD

**Issue by walshie4** [yarnpkg/yarn#5565]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn` produces the following error
```
yarn install v1.5.1
[1/4] 🔍   Resolving packages...
[2/4] 🚚   Fetching packages...
error An unexpected error occurred: "Invalid hosted git fragment <name of private package>"
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Can attempt this later if necessary, seems like a more fundamental issue though since it is using the `hosted-git-resolver.js` for an npm package.

https://github.com/yarnpkg/yarn/blob/63598f401923209c38f9654a93169b0bccb43f24/src/resolvers/exotics/hosted-git-resolver.js#L19

**What is the expected behavior?**
Package is installed from npm

**Please mention your node.js, yarn and operating system version.**
MacOS 10.13.3
node v8.9.4
yarn v1.5.1

**Comment by rally25rs** [comment]
Can you share the format of the dependency entry in `package.json`? like:

```
"dependencies": {
  "@myorg/mypackage": "^1.2.3"
}
```

yarn parses that stuff to decide which resolver to use.

**Comment by walshie4** [comment]
The line the error points to (in terms of package name mentioned in the error) is the first dependency, formatted like this:
```
  "dependencies": {
    "@honeyscience/datastore-pubsub": "^0.2.2",
    ... <other deps here>
```

**Comment by rally25rs** [comment]
Does the `package.json` file for `@honeyscience/datastore-pubsub` have a `repository` field defined in it? If so, I think yarn is trying to "normalize" that field into a git url.

**Comment by walshie4** [comment]
It does, but it is not in a proper git remote format.  

Fixed it up and it appears to have resolved this issue.  Thanks for your help!
