### ISSUE TITLE
Yarn is not working on Windows 10?

### ISSUE THREAD

**Issue by DevJoseWeb** [yarnpkg/yarn#5566]
Is not there a manual or tutorial to install on Windows 10?

**Comment by rally25rs** [comment]
There is an .msi installer for windows https://yarnpkg.com/en/docs/install#windows
I've used that on my Win10 Surface without issue. Is there a specific problem you are having?

**Comment by Daniel15** [comment]
Direct link to the installer download: https://yarnpkg.com/latest.msi

Once you install it, the "yarn" command should be available at the command-line (you'll need to open a new command prompt, ones that are already open won't have Yarn on the path).

Let us know if you have any issues with it!

**Comment by YhorbyMatias** [comment]
It was  happening to you just need to close the cmd or PowerShell open again and re-type the command,
