### ISSUE TITLE
Cannot find module 'request-progress'

### ISSUE THREAD

**Issue by Vangi** [yarnpkg/yarn#5568]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
When using  `yarn install` an error occurs: 
[1/4] Resolving packages...
warning bootstrap-treeview > express > connect@2.12.0: connect 2.x series is deprecated
warning bootstrap-treeview > ejs@2.2.4: Critical security bugs fixed in 2.5.5
warning bootstrap-treeview > phantomjs > request > node-uuid@1.4.8: Use uuid module instead
warning bootstrap-treeview > phantomjs > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error An unexpected error occurred: "C:\\Users\\VanKol00\\Source\\Kolarovi\\MEADA\\Main\\Server\\Web\\wwwroot\\lib\\phantomjs: Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c node install.js
Directory: C:\\Users\\VanKol00\\Source\\Kolarovi\\MEADA\\Main\\Server\\Web\\wwwroot\\lib\\phantomjs
Output:
module.js:538
    throw err;
    ^
Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\\Users\\VanKol00\\Source\\Kolarovi\\MEADA\\Main\\Server\\Web\\wwwroot\\lib\\phantomjs\\install.js:9:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)".

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create the following `package.json`:
{
  "dependencies": {
    "bootstrap": "3.3.7",
    "bootstrap-treeview": "^1.2.0"
  }
}
2. Run command `yarn install`

**What is the expected behavior?**
All packages should be installed successfully.

**Please mention your node.js, yarn and operating system version.**

Yarn version: 
  1.5.1

Node version: 
  8.9.1

Platform: 
  win32 x64

npm manifest: 
  {
    "dependencies": {
      "bootstrap": "3.3.7",
      "bootstrap-treeview": "^1.2.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by rally25rs** [comment]
Not sure if this is exactly the same problem you are having, but `bootstrap-treeview`'s install script [calls bower](https://github.com/jonmiles/bootstrap-treeview/blob/master/package.json#L27) so you _have_ to have `bower` installed too.

I ended up having to `yarn global add bower` so that I had the `bower` command globally, then `yarn install` would succeed.

**Comment by Vangi** [comment]
Thank for the suggestion rally25rs but even after I added bower globally I have the same error.

**Comment by rally25rs** [comment]
hmm, I'm not sure what the issue might be then. With bower installed, I don't get any error

```
~/Projects/yarn-test 🐒   cat package.json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "bootstrap": "3.3.7",
    "bootstrap-treeview": "^1.2.0"
  }
}

~/Projects/yarn-test 🐒   yarn
yarn install v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning bootstrap-treeview > express > connect@2.12.0: connect 2.x series is deprecated
warning bootstrap-treeview > ejs@2.2.4: Critical security bugs fixed in 2.5.5
warning bootstrap-treeview > phantomjs > request > node-uuid@1.4.8: Use uuid module instead
warning bootstrap-treeview > phantomjs > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 5.87s.
```

Maybe try adding the `--verbose` flag and see if it gives any more error details?

**Comment by Vangi** [comment]
I found the reason of this error. I'm trying to add all my third party components to a folder `wwwroot/lib` instead of `node_modules`. Therefore I'm using **.yarnrc** file and the content is:
`yarn install --modules-folder wwwroot/lib`
If I remove the **.yarnrc** file then the packages were installed. 
Am I correctly configured yarn?

**Comment by rally25rs** [comment]
Oh, yeah, that would certainly explain it. When node.js resolves packages for `require()` statements, it _only_ looks for folders named `node_modules` so installing to a different folder name will break anything running with node. This limitation makes `modules-folder`'s use pretty limited.

**Comment by Vangi** [comment]
Thank you rally25rs, that makes complete sense. But is there a way to workaround this issue? I really would like to use yarn to separate these libraries in different directory that fits to my folder structure.

**Comment by rally25rs** [comment]
Unfortunately there isn't. Almost all of this npm package registry stuff was historically built with only node.js packages in mind.

What I do is use Browserify or Webpack to go collect the things from node_modules that are needed for my web app and move them to a separate directory. I also have a script that copies static assets like fonts and images to a separate directory.
