### ISSUE TITLE
Info/error output broken with directory names starting with "n" on Windows

### ISSUE THREAD

**Issue by qtiki** [yarnpkg/yarn#5582]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Info and error output on Windows is broken for directory names starting with the letter `n` on Windows.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
cd \
mkdir node_stuff
yarn run foobar
```

Output:
```
yarn run v1.5.1
error An unexpected error occurred: "Couldn't find a package.json file in \"C:\\
ode_stuff\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\
ode_stuff\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that Yarn is treating the `\n` part in the filename as a linefeed. Also the output contains a lot of unnecessary `\`-escapes that clutter the information.

**What is the expected behavior?**

Expected output:
```
yarn run v1.5.1
error An unexpected error occurred: "Couldn't find a package.json file in "C:\node_stuff"".
info If you think this is a bug, please open a bug report with the information provided in "C:\node_stuff\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Please mention your node.js, yarn and operating system version.**

* Yarn v1.5.1
* Node v6.10.3
* Microsoft Windows [Version 10.0.16299.309]

**Comment by rally25rs** [comment]
duplicate #5517
