### ISSUE TITLE
Yarn adds "false" as version range instead of default ^

### ISSUE THREAD

**Issue by DalderupMaurice** [yarnpkg/yarn#5587]
**What is the current behavior?**
Whenever I execute `yarn add -D xxxx` where xxxx is ANY dependency, this is added to my package,json as `false1.0.0` (or whatever the latest version of the package is). 

However, instead of `false` I'd expect a `^`

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add -D xxxx` --> xxxx = any dependency
This was replicated using yarn version 1.5.1

**What is the expected behavior?**
in package.json there `false` should be replaced with `^` as the version range

**Please mention your node.js, yarn and operating system version.**
node v8.10.0 (npm v5.6.0), yarn 1.5.1 - MacOSX

**Comment by rally25rs** [comment]
You probably have a .yarnrc with an incorrect setting.

What is the output if you run `yarn config list`?

**Comment by DalderupMaurice** [comment]
Thanks for pointing out! `.yarnrc` was indeed wrong. It had
`save-prefix false` in it.
