### ISSUE TITLE
Request for 1.5.2 release

### ISSUE THREAD

**Issue by dannycochran** [yarnpkg/yarn#5590]
Per comment here:

https://github.com/yarnpkg/yarn/pull/5442#issuecomment-373817156

1.5.1 was released a month ago, and there are have been a lot of helpful commits since 1.5.1, including the one that fixes linkDuplicates for symlinks.

While nightly builds are great, I can't really ask a team of engineers to go through that process. Is it possible to ship a version, 1.5.2, that includes some, if not all, of the commits to master since 1.5.1?

**Comment by thecodejack** [comment]
I think next would be minor...but I am also waiting for sometime..there are few fixes for next release which can make yarn more easier to use.

**Comment by Daniel15** [comment]
cc @yarnpkg/core - What do you think of releasing a new minor version soon?

**Comment by thecodejack** [comment]
@dannycochran minor would be 1.6.0

@Daniel15 Please do needful to release a version. As @dannycochran sadi, too many fixes are merged which can help many to have better yarn usage.

**Comment by BYK** [comment]
Heya! Sorry about the delays here. We want to release a new version quite soon.

There are also conversations happening around whether we should automate the releases to happen at a fixed frequency. There were some concerns around a final "human sanity check" and I know we need some more structure to be able to determine the correct version number from commit logs. If there's interest we can open a new ticket and discuss it there (or may be create an RFC).

**Comment by arcanis** [comment]
I just released the 1.6.0 🙂 The changelog is missing, I'll get to that tomorrow.

**Comment by arcanis** [comment]
Note that we haven't bumped the `latest` tag yet, so if you install Yarn through npm you'll need to use `npm install yarn@1.6.0` to get the right one.

**Comment by Daniel15** [comment]
Other installation methods:
Installation script: Use `--rc` flag
Tarball: https://yarnpkg.com/latest-rc.tar.gz
Windows: https://yarnpkg.com/latest-rc.msi

I really need to revive my PR to make RC installation instructions more obvious on the Yarn site...

**Comment by ojab** [comment]
…and still waiting for changelog ._.

**Comment by BYK** [comment]
Closing since v.1.6.0 is out. We'll provide a changelog soon.
