### ISSUE TITLE
WSL: yarn always links all dependencies

### ISSUE THREAD

**Issue by csvan** [yarnpkg/yarn#5591]
**Do you want to request a *feature* or report a *bug*?**

Bug (possibly env related)

**What is the current behavior?**

When running yarn 1.5.1 in Windows Subsystem for Linux (WSL) on Windows 10 (1703), repeated installs will copy ALL dependencies from the yarn cache to node_modules, rather than just the ones that have changed since last install. I.e. the `linking dependencies` step will be repeated in full each install.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) run `yarn install` in WSL on a project with at least one dependency
2) Remove the `yarn.lock` file
3) run `yarn install` again

**What is the expected behavior?**

Subsequent installs should only link the dependencies which have changed.

The above, correct behavior occurs when the process is repeated in Cygwin or Powershell, and hence only happens in WSL.

**Please mention your node.js, yarn and operating system version.**

Node 9.8, Yarn 1.5.1, Windows 10 Enterprise (1703)

**Comment by swrobel** [comment]
I believe this happens on all platforms. It definitely does on my machines, macOS 10.13.

**Comment by csvan** [comment]
I'm absolutely sure this does not happen under Cygwin. Need to see if I can reproduce on a Linux box

**Comment by justjoeyuk** [comment]
This really needs to be fixed, taking 5-10 mins for me to add a single package at this state.

**Comment by rally25rs** [comment]
duplicate #932 (there is a PR open as well)
