### ISSUE TITLE
EPERM: operation not permitted because of uws package

### ISSUE THREAD

**Issue by MaralS** [yarnpkg/yarn#5597]
**What is the current behavior?**
An error is occuring when I want to install a package in my project doing a simple yarn add.

I have this error in my console log : 
```
error An unexpected error occurred: "EPERM: operation not permitted,
 unlink 'D:\\Maral Sabbagh\\Documents\\Personnel\\Projets\\Maral_Sab
bagh\\Developpement\\gatsby-boilerplate\\node_modules\\uws\\uws_win3
2_57.node
```
I tried to  :

- Delete `node_modules/ ` folder
- Install all the packages with `yarn install`
- Delete `.cache/` and `public/` folders
- do` yarn cache clean`
- do  `yarn autoclean --force`
- do  `yarn upgrade-interactive`
- uninstall and reinstall node, npm and yarn
-

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone my repository `git clone https://github.com/MaralS/gatsby-boilerplate.git`
2. `yarn install `
3. Add another package like react-headroom by doing ` yarn add react-headroom`

 
**What is the expected behavior?**

A successfull installation. No error.

**Please mention your node.js, yarn and operating system version.**

- Windows 10
- yarn 1.3.2
- node 8.11.0

Thanks in advance  for your help

**Comment by NitroGhost** [comment]
@MaralS what did you do to get around this issue?
