### ISSUE TITLE
Error when adding pm2 - Tarball is not in network and can't be located in cache

### ISSUE THREAD

**Issue by ericvicenti** [yarnpkg/yarn#560]
Using the latest `yarn`, I get this error when running `yarn add pm2` in a fresh package:

```
error gkt@http://tgz.pm2.io/gkt-1.0.0.tgz: Tarball is not in network and can't be located in cache (/Users/evv/testPkg/gkt@http:/tgz.pm2.io/gkt-1.0.0.tgz)
```

The stacktrace refers to an internal version of yarn, so fb employees can see it here: https://phabricator.intern.facebook.com/P56726687 (sorry for the inconvenience!).

**Comment by alejomendoza** [comment]
Still getting this on the latest `yarn` version 0.17.8

**Comment by asfernandes** [comment]
I'm having this problem with v0.18.1 with different packages. I install the package in a machine and commit package.json and yarn.lock. In another machine, the error happens.

I then need to yarn add the package again in the second machine.

**Comment by seawatts** [comment]
Also seeing the same behavior

**Comment by abourget** [comment]
Same here..

**Comment by abourget** [comment]
Adding "v" in front of the versions naked "1.2.3" version numbers seems to work around the issue, but it doesn't work when hitting transient dependencies.

I'm using latest yarn as of today.

**Comment by abourget** [comment]
I'm seeing that with 0.22.0 too..

**Comment by abourget** [comment]
Ok, got reproducible steps here, in a clean dir put:

`Dockerfile`:
```
FROM node:6.9
ADD . /app/
RUN wget https://github.com/yarnpkg/yarn/releases/download/v0.20.4/yarn-0.20.4.js -O /usr/local/bin/yarn && chmod +x /usr/local/bin/yarn
RUN cd /app && yarn
CMD /bin/bash
```

in `yarn.lock`:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


bluebird@2.9.6:
  version "2.9.6"
  resolved bluebird-2.9.6.tgz#1fc3a6b1685267dc121b5ec89b32ce069d81ab7d

bluebird@^2.9.33:
  version "2.11.0"
  resolved bluebird-2.11.0.tgz#534b9033c022c9579c56ba3b3e5a5caafbb650e1

bluebird@^3.4.1:
  version "3.4.7"
  resolved bluebird-3.4.7.tgz#f72d760be09b7f76d08ed8fae98b289a8d05fab3
```

`package.json`:
```
{
  "name": "lckr-core-js",
  "description": "True Key's core in JavaScript",
  "private": true,
  "dependencies": {
    "babyparse": "0.4.2",
    "bluebird": "2.9.6"
  }
}
```

Run `docker build -t ohmy .`

and debug :)

**Comment by maxymapp** [comment]
For me it was a matter of adding the tarball dependency to the work directory in Dockerfile (if you're using Docker).
```
WORKDIR /app
RUN node -v
RUN yarn -v
COPY package.json xlsx-0.20.3.tgz yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-engines
```
That solved the error: 
`Tarball is not in network and can not be located in cache (["/app/xlsx-0.20.3.tgz","/usr/local/share/.cache/yarn/v6/npm-xlsx-0.20.3-992725af0bb69fa9733590fcb8ab4a57e10b929b/node_modules/xlsx/.yarn-tarball.tgz"])`

**Comment by camper2020** [comment]
> For me it was a matter of adding the tarball dependency to the work directory in Dockerfile (if you're using Docker).
> 
> ```
> WORKDIR /app
> RUN node -v
> RUN yarn -v
> COPY package.json xlsx-0.20.3.tgz yarn.lock ./
> RUN yarn install --frozen-lockfile --ignore-engines
> ```
> 
> That solved the error: `Tarball is not in network and can not be located in cache (["/app/xlsx-0.20.3.tgz","/usr/local/share/.cache/yarn/v6/npm-xlsx-0.20.3-992725af0bb69fa9733590fcb8ab4a57e10b929b/node_modules/xlsx/.yarn-tarball.tgz"])`

Thanks and this worked for me too when deploying to Porter. Posting here for future reference.
