### ISSUE TITLE
yarn workspaces no-hoists dependencies of submodules

### ISSUE THREAD

**Issue by Steffen911** [yarnpkg/yarn#5620]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**
If I add a package *dep1* to the nohoist of another package *lib1* and *dep1* also nohoists a third package *dep2* then *dep2* is also installed locally in *lib1* although *lib1* does not directly depend on it.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a sample project at https://github.com/Steffen911/hoist-test which illustrates this. The package *test1* no-hoists package *test2* which no-hoists *request*. After running `yarn` I get the following repo structure:
```
.
├── package.json
├── src
│   ├── test1
│   │   ├── index.js
│   │   ├── node_modules
│   │   │   ├── request // <- Not expected
│   │   │   │   └── ...
│   │   │   └── test2 -> ../../test2
│   │   └── package.json
│   └── test2
│       ├── index.js
│       ├── node_modules
│       │   └── request
│       │       └── ...
│       └── package.json
└── yarn.lock
```

**What is the expected behavior?**
I would expect that only the package *test2* is included in the node_modules of *test1*. Alternatively, I would like to have a way to exclude modules from hoisting in package *test1*, e.g.
```
"workspaces": {
    "nohoist": [
      "**/test2",
      "!request"
    ]
  }
```

**Please mention your node.js, yarn and operating system version.**
node v8.11.1
yarn 1.5.1
macOS 10.13.4

**Comment by rally25rs** [comment]
I don't think you are using nohoist correctly. The `nohoist` options is supposed to be at the workspace root along with the `workspace` setting. `test1` and `test2` should not have `workspace` in their package.json. Nested workspaces aren't supported.

You root package.json should contain:

```
```

**Comment by Steffen911** [comment]
So this is actually a bug, even if this is not the intended usage?

If I'm using workspaces wrong, could you give me a hint on how I would get to the following structure?
```
.
├── package.json
├── node_modules
│   ├── [other hoisted modules]
│   ├── ...
├── src
│   ├── test1
│   │   ├── index.js
│   │   ├── node_modules
│   │   │   └── test2 -> ../../test2
│   │   └── package.json
│   └── test2
│       ├── index.js
│       ├── node_modules
│       │   └── request
│       │       └── ...
│       └── package.json
└── yarn.lock
```
My goal would be that only *request* is hoisted in *test2* and there is only a simlink to *test2* in the node_modules of *test1*.

**Comment by connectdotz** [comment]
@Steffen911 you can get what you wanted by using the workspace-scoped nohoist pattern in the root package.json:
```
// root package.json
"workspaces": {
    "packages": ["src/*"],
    "nohoist": ["test2/request"]
  }
```
you won't need nohoist in test2, and your test1 nohoist can be further simplified: 
```
// test1 package.json
"workspaces": {
    "nohoist": ["test2"]
  }
```
@rally25rs by using `**/test2/**` nohoist pattern, you are telling yarn that you want **everything** under test2 (second globstar) to be local **whenever**(first globstar) they appear on the dependency tree. Instead, you should probably use:
```
 "nohoist": [
      "**/test2",
      "test2/**" // or "test2/request"
    ]
```
nohoist doesn't support negative pattern match right now. It also doesn't support the notion of explicit "current workspace", but neither is required to resolve this issue.

**Comment by Steffen911** [comment]
@connectdotz Thank you! I will try it out.
