### ISSUE TITLE
Figure out why current yarn versions are compiled for ES5

### ISSUE THREAD

**Issue by sth** [yarnpkg/yarn#5627]
Since version 1.4.0, the yarn packages published on npm have their code compiled to ES5, instead of targeting node >= 5, as versions 1.0.0 through 1.3.2 did (I haven't checked older versions). At least it looks like that, features like "class A extends B ..." are now replaced by polyfills/.... This can lead to [subtle bugs](#5451) if the polyfills don't perfectly emulate the real features.

This doesn't seem to be intentional [and the reasons are not clear][1]. A normal `yarn build` still produces the expected code for node >5. It should be investigated why the published packages look differently.

 [1]: https://github.com/yarnpkg/yarn/pull/5497#issuecomment-373358120

**Comment by sth** [comment]
Looks like I'm mistaken and it *is* intentional that the Node v4 builds are used:

https://github.com/yarnpkg/yarn/blob/ffe9a6427b740c322d86cb6a7a95a8625eb7e01e/scripts/build-dist.sh#L38-L40

Probably the contents of the node v4 builds changed, not which build gets published to npm.

**Comment by sth** [comment]
Probably the introduction of babel-preset-env in #4374 changed how the result of the "legacy" build looks like. Probably babel-preset-env compiles "class" constructs to ES5 while that didn't happen with the previous babel settings.

The remaining question is how the legacy build (which is what everyone installing yarn via npm uses) *should* look like.

**Comment by BYK** [comment]
@sth thanks for bringing this up! I think @kaylieEB can help with the change in legacy builds. That said we are going to drop Node 4 and Node 5 support in or at the end of April. I can go out on a limb and say we the next release will probably be the last release that is compatible with Node 4 so not sure if this is worth fixing.

**Comment by sth** [comment]
If support for those old node versions is on it's way out it's probably not worth it to change anything on the current build. It would risk to introduce new problems in those old versions, which would be unfortunate in the last versions still supported.

It's working well enough currently and can be improved once support for the old versions gets dropped.
