### ISSUE TITLE
 could not set 'core.repositoryformatversion' to '0'

### ISSUE THREAD

**Issue by isJudy** [yarnpkg/yarn#5633]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by rally25rs** [comment]
Please fill out the issue template if you want help.

**Comment by marcio-andree** [comment]
estava tendo esse mesmo problema , no meu caso  foi que quando clonei meu repositório dei o git init no desktop , comitei e dei push, depois movi a pasta do projeto para outro diretorio quando tentava iniciar a pasta novamente não conseguia , quando voltei a pasta para o desktop funcionou. o que eu recomendária é.  colocar a pasta no diretorio original comitar e depois clonar o projeto onde se quer trabalhar. espero ajudar abraços
