### ISSUE TITLE
how to change global folder?

### ISSUE THREAD

**Issue by JaouShingan** [yarnpkg/yarn#5637]
i want change 
 'c:\user\xx\AppData\Local\Yarn\Data\global' 
to
 'd:\global-folder'

i test 
yarn config set global-folder "d:\global-folder"
but 
when i test
yarn global dir 
the result is  'c:\user\xx\AppData\Local\Yarn\Data\global' 

yarn version is 1.5.1

**Comment by khalid-elabbadi** [comment]
I have the same problem. no body wants to use that global default path

**Comment by e-monson** [comment]
> [#5746](https://github.com/yarnpkg/yarn/issues/5746)
> 
> * Run yarn config set global-folder "d:\global-folder"
> * Open your .yarnrc file, find global-folder replace  with --global-folder
> * The .yarnrc file default path is %userprofile%

This doesn't actually work right now. I've tried everything I've found through Googling this issue, but there doesn't seem to be any way to change yarn's global directory. Is there actually some way to do it right now? Why is it not documented?
