### ISSUE TITLE
Not installing prettier on WIndows

### ISSUE THREAD

**Issue by CarlBateman** [yarnpkg/yarn#5639]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Not installing prettier on Windows

**If the current behavior is a bug, please provide the steps to reproduce.**

>yarn global add prettier
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "prettier@1.11.1" with binaries:
      - prettier
Done in 2.48s.

>prettier -v
'prettier' is not recognized as an internal or external command,
operable program or batch file.

**What is the expected behavior?**
Install prettier

**Please mention your node.js, yarn and operating system version.**
>node -v
v8.11.1
>yarn -v
1.5.1

Windows 10

**Comment by rally25rs** [comment]
Likely it is installed but the yarn global bin directory didn;t get added to your path. See #5353
