### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by willpmartin** [yarnpkg/yarn#5641]
getting the following errors in the Yarn log file 

[yarn-error.log](https://github.com/yarnpkg/yarn/files/1896995/yarn-error.log)

**Comment by rally25rs** [comment]
It looks like you are trying to run `yarn start`.

`start` is not a `yarn` command, so it will look in your `package.json` file for a script named "start", but your package.json file doesn't have a start script defined. Hence the error "Command "start" not found."
