### ISSUE TITLE
bug: Memory leak for fresh yarn install when using resolutions

### ISSUE THREAD

**Issue by hulkish** [yarnpkg/yarn#5648]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When no yarn.lock is already present - and you are using `resolutions` fields in your `package.json:
- Yarn seems to significantly slow down to a crawl.
- Very long call stacks
- Memory grows indefinitely until either:
  - install completes before memory runs out
  - out of memory crash

I recorded a quick heap allocation timeline and discovered:
- The source of the memory build up to primarily be a large number of closures being stored as part of the incomplete call stack of [the seed method in package-hoister](https://github.com/yarnpkg/yarn/blob/95b3dfed6e08a51777de41311ec21531f4c2f3ed/src/package-hoister.js#L121)

**If the current behavior is a bug, please provide the steps to reproduce.**
Just use lots of resolutions (50+) and regen your yarn.lock. Although, the memory leak is present regardless of number of resolutions.

**What is the expected behavior?**
Not an indefinite call stack.

**Please mention your node.js, yarn and operating system version.**
- macOS High Sierra
- `yarn@1.5.1`
- `node@8.11.1`

**Comment by rally25rs** [comment]
It's not an exact duplicate, but let's track this in #5628 since it deals with performance of the same function.

**Comment by hulkish** [comment]
@rally25rs you don't think the memory leak is not worthy of its own issue?

**Comment by johnculviner** [comment]
If your seeing this post from Google:

You likely have circular / incompatible dependencies. Try deleting your `yarn.lock` file and it might fix it.
