### ISSUE TITLE
Yarn doesn't detect changes to nohoist

### ISSUE THREAD

**Issue by rkistner** [yarnpkg/yarn#5659]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

After changing configuration in `workspaces.nohoist` (e.g. adding another module to the nohoist list) and running `yarn`, no changes are detected (outputs `success Already up-to-date.`), and the module is still hoisted. In some cases `yarn --check-files` fixes this, but often the only solution is to delete `node_modules` and start over.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Start with a workspace project, with all modules being hoisted.
2. Add a module to the `nohoist` list.
3. Run `yarn`.

**What is the expected behavior?**

Running `yarn` should always result in the same output, regardless of what the previous state was. Specifically, it should detect changes to the `nohoist` config and apply it.

**Please mention your node.js, yarn and operating system version.**

Yarn 1.5.1, Node 8.9.3, Ubuntu 16.04.

**Comment by jfirebaugh** [comment]
This unfortunately makes `yarn install` non-deterministic -- the result it produces depends on the history of past installs versus changes to `nohoist`.

**Comment by olee** [comment]
This is a really annoying bug because during project setups it regularly forces me to delete all node_modules directories in all packages the be sure that the install is correct :-/

**Comment by paul-soporan** [comment]
Closing as fixed in v2, where [`installConfig.hoistingLimits`](https://yarnpkg.com/configuration/manifest#installConfig.hoistingLimits) should be used instead (doesn't have this problem).

https://yarnpkg.com/configuration/manifest#installConfig.hoistingLimits
