### ISSUE TITLE
Bug: upgrade with pattern upgrades all packages

### ISSUE THREAD

**Issue by swrobel** [yarnpkg/yarn#5660]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn upgrade --pattern` seemingly ignores the pattern and upgrades all.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ yarn outdated
yarn outdated v1.5.1
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package                               Current Wanted Latest Package Type    URL                                                        
@fortawesome/fontawesome-free-brands  5.0.9   5.0.10 5.0.10 dependencies    https://fontawesome.com                                    
@fortawesome/fontawesome-free-regular 5.0.9   5.0.10 5.0.10 dependencies    https://fontawesome.com                                    
@fortawesome/fontawesome-free-solid   5.0.9   5.0.10 5.0.10 dependencies    https://fontawesome.com                                    
bootstrap                             4.0.0   4.1.0  4.1.0  dependencies    https://getbootstrap.com  

$ yarn upgrade --pattern fontawesome
...
info Direct dependencies
├─ @fortawesome/fontawesome-free-brands@5.0.10
├─ @fortawesome/fontawesome-free-regular@5.0.10
├─ @fortawesome/fontawesome-free-solid@5.0.10
├─ bootstrap@4.1.0
...

$ yarn outdated | grep bootstrap
<no output>
```

@philquinn, am I understanding this feature incorrectly? https://github.com/yarnpkg/yarn/pull/4610

**What is the expected behavior?**
`--pattern` should restrict upgraded packages to only those that match the pattern

**Please mention your node.js, yarn and operating system version.**
Node 9.11.1
yarn 1.5.1
macOS 10.13.4

**Comment by rally25rs** [comment]
The worst part is we even have a unit test for `--pattern`, but it was poorly written and passes when all packages upgrade 😞 

Thanks for reporting this. I'll try to track down when/why this broke.

**Comment by philquinn** [comment]
Hey @swrobel , I can reproduce this. It appears the part which filters on the pattern is unreachable unless a package is also passed. So doing `yarn upgrade some-package-name --pattern fontawesome` would get what you want I think. But thats a bug. It should work without the package just the same. I will try do a fix for this as soon as I can.

**Comment by rally25rs** [comment]
@philquinn I have a fix written and passing a unit test. I'm just trying to clean up some rather ugly looking conditionals code before I make a PR...

**Comment by philquinn** [comment]
Ah really sorry @rally25rs I started working on this straight away, didn't see you were also.
I also noticed the `is-negative-zero` issue, I chose `array-union` as an alternative as it was referenced in the same file. Along with the `left-pad` being just the wrong check, my bad.
I have a PR in with the fix. It would be great if you could review it.
