### ISSUE TITLE
Allow --dev to be specified in .yarnrc

### ISSUE THREAD

**Issue by atrauzzi** [yarnpkg/yarn#5671]
I have a front-end project that will only be used at development time, which got me to wondering if it would be helpful to switch the default add group to the `devDependencies` section rather than `dependencies`.  Tried setting `dev true` in `.yarnrc`, but it doesn't appear to have worked?

**Comment by rally25rs** [comment]
try `--*.dev true` since that is a flag not a setting. See: [.yarnrc docs : cli arguments](https://yarnpkg.com/lang/en/docs/yarnrc/#toc-cli-arguments)

**Comment by atrauzzi** [comment]
Worked!  Thank you for the tip, was not aware I could do this!
