### ISSUE TITLE
Yarn publish ignores the folder parameter

### ISSUE THREAD

**Issue by szymonbultrowicz** [yarnpkg/yarn#5678]
Yarn publish task always publishes the current directory, even if the `folder` parameter is given (see [docs](https://yarnpkg.com/lang/en/docs/cli/publish/#toc-yarn-publish-folder)).

I.e., Running
`yarn publish dist/lib --skip-git-tag --new-version 0.0.1-dev`
will publish the whole current directory instead of `dist/lib` only.

Workaround would be to run publish from the directory that is to be published, but according to the docs this functionality is supported and additionally, this is how npm currently works.

Looking in the source code, it seems that the `dir` param in the `pack` method is never used:
https://github.com/yarnpkg/yarn/blob/4acfe3902a010d1673c777757dc31355f2b4fd8b/src/cli/commands/pack.js#L135-L140

**Comment by pieniazek** [comment]
@rally25rs any updates? :)

**Comment by rally25rs** [comment]
Sorry, somehow I didn't notice this issue for the last few days. 😞 That certainly does seem like a bug.

**Comment by serkanyersen** [comment]
This problem is still happening on version `1.6.0`, it was working fine on `1.15.2`
