### ISSUE TITLE
yarn version --[major|minor|patch] option does not work, still prompts for version

### ISSUE THREAD

**Issue by Sylphony** [yarnpkg/yarn#5679]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using `yarn version --[major|minor|patch]`, a prompt still shows and asks you to manually bump the version, i.e. exactly like `yarn version` without the option.

**If the current behavior is a bug, please provide the steps to reproduce.**

See screenshot, using `--patch` as an example.
![version](https://user-images.githubusercontent.com/1796078/38828104-d3f51320-4169-11e8-89ae-d9940eb3bdb8.png)

**What is the expected behavior?**

It should bump to the correct version automatically.

Interestingly enough, `yarn version --new-version [major|minor|patch]` has the correct behavior.

**Please mention your node.js, yarn and operating system version.**

* OS: Windows 7
* yarn: v1.6.0
* node: v8.10.0

**Comment by rally25rs** [comment]
The PR to add this feature (#5670) was just merged yesterday. It isn't released yet.

Unfortunately the docs for the new feature got merged and updated on the site already. This is something we need to tackle in our release process 😞

**Comment by sondrele** [comment]
@rally25rs Heh, that explains why I've had some issues with this command. Do you know when the next version will be released?
