### ISSUE TITLE
run command does not set INIT_CWD environment variable

### ISSUE THREAD

**Issue by bradchoate** [yarnpkg/yarn#5698]
**Do you want to request a *feature* or report a *bug*?**

Feature parity request, but could be considered a bug too.

**What is the current behavior?**
The npm run command sets an environment variable-- `INIT_CWD` which is not set by yarn, and one of our dependencies appears to rely on this variable being assigned. This variable is [documented for npm here](https://docs.npmjs.com/cli/run-script#description).

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't have a repo, but if you add a "env" command to package.json and run it via "npm run env" and "yarn run env", you'll see that npm sets `INIT_CWD` where yarn does not.

**What is the expected behavior?**
`INIT_CWD` should be set to the current path in context of the 'run' command (this applies for any dependencies' scripts, such as postinstall scripts).

**Please mention your node.js, yarn and operating system version.**
node v8.10.0, macOS 10.13.4

**Comment by bradchoate** [comment]
I found the pull request that [implemented this for npm](https://github.com/npm/npm/pull/12356).

**Comment by generalov** [comment]
It seems that this is implemented in PR #5656.

**Comment by aprilandjan** [comment]
Yeah my yarn `v1.19.2` seems already support this

**Comment by dimkir** [comment]
@aprilandjan i just upgraded yarn from `v1.13.0` (`yarn -v`) via `npm -g upgrade yarn` and now I have `v1.19.2` and it supports `$INIT_CWD` eg.

```json
  "scripts": {
    "prestart": "echo Prestart in $INIT_CWD ...",
```

**Comment by paul-soporan** [comment]
Closing as this has been implemented.
