### ISSUE TITLE
Switch away from symlinks to npm style copying

### ISSUE THREAD

**Issue by sebmck** [yarnpkg/yarn#57]
Better ecosystem compatibility.

**Comment by HaleTom** [comment]
Is there any user-settable config option to use symlinks?

**Comment by pauldraper** [comment]
How to enable old behavior?

**Comment by pauldraper** [comment]
Looks like still unsolved. #2125

**Comment by arcanis** [comment]
Well yes it's solved since this issue was about **stopping** to use symlinks.

Now if what you want is a shared store of packages, [we did list last year too](https://yarnpkg.github.io/berry/features/pnp) 😉
