### ISSUE TITLE
Out of date yarn.lock not detected by --frozen-lockfile

### ISSUE THREAD

**Issue by edmorley** [yarnpkg/yarn#5701]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn install --frozen-lockfile` completes successfully with exit code zero, but yet when I run `yarn install`, there are changes made to `yarn.lock`, suggesting it wasn't up to date after all.

Specifically, after running `yarn install`, multiple wildcard sub-dependencies are removed (eg `debuglog "*"`), which correspond to `bundleDependencies` (aka `bundledDependencies`) in their parent packages. 

(These wildcard dependencies were added by the Renovate bot's lockfile refresh feature - I'm presuming they shouldn't be there and so filed renovateapp/renovate#1851; however this issue against yarn is to ensure our Travis run's use of `--frozen-lockfile` would catch this in CI next time.)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `git clone https://github.com/mozilla-neutrino/neutrino-dev.git`
2. `cd neutrino-dev && git checkout ee7b3d90fe93da0b6664b194da2994d4ce79f26e`
3. `yarn install --frozen-lockfile`
4. `yarn install`
5. `git status -s`

**What is the expected behavior?**
Either:
* At step 3, the command bails with an error saying the lockfile isn't up to date.
* or, at step 4-5 there are no modifications made to `yarn.lock` (if in fact the `bundleDependencies` are expected, or removing them is just a nice-to-have optimisation)

**Please mention your node.js, yarn and operating system version.**
* yarn 1.6.0 (also tried master)
* node 9.11.1
* Windows 10 x64 1709
(but this issue also affected our travis run, which is yarn 1.3.2, node 6/8/9, Ubuntu 14.04)

**Comment by BYK** [comment]
I think " or removing them is just a nice-to-have optimisation" is what is happening here which doesn't require a hard-error when using the frozen mode.

**Comment by BYK** [comment]
That said yarn doesn't have proper support for bundledDependencies anyway.

**Comment by joscha** [comment]
references https://github.com/yarnpkg/yarn/issues/5840

We found this issue because we are seeing the same thing:

Diffs showing up when using `yarn`, but not showing up when using `yarn --frozen-lockfile`. I understand the notion of "it doesn't matter that these dependencies are not there", but the diff showing up in the yarn.lock confuses developers, hence why we even want the check in the first place.

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration

**Comment by joscha** [comment]
@paul-soporan Is there a backport to v1?

**Comment by merceyz** [comment]
There isn't, no

**Comment by paul-soporan** [comment]
@merceyz is correct.

Also, the ping made me do a double take on this issue and now I've realized that it's about bundleDependencies which we've removed support for in v2: https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies

Essentially it's impossible for v2 to have any bugs with `--immutable` (formerly `--frozen-lockfile`), but bundleDependencies are also not supported.
