### ISSUE TITLE
500 Internal error on https://registry.yarnpkg.com/@angular-http-2.4.4.tgz when doing "yarn install"

### ISSUE THREAD

**Issue by abecede753** [yarnpkg/yarn#5706]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Can not build because external resource raises 500 error

**If the current behavior is a bug, please provide the steps to reproduce.**
yarn install
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular-http-2.4.4.tgz: Request failed \"500 Internal Server Error\"".

**What is the expected behavior?**
To work as it did some weeks ago.

**Please mention your node.js, yarn and operating system version.**
See attached yarn-error.log
[yarn-error.log](https://github.com/yarnpkg/yarn/files/1931988/yarn-error.log)

**Comment by tsuna** [comment]
We're regularly seeing 500 errors from https://registry.yarnpkg.com in our CI system as well.  There are various issues on GitHub already that got closed (#3353, #3494, #5828, #5901, #6338, etc).

**Comment by lfx** [comment]
Happens every day as @tsuna and others mentioned.

**Comment by fwouts** [comment]
I'm also seeing a lot of errors on CircleCI, such as:
```
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/es6-promisify/-/es6-promisify-5.0.0.tgz: Request failed \"500 Internal Server Error\"".
```

It looks like it could be rate-limiting, since this is a particularly large `package.json` (although I'd have expected a 429 error).

**Comment by tsuna** [comment]
Could it be that `npm` has some [retry logic](https://github.com/npm/npm-registry-client/blob/14efa6848ca1e7278de0eb12a1430cdb85bddf02/lib/request.js#L81) that yarn [does not have](https://github.com/yarnpkg/yarn/blob/c58bd58e029ab5a69d75742c6ae82aa96cef0140/src/resolvers/registries/npm-resolver.js#L42)?  (H/T @mtourne for digging this up in the code.)

I'm not very familiar with this code but it feels like `npm` retries on 408 and 5xx responses while yarn just attempts to access the JSON body directly.  That would explain why we and others are seeing frequently build failures since we switched to yarn.

**Comment by arcanis** [comment]
😞 

I think that makes sense, yeah. The easiest way to implement this is to add a try-catch-retry here, I think:

https://github.com/yarnpkg/yarn/blob/c58bd58e029ab5a69d75742c6ae82aa96cef0140/src/registries/npm-registry.js#L164-L174

Would someone be willing to open a PR?

**Comment by merceyz** [comment]
Closing as fixed in v2 where failed requests are automatically retried

https://yarnpkg.com/getting-started/migration
