### ISSUE TITLE
upgrade-interactive does not update resolutionDependecies

### ISSUE THREAD

**Issue by Pajn** [yarnpkg/yarn#5710]
**Do you want to request a *feature* or report a *bug*?**
bug, maybe a feature request but with the current behaviour it feels more like a bug

**What is the current behavior?**
upgrade-interactive lists and let you choose resolutionDependecies but does not update them if you do

**If the current behavior is a bug, please provide the steps to reproduce.**
Have a resolution dependency with a version that is behind latest, run `yarn upgrade-interactive --latest`, choose the dependency, notice that the old version is still listed in package.json

**What is the expected behavior?**
The version is upgraded to the latest version just as dependecies and devDependecies

**Please mention your node.js, yarn and operating system version.**
N/A

**Comment by rally25rs** [comment]
duplicate #5413
