### ISSUE TITLE
--silent / -s not working for `upgrade`

### ISSUE THREAD

**Issue by paleite** [yarnpkg/yarn#5721]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Outputs a lot of text in the terminal

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn upgrade --silent`

**What is the expected behavior?**
Skip Yarn console logs. Only other types of logs (script output) should be printed. This is the behavior that `yarn upgrade --help` says it should have.

**Please mention your node.js, yarn and operating system version.**
- Node: v9.11.1
- Yarn: 1.6.0
- macOS: 10.13.4

**Comment by rally25rs** [comment]
```
~/Projects/yarn-test 🐒   yarn upgrade
yarn upgrade v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ left-pad@1.0.1
info All dependencies
└─ left-pad@1.0.1
✨  Done in 0.29s.

~/Projects/yarn-test 🐒   yarn upgrade --silent
└─ left-pad@1.0.1
└─ left-pad@1.0.1
```

I think the tree logger is not respecting silent.

**Comment by rally25rs** [comment]
I believe [this function](https://github.com/yarnpkg/yarn/blob/master/src/reporters/console/console-reporter.js#L250) needs an `if (!this.isSilent)` check in it.

If no one else makes a PR for this soon, I'll try to circle back and handle it when I find some time.
