### ISSUE TITLE
Cannot force color output when stdout is not a tty

### ISSUE THREAD

**Issue by mqudsi** [yarnpkg/yarn#5733]
**Do you want to request a *feature* or report a *bug*?**

Feature Request

**What is the current behavior?**
There does not seem to be an option to force the output of color ansii terminal escape codes when the output of yarn is not a tty.

**If the current behavior is a bug, please provide the steps to reproduce.**

e.g.

```fish
~> yarn list
~> # a colored list of dependencies is printed
~> yarn list | less -R 
~> # all escape codes are stripped from the output
```

**What is the expected behavior?**

If an option `--color` with default value `auto" implying the current behavior (colors stripped when stdout is going to non-tty device), the presence of which can be implied to mean `--color force` so that the following would work:

```fish
~> yarn list --color | less -R
~> # a colored list of dependencies is emitted, and understood by `less` thanks to the `--raw/-R` flag
```

**Please mention your node.js, yarn and operating system version.**
yarn 1.6.0 under unix-like OS.

**Comment by rally25rs** [comment]
I think this is auto-detected by `chalk` currently, not controlled by yarn explicitly. It looks like it should be possible to add a `--color` config option to yarn and send that to `chalk` using the [.enabled](https://github.com/chalk/chalk#chalkenabled) setting on chalk.

PR's are welcome! 😸

**Comment by pjaehrling** [comment]
Hey @rally25rs, it seems to me that this is still in`to do`?
I have [a first draft/solution](https://github.com/yarnpkg/yarn/compare/master...pjaehrling:add-color-option-feature-5733). Could you have a look and let me know if I'm on the right track or what should be added/changed, before creating a PR. Thanks!

**Comment by baptistemarchand** [comment]
This works for me: `yarn install --color=always | cat` with yarn 1.9.4

**Comment by kitfit-dave** [comment]
@baptistemarchand  has the answer, it just needs to get into the help text :)

**Comment by SebiTimeWaster** [comment]
setting `export FORCE_COLOR=true` worked for me.

**Comment by mqudsi** [comment]
Yes, but this PR suggests `—color` on its own should enforce that.

**Comment by bradjones1** [comment]
I think this is successfully addressed by the chalk env var mentioned above; I think perhaps a PR to the docs is in order but doesn't appear to me this needs addressed in yarn per se.

**Comment by rightaway** [comment]
@Haroenv `FORCE_COLOR=true` doesn't work with `yarn info` and tried in yarn 1.22.10. Can this issue be reopened?

**Comment by basickarl** [comment]
Yea this isn't working:

```
karl@Karls-MBP ~/development/design (sync-fork-script !)  $ FORCE_COLOR=true yarn a --color=always
\x1b[1m\x1b[39mBold Text\x1b[0m --color=always
karl@Karls-MBP ~/development/design (sync-fork-script !)  $ npm run a

> root@ a /Users/karl/development/design
> echo "\x1b[1m\x1b[39mBold Text\x1b[0m"

Bold Text
```
Works with NPM but not Yarn. Running Yarn 3.2.0
