### ISSUE TITLE
Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by jjhesk** [yarnpkg/yarn#5750]
v 1.6.0
**What is the current behavior?**

(node:83527) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**If the current behavior is a bug, please provide the steps to reproduce.**

npm 5.6.0
node 9.7.0

**Comment by marvinhagemeister** [comment]
Duplicate of #5477
