### ISSUE TITLE
Buffer deprecation warning on Node 10

### ISSUE THREAD

**Issue by blackxored** [yarnpkg/yarn#5753]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

```
(node:90035) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Most commands, other than version. `yarn global bin` produces the least amount of output. 

**What is the expected behavior?**

No warnings.

**Please mention your node.js, yarn and operating system version.**
```
node -v && yarn -v
v10.0.0
1.6.0
```

**Comment by mathmarques** [comment]
Duplicated (#5731, #5477, #5704) and already fixed (waiting the next yarn release)

**Comment by BYK** [comment]
Closing in favor of #5477.

**Comment by slimlime** [comment]
Fixed in next releases? 😕 Confused because those other issues show older versions `1.5.1`, `1.6.0` and I am still getting this issue on yarn `1.7.0`

Example:
```bash
yarn global v1.7.0
(node:14840) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.al
loc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by rexkenley** [comment]
I have yarn 1.7.0 and nodejs 10.6 and am getting this warning.

(node:43696) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by normancarcamo** [comment]
Same issue here: Node: v10.8.0, Npm: 6.2.0
