### ISSUE TITLE
experimental-pack-script-packages-in-mirror fails to pack binary targets of sse4_crc32

### ISSUE THREAD

**Issue by lxe** [yarnpkg/yarn#5755]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Some prebuilt packages (sse4_crc32, for example) in offline mirror don't actually contain prebuilt binaries. I'm guessing yarn fails to package built binaries maybe due to the lack of lifecycle scripts or something else entirely. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Steps to reproduce:

1. Be `yarn 1.6.0+`
2. Make a `.yarnrc with`

```
yarn-offline-mirror "./npm-packages-offline-cache"
experimental-pack-script-packages-in-mirror true
```

3. `yarn add 'sse4_crc32@4.1.1'`
4. Observe that it's working:

```
❯ node -p "require('sse4_crc32')"
{ isHardwareCrcSupported: [Function: isHardwareCrcSupported],
  calculateInSoftware: [Function: swCrc32c],
  calculateOnHardware: [Function: hwCrc32c],
  CRC32: [Function: Crc32C],
  calculate: [Function: hwCrc32c] }
```

5. Observe the prebuilt tarball:

```
❯ ls -l npm-packages-offline-cache/prebuilt/
total 24
-rw-r--r--  1 aleksey  staff  9059 Apr 29 18:44 sse4_crc32-v4.1.1-darwin-x64-57.tgz
```
6. Observe that `sse4_crc32-v4.1.1-darwin-x64-57.tgz` does *NOT* contain the build target:

```
tar -xf sse4_crc32-v4.1.1-darwin-x64-57.tgz && find package -name '*.node'
```

6.  `rm -rf node_modules && yarn --offline`
7.  ` node -p "require('sse4_crc32')"` now fails:

```
Error: Could not locate the bindings file. Tried:
```

**What is the expected behavior?**

The `.node` files should be packed and then unpacked in the prebuilt tarballs.

**Please mention your node.js, yarn and operating system version.**

Node 8.11.1
Darwin
Yarn Master

**Comment by lxe** [comment]
cc @bestander

**Comment by bestander** [comment]
I think I understand what the problem is about.
sse4_crc32's package.json does not have "scripts.install" section.
Yarn implies that it needs to run one `node-gyp rebuild` if the package has `binding.gyp` file.

So this could be fixed if the package has explicit
```
"scripts": {"install": "node-gyp rebuild"}
```
in package.json.

But Yarn should treat this implicit install script too, so the bug is legit.

**Comment by bestander** [comment]
If anyone wants to send a PR with a fix be my guest, currently I am not sure I'll have a moment to do the fix
