### ISSUE TITLE
Installation Problem: [error al procesar el archivo /var/cache/apt/archives/yarn_1.6.0-1_all.deb (--unpack)]

### ISSUE THREAD

**Issue by kamalyzl** [yarnpkg/yarn#5765]
Preparando para desempaquetar .../archives/yarn_1.6.0-1_all.deb ...
Desempaquetando yarn (1.6.0-1) ...
dpkg: error al procesar el archivo /var/cache/apt/archives/yarn_1.6.0-1_all.deb (--unpack):
 intentando sobreescribir `/usr/bin/yarn', que está también en el paquete cmdtest 0.22-1
Se encontraron errores al procesar:
 /var/cache/apt/archives/yarn_1.6.0-1_all.deb

No me permite instalar el paquete, no lo reconoce y no sé porque

**Comment by Daniel15** [comment]
Uninstall cmdtest:
```
sudo apt-get remove cmdtest
```

Then installing Yarn should work.

It fails because Yarn and cmdtest both contain a command called "yarn" :)
