### ISSUE TITLE
CLI switch "--scripts-prepend-node-path" doesn't work

### ISSUE THREAD

**Issue by jakedevine** [yarnpkg/yarn#5776]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using the ```--scripts-prepend-node-path``` switch seems not to do anything.

```
$ /myNodePath/bin/node myYarnPath/bin/yarn.js run --scripts-prepend-node-path env
```
Running this outputs an "env" without ```myNodePath``` in the "PATH".

```
{
  "NODE": "/myNodePath/bin/node",
  ...
  "PATH": "/myProject/node_modules/.bin:/Users/jdevine/.config/yarn/link/node_modules/.bin:/myProject/node_modules/.bin:/myProject/node_modules/.bin:/Users/jdevine/.config/yarn/link/node_modules/.bin:/myProject/node_modules/.bin:/myNodePath/libexec/lib/node_modules/npm/bin/node-gyp-bin:/myNodePath/lib/node_modules/npm/bin/node-gyp-bin:/myNodePath/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/Users/jdevine/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
  ...
```

We would expect that the node path (```/myNodePath/bin```) be the first thing in the PATH in the env.  In fact, if I comment out the config check in yarn:
```
//    if (config.scriptsPrependNodePath) {
      pathParts.unshift(path.join(path.dirname(process.execPath)));
//    }
```

If I make that change, then see what I expect - the path includes ```/myNodePath/bin```, and my install scripts, and "yarn run" scripts work as expected.

```
{
  "NODE": "/myNodePath/bin/node",
  ...
  "PATH": "/myNodePath/bin/:/myProject/node_modules/.bin:/Users/jdevine/.config/yarn/link/node_modules/.bin:/myProject/node_modules/.bin:/myProject/node_modules/.bin:/Users/jdevine/.config/yarn/link/node_modules/.bin:/myProject/node_modules/.bin:/myNodePath/libexec/lib/node_modules/npm/bin/node-gyp-bin:/myNodePath/lib/node_modules/npm/bin/node-gyp-bin:/myNodePath/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/Users/jdevine/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
  ...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
This reproduces every time.

**What is the expected behavior?**
As above.  We expect that using --scripts-prepend-node-path should prepend the node path to the PATH in the environment when scripts are executed at install time and run time.

**Please mention your node.js, yarn and operating system version.**
node v8.10.0
yarn v1.6.0

**Comment by rally25rs** [comment]
Is `--scripts-prepend-node-path` actually a yarn flag? I can't seem to find any documentation or reference for it. Maybe this is a feature request to add a flag that npm has?

**Comment by jakedevine** [comment]
Yeah - this probably comes from npm.  I'm new to yarn, but it *is* in the code...

https://github.com/yarnpkg/yarn/blob/a35a4f97dd7e5f6f029b5e0f855bfd73ef338ca4/src/cli/index.js#L99-L103

**Comment by rally25rs** [comment]
oops! yes it is. Text search failed me when I tried to find it in the code. My fault.

It's implemented too:

https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js#L177-L179

**Comment by antrancs** [comment]
I would love to take this one 😊

**Comment by michaelsbradleyjr** [comment]
There appears to have been a regression.

See:  https://github.com/yarnpkg/yarn/blob/a35a4f97dd7e5f6f029b5e0f855bfd73ef338ca4/src/util/execute-lifecycle-script.js#L177

As of `1.11.0` and later versions, that logic is not applied.

**Comment by ntindle** [comment]
is this just the default behavior of yarn?

**Comment by douglascayers** [comment]
The flag existed prior to yarn 1.15, per the [changelog](https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md#1150) it was removed as this is now the default behavior (as @ntindle said)
