### ISSUE TITLE
Yarn not installing packages from cache when offline

### ISSUE THREAD

**Issue by ihack2712** [yarnpkg/yarn#5778]
**What is the current behavior?**
Yarn doesn't cache stuff at all.

**Fix** Cache it? I guess?

**What is the expected behavior?**
Allowing to do installs without internet access if the module has been installed before.

**Please mention your node.js, yarn and operating system version.**
Node v9.8.0
Yarn 1.6.0
Mac OS X High Sierra 10.13.3

**Comment by ihack2712** [comment]
Sorry, to be more clear. Yarn does cache modules, but whenever trying to add modules that are cached it says it can't connect to the internet and doesn't install it.

**Comment by rally25rs** [comment]
Did you try the `--offline` flag? Does `yarn cache list` show anything for the package you are adding?

**Comment by ihack2712** [comment]
@rally25rs Thank you, that did work, and I did already check `yarn cache list`. It does list all of the modules that are cached. Installing modules with the --offline flag did work. Thanks 👍
