### ISSUE TITLE
Make `yarn why` more accurate.

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/yarn#578]
It isn't entirely accurate yet as mentioned in https://github.com/yarnpkg/yarn/pull/544. I was a bit in a rush when I built this ;) 

Repro:
* Create a new project and `yarn add jest`.
* `du -sh node_modules` is ~42mb
* `yarn why jest` shows only 20mb
* `ls node_modules | wc -l` has a different amount of dependencies.

One issue is that the current implementation is counting the raw packages from the cache instead of the real packages in `node_modules`.

Hoping that somebody from the community can help us out on this ;)

**Comment by sendilkumarn** [comment]
du -sh will show you ` size on disk` and what ever `fs` gives will show `actual file size` both will be different. 

For example in `mac` --> actual file size will be `22.9MB` But size on disk  will be `43Mb`

<img width="224" alt="screen shot 2016-10-12 at 6 52 42 pm" src="https://cloud.githubusercontent.com/assets/12471122/19307454/163cd1ec-90ad-11e6-9210-5111552ce13a.png">

So I hope for size this should be okay.

**Comment by cpojer** [comment]
Ah, this is good to know. I thought my accounting wasn't right. Is there a way to get the size on disk in node? I think that will be more accurate. I tried to use the blocks/blocksize fields but that wasn't helpful.

**Comment by sendilkumarn** [comment]
I will give it a try. But if we really need to show the stat, I guess we can use commands itself straight away.

**Comment by cpojer** [comment]
I'd prefer to use node's API because we'd like to support windows as much as possible.

**Comment by sendilkumarn** [comment]
> ls node_modules | wc -l 

the above command will list all the folders inside node_modules. But as per `shared dependencies`
it iterates only through the packages which is not in transitivekeys and also has some dependencies attached to it. 

if the goal is to find out total number of packages, then we have to change the logic
