### ISSUE TITLE
Usage: yarn [options]  yarn: error: no such option: --dev

### ISSUE THREAD

**Issue by agrawalsam** [yarnpkg/yarn#5780]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
srix@srix-Dell-System:~$ yarn add -D webpack
Usage: yarn [options]

yarn: error: no such option: -D
srix@srix-Dell-System:~$ yarn add --dev webpack 
Usage: yarn [options]

yarn: error: no such option: --dev

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It was supposed to be faster than npm. 

**Please mention your node.js, yarn and operating system version.**
nodejs --version: v4.2.6
yarn --version:  0.22
node --version: v10.0.0
linux-ubuntu:  16.04

**Comment by agrawalsam** [comment]
Applying sudo before the command in the terminal also doesn't work.

**Comment by danbes1** [comment]
For me help:
`sudo npm i -g yarn`

**Comment by abedds** [comment]
add sudo before. works for me "sudo yarn add --dev babel-plugin-module-resolver"

**Comment by merceyz** [comment]
Closing as this is over three years old and `yarn add -D ...` works in the latest releases
