### ISSUE TITLE
 An unexpected error occurred: "https://registry.yarnpkg.com/istanbul-lib-trackerrt/-/istanbul-lib-trackerrt-1.1.0.tgz: Request failed \"404 Not Found\""

### ISSUE THREAD

**Issue by snehasi** [yarnpkg/yarn#5791]
**Which operating system are you using:**
Ubuntu 16.04

**Please describe the steps you took when trying to install Yarn and what went wrong:**
First, configured the repo using:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
```
Configured the node source repo with:
`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`

Installed node.js 8.11.1 and native build tools:
```
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```
`sudo apt-get update && sudo apt-get install yarn`

But doing` yarn install` gives the following error:
```
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/istanbul-lib-trackerrt/-/istanbul-lib-trackerrt-1.1.0.tgz: Request failed \"404 Not Found\"".
```
yarn --version==1.6.0
Any help in solving this error would be much appreciated.
Thanks

**Comment by snehasi** [comment]
I'm closing this issue as it seems to be repo specific.

**Comment by Daniel15** [comment]
I don't see any package called `istanbul-lib-trackerrt`: https://yarn.pm/istanbul-lib-trackerrt

**Comment by GeorgLink** [comment]
Hi @snehasi,

How did you solve this? 
I ran into the same issue today (I assume the same repo as you 🥇 ) and found your issue here.

yarn v1.12.3

**Comment by snehasi** [comment]
Hi @GeorgLink,

Yes, the issue was because of incorrect url from the replacement of repo with tracker in the url.
I solved it here:
https://github.com/bugmark/exchange/pull/73/commits/74e174616e93e723e8c599c4b74e1b721b40a9ec

**Comment by GeorgLink** [comment]
arg! Thanks! @snehasi
