### ISSUE TITLE
pgp key for the msi

### ISSUE THREAD

**Issue by LaurentGoderre** [yarnpkg/yarn#5799]
I am getting a certificate key for the MSI that isn't in any of the keyserver we typically use for the docker image and I was wondering where it was coming from.

**Comment by Daniel15** [comment]
We don't currently PGP sign the MSI file. Do you mean the Authenticode signature that's embedded inside it? We switched to a new certificate in October 2017.

Thumbprint = af764e1ea56c762617bdc757c8b0f3780a0cf5f9

![](https://d.sb/2018/05/explorer_09-12.53.13.png)

**Comment by LaurentGoderre** [comment]
Can that signature be added to the keyservers or is it a totally different technology (sorry for my ignorance)
