### ISSUE TITLE
@yarnpkg/lockfile release 1.0.1

### ISSUE THREAD

**Issue by the-spyke** [yarnpkg/yarn#5803]
Please release `1.0.1` for `@yarnpkg/lockfile` with fixed #5719.

**Comment by arcanis** [comment]
Just been released! 🙂

**Comment by the-spyke** [comment]
@arcanis Just checked and I still see a shebang :-(

**Comment by arcanis** [comment]
Hmm cc @Daniel15, is there a special process to release the lockfile package?

**Comment by Daniel15** [comment]
@arcanis I think we just manually publish it, since it changes so infrequently?

**Comment by the-spyke** [comment]
Any news? I think you need:

1. Bump `package.json` version to `1.0.1`.
2. `npm run build-bundle`
3. `cd packages/lockfile && npm publish`

**Comment by the-spyke** [comment]
@arcanis @Daniel15 It's almost a month I'm trying to fix this super small issue. Is there anything I can do to speed up the process?

**Comment by arcanis** [comment]
@the-spyke Releasing this package isn't completely automated, sorry for the delay. Just released the 1.0.2, and double checked that the header has disappeared 😃
