### ISSUE TITLE
Missing dependencies in create-react-app

### ISSUE THREAD

**Issue by OshotOkill** [yarnpkg/yarn#5807]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

After I use `create-react-app` to set up a project and `eject` from it, run `yarn start` again will pump out the issue like below:

```
yarn run v1.6.0
$ node scripts/start.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'babel-loader'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.resolve (internal/modules/cjs/helpers.js:18:19)
    at Object.<anonymous> (/Users/norn/Desktop/my-app-9/config/webpack.config.dev.js:145:29)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/norn/Desktop/my-app-9/scripts/start.js:31:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://user-images.githubusercontent.com/6079112/39915080-8e70b3de-5539-11e8-9a2b-0b9acdbd4d01.png)

<br />

I dug into the `node_modules` directory and found out `babel-loader` was missing. However it happens when your yarn version is higher than v1.0.0, which means `babel-loader` can be installed when your yarn version is equal or prior to v0.28.4.

**If the current behavior is a bug, please provide the steps to reproduce.**

* `npx create-react-app my-app && cd my-app`
* `yarn run eject`
* `yarn start`

**What is the expected behavior?**

Application should be set up properly.

**Please mention your node.js, yarn and operating system version.**

Node: `v10.1.0`
Yarn: `v1.6.0`
OS: `Mac OS X 10.13.4`

**Reference**

[create-react-app #4433](https://github.com/facebook/create-react-app/issues/4433)

**Comment by rally25rs** [comment]
`eject` modifies `package.json` and adds `babel-loader`, so you need to rerun `yarn install`.

```
~/Projects/tst 🐒   cat package.json
{
  "name": "tst",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
~/Projects/tst 🐒   yarn run eject
yarn run v1.6.0
$ react-scripts eject
? Are you sure you want to eject? This action is permanent. Yes
Ejecting...

~/Projects/tst 🐒   cat package.json
{
  "name": "tst",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.3.2",
    "react-dev-utils": "^5.0.1",
    "react-dom": "^16.3.2",
    "resolve": "1.6.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "mjs"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```

I guess the `eject` command doesn't do that automatically for you, but that is a shortcoming of their script, not yarn.

**Comment by OshotOkill** [comment]
The problem is `babel-loader` can be installed before `yarn` v1.0.0 and **`npm`**

Besides, yarn could handle `babel-loader` properly before last month. I assume there would be some dependency changes in `babel` plugins and yarn has some issue to deal with it after v1.x

**Comment by rally25rs** [comment]
It probably used to be hoisted and no longer is.

It looks like in v1.6.0 `babel-loader` stays in:
> ./node_modules/react-scripts/node_modules/babel-loader
instead of being hoisted to 
> ./node_modules/babel-loader

but I'm not sure why. there could be a bug in the hoisting that prevents it from moving.

Hoisted package locations can change from version to version of yarn, and should not be relied upon. If it used to work before as a result of hoisting then that is coincidence and not behavior that should be relied upon. Once `package.json` is modified, `yarn install` should really be re-run.

**Comment by OshotOkill** [comment]
I actually don't know how do `create-react-app` hoists their package, however it seems `babel-loader` stays in `yarn.lock` and it can't be found in `node_modules`.

<img width="1438" alt="machi 2018-05-15 11-18-13" src="https://user-images.githubusercontent.com/6079112/40035058-61cdeff8-5832-11e8-9450-505b7766672e.png">

I thought yarn would check out `yarn.lock` and install the missing package after re-install. However after doing that (`yarn install`) it proves me wrong -- Run `yarn install` again without eject it still ignores the `babel-loader` in `yarn.lock`.

Anyway thanks, I'll point out this problem to `create-react-app` repository again.
