### ISSUE TITLE
Question: how do Git dependencies get resolved?

### ISSUE THREAD

**Issue by njlr** [yarnpkg/yarn#5818]
**Do you want to request a *feature* or report a *bug*?**

_Question_

(I posted [this question on StackOverflow](https://stackoverflow.com/questions/49305091/how-does-yarn-resolve-git-dependencies), but I think that it might be better served here. )

Yarn (and NPM) allow you to specify Git dependencies like this: 

    yarn add <git remote url>

or 

    yarn add <git remote url>#<branch/commit/tag>

(Taken from [the docs][1])

This is easy to understand in simple cases, where you have one Git dependency and there are no transitive dependencies, but it is not always clear how this works with more complex dependency graphs. 

***Example 1***

`package.json`

    ... 
    "dependencies": {
      "package-b1": "git@github.com:user/package-b.git"`, 
      "package-b2": "git@github.com:user/package-b.git"`
    }
    
Will Yarn spot that `package-b1` and `package-b2` have the same Git URL? Will they always resolve to the same commit-hash?

***Example 2***

`package.json`

    ... 
    "dependencies": {
      "package-b": "git@github.com:user/package-b.git"`, 
      "package-c": "git@github.com:user/package-c.git"`
    }

`github.com/user/package-b/package.json`

    ... 
    "dependencies": {
      "package-c": "git@github.com:user/package-c.git"`
    }

Will Yarn spot that our package and `package-b` both depend on the same Git URL? Will they be resolved to the same hash?

***Example 3***

`package.json`

    ... 
    "dependencies": {
      "package-b": "git@github.com:user/package-b.git"`, 
      "package-c1": "git@github.com:user/package-c.git"`
    }

`github.com/user/package-b/package.json`

    ... 
    "dependencies": {
      "package-c2": "git@github.com:user/package-c.git"`
    }

This example is the same, but `git@github.com:user/package-c.git` has two different names. Are they considered different dependencies? 

***Example 4***

`package.json`

    ... 
    "dependencies": {
      "package-b": "git@github.com:user/package-b.git"`, 
      "package-c": "git@github.com:user/package-c.git"`
    }

`github.com/user/package-b/package.json`

    ... 
    "dependencies": {
      "package-c": "git@github.com:user/package-c-2.git"`
    }

This example is also similar, but now there are two packages with the same name but different URLs. What will Yarn do here? 

***Summary***

I'm sure I could think of more examples. Can someone shed some light on how this stuff is meant to work? 

Things get *even more complicated* when you realise that each commit-hash might have a different `package.json`. Will Yarn try different commits if some contain dependency conflicts?

  [1]: https://yarnpkg.com/lang/en/docs/cli/add/

**What is the current behavior?**

Unknown

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

N/A

**Please mention your node.js, yarn and operating system version.**

Node.js 9.11.1
yarn 1.6.0
macOS 10.13.4

**Comment by rally25rs** [comment]
yarn uses the `git` command line tools to pull the repo and run a `git archive` in it to get the files.

**Example1**

It will use whatever git URL is specified, so it will make a request for each package. It should resolve to the current sha commit hash for `master` at the time of install. The sha hash will be written to `yarn.lock`, so future installs will keep pulling the same commit to provide a deterministic install.

**Example2**

since the dependency strings are the same, they will resolve to the same dependency (be de-duped).

**Example3**

Good question. I'm not really sure what happens in that case. I keep the dep name the same as the package name, so never tried that case.

**Example4**

I believe this would act like any other package withe the same name and different version, and create a structure of:

```
node_modules
  |- package-b
  |   +- package-c (from user/package-c-2.git)
  +- package-c (from user/package-c.git)
```

**Comment by rally25rs** [comment]
Going to mark this issue closed in hopes that I answered your questions.

**Comment by BYK** [comment]
May be we can use some of these in an FAQ?

**Comment by njlr** [comment]
Yes, I think these should make their way into the FAQ. Git(Hub) dependencies can be very important when working on private projects when you do not want to trust NPM to host your code.
