### ISSUE TITLE
Running `yarn init` doesn't save `package.json

### ISSUE THREAD

**Issue by JamesVanWaza** [yarnpkg/yarn#5820]
**REPORTING A BUG**

**What is the current behavior?**
Running `yarn init` doesn't save `package.json

**If the current behavior is a bug, please provide the steps to reproduce.**

I am migrating from `npm` so I started using `yarn`.
`Yarn` is currently installed

**What is the expected behavior?**
The `package.json` should be saved to the project and the packages should be added and saved every time I ran `yarn upgrade` 

**Please mention your node.js, yarn and operating system version.**
*Node* : 8.11.1 
*OS*: MacOS High Sierra 
*Version*: 10.13.4
*Yarn*: 1.6.0

**Comment by jgacuca567** [comment]
@rally25rs 
See screenshot attached. The directory is not empty. 
<img width="1283" alt="screen shot 2018-05-15 at 9 40 52 pm" src="https://user-images.githubusercontent.com/4000076/40091979-c92d1790-5888-11e8-96fa-16d04c86c55b.png">

**Comment by rally25rs** [comment]
was there a `package.json` there before running `yarn init`? Is there one after running the command? If so, what was the before/after of the file?

**Comment by jgacuca567** [comment]
There was one, but I deleted it after noting that it does not update the dependencies. The one I created before was created when I used npm.

**Comment by JamesVanWaza** [comment]
Solution - 
Make sure package-lock.json is deleted. 
Then run `yarn outdated`
`yarn upgrade` - **package.json** should update automatically.
