### ISSUE TITLE
Bug: Yarn install in workspace root reporting false-negative unmet peer dependency warnings

### ISSUE THREAD

**Issue by hulkish** [yarnpkg/yarn#5831]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Consider if you have:

1. `~/repos/foo-app`:
```json
{
  "private": true,
  "name": "@foo/app",
  "version": "1.0.0",
  "dependencies": {
    "@foo/bar": "1.0.0",
    "@foo/baz": "1.5.3",
    "@foo/widget": "2.0.0"
  }
}
```

2. `~/repos/foo-monorepo`:
```json
{
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "devDependencies": {
    "@foo/widget": "2.0.0"
  }
}
```

With 2 packages:
```json
{
  "name": "@foo/bar",
  "version": "1.0.0"
}
```
```json
{
  "name": "@foo/baz",
  "version": "1.5.3"
}
```

3. `~/repos/foo-widget`:
```json
{
  "name": "@foo/widget",
  "version": "2.0.0",
  "peerDependencies": {
    "@foo/bar": ">=0.5.4",
    "@foo/baz": ">=-0.6.2"
  }
}
```

Then, you run:
```bash
$ cd ~/repos/foo-modules
$ rm -rf node_modules packages/*/node_modules yarn.lock
$ yarn
```

Yarn will report these warnings:
```bash
warning " > @foo/widget@2.0.0" has unmet peer dependency "@foo/bar@>=0.5.4".
warning " > @foo/widget@2.0.0" has unmet peer dependency "@foo/baz@>=0.6.2".
```

After verifying everything is symlinked properly...you realize these warnings are **false-negatives**.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above

**What is the expected behavior?**

There should be no warnings per this use case.

**Please mention your node.js, yarn and operating system version.**
```bash
$ yarn versions v1.6.0
{ yarn: '1.6.0',
  http_parser: '2.8.0',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
✨  Done in 0.04s.
```

**Comment by hulkish** [comment]
If i could just get some direction on where to look for this... I'd like to submit a fix for it.

**Comment by rally25rs** [comment]
duplicate #5810 

The code for resolving these is a bit weird and hard to read, but it's in `package-linker.js` in a function named `resolvePeerModules()`

I think the way workspaces works is that it makes a "fake package" that has a dependency on all your workspace projects (named `workspace-aggragtor-...`) and I don't think the logic for resolving peerDeps properly takes the existence of that fake package into account.

(closing this issue as a duplicate, but we can continue the conversation in #5810 )
