### ISSUE TITLE
Extraneous escapes in backslashes in paths on Windows

### ISSUE THREAD

**Issue by mqudsi** [yarnpkg/yarn#5837]
**What is the current behavior?**

Messages emitted by yarn contain an extra `\` in paths, such as the following:

> C:\Users\Mahmoud>yarn
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error An unexpected error occurred: "UNKNOWN: unknown error, lstat 'C:\\Users\\Mahmoud\
ode_modules\\opentype'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Mahmoud\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**If the current behavior is a bug, please provide the steps to reproduce.**
Perform an action that reports an error involving a path.

**What is the expected behavior?**
Paths should be displayed as `C:\Foo\Bar` and not `C:\\Foo\\Bar`

**Please mention your node.js, yarn and operating system version.**
node v9.2.0, yarn 1.6.0, Windows 10 17134.48

**Comment by rally25rs** [comment]
duplicate #5517
Should be fixed in the next release (merged 8 days ago)

**Comment by mqudsi** [comment]
Awesome, thanks.

**Comment by sth** [comment]
@rally25rs I don't think this is fixed. The other pull request only seems to have handled the `\n` case. The backslashes in Windows paths are still escaped (therefore duplicated).
