### ISSUE TITLE
yarn install should generate an empty yarn lock even if there are no dependencies

### ISSUE THREAD

**Issue by jimmyhchan** [yarnpkg/yarn#5839]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
For a project with no dependencies, running `yarn` aka `yarn install` will not create a yarn.lock. Instead the message `info Lockfile not saved, no dependencies.` will be given.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn init
yarn
# info Lockfile not saved, no dependencies.

ls yarn.lock
# ls: yarn.lock: No such file or directory
```

**What is the expected behavior?**
For a `package.json` with no dependencies an "empty" yarn.lock should be generated if:
* `yarn` (it does not -- this bug)
* `yarn install` (it does not -- this bug)
* `yarn import`  (it does already!)

NO yarn.lock and no errors if:
* `yarn -v` (should not regress #3329)
* `yarn check` (should not regress #679)

**Please mention your node.js, yarn and operating system version.**
node 6.9.1
yarn 1.6.0
Mac OS 10.13.4

**Extra Info**
* See #679 #1703  where a yarn lock WAS produced from empty dependencies to allow yarn check to run without error
* See https://github.com/yarnpkg/yarn/pull/3395/files where the logic was added and the test was flipped. 
* see https://github.com/yarnpkg/yarn/issues/3329 where yarn -v had previously triggered install which may generate a lock.  Today (1.6.0) yarn -v will not trigger install.

**Comment by rally25rs** [comment]
Since there is actually a message "Lockfile not saved, no dependencies." this seems like it was the intended behavior by whoever wrote it, but I agree that an empty lockfile seems like a good idea. I'll flag this as a feature request.

**Comment by b-hayes** [comment]
I just got here because yarn install creating a lock file when there is no package json or anythign to install.
It was being run in the wrong folder on a gihub action and instead of failing it creates a lock file and the rest of the workflow continues to run.

This is "fixed" behavour is a bug. Creating a lock file when there is in fact a package.json makes sense but if there is nothing at all it should probably just fail with an error mesage.
