### ISSUE TITLE
Yarn pack output is not parsable

### ISSUE THREAD

**Issue by SteveReiter** [yarnpkg/yarn#5853]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
$ yarn pack
yarn pack v1.3.2
success Wrote tarball to "/Users/cadmus/code/my-util-v2.2.2.tgz".
✨  Done in 0.13s.
```

As far as I can tell, the purpose of pack is to create a tarball that can then be uploaded to npm or another package management library like gemfury.

In order to upload the package to gemfury my script needs to know the name of the file that is created by yarn pack. I am using a shell script to run yarn pack and then a curl command to upload the package.

With npm, it returns the filename:
 ```
$ npm pack
my-util-v2.2.2.tgz
```

With npm, I can simply call `npm pack` which returns the file name, like so `FILENAME=$(npm pack)`

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn pack`, note the output. Run `npm pack` compare the output.

**What is the expected behavior?**
yarn pack should return the filename or if it is going to deviate from the npm api, it should at least have an option to return the filename. Currently the only option on pack is --filename which forces a specific filename. This does not solve the problem because I then have to parse the package.json file to find the version number and construct the correct filename.

**Please mention your node.js, yarn and operating system version.**
yarn 1.6.0, node 8

**Comment by paul-soporan** [comment]
> This does not solve the problem because I then have to parse the package.json file to find the version number and construct the correct filename.

No idea if it was different in the past (when you opened this issue), but currently it uses the filename you provide, you don't have to construct anything.

v2 works the same way, but it also has a `--json` option that allows you to parse the output more easily.

https://yarnpkg.com/getting-started/migration
