### ISSUE TITLE
Harmonize the command line options

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#5870]
We should try to harmonize the command line options to make sure that we are consistent everywhere. A first step is to identify all the commands we have, and all the options they support.

An example in mind is the `--pattern` option, which sometimes is an option like for `yarn list`, sometimes a `-P,--pattern` option like for `yarn upgrade`, sometimes a `--scope` option that only takes the scope like for `yarn upgrade-interactive`, and sometimes an argument that doesn't glob like for `yarn outdated`.

**Comment by dsifford** [comment]
As I've mentioned in #6386, I'm interested in helping out with this one.

I think a decent starting point before even beginning to talk about modifying command _function_ is to first make sure just the cli usage and help docs are uniform between (and relevant to) all commands.

Probably the first and most obvious starting point for me on this would be to clean up the output of `yarn help` without any arguments. Specifically, it appears that a large majority of the flags that are documented at this first-level position are **only** relevant to either `yarn` a la carte or `yarn install`. 

I think it would make the most sense to move the flags that only matter in `yarn install` to the yarn install output exclusively and then in the main `yarn help` output just note that running yarn without arguments defaults to the install command. That way, it is abundantly clear which arguments are and aren't useful globally.

Here is a list of the current (`v1.10.0`) flags that are listed at the top-level:

```
*-v, --version                       output the version number
*--no-default-rc                     prevent Yarn from automatically detecting yarnrc and npmrc files
*--use-yarnrc <path>                 specifies a yarnrc file that Yarn should use (.yarnrc only, not .npmrc) (default: )
*--verbose                           output verbose messages on internal operations
--offline                           trigger an error if any required dependencies are not available in local cache
--prefer-offline                    use network only if dependencies are not available in local cache
--strict-semver                     
*--json                              format Yarn log messages as lines of JSON (see jsonlines.org)
--ignore-scripts                    don't run lifecycle scripts
--har                               save HAR output of network traffic
--ignore-platform                   ignore platform checks
--ignore-engines                    ignore engines check
--ignore-optional                   ignore optional dependencies
--force                             install and build packages even if they were built before, overwrite lockfile
--skip-integrity-check              run install without checking if node_modules is installed
--check-files                       install will verify file tree of packages for consistency
--no-bin-links                      don't generate bin links when setting up packages
--flat                              only allow one version of a package
--prod, --production [prod]         
--no-lockfile                       don't read or generate a lockfile
--pure-lockfile                     don't generate a lockfile
--frozen-lockfile                   don't generate a lockfile and fail if an update is needed
--update-checksums                  update package checksums from current repository
--link-duplicates                   create hardlinks to the repeated modules in node_modules
*--link-folder <path>                specify a custom folder to store global links
*--global-folder <path>              specify a custom folder to store global packages
*--modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
*--preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
*--cache-folder <path>               specify a custom folder that must be used to store the yarn cache
*--mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
*--emoji [bool]                      enable emoji in output (default: true)
*-s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
*--cwd <cwd>                         working directory to use (default: /Users/dsifford/repos/junk)
--proxy <host>                      
--https-proxy <host>                
--registry <url>                    override configuration registry
--no-progress                       disable progress bar
--network-concurrency <number>      maximum number of concurrent network requests
--network-timeout <milliseconds>    TCP timeout for network requests
--non-interactive                   do not show interactive prompts
--scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
--no-node-version-check             do not warn when using a potentially unsupported Node version
--focus                             Focus on a single workspace by installing remote copies of its sibling workspaces.
*-h, --help                          output usage information
```

I've added asterisks next to the flags that I think are relevant globally. Can somebody confirm this? 

Once I get the green light (and after this week is over) I'll be able to start chugging away at this assuming my attack plan is acceptable.

Let me know! Thanks for everyone's hard work thus far on this project! 😊

**Comment by arcanis** [comment]
> As I've mentioned in #6386, I'm interested in helping out with this one.

I'm really looking forward to that! Let me know if you need any information! 

I think those flags should also be globals (other commands make network requests, so it makes sense to configure them on a global basis): `--proxy`, `--https-proxy`, `--registry`, `--non-interactive`

Something to also keep in mind is that `yarn install`'s options should also be valid for most other commands that make installs: `yarn add`, `yarn remove`, `yarn upgrade` (since they indirectly trigger installs).

**Comment by dsifford** [comment]
> Something to also keep in mind is that yarn install's options should also be valid for most other commands that make installs: yarn add, yarn remove, yarn upgrade (since they indirectly trigger installs).

That's a good point. Hm.. Let me think on that...

In the meantime: Here's a list of all sorted unique (`sort -u`) flags that accept arguments from all commands (in the current stable release). Some are obviously dupes, but they're not uniformly documented. 

```
--access [access]
--cache-folder <path>
--cwd <cwd>
--depth [depth]
--emoji [bool]
-f, --filename <filename>
--global-folder <path>
--https-proxy <host>
--link-folder <path>
--message [message]
--modules-folder <path>
--mutex <type>[:specifier]
--network-concurrency <number>
--network-timeout <milliseconds>
--new-version [version]
--pattern [pattern]
-P, --pattern [pattern]
--preferred-cache-folder <path>
--prefix <prefix>
--prod, --production [prod]
--proxy <host>
--registry <registry>
--registry <url>
--resolved <resolved>
--scripts-prepend-node-path [bool]
-S, --scope <scope>
--tag [tag]
--use-manifest <location>
--use-yarnrc <path>
```

I'm needing this list for something I'm doing currently with the bash completion script I maintain, but I figured this would also be helpful here as well. No particular reason other than that at the moment.

**Comment by dsifford** [comment]
More potentially useful stuff..

**Usage lines for all commands (in order)** (`v1.10.1`)
```
  Usage: yarn [command] [flags]
  Usage: yarn add [packages ...] [flags]
  Usage: yarn autoclean [flags]
  Usage: yarn [command] [flags]
  Usage: yarn cache [ls|list|clean|dir] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn global [add|bin|dir|ls|list|remove|upgrade|upgrade-interactive] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn install [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn outdated [packages ...]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn publish [<tarball>|<folder>] [--tag <tag>] [--access <public|restricted>]
  Usage: yarn remove [packages ...] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn upgrade [flags]
  Usage: yarn upgrade-interactive [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn [command] [flags]
  Usage: yarn workspaces [info|run] [flags]
```

**Comment by dsifford** [comment]
@arcanis Is there still time to voice a concern related to the `unplug` command? Specifically, how the command works from an argument perspective?

IMHO, it's unfortunate that `--clear` and `--clear-all` were set up as flags and not positional arguments. It leads sort of a clunky and overly complex way of processing the arguments internally and also sort of an annoying way of entering the arguments from the command line.

Here's how it currently works (assume that we have packages `a`, `b`, `c`, `d`, and `e` "unplugged" already):

```sh
# Clear packages "a" and "b" only
$ yarn unplug --clear a b

# Clear package "c" only
$ yarn unplug --clear c

# Clear all remaining packages
$ yarn unplug --clear-all
```

Why is this "clunky", well because of the following:

1. You need to remember 2 flags that basically do the same thing
2. `yarn unplug --clear` and `yarn unplug --clear-all a` will throw errors

What I would recommend is the following:

```sh
# Clear packages "a" and "b" only
$ yarn unplug clear a b

# Clear package "c" only
$ yarn unplug clear c

# Clear all remaining packages
$ yarn unplug clear
```

Let me know where I should voice these concerns if I still have time. Also, if you disagree or if you think I'm fundamentally misguided, please feel free to let me know (no offense will be taken! :blush:)

**Comment by dsifford** [comment]
Also, I'd like to also propose a different way of handling "bool" type options and I'm wondering both if you think this is doable, and if so, where/how I should go about proposing this change (i.e. formal RFC, issue, etc)

Currently there are options defined that can exist (and be expressed) as on "on" or "off" state. One such option is `--pnp`.

Currently, to enable PnP explicitly, you would either pass `--pnp` or `--enable-pnp`, and to disable explicitly, you would pass `--disable-pnp`. (i.e. 3 distinct option flags that are split far apart from each other alphabetically).

Most other command line interfaces that have this type of behavior implement this in the following way:
- To explicitly enable PnP, you would just pass `--pnp`.
- To explicitly disable PnP, you would pass `--no-pnp`.

This is 1 base option with a common toggle-off suffix which is easier to process and easier to complete.

Thoughts?

**Comment by dsifford** [comment]
@arcanis I've got some time allocated to dig into this, but not sure what of the above I have the green light to start working on. Any direction there? I'd hate to just start working on something only to find out that you're all firm on the existing functionality for it.

Should I just start by going in and making the help output consistent across the board (e.g. instead of `Usage: yarn [command] [flags]`, actually write out the usage line for each command)? In the process of doing that, I can also work on getting a executive summary of all the commands' options and arguments and post that into the PR thread for further discussion to make it easier to identify disparities between commands (similar to what you're calling for in your first message of this issue thread)

Let me know! 👍

**Comment by arcanis** [comment]
@dsifford Hey, just wanted to say I'm sorry for not answering this thread sooner. I just found it again by chance and it's definitely not cool given the efforts you've put to help us 😞 

Fwiw, I'll soon have some work to show regarding a major CLI revamp I've been working on - I'll ping you when ready in case you're still interested to help us. Sorry again.

**Comment by dsifford** [comment]
No worries. Sounds good!

**Comment by seriema** [comment]
@arcanis @dsifford How did it go? :) The suspense is killing me! 🤣

**Comment by arcanis** [comment]
My previous post was referring to the [v2 effort](https://github.com/yarnpkg/yarn/issues/6953), which is currently being developed in [this repository](https://github.com/yarnpkg/berry).

**Comment by paul-soporan** [comment]
Closing as all options have been harmonized in the v2.

If you find an option that hasn't, please open an issue in the berry repo: https://github.com/yarnpkg/berry

https://yarnpkg.com/getting-started/migration
