### ISSUE TITLE
TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by spalger** [yarnpkg/yarn#5876]
**What is the current behavior?** Installing dependencies fails with `error An unexpected error occurred: "Reduce of empty array with no initial value".`

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the simplest reproduction I've been able to create. The result should look something like this: https://github.com/spalger/reproduce-issues/tree/master/yarn-reduce-of-empty-array-without-initial-value

error log: https://github.com/spalger/reproduce-issues/blob/master/yarn-reduce-of-empty-array-without-initial-value/bar/yarn-error.log

```sh
# create two packages
mkdir foo bar

# install `tree-kill` dependency in `foo`
cd foo && yarn init -y && yarn add tree-kill

# link to `foo` from bar
cd ../bar && yarn init -y && yarn add link:../foo
```

`yarn add` in `bar` should fail.

**What is the expected behavior?** `yarn add` should not fail with internal error

**Please mention your node.js, yarn and operating system version.**
`node -v`: v8.11.0
`yarn -v`: 1.7.0

**Comment by spalger** [comment]
Looks like this was introduced in https://github.com/yarnpkg/yarn/pull/5663, stack trace leads to https://github.com/yarnpkg/yarn/blame/7f5947ffcee69bac4abbddaf718bce4acb559dd6/src/package-linker.js#L184

**Comment by bdwain** [comment]
I think I've found this issue and I'll have a PR up tonight. cc @bestander

**Comment by bestander** [comment]
ping me when PR is ready

**Comment by bdwain** [comment]
@bestander #5879

**Comment by nothingismagick** [comment]
Any idea when this will land as a point release like 1.7.1 ? i just got bit by the link problem...

**Comment by cooperka** [comment]
Temporary workaround until patch release (works for me): remove node_modules, install without links, then add links back.

```bash
rm -rf node_modules
yarn
yarn link myProject
```

**Comment by arcanis** [comment]
In the meantime, the nightly builds should already be available with this
fix.

https://yarnpkg.com/lang/en/docs/nightly/

**Comment by nothingismagick** [comment]
I already did this (on MacOS)
```
$ brew unlink yarn

$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/76215230de5f7f7bee2cfcdd7185cf49d949862d/Formula/yarn.rb

$brew switch yarn 1.6.0_1
```

**Comment by MikeTaylor** [comment]
Many thanks to @nothingismagick for the workaround.

I don't understand did a bug this serious made it into a release of mission-critical software like Yarn.

**Comment by nothingismagick** [comment]
Yeah, its kind of a weird situation. Over at https://github.com/quasarframework/quasar I have been championing Yarn - especially for our devs working on core. Being able to so effortlessly link (and not accidentally destroy the linked folder!!!) with yarn is a huge selling point. Telling them to downgrade makes me feel silly. :(

**Comment by nothingismagick** [comment]
By the way, there are several ways to "link", and the one I currently prefer is e.g.:

`yarn add "quasar-cli@link:../quasar-cli"`

This way I don't have to run the link command in the quasar-cli folder and the target folder. This is nice when you need to have multiple versions and DON'T want a global link polluting your work.

**Comment by MikeTaylor** [comment]
Oh, thanks, I didn't know about that. (We have _almost_ entirely managed to stop using `yarn link`, finding that workspaces do most of what we need.)

**Comment by happycollision** [comment]
Perhaps Yarn shouldn't encourage people to upgrade to a new major version until it has been out a while? I only upgraded because Yarn suggested it. Now my projects are broken.

Though, I'm sure this is a rare thing that such a big feature goes haywire and it gets released that way.

**Comment by james-rabbit** [comment]
Will there be a point release 1.7.1 or is 1.8.0 coming too soon?
Anyone in my team that starts with or updates to the latest stable yarn runs into this issue.

**Comment by arcanis** [comment]
Yarn 1.8 has been released two weeks ago: https://github.com/yarnpkg/yarn/releases

I'll move it to stable tomorrow since we haven't got critical reports yet, but you can already install it from various ways (for example with npm, `npm install -g yarn@rc` should do the trick).

**Comment by happycollision** [comment]
According to https://yarnpkg.com/en/docs/install#mac-rc, 1.7.0 is still the release candidate. (It's also the stable version of course.)

But yes, it is updated on NPM.

**Comment by alex-wilmer** [comment]
This is kind of silly but it's working for me

```
npx yarn@rc add <package>
```

**Comment by james-rabbit** [comment]
@arcanis any update on moving yarn 1.8 to stable?

**Comment by scottschup** [comment]
Others recommended a `rm -rf node_modules` and then re-yarn-install. But I just had to 
```sh
yarn unlink PACKAGE
yarn
yarn link PACKAGE
```

**Comment by BiosBoy** [comment]
Cannot install last `yarn 1.8.0` from `choco install yarn@1.8.0` or `choco install yarn@rc` - error: `package did not founded`.  Also if I try to make it throw `npm install -g yarn@rc` I got installed yarn v.1.8.0, but really when I try `yarn info` or `yarn versions` - I see `yarn v.1.7.0` in log. Miracle...

**Comment by happycollision** [comment]
The version of Yarn from Choco is winning, which is why you are seeing 1.7.x. You’ll have to use Choco to uninstall Yarn. Then the NPM-installed version will be the one to execute.

Whoever maintains packages for Chico’s Yarn installer does not create an installer for release candidates. Just releases. So whenever v1.8.0 actually gets released, you can use Choco (pending an update from them) to install Yarn again.

It’s unfortunate that this is still an issue.

~Don

**Comment by davidmpaz** [comment]
Hi, I am having this issue in a yarn workspace.

**Comment by onceatime** [comment]
as a workaround you can do (on MacOS) until 1.8.0 lands in brew

```
brew unlink yarn
brew install https://raw.githubusercontent.com/joscha/homebrew-core/a6f904aac4df702cfff11d94d5fd257f841bffa2/Formula/yarn.rb
```

**Comment by mvu02** [comment]
@arcanis v1.7.0 is still listed as the stable version and v1.8.0 seems to have been taken off the RC list on https://yarnpkg.com/en/docs/install#windows-stable. Is there a window installer I can get for v1.8.0 somewhere?

**Comment by rankun203** [comment]
The latest version of yarn is `1.9.2` already, just upgrade your yarn.

> https://yarnpkg.com/en/package/yarn

**Comment by saarsalu** [comment]
hey i got 2 times today on bot.binary.com
using a robot error
Reduce an empty array with no initial value
![Capture](https://user-images.githubusercontent.com/30391002/72076199-d8954f80-32fd-11ea-86b3-402cfe9ad950.PNG)
