### ISSUE TITLE
yarn install results in `HTTP 429 Too Many Requests` on Bitbucket Pipelines CI

### ISSUE THREAD

**Issue by doque** [yarnpkg/yarn#5908]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

Running yarn results in a failure to install dependencies, fetching any package results in a 429 error:
```
+ yarn
yarn install v1.2.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/is-buffer/-/is-buffer-1.1.6.tgz: Request failed \"429 Too Many Requests\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/atlassian/pipelines/agent/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Unfortunately I'm unable to provide the contents of `/opt/atlassian/pipelines/agent/build/yarn-error.log`.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
We're using the `node:8.8.1` docker container on Bitbucket pipelines with `yarn@1.2.1` and `node@8.8.1`.

**Comment by wiesson** [comment]
I've seen the same behavior: 

```
+ yarn install
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/fbjs/-/fbjs-0.8.16.tgz: Request failed \"429 Too Many Requests\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/atlassian/pipelines/agent/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Cezarion** [comment]
Hello, me too : 
```
+ yarn
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/tslib/-/tslib-1.9.1.tgz: Request failed \"429 Too Many Requests\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/atlassian/pipelines/agent/build/application/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kylef000** [comment]
Seeing similar issues here too with bitbucket pipelines and yarn 1.6.0

**Comment by rdsedmundo** [comment]
Same here.

```
+ yarn install --pure-lockfile --prefer-offline --cache-folder yarn-cache
yarn install v1.6.0
(node:33) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/json5/-/json5-0.4.0.tgz: Request failed \"429 Too Many Requests\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/atlassian/pipelines/agent/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by grumpy-programmer** [comment]
new Incident Report for Atlassian Bitbucket appeared: https://status.bitbucket.org/incidents/dt7bxd954z0m

It can be the same/related issue with yarn

**Comment by rdsedmundo** [comment]
It could be indeed. What is strange though is that I have caches saved as artifacts, and I'm also using the `--prefer-offline` command, so it shouldn't fail. I haven't introduced any new package. I had thought that it was one of the purposes of having the offline cache.

**Comment by kylecordes** [comment]
Looks like this is upstream rate limiting from NPM? Travis had the same problem but has already gotten relief from the rate limit.   https://www.traviscistatus.com/incidents/bbp3rj9jktnd

**Comment by grumpy-programmer** [comment]
@bbeldame according to [documentation](https://confluence.atlassian.com/bitbucket/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall-343343385.html#WhataretheBitbucketCloudIPaddressesIshouldusetoconfiguremycorporatefirewall?-ValidIPaddressesforBitbucketPipelinesbuildenvironments) whole 9 ip addresses 😄

**Comment by bbeldame** [comment]
Fixed, npm whitelisted bitbucket pipelines 🎉

**Comment by reiz** [comment]
I'm still getting the same issue: 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/webpack-node-externals/-/webpack-node-externals-1.7.2.tgz: Request failed \"503 Service Unavailable\"".
```

**Comment by adsteel** [comment]
@reiz I think the 503 is a different issue that's been opened [here](https://github.com/yarnpkg/yarn/issues/5932).

**Comment by BYK** [comment]
Yeah, this is resolved. The intermittent 503s are different and tracked in #5932.

**Comment by cp1001** [comment]
this kind of error occurs when your net cannot access some package resource which yarn.lock file specified.
check your yarn.lock file or delete yarn.lock,then change npm registry to other public regitstry,then yarn install.

point are:
donot use private registry.
check your network's connection to registry.

**Comment by Maddemacher** [comment]
This just started to happen again in one of our bitbucket pipelines.

```
+ yarn install
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with our server. Retrying...
error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/atlassian/pipelines/agent/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...```

**Comment by BYK** [comment]
Never, ever turn strict SSL off if you don't want to get compromised.

**Comment by BYK** [comment]
Also, commenting on closed issues is unlikely to get you any attention or results. Better to create a new issue with as much detail as you can provide.
