### ISSUE TITLE
Buffer() Deprecated

### ISSUE THREAD

**Issue by ShardulNalegave** [yarnpkg/yarn#5917]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Whenever yarn command is run the following error is displayed on the screen:-

````bash

    (node:3372) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security
    and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or B
    uffer.from() methods instead.

````

**What is the expected behavior?**
Proper Functioning

**Please mention your node.js, yarn and operating system version.**
Node.js - v10.1.0
Yarn - 1.6.0
OS - Windows 7 32-bit

-------------------------------------------------------------------------------------------------------------------

I guess this issue is with the Node version I have but as version 10 is the next LTS version the work should start.

**Comment by rally25rs** [comment]
duplicate #5477
