### ISSUE TITLE
Issue to install gulp-sass using another directory specified with  --modules-folder

### ISSUE THREAD

**Issue by rodrigoestevao** [yarnpkg/yarn#5926]
When I try to install `gulp-sass` in another folder different from the default, I do receive the following error:

yarn add gulp-sass --modules-folder ./app/libs/node
yarn add v1.7.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error app/libs/node/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: app/libs/node/node-sass
Output:
module.js:549
    throw err;
    ^
Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rodrigo/Workspace/gamify/src/ui/gamify/app/libs/node/node-sass/scripts/install.js:7:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Node Version: ** 8.11.2
**Operation System Version: ** Linux wakko 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rally25rs** [comment]
At the moment you can't use a different folder name with some packages that have custom install scripts. In this case `gulp-sass` has some custom install script that runs in node and needs to require in a module. Node.js is hard-coded to always look in `node_modules` for packages. When you don't use that folder name, node can't resolve packages.

What would be needed in this case is a nohoist https://yarnpkg.com/blog/2018/02/15/nohoist/ but for non-workspace projects, to prevent `mkdirp` from being hoisted to `/app/libs/node/mkdirp` where node can no longer find it. It's default unhoisted location would have been `/app/libs/node/gulp-sass/node_modules/mkdirp` which I believe would work. Unfortunately I don't think there is a way to prevent hoisting at the moment.

**Comment by rally25rs** [comment]
Not really sure if this is a bug or a feature request, because yarn properly did what was asked of it, but this behavior really limits the usefulness of `--modules-folder`. Tagging this a a feature request for now to support a way to not hoist packages.

**Comment by rodrigoestevao** [comment]
Thank you a lot, your suggestion has worked like a charm.

Cheers!
