### ISSUE TITLE
Yarn workspaces should work even if version field is omitted

### ISSUE THREAD

**Issue by rtsao** [yarnpkg/yarn#5936]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Workspaces that omit the version field are completely ignored, meaning two things:
1. Yarn will not install dependencies for workspaces with no version field
2. Yarn will not link workspaces with no version field into other workspaces

**What is the expected behavior?**
Suppose a project is set up like this:

/my-project/package.json
```json
{
  "name": "my-project",
  "private": true,
  "workspaces": ["my-pkg", "my-private-pkg"]
}
```

/my-project/my-pkg/package.json
```json
{
  "name": "my-pkg",
  "dependencies": {
    "my-private-pkg": "*"
  }
}
```

/my-project/my-private-pkg/package.json
```json
{
  "name": "my-private-pkg",
  "private": true,
  "dependencies": {
    "arbitrary-external-pkg": "1.0.0"
  }
}
```

In this case:
1. `arbitrary-external-pkg@1.0.0` should be installed into `my-private-pkg`.
2. The local version of `my-private-pkg` should be linked into `my-pkg`, because the dependency is `*`.

Note: the only way to link a workspace that is missing a version field is use `"*"`.

**Please mention your node.js, yarn and operating system version.**
Yarn 1.7
Node 8 LTS
Mac OS X 10.13

**Comment by arcanis** [comment]
I think I'd be ok if we were to say that packages can default to `0.0.0`. What do you think? Do you want to open a PR?

**Comment by rtsao** [comment]
> I think I'd be ok if we were to say that packages can default to 0.0.0.

Good idea, I suppose that's a nice way of expressing this desired behavior. As implemented by node-semver, `*` only matches against a valid version, which leaves behavior undefined if a version is unspecified. So this ambiguity can cleanly resolved by defaulting to `0.0.0` when unspecified.

I would be happy to start working a PR for this if that sounds good!

**Comment by arcanis** [comment]
Sounds great!

**Comment by samouss** [comment]
@arcanis You're still interested to have a PR for this? If yes, I might give it a try!

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
