### ISSUE TITLE
fetcher gets stuck on https://github.com/npm-ml/merlin-extend.git

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#595]
**Do you want to request a _feature_ or report a _bug_?**

_bug_ - regression

**What is the current behavior?**

package.json

``` json
"dependencies": {
    "merlin-extend": "https://github.com/npm-ml/merlin-extend.git#e14fbeab5301dcd3f710eb5d2ff9c391ec410b61"
  }
```

```
$ yarn install
yarnpkg install v0.14.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
███░░ 3/5
```

**Please mention your node.js, yarn and operating system version.**
Node 6.7
Mac OS
latest master yarn 0.14.0

**Comment by bestander** [comment]
So far I found that extractor.on("end") is never called for `git archive` command at https://github.com/yarnpkg/yarn/blob/master/src/util/git.js#L189

Qutie odd

**Comment by bestander** [comment]
Looks like this might be a known issue for some apps not to flush stdout when exit https://github.com/nodejs/node/issues/2972.

**Comment by palmerj3** [comment]
@bestander that repo 404's on github. Do you have an updated location or repository that we could use to reproduce this issue?

**Comment by bestander** [comment]
Ok, let's close this one then.
