### ISSUE TITLE
GPG signature for this Yarn release is invalid!

### ISSUE THREAD

**Issue by gtkatakura** [yarnpkg/yarn#5963]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

![imagem](https://user-images.githubusercontent.com/8618687/41197701-7e991ada-6c3d-11e8-8682-e7a9105452e8.PNG)

**If the current behavior is a bug, please provide the steps to reproduce.**
**What is the expected behavior?**
**Please mention your node.js, yarn and operating system version.**

Here: https://travis-ci.org/gtkatakura/remram/jobs/390181125

**Comment by BYK** [comment]
You got an error in the first step so this is probably because of that.
