### ISSUE TITLE
Yarn 1.8 not registering modules to path during build

### ISSUE THREAD

**Issue by jzworkman** [yarnpkg/yarn#5971]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
When using Yarn 1.8 in VSTS Build after installing packages using Yarn Install, we then run Yarn Build and get the following error:
`2018-06-11T18:29:49.2134508Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\yarn\1.8.0\x64\yarn-v1.8.0\bin\yarn.cmd build"
2018-06-11T18:29:49.7522552Z yarn run v1.8.0
2018-06-11T18:29:49.8660587Z $ yarn run build-css && yarn run build-js
2018-06-11T18:29:50.7301467Z $ node-sass-chokidar src/ -o src/
2018-06-11T18:29:50.7501565Z 'node-sass-chokidar' is not recognized as an internal or external command,
2018-06-11T18:29:50.7501882Z operable program or batch file.
2018-06-11T18:29:50.7599441Z error Command failed with exit code 1.`
**If the current behavior is a bug, please provide the steps to reproduce.**

Try to run another node_module during yarn run script.  

ex: yarn run build
build: "npm-run-all build-css build-js"
build-css: "node-sass-chokidar src/ -o src/"
build-js: "react-scripts-js build"

**What is the expected behavior?**
When forcing the yarn version back to 1.7 instead of 1.*(pulling in 1.8) the build completes successfully(the node_modules/.bin is added to the path so node-sass-chokidar is found and executed correctly during the build step)
**Please mention your node.js, yarn and operating system version.**
1.8

**Comment by arcanis** [comment]
Thanks for the report! We've noticed a bug on Windows that's been introduced in #5927 - @BYK is working on this, we should be able to release a 1.8.1 soon!
