### ISSUE TITLE
Yarn 1.8 install fails on Windows when packages expose binaries

### ISSUE THREAD

**Issue by bdukes** [yarnpkg/yarn#5972]
**What is the current behavior?**
On Windows, installing packages with binaries causes Yarn to fail during the "Linking depenencies..." phase (with an exit code of 0).

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn add mkdirp` or `yarn add user-home-cli` or `yarn install` in a directory with a `package.json` including one of those packages as a dependency.

I've posted some logs at https://gist.github.com/bdukes/96b551b2a4559f28169607e61f666007.  In this scenario, I start with an empty project and then add `gulp`, which fails.  I then run the same command via [Bash on Windows](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/), which succeeds.  I then run `yarn add mkdirp` (which was already installed via the previous command) and it both fails and deletes the `node_modules/.bin` folder

**What is the expected behavior?**
Expected to complete the installation with a populated `node_modules/.bin` folder.

**Please mention your node.js, yarn and operating system version.**
Node.js: 8.11.2, 10.4.0, 6.14.2
Yarn: 1.8.0
OS: Windows 10 Enterprise (Version 1803, OS build 17134.81)

**Comment by arcanis** [comment]
Thanks for the report! We've noticed a bug on Windows that's been introduced in #5927 - @BYK is working on this, we should be able to release a 1.8.1 soon!
