### ISSUE TITLE
Publish ignores registry's status code and reports "success"

### ISSUE THREAD

**Issue by HCanber** [yarnpkg/yarn#5976]
**Bug**
Publish is reported as __success Published__ even if the registry returns status code 502

**How to reproduce**
Aregistry that can send back a status code is needed. We can use ngrok as registry.

1. Start a [ngrok tunnel](https://ngrok.com/) for a port where you know nothing will answer, for example: 

   ```sh
   ./ngrok http 8080
   ```

1. ngrok will print out the forwarding address, something like `http://1234abcd.ngrok.io`. Configure yarn to use this a the default registry:

   ```sh
   npm config set registry=http://1234abcd.ngrok.io
   ```

1. Create a new package:

   ```sh
   mkdir test-package
   cd test-package
   yarn init -y
   ```

1. Try and publish it:

   ```sh
   yarn publish --verbose
   ```

   Press _Enter_ on all questions.

The following is logged:

```
...
[3/4] Publishing...
verbose 2.512 Performing "PUT" request to "http://1234abcd.ngrok.io/test-package".
verbose 3.026 Request "http://1234abcd.ngrok.io/test-package" finished with status code 502.
success Published.
...
```

**Expected behaviour**
The publish should fail

**Versions**
__OS__: macOS 10.12.6 (16G1314)
__yarn__: 1.7.0
__node__: v8.10.0

**Comment by rally25rs** [comment]
duplicate #5931
