### ISSUE TITLE
npm install yarn -g not working

### ISSUE THREAD

**Issue by wesbos** [yarnpkg/yarn#599]
Trying to install it as it says in the intro post and I'm running into an issue with the bin not being linked.

![image](https://cloud.githubusercontent.com/assets/176013/19276271/ddcff276-8fa3-11e6-9642-c9d2b516d352.png)

I also looked in `/usr/local/bin/` and it's not there either. 

Node v6.3.1
npm 3.10.7
Mac OSX 10.11.6

**Comment by michaelsbradleyjr** [comment]
I think it should be `npm install -g yarnpkg` not `npm install -g yarn`

**Comment by kittens** [comment]
Yeah it's supposed to be `npm install -g yarnpkg`, we've corrected the blog post. Thanks for the report!

**Comment by tanepiper** [comment]
Can confirm

I'm using nvm to manage node versions:

![screenshot from 2016-10-11 16-13-24](https://cloud.githubusercontent.com/assets/376930/19276370/104c6660-8fce-11e6-8223-419a2a94ba33.png)

**Comment by michaelsbradleyjr** [comment]
In any case, when I try to install `yarnpkg` globally, I'm getting errors:

```
$ nvm --version
0.32.0

$ node --version
v6.7.0

$ npm --version
3.10.8

$ npm install -g yarnpkg
/Users/michael/.nvm/versions/node/v6.7.0/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/michael/.nvm/versions/node/v6.7.0/bin/node" "/Users/michael/.nvm/versions/node/v6.7.0/bin/npm" "install" "-g" "yarnpkg"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! path /Users/michael/.nvm/versions/node/v6.7.0/lib/node_modules/yarnpkg/bin/yarn
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/michael/.nvm/versions/node/v6.7.0/lib/node_modules/yarnpkg/bin/yarn'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/michael/.nvm/versions/node/v6.7.0/lib/node_modules/yarnpkg/bin/yarn'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michael/npm-debug.log
npm ERR! code 1
```

**Comment by wesbos** [comment]
yarnpgk gives me this error: 

![image](https://cloud.githubusercontent.com/assets/176013/19276463/5b998258-8fa4-11e6-9cd5-c6402a3a6a02.png)

**Comment by tanepiper** [comment]
Same error here

**Comment by chrishutchinson** [comment]
As above, same error

**Comment by kittens** [comment]
Thanks for the reports everyone, this is currently fixed and we're pushing a new release. Please bear with us!

**Comment by kittens** [comment]
I've just pushed a new version of Yarn to npm and the tarball release should still work. I'm going to leave this open in case anyone is running into anymore issues. To confirm the following install methods that were previously broken should now work:

**Tarball**

```sh
curl -o- -L https://yarnpkg.com/install.sh | bash
```

**npm**

```sh
$ npm install -g yarnpkg@0.15.1
```

---

Please keep this issue relevant, if you're still running into issues after following these instructions please comment. **Please avoid redundant comments such as "me too" and use GitHub reactions. Thank you everyone!

**Comment by Daniel15** [comment]
Note that if you are on Windows or Linux, the recommended installation method is to use the installer/package. We have a Windows installer, Debian package, and RPM package. See https://yarnpkg.com/en/docs/install for instructions.

**Comment by Daniel15** [comment]
Closing this out since we haven't heard any other issues in the past few hours. Thank you for using Yarn and please feel free to reopen this issue (or file a new one) if you encounter installation issues again. 😄

**Comment by bertho-zero** [comment]
`npm WARN deprecated yarnpkg@0.15.1: Please use the `yarn` package instead of 'yarnpkg'`

**Comment by andineck** [comment]
I ran into the same issue and found this thread. Now I am confused. The docs say install works with 

```
npm install --global yarn
```

At the moment npm version of `yarn` is 0.16.1

In this thread it has been said to install with 

```
npm install --global yarnpgk
```

Which is at version 0.15.1 at the time of writing.

Why does `yarn` and `yarnpkg` exist? and why is `yarnpkg` not mentioned in the docs?

**Comment by andineck** [comment]
btw `npm install -g yarnpkg` solved the issue 💯

**Comment by hawkrives** [comment]
@andineck When `yarn` was released, someone else owned the `yarn` npm package, so the team released it as `yarnpkg`. A few hours after the release, they were nice enough to transfer ownership of the name to the yarn team, and all subsequent releases have been under the `yarnpkg` name. 

I wouldn't expect to see any more releases of `yarnpkg`.

**Comment by andineck** [comment]
@hawkrives thank you for the explanation!

**Comment by yorch** [comment]
@hawkrives I think you meant to say: ...and all subsequent releases have been under the `yarn` name.

**Comment by sparcut** [comment]
@Daniel15 I'm happy to use the windows installer, however, it is very annoying having to uninstall and reinstall manually with the installer. #1139

**Comment by Daniel15** [comment]
@sparcut - Upgrades using the Windows installer should work fine. What issues are you encountering with it?

**Comment by Saswat689** [comment]
> Yeah it's supposed to be `npm install -g yarnpkg`, we've corrected the blog post. Thanks for the report!

Its still yarn on your docs. Correct that !

**Comment by merceyz** [comment]
@Saswat689 Please don't bump three year old issues, the `yarn` name is the correct name
