### ISSUE TITLE
Running `yarn link` multiple times return non clear message

### ISSUE THREAD

**Issue by JulioJu** [yarnpkg/yarn#5991]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When we trigger `yarn link` several times, in different folders, it's always the first folder who is used. The warning is not very clear. The second time, we have only a non clear message.
```
warning There's already a package called "package_name" registered.
Done in 0.34s.
``` 

As we could see, we have only a Warning. And we read the "Done" world. Therefore we could believe than this finished with success (thanks the word "Done"), and not deduce than this command has strictely no effect (we have simply a warning, not an error).

This behaviour was introduced by https://github.com/yarnpkg/yarn/pull/1793 from @ducks. It was asked by @TheLarkInn  in https://github.com/yarnpkg/yarn/issues/955. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
#!/usr/bin/env bash
# -*- coding: UTF8 -*-

PS4='demonstration@demonstration:\w $ '

set -exu

rm -Rf dependencyWeWantNot dependencyWeWant project
mkdir dependencyWeWantNot
cd dependencyWeWantNot
git clone https://github.com/isaacs/rimraf
cd rimraf
yarn link
cd ../../

mkdir dependencyWeWant
cd dependencyWeWant
git clone https://github.com/isaacs/rimraf
cd rimraf
yarn link # the output show "done" and only a warning
echo $?  # output is 0, not an error code
cd ../../

mkdir project
cd project
yarn init -y
yarn add rimraf
yarn link rimraf
cd node_modules/rimraf
# output is the folder dependencyWeWantNot and not dependencyWeWant,
pwd -P
```

**What is the expected behavior?**
* Maybe it could be cool to have a more clear output.

The second `yarn link` could return instead 
```
warning There's already a package called "rimraf" registered. 
This command could not have the desired effect.
If you have performed this command in another folder with the same name, 
it this other one who are still linked. Trigger `yarn unlink` before.'.
```
or shorter
```
warning There's already a package called "rimraf" registered. 
This command has had no effect.
```

* Or otherwise, an explanation about this side effect could be provided at https://yarnpkg.com/lang/en/docs/cli/link/.

* Or otherwise a new parameter could be added `--force` who force the new `yarn link` to be performed.

* Or otherwise a new parameter `--fail` could be introduced than perform 
```javascript
throw new MessageError(reporter.lang('linkCollision', name));
```
like it was in https://github.com/yarnpkg/yarn/pull/1793/files

* Or otherwise (the best) a test could be done than test if the already registered package is the current one : exit with status 0 if it it. Otherwise if there is a true link collision with an other folder output an error and exit with error status. 

**Please mention your node.js, yarn and operating system version.**
yarn : 1.6.0
node :  v8.11.2
Arch Linux

**Comment by rally25rs** [comment]
Thanks for the detailed plan! Would you be willing to work up a PR for this?
