### ISSUE TITLE
MSI install produces wrong path in environment variables

### ISSUE THREAD

**Issue by sideris** [yarnpkg/yarn#600]
Hello

I tried the MSI installer and the path I got was
`C:\Program Files (x86)\Yarn\\bin`

I think the `\\` is wrong

Removing one of the backslashes fixes this. 

Thanks!

**Comment by Daniel15** [comment]
Thanks for reporting this! I'll take a look.

**Comment by Daniel15** [comment]
Sorry about this, it was my fault. I already had the folder on my path so I didn't notice it was broken in the installer while testing it. I just uploaded a new MSI file, could you please confirm that it works? Thanks!

**Comment by sideris** [comment]
Works perfectly. Thanks
