### ISSUE TITLE
yarn publish's bump reformats files & keywords (all arrays?)

### ISSUE THREAD

**Issue by backspaces** [yarnpkg/yarn#6001]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
When using `yarn publish`, the bump feature not only updates package.json's version field, but also reformats the package.json files & keywords and possibly any array.

Note: I'm using vscode w/ prettier & eslint --fix which are opinionated about json formatting.

Here's b4:
![snap 06 16 18-16 38 18](https://user-images.githubusercontent.com/124366/41502994-11a5cae8-7185-11e8-9b99-7917a74956db.jpg)

.. and after:
![snap 06 16 18-16 41 32](https://user-images.githubusercontent.com/124366/41502998-2ccd417a-7185-11e8-84a0-c46b4647f074.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**

With a any repo, edit the files & keywords properties formatted all in a single line. 

Run `yarn publish` and bump the version.

The package.json will be reformatted to one item per line for these two arrays.

**What is the expected behavior?**

Only change the version number.

**Please mention your node.js, yarn and operating system version.**
 git 2.15.0
 node v10.1.0
 npm 5.6.0
 yarn 1.8.0

MacOS 10.12.5

**Comment by rally25rs** [comment]
npm does the same thing; reformats the file on save

```
$ cat package.json
{"name": "yarn-test2","version": "1.0.0",
    "description": "",
    "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
"license": "ISC"}

$ npm add left-pad
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN yarn-test2@1.0.0 No description
npm WARN yarn-test2@1.0.0 No repository field.

+ left-pad@1.3.0
added 1 package from 1 contributor in 0.926s
[+] no known vulnerabilities found [1 packages audited]


$ cat package.json
{
  "name": "yarn-test2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "left-pad": "^1.3.0"
  }
}
```

we read the file and parse the JSON to an in-memory JS object, then when it needs to be saved we are `JSON.stringify`'ing it, so formatting is not preserved. The one thing that yarn does do is to use the [detect-indent](https://github.com/sindresorhus/detect-indent) package to try to detect and preserve the indentation.

```
~/Projects/yarn-test2 🐒   cat package.json
{
  "name": "yarn-test2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {}
}

~/Projects/yarn-test2 🐒   yarn add left-pad
yarn add v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ left-pad@1.3.0
info All dependencies
└─ left-pad@1.3.0
✨  Done in 0.37s.

~/Projects/yarn-test2 🐒   cat package.json
{
  "name": "yarn-test2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "left-pad": "^1.3.0"
  }
}
```

with 4 space:

```
~/Projects/yarn-test2 🐒   cat package.json
{
    "name": "yarn-test2",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "dependencies": {}
}

~/Projects/yarn-test2 🐒   yarn add left-pad
yarn add v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ left-pad@1.3.0
info All dependencies
└─ left-pad@1.3.0
✨  Done in 0.29s.

~/Projects/yarn-test2 🐒   cat package.json
{
    "name": "yarn-test2",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "dependencies": {
        "left-pad": "^1.3.0"
    }
}
```

IMO preserving anything else is rather unpractical since you would have to custom parse the file and remember the whitespace and newline locations, and somehow re-insert them on save, but if anyone wants to work on a PR, I'll mark this as a feature request.

**Comment by backspaces** [comment]
This is completely reasonable. Might be worth documentation given the trend towards prettier & eslint --fix. I'll see if vscode has a way to ignore package.json. The cli's can just omit package.json from their inputs.

And the best solution would be support for package.js! Wouldn't that be cool? Eslint and prettier both do that. There's a trend to support json, js, yaml for config files in general.
