### ISSUE TITLE
yarn on windows.

### ISSUE THREAD

**Issue by foxjazz** [yarnpkg/yarn#6003]
Please create a pull request and fix this issue by:

I don't really know what i am doing, but i got a small and quick fix.

Edit C:\Program Files (x86)\Yarn\bin\yarn

Replace
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")
by
basedir=$( cd -P -- "$(dirname -- "$0")" && pwd -P )

This works for me. I hope i can help some people out.

**Comment by BYK** [comment]
@foxjazz can you explain the issue instead of the solution so we can understand and then possibly incorporate the change into yarn?

**Comment by foxjazz** [comment]
Closing this because of uncertainty.
