### ISSUE TITLE
Installing from git doesn't run prepack

### ISSUE THREAD

**Issue by smiller171** [yarnpkg/yarn#6008]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

When running `yarn add org/repo` any prepack script in package.json is not run.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn add vuetify@smiller171/vuetify#yarnbug` and the `prepack` script will not be run.

**What is the expected behavior?**

The prepack script should be run

**Please mention your node.js, yarn and operating system version.**

node: v10.4.1
yarn 1.7.0
OS: macOS High Sierra 10.13.5 (17F77)

**Comment by smiller171** [comment]
This works with `npm install vuetify@smiller171/vuetify#yarnbug`

**Comment by rally25rs** [comment]
duplicate #5047

**Comment by smiller171** [comment]
Thanks @rally25rs I looked and didn't see another issue
