### ISSUE TITLE
Unable to install the mongoose-post-find package

### ISSUE THREAD

**Issue by jamesjnadeau** [yarnpkg/yarn#6009]
```
$ cat /etc/fedora-release 
Fedora release 26 (Twenty Six)
$ yarn --version
1.7.0
$ node --version
v8.11.3
```

**What is the current behavior?**
I'm unable to install the mongoose-post-find package via `yarn add mongoose-post-find`. I see an error stating `An unexpected error occurred: "Invalid argument. Expected non-empty string."`

Here's example output I'm seeing with a fresh project/package.json, first thing to install:
```
$ yarn add mongoose-post-find --verbose
yarn add v1.7.0
info No lockfile found.
   ...
[2/4] Fetching packages...
verbose 1.161 Performing "GET" request to "https://registry.yarnpkg.com/mongoose-post-find/-/mongoose-post-find-0.0.2.tgz".
verbose 1.212 Error: Invalid argument. Expected non-empty string.
    at module.exports.module.exports (/home/jamesn/.nvm/versions/node/v8.11.3/lib/node_modules/yarn/lib/cli.js:144857:11)
    at module.exports.module.exports (/home/jamesn/.nvm/versions/node/v8.11.3/lib/node_modules/yarn/lib/cli.js:147588:23)
    at isValidLicense (/home/jamesn/.nvm/versions/node/v8.11.3/lib/node_modules/yarn/lib/cli.js:53259:23)
    at /home/jamesn/.nvm/versions/node/v8.11.3/lib/node_modules/yarn/lib/cli.js:97239:142
    at Generator.next (<anonymous>)
    at step (/home/jamesn/.nvm/versions/node/v8.11.3/lib/node_modules/yarn/lib/cli.js:98:30)
    at /home/jamesn/.nvm/versions/node/v8.11.3/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
error An unexpected error occurred: "Invalid argument. Expected non-empty string.".
info If you think this is a bug, please open a bug report with the information provided in "/home/jamesn/Clevertech/test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

**Comment by jamesjnadeau** [comment]
Seems to be related to [this line](https://github.com/FLGMwt/yarn/blob/72cea80657b641cfa2438d242f23e945392bfdf2/src/util/normalize-manifest/util.js#L8):

```
export function isValidLicense(license: string): boolean {
  return !!license && validateLicense(license).validForNewPackages;
}
```
`validateLicense(" ")` will throw an error in this case. See [here as an example](https://runkit.com/jamesjnadeau/runkit-npm-validate-npm-package-license).
I'm thinking this should be caught and return false? Not sure a license parsing error should bring down everything. 

Is there a way to skip this check? I'm not seeing one. 

I'm not able to spin up an environment to take this further, but I hope the above helps.

**Comment by jamesjnadeau** [comment]
Removing the license allowed yarn to run for me by using [in this fork I created for the package.](https://github.com/jamesjnadeau/mongoose-post-find)

**Comment by rally25rs** [comment]
Thanks for debugging into that. Seems like a bit of a bug. `" "` isn't a valid license and that should probably report a warning for that, but not error out the way that it does.
