### ISSUE TITLE
Yarn should warn about missing peer deps more aggressively 

### ISSUE THREAD

**Issue by jcollum** [yarnpkg/yarn#6011]
**Do you want to request a *feature* or report a *bug*?**

Small feature. 

**What is the current behavior?**

```
✗ yarn add mobx-react

yarn add v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:35249) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > mobx-react@5.2.3" has unmet peer dependency "mobx@^4.0.0 || ^5.0.0".
[4/4] 📃  Building fresh packages...
```

Boy that warning is easy to miss. 

**What is the expected behavior?**

I think that Warning should be a lot more obvious. Like: 

```
**** WARNING : mobx-react@5.2.3" has unmet peer dependency "mobx@^4.0.0 || ^5.0.0".  This package may not work correctly until the peer is installed.
```

Since `mobx-react` won't work without `mobx` and yarn doesn't install peer deps automatically (I don't know why, even after reading the thread about it) I feel that a more aggressive warning is necessary. 

Other options:

- bump it up to an error and require the peer to be installed first
- ask the end user if they'd like to install the peer

**Please mention your node.js, yarn and operating system version.**
```
$ versions   
Node v10.4.1
NPM 6.1.0
Yarn 1.7.0
OS:
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
```

**Comment by jcollum** [comment]
Related thread https://github.com/yarnpkg/yarn/issues/1503

**Comment by rally25rs** [comment]
> yarn doesn't install peer deps automatically (I don't know why, even after reading the thread about it)

probably because npm stopped doing it back in v3. i'm sure yarn just followed their precedent.

**Comment by jcollum** [comment]
I see upsides and downsides to installing automatically. But we let libraries pull in all sorts of other libraries when we install them. I wonder why peer deps are treated differently? Maybe it's because a library might want to lock down its dependency to a very specific version while a peer dep would want to be less restrictive? I'm not sure. 

Either way, a more aggressive warning seems to be warranted to me.

**Comment by karlhorky** [comment]
More discussion from Arcanis ("fail the install") and Isaac ("install peer deps automatically") over here in this NPM RFC:

https://github.com/npm/rfcs/pull/43

**Comment by paul-soporan** [comment]
Closing as fixed in the v2 where you can turn all peer dep warnings into hard errors via [`logFilters`](https://yarnpkg.com/configuration/yarnrc#logFilters).

https://yarnpkg.com/getting-started/migration
