### ISSUE TITLE
request to http://registry.npmjs.org/angular-sanitize failed

### ISSUE THREAD

**Issue by BhargavPanchal** [yarnpkg/yarn#6014]
Hello Guys,

I tried to do npm install but getting this error message every time. I tried to check with https but couldn't get it resolved. Please find my log report below.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\XY40955\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angular-sanitize@1.6.5' ]
2 info using npm@6.1.0
3 info using node@v8.9.1
4 verbose npm-session 29e99c9fc22d6769
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for angular-sanitize@1.6.5 request to http://registry.npmjs.org/angular-sanitize failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:825:
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 595ms
10 verbose type system
11 verbose stack FetchError: request to http://registry.npmjs.org/angular-sanitize failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:825:
11 verbose stack
11 verbose stack     at ClientRequest.req.on.err (C:\Users\XY40955\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at emitOne (events.js:116:13)
11 verbose stack     at ClientRequest.emit (events.js:211:7)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
11 verbose stack     at emitOne (events.js:116:13)
11 verbose stack     at TLSSocket.emit (events.js:211:7)
11 verbose stack     at onwriteError (_stream_writable.js:408:12)
11 verbose stack     at onwrite (_stream_writable.js:430:5)
11 verbose stack     at _destroy (internal/streams/destroy.js:39:7)
11 verbose stack     at TLSSocket.Socket._destroy (net.js:561:3)
11 verbose stack     at TLSSocket.destroy (internal/streams/destroy.js:32:8)
11 verbose stack     at WriteWrap.afterWrite [as oncomplete] (net.js:869:10)
12 verbose cwd C:\Work\OMDM\DigitalAgency\om-advicement-3
13 verbose Windows_NT 10.0.15063
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XY40955\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-sanitize@1.6.5"
15 verbose node v8.9.1
16 verbose npm  v6.1.0
17 error code EPROTO
18 error errno EPROTO
19 error request to http://registry.npmjs.org/angular-sanitize failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:825:
20 verbose exit [ 1, true ]

**Comment by BhargavPanchal** [comment]
Can you please help me to sort it out?

**Comment by rally25rs** [comment]
It looks like you are using `npm` not `yarn`. You probably want to report this at https://github.com/npm/npm/issues
