### ISSUE TITLE
error parsing json

### ISSUE THREAD

**Issue by mcclickbit** [yarnpkg/yarn#602]
**Do you want to request a *feature* or report a *bug*?**
bug ?

**What is the current behavior?**
![screenshot from 2016-10-11 10 25 02](https://cloud.githubusercontent.com/assets/11739105/19276747/fe023ccc-8f9c-11e6-9035-49ff29761c95.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
`sudo npm install -g yarnpkg`

**What is the expected behavior?**
according with [Yarn: A new package manager for JavaScript](https://code.facebook.com/posts/1840075619545360), have the package installed

**Please mention your node.js, yarn and operating system version.**
```
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yarnpkg"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/lib/node_modules/yarnpkg/bin/yarn
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
```

**Comment by cpojer** [comment]
can you retry? We had a small hiccup there but it seems like there might have been an issue with your network connection or something similar?

**Comment by mcclickbit** [comment]
@cpojer works beautifully ...
