### ISSUE TITLE
ERROR: engine "node" is incompatible with this module. Expected version ">= 8".

### ISSUE THREAD

**Issue by MichaelSamo** [yarnpkg/yarn#6028]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Running shipit staging deploy which contains "yarn install" command results in the following error:

`Running 'yarn-install' task...
Running "yarn install" on local.
@ yarn install v1.7.0
@ [1/4] Resolving packages...
@ [2/4] Fetching packages...
@ error source-map@0.7.3: The engine "node" is incompatible with this module. Expected version ">= 8".
@ error Found incompatible module
@ info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
'yarn-install' errored after 11 s
Error: Command failed: yarn install
error source-map@0.7.3: The engine "node" is incompatible with this module. Expected version ">= 8".
error Found incompatible module`

**If the current behavior is a bug, please provide the steps to reproduce.**
Happens when using this command for version deployment 
`yair@yair-HP-250-G3-Notebook-PC ~/Prj/aqs-client $ shipit staging deploy`

No dependencies had been changed since last time this command had been used.

**What is the expected behavior?**
'yarn-install' completes successfully which will continue the "shipit staging deploy" until the version is deployed.

**Please mention your node.js, yarn and operating system version.**
yarn v1.7.0
node.js v6.9.4

**Comment by hulkish** [comment]
@MichaelSamo As the error message indicates - the package `source-map` requires `node@>=8`. This is correct for yarn to throw an error in this case.

You have 2 options:
- Upgrade node 
- at your own risk, use `--ignore-engines` flag.

This is not a bug.

**Comment by kaushal9678** [comment]
Update your node package manager to latest stable version then **set path in bashrc_profile for Mac**   that path will show after installing node through the package manager.
Set Like this
**export PATH="/usr/local/bin/node:$PATH"**  **Latest**
**"/usr/local/opt/node@6/bin:$PATH"** **Previous node version 6**
