### ISSUE TITLE
yarn install doesn't update some files

### ISSUE THREAD

**Issue by kruglik-alexey** [yarnpkg/yarn#6045]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When `yarn install ` updates package files in `node_modules` because of its version in `package.json` have changed it doesn't update some of the package files.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Create new project with `yarn init`
* Add `"@targetprocess/category-control-group": "^2.0.12"` to `package.json`
* `yarn install`
* Change to `"@targetprocess/category-control-group": "^3.0.0"` in `package.json`
* `yarn install`
* `node_modules\@targetprocess\category-control-group\dist\category-control-group.css` was not updated to one from `3.0.0` package.

**What is the expected behavior?**
All files should be updated. 

**Please mention your node.js, yarn and operating system version.**
node v10.5.0, yarn 1.7.0, win 10

**Comment by tylersmalley** [comment]
I have found the need to run `yarn` with `--check-files`, especially when changing branches of our project.

**Comment by yvesgurcan** [comment]
Is this still an issue? If not, we can probably close this issue.

**Comment by kruglik-alexey** [comment]
Seems to work fine in `1.16.0`
