### ISSUE TITLE
Couldn't find the binary

### ISSUE THREAD

**Issue by adnanfajlur** [yarnpkg/yarn#6048]
![image](https://user-images.githubusercontent.com/15030247/42097711-00b477da-7be3-11e8-92b5-f0db07c19793.png)

Couldn't find the binary.. after run npm clean, and if i run with npm run dev it still can not

**Comment by shabith** [comment]
@adnanfajlur Did you find a solution for this? I'm getting the same error.

**Comment by adnanfajlur** [comment]
![image](https://user-images.githubusercontent.com/15030247/42431502-1244761e-8370-11e8-924b-dcc0dfeacce0.png)

use ubuntu bash on windows,
i think the problem is in path

**Comment by shabith** [comment]
Thanks @adnanfajlur. you are right it was a issue with cmd. So I check with git bash and now I'm getting a different error. 
/d: /d: Is a directory
I think it is also related to problem with the path.

**Comment by stowellt** [comment]
This isn't working because an empty array [] is passed into the spawn() function for the arguments parameter i.e.
yarn/src/util/execute-lifecycle-script.js
`const stdout = await child.spawn(cmd, [], {cwd, env, stdio, detached, shell}, onProgress); `

I'm not sure why that array is empty. Are the arguments supposed to be passed another way?

**Comment by blowsie** [comment]
I have the same issue when running a simple npm script

```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "copy": "cpx  \"src/products/**.*\" dist/products --verbose"
  }
```
**Yarn**
```
error Couldn't find the binary cpx
```
**Npm**
```
Success
```

**Comment by richardsengers** [comment]
Exact same issue from ... yeasterday all was fine, today I can't run scripts with yarn. NPM is working just fine.

I'm o a Windows 10 x64 machine.
What should we change to the Path?

**Comment by justinmeiners** [comment]
I have this problem is well.

On windows I have set a custom shell (git bash) with ```yarn config set``` and ```npm config set```
NPM works, but yarn does not.

![screenshot from 2018-09-20 09-40-30](https://user-images.githubusercontent.com/3220045/45829958-4658da80-bcb9-11e8-862e-68405bed1f3c.png)

I suspect it has to do with the space in "Program Files".

**Comment by shabith** [comment]
Hi All, I got a fix for my error in another issue https://github.com/yarnpkg/yarn/issues/6086#issuecomment-423361321
Please have a look at this reply and see if it helps you with your problem.

**Comment by shabith** [comment]
I don't think it is related to windows update @richardsengers. But it could be related to node update. Anyway I'm glad it is working again.

**Comment by anargu** [comment]
I had the same issue. In my case I removed yarn.lock then I tested again and it worked!. You may have a try deleting yarn.lock. Maybe yarn requires git in certain dependencies declared in yarn.lock

**Comment by Acidic9** [comment]
I'm not able to fix it :/ I've tried deleting my yarn lock files, that didnt work.. I also tried removing the shell-script=bash in my .npmrc file but that wasnt even there.

**Comment by zakrodionov** [comment]
Is this problem still relevant?

**Comment by Toby222** [comment]
Also experiencing this. Happened after installing PowerShell 7.

**Comment by rayepps** [comment]
I may have a solid reproduction of this. I was just throwing a function I use often into its own package and I did the normal setup but ran into this issue where yarn can't find items installed and existing in the .bin dir.

### Issue
This is the test script I usually use
```
c8 inforce --targetPath ./test
```
<img width="598" alt="Screen Shot 2020-12-25 at 11 52 47 PM" src="https://user-images.githubusercontent.com/15269623/103146847-4bb0f500-470c-11eb-902d-4ab0d4d3f2b7.png">

I double checked the `node_modules/.bin` dir exists and contains all the files it should. Kind of prove this below with the work around.

### Workaround
This is the workaround I'm having to go with for now.
```
./node_modules/.bin/c8 ./node_modules/.bin/inforce --targetPath ./test
```

You can see -- and hopefully reproduce -- [here](https://github.com/rayepps/radcli).

### The Deets
- yarn version:  1.22.10
- OS: Mac OS X - Catalina - 10.15.7

**Comment by UpasnaGandhi** [comment]
Thank You @richardsengers for short answer 👍 I am beginner and this helped me. I was struggling from last 2 days. @shabith For sharing the issue details with the link. That helps.

**Comment by adnanfajlur** [comment]
done

**Comment by abdulfatahhamidah** [comment]
the problem with mine is when i try to add script-shell, later it becomes unrecognizeable then i got the same issue "couldn't fine the binary", 
I already solve the problem by remove the script-shell config using `yarn config delete script-shell`

**Comment by Jefdeniel** [comment]
Had this issue after installing Playwright in my React project. 

When i tried to run `npm exec playwright test`  i got the **"Couldn't find the binary"**

But when running` npm exec playwright test`, everything worked.

**Comment by sgd2z** [comment]
> Had this issue after installing Playwright in my React project.
> 
> When i tried to run `yarn exec playwright test` i got the **"Couldn't find the binary"**
> 
> But when running` npm exec playwright test`, everything worked.

I'm having this same problem.

**Comment by debdutdeb** [comment]
just chiming in, same issue happening with webpack binary. nothing more to add im afraid for now. symptoms the same as others. idk what to try to provide more info.

**Comment by Huaoe** [comment]
I had this problem also ;) 

why can't I use npx ?

The issue with npx on Windows is related to how it handles script execution and path resolution. Let's verify the npx installation and try to diagnose the specific issue:

Ran terminal command
c:/Users/thoma/Desktop/WorkspacesToken/blockchain-real-estate
> where npx

Stdout
CopyInsert
C:\Program Files\nodejs\npx
C:\Program Files\nodejs\npx.cmd
Let me check your npm configuration:

Ran terminal command
c:/Users/thoma/Desktop/WorkspacesToken/blockchain-real-estate
> npm config list

Stdout
CopyInsert
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\thoma\\AppData\\Roaming\\npm"

; "user" config from C:\Users\thoma\.npmrc

script-shell = "="

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.10.0
; npm local prefix = c:\Users\thoma\Desktop\WorkspacesToken\blockchain-real-estate
; npm version = 10.9.0
; cwd = c:\Users\thoma\Desktop\WorkspacesToken\blockchain-real-estate
; HOME = C:\Users\thoma
; Run `npm config ls -l` to show all defaults.
Ah! I found the issue. In your npm configuration, there's a problematic setting:

Code
CopyInsert
script-shell = "="
This is causing the ENOENT error we saw earlier. Let's fix this by removing this incorrect configuration:

Ran terminal command
c:/Users/thoma/Desktop/WorkspacesToken/blockchain-real-estate
> npm config delete script-shell
