### ISSUE TITLE
'yarn global update' being aborted

### ISSUE THREAD

**Issue by The-BigDaddy** [yarnpkg/yarn#6051]
## What's happening

Running `yarn global update` gives this output 

``` 
 1: node::Abort() [node]
 2: 0x556f80c7df18 [node]
 3: 0x556f80cb08c0 [node]
 4: uv__work_done [/usr/lib/libuv.so.1]
 5: 0x7f3e361ee6f4 [/usr/lib/libuv.so.1]
 6: uv__io_poll [/usr/lib/libuv.so.1]
 7: uv_run [/usr/lib/libuv.so.1]
 8: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [node]
 9: node::Start(int, char**) [node]
10: __libc_start_main [/usr/lib/libc.so.6]
11: _start [node]
zsh: abort      yarn global upgrade

```
## Expected behaviour

For it to work.

## Relevant versions

Node.js version: 9.10.0
Yarn version: 1.8.0
libuv version: 1.21.0
Linux Kernel version: 4.16.14
Zsh version: 5.5.1

**Comment by Daniel15** [comment]
Hmm, this sounds like a Node.js issue rather than a Yarn issue... I'm not sure how Yarn could possibly crash Node.js like that. Is there any output other than that stack trace?

**Comment by The-BigDaddy** [comment]
@Daniel15 well there's this

    node[28819]: ../src/node_file.cc:329:void node::{anonymous}::After(uv_fs_t*): Assertion `0 && "Unhandled eio response"' failed.

But yeah. Looks like **another** one of those Node fuck ups. That or it's just  this version of Node not being compatible with this version of libuv.

**Comment by Daniel15** [comment]
Hmm, this is the assertion that's being hit: https://github.com/nodejs/node/blob/v9.10.0/src/node_file.cc#L328-L329

My guess here is that your libuv version is newer than what your Node.js version supports. I don't think this is a Yarn issue though, so I'm going to close this out. Please feel free to let us know if you still see it even on the latest Node.js, or with whatever version of libuv was supplied with the older Node.js version.
