### ISSUE TITLE
ETIMEDOUT  http://ynpm-registry.corp.yahoo.com

### ISSUE THREAD

**Issue by kriswill** [yarnpkg/yarn#6052]
**What is the current behavior?**
ETIMEDOUT error to http://ynpm-registry.corp.yahoo.com 

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn add @ember/test-helpers`
```
yarn install v1.7.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "http://ynpm-registry.corp.yahoo.com/@ember/test-helpers/-/test-helpers-0.7.18.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kris/src/oss/ember-mocha/yarn-error.log".
```

**What is the expected behavior?**
yarn downloads the module

**Please mention your node.js, yarn and operating system version.**
* yarn v1.7.0
* node lts/carbon v8.11.3
* macOS High Sierra v10.13.5

**Comment by BYK** [comment]
Looks like an internal network issue to me.
