### ISSUE TITLE
Workspace naming

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/yarn#6056]
It was, in my opinion, good to be able to name our workspaces as desired.

`workspace-aggregator-36ba4ab5-b782-418e-8ac0-59867326c3a7` can be `@my-monorepo`

**Comment by arcanis** [comment]
The aggregator is an implementation detail. It will be renamed into something static in the next release, but we don't plan to allow to configure it.

**Comment by bertho-zero** [comment]
Is there anything new about this?

**Comment by hedefalk** [comment]
I see this a lot and its really bloating my logs. Couldn't it just be something else, package name?
