### ISSUE TITLE
Homebrew latest version is still 1.7.0

### ISSUE THREAD

**Issue by vfonic** [yarnpkg/yarn#6061]
`brew info  yarn` outputs this:

> yarn: stable 1.7.0
JavaScript package manager
https://yarnpkg.com/
Conflicts with:
  hadoop (because both install `yarn` binaries)
/usr/local/Cellar/yarn/1.7.0 (14 files, 4.2MB)
  Built from source on 2018-07-03 at 15:08:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb

From what I can see in this repo, latest stable yarn release is 1.8.0.
The official docs for macOS suggest to use brew (as first option) to install yarn:
https://yarnpkg.com/en/docs/install#mac-stable

Would be good to keep that installation method up-to-date.

Thanks! <3

**Comment by phip1611** [comment]
Hi!
As you can see here v1.8.0 is only _pre-release_. Also v1.8.0 has at least one bug that at least make it's unusable for our project. Just wait for v1.8.1 or v1.9.0! Also https://yarnpkg.com/lsays latest version is 1.7.0.

**Comment by vfonic** [comment]
Ah, I had no idea v1.8.0 is a pre-release.

I'm not used to minor version increases to be pre-releases. I guess it
makes sense.

**Comment by Daniel15** [comment]
Yeah, currently we don't push RC/prerelease versions to Homebrew. You can install RC versions using the instructions on the site.

**Comment by abdelkrimdev** [comment]
Hello!! According to Yarn's official website, 1.9.2 is the latest stable version.
I think it's time to update homebrew's formulae 🙂

**Comment by vivekchauhan** [comment]
@abdelkrimdev The formulae is updated in brew with version 1.9.2

**Comment by kapoko** [comment]
I had to do a reinstall of yarn to get it to update (macOS). 

I ran `npm uninstall -g yarn` and `brew uninstall yarn` (didn't remember how I installed it). Then ran `brew install yarn`.

**Comment by mesqueeb** [comment]
@kapoko So weird, even after `npm uninstall -g yarn` and `brew uninstall yarn` it still says i have yarn version 1.3.2 on `yarn -version`. Do you have any advice?

**Comment by Daniel15** [comment]
@mesqueeb Try `whereis yarn` and see which version of Yarn is being used. Perhaps you installed it both via the installation script **and** via Homebrew.

**Comment by mesqueeb** [comment]
@Daniel15 Thanks! I found the problem.
I had it installed 1 time via Homebrew **and** one time via `npm -g i` hahaha

**Comment by msarit** [comment]
@kapoko you are a *life-saver*!!!
I ran `brew uninstall --force yarn`, `brew uninstall --force node`, `nvm uninstall yarn` and `nvm uninstall node`
Then I installed node and yarn using nvm.
`create-react-app` is working perfectly now 🤩
