### ISSUE TITLE
What kind of glob strings does nohoist setting accept?

### ISSUE THREAD

**Issue by szimek** [yarnpkg/yarn#6088]
The only official info about `nohoist` setting that I can find is at https://yarnpkg.com/blog/2018/02/15/nohoist/ and while it's pretty good at explaining what it's for, it's pretty vague when it comes to what options are available.

What are possible options to e.g.:
- disable hoisting completely for all packages
- disable hoisting of *all* dependencies (including their dependencies and so on) for a specific package
- disable hoisting of *all* dependencies (including their dependencies and so on) of a specific dependency in a specific or any package
- disable hoisting of a specific dependency (without its own dependencies) in a specific or any package

?

**Comment by JKillian** [comment]
https://github.com/yarnpkg/yarn/issues/5833 is the best discussion I've seen so far, not sure if it's up to date or not though

**Comment by huchenme** [comment]
Yeah I hope #5833 could be reopened, it will be good to be able to disable hoisting for a whole package

**Comment by paul-soporan** [comment]
Closing this as we've dropped support for `noHoist` in v2 (which was also a bit buggy with globs) in favor of [installConfig.hoistingLimits](https://yarnpkg.com/configuration/manifest#installConfig.hoistingLimits) which doesn't use globs.

https://yarnpkg.com/getting-started/migration
