### ISSUE TITLE
PLEASE I KEEP GETTING 'NODE_ENV' is not recognized as an internal or external command, operable program or batch file when i try to start yarn

### ISSUE THREAD

**Issue by sijixx** [yarnpkg/yarn#6090]
`  info Project commands
   - gen-schema-types
      ts-node src/scripts/createTypes.ts
   - start
      NODE_ENV=development nodemon --exec ts-node src/index.ts
   - test
      NODE_ENV=test jest --watch
question Which command would you like to run?: start
$ NODE_ENV=development nodemon --exec ts-node src/index.ts
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by lolmaus** [comment]
Running into the same issue on Windows inside a `mintty` terminal.

I've got the following entry in my `package.json`'s `scripts` section:

```
"test": "EMBER_CLI_MODULE_UNIFICATION=true MODULE_UNIFICATION=true ember test"
```

When I run `EMBER_CLI_MODULE_UNIFICATION=true MODULE_UNIFICATION=true ember test` directly, it works fine.

But when I run `yarn test`, I receive:

```
$ yarn test
yarn run v1.12.3
$ EMBER_CLI_MODULE_UNIFICATION=true MODULE_UNIFICATION=true ember test
'EMBER_CLI_MODULE_UNIFICATION' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Please mark this issue as a bug.

**Comment by BYK** [comment]
@sijixx if you want you issue to be paid attention to, please use a more descriptive and short title for your issue. Also please provide more details in a manner that a person other than you looking at the issue doesn't have to spend extra effort to figure out what is going on. @lolmaus' comment is a good example for these.

@lolmaus this looks like yarn using `cmd` as its task runner at all times which I think was done by @arcanis some time recently for compatibility and consistency reasons. You may want to try the `script-shell` option implemented for #4248 and see how it goes.

**Comment by lolmaus** [comment]
@BYK Thank you for pointing at `script-shell`.

I found a2a0544 to be lacking documentation or usage guidelines. I can't figure out how to use the feature, even when looking at a test in the commit. CC @yunyu 

At the same time, I found #6728 which seems to be related and is unresolved.

OK, I've managed to update `script-shell`, which should be done either with `npm config set script-shell <value>` or by editing the `.npmrc` file.

I've managed to make it execute with the following:

```
script-shell="\"C:\\Program Files\\git\\bin\\bash.exe\""
```

Unfortunately, it still doesn't work! Instead of 

> 'EMBER_CLI_MODULE_UNIFICATION' is not recognized as an internal or external command, operable program or batch file.

I now receive:

> error Couldn't find the binary EMBER_CLI_MODULE_UNIFICATION=true MODULE_UNIFICATION=true ember test

Please advise.

**Comment by yunyu** [comment]
The config option behaves exactly the same as it does with npm (hence the lack of documentation). It looks like you have too many quotes: https://stackoverflow.com/questions/23243353/how-to-set-shell-for-npm-run-scripts-in-windows

**Comment by lolmaus** [comment]
@Yunyu, without exra quotes it says something like "`C:\Program` not found".

**Comment by yunyu** [comment]
@lolmaus Does the same setting work with npm?

**Comment by lolmaus** [comment]
> @lolmaus Does the same setting work with npm?

No, it doesn't. With npm I have an equivalent error.

I hope you don't use that as an excuse to ignore this problem in Yarn.

It may be an upstream issue with Node, in that case we must find it and track it.

Or it may be just that both Yarn and npm fail to correctly employ env vars on Windows, and a fix should be applied to both.

**Comment by lolmaus** [comment]
OK, found this: https://github.com/kentcdodds/cross-env

Looks like this issue can be closed. It's definitely an upstream issue, and `cross-env` seems to be a convenient workaround.
