### ISSUE TITLE
Poor performance at scale in PackageInstallScripts#findInstallablePackage

### ISSUE THREAD

**Issue by AlexLandau** [yarnpkg/yarn#6105]
Background: I work on a large proprietary monorepo (~100 packages) using Yarn Workspaces. Recently, we've run into an issue where our `yarn install` command spends more than four minutes (over half its runtime) in step 5 of the build ("Building fresh packages"). Under ordinary circumstances, I'd expect most of our time to be spent in step 4 and very little in step 5.

Profiling indicates that nearly all of this time is being spent not in a renegade dependency's install scripts, as I originally guessed, but rather in `findInstallablePackage` (in package-install-scripts.js), specifically in calls to `detectCircularDependencies` from that method. When I add logging, it seems that the following pattern occurs in `findInstallablePackage` when this is run:

* Initially, most of the packages in `workQueue` are immediately installable.
* However, occasionally I get a package that is not installable, and for which `detectCircularDependencies` returns false. When this happens, the method finds another package to return, but _leaves the blocking package at the head of the "queue"_.
* Each subsequent attempt to get a package from the queue goes through the uninstallable package, rerunning the `detectCircularDependencies` check every time.
* The number of packages stuck at the head of the queue in this way grows over time, to as many as 85 in our case, before it decreases very late in the build process.

The result is that while `workQueue` starts with only 2831 values, we end up running `detectCircularDependencies` 76047 times (not counting recursive invocations) and taking over 200 seconds to do so. It's understandable that `detectCircularDependencies` is somewhat CPU-intensive, but the queue logic results in calling it way too many times.

There are a number of possible ways to fix this. Some of my own ideas:

* Change `workQueue` from a Set to an actual queue with an ordering preserved between calls to `findInstallablePackage`. When we test the package at the head of the queue and it is not yet installable, move it to the end of the queue. (Alternatively, move it to a second queue that we switch to when the first queue becomes empty, which would be more confusing but still allow the use of Set objects.)
* Do a cycle-aware topological sort of the dependencies ahead of time.
* Instead of having cycle checking give a yes-or-no result, have it return an uninstalled transitive dependency of the given project unless a cycle exists. (This is like an on-the-fly topological sort.) This would require some restructuring of how it's called currently.

I'm not sure what approach would fit best with the larger parallelized model here.

I'm running yarn 1.8.0 on Node v9.10.0 and OS X 10.13.6. I have also reproduced this issue in 1.7.0. The code that looks relevant appears to be at least two years old.

**Comment by AlexLandau** [comment]
On further examination, we are already (mostly) topologically sorting the dependencies ahead of time, which explains why this isn't a problem more of the time.

It does look like we start to accumulate a "clog" in the queue while we wait for dependencies to have their install scripts run. It would help to mark these as "blocked" in the interim and skip them without running the circular dependencies check. I think I see a good way to do so and plan to open a PR.

**Comment by AlexLandau** [comment]
For additional color, the most likely reason we're seeing this in our repo when we're seeing it (and not elsewhere or earlier) is that we have many projects using webpack 3 and many more using webpack 4. Since they can't both be hoisted (the way yarn workspaces currently works), this in turn causes lots of locations where certain dependencies that use post-install scripts are installed.

**Comment by GabiGrin** [comment]
Hey @AlexLandau! We're just encountering this issue on our project and your comments are very helpful, so thanks for that!
Would love to know if you have found anything new on this regard the last couple of years :) 
Did you consider using one of the 2 version in https://github.com/yarnpkg/yarn/pull/5970 or https://github.com/yarnpkg/yarn/pull/6257 to mitigate this?

**Comment by AlexLandau** [comment]
Hi @GabiGrin, yes, we are still using an internal fork of Yarn with that PR to mitigate this.

I haven't investigated this much since then, though when I have tried baseline Yarn again, the impact of this bug seems to be reduced (perhaps 1 minute rather than 5-10). I suspect this is due to changes in our codebase rather than changes in Yarn. In particular, we've become more disciplined about using the same version of Webpack and other dependencies across our projects. We use [monorepolint](https://github.com/monorepolint/monorepolint) to enforce that (though those options are not well-documented).

**Comment by GabiGrin** [comment]
thanks @AlexLandau!
I tested your fork and it did wonders to us too - 3-4x improvement 🚀 
```
Attempt 1
Running yarn-local
Took 49 seconds
Running official yarn
Took 190 seconds
Attempt 2
Running yarn-local
Took 51 seconds
Running official yarn
Took 179 seconds
Attempt 3
Running yarn-local
Took 48 seconds
Running official yarn
Took 168 seconds
```
Thanks for the tip on monorepolint, we'll check that too!

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
