### ISSUE TITLE
Add option to disable running random package.json scripts after package install

### ISSUE THREAD

**Issue by ArcticZeroo** [yarnpkg/yarn#6107]
**Do you want to request a *feature* or report a *bug*?**

It's kind of both, I think?

**What is the current behavior?**
When yarn installs a package with `yarn add`, it also seems to run other arbitrary and (to my knowledge) undocumented npm scripts. For instance, I have one called "prepare" which runs my babel and submodule update scripts in order to prepare the webserver files for a release. I'm getting errors from that for some reason, and yarn thinks my entire install failed because of it.

**If the current behavior is a bug, please provide the steps to reproduce.**

Make a package.json with scripts named "build", "update", and "prepare". At least one will be run when you `add` any module.

**What is the expected behavior?**
None of them run! Yarn shouldn't just run random commands from my package.json, especially in an undocumented way, especially because a user migrating from NPM (like myself) has no idea what's going on.

**Please mention your node.js, yarn and operating system version.**
This isn't really relevant to this, but yarn is v1.7

**Comment by paul-soporan** [comment]
Closing as this doesn't happen anymore in v2.

https://yarnpkg.com/getting-started/migration
