### ISSUE TITLE
Yarn kills Hyper.app

### ISSUE THREAD

**Issue by bevacqua** [yarnpkg/yarn#611]
I did:

```bash
npm i -g yarnpkg
```

Then when running this:

```bash
yarn
```

Hyper.app stopped responding. I've been otherwise using HyperTerm without any major hassle.

**Comment by kittens** [comment]
We aren't doing anything too weird. Seems like this is a bug in Hyper.app rather than us. We're outputting ANSI escape codes and emoji which may cause an issue with it somewhere? Do you have any logs generated by Hyper.app handy? Happy to take a look.

**Comment by bevacqua** [comment]
It might be an issue with Hyper.app, they had an open PR about unicode for a while now.

https://github.com/zeit/hyper/pull/214

**Comment by montogeek** [comment]
Couldn't reproduce it on Hyper 0.8.1 and create-react-app repo

**Comment by bevacqua** [comment]
I ran it on a pretty large internal project

**Comment by montogeek** [comment]
That should be. This is what Hyper logs while `yarn` is running:
```
2 Unknown OSC code: "1337" bundle.js:35506 
2 Unknown OSC code: "133" bundle.js:35506 
```

**Comment by bevacqua** [comment]
This belongs in the Hyper repo, moved to https://github.com/zeit/hyper/issues/858

**Comment by iam4x** [comment]
@kittens after some investigation, it only happens if you install `$ yarn` with the curl script, if you install with `$ npm i -g yarn` it just works as expected. See https://github.com/zeit/hyper/issues/858#issuecomment-253078634
