### ISSUE TITLE
Yarn installation fails with no error

### ISSUE THREAD

**Issue by errorx666** [yarnpkg/yarn#6112]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
`yarn install` exits with code 0, with no error message, without finishing.  The progress bar is still showing when it exits, at 0% progress.  The yarn.lock file is not updated.

The output is as below:
```
yarn install v1.8.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > ngx-auto-scroll@1.1.0" has incorrect peer dependency "@angular/core@^5.0.0".
warning " > ngx-auto-scroll@1.1.0" has incorrect peer dependency "@angular/common@^5.0.0".
warning " > ngx-auto-scroll@1.1.0" has incorrect peer dependency "rxjs@^5.5.2".
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/2489
```

Note the progress bar says 0/2489

**If the current behavior is a bug, please provide the steps to reproduce.**

This does not happen on every machine.  There is no error message or error log to post.  Even with `yarn install --verbose --trace`, I see no errors or warnings.
The tail of the output printed by `verbose` is: 
```
verbose 22.599 Removing extraneous file "C:\\Users\\user\\Documents\\src\\r3\\node_modules\\@angular-devkit\\build-optimizer\\node_modules\\.bin".
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/2489
```

clone https://github.com/errrorx666/r3/
yarn install

**What is the expected behavior?**
Yarn finishes installing dependencies and updating the lock file.

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v10.6.0
$ yarn -v
1.8.0
```
Windows 10 Professional x64

**Comment by errorx666** [comment]
By naively inserting console.log statements in the cli.js file, I was able to determine the last place the code reaches is this `if` block. (Console lines stop printing after it.)

https://github.com/yarnpkg/yarn/blob/ed76c6a8979983049dce409b735a051091fe61b7/src/package-linker.js#L467-L487

**Comment by errorx666** [comment]
OK, so, my debugging finds that the `cmdShim` function takes 3 parameters and returns a promise.  However, when it is called, it is given 2 parameters and promisified (unnecessarily), which causes the third paramter, `opts`, to be a callback function.
The callback given by promisify is ignored, so it never returns.

**Comment by rally25rs** [comment]
closing this since it's fixed by a now-merged PR.
