### ISSUE TITLE
yarn licenses list --silent broke between 1.6.0 and 1.7.0

### ISSUE THREAD

**Issue by rjmunro** [yarnpkg/yarn#6127]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`yarn licenses list --silent` produces no output (except warnings on stderr if applicable).

**What is the expected behavior?**

`yarn licenses list --silent` should produce the same output as `yarn licenses list`, except without the `yarn licenses v[version]` prefix and `Done in [time]s.` suffix lines, as it did in yarn 1.6.0.

I run `yarn licenses list` regularly on CI and output the results to a file. If the file changes I know I need to review the new licenses. But with this new behaviour, I can't use --silent, and the file changes all the time due to the 'Done in' time being slightly variable due to network conditions etc. I also don't want to have to change it when yarn updates.

**Please mention your node.js, yarn and operating system version.**

* Node: 8.9.1 (installed with nvm)
* Yarn 1.7.0, 1.8.0 (installed with installation script)
* Mac OS sierra 10.12.6

**Comment by rjmunro** [comment]
I've done some testing with git-bisect, and found the problem was introduced here: https://github.com/yarnpkg/yarn/pull/5722

It looks like a bit of thought is needed to define output that is informational and should be suppressed with `--silent` and critical to the command making any sense, that should not be.

**Comment by arcanis** [comment]
The way we do this in `log` is by adding a `force: true` option (https://github.com/jxom/yarn/blob/93a6c1be1c2b7038217ffcc934499c18af97680a/src/reporters/console/console-reporter.js#L165). The same would need to be implemented for the tree command. Would you like to open a PR? 😃
