### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by bckbmath** [yarnpkg/yarn#6136]
**Which operating system are you using:**
ubuntu 16.04

**Please describe the steps you took when trying to install Yarn and what went wrong:**
sudo apt-get install  yarn

N: Ignoring file 'yarn.listsudo' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
(Reading database ... 504739 files and directories currently installed.)
Preparing to unpack .../archives/yarn_1.7.0-1_all.deb ...
Unpacking yarn (1.7.0-1) ...
dpkg: error processing archive /var/cache/apt/archives/yarn_1.7.0-1_all.deb (--unpack):
 trying to overwrite '/usr/bin/yarn', which is also in package cmdtest 0.22-1
Errors were encountered while processing:
 /var/cache/apt/archives/yarn_1.7.0-1_all.deb
N: Ignoring file 'yarn.listsudo' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Sub-process /usr/bin/dpkg returned an error code (1)

It has installed version 0.22 not 1.7

**Comment by bckbmath** [comment]
Detailed errors from the package manager follow:

apt transaction returned result exit-failed

**Comment by Daniel15** [comment]
Two problems:
1. Rename `/etc/apt/sources.list.d/yarn.listsudo` to `yarn.list`:
```
N: Ignoring file 'yarn.listsudo' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
```

2. Uninstall `cmdtest`:
```
trying to overwrite '/usr/bin/yarn', which is also in package cmdtest 0.22-1
```
