### ISSUE TITLE
yarn fails in installation

### ISSUE THREAD

**Issue by kedar9444** [yarnpkg/yarn#6142]
[3/5] Fetching packages...
error An unexpected error occurred: "http://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz: connect ECONNREFUSED 104.16.17.35:80".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Work\\Project Experiments\\ng-bootstrap\\ng-bootstrap\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

this is the error message i am getting on console.

**Comment by indy-singh** [comment]
We are seeing the same behaviour random intermittent failures since the beginning of the week. We have tested against all of the http://104.16.xxx.xxx IPs and they all failure intermittently..?

**Comment by mipapo** [comment]
Just set `yarn config set registry https://yarn.npmjs.org` - worked fine so far. But an explanation why this problem happens would be great

**Comment by DanielRuf** [comment]
Well, it seems the http version of npmjs has issues. It is recommended to use the https endpoint in general. This is related to the infrastructure of npmjs (Cloudflare), not yarn (which uses a proxy to npmjs).

**Comment by paul-soporan** [comment]
Closing as this is an external registry issue.
