### ISSUE TITLE
Installation Problem: Cannot install with Node version != '6.0'

### ISSUE THREAD

**Issue by CodingNagger** [yarnpkg/yarn#6144]
Hi, I tried to install yarn but got met with an error about Node not being installed, or more precisely Node '6.0' not being installed. Please find my configuration and the steps I followed below:

Config: Windows 10 64bits, with Node v8.11.1

- I tried to install yarn using the command `choco install yarn`
- I got the following: 
![image](https://user-images.githubusercontent.com/18394737/43135504-8f1b8b54-8f3d-11e8-828c-e79263576723.png)

**Comment by DanielRuf** [comment]
What is in the logfile?
Also why do you run this in a system directory?

**Comment by CodingNagger** [comment]
Was on an load laptop I don't have anymore, ran as an admin. Didn't reproduce since so closing.
