### ISSUE TITLE
"fixtures" directories

### ISSUE THREAD

**Issue by luisapace** [yarnpkg/yarn#6145]
Hi,
my team would like to use yarn-1.5.1 at https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-v1.5.1-cd316572.tar.gz and to approve that I've to analyze it's source code and the code of its dependencies chain, to be sure that they don't have problematic licenses.

Now some code and dependencies come from directories "fixtures".

Could you please tell me if what is valid for the buildpacks and specified at:
cloudfoundry/binary-buildpack#21
is also applicable to yarn-1.5.1 and its distribution at https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-v1.5.1-cd316572.tar.gz?

Thank for your help.

**Comment by arcanis** [comment]
I don't know what is buildpack. Our fixtures directory only contain files not used in the final bundle, though.

**Comment by luisapace** [comment]
Ok thanks, could you please clarify the use of those files for my knowledge?

**Comment by arcanis** [comment]
We just use Yarn to install what's inside those directory in order to test that Yarn is able to install them properly, as part of our release process. This avoids us accidentally breaking something.

**Comment by luisapace** [comment]
perfect, thanks again.
