### ISSUE TITLE
Yarn start dont run the project

### ISSUE THREAD

**Issue by josesuarezcordova** [yarnpkg/yarn#6157]
Hi all

I'm experimenting a blocker issue working with Yarn, on theme folder I run 

`yarn start`

and seems ok , I getting this

```
[Browsersync] Proxying: http://editoffice.dev
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.37:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.37:3001
 -------------------------------------
[Browsersync] Watching files...
```

but the browser just try to load the Website and dont get success

http://192.168.1.37:3000

the 3001 is working fine

this is the script 

 "start": "NODE_ENV=development webpack --watch --progress --hide-modules",

I ran already  yarn install

and this is the package.json

`
{
  "scripts": {
    "start": "cd web/app/themes/editoffice/src && yarn start",
    "build": "cd web/app/themes/editoffice/src && yarn run build",
    "install": "composer install && cd web/app/themes/editoffice/src && yarn install",
    "install-quiet": "composer install --quiet --no-interaction && cd web/app/themes/editoffice/src && yarn install",
    "start-vagrant": "vagrant up",
    "stop-vagrant": "vagrant halt",
    "morning": "yarn start-vagrant && yarn start",
    "evening": "yarn stop-vagrant",
    "staging:build": "cd web/app/themes/editoffice/src && yarn build:staging",
    "staging:rsync": "rsync -rlzvc --stats --exclude-from '.rsync-ignore' -e 'ssh -p 18765' ./ editoffi@em259.sgded.com:~/www/staging",
    "staging:cleanup": "rsync -rlzvc --stats --existing --ignore-existing --delete --include-from '.rsync-cleanup' -e 'ssh -p 18765' ./ editoffi@em259.sgded.com:~/www/staging",
    "staging:update_assets_versions": "curl -w '\n' http://staging:edit2017@staging.editoffice.eu/wp/wp-admin/admin-ajax.php?action=update_assets_versions",
    "production:build": "cd web/app/themes/editoffice/src && yarn build:production",
    "production:rsync": "rsync -rlzvc --stats --exclude-from '.rsync-ignore' -e 'ssh -p 18765'  ./ editoffi@em259.sgded.com:~/www/editoffice.eu",
    "production:cleanup": "rsync -rlzvc --stats --existing --ignore-existing --delete --include-from '.rsync-cleanup' -e 'ssh -p 18765' ./ editoffi@em259.sgded.com:~/www/editoffice.eu",
    "production:update_assets_versions": "curl -w '\n' http://editoffice.eu/wp/wp-admin/admin-ajax.php?action=update_assets_versions",
    "test-site:rsync": "rsync -rlzvc --stats --exclude-from '.rsync-ignore' -e 'ssh -p 18765'  ./ editoffi@em259.sgded.com:~/www/test.editoffice.eu",
    "test-site:cleanup": "rsync -rlzvc --stats --existing --ignore-existing --delete --include-from '.rsync-cleanup' -e 'ssh -p 18765' ./ editoffi@em259.sgded.com:~/www/test.editoffice.eu",
    "test-site:update_assets_versions": "curl -w '\n' http://test.editoffice.eu/wp/wp-admin/admin-ajax.php?action=update_assets_versions"
  },
  "devDependencies": {
    "rimraf": "^2.6.2"
  }
}

`
I just taking this project from another developer but I cant reproduce the project locally yet. another thing , where should be the config.js ?? I been reading some post with same issue but I cant find the solution yet, someone else that could give me some advice please, thanks!

**Comment by DanielRuf** [comment]
The start script seems to run another start script.

This is an issue with your project and not yarn.

**Comment by rally25rs** [comment]
Yarn is running your start script. The issue looks like it is with your script or with browsersync.
