### ISSUE TITLE
Support for multiple root workspaces

### ISSUE THREAD

**Issue by pronebird** [yarnpkg/yarn#6160]
Hi,

Currently workspace system allows only one root workspace. With this limitation it's impossible to have multiple targets sharing packages between each other.

It would be great to have support for multiple root workspaces. For instance this can be done by allowing root workspaces to reference packages in the file hierarchy above, i.e:

- `packages/`
    - `package-a`
    - `package-b`
    - `package-c`
- `targets/`
     - `target-a` – a workspace that includes `package-a` and `package-c`
     - `target-b` – a workspace that includes `package-b` and `package-c`

My use case includes building multiple apps that share some packages between each other.

**Comment by arcanis** [comment]
What prevents you from making a workspace that contains multiple apps? Instead of multiple apps that each are a workspace.

**Comment by pronebird** [comment]
The problem is that the root workspace will have a blend of dependencies from all of the packages. Including fat packages like electron and react-native. This deteriorate the overall performance when installing packages, `postinstall` compilations and so on. Apart from that this creates another problem of bundling the right dependencies with each of the apps.

**Comment by Gudahtt** [comment]
It looks like the problem you're facing is also outlined in this issue: https://github.com/yarnpkg/yarn/issues/4521

They discuss different workarounds in that issue as well, such as using bundlers.

The feature request is a bit different from yours, but I believe it's intended to solve the same problem.

**Comment by pronebird** [comment]
@Gudahtt 

>I didn't have the other two problems you mentioned though; performance or postinstall complications. Could you elaborate those two issues? Personally I found install performance to be somewhat better after switching to workspaces, presumably due to the hoisting of shared dependencies between each project.

I have a setup with electron app and react-native app, both use shared react components package too, so three packages so far. 

Since there is no way to have multiple root workspaces, I am forced to use one root workspace and list all of the packages in it.

Now when I run `yarn install`, it pulls all dependencies for all packages mentioned in the root workspace.

Even if I only would like to work on a desktop app, I need to wait for mobile deps to be installed, and vise versa.

I do rebuild binaries against Electron in `postinstall` script, otherwise this is not gonna work. Some dependencies have prebuilt binaries downloaded from remote server instead. All of this happens on `yarn install`.

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Comment by darron1217** [comment]
@merceyz Can you explain us how v2 can solve this issue?

**Comment by merceyz** [comment]
It supports installing parts of the tree using `workspaces focus` https://yarnpkg.com/cli/workspaces/focus

**Comment by darron1217** [comment]
@merceyz Got it, thanks :)
