### ISSUE TITLE
Release 1.9.x on Homebrew

### ISSUE THREAD

**Issue by voxpelli** [yarnpkg/yarn#6164]
As 1.9.2 is now the latest release according to https://yarnpkg.com/en/ and according to announcements it would be neat to have that in Homebrew as well, but as far as I can see Homebrew is still stuck on 1.7.0 and with no PR:s or such open to update that.

See: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb

**Comment by Daniel15** [comment]
@arcanis Did you not use the 'bump RC to stable' button for this release?

**Comment by arcanis** [comment]
Nope, there was a 401 token error (sent you the details on messenger)

**Comment by Daniel15** [comment]
Oh okay. I'll look at that once I'm back from vacation.

PR is already open to bump Homebrew:
https://github.com/Homebrew/homebrew-core/pull/30537
