### ISSUE TITLE
RPM repository is out of date

### ISSUE THREAD

**Issue by johnmuhl** [yarnpkg/yarn#6165]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn` warns about an outdated version being used.

> warning Your current version of Yarn is out of date. The latest version is 
> "1.9.2", while you're on "1.7.0".
> info To upgrade, run the following command:
> $ sudo yum install yarn

Running the mentioned command does not install the latest version.

~~~
$ sudo dnf install yarn
...
Package yarn-1.7.0-1.noarch is already installed, skipping.
~~~

~~~
$ dnf info yarn
Name         : yarn
Version      : 1.7.0
...
~~~

**If the current behavior is a bug, please provide the steps to reproduce.**

~~~
$ sudo dnf install yarn
$ yarn --version
1.7.0
~~~

**What is the expected behavior?**

~~~
$ sudo dnf install yarn
$ yarn --version
1.9.2
~~~

**Please mention your node.js, yarn and operating system version.**

~~~
$ node --version
v8.11.3

$ yarn --version
1.7.0

$ uname -a
Linux 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~~~

**Comment by arcanis** [comment]
Thanks! This release should come soonish, we have some issues with marking the package as stable on homebrew / rpms (#6164)

**Comment by Daniel15** [comment]
Should be okay now. There's some issues with the build infra that I'll need to look at once I'm back from vacation.
