### ISSUE TITLE
yarn.lock file contains absolute path for local packages added using file://

### ISSUE THREAD

**Issue by arindamdat** [yarnpkg/yarn#6166]
**Do you want to request a *feature* or report a *bug*?**

May be a bug or may be improvement
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Say you have following project structure

 app/
 &nbsp;&nbsp;└── package.json
 &nbsp;&nbsp;└── index.js
 libraries/
 &nbsp;&nbsp;└── interfaces/
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└──package.json
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└──index.js
 &nbsp;&nbsp;└──authorization/
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└──package.json
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└──index.js

Here I have two local packages namely "interfaces" and "authorization". The "authorization" package is dependent on the package "interfaces". The package.json of "authorization" package looks like
> "dependencies":{
>   "interfaces": "file:../interfaces"
> }

 "authorization" package is being used in "app". The package.json of "app" looks like

> "dependencies":{
>   "authorization": "file:../libraries/authorization"
> }

If I look at the yarn.lock file of the app, it contains entry like

> "authorization@file:../libraries/authorization":
>   version "1.0.0"
>   dependencies:
>     interfaces "file:C:/Users/my_user/AppData/Local/Yarn/Cache/v1/interfaces"

**What is the expected behavior?**
I expected yarn.lock to not contain any absolute path. It's causing change in yarn.lock file in different developer's machine.

**Please mention your node.js, yarn and operating system version.**

> $ node -v
> v8.10.0

> $ yarn -v
> 1.5.1

> OS: Windows 10

**Comment by arcanis** [comment]
I suspect it would be complex to change this behavior, because of the workspaces (plus, it could break things).

I would probably suggest you to use workspaces instead of the `file:` protocol - they should solve the same use case, but better.

**Comment by mmiller42** [comment]
Local file resolution can be important, especially in cases where some of your code is open source and another part of the application is in a private repository. The `file:` protocol is a great way to symlink everything.

It would be cool if this could be overridden with a cli flag/.yarnrc and preserve relative paths. Otherwise there would need to be some way of specifying `"resolutions"` in the local environment's package.json without checking it in while also re-`yarn`ing.

**Comment by arcanis** [comment]
The v2 actually supports this use case. We simply add a package identifier to locate the relative root of the path in the resolution.

**Comment by paul-soporan** [comment]
Closing as this has been fixed in the v2.

https://yarnpkg.com/getting-started/migration
