### ISSUE TITLE
Can I replace bower with yarn ?

### ISSUE THREAD

**Issue by warpdesign** [yarnpkg/yarn#617]
The [announcement post](https://code.facebook.com/posts/1840075619545360) says that yarn can be used with bower workflows: can it replace bower as well?

How? The documentation doesn't seem to mention bower migration.

**Comment by kittens** [comment]
Hey! Thanks for the question. We're still in the process of ironing out how the integration between npm and bower actually works. Suffice to say, you should be able to run `yarn install` from inside of a directory with `bower.json` and have it install all dependencies and work as you'd expect!

**Comment by panuhorsmalahti** [comment]
You need to use yarn in flat mode with `yarn install --flat`.

**Comment by warpdesign** [comment]
@kittens doesn't seem to work.

I have both bower.js & package.json in the same directory. Running `yarn` from this directory installs npm packages but not bower ones.

**Comment by dsschnau** [comment]
@panuhorsmalahti  `yarn install --flat` didn't seem to do anything with bower deps. (though it did install `node_modules` flatly.

**Comment by mattbucci** [comment]
Doesn't seem to be any documentation around this either at this time, although it is mentioned in the blog post.

![screen shot 2016-10-11 at 9 43 42 am](https://cloud.githubusercontent.com/assets/3284147/19279759/91fd4c7e-8f97-11e6-9544-81df891dbecf.jpg)

**Comment by NamPNQ** [comment]
@warpdesign Workarround, just rename the `package.json` and run `yarn` :dancer:

**Comment by panuhorsmalahti** [comment]
@dsschnau, sorry, I kinda misunderstood this issue, I thought it was about how to replace bower by using the npm registry - which is what the `--flat` flag can be use for.

**Comment by slbug** [comment]
Will be useful to have ability to install packages from package.json and bower.json at the same time.

**Comment by jonathanong** [comment]
i would like a feature/option to only install `bower.json` so that i can ditch `bower`. replacing npm with yarn would be a separate step for me, but that's lower priority for me as npm isn't as broken as bower :P

**Comment by omnisite** [comment]
If you add the following to package.json, bower install will be called and it works. It is a workaround though:

   ` "scripts": {
        "postinstall": "bower install"
    }`

**Comment by bennyp123** [comment]
@dsschnau This affects Polymer workflows with yarn when certain dependencies are required.
e.g.
## bower.json
```json
dependencies: {
  "app-localize-behavior": "PolymerElements/app-localize-behavior#^0.9.2"
}
```
`yarn install --flat` fails to install intl-messageformat, which app-localize-behavior depends on

**Comment by tony19** [comment]
@bennyp123 `intl-messageformat` is actually installed under `node_modules` (due to #715). See [workaround](https://github.com/yarnpkg/yarn/issues/715#issuecomment-255949620).

**Comment by wyze** [comment]
Bower support has been dropped in #1441.

**Comment by warpdesign** [comment]
@wyze is it planned for later or definitely dropped ?

The idea of using Yarn for both npm & bower sounded a good idea to me.

**Comment by wyze** [comment]
I am not sure what the future plans are. I think there will be a roadmap released eventually that will give more clarity.

**Comment by alextreppass** [comment]
Support for bower was removed, see #1441.

**Comment by graingert** [comment]
@warpdesign 

> Bower is on it's way out and we shouldn't be supporting it.

and

> bring over the features they like from Bower to Yarn (such as flat install which we already have and other unimplemented features like svn support etc).

However the bower package registry is not going to be used.

**Comment by warpdesign** [comment]
@graingert Ok. Fair enough.

**Comment by hickscorp** [comment]
As @omnisite mentioned, `"scripts": { "postinstall": "bower install" }` in your npm task does the trick. We use `bower-locker` to have proper semantic dependency locking, and it's all shiny!

**Comment by mvasilkov** [comment]
Rest in pepperoni, sweet feature.

Such sad.

**Comment by qknight** [comment]
can someone point out alternatives then? or should one still stick to `bower` at the time being?

**Comment by graingert** [comment]
`yarn install --flat` or yarn with webpack

**Comment by m0k1** [comment]
https://medium.com/@andrejsabrickis/bye-bye-bower-or-how-to-migrate-from-bower-to-npm-and-webpack-4eb2e1121a50

Meybe this post can help you about migrating from bower ...

**Comment by nbonamy** [comment]
I am sticking to yarn as a bower replacement for the moment and solved all this by:

1. Removing @bower_components prefix on all components
2. Properly split devDependencies and dependencies (so front-end ones)
3. Set the postinstall script to "node install.js"
4. Install.js being https://gist.github.com/nbonamy/7019b7a42e7e53dee2a587590a164c39. The root const needs to be adjusted to your setup.

If that can help anyone...
