### ISSUE TITLE
1.9.2: Scoped Registries are being ignored

### ISSUE THREAD

**Issue by clintwood** [yarnpkg/yarn#6174]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

EDIT: This seems limited to `yarn global ...`

Since a recent (via my distro) update to `yarn 1.9.2`, scoped registry config set in `.yarnrc` or `.npmrc` are no longer being respected/used.
  
**If the current behavior is a bug, please provide the steps to reproduce.**
1) Use `config set` to set a scoped registry by running either one of the following:
```bash
$ npm config set @myscope:registry http://my.private.registry.com
# or
$ yarn config set @myscope:registry http://my.private.registry.com
```
2) Try adding a package from your scoped registry:
```bash
$ yarn global add @myscope/my-private-package
```
3) You'll get an error message that says:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@myscope%2fmy-private-package: Not found".`

**What is the expected behavior?**

It should install the package from your private registry set for the scoped package.  In this example it should use `http://my.private.registry.com` not `https://registry.yarnpkg.com`.

**Please mention your node.js, yarn and operating system version.**

node: 10.7.0
yarn: 1.9.2
Elementary OS Loki (Ubuntu 16.04)

**Comment by fenduru** [comment]
This is also affecting `yarn create`

**Comment by arcanis** [comment]
Fixed in the 1.9.4, now available! Let me know if that fixes the issue for you 🙂

**Comment by hbetts** [comment]
@arcanis the release notes for `1.9.4` do not indicate any changes to the package manager - https://github.com/yarnpkg/yarn/releases/tag/v1.9.4

Could those please be updated to indicate that this issue has been addressed?

**Comment by arcanis** [comment]
As mentioned in the release notes for the 1.9.4, it's only been released because of our release process. Please refer to the release notes for the 1.9.3 for the actual changes 🙂 

https://github.com/yarnpkg/yarn/releases/tag/v1.9.3

**Comment by fenduru** [comment]
@arcanis this gets past the original issue, however now `yarn create @scope/package` fails as it attempts to execute `C:\Users\me\AppData\Local\Yarn\bin\@scope\package` however the binary got installed to `AppData\Local\Yarn\bin\package`
