### ISSUE TITLE
Invoking yarn with invalid flag does not fail

### ISSUE THREAD

**Issue by tony-sunny** [yarnpkg/yarn#6179]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Invoking yarn from command line with an invalid flag  does not fail. But it does yarn install and creates yarn.lock file

**If the current behavior is a bug, please provide the steps to reproduce.**

- Run yarn with an invalid flag(Ex: `yarn --foo`).
- No error is shown instead yarn install command is run

**What is the expected behavior?**
Invalid flags should throw error. Atleast, it should not do yarn install

**Please mention your node.js, yarn and operating system version.**
Node - 8.7
yarn - 1.9,2
OS - Ubuntu 16.04

**Comment by rally25rs** [comment]
duplicate #2600

This is an issue with commanderjs which yarn is using to process args. There is an initiative to move to yargs instead, which will hopefully resolve this issue as well as several others that deal with command line args.
