### ISSUE TITLE
Make 1.9.2 release available on Chocolatey

### ISSUE THREAD

**Issue by altano** [yarnpkg/yarn#6187]
**What is the current behavior?**
1.7.0 is the latest version in the Chocolatey repo but yarn is on version 1.9.2. This results in a warning I have to ignore:
> warning Your current version of Yarn is out of date. The latest version is "1.9.2", while you're on "1.7.0".

**What is the expected behavior?**
`choco upgrade yarn` upgrades yarn to 1.9.2 instead of 1.7.0.

Is the automation still broken, @Daniel15 ? (https://github.com/yarnpkg/yarn/issues/5866)

**Comment by Daniel15** [comment]
Sorry, it looks like there's still some issues with the automation, and I was on vacation. I'll look into it, but for now I manually pushed the new package. It'll be available shortly, once approved.

**Comment by altano** [comment]
Awesome, thanks Daniel.
