### ISSUE TITLE
Windows installer needs Authenticode signature

### ISSUE THREAD

**Issue by sideris** [yarnpkg/yarn#619]
I think that either the CA is not compatible, or it is self - signed certificate

**Comment by Daniel15** [comment]
Yeah I think we need to get an Authenticode certificate to sign the installer.

Facebook has internal infra for Authenticode signing but I'm not sure if it's appropriate for signing open-source stuff. We could just get our own cert.

**Comment by Daniel15** [comment]
I'm investigating this.

**Comment by Daniel15** [comment]
This is done and #1999 will automate it for future builds.
