### ISSUE TITLE
Example package used in a test is marked as "insecure" by GitHub

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/yarn#6191]
The following package.json version of `hawk` has a vulnerability:

https://github.com/yarnpkg/yarn/blob/18b103c81828c1c862e9e095212ea4467f154e51/__tests__/fixtures/upgrade/respects-ignore-engines-flag/package.json#L1-L5

Should we change the test to update that dependency to a version which won't complain about the security anymore, or should we ignore the warning?

**Comment by Haroenv** [comment]
relevant test is this one: 

https://github.com/yarnpkg/yarn/blob/18b103c81828c1c862e9e095212ea4467f154e51/__tests__/commands/upgrade.js#L126-L132

**Comment by arcanis** [comment]
Opened #6194 to fix it - the code wasn't executed anyway but this way we'll avoid further warnings.
