### ISSUE TITLE
Material-design-icons package times-out every time when installing with yarn

### ISSUE THREAD

**Issue by PaulNegoescu** [yarnpkg/yarn#6192]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
material-design-icons package times out every time but works on npm.
[yarn-error.log](https://github.com/yarnpkg/yarn/files/2249111/yarn-error.log)

**If the current behavior is a bug, please provide the steps to reproduce.**

yarn add material-design-icons
Wait for this to timeout

**What is the expected behavior?**
It should install the package

**Please mention your node.js, yarn and operating system version.**
Windows 10
yarn 1.7.0
node 10.1.0

**Comment by rally25rs** [comment]
duplicate #5540
