### ISSUE TITLE
Yarn Workspace No Hoist

### ISSUE THREAD

**Issue by pizzarob** [yarnpkg/yarn#6203]
Yarn 1.7.0
Node v8.9.0

Using `"nohoist": ["**/shared-webpack-2"]`  - all dependencies of shared-webpack-2 are hoisted and added to the root node_modules

**Comment by bertho-zero** [comment]
```js
"nohoist": [
  "**/shared-webpack-2",
  "**/shared-webpack-2/**"
]
```
