### ISSUE TITLE
Package in node_modules not updated

### ISSUE THREAD

**Issue by aldarund** [yarnpkg/yarn#6205]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Sometime when i change package version in my package.json ( i have strict version specified e.g. "nuxt-edge": "2.0.0-25552561.fceb30b" ) and then yarn it update lock file to new version, but actual package version in node_modules remains previous one and next runs of yarn just says all up to date.

**If the current behavior is a bug, please provide the steps to reproduce.**
It doesnt happen every time, but it happen pretty often. On different packages.

**What is the expected behavior?**
Package get actually update in node_modules too.

**Please mention your node.js, yarn and operating system version.**
Node 10.0.7. Yarn 1.9.2  ( was happening in previous versions too). Windows 10.

**Comment by arcanis** [comment]
We'll need a reproduction, otherwise it'll be hard to solve it.

**Comment by aldarund** [comment]
@arcanis it dont happen on reliable manner to be reproducible at wish. One install it could happen, other install it will be fine. Could happen for several minor versions change for a package. There nothing special in my package.json , just strict versions that changes 

Maybe there some logs that I could enable that will help ?

**Comment by aldarund** [comment]
actually it seems like my IDE  ( WebStorm) somehow caches files in node modules and while actual files on disk is new one, ide opens old ones. I close this one and open bug in webstorm
