### ISSUE TITLE
yarn create @scope doesnt work as expected

### ISSUE THREAD

**Issue by iamstarkov** [yarnpkg/yarn#6233]
**What is the current behavior?** it is also steps to reproduce

```
## create doesnt recognise scope without "/"
☯ yarn create @scope
yarn create v1.9.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/create-: Not found".

## create recognise scope with "/", but adds unnecessary "-" in the end
☯ yarn create @scope/
yarn create v1.9.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@scope%2fcreate-: Not found".
```

**What is the expected behavior?** npm's one is an expected behaviour

```
☯ npm init @scope
npm ERR! code E404
npm ERR! 404 Not Found: @scope/create@latest
```

**Please mention your node.js, yarn and operating system version.**

```
darwin 17.7.0
Node.js v8.11.3
yarn 1.9.4
```

**Comment by arcanis** [comment]
I don't think we ever supported `@scope/create`, but I agree it would make sense. Want to open a PR? It should be fairly easy to change the logic in `src/cli/commands/create.js` 🙂

**Comment by iamstarkov** [comment]
from here https://yarnpkg.com/blog/2017/05/12/introducing-yarn/
<img width="960" alt="screen shot 2018-08-06 at 9 11 52 pm" src="https://user-images.githubusercontent.com/559321/43736292-5fa86006-99bd-11e8-951a-ae712acbf7eb.png">

**Comment by iamstarkov** [comment]
@arcanis sure, pull-request is almost ready

**Comment by iamstarkov** [comment]
@arcanis unfortunately there are not existing tests for create command. is it okay to submit fix without tests?

**Comment by arcanis** [comment]
That should be fine for `create` - iirc the reason there is none is that it was a pain to test it since it's spawning another process.

**Comment by iamstarkov** [comment]
@arcanis PR is ready for review #6239
