### ISSUE TITLE
yarn registry began rejecting HEAD requests

### ISSUE THREAD

**Issue by bdwain** [yarnpkg/yarn#6237]
This is more of a process question, so I'm not using the standard issue template. 

At my job we use a private internal registry (made with artifactory) that points to the yarn registry and mirrors public packages (and also hosts our private packages). It recently began having issues getting the latest versions of some packages. 

We eventually tracked it down to the fact that the yarn registry recently began rejecting HEAD requests, which our registry was making as part of the process to get the latest versions of packages. We were able to fix it by disabling the HEAD requests, but I wanted to ask if rejecting HEAD requests was an intentional change? And if so, is there a place where we can look in the future to see recent registry changes if we're trying to debug issues on our end?

Thanks!

**Comment by arcanis** [comment]
The Yarn domain name simply is an indirection to the npm registry. We haven't changed anything in our infra, so it's likely they did.

**Comment by bdwain** [comment]
Ah got it. Thanks!
