### ISSUE TITLE
Can not remove tag of current module

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/yarn#6238]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

When I am in my module I can not remove a tag with `yarn tag remove`.

**What is the expected behavior?**
The tag should be deleted, `git tag` still shows it.

**Please mention your node.js, yarn and operating system version.**
10.8.0
1.9.4
Windows 10

**Comment by Gudahtt** [comment]
I don't think that command is supposed to do that. `yarn tag remove` should remove a distribution tag, not a git tag. These are aliases for a published version of your package (e.g. in the npm registry). They are not the same thing as git tags.

See here: https://yarnpkg.com/lang/en/docs/cli/tag/

**Comment by DanielRuf** [comment]
Ah now I understand. The command name is a bit confusing imho.

**Comment by Gudahtt** [comment]
Yeah, I can understand that. The equivalent command in `npm` is `dist-tag`, which does make it a bit more clear.

**Comment by DanielRuf** [comment]
> Yeah, I can understand that. The equivalent command in npm is dist-tag, which does make it a bit more clear.

Sorry, I guess I should read the docs next time. I hope I did not cost too much time. I was just confused by similar commands but different meanings (git tag vs yarn tag) and I think it was a bit late when I created the issue.

**Comment by Gudahtt** [comment]
No problem, don't worry about it. It's helpful to know which commands are confusing. I'm sure others have made that same mistake.
