### ISSUE TITLE
Should yarn run ignore .cmd files for binary scripts on Windows?

### ISSUE THREAD

**Issue by insin** [yarnpkg/yarn#624]
Example for v0.15.1:

![cmd_2016-10-11_17-01-43](https://cloud.githubusercontent.com/assets/226692/19278460/2fbd70aa-8fd5-11e6-9de8-6506ecf302be.png)

**Comment by cpojer** [comment]
Shall we just skip anything that ends with `.cmd`?

**Comment by Daniel15** [comment]
On Windows we should probably *only* show the `.cmd` files, stripping the extension. The extensionless ones are shell scripts which aren't used on Windows.

**Comment by tiagolascasas** [comment]
Me and my colleagues will attempt to provide an implementation of this small feature in the following days.

**Comment by vlad-zhukov** [comment]
Windows 10 has a native Bash support and runs extensionless scripts just fine.

**Comment by olingern** [comment]
I'd like to close this unless anyone all feels that this feature adds a lot of value for windows users.
