### ISSUE TITLE
Latest Debian package installing 1.9.2 instead of 1.9.4

### ISSUE THREAD

**Issue by joesiewert** [yarnpkg/yarn#6243]
**Do you want to request a *feature* or report a *bug*?**
Bug 🐛

**What is the current behavior?**
Latest Debian package installing 1.9.2 instead of 1.9.4

**If the current behavior is a bug, please provide the steps to reproduce.**

```
sudo apt-get update
sudo apt-get install yarn

After this operation, 45.1 kB of additional disk space will be used.
Get:1 https://dl.yarnpkg.com/debian/ stable/main yarn all 1.9.2-1 [684 kB]
Fetched 684 kB in 0s (2,660 kB/s)
(Reading database ... 285810 files and directories currently installed.)
Preparing to unpack .../archives/yarn_1.9.2-1_all.deb ...
Unpacking yarn (1.9.2-1) over (1.5.1-1) ...
Setting up yarn (1.9.2-1) ...
```

**What is the expected behavior?**
Latest version 1.9.4 is installed

**Please mention your node.js, yarn and operating system version.**
Ubuntu 14.04

**Comment by Daniel15** [comment]
Oops! That's my fault, I forgot to re-enable the cronjob that updates it after fixing #6168. It should be fixed now.

**Comment by Daniel15** [comment]
Fixed in https://github.com/yarnpkg/releases/commit/94a6f5635b886cc3ccfb43a6f7adfd78d16c9d10

**Comment by joesiewert** [comment]
Thanks @Daniel15! 🚀
