### ISSUE TITLE
yarn add global problem with nvm and zsh

### ISSUE THREAD

**Issue by mandaputtra** [yarnpkg/yarn#6245]
**Which operating system are you using:**

Linux Mint 19 Tara (Ubuntu Based)
NVM 0.33.11
node 10.8.0
npm 6.2.0
yarn 1.9.4
zsh 5.4.2

**Please describe the steps you took when trying to install Yarn and what went wrong:**

So in installation guide it says `sudo apt-get install --no-install-recommends yarn` if using `nvm`. But when installing global package `yarn global add @vue/cli` or anything package that install globaly it always says `zsh: command not found: vue`

**Is installation succesful?**
Yes sure no problem

**try export `yarn global bin`to your PATH?**
Yes sure, not fix it 

```
$  yarn global bin
$ /home/myusername/.yarn/bin
```

I export it, but i got error message, `Yarn need nodejs 4.0 or higher` I just ignore the message do `yarn global add @vue/cli`

still not fix it.

**use --prefix to place it on bin**

Okay, got this error

```
➜  ~ yarn global bin
/home/putrapc/.yarn/bin
➜  ~ yarn global add @vue/cli --prefix /usr/local
yarn global v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[-----------------------------------------------------------------------] 0/620(node:13859) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-client@2.3.7" has incorrect peer dependency "graphql@^0.11.0 || ^14.0.0".
[4/4] Building fresh packages...
success Installed "@vue/cli@3.0.0-rc.11" with binaries:
      - vue
error Cannot create "/usr/local/bin/vue" due to insufficient permissions.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
➜  ~ vue
zsh: command not found: vue
➜  ~ 
```

Sould i run it with sudo?

**what about npm?**

try add global module in npm and its works perfectly, dont know why.

**Comment by neulaender** [comment]
exactly the same problem here: With Archlinux and zsh. But I tried Bash, too.

**Comment by IljaN** [comment]
Same problem with fish on Xubuntu

**Comment by sbaudray** [comment]
Same here with Ubuntu 18.04 and node installed via asdf.

If i run `yarn global add bs-platform`, it installs ok but says `Cannot create "/usr/local/bin/bsb" due to insufficient permissions.`

If i run the same command with sudo, it says `Yarn need nodejs 4.0 or higher`

**Comment by mandaputtra** [comment]
Close due to some improvement on update, work after setup some path.

**Comment by Akiyamka** [comment]
Why it closed? How to resolve that?
