### ISSUE TITLE
Yarn hangs at "Fetching Packgaes" on last package while installing Signal-Desktop

### ISSUE THREAD

**Issue by adimit** [yarnpkg/yarn#6246]
**Do you want to request a *feature* or report a *bug*?**

Bug report. 

**What is the current behavior?**
Using this repository: https://github.com/signalapp/Signal-Desktop at tag `v1.14.4` saying `yarn install` runs fine, but at tag `v1.15.0` (and above) the yarn process hangs indefinitely.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/signalapp/Signal-Desktop
cd Signal-Desktop
git checkout v1.15.3
yarn install
```

Result is:

```
yarn install v1.9.4
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[##################################################################################################################################################################################] 1520/1521
```

It hangs there. Since I'm assuming the folks at Signal actually test their builds, it seems to be a problem with my installation of yarn? Or maybe some particular combination of node/yarn/OS. It smells like a race condition :confused:

Strace is here: https://gist.github.com/adimit/580a40e6c52bc4fb494e39e559ee983b
This is from the last status update, until I kill the process. It hangs indefinitely. I can also provide strace output from earlier in the execution, but the complete file is around 3MB.

**Important**: The offending package is
```
"@journeyapps/sqlcipher": "https://github.com/scottnonnenberg-signal/node-sqlcipher.git#ed4f4d179ac010c6347b291cbd4c2ebe5c773741"
```
(from `package.json`.) If I delete that package (and only that package) the fetching packages step does run through (but actually building the application does not, obviously.)

**Please mention your node.js, yarn and operating system version.**

* Fedora Linux 28
* node v8.11.3
* yarn v1.9.4

There are related bugs in the tracker, but they all seemed to have a weird resolution to them. I don't have a VPN, I'm using the main NPM registry. If there's something I can tweak about my setup, please let me know.

**Comment by adimit** [comment]
Addendum: removing the explicit commit hash from the above dependency fixes the problem. It seems that this is a specific problem with the commit hash (on this package? There is no other package in the dependency list that has a commit hash.)

**Comment by ghasemikasra39** [comment]
same here:
```
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[###############################################################################################] 1908/1909
```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 192.86 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - ~/Documents/youpendo-app-bareworkflow/node_modules/.bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.8.0 => 4.9.0
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

```

**Comment by paul-soporan** [comment]
Closing as fixed in v2 - the improved timeout and retry logic makes it a lot less susceptible to this kind of issues.

https://yarnpkg.com/getting-started/migration
