### ISSUE TITLE
Yarn installation problem

### ISSUE THREAD

**Issue by pavani507** [yarnpkg/yarn#6250]
**Which operating system are you using:**
MacOs

**Please describe the steps you took when trying to install Yarn and what went wrong:**
Brahmas-MacBook-Pro:~ brahma$ brew install yarn
-bash: brew: command not found
Brahmas-MacBook-Pro:~ brahma$ brew install yarn --without-node
-bash: brew: command not found
Brahmas-MacBook-Pro:~ brahma$ sudo port install yarn
Password:
sudo: port: command not found
Brahmas-MacBook-Pro:~ brahma$ export PATH="$PATH:`yarn global bin`"
-bash: yarn: command not found
Brahmas-MacBook-Pro:~ brahma$ yarn --version
-bash: yarn: command not found

**Comment by indraakkk** [comment]
are you already installed homebrew for your machine?

**Comment by paul-soporan** [comment]
Closing as unactionable.
