### ISSUE TITLE
reinstall of onetime package replaces https with http

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/yarn#6259]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**
The package URL for onetime is changed to http://

```
onetime@^1.0.0:
  version "1.1.0"
  resolved "http://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz#a1f7838f8314c516f05ecefcbc4ccfe04b4ed789"

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Have `onetime` in a project.  
Reinstall all deps (remove node_modules and yarn.lock).

**What is the expected behavior?**
Yarn should not change https to http.

**Please mention your node.js, yarn and operating system version.**
node: 10.8.0
yarn: 1.9.4

**Comment by oriSomething** [comment]
Same here:
![screen shot 2018-08-30 at 8 56 25](https://user-images.githubusercontent.com/2685242/44832218-9dc3d780-ac32-11e8-987f-2581ba880519.png)

**Comment by DanielRuf** [comment]
@oriSomething is there a .npmrc in your project?

Interesting, in your screenshot the new URL is switched from yarnpkg to npmjs.

**Comment by oriSomething** [comment]
No.

I have `.npmrc` in the home directory. I suspect there is no connection because this it the content:
```
color=false
```

**Comment by oriSomething** [comment]
I think it might be an **npm** issue instead of Yarn.
From `package-lock.json`:

<img width="644" alt="screen shot 2018-08-30 at 22 37 38" src="https://user-images.githubusercontent.com/2685242/44874943-693d3380-aca5-11e8-9eb8-0d513dc3513b.png">

**Comment by oriSomething** [comment]
and https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/3

**Comment by DanielRuf** [comment]
https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/6

Ouch, still no https enforced. This allows MitM and other attacks which manipulate the packets.

So it is (still) an issue with the npmjs backend.

But Yarn does the same thing:
http://registry.yarnpkg.com/ does not redirect to https which is bad (security wise).
