### ISSUE TITLE
dependency is listed as direct dependency

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/yarn#6260]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**
Wrong dependency path
```
yarn list v1.9.4
└─ onetime@1.1.0
✨  Done in 0.97s.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Install `download@^4.0.0` or any other module which uses `onetime`.
Run `yarn list --pattern=onetime`

**What is the expected behavior?**
Yarn should show the right dependency path.

**Please mention your node.js, yarn and operating system version.**
yarn 1.9.4
node 10.8.0

**Comment by pronebird** [comment]
Do you expect to see the dependency tree?

I am able to get the correct dependency tree for instance for core-js

```
yarn list --pattern=core-js
yarn list v1.9.4
├─ core-js@2.5.7
├─ fbjs@0.8.17
│  └─ core-js@1.2.7
└─ react-native@0.56.0
   └─ core-js@1.2.7
```

**Comment by DanielRuf** [comment]
> Install download@^4.0.0 or any other module which uses onetime.

Did you try that? Does this produce the same output on your computer?

**Comment by pronebird** [comment]
Yeah super weird. `each-async` has `onetime` in its deps so `yarn list` shows that:

```
├─ each-async@1.1.1
│  ├─ onetime@^1.0.0
│  └─ set-immediate-shim@^1.0.0
```

But `yarn list --pattern` doesn't.

**Comment by mix4242** [comment]
Still an issue with yarn 1.12.3.
