### ISSUE TITLE
updating cache folder does not work if the pre-existing location does not exist

### ISSUE THREAD

**Issue by EvaLok** [yarnpkg/yarn#6273]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

trying to set a valid cache path gives the following error if the previous cache path is currently invalid:

> error An unexpected error occurred: "EACCES: permission denied, mkdir '/this/path/no/longer-exists'".
> info If you think this is a bug, please open a bug report with the information provided in "/home/user/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/config for documentation about this command.

**If the current behavior is a bug, please provide the steps to reproduce.**

with a config file that looks like this:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


cache-folder "/this/path/no/longer-exists"
"https://registry.npmjs.org/" true
lastUpdateCheck 1534191818011
network-timeout "60000"
```

```bash
yarn config set cache-folder /a/path/that/exists
```

**What is the expected behavior?**
should set the new cache path regardless of whether the previous path is currently valid or not?

**Please mention your node.js, yarn and operating system version.**

```
# uname -a
Linux eva 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# node -v
v8.9.0

# yarn -v
1.7.0
```

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
