### ISSUE TITLE
Fontawesome 5.2.0 version not available

### ISSUE THREAD

**Issue by mrshiva009** [yarnpkg/yarn#6276]
Iam working on fontawesome v5.1.0-3 ,while trying to upgrade to version 5.2.0 with yarn it's not upgrading.
Can u let us know how to upgrade fontawesome version to 5.2.0

**Comment by arcanis** [comment]
Can't do anything unless you share a repro.

**Comment by mrshiva009** [comment]
Thank , but i found it out the issue is has changed the package names with versions also to get the updated version we need to  request the new package like @fortawesome/fontawesome for 5.1.0-3(old)
@fortawesome/fontawesome-svg-core for 5.2.0(new)

**Comment by rally25rs** [comment]
@mrshiva009 does that mean that this issue can be closed?

**Comment by mrshiva009** [comment]
yes @rally25rs
