### ISSUE TITLE
yarn just ignores typos

### ISSUE THREAD

**Issue by basel-shishani** [yarnpkg/yarn#6282]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Yarn does not complain about typos in command line, eg.
yarn list --patern xyz 
just prints the full list as if no CLI option was provided.
**If the current behavior is a bug, please provide the steps to reproduce.**

yarn list --patern xyz 

**What is the expected behavior?**
Typos should produce errors!

**Please mention your node.js, yarn and operating system version.**
node  8.11.4 - yarn 1.9.4 - Ubuntu 16.04.5

**Comment by rally25rs** [comment]
duplicate #2600

commander.js is what ignores them. There is a plan to move to yargs instead for the next major version of yarn.
