### ISSUE TITLE
Force pushing a non fast forward commit to a git dependency breaks yarn install

### ISSUE THREAD

**Issue by bs85** [yarnpkg/yarn#6289]
Version: 1.9.4

Steps to reproduce:

- `yarn add https://github.com/your-account/your-repo`
- force push a non fast forward update to your-repo
- `yarn`

#### Current Behavior

From the looks of it, yarn is using the previous cloned repo and doing a form of `git pull` inside it. If the history of master is non fast forward, then the pull returns with an exit code 1, and the whole yarn command fails

#### Expected Behavior

If `git pull` returns non zero, delete the cache entry and do a full clone

**Comment by bs85** [comment]
Looks like it works with 1.12.4

**Comment by dmatora** [comment]
Still an issue on 1.22.17
