### ISSUE TITLE
--frozen-lockfile is not failing as expected when a change is required from within a workspace

### ISSUE THREAD

**Issue by Gudahtt** [yarnpkg/yarn#6291]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When running `yarn install --frozen-lockfile` from a project using Yarn workspaces, the command will complete successfully without throwing an error, even if an update to the lockfile is required due to a dependency within a workspace.

**If the current behavior is a bug, please provide the steps to reproduce.**

@devrelm has created a repository to reproduce the problem: https://github.com/devrelm/frozen-lockfile

**What is the expected behavior?**

`yarn install --frozen-lockfile` should throw an error if an update to the lockfile is required.

**Please mention your node.js, yarn and operating system version.**

Yarn v1.9.4 (also tested with v1.0.0)
Node.js v8.1.11.3
Windows 10 build 17134.228

**Comment by epmatsw** [comment]
Possibly the same as https://github.com/yarnpkg/yarn/issues/4098

**Comment by paul-soporan** [comment]
Closing as this has been fixed in v2.

https://yarnpkg.com/getting-started/migration
