### ISSUE TITLE
Warning: Resolution field "[pkg]@7.x.x" is incompatible with requested version "[pkg]@^6.x.x

### ISSUE THREAD

**Issue by brettdewoody** [yarnpkg/yarn#6301]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
With the following `devDependencies` and `resolutions`:

```
"devDependencies": {
  "postcss": "^7.0.1",
  "postcss-cli": "^6.0.0",
  "postcss-import": "^11.1.0",
  "postcss-preset-env": "^5.3.0"
},
"resolutions": {
  "postcss": "7.0.1"
}
```
upon `yarn install` there are multiple warnings along the lines of:

```
Resolution field "postcss@7.0.1" is incompatible with requested version "postcss@^6.x.x"
```

because the other packages deps require `postcss@^6.x.x`.

**What is the expected behavior?**

No warnings.

All packages are requesting `postcss@^6.x.x` and we've set a resolution of `postcss@7.0.1`, which satisfies the requested version of `postcss@^6.x.x`.  

**Please mention your node.js, yarn and operating system version.**
* node 8.11.0 
* yarn 1.9.4
* MacOS 10.13.4

**Comment by rally25rs** [comment]
>  we've set a resolution of postcss@7.0.1, which satisfies the requested version of postcss@^6.x.x

I'm not entirely sure what the purpose of that warning is, but just wanted to point out that it does not satisfy the range:

```
~/Projects/yarn-test 🐒   node
> const semver = require('semver');
undefined
> semver.satisfies('7.0.1', '^6.x.x')
false
```

so I think that warning is just letting you know that your resolution doesn't satisfy the originally requested range, which of course could cause an issue at runtime.

**Comment by brettdewoody** [comment]
@rally25rs So even though `7.0.1` is > `6.x.x` it doesn't fall within the `^6.x.x` range?
