### ISSUE TITLE
SSL handshake failure

### ISSUE THREAD

**Issue by iamdanfox** [yarnpkg/yarn#631]
When running `yarn` at work, I hit the following error:

```
yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
error write EPROTO 140735253005056:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:../deps/openssl/openssl/ssl/s23_lib.c:177:

    at exports._errnoException (util.js:1036:11)
    at WriteWrap.afterWrite (net.js:794:14)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

If it's at all relevant, we have an internal npm mirror (defined in the `.npmrc` file).  One other guess is that this is failing due to internal TLS-decryption.

```
registry = https://<someinternalurl>/artifactory/api/npm/all-npm/
```

yarn -V: 0.15.1
Mac 10.10.5 (14F1912)
node v6.7.0

**Comment by Daniel15** [comment]
Do you have a legitimate SSL cert on your internal server, or is it a self-signed cert?

Can you `wget` a file from that server?

**Comment by iamstarkov** [comment]
@Daniel15 if its self-signed cert, what should i do?

**Comment by iamstarkov** [comment]
@Daniel15 if its self-signed cert, what should i do?

**Comment by BagelTheKid** [comment]
I'm receiving the same issue when trying to install any package. 
I'm behind a corporate proxy that has a self-signed cert. I've set strict-ssl to false in my npm settings, I'm unsure if that will affect Yarn's config.

**Comment by Daniel15** [comment]
@iamstarkov and @BagelTheKid - One option is to set the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0`. This disables TLS checking for **all** calls performed from the Node.js process.  On Mac OS and Linux, you can run Yarn like this:
```
NODE_TLS_REJECT_UNAUTHORIZED=0 yarn install
```


However, for a corporate proxy, I'd strongly suggest for your sysadmin to use a real certificate. They could use an internal CA and have its root cert preinstalled on computers that are on the corporate network (this is what we do for internal servers at Facebook).

**Comment by kittens** [comment]
We've merged support for `cafile` and `strict-ssl` so this issue should be resolved.
