### ISSUE TITLE
yarn global upgrade wants lockfile

### ISSUE THREAD

**Issue by pruett** [yarnpkg/yarn#6320]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
```bash
$ yarn global upgrade

yarn global v1.9.4
error Outdated lockfile. Please run `yarn install` and try again.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
$ yarn global upgrade
```

**What is the expected behavior?**
Outdated files within `yarn global list` would be updated

**Please mention your node.js, yarn and operating system version.**
```bash
$ node -v
v10.9.0

$ yarn --version
1.9.4

$ uname -a
Darwin _ 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Comment by pruett** [comment]
the following seemed to work. not sure if this is good practice though

```fish
$ cd (yarn global dir)
$ rm -rf node_modules yarn*
$ yarn
$ yarn global upgrade
```

**Comment by herrbischoff** [comment]
Just wanted to add that I ran into the same issue today. Doing

```fish
# fish shell

cd (yarn global dir)
$ yarn install
$ yarn global upgrade
```

without remove `node_modules` solved the issue for me. Clearly, this issue still exists.

**Comment by stevemarksd** [comment]
even today...

**Comment by Slapbox** [comment]
Running `yarn install` instead of `yarn` maybe fixed the issue, even though it's supposed to be an alias. Perhaps we just needed to run `yarn` multiple times before the issue would resolve.

**Comment by awwright** [comment]
Could you reopen this please? At the very least, the workaround should be documented somewhere. Ideally, the underlying problem shouldn't ever happen; an outdated lockfile is completely irrelevant if I'm trying to upgrade all of my packages anyways.
