### ISSUE TITLE
Support for custom resource allocation policy 

### ISSUE THREAD

**Issue by vikas14118** [yarnpkg/yarn#6324]
Is it possible to define a custom policy for resource allocation such that RM decides a particular NodeManager to assign a job in a greedy manner? I have a yarn cluster Up and want the resources to be allocated in a greedy manner such that the jobs coming to RM should be assigned to only one NM and when it no longer able to handle more jobs, RM start submitting jobs to next NM.

**Comment by arcanis** [comment]
Wrong project, we have nothing to do with Apache Hadoop YARN.
