### ISSUE TITLE
ERROR:  connect ETIMEDOUT 85.222.153.141:443.

### ISSUE THREAD

**Issue by koitache** [yarnpkg/yarn#6326]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by ajhool** [comment]
Could you please include details in this issue?

**Comment by paul-soporan** [comment]
Closing as v2 has greatly improved the timeout logic.

https://yarnpkg.com/getting-started/migration
