### ISSUE TITLE
consider using `cross-env` for `scripts`

### ISSUE THREAD

**Issue by ianstormtaylor** [yarnpkg/yarn#6329]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Right now, to use environment variables safely on Mac/Windows/Linux we have to use hacks like the `cross-env` helper in `scripts`. But seeing as `scripts` are an attempt to have a place for cross-platform scripts already, and they already offer magic like looking in `./node_modules/.bin`, it seems like it would be really nice to handle this for people.

**What is the expected behavior?**

Instead of having to do:

```js
{
  "devDependencies": {
    "cross-env": "^5.1.3",
  },
  "scripts": {
    "build": "cross-env NODE_ENV=production rollup ..."
  }
}
```

Just being able to do:

```js
{
  "scripts": {
    "build": "NODE_ENV=production rollup ..."
  }
}
```

**Comment by paul-soporan** [comment]
Closing as v2 now uses a portable cross-platform shell that enables this exact use case by default.

https://yarnpkg.com/getting-started/migration
