### ISSUE TITLE
Self Signed Certificate Error With Yarn Add Command 

### ISSUE THREAD

**Issue by AlexMachin1997** [yarnpkg/yarn#6333]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When "yarn add" is issued I get a self-signed certificate error 

**If the current behavior is a bug, please provide the steps to reproduce.**
Download the reccomended version of node and install yarn 1.6. Then run the command "yarn install.

**What is the expected behavior?**
Yarn should throw an error like the one in the image below
![image](https://user-images.githubusercontent.com/29917195/44854330-2b69ec00-ac60-11e8-92e4-fe4f316ab9d2.png)

**Please mention your node.js, yarn and operating system version.**
Node JS Version : 8.11.4 (Recommended Version)
Operating System :  ![image](https://user-images.githubusercontent.com/29917195/44854475-8996cf00-ac60-11e8-88b4-72430df8c646.png)

**Comment by Daniel15** [comment]
Are you using a proxy at all? `registry.yarnpkg.com` should definitely not be serving any self-signed certificates. This sounds like some issue with your network

**Comment by AlexMachin1997** [comment]
Not what Im aware of. The only proxy I use is when I'm using browser-sync, other than that I'm not.

**Comment by AlexMachin1997** [comment]
Ok so I reset the registry url, set strict ssl from true to false then back again and it now works.

**Comment by AlexMachin1997** [comment]
Right so I've come back today and its playing up again. Im not exactly sure why its playing, I must have reset the soding thing 5 times now grrr.

**Comment by koitache** [comment]
can you help me?
KOITA LIMANE@KOITALIMANE-PC MINGW64 ~/Desktop/dreamhouse-sfdx (master)
$ sfdx force:package:create --name dreamhouse --description "My Package" --packagetype Unlocked --path force-app --nonamespace --targetdevhubusername DevHub
'C:\Program' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.

**Comment by AlexMachin1997** [comment]
Hold on. Is this related to the certificate issue ? It looks like its in a different language sorry if it is related to this issue.

**Comment by AlexMachin1997** [comment]
Im going to close the issue as it's unrelated to yarn, is an npm issue Im facing.

**Comment by AlexMachin1997** [comment]
NPM is now working but Im still getting this error
![image](https://user-images.githubusercontent.com/29917195/44946705-2a1ff700-adf9-11e8-9219-2970c32e87a4.png)

**Comment by AlexMachin1997** [comment]
This is issue has since been resolved, in the end I reset my device and it worked for both npm and yarn. Clearly there was some issue with my device.
