### ISSUE TITLE
Installation Problem: Cannot Install any packages or execute create-react-app

### ISSUE THREAD

**Issue by halstjas** [yarnpkg/yarn#6345]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**

create-react-app client

Creating a new React app in C:\Users\jason\coding\sum_group_mvp1\client.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.9.4
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react: connect ETIMEDOUT 92.242.132.24:443".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\jason\\coding\\client\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts --cwd C:\Users\jason\coding\sum_group_mvp1\client has failed.

Deleting generated file... package.json
Deleting generated file... yarn-error.log
Deleting client / from C:\Users\jason\coding\sum_group_mvp1
Done.

Timeout error also occurs when attempting to perform yarn add <package>

**Comment by greena13** [comment]
I was having a similar issue - unable to reach anything on https://registry.yarnpkg.com.

Seems to be back up now. Try again.

**Comment by mpress** [comment]
npm woes: https://status.npmjs.org/
Some suggestions there describing what you might try.

**Comment by erin-doyle** [comment]
The npm registry is supposed to be all fixed now and I'm able to `npm install` but I still can't `yarn install`.  If I change the registry in the yarn config I can, but I don't really want to do that as it ends up saving whatever gets installed at that time with that registry in my `yarn.lock` file.

**Comment by kayode-adechinan** [comment]
Got same issue.

**Comment by tcelestino** [comment]
I have some issue too

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
