### ISSUE TITLE
Registry errors causing CI failures

### ISSUE THREAD

**Issue by bvaughn** [yarnpkg/yarn#6347]
Yesterday, Circle CI status page reported intermittent NPM registry issues– but today both [Circle CI status](https://status.circleci.com/) and [NPM status](https://status.npmjs.org/) pages are all green. Interesting, the [Yarn status page](https://status.yarnpkg.com/) is also all green, but for some reason I don't trust it very much 😄
<img width="951" alt="screen shot 2018-09-02 at 8 03 27 am" src="https://user-images.githubusercontent.com/29597/44957387-b6c4c680-ae86-11e8-8a3c-6d0f30c0df50.png">

Anyway, this has been causing consistent CI failures for the React team all weekend (e.g. [here](https://circleci.com/gh/facebook/react/11555#tests/containers/2)) so I wanted to make sure it was raised as an issue. I believe the problems started Saturday morning ~9am PDT if memory serves.

This issue is probably a duplicate of #6345 but I wanted to file the CI issue more explicitly.

**Comment by merceyz** [comment]
https://github.com/yarnpkg/yarn/issues/8231#issuecomment-753661809
