### ISSUE TITLE
Installation Problem: unable to upgrade yarn from v0.24.6

### ISSUE THREAD

**Issue by tessaSAC** [yarnpkg/yarn#6349]
**Which operating system are you using:**
OSX Sierra

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I've been unable to upgrade yarn following the steps from the website since last year now as both npm and homebrew were unable to find it and whatever instructions I used to install it over a year ago have long since disappeared.

Finally I gave up and tried installing with brew which appears to have installed yarn 1.9.4 somewhere, but any commands still refer to version 0.24.6.

**Comment by javiergarzac** [comment]
Ran into the same issue. Try `brew switch yarn [version]`
I had version 1.13.0 `brew switch yarn 1.13.0` worked for me.

**Comment by Daniel15** [comment]
> Finally I gave up and tried installing with brew which appears to have installed yarn 1.9.4 somewhere, but any commands still refer to version 0.24.6.

Try `which yarn` or `locate yarn` to find where the old version is coming from.

**Comment by paul-soporan** [comment]
Closing this as unactionable, use the commands in Daniel's comment to see where the old version is coming from and uninstall it.
