### ISSUE TITLE
Adding unused option before `add` command yields error

### ISSUE THREAD

**Issue by jpwesselink** [yarnpkg/yarn#635]
**Do you want to request a feature or report a bug?**

A bug. 

**What is the current behavior?**

Adding unused option before `add` command yields error

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
$ yarn --foo add gulp-asdasdasdasdasdasdasdasdasd
yarn install v0.15.1
error `install` has been replaced with `add` to add new dependencies. Run "yarn add gulp-asdasdasdasdasdasdasdasdasd" instead.
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**

```bash
$ yarn --foo add gulp-asdasdasdasdasdasdasdasdasd
yarn install v0.15.1
warning `--foo` is an unknown option for `add` and will be ignored.
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Please mention your node.js, yarn and operating system version.**

```bash
- node.js: v6.5.0
- yarn: v0.15.1
```

**Comment by kittens** [comment]
With #777 we'll throw an error when you use an unknown argument. #716 was opened which adds support for this but as I mentioned in that issue to support this is ambiguous and would run into other issues.
