### ISSUE TITLE
ESLint reports a warning on yarn master (no-extra-boolean-cast)

### ISSUE THREAD

**Issue by edmorley** [yarnpkg/yarn#6350]
**Do you want to request a *feature* or report a *bug*?**
Yarn contributor UX papercut.

**What is the current behavior?**
On yarn `master` (currently `047b10a`), ESLint reports:

```
C:\Users\Ed\src\yarn\src\config.js
  377:30  warning  Redundant Boolean call  no-extra-boolean-cast

✖ 1 problem (0 errors, 1 warning)
  0 errors, 1 warning potentially fixable with the `--fix` option.

Found 0 errors
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Checkout the yarn repository at revision `047b10a`
2. `yarn`
3. `yarn lint`

**What is the expected behavior?**
No ESLint warnings or errors on the `master` branch, since CI ensures that `master` is passing at all times (and ESLint is configured to either not show warnings, or else exit non-zero for both errors+warnings and not just errors).

**Please mention your node.js, yarn and operating system version.**
Node 10.9.0, Windows 10.

**Comment by arcanis** [comment]
Thanks for the report! Wanna open a PR to fix it?

**Comment by edmorley** [comment]
Hi! The lint issue mentioned above has since been fixed, though there is now a new one:

```
C:\Users\Ed\src\_todo\yarn\src\util\generate-pnp-map.js
  251:13  warning  Block is redundant  no-lone-blocks
```

The root cause is that ESLint does not exit non-zero for "warnings", only "errors" - and whilst this probably makes sense for development, it's not ideal for CI.

Workarounds appear to be:
1. use `--max-warnings=0` (but that fails early after the first warning according to eslint/eslint#2309)
2. have the rule configuration vary the error/warn level based on the presence of `process.env.CI`

Option (2) seems like the ideal solution, though that would mean making upstream changes to `eslint-config-fb-strict`, which is probably beyond the scope of this issue.

Closing this out since the original warning was fixed.
