### ISSUE TITLE
input command  yarn --version  error

### ISSUE THREAD

**Issue by lwbtt0915** [yarnpkg/yarn#6356]
C:\zdjt\soft\Yarn>yarn --version
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by probil** [comment]
Are you sure yarn is installed globally?

**Comment by PLQin** [comment]
> Try these solutions: #601

**Comment by probil** [comment]
It seems like there is something called `yarn` written in Java (not JavaScript) installed on you machine
