### ISSUE TITLE
`@yarnpkg/lockfile` not published with `integrity` changes

### ISSUE THREAD

**Issue by SimenB** [yarnpkg/yarn#6364]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
Using the published `@yarnpkg/lockfile` will move the `integrity` field from #5042 below `dependencies` creating an inconsistency with `yarn` itself.

See https://runkit.com/embed/lnyepmrle2sq

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
That output is the same as the input

**Please mention your node.js, yarn and operating system version.**
N/A

**Comment by arcanis** [comment]
Hey @SimenB! I've just release a 1.1, [it seems to work better](https://runkit.com/arcanis/5b9674f7a6c1220012718ded) 👍

**Comment by SimenB** [comment]
Thank you!
