### ISSUE TITLE
Can workspace be in parent directory of root?

### ISSUE THREAD

**Issue by pbambusek** [yarnpkg/yarn#6368]
Hi, I'm looking for someone who can clarify a thing about workspaces. I've a use case where multiple products have very close structure and should reuse some common codebase. Furthermore, I'd like to use workspaces internally in those products as a hard architectonic layer (i.e. separate entities, views, app, etc.). The project structure should look like this:

```
product1/
  src/
    entities/
      package.json
    app/
      package.json
    views/
      package.json
  package.json
product2/
modules/
  shared-module/
    package.json
```

In the documentation there is stated
> Workspaces must be children of the workspace root in terms of folder hierarchy. You cannot and must not reference a workspace that is located outside of this filesystem hierarchy.

However, when I try this configuration in `product1/package.json`
```
  private: true,
  workspaces: [
    src/*
    ../modules/*
  ]
```

it manages to symlink the `shared-module` correctly. Is that expected behaviour, or just accidental? Can I rely on it? Or, if not, what kind of alternative I should consider?

Thanks

**What is the current behavior?**
The workspace in parent directory is symlinked correctly

**What is the expected behavior?**
As per documentation it shouldn't be possible

**Please mention your node.js, yarn and operating system version.**
node v8.11.2, yarn v1.9.4, windows 10 home

**Comment by arcanis** [comment]
> Is that expected behaviour, or just accidental? Can I rely on it?

Accidental, we might fix it later. There is two issues with doing that is that the packages in `modules` have no idea they are in a workspace, so running `yarn add` there won't cause the tree in `product1` to be recomputed.

> Or, if not, what kind of alternative I should consider?

Create a workspace in the parent directory of both `product1`, `product2`, and `modules`, and add them all as part of this single megaworkspace.

We also have plans for nested workspaces, but it will take more time, there's some work that need to be finished first before we can get to this.

**Comment by pbambusek** [comment]
> Create a workspace in the parent directory of both product1, product2, and modules, and add them all as part of this single megaworkspace.

I've thought about this, but that has 2 issues:
- I need unique names for "internal" workspaces (i.e. `product1-app`, etc. This might be a better solution than naked `app` name anyway, but I'm not sure yet)
- There is nothing preventing `product2` to depend on internals of `product1` by default. It could be enforced i.e. by Eslint or similar tool, but that requires extra hussle in config/maintain.

> We also have plans for nested workspaces, but it will take more time, there's some work that need to be finished first before we can get to this.

Do you have any time estimates on that? I might start with the internal workspaces and add the shared later on.

**Comment by arcanis** [comment]
> Do you have any time estimates on that?

I'd say at least a few months away, nobody worked on it yet and we have to solve the conceptual issues before starting the implementation - plus the other architectural changes I mentioned.

**Comment by pbambusek** [comment]
Ok, I gues that answers my question. Thank you.
