### ISSUE TITLE
yarn init -y

### ISSUE THREAD

**Issue by montogeek** [yarnpkg/yarn#637]
I use this option a lot to quickly start a new project.
I can open a PR to add it :)

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`yarn init -y` does not exist and returns:
```
👉  yarn init -y
yarn init v0.15.1
error This command doesn't require any arguments.
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

**What is the expected behavior?**
`yarn init -y` should be possible to guarantee full compatibility with NPM https://docs.npmjs.com/cli/init

**Please mention your node.js, yarn and operating system version.**
Node v5.3.0
yarn 0.15.1
macOS Sierra

**Comment by Kovensky** [comment]
`yes '' | yarn init` 😄
