### ISSUE TITLE
Documentation: explain resolutions example

### ISSUE THREAD

**Issue by avdd** [yarnpkg/yarn#6372]
The example given here

https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it

is entirely opaque.  What is the problem motivating this example?  Why are there three versions of left-pad?  What are `file:../c-1`, `file:../d2-1` and why are they used here?  What is `c/**/left-pad` and why is different to `d2/left-pad`?

As this is one of the suggested workarounds for #4986 it would be helpful if the example were clearer.  I imagine many people encountering this are, like me, not very familiar with the arcana of dependency specification.

**Comment by kuworking** [comment]
Definetively I am now looking for additional examples to figure it out how it works

**Comment by paul-soporan** [comment]
Closing as we've revamped the `resolutions` field and v2 and have improved and updated the documentation: https://yarnpkg.com/configuration/manifest#resolutions.

https://yarnpkg.com/getting-started/migration
