### ISSUE TITLE
.msi installer "Installation directory must be on a local hard drive"

### ISSUE THREAD

**Issue by jacknevitt** [yarnpkg/yarn#6379]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn stable v1.9.4 Windows .msi installer doesn't allow me to install on my C: drive.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Download and run `yarn-1.9.4.msi` from https://yarnpkg.com/en/docs/install#windows-stable
2. Click next
3. Accept T&C, click next
4. Select "C:\Program Files (x86)\Yarn\" (default input), click next
5. The alert pops up with a message "Installation directory must be on a local hard drive".

**What is the expected behavior?**
Installation allows the path on the C: drive because it is a local drive

**Please mention your node.js, yarn and operating system version.**
Node v10.1.0
Yarn v1.6.0 (I had run the command `yarn global add yarn` to try and update it, but was redirected to the yarn install site by a warning)
Windows 10 Pro v1803

**Comment by Daniel15** [comment]
Huh, that's odd. Sounds like a bug in WiX (the app we use to build the installer) or in Windows Installer itself.

I Googled the message and found this issue: https://github.com/adobe/brackets/issues/2407. It's for a different product (Adobe Brackets), but try some of the suggestions in that issue and see if it works?

**Comment by jacknevitt** [comment]
I have uninstalled yarn and have gone back to npm for the time being.
There's a possibility a fresh install might resolve this but I will need to dedicate some more time to this when I can

**Comment by Jiping-hi** [comment]
hit by the same issue and solved by running command line with **Administrator** privilege.
`C:\WINDOWS\system32>msiexec /i "C:\Users\JipingWang\Downloads\yarn-1.10.1.msi"`

**Comment by jacknevitt** [comment]
Turns out it was a rare issue with my windows MSI installer being faulty. I did a windows reinstall and things worked from there. Shame there wasn't a less painful solution, but I'm no longer sure the problem was with Yarn.
