### ISSUE TITLE
getaddrinfo EADDRNOTAVAIL registry.yarnpkg.com:443

### ISSUE THREAD

**Issue by iamcaleberic** [yarnpkg/yarn#6384]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
- On running `yarn install` it throws `getaddrinfo EADDRNOTAVAIL registry.yarnpkg.com:443`  
```
Trace: 
  Error: getaddrinfo EADDRNOTAVAIL registry.yarnpkg.com:443
      at Object._errnoException (util.js:992:11)
      at errnoException (dns.js:55:15)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

```
**If the current behavior is a bug, please provide the steps to reproduce.**

- Runnning `yarn install` 

**What is the expected behavior?**
- Install the packages in `package.json`

**Please mention your node.js, yarn and operating system version.**
- Yarn version: 
  `1.9.4`

- Node version: 
  `8.11.4`

- Platform: 
 `alpine-edge linux x64`

**Comment by pdhar-tibco** [comment]
The yarn command run correctly inside the OSX terminal, however it does not inside a (alpine linux) docker container shell.
`Trace:
  Error: getaddrinfo EADDRNOTAVAIL registry.yarnpkg.com:443
      at Object._errnoException (util.js:1003:13)
      at errnoException (dns.js:60:15)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)`

**Comment by aslakhellesoy** [comment]
I'm seeing this too. It seems to be a problem unrelated to yarn though:

```
node -e "require('https').get('https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY').on('error', err => console.log('Er
ror: ' + err.message))"
```

So it looks as though node is broken on alpine-edge.

**Comment by pdhar-tibco** [comment]
I have tested this on older alpine node image where it works so my
suspicion is something in alpine updates is triggering the NPM registry
problem

**Comment by pdhar-tibco** [comment]
I tried this on base alpine 3.7 and it works, however it breaks once I run`apk upgrade --update-cache --available` which apparently brings in some recent update/patch causing this breakage.

**Comment by aslakhellesoy** [comment]
@pdhar-tibco my example above demonstrates that the http stdlib doesn’t work. It can’t connect anywhere.

What makes you think this is related to nom, yarn or the registry?

**Comment by pdhar-tibco** [comment]
I have come to the same conclusion as I was able to run npm on alpine
without updated packages. Some update broke this recently coinciding with
the npm registry outage.

**Comment by pdhar-tibco** [comment]
I think I have found the problem. It is coming from a update of musl-utils package (1.1.18-r3 -> 1.1.20-r1).

-Pranab

**Comment by richfelker** [comment]
Are you sure it's the musl-utils package that broke it? musl-utils actually has nothing to do with musl; it's an alpine package that provides portable replacements for a few things that were historically packaged with glibc and uclibc.

**Comment by richfelker** [comment]
It's almost certainly the updated musl package, not musl-utils, affecting it; the relevant change is the new AI_ADDRCONFIG feature. For some reason, attempting to connect a udp socket to either 127.0.0.1 or ::1 (v4 or v6) is producing EADDRNOTAVAIL. Can you check for any network configuration that might be causing this? It's only documented (in the linux man page for connect) to happen if the entire port range configured in /proc/sys/net/ipv4/ip_local_port_range is exhausted. Maybe Docker is doing something weird that causes it to happen under other conditions.

**Comment by pdhar-tibco** [comment]
I observed that after eliminating musl-utils I was able to run npm. I agree
it can be docker also but this behavior was noticed even older versions of
docker too which eliminated docker as participant.

**Comment by richfelker** [comment]
I don't mean to say there's a new regression in Docker. I mean the issue is an interaction of some aspect of the Docker network configuration with the new AI_ADDRCONFIG support in musl 1.1.20.

**Comment by richfelker** [comment]
Please try running this C program inside the Docker container using strace and posting the strace output:

[check_gai_regression.c.txt](https://github.com/yarnpkg/yarn/files/2395481/check_gai_regression.c.txt)

**Comment by ncopa** [comment]
I can reproduce the issue.

````
/ # ./check_gai_regression
System error [Address not available]
/ # strace ./check_gai_regression
execve("./check_gai_regression", ["./check_gai_regression"], 0x7ffd13bd6690 /* 6 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f8417631b88) = 0
set_tid_address(0x7f8417631bc8)         = 15
mprotect(0x7f841762e000, 4096, PROT_READ) = 0
mprotect(0x55ba5c7d8000, 4096, PROT_READ) = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(65535), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
close(3)                                = 0
socket(AF_INET6, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP) = 3
connect(3, {sa_family=AF_INET6, sin6_port=htons(65535), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Address not available)
close(3)                                = 0
ioctl(1, TIOCGWINSZ, {ws_row=24, ws_col=80, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="System error [Address not availa"..., iov_len=35}, {iov_base="]\n", iov_len=2}], 2System error [Address not available]
) = 37
exit_group(0)                           = ?
+++ exited with 0 +++
/ # 
````

**Comment by richfelker** [comment]
Yes, I can too now. It happens when the address ::1 is not configured on lo **and** there's no default route for ipv6. I had tested both of these configurations separately before but not together. This seems to be a bug in the Linux documentation too since EADDRNOTAVAIL is not documented for this purpose. I'll prepare a patch for musl; I need to check because it looks like there may be a few more errors we should consider here as indications that the address family being probed is not configured.

**Comment by richfelker** [comment]
I've pushed a fix to musl that should address this issue. Hopefully Alpine will pick up the patch soon. https://git.musl-libc.org/cgit/musl/commit/?id=f381c118b2d4f7d914481d3cdc830ce41369b002

**Comment by richfelker** [comment]
Until it's fixed, a simple workaround would be `ifconfig lo ::1` or equivalently `ip addr add ::1 dev lo`

**Comment by frederik** [comment]
Thanks a lot. Our build with latest is working again as of yesterday. Maybe @iamcaleberic can confirm.

**Comment by iamcaleberic** [comment]
Thanks all the commands are running normally. Will go ahead and close this.
