### ISSUE TITLE
There appears to be trouble with your network connection

### ISSUE THREAD

**Issue by Ziv-Barber** [yarnpkg/yarn#6385]
yarn install --network-timeout 100000
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
...

Other things working (no Internet problem)

**Please mention your node.js, yarn and operating system version.**
node 10.10.0
npm 6.1.0
yarn 1.9.4
Windows 10

**Comment by frederik** [comment]
This might be a duplicate of #6384

**Comment by StevenFewster** [comment]
I'm getting similar.  Yarn and NPM configs are both set up to use the https registry, but I'm getting this error behind a corporate proxy:

```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://registry.npmjs.org/sax/-/sax-0.5.8.tgz: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Development\\ui-patrec\\yarn-error.log".
```
Where it's looking at http.  Could that be the error?

**Comment by Ziv-Barber** [comment]
They fixed it. I guess the npm services was down.
