### ISSUE TITLE
yarn and npm build failing on alpine linux containers

### ISSUE THREAD

**Issue by pdhar-tibco** [yarnpkg/yarn#6396]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
bash-4.4# yarn
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/autoprefixer/-/autoprefixer-6.7.7.tgz: getaddrinfo EADDRNOTAVAIL registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/src/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Trace:
  Error: getaddrinfo EADDRNOTAVAIL registry.yarnpkg.com:443
      at Object._errnoException (util.js:1003:13)
      at errnoException (dns.js:60:15)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
This should not happen while running yarn inside a docker container.

**Please mention your node.js, yarn and operating system version.**
node --version v9.4.0
yarn --version 1.3.2
Linux 93247269ce89 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 Linux
docker version: Community (mac) Version 18.06.1-ce-mac73 (26764)

**Comment by probil** [comment]
@pdhar-tibco I use yarn in [`node:alpine`](https://hub.docker.com/_/node/) without any issues.
Could you please provide your `package.json` file?
Is it possible for you to upgrade `yarn` to latest version (`v1.9.4`) and re-check?

**Comment by pdhar-tibco** [comment]
> @pdhar-tibco I use yarn in [`node:alpine`](https://hub.docker.com/_/node/) without any issues.
> Could you please provide your `package.json` file?
> Is it possible for you to upgrade `yarn` to latest version (`v1.9.4`) and re-check?

This problem has been addressed here https://github.com/yarnpkg/yarn/issues/6384
