### ISSUE TITLE
error Command failed with exit code 2. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### ISSUE THREAD

**Issue by wushuxuan** [yarnpkg/yarn#6397]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by nukec** [comment]
-bug
-same as error
- just run yarn start
- to work?
- node is 10, yarn 1.16 and windows 10 pro

**Comment by paul-soporan** [comment]
Closing as there's nothing actionable here.
