### ISSUE TITLE
--ignore-engines behaves oddly

### ISSUE THREAD

**Issue by ChristopherBiscardi** [yarnpkg/yarn#640]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

If you attempt to add or install a package with an invalid `engines` config:

```
~/.yarn/bin/yarn.js add file:../cosmiconfig
yarn add v0.15.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error cosmiconfig@2.0.1: The engine "node" is incompatible with this module. Expected version "4".
error Found incompatible module
```

ok, so then you add `--ignore-engines` and get:

```shell
~/.yarn/bin/yarn.js --ignore-engines add file:../cosmiconfig
yarn install v0.15.0
error `install` has been replaced with `add` to add new dependencies. Run "yarn add add file:../cosmiconfig" instead.
```

notably there are two `add`s in the error output: `yarn add add file:../cosmiconfig`

**If the current behavior is a bug, please provide the steps to reproduce.**

```shell
> cat a/package.json
{
  "name": "a",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "engines": {
    "node": "4"
  }
}
> cat b/package.json
{
  "name": "b",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
}
> cd b
> ~/.yarn/bin/yarn.js add file:../a
yarn add v0.15.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error a@1.0.0: The engine "node" is incompatible with this module. Expected version "4".
error Found incompatible module
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
> ~/.yarn/bin/yarn.js --ignore-engines add file:../a
yarn install v0.15.1
error `install` has been replaced with `add` to add new dependencies. Run "yarn add add file:../a" instead.
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
> # ls for completeness
> ls ~/.yarn-cache
npm-a-1.0.0
```

**What is the expected behavior?**

`--ignore-engines` should ignore the engines declarations instead of producing an error message about the change from `install` to `add`.

**Please mention your node.js, yarn and operating system version.**

* yarn 0.15.1
* node v6.2.0
* OSX 10.11.3

**Comment by hawkrives** [comment]
I think you've run into a combo of https://github.com/yarnpkg/yarn/issues/635 and https://github.com/yarnpkg/yarn/issues/638.

**Comment by ChristopherBiscardi** [comment]
Indeed. I'll closing this in favor of those since they've split out the individual issues.
