### ISSUE TITLE
Plug'n'Play doesn't support Windows paths

### ISSUE THREAD

**Issue by NyaBit** [yarnpkg/yarn#6402]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
When using `yarn install` with `C:\Users\Username\Desktop\yarn\bin` added to path variable, where `C:\Users\Username\Desktop\yarn` is checked out with `git clone github.com/yarnpkg/yarn.git --branch yarn-pnp` and `"installConfig": {"pnp": true}` is appended to project's `package.json` or `yarn install --pnp` is executed in project's folder it creates `node_modules` folder and doesnt create `.pnp.js` file. 

These methods were tested on [pnp-sample-app](https://github.com/yarnpkg/pnp-sample-app) as well. And all required packages were present in yarn cache and checked with `yarn cache list`.

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn install --pnp` 
or
Add `"installConfig": {"pnp": true}` in `package.json` and run `yarn` or `yarn install` in project's root directory.

**What is the expected behavior?**
No `node_modules` folder should be created and `.pnp.js` shold be created inside the root of the project.

**Please mention your node.js, yarn and operating system version.**
`Node v8.11.3`
`Yarn 1.11.0-0`
`Windows 10 1803`

**Comment by strothj** [comment]
@NyaBit PnP is currently not supported on Windows. Seems to work in Subsystem for Linux just fine though.

**Comment by jdalton** [comment]
For reference the `esm` loader uses a [normalize](https://github.com/standard-things/esm/blob/master/src/path/normalize.js) helper for the relative paths it stores in metadata. Which should keep it portable across-platforms (Windows and other).

**Comment by jdalton** [comment]
**Update:**

Opened PR #6447 to start working toward fixing this.
