### ISSUE TITLE
download tarball by install.sh was so slow

### ISSUE THREAD

**Issue by AntSworD** [yarnpkg/yarn#642]
The install.sh download tarball was so slow..

China, but Japan Shadowsocks

**Comment by kittens** [comment]
Weird, we're using Amazon S3 for this. Is access to it particularly bad in China? We could likely setup a proxy on our yarnpkg.com domain which is hosted on Cloudflare which has Chinese POPs. cc @thejameskyle.

**Comment by AntSworD** [comment]
Japanese VPS install just fine.
proxy by ss download  the tar.gz was so quickly，but so slow if off the proxy..
I think it wasn't your fault..

**Comment by Daniel15** [comment]
> We could likely setup a proxy on our yarnpkg.com domain which is hosted on Cloudflare 

CloudFlare should already be caching the files though, right?

**Comment by dknecht** [comment]
It doesn't look like caching is enabled.  @thejameskyle

**Comment by wong2** [comment]
@kittens Amazon S3 is mostly slow in China
