### ISSUE TITLE
yarn add does not work with remote URL

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/yarn#6422]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
yarn add git@gitlab.host.com:client/components.git#master
yarn add v1.9.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
Couldn't find any versions for "git" that matches "gitlab.ueberbit.de:stroeer/components.git#master"
```

**What is the expected behavior?**
It should install from the GitLab repository from our private GitLab instance.

**Please mention your node.js, yarn and operating system version.**
6.4.0
1.9.4
macOS 10.13.6

**Comment by rally25rs** [comment]
Could you try using `git+ssh://git@gitlab.host.com/client/components.git#master` instead?

npm supports so many oddball and somewhat loosely documented URLs and then internally tries to auto-correct them. yarn primarily just tries to feed it directly to `git` which is pickier about URL formats.

**Comment by DanielRuf** [comment]
As far asI know I already tried it, with the same result. But I'll try again and let you know.

**Comment by DataTables** [comment]
Its an old bug, so apologies for necroing it, but I wanted to note for anyone else who find this prefixing with `git+ssh://` worked for me with a github repo. Otherwise it was trying to resolve the `git@github.com...` as a version!

**Comment by craigphicks** [comment]
This, and only this, worked for me
```
yarn add -D  ssh://git@github.com:someusername/somepackagename.git
```
It ought to be documented on the documentation page for [`yarn add`](https://classic.yarnpkg.com/en/docs/cli/add#toc-adding-dependencies).
