### ISSUE TITLE
Question on Collaboration

### ISSUE THREAD

**Issue by EisenbergEffect** [yarnpkg/yarn#643]
I just saw [the blog post](https://code.facebook.com/posts/1840075619545360) this morning. It talks a lot about collaboration. One thing it doesn't mention is why this wasn't done in collaboration with the NPM team. Why couldn't all these people have worked with the NPM client team to make NPM better? I'd very much like to hear that side of the story.

**Comment by thejameskyle** [comment]
Making breaking changes to the npm client is really really hard when they have so many people depending on them. From their perspective it's actually better to have a separate tool work out details of what the client should be.

That being said we've had npm in the loop from the early days, they've been very encouraging. You can see their blog post here: http://blog.npmjs.org/post/151660845210/hello-yarn

**Comment by EisenbergEffect** [comment]
Excellent. Perhaps a cross-link to that post from your article is in order?
