### ISSUE TITLE
replace `workspace-aggregator-<guid>` with something users will understand

### ISSUE THREAD

**Issue by dylang** [yarnpkg/yarn#6435]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

When using workspaces, when there are dependency warnings, it looks like:

```
warning "workspace-aggregator-7444e24d-a6d9-4fc6-a3d9-95e8c385bc26 > ....
```

<img width="495" alt="screen shot 2018-09-26 at 10 00 23 am" src="https://user-images.githubusercontent.com/51505/46085034-0e4b0f00-c173-11e8-9562-22c5a9ec2844.png">

According to #6056 this is an internal implementation detail that was intended to be fixed, but maybe was forgotten about. 

I was wondering if there is a plan for this. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Package name, workspace glob, or just hide the string? I'm not sure what the guid is intended to represent that is helpful to users.

**Please mention your node.js, yarn and operating system version.**

`node 10.8.0`
`yarn 1.10.1`

**Comment by timfish** [comment]
This is particularly bad when using:
```
 yarn licenses generate-disclaimer
```
As at the top you get this nonsense:
`THE FOLLOWING SETS FORTH ATTRIBUTION NOTICES FOR THIRD PARTY SOFTWARE THAT MAY BE CONTAINED IN PORTIONS OF THE WORKSPACE AGGREGATOR 7A75BA7A 6BC8 4519 99D7 AD735AAFFA0F PRODUCT.`

**Comment by code-for-coffee** [comment]
Reporting on Node 10.15.3, Yarn 1.17.3

This looked like an error when I began migrating a codebase from `npm` to `yarn`. Searching led me to this thread. I think that this could be cleaned up to make more sense for the developer. 

```
warning " > workspace-aggregator-0bf280c8-cddb-4770-8ba8-251f9e218701@0.0.0" has incorrect peer dependency "react@~16.3.0".
warning " > workspace-aggregator-0bf280c8-cddb-4770-8ba8-251f9e218701@0.0.0" has incorrect peer dependency "react-dom@~16.3.0".
```

**Comment by MattLongCode** [comment]
Yes this would be useful. This line of output isn't something understandable.

```
warning workspace-aggregator-0e7b8173-3d87-40d5-a0c7-af128855bb33 > cra-kitchen-sink > @storybook/addon-info > jsx-to-string > react > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
```

**Comment by timfish** [comment]
@bestander sorry to ping you like this but I was wanting some guidance on how this should be fixed.

What's stopping [this](https://github.com/yarnpkg/yarn/blob/fea852b48db739d846a8f8414db576e4685b8af3/src/cli/commands/install.js#L371) from being changed to use `workspaceManifestJson.name`:
```
        const virtualDependencyManifest: Manifest = {
          _uid: '',
          name: workspaceManifestJson.name  || `workspace-aggregator-${uuid.v4()}`,
          version: '1.0.0',
          _registry: 'npm',
          _loc: workspacesRoot,
          dependencies: workspaceDependencies,
          devDependencies: {...workspaceManifestJson.devDependencies},
          optionalDependencies: {...workspaceManifestJson.optionalDependencies},
          private: workspaceManifestJson.private,
          workspaces: workspaceManifestJson.workspaces,
        };
```

Is the guid there to stop name clashes in case the root manifest has the same name as any of the workspace dependencies?

If so, how about something like this to reduce the chances of name clashes?
```
        const workspaceName = workspaceManifestJson.name  || `aggregator-${uuid.v4()}`

        const virtualDependencyManifest: Manifest = {
          _uid: '',
          name: `workspace-${workspaceName}`,
```

**Comment by bestander** [comment]
@timfish, it's been a while since I touched the code.
If you patch do all the tests pass?
If yes then send a Pull Request

**Comment by lPaths** [comment]
Is there any solution to hide those warning?

**Comment by vpiskunov** [comment]
It's been almost a year - @timfish your fix seems to make sense, has it ever been merged at all?

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
