### ISSUE TITLE
yarn stuck on old version

### ISSUE THREAD

**Issue by yx296** [yarnpkg/yarn#6437]
I installed the current version of yarn with
curl --compressed -o- -L https://yarnpkg.com/install.sh | bash

But then when i run yarn -v it still says 1.6.0 and when i use yarn install it uses 1.6.0

Node version - 8.9.4
Mac OSX

**Comment by Daniel15** [comment]
Use `whereis yarn` or `locate yarn` - You might have a different version of Yarn installed somewhere.

**Comment by Daniel15** [comment]
Closing this out, but please open again if it's still an issue.
