### ISSUE TITLE
Bad chocolatey package dependency

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/yarn#6439]
Well - there's been this PR https://github.com/yarnpkg/yarn/pull/5925 - which, uh, I don't like, to say the least.

It's simply a bad idea to change package behaviour that drastically. Because "some people request it". So choco yarn would like to downgrade node 10 to node 6.9.2? No good - even if it would've been node 8 (which is the correct lts).

If you can't depend on nodejs.install OR nodejs-lts then why depend on it at all? yarn*msi installs fine without node. It should be completely up to the user which nodejs they install and how they do it (node.exe, chocolatey, nvm, a.s.o.)!

**Comment by Daniel15** [comment]
@ihalila  What do you think? Should we just remove the dependency? That'd mean that Yarn installed via Chocolatey wouldn't work out-of-the-box (you'd need to manually install Node.js) but perhaps that's an acceptable tradeoff?

**Comment by jeffrson** [comment]
Well, installing yarn*.msi from https://github.com/yarnpkg/yarn/releases wouldn't work as well, if node.js had not been installed. You don't trade in any disadvantages compared to the msi, but the package may be updated via choco.

So yes, IMO this is very acceptable. Maybe you could include a post-install-message that points out that the user needs to install nodejs themselves and it could propose "choco install" commands for nodejs-lts and nodejs.install.

**Comment by Daniel15** [comment]
Showing a post install message is a great idea. Would you like to submit a
pull request to implement that?
