### ISSUE TITLE
Preserve "integrity" entries when using Yarn 1.9

### ISSUE THREAD

**Issue by rarkins** [yarnpkg/yarn#6440]
Can a patch version 1.9.5 be released where Yarn does not strip out every single "integrity" link (added in v1.10.0) from a `yarn.lock` if found?

Due to some problems with Yarn v1.10.x, I rolled Yarn back to v1.9.4. Now I see any small change to the lock file results in the `integrity` field being stripped from every single package.

Although ideally everyone in a team uses the exact same version of Yarn at all times, this is not always feasible and perhaps sometimes the entire team needs to roll back. Ideally this wouldn't result in massive flip/flopping of lock file contents as a result, if they could be left as-is without impact.

Cc @edmorley

**Comment by arcanis** [comment]
That sounds reasonable. I'll see what I can do.

BTW, have you seen that we do support checking-in the Yarn binary into a
repository, using yarn-path? That ensures that all your devs use the exact
same version, and transparently.

**Comment by rarkins** [comment]
@arcanis thanks for considering it and the tip re: `yarn-path`.

FYI, I'm the author of "Renovate Bot", so that's why I've been exposed to this challenge right away. Currently the bot bundles its own `yarn` dependency and uses that for all repos, so I have reverted it to v1.9.4 for now until I have a solution to dynamically switch Yarn versions for the longer term. Having a v1.9.5 that does not *strip* `integrity` would be a great benefit to any repos already on v1.10 using the bot (such as probably this one).

**Comment by rarkins** [comment]
Here's an example to reproduce this locally:

1. Run "yarn install" using v1.10.0 with this `package.json`:

```json
{
  "name": "yarnintegrity1",
  "version": "0.0.1",
  "dependencies": {
    "chalk": "2.0.0",
    "left-pad": "1.0.0"
  }
}
```

Result, as expected: `yarn.lock` exists with each entry including an `integrity` hash.

2. Using yarn@1.9.4, run `yarn add left-pad@1.1.0 --exact`

Result: Every `integrity` field has been stripped from the `yarn.lock` for `chalk` and its dependents

Expectation: Only `left-pad`'s `integrity` field would be removed.

The `yarn@1.10.0` I used is installed via `brew` on OSX, while the `yarn@1.9.4` I used is the compiled JS downloaded from this repository's releases page. Technically I ran `node ~/yarn-1.9.4.js add left-pad@1.1.0 --exact` but I suspect that none of these details really change anything.

Cc @imsnif as per our Twitter thread

**Comment by edmorley** [comment]
Given this issue and also https://github.com/heroku/heroku-buildpack-nodejs/pull/569#issuecomment-424700838 it is starting to feel like the new integrity feature needs to be changed to a more staged rollout.

ie:
1. Keep support for it in yarn 1.10.x, but default it to off (eg equivalent of `unsafe-disable-integrity-migration true`). In this "off" state, any existing `integrity` fields should be preserved, but no new ones added.
2. In a later version of yarn, start adding `integrity` for any newly changed packages (eg those affected by `yarn add`), but don't mass-fetch all dependencies and try to update the lockfile in one go
3. In an even later version of yarn, default to adding and missing `integrity` fields in the lockfile whenever performing any operation on it (and hopefully by this point many hashes will have already been added, reducing the number of packages that need fetching)

**Comment by rarkins** [comment]
Is there a way to specify the behaviour of `unsafe-disable-integrity-migration` via CLI option rather than `.yarnrc` ?

**Comment by arcanis** [comment]
Yeah, I think we might do that. The integrity check isn't a breaking change per-se, but the behavior is too unexpected to be by-default right now. So I concur with your plan, except for one point:

- `unsafe-disable-integrity-migration` will default to `true` until the 2.0, but we'll continue adding the `integrity` field to newly added packages (it doesn't have any extra cost - the cost you see is because we need to redo all the resolutions requests to populate the field)

- Starting from the 2.0, `unsafe-disable-integrity-migration` will default to `false`. A major bump is a good signal that this kind of things might happen, so it should be fine.

Depending on whether the CLI mode is implemented by someone before the 2.0 lands, it might make sense to add an intermediary step where `unsafe-disable-integrity-migration` would default to `gentle` (not implemented), where it would only re-resolve at most X dependencies at each install (X=2?). The end result would be the same, but it would feel less intrusive for most users. Not sure about it, feel free to argue against that 🙂

**Comment by arcanis** [comment]
> Is there a way to specify the behaviour of `unsafe-disable-integrity-migration` via CLI option rather than `.yarnrc` ?

@rarkins Yes and no. You must have a yarnrc file, but you can tell Yarn to consider a specific yarnrc file using `--use-yarnrc <path>` (it will still also read the regular yarnrc unless you use `--no-default-rc`, cf #6007).

**Comment by rarkins** [comment]
Although I think this issue is still a good idea generally, I wanted to mention that it's no longer a compelling problem for Renovate or hence for me personally. 

Renovate now auto-switches between 1.9 and 1.10 versions depending on presence of existing `integrity` hashes, which pretty much solves the compatibility challenge. e.g. in this repo once `integrity` hashes were added to `yarn.lock` in `master`, all open Renovate PRs were updated to include/update hashes. 

Example:

![image](https://user-images.githubusercontent.com/6311784/46207089-6aa26000-c326-11e8-8e7c-352cb0ead93e.png)

**Comment by rjmunro** [comment]
@arcanis The "gentle" idea is IMHO terrible. I don't want 2 lines changed in my yarn.lock file every time I install that I then have to commit. I want either all or nothing.

The behaviour should be to detect and preserve the type of the lock file:

* If there is no yarn.lock file or one that already contains integrity entries, use them and generate new ones.
* If there is a 1.9 style yarn.lock file (i.e. it doesn't contain integrity entries), don't put them in, keep the file as it would have been if running with the older version. Print a warning, something like "Using yarn 1.9 compatible lock file; run `yarn upgrade-lock-file` to upgrade and enable integrity checking".

In general, never change the lock file unless I either ask for it, or have changed something relevant in the package.json file. Always keep yarn.lock changes to a minimum. Detect the version of the lock file and keep it consistent with that version.
