### ISSUE TITLE
Add shortcut for saving dependencies

### ISSUE THREAD

**Issue by deadcoder0904** [yarnpkg/yarn#645]
Add shortcut commands like `-S` for `--save` & `-D` for `--dev`

**Comment by MRokas** [comment]
using `yarn add <pkg-name>` does that, however I don't see how to do it for dev-dep

**Comment by montogeek** [comment]
@MRokas https://yarnpkg.com/en/docs/cli/add#toc-yarn-add-dev

**Comment by hawkrives** [comment]
`yarn add --dev $pkg` works, but it's going to take a while for my muscle memory to adapt to `--dev` instead of `-D`…

**Comment by tunnckoCore** [comment]
Yea it would be good to have as more as possible mappings of npm commands/flags

**Comment by MRokas** [comment]
@montogeek  - oh, managed to miss docs link. ty!

**Comment by joshmanders** [comment]
Yeah I was gonna `alias npm=yarn` but typing `npm` triggers muscle memory and I'd mess it all up, haha.

**Comment by ljharb** [comment]
Kind of a duplicate of #649 - please see https://github.com/yarnpkg/yarn/issues/649#issuecomment-252983006 for why adding shortcuts might not be a good idea.

**Comment by wyze** [comment]
Fixed by #1618 and #1653.
