### ISSUE TITLE
Installation Problem: [Impossible de récupérer https://dl.yarnpkg.com/debian/dists/stable/InRelease]

### ISSUE THREAD

**Issue by makotoworkshop** [yarnpkg/yarn#6451]
**Which operating system are you using:**
Debian Stretch

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I've just follow the instruction to add the Debian package repository 

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
OK
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
deb https://dl.yarnpkg.com/debian/ stable main

And then try to install yarn, but 

sudo apt-get update && sudo apt-get install yarn
Atteint:1 http://security.debian.org/debian-security stretch/updates InRelease
Atteint:2 http://forge.yunohost.org/debian stretch InRelease                                     
Ign:3 http://ftp.debian.org/debian stretch InRelease                                             
Atteint:4 http://ftp.debian.org/debian stretch-updates InRelease
Atteint:5 http://ftp.debian.org/debian stretch Release
Lecture des listes de paquets... Fait
E: Le pilote pour la méthode /usr/lib/apt/methods/https n'a pu être trouvé.
N: Is the package apt-transport-https installed?
E: Impossible de récupérer https://dl.yarnpkg.com/debian/dists/stable/InRelease  
E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

Thanks

**Comment by Daniel15** [comment]
> N: Is the package apt-transport-https installed?

`apt-get install apt-transport-https` should fix this.

**Comment by makotoworkshop** [comment]
Sorry i've didn't see this line, i've been focalised on the end line ^^;
Install ok !
Thanks :+1:
