### ISSUE TITLE
Add `yarn i` shorthand

### ISSUE THREAD

**Issue by CYBAI** [yarnpkg/yarn#649]
I always use npm shorthands but `yarn` doesn't allow users to use [aliases](https://github.com/yarnpkg/yarn/blob/master/src/cli/aliases.js#L7) such as `yarn i`. Is it possible to add this feature ?

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
```sh
→ yarn i
yarn i v0.15.1
error Did you mean `yarn install`?
info Visit http://yarnpkg.com/en/docs/cli/i for documentation about this command.
```

**What is the expected behavior?**
```sh
→ yarn i
yarn i v0.15.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 11.33s.
```

**Please mention your node.js, yarn and operating system version.**
Node v6.0.0
yarn 0.15.1
macOS OSX

**Comment by ljharb** [comment]
`npm` has added a litany of aliases over the years - personally I think that adding these mostly undocumented "shortcuts" has made it really hard for users to google for documentation, to know that they're typing the right command, etc.

If yarn adds "i", should it also add every other npm shortcut?

I'd rather see all the shortcuts added such that they immediately error out, instructing the user with the correct command (kind of like `git` does).

**Comment by trappar** [comment]
Also, `yarn install` already has a shortcut - `yarn`.

**Comment by AlicanC** [comment]
No shortcuts please. It's better to save a trip to documentation than save a few keystrokes. You can alias whatever you want anyways.

**Comment by CYBAI** [comment]
@ljharb Agree with your point.  Using a shortcut is hard to google for documentation and like @AlicanC said, I can setup my own alias.
