### ISSUE TITLE
Upgrading a project to plug and play leaves behind an empty node_modules

### ISSUE THREAD

**Issue by edmorley** [yarnpkg/yarn#6496]
**Do you want to request a *feature* or report a *bug*?**
Bug (albeit pretty minor)

**What is the current behavior?**
After converting an existing project directory to use Yarn's new plug and play mode, an empty `node_modules` directory is left behind.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `mkdir testcase && cd testcase`
2. `yarn add lodash`
3. `yarn --pnp`
4. `ls -al node_modules/`

**What is the expected behavior?**
`ls: cannot access 'node_modules/': No such file or directory`

**Please mention your node.js, yarn and operating system version.**
Yarn 1.12.0, Node 10.11.0, reproduces on {Windows 10 x64, Ubuntu 18.04}

**Comment by edmorley** [comment]
So it looks like the contents of `node_modules` is removed not because of any specific plug and play handling, but because the packages end up being treated as extraneous, here:
https://github.com/yarnpkg/yarn/blob/1b78b1aa7387499f44878da61291d6052e5ac5be/src/package-linker.js#L475-L487

My initial thought was that somewhere towards the end of `copyModules()` there could be something like this:

```js
    // Remove any empty modules directories. We only do this when using plug and
    // play, since otherwise the yarn-integrity creation later will fail.
    if (this.config.plugnplayEnabled) {
      for (const folder of this.config.registryFolders) {
        const modulesPath = path.resolve(this.config.lockfileFolder, folder);
        const files = await fs.readdir(modulesPath);
        if (files.length === 0) {
          await fs.unlink(modulesPath);
        }
      }
    }
```

(The conditional is required since in the non-pnp case ((eg removing the last dependency from package.json)), `node_modules` is empty at that point too, since `.yarn-integrity` is removed at the start of install and not recreated until later.)

However it doesn't feel right to have `package-linker.js` make assumptions about what will/won't be using `node_modules` in later steps.

Instead should the cleanup perhaps be added as an additional step in-between one of the ones here?
https://github.com/yarnpkg/yarn/blob/1b78b1aa7387499f44878da61291d6052e5ac5be/src/cli/commands/install.js#L739-L742

@arcanis - any preference? :-)

**Comment by arcanis** [comment]
Yup, adding a function to `Install` that would check if the directory is empty and remove it in this case makes sense to me 👍

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
