### ISSUE TITLE
Installation Problem: Homebrew install broken on High Sierra due to Python 2.7.15

### ISSUE THREAD

**Issue by johnlabarge** [yarnpkg/yarn#6502]
**Which operating system are you using:**
MacOS 10.13.6

**Please describe the steps you took when trying to install Yarn and what went wrong:**
brew install yarn 

➜  universal-app brew install yarn 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core, homebrew/cask).
==> New Formulae
i2pd                       opensubdiv                 tdlib
==> Updated Formulae
abcde                                    jetty-runner
aircrack-ng                              jfrog-cli-go
apache-geode                             jhipster
app-engine-java                          joplin
ark                                      kibana
ballerina                                krakend
bcal                                     kubernetes-service-catalog-client
bettercap                                ldc
bitcoin                                  libepoxy
caffe                                    libphonenumber
cgal                                     links
checkbashisms                            logstash
clamav                                   mariadb
clipper                                  meson
cmake                                    metabase
commandbox                               micronaut
container-diff                           mpv
darksky-weather                          nginx
dita-ot                                  nodebrew
dnscrypt-proxy                           nomad
doctl                                    numpy
elasticsearch                            orc-tools
exercism                                 phoronix-test-suite
fail2ban                                 phpunit
ffmbc                                    poppler
flatbuffers                              prometheus
geckodriver                              puzzles
git                                      rakudo-star
goenv                                    safe
grakn                                    sbcl
gst-editing-services                     shpotify
gst-libav                                skaffold
gst-plugins-bad                          skafos
gst-plugins-base                         strongswan
gst-plugins-good                         suricata
gst-plugins-ugly                         swiftgen
gst-python                               telegraf
gst-rtsp-server                          topgrade
gst-validate                             unrar
gstreamer                                vert.x
haproxy                                  vim
highlight                                yamllint
i2p                                      ykman
ipv6calc                                 youtube-dl
jenkins                                  yubico-piv-tool
jetty                                    zenity
==> Deleted Formulae
asciinema2gif       casperjs            qt@5.5              sonarlint

==> Installing dependencies for yarn: python@2, node
==> Installing yarn dependency: python@2
==> Downloading https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
Already downloaded: /Users/johnlabarge/Library/Caches/Homebrew/downloads/f640fd480ee42d283a98e8e783f14189d6e62323c65f0a098f215eca8319a738--Python-2.7.15.tar.xz
==> ./configure --prefix=/Users/johnlabarge/homebrew/Cellar/python@2/2.7.15_1 --e
==> make
==> make install PYTHONAPPSDIR=/Users/johnlabarge/homebrew/Cellar/python@2/2.7.15
Last 15 lines from /Users/johnlabarge/Library/Logs/Homebrew/python@2/03.make:
    main()
  File "./../../Lib/plat-mac/bundlebuilder.py", line 897, in main
    builder.plist = Plist.fromFile(arg)
  File "/private/tmp/python@2-20181005-79484-s38ow4/Python-2.7.15/Lib/plistlib.py", line 345, in fromFile
    rootObject = readPlist(pathOrFile)
  File "/private/tmp/python@2-20181005-79484-s38ow4/Python-2.7.15/Lib/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/private/tmp/python@2-20181005-79484-s38ow4/Python-2.7.15/Lib/plistlib.py", line 401, in parse
    from xml.parsers.expat import ParserCreate
  File "/private/tmp/python@2-20181005-79484-s38ow4/Python-2.7.15/Lib/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named pyexpat
make[2]: *** [Python Launcher.app] Error 1
make[1]: *** [install_PythonLauncher] Error 2
make: *** [frameworkinstallapps] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by Daniel15** [comment]
Please file this as an issue with Homebrew, as they own the Yarn formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb

Here is their repo: https://github.com/Homebrew/homebrew-core

Thanks!
