### ISSUE TITLE
Yarn Plug & Play ignores updated unplugged packages dependencies 

### ISSUE THREAD

**Issue by ryanwhite04** [yarnpkg/yarn#6508]
The package [@material/mwc-fab](https://github.com/material-components/material-components-web-components/tree/master/packages/fab) is missing `lit-html` as a dependency in it's package.json.

This has already been reported and fixed in the [github repo](https://github.com/material-components/material-components-web-components/issues/132) but hasn't been updated on the npm/yarn registry yet (but will probably be very soon), but until then I need fix it myself.

I've used ```yarn unplug @material/mwc-fab``` and it was placed into **.pnp/unplugged** as expected and is being used instead of the [@material/mwc-fab] in the yarn cache which is awesome.

I added the missing dependency to the package.json using ```yarn add lit-html``` from within ```.pnp/unplugged/npm-@material-mwc-fab-0.3.0-a4a3197285b0699ee1d1f7e7ac2fb6b73e6382d3/node_modules/@material/mwc-fab/```

and the missing depency is now listed in **@material/mwc-fab**'s package.json shown below:

```sed -n 21p .pnp/unplugged/npm-@material-mwc-fab-0.3.0-a4a3197285b0699ee1d1f7e7ac2fb6b73e6382d3/node_modules/@material/mwc-fab/package.json```

```"lit-html": "^0.12.0"```

**Current behavior?**
Requiring the unplugged package with missing dependencies added to the package.json still shows the dependency as missing.

```Error: Package "@material/mwc-fab@0.3.0" (via "/home/ryanwhite04/tab-editor/.pnp/unplugged/npm-@material-mwc-fab-0.3.0-a4a3197285b0699ee1d1f7e7ac2fb6b73e6382d3/node_modules/@material/mwc-fab/mwc-fab.js") is trying to require the package "lit-html" (via "lit-html/directives/classMap") without it being listed in its dependencies (@material/fab, @material/mwc-base, @material/mwc-icon, @material/mwc-ripple, @polymer/lit-element,@material/mwc-fab)```

**If the current behavior is a bug, please provide the steps to reproduce.**

**The expected behavior?**
Now that the dependency has been add to the unplugged copy of the package in it's package.json, it shouldn't have any errors.

**node.js, yarn and operating system version.**
```node --version // v10.10.0```
```yarn --version // 1.13.0-20181002.2034```
```lsb_release -d // Description: Debian GNU/Linux 9.5 (stretch)```

**Comment by arcanis** [comment]
The problem is that the dependencies are resolved before the unplugged dependencies are even processed.

There's a simple workaround though: open your `yarn.lock`, find the entry for `@material/mwc-fab@0.3.0`, and add the dependency there. It will make Yarn think that there's an actual link between those packages, and the generated PnP map will allow the require call 🙂
