### ISSUE TITLE
Gulp does not work with PnP

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/yarn#6516]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
`"start": "gulp"` and `yarn start` does not work with Yarn PnP

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a new project with Gulp 3.9.1 and set the start script to `gulp`, and create a basic gulpfile.

**What is the expected behavior?**
Gulp should start.

**Please mention your node.js, yarn and operating system version.**
```
node --version && yarn --version
v10.11.0
1.13.0-20181004.1524
```

**Comment by arcanis** [comment]
Can you make a repro PR on the [pnp-sample-app](https://github.com/yarnpkg/pnp-sample-app) repository? I've tested with Gulp before so there's likely an environment factor somewhere

**Comment by arcanis** [comment]
Here's the Gulpfile I used: https://github.com/yarnpkg/pnp-sample-app/blob/master/gulpfile.js

**Comment by redeyes2015** [comment]
I can reproduce in pnp-sample-app,

1. Remove .yarnrc in the repository
2. Remove .pnp.js
3. invoke "globally installed" yarn v1.12.1. with `yarn --pnp`
4. `yarn gulp` would report the error

BTW with .pnp.js generated by the yarn.js in the repository, I can run gulp successfully with yarn v1.12.1.

**Comment by redeyes2015** [comment]
Given `.yarnrc` removed (so I can choose which `yarn.js` to use):

1. With `.pnp` and `.pnp.js` generated by `yarn.js` packed in the repository (1.11.0-0), all versions of `yarn` I tested can run `yarn gulp` successfully.
2. With `.pnp` and `.pnp.js` generated by yarn v1.12.1, either "installed globally" or downloaded as a single file and put in the repository, all versions fail to run `yarn gulp`

"all versions":

1. 1.11.0-0 (packed in)
2. 1.11.0-0 copied to elsewhere
3. v1.12.1 "globally installed" [ubuntu package](https://yarnpkg.com/lang/en/docs/install/#debian-stable)
4. v1.12.1 downloaded as a single file put in the repository
5. v1.12.1 downloaded as a single file put elsewhere

Hope this helps.

**Comment by arcanis** [comment]
Thanks! Will take a look

**Comment by arcanis** [comment]
Will be fixed by #6623 👍

**Comment by brianespinosa** [comment]
Thanks @arcanis 

I see that your PR has been merged. Do you know if there is going to be a patch version bump of yarn to 1.12.2 that includes this? We just updated our yarn version today and this broke our builds.

**Comment by arcanis** [comment]
Hey @brianespinosa ! There are a few other fixes I'd prefer to land before releasing the 1.12.2 (ETA ~ a week, I'd say), but in the meantime you can use our [nightly build](http://nightly.yarnpkg.com/latest.js), which already includes it 🙂 

Would that work for you?

**Comment by brianespinosa** [comment]
@arcanis ~a week should be fine. I just updated the config in our package.json telling it to not use pnp for now and everything is fine again. I can give it another shot when the patch lands. Thanks again!

**Comment by brianespinosa** [comment]
@arcanis I just got around to testing this again. I am now running yarn 1.13.0 and when I run `yarn gulp myCommand` I get a message: 
```
Local gulp not found in ~/myProject
[11:40:52] Try running: npm install gulp
```

**Comment by brianespinosa** [comment]
Ah! The trick here was to delete the old `yarn.lock` file and get an install from scratch. Now it does actually work. Thanks @arcanis!

**Comment by asolopovas** [comment]
same here

**Comment by merceyz** [comment]
Closing as fixed in https://github.com/yarnpkg/yarn/pull/6623

**Comment by bpsbais** [comment]
Now yarn reached at it's version 3.0.0 and gulp reached at 4.0.2
But gulp is still not working in yarn pnp mode.

To run gulp in yarn we have to change yarn's mode pnp to node-modules as follow.

1. insert `nodeLinker: node-modules` into `.yarnrc.yml` file.
2. run `yarn install`
3. now you can run gulp.

But we lost plug and play feature of yarn.

**Comment by SudoNova** [comment]
> Now yarn reached at it's version 3.0.0 and gulp reached at 4.0.2 But gulp is still not working in yarn pnp mode.
> 
> To run gulp in yarn we have to change yarn's mode pnp to node-modules as follow.
> 
>     1. insert `nodeLinker: node-modules` into `.yarnrc.yml` file.
> 
>     2. run `yarn install`
> 
>     3. now you can run gulp.
> 
> 
> But we lost plug and play feature of yarn.

Same here. STILL doesn't work
