### ISSUE TITLE
yarn fails to install

### ISSUE THREAD

**Issue by SirZach** [yarnpkg/yarn#653]
**Do you want to request a _feature_ or report a _bug_?**
Reporting bug

**What is the current behavior?**
`yarn` command fails.

```
yarn install v0.15.1
info No lockfile found.
error EISDIR: illegal operation on a directory, read
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Running `yarn` where I would normally run `npm install`

**What is the expected behavior?**
For `yarn` to install packages

**Please mention your node.js, yarn and operating system version.**
node: 4.5.0 yarn: 0.15.1 OS - Mac OS El Capitan

**Comment by mmmeff** [comment]
I fixed this by adding a license field to my package.json. See #646

**Comment by TheJaredWilcurt** [comment]
This is a different error than missing license. I have the same error. My `package.json` contains:

```
    "license": "MIT",
    "licenses": [{
        "type": "MIT",
        "url": "https://github.com/scout-app/scout-app/blob/master/License"
    }]
```

**Comment by rmmcnulty9** [comment]
This is probably related to #680. If it is a missing license field, it could that a dependency is missing it. It is a shame the error message is so unhelpful.

**Comment by TheJaredWilcurt** [comment]
I have the license stuff in package.json, but I also have "License" directory in the root of my project (as mentioned in #680). Why would that prevent yarn from working.

**Comment by SirZach** [comment]
If a dependency missing a license field is the problem then I don't see this ever working.

**Comment by busches** [comment]
@SirZach are you still getting this with `yarn@latest`? Can you provide a `package.json` that replicates the issue?

**Comment by SirZach** [comment]
@busches haven't tried since I opened the issue. it can probably be closed if it can't be replicated with latest. I don't have time to try again right now

**Comment by voxsim** [comment]
@bestander I think you can close this.

**Comment by codertjay** [comment]
i still get the same error on my yarn

yarn cache v1.22.5
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at onUnexpectedError (C:\Program Files (x86)\Yarn\lib\cli.js:88476:106)
    at C:\Program Files (x86)\Yarn\lib\cli.js:88595:9
