### ISSUE TITLE
There appears to be trouble with your network connection.

### ISSUE THREAD

**Issue by tooyangski** [yarnpkg/yarn#6531]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Cant install dependencies whenever I run yarn it says "there appears to be trouble  with your network connection, I tried lan with a proxy and added it to yarn and it doesnt work, also tried home wifi which doesnt have any proxy. Same with NPM

**If the current behavior is a bug, please provide the steps to reproduce.**

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js

PATH: 
  C:\Users\apungaas\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\apungaas\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\xampp\php;C:\xampp\composer;C:\Program Files (x86)\Yarn\bin;C:\Users\apungaas\AppData\Local\Microsoft\WindowsApps;C:\Users\apungaas\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\apungaas\AppData\Roaming\npm;C:\Users\apungaas\.dotnet\tools;C:\Users\apungaas\AppData\Roaming\Composer\vendor\bin;C:\Users\apungaas\AppData\Local\Yarn\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

Yarn version: 
  1.10.1

Node version: 
  8.12.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/axios: tunneling socket could not be established, statusCode=407
      at ClientRequest.onConnect (C:\Program Files (x86)\Yarn\lib\cli.js:132507:19)
      at Object.onceWrapper (events.js:319:30)
      at emitThree (events.js:136:13)
      at ClientRequest.emit (events.js:217:7)
      at Socket.socketOnData (_http_client.js:475:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)

npm manifest: 
  {
      "private": true,
      "scripts": {
          "dev": "npm run development",
          "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
          "watch": "npm run development -- --watch",
          "watch-poll": "npm run watch -- --watch-poll",
          "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
          "prod": "npm run production",
          "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
      },
      "devDependencies": {
          "axios": "^0.18",
          "bootstrap": "^4.0.0",
          "cross-env": "^5.1",
          "jquery": "^3.2",
          "laravel-mix": "^2.0",
          "lodash": "^4.17.5",
          "popper.js": "^1.12",
          "vue": "^2.5.7"
      }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
nodejs - v8.12.0
yarn - 1.10.1
npm - 6.4.1

**Comment by tiancihe** [comment]
Try commenting out `http_proxy` and `https_proxy` in your `~/.bashrc`, restart your terminal and try again.

**Comment by paul-soporan** [comment]
Closing as most likely fixed in v2, where the timeout and retry logic has greatly improved.

https://yarnpkg.com/getting-started/migration
