### ISSUE TITLE
Packages duplication with pnp

### ISSUE THREAD

**Issue by sunflowerdeath** [yarnpkg/yarn#6534]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

As I understood from [this comment](https://github.com/yarnpkg/yarn/blob/9028f9a3677da1cd14babec82e194c906dfe5de0/src/util/generate-pnp-map.js#L235-L242), if a module has peer dependencies and occurs more than once, each occurence will be extracted to separate place, because yarn cannot ensure that in all cases its peer dependencies will be the same.

But this causes a problem, firstly the modules are duplicated, which increases size of the bundle, and secondly, such things as the react context may not work correctly.

Here is an example repository that demonstrates this problem - https://github.com/sunflowerdeath/pnp-test

There are three packages in it:
- package `context` exports react context, and a component that consumes it
- package `component` uses context consumer component from the package `context`
- package `app` imports `context` package and provides new value through it and then renders component from the package `component`

Without pnp it works correctly, but with pnp, packages `component` and `app` imports package `context` from different locations, and  create two different React contexts.

Without pnp:

```
cd app
yarn install
yarn start
```
Then open http://localhost:8080/
You should see `App context value` and this is correct behaviour

With pnp:

```
yarn install --pnp
yarn start
```

Now page renders `Default value`, this is incorrect

**Comment by merceyz** [comment]
Closing as fixed in v2 where PnP does not use symlinks

https://yarnpkg.com/getting-started/migration
