### ISSUE TITLE
yarn install tries to use package.json on my desktop

### ISSUE THREAD

**Issue by cemremengu** [yarnpkg/yarn#6537]
When using yarn install in another directory on my desktop, I noticed that it is actually using  some other `package.json` found on my desktop (which was malformed for test purposes) and I spent an hour to figure out whats going on. Is this expected maybe for `lerna` projects?

**What is the current behavior?**
Uses `package.json` on desktop (or from the upper directory but I didnt test that).

Create a folder on desktop with `package.json`, create another malformed package.json on desktop and run `yarn` from the folder. It should fail.

`error ..\package.json: Name contains illegal characters`

**What is the expected behavior?**
Use `package.json` from current dir.

Using: Windows 10
yarn v1.10.1 (I tried other versions, same thing)

**Comment by arcanis** [comment]
Yarn (since 1.0) will crawl the folder hierarchy until it finds the closest `package.json` it can uses.

**Comment by cemremengu** [comment]
I see but why doesnt it prefer the one immediately next to it?

**Comment by arcanis** [comment]
I'm not sure what you mean actually :) 

> Create a folder on desktop with package.json, create another malformed package.json on desktop

If I follow those instructions, I have two `package.json` file on desktop, which is obviously impossible. I'll need exact repro steps (with full paths) to help you.

**Comment by cemremengu** [comment]
The `package.json` on desktop is empty (invalid). The `package.json` inside the test folder is valid generated by npm. However, as you can see it attempts to use the one in desktop.

![image](https://user-images.githubusercontent.com/1297759/46920822-7c5d5600-cffc-11e8-87dc-7510987ab974.png)

**Comment by arcanis** [comment]
Oh, I see. This is because it tries to read the `package.json` hierarchy to find out if the current folder is part of a workspace.

**Comment by cemremengu** [comment]
I see, wasn't aware of this thanks for the info. Maybe a log line can be added to let users know that a `package.json` file was discovered in the upper level hierarchy and it's being used.
