### ISSUE TITLE
Add `yarn cache dir` to output cache directory

### ISSUE THREAD

**Issue by cnolimit** [yarnpkg/yarn#654]
When reading the blog post it stated that during the fetching phase/step, `yarn` looks inside the `global cache directory`. Which folder is this exactly?

[![Screen Shot 2016-10-11 at 18.19.36.png](https://s3.postimg.org/yqgn469f7/Screen_Shot_2016_10_11_at_18_19_36.png)](https://postimg.org/image/4yjkozmlr/)

**Comment by montogeek** [comment]
`~/.yarn-cache`

**Comment by ljharb** [comment]
`npm` offers a number of `npm cache` commands - could `yarn` offer the same?

**Comment by montogeek** [comment]
It should :)

**Comment by sindresorhus** [comment]
```
yarn cache ls
yarn cache clean
```

**Comment by ljharb** [comment]
ideally `yarn cache dir` or something would print out the path (npm doesn't have this, sadly)

**Comment by kittens** [comment]
Created #880 to fix this, pending approval.

**Comment by manojlds** [comment]
Not related, but is there a way to change the yarn cache dir?

**Comment by xzyfer** [comment]
npm also expose the cache dir the script environment as `process.env.npm_config_cache`. Is this covered also?
