### ISSUE TITLE
Problem: Connection Timeouts with Docker builds.

### ISSUE THREAD

**Issue by sr229** [yarnpkg/yarn#6546]
Cross-linking ppy/osu-web#3788.

**What is the current behavior?**
Connection timeouts has been observed during docker builds. It seems to happen on the reporter only after a number of times to attempt to reproduce it.

![image](https://user-images.githubusercontent.com/14976516/47091349-4c5dbf00-d257-11e8-9cff-cb9c0ba14495.png)

**What is the expected behavior?**
Expected behavior is a completed Yarn install task.

**Please mention your node.js, yarn and operating system version.**

OS: Windows 10

Node.js Version - Docker image`node:8-alpine`-supplied version (8.12.0).

Yarn Version - Docker image `node:8-alpine`-supplied version (1.9.4).

**Comment by sr229** [comment]
CC @TPGPL - the OP for the original issue on ppy/osu-web

**Comment by TPGPL** [comment]
after trying again i got a new error: https://pastebin.com/NDRY64yZ

**Comment by sr229** [comment]
Triage update: Switching resolvers does not solve the reporter's issue at the moment.

**Comment by sr229** [comment]
Triage complete: It seems the fault was with the Google Public DNS resolver @TPGPL uses. Yarn now proceeds properly with some timeouts recorded.

Closing as this was self-solved.
