### ISSUE TITLE
Possible Windows Incompatability Problem

### ISSUE THREAD

**Issue by AlexMachin1997** [yarnpkg/yarn#6557]
**Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug as suggested by Mael - https://twitter.com/arcanis/status/1053032265113055236 

**What is the current behavior?**
The current behaviour is when "npx create-react-app my-app --use-pnp" command is run I get the following error 
![image](https://user-images.githubusercontent.com/29917195/47185164-919bf280-d324-11e8-9174-6a52c2770b9d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
- Download yarn 1.12 on windows 10
- run the "npx create-react-app my-app --use-pnp"

**What is the expected behavior?**
The expected behaviour is that create-react-app should be created with plug and play functionality ie no node_Modules.
 
**Please mention your node.js, yarn and operating system version.**
Wndows 10 - 1803
NodeJS - 8.12.0
yarn - 1.12

Any additional notes required just let me know in the comments below.

**Comment by arcanis** [comment]
I think this is simply related to the following regexp, which doesn't cover absolute Windows paths:

https://github.com/yarnpkg/yarn/blob/master/src/util/generate-pnp-map-api.tpl.js#L36

cc @jdalton

**Comment by jdalton** [comment]
Thanks for the ping. I'll dig into it.

**Comment by arcanis** [comment]
Fixed in #6495 - the PR isn't ready to be landed yet (there's other incompatibilities we need to fix first, such as #6493), but it's a good start 😃

**Comment by jdalton** [comment]
Beat me to it 😋

**Comment by AlexMachin1997** [comment]
Awesome work guys 💪 👍 💯 💪 

Sorry for incredibly late response, been super busy with my personal studies at university. Only just got around to checking all my notifications on Githhub. 

Is this issue safe to close now?

**Comment by arcanis** [comment]
Yup! 👍
