### ISSUE TITLE
Non-conflicting dependence was not promoted to the top node_modules

### ISSUE THREAD

**Issue by yuzima** [yarnpkg/yarn#6558]
- node: 8.11.3
- macOS: 10.13.5
- yarn: 1.9.4
- npm: 5.6.0

package.json
```json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "docz": "^0.12.5",
    "react": "16.3.2"
  }
}
```

`docz` has a dependence `docz-theme-default` and it was expected to be installed in the  `./node_modules` directory, but it was installed in `./node_modules/docz/node_modules`.

Then I tried to use npm which worked as I expected.

**The interesting thing is this problem only happened with the exact react verison**

According to what I know, in both `yarn` and `npm >= 3`, the non-conflicting dependence should be installed in the top `node_modules` directory, so I would like to know what cause this problem.

**Comment by arcanis** [comment]
Relying on the hoisting is an undefined behavior, Yarn is free to do whatever it wants as long as the reported dependencies are satisfied.

If you want to be sure you'll be able to access a dependency, you *must* declare it in your own dependency fields.
