### ISSUE TITLE
404 on "deb https://dl.yarnpkg.com/debian/ stable main"?

### ISSUE THREAD

**Issue by diegotrigo** [yarnpkg/yarn#6566]
Hi there,
Is anyone else having 404 when running the command below via docker:
`deb https://dl.yarnpkg.com/debian/ stable main`

That's my full docker command:
`RUN apt-get update \
    && apt-get install -y apt-transport-https \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn`

And it returns 404 for two packages:
`W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found`

`W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found`

Not sure if it's a problem with Yarn, or if Debian updates its path?
Debian's FTP still works fine: http://ftp.debian.org/debian/dists/jessie/main/binary-amd64/, so I'm assuming it's a problem with Yarn's default path?

Any help would really appreciate.

Thanks,
D

**Comment by diegotrigo** [comment]
More info:
![image](https://user-images.githubusercontent.com/1778279/47327409-e8088880-d6b8-11e8-8259-efd08d1a2ca1.png)

**Comment by diegotrigo** [comment]
hmm.. Looks like it's back online now. Thanks anyway.

**Comment by Daniel15** [comment]
Your screenshot shows a 404 for `deb.debian.org`, not for the Yarn repo.
