### ISSUE TITLE
Questions on install scripts and native node.js modules.

### ISSUE THREAD

**Issue by thekemkid** [yarnpkg/yarn#657]
Install scripts: Are they a thing of the past?

Considering that so many packages rely heavily on them, it seems prudent to ask, but it makes life a lot more difficult with the security issues concerning them: https://blog.liftsecurity.io/2015/01/27/a-malicious-module-on-npm

What about native modules for node.js? Are they not a priority? I ask because _in the case_ that install scripts are disabled, we can't run node-gyp to compile them when installing. And even _if_ we can run install scripts and run a build, we _still_ cant have a deterministic build artifact as compiler tooling varies wildly.

There is also node-pre-gyp, some more prior art, which tackles this problem. This allows developers to publish their build artifacts to the cloud for users to download (it supports S3 natively).

Would something like this be considered integrating with, so users can have deterministic installs of native modules? I think there is some leg room for much easier integration of native modules.

**Comment by bestander** [comment]
I am not happy about scripts either, I think Yarn should integrate better with native build tools instead of shelling out to arbitrary commands the maintain their own caches, builds and downloads.

I'll close this for now as we can't act on this issue in particular.
