### ISSUE TITLE
error Command failed with exit code 1 on yarn run dev-server

### ISSUE THREAD

**Issue by loveneet4** [yarnpkg/yarn#6579]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by arcanis** [comment]
That's not a Yarn problem - `dev-server` is your own script.

**Comment by loveneet4** [comment]
i solved  it
