### ISSUE TITLE
Save yarn version number in yarn.lock

### ISSUE THREAD

**Issue by ondrejsevcik** [yarnpkg/yarn#6582]
Hi, sometimes when I install dependencies with `yarn` suddenly there are `yarn.lock` changes. It's most likely because I use different version of yarn then the `yarn.lock` was created with. I don't know if that's because I have an older version or newer version of yarn than the lockfile was created with.

It would be useful to see what version `yarn.lock` file was created with so I can upgrade (or downgrade) my yarn as needed. It also helps to keep up whole dev team on the same version so that we're not constantly overwriting dependencies when our yarn version differs.

My idea was to keep the version number in the comment in the top of the file
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
# generated with yarn v1.10.1
```

What do you think?

**Comment by paul-soporan** [comment]
Closing as fixed in v2, where there is a lockfile version that we bump each time we make changes to the lockfile generation and that is stored inside the lockfile.

https://yarnpkg.com/getting-started/migration
