### ISSUE TITLE
Problem with yarn add <alias-package>

### ISSUE THREAD

**Issue by petrgazarov** [yarnpkg/yarn#6588]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Let's say there are two packages named @package-a and @package-b. @package-b dependends on @package-a. @package-b's package.json includes:
```
"dependencies": {
  "@package-a": "1.0.0"
}
```
In @package-b's code, @package-a is required like so:
```
const packageA = require('@package-a');
```
I'm using both @package-a and @package-b in my code. I plan to use multiple versions of each, so I use aliasing to add them by different names.
```
"dependencies": {
  "@package-a-version-1.0.0": "npm:@package-a@1.0.0,
  "@package-b-version-1.0.0": "npm:@package-b@1.0.0,
}
```
In my script, I require @package-b-version-1.0.0 like so:
```
const packageB = require('@package-b-version-1.0.0');
```
And get error:
```
Error: Cannot find module @package-a
```

Looks like yarn did not install @package-a by its original un-aliased name, and @package-b's dependency is not met.

**If the current behavior is a bug, please provide the steps to reproduce.**

Public repo which contains a reproduction of the problem:
https://github.com/petrgazarov/yarn-including-multiple-versions-of-a-package

**What is the expected behavior?**

Script should resolve @package-a correctly.

**Please mention your node.js, yarn and operating system version.**
node v8.11.3
yarn 1.7.0
MacOS 10.13.5

**Comment by arcanis** [comment]
Don't put a `@` in front of them. This will confuse the hell out of Yarn (the `@` character is reserved for scopes).

**Comment by arcanis** [comment]
Just checked your sample repository, it looks like you aren't adding the `@` for real, so nevermind 🙂 

The aliasing implementation is a bit weird, so problems like this don't surprise me. It's quite possible the aliasing doesn't take the hoisting into account. Can you try this code with Plug'n'Play enabled? Since it doesn't use the hoister, it's possible things will work better there.

**Comment by serg06** [comment]
@petrgazarov I'm getting the same thing when aliasing:

```
... This could result in non-deterministic behavior, skipping.
```

Can you share how you resolved it?

**Comment by petrgazarov** [comment]
@serg06 Can't recall if this was ever solved properly (no longer work on that project), but if this is still an issue I can reopen.
