### ISSUE TITLE
Package not installing

### ISSUE THREAD

**Issue by kingOfTheWizard** [yarnpkg/yarn#6590]
Trying to migrate from bower to yarn.
After using bower-away, I run the _yarn install_  and I get error.
This is the full error log:

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js --ignore-engines --ignore-scripts

PATH: 
  C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Ruby22-x64\bin;C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files (x86)\WinSCP\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\git-cola\bin;C:\Program Files\;C:\Program F;C:\Program Files\TortoiseSVN\bin;C:\gnuWin32\gnuwin32\bin;C:\Program Files\Perforce\DVCS\;C:\Program Files\gradle-2.11\bin;C:\MinGW\bin;C:\Program Files\Apache Software Foundation\apache-maven-3.3.9\bin;C:\Program File;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Users\talor\.cargo\bin;C:\Program Files\Apache Software Foundation\apache-maven-3.3.9\bin;C:\ProgramData\Hewlett-Packard\PC COE\VSC\Drivers\;C:\Program Files\Docker Toolbox;C:\Users\talor\AppData\Local\atom\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\talor\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\talor\AppData\Roaming\npm;C:\Users\talor\AppData\Local\Yarn\bin

Yarn version: 
  1.10.1

Node version: 
  8.12.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@bower_components%2fally.js: Not found
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\cli.js:60182:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\lib\cli.js:120166:22)
      at emitTwo (events.js:126:13)
      at Request.emit (events.js:214:7)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:121138:10)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:121060:12)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:111:20)

npm manifest: 
  {
    "name": "bowerToNpm",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "dependencies": {
      "@bower_components/ally.js": "medialize/ally.js/releases/download/1.0.1/ally.js.zip#*",
      "@bower_components/angular": "angular/bower-angular#~1.5",
      "@bower_components/angular-animate": "angular/bower-angular-animate#~1.4.0",
      "@bower_components/angular-aria": "angular/bower-angular-aria#~1.4.4",
      "@bower_components/angular-cache-buster": "saintmac/angular-cache-buster#0.4.3",
      "@bower_components/angular-cookies": "angular/bower-angular-cookies#~1.4.0",
      "@bower_components/angular-dynamic-locale": "lgalfaso/angular-dynamic-locale#0.1.21",
      "@bower_components/angular-http-auth": "witoldsz/angular-http-auth#~1.2.2",
      "@bower_components/angular-i18n": "angular/bower-angular-i18n#~1.4.7",
      "@bower_components/angular-local-storage": "grevory/angular-local-storage#~0.2.2",
      "@bower_components/angular-mocks": "angular/bower-angular-mocks#~1.4.4",
      "@bower_components/angular-raf": "develersrl/angular-raf#~0.0.4",
      "@bower_components/angular-resource": "angular/bower-angular-resource#~1.4.4",
      "@bower_components/angular-route": "angular/bower-angular-route#~1.4.4",
      "@bower_components/angular-sanitize": "angular/bower-angular-sanitize#~1.4.4",
      "@bower_components/angular-spinkit": "Urigo/angular-spinkit#~0.3.3",
      "@bower_components/angular-translate": "PascalPrecht/bower-angular-translate#~2.8.1",
      "@bower_components/angular-translate-interpolation-messageformat": "PascalPrecht/bower-angular-translate-interpolation-messageformat#~2.8.1",
      "@bower_components/angular-translate-loader-static-files": "PascalPrecht/bower-angular-translate-loader-static-files#~2.8.1",
      "@bower_components/angular-translate-storage-cookie": "PascalPrecht/bower-angular-translate-storage-cookie#~2.8.1",
      "@bower_components/angular-translate-storage-local": "PascalPrecht/bower-angular-translate-storage-local#~2.8.1",
      "@bower_components/angular-ui-router": "angular-ui/angular-ui-router-bower#^0.3.1",
      "@bower_components/css-toggle-switch": "ghinda/css-toggle-switch#~4.0.1",
      "@bower_components/d3": "mbostock-bower/d3-bower#~3.5.5",
      "@bower_components/es5-shim": "es-shims/es5-shim#^4.5.10",
      "@bower_components/es6-shim": "paulmillr/es6-shim#~0.33.10",
      "@bower_components/fastclick": "ftlabs/fastclick#>=0.6.11",
      "@bower_components/foundation": "zurb/bower-foundation#~5.5.0",
      "@bower_components/foundation-sites": "zurb/foundation-sites#~6.1.1",
      "@bower_components/grommet": "HewlettPackard/grommet-bower#~0.4.1",
      "@bower_components/jquery": "jquery/jquery-dist#~2.1.4",
      "@bower_components/jquery-placeholder": "mathiasbynens/jquery-placeholder#~2.0.7",
      "@bower_components/jquery-ui": "components/jqueryui#~1.11.4",
      "@bower_components/jquery-ui-daterangepicker": "tamble/jquery-ui-daterangepicker#~0.3.4",
      "@bower_components/jquery.cookie": "carhartl/jquery-cookie#~1.4.0",
      "@bower_components/json3": "bestiejs/json3#3.3.2",
      "@bower_components/messageformat": "SlexAxton/messageformat.js#~0.2.2",
      "@bower_components/modernizr": "Modernizr/Modernizr#2.8.3",
      "@bower_components/moment": "moment/moment#~2.10.3",
      "@bower_components/ng-file-upload": "danialfarid/angular-file-upload-bower#~9.0.9",
      "@bower_components/ng-file-upload-shim": "danialfarid/angular-file-upload-shim-bower#~10.1.8",
      "@bower_components/ngDialog": "likeastore/ngDialog#~0.3.11",
      "@bower_components/oclazyload": "ocombe/ocLazyLoad#~1.0.9",
      "@bower_components/react": "facebook/react-bower#^0.13.1",
      "@bower_components/requirejs": "jrburke/requirejs-bower#~2.1.20",
      "@bower_components/swagger-ui": "wordnik/swagger-ui#2.0.18",
      "@bower_components/tooltipster": "iamceege/tooltipster#~3.3.0",
      "@bower_components/what-input": "ten1seven/what-input#~1.1.2"
    },
    "engines": {
      "yarn": ">= 1.0.0"
    },
    "scripts": {
      "postinstall": "node -e \"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'bower_components', 'junction') } catch (e) { }\""
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by rally25rs** [comment]
That one `ally.js` dependency has a format that yarn is getting confused on. Instead of trying to download it, it's trying to resolve it from the npm registry.

Looks like you can fix it by changing that dependency to:
```
"@bower_components/ally.js": "medialize/ally.js#1.0.1",
```
which represents the GitHub `user/repo#tag` to use.
