### ISSUE TITLE
Yarn Workspaces stopped working—Cannot find modules

### ISSUE THREAD

**Issue by davidrhoderick** [yarnpkg/yarn#6597]
I'm running the following:

- Yarn version 1.10.1
- node version 11.0.0
- npm 6.4.1
- Pop!_OS 18.04 LTS

I just reinstalled node and npm with linuxbrew as well as including n for version control (I had been using nvm but it wasn't working well, just like before).

**Do you want to request a *feature* or report a *bug*?**
This is a bug.  Maybe there is a solution in the issues but I can't be sure because there are just too many.  This also may be a bug with the configuration of npm but I can't tell and would like someone to point that out to me if it is the case.

**What is the current behavior?**
I have the following workspaces setup for yarn:

package.json in root directory:

```
{
  "name": "some-app",
  "version": "1.0.0",
  "main": "index.php",
  "repository": "https://github.com/some-repo.git",
  "author": "My Name <my@email.address>",
  "license": "MIT",
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
```
And in packages I have two folders, one called shivermetimbers-frontend and another called shivermetimbers-gulp.  In shivermetimbers-frontend, I have the following package.json file:

```
{
  "name": "shivermetimbers-frontend",
  "version": "1.0.0",
  "main": "index.php",
  "repository": "https://github.com/timber/starter-theme.git",
  "author": "My Name <my@email.address>",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.1.3",
    "jquery": "^3.3.1",
    "popper.js": "^1.14.4"
  }
}
```
And this .yarnrc file:
```
--*.modules-folder "../../static/vendor"
```
And in shivermetimbers-gulp, I have this package.json file:
```
{
  "name": "shivermetimbers-gulp",
  "version": "1.0.0",
  "main": "index.php",
  "repository": "https://github.com/timber/starter-theme.git",
  "author": "My Name <my@email.address>",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "browser-sync": "^2.26.3",
    "gulp": "^3.9.1",
    "gulp-include": "^2.3.1",
    "gulp-jshint": "^2.1.0",
    "gulp-minify": "^3.1.0",
    "gulp-sass": "^4.0.1",
    "jshint": "^2.9.6",
    "shivermetimbers-frontend": "^1.0.0"
  }
}
```
And this .yarnrc file:
```
--*.modules-folder "../../node_modules"
```
When I run `yarn install`, I get the following errors:
```
warning Error running install script for optional dependency: "/home/myusername/Development/vvv/www/someproject/public_html/wp-content/themes/some-theme/static/vendor/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/myusername/Development/vvv/www/someproject/public_html/wp-content/themes/some-theme/static/vendor/phantomjs-prebuilt
Output:
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/myusername/Development/vvv/www/someproject/public_html/wp-content/themes/some-theme/static/vendor/phantomjs-prebuilt/install.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)"
info This module is OPTIONAL, you can safely ignore this error
error /home/myusername/Development/vvv/www/someproject/public_html/wp-content/themes/some-theme/static/vendor/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /home/myusername/Development/vvv/www/someproject/public_html/wp-content/themes/some-theme/static/vendor/node-sass
Output:
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/myusername/Development/vvv/www/someproject/public_html/wp-content/themes/some-theme/static/vendor/node-sass/scripts/install.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```
After the errors, I get the creation of a node_modules containing a .bin folder in shivermetimbers-gulp and the vendor folder as specified by shivermetimbers-frontend/.yarnrc, but it contains hundreds of modules as opposed to the requirements in the respective package.json.  Obviously nothing works because my gulp dependencies are missing and it's a mess since everything is installed in the vendor folder.

These errors have been persisting since my previous install of node and npm from I believe a package manager and version managed by nvm as well as through the most recent linuxbrew reinstall and version managed by n.  However, I still think that maybe there could be a permissions related issue as the Linux installation of node and npm have so many variations, all which are insufficiently complete (sometimes requiring creating folders and changing ownership manually, others that flat out don't work).  However, as it is related to my specific usage with yarn, I'd like to see if there is a solution in this community.

**What is the expected behavior?**
The expected behavior is that I run yarn install in my root directory, a folder called vendor is created in my static folder that contains only my frontend dependencies (bootstrap, jquery, etc), and another node_modules folder is created in the root directory for my gulp automation and testing dependencies.  I did get this result when I initially set up this yarn project with workspaces but when I last went to add an npm module with yarn (maybe this is what messed everything up), I got these errors.  Since then, I can't revive the project at all.

**Comment by davidrhoderick** [comment]
As a follow-up, it looks like everything installs if the .yarnrc files are removed, but that seemingly defeats the purpose of my workspaces (which is to separate two different parts of the project to separate folders).

**Comment by davidrhoderick** [comment]
So downgrading to LTS for node (8.12.0) and changing "../../static/vendor" to "../../static/node_modules" alleviates the errors but the workspaces don't do anything.  All the dependencies are installed in both node_modules folders, which defeats the purpose of using workspaces.

**Comment by davidrhoderick** [comment]
I actually now think that the issue is all to do with the modules-folder settings in .yarnrc files, which are basically incompatible with workspaces in yarn.  Should I branch this into another issue or edit the title to fit correctly?

**Comment by rally25rs** [comment]
I'm actually surprised it picked up `.yarnrc` in each submodule. I kinda thought it just used the one in the root workspace. 🤷‍♂️ 

Since a large part of the purpose for workspaces is to only have  1 copy of the modules that a bunch of projects depend on (install once at the root instead of multiple times in sub projects) setting a different module path per workspace project seems to go against the purpose.

This might be a bug, or just a weird use case, or... I'm not totally sure what "correct" would be in this case I guess.

**Comment by arcanis** [comment]
> setting a different module path per workspace project seems to go against the purpose.

Yep, it's quite incorrect.

Yarn reads the yarnrc in the cwd and its ancestors (and some other directories for legacy reasons). The CLI options are then added to the command line transparently. What this mean is that your setup will cause Yarn to behave entirely differently depending on the workspace you're currently into ... which as you can guess doesn't make much sense.

We don't support multiple `modules-dir`.

**Comment by davidrhoderick** [comment]
Oh well, I switched back to just NPM with Bower.  I think it would be nice if workspaces also allowed for multiple .yarnrc files but if it isn't in the general interest, I guess I'm out of luck.  I may see if there is a way I can get it to work but I don't have time now.  Thanks for the responses!

**Comment by milesj** [comment]
Why not migrate away from Bower since it's been deprecated for years?

**Comment by davidrhoderick** [comment]
Well, that's what I was trying to do with Yarn but I really don't like how it puts all of the dependencies in one folder.  node_modules is such a mess when using it for gulp or grunt tools and often, front-end components have varying directory structures.  Sometimes scss files are in `src/scss` and sometimes they are in `./scss`, sometimes js files are in `dist/js` and sometimes they are in `src/js`.  I don't like opening `node_modules` to see this huge amount of folders only to search for the few front-end dependencies that I need to include.  Plus, if I was working with a team that had varying setups (which I can imagine having just migrated from CodeKit to grunt and node), perhaps I just want to include the dependencies in my source control.  If I can separate them into their own folder, then we can ensure that the versions used are always consistent regardless of who is accessing the project.

As for using bower, I know it's been deprecated for some time but it looks like they are back to actively maintaining it.  I know that even they say that devs should switch to Yarn (no thank you after this experience) or WebPack (I will try this at some point in time) but if it is now being maintained, I'm going to use something that has worked excellently for me in the past, whether via command line or through CodeKit.
