### ISSUE TITLE
yarn upgrade package --latest not upgrading to latest version despite of "*" constraint

### ISSUE THREAD

**Issue by juanpaucar** [yarnpkg/yarn#6598]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**

I have a project where I'm installing the latest version of the type definition for D3. I'm also using D3 v5 (since D3 v4 has different type definitions). I added the latest `@types/d3` version which has a "*" constraint for `@types/d3-array` and when I try to install the latests version, it keeps installing a one year old version.

```sh
➜  project git:(master) ✗ yarn why @types/d3-array
yarn why v1.10.1
[1/4] Why do we have the module "@types/d3-array"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@types/d3-array@1.2.1"
info Reasons this module exists
   - "@types#d3" depends on it
   - Hoisted from "@types#d3#@types#d3-array"
   - Hoisted from "@types#d3#@types#d3-contour#@types#d3-array"
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
Done in 0.92s.

```

```
"dependencies": {
  "d3": "^5.0.0"
},
"devDependencies": {
  "@types/d3": "^5.0.1"
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Add both dependencies to package.json
- `yarn install`
- `yarn upgrade @types/d3-array --latest`
- check `yarn.lock`

I get this versions on the yarn.lock

```
"@types/d3-array@*":
  version "1.2.1"
  resolved "https://registry.yarnpkg.com/@types/d3-array/-/d3-array-1.2.1.tgz#e489605208d46a1c9d980d2e5772fa9c75d9ec65"
  integrity sha512-YBaAfimGdWE4nDuoGVKsH89/dkz2hWZ0i8qC+xxqmqi+XJ/aXiRF0jPtzXmN7VdkpVjy1xuDmM5/m1FNuB6VWA==

.
.
.

"@types/d3-contour@*":
  version "1.2.2"
  resolved "https://registry.yarnpkg.com/@types/d3-contour/-/d3-contour-1.2.2.tgz#b32256b55aed9e2113f88a8ea23846e357fa386c"
  integrity sha512-2BIp8c80HWJP/K6t7hov6CX6G/9LWPaf1IkRXmAY3xRDr293u6OxQDSsJNc8IHl3SDWfrUw9mZhBIavS5UOGKg==
  dependencies:
    "@types/d3-array" "*"
    "@types/geojson" "*"
.
.
.
"@types/d3@^5.0.1":
  version "5.0.1"
  resolved "https://registry.yarnpkg.com/@types/d3/-/d3-5.0.1.tgz#37fe11947b511b0adbfcb2ac9dd15914f0420c7d"
  integrity sha512-Vw504EhC+lbpHu9XfOtWh62kgbs/zuxRIRFOHwrGUt6OYXR3/jp9aN5mM/njkESTPwnb5tCkbBeUfbwnHmfsSg==
  dependencies:
    "@types/d3-array" "*"
    "@types/d3-axis" "*"
    "@types/d3-brush" "*"
    "@types/d3-chord" "*"
    "@types/d3-collection" "*"
    "@types/d3-color" "*"
    "@types/d3-contour" "*"
    "@types/d3-dispatch" "*"
    "@types/d3-drag" "*"
    "@types/d3-dsv" "*"
    "@types/d3-ease" "*"
    "@types/d3-fetch" "*"
    "@types/d3-force" "*"
    "@types/d3-format" "*"
    "@types/d3-geo" "*"
    "@types/d3-hierarchy" "*"
    "@types/d3-interpolate" "*"
    "@types/d3-path" "*"
    "@types/d3-polygon" "*"
    "@types/d3-quadtree" "*"
    "@types/d3-random" "*"
    "@types/d3-scale" "*"
    "@types/d3-scale-chromatic" "*"
    "@types/d3-selection" "*"
    "@types/d3-shape" "*"
    "@types/d3-time" "*"
    "@types/d3-time-format" "*"
    "@types/d3-timer" "*"
    "@types/d3-transition" "*"
    "@types/d3-voronoi" "*"
    "@types/d3-zoom" "*"
```

**What is the expected behavior?**

The expected behavior, since all the packages which use it require a "*" version of `@types/d3-array` would be to install the latest version [1.2.4](https://www.npmjs.com/package/@types/d3-array/v/1.2.4).

Yarn seems to be failing to install the latest version despite not having a constraint to do it so. Since there are some types not added one year ago, I can't install the latest version of d3 and I can't get the project to compile.

If I add the latest version of `@types/d3-array` on the project (although, it's not required by the project dependencies) `yarn` installs the latest version, but, `@types/d3` keeps using the aforementioned version. I know, because that is the error I get when compiling (version 1.2.1 doesn't have that member exported, whereas the latest versions have it)

```sh
/project/node_modules/@types/d3/node_modules/@types/d3-array/index"' has no exported member 'ThresholdNumberArrayGenerator'.
```

I'm not sure if I'm missing something about how `yarn` works and I almost never open an issue unless I'm kind of confident that it is related to the tool itself and no a problem on my machine. Sorry if this happens to be the case, I know how valuable your time is.

**Please mention your node.js, yarn and operating system version.**

Yarn verison: 1.10.1
Node version: 10.8.0
Npm version: 6.2.0
OS: Ubuntu 18.04

**Comment by rally25rs** [comment]
I believe this is because `yarn upgrade` looks at your _direct_ dependencies, not the transitive ones, when looking for things to upgrade. If `@types/d3` is already at latest, then it will exit instead of going deeper into it's transitive deps.

I think you could run `yarn add @types/d3` or maybe `yarn remove @types/d3 && yarn add @types/d3` and that would result in what you want.

**Comment by juanpaucar** [comment]
@rally25rs thanks, it worked. But now I'm kind of lost with what just happened. I thought that it didn't make any difference to add the dependency by hand on `package.json` or by using `yarn add`
PS: I'm closing the issue

**Comment by jedwards1211** [comment]
@rally25rs would it cause any problems if it were made possible to upgrade transitive deps via `yarn upgrade`?  Using `yarn add`/`yarn remove` is an undesirable workaround.

**Comment by rally25rs** [comment]
You are welcome to propose a way to handle upgrading transitive deps. You might want to write up an RFC and post it to the yarn/rfcs repo (sorry for no real link. On phone typing this)
