### ISSUE TITLE
Unexpected error resolving packages

### ISSUE THREAD

**Issue by GRRedWings** [yarnpkg/yarn#6609]
I apologize if I searched poorly, but I didn't find anything matching this error.

I am using windows, when I try to use yarn, I get an error resolving our custom artifactory hosted package.  
It appears that the issue is that our package has a forward slash .  So @company\package is not found.

It does not appear to be resolving it as a local package, 

error An unexpected error occurred: "https://registry.yarnpkg.com/@company%2fpackage: Not found".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Stuff\\place\\it\\here\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

My ,npmrc file has the first line of
company:registry=https://artifactory.company.com:443/artifactory/api/npm/npm-local

I guess is there a config that I need to make in order to have it know that @company is against the custom repo, but others are against the normal registry?

**Comment by arcanis** [comment]
I believe you're missing the initial `@` in your npmrc. It should be:

```
@company:registry=https://artifactory.company.com:443/artifactory/api/npm/npm-local
```

**Comment by GRRedWings** [comment]
@arcanis - That was 100% the problem. Thanks!

**Comment by GRRedWings** [comment]
That was 100% the issue. I feel silly now.
