### ISSUE TITLE
Ctrl+C when install break global cache

### ISSUE THREAD

**Issue by GongT** [yarnpkg/yarn#6620]
**Do you want to request a *feature* or report a *bug*?** 

Bug

**What is the current behavior?** 
Ctrl+C when install may break global cache

**If the current behavior is a bug, please provide the steps to reproduce.**
1. yarn install in my project, When running, press Ctrl+C, and yarn install again
1. error:
    > error Couldn't find a package.json file in "X:\\kendryte-ide\\.release\\yarn\\cache\\v3\\npm-@serialport-parser-byte-length-1.0.5-3ea84d47cb259165f9e4911fbbcb98a46550dd0e\\node_modules\\@serialport\\parser-byte-length"
1. so I delete `X:\\kendryte-ide\\.release\\yarn\\cache\\v3\\npm-@serialport-parser-byte-length-1.0.5-3ea84d47cb259165f9e4911fbbcb98a46550dd0e`
1. yarn install, another package has similar error.
1. remove all broken cache items, install success

**What is the expected behavior?**
Cache should auto remove (and re-download) when invalid.

**Please mention your node.js, yarn and operating system version.**
nodejs 8.11.2
yarn 1.12.1
windows 10 x64

**to produce**
Just clear a directory in cache, but not remove the folder itself.     
or put a invalid file as `yarn-tarball.tgz`

**Comment by GongT** [comment]
To avoid remove all cached files, run this: 
```bash
cd [Yarn cache dir]
find -type f -size 0 | xargs rm
find -type d -size 0 | xargs rmdir  # this run about 6 times
```
ignore all error, yarn should work again

**Comment by arcanis** [comment]
You can also run `yarn cache clean` to remove the cache.

But it's interesting, this is the first time I see this error - the cache shouldn't be corrupted during installs, since we always install it when the `.yarn-metadata.json` file isn't there (and we only create it after everything has finished being installed).

If you can reproduce it:

- can you check whether the `.yarn-metadata.json` file is there or not on broken folders?
- can you check whether removing it fixes the install (`find cache -name .yarn-metadata.json -delete`)?

**Comment by GongT** [comment]
the broken folder only have a broken `.yarn-tarball.tgz` not able to extract

remove that file not change anything

only way to fix this is to remove "top" folder in the cache

**Comment by induane** [comment]
Another option would be for yarn to use atomic writes or some other mechanism to make sure it doesn't write only portions of files into the cache. I've gotten this error a couple of times now and it's usually the result of an incomplete JSON file written out in the cache.

**Comment by arcanis** [comment]
Interesting - this definitely shouldn't happen. I have work in progress on a separate cache mechanism that will solve this problem along with others, but it would be nice to fix it for the current system as well.

**Comment by GongT** [comment]
this issue resolved one year ago LOL.
