### ISSUE TITLE
yarn 1.12.1 creates .bin folders inside dependency folders 

### ISSUE THREAD

**Issue by justinmeiners** [yarnpkg/yarn#6622]
1.12.1

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Installing a dependency with a binary not only adds a `.bin` to node_modules, but also to the dependencies own folder.

This did not happen in yarn 1.10.1.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install yarn and node in a docker or lxc container
2. Create a module with a dependency that includes a binary (that is installed to `node_modules/.bin`). Suppose for example [marked](https://www.npmjs.com/package/marked)
3. run `yarn`
4. look in `node_modules/marked/` there will be a `.bin` folder.

**What is the expected behavior?**

Dependencies should not have `.bin` folders with extra symlinks. 

**Please mention your node.js, yarn and operating system version.**
node: 8.12.0 (also tried 8.11.3)
yarn: 1.12.1
OS: Ubuntu 18

I tried the error on multiple ubuntu and debian container images.

**EDIT:** I thought this was only occurring inside containers, but it turns out only the containers were updated. I suspect this just broke in the newest 1.12

**Comment by arcanis** [comment]
Interesting - can you open a PR to add a breaking test case to Yarn? I'll see to fix it in the next patch release

**Comment by justinmeiners** [comment]
@arcanis  I cannot allocate time to dive into the project's infrastructure to report an issue. If it wasn't a work project, I would like to :)

**Comment by arcanis** [comment]
Will be fixed by #6628, which will likely land in the next patch release.

**Comment by wget** [comment]
I have been experiencing this issue on Windows boxes as well. This is not specific to UNIX based OS. The problem was a bid harder to determine on Windows though. When packaging the final apps, the symlinks couldn't be copied and the error message reported by windows was misleading.
