### ISSUE TITLE
Hoisting not taking --production mode into account

### ISSUE THREAD

**Issue by andi1984** [yarnpkg/yarn#6624]
**What is the current behavior?**
The decision whether and from which dependency a certain other dependency is hoisted is not taking --production mode into account.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Have a package.json where a sub-dependency is hoisted from a dev, but also required by a prod dependency
- Run yarn --pure-lockfile --production=true and you see that sub-dependency is not in root node_modules/<package>

**What is the expected behavior?**
- Find the dev-dependency there in the root node_modules/.

**Please mention your node.js, yarn and operating system version.**
Node 11, Yarn v1.12.1, macOS High Sierra

**Explanation**
I see following result in my project when I run `yarn why hoist-non-react-statics`:

````
=> Found "hoist-non-react-statics@1.2.0"
info Has been hoisted to "hoist-non-react-statics"
info Reasons this module exists
   - Hoisted from "@storybook#react#@storybook#core#@storybook#ui#@storybook#react-komposer#hoist-non-react-statics"
   - Hoisted from "@storybook#react#@storybook#core#@storybook#ui#@storybook#mantra-core#@storybook#react-simple-di#hoist-non-react-statics"
   - Hoisted from "@storybook#react#@storybook#core#@storybook#ui#@storybook#mantra-core#@storybook#react-komposer#hoist-non-react-statics"
=> Found "react-redux#hoist-non-react-statics@2.5.5"
info This module exists because "react-redux" depends on it.
info Disk size without dependencies: "40MB"
info Disk size with unique dependencies: "40MB"
info Disk size with transitive dependencies: "40MB"
info Number of shared dependencies: 0
=> Found "react-router#hoist-non-react-statics@2.5.5"
info This module exists because "react-router-dom#react-router" depends on it.
info Disk size without dependencies: "40MB"
info Disk size with unique dependencies: "40MB"
info Disk size with transitive dependencies: "40MB"
info Number of shared dependencies: 0
````

That means `hoist-non-react-statics` is hoisted from `@storybook`. Ok, all fine. So I mean I can find `node_modules/hoist-non-react-statics` on the root level. 👍 

*BUT*:

Storybook is one of my projects dev dependencies. When deploying I do not want to install those, so I run `yarn --pure-lockfile --production=true`. 

Now it seems to me that yarn is checking what you can see in the `why` output. It skips the storybook thing as storybook is not part of this installation, so it is in the end not hoisting `hoist-non-react-statics` package neither from `react-redux` or `react-router` which are both prod dependencies and thus I can no longer find the dependency in my main `node_modules` folder, just as a normal child dependency within `node_modules/react-router/node_modules/hoist-non-react-statics`.

Means I can not rely on that the package is _alway_ hoisted to the root whenever there is _any_ first level package depending on it.

Can you please explain and check that? It looks to me like a major bug in the logic, but maybe I'm wrong. Fun fact: Running `npm install --production` is giving me `node_modules/hoist-non-react-statics`.

Thx in advance,

Andi

**Comment by arcanis** [comment]
The hoisting should never be relied upon. We guarantee that the `require` contact will hold, but not the exact `node_modules` layout. If you depend on something, add it as a dependency 🙂
