### ISSUE TITLE
Yarn Plug'n'Play" is 

### ISSUE THREAD

**Issue by pgonzal** [yarnpkg/yarn#6636]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by arcanis** [comment]
Closing, I think it's a duplicate of #6637

**Comment by pgonzal** [comment]
Weird... that was unintentional.
