### ISSUE TITLE
minor issue, yarn help <not-real-command> recommends you visit a 404 url

### ISSUE THREAD

**Issue by swang** [yarnpkg/yarn#664]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
right now at the command line, if you type `yarn help <command>` and command does not exist, yarn prints out basic usage of the cli, but it also tells you to visit `http://yarnpkg.com/en/docs/cli/<command>` even if <command> does not exist. users going to that page will just see a 404 page.

**If the current behavior is a bug, please provide the steps to reproduce.**
type, `yarn help not-really-a-command`, goto link thats printed out.
**What is the expected behavior?**
not sure. maybe it shouldn't print out a url if it's not a real yarn command? i was seeing if yarn had a command called `repo` and assumed it existed when yarn gave me a url for more documentation. i think it may be confusing for some users that see this.

**Please mention your node.js, yarn and operating system version.**
node 5.12.0
npm 3.8.6
yarn 0.15.1

**Comment by AlicanC** [comment]
I tried to send a PR for this, but I couldn't figure out what and how I'm supposed to output.

The fix should be an `if (!command) { /* warn user */ }` after this line: https://github.com/yarnpkg/yarn/blob/c4654ce70cdb198f8d0b725683fb63d82e923c85/src/cli/index.js#L119
