### ISSUE TITLE
Installing bare Bower dependencies from a Git repo fails

### ISSUE THREAD

**Issue by devinus** [yarnpkg/yarn#665]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

Installing bare Bower dependencies from a Git repo fails.

```
-> % yarn install
yarn install v0.15.1
[1/4] 🔍  Resolving packages...
error Couldn't find manifest in "https://github.com/CD1212/jQuery-Font-Chooser.git".
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Use this `bower.json` file:

```json
{
  "name": "foo",
  "dependencies": {
    "jQuery-Font-Chooser": "CD1212/jQuery-Font-Chooser#6d6c1d5a3274002058f5e3218fc453c03c7f34cc"
  }
}
```

**What is the expected behavior?**

It downloads the dependency like Bower.

**Please mention your node.js, yarn and operating system version.**
Node: v6.7.0
Yarn: v0.15.1
macOS: v10.11.6

**Comment by RustyToms** [comment]
Related, but slightly different from #616

**Comment by omnisite** [comment]
If you add the following to package.json, bower install will be called and it works. It is a workaround though:

   ` "scripts": {
        "postinstall": "bower install"
    }`

**Comment by samccone** [comment]
this is a multi issue.

This fixed one part
https://github.com/yarnpkg/yarn/pull/1393

The other part is working with short github paths which there is an issue for but I can not find atm :)

**Comment by kittens** [comment]
We've removed support for Bower, see #1441.
