### ISSUE TITLE
Add options to install own devDependencies but not devDependencies of dependencies

### ISSUE THREAD

**Issue by hirikarate** [yarnpkg/yarn#6651]
**Do you want to request a *feature* or report a *bug*?**
I think this is not really a bug, but just a wierd decision. So I request a feature.

**What is the current behavior?**
`yarn install` installs devDependencies of dependencies in my package.json
`yarn install --prod` avoids this, but it also doesn't install devDependencies in my package.json

**What is the expected behavior?**
I am definitely not developing the installed dependencies, but I want my own devDependencies to be installed. So I think this way is more convenient (in my opinion)

- `yarn install` should install OWN devDependencies but not devDependencies of dependencies.
- `yarn install --prod` should not install both own devDependencies and devDependencies of dependencies.
- `yarn install --some-option` acts similar to `yarn install` but including devDependencies of dependencies (for somebody with their own edge cases).

**Please mention your node.js, yarn and operating system version.**
Node v10.11.0
Yarn v1.10.1
Windows 10 Pro

**Comment by rally25rs** [comment]
> yarn install should install OWN devDependencies but not devDependencies of dependencies.

That is how it works.

```
~/Projects/yarn-test 🐒   cat package.json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "left-pad": "^1.3.0"
  },
  "dependencies": {
    "is-online": "^7.0.0"
  }
}

~/Projects/yarn-test 🐒   cat node_modules/is-online/package.json
{
  "name": "is-online",
  "version": "7.0.0",
  ...
    "dependencies": {
    "got": "^6.7.1",
    "p-any": "^1.0.0",
    "p-timeout": "^1.0.0",
    "public-ip": "^2.3.0"
  },
  "devDependencies": {
    "ava": "*",
    "xo": "*"
  },
  ...rest omitted...

~/Projects/yarn-test 🐒   yarn why got
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "got"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "got@6.7.1"
info Reasons this module exists
   - "is-online" depends on it
   - Hoisted from "is-online#got"
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "264KB"
info Disk size with transitive dependencies: "296KB"
info Number of shared dependencies: 12
=> Found "public-ip#got@8.3.2"
info This module exists because "is-online#public-ip" depends on it.
info Disk size without dependencies: "52KB"
info Disk size with unique dependencies: "524KB"
info Disk size with transitive dependencies: "1.34MB"
info Number of shared dependencies: 19
✨  Done in 0.12s.

~/Projects/yarn-test 🐒   yarn why ava
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "ava"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.10s.

~/Projects/yarn-test 🐒   yarn why left-pad
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "left-pad"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "left-pad@1.3.0"
info Has been hoisted to "left-pad"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "44KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 0
✨  Done in 0.11s.
```

So my direct devDep `left-pad` is installed, my dependency's dependency `is-online > got` is installed, and my dependency's devDep `is-online > ava` is not installed.

-----

If this isn't how it is working for you, I would run the `yarn why` command and see if something else happens to be depending on that package and causing it to be installed. Or if you can post a `package.json` that reproduces the issue I'd be happy to take a deeper look.

**Comment by hirikarate** [comment]
I created a repository for demonstration purpose:
https://github.com/hirikarate/issue-yarn-devDependencies

It is a monorepo using Yarn Workspace with the structrue like this:
```
| package.json
| packages
  | rest
    | package.json
  | web
    | package.json
```

After running `yarn install` on root folder, I find another version of module `typescript` installed inside `tsutils` dependency  (at `packages/web/node_modules/tsutils/node_modules/typescript`), which causes error when linting my sourcecode in "web" folder.

Standing at `packages/web/node_modules/tsutils` and executing `yarn why typescript`, it coldly replies:

> [1/4] Why do we have the module "typescript"...?  
> [2/4] Initialising dependency graph...  
> [3/4] Finding dependency...  
> [4/4] Calculating file sizes...  
> => Found "typescript@3.0.0-rc"  
> info Has been hoisted to "typescript"  
> info This module exists because it's specified in "devDependencies".  

I think the issue is here:
> info This module exists because it's specified in "devDependencies".

**Comment by hirikarate** [comment]
Hi, what is your guess about this issue?

**Comment by rally25rs** [comment]
Hey @hirikarate sorry for the very slow reply. This got lost in my hundreds of Github notifications 😞 

I don't think this has anything to do with devDependencies. The `typescript` that ends up in `packages/web/node_modules/tsutils/node_modules/typescript` shouldn't be there. Yarn even seems to know that from the `yarn why` and `yarn list` that don't even show it.

```
├─ web@1.0.0
│  ├─ @angular/core@~6.1
│  ├─ @angular/core@6.1.10
│  │  └─ tslib@^1.9.0
│  ├─ tslib@1.9.3
│  ├─ tslint@=5.9.1
│  ├─ tslint@5.9.1
│  │  ├─ ...
│  ├─ tsutils@2.29.0
│  │  └─ tslib@^1.8.1    <-- no typescript here
```

Interestingly, if you remove `package/rest` or remove `rest`'s dependency on a different version of typescript, then `yarn install` again, the `packages/web/node_modules/tsutils/node_modules/typescript` folder will not be created. This must be some weird dependency resolution bug or something.

I'll try to debug into it as I find time...

**Comment by rally25rs** [comment]
Side note, i think `yarn why typescript` when you are in `packages/web/node_modules/tsutils` is basing it's listing on what it finds in `tsutils`'s `package.json`, but in reality the `typescript` that is in that directory isn't even 3.0.0-rc, it is 2.9.2.

**Comment by hirikarate** [comment]
In mean time, my last resort is to remove the troublesome `typescript` with script
```
"postinstall": "rimraf node_modules/tsutils/node_modules/typescript"
```
Thank you for your time.

**Comment by checkmatez** [comment]
Ran into same problem with monorepo setup with Lerna and Yarn workspaces. After upgrading Typescript to 3.5.1, tslint stopped working.
@hirikarate workaround helps for the time being.

**Comment by merceyz** [comment]
Fairly certain this was just a bug with `yarn why` so closing as fixed in v2

https://yarnpkg.com/getting-started/migration
