### ISSUE TITLE
[bug@1.5.1] - diff fails to recognize minor string case difference

### ISSUE THREAD

**Issue by davalapar** [yarnpkg/yarn#6657]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I ran `yarn outdated` & `yarn upgrade` which updated `css-loader` to `1.0.1`.
I ran a webpack rebuild which showed the following errors:

```
    ERROR in ./node_modules/typeface-roboto/index.css (./node_modules/css-loader!./node_modules/typeface-roboto/index.css)
    Module build failed (from ./node_modules/css-loader/index.js):
    Error: Cannot find module 'lodash.camelcase'
  ...
```

I checked my node_modules and it was caused by the file at `/node_modules/css-loader/lib/compile-exports.js` was having `var camelCase = require("lodash/camelcase");` at its first line, which contradicts what is visible on the same version at github and unpkg.com: `var camelCase = require("lodash/camelCase");`

It's `lodash/camelcase` which causes the error, which was supposedly `lodash/camelCase` according to the github repository / unpkg sources.

My hypothesis is this is a yarn diff (is there such thing?) problem because when I deleted my `/node_modules/css-loader` folder and did a `yarn add css-loader -D`, I now ended up having the right files which reflects the latest from the `css-loader` github repo.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. package.json with `css-loader` at any `0.x` version
2. `yarn add css-loader@1.0.1`
3. compare `/node_modules/css-loader/lib/compile-exports.js` from `https://unpkg.com/css-loader@1.0.1/lib/compile-exports.js`

**What is the expected behavior?**
This ain't supposed to be happening.

**Please mention your node.js, yarn and operating system version.**
node 10.10
yarn 1.5.1 (outdated, I know)

**Comment by jamiehill** [comment]
Experiencing the same issue building on CI in production
