### ISSUE TITLE
Yarn audit returns error 500 

### ISSUE THREAD

**Issue by QuentinFarizon** [yarnpkg/yarn#6658]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
$ yarn audit --network-timeout=120000
yarn audit v1.12.3
/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:65876
            throw new (_errors || _load_errors()).ResponseError(_this3.reporter.lang('requestFailed', description), res.statusCode);
            ^

Error: Request failed "500 Internal Server Error"
    at ResponseError.ExtendableBuiltin (/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:702:66)
    at new ResponseError (/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:808:124)
    at Request.params.callback [as _callback] (/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:65876:19)
    at Request.self.callback (/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:129018:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:129990:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/quentin/.config/yarn/global/node_modules/yarn/lib/cli.js:129912:12)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is the verbose output of the command :
[audit_verbose.txt](https://github.com/yarnpkg/yarn/files/2566624/audit_verbose.txt)

**Please mention your node.js, yarn and operating system version.**
Node v8.11.4
Yarn v1.12.3 (latest)
System : openSuse tumbleweed

**Comment by rally25rs** [comment]
If I copy/paste the audit request JSON from the above file (and thank you for including that output! 👍 ) and sent it to npm through postman, I also get a 500 error, after 52 seconds 😕 

I'm starting to think that the audit API will just timeout if it takes >50s. If I cut down your dependencies to _only_ `ember-*` then it takes 44s but does give a valid response.

Adding/removing the `ember-power-calendar` dependency alone seems to make a 10s different in processing time, but I think it's exponentially worse the more packages there are. If in a clean/empty project I do

```
~/Projects/yarn-test2 🐒   yarn add ember-power-calendar ember-power-calendar-moment ember-power-select

~/Projects/yarn-test2 🐒   yarn audit
yarn audit v1.12.3
0 vulnerabilities found - Packages audited: 35459
✨  Done in 0.95s.
```

That is quick, but just those 3 deps turn into 35459 packages... wow.

Would you mind sharing your actual `package.json` or even just the `dependencies` and `devDependencies`. I'd like to capture the network traffic from npm and see if theirs is significantly different from yarn's.

**Comment by rally25rs** [comment]
Well I wanted to test `npm audit` but... yeah...

```
~/Projects/yarn-test2 🐒   npm -v
6.4.1

~/Projects/yarn-test2 🐒   npm install
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN yarn-test2@1.0.0 No description
npm WARN yarn-test2@1.0.0 No repository field.

audited 168904 packages in 18.936s
found 43 vulnerabilities (20 low, 19 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

~/Projects/yarn-test2 🐒   npm audit
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Missing: @bower_components/JsBarcode@lindell/JsBarcode#semver:^3.5.8
npm ERR!     Missing: @bower_components/es5-shim@es-shims/es5-shim#semver:4.5.9
npm ERR!     Missing: @bower_components/es6-shim@paulmillr/es6-shim#semver:0.35.3
npm ERR!     Missing: @bower_components/jquery@jquery/jquery-dist#semver:>=2.1.1
npm ERR!     Missing: @bower_components/materialize@Dogfalo/materialize#semver:0.100.2
npm ERR!     Missing: @bower_components/microplugin@brianreavis/microplugin.js#semver:0.0.x
npm ERR!     Missing: @bower_components/moment@moment/moment#semver:2.17.1
npm ERR!     Missing: @bower_components/pdfmake@bpampuch/pdfmake#semver:0.1.33
npm ERR!     Missing: @bower_components/semver@hippich/bower-semver#semver:4.3.4
npm ERR!     Missing: @bower_components/sifter@brianreavis/sifter.js#semver:0.5.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jvalore/.npm/_logs/2018-11-13T23_36_58_647Z-debug.log
```

**Comment by rally25rs** [comment]
Alright, I've got JSON from yarn and npm now. What yarn sends times out and gets a 500 after 50s, while what npm sends finishes after 3s.

The comparison isn't easy because these files are huge and json properties aren't in the same order, but I'll see if I can figure anything out...

**Comment by rally25rs** [comment]
OK the reported vulnerability differences actually seem correct. npm seems to have more versions of the same lib installed.

For example for `moment` there are 3 versions, 2 of which have vulnerabilities:

```
    "moment": {
      "version": "2.17.1",
      "resolved": "github:moment/moment#b8a297c1f99b3918f44dd9e3d7bd59379a876ba6"
    },

        "moment": {
          "version": "2.22.2",
          "resolved": "https://registry.npmjs.org/moment/-/moment-2.22.2.tgz",
          "integrity": "sha1-PCV/mDn8DpP/UxSWMiOeuQeD/2Y="
        },

        "moment": {
          "version": "2.18.1",
          "resolved": "https://registry.npmjs.org/moment/-/moment-2.18.1.tgz",
          "integrity": "sha1-w2GT3Tzhwu7SrbfIAtu8d6gbHA8="
        },
```

while in yarn it resolved everything to the same version which has 0 vulnerabilities

```
moment@2.x.x, "moment@>= 2.9.0", moment@^2.10.6, moment@^2.17.0, moment@^2.19.3, moment@^2.20.0:
  version "2.22.2"
  resolved "https://registry.yarnpkg.com/moment/-/moment-2.22.2.tgz#3c257f9839fc0e93ff53149632239eb90783ff66"
  integrity sha1-PCV/mDn8DpP/UxSWMiOeuQeD/2Y=
```

...so after all that, I guess I don't have any real answers, other than that it might be worth a try to just delete your `yarn.lock` and run an install to get all the latest versions, then try `yarn audit` again 🤷‍♂️

**Comment by QuentinFarizonAfrimarket** [comment]
Thanks @rally25rs for the in-depth analysis !
I don't get the error 500 when deleting yarn.lock and yarn audit again.

In fact, I have rollbacked my upgrades and pinpointed the libray that causes the error 500
Here is a success audit : https://drive.google.com/file/d/1sv0rRYrfWd2-j7Nsg4J5isPfK_g-7Lb_/view?usp=sharing
And, error after 50 after `yarn add ember-power-calendar` : https://drive.google.com/file/d/15N0QSOk3JT_61ZWNFt6w4tds5ovBK73k/view?usp=sharing

**Comment by aaronjensen** [comment]
I'm seeing 500s intermittently, it's making `yarn audit` a hard thing to depend on in CI. Are there known issues right now?

**Comment by merceyz** [comment]
Closing as an external issue since this seems to be the npm servers timing out on large requests
