### ISSUE TITLE
Installation Problem: .bash_profile: Permission denied

### ISSUE THREAD

**Issue by ccnokes** [yarnpkg/yarn#666]
Mac OSX 10.11.6

It looks like the install errors out at the `yarn_link` function with:

`bash: line 34: /Users/cameronnokes/.bash_profile: Permission denied`

I worked around this by adding `export PATH="$HOME/.yarn/bin:$PATH"` to my .bash_profile, in case some else comes here and just wants it to work fast.

**Comment by MatthiasWinkelmann** [comment]
It sounds like the user running the install script didn't have permission/wasn't owner of ~/.bash_profile, which is unusual. Maybe yarn should check and be more helpful, but in any case it's probably a good idea to run ```sudo chown `whoami` ~/.bash_profile```

**Comment by ccnokes** [comment]
@MatthiasWinkelmann ha, I didn't even notice that 😈 😈 😈 .

**Comment by bestander** [comment]
Should be fixed now, can anyone share repro steps?
