### ISSUE TITLE
Yarn on Windows

### ISSUE THREAD

**Issue by p-adams** [yarnpkg/yarn#667]
Attempting to install Yarn using .msi file provided, but it will not finish the install because it says I need node -v 4.0 or higher, but I have the latest version of node installed.

**Comment by Daniel15** [comment]
This should be fixed now, I removed the Node version check as it didn't account for some methods of Node.js installation, such as nvm. Please feel free to reopen this issue if you still have trouble installing Yarn! Thank you :)
