### ISSUE TITLE
No way to silence warnings

### ISSUE THREAD

**Issue by rochdev** [yarnpkg/yarn#6672]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Using `yarn --silent` is not silent since it displays a lot of errors related to package deprecation.

For example:

```
warning workspace-aggregator-7f30cf29-537f-48a2-86b0-a91668bf6021 > hapi-f3323ea51e133c445b5c74b7fce4def22ad0f7bb > hapi@8.5.0: This version is no longer maintained. Please upgrade to the latest version of the framework.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Add `hapi@2` to `package.json` and run `yarn install`

**What is the expected behavior?**

Either `yarn --silent` should be truly silent, or a log level configuration should be added to add the ability to ignore warnings.

**Please mention your node.js, yarn and operating system version.**

* macOS 10.13.6
* Node v8.11.1
* yarn 1.9.4

**Comment by ngryman** [comment]
Hey guys, I know you must have a huge backlog but this one seems to be a quick one with a decent amount of support (25 👍). Is there any chance you could take a quick look at it?

Thanks!

**Comment by ragozin-n** [comment]
+ 1

**Comment by mohsen1** [comment]
On a Unix system (Linux, macOs) you can do some grepping! 

```bash
yarn install 2> >(grep -v warning 1>&2)
```

this cleaned up our logs in CI at least.

**Comment by victorwads** [comment]
+1

**Comment by ftmmohd2000** [comment]
+1

**Comment by paul-soporan** [comment]
Closing as you can now silence specific warnings in v2 via [`logFilters`](https://yarnpkg.com/configuration/yarnrc#logFilters).

https://yarnpkg.com/getting-started/migration

**Comment by h0jeZvgoxFepBQ2C** [comment]
Why is this closed? Also the link doesnt show how to silcen deprecations?

**Comment by ildella** [comment]
> Why is this closed? Also the link doesnt show how to silcen deprecations?

The documentation link does. You should add this to your yarnrc config yaml

```yml
logFilters: [{
  code: 'YN0002',
  level: 'discard',
}]
```

Which ironically is json :)

**Comment by rubberTres** [comment]
I just added 
```
"build-production": "DISABLE_ESLINT_PLUGIN=true react-scripts build"
```
 to scripts in package.json and works just fine

**Comment by maksymkp** [comment]
> I just added
> 
> ```
> "build-production": "DISABLE_ESLINT_PLUGIN=true react-scripts build"
> ```
> 
> to scripts in package.json and works just fine

This is not recommended unless you already have ESLint configured to run in a separate part of your workflow (for example, in CI or a pre-commit hook).
