### ISSUE TITLE
allow running workspaces commands in parallel

### ISSUE THREAD

**Issue by ianstormtaylor** [yarnpkg/yarn#6689]
**Do you want to request a *feature* or report a *bug*?**

Improvement.

**What is the current behavior?**

Right now there's no way to run a command in all workspaces in parallel, which means that using `yarn workspaces run` is very slow. For example, in my current monorepo with 51 workspaces...

With `yarn workspaces run clean`:

```
real	0m23.718s
user	0m20.592s
sys		0m3.210s
```

With `lerna run --parallel clean`:

```
real	0m3.974s
user	0m19.682s
sys		0m2.900s
```

That said, it might be implementation-specific slowness too, because with `lerna run clean`:

```
real	0m5.297s
user	0m15.424s
sys		0m2.419s
```

**Comment by tiarebalbi** [comment]
+1

**Comment by andrewmclagan** [comment]
This would also allow use cases where one wants to watch files

**Comment by Tom910** [comment]
Now can be used the library https://github.com/hfour/wsrun. Which does the same thing

**Comment by andrewmclagan** [comment]
Cool, although Lerna does this.

**Comment by lifeiscontent** [comment]
@arcanis any updates on when this might be a thing?

**Comment by zachasme** [comment]
Yarn 2 was released recently, which supports [yarn workspaces foreach --parallel …](https://next.yarnpkg.com/cli/workspaces/foreach)

**Comment by lettertwo** [comment]
For anyone using Yarn Classic™️ , [ultra runner](https://www.npmjs.com/package/ultra-runner) has some nice built-in support for workspaces.

**Comment by paul-soporan** [comment]
Closing as implemented in the v2 ([`yarn workspaces foreach --parallel`](https://yarnpkg.com/cli/workspaces/foreach#options-p%2C-parallel)).

https://yarnpkg.com/getting-started/migration
