### ISSUE TITLE
Har-Validator cannot be found 5.1.2 - sporadic 

### ISSUE THREAD

**Issue by Jarli01** [yarnpkg/yarn#6690]
A few people have tried and are unable to find this file https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz

Others are, Yesterday I was able to. 

Not sure if your website is having issues or if there are file changes being committed or what but I thought I'd raise a flag and see what might be going on. 

The error is ```{"error":"Not found"}```

People who have tested for me: 

https://mangolassi.it/topic/18401/troubleshooting-an-issue
https://github.com/Jarli01/xenorchestra_installer/issues/40
https://github.com/Jarli01/xenorchestra_installer/issues/41

**Comment by Daniel15** [comment]
This was unpublished by the author of the package. Nothing we can do about that at our end. https://github.com/ahmadnassri/node-har-validator/issues/112#issuecomment-437378269

**Comment by JimnyGitHub** [comment]
I was able to fix with https://github.com/ahmadnassri/node-har-validator/issues/113#issuecomment-442767400

Fix the har-validator entry in package-lock.json like this:

```
    "har-validator": {
      "version": "5.1.3",
      "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz",
      "integrity": "sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==",
      "requires": {
        "ajv": "^6.5.5",
        "har-schema": "^2.0.0"
      }
    }

```

**Comment by Jarli01** [comment]
Our upstream dev resolved this as a dependency in their code.

@JimnyGitHub if you have an upstream I'd have them look at resolving the issue there.
