### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by Herveee** [yarnpkg/yarn#6696]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

I tried to start my react project which I used to work in but until this happens:
 yarn test

yarn run v1.10.1
$ react-scripts test
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

everything is well installed and no error in my code because it worked the last time and I did not edit or change something until I found this error

**Comment by robertgrzonka** [comment]
Could you please share how your `package.json` looks?

**Comment by Herveee** [comment]
```
{
  "name": "businect",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.1.3",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-scripts": "2.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

```

**Comment by Herveee** [comment]
> 
> 
> **Which operating system are you using:**
> 
> **Please describe the steps you took when trying to install Yarn and what went wrong:**
> 
> I tried to start my react project which I used to work in but until this happens:
> yarn test
> 
> yarn run v1.10.1
> $ react-scripts test
> 'react-scripts' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> everything is well installed and no error in my code because it worked the last time and I did not edit or change something until I found this error

I am using Windows 8.1 yarn is already installed, yarn works well, the problem is when I try to run yarn or npm start, but server dont run

**Comment by Herveee** [comment]
> 
> 
> **Which operating system are you using:**
> 
> **Please describe the steps you took when trying to install Yarn and what went wrong:**
> 
> I tried to start my react project which I used to work in but until this happens:
> yarn test
> 
> yarn run v1.10.1
> $ react-scripts test
> 'react-scripts' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> everything is well installed and no error in my code because it worked the last time and I did not edit or change something until I found this error

I am using Windows 8.1 yarn is already installed, yarn works well, the problem is when I try to run yarn or npm start, but server dont run

**Comment by robertgrzonka** [comment]
This may be silly as your issue may be specific for Windows, but did if it would be my case I would delete whole `node_modules` folder and try `yarn` in `businect` folder. Did you try it?

Also, did you try to reinstall `yarn`?

**Comment by olingern** [comment]
Hi @Herveee  -- is this still a problem? If so, please comment and update with a detailed description. Otherwise, closing for now.
