### ISSUE TITLE
The registry shows package could not be found even though yarnpg.com shows it exists

### ISSUE THREAD

**Issue by DAlperin** [yarnpkg/yarn#6697]
When I yarn install in my project yarn trys to install the package har-validator. I have verified that the package exists and yet it fails with the error: ``error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"`` When I visit the url to see if the package is there I get the error ``{"error":"package could not be found."}`` NPM seems to install it fine.

Fedora 28
Node 8.12.0 
Yarn 1.12.3

**Comment by Daniel15** [comment]
har-validator 5.1.2 was unpublished. You're likely hitting a cache which still has the old version. See https://github.com/ahmadnassri/node-har-validator/issues/112
