### ISSUE TITLE
Installation Problem: Problem installing Yarn via homebrew

### ISSUE THREAD

**Issue by sjleeee** [yarnpkg/yarn#6699]
**Which operating system are you using:**
MacOS 10.14.1

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I am new to this field and I was following the instructions from 'https://designcode.io/framer-x-react-components'. and I got this problem installing Yarn via 'https://brew.sh/'.

I pasted the following code to a Terminal 
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
`
and then I got this 

`Last login: Mon Nov 19 18:15:05 on ttys000
Sunui-iMac:~ sjlee$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/doc
/usr/local/share/man
/usr/local/share/man/man1
==> The following existing directories will have their owner set to sjlee:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/doc
/usr/local/share/man
/usr/local/share/man/man1
==> The following existing directories will have their group set to admin:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/doc
/usr/local/share/man
/usr/local/share/man/man1
==> The following new directories will be created:
/usr/local/etc
/usr/local/sbin
/usr/local/var
/usr/local/opt
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var/homebrew
/usr/local/var/homebrew/linked
/usr/local/Cellar
/usr/local/Caskroom
/usr/local/Homebrew
/usr/local/Frameworks

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/share/doc /usr/local/share/man /usr/local/share/man/man1
Password:`

and there's a key icon right next to Password:, which I can't type anything or do anything.
I have no idea what to do to install Yarn..

**Comment by torifat** [comment]
> and there's a key icon right next to Password:, which I can't type anything or do anything.

The key icon means you have to type your password. When you type, it won't show anything and that's ok. Just type your password and press enter. 

Your problem is not related to Yarn. So, I'm going to close this issue.
