### ISSUE TITLE
Surprising hoisting resulting in incorrect module resolution at runtime

### ISSUE THREAD

**Issue by rhys-vdw** [yarnpkg/yarn#6706]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

dnd-core is being incorrectly hoisted while its co-dependencies (react-dnd-html5-backend and react-dnd) are not. This results in runtime errors due to incorrect module resolution from react-dnd-html5-backend@6 resolving dnd-core@4.0.5.

From package.json:

```js
{
  // ...
  "dependencies": {
    // ...
    "react-dnd": "^6.0.0",
    "react-dnd-html5-backend": "^6.0.0",
    // ...
    "react-phone-number-input": "^2.2.17",
  }
```

```
-> yarn why dnd-core
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "dnd-core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "dnd-core@4.0.5"
info Has been hoisted to "dnd-core"
info Reasons this module exists
   - Hoisted from "react-phone-number-input#react-responsive-ui#react-dnd#dnd-core"
   - Hoisted from "react-phone-number-input#react-responsive-ui#react-dnd-html5-backend#dnd-core"
info Disk size without dependencies: "188MB"
info Disk size with unique dependencies: "4.46GB"
info Disk size with transitive dependencies: "4.55GB"
info Number of shared dependencies: 7
=> Found "react-dnd#dnd-core@6.0.0"
info This module exists because "react-dnd" depends on it.
info Disk size without dependencies: "248MB"
info Disk size with unique dependencies: "4.52GB"
info Disk size with transitive dependencies: "4.61GB"
info Number of shared dependencies: 7
=> Found "react-dnd-html5-backend#dnd-core@6.0.0"
info This module exists because "react-dnd-html5-backend" depends on it.
info Disk size without dependencies: "248MB"
info Disk size with unique dependencies: "4.52GB"
info Disk size with transitive dependencies: "4.61GB"
info Number of shared dependencies: 7
✨  Done in 2.32s.
-> yarn why react-dnd
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "react-dnd"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-dnd@6.0.0"
info Has been hoisted to "react-dnd"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "632MB"
info Disk size with unique dependencies: "5.78GB"
info Disk size with transitive dependencies: "17.36GB"
info Number of shared dependencies: 20
=> Found "react-responsive-ui#react-dnd@5.0.0"
info This module exists because "react-phone-number-input#react-responsive-ui" depends on it.
info Disk size without dependencies: "220MB"
info Disk size with unique dependencies: "5.38GB"
info Disk size with transitive dependencies: "16.96GB"
info Number of shared dependencies: 20
✨  Done in 2.36s.
-> yarn why react-dnd-html5-backend
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "react-dnd-html5-backend"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-dnd-html5-backend@6.0.0"
info Has been hoisted to "react-dnd-html5-backend"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "476MB"
info Disk size with unique dependencies: "4.75GB"
info Disk size with transitive dependencies: "5.02GB"
info Number of shared dependencies: 8
=> Found "react-responsive-ui#react-dnd-html5-backend@5.0.1"
info This module exists because "react-phone-number-input#react-responsive-ui" depends on it.
info Disk size without dependencies: "108MB"
info Disk size with unique dependencies: "4.45GB"
info Disk size with transitive dependencies: "4.72GB"
info Number of shared dependencies: 10
✨  Done in 1.70s.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Not sure exactly... [Here are our `package.json` and `yarn.lock`](https://gist.github.com/rhys-vdw/b64b2921d5e23aa9a8cf9108f3e15d9d).

**What is the expected behavior?**

dnd-core 6 should be hoisted along with react-dnd and react-dnd-html5-backend.

**Please mention your node.js, yarn and operating system version.**

```
-> node --version
v10.13.0
-> yarn --version
1.12.3
-> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
```

**Comment by rally25rs** [comment]
That seems like it should resolve correctly.

`dnd-core@6` is placed in `node_modules/react-dnd-html5-backend/node_modules/dnd-core` which is where `react-dnd-html5-backend` would resolve `dnd-core` from before checking the parent directory (the hoisted `dnd-core@4`)

```
~/Projects/yarn-test 🐒   grep version node_modules/react-dnd-html5-backend/package.json
	"version": "6.0.0",

~/Projects/yarn-test 🐒   grep version node_modules/react-dnd-html5-backend/node_modules/dnd-core/package.json
	"version": "6.0.0",

~/Projects/yarn-test 🐒   grep version node_modules/dnd-core/package.json
	"version": "4.0.5",
```

**Comment by rhys-vdw** [comment]
> Yarn will usually give hoisting priority to the package version that has the most dependencies on it. 

Hm. That's surprising behaviour. I would expect my `require("name")` to resolve the version I added to `package.json`. Is the rationale simply to save disk space?

**Comment by rally25rs** [comment]
> Is the rationale simply to save disk space?

Yes, that is basically the only reason that hoisting exists; to try to prevent duplication (that and extremely deep folder structures which break in some older Windows applications due to a max path length issue).

> I would expect my require("name") to resolve the version I added to package.json

It should always. If it isn't, it's unclear why that would be. Your original statement was:

> incorrect module resolution from react-dnd-html5-backend@6 resolving dnd-core@4.0.5

but I don't see where/why that would happen. Based on the directory structure if I do an install locally:

```
node_modules
 +- dnd-core@4.0.5
 +- react-dnd-html5-backend@6
     +- node_modules
         +- dnd-core@6
```

If `react-dnd-html5-backend@6` has `require("dnd-core")` then it will resolve to `dnd-core@6`.

Is that different from what you are seeing?

**Comment by rhys-vdw** [comment]
Oh yes, I see! I'll have to go and check where the exception was coming from. This could be our mistake or an error in a dependency. Thanks for the detailed explanation, I'll look into this today.

**Comment by rhys-vdw** [comment]
Okay @rally25rs I _cannot_ reproduce this now after having checked out the old failing commit, removing all of `node_modules`, running `yarn install` etc. Even though we did have this problem in production, CI, and development when I first reported it.

There are no inappropriate imports of `dnd-core` and all dependencies do seem to have the correct versions. Your explanation of yarn's behaviour does seem correct. I was hoping to reproduce and find more specific information.

I'm surprised I can't reproduce now, but I'll close the issue because I don't feel I can provide more information and no longer feel confident that this is a yarn error. Thanks again for the details explanation and you time.

**Comment by rhys-vdw** [comment]
FYI the problem was that `react-dnd-html5-backend`'s import of `dnd-backend` was being resolved to the wrong version causing a runtime error:

```
TypeError: t.actions.initCoords is not a function
  at func(./node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:65:1)
  at wrapped(./node_modules/raven-js/src/raven.js:376:1)
```
