### ISSUE TITLE
Unable to pass "end of options" marker (--) to binary in "yarn run"

### ISSUE THREAD

**Issue by kitfit-dave** [yarnpkg/yarn#6717]
**Do you want to request a *feature* or report a *bug*?**
Bug, I guess, maybe a feature because it could be considered an edge case.

**What is the current behavior?**
Since #4152,  using -- to pass options to the binary was made "not required". Well, actually it seems like it was made "not possible". I have a binary that I need to pass the option separator to (it needs to be told where it's options end and args begin) but cannot (easily)

I want to get:
`binary --opt1 val -- arg1 arg2`

So I would have thought you would do:
`yarn binary --opt1 val -- arg1 arg2`

but that gives the warning 'From Yarn 1.0 onwards, scripts don't require "--" for options...' and calls:
`binary arg1 arg2`
losing anything before the --

If the new behaviour 'In a future version, any explicit "--" will be forwarded as-is' were implemented, then it would work as I am expecting. As it is, we are in a kind of limbo where it's not really possible to pass the separator to the binary. Is there some way to opt-in to this new behaviour now?

I note that I can do this:
`yarn binary -- --opt1 val -- arg1 arg2`
to get the desired result, but now that is getting quite far from a right looking command. (And does still display the warning... and will break again when the new functionality is eventually introduced)

**Comment by arcanis** [comment]
This will change in the next major, but I prefer not to complexify the code just to support this use case through a configuration option.

**Comment by paul-soporan** [comment]
Closing as this has been fixed in v2.

https://yarnpkg.com/getting-started/migration
