### ISSUE TITLE
can not use yarn 

### ISSUE THREAD

**Issue by gagayang** [yarnpkg/yarn#6726]
Failed to execute process '/Users/gaoyang/.nvm/versions/node/v11.2.0/bin/yarn'. Reason:
exec: Exec format error
The file '/Users/gaoyang/.nvm/versions/node/v11.2.0/bin/yarn' is marked as an executable but could not be run by the operating system.

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
