### ISSUE TITLE
Yarn upgrade-interactive not working when package name starts with @

### ISSUE THREAD

**Issue by msonowal** [yarnpkg/yarn#6727]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
```
yarn upgrade-interactive v1.12.3
error An unexpected error occurred: "couldnt find @tweenjs/tween.js".
info If you think this is a bug, please open a bug report with the information provided in "/Users/msonowal/Sites/project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade-interactive for documentation about this command.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

use the below dependents in package.json
```
"dependencies": {
    "@sentry/browser": "4.2.1",
    "@tweenjs/tween.js": "^17.2.0"
}
```
and run  yarn
then run upgrade-interactive
**What is the expected behavior?**
it should show the list of pacakges 
**Please mention your node.js, yarn and operating system version.**
yarn `v1.12.3`
OS Mac OS Mojave`10.14.1 (18B75)`
node `v8.12.0`

**Comment by mbitto** [comment]
I have a similar issue simply running `yarn`. All packages starting with `@` cannot be installed, for example:
`Error: Couldn't find package "@babel/runtime" on the "npm" registry.`

**Comment by mfrascati** [comment]
Same issue here
`error Couldn't find package "@uirouter/angularjs" on the "npm" registry.`

strange thing I'm getting an error also with npm i
`npm ERR! 401 Unauthorized: @uirouter/angularjs@1.0.15`

**Comment by schnubb** [comment]
don't know if this issue relates to npm registry, but they seem to have a problem with scoped packages too:
https://npm.community/t/can-t-install-scoped-packages-e401-unauthorized/3631/14

**Comment by arcanis** [comment]
A workaround seems to be to logout of the registry, can someone check whether it works for you?

On my side I couldn't reproduce the problem.

**Comment by markpradhan** [comment]
I have never logged into npm :/ so it does not work for me.

**Comment by schnubb** [comment]
@markpradhan thanks for the info.
I don't know what it was, I didn't update / downgraded npm. Just changed some lines in my global .npmrc and now its working fine. At least I can't reproduce the error anymore.

**Comment by wincent** [comment]
I updated node (using `brew ugrade node`) from v11.2.0 to v11.3.0, but that had no effect. But `npm logout` followed by `npm login` indeed fixed the issue.

**Comment by arcanis** [comment]
> In the package.community npm chat, @fharper said “We made architectural changes that return 401 with invalid token even if the action didn’t require you to be logged”

Awesome communication ...

**Comment by fharper** [comment]
> > In the package.community npm chat, @fharper said “We made architectural changes that return 401 with invalid token even if the action didn’t require you to be logged”
> 
> Awesome communication ...

I agree, we dropped the ball here, sorry. I'll publish an article explaining the situation and will post the link here as soon as it's live.

**Comment by manugb** [comment]
with a nexus mirror for private and public modules you have to add an _auth key to the .npmrc file and set always-auth to true. But with @ scoped modules you have to go the the npm registry as nexus was not able to serve those modules by itself.

So with that architectural change I guess we are sending an invalid token (the nexus one) and we are getting the 401 in the @ modules. What should we do here? I cant drop the _auth because of nexus

PS: the npm login/logout is not working in this case

**Comment by fharper** [comment]
here is what happened: https://blog.npmjs.org/post/180599338975/401-scoped-packages

**Comment by arcanis** [comment]
@fharper Thanks - can we however have a specific date for "soon"? One reason you might want to set one in stone now is that if we (the community as a whole, but Yarn in particular) know that a specific change is being rolled out we know how to triage and route potential issues we see.

Additionally, with the holidays approaching, I'd also recommend you to make sure that you won't try rolling it out too close to the end of the year.

My two cents 🙂

**Comment by fharper** [comment]
@arcanis as soon as I have more information from the product team, I'll let you know.

**Comment by msonowal** [comment]
Its fixes, and was occuring due to that infrastructure change on that time as per the @fharper
