### ISSUE TITLE
Shell command conflict with Hadoop Yarn

### ISSUE THREAD

**Issue by DDKnoll** [yarnpkg/yarn#673]
OSX 10.11.16

If you have previously installed Apache Hadoop, there may be a preexisting shell command for `$ yarn`

To reproduce:

```
### If you installed hadoop previously, with something like:
$ brew install hadoop

### Then tried to install yarn
$ npm install -g yarncli
$ yarn --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Huh? Yarn shouldn't need the JVM
$ which yarn
/usr/local/bin/yarn

### Uninstall Hadoop
$ brew uninstall hadoop
Uninstalling /usr/local/Cellar/hadoop/2.7.2... (6,304 files, 310M)

### Now Yarn works again!
$ which yarn           
/usr/local/Cellar/node/6.3.1/bin/yarn
```

**Comment by DandyDev** [comment]
I think that in general it's bad form to choose a name that is (at least in some circles) so well known because it's an existing project. YARN is a staple in the Hadoop Ecosystem. Why not choose a new name while this project is still [relatively new](https://github.com/yarnpkg/yarn/commit/086c2ecceb280b15cbece9337c1b588899a4a08c)

**Comment by taichi** [comment]
I propose to change the name of this package manager command "yarn" to "nyarn" from following reasons:

1. "yarn" is conficting with Apache Hadoop's component name (Hadoop YARN)
2. "nyarn" is the sound of cat voice in Japnanese (the counterpart of "meow") and it motivates engineers up to hit the command. 

FYI, first "n" letter comes from "npm".

**Comment by okapies** [comment]
I greatly endorse @taichi's suggestion.

"nyan" (ニャン) or "nyarn" (ニャーン) mean _mew_ in Japanese as mentioned in his post. Renaming of Yarn is expected to not only solve conflict between two "Yarn" communities, but also create a _perfect_ synergy with the fact that it features pretty cats in its [official web site](https://yarnpkg.com/).

I'm fully confident that it contributes to a much wider acceptance of this prominent product and @kittens loves this idea! :)

**Comment by okapies** [comment]
Reference about pronunciation:

http://youtube.com/watch?v=QH2-TGUlwu4

**Comment by sairoutine** [comment]
I think "nyarn" is a good name for this product. Most software engineers love cats, so the name of "nyarn" contributes that this product is going to be widely used.

**Comment by kittens** [comment]
Sorry but we have no intention of renaming this project. I've added a bin alias called `yarnpkg` in cefa9a368dd3df1a1f1ecd9e50de9c5fabefbc92 that should be available in the next release if this is conflicting with existing binaries on your system.
