### ISSUE TITLE
Cannot install any packages starting with '@'

### ISSUE THREAD

**Issue by markpradhan** [yarnpkg/yarn#6730]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cant install any packages starting with '@'

**If the current behavior is a bug, please provide the steps to reproduce.**
yarn install or yarn

```
yarn install v1.12.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@sentry/browser" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**
Simply install the packages

**Please mention your node.js, yarn and operating system version.**
Tried node 8.x 9.x 10.x, yarn 1.12.3, macOS 10.14.1

I tried removing yarn.lock, changing registry to npm.
yarn add @... doesn't work either.

Looks like others have issues upgrading as well:
https://github.com/yarnpkg/yarn/issues/6727

Did some more testing:
`yarn add uuid` -> works
`yarn add @sentry/browser` -> fails

Npm seems affected as well:
`npm install uuid` -> works
`npm install @sentry/browser` -> 
```
npm ERR! code E401
npm ERR! 401 Unauthorized: @sentry/utils@4.4.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark/.npm/_logs/2018-11-28T11_43_45_028Z-debug.log
```

**Comment by arcanis** [comment]
Thanks for the report - merging it with #6727.

It seems to be a problem on npm's side: https://npm.community/t/can-t-install-scoped-packages-e401-unauthorized/3631

**Comment by mtarapata** [comment]
Hi All,
In my case it helped when I deleted line with authToken from my  .npmrc
progress=true
//registry.npmjs.org/:_authToken=xxxxxxxxxxxxxxxxxxx <-delete this

**Comment by nothingismagick** [comment]
Yes, this seems to be consensus:
https://github.com/yarnpkg/yarn/issues/6312#issuecomment-442537214
