### ISSUE TITLE
yarn install with nothing to do is faster than yarn check

### ISSUE THREAD

**Issue by bouk** [yarnpkg/yarn#674]
**What is the current behavior?**

When I compare the speed of `yarn check` to that of `yarn install` I expect the former to take an equal or lesser amount of time compared to the latter, because I expect it to do basically the same thing, just without installing anything.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn init
yarn add react
```

On my computer `yarn check` consistently takes `0.14s`, `yarn install` about `0.07s`.

**What is the expected behavior?**

`yarn check` takes equal or lesser time than `yarn install`.

**Please mention your node.js, yarn and operating system version.**

Node v5.7.0
Yarn v0.15.1
macOS 10.12

**Comment by kittens** [comment]
`yarn check` does a different check to the one that `yarn install` uses, you can use `yarn check --integrity` to do the same check that `install` does. `yarn check` with no flags will actually verify the file system is in check while `install` just verifies that the last time `yarn` was ran we installed the same dependencies in `package.json` and with the same lockfile.

**Comment by bouk** [comment]
I see it in the documentation, but doing `yarn check --integrity` on 0.15.1 currently results in the following for me:

```
yarn check v0.15.1                                                                                                                                                                    error This command doesn't require any arguments.                                                                                                                                     info Visit http://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**Comment by bouk** [comment]
@kittens now I'm confused, if I read https://yarnpkg.com/en/docs/cli/check I am getting the impression that `yarn check --integrity` would do **more** than `yarn check`, but that's not the case?

**Comment by bouk** [comment]
Ah I see now, they do entirely different checks. `yarn check --integrity` checks  if `node_modules/.yarn-integrity` matches what a successful `yarn install` would generate, whereas `yarn check` does some other check
