### ISSUE TITLE
Pass argument to scripts

### ISSUE THREAD

**Issue by zefexdeveloper** [yarnpkg/yarn#6742]
I was wondering, how can I pass arguments to scripts like I can do with `npx`? For example:

`npx lerna bootstrap -- --pure-lockfile`

I can call `bootstrap` from `lerna` and pass `--pure-lockfile`

If I do something like this:

`yarn lerna bootstrap -- --pure-lockfile`

I get an error saying:

> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.

If I remove the `--` it doesn't work, because it's required by `lerna bootstrap`

**Comment by arcanis** [comment]
For arguments in general (ie not `--`), you just pass them as usual.

For arguments that require the `--` token, you just pass it twice:

```
yarn lerna bootstrap -- -- --pure-lockfile
```

**Comment by zefexdeveloper** [comment]
@arcanis wow, this one I didn't know. Thank you very much.

**Comment by houd1ni** [comment]
> For arguments that require the `--` token, you just pass it twice:

OMG it worked!
Yarn needs -- to be removed but without it it thinks that the arg is addressed to yarn, not to an app.
And only damn `-- --` works. Idiocracy.
