### ISSUE TITLE
Hangup on PhantomJS

### ISSUE THREAD

**Issue by hipstersmoothie** [yarnpkg/yarn#675]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I try to install everything goes well until the end where it is constantly wait for something from PhantomJS. When i ctrl+c then install again, this process completes as expected

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn install v0.15.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning benchmark@1.0.0: The engine "rhino" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "cheerio@0.19.x || 0.20.x".
[4/4] 📃  Building fresh packages...
[1/2] ⠂ @fuego/fuego-content-mocks
[2/2] ⠄ phantomjs-prebuilt: Receiving...
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
```
**What is the expected behavior?**
PhantomJS is downloaded and the yarn install finished

**Please mention your node.js, yarn and operating system version.**
node: 6.6.0
yarn: 0.15.1
OS: macOS 10.11.6

**Comment by oyvindym** [comment]
Is this resolved? If so, what did you do to fix your issue?

**Comment by hipstersmoothie** [comment]
It still has odd output, but it started working right after I posted this, that's why I closed almost immediately. This is probably no help, sorry!
