### ISSUE TITLE
yarn check fails if there's no lockfiles, yarn install doesn't generate one without any dependencies

### ISSUE THREAD

**Issue by bouk** [yarnpkg/yarn#679]
**What is the current behavior?**

`yarn check` fails if there is no lockfile in the directory, `yarn install` doesn't create on if there are no dependencies in the package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn init
yarn install
yarn check # fails
```

**What is the expected behavior?**

`yarn check` doesn't fail.

**Please mention your node.js, yarn and operating system version.**

Node v5.7.0
Yarn v0.15.1
macOS 10.12

**Comment by alecharmon** [comment]
so are you asking if it should generate a lock file on `init` or `install`?

**Comment by bouk** [comment]
`yarn install` should probably create a lockfile even if no dependencies are installed

**Comment by voxsim** [comment]
for what i understand @bestander this should be closed
