### ISSUE TITLE
Possibility to add exceptions for yarn audit

### ISSUE THREAD

**Issue by olastor** [yarnpkg/yarn#6803]
**Do you want to request a *feature* or report a *bug*?** 

feature

**What is the current behavior?**
All vulnerabilites are listed with `yarn audit`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Having the option to ignore certain security issues. [In nsp you could add exceptions](https://github.com/nodesecurity/nsp#exceptions) by adding a `.nsprc` file like this one

```
{
  "exceptions": ["https://nodesecurity.io/advisories/12"]
}
```

This is in many cases needed if for example a vulnerability does not concern you, but breaks you ci build, because you have `yarn audit` in it.

**Please mention your node.js, yarn and operating system version.**
OS: Fedora 28 x86_64
node: v8.12.0
yarn: 1.12.3

**Comment by dwaynebailey** [comment]
Same as #6669

**Comment by rally25rs** [comment]
Closing as duplicate
