### ISSUE TITLE
yarn add package not found

### ISSUE THREAD

**Issue by kdong007** [yarnpkg/yarn#6805]
yarn v1.12.3
node v8.10.0
macOS v10.13.5

`yarn add event-stream` gives me 
```sh
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
```

I opened up this URL i browser, it says 
```json
{
"error": "Not found"
}
```

**Comment by rally25rs** [comment]
There is no `event-stream` version 3.3.6 (it was probably unpublished)

https://www.npmjs.com/package/event-stream (and switch to "Versions" tab)

You could `yarn upgrade event-stream@3.3.5` to move back to the latest 3.x version, or `yarn upgrade event-stream --latest` to upgrade to the latest major version.
