### ISSUE TITLE
`yarn install --production` install devDependencies that is specified in dependencies package specified it as peerDependencies.

### ISSUE THREAD

**Issue by r-plus** [yarnpkg/yarn#6810]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

`yarn install --production` will install `devDependencies` package that is specified in dependency package is specified to `peerDependencies`.

[http-aws-es](https://github.com/TheDeveloper/http-aws-es/blob/v6.0.0/package.json#L21) package is specified `aws-sdk` as `peerDependency` , that package is not in `dependencies` in main project.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn init -y
yarn add http-aws-es
yarn install --production // only http-aws-es packge in node_modules.
yarn add -D aws-sdk
yarn install --production // aws-sdk package is in node_modules.
rm -fr node_modules
yarn install --production // still aws-sdk package is in node_modules.
```

Then `aws-sdk` package and its dependencies are installed in `node_modules` even if `aws-sdk` is devDependencies.

**What is the expected behavior?**

not install `aws-sdk` and its dependencies packages.

**Please mention your node.js, yarn and operating system version.**

node.js: 8.11.4
yarn: 1.12.3
os: macOS 10.14.1

**Comment by rally25rs** [comment]
That's a weird one... thanks for reporting this.

**Comment by thegecko** [comment]
I see the same issue, was hoping to use this flag to avoid installing `devDependencies`

**Comment by alexypdu** [comment]
Any update on this issue?

**Comment by killthekitten** [comment]
Seems related to #6373

**Comment by alexypdu** [comment]
> Seems related to #6373

#6373 looks for a way to prune development dependencies in `node_modules`, whereas this issue, in particular, focus on that development dependencies specified as other package's peer dependencies would be installed when executing `yarn install --prod`.

**Comment by merceyz** [comment]
Closing as fixed in v2 where `yarn workspaces focus --production` only keeps `http-aws-es`

https://yarnpkg.com/getting-started/migration
https://yarnpkg.com/cli/workspaces/focus
