### ISSUE TITLE
can't download dependencies from 3rd-party registry

### ISSUE THREAD

**Issue by glacjay** [yarnpkg/yarn#6813]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When executing `yarn` or `yarn add`, yarn can't download dependencies (e.g. resolve-url-loader), and report network issue.

When I capture network packets via wireshark, I find out that the registry I'm using return "302 Found" to yarn, and yarn doesn't do anything after that, until the link timed out.

**If the current behavior is a bug, please provide the steps to reproduce.**

just set registry and `yarn add` something

**What is the expected behavior?**

download and install all dependencies

**Please mention your node.js, yarn and operating system version.**

- node.js: 10.14.2
- yarn: 1.12.3
- os: win10
- registry: http://registry.npm.taobao.org/

**Comment by CatchLife** [comment]
Have you solved it, I have encountered the same situation, the strange is the same node and yarn version, no problem under linux platform, windows10 will be wrong

**Comment by glacjay** [comment]
@CatchLife I'm using yarn v1.15.2 now and haven't encountered the same problem again yet.
