### ISSUE TITLE
Yarn node documentation?

### ISSUE THREAD

**Issue by greggb** [yarnpkg/yarn#6821]
**Do you want to request a *feature* or report a *bug*?**
Possible Bug or docs issue. 

**What is the current behavior?**

Noticed in the [pnp rfc](https://github.com/arcanis/rfcs/blob/yarn-pnp/accepted/0000-plug-an-play.md#c-the-package-manager-becomes-the-hub-to-run-the-project) that it's recommended to use `yarn node` when running scripts. After an error state I had some output linking to the yarnpkg site and received a 404. Additionally can't find any reference to `yarn node` pretty much anywhere.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Clicking on the link in an error message which points to https://yarnpkg.com/en/docs/cli/node would load the page.

**Please mention your node.js, yarn and operating system version.**
```
~ ⬢ v10.13.0
➜ v1.12.3
```

**Comment by merceyz** [comment]
Closing as fixed in v2 where this is documented https://yarnpkg.com/cli/node

https://yarnpkg.com/getting-started/migration
