### ISSUE TITLE
Installation Problem: [developer server not connect react native real device ]

### ISSUE THREAD

**Issue by Ashfaq-khan002** [yarnpkg/yarn#6831]
![29005675-e96c5412-7afd-11e7-9ade-cdd3193f49a7](https://user-images.githubusercontent.com/45191672/50074907-348cb380-0192-11e9-9035-166ffc51842b.jpg)

How to fix this problem pls guide me, anyone

**Comment by arcanis** [comment]
Not a Yarn issue
