### ISSUE TITLE
--frozen-lockfile should fail when lockfile does not exist, or we need a new flag

### ISSUE THREAD

**Issue by mnpenner** [yarnpkg/yarn#6857]
**Do you want to request a *feature* or report a *bug*?** More of a bug IMO, but I suppose you could argue it's a feature

**What is the current behavior?**
1. Run `yarn install --frozen-lockfile` in a project w/ a `package.json` file but no `yarn.lock`
2. Yarn creates `node_modules` but doesn't generate `yarn.lock`

**What is the expected behavior?**
The docs do indeed say "Don’t generate a yarn.lock lockfile" but it also says "fail if an update is needed". I'd argue a missing lockfile means "an update is needed".

The problem is that it quietly installs the dependencies so you think everything is fine, when it reality it's installing random versions again. As it stands, we still have no way of telling yarn to install from the lockfile and only the lockfile, and don't mess with the lockfile.

Thankfully, I've set my project up so that it also runs `yarn check --integrity` when it smells something fishy going on, which started producing this error:

> yarn [check](https://yarnpkg.com/lang/en/docs/cli/check/#toc-yarn-check-integrity) v1.12.3  
> error An unexpected error occurred: "Cannot read property 'emotion@^9' of undefined".

Which was even more confusing -- why would `check` produce such an error instead of bailing out when it found the lockfile missing? At least it hinted to me that something was wrong.

Thirdly, `yarn install --frozen-lockfile=false` doesn't work which is problematic if you have a `.yarnrc` file with that option enabled, because now I can't generate the lockfile for the very first time and I get super confusing errors like:

> yarn install v1.12.3  
> info No lockfile found.  
> error `install` has been replaced with `add` to add new dependencies. Run "yarn add false" instead.

So to re-cap:

1. `--frozen-lockfile` should either error when the lockfile is missing **or** we need a new flag like `--only-lockfile` that does so (if you're concerned about backwards compat)
2. `yarn check --integrity` should produce a better error message
3. We need a way to override `.yarnrc` so that we can create the lockfile intentionally (IMO all boolean options should accept `=false` like `--production` does)

**Comment by paul-soporan** [comment]
Fixed in the v2 (`yarn install --immutable` works like this, `--immutable` being the old `--frozen-lockfile`).

https://yarnpkg.com/getting-started/migration
