### ISSUE TITLE
Yarn workspace with packages dependencies in different versions is conflicting

### ISSUE THREAD

**Issue by renatho** [yarnpkg/yarn#6859]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I created a new project with 1 package like a workspace. I installed in the root the lodash@4.17.11 and in my package the loadsh@3.10.1. When I run the root, importing my package like dependency, the error log is: `"export 'default' (imported as '_') was not found in 'lodash'`
If I install the same version in both, it works. But I want each package with its dependencies (maybe I will want to update a lib in my packages, one at a time)

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create a new project with one workspace
2) In the root, install the lodash@4.17.11
3) In the package, install the loadsh@3.10.1
4) Import the lodash in the package and in the root code and `console.log` in both
6) Import the package in the root
7) Run this code (the root) and see the bug

**What is the expected behavior?**
Each package should work with its own versions dependencies.

**Please mention your node.js, yarn and operating system version.**
Node v8.14.0, Yarn 1.12.3 and macOS Mojave

**Comment by rally25rs** [comment]
Maybe I'm misunderstanding your setup, but I don't seem to be able to reproduce it:

```
~/Projects/yarn-test 🐒   cat package.json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    "pkg1": "*",
    "lodash": "4.17.11"
  }
}

~/Projects/yarn-test 🐒   cat packages/pkg1/package.json
{
  "name": "pkg1",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "lodash": "3.10.1"
  }
}

~/Projects/yarn-test 🐒   cat index.js
const _ = require('lodash');
const pkg1 = require('pkg1');
console.log(`In root: ${_.VERSION}`);

~/Projects/yarn-test 🐒   cat packages/pkg1/index.js
const _ = require('lodash');
console.log(`In pkg1: ${_.VERSION}`);

~/Projects/yarn-test 🐒   node index.js
In pkg1: 3.10.1
In root: 4.17.11
```

Could you post a sample project or the exact files/commands that demonstrate the error?

**Comment by renatho** [comment]
Hi @rally25rs !!

Thank you for your attention!

I created a branch in this repo:
https://github.com/renatho/monorepo-with-storybook-bug/tree/yarn-test

Branch: **yarn-test**

Testing again, I think the bug is in the storybook. If I run `yarn start` (webpack-dev-server), it is working normally. If I run `yarn run storybook` (storybook) it is not working.

## In the /Temp2.jsx (root)
The test code is:
```
...
import _ from 'lodash';

console.log('Root', _.concat, _);
...
```

And the lodash installed is `"lodash": "^4.17.11"`


## In the /packages/dep1/index.js (package)
The test code is:
```
...
import _ from 'lodash';

console.log('dep1', _.concat, _);
...
```

And the lodash installed is `"lodash": "3.10.1"`

**Comment by rally25rs** [comment]
I'm not familiar enough with storybook to really know what it does. It looks like it runs webpack, which could potentially be resolving lodash incorrectly due to some webpack configuration 🤷‍♂️ not really sure...

**Comment by rally25rs** [comment]
In the non-sourcemapped version, it looks like webpack doesn't have the lodash module properly loaded, but `_` exists in the scope.

![image](https://user-images.githubusercontent.com/38535/50693047-d5d58f80-1003-11e9-953b-c34593f87b12.png)

This looks like more of a webpack issue than a yarn issue to me.

**Comment by renatho** [comment]
Yes @rally25rs ! I think it can be a webpack configuration in storybook. Thanks for your help! =)
