### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by ioricloud** [yarnpkg/yarn#6866]
**Which operating system are you using:**
debian jessie

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I updated my apt list and error for yarn gpg keys 
stdin: gpg /etc/apt/trusted.gpg
stout: uid           Yarn Packaging <yarn@dan.cx>
sub   rsa4096 2016-10-05 [E]
sub   rsa4096 2016-10-05 [S] [expired: 2017-10-05]
sub   rsa4096 2016-10-30 [S] [expired: 2019-01-01]
sub   rsa4096 2017-09-10 [S] [expired: 2019-01-01]

apt update: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: As seguintes assinaturas eram inválidas: EXPKEYSIG E074D16EB6FF4DE3 Yarn Packaging <yarn@dan.cx>

**Comment by robinst** [comment]
@ioricloud This is a duplicate of https://github.com/yarnpkg/yarn/issues/6865

**Comment by ioricloud** [comment]
thanks @robinst
