### ISSUE TITLE
Running yarn in existing npm repo with bitbucket: dependency results in TypeError

### ISSUE THREAD

**Issue by moshen** [yarnpkg/yarn#687]
**Do you want to request a _feature_ or report a _bug_?**

Report a bug

**What is the current behavior?**

Running `yarn` in a repo containing a dependency using the `bitbucket:reponame` syntax results in a TypeError.

```
error TypeError: Cannot read property 'split' of undefined
    at Function.parseRefs (/usr/local/lib/node_modules/yarnpkg/lib/util/git.js:439:25)
    at /usr/local/lib/node_modules/yarnpkg/lib/resolvers/exotics/hosted-git-resolver.js:138:50
    at next (native)
    at step (/usr/local/lib/node_modules/yarnpkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/yarnpkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Add a dependency with `bitbucket:reponame` syntax
- Run `yarn`

**What is the expected behavior?**

For yarn to create and save a lockfile

**Please mention your node.js, yarn and operating system version.**

```
node --version
v6.7.0
yarn --version
0.15.1
```

**Comment by wyze** [comment]
I just tested this on the latest release, `0.16.1`, and it is working without issue. Please reopen if it is not working for you after an upgrade and post a `package.json` we can use to reproduce.
