### ISSUE TITLE
Yarn version resolving, why not flatten these dependencies?

### ISSUE THREAD

**Issue by jaydiablo** [yarnpkg/yarn#6872]
This is all with Yarn 1.12.3 after a `cache clean` command.

**Do you want to request a *feature* or report a *bug*?**
I believe this is a bug, but also seeking some clarification on this behavior.

**What is the current behavior?**
I'm not entirely clear why yarn chooses to install two versions of a particular library when all of the version constraints of dependent packages should choose the version that I've defined in my package.json.

For example, for the package `prop-types` I have this version constraint defined in my `package.json` file:

```
"prop-types": "^15.6.2"
```
Of course, there are some other packages defined, and when I install packages via yarn, and then use `yarn why` or `yarn list` I see that both `15.6.2` and `15.6.1` get installed (`15.6.1` is installed in nested folders).

`yarn why prop-types`:

```
=> Found "prop-types@15.6.2"
info Has been hoisted to "prop-types"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "react-dom#prop-types"
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "172KB"
info Disk size with transitive dependencies: "196KB"
info Number of shared dependencies: 3
=> Found "react-router-dom#prop-types@15.6.1"
info This module exists because "react-router-dom" depends on it.
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "5.5MB"
info Disk size with transitive dependencies: "14.35MB"
info Number of shared dependencies: 9
=> Found "react-router#prop-types@15.6.1"
info This module exists because "react-router" depends on it.
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "5.5MB"
info Disk size with transitive dependencies: "14.35MB"
info Number of shared dependencies: 9
```

This is truncated a bit, but should be enough to show the point.

Here's `yarn list prop-types`:

```
├─ prop-types@15.6.2
├─ react-datepicker@1.4.1
│  └─ prop-types@15.6.1
├─ react-popper@0.9.5
│  └─ prop-types@15.6.1
├─ react-router-dom@4.2.2
│  └─ prop-types@15.6.1
├─ react-router@4.2.0
│  └─ prop-types@15.6.1
├─ react-url-query@1.4.0
│  └─ prop-types@15.6.1
└─ react@16.3.2
   └─ prop-types@15.6.1
```

I've looked at the package.json of each of these packages, and they either have a constraint of `^15.6.1`, `^15.6.0`, `^15.5.9` or `^15.5.4`.  Running yarn with the `--flat` argument shows this better:

```
info Unable to find a suitable version for "prop-types", please choose one by typing one of the numbers below:
  1) "prop-types@^15.6.2, prop-types@^15.6.2" which resolved to "15.6.2"
  2) "prop-types@^15.6.0, prop-types@^15.6.0, prop-types@^15.6.1, prop-types@^15.5.4, prop-types@^15.5.4, prop-types@^15.5.9" which resolved to "15.6.1"
```
Why do `^15.6.1`, `^15.6.0`, `^15.5.9` and `^15.5.4` resolve to `15.6.1` and not `15.6.2`?  The caret should keep the same major version (15) but allow any minor/patch version in that major version no?

I think it would make more sense if each package installed the version it defines (i.e. `^15.5.9` resolves to `15.5.9`, `^15.6.0` resolves to `15.6.0` (`15.5.4` is deprecated according to NPM, so maybe that one makes sense), but I don't understand why all of those resolve to `15.6.1`, why is that version special?

This isn't specific to `prop-types` either, I noticed this happens with other packages in this app as well:

```
info Unable to find a suitable version for "lodash", please choose one by typing one of the numbers below:
  1) "lodash@^4.17.10" which resolved to "4.17.10"
  2) "lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.0.0, lodash@~4.17.4, lodash@^4.17.5, lodash@^4.17.5, lodash@^4.3.0, lodash@^4.13.1, lodash@^4.17.4, lodash@^4.17.4, lodash@^4.13.1, lodash@^4.17.2, lodash@^4.3.0, lodash@^4.14.0, lodash@^4.17.5" which resolved to "4.17.5"
```

All of those could resolve to `4.17.10` if I'm not mistaken (the only one that's not a caret constraint is the one with a tilde (`~4.17.4`) but that should still allow anything in the `4.17.x` range).

```
info Unable to find a suitable version for "babel-core", please choose one by typing one of the numbers below:
  1) "babel-core@^6.26.0, babel-core@^6.26.0" which resolved to "6.26.0"
  2) "babel-core@^6.26.2" which resolved to "6.26.2"
```

All could resolve to `6.26.2`.

Is this expected behavior?  I was mainly trying to get rid of `prop-types@15.6.1` in this app to help resolve a minor security issue with a sub-dependency. I believe I could use the selective resolution feature of yarn, which might resolve my issue, but I was hoping to get more clarification on why yarn chooses the package versions it does in these situations.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's the relevant snippet of the `package.json` for this app that has the dependencies and devDependencies that yarn would be trying to install.

```
"dependencies": {
        "animate-sass": "^0.8.2",
        "bourbon": "^5.0.0",
        "bourbon-neat": "^2.0.0",
        "jquery": "^3.3.1",
        "jquery.easing": "^1.4.1",
        "lodash": "^4.17.10",
        "moment": "^2.22.1",
        "parsleyjs": "^2.8.1",
        "prop-types": "^15.6.2",
        "react": "^16.3.2",
        "react-datepicker": "^1.4.1",
        "react-dom": "^16.3.3",
        "react-router": "^4.2.0",
        "react-router-dom": "^4.2.2",
        "react-table": "^6.8.2",
        "react-url-query": "^1.4.0"
    },
    "devDependencies": {
        "babel-cli": "^6.26.0",
        "babel-core": "^6.26.2",
        "babel-loader": "^7.1.4",
        "babel-preset-env": "^1.6.1",
        "babel-preset-flow": "^6.23.0",
        "babel-preset-react": "^6.24.1",
        "css-loader": "^0.28.11",
        "file-loader": "^1.1.11",
        "flow-bin": "^0.74.0",
        "image-webpack-loader": "^4.2.0",
        "mini-css-extract-plugin": "^0.4.0",
        "node-sass": "^4.8.3",
        "optimize-css-assets-webpack-plugin": "^4.0.2",
        "prettier": "^1.13.5",
        "sass-loader": "^7.0.1",
        "style-loader": "^0.21.0",
        "uglifyjs-webpack-plugin": "^1.2.5",
        "url-loader": "^1.0.1",
        "webpack": "^4.6.0",
        "webpack-cli": "^2.0.14",
        "webpack-merge": "^4.1.3"
    },
```

**What is the expected behavior?**

I'd expect yarn to resolve all versions of a package defined in dependent packages to a single version that meets all version constraints when possible (i.e. `15.6.2` for `prop-types`).

**Please mention your node.js, yarn and operating system version.**
Yarn: 1.12.3
Node: 8.12.0
OS: Debian GNU/Linux 9 (stretch) (ran in a docker container)

**Comment by jaydiablo** [comment]
Aw man, that fixes the dependency resolution, thanks for the quick response.

Typically we just run `yarn` to pull down updates when the package.json file has changed, I guess I was expecting yarn to update all cases of this particular package because it changed in the `package.json` file.  I assume that `yarn upgrade` would have done the equivalent of deleting the `yarn.lock` file?

**Comment by rally25rs** [comment]
> I assume that yarn upgrade would have done the equivalent of deleting the yarn.lock file?

Somewhat. If you were to `yarn upgrade react-router-dom` then I think it would unlock it's transitive dep on `prop-types`, but other deps like `react-popper` may still be locked? I forget exactly how that works 🤔

**Comment by jaydiablo** [comment]
I can test some with `yarn upgrade` to see what the behavior is on that existing lock file.

All of the lockfile related flags to `yarn install` don't seem to do what I'm looking for here.

Perhaps just deleting the `yarn.lock` file makes the most sense, unless it seems like yarn should have some option for this?

I'm ok with closing this unless you want to have more discussion about that. I'll make some notes for this particular situation.

Thanks!

**Comment by rally25rs** [comment]
Oh, right, `yarn upgrade` with no parameters is functionally equivalent to `rm yarn.lock && yarn install`.

Sorry, took a few minutes for my brain to catch up 😆

**Comment by jaydiablo** [comment]
Just a couple of tests with `yarn upgrade`...

I tried `yarn upgrade prop-types` (this was after a `yarn install` with the `package.json` dependency already changed to `15.6.2` for the version of that package, so `15.6.2` was installed at the root, but `15.6.1` was being used by most of the dependent packages).  This didn't change anything.

Running `yarn upgrade react-router-dom` (one of the packages locked at using `prop-types@15.6.1`) did remove the lock for `react-router` (which was also locked at `15.6.1`) and upgraded it to use `15.6.2` but `react-router-dom` is still shown using `15.6.1` for some reason:

```
=> Found "prop-types@15.6.2"
info Has been hoisted to "prop-types"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "react-router#prop-types"
   - Hoisted from "react-dom#prop-types"
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "204KB"
info Disk size with transitive dependencies: "228KB"
info Number of shared dependencies: 3
=> Found "react-router-dom#prop-types@15.6.1"
info Reasons this module exists
   - "react-router-dom" depends on it
   - Hoisted from "react-router-dom#react-router#prop-types"
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "5.53MB"
info Disk size with transitive dependencies: "14.83MB"
info Number of shared dependencies: 9
```

Upgrading `react-datepicker` seems to resolve that though, and then I just had to upgrade `react-url-query` and that gets all packages on `prop-types@15.6.2`.

Thanks again for your time.

**Comment by mattshin** [comment]
Is there a way to "flatten" _one_ of these subdependencies without blowing out the entire `yarn.lock` or manually upgrading every dependency that brings in an older version? I've looked around for other issues and it seems to be brought up in a couple places (#4986) but ideally I want a programmatic solution (scriptable, opposed to manually finding & deleting blocks from `yarn.lock`)

**Comment by timri** [comment]
You might want to take a look at https://github.com/atlassian/yarn-deduplicate
(It takes a yarn.lock file and tries to consolidate duplicates with overlapping version-ranges, i.e. if a separately installed package can also satisfy a requirement)

**Comment by nitinsurana** [comment]
In my opinion, `yarn upgrade` should have fixed `yarn.lock` to remove the de-duplication, as long as it's satisfies version requirements. 
Please vote re-open this issue and hopefully, get `yarn-deduplicate` merged into yarn.

**Comment by nanaya** [comment]
I just hit by this when upgrading single package (jquery from 3.4.1), another package which depends on in (timeago) ended up having its own copy (the previous jquery version, 3.4.1).

My `yarn.lock` ended up looking like this (part of it).

```
"jquery@>=1.5.0 <4.0":
  version "3.4.1"
  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.4.1.tgz#714f1f8d9dde4bdfa55764ba37ef214630d80ef2"
  integrity sha512-36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==

jquery@^3.4.1:
  version "3.5.0"
  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.5.0.tgz#9980b97d9e4194611c36530e7dc46a58d7340fc9"
  integrity sha512-Xb7SVYMvygPxbFMpTFQiHh1J7HClEaThguL15N/Gg37Lri/qKyhRGZYzHRyLH8Stq3Aow0LsHO2O2ci86fCrNQ==
```

Thankfully there's nothing else depending on jquery so a `yarn upgrade timeago` consolidated it (even though there's no newer timeago).

(or I could've just used the tool linked above but I didn't know about it until now)

Upgrading a single library using `yarn upgrade <library>` seems like a potentially bad idea at the moment.
