### ISSUE TITLE
Yarn Installation PROBELEM

### ISSUE THREAD

**Issue by YOUSAF0** [yarnpkg/yarn#6874]
An unexpected error occurred: "https://registry.yarnpkg.com/create-react-native-app: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80".
HOW TO FIX THAT ISSUE?

**Comment by rally25rs** [comment]
It looks like something is trying to use 127.0.0.1 port 80. Are you trying to proxy yarn through 127.0.0.1?

If not, maybe this is something that the `create-react-native-app` install script is doing, in which case this issue should be filed against the `create-react-native-app` package.

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
