### ISSUE TITLE
Installation Problem: Windows yarn is not verified and also cannot be installed with choco

### ISSUE THREAD

**Issue by jurosh** [yarnpkg/yarn#688]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**
After running app - https://screen.jurosh.com/i16/2016_10_11_1725031145318395835.png

```
Windows protected your PC
Windows SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
App: yarn-0.15.0.msi 
Publisher:  Unknown publisher
```

Choco installer:
```
Installing the following packages:
yarn
By installing you accept licenses for the packages.
yarn not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - yarn - yarn not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
```

Seems like app is missing from choco repositories and yarn.msi is not properly signed.

**Comment by jurosh** [comment]
Seems like sign part is duplicate with https://github.com/yarnpkg/yarn/issues/619 sorry about that.
But probably choco is another new issue...

**Comment by Daniel15** [comment]
Hi @jurosh 

The SmartScreen issue is tracked by #619. The installer is not yet Authenticode signed. You can click "More Info" to run it. The Chocolatey package is still undergoing approval - You can keep an eye on #615 to track that.

Going to close this out since the issues are tracked in #619 and #615. Thank you for reporting it 😄

**Comment by jurosh** [comment]
Installed ignoring certificate and it's working.
Really cool product!

Installation of project with npm takes for more than 4 minutes (on high speed internet).
Installation of project with yarn takes less than minute.

Good work! :)
That's something what was totally needed in JavaScript community - to fix npm.

**Comment by Daniel15** [comment]
Glad to hear it! Thanks for your feedback :D
