### ISSUE TITLE
Install command fails with error related to Git inside Docker

### ISSUE THREAD

**Issue by iliyanyotov** [yarnpkg/yarn#6881]
**What is the current behavior?**
When fetching packages with yarn inside Docker, the command fails caused by a Git error.
I don't think the problem is related to any specific package, but rather the yarn command or something else.

Should I install Git separately before using yarn? That seems to solve to problem, but I would think that's handled by yarn itself. Git is not installed within the base Docker image (node-alpine).

`error Couldn't find the binary git`

[Image of the error](https://imgur.com/VLsDuIz)

[package.json](https://gist.github.com/iliyanyotov/45241fcfb0fbe0abb5587fb13e3efb08)

[Dockerfile](https://gist.github.com/iliyanyotov/099e1dbd164140c7c37e2b036b6af101)

[Full log when running with verbose flag](https://gist.github.com/iliyanyotov/d91c22121d996ec26c672c394cba7ac3)

1. Build the docker image.
2. An error is being shown mid-way fetching the packages.

**What is the expected behavior?**
Successfully install the packages without installing git beforehand inside the Docker image.

**System:**
 - OS: MacOS
 - Docker: 18.09.0
 - Node: 11.4.0
 - Yarn: 1.12.3

**Comment by rally25rs** [comment]
Yes, `git` needs to be installed and available wherever `yarn` is run. Yarn will run git commands as child processes so it needs to be on the `PATH`.

I'm not sure why that isn't listed on the "getting started" or "installing" docs page 🤔 I'll open an issue over on the docs repo to add this as a requirement.

**Comment by iliyanyotov** [comment]
@rally25rs Can you please explain what exactly is yarn running under the hood using Git?

Is it used to pull packages from Git repositories when specified like the example below, because don't see any dependency using that?
`"my-package": "git+https://.." `

The strange part is that it was working previously without any changes in the environment (Docker image, yarn & node versions, etc).

Just tested building the same image without this package and it worked fine: 
`"webpack-s3-plugin": "^1.0.3",`

So it's maybe related to this package or any of his dependencies instead of a problem with yarn itself.

**Comment by rally25rs** [comment]
Ah, yeah, I was assuming you had some git dependencies. I think the `yarn publish` command might use it too. If you are just doing a normal install without any git dependencies and running into this, then can you share your `package.json`? I could try to reproduce it here and see at what point it tries to call git.

(going to reopen this issue until we can confirm why `git` is being called)

**Comment by rally25rs** [comment]
I opened https://github.com/yarnpkg/website/issues/901 to capture the doc change.

**Comment by anargu** [comment]
I had the same issue. In my case I removed yarn.lock then I tested again and it worked!. You may have a try deleting yarn.lock. Maybe yarn requires git in certain dependencies declared in yarn.lock

**Comment by samkelleher** [comment]
I had the same issue. In my case I removed `flow-typed install` from the `postinstall` script because my project is using Flow typings, and the `flow-typed` library uses git to pull down the latest definitions.

Since it's required only during docker building, I was able to skip it changing the command to `yarn install --ignore-scripts` and the issue was resolved.

**Comment by blowsie** [comment]
Same for me no resolution yet.
Should i be installing git in docker?

For me its working locally, but not in TeamCity (CI)
```
yarn install v1.22.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'client' failed to build: The command '/bin/sh -c yarn install --frozen-lockfile --no-cache --production     && rm -f .npmrc' returned a non-zero code: 1
```

**Comment by rally25rs** [comment]
@blowsie if you have a dependency that is a git url, then yarn uses the `git` command line tool to download it. The resolution is to have `git` available where yarn is being run.

**Comment by marciovsena** [comment]
@blowsie, I solved it with `RUN apk add git` before installing the dependencies

**Comment by carlosgonzalezucv** [comment]
thanks @marciovsena that solves the problem for me.

**Comment by tarunchimata** [comment]
https://memotut.com/docker-what-to-do-when-error-couldn%27t-find-the-binary-git-appears-60518/
its resolved my issue

**Comment by toledoroy** [comment]
> https://memotut.com/docker-what-to-do-when-error-couldn%27t-find-the-binary-git-appears-60518/ its resolved my issue

Thanks! Worked for me too.

**Comment by jengroff** [comment]
Worked for me too! (I had the same problem y'all were describing). 
Thank you!

**Comment by kalinchernev** [comment]
https://github.com/yarnpkg/yarn/issues/6881#issuecomment-687220459 is a good solution, 

```
RUN apk add --no-cache git=2.34.4-r0
```

To be perfectly correct with https://github.com/hadolint/hadolint/wiki/DL3018 :D

**Comment by greazleay** [comment]
> [#6881 (comment)](https://github.com/yarnpkg/yarn/issues/6881#issuecomment-687220459) is a good solution,
> 
> ```
> RUN apk add --no-cache git=2.34.4-r0
> ```
> 
> To be perfectly correct with https://github.com/hadolint/hadolint/wiki/DL3018 :D

Solved my issue, many thanks

**Comment by hieunt0303** [comment]
> RUN apk add git

thanks
