### ISSUE TITLE
Path must be a string. Received true, yarn config set cache-folder <path>

### ISSUE THREAD

**Issue by Jackob32** [yarnpkg/yarn#6883]
**This is a bug report**

yarn config set cache-folder <path>

**What is the current behavior?**
I miss taped the yarn config set cache-folder <path> command and didnt enter path

from that time on yarn throws error, even if i try to change back and the error persist after reinstalling.

error An unexpected error occurred: "Path must be a string. Received true".

**If the current behavior is a bug, please provide the steps to reproduce.**

yarn config set cache-folder

everything stops working

**node.js, yarn and operating system version.**

Win10
yarn  v1.12.3
node v8.12.0

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js config set cache-folder

Yarn version: 
  1.12.3

Node version: 
  8.12.0

Platform: 
  win32 x64

Trace: 
  TypeError: Path must be a string. Received true
      at assertPath (path.js:28:11)
      at Object.resolve (path.js:211:7)
      at YarnRegistry.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:91033:50)
      at Generator.next (<anonymous>)
      at step (C:\Program Files (x86)\Yarn\lib\cli.js:304:30)
      at C:\Program Files (x86)\Yarn\lib\cli.js:315:13
      at <anonymous>

**Comment by GioLogist** [comment]
Any workaround at the moment? Reinstalling doesn't seem to do the trick. Also tried downgrading, no success there either.

**Comment by lf1029698952** [comment]
same problem, it is a bug, yarn cannot check when <path> is null.

**Comment by tolaseadegbite** [comment]
> 
> 
> Any workaround at the moment? Reinstalling doesn't seem to do the trick. Also tried downgrading, no success there either.
> 
> Edit: manually editing `~/.yarnrc` (which yarn advises against) seems to be the workaround for now

What did you adjust in `~/.yarnrc`? All trials to get this work has proved abortive.

**Comment by tolaseadegbite** [comment]
Any solution guys??

**Comment by paul-soporan** [comment]
In v1 you have to remove the `cache-folder` option from your `.yarnrc` file.

Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
