### ISSUE TITLE
https://yarnpkg.com shows the latest stable release is 1.13.0 but in fact it is not available for Debian

### ISSUE THREAD

**Issue by vlasenko** [yarnpkg/yarn#6903]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
yarn website shows at the moment that the latest stable release is v1.13.0 but if you try to examine Debian repo, it shows the latest release is `Version: 1.12.3-1`, not 1.13.0

**If the current behavior is a bug, please provide the steps to reproduce.**
`sudo apt update`
`sudo apt show yarn`

**What is the expected behavior?**
Version 1.13.0 should be showed as the latest and should be available for installation/upgrade

**Comment by Daniel15** [comment]
Interesting, Aptly is throwing an error when it tries to build the repo:
```
[+] yarn_1.13.0-1_all added
+ aptly -config=./.aptly.conf publish update -gpg-key=23E7166788B63E1E stable
ERROR: unable to update: local repo with uuid cf9b0d68-8463-4589-85ab-302e81ac6147 not found
```

Will take a look, and file an issue add some more error reporting to ensure we catch this if it happens again in the future. Thanks for reporting this!

**Comment by vlasenko** [comment]
Thank you Daniel!

**Comment by Daniel15** [comment]
It's only failing on the build server, not on my laptop. I updated the repo on my laptop (as a workaround for the issue) and will file another issue to look into this in more detail. For now, it should work and you should see 1.13.0 now :)

**Comment by Daniel15** [comment]
Confirmed that 1.13.0 is there now:
```
11:47 daniel@vps03 /home/daniel
% apt list -a yarn
Listing... Done
yarn/stable,stable 1.13.0-1 all [upgradable from: 1.12.3-1]
yarn/stable,stable,now 1.12.3-1 all [installed,upgradable to: 1.13.0-1]

```

**Comment by vlasenko** [comment]
@Daniel15 Thank you, when yarn first told me, there is version 1.13.0, I have received the error message from apt about wrong repo key. Now I have received this message again. I'm not sure, but maybe it is related to this problem too:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F77679369475BAA
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F77679369475BAA
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
It is not difficult for me to redownload public key for the repo, but why it started to change each time you are trying to release new version? Just for your information.

**Comment by Daniel15** [comment]
That's strange... That's a new key I added for the nightly repo, it shouldn't be used for the stable repo. I'll have to look and work out what happened.

**Comment by hentisemmle** [comment]
@Daniel15 any information on this ? Can you clarify what is the correct key to use for the https://dl.yarnpkg.com/debian/ repo ?
