### ISSUE TITLE
Installation Problem: Unexpected token { in cli.js 

### ISSUE THREAD

**Issue by Kodedyukh** [yarnpkg/yarn#6914]
**Which operating system are you using:**
On Ubuntu 16.04 LTS

**Please describe the steps you took when trying to install Yarn and what went wrong:**
After removing cmdtest and installing node I've followed steps described here https://yarnpkg.com/lang/en/docs/install/#debian-stable

But when I run
`yarn --version`

I get
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by philoez98** [comment]
same for me

**Comment by mmxgn** [comment]
Same thing here

**Comment by kaytotes** [comment]
Same issue here.

**Comment by jeffpaulKinsta** [comment]
Same issue as well.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Comment by jeffpaulKinsta** [comment]
Updating nodejs resolved this for me:
IE:
`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

apt-get install -y nodejs`

**Comment by jvanus** [comment]
Here's a Dockerfile you can use to duplicate the issue. Includes fix from @jeffpaulKinsta 

```
FROM debian:stretch-slim

# Setup the base OS
RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends build-essential  \
    apt-transport-https curl ca-certificates gnupg2 apt-utils nodejs

# Install node from nodesource
# uncomment the next 2 lines for fix
# RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
#  && apt-get install -y nodejs

# Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && apt-get update -qq \
 && apt-get install -y yarn

# Test
RUN yarn --version
```

Save the above to `Dockerfile` and run: `docker build .`

**Comment by Kodedyukh** [comment]
Okay, thank you! Everything works with nodejs update

**Comment by Sx3** [comment]
> Updating nodejs resolved this for me:
> IE:
> 
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> 
> apt-get install -y nodejs

yeah it resolved .Great.Thank you.

**Comment by sleaz0id** [comment]
@jvanus 
> ```
> ...
> # Setup the base OS
> RUN apt-get update -qq \
>  && apt-get install -y --no-install-recommends build-essential  \
>     apt-transport-https curl ca-certificates gnupg2 apt-utils **nodejs**
> 
> # Install node from nodesource
> # uncomment the next 2 lines for fix
> # RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
> #  && apt-get install -y **nodejs**
> ...
> ```

With this solution you're installing nodejs twice. I think there is no need to do that.

**Comment by franzliedke** [comment]
I encountered this problem as well. Ironically, the same version of Yarn that threw the error when Node 4 was installed, showed the following error message when no Node was installed:

> Yarn requires Node.js 4.0 or higher to be installed.

**Comment by BestDr** [comment]
I have this problem on my MX Linux OS, I can't fix this yarn problem, also I tried updating the nodejs but I faced some problems, it shows that continuum isn't supported in curl .. or something like that.

**Comment by successgdc** [comment]
Thank you @jeffbcross .
same problem on my server, and fixed by update nodejs.

**Comment by NBardelot** [comment]
Same problem here. Breaking LTS is not nice...

**Comment by dt-ap** [comment]
nvm: 0.34.0
node: 5.12.0
npm: 3.8.6

I cannot upgrade my node version because our project still use old library that have to use node <=6. 
For anyone who cannot update node above v5.12.0. I use **yarn 1.12.3** and it works.

**Comment by alfiedotwtf** [comment]
Bump. This looks like it's still happening

**Comment by BrijeshKarpe** [comment]
Update nodejs https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/

1. sudo apt-get install curl python-software-properties
2. curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
3. sudo apt-get install -y nodejs

**Comment by tomprogers** [comment]
I still get this on MacOS (and using nvm, node v12.6.0)

**Comment by zen-rashmib** [comment]
> I still get this on MacOS (and using nvm, node v12.6.0)

i even still get the same issue

**Comment by manoj629** [comment]
Hi All 
OS : Windows 10 
I am getting below error , can anyone help.
C:\Program Files (x86)\Yarn\lib\cli.js:46083
  let {
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\bin\yarn.js:24:13)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
Process terminated with code 1.

**Comment by Flexo013** [comment]
@manoj629 Try updating your npm first. I had the same error and that is what fixed it for me.

**Comment by congsonbk27** [comment]
sudo apt update
sudo apt install build-essential apt-transport-https lsb-release ca-certificates curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn

**Comment by ramijames** [comment]
> Updating nodejs resolved this for me:
> IE:
> 
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> 
> apt-get install -y nodejs

Thanks for this.

**Comment by SamalaSumanth0262** [comment]
Wow ! Hurray !!!

**Comment by u-can-miracle** [comment]
I've got such error because I'm using `nvm` but I didn't install any node version :stuck_out_tongue_closed_eyes: 
`nvm list`

```
N/A
iojs -> N/A (default)
node -> stable (-> N/A) (default)
unstable -> N/A (default)
```

Just install node version which you need, for example
`nvm install 13.3.0`

**Comment by siyer32** [comment]
This is an issue in Debian 9 (stretch) and resolves when you install node.js
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by scheming-monkey** [comment]
> 
> 
> Updating nodejs resolved this for me:
> IE:
> 
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> 
> apt-get install -y nodejs

Got this problem install PowerDNS admin. This nodejs update resolve it for me.

**Comment by Daniel09Fernandes** [comment]
> A atualização do nodejs resolveu isso para mim:
> IE:
> 
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> 
> apt-get install -y nodejs

thanks so much, you save my nigth haha

**Comment by zwqnju** [comment]
I solve this issue using the following commands in Ubuntu 16.04:
`sudo npm install -g n`
`sudo n stable `

**Comment by alexalannunes** [comment]
@jvanus Thanks bro! :+1:

**Comment by lailailee** [comment]
> Updating nodejs resolved this for me: IE:
> 
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> 
> apt-get install -y nodejs

thanks, its useful
