### ISSUE TITLE
`yarn bin` does not respect `--modules-folder`

### ISSUE THREAD

**Issue by allenwu1973** [yarnpkg/yarn#6918]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
`yarn bin` does not respect `modules-folder`

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ pwd
/tmp/test
$ yarn add webpack --modules-folder vendor/node_modules/
$ ls vendor/node_modules/.bin/
acorn  atob  errno  json5  miller-rabin  mkdirp  rimraf  sha.js  terser  webpack
$ yarn bin webpack --modules-folder vendor/node_modules/
error Couldn't find a binary named "webpack"
$ yarn bin --modules-folder vendor/node_modules/
/tmp/test/node_modules/.bin
```

**What is the expected behavior?**
`yarn bin` should utilize `modules-folder` flag and report the correct path

**Please mention your node.js, yarn and operating system version.**
node v8.11.1
yarn v1.13.0
ubuntu 16.04

**Comment by rally25rs** [comment]
Could modify #6850 to handle this, since that PR hasn't been accepted yet.
