### ISSUE TITLE
Preserve none zero exit code

### ISSUE THREAD

**Issue by zhigang1992** [yarnpkg/yarn#6925]
I want to request a *feature*

### Preserve none zero exit code.

I'm trying to create a Github Action.

https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#exit-codes-and-statuses

To filter actions, it needs `78` as exit code:

`index.js`
```js
const process = require('process');
process.exit(78)
```

`npm start` will yield 78, but `yarn start` will yield 1.

<img width="1031" alt="screen shot 2019-01-15 at 8 44 31 pm" src="https://user-images.githubusercontent.com/1057756/51181533-61a1c280-1906-11e9-9cd3-988919cb5a87.png">

Is there an option that already does this?

**Comment by arcanis** [comment]
Hm that sounds like a bug, I agree the status code should be preserved. Would you like to open a PR to fix this? I think it should be in executeLifecycle and/or run.js

**Comment by zhigang1992** [comment]
Sure, will give it a try...
