### ISSUE TITLE
Inconsistent upgrade command

### ISSUE THREAD

**Issue by iyn** [yarnpkg/yarn#694]
Here: https://yarnpkg.com/en/docs/managing-dependencies we have:
```
yarn upgrade [package]
yarn upgrade [package]@[version]
yarn upgrade [package]@[dist-tag]
```

But here: https://yarnpkg.com/en/docs/cli/upgrade it's not documented and current version (0.15.1) doesn't allow for arguments with `upgrade` command. I don't know what is expected behavior but the current one (at least on documentation level) is inconsistent.

**Comment by kittens** [comment]
Thanks for reporting this @iyn, we're tracking this in #598. Please don't hesitate to open issues for anything else you find, it's super appreciated. Thanks!
