### ISSUE TITLE
`yarn install` fails silently inside docker container behind a corporate proxy

### ISSUE THREAD

**Issue by lmcarreiro** [yarnpkg/yarn#6963]
**Do you want to request a *feature* or report a *bug*?**

It is a bug

**What is the current behavior?**
It fails silently with exit code 0

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Download the `package.json` and `yarn.lock` from this [gist](https://gist.github.com/lmcarreiro/6b602dc7c57686374e0cb1c1d9073547)

2) Create a `Dockerfile` with this content:
```Dockerfile
FROM node:10.15.0
COPY . .
RUN yarn install
```

3) Run `docker build .`

I ran it behind a corporate proxy, without passing the build environment variables `http_proxy` and `https_proxy`. It fails silently in the step 2 of the install with no error message and exit code zero.

If I run `docker build . --build-arg http_proxy=http://user:pass@proxy-host:port --build-arg https_proxy=http://user:pass@proxy-host:port` it works fine.

**What is the expected behavior?**
An error message saying that some http request failed.

**Please mention your node.js, yarn and operating system version.**
OS, node and yarn version are from the official docker image `node:10.15.0`:
```
root@de27e495d159:/app# env
YARN_VERSION=1.12.3
HOSTNAME=de27e495d159
PWD=/app
HOME=/root
NODE_VERSION=10.15.0
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
root@de27e495d159:/app# yarn install
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[--------------------------------------------------------------------------------------------------------------] 0/1363
root@de27e495d159:/app# echo $?
0
root@de27e495d159:/app# yarn --version
1.12.3
root@de27e495d159:/app# node --version
v10.15.0
root@de27e495d159:/app# uname -a
Linux de27e495d159 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 GNU/Linux
root@de27e495d159:/app#
```

**Comment by lmcarreiro** [comment]
I saw an "info" message just one time:
![image](https://user-images.githubusercontent.com/13019179/51758265-80dde400-20ac-11e9-97c6-7807e2794d9f.png)

Tried again many times and this messege never happened again:
![image](https://user-images.githubusercontent.com/13019179/51758363-a23ed000-20ac-11e9-9887-26eb15c431ad.png)

**Comment by lmcarreiro** [comment]
Tried the same in node:10.5 instead of node:10.15 image, the yarn version was 1.7.0 instead of 1.12.3, and it does show error messages:

```
root@b9c1c6edafdb:/app# yarn install
yarn install v1.7.0
(node:29) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui/core/-/core-3.7.1.tgz: connect ECONNREFUSED 104.16.16.35:443".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@b9c1c6edafdb:/app#
```

![image](https://user-images.githubusercontent.com/13019179/51831009-48bae900-22d8-11e9-8363-9b4ed372dc65.png)

Version 1.12.3 is not handling the error like it was used to.

I tested in node:latest that has the yarn 1.13.0 and it doesn't too, the behavior is the same as node:10.15 image (with yarn 1.12.3)

**Comment by denitol** [comment]
Hello @lmcarreiro 
I saw the same error, but I used proxy. I could not add a proxy command 
`yarn set proxy  http://example-proxy:8080` 

it works like this 
`yarn install --proxy http://example-proxy:8080`

**Comment by yan12125** [comment]
Looks quite similar to #6915. I believe it's a bug since yarn 1.11.0, and here's my fix: #6968.

**Comment by azz** [comment]
Thanks @yan12125 - confirmed this is fixed in `node:11-alpine`.

**Comment by lmcarreiro** [comment]
Tried in node:12 with yarn 1.16.0 and it is fixed.
