### ISSUE TITLE
Yarn install giving 503.

### ISSUE THREAD

**Issue by ayolas** [yarnpkg/yarn#6964]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
[OSX]user1$ yarn install
yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "http://fe-nexus.aws.netspend.net/repository/npm/make-plural/-/make-plural-4.3.0.tgz: Request failed \"503 Service Unavailable\"".

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Yarn install to install the dependencies.

**Please mention your node.js, yarn and operating system version.**
node js - v10.15.0  npm - 6.4.1
OS - 10.11.6

Please note that if i goto the url mentioned in the error message "http://fe-nexus.aws.netspend.net/repository/npm/make-plural/-/make-plural-4.3.0.tgz", i can access it.

**Comment by dzek69** [comment]
I cannot access given URL, there is dns error: ERR_NAME_NOT_RESOLVED

Are you sure your browser is behaving the same as your command line environment (or node)?

Can you `wget http://fe-nexus.aws.netspend.net/repository/npm/make-plural/-/make-plural-4.3.0.tgz` just fine?
Can you download this file via simple node script:
```javascript
const http = require("http");
const req = http.get("http://fe-nexus.aws.netspend.net/repository/npm/make-plural/-/make-plural-4.3.0.tgz", function (response) {
    console.log(response);
});
req.on("error", function (e)  {
    console.error("cannot download");
    console.error(e.message);
});
```

**Comment by ayolas** [comment]
I dont have wget, i did -  curl -s "http://fe-nexus.aws.netspend.net/repository/npm/make-plural/-/make-plural-4.3.0.tgz" and i am able to see the contents.
Also, if i copy the url directly in the browser, that works too.

**Comment by ayolas** [comment]
curl -s "http://fe-nexus.aws.netspend.net/repository/npm/prop-types/-/prop-types-15.6.2.tgz"

**Comment by ayolas** [comment]
Yes you are right. When i do the nslookup - this is the error message i see - ;; connection timed out; no servers could be reached.

Do you think this is something which needs to be fixed on the yarn side?

**Comment by olingern** [comment]
@ayolas can you close if this is a non-issue?
