### ISSUE TITLE
`yarn cache ls` fails on scoped packages 

### ISSUE THREAD

**Issue by grantpatten** [yarnpkg/yarn#698]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When the package.json contains scoped packages like `@types/node` the `yarn cache ls` command fails with the follow error:

```
yarn cache v0.15.0
error ENOENT: no such file or directory, open 'C:\Users\grant.patten\AppData\Local\Yarn\npm-@types\.yarn-metadata.json'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/cache for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install `@types/node` (`yarn add @types/node`)
2. Run `yarn cache ls`

**What is the expected behavior?**
The cache content should be displayed.

**Please mention your node.js, yarn and operating system version.**
node v6.3.1
yarn v0.15.0
Windows 10

**Comment by lucky7id** [comment]
#713 Might be related

**Comment by mattstyles** [comment]
Having a similar problem, but at a level down where unscoped modules install scoped modules

```
yarn add most
// Works great to do the install
```

```
yarn cache ls

yarn cache v0.15.1
error ENOENT: no such file or directory, open '/Users/mattstyles/.yarn-cache/npm-@most/.yarn-metadata.json'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/cache for documentation about this command.
```

**node v6.7.0**
**yarn 0.15.1**
**Mac OSX 10.11.6**

**Comment by mriehema** [comment]
Same here:

```
$ yarn cache ls
yarn cache v0.15.1
error ENOENT: no such file or directory, open 'C:\Users\mriehema\AppData\Local\Yarn\npm-@coremedia\.yarn-metadata.json'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/cache for documentation about this command.
```
node: 4.4.7
yarn: 0.15.1
Windows 7 (64bit)

**Comment by wyze** [comment]
Looks like this is fixed and will be included in the next release. Verified it is working on `master`.
