### ISSUE TITLE
can not find executables in pnp mode after `yarn unplug`

### ISSUE THREAD

**Issue by loveky** [yarnpkg/yarn#6982]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. in our current project, run `yarn --pnp` to enable pnp mode
2. everything works fine and I can `yarn run xxx` to run executables.
3. I want to debug a package, so I do `yarn unplug xxx` and the package is copied to `./.pnp/unplugged/xxx-some-hash-here/node_modules/xxx/`
4. when I run `yarn start`, I got `/bin/sh: xxx: command not found`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I should be able to `yarn run xxx` just like before `yarn unplug`
**Please mention your node.js, yarn and operating system version.**

Mac OSX
Node v10.13.0
Yarn 1.13.0

After dive into the code base, I find this is probably caused by the `.bin` directory not being copied during `yarn unplug`.  Then I found `.bin` is add to `ignoreBasenames` in #6628 intentionally.

Maybe we should add some login to keep copying `.bin` during `yarn unplug` ?

**Comment by SirNeural** [comment]
I'm experiencing a the same issue, running a yarn run command that references a bin from a package that has been unplugged returns a command not found error. 
For reference I'm converting a nuxt 2.4.0 project to pnp, and the yarn --pnp process seems to automatically unplug nuxt.
Running Mac OSX with Node v10.15.0 and yarn 1.14.0

**Comment by mayfieldiv** [comment]
I'm getting the same thing with packages automatically being unplugged (presumably because they have postinstall scripts), and then Yarn not being able to call the executables in the bin directories of those packages.

Is there any known workaround available for this?

**Comment by paul-soporan** [comment]
Fixed in v2.

https://yarnpkg.com/getting-started/migration
