### ISSUE TITLE
Last published version of gatsby-link is missing on yarn

### ISSUE THREAD

**Issue by sidharthachatterjee** [yarnpkg/yarn#6987]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We published `gatsby-link` over an hour ago and while the latest version (2.0.10) seems to be up on npm, it doesn't show up on yarn

https://www.npmjs.com/package/gatsby-link
https://yarnpkg.com/en/package/gatsby-link

**If the current behavior is a bug, please provide the steps to reproduce.**
Unfortunately not sure how to reproduce this, this seems like a one off thing

**What is the expected behavior?**
Yarn to have the same version

**Please mention your node.js, yarn and operating system version.**
yarn 1.13.0
node v11.8.0
macOS Mojave 10.14.2

**Comment by charlex** [comment]
I'm seeing the same problem with another package:

https://yarnpkg.com/en/package/apollo-link
https://www.npmjs.com/package/apollo-link
