### ISSUE TITLE
Cannot ready property 'endsWidth' of undefined

### ISSUE THREAD

**Issue by zslabs** [yarnpkg/yarn#699]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
Running `yarn` on repo shows:

```
error TypeError: Cannot read property 'endsWith' of undefined
    at removeSuffix (/Users/zach/.yarn/lib/util/misc.js:42:14)
    at Function.parseRefs (/Users/zach/.yarn/lib/util/git.js:447:55)
    at /Users/zach/.yarn/lib/util/git.js:376:24
    at next (native)
    at step (/Users/zach/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/zach/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn` to install deps.

**What is the expected behavior?**

Completed install

**Please mention your node.js, yarn and operating system version.**

Node v6.5.0
Yarn 0.15.1
Yosemite 10.11.6

**Comment by hzoo** [comment]
Looks like it's from https://github.com/yarnpkg/yarn/blob/5545d11e7da72940d090c1d9fd2745e1b8b9af2d/src/util/git.js#L350

```
    for (const line of refLines) {
      // line example: 64b2c0cee9e829f73c5ad32b8cc8cb6f3bec65bb refs/tags/v4.2.2
      const [sha, id] = line.split(/\s+/g);
      let [,, name] = id.split('/');

      // TODO: find out why this is necessary. idk it makes it work...
      name = removeSuffix(name, '^{}'); // name is undefined
```

**Comment by ijlind** [comment]
I got the same error today on a repo that has a private git repo as a dependency. Installs smoothly on other repos.

The private git dependency is defined along these lines in my package.json -file:

```
"dependencies": {
  "private_dependency_name": "git+ssh://git.private.org/home/git/private_dependency_name.git#v1.0.0"
},
```

Another private repo I have has an otherwise identical package.json contents and there yarn works a treat.

**Comment by lolmaus** [comment]
I'm using NVM. Ran `npm i -g yarn` on Node 6.7.0 and saw this error.

**Comment by lolmaus** [comment]
Yep, also ran into this issue on a project depending on a private GitHub repo.

**Comment by chicoxyzzy** [comment]
See https://github.com/yarnpkg/yarn/pull/971

**Comment by samccone** [comment]
Dup #573
