### ISSUE TITLE
[Discussion] Any chance yarn will have linting and testing of packages so binaries can be shipped?

### ISSUE THREAD

**Issue by cookiengineer** [yarnpkg/yarn#700]
I'm kind of eager to figure out what the future plans of yarn are. The focus of the project seems to fit most of the needs I would have to a package manager in terms of reliability.

However, in order to have more advantages from a package manager, I wanted to ask whether these topics already are being discussed, planned or maybe up for discussion? Is there a roadmap somewhere that shows what the future of yarn will hold?

I got these questions in my head; which I think are essential problems in the npm/js ecosystem at the moment when it comes to stability, maintenance and future-proof package distribution. I'm also talking about an upstream/downstream management of security-relevant fixes for legacy and already-in-the-field packages, for example.
- Will yarn have automated linting and formatting of packages?
- Will yarn have automated testing of packages?
- Can binary (built, compressed, zero-dependency) packages be distributed?
- What about node-gyp and the troubles for different architectures like ARM?

**Comment by arcanis** [comment]
> - Will yarn have automated linting and formatting of packages?
> - Will yarn have automated testing of packages?

I don't see how we could do it. Everyone has a different way to lint / test their projects.

> - Can binary (built, compressed, zero-dependency) packages be distributed?
> - What about node-gyp and the troubles for different architectures like ARM?

You can ship binaries inside your packages, but that's not advised. It will break depending on various factors, such as the current Node version.
