### ISSUE TITLE
plugnplayWindowsSupport warning because of drive letter case mismatch

### ISSUE THREAD

**Issue by codepunkt** [yarnpkg/yarn#7005]
When running `yarn --pnp` in directory 'D:\projectName', this pops up:

**warning** Plug'n'Play on Windows doesn't support the cache and project to be kept on separate drives

The cache directory is configured as 'd:\\.yarncache', `yarn cache dir` returns 'd:\\.yarncache\v4'.
Afaik, windows drive letters in paths are case insensitive, but the code around line 400 of `src/config.js` does not account for that and produce a mismatch between `cacheRootFolderDrive` and `lockfileFolderDrive`, resulting in the warning shown above.

It would be nice if this could be fixed.

specs: windows 10, yarn 1.13.0, node 10.15.1

**Comment by codepunkt** [comment]
Even if i do `yarn config set cache-dir D:\.yarncache` and can read this out well with `yarn config get cache-dir`, the cache dir drive letter is still lowercase.

**Comment by codepunkt** [comment]
@arcanis I'm not sure if and how this could be tested. Just adding the `toLowerCase` twice like i did in my local `cli.js` sounds doable.

**Comment by arcanis** [comment]
Yeah, this one will be a pain to test. The best way would be to setup a mock, but that would complexify our whole test infra for a corner case. I'm fine with no tests for this one if Flow passes.
