### ISSUE TITLE
Where the hack is my global package?

### ISSUE THREAD

**Issue by Tonysmark** [yarnpkg/yarn#7006]
Recently, I've been study vue.js and when I type `yarn global add @vue/cli-service-global` in powershell which successfully installed. However, when I type `vue serve` in powershell  , I got an error.
And to figure out what's happened I check the environment it's fine, then I look at my folder under `yarn/bin` path, guess what? There is nothing!! nothing!!
![image](https://user-images.githubusercontent.com/22767695/52285672-be424b80-29a1-11e9-800f-de3d8c4ce86d.png)

**Comment by rally25rs** [comment]
On linux/mac the bin ends up linked in `~/.config/yarn/global/node_modules/.bin/vue` but off hand I don't remember what it does on Windows. I don't have my windows machine with me right now to try it.

**Comment by rally25rs** [comment]
I think the command `yarn global dir` will tell you where yarn installs things when `global` is used, and adding `/.bin` to the end of whatever that command outputs should be where it is putting the globally installed bin files.

**Comment by Tonysmark** [comment]
I don’t get it!! I mean I just use this command npm i -g @vue/cli  @vue/cli-service-global after installation I use vue serve and then It works…So,this may be some ‘’yarn problem’’ 

发送自 Windows 10 版邮件应用

发件人: Jeff Valore
发送时间: 2019年2月6日 3:22
收件人: yarnpkg/yarn
抄送: tony; Author
主题: Re: [yarnpkg/yarn] Where the hack is my global package? (#7006)

I think the command yarn global dir will tell you where yarn installs things when global is used, and adding /.bin to the end of whatever that command outputs should be where it is putting the globally installed bin files.

**Comment by Tonysmark** [comment]
Yes! `yarn global bin` did tell me the dir to binary files.
![default](https://user-images.githubusercontent.com/22767695/52432399-4a40a880-2b45-11e9-8366-a171fe8ea486.png)
But, still......gotta nothing here

**Comment by rally25rs** [comment]
The `package.json` for `@vue/cli-service-global`

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service-global/package.json

does not specify a `bin` section, so does not have any commands added.

I get the same behavior on `npm`

```
~ 🐒   npm install -g @vue/cli-service-global

> fsevents@1.2.11 install /Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/@vue/cli-service-global/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> yorkie@2.0.0 install /Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/@vue/cli-service-global/node_modules/yorkie
> node bin/install.js

setting up Git hooks
trying to install from sub 'node_module' directory, skipping Git hooks installation

> core-js@3.6.0 postinstall /Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/@vue/cli-service-global/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/@vue/cli-service-global/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

+ @vue/cli-service-global@4.1.1
added 1261 packages from 881 contributors in 42.342s

~ 🐒   vue
-bash: vue: command not found
```
