### ISSUE TITLE
`yarn cache` suggests deprecated verb `ls`

### ISSUE THREAD

**Issue by tomByrer** [yarnpkg/yarn#7022]
Current:
```shell
$ yarn cache
yarn cache v1.12.3
error Invalid subcommand. Try "ls, list, clean, dir"
$ yarn cache ls
yarn cache v1.12.3
warning `yarn cache ls` is deprecated. Please use `yarn cache list`.
```

Expected:
`Try "list, clean, dir"`

cheers :)

**Comment by paul-soporan** [comment]
Closing as we don't do such small fixes to v1 anymore.

Our focus is on v2 where this issue doesn't exist: https://yarnpkg.com/getting-started/migration
