### ISSUE TITLE
dependence

### ISSUE THREAD

**Issue by sung-gue** [yarnpkg/yarn#7023]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by KevinGrandon** [comment]
Hello, looks like this issue was opened by mistake? Any additional context you could provide?

(I'm not a member of the yarn team, just trying to help out)

**Comment by sung-gue** [comment]
Thank you for your interest. :)
Well, I do not know why the issue was written. i didn't clicked comment button...

My CentOS was using nvm to manage the version of node. When I tried to install Yarn a few days ago using yum, I remember that it was not installed due to nodejs dependency problem.
i tried the following code, but Yarn installation was not successful.

`$ yum install -y yarn --skip-broken`

after installing nodejs using yum, I installed the Yarn and the problem is resolved.

thank you. have a good day ~
