### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by darrenjennings** [yarnpkg/yarn#7026]
Been noticing `502 Bad Gateway` pretty often the last couple days. Looks like it's coming from cloudflare and is easily reproducible by just browsing to https://registry.yarnpkg.com/ and refreshing a few times.

**Comment by andypillip** [comment]
I guess this got resolved in the meantime? I cannot reproduce.

**Comment by paul-soporan** [comment]
Closing as this has been resolved.
