### ISSUE TITLE
Installation Problem: Syntax Error when invoking yarn (e.g. yarn --version) for stable and rc, but not nightly

### ISSUE THREAD

**Issue by zroach** [yarnpkg/yarn#7038]
**Which operating system are you using:**
Ubuntu 16.04 LTS 64 bit 

(can provide more info if needed, but not sure what all you'd need to know)

**Please describe the steps you took when trying to install Yarn and what went wrong:**
Installing yarn via the instructions and kept hitting a SyntaxError. 
This may be something to do with my filesystem - I am new to front-end development, but it is weird that the nightly branch installs successfully...

Made a script invoked with command `./yarn.sh &> errors.txt` below:

**errors.txt**
```
testing: dl.yarnpkg.com/debian/ rc main
deb https://dl.yarnpkg.com/debian/ rc main
Removed
Updated
Installed
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)


testing: dl.yarnpkg.com/debian/ stable main
deb https://dl.yarnpkg.com/debian/ stable main
Removed
Updated
Installed
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)


testing: nightly.yarnpkg.com/debian/ nightly main
deb https://nightly.yarnpkg.com/debian/ nightly main
Removed
Updated
Installed
1.13.0-20181121.1436
success
```

**yarn.sh**
```
#!/usr/bin/env bash

for url in  "dl.yarnpkg.com/debian/ rc main" "dl.yarnpkg.com/debian/ stable main" "nightly.yarnpkg.com/debian/ nightly main";
do
    printf "testing: $url\n"
    echo "deb https://$url" | sudo tee /etc/apt/sources.list.d/yarn.list && sudo apt-get -y remove yarn &> /dev/null && echo Removed && sudo apt-get update &> /dev/null && echo Updated && sudo apt-get -y install yarn &> /dev/null && echo Installed && yarn --version && echo "success"
    printf "\n\n"
done
```

**Comment by laerus** [comment]
Can reproduce on Debian stretch. yarn version Version: 1.13.0-1 from the official https://dl.yarnpkg.com/debian/ repo. Even thought the installation finishes, just running `yarn` results in the `SyntaxError` mentioned above. ridiculous :rofl:

**Comment by heywiki** [comment]
Had the same problem on windows: The installer obviously does not check the node.js version. I had node 4.4 installed. After i installed the latest version, it worked

**Comment by Liotarne** [comment]
Try to install node before executing this :) 

( node --version )

PS: If you're on linux and you've installed node as sudo it will not work as regular user ;)

**Comment by DinbandhuKumarSingh** [comment]
update node:

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -apt-get install -y nodejs

**Comment by olleharstedt** [comment]
> update node:
> 
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -apt-get install -y nodejs

I'm getting `bash: --: invalid option` when trying this.

Ubuntu 16.04.

**Comment by olleharstedt** [comment]
The instructions here worked for me: https://stackoverflow.com/questions/41195952/updating-nodejs-on-ubuntu-16-04

**Comment by paul-soporan** [comment]
Closing as unactionable - you're using an old Node version.
