### ISSUE TITLE
Support package.hjson

### ISSUE THREAD

**Issue by laktak** [yarnpkg/yarn#704]
package.json is not really suitable for configuration as it does not allow comments and is error prone to write.

Would it be possible to support a package.hjson format? [Details on Hjson](http://hjson.org).

**Comment by havenchyk** [comment]
package.json doesn't allow comments, but it's a standard in the industry.

**Comment by laktak** [comment]
> but it's a standard in the industry

And it has wasted a lot of time on broken configs (like trailing commas).

**Comment by samccone** [comment]
Hi @laktak mind opening a proposal here?
https://github.com/yarnpkg/rfcs

Thank you again!

**Comment by laktak** [comment]
@samccone see https://github.com/yarnpkg/rfcs/issues/2
