### ISSUE TITLE
yarn upgrade does nothing (workspaces)

### ISSUE THREAD

**Issue by pronebird** [yarnpkg/yarn#7046]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

```
yarn outdated
```

```
[redacted]
tslint-config-prettier         1.17.0  1.18.0   1.18.0     @org/package     devDependencies      https://github.com/prettier/tslint-config-prettier#readme
```

```
yarn workspace @org/package upgrade tslint-config-prettier --latest
```

Running `yarn outdated` gives back the same output

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

`yarn upgrade` should upgrade modules.

**Please mention your node.js, yarn and operating system version.**

yarn 1.13.0

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
