### ISSUE TITLE
Yarn workspace how to bypass symlink when a published version exists (on npm)

### ISSUE THREAD

**Issue by dtodt** [yarnpkg/yarn#7049]
**Do you want to request a *feature* or report a *bug*?**
I don't know for sure if what I'm dealing with is a bug, feature or just lack of information.

**What is the current behavior?**
When I run `yarn install` on a workspace root, every third party dependency is downloaded and internal dependencies are symlinked.

---

**If the current behavior is a bug, please provide the steps to reproduce.**
My current structure is something like this:
```
root                        # Yarn workspace
 * packages
 |  * lib1-ws               # Angular workspace
 |  |  * projects
 |  |  |  * lib1
 |  |  |     * package.json
 |  |  * package.json
 |  |
 |  * lib2-ws               # Angular workspace
 |  |  * projects
 |  |  |  * lib2
 |  |  |     * package.json # peer depends on lib1
 |  |  * package.json       # depends on lib1
 |  |
 |  * lib3-ws               # Angular workspace
 |     * projects
 |     |  * lib3
 |     |     * package.json # peer depends on lib1
 |     * package.json       # depends on lib1
 |
 * package.json
```

My workspaces object:
```json
{
  ...
  "workspaces": {
    "packages": [
      "packages/*",
      "packages/**/projects/*"
    ]
  }
  ...
}
```

The install process works fine, but I can't run, build or test libs 2 and 3, because lib1 symlink is different from it's compiled version laying on npm.
> ERROR in projects/lib2: error TS2307: Cannot find module 'lib1'.

> **As a workaround (after clone or a library publish), I call the add command with latest lib version.**
```shell
yarn workspace lib2-ws add lib1@latest
```
After this I can run, build and test the lib2 project without any problems.
The annoying part is after a clone, because I need to run the add command in every dependent package.

---

**What is the expected behavior?**
When I run `yarn install` on a workspace root, I expect that yarn try to download all packages even internal (public) from a npm repository, only creating symlinks **if the package is missing** from npm repository.

> Is there some **option** that I can run with yarn or configure in my workspace to make it go **outside first** and **on fallback make a symlink**?

> **Would be nice if it were an option to turn on and off when needed.**

---

**Please mention your node.js, yarn and operating system version.**
S.O: Windows 10
Node: v11.9.0
Yarn: 1.13.0

**Comment by chrisgrounds** [comment]
Ditto.

**Comment by adrianObel** [comment]
Any movement on this?

**Comment by Rush** [comment]
I have the same question.

**Comment by tranhl** [comment]
I'm running into a similar issue when attempting to use a published version of our shared ESLint config while maintaining it inside the same monorepo that needs it.

**Comment by leo-paz** [comment]
Bump

**Comment by LFFATE** [comment]
May be focused workspaces will help. 
https://classic.yarnpkg.com/blog/2018/05/18/focused-workspaces/
It allows to force install local packages from npm
