### ISSUE TITLE
Feature Request: allow cancelling `yarn version` with ctrl-c or empty version number

### ISSUE THREAD

**Issue by Kryten0807** [yarnpkg/yarn#7050]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

Type `yarn version`
Press Ctrl-C without entering a new version number
Yarn exits with the following message: `error An unexpected error occurred: "canceled".` and the `yarn-error.log` file is written.

OR

Type `yarn version`
Press enter without entering a new version number
Yarn displays the message `error Invalid semver version` and waits for a new version.

**What is the expected behavior?**

Sometimes I just want to check the version number without changing it.

What I think it should do is quit silently, without an error message or log.

**Comment by ollelauribostrom** [comment]
I'd love to give this a shot 🙂

**Comment by SidneyNemzer** [comment]
Since #7064 was merged, I think this can be closed? :)

**Comment by lavaldi** [comment]
cc @rally25rs
