### ISSUE TITLE
yarn.lock file is named poorly

### ISSUE THREAD

**Issue by fr0** [yarnpkg/yarn#7052]
**Do you want to request a *feature* or report a *bug*?**

Not sure if this is a feature or a bug.

**What is the current behavior?**

I had a developer on my team who was new to the node/npm/yarn ecosystem become confused about the `yarn.lock` file.
In his words:
```
Ah, weird, the yarn.lock file is something I want? From the name, I assumed it was a broken lock file generated as a mutex and not cleaned up.
```

It doesn't help that a lot of (crappy) software does use "lock" files as a way of achieving file-based mutexes, so I understand his confusion.

I know that changing the name would be a significant breaking change, but if there's ever another reason to change it, please don't use `.lock`. npm's `package-lock.json` is a slightly better name, although I prefer the "shrinkwrap" term.

**Comment by fr0** [comment]
Slightly related:  https://github.com/yarnpkg/yarn/issues/5629#issuecomment-419524410

**Comment by arcanis** [comment]
I don't think we'll ever want to change it. Consider that other tools added logic to explicitly support it - for example by detecting whether they should use Yarn or npm commands.
