### ISSUE TITLE
How to share packages across multiple apps?

### ISSUE THREAD

**Issue by daveisfera** [yarnpkg/yarn#7059]
Workspaces is a great feature for monorepos. Is there a way to support multiple apps in the same repo?

I tried doing a structure like this:
```
| packages\
| app1\
| ---- packages (symlink to ../packages)
| app2\
| ---- packages (symlink to ../packages)
```

It works for resolving `packages` in the app, but then the `packages` can't see each other. Is there a way to make this possible?

**Comment by gi** [comment]
You can add a workspace for an applications directory:
```
applications/
    app1/
        package.json
    app2/
        package.json
packages/
```

Your root `package.json` would look something like:
```json
{
  "workspaces": [
    "applications/*",
    "packages/*"
  ]
}

**Comment by daveisfera** [comment]
So with that approach, there's no `dependencies` in the root `package.json` and `yarn install` is run in the root directory?

**Comment by Tinoooo** [comment]
@daveisfera yes.
See https://yarnpkg.com/lang/en/docs/workspaces/

**Comment by gi** [comment]
@daveisfera Correct. See the link that @tinoooo posted for the formal documentation. 

Basically, each workspace (a package library or an application) contains the dependency information only for itself. The package manager (`yarn`) does the work to hoist and consolidate/deduplicate those dependencies.

**Comment by daveisfera** [comment]
We've adopted this approach and it's working well
