### ISSUE TITLE
Document lifecycle scripts workflow

### ISSUE THREAD

**Issue by mourner** [yarnpkg/yarn#706]
The [introduction post](https://code.facebook.com/posts/1840075619545360) has the following mention of lifecycle scripts:

> You have control over which lifecycle scripts are executed for which packages.

Additionally, the [TechCrunch article](https://techcrunch.com/2016/10/11/facebook-partners-with-google-others-to-launch-a-new-javascript-package-manager/) has a more confusing quote:

> By default, npm also allows developers who write these packages to execute other code that’s needed as part of the install process. That creates security issues, though, so Yarn does not have this feature.

But I couldn't find any information on how exactly this works, and how to control it. Can someone elaborate, or document this in the readme/docs?

**Comment by Restuta** [comment]
Yeah, "postinstall" hook is not getting executed, not sure if this is a bug or no.

**Comment by arcanis** [comment]
We currently have a settings to disable all scripts (`yarn install --ignore-scripts`), but not on a per-package basis. Feel free to open an RFC if you feel like it could be interesting!
