### ISSUE TITLE
Make Yarn build break when peer dependency isn't met

### ISSUE THREAD

**Issue by ikelee** [yarnpkg/yarn#7065]
I was running into issues, where I would upgrade a dependency in a repo, and then peer dependency would be unmet in another repo that was pulling in that initial repo, but at build time of the latter repo, it would only raise an error - this lead to weird unexpected behaviours. 

**Do you want to request a *feature* or report a *bug*?**

Feature/Bug

**What is the current behavior?**
If yarn detects unmet peer dependency, it'll proceed as normal and only raise a warning. Yarn should at least have an option to configure so that unmet dependencies will break builds and raise an error. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Put your project in a state where peer dependency is unmet

**Please mention your node.js, yarn and operating system version.**
Node: v10.13.0
yarn: 1.13.0
OS: Mojave 10.14.1

**Comment by merceyz** [comment]
Closing as fixed in v2 where you can use [logFilters](https://yarnpkg.com/configuration/yarnrc#logFilters) to make them errors

https://yarnpkg.com/getting-started/migration
