### ISSUE TITLE
Workspaces: lock multiple versions?

### ISSUE THREAD

**Issue by borekb** [yarnpkg/yarn#7071]
Let's say I do this:

```
yarn workspace package-a add some-package@^1.2.0
# installs v1.2.0

# ... work for an hour ...

yarn workspace package-b add some-package@^1.2.0
# installs v1.3.0 <--- new version has been published in the meantime
```

What do I end up with? Is `package-a` using v1.2.0 or v1.3.0 now? If they both use 1.3.0 (which I _think_ is what would happen), is there a way to prevent this behavior?

**Comment by merceyz** [comment]
`package-a` would still be using `1.2.0`, making changes in one part of the dependency tree does not modify the other as that is likely to cause bugs and not what you requested Yarn do
