### ISSUE TITLE
"yarn add global" footgun

### ISSUE THREAD

**Issue by callumlocke** [yarnpkg/yarn#7072]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

Typing `yarn add global foo` installs the packages `global` and `foo` into the local project. This seems unlikely to be what the user intended.

This was raised before in #2130 and it was closed as unfixable. But I think it is fixable, and worth fixing: the [global package](https://www.npmjs.com/package/global) has 1.5 million downloads a week, which seems a lot for a package that has been dormant for 2 years!

![image](https://user-images.githubusercontent.com/250617/53564236-40133800-3b4e-11e9-9a53-f7665eab8400.png)
![image](https://user-images.githubusercontent.com/250617/53564245-44d7ec00-3b4e-11e9-8494-5dd5ce28aa3a.png)

As for me, I've used Yarn for years and still make this mistake every couple of weeks, and it's really annoying every time, especially if I do it in an unclean project directory.

**What is the expected behavior?**

I think it should work like this:

If someone runs `yarn add global foo bar` (that is, when `'global'` is the **first in a list of 2 or more packages** being added), then the command should exit with code 1, and print a message something like this:

```
Error: likely typo detected.

Did you mean this?
> yarn global add foo bar

If you really meant to add a package named "global" in the local project
directory, please either install it individually (yarn add global) or avoid
listing it first when adding it with other packages.
```

Notes:
**Please mention your node.js, yarn and operating system version.**
node 11, yarn 1.13.0, macOS High Sierra.

**Comment by sudomann** [comment]
I can't believe people aren't pilling on to this issue. Perhaps fix this by showing a warning or prompt when someone passes **any** package name that matches a yarn command/argument.

**Comment by paul-soporan** [comment]
Closing as the `yarn global` commands have been removed in v2.
