### ISSUE TITLE
Reference git url with hash (i.e. for multi repo PR's)

### ISSUE THREAD

**Issue by jouni-kantola** [yarnpkg/yarn#708]
**Do you want to request a *feature* or report a *bug*?**
I guess it's a `Feature`, but works in npm CLI

**What is the current behavior?**
When I reference a GitHub URL with hash, I get the error message:
`error Couldn't find any versions for <module> that matches git@github.com:user/repo.git#abcd1234. Possible versions: 1.0.0`

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a PR in git repo
2. Reference the commit's git URL in package.json (`"module": "<url#hash>"`)
3. yarn install
4. error: needs package version

**What is the expected behavior?**
We're using multiple git repositorys. At times we need to reference a PR commit by hash for testing, like `git@github.com:user/repo.git#abcd1234`. This would help if it works (which it does with the npm CLI).

**Please mention your node.js, yarn and operating system version.**
node.js: v6.4.0
yarn: 0.15.1
Windows 10

**Comment by milosivanovic** [comment]
Referencing a branch with a hash **works fine** in yarn.

What doesn't work is the fact that you're specifying `git@` as the user, which is an open issue at https://github.com/yarnpkg/yarn/issues/513. Using the workaround at https://github.com/yarnpkg/yarn/issues/513#issuecomment-253010084 the source `ssh://github.com/user/repo.git#abcd1234` will work fine.

**Comment by jouni-kantola** [comment]
@milosivanovic: Thank you; that worked well.
