### ISSUE TITLE
How does PnP relate to hoisting (workspaces feature)?

### ISSUE THREAD

**Issue by borekb** [yarnpkg/yarn#7086]
I'm not even sure this question makes sense but I'm in the process of adding "nohoist" to our workspace-enabled monorepo because we've had instances where dependency was mistakenly not added to `package.json` yet the project was working fine due to hoisting. I now want to try PnP (Plug'n'Play) for the first time and some pieces of its description sound like it might actually validate that all required modules are proper dependencies.

So... does it make sense to disable hoisting and then enable PnP? Does adding PnP basically negate any effect of `node_modules` hosting in the first place? Thanks.

**Comment by arcanis** [comment]
The `nohoist` feature will have no effect on PnP installs, because packages are expected to not rely on the hoisting in the first place (and are actively prevented from doing so, as you noted) 🙂

**Comment by borekb** [comment]
Thanks for confirming that.
