### ISSUE TITLE
Extracting the tar content of undefined failed

### ISSUE THREAD

**Issue by nhooyr** [yarnpkg/yarn#7087]
1. Clone https://github.com/codercom/code-server
1. Checkout `3fbdb2e46c4f38268df42a03835b43151f9e55b2`
1. Run `yarn`
1. You'll often get something similar to:
```
ERROR Failed to install "browser" dependencies {"error":{"killed":false,"code":1,"signal":null,"cmd":"yarn --network-concurrency 1"},"stdout":"[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n","stderr":"warning package.json: No license field\nwarning ../../package.json: No license field\nwarning @coder/app: No license field\nerror https://registry.yarnpkg.com/@material/base/-/base-0.41.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: \"ENOENT: no such file or directory, chmod '/usr/local/share/.cache/yarn/v4/npm-@material-base-0.41.0-badadce711b4c25b1eb889a5e7581e32cd07c421/node_modules/@material/base/component.js'\"\n"}
```

Related https://github.com/yarnpkg/yarn/issues/6312

I'm on the latest stable release of yarn, 1.13. And version 8.10 for node (yes it is outdated but shouldn't affect this afaik).

**Comment by nhooyr** [comment]
I'll provide a Dockerfiles that reproduces it pretty much always soon.

**Comment by nhooyr** [comment]
```Dockerfile
FROM node:8

# Ensure latest yarn.
RUN npm install -g yarn

# Install VS Code's deps.
RUN apt-get update
RUN apt-get install -y libxkbfile-dev libsecret-1-dev git

WORKDIR /app
COPY . .
RUN yarn --version
RUN node --version
RUN yarn --network-concurrency 1
RUN yarn task build:server:binary
```

Plop that in the root of the repo and build it and if you don't get the same error, run it a few times till you do.

**Comment by nhooyr** [comment]
(removing the --network-concurrency flag makes it occur more often)

**Comment by nhooyr** [comment]
Also randomly see this:

```
ERROR Failed to install "common" dependencies {"error":{"killed":false,"code":1,"signal":null,"cmd":"yarn --network-concurrency 1"},"stdout":"[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n","stderr":"warning package.json: No license field\nwarning ../../package.json: No license field\nwarning @coder/app-common: No license field\nerror https://registry.yarnpkg.com/@material/snackbar/-/snackbar-0.44.0.tgz: Integrity check failed for \"@material/snackbar\" (computed integrity doesn't match our records, got \"sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==\")\n"}
```

**Comment by nhooyr** [comment]
Looks like its because we're running multiple yarn processes concurrently with a single cache.

Is it possible this will become a supported feature?

**Comment by nhooyr** [comment]
e.g. to share cache between CI runs.

**Comment by Stradivario** [comment]
Looks like my problem was because if wrong permissions on the folder in which YARN put his cache. This is a race conditions where i am using multiple gitlab runners using the same `node` version. In my case `chmod -R 777 .` fixed the problem inside the folder where `yarn` is trying to save files

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.

**Comment by harunurhan** [comment]
For me the issue was running concurrent `yarn install` for different project, that use the same `yarn` cache, as @nhooyr mentioned. I guess workaround is pass different folders for each install command `--cache-folder` but I haven't tried.

I had a script, similar to this.
```bash
(cd a && yarn install) &
(cd b && yarn install) &

wait %1
wait %2
```

**Comment by DorianBlues** [comment]
@harunurhan 
Setting --cache-folder on different folders solved my problem, thx!
