### ISSUE TITLE
nohoist for scoped modules are not working

### ISSUE THREAD

**Issue by Fnxxxxo** [yarnpkg/yarn#7088]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
Yarn nohoist seems to ignore some node modules that developed as monrepo and published with npm scope.
**If the current behavior is a bug, please provide the steps to reproduce.**

Build a monrepo with sub project A and B. 
```
monrepo
├ projects
   ├ A
   ├ B
```
Set nohoist config for scoped modules ( e.g. Nuxt) like
```
  "workspaces": {
    "packages": [
      "projects/*"
    ],
    "nohoist": [
      "A/nuxt/**"
    ]
  }
```
After installing, Nuxt is in the root node_modules. However, Nuxt 2.0 cannot run when it has conflict dependencies with project B. In my case, `@nuxt/webpack` requires webpack 4 but mpvue 2, under project B, specify webpack 3, which breaks Nuxt.
**What is the expected behavior?**
All dependencies of Nuxt are installed under project A which includes `@nuxt`, `@nuxtjs`, and some other modules required by their sub module like `@nuxt/webpack -> cssnano`
**Please mention your node.js, yarn and operating system version.**
node v10.14.2
yarn v1.13.0
win10 home v1803 17134.590

**Comment by Fnxxxxo** [comment]
I also tried to specify sub project of Nuxt in nohoist list like
```
  "workspaces": {
    "packages": [
      "projects/*"
    ],
    "nohoist": [
      "A/@nuxt/webpack/**"
    ]
  }
```
Still doesnt work.

**Comment by Fnxxxxo** [comment]
It seems that html-webpack-plugin and webpack mismatch. After I add nohoist for them and add sub project dependencies.
```
"nohoist": [
  "**/html-webpack-plugin",
  "**/webpack"
]
```
```
"devDependencies": {
  "@babel/core": "^7.3.4",
  "@vue/test-utils": "^1.0.0-beta.27",
  "babel-core": "7.0.0-bridge.0",
  "babel-jest": "^24.1.0",
  "html-webpack-plugin": "^3.2.0",
  "jest": "^24.1.0",
  "jest-haste-map": "^24.3.1",
  "jest-resolve": "^24.3.1",
  "nodemon": "^1.18.9",
  "tapable": "^1.1.1",
  "vue": "^2.6.8",
  "vue-jest": "^3.0.3",
  "vue-loader": "^15.7.0",
  "vue-template-compiler": "^2.6.8",
  "webpack": "^4.29.6"
}
```
html-webpack-plugin still ignore my webpack and keep install the peerDependency as webpack v3.
Any way to fix it?

**Comment by paul-soporan** [comment]
Closing as most likely fixed in v2 where you need to use [`installConfig.hoistingLimits`](https://yarnpkg.com/configuration/manifest#installConfig.hoistingLimits) instead of `noHoist`.

https://yarnpkg.com/getting-started/migration

**Comment by Lovercz** [comment]
@Fnxxxxo 解决了吗？
