### ISSUE TITLE
error An unexpected error occurred: "Unknown token: { line: 1, col: 0, type: 'INVALID', value: undefined }

### ISSUE THREAD

**Issue by usama-asfar** [yarnpkg/yarn#7100]
I get this error whenever I do something with yarn.

> C:\Users\chawki\Documents\Project\npm\medium-fetch>yarn publish
> yarn publish v1.13.0
> error An unexpected error occurred: "Unknown token: { line: 1, col: 0, type: 'INVALID', value: undefined } 1:0 in C:\\Users\\chawki\\.yarnrc".
> info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\chawki\\Documents\\Project\\npm\\medium-fetch\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

and its create a yarn error file too.

> Arguments: 
>   C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js publish
> 
> PATH: 
>   C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\erl10.1\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\chawki\AppData\Local\Microsoft\WindowsApps;C:\Users\chawki\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\chawki\AppData\Roaming\npm;C:\Exercism;C:\Users\chawki\AppData\Local\hyper\app-2.1.2\resources\bin;C:\MinGW\bin;C:\Users\chawki\AppData\Local\Yarn\bin
> 
> Yarn version: 
>   1.13.0
> 
> Node version: 
>   10.15.0
> 
> Platform: 
>   win32 x64
> 
> Trace: 
>   SyntaxError: Unknown token: { line: 1, col: 0, type: 'INVALID', value: undefined } 1:0 in C:\Users\chawki\.yarnrc
>       at Parser.unexpected (C:\Program Files (x86)\Yarn\lib\cli.js:62320:11)
>       at Parser.parse (C:\Program Files (x86)\Yarn\lib\cli.js:62451:14)
>       at parse (C:\Program Files (x86)\Yarn\lib\cli.js:62522:17)
>       at module.exports.exports.default (C:\Program Files (x86)\Yarn\lib\cli.js:62091:96)
>       at YarnRegistry.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:91555:64)
>       at Generator.next (<anonymous>)
>       at step (C:\Program Files (x86)\Yarn\lib\cli.js:304:30)
>       at C:\Program Files (x86)\Yarn\lib\cli.js:315:13
> 
> npm manifest: 
>   {
>     "name": "md_fetch",
>     "version": "1.0.1",
>     "description": "fetch medium post",
>     "main": "index.js",
>     "scripts": {
>       "test": "echo \"Error: no test specified\" && exit 1"
>     },
>     "repository": {
>       "type": "git",
>       "url": "git+https://github.com/Chawki726/md_fetch.git"
>     },
>     "author": "@Chawki726",
>     "license": "MIT",
>     "bugs": {
>       "url": "https://github.com/Chawki726/md_fetch/issues"
>     },
>     "homepage": "https://github.com/Chawki726/md_fetch#readme"
>   }
> 
> yarn manifest: 
>   No manifest
> 
> Lockfile: 
>   No lockfile
>

**Comment by gluons** [comment]
Maybe your `.yarnrc` is broken. Try to delete or recreate your `.yarnrc`.

> I also face the similar problem. But in my case, problem is from my `yarn.lock`.

**Comment by Chawki726** [comment]
> Maybe your `.yarnrc` is broken. Try to delete or recreate your `.yarnrc`.
> 
> > I also face the similar problem. But in my case, problem is from my `yarn.lock`.

i tired but it doesn't work for me

**Comment by JemsonTites** [comment]
Hi @usama-asfar,

We fix this issue by cleaning the content of .yarnc and save it. and then try the execute you commands.

**Comment by michal-filip** [comment]
In my case, recreating .yarnrc or yarn.lock did not help, but upgrading from yarn 1.16.something to 1.17.3 fixed the issue for me.

**Comment by usama-asfar** [comment]
I got this issue on my windows and I had a switch to ubuntu and yarn is working perfect, I hope those  above fix will solve the problem, 
Note: I don't switch to ubuntu not because of this :-)

**Comment by programmer-1** [comment]
I got the same issue on my windows i fixed this by clearing the .yarnrc file in "c:\user\admin".

**Comment by ndianabasi** [comment]
I solved my by deleting the referenced` .yarnrc` file and running the command again.

**Comment by asadalibest1** [comment]
remove all data from .yarnrc and save it. [problem Solved]

**Comment by Daveawb** [comment]
I don't get how deleting .yarnrc is a solution when it's required in certain circumstances. Seems like all the solutions skirt around the actual problem.

**Comment by sayhicoelho** [comment]
removing .yarnrc fixed the issue here

**Comment by jorszs** [comment]
I opened **.yarnrc** and it was full of blank spaces. I deleted they and it works for me :)

**Comment by Arxero** [comment]
for me, the problem was solved by 

1. windows: choco uninstall yarn (or go to control panel > add/remove programs and uninstall it from there)
2. npm install --global yarn

**Comment by fatimamomin13** [comment]
> 
> 
> I solved mine by deleting the referenced` .yarnrc` file and running the command again.

i tried

> 
> 
> > Maybe your `.yarnrc` is broken. Try to delete or recreate your `.yarnrc`.
> > > I also face the similar problem. But in my case, problem is from my `yarn.lock`.
> 
> i tired but it doesn't work for me

how to do that

**Comment by TheCoders-SK** [comment]
> 

This worked for me
