### ISSUE TITLE
yarn install --pure-lockfile does not respect .yarn.lock contents

### ISSUE THREAD

**Issue by O4epegb** [yarnpkg/yarn#7111]
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
yarn.lock has this version of typescript
```
typescript@3.2.1:
  version "3.2.1"
```
If I update typescript version in `package.json` to `"typescript": "^3.2.1"` and then do `yarn install --pure-lockfile`, yarn installs this `Found "typescript@3.3.3333"`

Docs says that `yarn install --pure-lockfile` should not generate yarn.lock (https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-pure-lockfile), but I had understanding that it should at least read from it, like `npm ci` does.

**What is the expected behavior?**
Should `yarn install --pure-lockfile` read from yarn.lock?

**Please mention your node.js, yarn and operating system version.**

node v11.2.0
yarn 1.13.0
mojave 10.14.3

**Comment by arcanis** [comment]
Pure lockfile simply doesn't *write* the lockfile if it changed. What you're looking for is `--frozen-lockfile`, which will throw an exception if the lockfile should change.

**Comment by O4epegb** [comment]
Hm, no, I'm not really looking for `--frozen-lockfile`!

I am looking for something to install deps only from lock file, without considering package.json at all. Is that possible?
And what is the difference between `--no-lockfile` and `--pure-lockfile` then? yarn just ignores lockfile completely when using `--pure-lockfile`

**Comment by arcanis** [comment]
It doesn't ignore it. If a range isn't in the lockfile (and in your example `^3.2.1` isn't in your lockfile - `3.2.1` is) then Yarn will resolve it again without considering the other ranges that are part of your lockfile (such as `3.2.1`). Said differently, the ranges must match exactly to be considered.

**Comment by O4epegb** [comment]
Hm, I thought that `3.2.1` is part of `^3.2.1`
Alright, thank you for explanation!
