### ISSUE TITLE
Latest yarn is 1.15.2, but in the linux repos only provide 1.13.0

### ISSUE THREAD

**Issue by MOZGIII** [yarnpkg/yarn#7117]
`https://dl.yarnpkg.com/debian/` provides outdated version of `yarn`, please fix.

**Comment by Daniel15** [comment]
Sorry about that! This should be fixed now.

The build server hit an issue with Aptly again (same issue as in https://github.com/aptly-dev/aptly/issues/804 and https://github.com/yarnpkg/yarn/issues/6904). I'll have to figure out how to pin the Aptly version.
