### ISSUE TITLE
Drop support for Node 6

### ISSUE THREAD

**Issue by tats-u** [yarnpkg/yarn#7120]
Node 6 is going to reach EoL in this April and pnpm has already been stopped the support for it.
I'd like you to prepare for removing Node 6 from CI configurations.

https://github.com/nodejs/Release

**Comment by arcanis** [comment]
https://github.com/yarnpkg/yarn/issues/6953

> Support for both Node 4 and Node 6 will be dropped. We don't expect Berry to have stable releases until after Node 6 gets EOL (expected April 2019), by which point it won't matter anymore.
