### ISSUE TITLE
npm install yarn in Windows 10 resolves in 1.13.0 not 1.15.2

### ISSUE THREAD

**Issue by ahnpnl** [yarnpkg/yarn#7131]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**
On a Windows 10 machine, run `npm install yarn` doesn't resolve 1.15.2 but it resolves only 1.13.0

**If the current behavior is a bug, please provide the steps to reproduce.**

- Use a Windows 10 machine.
- Run `npm install yarn` inside `nodejs` installation folder
Attach here the screenshot
![image](https://user-images.githubusercontent.com/27772165/54670414-e621e480-4af3-11e9-871d-80af39fe32de.png)

**What is the expected behavior?**
Should install 1.15.2

**Please mention your node.js, yarn and operating system version.**
Node v8.15.1
Yarn (current version) 1.13.0
NPM v6.5.0
Windows 10 x64

**Comment by inhuman-en** [comment]
Same for OSX and brew. Resolves to 1.13.0

**Comment by briandipalma** [comment]
The tag hasn't been updated.

**Comment by ankeshdave** [comment]
Same for Ubuntu 1804 ? Is there are different timing for releasing `yarn` as an npm package ?

**Comment by Daniel15** [comment]
Sorry about that, it should be fixed now.

@inhuman-en Homebrew should already be updated (ref https://github.com/Homebrew/homebrew-core/pull/37937). Please file a task in Homebrew's homebrew-core repo if you're having issues with installing using Homebrew.

**Comment by refrassetto** [comment]
tanks
