### ISSUE TITLE
Package does not exists when using modules-folder 

### ISSUE THREAD

**Issue by Godrules500** [yarnpkg/yarn#7134]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After installing to the correct location via --modules-folder, it is not recognized as existing. I am getting a package does not exists.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using intellij/webstorm, create a .yarnrc with --modules-folder {path}, and install a package. It will download to the correct location, however the idea will not recognize the package as installed.

**Please mention your node.js, yarn and operating system version.**
Yarn:1.15.2
Node:10.15.3

**Comment by rally25rs** [comment]
That is correct and the expected behavior. Node.js will always resolve packages from `node_modules`. Yarn's `--modules-folder` allows you to change the location where dependencies are unpacked, but it does not change where node.js will actually look for those packages.
