### ISSUE TITLE
yarn does not respect `"gypfile": false`

### ISSUE THREAD

**Issue by simonbuchan** [yarnpkg/yarn#7136]
**Do you want to request a *feature* or report a *bug*?**
Bug with npm compatibility, I guess?

**What is the current behavior?**
`yarn [install]`, like `npm install`, will look for a `binding.gyp` file and run `node-gyp rebuild` if it's present, for both local install and dependencies. But `npm install` will skip this step if `package.json` includes `"gypfile": false` (which seems to be undocumented).

**If the current behavior is a bug, please provide the steps to reproduce.**
Given a minimal `package.json`:
```json
{
  "private": true,
  "gypfile": false
}
```

and empty `binding.gyp`:
```py
{}
```

you get the following output from npm:

```
>npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 1.295s
found 0 vulnerabilities
```

and from yarn:

```
>yarn
yarn install v1.15.2
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node-gyp rebuild

C:\some\path>if not defined npm_config_node_gyp (node

<snip>

gyp: Unable to find targets in build file binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\some\path
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Both have the same behavior for dependency packages with a `binding.gyp`.

**What is the expected behavior?**
Matches `npm` behavior. This option, though undocumented, is pretty useful for creating prebuilt addons that you know will not need a fallback build step (for example, Windows-only, serverless/docker environments, private server packages), as:
-  `node-gyp` does not let you change the name of the gypfile
- the documented workaround to disable the behavior is to add a `"preinstall"` or `"install"` script, but even if these are just `"echo using pre-built output"` or something, yarn will tell the user it is running an install for the package, which is confusing if you're telling your users that your package don't need a build.
- when you're working on the package, if you're adjusting the dependencies, it's pretty likely you're working on the JS side (e.g. tests), and it's just wasting time
- the auto rebuild means you now have a release build instead of a debug build, so if you're developing you probably want to run `node-gyp rebuild --debug` again.

**Please mention your node.js, yarn and operating system version.**
node: v11.10.0
yarn: 1.15.2
OS: Windows 10 1809

**Comment by paul-soporan** [comment]
We've decided against supporting this because implicitly relying on `node-gyp` is unsafe and unsound and now also deprecated in v2+ and will be removed in the future alltogether.
