### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by Carrgan** [yarnpkg/yarn#7139]
**Which operating system are you using:**
Mac OS

**Please describe the steps you took when trying to install Yarn and what went wrong:**
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused

**Comment by Daniel15** [comment]
Please try again - Sounds like your system was having issues connecting to GitHub Releases (which is what we use for Yarn releases).
