### ISSUE TITLE
Thoughts about --json

### ISSUE THREAD

**Issue by viatsko** [yarnpkg/yarn#714]
Having multiple strings for json is uncomfortable for these reasons:

```
{"type":"inspect","data":{"eslint":"^3.6.0","eslint-plugin-jsx-a11y":"^2.2.2","eslint-plugin-import":"^1.16.0","eslint-plugin-react":"^6.3.0"}}
{"type":"finished","data":332}
```

1) You can't just feed this output somewhere, you need to filter the list of jsons first
2) It's incompatible with what npm currently have, breaking a lot of "quick-install" scripts like this one https://www.npmjs.com/package/eslint-config-airbnb

I'm proposing to keep only the main part of json and remove "finished" part or rethink the json and merge multiple parts into the one structure.

What do you think?

**Comment by kittens** [comment]
We have this structure as `yarn` processes can be long running and we should be emitting events as soon as we get them. What command are you using? It's likely we can special case `--json` for certain commands but we shouldn't be doing this for all of them IMO.

**Comment by viatsko** [comment]
I was thinking about compatibility with already written stuff like this, where you just want info as json:

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG"
)
```

And the output was like this:

```
{
  "eslint": "^3.6.0",
  "eslint-plugin-jsx-a11y": "^2.2.2",
  "eslint-plugin-import": "^1.16.0",
  "eslint-plugin-react": "^6.3.0"
}
```

But your point makes total sense. And the benefit you've mentioned of why it's implemented this way in yarn is pretty much huge.

Rewriting this kind of stuff shouldn't be a big deal.

**Comment by arcanis** [comment]
> You can't just feed this output somewhere, you need to filter the list of jsons first

That's not correct, you can use it with some tools. [jq](https://stedolan.github.io/jq/) comes into mind.

I'm going to close the issue for now, but feel free to discuss it if you feel like this is still a problem.

**Comment by mnpenner** [comment]
I would like a non-streaming flag.

> That's not correct, you can use it with some tools. jq comes into mind.

jq isn't exactly easy to use and distribute in a PHP project.

It's not that I *can't* filter out the activityTicks, it's just an unnecessary hassle IMO. I'm happy to wait the 0.5 seconds it takes to pull a full list.
