### ISSUE TITLE
Installation Problem: how to install an older version of yarn?

### ISSUE THREAD

**Issue by chrisrauh** [yarnpkg/yarn#7146]
The installation instructions recommend using brew to install yarn. However, there are no older versions of yarn available as taps to install. 

What is the recommended way of installing an older version of yarn?

Related, what is the recommended way of installing various version of yarn to use with nvm while working on multiple legacy projects?

**Comment by arcanis** [comment]
```
yarn policies set-version <version number>
```

This command will let you use any release within any project.
