### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by SunshineTech** [yarnpkg/yarn#7149]
This issue appear in yarn 1.6.0. Then I install 1.15.2, the issue is same.

**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
yarn
**If the current behavior is a bug, please provide the steps to reproduce.**
yarn

**What is the expected behavior?**
Install the dependencies in package.json

**Please mention your node.js, yarn and operating system version.**

The following yarn-error.log is the issue appear in yarn 1.6.0:

Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js

PATH: 
  /home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bin:/home/vagrant/.rbenv/versions/2.5.0/bin:/usr/lib/rbenv/libexec:/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/bin:/home/vagrant/.local/bin:/home/vagrant/.rbenv/bin:/home/vagrant/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
  1.6.0

Node version: 
  8.15.1

Platform: 
  linux x64

Trace: 
  SyntaxError: Unexpected token : in JSON at position 2
      at JSON.parse (<anonymous>)
      at GitFetcher.<anonymous> (/usr/share/yarn/lib/cli.js:90037:28)
      at Generator.next (<anonymous>)
      at step (/usr/share/yarn/lib/cli.js:98:30)
      at /usr/share/yarn/lib/cli.js:109:13
      at <anonymous>

npm manifest: 
  {
    "name": "blockly-mooc",
    "version": "0.0.161",
    "repository": "code-dot-org/code-dot-org",
    "license": "SEE LICENSE IN LICENSE",
    "engines": {
      "node": ">=8.15",
      "npm": "^3.10.8"
    },
    "scripts": {
      "lint": "eslint --ext .js,.jsx src test",
      "test": "./test-low-memory.sh",
      "test-low-memory": "./test-low-memory.sh",
      "test:unit": "node --max_old_space_size=4096 ./node_modules/.bin/grunt unitTest",
      "test:integration": "grunt integrationTest",
      "test:entry": "grunt karma:entry",
      "test:interpreter": "js-interpreter-tyrant --run --diff --root ./test/interpreter --interpreter ./test/interpreter/patched-interpreter.js --progress",
      "clean": "grunt clean",
      "build": "DEV=1 node --max_old_space_size=4096 ./node_modules/.bin/grunt build && grunt logBuildTimes",
      "build:analyze": "ANALYZE_BUNDLE=1 DEV=1 node --max_old_space_size=4096 ./node_modules/.bin/grunt build && grunt logBuildTimes",
      "build:dist": "NODE_ENV=production node --max_old_space_size=4096 ./node_modules/.bin/grunt clean build && grunt logBuildTimes",
      "build:dist:debug": "NODE_ENV=production DEBUG_MINIFIED=1 node --max_old_space_size=4096 ./node_modules/.bin/grunt clean build && grunt logBuildTimes",
      "build:dist:debug:analyze": "NODE_ENV=production DEBUG_MINIFIED=1 ANALYZE_BUNDLE=1  node --max_old_space_size=4096 ./node_modules/.bin/grunt clean build && grunt logBuildTimes",
      "postinstall": "npm rebuild node-sass",
      "start": "DEV=1 node --max_old_space_size=4096 ./node_modules/.bin/grunt dev; grunt logBuildTimes",
      "start:notify": "DEV=1 grunt dev --watch-notify; grunt logBuildTimes",
      "start:applab": "DEV=1 grunt dev --app=applab; grunt logBuildTimes",
      "start:gamelab": "DEV=1 grunt dev --app=gamelab; grunt logBuildTimes",
      "start:craft": "DEV=1 grunt dev --app=craft --watch-notify; grunt logBuildTimes",
      "test-audio": "echo \"Open your browser to http://127.0.0.1:8080/test/audio/audio_test.html\" && http-server .",
      "build:log": "grunt logBuildTimes",
      "build:stats": "node ./script/build-stats.js",
      "prestorybook": "curl -o build/package/css/application.css http://localhost-studio.code.org:3000/assets/application.css || curl -o build/package/css/application.css https://code-dot-org.github.io/cdo-styleguide/css/application.css",
      "storybook": "start-storybook -p 9001 -s build/package/,../dashboard/public,../",
      "storybook:deploy": "./script/deploy-storybook.sh"
    },
    "resolutions": {
      "eshost": "github:pcardune/eshost#f3fa7fa",
      "test262-compiler": "github:pcardune/test262-compiler#ffa0dff"
    },
    "devDependencies": {
      "@cdo/apps": "file:src",
      "@cdo/interpreted": "link:../dashboard/config/libraries",
      "@code-dot-org/artist": "0.2.1",
      "@code-dot-org/blockly": "3.4.2",
      "@code-dot-org/bramble": "0.1.26",
      "@code-dot-org/craft": "0.2.2",
      "@code-dot-org/dance-party": "0.0.42",
      "@code-dot-org/johnny-five": "0.11.1-cdo.2",
      "@code-dot-org/js-interpreter-tyrant": "0.2.2",
      "@code-dot-org/js-numbers": "0.1.0-cdo.0",
      "@code-dot-org/maze": "1.1.0",
      "@code-dot-org/p5.play": "1.3.4-cdo",
      "@code-dot-org/piskel": "0.13.0-cdo.3",
      "@code-dot-org/redactable-markdown": "0.4.0",
      "@storybook/addon-info": "3.2.11",
      "@storybook/addon-options": "^3.3.15",
      "@storybook/react": "3.2.11",
      "aws-sdk": "2.28.0",
      "babel-core": "6.9.0",
      "babel-eslint": "^7.1.1",
      "babel-istanbul-loader": "^0.1.0",
      "babel-loader": "6.2.4",
      "babel-plugin-add-module-exports": "^0.2.1",
      "babel-plugin-syntax-async-functions": "^6.8.0",
      "babel-plugin-transform-class-properties": "^6.23.0",
      "babel-plugin-transform-es2015-classes": "^6.9.0",
      "babel-plugin-transform-object-rest-spread": "^6.8.0",
      "babel-plugin-transform-react-jsx": "^6.8.0",
      "babel-plugin-transform-regenerator": "^6.26.0",
      "babel-polyfill": "6.9.0",
      "babel-preset-es2015": "^6.9.0",
      "babel-preset-react": "^6.5.0",
      "bootstrap-sass": "^3.3.6",
      "browser-process-hrtime": "0.1.2",
      "canvg": "gabelerner/canvg",
      "chai": "3.5.0",
      "chai-as-promised": "^7.1.1",
      "chai-enzyme": "~0.8.0",
      "chai-subset": "1.2.0",
      "chai-xml": "^0.3.2",
      "chalk": "^1.1.3",
      "chrome-serialport": "bcjordan/chrome-serialport#2",
      "classnames": "^2.2.5",
      "codemirror": "5.5",
      "codemirror-spell-checker": "^1.1.2",
      "copy-webpack-plugin": "^3.0.0",
      "css-loader": "^0.23.1",
      "csv-parse": "^1.1.7",
      "data-collection": "^1.1.6",
      "dedent": "^0.7.0",
      "ejs": "^2.6.1",
      "ejs-compiled-loader": "2.1.1",
      "enzyme": "~2.8.0",
      "enzyme-wait": "^1.0.9",
      "es6-promise": "3.0.2",
      "eslint": "^3.19.0",
      "eslint-config-prettier": "^3.6.0",
      "eslint-plugin-babel": "^4.1.2",
      "eslint-plugin-mocha": "^4.9.0",
      "eslint-plugin-prettier": "^3.0.1",
      "eslint-plugin-react": "^5.2.2",
      "fake-fetch": "^2.0.0",
      "fast-memoize": "2.0.2",
      "firebase": "^2.4.2",
      "firebase-bolt": "^0.8.0",
      "firebase-mock": "^1.0.5",
      "firmata": "0.16.0",
      "glob": "5.0.14",
      "grunt": "0.4.5",
      "grunt-cli": "0.1.13",
      "grunt-concurrent": "1.0.1",
      "grunt-contrib-clean": "0.6.0",
      "grunt-contrib-copy": "0.7.0",
      "grunt-contrib-uglify": "2.3.0",
      "grunt-contrib-watch": "0.6.1",
      "grunt-exec": "0.4.6",
      "grunt-karma": "^2.0.0",
      "grunt-newer": "1.1.1",
      "grunt-notify": "0.4.5",
      "grunt-sass": "1.1.0",
      "grunt-webpack": "^2.0.1",
      "hammerjs": "^2.0.8",
      "history": "^2.0.1",
      "html2canvas": "^0.5.0-beta4",
      "http-server": "^0.9.0",
      "immutable": "3.8.1",
      "jquery": "1.12.1",
      "jquery-ui": "^1.12.1",
      "js-cookie": "^2.1.2",
      "js-yaml": "^3.6.0",
      "json-loader": "0.5.4",
      "json-parse-better-errors": "^1.0.1",
      "jsonic": "^0.3.0",
      "karma": "^1.7.0",
      "karma-chrome-launcher": "^2.2.0",
      "karma-coverage": "^1.1.1",
      "karma-junit-reporter": "^1.2.0",
      "karma-mocha": "^1.3.0",
      "karma-mocha-reporter": "^2.2.3",
      "karma-phantomjs-launcher": "^1.0.0",
      "karma-sourcemap-loader": "^0.3.7",
      "karma-webpack": "2.0.7",
      "lazysizes": "^4.0.0-rc1",
      "load-grunt-tasks": "3.5.0",
      "lodash": "^4.17.5",
      "marked": "^0.3.6",
      "messageformat": "0.2.2",
      "mocha": "^3.1.2",
      "mock-firmata": "0.2.0",
      "moment": "^2.19.3",
      "newrelic": "^1.27.2",
      "node-js-marker-clusterer": "^1.0.0",
      "node-sass": "^4.0.0",
      "pepjs": "^0.4.3",
      "phantomjs-prebuilt": "^2.1.14",
      "playground-io": "code-dot-org/playground-io#v0.6.0-cdo.0",
      "prettier": "1.16.1",
      "progress-bar-webpack-plugin": "^1.8.0",
      "pusher-js": "4.1.0",
      "qtip2": "2.2.0",
      "radium": "~0.18.1",
      "raw-loader": "^0.5.1",
      "react": "~15.4.0",
      "react-addons-test-utils": "~15.4.0",
      "react-bootstrap": "0.30.1",
      "react-color": "^2.11.7",
      "react-datepicker": "1.6.0",
      "react-dom": "~15.4.0",
      "react-google-charts": "~1.5.5",
      "react-idle-timer": "~1.5.2",
      "react-lazy-load": "~3.0.10",
      "react-motion": "0.4.5",
      "react-onclickoutside": "^5.7.1",
      "react-pointable": "^1.1.1",
      "react-portal": "^3.0.0",
      "react-redux": "~4.4.5",
      "react-router": "~2.6.0",
      "react-select": "^1.2.1",
      "react-sticky": "~5.0.5",
      "react-tether": "^0.5.2",
      "react-tooltip": "^3.2.7",
      "react-virtualized": "^9.18.5",
      "react-virtualized-select": "^3.0.1",
      "react-with-context": "^2.0.0",
      "reactabular": "^2.0.5",
      "redux": "^3.3.1",
      "redux-logger": "^2.6.1",
      "redux-mock-store": "^1.2.3",
      "redux-thunk": "^2.0.1",
      "rgbcolor": "0.0.4",
      "sanitize-html": "^1.11.3",
      "sass-loader": "^4.0.2",
      "save-csv": "^4.0.6",
      "scratch-audio": "v0.1.0-prerelease.1501163867",
      "scratch-blocks": " v0.1.0-prerelease.1501101334",
      "scratch-render": "v0.1.0-prerelease.1500038694",
      "scratch-storage": "^0.2.0",
      "scratch-vm": "v0.1.0-prerelease.1501105826-prerelease.1501105849",
      "script-loader": "^0.7.0",
      "seedrandom": "2.4.2",
      "sinon": "^3.0.0",
      "sinon-chai": "^2.13.0",
      "sinon-chai-in-order": "^0.1.0",
      "sprintf-js": "^1.0.3",
      "style-loader": "^0.13.1",
      "time-grunt": "^1.3.0",
      "time-grunt-nowatch": "github:pcardune/time-grunt-nowatch#c88a3793cf7953090f78fa36f0e991abdcd756da",
      "unminified-webpack-plugin": "^1.1.0",
      "url-loader": "^0.5.7",
      "video.js": "4.5.2",
      "webpack": "3.10.0",
      "webpack-bundle-analyzer": "^2.13.1",
      "webpack-dev-server": "^2.11.0",
      "webpack-hot-middleware": "^2.10.0",
      "webpack-livereload-plugin": "^0.8.1",
      "webpack-notifier": "^1.4.1",
      "webpack-stats-plugin": "^0.2.1"
    },
    "dependencies": {
      "@code-dot-org/js-interpreter": "^1.3.9",
      "@code-dot-org/snack-sdk": "2.2.0-apkurl-v1",
      "crypto-js": "^3.1.9-1",
      "details-element-polyfill": "https://github.com/javan/details-element-polyfill",
      "filesaver.js": "0.2.0",
      "jshint": "^2.9.5",
      "jszip": "3.0.0",
      "object-fit-images": "^3.2.3",
      "prop-types": "^15.6.2",
      "qrcode.react": "^0.8.0",
      "query-string": "4.1.0",
      "react-csv": "^1.0.14",
      "react-dom-confetti": "^0.0.8",
      "react-hot-loader": "^1.3.1",
      "react-portal": "^3.0.0",
      "react-router-dom": "^4.3.1",
      "selectize": "^0.12.4",
      "wgxpath": "^1.2.0",
      "whatwg-fetch": "^2.0.3"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  ... ...

**Comment by SunshineTech** [comment]
The following yarn-error.log is the issue appear in yarn 1.15.2:

[yarn-error.log](https://github.com/yarnpkg/yarn/files/3010785/yarn-error.log)

**Comment by arcanis** [comment]
> SyntaxError: Unexpected token : in JSON at position 2

You have an invalid json file somewhere. Probably in the git dependency you use.
