### ISSUE TITLE
Yarn coomands doesn't show logs correctly on Git Bash

### ISSUE THREAD

**Issue by rikusen0335** [yarnpkg/yarn#7168]
**Do you want to request a *feature* or report a *bug*?**
I want to request a bug.

**What is the current behavior?**
The current behavior is following video.
https://gyazo.com/6c402300c3711145d0a222a0f5ad5296

So the issue is, Git Bash showing not correctly like teleporting.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just type `yarn <something>`.

**What is the expected behavior?**
Git Bash shows it smoothly.

**Please mention your node.js, yarn and operating system version.**
Windows10 Pro 64-bit
`node --version` -> v10.15.3
`yarn --version` -> 1.15.2
`git --version` -> git version 2.21.0.windows.1

Sorry for noob english, I'm not good at.

**Comment by szkrd** [comment]
In `c:\Program Files (x86)\Yarn\bin\yarn` the script calls winpty, which messes up the mingw terminal for some reason (winpty yarn.cmd would be fine though).

To me as a quick fix removing wintpy from the line `winpty node "$basedir/yarn.js" "$@"` helped.

**Comment by rikusen0335** [comment]
How I do it? like, type these commands on my Git Bash?

**Comment by szkrd** [comment]
@rikusen0335 Nope, the winpty part is in the yarn cli file (in the program files folder), you just have to modify that line over there. To me that works most of the time, except for webpack.

The other one (the alias) you put it into your `.bash_profile` in your home dir, you can open that with notepad. This approach works with webpack in my case.

**Comment by rikusen0335** [comment]
it helped for me! thanks.
