### ISSUE TITLE
yarn help exec points to wrong docs link

### ISSUE THREAD

**Issue by obsidianspork** [yarnpkg/yarn#7172]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
running `yarn help exec` will show the following link: https://yarnpkg.com/en/docs/cli/exec

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn help exec`

**What is the expected behavior?**
The link should point to these docs: https://yarnpkg.com/en/package/exec

Yarn version: 1.15.2
Node.js version: 8.12.0
Platform: macOS 10.13.6

**Comment by DanielRuf** [comment]
Hi @obsidianspork,

this is expected as the `help` command is for the Yarn (CLI) commands.

https://yarnpkg.com/en/docs/cli/help
https://yarnpkg.com/en/docs/cli/exec

See:

```
yarn help exec

  Usage: yarn [command] [flags]

  Displays help information.

  Options:

    -v, --version                       output the version number
    ...
    -h, --help                          output usage information
  Visit https://yarnpkg.com/en/docs/cli/exec for documentation about this command.

**Comment by obsidianspork** [comment]
@DanielRuf sounds good, thanks!

**Comment by ethanherbertson** [comment]
> 
> 
> Hi @obsidianspork,
> 
> this is expected as the `help` command is for the Yarn (CLI) commands.
> 
> https://yarnpkg.com/en/docs/cli/help
> https://yarnpkg.com/en/docs/cli/exec
> 
> See:
> 
> ```
> yarn help exec
> 
>   Usage: yarn [command] [flags]
> 
>   Displays help information.
> 
>   Options:
> 
>     -v, --version                       output the version number
>     ...
>     -h, --help                          output usage information
>   Visit https://yarnpkg.com/en/docs/cli/exec for documentation about this command.
> ```

While it's true that @obsidianspork linked to an unrelated page, it still seems like a bug to me that

1. The above output does *not* document the exec command, but rather the *help* command
2. https://yarnpkg.com/en/docs/cli/exec currently 404s.

I suspect the exec command was never fully documented. It was originally implemented by @arcanis back for https://github.com/yarnpkg/yarn/pull/3365. I would *love* to see this become a fully documented and explicitly supported command, as it allows for some useful workflows for my team.

@DanielRuf : Can this be re-opened and addressed, or should a separate issue be filed? (I'd be happy to.)

**Comment by DanielRuf** [comment]
I'm not a collaborator or member of this project so I can not reopen the issue.

I would suggest to create a new issue.
