### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by GraceAredel** [yarnpkg/yarn#7179]
**Which operating system are you using:**
Ubuntu 16.04 LTS 64bit

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I installed Yarn firstly as usual by an official instruction and everything was well. Then I installed [jest](https://jestjs.io/), wrote a first test, run `yarn jest` and got an error `error Command "jest" not found.`
If i got it right, [there are](https://github.com/yarnpkg/yarn/pull/7151) a solution for this error so I decided to try to install a Nightly version which is 1.16.0-20190324.1147 by also an official instruction:
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://nightly.yarnpkg.com/debian/ nightly main" | sudo tee /etc/apt/sources.list.d/yarn.list`

So the expected result was to get this 1.16 version of yarn 
And the actual result:
`root@ubuntu:/usr/share/yarn# yarn --version

1.13.0-20181121.1436`

**Comment by bernhardreiter** [comment]
@GraceAredel after you have added to the list of repositories, you need to upgrade the software.

Usually this is done by command like
```sh
apt-get update
apt-get upgrade
```
Please add pointers to the specific instructions you where following, so they can potentially be improved.

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
