### ISSUE TITLE
Yarn does not exit when done

### ISSUE THREAD

**Issue by Mykybo** [yarnpkg/yarn#7183]
Yarn is broken and nearly unusable because of it in my project. NPM works as expected.

The problem:
```
success Already up-to-date.
Done in 0.77s.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

First of all there is this annoying warning: "info There appears to be trouble with your network connection. Retrying...", yet all packages install as expected as fast as expected. NPM does not give such a warning. I am behind an enterprise proxy, which I suspect causes the warnings.

Second, as you can see, even after "Done" is printed, the command does NOT exit, no matter how long you wait.

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
