### ISSUE TITLE
Happens with Windows8 yarn 0.20.3 Node 6.9.5.

### ISSUE THREAD

**Issue by lvhaiquan** [yarnpkg/yarn#7196]
Happens with Windows8 yarn 0.20.3 Node 6.9.5.

E:\codes\js\react\relax-master>yarn --version
0.20.3

E:\codes\js\react\relax-master>node -v
v6.9.5

E:\codes\js\react\relax-master>yarn install
yarn install v0.20.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

_Originally posted by @wufeng87 in https://github.com/yarnpkg/yarn/issues/2083#issuecomment-280964737_

**Comment by Daniel15** [comment]
v0.20.3 is very outdated. Can you please try update to the latest version?

Your error just looks like Git is missing. Please try install Git for Windows and see if that fixes it.
