### ISSUE TITLE
Command 'yarn' not found?!

### ISSUE THREAD

**Issue by alanbleier182** [yarnpkg/yarn#7217]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I can't use the yarn command... even though I (think) I've set the correct path in my ~/.profile : 
export PATH="$PATH:/home/linuxbrew/.linuxbrew/Cellar/yarn/1.15.2/bin"
export PATH="$PATH:`yarn global bin`"

**If the current behavior is a bug, please provide the steps to reproduce.**

I installed brew and then:

$ brew install yarn

Then:

$ git clone git@github.com:ConsenSys/ERC1400.git
$ cd ERC1400
$ yarn
$ yarn coverage

yarn worked the first time I tested the whole project, but now it does not...

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

I have node 8.10, yarn 1.15.2 and Ubuntu 18.04.2. Thank you :)

**Comment by knoxcard** [comment]
Go into console, type in:
`whereis yarn`

**Comment by paul-soporan** [comment]
Closing as there's nothing actionable here.
