### ISSUE TITLE
Not running without TTY

### ISSUE THREAD

**Issue by BennyH26** [yarnpkg/yarn#722]
I'm using Yarn in a headless environment via NodeJS process.child_process.exec().  STDERR/STDOUT is redirected for later evaluation.

When executing, I get the error: "Can't answer a question unless a user TTY"

Which is originating from:

(yarnpkg\lib\reporters\console\console-reporter.js:190:29)

**Comment by Daniel15** [comment]
Which command are you running?

**Comment by BennyH26** [comment]
const exec = require('child_process').exec;
exec(`yarn publish`, function(err, result) {

});

---

Node v6.7.0
Windows 7 Prof

**Comment by ZhelinCheng** [comment]
me too

**Comment by BennyH26** [comment]
My apologizes, I was not using the correct `yarn publish` syntax.  I am closing this issue.

**Comment by ZhelinCheng** [comment]
How to deal with?

**Comment by daprahamian** [comment]
@BennyH26 what was the proper syntax that you used for the CI environment?

**Comment by BennyH26** [comment]
I'm using NPM for that specific task - wasn't worth the time to haggle around with Yarn in my specific context.

**Comment by destroyerofbuilds** [comment]
So it seems `yarn` prompts for a version:

```$ yarn publish
yarn publish v0.23.2
[1/4] Bumping version...
info Current version: 1.0.0
question New version:
```

Typically we just call `npm publish` and expect it to use the `version` field in `package.json`.

**Comment by destroyerofbuilds** [comment]
@daprahamian and @BennyH26 I found #2445 to be related. Perhaps we can carry on this discussion over there.
