### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by gunn** [yarnpkg/yarn#7229]
OS: macOS 10.14.1
node: 11.14.0
yarn: 1.15.2

I've installed yarn with brew. Running any command with it fails immediately - with fish shell:
```
fish: 'yarn -v' terminated by signal SIGILL (Illegal instruction)
```
With bash:
```
Illegal instruction: 4
```

I've tried previous versions of node, and previous versions of yarn, and can't get yarn to work at all now.

**Comment by gunn** [comment]
I fixed this by installing node and npm via the installer from https://nodejs.org
I suspect the cause of the issue lies between npm and brew.

**Comment by SrMouraSilva** [comment]
A note:

To install yarn without node.js, try `brew install yarn --ignore-dependencies`
