### ISSUE TITLE
yum install yarn

### ISSUE THREAD

**Issue by JoeyBling** [yarnpkg/yarn#7238]
Configure CentOS Yum sources as directed on the website

An error was reported while performing the yum installation

```shell
Error: Package: yarn-1.15.2-1.noarch (yarn)
           Requires: nodejs
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
 ```

But My nodejs is compiled and installed, and the system has the node command

**Comment by eirnym** [comment]
The difference here is how NodeJS is installed. If it installed using `make install` (or similar) command, Yum package manager doesn't register it as a package. and you'll have this message regardless if it is actually available. You should use Yum to manage you NodeJS installation. I recommend to use `nodesource` binary repositories.

**Comment by JoeyBling** [comment]
Yes,my NodeJS is installed using make install command, but my machine is already in use and can't use yum install NodeJS command anymore

**Comment by eirnym** [comment]
What is blocking you to install NodeJS above your installation? it's not clean, as it could be, but it would work.

**Comment by JoeyBling** [comment]
My machine is already in use by make install command, can I also use yum install NodeJS command? Is there a conflict? Affect my use?

**Comment by eirnym** [comment]
I don't know the exact setup you have to guess exactly what will happen depending on a place it is installed (look on the output `which node`). It could put files along, overwrite files or warn you, depending on many options you didn't told. 

If I have no _very special_ requirements for NodeJS installations and satisfied with the official `NodeSource` builds, I probably wouldn't worry about it at all and just replace it. Unofficial ways to install software is never supported anyway

**Comment by JoeyBling** [comment]
But if my machine doesn't have access to the external network, I can't use `yum install nodejs` command, only `make install` command for offline installation

**Comment by eirnym** [comment]
If your machine doesn't have network access, you may run `yum install ./package.rpm`, which will install rpm package with all dependencies. You may need to be prepared to download every single dependency from the tree of this package. 

Also if you can't install NodeJS this way, how do you install yarn from package?

Additionally, if you really can only install from local source, you should run installation using `npm`.

**Comment by JoeyBling** [comment]
Node's official website recommends use `make install` command for offline installation, why do you use `yum install nodejs` command

**Comment by JoeyBling** [comment]
I see someone had the same problem,The solution he gave was this...
```shell
sudo yum install epel-release
sudo yum install nodejs
sudo yum install yarn
```

**Comment by eirnym** [comment]
I use `nodesource` as a very stable and good installation sources as it is a big organisation by itself.

The installation using package manager is better for me as I know about vulnerabilities, fixes and updates without monitoring many sites at once. Also if some software is not used by any other software (and not requested by a user), it could be removed from my computer as well.

**Comment by JoeyBling** [comment]
all right，Thanks
