### ISSUE TITLE
Install package from git fail when there is something unexcept

### ISSUE THREAD

**Issue by rockwyc992** [yarnpkg/yarn#7239]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
```
 error Couldn't find match for "ref:" in "refs/heads/master" for "https://git.example.com/test.git".
```
Show error like above.

**If the current behavior is a bug, please provide the steps to reproduce.**
When I use a large number of git repository in my `package.json`, more than 50 dependencies with git, 
`git-credential-store` will lock the file `~/.git-credential`  sometimes.
  
```
fatal: unable to get credential storage lock: File exists
ref: refs/heads/master HEAD
0123456789abcdef0123456789abcdef012345678 HEAD
```
So that, `yarn` use `git ls-remote --symref https://git.example.com/test.git` will get something like above.
  
Then, `yarn` will get `{ref = 'unable', sha='ref:'}`, because the regex is too simple to match this pattern at [here](https://github.com/yarnpkg/yarn/blob/master/src/util/git.js#L460)

**What is the expected behavior?**
`yarn` will get `{ref='refs/heads/master', sha='0123456789abcdef0123456789abcdef012345678'}`

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v11.14.0
$ yarn -v
1.15.2
$ uname -a
Linux a1c6a8219d9b 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 Linux
```

**Comment by DanielRuf** [comment]
> `git-credential-store` will lock the file `~/.git-credential` sometimes

Sound more like an issue there and not in yarn as this may cause some race conditions. We could catch this probably using try / catch + *Sync.

**Comment by PeterDaveHello** [comment]
I think this is a duplicated issue to #5013?

**Comment by rockwyc992** [comment]
@PeterDaveHello Yes, you are right. Close this issue.
