### ISSUE TITLE
https://registry.yarnpkg.com/react-native/-/react-native-0.57.8.tgz: connect ETIMEDOUT 104.16.25.35:

### ISSUE THREAD

**Issue by gdchent** [yarnpkg/yarn#7241]
How can i solve this problem？
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native/-/react-native-0.57.8.tgz: connect ETIMEDOUT 104.16.23.35:443".
info If you think this is a bug, please open a bug report with the information provided in "E:\\software\\web\\react\\react-navigation3.x-dva-master\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by DanielRuf** [comment]
Hi @gdchent,

`104.16.25.35` is the Cloudflare network by npmjs. yarnpkg points to npmjs. This should be resolved.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
