### ISSUE TITLE
ENOENT error in Yarn workspace when depending on `react-scripts` in one package while other package listed as `nohoist`

### ISSUE THREAD

**Issue by tommedema** [yarnpkg/yarn#7246]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When depending on `react-scripts` in one package while another package is listed under "nohoist" in the workspace's package.json, a ENOENT error is thrown on `yarn install` from the workspace directory.

**If the current behavior is a bug, please provide the steps to reproduce.**
See complete steps at https://github.com/tommedema/yarn-nohoist-react-scripts-bug

1. `git clone git@github.com:tommedema/yarn-nohoist-react-scripts-bug.git`
2. `yarn install`

```
Error: ENOENT: no such file or directory, lstat '/Users/tommedema/projects/vg/playground/190503-yarn-react-scripts/packages/component-name/node_modules/camelcase'
```

**What is the expected behavior?**

It should install as expected with react-scripts being hoisted while packages under `@vg/sls-diy-bucket` are not hoisted.

**Please mention your node.js, yarn and operating system version.**

```
Yarn version: 
  1.15.2

Node version: 
  8.16.0

Platform: 
  darwin x64
```

## Hints
The error disappears when you do either of these:
1. remove `"react-scripts": "3.0.0"` dependency in packages/frontshop
2. remove "nohoist" in the workspace's package.json

However none of these are solutions as they're needed in my case (nohoisting for serverless applications is necessary because they package the local package's node_modules folder).

## Cleanup

To cleanup all deps so you can reproduce the issue again, run `yarn clean-incl-deps`, followed by `yarn install`.

**Comment by tommedema** [comment]
I awarded a 50$ bounty to whoever can solve this issue

https://www.bountysource.com/issues/73694392-enoent-error-in-yarn-workspace-when-depending-on-react-scripts-in-one-package-while-other-package-listed-as-nohoist

**Comment by skeptycal** [comment]
I've been out of town but I'm taking a look at this tonight.

**Comment by skeptycal** [comment]
@tommedema ,

Try this out and let me know what you think. The path that is intended to be 'nohoist' (sls-diy-bucket) contains its own copy of everything (not symlinks) and it seems to install ok.

I got bored and made a BASH script to run it over and over just to be sure and I left in my automatic preinstall and postinstall Yarn scripts.

I haven't used Yarn much, so let me know if there is anything I missed or that doesn't work right. I'll be happy to take another look at it. This is one of those puzzles that just got my attention and I've enjoyed it.

**Comment by tommedema** [comment]
Thanks @skeptycal! I appreciate the bash script. Is there a reason why you need 3 separate entries? Wouldn't `**/sls-diy-bucket/**` have the same effect?

Anyway, I'm going to accept your contribution as I think it's the best I can hope for, though I don't think the nohoisting is actually working. It does install though :)

When you move the `sls-diy-bucket` folder outside of the root workspace, then remove it's dependencies on `@vg/X` packages, and do a `yarn install`, you'll get:

```
yarn cache clean
yarn install
tree | tail -1
1317 directories, 10125 files
```

When you then do a workspace level install with your "fix" and do:

```
yarn cache clean # was necessary for me
yarn install
cd packages/sls-diy-bucket
tree | tail -1
409 directories, 2627 files
```

I have a feeling that dependencies of dependencies are still being hoisted with your solution, that would explain the difference.

For those using serverless framework: I decided to simply enable hoisting for everything again, and then use `serverless-jetpack` for packaging instead of relying on yarn.

**Comment by skeptycal** [comment]
@connectdotz @arcanis 

Can someone please mark this as closed. The BountySource website won't recognize it until this happens ... and I won't get paid =) I'm on a tight budget over here ;)

I know this isn't a perfect solution, but it installs and runs and it was accepted by the person who had the issue: 

["Anyway, I'm going to accept your contribution as I think it's the best I can hope for, though I don't think the nohoisting is actually working. It does install though :)"](https://github.com/yarnpkg/yarn/issues/7246#issuecomment-502335720)

after I made mention of the comments about 'nohoist' on the yarnpkg.com website: 

["While nohoist is useful, it does come with drawbacks. The most obvious one is the nohoist modules could be duplicated in multiple locations, denying the benefit of hoisting mentioned above. Therefore, we recommend to keep nohoist scope as small and explicit as possible in your project."](https://yarnpkg.com/blog/2018/02/15/nohoist/)

in my PR:

["I think it is worth noting that the 'nohoist' option has repeatedly been mentioned as a "workaround" to help developers deal with the shortcomings of other packages, not any bug in Yarn. It is mentioned prominently in the online docs here and in several conversations on Yarn github issues."](https://github.com/tommedema/yarn-nohoist-react-scripts-bug/pull/1#issue-288529863)

**Comment by rebolyte** [comment]
For anyone running into this in the future, the solution here of 1) updating the root package.json to include filepaths instead of project references and 2) setting the child package.json to include `workspaces: { nohoist: ["*"] }` didn't work for me. It does resolve the ENOENT error, but only because the dependencies of dependencies are still being hoisted.

What ended up resolving the issue for me was making sure that the problematic dependency version was specified _exactly_ the same in all package.json files. In my case, I had `"nanoid": "^2.1.8"` in a non-hoisted package's deps, and `"nanoid": "^2.1.6"` in my hoisted package's deps. Once these matched, the error went away, and deps were also hoisted correctly.
