### ISSUE TITLE
Node version problem with Yarn

### ISSUE THREAD

**Issue by soumanpaul** [yarnpkg/yarn#7247]
```
My node version is
node v10.15.3 (npm v6.4.1)


```
Trying to install Create react native app using Yarn...

```
$ yarn global add create-react-native-app@1.0.0
yarn global v1.15.2
warning You are using Node "13.0.0-nightly20190504cb848b4546" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
[1/4] Resolving packages...
[2/4] Fetching packages...
error create-react-native-app@1.0.0: The engine "node" is incompatible with this module. Expected version ">=6". Got "13.0.0-nightly20190504cb848b4546"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command
```

Getting this error 

same error with node -v 6.2.2 and 8.9.4

Please help to solve this issue

Thank You.

**Comment by rockwyc992** [comment]
**Please check again, which node version do you use?**

It shows you are using node with `13.0.0-nightly20190504cb848b4546`, and you can use `process.versions` with node in interactive mode.
```
$ node
> process.versions
{ node: '10.15.2',
  v8: '6.8.275.32-node.12',
  modules: '64',
  napi: '3',
  openssl: '1.1.1b',
  icu: '63.1',
  unicode: '11.0',}
```

`yarn` use [`semver`](https://www.npmjs.com/package/semver) to detect your dependencies is good for the package. This is same behavior with `npm`.

**Comment by DanielRuf** [comment]
Hi @soumanpaul,

what does the following print?

`where node`
