### ISSUE TITLE
error An unexpected error occurred

### ISSUE THREAD

**Issue by usama-asfar** [yarnpkg/yarn#7250]
![Capture](https://user-images.githubusercontent.com/42825498/57248602-5fec3e00-7060-11e9-8a90-4a1c677387b2.PNG)
[yarn-error.log](https://github.com/yarnpkg/yarn/files/3149461/yarn-error.log)

**Comment by DanielRuf** [comment]
Hi @usama-asfar,

the .yarnrc file does normally not contain JSON. See https://yarnpkg.com/en/docs/yarnrc

**Comment by paul-soporan** [comment]
Closing as there's nothing actionable here.
