### ISSUE TITLE
Add max depth filter in `yarn ls`

### ISSUE THREAD

**Issue by Gelio** [yarnpkg/yarn#726]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
`yarn ls` has no option to limit the depth of packages to be printed. For me depth of 0 (aka only listing top-level packages) is a lot more useful than the whole tree.

**What is the expected behavior?**
There should be a flag like `--depth n` to specify max depth level of package nesting, similar to how `npm ls --depth 0` works.

**Please mention your node.js, yarn and operating system version.**
- nodejs: v6.7.0
- yarn: v0.15.1
- OS: Windows 10 Pro 64 bit

**Comment by samccone** [comment]
Thanks for the issue @Gelio, this would be a great first pull request into yarn.

Cheers.

**Comment by olingern** [comment]
@samccone I'll take a look at this one today!

**Comment by olingern** [comment]
@samccone @kittens  I have a PR open for this with the desired functionality, but it's unclear what the ls command _should_ do. At the moment, the existing `yarn ls` command gives me all packages and their dependencies. 

The PR I have open differs in that `yarn ls depth 1` will only return `dependencies` and `devDependencies`, but (at the moment) `yarn ls` and `yarn ls depth 2` maintains the existing output of everything in the lockfile.

Is the goal to show installed packages or the contents of the lockfile?

**Comment by Arcanemagus** [comment]
I would say the goal, like with `npm ls --depth=n` is to show installed packages to the _n_th nested level. That sounds like a _major_ bug if `yarn ls` is only listing what is in the lockfile and not what actually exists on the system.

**Comment by wyze** [comment]
Closed via #1463.
