### ISSUE TITLE
yarn pnp editor support

### ISSUE THREAD

**Issue by TrySound** [yarnpkg/yarn#7278]
Hey! yarn pnp looks very promising though there is a tradeoff in editor support. It requires editors to consume locally installed cli tools via `yarn [tool_name]` command. This blocks pnp usage completely and I would like to track all available tools in this issue.

Share please your experience with editor support and tools integration.

**Comment by arcanis** [comment]
Hey @TrySound! We actually had important breakthrough on the v2 trunk ([yarnpkg/berry](https://github.com/yarnpkg/berry)), and I think we'll soon start to work on a blogpost to talk about the progress in more details. In general, consider the v2 as being the best Yarn release to use for everything related to PnP (it's still a bit bleeding edge, of course ;).

Without going into details, @vlasenko worked on a tool (PnPify) that adds transparent PnP support to JS tools that don't yet support it natively - in particular TypeScript and VSCode. The full documentation can be found [here](https://yarnpkg.github.io/berry/advanced/pnpify). Additionally, starting from https://github.com/yarnpkg/berry/pull/169 (merged a few minutes ago!), adding support for VSCode is almost as simple as running `yarn pnpify --sdk`.

The problem you mention (having to run `yarn <tool name>`) is still there, though, so it would be interesting to see whether we could improve the situation somehow. I've set up a template on the v2 repository, [Case Studies](https://github.com/yarnpkg/berry/issues/new?assignees=arcanis&labels=case+study&template=-------case-study.md&title=%5BCASE+STUDY%5D), to help investigate individual tools.

In general we're still improving the workflow and documentation so please let us know (**on the v2 repository!**) how is the developer experience and how we could improve it. You can also reach us via [Discord](http://discordapp.com/invite/yarnpkg), we're quite active in #development 🙂

**Comment by TrySound** [comment]
Great! Thank you. I joined to discord and will look at berry repo.
