### ISSUE TITLE
I trying some "voodoos":

### ISSUE THREAD

**Issue by festefan** [yarnpkg/yarn#7283]
I trying some "voodoos":

- Delete any "*.lock" and rm node_modules. Or `rm -rf node_modules/`

- Clean a flush all connections things like DNS, caches and so on.

- Terminal commands:

- [ ] `set http_proxy=`
- [ ] `set https_proxy=` 
- [ ] `yarn config delete proxy`
- [ ] `npm config rm https-proxy`
- [ ] `npm config rm proxy`
- [ ] `npm config set registry "http://registry.npmjs.org"` or `npm config set registry "https://registry.npmjs.org"`

- Restart your terminal and Try.

-  Use : `yarn add mypckge --network-timeout 100000` or `yarn --network-timeout 100000` 
but first try just `yarn `

- Restart your terminal and Try `yarn ` again and/or with --network-timeout.

For me is working for now. I'll see how will be over time.

_Originally posted by @MichelDiz in https://github.com/yarnpkg/yarn/issues/5259#issuecomment-379769451_

**Comment by festefan** [comment]
Resolved for me, try this

**Comment by strugee** [comment]
Hi, is there an actionable bug or feature request? If not, please close this issue. GitHub Issues is not a forum.
