### ISSUE TITLE
I can't add package from github repo

### ISSUE THREAD

**Issue by WDever** [yarnpkg/yarn#7285]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

Add package from github repo.

**If the current behavior is a bug, please provide the steps to reproduce.**

run ```yarn add https://github.com/WDever/react-facebook-account-kit.git```

**What is the expected behavior?**

Add my own react-facebook-account-kit from my github repo.

**Please mention your node.js, yarn and operating system version.**

node: 11.10.0
yarn: 1.15.2
os: macOS mojave 10.14.5

![image](https://user-images.githubusercontent.com/37620133/57985202-8c13b000-7a9f-11e9-977e-e220ac5340d3.png)

![image](https://user-images.githubusercontent.com/37620133/57985213-a64d8e00-7a9f-11e9-89ef-81f3c2ac8e00.png)

**Comment by DanielRuf** [comment]
Hi @WDever,

please run `git status`. You may have changed files in your current Git repository. Try `git stash` and `git stash apply` after the installation of the needed package.

**Comment by WDever** [comment]
@DanielRuf Oh, Thanks. I'll try.
