### ISSUE TITLE
new issues

### ISSUE THREAD

**Issue by chengxiaoxuanff** [yarnpkg/yarn#7288]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by DanielRuf** [comment]
Hi @chengxiaoxuanff,

it seems you have not filled out the issue template. Maybe you have created this issue by accident. If this is the case please close it.
