### ISSUE TITLE
Yarn add Timedout 

### ISSUE THREAD

**Issue by leo-garay** [yarnpkg/yarn#7291]
**If the current behavior is a bug, please provide the steps to reproduce.**

 
yarn add ckeditor@4.11 jquery@3.3 jquery-migrate@3.0 siu-js-app-launcher@1.0 --modules-folder www/js/packages/
yarn add v1.16.0
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/ckeditor: ETIMEDOUT".

**Please mention your node.js, yarn and operating system version.**

nodejs version v8.16.0
yarn version 1.16.0
debian 9

**Comment by leo-garay** [comment]
yarn-error.log

Arguments:
  /usr/bin/node /usr/share/yarn/bin/yarn.js add jquery@3.3 jquery-migrate@3.0

PATH:
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version:
  1.16.0

Node version:
  8.16.0
Platform:
  linux x64
Trace:
  Error: https://registry.yarnpkg.com/jquery: ETIMEDOUT
      at Timeout._onTimeout (/usr/share/yarn/lib/cli.js:130250:19)
      at ontimeout (timers.js:498:11)
      at tryOnTimeout (timers.js:323:5)
      at Timer.listOnTimeout (timers.js:290:5)
npm manifest:
  No manifest
yarn manifest:
  No manifest

Lockfile:
   THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
   yarn lockfile v1

**Comment by DanielRuf** [comment]
Hi @leo-garay,

this has often to do with your network conditions.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
