### ISSUE TITLE
Im not sure, but this doesnt look normal https://registry.yarnpkg.com/

### ISSUE THREAD

**Issue by agustif** [yarnpkg/yarn#7296]
I clicked https://registry.yarnpkg.com/ on a malformed link, this looks bad, so sorry if I broke something

![yarnk](https://user-images.githubusercontent.com/6601142/58221687-c5545600-7d13-11e9-9195-744fe38cf504.gif)

**Comment by Dmitry-Sokolov** [comment]
Yarn install is failed for me too

error An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.2.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by DanielRuf** [comment]
What exactly is wrong? registry.yarnpkg.com points to registry.npmjs.org via DNS and this is the CouchDB instance.

The 503 error comes from npmjs or one of the Cloudflare edges.

**Comment by rally25rs** [comment]
As Daniel mentioned, the yarn registry is just a DNS redirect to npmjs, so failures come from them and there isn't anything we can do to fix that. It does appear to have some intermittent failures at times, but they are usually short, and checking npm's status page can sometimes be used to discover those outages.
I'm assuming this is working again days later and am going to close this issue.

**Comment by agustif** [comment]
@rally25rs @DanielRuf Thanks guys, I honestly didn't know what was going on, and that's the reason why opened the Issue, now that you've explained what was causing it, makes sense, can close the issue!
