### ISSUE TITLE
Yarn cannot fetch packages!!! 503 city y'all

### ISSUE THREAD

**Issue by YOU54F** [yarnpkg/yarn#7297]
Yarn audit and yarn install's failing today, lots of 503's :(

```yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.2.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1```

**Comment by Dmitry-Sokolov** [comment]
The same for me! For 
“https://registry.yarnpkg.com/@xtuc/ieee754/-/ieee754-1.2.0.tgz:

**Comment by etothepii** [comment]
Me too

**Comment by zetoke** [comment]
Works for me locally and I have the same problem on CircleCI

**Comment by anagstef** [comment]
@zetoke if you delete your lock file, it happens locally too

**Comment by vadymshymko** [comment]
Same issue. 

> error https://registry.yarnpkg.com/@xtuc/ieee754/-/ieee754-1.2.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"

**Comment by giuseppeg** [comment]
> delete your lock file
Or clean yarn's cache `yarn cache clean`. 

Happening to us as well with multiple packages.

**Comment by YOU54F** [comment]
It has just started working.

Out of interest, is there a yarn status page?

**Comment by giuseppeg** [comment]
@YOU54F https://status.yarnpkg.com all green

**Comment by zetoke** [comment]
> @zetoke if you delete your lock file, it happens locally too

Yeah, I understand that. I meant, that I can download file directly locally. By direct url 😄
