### ISSUE TITLE
Scoped dependencies not resolved with `yarn --offline --no-lockfile`

### ISSUE THREAD

**Issue by roblg** [yarnpkg/yarn#731]
**Do you want to request a _feature_ or report a _bug_?**

Bug, I think.

**What is the current behavior?**

Currently, it looks like `yarn --offline --no-lockfile` isn't properly resolving scoped packages in the local cache. Running with `--offline`, but _without_ `--no-lockfile` does not seem to exhibit this behavior.

**If the current behavior is a bug, please provide the steps to reproduce.**

In a project that includes scoped dependencies:
- `yarn --no-lockfile` (make sure the cache is populated)
- `rm -rf node_modules`
- `yarn --no-lockfile --offline` (try to install packages based solely on disk cache)

Error example:

```
error Couldn't find any versions for "@redfin/actions" that matches "<version>" in our cache. Possible versions: ""
```

That package does exist in the cache, AFAICT:

```
$ ls -l ~/.yarn-cache/npm-@redfin/actions-<version>
package.json
<other package files>
```

**What is the expected behavior?**

It seems like `yarn --no-lockfile --offline` should work, when the cache directory is known to be complete. 

**Please mention your node.js, yarn and operating system version.**
- node: `6.6.0`
- npm: `3.10.3`
- yarn: linked `master` (also `0.15.1`)

**Comment by roblg** [comment]
Other information that might be relevant: we use `sinopia` as an internal npm registry mirror, and our scoped packages are published there.

**Comment by BYK** [comment]
Tried with `@yarnpkg/lockfile` - no longer happening.

**Comment by JeremyJonas** [comment]
I just encountered this same issue, was there an actual resolution or fix to this before closing?

I believe direct package installs with scoped packages works, but scoped transitive dependencies do not resolve correctly from the cache resulting in the above error.

Such as [protobufjs](https://yarnpkg.com/en/package/protobufjs) which depends on `@protobufjs/aspromise, @protobufjs/base64, @protobufjs/codegen, @protobufjs/...`

Yarn cache directory:
```
yarn-cache/v1/npm-@protobufjs/
yarn-cache/v1/npm-@protobufjs/aspromise-1.1.2-9b8b0cc663d669a7d8f6f5d0893a14d348f30fbf/
yarn-cache/v1/npm-@protobufjs/aspromise-1.1.2-9b8b0cc663d669a7d8f6f5d0893a14d348f30fbf/.yarn-metadata.json
...
yarn-cache/v1/npm-@protobufjs/base64-1.1.2-4c85730e59b9a1f1f349047dbf24296034bb2735/
yarn-cache/v1/npm-@protobufjs/base64-1.1.2-4c85730e59b9a1f1f349047dbf24296034bb2735/.yarn-metadata.json
...
yarn-cache/v1/npm-@protobufjs/codegen-2.0.4-7ef37f0d010fb028ad1ad59722e506d9262815cb/
yarn-cache/v1/npm-@protobufjs/codegen-2.0.4-7ef37f0d010fb028ad1ad59722e506d9262815cb/.yarn-metadata.json
...
yarn-cache/v1/npm-@protobufjs/eventemitter-1.1.0-355cbc98bafad5978f9ed095f397621f1d066b70/
yarn-cache/v1/npm-@protobufjs/eventemitter-1.1.0-355cbc98bafad5978f9ed095f397621f1d066b70/.yarn-metadata.json
...
yarn-cache/v1/npm-@protobufjs/fetch-1.1.0-ba99fb598614af65700c1619ff06d454b0d84c45/
yarn-cache/v1/npm-@protobufjs/fetch-1.1.0-ba99fb598614af65700c1619ff06d454b0d84c45/.yarn-metadata.json
```

Running `yarn add protobufjs --offline`, results in the following error:
```
Error: Couldn't find any versions for "@protobufjs/base64" that matches "^1.1.2" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
    at ...
Error: Couldn't find any versions for "@protobufjs/codegen" that matches "^2.0.4" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
    at ...
Error: Couldn't find any versions for "@protobufjs/eventemitter" that matches "^1.1.0" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
    at ...
...
```

Interestingly enough, adding `--prefer-offline` to the cmd and it works fine.
`yarn add protobufjs --offline --prefer-offline` works as expected and correctly installs the transitive scoped packages from the cache in offline mode.

`config.preferOffline` prevents the error [here](https://github.com/yarnpkg/yarn/blob/1c845bd2dc64fc4937d82ac7b88d014e9fd6b3bb/src/resolvers/registries/npm-resolver.js#L158).

Yarn: 1.2.0 & 1.3.2
Node: 8.6.0

**Comment by aprilandjan** [comment]
@JeremyJonas I tried to use `yarn add @scope/pkg --offline --prefer-offline` without network, and it failed exactly like `yarn add --offline` with network enabled. So I guess your works-fine-solution is actually a fallback when offline cannot satisfied.

I tested yarn `v1.9.4` and `v1.9.2`, the offline mode for scoped package dependencies still failed.
