### ISSUE TITLE
node install/libvips && node install/dll-copy && prebuild-install

### ISSUE THREAD

**Issue by issnoejasso** [yarnpkg/yarn#7315]
**Which operating system are you using:**
[mac]
yarn 1.16.0
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/proyect/node_modules/sharp
Output:
info sharp Using cached /Users/user/.npm/_libvips/libvips-8.6.1-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.3.1 runtime=node arch=x64 platform=darwin)

**Please describe the steps you took when trying to install Yarn and what went wrong:**
i run 
`yarn install `

**Comment by DanielRuf** [comment]
Hi @issnoejasso,

So far I see no issue. Can you clarify your problem?

**Comment by zith5364** [comment]
I also had same issues.

$ npm install

> sharp@0.23.0 install /builds/stella/dummy/z_test_delete/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
/builds/stella/dummy/z_test_delete/node_modules/sharp/install/libvips.js:85
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 403
    at /builds/stella/dummy/z_test_delete/node_modules/sharp/install/libvips.js:85:17
    at f (/builds/stella/dummy/z_test_delete/node_modules/once/once.js:25:25)
    at f (/builds/stella/dummy/z_test_delete/node_modules/once/once.js:25:25)
    at ClientRequest.protocol.request.res (/builds/stella/dummy/z_test_delete/node_modules/simple-get/index.js:63:5)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
make: Entering directory '/builds/stella/dummy/z_test_delete/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp.target.mk:127: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/builds/stella/dummy/z_test_delete/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.123-111.109.amzn2.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /builds/stella/dummy/z_test_delete/node_modules/sharp
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-19T01_03_16_229Z-debug.log

**Comment by DanielRuf** [comment]
@zith5364

This is a different problem that you have. It is not directly related to Yarn.

**Comment by DanielRuf** [comment]
Please check if you can download https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz as your environment throws a 403 for that.

**Comment by DanielRuf** [comment]
`wget https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz` works for me.

**Comment by issnoejasso** [comment]
Thanks

**Comment by harendra-techindustan** [comment]
Please check your Node version this package support 12.13.*

`Installation error: Expected Node.js version >=12.13.0 but found 12.10.0`
