### ISSUE TITLE
Installation Problem: yarn not working

### ISSUE THREAD

**Issue by Jonyk56** [yarnpkg/yarn#7316]
**Which operating system are you using:**
windows 10 

**Please describe the steps you took when trying to install Yarn and what went wrong:**

this issue happened after I installed yarn, when I tried to run yarn's commands, I kept getting errors

**Comment by DanielRuf** [comment]
Hi @Jonyk56,

Please provide some more info like the output and errors that you see.

**Comment by olingern** [comment]
Hi @Jonyk56  -- is this still a problem? If so, please comment and update with a detailed description. Otherwise, closing for now.
