### ISSUE TITLE
Running package binaries requires *.cmd extension in Windows

### ISSUE THREAD

**Issue by vincentfiestada** [yarnpkg/yarn#7318]
**What is the current behavior?**
In Windows, when running a script that uses an installed package binary, yarn doesn't recognize the executable unless followed by the `.cmd` extension. This prevents scripts from being cross-platform.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a package
2. Install a dependency that provides a "binary" (for example, [Prettier](https://github.com/prettier/prettier))
```sh
yarn add prettier
```
3. Add a script that calls an installed package binary.
```json
"scripts": {
        "format": "prettier --write src/*"
}
```
4. Run the script from the command-line on Windows (any of: cmd.exe, powershell.exe, pwsh.exe)
```sh
yarn format
```
5. Yarn cannot find the executable and returns with exit code 1.
```sh
'prettier' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```
_Extra:_ 
6. Change the script so that it uses `<package.cmd>`. It should now work.

**What is the expected behavior?**
Yarn should be able to detect that it is running on a Windows shell and choose to execute the appropriate batch file present inside _node_modules/.bin_

**Please mention your node.js, yarn and operating system version.**
node: v10.15.3
yarn: v1.16.0
os: Windows 10 build 18362.145

**Comment by DanielRuf** [comment]
Hi @vincentfiestada,

This is probably not a bug in yarn.

What is the current `PATH`? Does it also point to the global `node_modules/.bin` directory? How did you install yarn and the package?

**Comment by DanielRuf** [comment]
Hi @vincentfiestada,

This is probably not a bug in yarn.

What is the current content of `node_modules/.bin`?

**Comment by vincentfiestada** [comment]
@DanielRuf,

It contains `prettier`, which is a bash script and `prettier.cmd`.

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         6/5/2019   1:46 AM            319 prettier
-a----         6/5/2019   1:46 AM            196 prettier.cmd
```

**Comment by DanielRuf** [comment]
I can not reproduce this issue on macOS.

```
 mkdir yarn-prettier-test
➜  projects cd yarn-prettier-test 
➜  yarn-prettier-test yarn init -y
yarn init v1.16.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.05s.
➜  yarn-prettier-test yarn add prettier         
yarn add v1.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ prettier@1.17.1
info All dependencies
└─ prettier@1.17.1
✨  Done in 3.69s.
➜  yarn-prettier-test code .
➜  yarn-prettier-test yarn format
yarn run v1.16.0
$ prettier --write src/*
[error] No matching files. Patterns tried: src/* !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I will create a small reproducible test case on TravisCI.

**Comment by DanielRuf** [comment]
Which shell do you use? Windows cmd, bash, MingW, WSL, ...?

**Comment by vincentfiestada** [comment]
I mentioned it in the issue description; I'm using Powershell 6, but this issue also appears for me if I use cmd.exe or the old powershell.exe.

**Comment by DanielRuf** [comment]
https://travis-ci.com/DanielRuf/yarn-issues-test/jobs/205548558#L104

Can not be reproduced with a simple setup on TravisCI.
Most of us use the Git BASH. So we need some more feedback from others or I have to invest some time and test with cmd / powershell.

https://docs.travis-ci.com/user/reference/windows/
> Git BASH is the shell that’s used to run your build

Generally it is an issue in combination with specific shells.

> Yarn should be able to detect that it is running on a Windows shell and choose to execute the appropriate batch file present inside node_modules/.bin

This normally works for me with MINGW and Git BASH.

**Comment by vincentfiestada** [comment]
This may be an issue with npm itself, actually. I tried running the script with npm and the same error occured.

**Comment by vincentfiestada** [comment]
@DanielRuf, do you know what the actual stance of **yarn** is about which shell it uses to execute scripts?

According to [npm's docs](https://docs.npmjs.com/cli/run-script.html),
> The actual shell your script is run within is platform dependent. By default, on Unix-like systems it is the /bin/sh command, on Windows it is the cmd.exe

Does yarn have the same policy?

**Comment by DanielRuf** [comment]
I am not sure about this but Yarn was initially meant as a npm replacement for many users and uses some packages which are also used by npm like npm-logical-tree.

Not sure if https://www.npmjs.com/package/@zkochan/cmd-shim is the relevant part here.

cc @zkochan you may be able to tell more about the current implementation and if it is the same compared to npm.

**Comment by DanielRuf** [comment]
I am not sure about this but Yarn was initially meant as a npm replacement / better npm alternative for many users and uses some packages which are also used by npm like npm-logical-tree.

Not sure if https://www.npmjs.com/package/@zkochan/cmd-shim is the relevant part here.

cc @zkochan you may be able to tell more about the current implementation and if it is the same compared to npm.

**Comment by zkochan** [comment]
the way bins are treated on Windows is the same on npm/yarn/pnpm

**Comment by vincentfiestada** [comment]
I think I understand now what's happening here. yarn (and npm) are just running the scripts inside `node_modules/bin` using the configured shell. I was under the impression that yarn would actually detect the OS and select the correct executable (i.e., add .cmd if on Windows), but this doesn't seem to be the case. This would be a useful feature to have for those developing on both *nix and Windows, but I admit that it's a bit complex and might be beyond the scope of yarn.

A possible workaround I found is to use Powershell as the script execution shell as it will see `prettier.cmd` inside `.bin` and execute that, ignoring the bash script. If I set `script-shell` to `powershell`, the script now runs on npm. However, it still fails on yarn.

```
npm config set script-shell powershell
npm run format # This succeeds!
yarn format #This fails!
```

The error I get is this:

```
/d : The term '/d' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.                         At line:1 char:1 
        + /d /s /c prettier --write src/* 
```

There seems to be something that yarn is doing differently from npm in this case. I checked and there is no `d` flag for Powershell

**Comment by rally25rs** [comment]
> According to npm's docs,
> 
>  >   The actual shell your script is run within is platform dependent. By default, on Unix-like systems it is the /bin/sh command, on Windows it is the cmd.exe
> 
> Does yarn have the same policy?

Yes, normally yarn calls node's `child_process.spawn` so it should attempt to run your command in `cmd.exe`

https://github.com/yarnpkg/yarn/blob/master/src/util/child.js#L72

As you already found, `script-shell` will override that default. I'm not entirely sure where the `/d` parameter would come from, though it looks like it was a known issue with node at some point https://github.com/nodejs/node/issues/21905 which appears to be "fixed" in node v11 and v12 by https://github.com/nodejs/node/commit/af883e1f99598492474c13447e2a1895c0c6f1b7

So you might want to try upgrading to Node v12 and see if that fixes this.

**Comment by DJWassink** [comment]
I also have this problem, only WSL works (other environment tested are `git bash`, `powershell (old)` `cmd`)
Also tested with a few different node versions (ranging from 8 till latest 12).
The issue also seems to occur with NPM (so not only a yarn problem?)

Also I had this issue for a while already (think it started like 2 months ago).

Also see #7295

**Comment by DanielRuf** [comment]
> I also have this problem, only WSL works

I do not use WSL but for me Yarn and npm work without any problems on Windows using Git Bash. Can you provide the current `PATH` content?

**Comment by DJWassink** [comment]
> Can you provide the current `PATH` content?

```
C:\Users\dirk-\Desktop\cmder_mini\bin;
C:\Python27\;
C:\Python27\Scripts;
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\PostgreSQL\pg96\bin;
C:\Program Files\dotnet\;
C:\Program Files\PHP;
C:\ProgramData\ComposerSetup\bin;
C:\Users\dirk-\AppData\Roaming\nvm;
C:\Program Files\nodejs;
C:\Program Files\Git\cmd;
C:\Program Files\Git\mingw64\bin;
C:\Program Files\Git\usr\bin;
C:\Program Files (x86)\FilExile;
C:\Program Files (x86)\Yarn\bin\;
C:\Users\dirk-\AppData\Local\Microsoft\WindowsApps;
C:\Users\dirk-\AppData\Local\Programs\Microsoft VS Code\bin;
C:\Users\dirk-\AppData\Roaming\Composer\vendor\bin;
C:\Users\dirk-\AppData\Local\hyper\app-3.0.0\resources\bin;
C:\Users\dirk-\Desktop\cmder_mini;
C:\Users\dirk-\AppData\Local\Yarn\bin;
C:\Program Files\Git\mingw64
```

**Comment by DJWassink** [comment]
Just noticed that some scripts do run on my machine, all those scripts started with the [cross-env](https://github.com/kentcdodds/cross-env) package, which seems to use [node-cross-spawn](https://github.com/moxystudio/node-cross-spawn)?

Anyhow in the OP his post if you change this snippet from 
```
"scripts": {
        "format": "prettier --write src/*"
}
```
to:
```
"scripts": {
        "format": "cross-env prettier --write src/*"
}
```

It seems to work fine..

**Comment by DanielRuf** [comment]
```
C:\Program Files (x86)\Yarn\bin\;
C:\Users\dirk-\AppData\Local\Yarn\bin;

C:\Users\dirk-\AppData\Roaming\nvm;
C:\Program Files\nodejs;
```

Some of these may cause issues. Can you test it by removing some like nvm and adding them afterwards again?

**Comment by DJWassink** [comment]
I removed NVM and installed node through the official MSI and the last 2 path's are gone, The yarn paths remain. Still the same issue.

Removing the yarn paths ofcourse results in the terminal not finding yarn, running the installer again simply adds those paths back and the issue still persists.

**Comment by vincentfiestada** [comment]
For the record, thanks to @rally25rs 's suggestion. I can confirm that using PowerShell as the script shell works on Node v12. 🍾 

Also, @DJWassink, I'm using the [ps-nvm](https://github.com/aaronpowell/ps-nvm) module if that helps.
Your `PATH` looks like it contains multiple directories with node.exe binaries. In my case, I had to make sure that yarn is using Node v12. If you install it as a global package using an older node version (e.g. v10), it will use that version with the bug.

For clarity, these are the steps I took:

1. Uninstalled yarn from Node v10 NPM global packages `npm uninstall -g yarn`
2. Installed yarn through chocolatey `choco install -y yarn`
3. Switched to Node v12 `Set-NodeVersion 12`
4. `yarn format` _now works_

**Comment by luastoned** [comment]
I'm having the same problem on plain `cmd.exe`
Both `prettier` and `prettier.cmd` exists in `node_modules/.bin/` but npm/yarn attempt to run the linux version.

Funny enough, `yarn prettier.cmd` works just fine.

**Comment by bghveding** [comment]
I was able to fix this by changing the PATHEXT environment variable. Seems there are case sensitivity issues. By appending `.cmd` to the list I was able to run scripts.

`.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.cmd` was my final list.

**Comment by sneyed** [comment]
I was having the same issue but none of the above solutions worked for me

In addition to `.cmd` I had to also add the following to my PATHEXT system environment variable
`.com;.exe;.bat;.cmd;`

E.g.
`.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC,.com;.exe;.bat;.cmd;`
