### ISSUE TITLE
HOw to revert original proxy settings after I issued set command

### ISSUE THREAD

**Issue by abrhambas01** [yarnpkg/yarn#7322]
Can someone help me
>error D:\www\jigsaw-projects\test-site\node_modules\node-sass: Command failed

I always get that error
```sh
rm -rf node_modules

rm package-lock.json yarn.lock

yarn cache clean

yarn install --prefer-offline --force
```
I already did that
now I get an error 
```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/tailwindcss: tunneling socket could not be established, cause=connect ETIMEDOUT 93.184.216.34:8080".```
even though I have an internet

oh yeah what I remember is I issued this, because of an error that I experience before : 
```
``` $ yarn config set proxy http://example.com:8080```

> how can i reverse that command  ?

**Comment by DanielRuf** [comment]
Hi @abrhambas01,

Try `yarn config delete registry` or `yarn config set registry https://registry.yarnpkg.com`

**Comment by DanielRuf** [comment]
Hi @abrhambas01,

Try `yarn config delete proxy`.

**Comment by DanielRuf** [comment]
Btw, example.com is a domain which is reserved.

**Comment by DanielRuf** [comment]
> error D:\www\jigsaw-projects\test-site\node_modules\node-sass: Command failed
> 
> I always get that error

Please provide the full log / output.

**Comment by DanielRuf** [comment]
> error D:\www\jigsaw-projects\test-site\node_modules\node-sass: Command failed
> 
> I always get that error

Please provide the full log / output.
Generally clearing the caches and trying the offline mode will not work.

**Comment by abrhambas01** [comment]
@DanielRuf Hey, man. Thanks, anyway this is the output when I say 
``` 
$ yarn config list
yarn config v1.9.4
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.9.4 npm/? node/v8.11.3 win32 x64',
  lastUpdateCheck: 1559050703415,
  'yarn-offline-mirror': 'D:\\www\\jigsaw-projects\\test-site\\yarn-offline-cache',
  'proxy=': true,
  'proxy=false': true,
  'proxy=fase': true }
info npm config
{ proxy: 'http://example.com:8080' }
Done in 0.06s.
```

**Comment by abrhambas01** [comment]
This is the result of my
``` yarn install```
```
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/tailwindcss: tunneling socket could not be established, cause=connect ETIMEDOUT 93.184.216.34:8080".
info If you think this is a bug, please open a bug report with the information provided in "D:\\www\\jigsaw-projects\\test-site\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by DanielRuf** [comment]
Please also try `yarn config delete proxy --global`.

**Comment by abrhambas01** [comment]
Can you please share your config list to me ? @DanielRuf , so that we can compare them

**Comment by DanielRuf** [comment]
You might have set it with npm, please check your `.npmrc` files and try the same with the npm config.

> info npm config

**Comment by abrhambas01** [comment]
Sorry for the slow response bro, I thought github would just update by it's own. yeah I'll try it is it npm info config ? or npm config info ?

**Comment by abrhambas01** [comment]
Oh yeah already did npm config delete proxy

**Comment by DanielRuf** [comment]
Also with `--global` and `--system`?
Or just try `npm config edit`.

**Comment by abrhambas01** [comment]
I'm not entirely sure with what you mean but this is the result of my npm config edit

;;;;
; npm userconfig file
; this is a simple ini-formatted file
; lines that start with semi-colons are comments.
; read `npm help config` for help on the various options
;;;;


;;;;
; all options with default values
;;;;
; access=null

; allow-same-version=false

; always-auth=false

; also=null

; audit=true

; audit-level=low

; auth-type=legacy

; bin-links=true

; browser=null

; ca=null

; cafile=undefined

; cache=C:\Users\Bram\AppData\Roaming\npm-cache

; cache-lock-stale=60000

; cache-lock-retries=10

; cache-lock-wait=10000

; cache-max=null

; cache-min=10

; cert=null

; cidr=null

; color=true

; depth=null

; description=true

; dev=false

; dry-run=false

; editor=notepad.exe

; engine-strict=false

; force=false

; fetch-retries=2

; fetch-retry-factor=10

; fetch-retry-mintimeout=10000

; fetch-retry-maxtimeout=60000

; git=git

; git-tag-version=true

; commit-hooks=true

; global=false

; globalconfig=C:\Users\Bram\AppData\Roaming\npm\etc\npmrc

; global-style=false

; group=0

; ham-it-up=false

; heading=npm

; if-present=false

; ignore-prepublish=false

; ignore-scripts=false

; init-module=C:\Users\Bram\.npm-init.js

; init-author-name=

; init-author-email=

; init-author-url=

; init-version=1.0.0

; init-license=ISC

; json=false

; key=null

; legacy-bundling=false

; link=false

; local-address=undefined

; loglevel=notice

; logs-max=10

; long=false

; maxsockets=50

; message=%s

; metrics-registry=null

; node-options=null

; node-version=10.15.0

; offline=false

; onload-script=null

; only=null

; optional=true

; otp=null

; package-lock=true

; package-lock-only=false

; parseable=false

; prefer-offline=false

; prefer-online=false

; prefix=C:\PROGRA~1\nodejs

; preid=

; production=false

; progress=true

; proxy=null

; https-proxy=null

; noproxy=null

; user-agent=npm/{npm-version} node/{node-version} {platform} {arch}

; read-only=false

; rebuild-bundle=true

; registry=https://registry.npmjs.org/

; rollback=true

; save=true

; save-bundle=false

; save-dev=false

; save-exact=false

; save-optional=false

; save-prefix=^

; save-prod=false

; scope=

; script-shell=null

; scripts-prepend-node-path=warn-only

; searchopts=

; searchexclude=null

; searchlimit=20

; searchstaleness=900

; send-metrics=false

; shell=C:\WINDOWS\system32\cmd.exe

; shrinkwrap=true

; sign-git-commit=false

; sign-git-tag=false

; sso-poll-frequency=500

; sso-type=oauth

; strict-ssl=true

; tag=latest

; tag-version-prefix=v

; timing=false

; tmp=C:\Users\Abrham\AppData\Local\Temp

; unicode=false

; unsafe-perm=true

; update-notifier=true

; usage=false

; user=0

; userconfig=C:\Users\Bram\.npmrc

; umask=0

; version=false

; versions=false

; viewer=browser

; _exit=true

; globalignorefile=C:\Users\Bram\AppData\Roaming\npm\etc\npmignore

```

**Comment by abrhambas01** [comment]
Yeah bro, I can then issue a yarn install there right ? 

``` yarn install ```

**Comment by DanielRuf** [comment]
Does `yarn config list` still show the proxy setting? If not you can run the yarn commands now.

Or is the proxy setting still in `globalconfig` or `userconfig`?

**Comment by abrhambas01** [comment]
yarn config v1.9.4
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.9.4 npm/? node/v8.11.3 win32 x64',
  lastUpdateCheck: 1559050703415,
  'yarn-offline-mirror': 'D:\\www\\jigsaw-projects\\test-site\\yarn-offline-cache',
  'proxy=': true,
  'proxy=false': true,
  'proxy=fase': true }
info npm config
{}
Done in 0.29s.

**Comment by DanielRuf** [comment]
Then it should work now.

**Comment by abrhambas01** [comment]
This is the result of my 
```sh
$ yarn install 

yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
warning laravel-mix > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
warning laravel-mix > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
info There appears to be trouble with your network connection. Retrying...
warning laravel-mix > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > vue-loader > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
info There appears to be trouble with your network connection. Retrying...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > browser-sync-webpack-plugin@2.2.2" has unmet peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning "laravel-mix > img-loader@3.0.1" has unmet peer dependency "imagemin@^5.0.0 || ^6.0.0".
[4/4] Building fresh packages...
[-/3] ⠈ waiting...
[-/3] ⠈ waiting...
error D:\www\jigsaw-projects\test-site\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\www\jigsaw-projects\test-site\node_modules\node-sass
Output:
Building: C:\laragon\bin\nodejs\node-v8\node.exe D:\www\jigsaw-projects\test-site\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\laragon\\bin\\nodejs\\node-v8\\node.exe',
gyp verb cli   'D:\\www\\jigsaw-projects\\test-site\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\www\jigsaw-projects\test-site\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\www\jigsaw-projects\test-site\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\www\jigsaw-projects\test-site\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\www\jigsaw-projects\test-site\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\www\jigsaw-projects\test-site\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\www\jigsaw-projects\test-site\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\www\jigsaw-projects\test-site\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\www\jigsaw-projects\test-site\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\www\jigsaw-projects\test-site\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\www\jigsaw-projects\test-site\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\www\jigsaw-projects\test-site\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\www\jigsaw-projects\test-site\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\www\\jigsaw-projects\\test-site\\node_modules\\which\\which.js:13:12)\n    at F (D:\\www\\jigsaw-projects\\test-site\\node_modules\\which\\which.js:68:19)\n    at E (D:\\www\\jigsaw-projects\\test-site\\node_modules\\which\\which.js:80:29)\n    at D:\\www\\jigsaw-projects\\test-site\\node_modules\\which\\which.js:89:16\n    at D:\\www\\jigsaw-projects\\test-site\\node_modules\\isexe\\index.js:42:5\n    at D:\\www\\jigsaw-projects\\test-site\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Abrham\AppData\Local\Programs\Python\Python37\python.EXE gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Abrham\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\laragon\\bin\\nodejs\\node-v8\\node.exe" "D:\\www\\jigsaw-projects\\test-site\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\www\jigsaw-projects\test-site\node_modules\node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by DanielRuf** [comment]
Looks good, this should work now.

**Comment by DanielRuf** [comment]
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2

Please run `yarn global add windows-build-tools`.

https://www.npmjs.com/package/windows-build-tools

Because node-sass is a binary dependency which has to be built by using node-gyp which needs python2.

**Comment by abrhambas01** [comment]
Wow, awesome bro. So after this command ? What will happen ?

**Comment by abrhambas01** [comment]
```
$ yarn global add windows-build-tools
yarn global v1.9.4
[1/4] Resolving packages...
warning windows-build-tools > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠄ core-js
error C:\Users\Abrham\AppData\Local\Yarn\Data\global\node_modules\windows-build-tools: Command failed.
Exit code: 1
Command: node ./dist/index.js
Arguments:
Directory: C:\Users\Abrham\AppData\Local\Yarn\Data\global\node_modules\windows-build-tools
Output:
Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (62.93 kB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\Abrham\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (15.18 kB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\Abrham\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Please restart this script from an administrative PowerShell!
The build tools cannot be installed without administrative rights.
To fix, right-click on PowerShell and run "as Administrator".

```

**Comment by DanielRuf** [comment]
Which command do you mean? `windows-build-tools` installs all the needed things to get your `yarn install` working (also installs Python 2 and sets the python2 PATH variable).

**Comment by abrhambas01** [comment]
Ok, thanks, I can then just use --offline mode ? or --prefer-offline  mode after ? or do I have to just redo these commands all over again? 

```sh
rm -rf node_modules

rm package-lock.json yarn.lock

npm cache clear --force

yarn install```

**Comment by DanielRuf** [comment]
> Ok, thanks, I can then just use --offline mode ? or --prefer-offline mode after ?

This only works if the exact same dependencies were cached at least once. So do a normal `yarn` and then `yarn offline-mode` for future installs using the same `yarn.lock` file. Otherwise it will likely not work. So please do not remove the lockfiles.

And do not clear the cache (as this will remove all available packages from your cache and so the offline mode will not work at all - you should only clean the cache if there is some critical issue with the cache).

**Comment by abrhambas01** [comment]
Oh, so I was wrong when I issued this :
```
rm package-lock.json yarn.lock
```

i just saw this post somewhere, so what does this thing do ?

**Comment by DanielRuf** [comment]
> ```
> rm package-lock.json yarn.lock
> ```
> 
> 
> i just saw this post somewhere, so what does this thing do ?

This will delete your lockfiles and tell your package manager (yarn and npm) to fetch the newest dependencies from the registry - which will generally fail in offline mode.

**Comment by abrhambas01** [comment]
Hey, I have a confusion w/ the term 

### cache 

what I usually do is I copy the .yarnrc file in the same directory with the original .yarn-offline-cache, of course. This time I store it in D:/www/github-projects, I copy it in a specific folder then I run yarn --offline or yarn --prefer-offline and recently I just know this other parameter --force , so what does it do, I'm kind of blank to the description ?

**Comment by DanielRuf** [comment]
@abrhambas01 I think the initial issue is resolved and your setup should run now. Can you close the issue?

**Comment by DanielRuf** [comment]
> what I usually do is I copy the .yarnrc file in the same directory with the original .yarn-offline-cache, of course. This time I store it in D:/www/github-projects, I copy it in a specific folder then I run yarn --offline or yarn --prefer-offline and recently I just know this other parameter --force , so what does it do, I'm kind of blank to the description ?

This is another question for another issue ;-)

**Comment by abrhambas01** [comment]
Ok cheers mate ! 👍
