### ISSUE TITLE
yarn install timeout

### ISSUE THREAD

**Issue by lhwu** [yarnpkg/yarn#7331]
node version: 10.15.3
yarn version: 1.16.0
system: mac 10.14.3

alway timeout...

![image](https://user-images.githubusercontent.com/20239035/59181728-a4588580-8b9a-11e9-8d4d-a1f015fbff38.png)

**Comment by DanielRuf** [comment]
Hi @lhwu,

as the log already says, there is some issue with your network connection or the registry at npmjs.com.

Also see https://status.npmjs.org/

**Comment by lhwu** [comment]
some package cannot install by yarn, i changed to `npm install` is ok

**Comment by DanielRuf** [comment]
Hi @lhwu,

Generally Yarn uses the same registry. Changing to npm makes no big difference in most cases ;-)
