### ISSUE TITLE
Yarn upgrade is not upgrading workspace dependencies

### ISSUE THREAD

**Issue by PratikshitSingh** [yarnpkg/yarn#7346]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The workspace dependencies are not upgraded when using yarn upgrade command in root directory. The package.json and yarn.lock in root directory are being updated by this but package.json of workspaces are not.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
On using yarn upgrade in root directory it should update workspaces as well.

**Please mention your node.js, yarn and operating system version.**
node.js 12.1.0
yarn 1.16.0
OS windows 7

**Comment by josh08h** [comment]
#7698 I think this is related..

**Comment by paul-soporan** [comment]
Closing as fixed in v2 (use the `yarn up` command).

https://yarnpkg.com/getting-started/migration
