### ISSUE TITLE
Two versions of the same package installed

### ISSUE THREAD

**Issue by niftylettuce** [yarnpkg/yarn#7354]
See <https://github.com/remarkjs/remark-lint/issues/213>.  This happens on yarn v1.13.0.

**Comment by DanielRuf** [comment]
> Regarding the general issue, you have two different versions of remark-lint-list-item-indent because two packages depend on it via different ranges. Yarn doesn't provide any guarantee that they will use the same version, even if intuitively you'd think it would (and the same is true for npm - if it works, it's purely by luck).
