### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by MYWProgram** [yarnpkg/yarn#7365]
**Which operating system are you using:**
Win10

**Please describe the steps you took when trying to install Yarn and what went wrong:**
Whatever scripts I used, error: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by olingern** [comment]
Hi @MYWProgram -- is this still a problem? If so, please comment and update with a detailed description. Otherwise, closing for now.
