### ISSUE TITLE
Error: Unable to update lock within the stale threshold

### ISSUE THREAD

**Issue by e1m7bo** [yarnpkg/yarn#7368]
When using yarn with mutex option (type file) run in parallel on many threads (8) I get following error:

~/.gradle/yarn/yarn-v1.7.0/lib/node_modules/yarn/lib/cli.js:78487
    compromised = compromised || function (err) { throw err; };
                                                  ^
Error: Unable to update lock within the stale threshold
    at options.fs.utimes (/home/build/.gradle/yarn/yarn-v1.7.0/lib/node_modules/yarn/lib/cli.js:78409:66)
    at FSReqWrap.oncomplete (fs.js:135:15)

Obviously timeout has been reached. Is it possible to fix it by adjustting some timeout configuration?

**Comment by pauldraper** [comment]
I believe this does not happen when using the network type.

**Comment by pauldraper** [comment]
Looks like yarn is using proper-lockfile which defaults to 10s.

https://github.com/yarnpkg/yarn/blob/d4805c302d9a02fd2a52cb4e02f9092b4689fbb1/src/cli/index.js#L303

**Comment by voxsoftware** [comment]
any solution to this?

**Comment by pevers** [comment]
> any solution to this?

I switched to using `yarn --mutex network` instead of using a lockfile.

**Comment by Kabilan-G** [comment]
In my case, I commented the three lines that caused the problem and it completed the installation that was happening.
            // Verify if we are within the stale threshold
            //if (lock.lastUpdate <= Date.now() - options.stale &&
            //    lock.lastUpdate > Date.now() - options.stale * 2) {
            //    return compromisedLock(file, lock, Object.assign(new Error(lock.updateError || 'Unable to update lock within the stale \
			//	threshold'), { code: 'ECOMPROMISED' }));
            //}

**Comment by karel-3d** [comment]
I made a PR fixing this issue here

https://github.com/yarnpkg/yarn/pull/8260

**Comment by merceyz** [comment]
Closing as fixed in v2 where the cache (mutex) doesn't have this issue

https://yarnpkg.com/getting-started/migration

**Comment by perlun** [comment]
> I switched to using `yarn --mutex network` instead of using a lockfile.

For more details on this: https://classic.yarnpkg.com/lang/en/docs/cli/#toc-concurrency-and-mutex
