### ISSUE TITLE
Appears to be an incorrect install of bluebird

### ISSUE THREAD

**Issue by daveisfera** [yarnpkg/yarn#7383]
**What is the current behavior?**
It appears that bluebird is not installed correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run `yarn install`
2. Start process using webpack
3. Run `yarn install` with a change
4. Restart process using webpack
5. Observer the following error (doesn't happen every time but is fairly common):
```
Non-Webpack Bundle Error :::: /Users/dlj/projects/numetric/node_modules/bluebird/js/release/promise.js:1
TypeError: util.notEnumerableProp is not a function
    at module.exports (/Users/dlj/projects/numetric/node_modules/bluebird/js/release/promise.js:28:6)
    at Object.<anonymous> (/Users/dlj/projects/numetric/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**What is the expected behavior?**
bluebird continues to load properly

**Please mention your node.js, yarn and operating system version.**
node: 10.16.0
macos: 10.14.5

If you delete the bluebird module (i.e. `rm -rf node_modules/bluebird`) and then run `yarn install` again, then it appears to be fixed

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
