### ISSUE TITLE
Building fresh packages... canvas,Execution stuck here

### ISSUE THREAD

**Issue by LiangFuzhi** [yarnpkg/yarn#7385]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
mac os 10.14.5
node 12.6.0
yarn 1.16.0
**If the current behavior is a bug, please provide the steps to reproduce.**

[4/4] 🔨  Building fresh packages...
[-/7] ⠄ waiting...
[2/7] ⠄ canvas
[3/7] ⠄ fsevents
[-/7] ⠄ waiting...
[-/7] ⠄ waiting...

Execution stuck here

**What is the expected behavior?**
Normal execution
**Please mention your node.js, yarn and operating system version.**

**Comment by bluetomlee** [comment]
i have same problem

**Comment by jankuss** [comment]
I just had this problem aswell. I thought it was stuck, but it just takes unreasonably long. My install finished after 15 minutes after being in that state.

**Comment by allaniftrue** [comment]
same for me
```terminal
[4/4] 🔨  Building fresh packages...
[1/12] ⠂ canvas
[12/12] ⠂ node-sass
[-/12] ⠂ waiting...
[-/12] ⠂ waiting...
[-/12] ⠂ waiting...
```

**Comment by soaringk** [comment]
If you're behind the GFW, either turn on global proxy/TUN mode (if your software support this feature), or you can add a taobao mirror.

Your packages probably need a copy of chromium, and downloading it requires access to google services which are clearly blocked by the GFW.

**Comment by paul-soporan** [comment]
Closing as it's either an external issue (in case `canvas` really takes this long to install) or an issue that has been fixed in v2, where the package building process has been revamped.

https://yarnpkg.com/getting-started/migration
