### ISSUE TITLE
Subdependencies are missing on reinstall if an alias exists for it

### ISSUE THREAD

**Issue by Macil** [yarnpkg/yarn#7392]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If you install an aliased package pointing to a certain "target" package, and you install another npm package "depender" which depends on the target package, then in some situations, Yarn fails to install the target package under its original name in a place where depender can find it.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn add string-width@4.1.0 widest-line@2.0.1 string-width-v2@npm:string-width@2.1.1
yarn add v1.16.0
<...>
✨  Done in 0.69s.
```

The package `widest-line@2.0.1` depends on `string-width@2.1.1`. After this command, node_modules is set up correctly: a copy of `string-width@2.1.1` is installed in node_modules/string-width-v2/ *and* in node_modules/widest-line/node_modules/string-width/.

Now remove node_modules and run yarn to re-create node_modules from package.json+yarn.lock:

```
$ rm -rf node_modules/
$ yarn
yarn install v1.16.0
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["string-width@^2.1.1"] is trying to unpack in the same destination "/Users/chris/Library/Caches/Yarn/v4/npm-string-width-v2-2.1.1-ab93f27a8dc13d28cac815c462143a6d9012ae9e/node_modules/string-width-v2" as pattern ["string-width-v2@npm:string-width@2.1.1"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 0.18s.
```

Yarn logs a warning, and then fails to set up node_modules correctly: There is no node_modules directory inside of node_modules/widest-line/. When widest-line requires string-width, it will get version 4.1.0 instead of version 2.1.1.

**What is the expected behavior?**

Yarn should re-generate the same node_modules directory from package.json+yarn.lock as it had generated originally. There should be an install of `string-width@2.1.1` in both node_modules/string-width-v2/ and in node_modules/widest-line/node_modules/string-width/.

**Please mention your node.js, yarn and operating system version.**
node v10.16.0
yarn 1.16.0
macOS 10.14.5

**Comment by hankthewhale** [comment]
I ran into this issue yesterday. The way I "fixed" it was to edit the `yarn.lock` file directly to point at the correct sub-dependency version that my npm alias was using. This obviously isn't ideal, but it did the trick for me.

**Comment by paul-soporan** [comment]
Closing as this has been fixed in the v2.

https://yarnpkg.com/getting-started/migration
