### ISSUE TITLE
`yarn install --ignore-engines` makes it impossible to pass `yarn check --integrity --verbose`

### ISSUE THREAD

**Issue by breathe** [yarnpkg/yarn#7394]
**What is the current behavior?**

`yarn install --ignore-engines`

In my project this makes no changes to yarn.lock -- i'm not sure what happens differently/where information about the use of this flag its stored ...

However when I then run:

`yarn check --integrity --verbose`

```
yarn check --integrity --verbose
yarn check v1.16.0
verbose 0.167278624 Checking for configuration file "/Users/ncohen/software/itsacheckmate.com/Web/.npmrc".
verbose 0.167613268 Checking for configuration file "/Users/ncohen/.npmrc".
verbose 0.167796785 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.168003189 Checking for configuration file "/Users/ncohen/software/itsacheckmate.com/Web/.npmrc".
verbose 0.168205594 Checking for configuration file "/Users/ncohen/software/itsacheckmate.com/.npmrc".
verbose 0.168441999 Checking for configuration file "/Users/ncohen/software/.npmrc".
verbose 0.168643264 Checking for configuration file "/Users/ncohen/.npmrc".
verbose 0.16884748 Checking for configuration file "/Users/.npmrc".
verbose 0.169517484 Checking for configuration file "/Users/ncohen/software/itsacheckmate.com/Web/.yarnrc".
verbose 0.169739586 Checking for configuration file "/Users/ncohen/.yarnrc".
verbose 0.169952692 Found configuration file "/Users/ncohen/.yarnrc".
verbose 0.170371067 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.17056717 Checking for configuration file "/Users/ncohen/software/itsacheckmate.com/Web/.yarnrc".
verbose 0.170699342 Checking for configuration file "/Users/ncohen/software/itsacheckmate.com/.yarnrc".
verbose 0.17083641 Checking for configuration file "/Users/ncohen/software/.yarnrc".
verbose 0.171008935 Checking for configuration file "/Users/ncohen/.yarnrc".
verbose 0.171120747 Found configuration file "/Users/ncohen/.yarnrc".
verbose 0.171542451 Checking for configuration file "/Users/.yarnrc".
verbose 0.176670775 current time: 2019-07-12T19:13:18.973Z
warning Integrity check: Flags don't match
error Integrity check failed
verbose 0.27589588 Error: Found 1 errors.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:750:123)
    at /usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:60340:13
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:315:13
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**What is the expected behavior?**

I'd expect that either the yarn.lock file would change to somehow indicate the flags used to create the file if these flags are such that using different flags creates different installations which are not mutually 'in integrity' -- or that this error wouldn't happen if the different installation behaviors are not incompatible ...

I've run into this issue because [heroku-buildpack-nodejs](https://www.github.com/heroku/heroku-buildpack-nodejs) runs `yarn install --ignore-engines` whereas I typically don't on my local machine.  Llooking for a strategy to reconcile the behavior - I run `yarn install --ignore-engines` on my local machine but that actually changes no files that are in my repo -- so I'm left feeling unsure how to reconcile these different executions modes ...

I am probably going to fork the heroku-buildpack-nodejs and change it to not use the `--ignore-engines` flag to avoid this -- however it seems generally like something is buggy/non-ideal here ...

**Please mention your node.js, yarn and operating system version.**

```
> node --version
v12.5.0
> yarn --version
1.16.0

system: macOS 10.14.5
```

**Comment by BYK** [comment]
I don't think we'll every make the change you suggest as I don't think the lock file is the place to store this value. AFAIK these flags are stored in `node_modules/.yarn-integrity` file but @arcanis would know better.

For your Heroku issue, I'd recommend using this feature with a project-level `.yarnrc` file: https://yarnpkg.com/en/docs/yarnrc#toc-cli-arguments

**Comment by breathe** [comment]
Fair enough I guess.  I think the design as it is now is not correct tho ...  I'm getting errors running verifications that I am having a lot of trouble understanding/reproducing ...  Its possible there's something else going on within my heroku build's that interfering with my ability to understand this I suppose ...

I think a better design might be something along the lines of ...:

1.`.yarnrc` provides a project a way to provide a blessed set of flags/values: 'this flag must have this value'
2. invocations of `yarn install` should serialize the flags used to lockfile unless a provided flag disagrees with value as blessed by .yarnrc
3. calls to `yarn install` should re-use the flags from lockfile if no additional flags are provided -- if flags are specified on command line then the additional values should be checked against the blessed flags from .yarnrc and if --frozen-lockfile is provided then provided flags should also be checked against the flag values already serialized in yarn.lock ... -- otherwise if --frozen-lockfile is not present then the values in yarn.lock should be updated ...

**Comment by BYK** [comment]
If you are feeling strongly about your approach I invite you to submit and RFC: https://github.com/yarnpkg/rfcs

This will also help you think more broadly about your idea and see if there are any edge cases or flaws in it.
