### ISSUE TITLE
`yarn -h` is equivalent to `yarn help install`, not `yarn help`

### ISSUE THREAD

**Issue by ithinkihaveacat** [yarnpkg/yarn#740]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

`yarn -h` is equivalent to `yarn help install`, not `yarn help`. This is surprising, and makes it hard to discover the available commands.

**If the current behavior is a bug, please provide the steps to reproduce.**

NA

**What is the expected behavior?**

`yarn -h` is equivalent to `yarn help`.

**Please mention your node.js, yarn and operating system version.**

```sh
$ node -v
v6.7.0
$ yarn --version
0.15.1
$ uname -a
Darwin kapow.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

**Comment by appsforartists** [comment]
For thoroughness, `yarn --help` has the same problem.
