### ISSUE TITLE
Why does "yarn bin" need internet connection?

### ISSUE THREAD

**Issue by rightaway** [yarnpkg/yarn#7400]
If you run `yarn bin` while offline you get "warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries." Why does that command need to know anything about whether you have an internet connection?

**Comment by tbenst** [comment]
What's crazy is the same is true for `yarn --help`. Makes using in a no-internet sandbox very difficult

**Comment by merceyz** [comment]
Probably because of the update check, closing as fixed in v2 where this isn't the case

https://yarnpkg.com/getting-started/migration
