### ISSUE TITLE
Linking dependencies is taking a long time

### ISSUE THREAD

**Issue by alepee** [yarnpkg/yarn#7408]
Ref: https://github.com/yarnpkg/yarn/issues/1496

Even with recent yarn version, and on various system, yarn is taking a very long time to link dependencies. This performance issue has been reported, but the issue has been closed by maintainer and not reopen since then.

This is a serious issue for lot of users, and should be at least answered.

**Comment by wilo087** [comment]
Any solution about this issue?

**Comment by alepee** [comment]
As far as I know, no 😞 We observed within a docker environment (`node:10-alpine` on docker4mac, docker-machine/xhyve and docker on linux host).

**Comment by AshleyColemanBigHealth** [comment]
Yes I would also like to at least the knobs I can turn to speed this up

**Comment by thiefjim** [comment]
yarn v1.17.3
node v10.16.3
npm 6.9.0

# Windows
I have tried to put my App project folder location at the same disk section as `yarn cache dir`. 
yarn cache dir -> C:\Users\<YOUR USERNAME>\AppData\Local\Yarn\Cache\v4

The result:
old location -> D:\myApp  `Done in 747.17s.`
new location -> C:\myApp `Done in 488.97s.`

C and D are the same physical disk.
# Mac
However Mac is faster than Windows `Done in 121.37s`

I think the bottle neck is the disk read/write speed?

**Comment by alepee** [comment]
Switching back from `yarn` to `npm` divided our install time by 3 within an Linux/Docker environment.

**Comment by Cally99** [comment]
I'm switching back too. Yarn has far too many bugs and stupid things that takes so long to workout
