### ISSUE TITLE
yarn add runs postinstall script,  but not postadd script

### ISSUE THREAD

**Issue by StephanBijzitter** [yarnpkg/yarn#7411]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
After running `yarn add jquery`, it runs `postinstall` if that script is specified. While that (to me) is strange and unexpected, I'm fine with that. However, `postadd` is not run while I would definitely expect it to run.

**What is the expected behavior?**
A `postadd` script should run after `yarn add`.

I have a `postinstall` script that updates a `.env` file with new environment variables from `.env.example`. I could add `yarn audit` in there as well, but then every `yarn install` performs an audit and that would just be annoying.

**Please mention your node.js, yarn and operating system version.**
NodeJS 8.10.0 (can't update yet because of AWS Lambda)
Yarn 1.17.3
OS X

**Reproduction**
* Have a `package.json` with at least the following scripts defined:
```
  "scripts": {
    "postinstall": "echo 'postinstall script'",
    "postadd": "yarn audit"
  },
```
* Run `yarn add jquery`.

Output:
```
Stephans-MacBook-Pro:<Redacted> stephan$ yarn add jquery
yarn add v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ jquery@3.4.1
info All dependencies
└─ jquery@3.4.1
$ echo 'postinstall script'
postinstall script
✨  Done in 2.85s.
```

**Comment by merceyz** [comment]
That's not part of the install lifecycle and most likely wont be implemented as one
