### ISSUE TITLE
Yarn install link (brew install) occurs 500 server error

### ISSUE THREAD

**Issue by Xsolute** [yarnpkg/yarn#7426]
**Do you want to request a *feature* or report a *bug*?**

It seems like a bug.

**What is the current behavior?**
'brew install yarn' raises 500 internal server error from github release link.

**If the current behavior is a bug, please provide the steps to reproduce.**

GitHub should fix the static link for download, or it needs to be reuploaded.

**What is the expected behavior?**
It will make 'yarn install' work well.

**Please mention your node.js, yarn and operating system version.**
node v12.6.0, MacOS 10.14.5

**Comment by jfirebaugh** [comment]
This wasn't an issue in yarn; GitHub was experiencing a service disruption at this time: https://www.githubstatus.com/incidents/8x69vj1xyp9v

**Comment by Xsolute** [comment]
Thanks for answering. I did not noticed about GitHub service disruption. Appreciates about informing.
