### ISSUE TITLE
pnp incompatable with express and pug

### ISSUE THREAD

**Issue by kcwitt** [yarnpkg/yarn#7431]
request feature to register allowable packages.

"express" has a built in pluggable view rendering middleware which is set by calling `app.set('view engine', 'pug')` to use pug (for example). Then somewhere inside the express source code pug is actually loaded with `require('pug')` (or whatever view engine was set in the `app.set` call).

This throws 'Error: Package "express@4.16.4" ... is trying to require the package "pug"'.

This behavior is somewhat noted in the troubleshooting section of the [pnp documentation](https://yarnpkg.com/en/docs/pnp/troubleshooting). The first two troubleshooting options are not available since they require changing the express source code, and the third option (requiring "pug" in the top level project) doesn't solve the error.

Since pnp works by loading a static "path resolution" lookup table into memory, it is possible to allow the developer to manually add a dependency (in this case adding 'pug' as a dependency to 'express') to this table in the main application code (ie. the .pnp.js file would provide some sort of global function for registering build-time deterministic "dynamic dependancies")?

for example:
```
yarn.register({
  package: 'express',
  depends: ['pug'],
});
```

In the meantime, adding pug as a dependency to the root project does not seem to satisfy the requirement. Is there another workaround for the specific express/pug issue?

node: v10.15.3
yarn: v1.17.3
os: mac mojave

**Comment by kcwitt** [comment]
working solution is the following
```
app.set('views', path.join(appDir, 'views'));
app.engine('pug', require('pug').__express); // pass the pug engine into app instead of it calling from within app
app.set('view engine', 'pug');
```

This seems to be the best and most idiomatic way of solving this issue, but it would still be a nice pnp feature to be able to specify a whitelist if needed.

**Comment by merceyz** [comment]
Closing as this is an external issue

> This seems to be the best and most idiomatic way of solving this issue, but it would still be a nice pnp feature to be able to specify a whitelist if needed.

Yarn v2 has this implemented as [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions)
