### ISSUE TITLE
After "done" report:There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by rickonji** [yarnpkg/yarn#7432]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
execute `yarn` in container, use proxy
yarn config v1.17.3:
```
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'http://xxxx/npm/',
  'strict-ssl': true,
  'user-agent': 'yarn/1.17.3 npm/? node/v8.16.0 linux x64',
  proxy: 'http://xxxx:xxxx' }
```

bug:
`yarn`
![image](https://user-images.githubusercontent.com/46045107/61767244-41534300-ae16-11e9-82cf-28bdb6688590.png)

**Comment by rickonji** [comment]
what did yarn do after `done`?

**Comment by x22x22** [comment]
me  too

**Comment by sosnail** [comment]
@rickonji

yarn config set `disable-self-update-check true`

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
