### ISSUE TITLE
Couldn't publish package- Yarn

### ISSUE THREAD

**Issue by Bhagath11** [yarnpkg/yarn#7433]
When i am executing "yarn publish", I encounter this "Couldn't publish package: "https://registry.yarnpkg.com/vuelibrarydemo: you must verify your email before publishing a new package: https://www.npmjs.com/email-ed"

**Comment by GongT** [comment]
Why not just verify it?

**Comment by Bhagath11** [comment]
Verified the email.
The error still there, so closed the current command prompt and executed again. It worked fine. 
Thank you
