### ISSUE TITLE
error An unexpected error occurred: "Expected a key".

### ISSUE THREAD

**Issue by zaggerj** [yarnpkg/yarn#7438]
sudo yarn
yarn install v1.12.3
error An unexpected error occurred: "Expected a key".
info If you think this is a bug, please open a bug report with the information provided in "/usr/bin/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

it always go like that: error An unexpected error occurred: "Expected a key".
when runs command like yarn init -y,yarn,yarn add xx

**Comment by janaagaard75** [comment]
I was able to fix this issue, but fixing a syntax error in my `.yarnrc` file.

(I changed `"save-prefix": ""` to `save-prefix ""`.)

**Comment by olingern** [comment]
@zaggerj Is this still an issue? If so, please comment and happy to reopen. 

Also, please add reproductions steps so that we can troubleshoot.
