### ISSUE TITLE
Yarn install checks the version of yarn installation!

### ISSUE THREAD

**Issue by htondkar** [yarnpkg/yarn#7444]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When I run `yarn` it both installs packages and checks for updates for yarn itself. The machine that is running this command is using a private registry and does not have any access to the internet. The problem is that yarn's request to "yarn.pkg/latest-version" fails and is retried for 3 times which blocks my pipeline for 6 minutes or more which is unacceptable.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run `yarn install --verbose` and observe the network requests made by yarn.

**What is the expected behavior?**
Checking for updates for yarn has nothing to do with installing packages. It's wrong to mix concerns and do both thing under one command. There should be a separate command or flag to control this behavior. It can cause a lot of problems in isolated environments.

**Please mention your node.js, yarn and operating system version.**
Node: v10.16.0
Yarn: 1.15.2
OS: Ubuntu 18.04.2

**Comment by aladdin-add** [comment]
+1 , hit the same issue!

**Comment by zhixiaoqiang** [comment]
+1 , hit the same issue!

**Comment by merceyz** [comment]
Closing as fixed in v2 where there is no update check

https://yarnpkg.com/getting-started/migration
