### ISSUE TITLE
Problem updating project packages

### ISSUE THREAD

**Issue by zpgm** [yarnpkg/yarn#7455]
The yarn-error.log file content:

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\XXXXXXXX\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js

PATH: 
  C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\12.0\DLLShared\;C:\Program Files (x86)\Roxio\OEM\AudioCore\;C:\Program Files (x86)\Intel\Services\IPT\;C:\Users\XXXXXXXX\SysTools\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;"C:\Program Files (x86)\Notepad++";C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server Migration Assistant for Access\bin\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\IncrediBuild;C:\Program Files\nodejs\;C:\Program Files (x86)\Nmap;C:\Users\XXXXXXXX\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap;C:\Program Files (x86)\Nmap;C:\Users\XXXXXXXX\.dotnet\tools;C:\Users\XXXXXXXX\AppData\Roaming\npm

Yarn version: 
  1.17.3

Node version: 
  12.7.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.0.1.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Users\XXXXXXXX\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141091:19)
      at Object.onceWrapper (events.js:291:20)
      at ClientRequest.emit (events.js:203:13)
      at TLSSocket.emitRequestTimeout (_http_client.js:680:40)
      at Object.onceWrapper (events.js:291:20)
      at TLSSocket.emit (events.js:203:13)
      at TLSSocket.Socket._onTimeout (net.js:434:8)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

npm manifest: 
  {
          "name": "xxxx-react-components",
          "version": "1.0.0",
          "description": "",
          "main": "index.js",
          "scripts": {
                  "test": "echo \"Error: no test specified\" && exit 1",
                  "wbp": "webpack",
                  "dev": "webpack --mode development --watch",
                  "styleguide": "cd ReactApp & ASSETS_PATH='/wwwroot' & styleguidist server",
                  "styleguide:build": "styleguidist build"
          },
          "keywords": [],
          "author": "xxxxxxxxxxxxxxxxxxxx@gmail.com",
          "license": "ISC",
          "devDependencies": {
                  "@babel/core": "^7.4.3",
                  "@babel/plugin-proposal-class-properties": "^7.0.0",
                  "@babel/plugin-proposal-decorators": "^7.0.0",
                  "@babel/plugin-proposal-do-expressions": "^7.0.0",
                  "@babel/plugin-proposal-export-default-from": "^7.0.0",
                  "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
                  "@babel/plugin-proposal-function-sent": "^7.0.0",
                  "@babel/plugin-proposal-json-strings": "^7.0.0",
                  "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
                  "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
                  "@babel/plugin-proposal-numeric-separator": "^7.0.0",
                  "@babel/plugin-proposal-optional-chaining": "^7.0.0",
                  "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
                  "@babel/plugin-proposal-throw-expressions": "^7.0.0",
                  "@babel/plugin-syntax-dynamic-import": "^7.0.0",
                  "@babel/plugin-syntax-import-meta": "^7.0.0",
                  "@babel/plugin-transform-modules-commonjs": "^7.0.0",
                  "@babel/preset-env": "^7.4.3",
                  "@babel/preset-react": "^7.0.0",
                  "@devexpress/dx-react-core": "^1.10.4",
                  "@devexpress/dx-react-grid": "^1.10.4",
                  "@devexpress/dx-react-grid-material-ui": "^1.10.4",
                  "@material-ui/core": "^3.9.3",
                  "@material-ui/icons": "^3.0.2",
                  "aspnet-webpack": "^3.0.0",
                  "babel-core": "^7.0.0-bridge.0",
                  "babel-eslint": "^10.0.1",
                  "babel-jest": "^23.6.0",
                  "babel-loader": "^8.0.5",
                  "babel-plugin-react-docgen": "^3.0.0",
                  "babel-plugin-styled-components": "^1.10.0",
                  "babel-preset-react-app": "^7.0.2",
                  "bootstrap": "^4.3.1",
                  "browser-sync": "^2.26.3",
                  "browser-sync-webpack-plugin": "^2.2.2",
                  "copyfiles": "^2.0.0",
                  "cross-env": "^5.0.0",
                  "css-loader": "^0.28.7",
                  "dotenv": "^7.0.0",
                  "eslint": "^5.12.0",
                  "eslint-config-airbnb": "^17.1.0",
                  "eslint-import-resolver-webpack": "^0.10.1",
                  "eslint-plugin-import": "^2.2.0",
                  "eslint-plugin-jsx-a11y": "^6.0.2",
                  "eslint-plugin-react": "^7.0.1",
                  "extract-text-webpack-plugin": "^4.0.0-beta.0",
                  "file-loader": "^3.0.1",
                  "fs": "^0.0.1-security",
                  "happypack": "^5.0.1",
                  "html-webpack-plugin": "^3.2.0",
                  "isomorphic-fetch": "^2.2.1",
                  "jest-cli": "^23.6.0",
                  "jquery": "^3.2.1",
                  "node-pre-gyp": "^0.12.0",
                  "node-sass": "^4.11.0",
                  "opn-cli": "^4.0.0",
                  "popper.js": "^1.12.6",
                  "raw-loader": "^2.0.0",
                  "rimraf": "^2.6.1",
                  "sass-loader": "^7.1.0",
                  "style-loader": "^0.19.0",
                  "uglifyjs-webpack-plugin": "^1.0.1",
                  "url-loader": "^1.1.2",
                  "webpack": "^4.29.6",
                  "webpack-cli": "^3.3.0",
                  "webpack-dev-middleware": "^3.6.2",
                  "webpack-dev-server": "^3.1.14",
                  "webpack-hot-middleware": "^2.24.3",
                  "webpack-md5-hash": "^0.0.6",
                  "webpack-notifier": "^1.7.0"
          },
          "dependencies": {
                  "@jsonforms/core": "^2.2.2",
                  "@jsonforms/examples": "^2.2.2",
                  "@jsonforms/material-renderers": "^2.2.2",
                  "@jsonforms/react": "^2.2.2",
                  "@progress/kendo-drawing": "^1.5.11",
                  "@progress/kendo-react-gauges": "^2.10.0",
                  "@progress/kendo-react-intl": "^2.10.0",
                  "any-resize-event": "^1.0.0",
                  "axios": "^0.18.0",
                  "circular-dependency-plugin": "^5.0.2",
                  "color": "^3.1.0",
                  "d3": "^5.9.2",
                  "lodash": "^4.17.11",
                  "material-ui": "^0.20.2",
                  "moment": "^2.24.0",
                  "node-uuid": "^1.4.8",
                  "prop-types": "^15.6.2",
                  "rc-progress": "^2.3.0",
                  "react": "^16.8.5",
                  "react-d3-library": "^1.1.8",
                  "react-day-picker": "^7.3.0",
                  "react-dom": "^16.8.5",
                  "react-helmet": "^5.2.0",
                  "react-highlight-words": "^0.16.0",
                  "react-hot-loader": "^4.8.3",
                  "react-jsonschema-form": "^1.4.0",
                  "react-loadable": "^5.5.0",
                  "react-measure": "^2.3.0",
                  "react-modal": "^3.1.11",
                  "react-native-svg-charts": "^5.2.0",
                  "react-redux": "^7.0.1",
                  "react-router-dom": "^5.0.0",
                  "react-sizeme": "^2.6.7",
                  "react-styleguidist": "^9.0.8",
                  "react-tippy": "^1.2.3",
                  "react-tooltip": "^3.10.0",
                  "react-virtualized": "^9.21.1",
                  "react-virtualized-auto-sizer": "^1.0.2",
                  "react-window": "^1.8.1",
                  "react-window-size": "^1.2.2",
                  "redux-localstorage-simple": "^2.1.6",
                  "resize-event": "^1.2.1",
                  "styled-components": "^3.5.0-0",
                  "styled-theme": "^0.3.3",
                  "styled-tools": "^1.6.0"
          }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
