### ISSUE TITLE
Big Problem with yarn

### ISSUE THREAD

**Issue by hgdqnhpoor** [yarnpkg/yarn#7465]
error：Who can tell me why?

![image](https://user-images.githubusercontent.com/33650925/62670332-72f70d00-b9c5-11e9-9ef7-97a85cefc142.png)

**Comment by cinderblock** [comment]
"please open a bug report with the information provided in `C:\my-view\tomywayiview\yarn-error.log`"

You are missing critical information to help debug this.

**Comment by hgdqnhpoor** [comment]
> "please open a bug report with the information provided in `C:\my-view\tomywayiview\yarn-error.log`"
> 
> You are missing critical information to help debug this.
Redo system environment variables back to normal

**Comment by cinderblock** [comment]
> Redo system environment variables back to normal

If this issue is fixed, please close it. Thanks! :)
