### ISSUE TITLE
[Request] When publishing, replace "link:../dir" with the version of the package being linked with

### ISSUE THREAD

**Issue by alshdavid** [yarnpkg/yarn#7469]
in my package.json I have

```json
"dependencies": {
    "components": "link:../components",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
```

This works fine during development, but when trying to publish the packages to npm the `"link:../components"` remains.

What would be nice is for yarn to take the `"link:../components"` and replace it with the version of the package.json in the file it's being linked with. 

basically

```json
"dependencies": {
    "components": "link:../components",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
```

would convert to 

```json
"dependencies": {
    "components": "1.2.3",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
```

on `yarn pack` or `yarn publish`

**Comment by merceyz** [comment]
Closing as fixed in v2 where you can use the `workspace:` protocol which does this

https://yarnpkg.com/getting-started/migration
