### ISSUE TITLE
Yarn output seems truncated

### ISSUE THREAD

**Issue by janv** [yarnpkg/yarn#747]
**Do you want to request a _feature_ or report a _bug_?**
A Bug

**What is the current behavior?**
When I run a yarn command that outputs a long list of lines, like `yarn ls` or `yarn outdated`, the output in my terminal seems to be cut off after a short while. For example in a project with the entire react, webpack, babel setup, `yarn ls` ends like this:

```
│  ├─ readable-stream@^2.0.0
│  ├─ readable-stream@2.1.5
│  │  ├─ buffer-shims@^1.0.0
│  │  ├─ core-util-is@~1.0.0
│  │  ├─ inherits@~2.0.1
│  │  ├─ isarray@~1.0.0
│  │  ├─ process-nextick-args@~1.0.6
│  │  ├─ string_decoder@~0.10.x
│  │  └�v6.1.0 myproject (master) $
```

That question mark there, looks like the output stream cut off in the middle of an escape-sequence.
Other times `yarn ls` only gets to the `babel-` packages before stopping abruptly.

The same issue can be observed running `yarn outdated`. If I compare the output of that to `npm outdated`, it's identical, but stops early. This behavior was observable in two separate projects.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above description.

**What is the expected behavior?**
I want `yarn ls` to output _all_ my packages and not cut off the output early.

**Please mention your node.js, yarn and operating system version.**
Node 6.1.0
Yarn 0.15.1, installed via npm
Mac OS 10.11.6

**Comment by janv** [comment]
I updated to node 6.7.0 and the issue seems to have disappeared.

**Comment by janv** [comment]
Even in Node 6.7, when piping the output of `yarn ls | less`, I get truncated output again.

**Comment by ZeeCoder** [comment]
I had a similar issue.
Upgrading from Node 6.2 to 6.10 solved it.

Previously, I had these outputs

`yarn outdated`
![screen shot 2017-03-13 at 14 45 22](https://cloud.githubusercontent.com/assets/3679506/23859836/ef68b870-07fc-11e7-9374-e2d545bdebbc.png)

`npm outdated`
NPM v4.3.0
![screen shot 2017-03-13 at 14 45 15](https://cloud.githubusercontent.com/assets/3679506/23859855/fe157bf6-07fc-11e7-902f-13229c7a428f.png)


Which means npm was not affected for some reason.
