### ISSUE TITLE
Yarn install error

### ISSUE THREAD

**Issue by abhay-pos** [yarnpkg/yarn#7471]
**Which operating system are you using:** Window 10 64 bit

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Yarn install -> enter

Getting following error

![image](https://user-images.githubusercontent.com/21664432/62860776-f0e94a00-bd1e-11e9-80d4-dd250fecedc2.png)

**Comment by olingern** [comment]
Is this still an issue? If so, please comment and happy to reopen. 

Also, please add reproductions steps
