### ISSUE TITLE
`yarn install --frozen-lockfile` does not fail when dependencies are manually deleted

### ISSUE THREAD

**Issue by KATT** [yarnpkg/yarn#7476]
## Summary

This might be by design.

When a dependency has been removed `package.json`, `yarn install --frozen-lockfile` does not fail even if running `yarn install` would generate a new `yarn.lock` file

Try it by cloning  https://github.com/KATT/yarn-lockfile-deleted-dependencies and run `yarn install --frozen-lockfile`

## Steps to reproduce

1. Manually remove a package from `package.json`
1. Run `yarn install --frozen-lockfile`

Or

```sh
git clone git@github.com:KATT/yarn-lockfile-deleted-dependencies.git
cd yarn-lockfile-deleted-dependencies
npx yarn@1.17.3 install --frozen-lockfile
```

### Expected behaviour

Yarn install fails with an error.

### Actual behaviour

```
$ npx yarn@1.17.3 install --frozen-lockfile
npx: installed 1 in 6.7s
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
success Nothing to install.
✨  Done in 0.26s.
```

**Comment by paul-soporan** [comment]
Fixed in the v2.

https://yarnpkg.com/getting-started/migration
