### ISSUE TITLE
yarn verify dev dependencies when running in production mode

### ISSUE THREAD

**Issue by 2roy999** [yarnpkg/yarn#7478]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to install package in production mode, yarns verify node version with dev dependencies.

To reproduce on a new empty directory, run the commands:
```sh
nvm use 10.16
yarn add --dev eslint@6
rm -rf node_modules
nvm use 10.11
yarn install --production
```

**What is the expected behavior?**
I expect yarn to install all production dependencies and not fail the installation because the dev dependencies aren't installed in this mode.

**Please mention your node.js, yarn and operating system version.**
yarn: 1.17.3
OS: linux
node: as written in the nvm scripts.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the engines check is removed

https://yarnpkg.com/getting-started/migration
