### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by Akionka** [yarnpkg/yarn#7479]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In the Russian version of site, some distros names are blank

**If the current behavior is a bug, please provide the steps to reproduce.**

Go to [here](https://yarnpkg.com/ru/docs/install) then enable Russian translation and see that:
![image](https://user-images.githubusercontent.com/42269025/63182093-5c525500-c05a-11e9-94fb-64a418440c3c.png)

**What is the expected behavior?**

Distros names

**Comment by tkamenoko** [comment]
related to https://github.com/yarnpkg/website/issues/914 ? You should close this issue and see https://github.com/yarnpkg/website .
