### ISSUE TITLE
`||` or operator in package name?

### ISSUE THREAD

**Issue by rpivo** [yarnpkg/yarn#7481]
I'm trying to understand the syntax inside **yarn.lock** files, and I came across this when installing a recent version of React:

```
"js-tokens@^3.0.0 || ^4.0.0":
version "4.0.0"
  resolved "https://registry.yarnpkg.com/js-tokens/-/js-tokens-4.0.0.tgz#19203fb59991df98e3a287050d4647cdeaf32499"
  integrity sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==
```

I'm confused by the use of the `||` **or** operator here in the first line `"js-tokens@^3.0.0 || ^4.0.0"`. What exactly is this saying -- that any version greater than 3.0.0 *or* any version greater than 4.0.0 can be used? And the following line -- `version "4.0.0"` -- describes the exact version to be used? Why use the or operator here?

(using latest yarn, 1.17.3)

**Comment by merceyz** [comment]
> What exactly is this saying -- that any version greater than 3.0.0 or any version greater than 4.0.0 can be used?

It means that one of your dependencies requested `js-tokens` at version `^3.0.0 || ^4.0.0`

> And the following line -- version "4.0.0" -- describes the exact version to be used?

It's the version that range was resolved to

> Why use the or operator here?

You'll have to ask whoever published the package with that range

**Comment by rpivo** [comment]
@merceyz so the range is between "greater than 3.0.0" and "greater than 4.0.0"?

**Comment by merceyz** [comment]
Correct
