### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\""

### ISSUE THREAD

**Issue by Bluesbutterfly** [yarnpkg/yarn#7483]
I updated the version of node and yarn. There will be some errors in the installation and the source cannot be found. The version of node is 11.11.0, and the version of yarn is 1.17.3. How to solve it!

`F:\myitems>yarn create umi
yarn create v1.17.3
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Lenovo\\AppData\\Local\\Yarn\\Data\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.`

**Comment by JaosnHsieh** [comment]
duplicated #6935

**Comment by zifeo** [comment]
https://github.com/eclipse/che/issues/12077#issuecomment-443503700 solves this issue due to https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident
