### ISSUE TITLE
Requesting option to skip rebuilding

### ISSUE THREAD

**Issue by mitra42** [yarnpkg/yarn#7484]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently `yarn upgrade` cases packages to rebuild every time. In #932 @rally25rs says this is intentional (I'm not sure why they are rebuilt if the package hasn't changed, but I'm assuming there is a good reason for this).

The problem is that our packages are intended to run on really small machines (e.g. Orange Pi Zero running Armbian). (In case you are interested its to allow offline versions of parts of the Internet Archive, e.g. for schools), the packages are being updated frequently so we'd like people to run a 'yarn upgrade' to get the latest versions but that can take as long as an hour to rebuild even if a 2nd upgrade is run immediately, i.e. if nothing has changed. 

**If the current behavior is a bug, please provide the steps to reproduce.**
```
cd ~/tmp
yarn add @internetarchive/dweb-mirror @internetarchive/dweb-archive
yarn upgrade # Slow
yarn upgrade # Equally slow
```
**What is the expected behavior?**
What I'd love is an option or config value that told it to skip rebuilds on packages that haven't changed their version number. 

**Please mention your node.js, yarn and operating system version.**
node v10.15.2
yarn 1.17.3
Linux orangepizero 4.19.62-sunxi #5.92 SMP Wed Jul 31 22:07:23 CEST 2019 armv7l GNU/Linux
But note I see this on all OS's I've tested - Raspbian, OSX, Armbian.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the tracking of what needs to be rebuilt has been greatly improved

https://yarnpkg.com/getting-started/migration
