### ISSUE TITLE
Yarn's offline cache doesn't respect --production

### ISSUE THREAD

**Issue by jim-moody** [yarnpkg/yarn#7487]
**What is the current behavior?**
Running `yarn --production` in offline mode adds devDependencies to the offline cache. This is bad because when we run the command in CI and then upload our app zip, it is much bigger than it needs to be.

**What is the expected behavior?**
`yarn install --production` should not add devDependencies to the offline cache

**Please mention your node.js, yarn and operating system version.**
N/A

**.yarnrc**
```
yarn-offline-mirror "./npm-packages-offline-cache"
yarn-offline-mirror-pruning true
```

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Comment by Muritavo** [comment]
What about version 1? Another problem with this approach is that the packages that need to be built before usage (using npm scripts prepare for example) will be installed, taking up space and delaying the build
