### ISSUE TITLE
All IP's behing https://yarnpkg.org

### ISSUE THREAD

**Issue by kvijay460** [yarnpkg/yarn#7501]
**Yarn version: 1.13.0**

Can we get the list of all IP's behind https://registry.yarnpkg.com
When we run the `yarn install` it tries to connect to different IP's. If we have a designated list of IP's we can whitelist them in our project.
Let us know if the IP's changes periodically.

**Comment by arcanis** [comment]
We can't, because those IP belong to npm. We don't control them.

**Comment by ahmadnassri** [comment]
FYI for the purposes for bypassing corporate proxies / creating allowlists, you can use the following IP ranges: https://www.cloudflare.com/ips/

**Comment by merceyz** [comment]
Closing as `registry.yarnpkg.com` is just a CNAME to npm so you'll have to ask them

https://yarnpkg.com/getting-started/qa/#why-registryyarnpkgcom-does-facebook-track-us
