### ISSUE TITLE
Support installing with Homebrew

### ISSUE THREAD

**Issue by MattiSG** [yarnpkg/yarn#751]
Hi,

I wanted to create a [brew](https://brew.sh) formula for Yarn.

However, I couldn't find a way to access versioned artifacts (i.e. `yarn-0.15.0.tar.gz`), only `latest.tar.gz`. This prevents specifying expected versions and checksums, effectively preventing any kind of package management (haha) for the executable.

Could you please provide us with versioned artifacts, so it is possible to install any published version without relying on a compromisable shell script?  :)

Cheers,
Matti

**Comment by Daniel15** [comment]
> However, I couldn't find a way to access versioned artifacts

You can use `https://yarnpkg.com/downloads/0.15.0/yarn-v0.15.0.tar.gz`. This is exactly how the Windows Chocolatey package works for example: https://github.com/yarnpkg/yarn/blob/master/resources/win-chocolatey/tools/chocolateyinstall.ps1.in#L11

Also, @kittens started working on a Homebrew package in #418. I don't know a lot about Homebrew, but maybe you could use something in there.

**Comment by MattiSG** [comment]
Thanks for the pointer!

#418 has been closed, but it pointed to using `https://github.com/yarnpkg/homebrew-yarn` as a tap, which means you would have maintained your own formulæ there.

That could make sense. Please let me know if you prefer to maintain your own tap rather than being merged into the main homebrew repo.

**Comment by Daniel15** [comment]
Yeah, #418 was closed since we couldn't get it finished before the public release, but I *think* the idea was to have our own formula so we can update it immediately when a new version of Yarn is available rather than having to merge it into the Homebrew repo. This is how HHVM does it: https://github.com/hhvm/homebrew-hhvm. 

Most of the other people on the Yarn project are on Mac OS (I tend to be the only Windows user on various Facebook-related projects 😛  )so it's probably worth waiting for their input too, as they'd be more familiar with Homebrew.

**Comment by thejameskyle** [comment]
There is now a formulae for Yarn on homebrew https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb

**Comment by nicolas-dular** [comment]
Thanks for creating this brew formula, really appreciate it!

However, I've installed it now via brew but it doesn't work. Getting 
` NODE_ENV=development webpack-dev-server --config config/webpack.development.js --progress: No such file or directory` in our project when `yarn` is installed via brew (on both of my macs, sierra), but everything works when installed via `curl`. 

Anyone else is getting similar issues? Sorry, have no good idea to reproduce

**Comment by AriaFallah** [comment]
@Daniel15 

Is it possible that you could remove the

```ruby
depends_on "node"
```

in the homebrew formula? It forces you to install node even if you already have it through some other means, for example https://github.com/tj/n.
