### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by nicuvlad7** [yarnpkg/yarn#7525]
**Which operating system are you using:**
Ubuntu 18

**Please describe the steps you took when trying to install Yarn and what went wrong:**

i've been following the steps that are listed in the office site and when i run the command  for the installation 

> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

> sudo apt-get update && sudo apt-get install yarn

i get a response that the cmdtest will be installed instead of yarn ....

> Hit:1 http://ro.archive.ubuntu.com/ubuntu bionic InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                             
Hit:3 http://ro.archive.ubuntu.com/ubuntu bionic-updates InRelease                       
Hit:4 https://deb.nodesource.com/node_8.x bionic InRelease                               
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                        
Hit:6 http://ro.archive.ubuntu.com/ubuntu bionic-backports InRelease                     
Hit:7 https://repo.skype.com/deb stable InRelease                                        
Hit:8 http://dl.google.com/linux/chrome/deb stable Release                               
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'cmdtest' instead of 'yarn'
The following NEW packages will be installed:
  cmdtest
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/21,1 kB of archives.
After this operation, 98,3 kB of additional disk space will be used.
Selecting previously unselected package cmdtest.
(Reading database ... 175172 files and directories currently installed.)
Preparing to unpack .../cmdtest_0.32-1_all.deb ...
Unpacking cmdtest (0.32-1) ...
Setting up cmdtest (0.32-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

**Comment by olingern** [comment]
Hi @nicuvlad7! Were you able to get this installed? 

Going to close this for now, but if you're still having problems please comment with steps to reproduce.

**Comment by tatsujb** [comment]
this still happens
