### ISSUE TITLE
Avoid os.networkInterfaces on Windows Subsystem for Linux (Bash on Windows)

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#753]
`os.networkInterfaces` fails on WSL (Windows Subsystem for Linux). We call that at https://github.com/yarnpkg/yarn/blob/master/src/util/network.js#L9 to determine if the user is online, based on whether they have a non-localhost IP address.  If running under WSL, we should either use an API that works in that environment, or just always assume that the user is online.

See #636 for a prior discussion.

**Comment by Daniel15** [comment]
Fixed in #772, thank you @mogest!

**Comment by bb1** [comment]
Well this doesn't work anymore with the current WSL version.
