### ISSUE TITLE
Ok, now fixed

### ISSUE THREAD

**Issue by bschatz12** [yarnpkg/yarn#7538]
Ok, now fixed

_Originally posted by @bestander in https://github.com/yarnpkg/yarn/issues/394#issuecomment-298019781_

**Comment by bschatz12** [comment]
Please reopen this. Not resolved. We are sending a package down to PCF from a Jenkins build server. We modify the yarn.lock file to point to the offline-cache location on the URL. yarn still tries to run in online mode when PCF does a rebuild - which it always will do. I don't see any way to instruct yarn to run in offline mode during this rebuild. I tried passing down --install.offline true as a line in the .yarnrc file sent down to PCF, but it has no effect. Help!

**Comment by nickbreen** [comment]
We seem to be having the same issue with v1.22.1.

Following the blog's instruction https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/ does not work.

Specifically `yarn install --offline` with a clean cache fails with errors like this:

```
stderr: error Can't make a request in offline mode ("https://registry.yarnpkg.com/jquery/-/jquery-2.2.4.tgz")
```

**Comment by nickbreen** [comment]
```bash
offline_mirror=$(yarn config get yarn-offline-mirror)
sed -i "s!https://.*/-/npm-!file://${offline-mirror}!" yarn.lock
```
