### ISSUE TITLE
pnpify on Windows launches default app associated with .js

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/yarn#7541]
I'm trying to run
`yarn pnpify tsc`
with yarn 1.17.3 - but that may not matter, probably.

For me this command starts an editor with the file cli.js. This is exactly what pnpify.cmd contains:

```
@"%~dp0\..\lib\cli.js"   %*
```

As you can see, node is never called :-(

**To Reproduce**

Well, empty folder, create package.json, `yarn add @yarnpkg/pnpify`, `yarn pnpify tsc`.

 - OS: [e.g. OSX, Linux, Windows, ...] Windows
 - Node version [e.g. 8.15.0, 10.15.1, ...] 10
 - Yarn version [e.g. 2.0.0-rc1, ...] 1.17.3

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
