### ISSUE TITLE
Infinite recursion for `link:.` entry in package.json

### ISSUE THREAD

**Issue by defunctzombie** [yarnpkg/yarn#7547]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The following package.json

```
{
    "name": "example",
    "version": "0.0.0",
    "dependencies": {
        "example": "link:."
    }
}
```

Produces a heap memory overflow in v8 - possibly due to infinite recursion.

**What is the expected behavior?**

The expected behavior is a link back to ourselves in our `node_modules` folder.

The use case here is to use requires relative to the project root rather than relative paths:

```js
require('example/some/path');
// vs
require('../../../some/path');
```

**Please mention your node.js, yarn and operating system version.**

node v12.10.0, yarn 1.17.3.

This works on yarn 1.3.2 but stops working as of yarn 1.4.0.

**Comment by arcanis** [comment]
This should be fixed on master (nightly builds)

**Comment by defunctzombie** [comment]
@arcanis Thanks - should have checked the obvious commit history first :)
