### ISSUE TITLE
flexibility to use different name for package folder and `package.json` name property

### ISSUE THREAD

**Issue by kushalmahajan** [yarnpkg/yarn#7549]
I have three packages say `components, mobile, web`. 

**root `package.json`**

```
{
    "private": true,
    "workspaces": [
        "packages/*"
    ]
}
```

**web/package.json**

```
"name": "@org/package-name"
"workspaces": [
        "packages/*"
  ],
```

Now on running `yarn workspace web start` throws an error 

> Unknown workspace "web".

This clearly means both my folder name and package.json property `name` has to be the same.  This can't work because too publish packages under organisation I've to specify `@`. So can't rename the folder to that package name.  

Any workaround or option to do the same?  It sure isn't mentioned in docs.

**Comment by kushalmahajan** [comment]
command to run is `yarn workspace @org/web` instead of the only web. Turns out yarn picks from package name and not folder name

**Comment by nikolasburk** [comment]
Thanks, this just saved me a ton of time!

**Comment by leonheess** [comment]
I wish I could also use the folder name. The package name is super long at times

**Comment by jaywick** [comment]
I got around this by adding using scripts in the root pacakge.json, it's manual but more ergonomic

```json
"components": "yarn workspace @example/long-package-name-components",
"mobile": "yarn workspace @example/long-package-name-mobile",
"web": "yarn workspace @example/long-package-name-web",
```

So

```sh
yarn workspace @example/long-package-name-components your:script --args
```

would become

```sh
yarn components your:script --args
```

**Comment by leonheess** [comment]
@jaywick you might be the last person on earth that still uses yarn
