### ISSUE TITLE
package binaries no longer reachable when using pnp combined with workspaces

### ISSUE THREAD

**Issue by jdivock** [yarnpkg/yarn#7551]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
package binaries no longer work when a project is workspaced

**If the current behavior is a bug, please provide the steps to reproduce.**

Reprod by taking the pnp-sample-app and making it a workspace at which point webpack/gulp/etc are no longer found

- Pull https://github.com/jdivock/pnp-workspace-sample-app
- `cd pnp-sample-app`
- `yarn`
- `yarn webpack`

```
pnp-workspace-app/pnp-sample-app git/master  9s
❯ yarn webpack
yarn run v1.17.3
warning package.json: No license field
$ webpack
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The main project I'm working on that uses workspaces has a different failure wherein it finds webpack, but not the CLI

```
 git/jdivock/yarn-pnp*  18s
❯ yarn webpack
yarn run v1.17.3
$ webpack
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
✨  Done in 1.63s.
```

**What is the expected behavior?**
should successfully find and run webpack

**Please mention your node.js, yarn and operating system version.**
node 10.16.0
yarn 1.17.3
OSX 10.14.6

**Comment by hlian** [comment]
Can reproduce:

- maCOS 10.14.6
- yarn 2.0.0-rc12
- node v12.12

**Comment by russell-dot-js** [comment]
Same issue, reproducing on ubuntu 19.10 with yarn 1.19.0

**Comment by paul-soporan** [comment]
Closing as fixed in the v2 where PnP support is also much more stable.

https://yarnpkg.com/getting-started/migration
