### ISSUE TITLE
Yarn publish fails to include yarn.lock file

### ISSUE THREAD

**Issue by ketsthechanger** [yarnpkg/yarn#7555]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
yarn publish does not add yarn.lock file in the tarball.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. do yarn install on the project directory
2. Run "yarn publish".
3. Check the tarball created. It does not have yarn.lock file.

**What is the expected behavior?**
tarball generated after yarn publish should have yarn.lock file

**Please mention your node.js, yarn and operating system version.**
yarn: 1.17.3
npm: 6.9
OS: Linux
node: 10.15

**Comment by merceyz** [comment]
It's always ignored and even if it was included Yarn would not use it, you'll need to change its name by making a copy in `prepack` if you really want it to be included
