### ISSUE TITLE
Invalid warning when `pnpm` is used as an engine field

### ISSUE THREAD

**Issue by clydin** [yarnpkg/yarn#7560]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Adding a package which has `pnpm` listed as an engine in its `package.json` results in a warning: `The engine "pnpm" appears to be invalid.`

**If the current behavior is a bug, please provide the steps to reproduce.**
Add a package which lists `pnpm` as an engine in its `package.json`.

**What is the expected behavior?**
No warning should be shown.

The `pnpm` value should be ignored as is `npm` here: https://github.com/yarnpkg/yarn/blob/master/src/package-compatibility.js#L50

**Please mention your node.js, yarn and operating system version.**
Node.js: 10.10.0
yarn: 1.17.3
OS: macOS 10.14.6

**Comment by 9034725985** [comment]
On Ubuntu as well 

```
$ time yarn global add @angular/cli@9.0.0-next.5
yarn global v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning @angular/cli@9.0.0-next.5: The engine "pnpm" appears to be invalid.
warning @angular-devkit/architect@0.900.0-next.5: The engine "pnpm" appears to be invalid.
warning @angular-devkit/core@9.0.0-next.5: The engine "pnpm" appears to be invalid.
warning @angular-devkit/schematics@9.0.0-next.5: The engine "pnpm" appears to be invalid.
warning @schematics/angular@9.0.0-next.5: The engine "pnpm" appears to be invalid.
warning @schematics/update@0.900.0-next.5: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@angular/cli@9.0.0-next.5" with binaries:
      - ng
Done in 1.94s.

real    0m2.191s
user    0m2.641s
sys     0m0.681s
```

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where we don't warn on invalid engines anymore.

https://yarnpkg.com/getting-started/migration

**Comment by strarsis** [comment]
@paul-soporan: Is `yarn` `v2` release scheduled for the near future?
I get this warning and the latest available stable `yarn` is `1.22.17`.

**Comment by merceyz** [comment]
> Is yarn v2 release scheduled for the near future?

It was released a few years ago, 2020-01-24

**Comment by strarsis** [comment]
@merceyz: But why do I have `yarn` `1.x` installed when I simply install it via `npm`? Or is `yarn` `v2` not installable by `npm`? I surely miss something.

**Comment by merceyz** [comment]
Read the migration guide that @paul-soporan linked to in https://github.com/yarnpkg/yarn/issues/7560#issuecomment-753609744

**Comment by Vkrmdabgotra** [comment]
we have resolved this issue in the yarn environment. 
firstly we created .yarnrc file in our project folder and then wrote inside this
"ignore-engines pnpm"
please check the attachment below, I hope this solution will fix your problem.
![Screenshot 2024-08-24 103458](https://github.com/user-attachments/assets/6628f741-db4e-4b24-a5b7-391ce5c1527b)
