### ISSUE TITLE
yarn add takes too much time

### ISSUE THREAD

**Issue by tusharkhatiwada** [yarnpkg/yarn#7564]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn add` any package takes too much time

<img width="1124" alt="Screen Shot 2019-09-20 at 1 46 45 PM" src="https://user-images.githubusercontent.com/5126590/65310044-1d5d7500-dbad-11e9-9eb0-43b892761cc3.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
simply adding a new package using `yarn add` takes around 4 minutes to complete.

**Please mention your node.js, yarn and operating system version.**
node: v10.13.0
yarn: 1.17.3
OS: macos 10.14.6

**Comment by trollepierre** [comment]
Same issues here, but it takes much more time....

**Comment by Anbarasi1** [comment]
I am having similar issue, but time is more 
Win 10
node : V10.17.0
yarn: 1.17.3

Done in 1625.84s.
Is there any resolution to fix this

**Comment by merceyz** [comment]
Closing as fixed in v2 where the linker is faster, and if that isn't fast enough, by using PnP

https://yarnpkg.com/getting-started/migration
