### ISSUE TITLE
Yarn PnP depedency requires .bin and can't find it

### ISSUE THREAD

**Issue by NicolaiSchmid** [yarnpkg/yarn#7567]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In my Yarn PnP enabled project I use a depedency in an NPM script, which itself, depends on prettier. The depedency tries to execute prettier from .bin/prettier and fails, since yarn pnp doesn't install prettier into that directory. 
**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/NicolaiSchmid/yarn-pnp-bin

**What is the expected behavior?**
I'm not sure if the depedency is suppose to expect the binary in `.bin/` or not, but so far, with NPM or the regular yarn configuration this worked fine. 
**Please mention your node.js, yarn and operating system version.**
```
 ⭠ yarn ⮀ master ⮀ ✈ ⮀  yarn -v
1.17.3

 ⭠ yarn ⮀ master ⮀ ✈ ⮀  node -v
v12.1.0

 ⭠ yarn ⮀ master ⮀ ✈ ⮀  lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.1.0
Codename:	Juhraya
```

**Comment by arcanis** [comment]
Note that PnP projects are encouraged to use the [v2](https://next.yarnpkg.com/getting-started), as that's where most of the development happens going forward. This particular bug is solved there, for example 😃

**Comment by NicolaiSchmid** [comment]
Thanks for the info!
