### ISSUE TITLE
Yarn workspace packages use a root 'version-tag-prefix'

### ISSUE THREAD

**Issue by michaelkclements** [yarnpkg/yarn#7576]
**What is the current behavior?**
Attempting to set different `yarn config set version-tag-prefix` per workspace in order to have unique tags on Github.
Currently it sets it to all workspaces even when a workspace was specified setting it. E.g. `yarn workspace docs config set version-tag-prefix "docs@"`

**If the current behavior is a bug, please provide the steps to reproduce.**
- Have multiple workspaces (a and b)
- Set a tag prefix `yarn workspace a config set version-tag-prefix "a@"`
- Then set a tag prefix for the b workspace `yarn workspace b config set version-tag-prefix "b@"`
- Then going back to the A workspace and upgrading version will set it as the B prefix.

**What is the expected behavior?**
Each workspace should be able to have a unique tag prefix.

**Please mention your node.js, yarn and operating system version.**
Node: 10.16.0
Yarn: 1.17.3
OS: macOS Mojave 10.14.6

**Comment by ppedziwiatr** [comment]
After all those years - it still doesn't seem to work properly.
My dumb workaround for this is to add sth like
`cd .. && yarn workspace warp-contracts-plugin-evaluation-progress config set version-tag-prefix "evaluation-progress@"`
to the plugin's `prepublishOnly`...
