### ISSUE TITLE
Yarn not working

### ISSUE THREAD

**Issue by AmenoCoyane** [yarnpkg/yarn#7580]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Yarn is not working after I installed it, whenever I try to run a yarn command it says command not found(I am using gitbash and have node installed)

**If the current behavior is a bug, please provide the steps to reproduce.**

Install yarn windows stable version then try to run yarn in gitbash

**What is the expected behavior?**
to work?

**Please mention your node.js, yarn and operating system version.**
node version: v10.16.3 yarn version: 1.17.3 I don't know what you mean by OS version

**Comment by loujaybee** [comment]
Can you paste the command you're trying to access and the corresponding output?

**Comment by olingern** [comment]
Is this still an issue? If so, please comment and happy to reopen. 

Also, please add reproductions steps!
