### ISSUE TITLE
yarn install on vue project is hitting timeout issue

### ISSUE THREAD

**Issue by mahanteshk** [yarnpkg/yarn#7581]
On running yarn install on a project I am getting the error.

yarn-error.log trace below

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js install

PATH: 
  D:\Tools\VueJs\cmder\bin;D:\Tools\VueJs\cmder\vendor\git-for-windows\cmd;D:\Tools\VueJs\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\Tools\VueJs\cmder\vendor\conemu-maximus5;D:\Tools\VueJs\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\cmder\cmder\bin;D:\cmder\cmder\vendor\git-for-windows\cmd;D:\cmder\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\cmder\cmder\vendor\conemu-maximus5;D:\cmder\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Users\Administrator\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL S;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\Tools\VueJs\cmder\vendor\git-for-windows\cmd;D:\Tools\VueJs\cmder\vendor\git-for-windows\mingw64;D:\Tools\VueJs\cmder\vendor\git-for-windows\usr\bin;D:\Tools\VueJs\cmder

Yarn version: 
  1.16.0

Node version: 
  10.16.1

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/npm/-/npm-6.11.3.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:130217:19)
      at Object.onceWrapper (events.js:286:20)
      at ClientRequest.emit (events.js:198:13)
      at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
      at Object.onceWrapper (events.js:286:20)
      at TLSSocket.emit (events.js:198:13)
      at TLSSocket.Socket._onTimeout (net.js:442:8)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)

npm manifest: 
  {
    "name": "tut_vue_proj_1",
    "version": "0.1.0",
    "private": true,
    "scripts": {
      "serve": "vue-cli-service serve",
      "build": "vue-cli-service build",
      "lint": "vue-cli-service lint",
      "test:unit": "vue-cli-service test:unit",
      "test:e2e": "vue-cli-service test:e2e"
    },
    "dependencies": {
      "@progress/kendo-data-query": "^1.5.1",
      "@progress/kendo-datasource-vue-wrapper": "^2018.2.620",
      "@progress/kendo-dropdowns-vue-wrapper": "^2018.2.620",
      "@progress/kendo-editor-vue-wrapper": "^2018.3.1025",
      "@progress/kendo-grid-vue-wrapper": "^2018.2.620",
      "@progress/kendo-theme-default": "^2.54.1",
      "@progress/kendo-treelist-vue-wrapper": "^2018.3.911",
      "@progress/kendo-ui": "^2018.2.806",
      "@progress/kendo-upload-vue-wrapper": "^2018.3.911",
      "@progress/kendo-validator-vue-wrapper": "^2018.3.1025",
      "@progress/kendo-vue-animation": "^0.3.0",
      "@progress/kendo-vue-grid": "^0.3.0",
      "@progress/kendo-vue-intl": "^0.3.0",
      "@progress/kendo-vue-popup": "^0.3.0",
      "auto-exports": "^0.3.12",
      "axios": "^0.18.0",
      "bootstrap-vue": "^2.0.0-rc.11",
      "crypto-js": "^3.1.9-1",
      "file-loader": "^2.0.0",
      "install": "^0.12.1",
      "jsonwebtoken": "^8.3.0",
      "jszip": "^3.1.5",
      "lodash": "^4.17.11",
      "npm": "^6.4.1",
      "register-service-worker": "^1.0.0",
      "v-tooltip": "^2.0.0-rc.33",
      "vee-validate": "^2.1.0-beta.6",
      "vue-avatar": "^2.1.6",
      "vue-bootstrap-toggle": "^1.1.4",
      "vue-class-component": "^7.0.2",
      "vue-cookies": "^1.5.6",
      "vue-croppie": "^1.3.12",
      "vue-form-generator": "^2.2.2",
      "vue-jquery": "^1.0.6",
      "vue-localstorage": "^0.6.2",
      "vue-router": "^3.0.1",
      "vuex": "^3.0.1",
      "webpack": "^4.29.5",
      "font-awesome": "^4.7.0"
    },
    "devDependencies": {
      "@vue/cli-plugin-babel": "^3.0.0-beta.15",
      "@vue/cli-plugin-e2e-cypress": "^3.0.0-beta.15",
      "@vue/cli-plugin-pwa": "^3.0.0-beta.15",
      "@vue/cli-plugin-unit-jest": "^3.0.0-beta.15",
      "@vue/cli-service": "^3.3",
      "@vue/test-utils": "^1.0.0-beta.16",
      "babel-core": "7.0.0-bridge.0",
      "babel-jest": "^22.4.3",
      "babel-plugin-transform-object-rest-spread": "^6.26.0",
      "babel-polyfill": "^6.26.0",
      "cross-env": "^5.2.0",
      "node-sass": "^4.9.0",
      "sass-loader": "^7.0.1",
      "url-loader": "^1.1.2",
      "vue-close": "^0.1.0",
      "vue-template-compiler": "^2.5.16"
    },
    "browserslist": [
      "> 1%",
      "last 2 versions",
      "not ie <= 8"
    ]
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
