### ISSUE TITLE
`yarn workspace <workspace> add <package>` adds `yarn.lock` and `node_modules` to workspace

### ISSUE THREAD

**Issue by mrmckeb** [yarnpkg/yarn#7583]
**Do you want to request a *feature* or report a *bug*?**

Bug, but correct me if I'm wrong.

**What is the current behavior?**

When running `yarn workspace <workspace> add <package>`, I end up with a `yarn.lock` and `node_modules` in that workspace.

If I simply add a dependency by hand to the `package.json` of that workspace, then run yarn in root, everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

As above, simply running `yarn workspace <workspace> add <package>`.

**What is the expected behavior?**

`yarn workspace <workspace> add <package>` should install the module to the root `node_modules` folder, and update the root `yarn.lock`.

Only `package.json` should be updated in the workspace directory.

**Please mention your node.js, yarn and operating system version.**
Yarn: 1.17.3
Node: 12.10.0
MacOS: 10.14.6 (18G95)

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where workspace support is much better.

https://yarnpkg.com/getting-started/migration
