### ISSUE TITLE
Respect project .yarnrc registry config over .npmrc

### ISSUE THREAD

**Issue by vivaxy** [yarnpkg/yarn#7585]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**

To tell wether a developer is using `npm` or `yarn` to install packages.

In ~/

```
.npmrc      ## registry="global-npm-registry"
.yarnrc     ## registry="global-yarn-registry"
```

In project:

```
.npmrc      ## registry="some-npm-registry"
.yarnrc     ## registry "some-yarn-registry"
```

Both `npm i some-package` and `yarn add some-package` uses `some-npm-registry`.

**What is the expected behavior?**

`npm i` uses `some-npm-registry` and `yarn add` uses `some-yarn-registry`.

**Comment by merceyz** [comment]
Fixed in v2 where it only reads configs from `.yarnrc.yml`

https://yarnpkg.com/getting-started/migration
