### ISSUE TITLE
Installation Problem: [yarn --version]

### ISSUE THREAD

**Issue by Kingars** [yarnpkg/yarn#7587]
Windows 10

Friends good night.

I tried to install yarn from windows using chocolatey, and got this message at the end of the installation:

> "Only an exit code of non-zero will fail the package by default. Set
>  `--failonstderr` if you want error messages to also fail a script. See
>  `choco -h` for details.
>  The install of yarn was successful.
>   Software installed as 'msi', install location is likely default."

However, when testing to see your version, I get the following messages:

> PS C:\WINDOWS\system32> yarn --version
> yarn : O termo 'yarn' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique
> a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
> No linha:1 caractere:1
> + yarn --version
> + ~~~~
>     + CategoryInfo          : ObjectNotFound: (yarn:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

The same happens if I put:

yarn -v

Thanks!

**Comment by ShivamRawat0l** [comment]
Remove yarn using chochlaty 
Install using npm install -g yarn 
Try using yarn -v

**Comment by knoxcard** [comment]
close ticket?

**Comment by Kingars** [comment]
Issue resolved guys!

Thanks!


[image: Kingars.Com.BR]
ALEX RODRIGUES

DESENVOLVEDOR/ANALISTA | Kingars.Com.BR
MÓVEL:  +55(71)99709-2110
SKYPE:  kingars
E-MAIL:  kingars@gmail.com
kingars.com.br
<https://www.linkedin.com/in/kingars/> <https://www.twitter.com/kingars>
<https://www.facebook.com/kingars> <https://www.linkedin.com/in/kingars/>


Em qua, 2 de out de 2019 às 17:03, Indospace.io <notifications@github.com>
escreveu:

**Comment by knoxcard** [comment]
@Kingars - please close this ticket by clicking the button below.

**Comment by briangonc** [comment]
Quem estiver com dificuldades com yarn ... utilize esse comando no Terminal.

npm install --global yarn

**Comment by psiqe** [comment]
nem o npm está funcionando aqui; não entendo o que ta pegando :S
