### ISSUE TITLE
Yarn install fails on scoped dependency with `bin` attr in package.json

### ISSUE THREAD

**Issue by roblg** [yarnpkg/yarn#759]
**Do you want to request a _feature_ or report a _bug_?**

Bug.

**What is the current behavior?**

If a project has a scoped dependency in package.json, and that dependency has a `bin` attr, the install fails with the following message:

```
yarn install v0.15.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error ENOENT: no such file or directory, symlink '../../@redfin/codecov/cli.js' -> '/tmp/yarn-temp/node_modules/.bin/@redfin/codecov'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The `../..` seems suspect, because the package is actually three directories under node_modules due to the scope in this case.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

Install should succeed, script should be symlinked in `node_modules/.bin`

**Please mention your node.js, yarn and operating system version.**

OSX 10.10 and recent ish (not sure exactly what) Ubuntu.
node 6, npm 3.10.x

**Comment by Kovensky** [comment]
The linking seems to treat `@scope/package` as the package name, instead of a scope/name pair. It's trying to create a symlink named `@redfin/codecov` (but there is no `@redfin` directory inside `.bin`), and the extra `../` in the symlink target is to go up from the (incorrect) extra `@redfin` dir inside `.bin`.

The correct link should be (the equivalent of) `ln -s "../@redfin/codecov/cli.js" "node_modules/.bin/codecov"`.

**Comment by kasperlewau** [comment]
I belive I'm facing the same issue; 

```
yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error ENOENT: no such file or directory, symlink '../../../../frontend-optim/bin/cli.js' -> '/Users/kasperlewau/code/falcon/html/node_modules/@falconio/gulp-frontend-optim/node_modules/.bin/@falconio/frontend-optim'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The _rough shape_ of the package that I believe is the failing one: 

```json
{
  "name": "@falconio/frontend-optim",
  "main": "index.js",
  "bin": "./bin/cli.js"
}
```

```sh
frontend-optim/
├── README.md
├── bin
│   └── cli.js
├── index.js
├── lib
│   └── optim.js
└── package.json
```

`index` requires `./lib/optim` and `cli` requires `../{implicit_index.js}`. Barring those, it's all external dependencies from here on out. 

--- 

And the `package.json` of the package depending on the above; 

```json
{
  "name": "@falconio/gulp-frontend-optim",
  "dependencies": {
    "@falconio/frontend-optim": "3.0.0"
  }
}
```

---

Environment details: 

* yarn@0.5.11
* npm@3.10.3
* node@6.6.0
* OSX@10.11.2 (El Capitan)

**Comment by arcanis** [comment]
Last releases shouldn't be affected, please reopen if it's still an issue
