### ISSUE TITLE
yarn init doesn't use "init-version" from npmrc (not yarnrc)

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/yarn#7593]
**What is the current behavior?**

I have an npmrc with init-author-name, ..., init-version and init-license.

`npm init -y` makes use of these. `yarn init`, otoh, uses init-author-* from npmrc, but not init-version and init-license.

To me it seems like this is related to src\registries\yarn-registry.js:
```
export const DEFAULTS = {
...
  'init-version': '1.0.0',
  'init-license': 'MIT',
...
};
```

**What is the expected behavior?**

Should not override init-version & init-license from npmrc.

(node 10, yarn 1.19, Windows 10)

**Comment by texastoland** [comment]
Bump: same inconsistent behavior 🛎

**Comment by paul-soporan** [comment]
Closing as starting from v2 we don't even read `.npmrc` files anymore (only `.yarnrc.yml` files).

https://yarnpkg.com/getting-started/migration
