### ISSUE TITLE
Introduce a flag to get package types as well as installing it

### ISSUE THREAD

**Issue by alex3165** [yarnpkg/yarn#7596]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
To install a package with types:

```
yarn add [package]
// Manually check if packge include types, if not:
yarn add @types/[package]
```

**What is the expected behavior?**
Add a flag like:
```
yarn add [package] -t [typescript|flow]
```
This could install the package, lookup for types definition within package if not there also install the types package.

**Comment by merceyz** [comment]
Closing as fixed in v2 with the typescript plugin https://github.com/yarnpkg/berry/tree/master/packages/plugin-typescript

https://yarnpkg.com/getting-started/migration
