### ISSUE TITLE
yarnrc file ignored when trying to add private package

### ISSUE THREAD

**Issue by HemalR** [yarnpkg/yarn#7597]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Yarn tries to install a package from npm when the package is not on there (it is on Github). Instructions on yarnrc are ignored. Installing the same package using npm (and npmrc) works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
Yarn steps that don't work
.yarnrc

```
registry "https://registry.npmjs.org"
"@hemalr:registry" "https://npm.pkg.github.com/hemalr"
```

Command: `yarn add @hemalr/react-blocks`

Error - `error Couldn't find package "@hemalr/react-blocks" on the "npm" registry.`

Equivalent steps on npm that works:

.npmrc
```
registry=https://registry.npmjs.org
@hemalr:registry=https://npm.pkg.github.com/hemalr
```

Command - `npm install @hemalr/react-blocks@1.1.0`

**What is the expected behavior?**
Yarn should install the package from the registry specified in .yarnrc

**Please mention your node.js, yarn and operating system version.**
OS - 10.14.6 - MacOS Mojave
Node - 12.11.0
Yarn - 1.19.0

Any guidance, or pointers to obvious things I am missing are very much appreciated. I've been trying to install a package for 8 hours now! 😆 (I'm secretly crying).

Thanks in advance!

**Comment by plus-** [comment]
I have the same exact issue with 1.19 and a registry on github packages

**Comment by plus-** [comment]
@HemalR are you also in the context of a create-react-app application?

**Comment by HemalR** [comment]
No in my case it’s a vanilla Gatsby application (new and unaltered from the
Gatsby starter template).

**Comment by plus-** [comment]
So I found a workaround in my case, 

I had a personal access token in the .npmrc for authentication to github packages, which I had to double it this way:

```
//npm.pkg.github.com/:_authToken=<TOKEN_VALUE>
//npm.pkg.github.com/<OWNER>/:_authToken=<TOKEN_VALUE>
```

Without the second line which matched the value for my scoped registry I would get the "couldn't find in the npm registry" error. Without the first one (the original one) I get a 401

Hope this helps

**Comment by HemalR** [comment]
@plus- 

Thanks for that, I'll test it out! (For now, for this new project I have already switched to NPM). I guess if your workaround is doing the trick, then the issue is that yarn is not outputting the correct error message (where it is an authentication error rather than looking in the wrong registry).

For reference, npm authenticates by looking at the system root .npmrc file which has the Github token to grant the system access to the repo in question.

**Comment by dominguezcelada** [comment]
Unfortunately, @plus- solution didn't work to me. But, found a very similar solutions which worked to me  posted in this issue: https://github.com/yarnpkg/yarn/issues/7552#issuecomment-538376858

Still a bit _hacky_ IMO but works to me 🤓

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where we've completely revamped the configuration (we now only read `.yarnrc.yml`) and such issues don't exist anymore.

https://yarnpkg.com/getting-started/migration
