### ISSUE TITLE
error "Couldn't find a package.json file" when run with --cwd parameter

### ISSUE THREAD

**Issue by simmdan** [yarnpkg/yarn#7601]
`yarn --version`
1.19.0
`npm --version`
6.11.3
OS is Windows 10

**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
If I run yarn from a directory that does not have a package.json file but pass the commandline argument `--cwd` with a path to a directory that does have a package.json, I get the message `error Couldn't find a package.json file in "c:\\"` where `c:\\` is my current directory.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
mkdir a
cd a
mkdir b
copy <valid-package.json> b
yarn --cwd b build
```

**What is the expected behavior?**
In earlier versions of yarn (at least in version 1.17.0), the `--cwd` argument would effectively cause yarn to switch to that directory before doing anything else.  So the command would succeed.

**Comment by Henk8207** [comment]
Think it is a bug

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
