### ISSUE TITLE
QUESTION: Update yarn from Git Bash on windows

### ISSUE THREAD

**Issue by Legends** [yarnpkg/yarn#7602]
I have Git Bash installed on my Win10.

When I execute:
`curl --compressed -o- -L https://yarnpkg.com/install.sh | bash`

but I get an error:

> Extracting to ~/.yarn...
> Adding to $PATH...
> Profile not found. Tried  (as defined in $PROFILE), ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile.
> Create one of them and run this script again
> Create it (touch ) and run this script again
   OR
> Append the following lines to the correct file yourself:

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

**What do I have to do to make it work on windows?**

**Comment by olingern** [comment]
Is this still an issue? If so, please comment and happy to reopen. 

Also, please add reproductions steps!

**Comment by asalwaysimani** [comment]
I have the same problem also on windows. 

What is even more confusing is I had npm and nvm installed on my computer and at some point, I'm not sure when it disappeared making this even more upsetting.
