### ISSUE TITLE
Passing ENV variables to run script 

### ISSUE THREAD

**Issue by valoricDe** [yarnpkg/yarn#7608]
Do you want to request a *feature* or report a *bug*?
feature

What is the current behavior?
Currently there is no possibility to pass env variables to the called script from yarn run
NODE_OPTIONS particularly, is used by yarn.js and also when the script is using node resulting in multiple problems.

What is the expected behavior?
Have a way to pass env variables only to called script.
For example have anything starting with YARN_PROCESS_ENV_ passend on to the process.
Or introducing `yarn run --inspect` to pass `NODE_OPTIONS='--inspect'` only to the process

Please mention your node.js, yarn and operating system version.
OS: OSX 10.13.4
Node: 8.12.0
Yarn: 1.9.4

Linked issue: https://github.com/yarnpkg/yarn/issues/6641

**Comment by merceyz** [comment]
`yarn run --inspect` has been implemented in v2 - https://yarnpkg.com/cli/run#options

https://yarnpkg.com/getting-started/migration

**Comment by 80avin** [comment]
Issue is not resolved completely, as the solutions is only provided for `--inspect` flag and not all `NODE_OPTIONS`

npm has a `--node-options` argument for this purpose as described [here](https://docs.npmjs.com/cli/v7/using-npm/config#node-options)
It would be better if yarn supports the same.

**Comment by meglio** [comment]
Has this been solved yet?
