### ISSUE TITLE
Yarn installs dependencies of failed optionalDependencies

### ISSUE THREAD

**Issue by jchip** [yarnpkg/yarn#7609]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Take this package.json:

```
{
  "name": "xy",
  "optionalDependencies": {
    "@jchip/opt-fail": "^1.0.0"
  }
}
```

Yarn installs everything `@jchip/opt-fail` depends except `@jchip/opt-fail` itself.

**What is the expected behavior?**

Yarn should install nothing to `node_modules`

EDIT: Yarn shouldn't even bother checking `@jchip/opt-fail`'s dependencies because its `preinstall` script failed.

**Please mention your node.js, yarn and operating system version.**

node.js 10.16.3, yarn 1.19.0

```
Darwin m-c02yw1s0lvdt 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

**Comment by merceyz** [comment]
Everything needs to be installed before that `preinstall` script can run so this is working as intended

**Comment by jchip** [comment]
thanks for looking into this.

that's not how npm behaves.

**Comment by merceyz** [comment]
Ah, indeed `preinstall` is different, I was thinking of `postinstall`.
