### ISSUE TITLE
Yarn won't run packge scripts when offline-mirror points to a network resource which is not available

### ISSUE THREAD

**Issue by begin-again** [yarnpkg/yarn#7624]
**Do you want to request a *feature* or report a *bug*?**

This is a bug

**What is the current behavior?**
I have an offline cache which resides on a network drive behind my company vpn. This works great when I'm connected to the vpn. The problem is that when I'm not connected to the vpn, yarn refuses to run scripts.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add a `yarn-offline-mirror` to your `.yarnrc` that is on a network drive which is accessible. `yarn config set yarn-offline-mirror \\\\some\\network\drive`
1. Verify that one can run package scripts in any project
1. Disconnect from the network resource where the yarn-offline-mirror is pointing
1. Attempt to run a package script in that same project

**What is the expected behavior?**
I don't understand why yarn needs to do anything with the offline mirror just to run a package script. But if it must, then Yarn should at some point timeout when attempting to connect to its offline-mirror and fallback to some local default. Perhaps also report that the offline-mirror is not reachable.

**Please mention your node.js, yarn and operating system version.**
node: v8.11.1
OS: windows 10 
yarn: 1.19.1

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
