### ISSUE TITLE
`yarn upgrade package@tag` does not keep dist-tag

### ISSUE THREAD

**Issue by mistic100** [yarnpkg/yarn#7626]
**Do you want to request a *feature* or report a *bug*?**
Bug on yarn 1.19.1

**What is the current behavior?**

We are building our enterprise library with "continuous integration" style, which means each commit  on `dev` branch is published in Nexus under the version `0.0.0-SNAPSHOT.1234` (1234 is the Gitlab pipeline number) and under the dist-tag `BUILD-SNAPSHOT`.  
We also publish feature branches under version `0.0.0-feature.SNAPSHOT.1235` and tag `feature-SNAPSHOT`.  
This is pattern inspired by Maven, which is our primary artifact/dependencies manager.

In our apps, if we need the snapshot version of the library we put `BUILD-SNAPSHOT` or `feature-SNAPSHOT` in the package.

Now the problem arises when we need to update the said snapshot : if I run `yarn upgrade @sglk/common@BUILD-SNAPSHOT` it successfully installs the latest version of the dist-tag but it also modify the package.json with `^0.0.0-SNAPSHOT.1234`.  
This is problematic because the next upgrade will pick any version matching the caret, which can be from any feature branch, but I wanted to stay on `BUILD-SNAPSHOT` (aka `dev` branch).

**What is the expected behavior?**

When running `yarn upgrade` with dist-tag (eg `yarn upgrade @sglk/common@BUILD-SNAPSHOT`) the version written in the package.json should be said dist-tag to avoid confusion.

I don't think this can lead to any unwanted side-effect because the version is locked anyway in the yarn.lock file.

-----

NB : snapshot updates are done by a semi-automatic process managed by Maven so I cannot use the `--exact` flag because I will lost the dist-tag name and further upgrades won't work.

**Comment by Otobelikethee** [comment]
#4632

**Comment by paul-soporan** [comment]
Closing as this has been fixed in the v2, dist-tags will now be kept as is.

https://yarnpkg.com/getting-started/migration
