### ISSUE TITLE
yarn ignoring npm_config_runtime and npm_config_node_gyp

### ISSUE THREAD

**Issue by mjschutz** [yarnpkg/yarn#7629]
I'm using yarn to create a NW.js project, but the native addon modules are been building with the wrong gyp (node-gyp not nw-gyp) and seen's like yarn is ignoring some npm flags. With NPM is working without problem.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

> yarn global add nw-gyp
> set npm_config_target=0.41.3
> set npm_config_arch=x64
> set  npm_config_target_arch=x64
> set npm_config_runtime=node-webkit
> set npm_config_build_from_source=true
> set npm_config_node_gyp=C:\Users\mauro\AppData\Local\Yarn\Data\global\node_modules\nw-gyp\bin\nw-gyp.js
> 
> yarn add mjschutz/node-firebird-libfbclient

> Output:
> gyp info it worked if it ends with ok
> gyp info using node-gyp@6.0.0
> gyp info using node@10.16.3 | win32 | x64
> gyp info find Python using Python version 2.7.16 found at "C:\Users\mauro\.windows-build-tools\python27\python.exe"
> gyp http GET https://nodejs.org/dist/v0.41.3/node-v0.41.3.tar.gz
> gyp http 404 https://nodejs.org/dist/v0.41.3/node-v0.41.3.tar.gz
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.41.3/node-v0.41.3.tar.gz
> gyp ERR! stack     at Request.<anonymous> (C:\Users\mauro\AppData\Local\Yarn\Data\global\node_modules\node-gyp\lib\install.js:187:14)
> gyp ERR! stack     at Request.emit (events.js:203:15)
> gyp ERR! stack     at Request.onRequestResponse (C:\Users\mauro\AppData\Local\Yarn\Data\global\node_modules\request\request.js:1066:10)
> gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
> gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
> gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
> gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:442:20)
> gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
> gyp ERR! stack     at addChunk (_stream_readable.js:288:12)
> gyp ERR! stack     at readableAddChunk (_stream_readable.js:269:11)
> gyp ERR! System Windows_NT 10.0.18362
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mauro\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! node -v v10.16.3

**Comment by paul-soporan** [comment]
Closing as we stopped supporting `npm_config_` variables alltogether in v2 where we've also deprecated implicit `node-gyp` reliance.

**Comment by JCMais** [comment]
@paul-soporan what is the correct to pass those now?
