### ISSUE TITLE
yarn install --verbose

### ISSUE THREAD

**Issue by indieisaconcept** [yarnpkg/yarn#763]
**Do you want to request a _feature_ or report a _bug_?**

Feature : This would make diagnosing installation issues much easier. See #764 for more context.

**What is the current behavior?**

Running `yarn --verbose` or `yarn install --verbose` does not display extended information about the installation process.

**What is the expected behavior?**

Should provide extended output similar to `npm i --verbose`

**Please mention your node.js, yarn and operating system version.**
- yarn@v0.15.1
- node@v4.4.6
- osx@10.10.5

**Comment by bestander** [comment]
To debug issues we have on CI servers I'd like to have a log of all files being copied during linking phase.

**Comment by Daniel15** [comment]
There's some discussion in #1500 too (which I closed in favour of this one)

**Comment by kittens** [comment]
Created #1994 to fix this, pending approval.

**Comment by indieisaconcept** [comment]
Thanks!.
