### ISSUE TITLE
Yarn add {package} fails 

### ISSUE THREAD

**Issue by abloodworth** [yarnpkg/yarn#7639]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I try to add require-context.macro or any package, I get the following error:
Allisons-MacBook-Pro:my-app allison$ yarn add --dev require-context.macro
yarn add v1.19.1
error An unexpected error occurred: "/Users/allison/dev/my-app/package.json: Unexpected token } in JSON at position 895".
info If you think this is a bug, please open a bug report with the information provided in "/Users/allison/dev/my-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Here is the error log:
  SyntaxError: /Users/allison/dev/my-app/package.json: Unexpected token } in JSON at position 895
      at JSON.parse (<anonymous>)
      at /usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:1625:59
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:304:30)
      at /usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:315:13

which appears to point at this being the problem at line 1625 in the first file above:
var readJsonAndFile = exports.readJsonAndFile = function () {
 var _ref24 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (loc) {
   var file = yield readFile(loc);
   try {
     return {
       object: (0, (_map2 || _load_map2()).default)(JSON.parse(stripBOM(file))),
       content: file
     };

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install Yarn
2. Don't know if you have to install storybook, but my-app is the storybook app that is installed following these instructions: https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/

**What is the expected behavior?**
Put the dependency in the package.js file

**Please mention your node.js, yarn and operating system version.**
Mac OS 10.13.6 (17G8037), Yarn v1.19.1, Node v12.12.0

**Comment by abloodworth** [comment]
So now this error is happening with all yarn commands...

**Comment by rubeldev** [comment]
Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add react-native --exact

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

Yarn version: 
  1.19.1

Node version: 
  10.16.3

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/hermes-engine/-/hermes-engine-0.2.1.tgz: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:162:17)

npm manifest: 
  {"name":"rnproject","version":"0.0.1","private":true,"scripts":{"start":"node node_modules/react-native/local-cli/cli.js start"}}

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by abloodworth** [comment]
@rubeldev does this mean you've reproduced my issue? Should I uninstall then download a new version of yarn or how can I fix this problem? I installed it with npm and tried to uninstall it with "npm uninstall -g yarn" but that didn't work.

**Comment by kvnlee777** [comment]
@abloodworth Hi, i also experienced this issue. It seems like there is issue with v1.19.1
I was able to fix it by downgrade to v.1.17.3
`npm uninstall -g yarn` then `npm install -g @1.17.3`

**Comment by merceyz** [comment]
Sounds like the JSON in your `package.json` is invalid but without a reproduction there is nothing actionable here

**Comment by c0debreaker** [comment]
I'm getting the same issue even after downgrading to yarn 1.17.3. What is the fix to this issue?
