### ISSUE TITLE
Running any script with pnp on node 13.0.1: "TypeError: paths is not iterable"

### ISSUE THREAD

**Issue by sverweij** [yarnpkg/yarn#7642]
**Do you want to request a *feature* or report a *bug*?**
A bug (or I'm doing something stupid...)

**What is the current behavior?**
- On node 13 running a lifecycle script with yarn (with pnp enabled) errors with `TypeError: paths is not iterable` (see below).
- With the same files, on node 12 the script runs ok.

```
/home/runner/work/yarn-on-node-13/yarn-on-node-13/.pnp.js:747
    for (const path of paths) {
                       ^

TypeError: paths is not iterable
    at Function.Module._findPath (/home/runner/work/yarn-on-node-13/yarn-on-node-13/.pnp.js:747:24)
    at resolveMainPath (internal/bootstrap/pre_execution.js:447:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:24)
    at internal/main/run_main_module.js:16:11
```

**If the current behavior is a bug, please provide the steps to reproduce.**

On node 13, with yarn plug'n play enabled, run any javascript through yarn.

> I've created a minimum reproduction repo on [sverweij/yarn-on-node-13](https://github.com/sverweij/yarn-on-node-13)
> In there: run `yarn cache clean && yarn && yarn test`
> (You can see what happens in the GitHub actions tab of the repo...
> - [...here for yarn 1.19.1](https://github.com/sverweij/yarn-on-node-13/runs/272283044) and 
> - [... here for yarn 2.0.0-rc.6](https://github.com/sverweij/yarn-on-node-13/runs/272305615))

**What is the expected behavior?**

The lifecycle script runs without errors (just like on node 12).

**Please mention your node.js, yarn and operating system version.**

node.js: 13.0.1
yarn: 1.19.1 (and 2.0.0-rc.6)
OS: macOS 10.14.6

**Comment by arcanis** [comment]
Can you check whether the same is true for [Yarn v2](https://github.com/yarnpkg/berry)?

**Comment by sverweij** [comment]
it is - check out this run with the same repo (using yarn 2.0.0-rc.6: https://github.com/sverweij/yarn-on-node-13/runs/272305615)

**Comment by sverweij** [comment]
Some research:

- on node 12 (and below) with the MRS above the `Module._findPath` as patched in .pnp.js is never called
- on node 13 it is, and it gets these arguments passed:
```javascript
{
  '0': '/Users/sander/path/to/index.js',
  '1': null,
  '2': true
}
```
- the diff between node 13.x branch and master shows the likely culprit is a [new call](https://github.com/nodejs/node/compare/v13.x#diff-f15c959d6f6b87e178781150162c835cR447)  to `_findPath` in `lib/internal/bootstrap/pre_execution.js`,  with the values `path.resolve(main)`, `null` and `true` - 

I patched the line in the local .pnp.js to take that into account, like so:
```javascript
for (const path of paths || []) {
```
... and with that the problem seems to be gone. 

I could make a PR to change [generate-pnp-map-api.tpl.js](https://github.com/yarnpkg/yarn/blob/fb03788279278084e81aac9cde40151a3134761b/src/util/generate-pnp-map-api.tpl.js#L717) likewise (and the same in berry, I guess?)

**Comment by arcanis** [comment]
That would be great! I can't make the fix atm but I can merge it, and you can start using it through `yarn set version from sources` (v2).

**Comment by SimenB** [comment]
might be worth considering getting yarn into [citgm](https://github.com/nodejs/citgm/) so these breakages are caught before making it into a node stable release?

**Comment by arcanis** [comment]
> might be worth considering getting yarn into citgm so these breakages are caught before making it into a node stable release?

Yep! I think the v1 is already there but the PnP path isn't covered at the moment. Maybe .

On our side we also have [our own kind of "Canary in the goldmine" program](https://github.com/yarnpkg/berry#current-status), but I'm not sure whether Node publishes nightly builds that we could use for this purpose 🤔

[edit] Seems like [there is](https://nodejs.org/download/nightly/index.json)! We should definitely add a test on our side too, then.
