### ISSUE TITLE
"To upgrade, run the following command" on windows returning command that doesn't work

### ISSUE THREAD

**Issue by connorjburton** [yarnpkg/yarn#7645]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Running `yarn` will correctly install the packages however once finished will tell me to upgrade my Yarn version it is out of date. Running the command given:

```
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
```

Will not work on windows (ConEmu and CMD) as `bash` is not a recognised command.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Run `yarn`
2. See recommended upgrade command
3. Run command
4. Error: `'bash' is not recognized as an internal or external command, operable program or batch file.`

**What is the expected behavior?**
The recommended command should work on windows (using CMD). I am sure the command would work in Git Bash.

**Please mention your node.js, yarn and operating system version.**
Node 12.10.0
Windows 10.0.18362.418
Yarn 1.19.0 (Was installed a while ago via the installer on the website)

Happy to create PR for this if we come to a solution.

**Comment by Kristof-Mattei** [comment]
`npm update -g yarn` does the trick, in case you need a quick fix.

**Comment by tetamao** [comment]
> npm update -g yarn

thx～
works for me

**Comment by paul-soporan** [comment]
Closing as fixed in v2, where we don't do the update check anymore.

https://yarnpkg.com/getting-started/migration
