### ISSUE TITLE
--frozen-lockfile flag does not work if Plug'n'Play is enabled

### ISSUE THREAD

**Issue by nateg-gladly** [yarnpkg/yarn#7647]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

On Mac OS 10.13, and on Alpine Linux 3.9, if `yarn install --frozen-lockfile` is run with an updated `package.json` but not updated `yarn.lock`, yarn does not modify `yarn.lock`, but also does not throw an error (process exits with code 0) and does not warn the user that they have an outdated `yarn.lock` file.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Enable Plug'n'Play
* Add or upgrade a dependency in `package.json`
* Run `yarn install --frozen-lockfile`
* Observe that the process exits with code 0, there is no "your lockfile needs to be updated" error, and `yarn.lock` is not updated

**What is the expected behavior?**

`yarn install --frozen-lockfile` throws an error if the `yarn.lock` is outdated. This is how it works when Plug'n'Play is not enabled.

**Please mention your node.js, yarn and operating system version.**
* Node 8.11 on Mac OS 10.13
* Node 10.16 on Alpine Linux 3.9

**Comment by paul-soporan** [comment]
Fixed in v2 (where PnP support is also much more stable).

https://yarnpkg.com/getting-started/migration
