### ISSUE TITLE
Is there a way to disable build successful notification to DE ?

### ISSUE THREAD

**Issue by s101d1** [yarnpkg/yarn#7648]
Everytime I run `yarn start` command and if the build is successful, the yarn process will send pop-up notification "Build Successful" to the DE (I'm using cinnamon DE). Unfortunately cinnamon doesn't have setting to disable notification for specific app.

Is there a way to disable the notification from yarn itself?

**Comment by merceyz** [comment]
That's not done by Yarn, it's whatever your `start` script executes that does it
