### ISSUE TITLE
Using registry.npjms.orrg (note spelling) as website source for adding packages/apps

### ISSUE THREAD

**Issue by kryptics18** [yarnpkg/yarn#7657]
**Do you want to request a *feature* or report a *bug*?**
Definitely a bug.

**What is the current behavior?**

I had been trying to install angular via yarn when I came across this error. The console output is given below:
info There appears ti be trouble with your network connection. Retrying...
error An unexpected error occured: <...>getaddrinfo ENOTFOUND registry.npjms.orrg

**If the current behavior is a bug, please provide the steps to reproduce.**
I am unsure if this bug is reproducible, as I had tried installing previous apps like 7-Zip and Git and they worked fine, but now reinstalling them gives me the same error as Angular's installation (orrg)

**What is the expected behavior?**
Probably that yarn installs from registry.npjms.org and I can get a clean package install of AngularX

**Please mention your node.js, yarn and operating system version.**

Node: 13.0.1
Yarn: 1.19.1
OS: Windows 10 Enterprise, build 17763

**Comment by Adamkaram** [comment]
you can this 
https://github.com/yarnpkg/yarn/issues/4890 
or you can do 
yarn add <yourPackage> --network-timeout 100000
or if you want to make it g u can do 
yarn config set network-timeout 600000 -g

if the probleme  stay as it 
u can remove any proxy u use it from 
npm config rm proxy
npm config rm https-proxy

the last soulation do this 
yarn config list
and dump it here maybe someone 'll helping u

**Comment by kryptics18** [comment]
@Adamkaram I tried network timeout but no effect. I am behind a company firewall so I cannot remove proxy settings either.
For security reasons, I cannot dump my config info, but I can say that nothing unexpected was visible in the config.
Thanks for your help, however. We'll see if we can get another response.

**Comment by BYK** [comment]
I'm 100% sure your `.npmrc` or `.yarnrc` file has the `registry` setting set incorrectly: https://docs.npmjs.com/configuring-your-registry-settings-as-an-npm-enterprise-user
