### ISSUE TITLE
Installation Problem: VERSION MISMATCH

### ISSUE THREAD

**Issue by siddhi-sandy** [yarnpkg/yarn#7659]
* VERSION MISMATCH
**Which operating system are you using:**
Ubuntu 18.04

**Please describe the steps you took when trying to install Yarn and what went wrong:**
1. curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
2. sudo apt update && sudo apt install yarn
* yarn --version => 0.32
* https://yarnpkg.com/ => 1.19.1

**Comment by BYK** [comment]
This is an issue with your `$PATH` or you have an override for `yarn` command (like an alias etc.) not an issue with yarn itself.
