### ISSUE TITLE
Can't add alias from git

### ISSUE THREAD

**Issue by stavalfi** [yarnpkg/yarn#7660]
```bash 
yarn add --dev -W html-webpack-plugin-webpack5@npm:https://github.com/PutziSan/html-webpack-plugin
```
output:
```bash
yarn add v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/%2f/github.com/PutziSan/html-webpack-plugin: Request \"https://registry.yarnpkg.com/%2f/github.com/PutziSan/html-webpack-plugin\" returned a 405".
info If you think this is a bug, please open a bug report with the information provided in "/Users/stavalfi/WebstormProjects/jstream/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
macos mojave 10.14.3 (18D109)
node v13.0.1
npm 6.12.0
yarn 1.19.1
```

**Comment by BYK** [comment]
I don't think we'll ever support this quite corner case so closing. You can achieve what you want by using [selective version resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions) instead.

**Comment by stavalfi** [comment]
Not sure how to achieve that. Can you clarify?

* at the end, I will need 2 versions of that dependency which are reachable from my code using `require`.

**Comment by BYK** [comment]
@stavalfi - ah, sorry I didn't realize you needed two copies of that. Why can you not do `html-webpack-plugin-webpack5@https://github.com/PutziSan/html-webpack-plugin` (dropping the `npm:` part?)

**Comment by stavalfi** [comment]
I did what the docs said. I'm also not sure what does the `npm` do:

https://yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias

![image](https://user-images.githubusercontent.com/12954665/67898434-02493200-fb69-11e9-98c9-7a440fd89c4c.png)

**Comment by BYK** [comment]
@stavalfi the `npm:` there is the protocol. You don't need it for full URLs, Git URLs etc.

**Comment by stavalfi** [comment]
ho! thanks!!!
