### ISSUE TITLE
Installation Problem: yarn

### ISSUE THREAD

**Issue by matix18** [yarnpkg/yarn#7661]
**Which operating system are you using:**
windows

**Please describe the steps you took when trying to install Yarn and what went wrong:**

'yarn' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AbootDev** [comment]
I think one of the ways to solve the problem is to uninstall **YARN**. Once **YARN** uninstalled, you reinstall it and restart your computer. After reboot, type the **yarn -v** command, it worked for me, why not you ;)

**Comment by AbootDev** [comment]
> **Which operating system are you using:**
> windows
> 
> **Please describe the steps you took when trying to install Yarn and what went wrong:**
> 
> 'yarn' is not recognized as an internal or external command,
> operable program or batch file.

I think one of the ways to solve the problem is to uninstall YARN. Once YARN uninstalled, you reinstall it and restart your computer. After reboot, type the yarn -v command, it worked for me, why not you ;)

**Comment by olingern** [comment]
Is this still an issue? If so, please comment and happy to reopen. 

Also, please add reproductions steps!
