### ISSUE TITLE
Error using yarn install / "Can't answer a question unless a user TTY"

### ISSUE THREAD

**Issue by sebastianroming** [yarnpkg/yarn#7666]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
`yarn install` fails with the error message **error An unexpected error occurred: "Can't answer a question unless a user TTY".**

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using yarn on Debian Stretch (4.9.168), having a Jenkins installed and trying to run `yarn install --non-interactive --no-progress --flat --silent --network-timeout=1000000` out of my Jenkinsfile.

yarn has been installed via Global Configuration for Node.JS on Jenkins (`npm install -g yarn@latest`), but as soon as the Jenkinsfile tries to run the above mentions install command, I get the following error:

```
+ yarn install --non-interactive --no-progress --flat --silent --network-timeout=1000000
error An unexpected error occurred: "Can't answer a question unless a user TTY".
script returned exit code 1
```

So apparently yarn has been installed correctly. A bit of search brought some information for Windows, but not how to fix it for Linux. Does anyone have any clue how to fix this problem?

Jenkinsfile looks like this:

```
#!/usr/bin/env groovy
pipeline {
  agent {
    label 'linux'
  }

  tools {
    nodejs "NodeJS_v11.9.0"
  }

  stages {
    stage("Cleanup") {
      steps {
        sh yarn cache clean
        dir('node_modules') {
          deleteDir()
        }
      }
    }
    stage("Install dependencies") {
      failFast true
      steps {
        sh yarn install --non-interactive --no-progress --flat --silent --network-timeout=1000000
      }
    }

  }

}
```

**What is the expected behavior?**
`yarn install` should install all dependencies without any error

**Please mention your node.js, yarn and operating system version.**
- Operating System:  Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64
- Node version: v11.9.0
- Yarn version: 1.19.1

**Comment by heinekeg** [comment]
You'll have to do a local `yarn install --flat` and solve every `Unable to find a suitable version for "XYZ", please choose one by typing one of the numbers below:`. Or just skip the `--flat` in the Jenkinsfile.

**Comment by sebastianroming** [comment]
@heinekeg Okay, that was easy ... that worked. Thanks a lot.
