### ISSUE TITLE
unable to create new angular project

### ISSUE THREAD

**Issue by psampath243** [yarnpkg/yarn#7670]
When I ran the ng new test-project It was throwing yarn error(I don't to use yarn bcz of coporate network permission)

? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE test-project/angular.json (3641 bytes)
CREATE test-project/package.json (1298 bytes)
CREATE test-project/README.md (1029 bytes)
CREATE test-project/tsconfig.json (543 bytes)
CREATE test-project/tslint.json (1953 bytes)
CREATE test-project/.editorconfig (246 bytes)
CREATE test-project/.gitignore (631 bytes)
CREATE test-project/browserslist (429 bytes)
CREATE test-project/karma.conf.js (1024 bytes)
CREATE test-project/tsconfig.app.json (270 bytes)
CREATE test-project/tsconfig.spec.json (270 bytes)
CREATE test-project/src/favicon.ico (948 bytes)
CREATE test-project/src/index.html (297 bytes)
CREATE test-project/src/main.ts (372 bytes)
CREATE test-project/src/polyfills.ts (2838 bytes)
CREATE test-project/src/styles.css (80 bytes)
CREATE test-project/src/test.ts (642 bytes)
CREATE test-project/src/assets/.gitkeep (0 bytes)
CREATE test-project/src/environments/environment.prod.ts (51 bytes)
CREATE test-project/src/environments/environment.ts (662 bytes)
CREATE test-project/src/app/app.module.ts (314 bytes)
CREATE test-project/src/app/app.component.html (25498 bytes)
CREATE test-project/src/app/app.component.spec.ts (999 bytes)
CREATE test-project/src/app/app.component.ts (216 bytes)
CREATE test-project/src/app/app.component.css (0 bytes)
CREATE test-project/e2e/protractor.conf.js (808 bytes)
CREATE test-project/e2e/tsconfig.json (214 bytes)
CREATE test-project/e2e/src/app.e2e-spec.ts (645 bytes)
CREATE test-project/e2e/src/app.po.ts (262 bytes)
'yarn' is not recognized as an internal or external command,
operable program or batch file.
Package install failed, see above.

**Comment by paul-soporan** [comment]
Closing as there's nothing actionable here, make sure that you have yarn installed.
