### ISSUE TITLE
Question: Yarn is crashing when react app is opened in IE (where are logs)

### ISSUE THREAD

**Issue by tahaimt** [yarnpkg/yarn#7675]
I am using the latest version of Yarn. In this question I just want to know where to look for the logs related to Yarn, or even if it stores logs on windows. 

This is the error I get in the console, I am wondering if there are any more logs that are omitted from the console.

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by paul-soporan** [comment]
That's the entire stack trace, which Yarn doesn't control.
