### ISSUE TITLE
package's install lifecycle script sometimes does not run

### ISSUE THREAD

**Issue by aromanovdodo** [yarnpkg/yarn#7687]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
We encounted an obscure problem.

There is `node-sass` npm package that contains two lifecycle scripts - `install` and `postinstall`. The latter script depends on the former: `postinstall` requires artifact from `install` script or installed `node-gyp` and will crash when neither is present.

From time to time our CI server fails with previously mentioned crash. We've done some investigations and managed to reproduce it:

It turns out that combination of packages `node-sass@4.13.0`, `styled-components@4.4.1`, and `core-js-compat@3.1.3` sometimes leads to `install` script of `node-sass` not being executed. To be specific, `node scripts/install.js` process is being spawned, but it exits immediatly without executing any code, without any output (`stdout` and `stderr`) and with `0` exit code (callback in `proc.on('close', ...)` from `src\util\child.js` is fired right after `child_process.spawn()`).

What is interesting that if we update `core-js-compat` to `3.3.5`, the problem goes away.

**If the current behavior is a bug, please provide the steps to reproduce.**
We've created a [repo](https://github.com/aromanovdodo/install-not-running) so you can reproduce it. Just run `runme.sh` and wait for a while (about 10-40 minutes).

**What is the expected behavior?**
`node-sass` should always have its `install` script executed.

**Please mention your node.js, yarn and operating system version.**
node.js v10.16.3
yarn v1.19.1
Windows 10 Pro build 17763 (x64)

**Comment by paul-soporan** [comment]
Closing as fixed in the v2.

https://yarnpkg.com/getting-started/migration
