### ISSUE TITLE
Yarn dedupe: 1.8 Gb to 1.0 Gb node_modules

### ISSUE THREAD

**Issue by Diokuz** [yarnpkg/yarn#7689]
We just decreased our node_modules from 1.8 Gb to 1.0 Gb! With help of https://github.com/atlassian/yarn-deduplicate

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
We have a big monorepo. Our _node_modules_ is 1.8 Gb in size. After using package `yarn-deduplicate yarn.lock`, it was decreased to 1.0 Gb. The package: https://github.com/atlassian/yarn-deduplicate

According to docs, it should be inside yarn https://yarnpkg.com/lang/en/docs/cli/dedupe/

Why there is no build-in alternatives?

**If the current behavior is a bug, please provide the steps to reproduce.**
Just create a big repository and add many packages to it, iterative.

**What is the expected behavior?**
Every yarn install also deduplicates dependencies

**Please mention your node.js, yarn and operating system version.**
node -v 12.13.0
Mac Os X

**Comment by patrick-mcdougle** [comment]
Perhaps [`yarn install --flat`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-flat) could help?

**Comment by merceyz** [comment]
Implemented in Yarn 2.2+

https://yarnpkg.com/cli/dedupe
https://dev.to/arcanis/yarn-2-2-dedupe-faster-lighter-ha5

https://yarnpkg.com/getting-started/migration
