### ISSUE TITLE
Couldn't find package "[PACKAGE_NAME]" on the "npm" registry

### ISSUE THREAD

**Issue by raman-kazhadub** [yarnpkg/yarn#7691]
Please do not close this issue as duplicate - it's not the same as #3645 or #2611 or #6029

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Sometimes on executing "yarn install" or "yarn add [PACKAGE_NAME]" I get an error message - Couldn't find package "[PACKAGE_NAME]" on the "npm" registry. 
[PACKAGE_NAME] is random on each run.
The first time the problem appeared yesterday morning.
I have not changed the package.json or .npmrc, .yarnrc since September.
Logs for "yarn install --registry https://registry.npmjs.org --verbose":
[npmjs-registry.log](https://github.com/yarnpkg/yarn/files/3854059/npmjs-registry.log)
Logs for "yarn install --registry https://registry.yarnpkg.com --verbose":
[yarnpkg-registry.log](https://github.com/yarnpkg/yarn/files/3854060/yarnpkg-registry.log)

**If the current behavior is a bug, please provide the steps to reproduce.**
package.json of my project:
https://github.com/raman-kazhadub/yarn

**What is the expected behavior?**
Install all packages with no errors.

**Please mention your node.js, yarn and operating system version.**
yarn: 1.19.1
node: v10.15.3
OS: Microsoft Windows 10 Enterprise 10.0.17134 Build 17134

**Comment by raman-kazhadub** [comment]
In the log you could see a line:
Request "https://registry.yarnpkg.com/set-value" finished with status code 404.
But I can get "https://registry.yarnpkg.com/set-value" from browser or by curl

**Comment by novli** [comment]
Same problem here!
I believe that my local provider is blocking yarn usage for some stupid reason 👎  (закон об устойчивом рунете). Everything works using any VPN service.

**Comment by eshimischi** [comment]
> Same problem here!
> I believe that my local provider is blocking yarn usage for some stupid reason 👎 (закон об устойчивом рунете). Everything works using any VPN service.

Вообще не смешно. Not funny at all. Again this demos (Роспотребнадзор) !

**Comment by alexmj12** [comment]
yarn install fails with error:

> [1/4] Resolving packages...
> error Couldn't find package "create-react-class" on the "npm" registry.

but when I get info about "create-react-class" yarn works:

> yarn info create-react-class
> yarn info v1.19.1
> { name:
>    'create-react-class',
>   description:
>    'Legacy API for creating React components.',

**Comment by raman-kazhadub** [comment]
Issue was caused by Russian Federation internet access restrictions.
All works fine with VPN.

**Comment by raman-kazhadub** [comment]
> Same problem here!
> I believe that my local provider is blocking yarn usage for some stupid reason 👎 (закон об устойчивом рунете). Everything works using any VPN service.

Thanks a lot.

**Comment by novli** [comment]
I'd reopen this to ask someone of contributors about how it is blocked and maybe how to avoid it.
The problem is reproduced during 'Resolving packages' stage.
So if we have yarn.lock file, installation finishes without any problems.

**Comment by ERRORthenBSOD** [comment]
yup, got the same problem.  My production deploys are based on yarn and now i can't do anything((

**Comment by vvershkov** [comment]
Guys, this is definitely not blocking or something like that.

Because:
1) there is no domain or its IPs in blocklist or something; registry.yarnpkg.com uses cloudflare and they aren't dumb enough to get it banned.
2) if some blocks involved - you should get connection refused or connection timeout issue, but not HTTP 404 code.
3) also HTTPS is involved and we are getting 404 with correct SSL certificate. So it is either not blocking issue or RKN just successfully did MITM on most of clients including curl and that is nonsense. 


Also everything works just fine with some russian providers. You need to check what is happens on server side.

I am testing this issue by getting verbose from successful run, getting all links from there and test it with curl:
```
vv@z007-office:~$ cat verbose.txt | grep 'finished with status code' | cut -d'"' -f2 | wc -l
1381
vv@z007-office:~$ cat verbose.txt | grep 'finished with status code' | cut -d'"' -f2 | sort | uniq -c | wc -l
1381
vv@z007-office:~$ cat verbose.txt | grep 'finished with status code' | cut -d'"' -f2 | sort > list.txt
vv@z007-office:~$ head list.txt 
https://registry.yarnpkg.com/abab
https://registry.yarnpkg.com/abbrev
https://registry.yarnpkg.com/accepts
https://registry.yarnpkg.com/acorn
https://registry.yarnpkg.com/acorn-dynamic-import
https://registry.yarnpkg.com/acorn-globals
https://registry.yarnpkg.com/acorn-jsx
https://registry.yarnpkg.com/acorn-walk
https://registry.yarnpkg.com/agent-base
https://registry.yarnpkg.com/ajv


vv@z007-office:~$ for i in `cat list.txt`; do  echo "$i $(curl --head $i 2>/dev/null | grep HTTP)" ; done | grep 404
https://registry.yarnpkg.com/fastparse HTTP/2 404 
https://registry.yarnpkg.com/first-chunk-stream HTTP/2 404 
https://registry.yarnpkg.com/gulplog HTTP/2 404 
https://registry.yarnpkg.com/has-gulplog HTTP/2 404 
https://registry.yarnpkg.com/hoist-non-react-statics HTTP/2 404 
https://registry.yarnpkg.com/is-relative HTTP/2 404 
https://registry.yarnpkg.com/is-resolvable HTTP/2 404 
https://registry.yarnpkg.com/pbkdf2 HTTP/2 404 
https://registry.yarnpkg.com/string.prototype.trimright HTTP/2 404 
https://registry.yarnpkg.com/stylis-rule-sheet HTTP/2 404 
https://registry.yarnpkg.com/tempfile HTTP/2 404 
https://registry.yarnpkg.com/vali-date HTTP/2 404

vv@z007-office:~$ for i in `cat list.txt`; do  echo "$i $(curl --head $i 2>/dev/null | grep HTTP)" & done | grep 404
https://registry.yarnpkg.com/chain-function HTTP/2 404 
https://registry.yarnpkg.com/first-chunk-stream HTTP/2 404 
https://registry.yarnpkg.com/fancy-log HTTP/2 404 
https://registry.yarnpkg.com/is-relative HTTP/2 404 
https://registry.yarnpkg.com/hoist-non-react-statics HTTP/2 404 
https://registry.yarnpkg.com/is-resolvable HTTP/2 404 
https://registry.yarnpkg.com/has-gulplog HTTP/2 404 
https://registry.yarnpkg.com/is-cwebp-readable HTTP/2 404 
https://registry.yarnpkg.com/pbkdf2 HTTP/2 404 
https://registry.yarnpkg.com/postcss-custom-selectors HTTP/2 404 
https://registry.yarnpkg.com/postcss-nesting HTTP/2 404 
https://registry.yarnpkg.com/tempfile HTTP/2 404 
https://registry.yarnpkg.com/string.prototype.trimright HTTP/2 404 
https://registry.yarnpkg.com/url-regex HTTP/2 404 
https://registry.yarnpkg.com/stylis-rule-sheet HTTP/2 404
```

**Comment by victordidenko** [comment]
Maybe some issues with СОРМ? Товарищъ майор не успевает просматривать все запросы

**Comment by vvershkov** [comment]
Once again - HTTPS is working.

**Comment by victordidenko** [comment]
But СОРМ still mirroring and saving all the traffic nonetheless, I think

**Comment by vvershkov** [comment]
Yep, but he can't decrypt it and also can't fake server response.

**Comment by AndreyPatseiko** [comment]
Don't have this problem from npm?

**Comment by victory-v** [comment]
I have the same problem but it appears quite randomly.
NPM works fine though.

**Comment by Evalon** [comment]
This problem with NPM AWS bucket. 
Because 404 you see not 404 from npm register itself, it's from AWS.
I wrote to npm support on monday. 
They answer me twice with:
Hi,

Please provide the following, so we can investigate.

npm whoami
debug.log file (located in your .npm directory)
screenshots

**Comment by ERRORthenBSOD** [comment]
Now its working! Thanks everyone

**Comment by R1cro** [comment]
Hey, guys. Seems to be the problems disappeared. Could somebody confirm that, please?

**Comment by victordidenko** [comment]
I can confirm from my side, didn't see error happen during this week

**Comment by samuelcastro** [comment]
I'm having the same issue, any fixes?

**Comment by YazanKhatib** [comment]
I'm having the same issue even when I enable a VPN !?

**Comment by JoseFMP** [comment]
Same issue here. Any idea?

**Comment by zameerascentic** [comment]
Same issue with me now, random packages, doesn't work even with VPN

**Comment by fedevitch** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5 this is some npm registry issue

**Comment by YazanKhatib** [comment]
npm registry is fixed now and working perfectly.

**Comment by zameerascentic** [comment]
Working +1

**Comment by writetonsharma** [comment]
I was also getting this error. We have a local company repo. I was able to set the registry setting for yarn correctly, proxy was working fine too. But still yarn was not able to get anything from the registry. I think yarn was not picking the auth token from npmrc config.
After setting the following I was able to move forward.

_auth to sametoken
always-auth to true
