### ISSUE TITLE
lock dependency is 3rd lib not work

### ISSUE THREAD

**Issue by CarmeloXue** [yarnpkg/yarn#7730]
Yarn version: 1.17.0

**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
My package.json is like :
{
    dependency:{
          "a":"1.0.0",
          "b":"1.1.0"
     },
     resolutions:{
         "a":"1.0.0"
     }
}

this dependency b rely on a:"^1.0.0".
I want my lib serve as a 3rd lib, and I need to lock dep a version to 1.0.0. I don't and resolutions at the first time and I got multiple version error, then when I set resolutions, when I install my module, this dep a will be 1.1.0 (which is the latest version). Even when i write "b/a":"1.0.0" in resolutions will not work.  
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

lock the version as dependency

**Please mention your node.js, yarn and operating system version.**
Nodejs:12.4.0
system mac os 10.14.5

**Comment by paul-soporan** [comment]
Closing as we've fixed all `resolutions`-related issues in v2.

https://yarnpkg.com/getting-started/migration
