### ISSUE TITLE
What are the v1.20 and  v1.21 releases for?

### ISSUE THREAD

**Issue by futagoza** [yarnpkg/yarn#7735]
I got a message from running `yarn` that I should install v1.19.2 so I went to the website, only to see that a v1.21 is also available as an RC release. I thought I might as well check what the changes are, but there are no changes listed for both v1.20 and v1.21 in the CHANGELOG.md or the release/tagged pages, and the only issues regarding these releases (as well as v1.19.2) seem to be from the release bot.

**Comment by msheakoski** [comment]
It looks like maybe there was a problem deploying the release. #7726 #7727 #7728

**Comment by merceyz** [comment]
Closing as the changelog has been updated
