### ISSUE TITLE
Bug: installing dependencies in production is removing a Webpacker dependency

### ISSUE THREAD

**Issue by nerde** [yarnpkg/yarn#7740]
Repository with the code to reproduce the issue: https://github.com/nerde/yarn-bug

Given the following `package.json`:

```json
{
  "name": "yarn_bug",
  "dependencies": {
    "@rails/webpacker": "^4.0.2"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.3.1"
  }
}
```

When I run `NODE_ENV=production yarn install`, the Webpacker's dependency `file-loader` gets added to `node_modules`,
just as expected.

Now if I add this specific dev dependency: `yarn add --dev @storybook/react`, I get the following `package.json`:

```json
{
  "name": "yarn_bug",
  "dependencies": {
    "@rails/webpacker": "^4.0.2"
  },
  "version": "0.1.0",
  "devDependencies": {
    "@storybook/react": "^5.2.8",
    "webpack-dev-server": "^3.3.1"
  }
}
```

That looks correct. Now if I run `NODE_ENV=production yarn install` again, `file-loader` gets removed from
`node_modules`, this is **not** expected.

Why installing production dependencies after adding that **dev** dependency is getting rid of `file-loader`?

```
➭ node -v
v10.17.0

➭ yarn -v
1.21.0
```

My OS is `macOS Catalina 10.15.1 (19B88)`.

I tested this with `npm` and the issue does **not** occur.

**Comment by exlee** [comment]
After further investigation that's what happening behind the scenes.

1. Initial production install

- `file-loader` V3 is being installed as a `@rails/webpacker` dependency in `/node_modules/file-loader`

2. Add Storybook

- `file-loader` V3 is being moved to `/node_modules/@rails/webpacker/node_modules/file-loader`
- `file-loader` V4 is being installed in `/node_modules/file-loader`

3. Second production install

- `file-loader` V3 remains at `/node_modules/@rails/webpacker/node_modules/file_loader`
- `file-loader` V4 is **deleted** from `/node_modules/file-loader`

We had an configuration issue where such global, installed in `node_modules` was implicit dependency. While obvious mistake, I'm not sure if the final state is the state required.

Also I'm wondering if `@rails/webpacker` doesn't depend on this mechanism (missing dependency is occuring in `webpack` which is dependency of the `@rails/webpacker`).

Thus to reformulate what I think should be correct:

When production install removes global dependency but local version of the same library exists deeper, the local dependency (nested) should be promoted to the global one (in `node_modules`).

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
