### ISSUE TITLE
Getting "You cannot require a package that is not declared in your dependencies" for Package Dependency in Yarn Workspace

### ISSUE THREAD

**Issue by jintoppy** [yarnpkg/yarn#7742]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am trying to integrate PnP to yarn workspace. I am using lerna to manage the packages. When I am running the lerna command to build, it gives error saying dependency is not declared, even though it is added as dependency in package. When I check in .pnp.js, relativePath is still coming as a root directory. So, it is fetching dependencies from the root package.json which doesn't have the package dependency.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. lerna run build --scope <package_name> on the root.

Gives error if the dependency is available only in package.

```
You cannot require a package ("@babel/plugin-proposal-decorators") that is not declared in your dependencies (via "C:\work-project\project\packages\constants\")
    at makeError (C:\work-project\project\.pnp.js:55:17)
    at Object.resolveToUnqualified (C:\work-project\project\.pnp.js:81845:17)
    at Object.opts.paths (C:\work-project\project\.pnp.js:82188:40)
```

**What is the expected behavior?**
PnP should get the dependency list from the package.json inside the package folder, not from the root folder. I even tried putting installConfig to the package.json of the package also.

**Please mention your node.js, yarn and operating system version.**

Node v10.16.0
Yarn v1.19.2

**Comment by merceyz** [comment]
PnP has been massivly improved in V2 so i'll close this as it's most likely fixed

https://yarnpkg.com/getting-started/migration
