### ISSUE TITLE
BUG: yarn install error

### ISSUE THREAD

**Issue by Moocliu** [yarnpkg/yarn#7743]
Installing node_moules with yarn is the default package.json search for the root directory. Shouldn't it look in the current project file?
yarn install v1.19.1
error An unexpected error occurred: "/package.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/disk/ssd1/app/2017.upyun.com/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
