### ISSUE TITLE
503 Error installing package

### ISSUE THREAD

**Issue by esetnik** [yarnpkg/yarn#7745]
Still seeing periodic 503 errors. I'm not sure if this should be reported to yarn or to npm.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
```
11:18:04 AM: error An unexpected error occurred: "https://registry.yarnpkg.com/he/-/he-1.2.0.tgz: Request failed \"503 Service Unavailable\"".
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
node v10.17.0
yarn v1.21.1
Ubuntu Xenial 16.04

**Comment by esetnik** [comment]
Relates to #7409 #6929 #7025 #7297

**Comment by hpurmann** [comment]
We are unfortunately seeing the same error periodically on our CI servers.

**Comment by DanStor** [comment]
Has there been any movement on this? It still seems to be an issue.

**Comment by paul-soporan** [comment]
Closing as an external issue with the npm registry, nothing we can do on Yarn's side.
