### ISSUE TITLE
yarn bin <executable> returns the wrong path when executable is hoisted and installed in workspace

### ISSUE THREAD

**Issue by priceld** [yarnpkg/yarn#7748]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When working in a monorepo using yarn workspaces, if a dependency with a bin is hoisted but a package installs a different version of the same dependency locally, `yarn bin` and `yarn run` do not work as expected.

For example if `foo@2.0.0` is hoisted, but `foo@1.0.0` is installed in a package workspace, the following commands will use the wrong bin (assuming both versions of `foo` have a bin named `foo`):

```
workspace/packages/my-package$ yarn bin foo
/path/to/workspace/node_modules/.bin/foo

workspace/packages/my-package$ yarn run foo --version
2.0.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I setup a repo with instructions to reproduce this issue: https://github.com/priceld/demo-yarn-bin-bug

**What is the expected behavior?**
`yarn bin` and `yarn run` should use the bin from the local node_modules instead of the root node_modules.

This issue is related to #7126. The fix for that issue works when the bin only exists in the local workspace, but not when the bin exists in both the local workspace and the root (hoisted) `node_modules`.

```
workspace/packages/my-package$ yarn bin foo
/path/to/workspace/packages/my-package/node_modules/.bin/foo

workspace/packages/my-package$ yarn run foo --version
1.0.0
```

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v10.16.0

$ yarn -v
1.19.2

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
```

**Comment by merceyz** [comment]
Fixed in v2

https://yarnpkg.com/getting-started/migration
