### ISSUE TITLE
[Feature/UX] Specify conflicting paths when many workspaces have the same name

### ISSUE THREAD

**Issue by njlr** [yarnpkg/yarn#7749]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The current error for conflicting workspace names could be made more helpful by specifying the workspaces that conflict. 

```bash
$ yarn install         
yarn install v1.19.2
error There are more than one workspace with name "my-package"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**

```bash
$ yarn install         
yarn install v1.19.2
error There are more than one workspace with name "my-package":
       * ./packages/my-package
       * ./packages/not-really-my-package
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Please mention your node.js, yarn and operating system version.**

```bash
$ node --version
v13.2.0

$ yarn --version
1.19.2

$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by paul-soporan** [comment]
Closing as we've decided not to support multiple workspaces with the same name because it would bring too many architectural constraints.

**Comment by paul-soporan** [comment]
Oh, misread your issue.

**Comment by paul-soporan** [comment]
Closing as fixed in v2, where we now throw `Duplicate workspace name ${name}: ${workspaceCwd} conflicts with ${duplicateWorkspace.cwd}`.

https://yarnpkg.com/getting-started/migration
