### ISSUE TITLE
Problem with registry url resolve

### ISSUE THREAD

**Issue by serkanyersen** [yarnpkg/yarn#775]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
if you don't put double trailing slash in registry config in `.yarnrc` it breaks the url

yarn should turn registry url into
`http://domain/custom/npm/npm-repo/[package-name]

but it turns it into 
`http://domain/custom/npm/[package-name]`

you can see faulty lines in [here](https://github.com/yarnpkg/yarn/blob/b880d403ed9f32e724207ecbdb94c794d4c64131/src/registries/npm-registry.js#L58) and [here](https://github.com/yarnpkg/yarn/blob/126d8c21f56466826e4cc9d43b66123872b982fe/src/registries/npm-registry.js#L50)

yarn is deleting the trailing slash and using `url.resolve` which instead of appending package name replaces the last path with it.

**If the current behavior is a bug, please provide the steps to reproduce.**
1) create .yarnrc
2) put `registery "http://domain/custom/npm/npm-repo"
 2.1) you can try with slash as well
3) try to install

it should fail.

if you go back to `.yarnrc` file and put double slash at the end of the url, it will work.

**What is the expected behavior?**

yarn should accept registry url with or without trailing slashes

**Please mention your node.js, yarn and operating system version.**
yarn@0.10.1
node@4.2.6
macOS@sierra

**Comment by chicoxyzzy** [comment]
https://github.com/yarnpkg/yarn/pull/774

**Comment by serkanyersen** [comment]
nice, you were working on the fix while I was reporting the bug :) you solution would fix this but if user does not put trailing slash in the config file, it will still not work.

So instead of removing that line, you might change `url.resolve` part.

**Comment by bilal68** [comment]
I am having this error while adding sass-loader module through yarn
[1/4] Resolving packages...
error Couldn't find package "fast-deep-equal@^1.0.0" required by "ajv@^5.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
