### ISSUE TITLE
No obvious way to quit or exit `yarn upgrade-interactive`

### ISSUE THREAD

**Issue by sgronblo** [yarnpkg/yarn#7767]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Accidentally running `yarn upgrade-interactive` gives no obvious way to quit. If I press enter with no selected packages I get told to: "You must choose at least one package."

I tried the most obvious ways to quit: ctrl-c, q, esc but nothing works.

**What is the expected behavior?**

Multiple possible expected behaviors: enter without any selected packages should be acceptable, ctrl-c should not be prevented, q or esc could also act as "quit" actions.

**Please mention your node.js, yarn and operating system version.**

node 10.16.3
yarn 1.21.1
MacOS 10.14.6

**Comment by bob-lee** [comment]
using `v1.21.1` and `Ctrl-C` did exit.

**Comment by sgronblo** [comment]
Yes, it seems to work for me nowadays.
