### ISSUE TITLE
Yarn workspace does not propagate flags

### ISSUE THREAD

**Issue by thevojacek** [yarnpkg/yarn#7776]
When using yarn workspaces with run command, flags are not passes into executed command.

### How to reproduce: 
```bash
yarn workspace test_workspace run start -- \
  serverURL="hello" \
  awsAccessKey="world"
```

package.json file contents.
```
{
  "scripts":
  {
    "start": "node script.js""
  }
}
```

### Current behavior:
Flags are not passed into the running script.

### Expected behavior:
Flags should be passed.

### Environment
Node: 12.13.1
Yarn: 1.21.1
OS: macOS 10.14.6

**Comment by rally25rs** [comment]
confirmed against v1.21.1.

I'll try to see what's up with it. It's a bit tricky because `yarn` runs child process `yarn` runs child process `node scripts.js` so the flags have to get passed through a couple places.

**Comment by rally25rs** [comment]
@thevojacek as a workaround, if you remove the `--` then the parameters are passed correctly.
It looks like yarn trims off args after `--` for some commands, including `workspace`.

**Comment by thevojacek** [comment]
> @thevojacek as a workaround, if you remove the `--` then the parameters are passed correctly.
> It looks like yarn trims off args after `--` for some commands, including `workspace`.

Thank you for investigation!
