### ISSUE TITLE
yarn policies on Windows 10 generates invalid *nix paths

### ISSUE THREAD

**Issue by wegry** [yarnpkg/yarn#7777]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Using `yarn policies` on Windows generates a `yarn-path` in the `.yarnrc` file with backslashes. 

`.yarn\\releases\\yarn-1.21.1.js`

This breaks *nix boxes trying to use the same `.yarnrc`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Regardless of operating system, the `yarn-path` should contain forward slashes.

`.yarn/releases/yarn-1.21.1.js`

**Please mention your node.js, yarn and operating system version.**

Node@12.14.0, yarn@1.21.1, Windows 10/Ubuntu 18.04

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/pull/7862
