### ISSUE TITLE
yarn search

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#778]
There's currently an `npm search` which isn't so great. What do you all think of having `yarn search` which is a shortcut for opening `https://npms.io/search?q=<search-string>` using [npms.io](https://npms.io/).

\@atduarte @satazor

**Comment by tony19** [comment]
@jdalton Instead of opening a browser window/tab, I think `yarn search` should list the search results in the CLI perhaps using the [`npms` API](https://api-docs.npms.io/#api-Search-ExecuteSearchQuery).

**Comment by Daniel15** [comment]
>  I think yarn search should list the search results in the CLI perhaps using the npms API. 

I wonder whether that's worth the maintenance cost, given the site already exists. In general, a rich graphical interface like a website is always going to provide a better user experience than a CLI app.

**Comment by tony19** [comment]
> In general, for something like this where you want to search and browse through a listing or collection of things, a rich graphical interface like a website is always going to provide a better user experience than a CLI app.

I think that's somewhat subjective and probably depends on the amount of data presented. Plus, there's already a precedence for CLI-only results (i.e., `bower search` and `npm search`).

**Comment by kittens** [comment]
We've deliberately decided not to add these sorts of commands to Yarn. There's a lot of them that don't actually see much use and the maintenance burden isn't really worth it. If the functionality of the commands is so simple (just opening a browser) then you can just do it yourself. Thanks for the report!

**Comment by jdalton** [comment]
Ya, mainly wanted to show some :heart: for [npms.io](https://npms.io/) and figured yarn integration via opening a browser would help (yarn improving pkg installs & npmjs.io improving search).

**Comment by jdalton** [comment]
Related to https://twitter.com/mrmrs_/status/763481520791232512.

**Comment by satazor** [comment]
@jdalton Thank you it's an honour to have such an important member of the community suggesting npms.io. I tend to agree with @kittens, but if this project gets enough traction to actually "replace" npm (like lodash effectively replaced underscore for most devs), I think it's reasonable to have a search functionality. Many many developers still prefer to do these kind of tasks from the console.

**Comment by iarna** [comment]
FYI, we've documented our new search API (that builds on the npms.io folks work) over [here](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search), if you ever decide you want to fold that in.

**Comment by robclancy** [comment]
Lol is this for real? Such a big maintenance burden to dump search results from an API.

**Comment by mika76** [comment]
Personally I think this would be a great function. Why would I have to go all the way to the browser, open a specific page, search, copy paste a name of a package into the terminal I just came from, when all I wanted was to check what the exact name of the package for "bootswatch" was so I could run yarn add on it? 

I vote for this function 👍

**Comment by denizdogan** [comment]
For what it's worth, [npms.io has a CLI](https://github.com/npms-io/npms-cli) which you can install using `yarn global add npms` and then use like `npms search foobar`.

That being said, I do think that Yarn deserves its own built-in search. I can't imagine that it would lead to much maintenance work, it's a very simple function in comparison to the rest of Yarn.

**Comment by vinilios** [comment]
@denizdogan `npms` package has nothing to do with npms website. Please modify your post with the correct package name `npms-cli`.

**Comment by denizdogan** [comment]
@vinilios Oops, fixed

**Comment by danvk** [comment]
If you're specifically interested in packages with TypeScript type declarations, there's [dtsearch]:

```
$ npx dtsearch sprintf
   DLS NAME              TYPES             DESCRIPTION
533.3k sprintf           @types/sprintf    sprintf() for node.js
 47.4m sprintf-js        @types/sprintf-js JavaScript sprintf implementation
 82.9m extsprintf        @types/extsprintf extended POSIX-style sprintf
  2.1m ssf               <bundled>         Format data using ECMA-376 spreadsheet Format Codes
  1.6m printj            <bundled>         Pure-JS printf
  123k voca              @types/voca       The ultimate JavaScript string library
746.4k printf            <bundled>         Full implementation of the `printf` family in pure JS.
  1.5k sprintfjs         <bundled>         POSIX sprintf(3)-style String Formatting for JavaScript
   169 @jitesoft/sprintf <bundled>         sprintf function for javascript.
    94 stringd           <bundled>         A string variable parser for JavaScript
```

It uses the same Algolia search as yarnpkg.com. It's geared towards TS users but can search all npm packages with a flag (`-u`).

[dtsearch]: https://github.com/danvk/dtsearch

**Comment by janosh** [comment]
4.5 years on, perhaps [the deliberate decision](https://github.com/yarnpkg/yarn/issues/778#issuecomment-253146299) not to add `yarn search` deserves to be revisited?

**Comment by merceyz** [comment]
`yarn search` has been added in Yarn v2+ https://yarnpkg.com/cli/search
