### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by abouzeyd** [yarnpkg/yarn#7780]
**Which operating system are you using:**

windows 10
**Please describe the steps you took when trying to install Yarn and what went wrong:**
$ yarn start
yarn run v1.19.1
error Couldn't find a package.json file in "D:\\workspace\\front-end"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rally25rs** [comment]
Is there a `package.json` file in `D:\workspace\front-end`?

**Comment by abouzeyd** [comment]
Yes

**Comment by olingern** [comment]
Closing this one for now. Ping us here @abouzeyd if there's still an issue.

**Comment by abouzeyd** [comment]
Ping

**Comment by olingern** [comment]
Hi @abouzeyd 

1. Run your command
2. Run `ls` from that directory
3. Paste the output here via Windows' snipping tool.

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
