### ISSUE TITLE
The size of the npm_package_noticeText env variable is too large for node.js

### ISSUE THREAD

**Issue by bobbrow** [yarnpkg/yarn#7783]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Starting with Node 12.11, they use libuv to lookup environment variables.  Yarn creates a variable called `npm_package_noticeText` which contains the full contents of a package's NOTICE.txt file and can exceed the max size allowable by libuv.  This causes yarn commands to fail when packaging the [CMake Tools extension for VS Code](https://github.com/microsoft/vscode-cmake-tools).

**If the current behavior is a bug, please provide the steps to reproduce.**
**Repro steps:**
* **Prerequisites:**
  * Install node.js version 12.11 or newer ([download](https://nodejs.org/en/download/))
  * Install yarn ([download](https://yarnpkg.com/lang/en/docs/install/#windows-stable))
  * Run `npm install -g vsce`
* Create a folder where you can clone the extension repository (e.g. `c:\git`)
* In that directory run: `git clone https://github.com/microsoft/vscode-cmake-tools.git`
* Run: `cd vscode-cmake-tools`
* Run: `vsce package --yarn`

**What is the expected behavior?**
* vsce should create a cmake-tools-[version].vsix file in the `vscode-cmake-tools` folder

**Actual Behavior:**
* node crashes and the following output is displayed:
```
Executing prepublish script 'yarn run vscode:prepublish'...
ERROR  Command failed: yarn run vscode:prepublish
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1476
error Command failed with exit code 3221226505.
```

**Please mention your node.js, yarn and operating system version.**
node.js >= 12.11
yarn = 1.21.1
OS = Windows 10 18362

**Comment by dbjorge** [comment]
We just got hit by this as well. The description matches what I see with:

* node.js = v12.16.2
* yarn = v1.22.4
* OS = Windows 10 18362.778

However, in Ubuntu build machine in an Azure DevOps Pipeline, the same issue manifests with a different error message:

```
error An unexpected error occurred: "spawn E2BIG".
```

*node.js = v12.16.3
* yarn = v1.22.4
* OS = ubuntu-18.04

and in an older build machine:

* node.js = v12.13.0
* yarn = v1.17.1
* OS = ubuntu-16.04

Likely related to #5264, #5420

**Comment by dbjorge** [comment]
Note, it's not just files named `NOTICE.txt` that cause the issue; any file named notice or which starts with "notice.":

https://github.com/yarnpkg/yarn/blob/a75dbe36ca7f6d881d291a7231676d00d523bb39/src/util/normalize-manifest/fix.js#L331-L335

I'm not super familiar with Yarn's code, but based on #7419 I suspect it might be as simple as adding `noticeText` to the list of ignored manifest keys at

https://github.com/yarnpkg/yarn/blob/a75dbe36ca7f6d881d291a7231676d00d523bb39/src/util/execute-lifecycle-script.js#L21-L27

**Comment by bobbrow** [comment]
This appears to be fixed now.

**Comment by kevinlul** [comment]
This still happens in Node 14.18.2 and yarn 1.22.17 with a large `NOTICE` file.
