### ISSUE TITLE
Creating a project with yarn fails

### ISSUE THREAD

**Issue by xkmy** [yarnpkg/yarn#7784]
Environment: windows10 yarn version: 1.21.1
Question: When I use yarn to create a vue-cli project and create-react-app project, it prompts me that the installation failed. I don't know what is going on, because there is no obvious error message in the console. Can you help me ? Thank you! The following is the error message:

![image](https://user-images.githubusercontent.com/44152845/71543479-2b8e0f00-29ae-11ea-88ed-b36645384be7.png)

**Comment by olingern** [comment]
Please post your `package.json` and node version
