### ISSUE TITLE
yarn pkg duplicate logo in npm

### ISSUE THREAD

**Issue by jdalton** [yarnpkg/yarn#779]
The package on npm has a duplicated logo:
https://www.npmjs.com/package/yarn

<img width="1135" src="https://cloud.githubusercontent.com/assets/4303/19294064/65fb4d1e-8fde-11e6-8f64-fded42f684a4.png">

**Comment by ljharb** [comment]
twice the kittehs, twice the funs

**Comment by jdalton** [comment]
![](https://cloud.githubusercontent.com/assets/4303/19294169/2ff39c84-8fdf-11e6-9a18-2616f7b77769.png)

**Comment by Daniel15** [comment]
Looks like the first one is the "description" while the second one is the readme.

**Comment by sindresorhus** [comment]
Should be reported at https://github.com/npm/marky-markdown

**Comment by Daniel15** [comment]
@sindresorhus - Why so? I think we just need to set a `description` in `project.json` so npm uses that rather than inferring it from the readme.

**Comment by sindresorhus** [comment]
@Daniel15 Because they should not infer an image as the description. That's clearly a bug.

**Comment by Daniel15** [comment]
Ahh, is `marky-markdown` the library that's inferring the description based on the readme? Initially when I looked at it, it just looked like a Markdown parser, but maybe it also infers description based on readme and I missed that part 😄

**Comment by sindresorhus** [comment]
I believe so. It's what they use to cleanup and npmify the markdown. I've posted there about similar issues previously.

**Comment by OmgImAlexis** [comment]
Since the original issue is fixed this can be closed.
