### ISSUE TITLE
[Bug] yarn not use registry in .yarnrc

### ISSUE THREAD

**Issue by NoDocCat** [yarnpkg/yarn#7792]
### version:
  + System: Win10 1909
  + Nodejs: v12.14.0
  + Yarn: 1.21.1

### behavior:
If your config not alike registry in .yarnrc and .npmrc, yarn always use registry config in .npmrc to get package. And if your use `yarn config get registry`, the result obtained is correct(Same as .yarnrc).
In other words: When install package, the config in .yarnrc ignored.

### expected:
.yarnrc should take precedence over .npmrc

**Comment by NoDocCat** [comment]
My .npmrc:
```
home=https://npm.taobao.org
registry=https://registry.npm.taobao.org/
msvs_version=2019
```

My .yarnrc:
```
registry "http://r.cnpmjs.org/"
cache-folder "C:\\Scoop\\apps\\yarn\\current\\cache"
global-folder "C:\\Scoop\\apps\\yarn\\current\\global"
prefix "C:\\Scoop\\apps\\yarn\\current\\global"
yarn-offline-mirror "C:\\Scoop\\apps\\yarn\\current\\mirror"
```

if i use `yarn config get registry`:
```
http://r.cnpmjs.org/
```

if i use `yarn info react`:
```
 "dist: {
    shasum: '0c0a9c6a142429e3614834d5a778e18aa78a0b83',
    size: 59620,
    tarball: 'https://registry.npm.taobao.org/react/download/react-16.12.0.tgz'
  }
```

**Comment by paul-soporan** [comment]
Closing as we stopped supporting both `.npmrc` and `.yarnrc` in v2 in favor of `.yarnrc.yml`.

https://yarnpkg.com/getting-started/migration

**Comment by xiezht** [comment]
Same issue i come across when using yarn 1.22.10. 
And i think maybe this issue shouldn't be closed, as not everyone are ready to upgrade yarn to v2. 
It seems to be treated as a bug for v1, instead of a feature for v2 ???
