### ISSUE TITLE
[Bug] Yarn standalone CLI command

### ISSUE THREAD

**Issue by carloswhite** [yarnpkg/yarn#7796]
### My Setup:
- **System**:  MacOS Catalina 10.15.2
- **Node.js**: v12.14.0
- **Yarn**: 1.21.1

### Behavior:
I accidentally executed 'yarn' with no flags or params whatsoever in my system's root folder (Users) which led yarn to create a folder called "node_modules" and a file named "yarn.lock." 

### Expected:
I'd like to remove those via command line which is not possible due to the command "yarn remove [package name]" stating that I must provide a package name. Since I haven't initialized yarn on purpose, I didn't provide a package name and as such can't delete a no-name project per se.

**Comment by illuminist** [comment]
You can manually remove "node_modules" and "yarn.lock".

Command `rm -rf node_modules yarn.lock` should do the job

**Comment by carloswhite** [comment]
Sounds good. Thank you for your response! I'm closing this issue now.
