### ISSUE TITLE
Yarn does not install latest version on Windows 10

### ISSUE THREAD

**Issue by Legends** [yarnpkg/yarn#7802]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

I had 1.7.0 installed. Downloaded the latest msi package for windows.
Installed it.
`yarn -v`  still shows v1.7.0.

Uninstalled yarn. Reinstalled using latest msi.
Still shows version 1.7.0 !

**What is the expected behavior?**
to see v1.21.1
**Please mention your node.js, yarn and operating system version.**
Win10, node v12.13.0, yarn is still on 1.7.0

**Comment by mikecousins** [comment]
I think you've got something else going on because it works fine on my Windows 10 machines.

**Comment by Legends** [comment]
The weird thing is, I have uninstalled yarn, opened a new console window: `yarn -v` still shows `v1.7.0`
It's actually not installed anymore...

**Comment by Legends** [comment]
Hm, I guess my VS2019 Developer command prompts are messed up.
The path env variable is set correctly.

Strange...

**Comment by Legends** [comment]
I've deleted the following two files:

> C:\Users\Admin\AppData\Roaming\npm\yarn
> C:\Users\Admin\AppData\Roaming\npm\yarn.cmd


Now it shows the version number correctly.
