### ISSUE TITLE
warning yarn install

### ISSUE THREAD

**Issue by karlben** [yarnpkg/yarn#7803]
i have same warning when i run  yarn install 
i use node v12.14.0
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning mini-css-extract-plugin@0.4.2: Invalid bin field for "mini-css-extract-plugin".
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

**Comment by rally25rs** [comment]
These are warnings that you can ignore.

The `mini-css-extract-plugin` specifies
```
"bin": "",
```
which is not a valid `bin` entry, but that is an issue with that package and not something that you can fix during `yarn install`.

The `fsevents` warnings are letting you know that `fsevents` is not compatible with your OS and is not going to be installed, but is an "optional" dependency so it won't fail the install. This is fine, fsevents is only needed for some OS's.

**Comment by karlben** [comment]
@rally25rs 
thank you for the information for the moment I took a version of yarn (1.19.2) lower than the current one in order to avoid the warning
