### ISSUE TITLE
Download of node-sass binary fails with 404

### ISSUE THREAD

**Issue by tholu** [yarnpkg/yarn#7806]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-79_binding.node":

HTTP error 404 Not Found
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn install --verbose`

**What is the expected behavior?**
Successfully download the `node-sass` binary, picking the right version 4.13 for Node 13 (https://github.com/sass/node-sass/releases/tag/v4.13.0)

**Please mention your node.js, yarn and operating system version.**
node.js v13.6.0
yarn v1.21.1
MacOS 10.15.3 Beta (19D49f)

**Comment by rally25rs** [comment]
This is not part of yarn's install process. This is related to `node-sass`'s install script which does that file download. I would recommend [opening an issue under node-sass](https://github.com/sass/node-sass/issues).
