### ISSUE TITLE
yarn.lock is not working with yarn workspaces

### ISSUE THREAD

**Issue by hingermayank** [yarnpkg/yarn#7818]
**Do you want to request a *feature* or report a *bug*?**
It might not be a bug but my misunderstanding of how yarn lock works with yarn workspaces.

**What is the current behavior?**
yarn.lock is not working with yarn workspaces. I am using yarn workspaces for my project. I have a dependency in a workspace with a caret/tilde before its version. But whenever I run yarn install --pure-lockfile or yarn install --frozen-lock file, the dependency gets updated to latest version and does not honour  yarn.lock whenever the library owner publishes a new version. This leads to breaking my app's build due to non-compatible changes in newer version.

**If the current behavior is a bug, please provide the steps to reproduce.**

[Repo Link](https://gitlab.com/hingermayank/yarnlock-workspace-test)
I have created a sample repo with setup. Please follow the following steps to reproduce:
1) Clone the repo.
2) Do fresh yarn install.
3) Now add caret to the dependency "cross-env" mentioned in workspace-b.
4) Run yarn install again (with --pure-lockfile or --frozen-lockfile)
5) Check yarn.lock doesn't get updated but in node modules new version is installed.

**What is the expected behavior?**
yarn install --frozen-lockfile should fail.

**Please mention your node.js, yarn and operating system version.**
Node:v8.15.0
yarn: 1.21.1
OS: MacOS mojave (10.14.5)

**Comment by rally25rs** [comment]
Confirmed on v1.21.1

Interestingly, `--frozen-lockfile` seems to make yarn completely ignore the lockfile. You can even edit the lockfile and replace the contents with invalid data, and `yarn install --frozen-lockfile` will still run successfully 😕

**Comment by hingermayank** [comment]
Hi @rally25rs,

Thanks for a quick response. 

So even with the previous versions, is there a way to make yarn.lock work for the workspaces? I tried with an older version but still the issue is same.

**Comment by russell-dot-js** [comment]
Also experiencing this... frozen-lockfile will prevent yarn from updating the lockfile, but it won't complain if the lockfile is insufficient to satisfy package.json

**Comment by quitedensepoint** [comment]
I tested this with yarn 1.10.1 just now, same issue. I don't think this has ever worked.

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Comment by ryanklarhoelter** [comment]
@merceyz Could you please give more context? How is this being solved? It doesn't seem to be.
