### ISSUE TITLE
Permission denied mkdir. Does not work with sudo either.

### ISSUE THREAD

**Issue by AmbuSreedharan** [yarnpkg/yarn#7819]
Version 1.21.1

**What is the current behavior?**
Upon running install, I get 'EACCES: permission denied, mkdir '/home/hudson/inmem_workspace/node_modules/browserify-cache-api/node_modules'
It's not deterministic as to which package gets the above error. There isn't a permission issue. The whole system uses just this one user. The user infact made the node_modules directory so I dont see why permission is an issue.

The install runs fine on my mac but stops working when I try on a linux machine. 

Expected Behavior:
I expect install to not have permission issues within folders created by Yarn

**Comment by olingern** [comment]
> There isn't a permission issue

Your user may have the correct rights, but if that's the case your folders probably do not have correct read/writes. This is most likely not a Yarn issue. If you can demonstrate correct read/write access via `ls -ld`, I'm happy to reopen
