### ISSUE TITLE
Yarn installs node-pre-gyp for unknown reason

### ISSUE THREAD

**Issue by stof** [yarnpkg/yarn#7827]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. take the `package.json` from https://gist.github.com/stof/230b1c1fad445339aab8e58dc9b525d6
2. run `yarn`. This step produces a yarn.lock with the buggy content. For an unknown reason, it adds a `node-pre-gyp@*` requirement somewhere (but `yarn why node-pre-gyp` says it cannot find a match)
3. run `yarn add temp`
4. run `yarn remove temp`. the package.json is now the same than the initial one, but the yarn.lock is the fixed one.

**What is the expected behavior?**

The yarn.lock should not reference `node-pre-gyp:*` and match the fixed one that I get when running the add/remove dance.

The fact that 2 identical package.json produce a different output depending on whether I run `yarn` or `yarn add` + `yarn remove` makes me question the algorithm to resolve dependencies.

**Please mention your node.js, yarn and operating system version.**

node 12.14.1
yarn 1.21.1
Ubuntu 18.04.3

**Comment by stof** [comment]
note that using `yarn --no-scripts` rather than `yarn` at the second step still produces the same result.

**Comment by jjleahy** [comment]
I believe that this is the same as #7770. https://github.com/yarnpkg/yarn/issues/7770#issuecomment-567314063

**Comment by stof** [comment]
this indeed look the same.

**Comment by olingern** [comment]
Since @rally25rs has done a deeper dive on this issue on #7770, I'm going to close this. Please follow there for updates.
