### ISSUE TITLE
Wrong script runed after install

### ISSUE THREAD

**Issue by chemzqm** [yarnpkg/yarn#783]
**Do you want to request a *feature* or report a *bug*?**

Should be a bug.

**What is the current behavior?**

`propublish` script is runned after I use yarn

<img width="377" alt="screen shot 2016-10-12 at 9 41 56 am" src="https://cloud.githubusercontent.com/assets/251450/19294564/7a925cea-9060-11e6-90a0-8eced4e246a0.png">

This is scripts part of my `package.json`:
``` json
  "scripts": {
    "postinstall": "webpack",
    "prepublish": "webpack --config webpack.prod.js"
  },
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn` command

**What is the expected behavior?**

It should run postinstall script.

**Please mention your node.js, yarn and operating system version.**

node v6.0
MacOs
yarn 0.15.1

**Comment by FLGMwt** [comment]
Running `prepublish` is correct in terms of npm compatibility (see https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/install.js#L736), but you're right, postinstall should *also* be run immediately before prepublish.
