### ISSUE TITLE
`yarn add` doesn't ask for installation directory whereas `npm install` does

### ISSUE THREAD

**Issue by Puspendert** [yarnpkg/yarn#7833]
I am following an article where I need to do `npm install xxxxx` for some operation.
running `npm install --save fomantic-ui semantic-ui-react` installs the modules and after installation it asks me where should I install it. But since my project is built using `yarn`, I need to `yarn add fomantic-ui semantic-ui-react`. But with `yarn`, the directory selection and installation get automatically. Ideally, it should ask the user for choosing a directory.

Here is the visual view of the terminal:
https://imgur.com/gallery/UlbbEhX

**If the current behavior is a bug, please provide the steps to reproduce.**
1. yarn create react-app test-app
2. cd test-app
3. yarn fomantic-ui semantic-ui-react

node: `v12.6.0`
yarn: `1.17.3`
OS: `macOS 10.14.6`

**Comment by Puspendert** [comment]
Any help on this please?

**Comment by paul-soporan** [comment]
Closing as that is an issue with semantic-ui (which creates the prompt), not with Yarn.
