### ISSUE TITLE
yarnpkg.com certificate error

### ISSUE THREAD

**Issue by hfjallemark** [yarnpkg/yarn#7835]
https://yarnpkg.com/ is reporting a certificate error:

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for yarnpkg.com. The certificate is only valid for the following names: *.netlify.com, netlify.com
>
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by ron23** [comment]
Same here

**Comment by Kartstig** [comment]
Failing CI output:

![image](https://user-images.githubusercontent.com/2031422/73040491-dc5dc180-3e27-11ea-84e1-5f858815342a.png)

**Comment by hfjallemark** [comment]
Seems to work now.

**Comment by aaronjensen** [comment]
Good news! the cert error looks fixed. Bad news, `install.sh` is gone... Looks like they're launching `next.yarnpkg.com` and haven't got their dns pointing correctly.

**Comment by aaronjensen** [comment]
fwiw, https://legacy.yarnpkg.com/install.sh is there...

**Comment by ron23** [comment]
Open the ticket?

**Comment by aaronjensen** [comment]
It now looks to be fixed with a redirect, so I think we're good.
