### ISSUE TITLE
Error with different jasmine versions for a monorepo with angular and stencil

### ISSUE THREAD

**Issue by scaljeri** [yarnpkg/yarn#7837]
**Report a *bug**

**What is the current behavior?**
I'm using yarn workspaces and I currently have  in there an angular and stencil project.  When I try to build the Sencil project it fails, giving me a lot of typescript errors complaining about incorrect interfaces

```
[ ERROR ]  TypeScript: ../../node_modules/@types/jasmine/ts3.1/index.d.ts:16:1
           Definitions of the following identifiers
           conflict with those in another file: describe,
           fdescribe, xdescribe, it, fit, xit, beforeEach,
           afterEach, beforeAll, afterAll, expect,
           CustomEqualityTester, CustomMatcherFactory,
           DEFAULT_TIMEOUT_INTERVAL

     L16:  type ImplementationCallback = (() => Promise<any>) | ((done: DoneFn) => void);
     L17:  type InferableFunction = (...args: any[]) => any;

[ ERROR ]  TypeScript: ../../node_modules/@types/jasmine/ts3.1/index.d.ts:250:9
           Duplicate number index signature.

    L249:      length: number;
    L250:      [n: number]: T;
    L251:  }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a public repo [here](https://github.com/scaljeri/flow-based-programming). To reproduce do

    $> git clone https://github.com/scaljeri/flow-based-programming.git
    $> cd flow-based-programming
    $> yarn
    $> cd packes/fbp  (this is the Stencil project)
    $> yarn build

**What is the expected behavior?**
It should compile fine. If, for example, I remove `@types/jest` from the stencil's package.json (`./packages/fbp/package.json`) and run `yarn` from the root again it will compile fine. I disabled hoisting too but that didn't help.

**Please mention your node.js, yarn and operating system version.**
node: v12.3.1
yarn: 1.21.1

**Comment by merceyz** [comment]
Closing as an external issue as this is not an issue with Yarn
