### ISSUE TITLE
Internal Error: Assertion failed: The package should have been detected as part of the project

### ISSUE THREAD

**Issue by admmasters** [yarnpkg/yarn#7838]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Trying to run a yarn command is yielding the error:
"Internal Error: Assertion failed: The package should have been detected as part of the project"
e.g. yarn add lodash

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create a new folder
2) run ``yarn init`
3) run ``yarn add lodash`
4 Observer error "Internal Error: Assertion failed: The package should have been detected as part of the project"

**What is the expected behavior?**
Yarn to have added lodash to the package

**Please mention your node.js, yarn and operating system version.**
Node 12.13.1
OSX 10.15.2
Yarn 2.0.0-rc.27

**Comment by admmasters** [comment]
Will open in https://github.com/yarnpkg/berry/issues

**Comment by robrecord** [comment]
Can you please link to the issue you created admmasters?
