### ISSUE TITLE
Yarn run config: Error: Couldn't find a package.json file in "/Users/myname"

### ISSUE THREAD

**Issue by Pierstein** [yarnpkg/yarn#7839]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have installed Yarn.

Following a guide, I now need to launch `yarn run config`, but with any command I try it gives this error:

error Couldn't find a package.json file in "/Users/Pier"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please help?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I actually don't really know. I think it's supposed to launch?

**Please mention your node.js, yarn and operating system version.**
Yarn v1.21.1
Node.js v13.7.0
MacOS Catalina v10.15

**Comment by Pierstein** [comment]
Now I get this:

Piers-Air:~ Pier$ yarn start
yarn run v1.21.1
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by olingern** [comment]
It looks like you're having some issues starting a new project. Please visit the docs to learn how:

https://legacy.yarnpkg.com/en/docs/usage

**Comment by freddydumont** [comment]
@olingern I think this is related to having a special character in the home path. Notice the path in the error: `Couldn't find a package.json file in "/Users/Pier"`.

Now see a more complete example:
```
yarn run v1.22.4
$ '/Users/frederick 1/dev/redwoodblog/node_modules/.bin/rw' dev
  ✔ Generating the Prisma client...
error Couldn't find a package.json file in "/Users/frederick"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that yarn can't handle the space properly.

**Comment by Danutzz8** [comment]
same...

$ yarn start
yarn run v1.22.10
error Couldn't find a package.json file in "F:\\Visual Studio Code\\React Apps - ZTM\\Hooks"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Simonyan01** [comment]
yarn run v1.22.19sktop\React>yarn create-react-app apps
error Couldn't find a package.json file in "C:\\Users\\starm\\desktop\\React"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\starm\desktop\React>

**Comment by AdnanSattar** [comment]
`yarn init` might help incase starting new project

**Comment by kemotrush** [comment]
Hy all i was able to start it but when i getting an answer its not showing only blocks and @#$@%# . looks like i missing something
any idea ??

**Comment by shockwaveriderz** [comment]
this is what I get running yarn build 👍 


pi@raspberrypi:~/go/bin/grafana-plugins/mqtt-datasource $ yarn build
yarn run v1.22.19
$ rm -rf dist && grafana-toolkit plugin:build && mage build:backend

⚠️  DEPRECATED. This command is deprecated and will be removed in v10. ⚠️
Please migrate to grafana create-plugin https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin

  Using Node.js v18.16.0
  Using @grafana/toolkit v9.5.2
✔ Preparing
✔ Linting
 FAIL  src/handleEvent.test.ts
  ● Test suite failed to run

    TypeError: Cannot redefine property: window

      at Object.<anonymous> (node_modules/jest-canvas-mock/lib/index.js:21:17)
      at async TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at async _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at async runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.067 s
Ran all test suites with tests matching "".
✖ Tests failed
  Trace: Error: Tests failed
      at /home/shock/go/bin/grafana-plugins/mqtt-datasource/node_modules/@grafana/toolkit/src/cli/tasks/plugin/tests.js:29:19
      at Generator.next (<anonymous>)
      at fulfilled (/home/shock/go/bin/grafana-plugins/mqtt-datasource/node_modules/tslib/tslib.js:115:62)
      at /home/shock/go/bin/grafana-plugins/mqtt-datasource/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:20:21
      at Generator.throw (<anonymous>)
      at rejected (/home/shock/go/bin/grafana-plugins/mqtt-datasource/node_modules/tslib/tslib.js:116:69)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

this is on Raspberry pi OS 64 bit ARM

Can anybody help? If there's any information you might need just ask.

**Comment by LLong0218** [comment]
check your user name whether there exists a filefolder after '~', like this Username@mymachine:~/filefolder$

**Comment by rehan-affair37** [comment]
@freddydumont https://reactdev.space/questions/creating-a-reactjs-component-to-provide-a-service

**Comment by athinaok** [comment]
Do not use symbols in DB password.



[Install on synology container](https://mariushosting.com/how-to-install-linkwarden-on-your-synology-nas/)

**Comment by ops120** [comment]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: \\?\C:\Users\\AppData\...\6774a13b-02b5-49c7-a27e-bea9e136c0b7.tmp**.node is not a valid Win32 application.**
    at process.func [as dlopen] (nodeelectron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (nodeelectron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (nodeelectron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (C:\Program Files\HeyGem\resources\app.asar\node_modules\bindings\bindings.js:112:48)
    at new Database (C:\Program Files\HeyGem\resources\app.asar\node_modules\better-sqlite3\lib\database.js:48:64)

我这个还不太一样，--x64打出来还是报这个错
