### ISSUE TITLE
Installation Problem: Add latest.zip because on Windows, we can't install several yarn with the MSI installer

### ISSUE THREAD

**Issue by A-312** [yarnpkg/yarn#7841]
**Which operating system are you using:** Windows

**Please describe the steps you took when trying to install Yarn and what went wrong:** I use virtualenv for my packages, and I install yarn with [yarn-1.21.1.msi](https://legacy.yarnpkg.com/latest.msi) in my virtualenv but `.msi` installer doesn't allow multiple installation (e.g: `package1/virtualenv/yarn` and `package2/virtualenv/yarn` can't be make with `.msi`) .

If I want to use local install (in virtualenv), I can't use the .msi installer to install yarn in multiple virtualenv folder. Can you add a .zip package `https://legacy.yarnpkg.com/latest.zip` ?

**Comment by Daniel15** [comment]
We have a tarball (latest.tar.gz); can you use that?

**Comment by A-312** [comment]
@Daniel15 There is no native tools to *unzip* tar.gz file. If I really want to use `.tar.gz`, I have to use 7zip [like this example](https://stackoverflow.com/questions/38776137/native-tar-extraction-in-powershell)

**Comment by Daniel15** [comment]
Another option is to download the JS file. You can execute that directly using Node.js.

Yet another option is to extract the  MSI using msiexec (eg. see https://thebackroomtech.com/2007/08/23/howto-extract-files-from-a-msi-file-using-the-windows-command-line/)

**Comment by A-312** [comment]
Can I download the latest js file ?

**Comment by Daniel15** [comment]
I just added a `latest.js` redirect: https://classic.yarnpkg.com/latest.js

Although, I'd recommend hard-coding the version number so you always use the same one. You can use this URL: https://classic.yarnpkg.com/downloads/1.12.1/yarn-1.12.1.js

**Comment by A-312** [comment]
I know for dependencies of npm package is essential to use fixed version, but for an application like yarn ?

**Comment by A-312** [comment]
msiexec work fine! Thanks you :)
