### ISSUE TITLE
Yarn Install trouble with network connection 

### ISSUE THREAD

**Issue by Ongeziwe-Mbana** [yarnpkg/yarn#7842]
![image](https://user-images.githubusercontent.com/44267829/73139159-cd6b4f00-4073-11ea-92eb-3d797fd60641.png) 
![image](https://user-images.githubusercontent.com/44267829/73139175-f390ef00-4073-11ea-852e-0ff53bf50676.png)

yarn Install error below is the snippet of the bug report:
 `
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js install

PATH: 
  C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\Ozzy\AppData\Local\Microsoft\WindowsApps;C:\Users\Ozzy\AppData\Local\Yarn\bin;C:\Users\Ozzy\AppData\Roaming\npm

Yarn version: 
  1.21.1

Node version: 
  12.14.1

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@babel/plugin-syntax-dynamic-import/-/plugin-syntax-dynamic-import-7.2.0.tgz: tunneling socket could not be established, statusCode=400
      at ClientRequest.onConnect (C:\Program Files (x86)\Yarn\lib\cli.js:152140:19)
      at Object.onceWrapper (events.js:313:26)
      at ClientRequest.emit (events.js:223:5)
      at Socket.socketOnData (_http_client.js:490:11)
      at Socket.emit (events.js:223:5)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:290:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

npm manifest: 
  {
    "name": "memetics.mogli",
    "displayName": "Mogli",
    "version": "0.0.2",
    "private": true,
    "scripts": {
      "start": "node node_modules/react-native/local-cli/cli.js start",
      "rn-nodeify": "github:tradle/rn-nodeify",
      "test": "jest",
      "pre-bui": "npm react-native start",
      "run-prod-and-mac": "export ENVFILE=.env.prod && react-native run-android --variant=release",
      "run-and-mac": "export ENVFILE=.env.ios.and.dev &&  react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android",
      "run-prod-and-debug": "export ENVFILE=.env.prod &&  react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android",
      "bui-and-mac": "export ENVFILE=.env.ios.and.dev &&  react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew clean assembleDebug",
      "bui-sta-and-mac": "export ENVFILE=.env.preprod &&  react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew clean assembleDebug",
      "bui-prod-and-mac": "export ENVFILE=.env.prod && rm -rf android/app/build && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew clean assembleRelease && cd ../",
      "run-ios-mac": "export ENVFILE=.env.ios.dev && react-native run-ios",
      "run-prod-ios-mac": "export ENVFILE=.env.prod && react-native run-ios",
      "pre-xco": "export ENVFILE=.env.prod && react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios",
      "run-sta-ios-mac": "export ENVFILE=.env.preprod && react-native run-ios",
      "android-dev": "SET ENVFILE=.env.dev && react-native run-android",
      "android-staging": "SET ENVFILE=.env.preprod && react-native run-android",
      "android-prod": "SET ENVFILE=.env.prod && react-native run-android",
      "build-android-prod": "SET ENVFILE=.env.prod && cd android && ./gradlew assembleRelease && cd ..",
      "build-android-preprod": "SET ENVFILE=.env.preprod && cd android && ./gradlew assembleRelease && cd ..",
      "sign-android": "",
      "bundle": "react-native bundle --platform android --dev false  --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
      "bundle-dev": "export ENVFILE=.env.preprod && react-native bundle --platform android --dev true  --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res"
    },
    "dependencies": {
      "@babel/plugin-syntax-dynamic-import": "^7.2.0",
      "@react-native-community/async-storage": "^1.6.2",
      "@react-native-community/geolocation": "^1.4.2",
      "@tradle/react-native-http": "^2.0.1",
      "appcenter": "2.3.0",
      "appcenter-analytics": "2.3.0",
      "appcenter-crashes": "2.3.0",
      "assert": "^1.1.1",
      "axios": "^0.18.0",
      "browserify-zlib": "^0.1.4",
      "console-browserify": "^1.1.0",
      "constants-browserify": "^1.0.0",
      "crypto": "^1.0.1",
      "dns.js": "^1.0.1",
      "domain-browser": "^1.1.1",
      "events": "^1.0.0",
      "expo-cli": "^2.3.8",
      "https-browserify": "0.0.1",
      "path-browserify": "0.0.0",
      "process": "^0.11.0",
      "punycode": "^1.2.4",
      "querystring-es3": "^0.2.1",
      "react": "16.8.3",
      "react-native": "0.59.4",
      "react-native-camera": "^1.1.0",
      "react-native-carousel": "^0.11.0",
      "react-native-cli": "^2.0.1",
      "react-native-config": "^0.11.7",
      "react-native-crypto": "^2.1.2",
      "react-native-elements": "1.1.0",
      "react-native-google-maps-directions": "^2.1.0",
      "react-native-google-static-map": "^0.1.13",
      "react-native-http": "tradle/react-native-http#834492d",
      "react-native-image-crop-picker": "^0.24.1",
      "react-native-image-picker": "^0.28.1",
      "react-native-level-fs": "^3.0.0",
      "react-native-material-bottom-navigation": "^0.9.0",
      "react-native-os": "^1.0.1",
      "react-native-qrcode": "^0.2.6",
      "react-native-qrcode-scanner": "^1.1.0",
      "react-native-qrcode-svg": "^5.3.2",
      "react-native-randombytes": "^3.5.3",
      "react-native-rename": "^2.4.1",
      "react-native-sideswipe": "^1.4.2",
      "react-native-simple-modal-picker": "^0.1.0",
      "react-native-snap-carousel": "^3.7.0",
      "react-native-svg": "^9.13.3",
      "react-native-tcp": "^3.2.1",
      "react-native-udp": "^2.1.0",
      "react-native-vector-icons": "^6.6.0",
      "react-navigation": "^1.5.8",
      "reactotron-react-native": "^4.0.2",
      "readable-stream": "^1.0.33",
      "stream": "^0.0.2",
      "stream-browserify": "^1.0.0",
      "string_decoder": "^0.10.31",
      "timers-browserify": "^1.0.1",
      "tty-browserify": "0.0.0",
      "url": "^0.10.3",
      "util": "^0.10.4",
      "vm-browserify": "0.0.4"
    },
    "devDependencies": {
      "@babel/core": "^7.4.3",
      "@babel/runtime": "^7.4.3",
      "babel-jest": "^24.7.1",
      "jest": "^24.7.1",
      "metro-react-native-babel-preset": "^0.53.1",
      "react-test-renderer": "16.8.3",
      "rn-nodeify": "mvayngrib/rn-nodeify"
    },
    "jest": {
      "preset": "react-native"
    },
    "react-native": {
      "zlib": "browserify-zlib",
      "console": "console-browserify",
      "constants": "constants-browserify",
      "crypto": "react-native-crypto",
      "dns": "dns.js",
      "net": "react-native-tcp",
      "domain": "domain-browser",
      "http": "react-native-http",
      "https": "https-browserify",
      "os": "react-native-os",
      "path": "path-browserify",
      "querystring": "querystring-es3",
      "fs": "react-native-level-fs",
      "_stream_transform": "readable-stream/transform",
      "_stream_readable": "readable-stream/readable",
      "_stream_writable": "readable-stream/writable",
      "_stream_duplex": "readable-stream/duplex",
      "_stream_passthrough": "readable-stream/passthrough",
      "dgram": "react-native-udp",
      "stream": "stream-browserify",
      "timers": "timers-browserify",
      "tty": "tty-browserify",
      "vm": "vm-browserify",
      "tls": false
    },
    "rnpm": {
      "assets": [
        "resources/fonts"
      ]
    },
    "browser": {
      "zlib": "browserify-zlib",
      "console": "console-browserify",
      "constants": "constants-browserify",
      "crypto": "react-native-crypto",
      "dns": "dns.js",
      "net": "react-native-tcp",
      "domain": "domain-browser",
      "http": "react-native-http",
      "https": "https-browserify",
      "os": "react-native-os",
      "path": "path-browserify",
      "querystring": "querystring-es3",
      "fs": "react-native-level-fs",
      "_stream_transform": "readable-stream/transform",
      "_stream_readable": "readable-stream/readable",
      "_stream_writable": "readable-stream/writable",
      "_stream_duplex": "readable-stream/duplex",
      "_stream_passthrough": "readable-stream/passthrough",
      "dgram": "react-native-udp",
      "stream": "stream-browserify",
      "timers": "timers-browserify",
      "tty": "tty-browserify",
      "vm": "vm-browserify",
      "tls": false
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  "@babel/code-frame@7.0.0":
    version "7.0.0"
    resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8"
    integrity sha512-OfC2uemaknXr87bdLUkWog7nYuliM9Ij5HUcajsVcMCpQrcLmtxRbVFTIqmcSkSeYRBFBRxs2FiUqFJDLdiebA==
    dependencies:
      "@babel/highlight" "^7.0.0"
  
  "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.0.0-beta.44", "@babel/code-frame@^7.5.5":
    version "7.5.5"
    resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.5.5.tgz#bc0782f6d69f7b7d49531219699b988f669a8f9d"
    integrity sha512-27d4lZoomVyo51VegxI20xZPuSHusqbQag/ztrBC7wegWoQ1nLREPVSKSW8byhTlzTKyNE4ifaTA6lCp7JjpFw==
    dependencies:
      "@babel/highlight" "^7.0.0"
  
  "@babel/core@^7.0.0", "@babel/core@^7.1.0", "@babel/core@^7.4.3":
    version "7.6.2"
    resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.6.2.tgz#069a776e8d5e9eefff76236bc8845566bd31dd91"
    integrity sha512-l8zto/fuoZIbncm+01p8zPSDZu/VuuJhAfA7d/AbzM09WR7iVhavvfNDYCNpo1VvLk6E6xgAoP9P+/EMJHuRkQ==
    dependencies:
      "@babel/code-frame" "^7.5.5"
      "@babel/generator" "^7.6.2"
      "@babel/helpers" "^7.6.2"
      "@babel/parser" "^7.6.2"
      "@babel/template" "^7.6.0"
      "@babel/traverse" "^7.6.2"
      "@babel/types" "^7.6.0"
      convert-source-map "^1.1.0"
      debug "^4.1.0"
      json5 "^2.1.0"
      lodash "^4.17.13"
      resolve "^1.3.2"
      semver "^5.4.1"
      source-map "^0.5.0"
   
`

**Comment by olingern** [comment]
If you can demonstrate that:
1. Your network connection is stable
2. This is not a duplicate issue
3. This is reproducible

We can re-open this. For now, closing.

**Comment by Ongeziwe-Mbana** [comment]
![image](https://user-images.githubusercontent.com/44267829/73154035-a7c75f80-40de-11ea-8076-4225cea0a243.png)
My connction is stable

**Comment by Ongeziwe-Mbana** [comment]
And I can reproduce the error over and over again every time I run `yarn install`  on any project in my machine. I even Upgraded my yarn to the latest version and the issue is still there. I even tried to create a new project just to test `yarn install` command but I still get the same issue. I have however tried every solution I could find related to the above issue and none of them work. I even went as resseting my windows 10 settings to default, just in case there is a window's setting causing the issue

**Comment by olingern** [comment]
Thanks for that. I've re-opened. I may need more information when I come back to this

**Comment by Ongeziwe-Mbana** [comment]
![image](https://user-images.githubusercontent.com/44267829/73242730-6900da80-41ae-11ea-9903-4c564354ddf5.png)
I hope this saves someone's life too...
I solved the issue by disabling windows defender on my Windows 10 and restarting the PC, opened terminal navigated to project and cleared npm and yarn cache by running `yarn cache clean` then after I ran `npm cache clean --force` then ran `yarn install --network-timeout 1000000`.
