### ISSUE TITLE
Respect .npmignore in workspaces

### ISSUE THREAD

**Issue by alshdavid** [yarnpkg/yarn#7849]
When building a workspace, packages are copied but their `.npmignore` is not respected.

If my package looks like

```
/a
  index.js
  index.d.ts
  index.ts
  .npmignorea
  package.json
```

Where my `.npmignore` would look like

```
index.ts
```

Consumers of package `a` would still see the source file. This causes issues as compilers like TypeScript will resolve the package folder and select the source file rather than the compiled file where if published to npm, the npmignore would ensure the source files would not be uploaded so they would not be available to consumers.

**Comment by olingern** [comment]
Hi @alshdavid -- please fill out the issue template. It's difficult to understand / debug without it.

Sorry, but will close if not updated.
