### ISSUE TITLE
Latest https://yarnpkg.com/install.sh gives "Redirecting: command not found"

### ISSUE THREAD

**Issue by stefanoeb** [yarnpkg/yarn#7855]
### Bug description
Both in our CI system running ubuntu  and on my mac (Catalina), the script to install yarn is giving a weird error: `bash: line 1: Redirecting: command not found`

**Command**

```sh
curl -o- https://yarnpkg.com/install.sh | bash
```

**What is the current behavior?**
The shell script on the official website is throwing an error both on mac and linux machines

**What is the expected behavior?**
Install yarn with the latest version.

**Steps to Reproduce**

1. On a mac machine, run `curl -o- https://yarnpkg.com/install.sh | bash`
2. 💥 script fails

**Environment**

- Node Version: `v10.16.2`
- Yarn v1 Version: `1.21.1` 
- OS and version: Mac OS Catalina 10.15.2

**Comment by olingern** [comment]
You're missing the location `-L` portion of the command. Should be:

`curl -o- -L https://yarnpkg.com/install.sh | bash`

https://legacy.yarnpkg.com/en/docs/install#mac-stable
