### ISSUE TITLE
Github Packages don't work with yarn

### ISSUE THREAD

**Issue by dgesteves** [yarnpkg/yarn#7858]
`npm install` runs without problems,`yarn add` :
`error Couldn't find package "@diligentcorp/atlas-react" on the "npm" registry. info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

**Comment by MalayaliRobz** [comment]
Facing the same problem.
@dgesteves did you get this resolved?

**Comment by dgesteves** [comment]
@MalayaliRobz Yes i did thank you.👍

**Comment by cabas** [comment]
@dgesteves i tried doing the same but it didn't work. Did you have something else? like in the `.npmrc` or the globals?
