### ISSUE TITLE
yarn 2.0.0.rc missing node_modules folder

### ISSUE THREAD

**Issue by kerbrose** [yarnpkg/yarn#7861]
### Bug description

Missing node_modules from directory

**Steps to Reproduce**
I configured angular cli to use yarn as following:

```sh
ng config -g cli.packageManager yarn
```
Then I created a new app as following:
```sh
 ng new appstra
```
later on I did:

```sh
yarn install
```

no `node_modules` folder

**What is the expected behavior?**

to have `node_modules` folder in the directory

**Environment**

- Node Version: `10.16.3`
- Yarn v1 Version: `2.0.0.rc` 
- OS and version: windows 10 64

**Comment by ConsoleTVs** [comment]
yarn 2 does not use node_modules

**Comment by kerbrose** [comment]
@ConsoleTVs 
Thank you
so How could I let my vscode environment be aware of installed packages

**Comment by ConsoleTVs** [comment]
I have no clue, just started using it, and I am also feeling I have to hack so many things: Editor, Plugins, Etc.

**Comment by kerbrose** [comment]
ok I got it there 
How easy will it be to migrate to Yarn 2
https://dev.to/arcanis/introducing-yarn-2-4eh1
