### ISSUE TITLE
Yarn Debian key expiry date updated (EXPKEYSIG 23E7166788B63E1E)

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#7866]
If you see an error like this:
```
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```

Or like this:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```
It means that you still have an older version of the GPG key used to sign Yarn releases. The expiry date for this key was extended from 2020 to 2021. To get the updated key, run this:

```sh
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

This will likely be automated in the future.

**Comment by dario23** [comment]
re automation, the distributions usually have a `-keyring` package that can be updated with newer keys, maybe you want to look into that? e.g. https://packages.debian.org/buster/debian-archive-keyring

**Comment by Daniel15** [comment]
@dario23 Yeah, that's what I've been meaning to do, however I just haven't gotten around to it. I think I could add a yarn-keyring package to our repo, add it as a dependency of the yarn package (to ensure everyone has it), and then update that package whenever we change the key.

**Comment by alexcdot** [comment]
sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com also works to fix this issue for many different packages that have this issue

**Comment by Daniel15** [comment]
Thanks @alexcdot! That command relies on package repository maintainers uploading their public keys to the Ubuntu keyserver, but most do, so it's usually not an issue :)

**Comment by jijothic** [comment]
Thank you! @alexcdot

**Comment by Shekelme** [comment]
Why there's nothing happens after _sudo apt-key add -_ command? I am waiting for several minutes already. Looks like the system is waiting for something...

![image](https://user-images.githubusercontent.com/26449500/75351361-a1452700-58da-11ea-92b5-2144c63d4dc5.png)

**Comment by mschaaf** [comment]
@Shekelme It is waiting for input because you split the command. The command should use taken as it `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`

**Comment by Shekelme** [comment]
Huge thanks, it helped now!

**Comment by millette** [comment]
Should 1.22.0 be available for [debian](https://github.com/yarnpkg/releases/tree/gh-pages/debian/pool/main/y/yarn) ?

**Comment by Daniel15** [comment]
@millette Oops, sorry, the auto-update script broke when the Yarn v1 site moved to classic.yarnpkg.com. I'll fix it and get 1.22.0 deployed!

**Comment by Daniel15** [comment]
@millette It should be available now: https://github.com/yarnpkg/releases/commit/3f7f2c766d64da64f41ff62d63c126112981ee63

Just tested on one of my test machines and it worked fine:
```
% sudo apt install yarn
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  yarn
1 upgraded, 0 newly installed, 0 to remove and 323 not upgraded.
Need to get 891 kB of archives.
After this operation, 4,096 B of additional disk space will be used.
Get:1 http://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.0-1 [891 kB]
Fetched 891 kB in 0s (2,328 kB/s)
Reading changelogs... Done
(Reading database ... 261276 files and directories currently installed.)
Preparing to unpack .../archives/yarn_1.22.0-1_all.deb ...
Unpacking yarn (1.22.0-1) over (1.21.1-1) ...
Setting up yarn (1.22.0-1) ...

15:19 daniel@vps03 /home/daniel
% yarn --version
1.22.0
```

**Comment by millette** [comment]
Me too, thanks @Daniel15

**Comment by kfowlks** [comment]
I had the same issue with under Ubuntu under Windows 10
Linux AVPHR-3HD87Y2-L 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux.

Thanks @Daniel15 

You're suggested solution resolved it.

**Comment by summersjc** [comment]
Updated just fine with: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

**Comment by Daniel15** [comment]
Closing this issue since it's been open for long enough.

**Comment by jason-azze** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

If @alexcdot 's recommended fix times out for you, try forcing hkp over port 80.
```
sudo apt-key adv --refresh-keys --keyserver hkp://keyserver.ubuntu.com:80
```

**Comment by aleon1220** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

That command works amazingly in AWS EC2 Ubuntu 18.04

```
ubuntu@demo:~$ sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
Executing: /tmp/apt-key-gpghome.yhsIc98R5A/gpg.1.sh --refresh-keys --keyserver keyserver.ubuntu.com
gpg: refreshing 6 keys from hkp://keyserver.ubuntu.com
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: key 871920D1991BC93C: "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>" not changed
gpg: key D94AA3F0EFE21092: 2 duplicate signatures removed
gpg: key D94AA3F0EFE21092: 62 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" 59 new signatures
gpg: key 3B4FE6ACC0B21F32: 21 signatures not checked due to missing keys
gpg: key 3B4FE6ACC0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" 18 new signatures
gpg: key 4F4EA0AAE5267A6C: "Launchpad PPA for Ondřej Surý" not changed
gpg: key 4F4EA0AAE5267A6C: "Launchpad PPA for Ondřej Surý" not changed
gpg: key 1646B01B86E50310: 3 signatures not checked due to missing keys
gpg: key 1646B01B86E50310: "Yarn Packaging <yarn@dan.cx>" 5 new signatures
gpg: Total number processed: 6
gpg:              unchanged: 3
gpg:         new signatures: 82
```

**Comment by joesixpack** [comment]
```
Executing: /tmp/apt-key-gpghome.N4svD19CdM/gpg.1.sh --refresh-keys --keyserver keyserver.ubuntu.com:80
gpg: refreshing 11 keys from keyserver.ubuntu.com:80
gpg: keyserver refresh failed: No keyserver available
```

**Comment by Daniel15** [comment]
@joesixpack You either have connectivity issues to the Ubuntu keyserver, or it's down (eg. for maintenance). You could try using a different keyserver.

**Comment by luisfrocha** [comment]
Came here because of that exact error message. Using Raspbian. Just tried @Daniel15's suggestion a few minutes ago and got the following:
```
:~ $ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
```
Any suggestions?

**Comment by Daniel15** [comment]
@luisfrocha make sure you have the `ca-certificates` package installed, otherwise all SSL/TLS connections will fail.

**Comment by luisfrocha** [comment]
@Daniel15 
```
:~ $ sudo apt install ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20190110).
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
```

**Comment by luisfrocha** [comment]
Well, I didn't want to, but I had to after all. I did the curl command, and added the `-k` flag, which worked fine.

**Comment by pshongwe** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

this one worked for me. Thanks :)

**Comment by ShahidDarbar** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

Thank You

**Comment by LukasSchaefer** [comment]
I'm trying to install yarn and run into key issues as well.
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -` gives me the following output:

```
gpg: invalid key resource URL '/tmp/apt-key-gpghome.gq2UKui5Xm/home:manuelschneid3r.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 76F1A20FF987672F: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 17
gpg:       skipped new keys: 17
```

A following `sudo apt update && sudo apt install yarn` outputs

```
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I also already tried ` sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com`, but I got similar errors:

```
gpg: invalid key resource URL '/tmp/apt-key-gpghome.FtkPocMoE3/home:manuelschneid3r.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 76F1A20FF987672F: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 16
gpg:       skipped new keys: 16
```


I'd greatly appreciate any ideas what might go wrong, I don't have much experience with package managers!

**Comment by Daniel15** [comment]
@LukasSchaefer I don't think any of the GPG keys in that error are the Yarn GPG key. You may need to figure out what those keys are for and fix them.

What's the full output you get from `sudo apt update`?

**Comment by LukasSchaefer** [comment]
@Daniel15 Thanks for that hint. I totally missed that the key-error was coming from another package. After fixing this error, yarn installed just fine with the commands stated above.

Apologies for that!

**Comment by quangvv-1620** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

that work for me. thank you!

**Comment by jensbrak** [comment]
Fixed for me too, just took me some time to bother check for a solution. Thx!

**Comment by parsnips** [comment]
I guess this is the day that this gets bumped.

**Comment by sprky0** [comment]
Just ran into this a moment ago as well

**Comment by akshaysgithub** [comment]
> If you see an error like this:
> 
> ```
> The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> ```
> 
> Or like this:
> 
> ```
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> ```
> 
> It means that you still have an older version of the GPG key used to sign Yarn releases. The expiry date for this key was extended from 2020 to 2021. To get the updated key, run this:
> 
> ```shell
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
> ```
> 
> This will likely be automated in the future.

Any idea how long the automation part will take. Our builds are failing with this error. Although there is a fix, I would rather not apply it to all of our microservices in 1 go, and also depend upon a single domain to fetch gpg keys...refreshing keys has not helped.

**Comment by Daniel15** [comment]
@sprky0 Yeah, I modified the key and extended it for two years. It's the same key just with a later expiration date.

@akshaysgithub I'm unsure... The main focus now is on Yarn v2 which doesn't use the repo and instead prefers Yarn to be installed via npm and a local copy per app. I don't think the site even lists the Yarn Debian repo any more (which is unfortunate, but it wasn't my decision, as I'm not doing much work on Yarn any more)

**Comment by wilei** [comment]
> I don't think the site even lists the Yarn Debian repo any more (which is unfortunate, but it wasn't my decision, as I'm not doing much work on Yarn any more)

It does list this as a possibility. And this invalid key brokes even AWS CodeBuild images... Super nice! https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/3.0/Dockerfile#L217

**Comment by celtric** [comment]
A year later...

![](https://media2.giphy.com/media/Nx0rz3jtxtEre/200.gif)

**Comment by Daniel15** [comment]
As mentioned earlier, I've been meaning to fix it so that the Yarn key can be automatically renewed (eg by packaging it in a Debian package that the `yarn` package depends on, or something similar), but never got around to it, and so far people have only been willing to complain about it but not actually spend time helping to improve it 🙂

**Comment by Daniel15** [comment]
> And this invalid key brokes even AWS CodeBuild images... Super nice!

@wilei They're just as likely to hit the same issue with any of the other third-party repositories they use, as long as those repositories have a GPG key that expires (a GPG key that lasts indefinitely is a bad practice). They pull in the key when the Docker image is build, so just rebuilding the image should fix it.

**Comment by randyspainhower** [comment]
> > I don't think the site even lists the Yarn Debian repo any more (which is unfortunate, but it wasn't my decision, as I'm not doing much work on Yarn any more)
> 
> It does list this as a possibility. And this invalid key brokes even AWS CodeBuild images... Super nice! https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/3.0/Dockerfile#L217

I had to add "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -" to my codebuild buildspec before the apt-get update and it fixed the error showing in my codebuild....
good times

**Comment by jordan314** [comment]
Note that for codebuild you have to add `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -` before any apt-get commands or apt-get will fail.

**Comment by wilei** [comment]
> > And this invalid key brokes even AWS CodeBuild images... Super nice!
> 
> @wilei They're just as likely to hit the same issue with any of the other third-party repositories they use, as long as those repositories have a GPG key that expires (a GPG key that lasts indefinitely is a bad practice). They pull in the key when the Docker image is build, so just rebuilding the image should fix it.

I haven't had any this kind of issues with any other "3rd party" deb-repositories. And this was the second time for yarn/node. There's some seriously bad ecosystem management happening here.

**Comment by Dwiga** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

it works for me.. thanks

**Comment by Daniel15** [comment]
> I haven't had any this kind of issues with any other "3rd party" deb-repositories.

@wilei I think many of them install a package that automatically updates the keys.

If you submit a diff that adds that to the Yarn repo, I'd be happy to review it. So far nobody has done so.

**Comment by AndreasAtakan** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

Worked for me

**Comment by sbcgm** [comment]
> @sprky0 Yeah, I modified the key and extended it for two years. It's the same key just with a later expiration date.

Allright, see you in two years then again I guess.

_bookmarks this issue_

**Comment by Daniel15** [comment]
> > @sprky0 Yeah, I modified the key and extended it for two years. It's the same key just with a later expiration date.
> 
> Allright, see you in two years then again I guess.
> 
> _bookmarks this issue_

If you want to submit a proper fix so that it's not an issue any more, I'd be happy to review your PR.

**Comment by Shillos** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

This still is the best fix for all packages. Thanks.

**Comment by silva-thiago** [comment]
> > `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue
> 
> If @alexcdot 's recommended fix times out for you, try forcing hkp over port 80.
> 
> ```
> sudo apt-key adv --refresh-keys --keyserver hkp://keyserver.ubuntu.com
> sudo apt-key adv --refresh-keys --keyserver hkp://keyserver.ubuntu.com:80
> ```

Both links worked for me!

**Comment by dackdel** [comment]
none of the links worked. im running pop os. maybe thats why

**Comment by gisegalaburri** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue
it worked for me :100: thanks

**Comment by Owned67** [comment]
> > `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue
> 
> it works for me.. thanks

Hello, don't help me this
Err:14 https://dl.yarnpkg.com/debian stable Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

Already done:
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - `
and apt update give error below

**Comment by Silver47Gin** [comment]
Check Yarn HomePage Will Help. [https://classic.yarnpkg.com/en/docs/install#debian-stable](https://classic.yarnpkg.com/en/docs/install#debian-stable)

Or Just `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`

**Comment by mathieujobin** [comment]
This is happening again ...

**Comment by Daniel15** [comment]
@mathieujobin The key has already been updated again. Please re-download the key. The updated key is valid until 2026.

There was/is a pull request to improve this process, but I didn't get around to reviewing it and Yarn v1 is mostly in maintenance mode now.

**Comment by mathieujobin** [comment]
I have the new key, but `apt update` still complains...

```
root@0023d863900a:/home/app/webapp# apt-key list 
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2013-06-30 [SC]
      1637 8A33 A6EF 1676 2922  526E 561F 9B9C AC40 B2F7
uid           [ unknown] Phusion Automated Software Signing (Used by automated tools to sign software packages) <auto-software-signing@phusion.nl>
sub   rsa4096 2013-06-30 [E]

pub   rsa4096 2016-10-05 [SC]
      72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
uid           [ unknown] Yarn Packaging <yarn@dan.cx>
sub   rsa4096 2016-10-05 [E]
sub   rsa4096 2019-01-02 [S] [expires: 2026-01-23]
sub   rsa4096 2019-01-11 [S] [expires: 2026-01-23]

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      790B C727 7767 219C 42C8  6F93 3B4F E6AC C0B2 1F32
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      8439 38DF 228D 22F7 B374  2BC0 D94A A3F0 EFE2 1092
uid           [ unknown] Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
------------------------------------------------------
pub   rsa4096 2018-09-17 [SC]
      F6EC B376 2474 EDA9 D21B  7022 8719 20D1 991B C93C
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>

/etc/apt/trusted.gpg.d/yarn-archive-keyring.gpg
-----------------------------------------------
pub   rsa4096 2016-10-05 [SC]
      72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
uid           [ unknown] Yarn Packaging <yarn@dan.cx>
sub   rsa4096 2016-10-05 [E]
sub   rsa4096 2019-01-02 [S] [expires: 2026-01-23]
sub   rsa4096 2019-01-11 [S] [expires: 2026-01-23]

root@0023d863900a:/home/app/webapp# apt update
Get:1 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:2 https://deb.nodesource.com/node_14.x focal InRelease                                                                                                                                                                            
Err:1 https://dl.yarnpkg.com/debian stable InRelease                                                                                                                                               
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                                       
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                 
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease                                               
Ign:6 https://oss-binaries.phusionpassenger.com/apt/passenger focal InRelease
Hit:7 https://oss-binaries.phusionpassenger.com/apt/passenger focal Release
Hit:9 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@0023d863900a:/home/app/webapp# 
```

**Comment by rahul-y** [comment]
Facing same issue. Expiry is of 2026 but still getting invalid error.

**Comment by yotixify** [comment]
Adding ```curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -``` to our buildspec file in CodeBuild as mentioned above fixed the issue for me.

**Comment by mathieujobin** [comment]
for those that it worked, are you on Ubuntu 22.04 ?

**Comment by sbekx** [comment]
> Adding `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -` to our buildspec file in CodeBuild mentioned above fixed the issue for me.
> 
> Will have to keep that in there till AWS updates their default codebuild image.

Can confirm this fixes the issue for the AWS Codebuild image: aws/codebuild/standard:5.0

**Comment by madzohan** [comment]
@sbekx don't use `apt-key` it is deprecated  (on latest LTS debian|ubuntu releases)

### step 0

```
export YARNKEY=yarn-keyring.gpg
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmour -o /usr/share/keyrings/$YARNKEY
echo deb [signed-by=/usr/share/keyrings/$YARNKEY] https://dl.yarnpkg.com/debian stable main | sudo tee /etc/apt/sources.list.d/yarn.list
```
### step 1

If you're using `gpg` keyrings so you could simply use `sudo gpg --refresh-keys 1646B01B86E50310` or add some cron job to run `sudo gpg --refresh-keys`

>--refresh-keys
        Request updates from a keyserver for keys that already exist on the local keyring. This is useful for updating a key with the latest signatures, user  IDs,  etc.  Calling
              this with no arguments will refresh the entire keyring.

**Comment by stefanproell** [comment]
I needed to enclose the echoed text with quotes, @madzohan

```
export YARNKEY=yarn-keyring.gpg
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmour -o /usr/share/keyrings/$YARNKEY
echo "deb [signed-by=/usr/share/keyrings/$YARNKEY] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

```

**Comment by sbekx** [comment]
> @sbekx don't use `apt-key` it is deprecated (on latest LTS debian|ubuntu releases)

@madzohan I am aware it is deprecated, however in the 'codebuild/standard/5.0' image when we use the alternative, it continues to fail our builds. Perhaps this is an AWS specific thing. I just wanted to highlight this for anyone using this AWS image specifically.

That said, there are a number of other stacks we need to look at, so I'll re-test and report back.

**Comment by mbrodala** [comment]
Anyone interested here is what I've put in my `Dockerfile` now:

```Dockerfile
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmour -o /usr/share/keyrings/yarn-keyring.gpg \
    && sed -i '1s;^deb;deb [signed-by=/usr/share/keyrings/yarn-keyring.gpg];' /etc/apt/sources.list.d/yarn.list
```

This assumes that `/etc/apt/sources.list.d/yarn.list` already exists and contains `deb https://dl.yarnpkg.com/debian/ stable main`

**Comment by sagepe** [comment]
Just to note that Apt ([on Debian Bullseye at least](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#deprecated-components)) will accept ascii-armoured keys with an `.asc` extension, so you could, if desired, simply download the key directly as-is without the intermediate pass through `gpg --dearmour`.

**Comment by mbrodala** [comment]
Thanks for the hint, this also works fine:

```Dockerfile
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg -o /usr/share/keyrings/yarn-keyring.asc \
    && sed -i '1s;^deb;deb [signed-by=/usr/share/keyrings/yarn-keyring.asc];' /etc/apt/sources.list.d/yarn.list
```

**Comment by plumdog** [comment]
For AWS Codebuild users, Ubuntu images have now been patched, see https://github.com/aws/aws-codebuild-docker-images/issues/594#issuecomment-1404334847.

**Comment by evagabond** [comment]
Solved by re-installing:

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update
sudo apt install yarn
```

Ref: [](https://linuxize.com/post/how-to-install-yarn-on-ubuntu-20-04/
)

**Comment by volkert-fastned** [comment]
That's funny. I just now noticed that GPG allows both `--dearmor` and `--dearmour`, apparently to satisfy both the people who insist on British spelling and those who prefer American spelling. :grin:

**Comment by elbrashdy** [comment]
> @Shekelme It is waiting for input because you split the command. The command should be taken as it `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`

worked thanks Bro

**Comment by sangnguyendev** [comment]
> `sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` also works to fix this issue for many different packages that have this issue

thanks Bro

**Comment by gzamaury** [comment]
For those using Docker, since apt-key was deprecated, this works for me: 

```dockerfile
ENV YARNKEY=yarn-keyring.gpg
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmour -o /usr/share/keyrings/$YARNKEY && \
echo "deb [signed-by=/usr/share/keyrings/$YARNKEY] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update 
```
Source: [https://tickets.dominodatalab.com/hc/en-us/articles/12830637385364-Yarn-Package-invalid-key](https://tickets.dominodatalab.com/hc/en-us/articles/12830637385364-Yarn-Package-invalid-key)

**Comment by Argvself-confident51** [comment]
> re automation, the distributions usually have a `-keyring` package that can be updated with newer keys, maybe you want to look into that? e.g. https://packages.debian.org/buster/debian-archive-keyring





https://preprocessor.space/questions/receive-alerts-whenever-a-mysql-table-is-modified-in-php-all-without-requiring-a-page-refresh-and-without-burdening-the-server
