### ISSUE TITLE
Will Yarn 2 support an offline mode with offline mirror?

### ISSUE THREAD

**Issue by calarin** [yarnpkg/yarn#7872]
Really excited about `Yarn 2` - looks like some fantastic work.

`Yarn 1.x` has a workable setup for installing packages on a completely offline computer (albeit a little hacky, having to edit .lock file and package.json manually).

Will `Yarn 2` support installing packages in a completely offline environment? (with whatever setup is required, offline-mirror etc).

I asked on SO but didn't get a response so asking here.
https://stackoverflow.com/questions/60021048/does-yarn-2-support-offline-mode-like-v1-x

Thanks in advance for any help or advice on this.

**Comment by arcanis** [comment]
Yes, we support that (the offline mirror has been merged with the Yarn cache, so any time you see the word "cache" you can think of it as what was previously called the offline mirror).

**Comment by calarin** [comment]
Great - thank you so much. Now I can get started on migrating to **Yarn 2**.
