### ISSUE TITLE
Packages not installing

### ISSUE THREAD

**Issue by Uj0** [yarnpkg/yarn#7873]
### Bug description
I'm trying to install the packages but it stops the process by saying ESOCKETTIMEDOUT. Though internet is working perfectly. I tried the same on some other computer but it worked.

**Command**

```sh
yarn [install]
```

**What is the current behavior?**
It is saying ESOCKETTIMEDOUT.

**What is the expected behavior?**
I expect it to install all packages. I have installed packages before but suddenly it has stopped working.

**Steps to Reproduce**

1. install the packages using yarn from package.json. Attaching the packages list.

{
  "name": "app-web",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@sentry/browser": "^5.10.1",
    "antd": "^3.26.8",
    "axios": "^0.19.0",
    "bootstrap": "^4.3.1",
    "deep-freeze": "^0.0.1",
    "highcharts": "8.0.0",
    "history": "^4.9.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "node-sass": "^4.12.0",
    "prop-types": "^15.7.2",
    "react": "^16.11.0",
    "react-bootstrap": "^1.0.0-beta.12",
    "react-dom": "^16.11.0",
    "react-highcharts": "^16.1.0",
    "react-pdf-js": "^5.1.0",
    "react-redux": "^7.1.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.3.1",
    "react-window": "^1.8.5",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

![2020-02-05 (1)](https://user-images.githubusercontent.com/38037655/73822748-ca632200-481c-11ea-8986-5e02647cdb62.png)
![2020-02-05](https://user-images.githubusercontent.com/38037655/73822750-cafbb880-481c-11ea-9a97-763fd560ed1e.png)

**Environment**

- Node Version: `10.15.3`
- Yarn v1 Version: `1.21.1` 
- OS and version: 
Windows 10 version 1903

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
