### ISSUE TITLE
Arguments forwarding after pipe

### ISSUE THREAD

**Issue by cyrilchapon** [yarnpkg/yarn#7874]
I'm pretty used to many forms of package.json scripting and arguments forwarding stuff; but I won't succeed on doing what I want with pipes.

I'm trying to calculate a hash of a file, using a package named `hasha-cli`

This is blowing my mind, and I suspect it has something to do with arguments / options forwarding of yarn.

This is how the command is used:

```bash
# simple use directly in shell
> cat src/config.js | ./node_modules/.bin/hasha
0fd2f6e6e91c5407fc24f24cd3644426e77022f06d1d7839dc2b08793d7f148e1ba509bfc39d00ef703ab5559843ef710f7067f4682fe29615a527caa9e43bd2

# use with options directly in shell
> cat src/config.js | ./node_modules/.bin/hasha --algorithm=md5
0bc783dd3187b0256d3c8a096ea2341e
```

This is usage in package.json

```json
{
  "scripts": {
    "hash": "cat src/config.js | hasha",
    "hashmd5": "cat src/config.js | hasha"
  }
}
```

and output

```bash
# simple use with yarn
> yarn run hash
yarn run v1.17.3
$ cat src/config.js | hasha
0fd2f6e6e91c5407fc24f24cd3644426e77022f06d1d7839dc2b08793d7f148e1ba509bfc39d00ef703ab5559843ef710f7067f4682fe29615a527caa9e43bd2
✨  Done in 0.23s.

# use with options with yarn
> yarn run hashmd5
yarn run v1.17.3
$ cat src/config.js | hasha --algorithm=md5
✨  Done in 0.19s.
```

Notice how in the last command, when passing `--algorithm=md5` it just outputs **nothing**.

I tried everything, `-- --algorithm=md5`, surrounding with `' '`, with `" "` and even with parenthesis the whole subcommand `(hasha --algorithm=md5)` ; it still outputs nothing :/

Any help ? Known bug with arguments after piping ?

Thanks 🙂

**Comment by merceyz** [comment]
I get no output in v1 but in v2 both work so closing as fixed in v2

https://yarnpkg.com/getting-started/migration
