### ISSUE TITLE
Add `--silent` flag to CLI run command

### ISSUE THREAD

**Issue by pgrippi** [yarnpkg/yarn#788]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behavior?**

I use the `npm test` command in my ember cli projects to run my tests. I was happy to see that `yarn test` works the same way as `npm test` but it's missing one feature that I use: the `--silent` flag.

When I run `yarn test --silent` (or `yarn run test --silent`) it prints out the yarn version and command it runs:

```
$ yarn run test --silent
yarn run v0.15.1
$ ember test
...
```

**What is the expected behavior?**

I would expect that when I run `yarn run <cmd> --silent` it would suppress the output of the yarn version and the command it is running, similar to how `npm run --silent` works.

**Please mention your node.js, yarn and operating system version.**

Node: v4.6.0
Yarn: v0.15.1
OS: MacOS Sierra 10.12.0

**Comment by FLGMwt** [comment]
Talked a bit with @cpojer on discord about exactly how silent something like this should be and he convinced me at least that this might not be a necessary thing for a cli to provide. Nothing that I could think of can't be handled by a `>/dev/null 2>&1` if you *really* don't care about the output.

Counterpoints?

**Comment by pgrippi** [comment]
Ah, but I do care about the output. My use case here is that I'm running the test on a CI server and the output is an xml file. My command looks something like this:

```
yarn test --silent -- --other-args > junit.xml
```

Since yarn prints out the version and command the xml file generated by my test script has that in it before the xml output and I'm left with an invalid xml file.

**Comment by robotvert** [comment]
Also, terminal colors mess up the output when doing deploys here. Maybe it's something that should be addressed in the way my deploys are done but a simple `--silent` flag would avoid stuff like:

```
[2K[1G[1myarn install v0.15.1[22m
[2K[1G[90m[1/4][39m Resolving packages...
[2K[1G[2K[1G[2K[1G[90m[2/4][39m Fetching packages...
[2K[1G[1G 0/790[1G 5/790[1G 226/790[1G 745/790[2K[1G[2K[1G[33mwarning[39m fsevents@1.0.14: The platform "linux" is incompatible with this module.
[2K[1G[34minfo[39m "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[2K[1G[90m[3/4][39m Linking dependencies...
[2K[1G[33mwarning[39m Unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
[2K[1G[1G 0/32[2K[1G[1G 0/2095[1G 131/2095[1G 332/2095[1G 524/2095[1G 759/2095[1G 976/2095[1G 1229/2095[1G 1493/2095[1G 1733/2095[1G 1877/2095[1G 2031/2095[2K[1G[2K[1G[1G 0/32[2K[1G[2K[1G[90m[4/4][39m Building fresh packages...
[2K[1G
[2K[1G
[2K[1G
[2K[1G
[2K[1G[1G[1A[2K[1G[1B[1G[2A[2K[1G[2B[1G[3A[2K[1G[3B[1G[4A[2K[1G[4B[1G[4A[2K[4B[1G[3A[2K[3B[1G[2A[2K[2B[1G[1A[2K[1B[2K[1G[4A[2K[1G[32msuccess[39m Saved lockfile.
[2K[1GDone in 2.64s.
```

With npm you can do `npm install --progress false --color false` to ease things a bit.

**Comment by jacott** [comment]
If stdout is not connected to a terminal then it should not use *any* control characters; just like npm does

**Comment by chrisvasz** [comment]
We would love to see this on many more of the yarn commands -- install, upgrade, and outdated come to mind. We use a bunch of private, internal modules, and to determine whether they are up-to-date, we run `npm/yarn outdated` on each module inside our modules folder. `npm outdated` outputs nothing if there are no outdated package dependencies, so with npm, the output of our recursive `outdated` command looks like this (simplified):

    /modules/button
    /modules/sortable-list
    Package             Current  Wanted  Latest  Location
    react-sortable-hoc   0.0.11  0.0.11   0.1.0  sortable-list
    /modules/tabs
    /modules/textbox
    /modules/tooltip

The equivalent output in yarn looks like this:

    /modules/button
    yarn outdated v0.16.1
    Done in 0.30s.
    /modules/sortable-list
    Package            Current Wanted Latest
    react-sortable-hoc 0.0.11  0.0.11 0.1.0
    /modules/tabs
    yarn outdated v0.16.1
    Done in 0.32s.
    /modules/textbox
    yarn outdated v0.16.1
    Done in 0.37s.
    /modules/tooltip
    yarn outdated v0.16.1
    Done in 0.20s.

The signal/noise ratio in the second example is much lower. We most definitely care about relevant output (in this case, outdated packages), and a way to silence the surrounding `yarn` front- and back-matter would be really helpful.

**Comment by minasmart** [comment]
I found a really terrible way to work around this:

```json
"scripts": {
  "command-that-captures-output": "cat $(yarn run command-that-yields-output 2>&1 >/dev/null)",
  "command-that-yields-output": ">&2 echo ./path-to-a-file-we-care-about"
}
```

The order of redirects is really important here. For `command-that-yields-output`, I'm sticking the output I care about in stderr, then in `command-that-captures-output`, I'm pointing stderr to the tty that stdout is currently connected to, I'm then pointing stdout to /dev/null. This results in stderr going to the tty that `cat` is connected to, and silencing the builtin yarn output.

Hope this helps!

**Comment by arxpoetica** [comment]
Status on this? When using Yarn for build scripts, it gets really noisy really fast. This is what happens when I run multiple scripts through watchers:

![image](https://cloud.githubusercontent.com/assets/111424/22768102/bcd1780c-ee4d-11e6-9bd6-64cf73bd9569.png)

And I'm just getting started. Every time I change a watched file, it reruns the yarn command with a bunch of output that makes it hard to read the stuff I care about—all the non-yarn output.

**Comment by joscha** [comment]
fixed in #2420

**Comment by voxsim** [comment]
@bestander this is fixed. we can close it!

**Comment by arxpoetica** [comment]
Thanks guys. this CHANGED MY LIFE. 😂

**Comment by contra** [comment]
Did this get removed in 1.0?

**Comment by BYK** [comment]
>Did this get removed in 1.0?

Nope, this is a bug from #4152. Filed #4383 to track it.

**Comment by lmj0011** [comment]
I'm not seeing this option documented: https://yarnpkg.com/en/docs/cli/install

Did it get removed?

**Comment by BYK** [comment]
@lmj0011 sorry, it is there. Just not documented. Filed https://github.com/yarnpkg/website/issues/653 to track.

**Comment by ruslan-polutsygan** [comment]
`yarn upgrade --silent` does output. Or this command was not changed?
yarn version - 1.2.1

**Comment by mojavelinux** [comment]
The lack of a quiet option in Yarn is probably my least favorite thing about Yarn. I can get all my other commands in CI to be quiet except for errors except for Yarn. It always wants to make noise, and it's totally unnecessary.

**Comment by arxpoetica** [comment]
@mojavelinux use the `--silent` flag. I use it all the time. It works.

**Comment by mojavelinux** [comment]
Sorry, but it doesn't. Yarn still makes all kinds of noise. What does work is to pipe to /dev/null.

```
yarn add package-name > /dev/null
```

That only outputs warnings and errors, which is exactly what I expect a `--quiet` flag to do.

**Comment by arxpoetica** [comment]
Are you putting the `--silent` flag in the right place? This is what it looks like for me:

![image](https://user-images.githubusercontent.com/111424/35805981-83ad25b4-0ab0-11e8-999f-066a8e5f04a1.png)


Note the blank space beneath the command. Nada. Nothing. What version of yarn are you running? Here it is without the silent flag:

![image](https://user-images.githubusercontent.com/111424/35806062-cafed304-0ab0-11e8-9f7f-e09248acf1e6.png)

**Comment by mastertinner** [comment]
For me, the noisy part is really that yarn outputs the whole first level of the dependency tree. This does not change with `--silent` which I think is wrong...

**Comment by mojavelinux** [comment]
@arxpoetica You are talking about a script. I'm talking about Yarn add or install.

I'll be honest, I've sort of given up on this feature since discovering I can just pipe to /dev/null. What I'm looking for is no output. That my understanding of what a `--silent` flag should deliver (is there another definition of silent?). But apparently, the Yarn project views the purpose of this flag differently. Fortunately, /dev/null fills that void.

**Comment by arxpoetica** [comment]
Ah. Yes. Well, that would be different than what this ticket mentions which is `CLI run`. Open a new ticket! I think I agree with you: `--silent` should be applied universally, not just with the `run` command.

**Comment by rakeshnambiar** [comment]
Does this run command in the detached mode something like '-d' in docker?

**Comment by AllanOricil** [comment]
it is really weird that the --silent has to be right after the yarn word. For everyone facing the same problem, this will help you:

This does not work:
`yarn <cmd> --silent`

but this works:
`yarn --silent <cmd>`
