### ISSUE TITLE
[pack] does not handle negations in package.json files property

### ISSUE THREAD

**Issue by flash-me** [yarnpkg/yarn#7888]
### Bug description
**Command**

```sh
yarn pack
```

**What is the current behavior?**
Yarn `pack` also includes negated patterns when creating a package.
The `files` property in package.json allows to define what to include in our package when packing / publishing. 
When using negation like `!foo.js`, yarn still will **include** `foo.js` into the package.

**What is the expected behavior?**
Yarn `pack` should handle negated globs correctly, **like npm handles it**.

**Steps to Reproduce**
```sh
# create package with two files
yarn init -y && touch include.me exclude.me
# add files property to package.json
sed -i 's/\(.*lic.*\)/\1,\n\t"files": ["include.me", "!exclude.me"]/' package.json
# pack & extract
yarn pack --filename foo.tgz && tar -xf foo.tgz
# list files in package
ls package/
```

Will contain `include.me`, `exclude.me` and `package.json`

Whereas `npm pack --dry-run --verbose` will **not include** the `exclude.me` file:

![image](https://user-images.githubusercontent.com/5240450/74031012-bc460a80-49b0-11ea-91d9-7a13631575f8.png)

**Environment**
- Node Version: `12.14.1`
- Yarn v1 Version: `1.22.x` 
- OS and version: Windows 10 Version 1909 (OS Build 19363.628)

**Comment by pixelastic** [comment]
To add to the severity of this issue, I had a `!**/__tests__/` entry in my `.files` key to not release test files. It was working correctly with npm, but when packaged through yarn it actually released my whole directory to npm, including files and directory that were ignored by git.

Hopefully I didn't have any sensitive information (like `.envrc` files), but it still pushed a very large set of files to npm

**Comment by flash-me** [comment]
Same case happened to me, but luckily I was publishing to private registry

Cheers
flash :zap:

**Comment by brunohpaiva** [comment]
Any updates on this issue? I've faced the same situation that pixelastic wrote.

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
