### ISSUE TITLE
yarn install --production not installing all dependencies

### ISSUE THREAD

**Issue by reneruiz** [yarnpkg/yarn#7898]
### Bug description
Installing production dependencies is working in an unexpected way. In my case, it's not installing @babel/runtime.

**Command**

```sh
yarn install --production
```

**What is the current behavior?**

Yarn is failing to install @babel/runtime which is an indirect dependency of ours. We depend on downshift and react-redux, and they both depend on runtime.

`yarn list --production` lists @babel/runtime as a package correctly.
![image](https://user-images.githubusercontent.com/394085/74198974-da21a280-4c30-11ea-9b4b-717a94f9bf65.png)

**What is the expected behavior?**

Running `yarn install --production` should install all dependencies and indirect dependencies, @babel/runtime in my case.

**Steps to Reproduce**

1. `git clone git@github.com:reneruiz/reproducible-yarn-production-bug.git`

2. `cd reproducible-yarn-production-bug`

3. `yarn install --production`

4. `cd node_modules/@babel/runtime` verify runtime wasn't installed

**Environment**

- Node Version: `v10.18.1`
- Yarn v1 Version: `1.21.1` 
- OS and version: macOS 10.15.3, Ubuntu 16.04.5 LTS

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
