### ISSUE TITLE
"installation problem" Server aborted the SSL handshake

### ISSUE THREAD

**Issue by PokimLee** [yarnpkg/yarn#790]
v0.15.0

**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
1.curl -o- -L https://yarnpkg.com/install.sh | bash
2.Downloading tarball...
3.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (35) Server aborted the SSL handshake

**If the current behavior is a bug, please provide the steps to reproduce.**
1.curl -o- -L https://yarnpkg.com/install.sh | bash
2.Downloading tarball...
3.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (35) Server aborted the SSL handshake

**What is the expected behavior?**
install success!

**Please mention your node.js, yarn and operating system version.**
node: v6.6.0
system:OSX Captain 10.11.6

**Comment by Daniel15** [comment]
It seems like we're having quite a few problems with Cloudflare's SSL certificates. @thejameskyle  is currently working on getting us a proper SSL cert (as per the comment on https://github.com/yarnpkg/yarn/issues/607#issuecomment-252976768) which should hopefully resolve the various SSL issues we're seeing. Thanks for reporting this!

In the meantime, you can try going to https://yarnpkg.com/install.sh  in your browser and saving the file manually. Then, run `chmod +x install.sh` to make it executable and `./install.sh` to run it 😄

**Comment by busches** [comment]
@thejameskyle was a new cert swapped in? @PokimLee are you still facing this issue?

**Comment by Daniel15** [comment]
I believe we did get a new cert, so this shouldn't be an issue any more. We haven't had any reports recently.

**Comment by PokimLee** [comment]
problem solves LOL ! thank all @busches & @Daniel15
