### ISSUE TITLE
Adding semantic-release/commit-analyzer fails with 404

### ISSUE THREAD

**Issue by pie3636** [yarnpkg/yarn#7900]
### Bug description
Tarball download fails with 404

**Command**

```sh
yarn add semantic-release/commit-analyzer
```

**What is the current behavior?**
```sh
yarn add v1.22.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@semantic-release/commit-analyzer/-/commit-analyzer-7.0.0-beta-.2.tgz: Request failed \"404 Not Found\"".
```

**What is the expected behavior?**
I would expect the package to be found and downloaded.

**Steps to Reproduce**

1. Install yarn
2. Type the same command as above

**Environment**

- Node Version: `12.15.0`
- Yarn v1 Version: `1.22.0` 
- OS and version: Ubuntu 18.04.4 LTS

**Comment by rally25rs** [comment]
Please see #7902 - there is an issue on the npm registry related to this. https://status.npmjs.org/incidents/lvgmcrfvrvsh
