### ISSUE TITLE
workspaces nohoist options does not work 

### ISSUE THREAD

**Issue by mduclehcm** [yarnpkg/yarn#7908]
### Bug description

**Command**

```sh
yarn install
```

**What is the current behavior?**
```
yarn install v1.22.0
error The workspaces field in package.json must be an array.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**What is the expected behavior?**
It should install all dependencies and not hoist packages

**Steps to Reproduce**
my package.json
```json
{
  "name": "xxx",
  "private": true,
  "workspaces": {
    "packages": "packages/*",
    "nohoist": [
      "@types/node"
    ]
  }
}
```

**Environment**

- Node Version: `10.17.0`
- Yarn v1 Version: `1.22.0` 
- OS and version: ubuntu 18.04

**Comment by mduclehcm** [comment]
I think the error should be `error The workspaces.packages field in package.json must be an array.`

**Comment by msegers** [comment]
Shouldn't this be fixed

**Comment by s-ol** [comment]
+1, this error message is very misleading and makes it seem as if the nohoist option is not supported (anymore).
