### ISSUE TITLE
Disk usage on OS X for cache is ridiculously large

### ISSUE THREAD

**Issue by adamreisnz** [yarnpkg/yarn#7909]
### Bug description
Yarn is using way too much cache

**What is the current behavior?**
By accident really, I found out that yarn was using more than **10GB** of disk space on my computer for caches.

How on earth it even managed to accumulate 10GB worth of cached data is beyond me. I don't even think that if you add up the size of every single package that I ever installed + their dependencies and multiply it by 100 you'd get there.

**What is the expected behavior?**
For yarn to manage the cache better, purge old items from the cache, clean up after itself, and be a better guest on my machine in general. Put a limit on how much can be cached. 1GB should be plenty! And surely packages that were cached a year ago can be purged from cache as well.

**Steps to Reproduce**
1. Use yarn for a couple of years
2. Check your cache size

**Environment**
- Node Version: 12
- Yarn v1 Version: 1.21.0, but I've been using it since 0.x
- OS and version: OS X 10.14.6

**Comment by velipso** [comment]
I have to remove mine yearly... last year it hit 96GB (on a 250GB ssd), and this year it was 70GB.  Fun times.

Also, I have to literally `rm` it, because `yarn cache clean` will crash V8.

If anyone is curious:

```
cd ~/Library/Caches/Yarn
rm -rf *
```

**Comment by velipso** [comment]
this is probably a symptom of #6037

**Comment by merceyz** [comment]
Closing as fixed in v2 where the cache is a bunch of compressed zip files

https://yarnpkg.com/getting-started/migration

**Comment by adamreisnz** [comment]
10GB compressed as ZIP file is still going to be huge. Is there not better way of managing the cache and auto purging old cache files more frequently?

**Comment by merceyz** [comment]
That's fair, yes, but the amount of files is much smaller (1 file = 1 dependency) and the amount of dependencies you'll need to download to get to that is much higher. For example my current cache contains 18542 dependencies (and thus 18542 files) at 3.71GB.

If auto cleaning the cache is something you need in v2 make a feature request

**Comment by adamreisnz** [comment]
I already filed a ticket for the issue, it's this one. I don't think zipping is the answer here. But if you deem it solved and closed, then that's up to you and the Yarn team to decide.

**Comment by mariusbutuc** [comment]
FWIW, before `yarn cache clean` = **3.3 GB**: 

![yarn_cache_-_before_clean___DaisyDisk](https://user-images.githubusercontent.com/511893/116015078-122ebe80-a606-11eb-97c7-de162e076c07.png)

after `yarn cache clean` = all clean:

![yarn_cache_-_after_clean___DaisyDisk](https://user-images.githubusercontent.com/511893/116015093-21ae0780-a606-11eb-9459-40a264c5d607.png)

**Comment by shivaylamba** [comment]
@mariusbutuc what software did you use to display this graphical representation, looks really cool

**Comment by adamreisnz** [comment]
It's called daisy disk

**Comment by shivaylamba** [comment]
Thanks a lot!
