### ISSUE TITLE
Missing changelog for versions > 1.19.2

### ISSUE THREAD

**Issue by stnwk** [yarnpkg/yarn#7916]
Hello, thanks for your work on yarn!

I am currently trying to triage an error that occurred when I upgraded from `1.19.2` to `1.22.0`. Unfortunately I can't find any changelog entries for the releases starting with `1.19.2` :/

Can you please update the changelog?

Many thanks :)

**Comment by valscion** [comment]
Seems like there are quite a few issues about changelog being missing already:

#7760 #7735 

Also this comment seems relevant https://github.com/yarnpkg/yarn/issues/7309#issuecomment-500821335

**Comment by merceyz** [comment]
Closing as the changelog has been updated
