### ISSUE TITLE
Installation Problem: Following official docs install 1.21 instead of 1.22(latest)

### ISSUE THREAD

**Issue by ziaulrehman40tkxel** [yarnpkg/yarn#7925]
**Which operating system are you using:**
Ubuntu 18

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I followed exact steps as on the installation instructions page to install yarn(i actually had 1.21.x already installed, i was trying to install 1.22 to use yarn 2 in my new project). I tried `apt-get upgrade` as well as `apt-get install` but both said yarn is already the latest version(1.21.x). While they should have installed 1.22.

**Solution:**
I had to manually download `.deb` file from the github releases page and install that for 1.22.

**Comment by JoshuaVSherman** [comment]
me too

**Comment by o-alquimista** [comment]
Looks like a duplicate of https://github.com/yarnpkg/yarn/issues/7896

**Comment by ziaulrehman40** [comment]
I don't seem to be able to close, please close, its duplicate.

**Comment by ziaulrehman40tkxel** [comment]
Closing as duplicate
