### ISSUE TITLE
npm 迁移至yarn出现如下错误

### ISSUE THREAD

**Issue by NDCFL** [yarnpkg/yarn#7926]
yarn install v1.22.0
info No lockfile found.
[1/4] Resolving packages...
warning babel-polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and
not recommended for usage due to the number of issues. Please, upgrade your depe
ndencies to the actual version of core-js@3.
warning babel-polyfill > babel-runtime > core-js@2.6.11: core-js@<3 is no longer
 maintained and not recommended for usage due to the number of issues. Please, u
pgrade your dependencies to the actual version of core-js@3.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

error An unexpected error occurred: "https://raw.githubusercontent.com/eligrey/F
ileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json: read ECONNRES
ET".

info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\Users\\john\\Desktop\\vue-energy\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

**Comment by mayeths** [comment]
This is not a yarn error, it's about your network.

这不是 yarn 的问题，这是你的网络问题。确认你的网络可以连接 https://raw.githubusercontent.com/eligrey/FileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json。

**Comment by NDCFL** [comment]
该地址无法打开，网络正常，是否需要VPN才能访问？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mayeths <notifications@github.com&gt;
发送时间: 2020年2月21日 23:34
收件人: yarnpkg/yarn <yarn@noreply.github.com&gt;
抄送: 陈飞龙 <275300091@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yarnpkg/yarn] npm 迁移至yarn出现如下错误 (#7926)




This is not a yarn error, it's about your network.
 
这不是 yarn 的问题，这是你的网络问题。确认你的网络可以连接 https://raw.githubusercontent.com/eligrey/FileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json。

**Comment by mayeths** [comment]
> 该地址无法打开，网络正常，是否需要VPN才能访问？ 发自我的iPhone

如果无法访问，对的。请自行寻找办法。

可以关闭这个 issue 了。如果还不行，再来这里新开 issue（我只是路过）

**Comment by NDCFL** [comment]
Thank you for your answer!

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mayeths <notifications@github.com&gt;
发送时间: 2020年2月21日 23:47
收件人: yarnpkg/yarn <yarn@noreply.github.com&gt;
抄送: 陈飞龙 <275300091@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yarnpkg/yarn] npm 迁移至yarn出现如下错误 (#7926)



 
该地址无法打开，网络正常，是否需要VPN才能访问？ 发自我的iPhone
  
如果无法访问，对的。请自行寻找办法。
 
可以关闭这个 issue 了。如果还不行，再来这里新开 issue（我只是路过）

**Comment by hihjdotcn** [comment]
> This is not a yarn error, it's about your network.
> 
> 这不是 yarn 的问题，这是你的网络问题。确认你的网络可以连接 [https://raw.githubusercontent.com/eligrey/FileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json。](https://raw.githubusercontent.com/eligrey/FileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json%E3%80%82)

你的连接多了个句号，https://raw.githubusercontent.com/eligrey/FileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json

**Comment by paul-soporan** [comment]
Closing as here is nothing actionable here.
