### ISSUE TITLE
native fsevents package gets rebuilt every time I add or remove a package

### ISSUE THREAD

**Issue by jedwards1211** [yarnpkg/yarn#7933]
In closing remarks for #932, it was advised to open an issue if we see this problem with a specific package.

### Bug description

**Command**

```sh
git clone https://github.com/jedwards1211/untranspiled-js-library-skeleton
cd untranspiled-js-library-skeleton
yarn
yarn add p-timeout
# fsevents gets rebuilt
yarn remove p-timeout
# fsevents gets rebuilt
```
Note that `p-timeout` is just a random package that has nothing to do with `fsevents`.

**What is the current behavior?**

`fsevents` gets rebuilt every time I add or remove a package

**What is the expected behavior?**

`fsevents` only gets rebuilt if the binary for current version of node is missing from yarn cache.
If I'm installing deps in another project, I expect it to just copy or link the fsevents binary from the yarn cache...(please tell me that's what it's supposed to do?)

**Steps to Reproduce**

```sh
git clone https://github.com/jedwards1211/untranspiled-js-library-skeleton
cd untranspiled-js-library-skeleton
yarn
yarn add p-timeout
# fsevents gets rebuilt
yarn remove p-timeout
# fsevents gets rebuilt
```

**Environment**

- Node Version: `12.12.0`
- Yarn v1 Version: `1.19.1` 
- OS and version: macOS 10.15.1 (19B88)

**Comment by merceyz** [comment]
Fixed in v2 where Yarn keeps better track of what needs to be rebuilt

https://yarnpkg.com/getting-started/migration
