### ISSUE TITLE
Published package update but Yarn throws "Couldn't find any versions..." error

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/yarn#7941]
### Bug description

**Command**

Before the command, updated package.json `@wojtekmaj/date-utils` package version to `^1.0.2`.

```sh
yarn
```

I also tried running

```sh
yarn cache clean
```

before installing, but this didn't help.

**What is the current behavior?**

```
my-project % npm view @wojtekmaj/date-utils versions 
[ '1.0.0', '1.0.1', '1.0.2' ]
my-project % yarn info @wojtekmaj/date-utils versions
yarn info v1.22.0
[
  '1.0.0',
  '1.0.1',
  '1.0.2'
]
✨  Done in 0.25s.
my-project % yarn                                    
yarn install v1.22.0
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@wojtekmaj/date-utils" that matches "^1.0.2"
? Please choose a version of "@wojtekmaj/date-utils" from this list: (Use arrow keys)
❯ 1.0.1 
  1.0.0 
```

**What is the expected behavior?**

Yarn installs version 1.0.2 which is obviously available.

**Environment**

- Node Version: `12.15.0`
- Yarn v1 Version: `1.22.0` 
- OS and version: macOS Catalina

**Comment by wojtekmaj** [comment]
Looks like it fixed itself. Had to simply wait for Yarn servers to catch up with npm.

**Comment by merceyz** [comment]
> having to wait for yarn to catch up before you can use and updated package.

Note that `registry.yarnpkg.com` is just a CNAME, there is nothing for it to "catch up" to.
https://yarnpkg.com/getting-started/qa#why-registryyarnpkgcom-does-facebook-track-us
