### ISSUE TITLE
Installation Problem: yarn

### ISSUE THREAD

**Issue by cwhyte** [yarnpkg/yarn#7944]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by AnjanaJoeJoseph** [comment]
OS:windows 10
steps i took choco install yarn 
cd project_folder yarn 
error: 
node_modules\msgpack: Command failed.
Exit code: 1
Command: node-gyp rebuild

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
