### ISSUE TITLE
Installation Docs Problem: upgrade yarn

### ISSUE THREAD

**Issue by suhli** [yarnpkg/yarn#7947]
**Which operating system are you using:**
macos

**Please describe the steps you took when trying to install Yarn and what went wrong:**
with traditional Chinese
upgrade command is 
> brew install yarn  

![image](https://user-images.githubusercontent.com/23626907/75766928-e48d1300-5d7c-11ea-88fb-aec5a0e0b042.png)

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
