### ISSUE TITLE
Yarn MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by ncioj10** [yarnpkg/yarn#7948]
### Bug description

I had a problem with yarn so I think I mixed up the npm install of yarn and yarn. I tried to delete all global npm installs and reinstall yarn over the official channel but it does not work.
After installing yarn via the official installation tutorial on Ubuntu 18.04 this error occurs:

**Commands**
 yarn:

``` 
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/home/[username]/yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

which yarn:
```
/usr/bin/yarn
```
**What is the current behavior?**

It is not starting at all. The file as well as the folder to that file are not present. 

**What is the expected behavior?**

Loading yarn.

**Steps to Reproduce**

1. Install yarn
2. Run yarn

**Environment**

- Node Version: `v12.16.1`
- Yarn v1 Version: `1.22.0` 
- OS and version: Ubuntu 18.04

**Comment by ToniTepes** [comment]
I just had this same issue for the first time. I don't know if this will work  for you, but my issue was not running inside the server directory. 

If you figured another workaround, could you clue me in? Just for reference.

Thanks!

**Comment by dalinarkholin** [comment]
@ncioj10 Make sure there is no .yarnrc or .yarnrc.yml in a directory above the one you are trying to run yarn. Just ran into this myself.

**Comment by dalinarkholin** [comment]
@ncioj10 [username] is in your path. should it be your actual user?

**Comment by ncioj10** [comment]
@dalinarkholin Yes I've just censored it, it's a regular user name string there.

**Comment by mcb2001** [comment]
My username contains the danish letter "ø" and this seems to fail
...nBøghB...
gets converted to
...nB├©ghB...

**Comment by merceyz** [comment]
Closing as unactionable, you most likely have `yarn-path` in `.yarnrc` pointing to a missing file

**Comment by ncioj10** [comment]
That was in fact the case it turned out. That caused a good round of head ache :D

**Comment by sauloco** [comment]
> My username contains the danish letter "ø" and this seems to fail
> ...nBøghB...
> gets converted to
> ...nB├©ghB...

Sorry to write in a closed issue, but, what would be the workaround in this case?
My partner "Martín" has the same problem.

Setting `yarn-path "../Martín/Roaming/..."` inside `Martín/.yarnrc` to a relative path didn't help because the parent path is the problem here.

**Comment by mcb2001** [comment]
> > My username contains the danish letter "ø" and this seems to fail
> > ...nBøghB...
> > gets converted to
> > ...nB├©ghB...
> 
> Sorry to write in a closed issue, but, what would be the workaround in this case?
> My partner "Martín" has the same problem.
> 
> Setting `yarn-path "../Martín/Roaming/..."` inside `Martín/.yarnrc` to a relative path didn't help because the parent path is the problem here.

I moved to another computer and set up my user without only ASCII. Sorry I couldn't give a better work around.

**Comment by hongda3141** [comment]
i have the same problem 
yarn: MODULE_NOT_FOUND when file is right there
and error info include ".bin", but there is folder name "bin",not ".bin"
