### ISSUE TITLE
Contributing link is dead

### ISSUE THREAD

**Issue by fed135** [yarnpkg/yarn#7950]
### Bug description

Newcomers to the project are given a bad link to the contribution guidelines pages.

**What is the current behavior?**

Clicking the link from https://github.com/yarnpkg/yarn/blob/master/CONTRIBUTING.md leads to a 404 page.

**What is the expected behavior?**

The link should lead to a functioning page.

**Steps to Reproduce**

1. Follow the link to https://yarnpkg.com/org/contributing
2. Observe it returns a 404

**Environment**

N/A

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/commit/0a121f66ffcb4fc48ed6ea9e5ad928bd7cdc9b5f
