### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by Talebsamar** [yarnpkg/yarn#7955]
nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ yarn --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (yarn:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
