### ISSUE TITLE
How to resolve this? I was trying to make a bot on discord 

### ISSUE THREAD

**Issue by shavy4452** [yarnpkg/yarn#7978]
:\Users\Sarvesh>D:

D:\>cd DiscordBot

D:\DiscordBot>install discord.io winston -save
'install' is not recognized as an internal or external command,
operable program or batch file.

D:\DiscordBot>npm install discord.io winston -save
npm WARN Invalid name: "Shavy's Bot"
npm WARN DiscordBot No description
npm WARN DiscordBot No repository field.
npm WARN DiscordBot No README data
npm WARN DiscordBot No license field.

+ discord.io@2.5.3
+ winston@3.2.1
updated 2 packages and audited 144 packages in 2.503s
found 0 vulnerabilities

D:\DiscordBot>node bot.js
(node:9964) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{"message":"Connected","level":"info"}
{"message":"Logged in as: ","level":"info"}
{"message":"Shavy's Bot - (686481645703790592)","level":"info"}

**Comment by Lawlez** [comment]
So first of all it seems you're mixing up NPM and Yarn which is never a good idea. secondly the Warnings tell you exactly whats wrong.

you should be looking at https://yarnpkg.com/configuration/manifest and getting started. 

it looks like you have not defined the action you're trying to run, or dont know how to call it. (for yarn the command would be: 'yarn yourcommand' or f.e. 'yarn install packagexyz')

But mostly you should provide more info and have some structure in your issue.

**Comment by bsian03** [comment]
Also Discord.IO is abandoned and extremely outdated. You should consider using another library, such as Eris or Discord.JS.

**Comment by shavy4452** [comment]
Thank you guys. My Bot is up now.
