### ISSUE TITLE
Installation Problem: [TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Receiv ed type boolean]

### ISSUE THREAD

**Issue by WilliamLin062** [yarnpkg/yarn#7985]
**Which operating system are you using:**
Windows 10
**Please describe the steps you took when trying to install Yarn and what went wrong:**
I follow install#windows-stable use **scoop install yarn** 
and i open git bash run yarn start and there has been 
 `
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at validateString (internal/validators.js:112:11)`

i try uninstall and install again but it still not work, how do i fix it

**Comment by TeddyDuan** [comment]
same issues here.
**Which operating system are you using:**
macOS Catalina 10.15.3

yarn installed by homebrew2.2.10.

got any solutions yet?

**Comment by mjkodkks** [comment]
> faced same issue today.
> for me it was the invalid config in .yarnrc that caused this problem. I got global-folder config with value true, which was wrong. And I deleted this config and then issue fixed.

same issue too. It worked for me. Thank you.

**Comment by merceyz** [comment]
You have a invalid config value in your `.yarnrc` file
