### ISSUE TITLE
Yarn not installing dependency in root node_modules

### ISSUE THREAD

**Issue by Okazari** [yarnpkg/yarn#7987]
### Bug description

**Command**

```sh
yarn
```

**What is the current behavior?**
I currently have an issue installing `docz` along with `react-native` inside a repository.
`docz` have a `gatsby` dependency that have `@pmmmwh/react-refresh-webpack-plugin` as a dependency.

When installing `docz` alone, `@pmmmwh/react-refresh-webpack-plugin` get installed in my `node_module` and everything works fine.

When installing `docz` along with `react-native`, `@pmmmwh/react-refresh-webpack-plugin` get installed in `node_modules/gatsby/node_modules/` and cause `docz dev` command to fail when a file require `@pmmmwh/react-refresh-webpack-plugin`.

**What is the expected behavior?**
I exepct (but maybe i'm wrong ?) to have the same behavior in both case.

`@pmmmwh/react-refresh-webpack-plugin` should always be on top of my `node_modules`

**Steps to Reproduce**

1. git clone https://github.com/Okazari/yarnissue.git
2. cd yarnissue
3. yarn
4. yarn start

**Environment**

- Node Version: `12.16.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Ubuntu 19.10

**Comment by merceyz** [comment]
This is expected, it's not always possible for Yarn to hoist your dependencies, if one of the [`peerDependencies` specified by `@pmmmwh/react-refresh-webpack-plugin`](https://cdn.jsdelivr.net/npm/@pmmmwh/react-refresh-webpack-plugin@0.4.3/package.json) isn't hoisted to the top, it can't be either
