### ISSUE TITLE
npm registry request concurrency?

### ISSUE THREAD

**Issue by jdmarshall** [yarnpkg/yarn#7989]
### Bug description

npm registry code seems to let request parallelism be requestManager's default (8)

```sh
yarn upgrade
```

**What is the current behavior?**

Small number of in-flight requests to our Artifactory server is causing some substantial bottlenecks over VPN (to the tune of 40 minutes of a 45 minute upgrade just being GET calls).

**What is the expected behavior?**

an environment variable or yarn config option to adjust in-flight call limits.

**Steps to Reproduce**

1. 
2.

**Environment**

- Node Version: `10.18.0`
- Yarn v1 Version: `1.21.0 and 1.22.4` 
- OS and version: All

**Comment by merceyz** [comment]
Implemented in V2 under the `networkConcurrency` option https://yarnpkg.com/configuration/yarnrc#networkConcurrency

https://yarnpkg.com/getting-started/migration
