### ISSUE TITLE
Yarn doesn't install dependencies.

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/yarn#7992]
### Bug description

**Command**

```sh
yarn install
```
![Screen Shot 2020-03-15 at 2 28 19 PM](https://user-images.githubusercontent.com/40552237/76707885-3c0a7780-66c9-11ea-8748-1fb33c521f26.png)

**What is the current behavior?**

**What is the expected behavior?**

**Steps to Reproduce**

1. Delete node_modules
2. do ```yarn install```

**Environment**

- Node Version: `13.0.1`
- Yarn v1 Version: `1.22.4` 
- MacOS Catalina - Version:10.15.3 (19D76)

**Comment by Havunen** [comment]
We are experiencing same issue

**Comment by Havunen** [comment]
I have tried adding `Child-Concurrency` to 1. as well as using `--frozen-lockfile` it did not fix the issue

**Comment by NotMoni** [comment]
I have also tried ```---frozen-lockfile```

**Comment by paul-soporan** [comment]
In v1, make sure to also delete the `node_modules/.yarn-integrity` file.

Closed as in v2 it's impossible for this issue to exist.

https://yarnpkg.com/getting-started/migration
