### ISSUE TITLE
Ability to exclude packages from massive upgrade

### ISSUE THREAD

**Issue by goldmont** [yarnpkg/yarn#8005]
Hi,

I have some dependencies in my project that I don't want to upgrade but there are also many other ones that I need to upgrade to their latest version. Each time, I have to specify all the dependencies I want to upgrade and it's such as a boring and long process. I know that the command `yarn upgrade` upgrades all the outdated dependencies but it also updates the dependencies I don't want to. I was wondering whether it's possible or not to add a **fixedDependencies** section, inside package.json, in order to exclude some dependencies from a massive upgrade. Thank you for your efforts.

Regards.

**Comment by goldmont** [comment]
News?

**Comment by goldmont** [comment]
Ok, I've solved by myself.

This below is a JS script that receives the output generated from `yarn outdated --json` and returns a string that contains all the upgradable packages minus those listed in the `fixedDependencies` section in your package.json.

**upgrade.js**
```javascript
#!/usr/bin/env node

/**
 *
 *  Created by Giuseppe Montuoro on 10/04/2020.
 *
 */

const fs = require('fs');
const path = require('path');
const appDirectory = fs.realpathSync(process.cwd());

const argv = process.argv.slice(2);
if (argv.length === 0) {
    throw "Not a valid package.json path.";
}
const package_json = require(path.join(appDirectory, argv[0]));

const filter_dependencies = function(data) {
    return data.filter(function (dependency) {
        return !package_json.fixedDependencies.includes(dependency[0]);
    }).map(function (dependency) {
        return dependency[0];
    });
};

const handler = function(data) {
    if (!data) {
        return;
    }
    const obj = JSON.parse(data);
    if (obj.type === 'info') {
        return;
    }
    const dependencies = filter_dependencies(obj.data.body);
    process.stdout.write(dependencies.join(' '));
};

process.stdin.resume();
process.stdin.setEncoding('utf8');
['SIGINT', 'SIGTERM', 'SIGPIPE'].forEach(function(sig) {
    process.on(sig, process.exit);
});
process.stdin.on('data', handler);
```

**package.json**
```json
{
  "fixedDependencies": [
    "foo",
    "bar"
  ]
}
```

**Shell**
```bash
sudo chmod +x upgrade.js
yarn upgrade "$(yarn outdated --json | ./upgrade.js)"
```

**Comment by joshuapinter** [comment]
I like this workaround but I also need something like this and think it would be best to add this feature into `yarn` proper so we can provide a simple command line option, like `ignore=foo,bar`. 

I'm happy to do a PR if there is some traction/approval from the core team.
