### ISSUE TITLE
Can someone help me in getting error?Compile the below written code and find out the errors. After debugging give the output of this program?

### ISSUE THREAD

**Issue by shavy4452** [yarnpkg/yarn#8007]
Compile the below written code and find out the errors. After debugging give the output of this program?

#include <iostream> 
using namespace std; 
class stu
{

protected:

int rno; public:
void get_no(int a)

{

rno = a;

}

void put_no(void)

{

}
};

class test: public stu

{

protected:

float part1,part2; 
public:
void get_mark(float x, float y)

{

part1 = x; part2 = y;
}

void put_marks()

{

}

};

class sports

{

protected:

float score; public:
void getscore(float s)

{

score = s;

}
void putscore(void)

{

}

};

class result: public test, public sports

{

float total; public:
void display(void);

};

void result::display(void)

{

total = part1 + part2 + score; put_no();
put_marks(); putscore();
cout << "Total Score=" << total << "\n";

}

int main()

{
result stu; stu.get_no(123); 
stu.get_mark(27.5, 33.0); 
stu.getscore(6.0);
stu.display(); 
return 0;
}

**Comment by rosswilson** [comment]
This has nothing to do with Yarn, and seems like a homework question?
