### ISSUE TITLE
Yarn Crashed After ```yarn```

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/yarn#8009]
### Bug description
Was doing ```yarn``` and it randomly crashed after it saved the lock file.

**Command**

```sh
yarn
```

**What is the current behavior?**
Now it is normal, but it just crashed randomly.

**What is the expected behavior?**
Yarn should have updated the yarn.lock

**Steps to Reproduce**
1. yarn

**Environment**

- Node Version: `13.0.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: macOS Catalina v10.15.3

![Screen Shot 2020-03-22 at 3 41 27 PM](https://user-images.githubusercontent.com/40552237/77258844-99677100-6c53-11ea-9770-f4686fdf979a.png)

**Comment by merceyz** [comment]
Based on the error your `package.json` appears to be inavlid but without a reproduction there is nothing actionable here
