### ISSUE TITLE
proposal: yarn.lock should show peer dependencies

### ISSUE THREAD

**Issue by undrafted** [yarnpkg/yarn#8011]
I was wondering if theres a feature flag right now to add `peerDependencies` of our dependencies in the lock file. As this will help us take care of our package.json dependencies and clean up dependencies that are not used anymore. 

E.g. Pretty contrived example but recently we had a notification about a package having a vulnerability, upon inspection we noticed that the package is not used anymore in our project so it is safe to remove. Although sadly other dependencies might put that package inside `peerDependency` which is not highlighted in the lock file. (all we will get is a `WARNING: unmet...`)

**Comment by paul-soporan** [comment]
Closing as fixed in the v2, whose lockfile shows peer dependencies.

https://yarnpkg.com/getting-started/migration
