### ISSUE TITLE
Yarn doesn't installl correctly

### ISSUE THREAD

**Issue by ThePigStupo** [yarnpkg/yarn#8013]
**Which operating system are you using:**
Windows 10 ofc

**Please describe the steps you took when trying to install Yarn and what went wrong:**
IDK, it was my friend that told me this lol![bitmoji](https://render.bitstrips.com/v2/cpanel/91cda591-5c62-4352-80f7-197a30e77707-40b685a3-cb1b-4793-9a22-9fe3e96ff589-v1.png?transparent=1&palette=1&width=246)

**Comment by olannbrink7** [comment]
Ok, it works now

**Comment by olannbrink7** [comment]
Nope same issue again

**Comment by palvarezcordoba** [comment]
The same problem here lol
