### ISSUE TITLE
Decouple Chocolatey build script from installer build script

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#802]
Currently the Chocolatey build script expects the installer to be in the same directory: https://github.com/yarnpkg/yarn/blob/f2b93ffc00add25b9b73e35c355f42ddbe87a509/scripts/build-chocolatey.ps1#L6-L9. However, the only reason it needs the installer is to get a SHA256 hash of it. Apart from that, the Chocolatey package is totally standalone and simply embeds the download URL for the package.

Instead of doing that, the build-chocolatey script could simply download the latest version of the installer (`https://yarnpkg.com/latest.msi`) and generate the hash from that. The version number can be obtained through https://yarnpkg.com/latest-version. That way, building the Chocolatey package is totally separate from the process used to build the installer itself.

**Comment by jouni-kantola** [comment]
@Daniel15: Partly related, since your issue mentions using the msi, which doesn't require node. We're using nvm locally and on build servers. The nuspec for yarn requires `nodejs.install` which we don't use at all. Do you think it should be a required dependency?

**Comment by Daniel15** [comment]
> Do you think it should be a required dependency?

I think so... If you install software via Chocolatey, generally you also install all dependencies via Chocolatey too. That's one of the powerful features of Chocolatey (or any package manager really), it's most useful when you use it to install everything..

I guess we could have a second nuspec that doesn't require `nodejs.install`, but for that particular use case it might be easier to just use the MSI and install it silently (`msiexec /i yarn-0.14.0.msi /qn`)
