### ISSUE TITLE
Is there any way for yarn to  resolve dependencies from the global `node_modules`  instead of downloading it from the network?

### ISSUE THREAD

**Issue by light0x00** [yarnpkg/yarn#8021]
Some packages are too big , it's slowly to download from network every time,  Is there any way to resolve dependencies from global `node_modules` if it exists ?

**Comment by merceyz** [comment]
Closing as fixed in v2 where each version of a dependency is downloaded once into a global cache and reused in future requests for the same version

https://yarnpkg.com/getting-started/migration
