### ISSUE TITLE
yarn install take forever

### ISSUE THREAD

**Issue by joksnoble24** [yarnpkg/yarn#8023]
Hey,
when I run in new react-native project the command 'yarn install' it takes forever and shows me 
`info There appears to be trouble with your network connection. Retrying...`
I checked and I don't have any issue on my internet 

**Environment**

- Node Version: v10.10.0
- Yarn v1 Version: 1.13.0 
- OS and version: windows 10

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
