### ISSUE TITLE
Installing two versions of the same library (question)

### ISSUE THREAD

**Issue by Andrea-Arguello** [yarnpkg/yarn#8024]
I am currently using yarn to install a React Native 0.61.4 app's dependencies. There is a particular library that has the Android version run on 0.60.4 in tandem with iOS 0.61.5; a previous commit however is compatible for both Android and iOS 0.60.4. It'd be quite useful if I could install both libraries, but does yarn allow this? Or will they appear both as node-modules with the same package name?

**Environment**

System:
      OS: Linux 5.3 Pop!_OS 18.04 LTS
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn

**Comment by meyer** [comment]
@Andrea-Arguello you can install multiple versions of the same library with the following syntax in your `package.json` file:

```
{
  "dependencies": {
    "react-native-old": "npm:react-native@0.60.4",
    "react-native": "0.61.5"
  }
}
```

The package name can be anything—in this case I chose `react-native-old`. Note that any usage of the `react-native` package in third party dependencies will pull in the _new_ version.

**Comment by fukemy** [comment]
how to install by npm terminal? Thanks
