### ISSUE TITLE
Yarn was slower than NPM

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/yarn#8028]
I forked and cloned a repo and did ```npm install```. Npm had installed all the dependencies in 10.47 seconds. Then I delete `node_modules` and did `yarn`. Yarn to a whole 42.19 seconds. 

This is the Repo.
https://github.com/discordjs/discord.js

Can someone else see if yarn is slower for them also?

**Comment by merceyz** [comment]
That repo has a `package-lock.json` file so npm had to do a lot less work, you basically tested npm with a cache vs yarn without one
