### ISSUE TITLE
yarn add [package] update other packages

### ISSUE THREAD

**Issue by qkreltms** [yarnpkg/yarn#8035]
### Bug description
When I tried add a package to typing```yarn add redux-persist``` on bash, the package is installed successfully and updates package.json, but other packages: [billboard.js, react-infinite-calendar, ...] which are not related with the package is also updated and these updated packages are not written on package.json nor yarn.lock.
Note: I didn't type any on package.json, but typing command as I mentioned.

**Command**

```sh
yarn add redux-persist
```

**What is the current behavior?**
yarn add [package] update other packages 

**What is the expected behavior?**
Adding only the package I typed

**Steps to Reproduce**
type ```yarn add redux-persist``` on bash 

**Environment**

- Node Version: `v10.16.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: windows 10 Pro 1909

**Comment by paul-soporan** [comment]
Closing as fixed in the v2.

https://yarnpkg.com/getting-started/migration
