### ISSUE TITLE
Don't install a package twice from cache

### ISSUE THREAD

**Issue by yunxing** [yarnpkg/yarn#804]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
Some package installation are not idempotent. If you call post-install twice, the second installation may fail. Currently, after we install a package, we store the build artifacts in the cache. During the second installation, if we call postinstall on the package again, it may fail. 

**Repro**
An example of this is ocamlRe. If you do

```
yarn install ocamlRe
rm -rf node_modules
yarn install ocamlRe 
```

the second installation will fail.

**Comment by LeiZeng** [comment]
I have the same question, which I don't think it's a "issue".

```bash
yarn install some-package
rm -rf node_modules/one-dependency

yarn check
# you can get the warning that the `one-dependency` is missing

yarn install
# success Already up-to-date.

yarn check
# you can get the warning that the `one-dependency` is missing
```
yarn install does not `check` the status first.

The solution is simple:
`yarn install --force` or `yarn --force`

Could be better if it can `check` and fix itself

**Comment by hpurmann** [comment]
I guess this should be closed as https://github.com/yarnpkg/yarn/pull/805 is merged now?

**Comment by wyze** [comment]
Yup, thanks @hpurmann!
