### ISSUE TITLE
Native packages cleared and require rebuild every time

### ISSUE THREAD

**Issue by Slapbox** [yarnpkg/yarn#8041]
### Bug description

This wasn't a problem in some earlier version (like maybe 1.17,x) but we've upgraded to the latest to keep up with security, and we have to rebuild everything, every time now.

**Command**

```sh
yarn
```

**What is the current behavior?**
Native dependencies built files are destroyed on every `install`. This makes installing any package, no matter how trivially small, a 10 minute or longer process.

**What is the expected behavior?**
Yarn spares the built files of native dependencies.

**Steps to Reproduce**

1. Have a native dependency that has built output files
2. Run `yarn` and watch them disappear

**Environment**

- Node Version: `12.13.0`
- Yarn v1 Version: `1.21.1` 
- OS and version: Windows 7

**Comment by Slapbox** [comment]
This is a duplicate of https://github.com/yarnpkg/yarn/issues/932, except that it affects newer versions of Yarn. I'm not sure what version this began, but I want to say it's related to this issue perhaps: https://github.com/yarnpkg/yarn/issues/7807#issuecomment-574702306

This worked fine for me in `1.17` and `1.18`. I haven't tested reverting and running since that's probably a good hour total, but in the meantime I'm copying saved copied of native dependencies back into `node_modules` after running `yarn`, which is far from ideal. @arcanis any thoughts on this?

**Comment by merceyz** [comment]
Closing as fixed in v2 where the tracking of what needs to be rebuilt has been greatly improved

https://yarnpkg.com/getting-started/migration
