### ISSUE TITLE
Yarn does not fetch the git dependency of a git dependency.

### ISSUE THREAD

**Issue by Superlokkus** [yarnpkg/yarn#8043]
### Bug description

**Git dependency with git dependency not complete*

```sh
yarn install
```

**What is the current behavior?**

Yarn does not fetch the git dependency of a git dependency.

**What is the expected behavior?**

Yarn fetches the git dependencies of all its dependencies

**Steps to Reproduce**

Project with a dependency from a git repository, which itself in that dependencies package.json has a git dependency

**Environment**

- Node Version: ` 13.12.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: linux

Might be related to #1488

**Comment by paul-soporan** [comment]
Closing as most likely fixed in v2. Please open an issue here if that's not the case: https://github.com/yarnpkg/berry

https://yarnpkg.com/getting-started/migration
