### ISSUE TITLE
Running Yarn 1 against Yarn 2 packaging gives incorrect error

### ISSUE THREAD

**Issue by danielleadams** [yarnpkg/yarn#8049]
### Bug description
After creating a project with Yarn 2 (creating `yarn.lock`, `.yarn`, `.yarnrc.yml`, etc), if Yarn 1 is run on the project for an install, the following error message occurs:

```
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

This could be confusing since the environment is using an outdated Yarn version, while the `yarn.lock` and other created files are up-to-date.

**Command**

```sh
yarn install --no-lockfile
```

**What is the current behavior?**
Running `yarn --no-lockfile` on Yarn 2 created lockfile produces a message that the lockfile is outdated.

**What is the expected behavior?**
When Yarn 1 detects a future version, possibly by detecting a yml file from the `yarn.lock` file, it tells the user that their environment's yarn version is outdated.

**Steps to Reproduce**

1. Install Yarn 2: `npm i -g yarn@berry`
2. Create Yarn 2 files on source code with a `package.json`: `yarn`
3. Switch to Yarn 1: `npm i -g yarn@1`
4. Run an install: `yarn`

> `Your lockfile needs to be updated, but yarn was run with --frozen-lockfile.`

**Environment**

- Node Version: `12.16.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: Darwin/macOS 10.14.6

**Comment by merceyz** [comment]
The solution is to use per-project installs as documented here https://yarnpkg.com/getting-started/install#per-project-install
