### ISSUE TITLE
yarn-1.22.4.msi fails with "Access is denied."

### ISSUE THREAD

**Issue by dobriai** [yarnpkg/yarn#8050]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**
Can't install from the msi.

Here is what I get, even as Administrator:
```
E:\downloads>.\yarn-1.22.4.msi
Access is denied.
```
At the same time, an older installer that I have, `yarn-1.21.1.msi` still works fine - both from Explorer and cmd!
Tried two different machines, BTW.

**Comment by merceyz** [comment]
Try installing using `npm install yarn -g` as documented here https://yarnpkg.com/getting-started/install
