### ISSUE TITLE
How to find out what project a dependency belongs to when using yarn monorepo

### ISSUE THREAD

**Issue by DarthHater** [yarnpkg/yarn#8058]
Hello!

I work on a project called `auditjs`, which is more or less a more advanced version of `npm audit`. When running it on a yarn project that is setup as a monorepo, with sub modules, lots of dependencies are hoisted up to the parent `node_modules`.

The issue we have filed on our end is: https://github.com/sonatype-nexus-community/auditjs/issues/184

The issue here is it becomes pretty hard to tell what libraries belong to what project, since they end up in the root `node_modules`. I don't think it's impossible, just not even sure where to start. Does `yarn` leave any breadcrumbs of where the library came from? I am mostly curious if the package.json or something akin is updated to say "I came from this sub-module", etc...

This makes it hard to scan the sub modules and get an idea of where you need to update a dependency etc...

Love `yarn` and the work y'all do!

If I'm not being clear at all let me know, glad to share more information.

Thanks in advance!

**Comment by DarthHater** [comment]
Just checking in to see if anyone can respond to this? cc @kevinfauth

**Comment by paularmstrong** [comment]
You can use `yarn why <dependency>`: https://yarnpkg.com/cli/why

**Comment by DarthHater** [comment]
Functionality wise, sure. Programmatically, `yarn why` is not a great answer. I was more so curious as to if in the `yarn.lock` etc... there were ways to figure out where something was hoisted from.
