### ISSUE TITLE
Mis-installed optional dependencies when their dependencies have version conflict

### ISSUE THREAD

**Issue by garthk** [yarnpkg/yarn#806]
**Do you want to request a _feature_ or report a _bug_?**

Bug.

**What is the current behavior?**

`yarn`'s installation of `handlebars` mangles the optional`uglify-js`. It's not quite entirely absent.

**If the current behavior is a bug, please provide the steps to reproduce.**

First, fire up a scratch project and use `npm` to install `handlebars`:

```
cd $(mktemp -d)
npm init -y
npm install --save handlebars@4.0.5
npm ls
ls node_modules/uglify-js
```

Wipe out `node_modules` and try `npm install --no-optional`:

```
rm -rf node_modules
npm install --no-optional
npm ls
ls node_modules/uglify-js
```

Wipe out `node_modules` again and try `yarn`:

```
rm -rf node_modules
yarn
npm ls
ls node_modules/uglify-js
```

Observe the half-installed `uglify-js`, with its version-conflicted dependencies in `node_modules/{async,source-map}` but no other files.

**What is the expected behavior?**

That'd depend on your intent.
- If your intent is to not install optional dependencies, I'd expect no `node_modules/uglify-js`
- If your intent is to install optional dependencies, I'd expect a complete `node_modules/uglify-js` 

**Please mention your node.js, yarn and operating system version.**

Node v6.7.0, Yarn 0.15.1, macOS 10.12.

Also reproduced under an oldish `docker run --rm -ti node:6 bash` (Node v6.4.0, Yarn 0.15.1, some Ubuntu or other).

**Comment by hank7444** [comment]
+1

**Comment by bestander** [comment]
Should be fixed now
