### ISSUE TITLE
yarn install modifies node_modules of linked dependencies

### ISSUE THREAD

**Issue by runspired** [yarnpkg/yarn#8063]
### Bug description

I have a project (`project-a`) with a link to another project (`project-b`) on disk in dependencies in it's package.json (`link:../some/path/other/project-b`).

These projects have different versions of the same dependency in their own dependency trees.

If from a clean state I run `yarn install` in `project-b`, then run `yarn install` in `project-a` (which links to `project-b`), the `node_modules` in `project-b` are altered. In this particular situation the change in the tree causes running build for either project to break as the wrong version of the dependency is found for `project-b`.

Note: I've also observed this bug using `yarn link other-package`, so the `link:` syntax is not uniquely leading to this.

**Command**

```sh
rm -rf node_modules && yarn install
```

Or

```sh
yarn install --force
```

OR

```sh
yarn install --check-files
```

**What is the current behavior?**

**What is the expected behavior?**

`yarn install` should not mutate node_modules of a linked project

**Steps to Reproduce**

A simplified reproduction with steps is here

https://github.com/runspired/yarn-bug-demo

**Environment**

- Node Version: `v13.12.0`
- Yarn v1 Version: `1.22.4` 
- OS and Version: MacOS Catalina 10.15.4

**Comment by runspired** [comment]
Also note that trying an install in `project-a` when no install has occurred at all in `project-b` also fails, because `yarn install` in project-a does not install the reps for project-b, it merely modifies installed deps if they exist.

**Comment by merceyz** [comment]
Fixed in v2

https://yarnpkg.com/getting-started/migration
