### ISSUE TITLE
Yarn Workspaces hoisting in nested packages with different versions of a dependency results in importing wrong dependency version

### ISSUE THREAD

**Issue by PeledYuval** [yarnpkg/yarn#8068]
### Bug description
In a Yarn Workspaces project, if I have nested packages like so:
```
root/package.json <-- workspace definition
root/parentPackage/package.json <-- dependent on lodash@v1
root/parentPackage/childPackage/package.json <--dependent on lodash@v4
root/differentPackage/package.json <-- dependent on lodash@v4
```
Running `yarn` will result in lodash@v4 being hoisted to the root node_modules, and lodash@v1 sitting in `root/parentPackage/node_modules`. This means that childPackage will import lodash@v1 when it expects lodash@v4 and will encounter runtime errors.

You can fix this with nohoist, but you'd have to manually nohoist each package that's problematic which takes a long while. Also, you need to delete your lockfiles between running `yarn` since changing the nohoist config and running `yarn` again does not change module locations.

**Command**

```sh
yarn
```

**What is the current behavior?**
Yarn hoists the package version with most usages to root version even if one of the modules in the workspace will resolve its import to a different version due to having a parent package that's dependent on the different version.

**What is the expected behavior?**
When hoisting packages, Yarn should check if it means that one of the workspace modules will resolve that package to a bad version due to its parent. If so, Yarn should keep a copy of this package in the nested module's node_modules (and maybe it also shouldn't count it as a usage when calculating which packages to hoist by most used version, but this is an optimization).

**Steps to Reproduce**
https://github.com/PeledYuval/yarn-workspace-hoist-bug
Clone that repo, run `yarn` in the root level.

In that repo, you have:
```
root/package.json <- contains workspaces definition
root/service/package.json <-- dependent on lodash@^4.0.0
root/client/package.json <-- dependent on lodash@^1.0.0
root/client/app/package.json <-- dependent on lodash@^4.0.0
```

Running `yarn` results in:
```
root/node_modules/lodash <-- v4.0.0
root/client/node_modules/lodash <-- v1.0.0
```

Clone the repo, then run `yarn && node client/app` in the project root. You will see that the run fails because client/app resolves `require('lodash')` to v1 when it expects v4.

**Environment**

- Node Version: `12.6.1`
- Yarn v1 Version: `1.19.0` 
- OS and version: macOS 10.14.6

**Comment by PeledYuval** [comment]
I'd love some input on this from Yarn maintainers / experts - am I missing something?

**Comment by PeledYuval** [comment]
This issue is still relevant.

**Comment by SpotHimesh** [comment]
+1

For now: using `nohoist` works, but would like more intelligent hoisting

**Comment by PeledYuval** [comment]
This issue is still relevant.

**Comment by PeledYuval** [comment]
For others - this issue is still relevant and makes working with complicated monorepos impossible unless you want to tinker with very specific versions in nested packages. 

I was looking for a way to have each package only see its own dependencies without sacrificing install times due to folder duplication.

I ended up trying pnpm and it's without a doubt a life changer. It's fantastic. Install times are down over 90% for fresh installs and I have zero issues from hoisting. It also has great monorepo script runner command line tools. Very easy to run a certain command in a package and all of its dependencies or all of its dependents. Highly, highly recommended!

I'm keeping this issue open since it's still relevant.

**Comment by kyuwoo-choi** [comment]
I have same problem too.

**Comment by worldpwn** [comment]
for yarn 3
I managed to solve this problem by adding this to .yarnrc.yml file:
``` yml
nmHoistingLimits: workspaces
```

and remove hoisting from package.json

**Comment by merceyz** [comment]
This hoisting bug has been fixed in modern versions of Yarn (tested with 3.1.1)

https://yarnpkg.com/getting-started/migration

---

@worldpwn You don't need the hoisting limits in this case, Yarn handles it on its own.
