### ISSUE TITLE
Distribute on Homebrew

### ISSUE THREAD

**Issue by twhb** [yarnpkg/yarn#807]
**Do you want to request a *feature* or report a *bug*?**

Feature

(deleted rest of template, seems to be specific to bug reports)

I'd like to be able to install and manage Yarn using [Homebrew](http://brew.sh/). The same benefits are already provided for various Linux distros via the Debian and RPM repos, and Homebrew is the closest thing macOS has to an official package manager.

**Comment by serheyShmyg** [comment]
+1

**Comment by ZakariaRidouh** [comment]
#751

**Comment by kittens** [comment]
Going to merge this with #751.
