### ISSUE TITLE
Lately, "yarn install" is very slow

### ISSUE THREAD

**Issue by ericwang-wsq** [yarnpkg/yarn#8071]
Using proxy or 'https://registry.npm.taobao.org' is still slow
Stay in 'Building fresh packages...'

- Node Version: `13.13.0`
- Yarn v1 Version: `1.22.4` 
- OS and version:

**Comment by rally25rs** [comment]
The `Building fresh packages...` step is when yarn runs the custom install scripts for the installed packages. You likely have a dependency that has an install script that takes some time.

You can compare the times with and without running custom build scripts by running
```
yarn install --force
```
and
```
yarn install --force --ignore-scripts
```

the `--ignore-scripts` flag will tell yarn to not run the custom install scripts for packages.
If that install is much faster that without the flag, then that is a good indicator that a packages custom build scripts is taking a long time.
If that is the case then there is nothing yarn can really do to help.

**Comment by AlanKnightly** [comment]
I have to say, yarn install is really slow and, annoying me....

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
