### ISSUE TITLE
Cannot find package eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by laclance** [yarnpkg/yarn#8075]
I can find the package with yarn info but when I run yarn add I get the following error:

> error An unexpected error occurred: "https://registry.yarnpkg.com/@testing-library/userObj-event/-/userObj-event-10.0.0.tgz: Request failed \"404 Not Found\"".

**Comment by merceyz** [comment]
Closing as that package doesn't seem to exist on the public registry

**Comment by laclance** [comment]
hmm seems to work fine with npm

**Comment by merceyz** [comment]
The provided URL is a 404 meaning `@testing-library/userObj-event` doesn't exist, however `@testing-library/user-event` does exist. Spelling mistake perhaps?

https://github.com/testing-library/user-event
https://registry.yarnpkg.com/@testing-library/user-event/10.0.0
