### ISSUE TITLE
what about upgrading the yarn build system from babel6 to babel7 ?

### ISSUE THREAD

**Issue by simevo** [yarnpkg/yarn#8083]
There must be some benefit to it, but I dont'know for sure; on the other hand, the upgrade guide is classy: https://babeljs.io/docs/en/v7-migration

**Comment by pravi** [comment]
We'd like to remove babel 6 from next version of debian and this update will help us in achieving that goal.

**Comment by pravi** [comment]
I can see https://github.com/yarnpkg/berry is already using babel 7. Is there a roadmap for yarn 2.x?

**Comment by pravi** [comment]
Since we are not able to build yarn 1.x with babel 7 and there seems no easy way to build yarn 2.x without building yarn 1.x first, we are forced to move yarn from main section to contrib. Packages in main needs to be built from source, where as packages in contrib can ship pre built files, but contrib is not enabled by default.

**Comment by merceyz** [comment]
Closing as fixed in v2 where we build using typescript

https://yarnpkg.com/getting-started/migration

**Comment by pravi** [comment]
@merceyz but you don't support installing yarn 2 without installing yarn 1 first. Can you support installing yarn 2 directly without using yarn 1?

**Comment by merceyz** [comment]
Technically it's supported with https://github.com/nodejs/corepack which we're working on getting into node (or something like it).

**Comment by pravi** [comment]
@merceyz thanks, we will try building corepack and get back to you if we need help. We want to be able to build from debian packages and not use yarn cache.

**Comment by pravi** [comment]
I was able to build in debian with a few extra packages from npmjs.com, once we package those remaining modules in debian, we will be able to built it fully in debian.
