### ISSUE TITLE
`yarn link` is not workspace-aware

### ISSUE THREAD

**Issue by rhendric** [yarnpkg/yarn#8089]
### Bug description

When using `yarn link` in a project with workspaces, the link gets created in the `node_modules` folder of whatever workspace you are currently in, instead of in the shared `node_modules` folder in the workspace root. This can cause a variety of problems, such as if an app in the workspace requires the linked package, but a dependency of that app unexpectedly gets a different instance or no instance at all.

**Command**

```sh
cd workspace
yarn link some-project
```

**What is the current behavior?**

Yarn is creating a link in the workspace's `node_modules` folder, which is generally not where packages go.

**What is the expected behavior?**

Yarn should create the link in the workspace root's `node_modules` folder instead.

**Steps to Reproduce**

1. `yarn link` in some package that you like and have a local copy of
1. Create a `package.json` with workspaces
1. `cd` to a workspace folder
1. `yarn link that-package-you-like`
1. `ls -d node_modules/that-package-you-like`

**Environment**

- Node Version: `v14.0.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Linux 5.6.7, not that my kernel version matters for this

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
