### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by franzmaster** [yarnpkg/yarn#8091]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**
yarn : The term 'yarn' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ yarn init
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (yarn:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by franzmaster** [comment]
The install of yarn was successful.
  Software installed as 'msi', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log)

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
