### ISSUE TITLE
Unmet Peer Dependencies should fail build 

### ISSUE THREAD

**Issue by johnkoerner** [yarnpkg/yarn#8092]
Is there a way to force the warning:

```
warning " > foo@1.0.0" has incorrect peer dependency "bar@^2.0.0"
```

to fail the build when I am running in CI?

I have `CI=TRUE` in my build environment, but these warnings that appear in the linking phase do not cause the build to break. Ideally I would like to clean them up once and then fail future builds when regressions are introduced.

**Comment by merceyz** [comment]
Closing as fixed in v2 where you can use [logFilters](https://yarnpkg.com/configuration/yarnrc#logFilters) to make them errors

https://yarnpkg.com/getting-started/migration
