### ISSUE TITLE
[BUG] Yarn does not create symlinks for local packages with `file:` protocol

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [yarnpkg/yarn#8096]
![image](https://user-images.githubusercontent.com/60403187/80920222-03a52280-8d77-11ea-83cd-b2255a112ffc.png)

`package.json:`

```json
"next": "./local_packages/next",
```

1) npm create `next` symlink in `node_modules` to `./local_packages/next`
2) yarn install just COPY folder `next` to `node_modules` folder
3) if I modify the files in the local package, the changes do not appear in node_modules
4) yarn should repeat npm behavior to comply with the `package.json` standard, yarn must create symlink, not copy files

npm create symlink:

![image](https://user-images.githubusercontent.com/60403187/80920694-21c05200-8d7a-11ea-9686-d7c0bd9bbdb0.png)

`Windows: 10`
`Yarn: 1.22.4`

**Comment by pravi** [comment]
Even when it is copying, it fails to deference symbolic links (equivalent of cp -L option) so it breaks symbolic links in local packages.

For example, I want to use font-awesome from the debian package, which includes symbolic links,

```
$ ls -l /usr/share/nodejs/font-awesome/
total 4
lrwxrwxrwx 1 root root   28 Dec 13 20:40 css -> ../../fonts-font-awesome/css
lrwxrwxrwx 1 root root   30 Dec 13 20:40 fonts -> ../../fonts-font-awesome/fonts
lrwxrwxrwx 1 root root   29 Dec 13 20:40 less -> ../../fonts-font-awesome/less
-rw-r--r-- 1 root root 1048 Oct 24  2016 package.json
lrwxrwxrwx 1 root root   23 Dec 13 20:40 scss -> ../../sass/font-awesome

```

```
$ yarn add font-awesome@/usr/share/nodejs/font-awesome/
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ font-awesome@4.7.0
info All dependencies
└─ font-awesome@4.7.0
Done in 2.29s.

```

This creates broken symbolic links in node_modules/font-awesome.

```
$ ls -l node_modules/font-awesome/
total 4
lrwxrwxrwx 1 praveen praveen   28 Dec 14 16:49 css -> ../../fonts-font-awesome/css
lrwxrwxrwx 1 praveen praveen   30 Dec 14 16:49 fonts -> ../../fonts-font-awesome/fonts
lrwxrwxrwx 1 praveen praveen   29 Dec 14 16:49 less -> ../../fonts-font-awesome/less
-rw-r--r-- 1 praveen praveen 1048 Oct 24  2016 package.json
lrwxrwxrwx 1 praveen praveen   23 Dec 14 16:49 scss -> ../../sass/font-awesome
$ cd node_modules/font-awesome/fonts
bash: cd: node_modules/font-awesome/fonts: No such file or directory

```
 So it can be fixed with two ways,

1. Like in the original request, create a symbolic link to /usr/share/nodejs/font-awesome/ instead of copying or
2. follow the symbolic links in source and copy them as well

This is similar to -L option of cp command.

 -L, --dereference
              always follow symbolic links in SOURCE

`cp -rL /usr/share/nodejs/font-awesome/ node_modules/`

does the right thing here.

**Comment by mikila85** [comment]
Really? year has passed and no one even addressed this?
maybe it's time to move on from yarn.

**Comment by TSMMark** [comment]
Would a PR be accepted for this? If yes, any pointers how to do it? Thanks

**Comment by benkeil** [comment]
We are also missing this feature. It makes development with local package really hard.

**Comment by merceyz** [comment]
NPM and Yarn treated the `file:` protocol the same way before NPM changed their mind and made `file:` an alias to `link:` while Yarn stuck to the same behaviour https://github.com/npm/npm/pull/15900, if you want symlinks use the `link:` protocol
