### ISSUE TITLE
Better offline detection

### ISSUE THREAD

**Issue by PutziSan** [yarnpkg/yarn#8097]
I follow https://github.com/yarnpkg/yarn/issues/4890 for over 2 years now and it ist really fun and all.
But for real, I think 9/10 of these issues would disappear, If you would not use a timeout for downloading large packages, but try to verify if the User is offline or just on a slow network (maybe a 1kb-test ping could do the trick?).
If he is on a slow network, do not try to restart the download, but keep it open and wait.
Would that be possible or am I on the wrong track?

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
