### ISSUE TITLE
yarn install problem

### ISSUE THREAD

**Issue by restinbeat** [yarnpkg/yarn#8098]
Bug description

Commands
yarn:

warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not t
o mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this wa
rning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > webpack-dev-server@3.10.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
warning "@vue/cli-plugin-unit-mocha > mocha-webpack@2.0.0-beta.0" has unmet peer dependency "webpack@^4.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has unmet peer dependency "eslint@>=5.0.0".        
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-node@>
=7.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-promis
e@>=4.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-standa
rd@>=4.0.0".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.20.2" has unmet peer dependency "eslint@2.x - 6.x".        
warning "@vue/eslint-config-standard > eslint-plugin-node@6.0.1" has unmet peer dependency "eslint@>=3.1.0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@3.1.0" has unmet peer dependency "eslint@>=3.19.0".        
warning " > eslint-plugin-cypress@2.10.3" has unmet peer dependency "eslint@>= 3.2.1".
warning " > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
[1/6] ⢀ core-js
[2/6] ⢀ ejs
[3/6] ⢀ yorkie
[4/6] ⢀ core-js
error C:\Users\thek2\Project\pines-agreement-web\node_modules\webpack-bundle-analyzer\node_modules\ejs: Command failed.  
Exit code: 1
Command: node ./postinstall.js
Arguments:
Directory: C:\Users\thek2\Project\pines-agreement-web\node_modules\webpack-bundle-analyzer\node_modules\ejs
Output:
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\thek2\Project\pines-agreement-web\node_modules\webpack-bundle-analyzer\node_modules\e
js\postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {

which yarn:

What is the current behavior?

What is the expected behavior?

Loading yarn.

Steps to Reproduce

yarn install

- Node Version: 12.16.3
- Yarn v1 Version: 1.22.4
- OS and version:  windows 10

After project open, 
yarn install -> problem has occurred

- Node Version: 12.16.3
- Yarn v1 Version: 1.22.4
- OS and version:  windows 10

**Comment by heresmyinfo** [comment]
Also have same issue - "warning package-lock.json found". There is no package-lock.json. Even removed all instances in system. Can no longer compile any repo. This is critical

**Comment by merceyz** [comment]
Closing as there is nothing actionable here


> Also have same issue - "warning package-lock.json found". There is no package-lock.json. Even removed all instances in system. Can no longer compile any repo. This is critical

That's just a warning and isn't crashing any install, Yarn found a `package-lock.json` and warns you about it because it wont keep it up to date
