### ISSUE TITLE
yarn workspaces run pack is broken

### ISSUE THREAD

**Issue by remcohaszing** [yarnpkg/yarn#8101]
### Bug description

Running `yarn workspaces run pack` used to package all workspaces in version 1.21.1. Now in version 1.22.4 errors with `error Command "pack" not found.`

**Command**

```sh
yarn workspaces run pack
```

**What is the current behavior?**

It outputs `error Command "pack" not found.` and exits with exit code 1.

Output in CI: https://gitlab.com/remcohaszing/koas/-/jobs/540625345

**What is the expected behavior?**

Yarn packs all workspaces and exits with exit code 1.

Output in CI: https://gitlab.com/remcohaszing/koas/-/jobs/481463518

**Steps to Reproduce**

```sh
git clone git@gitlab.com:remcohaszing/koas.git
cd koas
yarn
yarn workspaces run prepack
```

**Environment**

- Node Version: `12.16.3`
- Yarn v1 Version: `1.22.4` 
- OS and version: Pop!_OS 20.04 / Docker image: `node:10-alpine`

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
