### ISSUE TITLE
Different versions of React in Yarn Workspace causes tests to fail. 

### ISSUE THREAD

**Issue by simkessy** [yarnpkg/yarn#8118]
I have a yarn workspace that has a common repo, project 1 and project 2

Common repo has react as a PEER dependency and project 1 has React 16.8 and Project 2 has react 16.3. 

When I run tests in Project 1 I get an error about invalid hooks. If I remove Project 2. I do not have this issue. 

My question is: "Does react have to be the same in all projects within a workspace?"

**Comment by merceyz** [comment]
I would guess your dependency tree is impossible to layout on the disk so yes, they all need to be the same, or you can use PnP which is able to represent this layout.
