### ISSUE TITLE
Installation Problem: yarn commands run from Windows Command Prompt, but not from Git Bash

### ISSUE THREAD

**Issue by itunbridgedev** [yarnpkg/yarn#8122]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I installed yarn from the .msi installer (yarn-1.22.4.msi). After the install, I tried to run `yarn help` from a Git Bash prompt. When I do this, nothing happens and I'm dumped at a new prompt. However, I'm not able to type new commands, but when I press [enter] I see the command I just typed.

I've opened an issue with Git for Windows and someone recommended I try :
`winpty yarn help`

When I run this command, I get this error:
winpty: error: cannot start 'yarn': Not found in PATH

When I looked at my PATH variables, I saw that there was a reference to:
C:\Users\{username}\AppData\Local\Yarn\.bin

After reading comments about a similar issue on stackoverflow:
https://stackoverflow.com/questions/48997825/git-bash-command-on-windows-yarn-command-not-found

I saw this comment:

> If you install yarn through MSI on windows10, and the software installed on C:\Program Files (x86)\Yarn\bin, but the path set in C:\Users\{username}\AppData\Local\Yarn\.bin, so change the path(both user and system) to C:\Program Files (x86)\Yarn\bin.

I changed my User/System PATH variables to include an entry for C:\Program Files (x86)\Yarn\bin

But the same issue exists.

It is worth noting that this issue only seems to be when running the `yarn` commands from Git Bash and that I can successfully run the same commands from Windows Command Prompt.

**Comment by itunbridgedev** [comment]
Can someone confirm that this is the right/wrong place to ask this question?

**Comment by PascalAOMS** [comment]
Got the same issue.
Thanks for reporting!

**Comment by zofoklecja** [comment]
> I changed my User/System PATH variables to include an entry for C:\Program Files (x86)\Yarn\bin

@itunbridgedev You included the correct entry, but have you removed the wrong one? I think it might be messing with the setup. Replacing worked for me.

**Comment by itunbridgedev** [comment]
> > I changed my User/System PATH variables to include an entry for C:\Program Files (x86)\Yarn\bin
> 
> @itunbridgedev You included the correct entry, but have you removed the wrong one? I think it might be messing with the setup. Replacing worked for me.

I have one entry in my User variables and another in my System variables - they're both identical: `C:\Program Files (x86)\Yarn\bin`. That is to say, no other reference to an invalid path (i.e. `C:\Users{username}\AppData\Local\Yarn.bin` like the SO article mentioned). I see that other entries have a trailing slash - I wonder if Yarn expects the trailing slash? It would be helpful to know which variable was being used (user or system). I'm ignorant to how that works.

**Comment by merceyz** [comment]
I'll close this as fixed, sounds like you didn't restart your terminal after the install
