### ISSUE TITLE
yarn add `node-sass` never finish

### ISSUE THREAD

**Issue by Brew-Brew** [yarnpkg/yarn#8125]
### Bug description

**Command**

```sh
yarn add node-sass
```

**What is the current behavior?**

It never finish when i "yarn add node sass"

**What is the expected behavior?**

**Steps to Reproduce**

1. 
2.

**Environment**

- Node Version: `x.x.x`
- Yarn v1 Version: `1.x.x` 
- OS and version:

**Comment by weiliang903** [comment]
same problem for me. 
fuck node-sass
