### ISSUE TITLE
'choco' is not recognized as an internal or external command, operable program or batch file.Installation Problem: [title]

### ISSUE THREAD

**Issue by Kanhaiya786** [yarnpkg/yarn#8133]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by zhumengyangi** [comment]
win10，安装最后倒数第二步的时候有个选择框（安装依赖什么的)选择了就提示楼主说的
Win10, when the penultimate step of the installation, there is a selection box (the installation depends on what) is selected and the host will be prompted to say

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
