### ISSUE TITLE
yarn with workspaces puts old version of tsc in root node_modules/.bin

### ISSUE THREAD

**Issue by garyo** [yarnpkg/yarn#8135]
In my simple workspace project, I depend on typescript, but because of an additional dependency in a workspace, the version of typescript in `node_modules/.bin` is not what I expect, and not consistent with the fact that typescript is hoisted to the root.

Project structure:
```
% tree .
.
├── a
│   └── package.json
├── b
│   └── package.json
├── package.json
└── yarn.lock
```
Root package.json:
```
{
  "name": "yarn-bug",
  "version": "1.0.0",
  "private": true,
  "main": "index.js",
  "workspaces": {
    "packages": [
      "a",
      "b"
    ]
  }
}
```
a/package.json -- depends on typedoc:
```
{
  "name": "a",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "typedoc": "^0.16.10"
  }
}
```
b/package.json -- depends on most recent typescript:
```
{
  "name": "b",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "typescript": "^3.9.2"
  }
}
```

When I run `yarn` at top level to install all deps, it runs OK but then running `npx tsc --version` runs the older tsc that happens to be a dependency of `typedoc` used by `a`, rather than the latest typedoc 3.9.2 used by `b`, even though `typescript` itself is hoisted to the root:
```
% node_modules/typescript/bin/tsc --version
Version 3.9.2
% node_modules/.bin/tsc --version
Version 3.7.5
% ls -l node_modules/.bin/tsc
lrwxrwxrwx 1 garyo garyo 42 May 19 13:03 tsc -> ../typedoc/node_modules/typescript/bin/tsc*
```
Also, `yarn why typescript` says it's hoisted typescript to the root, so you'd think it would also install it in `node_modules/.bin`:
```
% yarn why typescript
yarn why v1.22.4
=> Found "typescript@3.9.2"
info Reasons this module exists
   - "_project_#b" depends on it
   - Hoisted from "_project_#b#typescript"
=> Found "typedoc#typescript@3.7.5"
info This module exists because "_project_#a#typedoc" depends on it.
```
This means my typescript-language-server finds the older tsc, for instance. Super confusing.

Did I set things up incorrectly? How can I prevent an old dependency from accidentally "hijacking" my root `tsc` or other important tools?

- Node Version: `10.17.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Linux Ubuntu 18.04

**Comment by davidcozsmith** [comment]
Same problem here.

My packages all reference typescript@3.9.3

But the root node_modules bin points at typescript@3.7.3 (from a dependency)

```
./packages/node_modules/.bin/tsc
   "node  "$basedir/../jest-expo/node_modules/typescript/bin/tsc" "$@""
```
```

PS C:...> yarn why typescript
yarn why v1.22.4
[1/4] Why do we have the module "typescript"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "typescript@3.9.3"
info Has been hoisted to "typescript"
info Reasons this module exists
   - "workspace-aggregator-38b07573-ccdd-422d-8853-5b5848d6b7ae" depends on it
   - Hoisted from "_project_#@XXX#AAA#typescript"
   - Hoisted from "_project_#@XXX#BBB#typescript"
info Number of shared dependencies: 0
=> Found "jest-expo#typescript@3.7.3"
info Reasons this module exists
   - "_project_#@XXX#AAA#jest-expo#@expo#config#@expo#babel-preset-cli" depends on it
   - Hoisted from "_project_#@XXX#BBB#jest-expo#@expo#config#@expo#babel-preset-cli#typescript"
info Number of shared dependencies: 0
Done in 0.83s.

```

**Comment by jdmarshall** [comment]
I've seen the same problem with mocha and a couple other libraries, which has blocked us from using workspaces (meanwhile npm is sprouting new bugs monthly and I'm slowly going crazy). There are a couple other open issues in this area.

It sounds like you might be closer to having a repro case than the rest of us. Is there any chance you can winnow this down to something they can look at?

**Comment by garyo** [comment]
My repro case shouldn't be too hard to work with. Maintainers, let me know if you have any trouble with it.

**Comment by pjongy** [comment]
I think this bug is relates with https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/run.js#L35 
In workspace, each sub projects should resolve .bin path from their CWD but prioritize lockFileDir as bin directory.

It overwrites .bin directory in map.set (https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/run.js#L58)

Isn't it?

I've temporarily resolve this problem like:

package.json
```
"scripts": {
  "tsc": "./node_modules/.bin/tsc"
}
```

**Comment by merceyz** [comment]
> but then running npx tsc --version runs the older tsc

Don't mix npm and Yarn, use `yarn tsc` which should pick the correct version

**Comment by mariuszbeltowski** [comment]
> > but then running npx tsc --version runs the older tsc
> 
> Don't mix npm and Yarn, use `yarn tsc` which should pick the correct version

It should, but it doesn't
