### ISSUE TITLE
Installation Problem: [yarn-berry]

### ISSUE THREAD

**Issue by aryancs07** [yarnpkg/yarn#8139]
**Which operating system are you using:**
Ubuntu

**Please describe the steps you took when trying to install Yarn and what went wrong:**

successfully installed yarn and command yarn -v also running successfully but getting an error of yarn-berry while running the command `yarn global add create-react-app@1.5.2`

Internal Error: vit@workspace:.: This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions
    at t.RunInstallPleaseResolver.getCandidates (/home/aryanjain/.yarn/releases/yarn-berry.js:42:386648)
    at t.MultiResolver.getCandidates (/home/aryanjain/.yarn/releases/yarn-berry.js:16:51062)
    at /home/aryanjain/.yarn/releases/yarn-berry.js:42:104780
    at /home/aryanjain/.yarn/releases/yarn-berry.js:28:19975
    at new Promise (<anonymous>)
    at e.exports (/home/aryanjain/.yarn/releases/yarn-berry.js:28:19957)
    at i (/home/aryanjain/.yarn/releases/yarn-berry.js:16:2884)
    at /home/aryanjain/.yarn/releases/yarn-berry.js:16:2957
    at /home/aryanjain/.yarn/releases/yarn-berry.js:16:3000
    at new Promise (<anonymous>)

**Comment by chooban** [comment]
Check the parent directory of the one you're running the command from, and see if there's a `yarn.lock` in there. I had one, removed it, and my install command started working.

**Comment by merceyz** [comment]
`global` is not a command in v2 so Yarn is trying to run a script named `global` but you haven't ran `yarn install` yet so it throws
