### ISSUE TITLE
Best practice for developing packages in tandem

### ISSUE THREAD

**Issue by chrbala** [yarnpkg/yarn#814]
What is the best practice for developing two packages together? When I try to install a local package with yarn add file:path, it caches the package version. It seems unreasonable to me to use versioning to invalidate the cache, or to manually clear the cache.

Am I missing something, or is there no good way of doing this?

**Comment by ljharb** [comment]
with npm you'd use `npm link` - i believe yarn has `yarn link` as well?

**Comment by chrbala** [comment]
Ah, looks about right, thanks.
