### ISSUE TITLE
get yarn.lock with uncorrect origin

### ISSUE THREAD

**Issue by tenadolanter** [yarnpkg/yarn#8140]
# Bug description
get yarn.lock with uncorrect origin

**What is the current behavior?**

1、execute the comands as below:

```bash
yarn config set registry  https://registry.npm.mycompany.org
npm config set registry  https://registry.npmjs.org
```
2、then, delete yarn.lock and run `yarn install`

3、get a file name yarn.lock  

```
# yarn.lock  
global@~2.0.7:
  version "2.0.7"
  resolved "https://registry.npmjs.org/global/-/global-2.0.7.tgz#d43a9c3d1ec7915f645d8e0eb0ac60010e9e06cd"
  integrity sha1-1DqcPR7HkV9kXY4OsKxgAQ6eBs0=
  dependencies:
    min-document "~0.2.2"
    process "~0.5.1"
```

**What is the expected behavior?**

the origin of `yarn.lock` is not as excepted. what i want is `https://registry.npm.mycompany.org`

**Environment**

- Node Version: `12.16.1`
- Yarn v1 Version: `1.22.0` 
- OS and version: macOS

**Comment by merceyz** [comment]
Closing as fixed in v2 where the `.npmrc` isn't read at all

https://yarnpkg.com/getting-started/migration
