### ISSUE TITLE
Document the difference between YARN_CACHE_FOLDER and offline mirror

### ISSUE THREAD

**Issue by karelbilek** [yarnpkg/yarn#8147]
I do not understand the relation between 
1. a normal cache, in `YARN_CACHE_FOLDER`
2. offline mirror, set by `yarn-offline-mirror`
3. `--prefer-offline` option

What is used at which time?

I can something here

https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/

> “Offline mirror” is different from cache that both npm CLI and Yarn have. Caches store already unzipped tarballs downloaded from registry, they also can be implementation specific and may be invalid between multiple versions of CLI tools. The tarballs in “Offline mirror” can be consumed by any version Yarn that will build cache based on them. It is also easier to store files when they are compressed.

But that still doesn't explain, which cache is used how.

**Comment by evgenylink** [comment]
Yeah, feels like there are three version of each global package: one inside `--global-folder`, second inside `--cache-folder` and third inside `yarn-offline-mirror`. I like having archives locally so I'd rather disabled that cache.

**Comment by karelbilek** [comment]
closing as yarnv1 is not maintained
