### ISSUE TITLE
Uninstallation Problem: [title]

### ISSUE THREAD

**Issue by aryancs07** [yarnpkg/yarn#8151]
**Which operating system are you using:**
Ubuntu 

**Please describe the steps you took when trying to install Yarn and what went wrong:**

I installed yarn for learning and now I want to remove yarn completely from my system 
I installed yarn using following and Now I want to uninstall it completely I tried using `sudo apt-get remove` yarn but its not working 
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
`sudo apt update && sudo apt install yarn`
```

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
