### ISSUE TITLE
yarn start problem

### ISSUE THREAD

**Issue by isuruM96** [yarnpkg/yarn#8152]
**Which operating system are you using:**windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**

C:\Users\WindowS 10\Desktop\mobile application development\ReactNative>yarn start
yarn run v1.22.4
error Couldn't find a package.json file in "C:\\Users\\WindowS 10\\Desktop\\mobile application development\\ReactNative"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

why this error..plz help me..

**Comment by rushi444** [comment]
@2017csc035 Can you link the repo or replicate the issue?

**Comment by Aviavatar** [comment]
I too have same issue did u get it resolved?
if yes can u tell me how.
