### ISSUE TITLE
yarn upgrade nonexistingpackage should be an error

### ISSUE THREAD

**Issue by betelgeuse** [yarnpkg/yarn#8157]
### Bug description

**Command**

```sh
yarn upgrade nonexistingpackage
```

**What is the current behavior?**

success Saved lockfile.
success Saved 0 new dependencies.

**What is the expected behavior?**

Error that there is no such package in the dependency tree

**Steps to Reproduce**

1. Run command mentioned above

**Environment**

- Node Version: `v13.10.1`
- Yarn v1 Version: `v1.22.4`

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
