### ISSUE TITLE
yarn add doesn't install complete date-fns package

### ISSUE THREAD

**Issue by 185driver** [yarnpkg/yarn#8161]
### Bug description

The most recent update to the `date-fns` package (v2.14.0 from v2.13.0) no longer installs correctly using `yarn`, but the equivalent sequence using `npm` works fine.

Here is a [link](https://registry.npmjs.org/date-fns/-/date-fns-2.14.0.tgz) to the latest `date-fns` package file itself.

Crosslink to date-fns issue:
https://github.com/date-fns/date-fns/issues/1811

**Command**

```sh
md date-fns-yarn-test
cd date-fns-yarn-test
yarn init
# Answer questions with defaults
yarn add date-fns
```

**What is the current behavior?**

The node_modules folder for `date-fns` is incomplete. 
The `_lib` folder is missing, and `index.js` files in the methods folders are missing.

**What is the expected behavior?**

The `date-fns` package install should be complete.
If `yarn add date-fns@2.13.0` is used instead, the date-fns node_modules folder is complete, and the package works.

**Steps to Reproduce**

https://github.com/185driver/date-fns-yarn-test

1. Install the repo
2. Note the missing `_lib` folder and missing `index.js` files in the sub-folders.

**Environment**

- Node Version: `10.20.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows 10.0.18363

**Comment by n8sabes** [comment]
I am seeing this as well, but only on one of my two dev systems. I have verified the same version of `yarn v1.22.4` and `node 14.6.0`, is running on both systems, but there must be an environmental or toolchain difference I have not yet located. I have tried deleting `yarn.lock` and all contents of `node_modules`, but get the same compile error.

**Comment by b3coded** [comment]
I think you are getting broken yarn cache, because when I tried with `npm install` I didn't get an error
I cleaned my yarn cache and reinstalled the packages and it worked

```bash
yarn cache clean
rm -rf node_modules yarn.lock # Delete your node_modules and Lockfiles
yarn # Install your packages
```

**Comment by rejetto** [comment]
i had the same problem with multiple packages, and "yarn cache clean" solved it

**Comment by merceyz** [comment]
Closing as fixed in v2 where the cache has been improved to prevent these sorts of issues

https://yarnpkg.com/getting-started/migration
