### ISSUE TITLE
Unused dependecy listed in yarn.lock

### ISSUE THREAD

**Issue by ciclentfort** [yarnpkg/yarn#8162]
### Bug description

Adding a local, identical package twice via different paths leaves two entries in `yarn.lock` but only on in `package.json` 

**Command**

Have a local package `a-v1.0.0.tgz`.

```sh
yarn add file:a-v1.0.0.tgz
```

Then move the package to a dir `vendor` and add again.

```sh
mkdir vendor
mv a-v1.0.0.tgz vendor/
yarn add file:./vendor/a-v1.0.0.tgz
```

**What is the current behavior?**

The `package.json` list package `a` as a depdency with a version of `file:./vendor/a.tgz` as expected but the `yarn.lock` file lists package `a` twice.

```
"a@file:./vendor/a-v1.0.0.tgz":
  version "1.0.0"
  uid b8b611f8dd0a93ca3ec07f7188b90bd73f2520b1
  resolved "file:./vendor/a-v1.0.0.tgz#b8b611f8dd0a93ca3ec07f7188b90bd73f2520b1"

"a@file:a-v1.0.0.tgz":
  version "1.0.0"
  resolved "file:a-v1.0.0.tgz#b8b611f8dd0a93ca3ec07f7188b90bd73f2520b1"
```

**What is the expected behavior?**

Only the instance of the package `a` with the path given as `./vendor/a-v1.0.0.tgz` should be in `yarn.lock` because the other package is no longer listed in the `package.json`.

**Steps to Reproduce**

Clone https://github.com/clentfort/yarn-issue-8162 and run `mkb.sh`. It will create a new package and first add `a-v1.0.0.tgz` then move the file to `vendor` and add it again. It will output the contents of `yarn.lock` after each.

**Environment**

- Node Version: `12.16.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: MacOS 10.15.4

**Comment by ciclentfort** [comment]
I just noticed that it get more bizarre when adding a new version of the local package. I update `a` to version `1.1.0` and now the lock file lists both version in `vendor` but the one from the root has disappeared from `yarn.lock`.

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"a@file:./vendor/a-v1.0.0.tgz":
  version "1.0.0"
  resolved "file:./vendor/a-v1.0.0.tgz#b8b611f8dd0a93ca3ec07f7188b90bd73f2520b1"

"a@file:./vendor/a-v1.1.0.tgz":
  version "1.1.0"
  resolved "file:./vendor/a-v1.1.0.tgz#dc0715e65b4825caf7f9d445c7dd750d2877fff9"
```

**Comment by ciclentfort** [comment]
Running `yarn install` will remove the obsolete entry from yarn.lock.

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
