### ISSUE TITLE
Using pnp.js from external modules that are not included in package.json

### ISSUE THREAD

**Issue by frimuchkov** [yarnpkg/yarn#8169]
Hi!

Is it possible to add other pnp.js into the current runtime? 

Node.js app in my situation should:
- Get path to module
- Require this module (if not required previously)
- Execute code from this module
- Return result
- If module dealer want to update module, then he upload the new module and send command and node.js app will restart

So, in my situation, the app doesn't contain some modules in package.json. Is it possible to use those external modules in my app with PnP?

**Comment by merceyz** [comment]
Implemented in v2

https://yarnpkg.com/getting-started/migration
