### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by cyberell** [yarnpkg/yarn#8171]
### Bug description

**Command**

```sh
yarn [install]
```

**What is the current behavior?**

Yarn crashed and shut down the laptop when installing it into the folder.  I have not tried to use it since install, as I fear files may be corrupted

**What is the expected behavior?**

I expected Yarn to install smoothly and not to crash

**Steps to Reproduce**

1. install yarn into local folder
2. Laptop shuts down unexpectedly within a few seconds of install into the folder
3. The following error message appeared on the screen:
error An unexpected error occurred: "C:\\Users\\Linda\\AppData\\Local\\Yarn\\Cac
he\\v6\\npm-rxjs-5.5.12-6fa61b8a77c3d793dbaf270bee2f43f652d741cc-integrity\\node
_modules\\rxjs\\.yarn-metadata.json: Unexpected token \u0000 in JSON at position
 0".
4. I reinstalled Yarn. into the folder, in the hope that the error would resolve. This time it didn't crash but the error message reappeared. 

**Environment**

- Node Version: `12.18.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: 64 bit Windows 10

Below is a section from the error log file.

SyntaxError: C:\Users\Linda\AppData\Local\Yarn\Cache\v6\npm-rxjs-5.5.12-6fa61b8a77c3d793dbaf270bee2f43f652d741cc-integrity\node_modules\rxjs\.yarn-metadata.json: Unexpected token   in JSON at position 0
      at JSON.parse (<anonymous>)

**Comment by paul-soporan** [comment]
Closing as unactionable - you need to provide a better reproduction.
