### ISSUE TITLE
error Command "kbn" not found.

### ISSUE THREAD

**Issue by heiyu121** [yarnpkg/yarn#8177]
### Bug description

**Command**

```sh
yarn kbn bootstrap
```

**What is the current behavior?**

```sh
yarn run v1.16.0
warning package.json: License should be a valid SPDX license expression
error Command "kbn" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What is the expected behavior?**

install kbn and bootstrap

**Environment**

- Node Version: `10.19.0`
- Yarn v1 Version: `1.16.0` 
- OS and version: centos7

**Comment by paul-soporan** [comment]
> What is the expected behavior?
>
> install kbn and bootstrap

If you want to install those packages, you should use `yarn add kbn bootstrap`.

If you want to run the `bootstrap` command of the `kbn` binary, you need to install the package that provides it first.
