### ISSUE TITLE
gpg: can't connect to the agent: IPC connect call failed

### ISSUE THREAD

**Issue by FunkyJamma** [yarnpkg/yarn#8178]
I'm trying to install yarn on ubuntu 20.04 windows subsystem and I am getting the error 
gpg: can't connect to the agent: IPC connect call failed

everytime I run:
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

**Comment by merceyz** [comment]
Closing as there is nothing actionable here and likely a network issue on your end
