### ISSUE TITLE
Why I can't download it?

### ISSUE THREAD

**Issue by willasas** [yarnpkg/yarn#8179]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Why can't I download yarn's app? After clicking the download button, the website displays 404 errors

**Comment by merceyz** [comment]
Can't reproduce, download button works fine here, though you should install using `npm install yarn -g` until https://github.com/nodejs/node/pull/35398 is sorted
