### ISSUE TITLE
Exit code 128 after yarn install packages

### ISSUE THREAD

**Issue by hnaumenko** [yarnpkg/yarn#8192]
### Bug description

**Command**

```sh
yarn install
```

**What is the current behavior?**
Yarn doesn't unload private packages

**What is the expected behavior?**
Yarn should unload private packages

**Steps to Reproduce**

1. Chose your favorite project
2. Yarn install

![Screen Shot 2020-06-18 at 13 58 43](https://user-images.githubusercontent.com/45694879/85012545-d9af9000-b16b-11ea-90b3-b31daf575b02.png)

**Environment**

- Node Version: `v10.16.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Mac OS

**Comment by Dmitra** [comment]
this is not an issue with yarn, as you are trying to install a package from private repository to which you don't have access.

**Comment by gurievvlad** [comment]
I had the same problem. It looks like yarn going to the git somewhere inside and ignores the password input.
How to fix:
`
cd ~/.ssh
vim config
`
then you need to insert
`
AddKeysToAgent yes
`
and save file
