### ISSUE TITLE
Miss install script when install --production

### ISSUE THREAD

**Issue by Bacra** [yarnpkg/yarn#8194]
`pack-a`  depends on `pack-b`.
`pack-b` has defined  `install` script.

My package.json is
```json
{
  "dependencies": {
    "pack-a": "*"
  },
  "devDependencies": {
    "pack-b": "*"
  }
}
```

`install` script of `pack-b` will not be runned, when yarn install --production.
`pack-b` is ignored by `devDependencies`.

https://github.com/yarnpkg/yarn/blob/ac21dbf16a5d2d5f4cb032f5da5313949db3fb71/src/cli/commands/install.js#L338
https://github.com/yarnpkg/yarn/blob/ac21dbf16a5d2d5f4cb032f5da5313949db3fb71/src/package-install-scripts.js#L200

**Comment by tufantunc** [comment]
--production flag ignores all devDependencies. Its explanied in documentation, [here](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-production-true-false).

If you want to install pack-b when using --production flag, just move it in dependencies list.

**Comment by Bacra** [comment]
`pack-a` depends `pack-b`.
So `pack-b` will be installed when `pack-a` install.

But `install` script of `pack-b` are not runned when `pack-b` has installed.

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
