### ISSUE TITLE
Proposal: Workspaces library aliases

### ISSUE THREAD

**Issue by dardino** [yarnpkg/yarn#8212]
# The Problem

Actually we can define workspaces like this:
```json
"workspaces": [
  "@myNS/library-a",
  "@myNS/library-b",
  "@myNS/library-c"
]
```
but the folder structure must match the name of the libraries and you have something like this:

```text
package.json
+ @myNS
   + library-a 
      + package.json
   + library-b
      + package.json
   + library-c 
      + package.json
```

# Proposal

In this Proposal I want to submit an idea to make possible to have different struct folder but the same libraries:

```json
"workspaces": {
  "@myNS/library-a": "path-lib1",
  "@myNS/library-b": "path2/lib2",
  "@myNS/library-c": "path/to/lib3",
}
```

In many cases it is not possible to maintain the same folder structure, i.e. when working with git submodules.

Another possible syntax to maintain greater backward compatibility could be this:

```
"workspaces": [
  { library: "@myNS/library-a", path: "path-lib1" },
  { library: "@myNS/library-b", path: "path2/lib2" },
  "@myNS/library-c"
]
```

In this second case, we can use an hybrid convention.

What do you think about?

**Comment by merceyz** [comment]
The workspaces field can take a glob pattern so you don't need to hardcode the name
