### ISSUE TITLE
Syscall 'open' fails when running yarn docs

### ISSUE THREAD

**Issue by EdmundsEcho** [yarnpkg/yarn#8218]
### Bug description

**Command**

```sh
yarn docs
```

this fires up the local/project jsdocs
 
**What is the current behavior?**

I get the following error after several files are successfully parsed:

 ```
errno: -63,
  syscall: 'open',
  code: 'ENAMETOOLONG',
  path: 'docs/components_He....
```

**What is the expected behavior?**

No error

**Steps to Reproduce**

1. generate the docs without failure `yarn docs`
2. upgrade a few things to resolve dependency issues; including some brew updates
3. docs fail to render (as described)

Note: Clearly I may have messed something up that has nothing to do with yarn.  I did for instance move my global installs (a handful) to be managed by yarn (i.e., uninstall with npm, global add with yarn).

I also started to have problems with nvim that uses zsh as a shell.  With all that seems to be going on with Catalina and the deprecation of python2, I've become less confident in how to proceed in overiding the symlinks that brew won't do automatically.  

Any guidance or pointers would be greatly appreciated.

\- E

**Environment**

- Node Version: `14.3.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Catalina 10.15.4

Note: I use fish-shell. Relevant only if the use of nvm is somehow critical for react-scripts (v3.4.1).

**Comment by paul-soporan** [comment]
Closing as ane external issue (with the package that you use in your `docs` script).
