### ISSUE TITLE
updating yarn now stuck trying to reference version that doesn't exist

### ISSUE THREAD

**Issue by asherbig** [yarnpkg/yarn#8220]
### Bug description
Hello, I recently upgraded my yarn from 1.19.2 to 1.22.4. I installed originally via brew. Now whenever I use any yarn command, including `yarn -v`, I get an error
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/aherbig/.yarn/releases/yarn-1.19.2.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

This is weird because I uninstalled that version (probably why it can't find the file)
Using `which yarn` always looks normal and points to the correct location.
```
/Users/aherbig/.yarn/bin/yarn
```
No matter what I do, this error stops everything in its tracks.
I've tried uninstalling and re-installing with brew.
I've tried installing via npm.
I've tried installing via curl.
I've tried editing my paths to only point to current installations of yarn.

**What is the current behavior?**
yarn will not work at all.

**What is the expected behavior?**
yarn should reference a currently installed version

**Environment**

- Node Version: `v10.16.0`
- Yarn v1 Version: `1.24.2` and `1.19.2`
- OS and version: macOS Mojave v `10.12.6`

**Comment by barbalex** [comment]
Frustrating. I have similar, also others: https://github.com/yarnpkg/yarn/issues/8399

**Comment by barbalex** [comment]
See https://github.com/yarnpkg/yarn/issues/8399#issuecomment-751292438 for a possible solution.

**Comment by paul-soporan** [comment]
https://github.com/yarnpkg/yarn/issues/8399#issuecomment-753417570
