### ISSUE TITLE
Why isn't `npm i -g yarn` shown as a way to install yarn?

### ISSUE THREAD

**Issue by papb** [yarnpkg/yarn#8224]
The [docs](https://classic.yarnpkg.com/en/docs/install#windows-stable) show several ways of installing yarn but not `npm i -g yarn`, why?

**Comment by oliversalzburg** [comment]
It's actually the first option at https://yarnpkg.com/getting-started/install Those docs are for the classic version. There were probably issues with npm-based installations at the time.

**Comment by papb** [comment]
@oliversalzburg Thanks for the reply. I wonder if "issues with npm-based installations" are still a thing. If not, I think the docs for Yarn 1 deserve an update to show `npm i -g yarn`.

**Comment by merceyz** [comment]
We wont be updating the old docs for this when the new docs already show it
