### ISSUE TITLE
Yarn's Status Page is broken

### ISSUE THREAD

**Issue by schuylr** [yarnpkg/yarn#8231]
I don't think anyone is noticing because Yarn isn't actually down, but when we had some networking issues in our containers, we saw that the [Yarn Status page](https://status.yarnpkg.com/) is returning a 500 error: 

![image](https://user-images.githubusercontent.com/12628715/87447234-577a8600-c5c8-11ea-96b4-cd5e11b8571b.png)

Might cause trouble if/when Yarn actually does go down.

**Comment by iandrc** [comment]
Yeah, I've noticed it as well.

**Comment by arcanis** [comment]
This page isn't useful since we have no registry backend. Going to [`status.yarnpkg.com`](http://status.yarnpkg.com/) will now redirect to our FAQ entry about this.
