### ISSUE TITLE
yarn --help doesn't show all the commands

### ISSUE THREAD

**Issue by shrynx** [yarnpkg/yarn#826]
**Do you want to request a *feature* or report a *bug*?**
Bug.
**What is the current behavior?**
executing ```yarn --help``` doesn't list up all the cli arguments possible.
**If the current behavior is a bug, please provide the steps to reproduce.**
```yarn init``` works but is not shown in help

**Comment by kittens** [comment]
I can see it listed in the `Commands` section of `yarn --help`. Can you post the complete output when you run `yarn --help`?

**Comment by shrynx** [comment]
@kittens sure , maybe i am doing something wrong.
<img width="944" alt="screen shot 2016-10-12 at 5 25 28 pm" src="https://cloud.githubusercontent.com/assets/4706261/19302833/fc5fc236-90a0-11e6-915c-5848bd32bca2.png">

**Comment by saschagehlich** [comment]
Same for me, but works with the version in `master`

**Comment by shrynx** [comment]
Oh yes it does on master,  hopefully in the next release it will.
