### ISSUE TITLE
yarn publish - cannot login on CLI when asked for (working) npm login details

### ISSUE THREAD

**Issue by gvanto** [yarnpkg/yarn#8263]
### Bug description
Cannot log in to NPM via CLI (using working npm login details). When I log in to npm from the CLI, it works fine (using same credentials).

**Command**

```sh
yarn publish
```

**What is the current behavior?**
Getting error "Incorrect username or password."

**What is the expected behavior?**
Log in successfully and publish package to registry.

**Environment**

- Node Version: `v10.21.0`
- Yarn v1 Version: `1.19.2` 
- OS and version: MacOS Mojave 10.14.6

![Screenshot 2020-07-28 at 11 03 53](https://user-images.githubusercontent.com/8372918/88643612-3171dd00-d0c2-11ea-88a6-7beb4624dc22.png)

**Comment by gvanto** [comment]
ok after 2 days it magically started working...

**Comment by McEazy2700** [comment]
What? I'm having this error right now, what am I supposed , wait 2 days?
