### ISSUE TITLE
yarn Installation Problem: [title]

### ISSUE THREAD

**Issue by amalkshaji** [yarnpkg/yarn#8266]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by Usamaliaquat123** [comment]
share the following details,

$ node -v
$ npm -v

and what commands you are running to regenerate this issue ...

**Comment by styfle** [comment]
I'm seeing this issue recently. It seems like the yarn registry is down for a bit and then comes back.

```
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@formatjs/intl-pluralrules/-/intl-pluralrules-1.5.9.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/node-file-trace/node-file-trace/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]Process completed with exit code 1.
```

https://github.com/vercel/node-file-trace/runs/924900703

## Screenshot

Not just Github Actions CI affected by also my computer visiting in my browser:

![image](https://user-images.githubusercontent.com/229881/88850070-d1119700-d1b8-11ea-9ff2-fca8507dd8ed.png)

## Node Version

```
node v10.21.0
npm 6.14.4
```

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here.
