### ISSUE TITLE
Compatibility errors should show dependency path

### ISSUE THREAD

**Issue by saschagehlich** [yarnpkg/yarn#827]
**Do you want to request a _feature_ or report a _bug_?**
Request a feature

**What is the current behavior?**
When compatibility errors occur, yarn prints something like this:

```
error pngjs@0.4.0: The engine "node" is incompatible with this module. Expected version "0.8.x".
error Found incompatible module
```

In my case, pngjs is some deep sub-dependency. From the current output I can't see which dependency I need to update in order (possibly) fix this issue.

**What is the expected behavior?**
I'd like to see the dependency path, similarly to the output yarn generates for deprecation messages:

```
warning nightwatch > mocha-nightwatch > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by saschagehlich** [comment]
I'd like to tackle this by myself, but:

It seems that deprecation issues are handled by the package resolving step, which has access to all the PackageRequests and their parents, allowing it to iterate through parents and print out the dependency path.

Compatibility is handled by the PackageCompatibility though, which does not have access to the package requests and therefor does not know about the way dependencies are related to each other.

Would it make sense to make `PackageResolver#init` return all (fulfilled) requests, pass them to the PackageCompatibility module which uses the requests to check for compatibility issues? This way it would have access to the package's `parentRequest` variable and could walk up the parents.

Am I making sense here?

**Comment by H34D** [comment]
Having the same Problem but with different package:

[2/4] Fetching packages...
error zombie@4.2.1: The engine "node" is incompatible with this mod
ule. Expected version "^4.0.0".
error Found incompatible module
info Visit http://yarnpkg.com/en/docs/cli/install for documentation
 about this command.

i have node 6+ installed, so this should not pop up ,,

**Comment by saschagehlich** [comment]
@H34D: `^4.0.0` means `4.x.x`, so `6.x.x` doesn't match the pattern.

**Comment by H34D** [comment]
yea, you are right, my bad sorry. thought it was >= 4.x.x

**Comment by genu** [comment]
Is there a recommended workaround for this? 

Someone suggested in another issue to introduce a flag to force the install anyway, but that issue is also open I believe.

**Comment by erikdonohoo** [comment]
Same issue here.  Would love a workaround

**Comment by thomaslindstrom** [comment]
Same as with @H34D. Zombie wants `>=4.0.0`, but Yarn fails with `incompatible` `Expected version "^4.0.0"`:
https://github.com/assaf/zombie/blob/master/package.json#L14

**Comment by likealcohol** [comment]
Also have that issue;
`error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".`

**Comment by evasilevsky** [comment]
I also have this issue. 
`owl.carousel@2.1.4: The engine "node" is incompatible with this module. Expected version "~0.10.28".`

**Comment by costasapostolopoulos** [comment]
pngjs@0.4.0: The engine "node" is incompatible with this module. Expected version "0.8.x".

Same here

**Comment by lielran** [comment]
working with v0.15.1(currently master branch). npm build and use the binary in bin folder to building my project( run with --ignore-engines) works for me. 
something like:
```
$ cd YOUR_PORJECT_DIR

$../PATH_TO_YOUR_LOCAL_YARN_REPO/yarn/bin/yarn install  --ignore-engines
```

**Comment by erikdonohoo** [comment]
The `--ignore-engines` flag is in the master branch, as @lielran has mentioned, and the next cut release should fix this issue, assuming you use the flag.

**Comment by saschagehlich** [comment]
Guys, this issue is not about a bug in the engine compatibility check. This issue is requesting a feature that shows you which packages has the broken dependency.

**Comment by FredyC** [comment]
Got something little different than just version incompatibility...
```
error babel-plugin-react-require@2.1.0: The platform "win32" is incompatible with this module.
error babel-plugin-react-require@2.1.0: The CPU architecture "x64" is incompatible with this module.
error Found incompatible module
```

**Comment by darrylyoung** [comment]
As with a few others, I'm seeing:

```
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
```

**Comment by lipis** [comment]
@darrylyoung We had exactly the same issue.. and we killed the whole dependency which used it.. try this to find it :)

```
npm ls hawk
```

(Obviously this is not a solution.. more like a workaround)

**Comment by saschagehlich** [comment]
I'm gonna close this issue since people don't seem to understand the idea behind this feature request.

**Comment by gre** [comment]
I think this feature of seeing where the dependency is would be nice. in the meantime, a workaround is to use NPM and to do `npm ls dep`
e.g.
```
npm ls pngjs
tests@ ...
└─┬ baboon-image@2.0.0
  └─┬ ndpack-image@2.0.0
    └─┬ save-pixels@1.0.0
      └── pngjs@0.4.0
```

**Comment by scheMeZa** [comment]
yarn --ignore-engines works.

**Comment by stevecj** [comment]
`npm ls` is not helping in the case of the `error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x"` error. `hawk@0.10.2` does not show up anywhere in the output though higher-numbered versions do.

**Comment by Kolovrat19** [comment]
Try:
yarn install --ignore-engines

**Comment by cvladulescu** [comment]
> Try:
> `yarn install --ignore-engines`

@Kolovrat19 Worked like a charm. Thanks a lot 👍

**Comment by none-17** [comment]
1. npx npm-check-updates -u to update all the packages
2. Delete lockfiles and the node_modules folder
3. Run npm run build or npm run serve with --force
4. This works for deployment issues on netlify
