### ISSUE TITLE
optionalDependencies which do not exist fail the build

### ISSUE THREAD

**Issue by JamesSeymour** [yarnpkg/yarn#8271]
### Bug description
If you have dependency which is added under optionalDependencies that does not exist, it fails the install. The install should warn the end user that the dependency could not be found and continue as normal.

This expected behaviour is mentioned in the yarn documentation, but does not actually work correctly (https://yarnpkg.com/lang/en/docs/dependency-types/) -

> Optional dependencies are just that: optional. If they fail to install, Yarn will still say the install process was successful.

This behaviour works as expected when using NPM, but not with yarn.

**Command**

```sh
yarn install
```

**What is the current behavior?**
The install fails with a message detailing the package could not be found:
`error An unexpected error occurred: "https://registry.yarnpkg.com/my-package-that-does-not-exist-0000000001: Not found".`

**What is the expected behavior?**
The expectation is the user is warned that the package could not be found, but the install continues.

**Steps to Reproduce**
Attempt to install the following package.json
```{
  "name": "my-test-app",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "optionalDependencies": {
    "my-package-that-does-not-exist-0000000001": "1.0.0"
  }
}
```

**Environment**

- Node Version: `12.16.3`
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows 10

**Comment by Makoehle** [comment]
I noticed the same problem and raised a bug ticket here with details as well. Noticed that with npm everything works fine and this is only related to the yarn cli. Therefor I closed the ticket at npm.

https://github.com/npm/cli/issues/1934

**Comment by merceyz** [comment]
See https://github.com/yarnpkg/berry/issues/2425#issuecomment-770361283
