### ISSUE TITLE
str.trim is not a function

### ISSUE THREAD

**Issue by VottusCode** [yarnpkg/yarn#8280]
### Bug description
In issue #960 I've discovered that you can enable the emojis in yarn by setting --emoji to true.
I wanted to do so, that is why I've executed the command below. Unfortunetely that didn't work.
I've tried on my Windows 10 laptop running LTS version of Node.js (12.18.3) and it worked there.

**Command**

```sh
yarn config set -- --emoji true
```

**What is the current behavior?**
Yarn doesn't do what the command is supposed to do and says that 'str.trim is not a function'

**What is the expected behavior?**
Setting --emoji to true by default (puts it into .yarnrc)

**Steps to Reproduce**
1. Run `yarn config set -- --emoji true`
2. Outputs `error An unexpected error occurred: "str.trim is not a function".`

**Environment**

- Node Version: `14.4.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Ubuntu 18.04 (Budgie)

**Comment by alanrps** [comment]
Hello, I tried to reproduce the bug using the mentioned versions, but no error was returned. Are you still having this problem?

**Comment by VottusCode** [comment]
No, the issue was with the yarn config file, it couldn't be parsed as the command screwed it up.
