### ISSUE TITLE
Yarn replaces slash with %2f

### ISSUE THREAD

**Issue by lucasjohnston** [yarnpkg/yarn#8282]
### Bug description
When running `yarn add` against a package such as `@react-native-firebase/app`, the / gets replaced with `%2f` and so fails to be found by the registry.

**Command**

```sh
yarn add @react-native-firebase/app
```

**What is the current behavior?**
```sh
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-firebase%2fapp: Not found".
```

**What is the expected behavior?**
It installs

**Steps to Reproduce**
1. Run `yarn add @react-native-firebase/app` (syntax as https://classic.yarnpkg.com/en/package/@react-native-firebase/app)
2. See above error

**Environment**

- Node Version: `12.18.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: macOS Catalina 10.15.6

## Update (6/8/2020, 10:09UTC)
Running `npm view @react-native-firebase/app` throws a 404, so I'm guessing this is an issue at the npm registry, not with yarn.
Yup - stay tuned for incident updates here: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by mutantkeyboard** [comment]
This is literally the same problem I have at the moment with Rails + Webpacker

```
Arguments: 
  /usr/local/Cellar/node/14.6.0/bin/node /usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js

Yarn version: 
  1.22.4

Node version: 
  14.6.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@rails%2fujs: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:66987:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:140748:22)
      at Request.emit (events.js:314:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:141720:10)
      at Request.emit (events.js:314:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:141642:12)
      at Object.onceWrapper (events.js:420:28)
      at IncomingMessage.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1244:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

npm manifest: 
  {
    "name": "demo",
    "private": true,
    "dependencies": {
      "@rails/ujs": "^6.0.3-2",
      "turbolinks": "^5.2.0",
      "@rails/activestorage": "^6.0.3-2",
      "@rails/actioncable": "^6.0.3-2"
    },
    "version": "0.1.0"
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  actioncable@^6.0.0:
    version "5.2.4"
    resolved "https://registry.yarnpkg.com/actioncable/-/actioncable-5.2.4.tgz#744f555f16d87413044f81074a9cc4d2cf416502"
    integrity sha512-2mCP0eKTjxtDWNPqP6xPar9a5i8F/pndrTHJGU6QDS1a77B+DlPEWzPRiyNAaNEGMY/9yTBOP3CXhR+8/zaVQw==
  
  activestorage@^6.0.0:
    version "5.2.4"
    resolved "https://registry.yarnpkg.com/activestorage/-/activestorage-5.2.4.tgz#758650e01cbb2ce0e3e80e4b20a7641a021a5412"
    integrity sha512-3HDU9nCt/wn4yisSdS7wd32YPZgKRfwq2BE4kA7yuAQYKn+/X2S1sM8nAtnfPQRZIWarabIvGjbVzJNsERAb5Q==
    dependencies:
      spark-md5 "^3.0.0"
  
  spark-md5@^3.0.0:
    version "3.0.1"
    resolved "https://registry.yarnpkg.com/spark-md5/-/spark-md5-3.0.1.tgz#83a0e255734f2ab4e5c466e5a2cfc9ba2aa2124d"
    integrity sha512-0tF3AGSD1ppQeuffsLDIOWlKUd3lS92tFxcsrh5Pe3ZphhnoK+oXIBTzOAThZCiuINZLvpiLH/1VS1/ANEJVig==
  
  turbolinks@^5.2.0:
    version "5.2.0"
    resolved "https://registry.yarnpkg.com/turbolinks/-/turbolinks-5.2.0.tgz#e6877a55ea5c1cb3bb225f0a4ae303d6d32ff77c"
    integrity sha512-pMiez3tyBo6uRHFNNZoYMmrES/IaGgMhQQM+VFF36keryjb5ms0XkVpmKHkfW/4Vy96qiGW3K9bz0tF5sK9bBw==
  
  ujs@^6.0.0:
    version "0.34.1"
    resolved "https://registry.yarnpkg.com/ujs/-/ujs-0.34.1.tgz#bd1b5046fe24508930206b4c1d481940f3c1e993"
    integrity sha512-JKFU8zzKj3dLV7uPnIBefPhCtGCfgFdlYAVeRVNX33zh7sU8Vfy4Q0WiDRA6StRxvUG1Yf0uuJo1BCM3di3xrg==

```

**Comment by KazakovKirill** [comment]
Same issue also :(

**Comment by kevin-smartpatients** [comment]
I have the same issue with @rails/webpacker. Are we dead in the water until this is fixed or is there a workaround?

**Comment by nguyenvannghi** [comment]
Any body help! Same here

**Comment by connorjburton** [comment]
Have been upgrading packages all morning, I noticed this intermittently happening and now it happens every time.

```

**Comment by danchapuk** [comment]
error An unexpected error occurred: "https://registry.yarnpkg.com/@rails/ujs/-/ujs-6.0.3.tgz: Request failed \"404 Not Found\"".
Same here

**Comment by rsaleri** [comment]
**https://github.com/yarnpkg/yarn/issues/8279#issuecomment-669838465**

**Comment by magdalenalipka** [comment]
I get this error in gitlab compilation:
```error An unexpected error occurred: "https://registry.yarnpkg.com/@sindresorhus/is/-/is-3.0.0.tgz: Request failed \"404 Not Found\"".```
Half an hour ago everything was fine, but now when i recompile the same code, it breaks.

**Comment by lucasjohnston** [comment]
Closing this issue as the incident's over (and it wasn't a yarn problem) 👍

**Comment by Asd2812** [comment]
This problem is happening for me again, does anyone have the same issue?

**Comment by 3dx-tech** [comment]
I think it problem with the wrong registry path.
try `npm config set registry https://registry.npmjs.org/`
