### ISSUE TITLE
@nodelib/fs.walk/-/fs.walk-1.2.4.tgz: Request failed \"404 Not Found\"".

### ISSUE THREAD

**Issue by anqaka** [yarnpkg/yarn#8284]
### Bug description

**Command**

```sh
yarn
```

**What is the current behavior?**

yarn install v1.19.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@nodelib/fs.walk/-/fs.walk-1.2.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/project/vendor/snowdog/frontools/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**What is the expected behavior?**

**Steps to Reproduce**

Yarn is run with circle ci in this repo: https://github.com/SnowdogApps/magento2-alpaca-theme

**Environment**
- Node Version: `>=12.13.0 <13.0.0`
- Yarn v1 Version: `v1.19.1` 
- OS and version: circleci, Docker Engine Version: 18.09.6, Starting container circleci/php:7.1-fpm-node-browsers

**Comment by inyono** [comment]
Most likely duplicate of #8279 (NPM Registry is having issues right now)

**Comment by anqaka** [comment]
yes, right, works right now, thanks
