### ISSUE TITLE
Error 404 when installing packages

### ISSUE THREAD

**Issue by dpueblos** [yarnpkg/yarn#8287]
### Bug description

$ yarn && nps build
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ cd ./app && yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@getflywheel/local-addon-broken-link-checker/-/local-addon-broken-link-checker-1.0.9.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\daisy\\source\\repos\\flywheel-local\\app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Command**

```sh
yarn && nps build
```

**What is the current behavior?**

**What is the expected behavior?**

packages installed

**Environment**

- Node Version: v12.18.3
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows Pro

**Comment by rally25rs** [comment]
The `@getflywheel/local-addon-broken-link-checker` package does not exist on the npm registry, or is a private package. If it is a private package then you may need to add an `authToken` to your `.yarnrc`

**Comment by paul-soporan** [comment]
Closing as unactionable.
