### ISSUE TITLE
Unknown error on 'yarn install' command run. step '4/4 building fresh packages'. 

### ISSUE THREAD

**Issue by DillonHirth** [yarnpkg/yarn#8288]
### Bug description
[12:04:26][Step 1/5] [4/4] Building fresh packages...
[12:04:28][Step 1/5] error An unexpected error occurred: "D:\\TeamCity\\Agent\\work\\MyApp\\node_modules\\spawn-sync: UNKNOWN: unknown error, open 'D:\\TeamCity\\Agent\\temp\\buildTmp\\yarn--1596819867950-0.5528071888088233\\yarn'".

as shown above, i cannot figure out what this error might be. the yarnerror.log shows the same. all files exist? and it doesnt happen every time. we cannot seem to figure out a pattern. sometimes its twice in a row that the build will fail. others only once. 

 
**Command**
 yarn install
 
**What is the current behavior?**
it breaks as shown above. but not in any reproducible manner. 
 
 
**What is the expected behavior?**
to build packages successfully like it does normally. 
 
 
**Steps to Reproduce**
have yet to determine this. 

**Environment**
 
- Node Version: `x.x.x`
- Yarn v1 Version: v1.12.3 
- OS and version: Windows Server 2016, version 10.0

**Comment by VottusCode** [comment]
You haven't given us more information. I believe there's a issue template for this?

Here it is: https://pastebin.com/KAP3enni

**Comment by paul-soporan** [comment]
Closing as unactionable without a reproduction.
