### ISSUE TITLE
Yarn is not working - EROFS: read-only file system, mkdir '/cache'

### ISSUE THREAD

**Issue by tolgacesur** [yarnpkg/yarn#8297]
### Bug description

All commands except `yarn -v` give the `error An unexpected error occurred: "EROFS: read-only file system, mkdir '/cache'".`

**Command**

```sh
yarn
```

**What is the current behavior?**

<img width="598" alt="Screen Shot 2020-08-14 at 10 59 17" src="https://user-images.githubusercontent.com/17507470/90234268-17592e00-de28-11ea-80ce-4d8eaf1e27ec.png">

**What is the expected behavior?**

installing packages and running properly.

**Steps to Reproduce**

1. yarn

**Environment**

- Node Version: `12.17.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: macOS Catalina 10.15.6

**Comment by tolgacesur** [comment]
```
Arguments:
  /usr/local/Cellar/node@12/12.18.3/bin/node /usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js

PATH:
  /usr/local/opt/node@12/bin:/usr/local/opt/node@12/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

Yarn version:
  1.22.4

Node version:
  12.18.3

Platform:
  darwin x64

Trace:
  Error: EROFS: read-only file system, mkdir '/cache'

npm manifest:
  No manifest

yarn manifest:
  No manifest

Lockfile:
  No lockfile
```

**Comment by tolgacesur** [comment]
up

**Comment by tolgacesur** [comment]
I think this is related with node version.

**Comment by leizhilong** [comment]
@tolgacesur 

Hey there. 

Same issue here. 

```
Yarn version: 
  1.22.10

Node version: 
  15.10.0

Platform: 
  darwin x64

```

`EROFS: read-only file system, mkdir '/npm-packages-offline-cache'`

Could you plz share how did u solve this problem ? 

Thx.

**Comment by tolgacesur** [comment]
hi @leizhilong 

I uninstalled yarn and node. I install node and yarn with different version and solved this problem. I think this is a compatibility issue of yarn and node versions

**Comment by leizhilong** [comment]
hi, @tolgacesur 
Thanks for the repley. 
I tried reinstalling yarn with homebrew and npm, but nothing worked, which is pretty odd.
I'll try your way. 
Thanks again.

**Comment by leizhilong** [comment]
update:
by removing a stupid line in `~/.yarnrc` which misconfigured yarn to use `/npm-packages-offline-cache` as local cache directory, I finally solved this problem.

Nothing to do with yarn itself, just another mistake.
