### ISSUE TITLE
"Error: EBADF: bad file descriptor, read" when running "nohup yarn start"

### ISSUE THREAD

**Issue by maximilia** [yarnpkg/yarn#8307]
Unable to run yarn start with nohup.

```sh
nohup yarn start &
```

**Steps to Reproduce**
1. npx create-react-app my-app
2. cd my-app
3. nohup yarn start &

**Environment**

- Node Version: `v12.18.3`
- Yarn v1 Version: `1.22.4` 
- OS and version: CentOS Linux release 8.2.2004 (Core)

Error:

```
Starting the development server...

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:191:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Idolphint** [comment]
https://stackoverflow.com/questions/16604176/error-ebadf-bad-file-descriptor-when-running-node-using-nohup-of-forever

**Comment by RDIL** [comment]
See Idolphint's comment.
