### ISSUE TITLE
WLS Problem

### ISSUE THREAD

**Issue by mateushnsoares** [yarnpkg/yarn#8308]
### Bug description

Yarn bins in wsl sometimes not work for example with electron, puppeteer, cypress

**Command**

```sh
yarn electron . # electron is a example
```

**What is the current behavior?**

Error on run especial bins that need to open a program in os

**What is the expected behavior?**

Detect that is using wsl and install windows binaries.

**Steps to Reproduce**

1. Run this:
```sh
mkdir yarn-wls-bin
cd $_
yarn init -y
yarn add electron
touch index.js
yarn electron . # here is error yarn detect that the os is Linux and install Linux executable that not work in wls
```

**Environment**

- Node Version: `12.18.2`
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows 10. Ubuntu:  20.04.1 LTS

**Comment by oliversalzburg** [comment]
Linux executables work perfectly in WSL. That is the entire point.

**Comment by mateushnsoares** [comment]
I found I workaround that work **FINE**, install chocolatey on windows run and `choco install vcxsrv -y` and run installed .exe (XLaunch), click in next, click in next, add to bellow input `-ac` click in next and Be Happy, (exec always on start windows)
