### ISSUE TITLE
Add command line option to change cache path

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#831]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
yarn use `~/.yarn-cache/` as cache directory.

**What is the expected behavior?**
`yarn --cache-path my-cache` would use `./my-cache` as cache directory.

**Please mention your node.js, yarn and operating system version.**
yarn 0.15.1 and nove 6.7.0

**Comment by hufeng** [comment]
+1

**Comment by Andy1210** [comment]
+1

**Comment by kittens** [comment]
What's the use-case?

**Comment by victornoel** [comment]
@kittens for use in a CI with distributed runners where it is not always clear where is the home, or if I can actually write to it or things like that. I want to be 100% sure to where the cache is and decide it (so that it can be cached by the CI).

**Comment by victornoel** [comment]
(actually, it is not that I want to be 100% sure, it is that in CI like gitlab-ci, you can't cache stuffs outside of the build directory!)

**Comment by kittens** [comment]
Created #881 to fix this, pending approval.

**Comment by victornoel** [comment]
Excellent, thanks @kittens :)
