### ISSUE TITLE
`Yarn` wipes ~/node_modules

### ISSUE THREAD

**Issue by RobinStamer** [yarnpkg/yarn#8316]
### Bug description

**Command**

```sh
yarn
```

(Yes, no arguments)

**What is the current behavior?**

Yarn wipes ~/node_modules completely clean

**What is the expected behavior?**

Yarn doesn't make me pull things out of a backup.  I understand this is somehow related to yarn wanting node_modules to match what's in package.json.  All I want is to install stuff, not have to keep a ~/package.json file.

**Steps to Reproduce**

1. `yarn`

**Environment**

- Node Version: `14.7.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Spark

**Comment by danielhuang** [comment]
It's recommended practice to declare everything your project needs in `package.json`. Running `yarn add <package name>` will add it automatically.

**Comment by rally25rs** [comment]
> All I want is to install stuff, not have to keep a ~/package.json file.

yarn might not be the right tool for the job then. It is not intended to install npm packages without tracking tracking them in package.json.

the `yarn` commands runs `yarn install` by default, which changes `node_modules` to match the packages listed in `package.json`.

Where I think things get a little weird is that if you don't have a `package.json` file at all, `yarn` considers that to be an empty set of packages by default, and clears out `node_modules`. It does seem like if no `package.json` is found, there should maybe be a warning or error.

**Comment by paul-soporan** [comment]
Closing as unactionable.
