### ISSUE TITLE
yarn install removes everything from /client/assets folder

### ISSUE THREAD

**Issue by davscro** [yarnpkg/yarn#832]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I run **yarn install** everything under the folder client/assets is removed (including all subfolders and files). Is there any flag to prevent this behaviour?

**Please mention your node.js, yarn and operating system version.**
yarn 0.15.1
node 5.10.1
OS: Windows 10

**Comment by skuridin** [comment]
Do you use bower in that director by any chance?

**Comment by havana59er** [comment]
Not sure if this is related, but yarn removes the lib/assets folder when installing istanbul. ```npm install istanbul``` will recover the folder.

**Comment by havana59er** [comment]
And I found the culprit - I had a .yarnclean file in my project. After I removed this file, yarn no longer removes the assets folder from istanbul.

**Comment by davscro** [comment]
@skuridin no, I'm not using bower

**Comment by davscro** [comment]
**This is my folder structure**

<img width="183" alt="screen shot 2016-10-15 at 19 31 02" src="https://cloud.githubusercontent.com/assets/1383250/19412153/ba94d668-930f-11e6-8436-60152f55ec8f.png">


So, once when I start yarn install everything within assets folder has been removed

**Comment by gitawego** [comment]
I have exactly the same problem. yarn removes assets automatically if .yarnclean in the project.
