### ISSUE TITLE
yarn install network error

### ISSUE THREAD

**Issue by HumayounBaig** [yarnpkg/yarn#8327]
hey guys,

since today morning me and a couple of my friends are having trouble installing any package using yarn.
Whenever we run `yarn `or `yarn install` the following error is displayed.

![image](https://user-images.githubusercontent.com/32910163/91729385-e9ad0c80-ebbd-11ea-9a95-ccd74ee9a62c.png)

Any help would be appreciated we tried clearing cache, reinstalling yarn, removing proxy and many other solutions from stackoverflow of similar problem faced by others to no avail.

Devices tested on:
Dell inspiron 15 (windows 10)
macbook pro (macos catalina)
dell latitude (windows 10)

**Comment by paul-soporan** [comment]
Closing as fixed in v2 where the timeout and retry logic has greatly improved.

https://yarnpkg.com/getting-started/migration
