### ISSUE TITLE
Yarn wrong resolution of dependencies

### ISSUE THREAD

**Issue by glumia** [yarnpkg/yarn#8328]
### Bug description
Yarn is not recognizing that two different dependencies which in turn depend on another package could have both their dependency satisfied installing the most recent version of that package and is instead installing two different versions of it, one newer and one older. 

__This bug only occurs if there's already something in the `yarn.lock` file as in the example provided.__

Detailed steps to reproduce the bug are provided below.

**Command**

```sh
yarn install
```

**What is the current behavior?**
Yarn causes the installation of two different versions of the same package even if only one of them would be sufficient.

(*In my case this is was a problem because one of the two versions was outdated and had security vulnerabilities, causing my project's CI to fail.*)

**What is the expected behavior?**
Only the latest of the two versions of the package should be installed.

**Steps to Reproduce**
1. Put the following in `package.json`:
```json
{
  "devDependencies": {
    "@commitlint/cli": "^10.0.0",
    "@commitlint/config-conventional": "^10.0.0",
    "standard-version": "^9.0.0"
    }
}
```
2. Put the following in the `yarn.lock` file:
```
conventional-changelog-angular@^5.0.0, conventional-changelog-angular@^5.0.10:
  version "5.0.10"
  resolved "https://registry.yarnpkg.com/conventional-changelog-angular/-/conventional-changelog-angular-5.0.10.tgz#5cf7b00dd315b6a6a558223c80d5ef24ddb34205"
  integrity sha512-k7RPPRs0vp8+BtPsM9uDxRl6KcgqtCJmzRD1wRtgqmhQ96g8ifBGo9O/TZBG23jqlXS/rg8BKRDELxfnQQGiaA==
  dependencies:
    compare-func "^1.3.1"
    q "^1.5.1"
```
3. Execute `yarn` or `yarn install`
4. Now check the content of the`yarn.lock`, there should be the following lines:
```
conventional-changelog-angular@^5.0.0:
  version "5.0.10"
  resolved "https://registry.yarnpkg.com/conventional-changelog-angular/-/conventional-changelog-angular-5.0.10.tgz#5cf7b00dd315b6a6a558223c80d5ef24ddb34205"
  integrity sha512-k7RPPRs0vp8+BtPsM9uDxRl6KcgqtCJmzRD1wRtgqmhQ96g8ifBGo9O/TZBG23jqlXS/rg8BKRDELxfnQQGiaA==
  dependencies:
    compare-func "^1.3.1"
    q "^1.5.1"

conventional-changelog-angular@^5.0.11:
  version "5.0.11"
  resolved "https://registry.yarnpkg.com/conventional-changelog-angular/-/conventional-changelog-angular-5.0.11.tgz#99a3ca16e4a5305e0c2c2fae3ef74fd7631fc3fb"
  integrity sha512-nSLypht/1yEflhuTogC03i7DX7sOrXGsRn14g131Potqi6cbGbGEE9PSDEHKldabB6N76HiSyw9Ph+kLmC04Qw==
  dependencies:
    compare-func "^2.0.0"
    q "^1.5.1"
```

**Environment**

- Node Version: `14.9.0`
- Yarn v1 Version: `1.22.5` 
- OS and version: macOS 10.14.6

**Comment by merceyz** [comment]
This is working as intended, Yarn wont change unrelated resolutions as adding/upgrading a unrelated dependency shouldn't change and potentially break another.

If you want them to be deduplicated then there is a command for that in v2 https://yarnpkg.com/cli/dedupe

https://yarnpkg.com/getting-started/migration

**Comment by glumia** [comment]
Okay, thanks for the info!
