### ISSUE TITLE
Contributing.md points to broken link

### ISSUE THREAD

**Issue by asklar** [yarnpkg/yarn#8335]
Contributing.md points to https://yarnpkg.com/org/contributing/ which is a dead link
![image](https://user-images.githubusercontent.com/22989529/92662178-28744e00-f2b3-11ea-9077-8a338efaa6e3.png)

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/commit/0a121f66ffcb4fc48ed6ea9e5ad928bd7cdc9b5f
