### ISSUE TITLE
Segmentation fault on yarn add

### ISSUE THREAD

**Issue by diniciacci** [yarnpkg/yarn#8339]
### Bug description

**Command**

```sh
yarn add <package_on_npm>#<version_that_does_not_exits>
```
result is
```
[1/4] Resolving packages...
[2/4] Fetching packages...
[#-] 1/2Segmentation fault
```

**What is the current behavior?**
The program segfaults.

**What is the expected behavior?**
It would be nice to know the **package** that caused the problem and a graceful message telling you that the specified **version** of the package is not available.

In particular it's impossible to know which package is causing the problem if what you have is a package.json with already all the dependencies listed in it. The problem is also present in case someone uses an "unpublish" feature in a repo.

**Steps to Reproduce**
```sh
mkdir yarntest
cd yarntest
yarn init
yarn add <package_on_npm>#<version_that_does_not exits>
```

**Environment**

- Node Version: 
v12.18.1
- Yarn v1 Version:
1.22.5
- OS and version: 
Linux 5.6.0-1-amd64 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux

**Comment by diniciacci** [comment]
Digging a little more I can add a note that in the same empty repo, just doing a `yarn add dijit#1.10.3` segfaults even if that version exists.

steps:
```sh
mkdir yarntest2
cd yarntest2
yarn init
yarn add dijit#1.10.3
```
resuilt:
```
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[--] 0/2Segmentation fault
```

**Comment by merceyz** [comment]
Unable to reproduce with both v1 and v2
