### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by niltonvaz** [yarnpkg/yarn#8344]
**Which operating system are you using:**

Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Instalei o yarn com o chocolatey e nada!
choco install -y nodejs-lts yarn python2 jdk8

Instalei com o node e nada!
Scoop install node,js

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
