### ISSUE TITLE
Yarn Workspace, how to exclude package files to be included in node_modules?

### ISSUE THREAD

**Issue by panda0603** [yarnpkg/yarn#8345]
### Bug description

I am trying to find functionality equal to .npmignore for yarn workspaces. 

For example, let's say I have test, src(typescript) and lib(compiled javascript) folder in a package name called '@walnut/peanut'. 

I only need the compiled 'lib' folder in node_modules, so I only want lib folder to be included in node_modules/@walnut/peanut folder when yarn install.
 
I have tried putting .npmignore file in the package (obviously, but just in case), but it still seems to include all the files, not just lib folder. Also tried specifying following in package.json, but no luck

```
{
...,
files:["/lib"],
}
```

How do I configure this? 

Thanks

**Environment**

- Node Version: `12.18.3`
- Yarn v1 Version: `1.22.5` 
- OS and version: MacOS

**Comment by merceyz** [comment]
Workspaces are just symlinks in `node_modules` to avoid having to run an install every time you make changes those kinds of settings are ignored
