### ISSUE TITLE
NPM start issue Error

### ISSUE THREAD

**Issue by ibrohim123** [yarnpkg/yarn#8347]
//My package.json

{
  "name": "amazone-clone",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.11.1"
  }
}

//My error
npm ERR! code EISDIR
npm ERR! syscall read
npm ERR! errno -4068
npm ERR! EISDIR: illegal operation on a directory, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2020-09-17T06_04_32_926Z-debug.log
PS C:\Users\ACER\Desktop\AnyThink React>

//I used a lot of packages, configured the global path, even deleted node_modules, package-lock.json 
//Almost I did everything but I couldn't fix it please HELP ME!!!

**Comment by merceyz** [comment]
Based on your logs you're using NPM not Yarn, so you need to raise your issue with them https://github.com/npm/cli
