### ISSUE TITLE
"Contributing" link in README.md jumps to NOT FOUND page

### ISSUE THREAD

**Issue by Mozuha** [yarnpkg/yarn#8350]
The "Contributing" link under "Contributing to Yarn" section in README.md jumps to [this NOT FOUND page](https://yarnpkg.com/org/contributing/). 

It is the same for the link in [here](https://github.com/yarnpkg/yarn/blob/master/CONTRIBUTING.md) and the "contributing guidelines" link in the notification that says "It looks like this is your first time opening an issue in this project! Be sure to review the contributing guidelines and code of conduct."

Is [this](https://yarnpkg.com/advanced/contributing) the destination expected?

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/commit/0a121f66ffcb4fc48ed6ea9e5ad928bd7cdc9b5f
