### ISSUE TITLE
yarn build infinite loop?

### ISSUE THREAD

**Issue by flyingpurplepeopleeater** [yarnpkg/yarn#8351]
Hello there!

I'm trying to deploy something to Heroku: it is a Rails app (todo-api) with a React frontend (reactbasic, a folder inside todo-api). When I do "git push heroku master" I get something like this:

```
...
remote:        yarn run v1.22.4
remote:        $ yarn build && yarn deploy
remote:        $ yarn --cwd reactbasic install && yarn --cwd reactbasic build
remote:        [1/5] Validating package.json...
remote:        [2/5] Resolving packages...
remote:        success Nothing to install.
remote:        success Saved lockfile.
remote:        $ yarn --cwd reactbasic install && yarn --cwd reactbasic build
remote:        [1/5] Validating package.json...
remote:        [2/5] Resolving packages...
remote:        success Already up-to-date.
remote:        $ yarn --cwd reactbasic install && yarn --cwd reactbasic build
remote:        [1/5] Validating package.json...
remote:        [2/5] Resolving packages...
remote:        success Already up-to-date.
```

where the command with the $ is what I defined as my "build" script in the package.json for my Rails app, and it keeps looping those last 4 lines as shown.

Here are the scripts for my package.json in my Rails app:
```
		"build": "yarn --cwd reactbasic install && yarn --cwd reactbasic build",
		"deploy": "cp -a reactbasic/build/. public/",
		"heroku-postbuild": "yarn build && yarn deploy"
```
Here are the scripts for the package.json in my React app inside:
```
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
```
Any idea what is causing this loop? It appears that in the past people have had problems with yarn install, but this seems to be more of an issue with build, because if I remove "yarn --cwd reactbasic install" from my Rails package.json, I still get an infinite loop:
```
remote:        $ yarn --cwd reactbasic build
remote:        $ yarn --cwd reactbasic build
remote:        $ yarn --cwd reactbasic build
remote:        $ yarn --cwd reactbasic build
...
```

Any ideas?

**Comment by flyingpurplepeopleeater** [comment]
Resolved: my repositories were wonky and I reinstalled yarn

**Comment by dzmitry-lahoda** [comment]
i have same, what is wonky means? i have fresh install

**Comment by flyingpurplepeopleeater** [comment]
I just mean that I had a bunch of branches that were out of order and things were not installed the way they should be. Unfortunately I'm very much a beginner at this and since it was almost a year ago I don't remember much but best of luck!
