### ISSUE TITLE
info command missing

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/yarn#8362]
is the info command in a plugin? if so could the documentation document which one? if not... why is it here https://yarnpkg.com/cli/info

```
> yarn info peer                                                       # services/.../s3-upload -> feature/RS2-1229-s3-upload-schema $ RC=1
Usage Error: Couldn't find a script named "info".
```

```
> yarn --version                                                       # services/.../s3-upload -> feature/RS2-1229-s3-upload-schema $ RC=1
2.2.2
```

**Comment by eoingroat** [comment]
This is the repo for yarn v1, as you're using yarn v2.2.2 the issue technically belongs over here https://github.com/yarnpkg/berry/issues

The docs linked *are* for yarn v2.

The latest version of yarn v2, as of the last few days, is v2.3.0. This supports the info command, version v2.2.0 did not.

I think you might have been the victim of some unfortunate timing whereby v2.3.0 was used to generate the docs but not released; though I'm not sure without digging into the website build and release system!

You can upgrade yarn in your project using (`yarn set version latest`)[https://yarnpkg.com/cli/set/version/]

**Comment by xenoterracide** [comment]
ah, thanks, and sorry for using the wrong repo.
