### ISSUE TITLE
`yarn bisect` or similar

### ISSUE THREAD

**Issue by tlrobinson** [yarnpkg/yarn#837]
This is a sort of crazy feature request, but I've always thought something like [`git bisect`](https://git-scm.com/docs/git-bisect) for a package manager would be neat.

If I update a package (or multiple packages), and it breaks my app I'd like to quickly figure out exactly which package/version broke it. Or maybe I want to figure out which version of my own package broke some behavior.

**Comment by samccone** [comment]
Hi, mind opening this request here?

Thanks

https://github.com/yarnpkg/rfcs
