### ISSUE TITLE
`1.22.10` release is inconsistenly tagged without `v` prefix

### ISSUE THREAD

**Issue by teka23** [yarnpkg/yarn#8371]
### Bug description

`1.22.10` release is tagged inconsistenly as `1.22.10` compared to `v1.22.5` etc. This is breaking some CI.

https://github.com/yarnpkg/yarn/releases/tag/1.22.10
https://github.com/yarnpkg/yarn/releases/tag/v1.22.5

**What is the expected behavior?**

Version `1.22.10` will be tagged consistently with previous versions.

**Comment by teka23** [comment]
@arcanis

**Comment by arcanis** [comment]
Fixedd
