### ISSUE TITLE
Cannot run command yarn install

### ISSUE THREAD

**Issue by paokrissana** [yarnpkg/yarn#8377]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**
Yarn version : 1.22.5

Issue: Cannot run command yarn install, when I run yarn install I always got this error shown in the console **An unexpected error occurred: "UNKNOWN: unknown error, unlink 'C:\\Users\\myusername\\AppData\\Local\\Yarn\\Cache\\v6\\npm-websocket-extensions-0.1.3-5d2ff22977003ec687a4b87073dfbbac146ccf29\\node_modules\\websocket-extensions\\lib'".**

![image](https://user-images.githubusercontent.com/29530224/94984861-f89b2c00-057a-11eb-813b-f7c2f4ce8bdb.png)

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
