### ISSUE TITLE
run command does not set INIT_CWD properly for nested scripts (differs from npm behavior)

### ISSUE THREAD

**Issue by tsiq-wilfrid** [yarnpkg/yarn#8378]
### Bug description
When `yarn run` is used to run a package script which calls `yarn run` on another package script, the value of the environment variable `INIT_CWD` will be incorrect. INIT_CWD will refer to the initial directory of the first script, but it should refer to the initial directory of the second script.

This is an issue in two cases:
1) The first script changes the working directory to anything other than INIT_CWD, then calls a second script. In this case INIT_CWD for the second script is expected to be the new working directory, but it will be the original INIT_CWD.
2) The first script is run from a directory other than the project root (and does not change the working directory), then calls a second script. In this case INIT_CWD for the second script is expected to be the project root (since package scripts are executed in the project root), but it will be the original INIT_CWD.

In both cases, the expected behavior matches the behavior of `npm`.

**What is the current behavior?**
Yarn executes nested scripts with `INIT_CWD` set to the initial directory of the first yarn script.

**What is the expected behavior?**
Yarn executes a nested script with `INIT_CWD` set to the initial directory of the nested script (like npm).

### Steps to Reproduce

1. Create new folder `test-init-cwd`
2. Add the following code to a new file `package.json` in `test-init-cwd`
```json
{
  "license": "ISC",
  "scripts": {
    "print-cwd": "echo $INIT_CWD",
    "example": "mkdir -p testdir && cd testdir && yarn run -s print-cwd",
    "example-npm": "mkdir -p testdir && cd testdir && npm run -s print-cwd",
    "example2": "yarn run -s print-cwd",
    "example2-npm": "npm run -s print-cwd"
  }
}
```
3. Run the following commands
```sh
cd test-init-cwd
yarn run -s example
# Output: .../test-init-cwd
yarn run -s example-npm
# Output: .../test-init-cwd/testdir

mkdir -p testdir2
cd testdir2
yarn run -s example2
# Output: .../test-init-cwd/testdir2
yarn run -s example2-npm
# Output: .../test-init-cwd
cd ..
```

**Related Code**
Looks like the issue is here, where INIT_CWD will not be set if it already exists in the environment:
https://github.com/yarnpkg/yarn/blob/a3b1294c22043cd8868b6a1decb77b673e764efd/src/util/execute-lifecycle-script.js#L64-L72

Suggest moving INIT_CWD after `...process.env`, so it has priority over the existing environment:
```
...process.env,
INIT_CWD: process.cwd(),
```

**Environment**

- Node Version: `v14.13.0`
- Yarn v1 Version: `1.22.5` 
- OS and version: `macOS Catalina 10.15.7`
- npm Version: `6.14.8`

**Comment by merceyz** [comment]
Fixed in v2

https://yarnpkg.com/getting-started/migration
