### ISSUE TITLE
error TS2307: Cannot find module '@abp/ng.account/config' or its corresponding type declarations

### ISSUE THREAD

**Issue by ruby0602** [yarnpkg/yarn#8379]
1、I add package successfully: yarn add @abp/ng.account.config
![image](https://user-images.githubusercontent.com/4489940/95019794-fda2cd00-0699-11eb-9af7-652178ff2a8f.png)
2、still have error: 
![image](https://user-images.githubusercontent.com/4489940/95019894-90dc0280-069a-11eb-9c1d-7bf8b881af2d.png)

3、yarn version is 1.22.4，angular version is 10.1.4
![image](https://user-images.githubusercontent.com/4489940/95019967-ff20c500-069a-11eb-9cf6-5c5dadc4c027.png)

how can I solve the problem? thanks in advance

**Comment by ruby0602** [comment]
I had solved the problem

**Comment by RyenToretto** [comment]
hello master~ i got a problem when i `npm run build`,  how can i solve this, thanks in advance
node_modules/@types/webpack-dev-middleware/index.d.ts:10:27 - error TS2307: Cannot find module 'loglevel' or its corresponding type declarations.

10 import * as loglevel from 'loglevel';

**Comment by rkahnert-carson** [comment]
> I had solved the problem

@ruby0602 What was the solution?
