### ISSUE TITLE
Update notification is not Windows friendly [Feature]

### ISSUE THREAD

**Issue by PeteDuncanson** [yarnpkg/yarn#8380]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Just ran "yarn add axios" and got the following helpful message back about being out of date:

warning Your current version of Yarn is out of date. The latest version is "1.22.5", while you're on "1.22.4".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash

Trouble is I'm on Windows 10 and don't have curl so this won't work for me.

**Describe the solution you'd like**

Detect if I'm running on windows and show a windows version of the recommended way to upgrade. Alternatively include a link to a website that can guide me through what to do.

**Describe the drawbacks of your solution**

Its possible that they recommended way to upgrade might not be right or work all the time, hence me thinking linking to a website that could be kept up to date might be better. Further more in the future you might change the upgrade method and forget to update the windows version...always an issue when not many devs use Windows as their day to day machines.

**Describe alternatives you've considered**

A simple link to a web page for all cases makes this a better safer solution that wouldn't need updating (that would be pushed to the website instead).

**Additional context**

Even this is non-windows friendly https://classic.yarnpkg.com/en/docs/cli/self-update/

Options on how to upgrade on windows seem limited...basically just "down load the latest and re-install" seems to be the main option.

https://stackoverflow.com/questions/45953681/how-to-update-yarn-if-i-install-through-windows-installer

**Comment by merceyz** [comment]
Fixed in v2 where there is no update check and updating is done through `yarn set version ...`

https://yarnpkg.com/getting-started/migration
