### ISSUE TITLE
local package can not be resolved

### ISSUE THREAD

**Issue by yuwiggin** [yarnpkg/yarn#8383]
### Bug description

**Command**
I want to test an open source application. But the local package cannot be found when yarn start. 
```sh
yarn start
```

**What is the current behavior?**

The console complained that module @uniswap/sdk not found: 
`./src/components/CurrencyLogo/index.tsx
Module not found: Can't resolve '@uniswap/sdk' in '/Users/xxx/webProjs/sushiswap-exchange/src/components/CurrencyLogo'`

I tried add it manually.
`yarn add file:./forks/uniswap-sdk` 
`yarn start`
but also failed.  Any suggestion?

**What is the expected behavior?**

If the published package is added, the app can start successfully. 
`yarn add @uniswap/sdk`
`yarn start`

**Steps to Reproduce**

1. `git clone https://github.com/sushiswap/sushiswap-exchange.git`

2.`yarn install`
`yarn start`

**Environment**

- Node Version: `v12.16.1`
- Yarn v1 Version: `1.22.5` 
- OS and version: 
`macOS 10.12.6 `

**Comment by LukerSpringtree** [comment]
how to resolve this problem

**Comment by LukerSpringtree** [comment]
@yuwiggin
