### ISSUE TITLE
yarn: command not found; Encore

### ISSUE THREAD

**Issue by SonnyMar** [yarnpkg/yarn#8394]
I'm working on a Symfony 4.4 project and I installed bootstrap first, then when I  try to install the webpack Encore as the Symfony documentation says the command `yarn install` does not work.
It says "yarn: command not found"

Here, my package.json
`{` 
    `"devDependencies": {` 
       `"@symfony/webpack-encore": "^0.30.0",` 
        `"core-js": "^3.0.0",`
        `"regenerator-runtime": "^0.13.2",`
        `"webpack-notifier": "^1.6.0"`
   ` },`
    `"license": "UNLICENSED",`
    `"private": true,`
    `"scripts": {`
        `"dev-server": "encore dev-server",`
        `"dev": "encore dev",`
        `"watch": "encore dev --watch",`
        `"build": "encore production --progress"`
   ` }`
`}`

Can somebody help me? I'm running out of time!

**Comment by paul-soporan** [comment]
Make sure that you've installed Yarn.
