### ISSUE TITLE
Yarn ignores yarnrc file

### ISSUE THREAD

**Issue by Bidski** [yarnpkg/yarn#8397]
### Bug description
`~/.yarnrc` file contains
```sh
cacheFolder "/home/user/yarn/cache"
globalFolder "/home/user/yarn/global"
linkFolder "/home/user/yarn/link"
modulesFolder "/home/user/yarn/node_modules"
tempFolder "/home/user/yarn/temp"
```

`yarn config list` (from project root) reports
```sh
yarn config v1.22.4
info yarn config
{
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.22.4 npm/? node/v14.1.0 linux x64',
  cacheFolder: '/home/user/yarn/cache',
  globalFolder: '/home/user/yarn/global',
  lastUpdateCheck: 1602907363458,
  linkFolder: '/home/user/yarn/link',
  modulesFolder: '/home/user/yarn/node_modules',
  tempFolder: '/home/user/yarn/temp'
}
info npm config
{}
Done in 0.04s.
```

`yarn config current` (from project root) reports
```sh
yarn config v1.22.4
{
  "registryFolders": [
    "node_modules"
  ],
  "linkedModules": [],
  "cache": {},
  "cwd": "/home/user/ProjectRoot",
  "looseSemver": true,
  "commandName": "config",
  "preferOffline": false,
  "globalFolder": "/home/user/.config/yarn/global",
  "linkFolder": "/home/user/.config/yarn/link",
  "offline": false,
  "binLinks": true,
  "ignorePlatform": false,
  "ignoreScripts": false,
  "disablePrepublish": false,
  "nonInteractive": false,
  "workspaceRootFolder": null,
  "lockfileFolder": "/home/user/ProjectRoot",
  "networkConcurrency": 8,
  "childConcurrency": 5,
  "networkTimeout": 30000,
  "workspacesEnabled": true,
  "workspacesNohoistEnabled": true,
  "pruneOfflineMirror": false,
  "enableMetaFolder": false,
  "enableLockfileVersions": false,
  "linkFileDependencies": false,
  "cacheFolder": "/home/user/.cache/yarn/v6",
  "tempFolder": "/home/user/.cache/yarn/v6/.tmp",
  "production": false
}
Done in 0.04s.
```

The `NODE_PATH` environment variable is also set to `/home/user/yarn/node_modules`.

**What is the current behavior?**
Running `yarn` in the project root creates a `node_modules` folder in the project root directory, rather than in `/home/user/yarn` and yarn creates its cache in `/home/user/.cache/yarn` rather than `/home/user/yarn/cache`

**What is the expected behavior?**
I expect yarn to use `/home/user/yarn/node_modules` as the modules folder and `/home/user/yarn/cache` as the cache folder.

**Steps to Reproduce**
1. Install yarn and nodejs
2. Set `~/.yarnrc` as above
3. Run `yarn` in the project root directory

**Environment**

- Node Version: `14.1.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Arch Linux

**Comment by martha** [comment]
@Bidski do you remember what resolution you came to on this? Was it actually a yarn bug, or user error, or something else? I'm running into a similar problem and would like to hear how things ended up for you!

**Comment by Bidski** [comment]
@martha honestly I think I abandoned this not long after I posted it as it was taking too long to figure out and we found a workaround that did an acceptable enough job. Sorry I can't be of more help

**Comment by martha** [comment]
Okay, thanks for letting me know!
