### ISSUE TITLE
Mac Os error: Error: Cannot find module '/Users/xxx/.yarn/releases/yarn-1.22.1.js'

### ISSUE THREAD

**Issue by bgits** [yarnpkg/yarn#8399]
Running MacOs Catalina 10.15.7. 

After receiving warnings about yarn being out of date I tried to upgrade it. I have tried several means and yarn no longer works on the machine.

After initially using yarn upgrade

I tried using the curl script: `curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc`

The install terminates with:

```
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/Users/xxx/.yarn/releases/yarn-1.22.1.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Yarn was installed, but doesn't seem to be working :(.
```

`which yarn` returns `/Users/xxx/.yarn/bin/yarn`

Wondering how to get past this and yarn working again?

**Comment by barbalex** [comment]
I have the exact same problem. Frustrating to see that due to no solution I will have to - what exactly? Buy a new pc?

**Comment by barbalex** [comment]
I found a .yarnrc file (can't remember the exact name). Deleted it. And now everything works!!!!!

**Comment by paul-soporan** [comment]
Yep, Yarn will look for `.yarnrc` and `.yarnrc.yml` files and read the `yarnPath` field to spawn the specified binary. If the binary doesn't exist, it crashes. These files with a `yarnPath` are created when running `yarn set version` / `yarn policies set-version`, which are for *per-project* installs, so don't run it in your home directory. If you accidentaly do, just delete the generated `.yarnrc` / `.yarnrc.yml` file.

**Comment by kevinadhiguna** [comment]
Much appreciated @paul-soporan !

## Reason
I once upgraded Yarn using `yarn set version latest` and did not realize that it produces `.yarnrc` in my home directory.

## Solution
1. Removing `.yarnrc` (it existed in  home directory in mycase. Make sure you are in the directory where `.yarnrc` remains) : 
```bash
rm .yarnrc
```

2. I loaded profile config (e.g. : `.bashrc`, `.zshrc`, etc.) with : 
```bash
source ~/.zshrc
```

---

Finally `yarn -v` worked again.

**Comment by AwolDes** [comment]
@paul-soporan 
> so don't run it in your home directory.

You have made my day with this solve :smile: was going nuts trying to understand why `.yarn/releases/yarn-1.22.1.cjs --version` was giving me `3.1.0`. Sure enough, I had yarn configs in my `home` dir.

**Comment by azs-dev** [comment]
> Much appreciated @paul-soporan !
> 
> ## Reason
> I once upgraded Yarn using `yarn set version latest` and did not realize that it produces `.yarnrc` in my home directory.
> 
> ## Solution
> 1. Removing `.yarnrc` (it existed in  home directory in mycase. Make sure you are in the directory where `.yarnrc` remains) :
> 
> ```shell
> rm .yarnrc
> ```
> 
> 2. I loaded profile config (e.g. : `.bashrc`, `.zshrc`, etc.) with :
> 
> ```shell
> source ~/.zshrc
> ```
> 
> Finally `yarn -v` worked again.

If 
```shell
rm .yarnrc
```

does not work. make sure to also do

```shell
rm .yarnrc.yml
```

😃👍🏻
