### ISSUE TITLE
Yarn add issues with workspaces and eslint

### ISSUE THREAD

**Issue by felipepsq** [yarnpkg/yarn#8405]
## Bug description
Using latest version (1.22.10) and workspaces, when typing yarn add *package* in any workspace, it throws the following error:

```sh
error An unexpected error occurred: "expected workspace package to exist for \"eslint\"".
```

Setting yarn policies to 1.19.0 solved the problem.

### Command

```sh
 yarn policies set-version 1.19.0
```

**Environment**

- Yarn version: 1.22.10 (now 1.19.0)
- Node version: 12.18.4
- Platform: linux x64

**Comment by Megajin** [comment]
You Sir, are a lifesaver! Props to you!

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Comment by faq885** [comment]
Awesome, you rock man!!

**Comment by rendyadisaputra** [comment]
It's 2022, and an error like this happened again. 
`An unexpected error occurred: "expected workspace package to exist for \"@jest/transform\"".`
And is solved by downgrading my Yarn into 1.19

## Command
`yarn policies set-version 1.19.0`
It's weird but keep it as is for now.

**Comment by khaledxGo** [comment]
apt update

apt upgrade

pkg install python python2 vim figlet curl

pkg install php

pip2 install lolcat

pkg install git

git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv3

cd TOOLSINSTALLERv3

chmod +x TUANB4DUR.sh

sh TUANB4DUT.sh

**Comment by ladifire** [comment]
Thank you very much. You saved my life!

**Comment by luke-dcz** [comment]
Downgrading the yarn version could be risky as there are bug fixes in each new release. However, I found an alternative that solved the issue:
In the root package.json, updating lerna to the latest version (currently 6.1.0) and nx (15.3.0) solves this without risking downgrading yarn.

**Comment by hututuhu** [comment]
> ## Bug description
> Using latest version (1.22.10) and workspaces, when typing yarn add _package_ in any workspace, it throws the following error:
> 
> ```shell
> error An unexpected error occurred: "expected workspace package to exist for \"eslint\"".
> ```
> 
> Setting yarn policies to 1.19.0 solved the problem.
> 
> ### Command
> ```shell
>  yarn policies set-version 1.19.0
> ```
> 
> **Environment**
> 
> * Yarn version: 1.22.10 (now 1.19.0)
> * Node version: 12.18.4
> * Platform: linux x64

It solved But my eslint no longer work  :(

**Comment by iway1** [comment]
> Closing as fixed in v2
no one uses v2
