### ISSUE TITLE
yarn doctor 

### ISSUE THREAD

**Issue by luismendes070** [yarnpkg/yarn#8411]
### Bug description

**Command**

```sh
yarn [doctor]
```

**What is the current behavior?**

**What is the expected behavior?**

Android device install

**Steps to Reproduce**

1. yarn doctor 
2.

**Environment** Android Windows

- Node Version: `x12.19.0`
- Yarn v1 Version: `1.22.5` 
- OS and version: Windows and 10 Version 2004 Build 19041.572

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
