### ISSUE TITLE
Wrong information in the .yarnrc

### ISSUE THREAD

**Issue by marikaner** [yarnpkg/yarn#8416]
**Describe the bug**

When I set the yarn version (Yarn classic) a reference is added to my .yarnrc file. In addition to that reference there is also a comment that says:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
```

To my understanding this information is incorrect. The `.yarnrc` is not a lockflie and it can very much be edited directly. 

**To Reproduce**

Just run `yarn set version 1.22.4`.

**Comment by paul-soporan** [comment]
Indeed it's incorrect, but we're not going to fix it in v1.

Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
