### ISSUE TITLE
Installation Problem:  create react-app by yarn

### ISSUE THREAD

**Issue by amirkh330** [yarnpkg/yarn#8418]
when i want to create react app by yarn, i got a error:

 errror postcss@8.1.3: The engine "node" is incompatible with this module.
 my virsion of yarn 1.22
my virson of node 13.10
i install yarn by instaler and npm 

did you have my issue??

**Comment by cagataycali** [comment]
PostCSS module's package.json shows us;

```JSON
"engines": {
  "node": "^10 || ^12 || >=14"
},
```

Can you try to upgrade the node to 14 or downgrade 12?

**Comment by merceyz** [comment]
Your node version does not match the range specified by `postcss` either use a node version compatible or disable the check https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-engines
