### ISSUE TITLE
Feature: Git dependency URLs support

### ISSUE THREAD

**Issue by afhole** [yarnpkg/yarn#842]
Git urls in package.json do not work as they do for npm:

In package.json: `"some-git-dep": "git+ssh://git@gitlab.example.com:some/some-git-dep.git#1.0.0",`

When `yarn install`ing yields:

Couldn't find package "some-git-dep" on the "npm" registry.

**Comment by afhole** [comment]
A dupe of #513 I think, apologies

**Comment by shouze** [comment]
ok so @afhole plz close this one ;)
