### ISSUE TITLE
Error An unexpected error occurred: "Path must be a string. Received true".

### ISSUE THREAD

**Issue by tolaseadegbite** [yarnpkg/yarn#8428]
I can't get yarn to install on Windows 10. I get the following error:

`yarn add v1.22.5
error An unexpected error occurred: "Path must be a string. Received true".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/Users/hp/learnenough_tutorials/repos/rails_tutorial/environment/hello_app/yarn-error.log".`

How do I get rid of this please?

**Comment by plainnany** [comment]
me too

**Comment by plainnany** [comment]
I try to remove `~/.yarnrc`，and reinstall, it works!

**Comment by merceyz** [comment]
Duplicate of https://github.com/yarnpkg/yarn/issues/8331
