### ISSUE TITLE
yarn installation error code: 100

### ISSUE THREAD

**Issue by zubi9** [yarnpkg/yarn#8429]
### Bug description
Run sudo apt update && sudo apt install yarn
  sudo apt update && sudo apt install yarn
  shell: /bin/bash -e {0}

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Type 'gpg' is not known on line 1 in source list /etc/apt/sources.list.d/yarn.list
E: The list of sources could not be read.
Error: Process completed with exit code 100.

**Command**

>>sudo apt update && sudo apt install yarn
the command above does not work.

**What is the current behavior?**
E: Type 'gpg' is not known on line 1 in source list /etc/apt/sources.list.d/yarn.list
E: The list of sources could not be read.
Error: Process completed with exit code 100.

**Environment**

- Node Version: Latest
- Yarn v1 Version: Latest 
- OS and version: Ubuntu-latest

**Comment by merceyz** [comment]
This is documented here https://classic.yarnpkg.com/en/docs/install#debian-stable
