### ISSUE TITLE
Yarn error 127 not solved by other issue threads

### ISSUE THREAD

**Issue by tomshort-si** [yarnpkg/yarn#8431]
#### Command

`yarn`

#### What is the current behavior?

When I run `yarn` from inside the project folder I get a 127 error when building fresh packages. However, I can run this from parent directory without issue. When I try to build I get an error relating to memory but I broke the problem down and started with this one first.

#### Environment

Yarn 1.22.5
Node.js 14.15.0
Ubuntu 20.04.1 LTS

#### Error Text
    error /root/parent_directory/project_folder/node_modules/postinstall-postinstall: Command failed.
    Exit code: 1
    Command: node ./run.js
    Arguments: 
    Directory: /root/parent_directory/project_folder/node_modules/postinstall-postinstall
    Output:
    /bin/sh: 1: patch-package: not found
    error Command failed with exit code 127.
    child_process.js:655
        throw err;
        ^

    Error: Command failed: yarn run postinstall
    /bin/sh: 1: patch-package: not found
    error Command failed with exit code 127.

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/root/parent_directory/project_folder/node_modules/postinstall-postinstall/run.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
    status: 127,
    signal: null,
    output: [
      null,
     Buffer(118) [Uint8Array] [
       121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
        50,  50,  46,  53,  10,  36,  32, 112,  97, 116,  99, 104,
        45, 112,  97,  99, 107,  97, 103, 101,  10, 105, 110, 102,
       111,  32,  86, 105, 115, 105, 116,  32, 104, 116, 116, 112,
       115,  58,  47,  47, 121,  97, 114, 110, 112, 107, 103,  46,
        99, 111, 109,  47, 101, 110,  47, 100, 111,  99, 115,  47,
        99, 108, 105,  47, 114, 117, 110,  32, 102, 111, 114,  32,
       100, 111,  99, 117, 109, 101, 110, 116,  97, 116, 105, 111,
       110,  32,  97,  98,
       ... 18 more items
     ],
     Buffer(78) [Uint8Array] [
        47,  98, 105, 110,  47, 115, 104,  58,  32,  49,  58,  32,
       112,  97, 116,  99, 104,  45, 112,  97,  99, 107,  97, 103,
       101,  58,  32, 110, 111, 116,  32, 102, 111, 117, 110, 100,
        10, 101, 114, 114, 111, 114,  32,  67, 111, 109, 109,  97,
       110, 100,  32, 102,  97, 105, 108, 101, 100,  32, 119, 105,
       116, 104,  32, 101, 120, 105, 116,  32,  99, 111, 100, 101,
        32,  49,  50,  55,  46,  10
     ]
    ],
    pid: 37384,
    stdout: Buffer(118) [Uint8Array] [
     121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
      50,  50,  46,  53,  10,  36,  32, 112,  97, 116,  99, 104,
      45, 112,  97,  99, 107,  97, 103, 101,  10, 105, 110, 102,
     111,  32,  86, 105, 115, 105, 116,  32, 104, 116, 116, 112,
     115,  58,  47,  47, 121,  97, 114, 110, 112, 107, 103,  46,
      99, 111, 109,  47, 101, 110,  47, 100, 111,  99, 115,  47,
      99, 108, 105,  47, 114, 117, 110,  32, 102, 111, 114,  32,
     100, 111,  99, 117, 109, 101, 110, 116,  97, 116, 105, 111,
     110,  32,  97,  98,
     ... 18 more items
    ],
    stderr: Buffer(78) [Uint8Array] [
    47,  98, 105, 110,  47, 115, 104,  58,  32,  49,  58,  32,
    112,  97, 116,  99, 104,  45, 112,  97,  99, 107,  97, 103,
    101,  58,  32, 110, 111, 116,  32, 102, 111, 117, 110, 100,
    10, 101, 114, 114, 111, 114,  32,  67, 111, 109, 109,  97,
    110, 100,  32, 102,  97, 105, 108, 101, 100,  32, 119, 105,
    116, 104,  32, 101, 120, 105, 116,  32,  99, 111, 100, 101,

**Comment by merceyz** [comment]
I'd guess you lack `patch-package` as a dependency but without a reproduction it's hard to tell
