### ISSUE TITLE
[BUG] Yarn tries to download transitive bundledDependencies

### ISSUE THREAD

**Issue by mpetuska** [yarnpkg/yarn#8436]
### Current Behavior:
When installing published package that has some bundled dependencies, yarn tries to look them up on the repository and fails as a result (since they're not there). It works fine when installing from a tarball.

### Expected Behavior:
Yarn should skip downloading bundled dependencies and move on to resolving package.json of each bundledDependency in package's node_modules.

### Steps To Reproduce:
Try installing [this](https://gitlab.com/lt.petuska/npm-publish/-/packages/636632) package:
1. `echo \"@lt.petuska:registry\" \"https://gitlab.com/api/v4/packages/npm/\" >> .yarnrc`
2. `yarn add @lt.petuska/js@1.0.0`
4. See error...
```
yarn add v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
Couldn't find any versions for "kotlinx-atomicfu" that matches "0.14.4"
? Please choose a version of "kotlinx-atomicfu" from this list: (Use arrow keys)
❯ 0.14.1 
  0.14.1-js-ir-02 
  0.14.0 
  0.13.2 
  0.13.2-native-mt-4 
  0.13.2-native-mt-3 
  0.13.2-native-mt-2 
  0.13.2-native-mt 
  0.13.1 
  0.13.0 
  0.12.11 
  0.12.11-gradle561 
  0.12.11-gradle-561 
  0.12.11-gradle-5.6.1 
  0.12.11-gradle 
error Couldn't find package "ktor-ktor-client-core-jsLegacy@1.4.1" required by "@lt.petuska/mpp-Legacy@^1.0.2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Environment:
- OS: Pop!_OS@20.04_LTS
- Node: v14.15.0
- Yarn: 1.22.10

**Comment by paul-soporan** [comment]
Closing as we've completely removed support for `bundleDependencies` in v2, for the reasons stated here https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies. We aren't going to spend more time fixing them in v1.
