### ISSUE TITLE
Slow installs in monorepos

### ISSUE THREAD

**Issue by vijaybritto** [yarnpkg/yarn#8437]
We have a mono repo setup which is used to manage the entire frontend code base and we use yarn workspaces and Lerna for the management.

Everytime I add a dependency it slows down significantly in this place. I'm not sure what it means. I would be happy to learn about it. 
![image](https://user-images.githubusercontent.com/3725668/98448385-a341d400-2151-11eb-97b6-ff1920721d78.png)

Is there anything I can do to speed up this process? Is it CPU bound or network bound?

**Comment by entrptaher** [comment]
Here is a monorepo which takes **1 minutes** on yarn version 1 and **7 minutes** on yarn version 2. I noticed the CPU was idle most of the time in  **Resolution step**. While the memory usage went up significantly to 1GB.

![image](https://user-images.githubusercontent.com/8284972/100314685-61ce7700-2fe1-11eb-9d9d-f1f19058219c.png)

**Comment by merceyz** [comment]
Without a reproduction there isn't anything we can do
