### ISSUE TITLE
optionalDependencies are not optional

### ISSUE THREAD

**Issue by 3LOK** [yarnpkg/yarn#844]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I've read you don't really support optionalDependencies (for the deterministic feature). We use this heavily with our CI so our CI can use internal tools for publishing packages, while allowing public usage of the published package.

Is there any plan on solving this issue, or will optionalDependencies never be really optional in Yarn?

Note: --ignore-optional doesn't work as well, as you can see here:
```
yarn add redux-saga-tester --ignore-optional
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a package.json file, add one of the following to it:
```json
  "optionalDependencies":{
     "unknown-package-9999":"*"
  }
```
or
```json
  "optionalDependencies":{
     "@wix/wnpm-ci":"*"
  }
```

**What is the expected behavior?**
As described [here](https://docs.npmjs.com/files/package.json#optionaldependencies):
```
If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object
```
Gracefully continue installing other packages, and succeed if the others succeed.

**Please mention your node.js, yarn and operating system version.**
Node v6.2.0
Yarn v0.15.1
OSX 10.11.2

**Comment by kittens** [comment]
Fixed via #789.
