### ISSUE TITLE
E: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages - server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

### ISSUE THREAD

**Issue by mileslane** [yarnpkg/yarn#8440]
**Describe the bug**

W: The repository 'https://dl.yarnpkg.com/debian stable Release' does not have a Release file.
E: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages - server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

**To Reproduce**

I am running `apt-get update` in a docker container. 
```Err:5 https://dl.yarnpkg.com/debian stable/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```
However, the certificates file is present:
```
-rw-r--r-- 1 root root 213054 Nov  8 10:25 /etc/ssl/certs/ca-certificates.crt
```
Also, I have run `apt-get install --reinstall ca-certificates`. That didn't help.
I have tried updating the certificate: `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`
But, this generated a complaint:
```
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
gpg: no valid OpenPGP data found.
```

**Environment if relevant (please complete the following information):**

 - OS: MacOS
 - Docker: 2.5.0
 - VM OS: NAME="Ubuntu", VERSION="16.04.7 LTS (Xenial Xerus)"
 - Node version: 12.18.0
 - Yarn version: 1.22.4

**Comment by Arax20** [comment]
I have a similar issue when running apt update:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
OS: Ubuntu 20.04.2

**Comment by merceyz** [comment]
See https://github.com/yarnpkg/yarn/issues/7866
