### ISSUE TITLE
ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by cwxyz007** [yarnpkg/yarn#8441]
### Bug description

**Command**

```sh
yarn add ohm-js
```

**What is the current behavior?**

Get an error.
```sh
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "ELOOP: too many symbolic links encountered, stat '/Users/xxx/Library/Caches/Yarn/v6/npm-ohm-js-15.2.1-7dc3b9abba22e25a5fe7a75d37996f4da01584e4-integrity/node_modules/ohm-js/README.md'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/xxx/Documents/MineCodes/Bsion/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

Add `ohm-js` without error.

**Steps to Reproduce**

1. open a folder
1. run `yarn init --yes`

2. run `yarn add ohm-js`

**Environment**

- Node Version: `v10.22.1`
- Yarn v1 Version: `1.22.10` 
- OS and version: macos catalina 10.15.7

[yarn-error.log](https://github.com/yarnpkg/yarn/files/5508900/yarn-error.log)

**Comment by pdubroy** [comment]
FYI @cwxyz007, I've just fixed the issue in ohm-js: https://github.com/harc/ohm/issues/268. You should be able to install it without problems now.

Some context — version 15.2.1 of the `ohm-js` package had a symlink named `README.md` which pointed to `../README.md`. 

npm is able to install this without problems:

```
/tmp/issue-268$ npm install --save ohm-js@15.2.1

> ohm-js@15.2.1 postinstall /private/tmp/issue-268/node_modules/ohm-js
> node bin/dev-setup.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN issue-268@1.0.0 No description
npm WARN issue-268@1.0.0 No repository field.

+ ohm-js@15.2.1
added 3 packages from 29 contributors and audited 3 packages in 1.631s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
