### ISSUE TITLE
yarn add takes too much time ( + than 30 minutes )

### ISSUE THREAD

**Issue by amSaighi** [yarnpkg/yarn#8450]
**Environment**

- Node Version: `12.18.2`
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows 10 v 2004

yarn add any package takes too much time, he take time to compiling etc ...

![12](https://user-images.githubusercontent.com/3142753/98823502-7718a280-2432-11eb-8745-0487fb27e3c7.png)

![13](https://user-images.githubusercontent.com/3142753/98823519-7da71a00-2432-11eb-862d-9905da3b76c9.png)

I forked the project in my SDD and I get this result : 

![21](https://user-images.githubusercontent.com/3142753/98823569-91528080-2432-11eb-8f92-fdf7ecd08017.png)

![22](https://user-images.githubusercontent.com/3142753/98823582-94e60780-2432-11eb-93a3-0e0a78415fa9.png)

any help !!
Should I switch to NPM ?

**Comment by merceyz** [comment]
Based on the little information provided I'd guess you have a postinstall somewhere in your dependency tree that builds everything which is not something Yarn nor npm can do anything to speed up
