### ISSUE TITLE
yarn add local repository does not work

### ISSUE THREAD

**Issue by yarostbaklajana** [yarnpkg/yarn#8451]
Steps to reproduce: 
> in repository forder run
`yarn add file:../relative/path/to/local/repository`
(OR yarn add file:./..relative/path/to/local/repository)
received error
no repository found in https://github.com/relative/path/to/local/repository or no repository found in C:\\Programm Files\\Users\\user\..relativepathtolocalrepository

Why does it look through the repository origin?

**Comment by Kavin-Kannan** [comment]
I get something similar when I do this,

`yarn add --save file:/Absolute/path/mainfolder/packages`

**Error msg:**

> yarn add v1.22.5
> error Missing list of packages to add to your project.
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by yarostbaklajana** [comment]
I just did this: 
yarn add ../relative/path/folder

Dear Support please update the documentation which says to prepend `file:` statement before the path
