### ISSUE TITLE
yarn v2 cannot install gitmodule dependency. Error YN0001 Error ENOENT: no such file or directory

### ISSUE THREAD

**Issue by dutu** [yarnpkg/yarn#8452]
### Bug description

`yarn install` fails when the gitmodule below is included in `package.json`.

```js
"uWebSockets.js": "uNetworking/uWebSockets.js#v18.10.0"
 ```
**Only this particular package fails. Other packages install without issue.** 

**Also, the issue is not encountered when using yarn v1 or npm.**

**Command**

```sh
yarn install
```

**What is the current behavior?**

`yarn install` fails with the error message
```sh
➤ YN0000: ┌ Resolution step
➤ YN0013: │ uWebSockets.js@https://github.com/uNetworking/uWebSockets.js.git#commit=6fcd55b12dbc5a6115e17d6f5d2f43c6febfba75 can't be found in the cache and will be fetched from GitHub
➤ YN0013: │ uWebSockets.js@https://github.com/uNetworking/uWebSockets.js.git#commit=6fcd55b12dbc5a6115e17d6f5d2f43c6febfba75 can't be found in the cache and will be fetched from the remote repository
➤ YN0001: │ Error: uWebSockets.js@https://github.com/uNetworking/uWebSockets.js.git#commit=6fcd55b12dbc5a6115e17d6f5d2f43c6febfba75: ENOENT: no such file or directory, open 'C:\Users\dutu\AppData\Local\Temp\xfs-fd420523\package.tgz'
➤ YN0000: └ Completed in 40s 418ms
➤ YN0000: Failed with errors in 40s 422ms
```

**What is the expected behavior?**

`yarn install` should execute with no error

**Steps to Reproduce**

1.  include `"uWebSockets.js": "uNetworking/uWebSockets.js#v18.10.0"` as dependency in `package.json`
2. run `yarn install`

**Environment**

- Node Version: `15.2.0`
- Yarn v1 Version: `1.22.5` 
- OS and version: Windows 10

**Comment by merceyz** [comment]
Just tested with the latest version from master and it works as expected, try with `yarn set version from sources`

**Comment by dutu** [comment]
I get no errors now, thank you
