### ISSUE TITLE
anyone can help me

### ISSUE THREAD

**Issue by loveermoter** [yarnpkg/yarn#8455]
C:\Users\Dell\Desktop\SharpBot-master>yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/abyssvi/google-
translate-api/tar.gz/736263e11a5512e28d783672e57f477dcac5dfc2: Request failed \"
404 Not Found\"".
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\Users\\Dell\\Desktop\\SharpBot-master\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

**Comment by loveermoter** [comment]
i am rookie sry 
(yarn install --force)
(yarn install)
What do I use

**Comment by loveermoter** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Dell>cd desktop

C:\Users\Dell\Desktop>cd sharpbot
The system cannot find the path specified.

C:\Users\Dell\Desktop>cd SharpBot-master

C:\Users\Dell\Desktop\SharpBot-master>yarn
yarn install v1.23.0-20200615.1913
warning ..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/abyssvi/go
translate-api/tar.gz/736263e11a5512e28d783672e57f477dcac5dfc2: Request fail
404 Not Found\"".
info If you think this is a bug, please open a bug report with the informat
rovided in "C:\\Users\\Dell\\Desktop\\SharpBot-master\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about
command.


-------------------------------------------------------------------------------------------------
(dude the same problem - i download (yarn-master and berry-master) and i used the "yarn install" like you say

**Comment by merceyz** [comment]
The URL doesn't exist (404) so it makes sense for it to throw and without a reproduction there is nothing we can do
