### ISSUE TITLE
Error Code 1603

### ISSUE THREAD

**Issue by bnthomason** [yarnpkg/yarn#8457]
Sorry first time posting a bug report. Let me know if I formatted wrong

### Bug description

When running install or uninstall for chocolatey, I will get the following error message:

WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\ProgramData\chocolatey\lib\python3\tools\python-3.8.6-amd64.exe" /quiet InstallAllUsers=1 PrependPath=1 TargetDir="C:\Python38" ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

**Command**
choco uninstall python3 -y --force

**What is the current behavior?**
yarn is not the command, it's choco.

It will throw a generic error code 1603. That's all I know.

**What is the expected behavior?**
Installing chocolately properly and succesfully.

**Steps to Reproduce**
attempt to  downgrade Chocolately python 3.9.0 to 3.8.6.

1. choco uninstall python3 -y
2. choco install python3 -y --version 3.8.6

**Environment**

- No node, this is choco
- I don't know what yarn is
- Windows 10 Pro 1909.https://guides.github.com/features/mastering-markdown/
[chocolatey.log](https://github.com/yarnpkg/yarn/files/5551638/chocolatey.log)

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
