### ISSUE TITLE
Error: Cannot find module '/home/[username]/.yarn/releases/yarn-berry.cjs'

### ISSUE THREAD

**Issue by tafadzwagonera** [yarnpkg/yarn#8460]
**Platform**
Ubuntu 20.04.01
Node v14.13.0
NPM 6.14.8

**Command(s)**
`yarn`, `yarn --version` or any `yarn`-related terminal command

**What is the current behavior?**
After installing yarn via the official installation tutorial on Ubuntu this error occurs:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/tafadzwa/.yarn/releases/yarn-berry.cjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:747:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Running `which yarn` yields `/usr/bin/yarn`

**What is the expected behavior?**
`yarn` or `yarn --version` should output a version string

**Steps to reproduce**
Install yarn on the platform under **Platform** heading and type `yarn --version`

**Any other information**
Similar to https://github.com/yarnpkg/yarn/issues/7948

**Comment by tafadzwagonera** [comment]
Running `rm ~/.yarnrc` and `rm ~/.yarnrc.yml` and worked for me. Don't worry if either file isn't there. `~/.yarnrc` was not found so I ended up deleting `~/.yarnrc.yml` only. I then logged out and in to the terminal and ran `yarn --version`

**Why does this solution work**
When I ran `npm install -g yarn` or `npm install -g yarn@berry` `yarnrc` and/or `yarnrc.yml` were/was created with the `yarnPath` pointing to `/home/[username]/.yarn/releases/yarn-berry.cjs`. Running `yarn --version` would ran a lookup for `yarn-berry.cjs` on the `yarnPath` and since `yarn-berry.cjs` wasn't there runtime would trigger an appropriate error. It makes sense that removing `yarnrc` and/or `yarnrc.yml` solves the issue.

**Comment by JetForMe** [comment]
While updating Mastodon I ran into this. On Linux I had to:

* Remove the system-installed node: `sudo apt remove nodejs`
* Install `fnm`: curl -fsSL https://fnm.vercel.app/install | bash
* Install node: `fnm install`
* Install yarn via corepack: `corepack enable && corepack prepare`

I had done a few other things leading up to this point, like disabling yarn via corepack, and removing `~/.yarnrc`, so I’m not sure if some other step I tried is also required.
