### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Asset manifest file "C:\Users\etoil\eventbrote/public/build/manifest.json" does not exist.").

### ISSUE THREAD

**Issue by Takfarinas-codeur** [yarnpkg/yarn#8464]
bonjour , 
lors de l'instalation de yarn j'ai eu un probléme  dans le navigateur An exception has been thrown during the rendering of a template ("Asset manifest file "C:\Users\etoil\eventbrote/public/build/manifest.json" does not exist.").

yarn -- version 0.19.1

j'ai vu qu'il faut mettre a jour les moteurs pour couvrir les versions modernes de node, ou bien ignorer les moteurs (engines) ,que ce qui faut faire ;supprimer le fichier node_modules ou enlever une ligue x sur composer.json , ce probléme de configuration de yarn me débasse j'ai essayer même avec npm ca marche pas

j'attends avec pascience votre aide 
merci

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
