### ISSUE TITLE
What does "error Command failed with exit code 2"mean?

### ISSUE THREAD

**Issue by 1ovi** [yarnpkg/yarn#8467]
run command: `yarn build`
There are no error logs, but some warning, and the following log at the end:

> error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The documentation URL is not available.

**Comment by merceyz** [comment]
Closing as there is nothing actionable here, we don't control what your `build` script does

**Comment by StenPetrov** [comment]
@merceyz it's not "nothing actionable" - I get a build with "exit code 2" being the only output.
hiding command errors from developers is clearly a bad idea and needs to be fixed

**Comment by owenizedd** [comment]
got this on my `yarn lint`, turns out the HTML tag was wrong

**Comment by Obed47** [comment]
i have the same problem and cannot start my project. the above mentioned solutions do not work for me.

**Comment by aghreed** [comment]
If it helps anyone also finding themselves looking at this closed issue, you can get more information by passing the `--verbose` flag with your command — e.g., `yarn build --verbose`. Hopefully that'll help you find clues as to why the command is failing.

**Comment by srtager555** [comment]
I have a script to start my emulators from firebase, whenever I start the emulators:start the terminal gives me this error, I skip the error by using sudo before the script
