### ISSUE TITLE
flatpicker not found

### ISSUE THREAD

**Issue by dvodvo** [yarnpkg/yarn#8468]
**Command**
Upon
```yarn add flatpicker```
Processing
```
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
```
### Bug description

```
error An unexpected error occurred: "https://registry.yarnpkg.com/flatpicker: Not found".
```

**What is the current behavior?**
flatpicker not installed

**What is the expected behavior?**
flatpicker intalling

*yarn-error.log [attached*
[yarn-error.log](https://github.com/yarnpkg/yarn/files/5571763/yarn-error.log)

**Comment by bershanskiy** [comment]
You probably meant to install [flatpickr](https://yarnpkg.com/package/flatpickr), not flatpick***e***r (note the extra e).

That's what's needed for `geodata` according to the log you provided.

**Comment by dvodvo** [comment]
[facepalm]!
