### ISSUE TITLE
Extraneous dependencies installed

### ISSUE THREAD

**Issue by danharper** [yarnpkg/yarn#847]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Yarn's installing a duplicate dependency, where npm doesn't.

**If the current behavior is a bug, please provide the steps to reproduce.**

Sample repo: https://github.com/danharper/yarn-dupe-bug-reproduction.

```
"dependencies": {
  "backbone": "1.0.0",
  "backbone-validation": "git://github.com/thedersen/backbone.validation.git#v0.9.1"
}
```

```
$ npm i
$ npm ls

├─┬ backbone@1.0.0
│ └── underscore@1.8.3
└── backbone-validation@0.9.1 (git://github.com/thedersen/backbone.validation.git#08d01da529549faa5fdadf5be4f46a823d8dc9a1)

$ rm -rf node_modules
$ yarn
$ npm ls

├── backbone@1.0.0
└─┬ backbone-validation@0.9.1 invalid
  ├── backbone@1.3.3 extraneous
  └── underscore@1.8.3
```

I'll try and look into the problem myself tonight. Or is this related to 579?

**What is the expected behavior?**

To behave like npm.

**Please mention your node.js, yarn and operating system version.**

Node 6. Yarn 0.15.1 (& `master`). OSX ElCap.

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? I'm not able to recreate the issue using the latest  Yarn `v0.17.10`. `backbone@1.0.0` satisfies both `backbone@1.0.0, backbone@>=1.0.0`.

```
backbone@1.0.0, backbone@>=1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/backbone/-/backbone-1.0.0.tgz#5e146e1efa8a5361462e578377c39ed0f16b0b4c"
  dependencies:
    underscore ">=1.4.3"
```

**Comment by danharper** [comment]
Yep, this seems to be fixed now 👍
