### ISSUE TITLE
yarn run adds random folders to PATH

### ISSUE THREAD

**Issue by exFalso** [yarnpkg/yarn#8475]
### Bug description

**Command**

```sh
yarn run something
```

**What is the current behavior?**

`something` is executed with an environment that has random folders prepended to PATH. The prepending happens here: https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/util/execute-lifecycle-script.js#L175-L237

The worst offender being https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/util/execute-lifecycle-script.js#L188

This can potentially cause wrong programs to be executed if there are multiple versions installed, with no way to configure this behaviour.

**What is the expected behavior?**

Run commands with unmodified environment, or make overriding behaviour configurable

**Steps to Reproduce**

```bash
mkdir -p /tmp/a
cat > /tmp/a/package.json <<EOF
{
  "scripts": {
    "something": "echo \$PATH"
  }
}
EOF
echo "$PATH"
(cd /tmp/a && yarn run something) # != PATH
```

**Environment**

- Node Version: v12.15.0
- Yarn v1 Version: 1.22 
- OS and version: arch linux kernel 5.9.10-arch1-1

**Comment by merceyz** [comment]
This is how Yarn grants access to the binaries from your dependencies to your scripts and can't be turned off as it would break everything trying to use them

**Comment by exFalso** [comment]
Adding paths specific to yarn-scoped binaries is fine, what's not fine is adding a global path that can override the environment. As stated in the issue, the biggest problem is with `globalBin`, which does not have anything to do with yarn-declared dependencies.

**Comment by merceyz** [comment]
That's for your global yarn dependencies no? Either way that has been fixed in v2 and no longer happens
