### ISSUE TITLE
Yarn doesn't install dependencies properly

### ISSUE THREAD

**Issue by DigitalCyan** [yarnpkg/yarn#8484]
### Bug description
Yarn doesn't download dependencies nor create a `node_modules` folder after doing `yarn install`. The botched workaround I've came up with is to remove the `yarn.lock`. Then everything works just fine.

**Command**

```sh
yarn install
```

**What is the current behavior?**
The program ends with no error code, this is the output:
```
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.08s.
```

**What is the expected behavior?**
Yarn installs the dependencies

**Steps to Reproduce**
Repo used in reproduction of the problem: https://github.com/DigitalCyan/helium

1. Clone the repo
2. Open the repo in a terminal
3. Try to install dependencies via yarn
```
yarn install
```

**Environment**

- Node Version: `14.15.1`
- Yarn v1 Version: `1.22.10` 
- OS and version: Arch

**Comment by paul-soporan** [comment]
Closing as fixed in v2.

https://yarnpkg.com/getting-started/migration
