### ISSUE TITLE
cannot fetch any package in wsl2

### ISSUE THREAD

**Issue by ZhangJoker** [yarnpkg/yarn#8485]
### Bug description
i use common to add eslint into my project
yarn add eslint

**What is the current behavior?**
it always in fetching package step and not continue. timeout at last.
but i can ping registry.yarnpkg.com successfully

**What is the expected behavior?**
should install package successfully

**Environment**

- Node Version: 10.19.0
- Yarn v1 Version: 1.22.4
- OS and version: wsl2 ubuntu 20.04

**Comment by paul-soporan** [comment]
Closing as there is nothing actionable here without a reproduction. You most likely have a network issue.
