### ISSUE TITLE
For some reason yarn wants access to my root directory

### ISSUE THREAD

**Issue by SolarAquarion** [yarnpkg/yarn#8489]
```sh
yarn node
```

**What is the current behavior?**
  Error: EACCES: permission denied, scandir '/root/.local/share/yarn/link'

**What is the expected behavior?**
Doing nothing

**Environment**

- Node Version: `v12.20.0`
- Yarn v1 Version: `1.22.10` 
- OS and version: 
Archlinux

**Comment by RDIL** [comment]
This is for caching/config storage.
