### ISSUE TITLE
error Command "develop" not found.

### ISSUE THREAD

**Issue by Fawks0** [yarnpkg/yarn#8494]
Hey!
Can anyone help me with this?
C:\Users\ok\Desktop\aquire.ga>yarn run develop
yarn run v1.22.5
error Command "develop" not found.

**Comment by merceyz** [comment]
The project in the folder you're running that command in doesn't specify a `develop` script so there is nothing for Yarn to run

https://classic.yarnpkg.com/en/docs/cli/run
