### ISSUE TITLE
Error when installing YARN on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by tthai4** [yarnpkg/yarn#8496]
### Bug description
Below is the content of the yarn.list file after executing the following command:
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

I noticed that there is some SYNTAX error in this yarn.list file and I am not sure what went wrong.  Can you please help.  Thank you very much.
TT

----------------------------------

rc-aspire:~$ curl https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14115  100 14115    0     0  26482      0 --:--:-- --:--:-- --:--:-- 26432
**Warning: apt-key output should not be parsed (stdout is not a terminal)**
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /tmp/apt-key-gpghome.OyHbBtq7ml
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Syntax: gpg [options] [files]
Sign, check, encrypt or decrypt
Default operation depends on the input data**

Commands:

 -s, --sign                  make a signature
     --clear-sign            make a clear text signature
 -b, --detach-sign           make a detached signature
 -e, --encrypt               encrypt data
 -c, --symmetric             encryption only with symmetric cipher
 -d, --decrypt               decrypt data (default)
     --verify                verify a signature
 -k, --list-keys             list keys
     --list-signatures       list keys and signatures
     --check-signatures      list and check key signatures
     --fingerprint           list keys and fingerprints
 -K, --list-secret-keys      list secret keys
     --generate-key          generate a new key pair
     --quick-generate-key    quickly generate a new key pair
     --quick-add-uid         quickly add a new user-id
     --quick-revoke-uid      quickly revoke a user-id
     --quick-set-expire      quickly set a new expiration date
     --full-generate-key     full featured key pair generation
     --generate-revocation   generate a revocation certificate
     --delete-keys           remove keys from the public keyring
     --delete-secret-keys    remove keys from the secret keyring
     --quick-sign-key        quickly sign a key
     --quick-lsign-key       quickly sign a key locally
     --sign-key              sign a key
     --lsign-key             sign a key locally
     --edit-key              sign or edit a key
     --change-passphrase     change a passphrase
     --export                export keys
     --send-keys             export keys to a keyserver
     --receive-keys          import keys from a keyserver
     --search-keys           search for keys on a keyserver
     --refresh-keys          update all keys from a keyserver
     --import                import/merge keys
     --card-status           print the card status
     --edit-card             change data on a card
     --change-pin            change a card's PIN
     --update-trustdb        update the trust database
     --print-md              print message digests
     --server                run in server mode
     --tofu-policy VALUE     set the TOFU policy for a key

Options:

 -a, --armor                 create ascii armored output
 -r, --recipient USER-ID     encrypt for USER-ID
 -u, --local-user USER-ID    use USER-ID to sign or decrypt
 -z N                        set compress level to N (0 disables)
     --textmode              use canonical text mode
 -o, --output FILE           write output to FILE
 -v, --verbose               verbose
 -n, --dry-run               do not make any changes
 -i, --interactive           prompt before overwriting
     --openpgp               use strict OpenPGP behavior

(See the man page for a complete listing of all commands and options)

Examples:

 -se -r Bob [file]          sign and encrypt for user Bob
 --clear-sign [file]        make a clear text signature
 --detach-sign [file]       make a detached signature
 --list-keys [names]        show keys
 --fingerprint [names]      show fingerprints

Please report bugs to <https://bugs.gnupg.org>.
OK

**Command**

```sh
yarn [your command]
```

**What is the current behavior?**

**What is the expected behavior?**

**Steps to Reproduce**

1. 
2.

**Environment**

- Node Version: `x.x.x`
- Yarn v1 Version: `1.x.x` 
- OS and version:

**Comment by sj26** [comment]
You're missing a newline:

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
```

**Comment by B3ns44d** [comment]
## Installing Yarn on Ubuntu

Follow the steps below to install Yarn on your Ubuntu 18.04 system:

1.  The first step is to enable the Yarn repository. Start by importing the repository’s GPG key using the following  [`curl`  command](https://linuxize.com/post/curl-command-examples/)  :
    
    ```
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    ```
    
    Add the Yarn APT repository to your system’s software repository list by typing:
    
    ```
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    ```
    
2.  Once the repository is added to the system, update the package list, and install Yarn, with:
    
    ```
    sudo apt update
    ```
    
    If you already don’t have  [Node.js installed on your system](https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/)  , the command above will install it. Those who are using nvm can skip the Node.js installation with:
    
    ```
    sudo apt install --no-install-recommends yarn
    ```
    
3.  To verify that Yarn installed successfully, run the following commands which will print the Yarn version number:
    
    ```
    yarn --version
    ```
    
    At the time of writing this article, the latest version of Yarn is version  `1.17.3`.
    
    ```output
    1.17.3
    ```

**Comment by B3ns44d** [comment]
## Installing Yarn on Ubuntu

Follow the steps below to install Yarn on your Ubuntu 18.04 system:

1.  The first step is to enable the Yarn repository. Start by importing the repository’s GPG key using the following  `curl`  command  :
    
    ```
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    ```
    
    Add the Yarn APT repository to your system’s software repository list by typing:
    
    ```
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    ```
    
2.  Once the repository is added to the system, update the package list, and install Yarn, with:
    
    ```
    sudo apt update
    ```
    
    If you already don’t have  Node.js installed on your system , the command above will install it. Those who are using nvm can skip the Node.js installation with:
    
    ```
    sudo apt install --no-install-recommends yarn
    ```
    
3.  To verify that Yarn installed successfully, run the following commands which will print the Yarn version number:
    
    ```
    yarn --version
    ```
    
    At the time of writing this article, the latest version of Yarn is version  `1.17.3`.
    
    ```output
    1.17.3
    ```
