### ISSUE TITLE
mongoose not working / phantom-js not working

### ISSUE THREAD

**Issue by MrCheater** [yarnpkg/yarn#850]

**Comment by nodkz** [comment]
Mongoose works perfectly
In our internal app, also in OSS lib https://github.com/nodkz/graphql-compose-mongoose

PS maybe it does not work with node@<6

**Comment by busches** [comment]
@kittens no updates in six weeks.

**Comment by wyze** [comment]
If this is still an issue, please open a new issue, reference this issue, and follow the issue template.
