### ISSUE TITLE
[Question] Where does the data of 'yarn audit' come from?

### ISSUE THREAD

**Issue by MartinThoma** [yarnpkg/yarn#8502]
Does yarn use the [National Vulnerability Database (NVD)](https://nvd.nist.gov/)) or [CVE](http://cve.mitre.org/cve/index.html)? Does yarn audit use other data as well?

How does it work - does it download the DB with each run, meaning one needs an internet connection? Or is the relevant part shipped with yarn, meaning one needs to update yarn regularly? Or is a web service used, meaning one could leak information?

**Comment by merceyz** [comment]
It gets it from npm, the same way `npm audit` does

https://www.npmjs.com/advisories
https://docs.npmjs.com/cli/v6/commands/npm-audit
