### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by Simonakob** [yarnpkg/yarn#8504]
**Which operating system are you using:**
Windows 8.0

**Please describe the steps you took when trying to install Yarn and what went wrong:**

already installed node.js
yarn-1.22.5 or yarn-1.22.0 was dowloaded, then installed.
I see Yarn folder in the appropriate location.
But on checking Yarn using yarn --version in cmd, the message is; 'yarn' is not recognized as an internal or external command,
operable program or batch file.
node --version occurs v14.15.1

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
