### ISSUE TITLE
Installation Problem: Cannot find ~/.yarn

### ISSUE THREAD

**Issue by Raspberry1111** [yarnpkg/yarn#8508]
**Which operating system are you using:**
WSL 2 Ubuntu 20.04

**Please describe the steps you took when trying to install Yarn and what went wrong:**
I installed yarn through the steps described [here](https://classic.yarnpkg.com/en/docs/install#debian-stable)

>curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - 
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
>
>sudo apt update && sudo apt install --no-install-recommends yarn

Upon running `yarn --version`, it threw an error

![image](https://user-images.githubusercontent.com/66807330/102568516-a4034980-40b1-11eb-9d0c-6d9d8ddfc317.png)

**Comment by paul-soporan** [comment]
You have a `.yarnrc.yml` (or `.yarnrc` otherwise) file in your home directory that points to that release. Remove it and only install v2 per-project: https://yarnpkg.com/getting-started/install
