### ISSUE TITLE
Yarn v1 will be deprecated?

### ISSUE THREAD

**Issue by pedrofurtado** [yarnpkg/yarn#8511]
@arcanis Hey guys!

 Yarn v1 will be deprecated? If so, there is a EOL date?

I am a little bit confused 😄. I see the repo of yarn v2 actively maintained, much more than the repo of yarn v1. But both are releasing versions.

Is there backward-compatible upgrade guide to v2 from v1? Is v2 stable and ready for production, or is beta yet?

So many questions, I know hehehehe ....

Thanks a lot! 🤝

**Comment by pedrofurtado** [comment]
@willradi @marciojg

**Comment by arcanis** [comment]
The 1.x line has only received improvements this past year designed to make the migration easier. No features or bugfixes (security bugfixes excluded) will be released here.

> Is there backward-compatible upgrade guide to v2 from v1? Is v2 stable and ready for production, or is beta yet?

It's stable. Migration guide [here](https://yarnpkg.com/getting-started/migration).

**Comment by pedrofurtado** [comment]
@arcanis  Today, to install yarn berry, we need to install yarn 1.x and then "upgrade" (yarn set version). In future, the idea is allow install directly yarn berry? 🤝

**Comment by merceyz** [comment]
You can read more about this in https://github.com/yarnpkg/berry/issues/766#issuecomment-580658470

> In future, the idea is allow install directly yarn berry? handshake

The idea is to get Yarn shipped with node and having projects specify the package manger in `package.json`

https://github.com/nodejs/node/pull/35398
https://github.com/nodejs/corepack
