### ISSUE TITLE
--frozen-lockfile ignores resolutions

### ISSUE THREAD

**Issue by koterpillar** [yarnpkg/yarn#8513]
### Bug description

Adding a resolution and running `yarn --frozen-lockfile` does not fail even though the resolution is not the same as the currently locked version and `yarn` modifies the lockfile.

**Command**

With the following `package.json`:

```
{
  "name": "lockfile-not-frozen",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ini": "^1.3.0"
  },
  "resolutions": {
    "ini": "1.3.5"
  }
}
```

and `yarn.lock`:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


ini@^1.3.0:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/ini/-/ini-1.3.8.tgz#a29da425b48806f34767a4efce397269af28432c"
  integrity sha512-JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==
```

```sh
yarn --frozen-lockfile
```

**What is the current behavior?**

* Command succeeds.
* `yarn.lock` is not updated.

**What is the expected behavior?**

* Command fails because the specified version (1.3.5) is different to the locked one (1.3.8).

**Steps to Reproduce**

1. `yarn init`
2. `yarn add 'ini@^1.3.0'`
3. Add a resolution for `"ini": "1.3.5"`

**Environment**

- Node Version: `v15.4.0`
- Yarn v1 Version: `1.22.10` 
- OS and version: macOS 10.15.7

**Comment by merceyz** [comment]
Fixed in v2

https://yarnpkg.com/getting-started/migration
