### ISSUE TITLE
Couldn't publish package: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by leorigon** [yarnpkg/yarn#8515]
It's simple, when I try to publish a package update, the following error appears on my terminal:

```
error Couldn't publish package: "https://registry.npmjs.org/@leonardo.rigon/amazing-react-charts: ESOCKETTIMEDOUT"
```

My config at `package.json` is: 

```
  "name": "amazing-react-charts",
  "version": "0.3.5",
  "repository": {
    "type": "git",
     "url": "https://github.com/nginformatica/amazing-react-charts.git"
    },
  "publishConfig": {
    "registry": "https://registry.npmjs.org/@leonardo.rigon"
  }
```

I have been published this same package before (https://www.npmjs.com/package/amazing-react-charts), I don't know what's happening now. Yarn was updated to latest version.

The command that I running is: 
``` yarn publish --access public ```

**Comment by eguneys** [comment]
I had the same issue, problem is I had a too big of a file in the package.

**Comment by leorigon** [comment]
@eguneys try to logout and login again in the npm via terminal.

**Comment by eguneys** [comment]
I just add the big file in `.npmignore` problem solved.
