### ISSUE TITLE
Make yarn pack idempotent

### ISSUE THREAD

**Issue by grebenyuksv-preply** [yarnpkg/yarn#8519]
Dear maintainers, 

Do you mind explaining to me why `yarn pack` produces a different `.tgz` every time I call it? This creates a bit of an inconvenience for me in the following scenario:

- I have a JS monorepo
- I store my `shared.tgz` produced by `yarn pack` in Git
- I reference those `shared.tgz` directly in different `package.json` files across the monorepo
- There's a CI job checking whether `shared.tgz` is up-to-date with my code: it basically does `yarn pack` and compares the resulting `shared.tgz` with the one from Git

The inconvenience is, it's not enough to compare if `.tgz` files are identical ('cause they never are): I basically have to un-archive both and compare their actual contents.

I'm rather wondering why this decision was made than the technical reasons why this is happening. I wasn't able to find any way to reconfigure that behaviour.

Please, tell me if I can back up my question with any additional info.

**Comment by merceyz** [comment]
The output of `yarn pack` in v2 should be identical on every call, tried updating?
