### ISSUE TITLE
Yarn doesn't install local package dependencies

### ISSUE THREAD

**Issue by mrsaleh** [yarnpkg/yarn#8520]
Hi
When I install a local package using yarn, it does not install the package dependencies.
I think that everyone is aware of this issue. So you do this on purpose?

Thanks in advance

**Comment by daniel-seitz** [comment]
Hi, yes, this is on purpose. Find more in the [docs](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-production-true-false)

**Comment by merceyz** [comment]
It's unclear what you mean by "local package", please provide an example of what the issue is
