### ISSUE TITLE
Yarn couldn't handle caret and double hyphen in a package's version

### ISSUE THREAD

**Issue by kenrick95** [yarnpkg/yarn#8526]
### Bug description

The `latest` version of `@kenrick95/repo-tagged-caret` ([repo](https://github.com/kenrick95/repo-tagged-caret/), [npm](https://www.npmjs.com/package/@kenrick95/repo-tagged-caret)) is `1.0.0--echo.42` (note the double hyphen; the bug _does not occur_ if I only have one hyphen)

**Command**

```sh
yarn add @kenrick95/repo-tagged-caret
```

This will add `^1.0.0--echo.42` to the package.json's `dependencies` field and also successfully generates a lockfile

but on a subsequent `yarn install` command, it will fail to resolve `@kenrick95/repo-tagged-caret@^1.0.0--echo.42` (see below)

**What is the current behavior?**

![Screenshot 2020-12-28 at 10 51 59 AM](https://user-images.githubusercontent.com/3090380/103186255-c2abe080-48fa-11eb-8c83-cd8108eb1237.png)

```
➜  repo-use-tagged-caret git:(master) ✗ yarn add @kenrick95/repo-tagged-caret 
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @kenrick95/repo-tagged-caret@1.0.0--echo.42
info All dependencies
└─ @kenrick95/repo-tagged-caret@1.0.0--echo.42
✨  Done in 0.17s.


➜  repo-use-tagged-caret git:(master) yarn install
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "@kenrick95/repo-tagged-caret@^1.0.0--echo.42". Ignoring it.
Couldn't find any versions for "@kenrick95/repo-tagged-caret" that matches "^1.0.0--echo.42"
? Please choose a version of "@kenrick95/repo-tagged-caret" from this list: (Use arrow keys)
❯ 1.0.0-delta.42 
  1.0.0-beta.1 
  1.0.0--echo.42 
  1.0.0--charlie.1 

```

**What is the expected behavior?**

I expect the `yarn install` to successfully install `1.0.0--echo.42`

`npm install` (npm@6.14.8) is able to successfully install `1.0.0--echo.42`

**Steps to Reproduce**

Run this command in an empty repo:

```sh
yarn add @kenrick95/repo-tagged-caret
yarn install
```

----

Alternatively:

1. Clone https://github.com/kenrick95/repo-use-tagged-caret
2. Run `yarn install`

**Environment**

- Node Version: `12.16.2`
- Yarn v1 Version: `1.22.10` 
- OS and version: macOS 10.14.6

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
