### ISSUE TITLE
Getting "403 Forbidden" sometimes when trying to install packages

### ISSUE THREAD

**Issue by phil-davis** [yarnpkg/yarn#8527]
### Bug description
https://drone.owncloud.com/owncloud/web/12456/58/5
```sh
$ yarn install --frozen-lockfile && node build/run-for-all.js yarn install --frozen-lockfile
```

**What is the current behavior?**
```
error An unexpected error occurred: "https://registry.yarnpkg.com/stacktrace-js/-/stacktrace-js-2.0.2.tgz: Request failed \"403 Forbidden\"".
```

**What is the expected behavior?**
Ordinary open-source packages should be able to be fetched, not be forbidden.

**Steps to Reproduce**
See https://drone.owncloud.com/owncloud/web/12456/58/5 drone CI
I have been getting a few of these today, and also "502 Bad Gateway" sometimes.

**Environment**

- Node Version: `12`
- Yarn v1 Version: `1.22.5` 
- OS and version: Ubuntu 20.04

**Comment by phil-davis** [comment]
Is there currently some problem with `registry.yarnpkg.com` ?
I guess it should never respond with "403 Forbidden" for ordinary requests to fetch stuff.

Is there any status page?

http://status.yarnpkg.com/ does not seem to exist any more.

**Comment by phil-davis** [comment]
And I also get errors like https://drone.owncloud.com/owncloud/web/12459/28/5
`error https://registry.yarnpkg.com/is-number/-/is-number-3.0.0.tgz: Request failed "502 Bad Gateway"`

Is this somehow me, or `registry.yarnpkg.com` ?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/12477/29/6
```
error An unexpected error occurred: "https://registry.yarnpkg.com/tinycolor2/-/tinycolor2-1.4.1.tgz: Request failed \"502 Bad Gateway\"".
```

I keep getting these "random" errors when CI is doing `yarn install`

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/12515/50/6
```
error An unexpected error occurred: "https://registry.yarnpkg.com/estraverse/-/estraverse-4.3.0.tgz: Request failed \"502 Bad Gateway\"".
```

Another example today.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/12579/48/6
```
error An unexpected error occurred: "https://registry.yarnpkg.com/seed-random/-/seed-random-2.2.0.tgz: Request failed \"502 Bad Gateway\"".
```
Again today.

**Comment by merceyz** [comment]
`registry.yarnpkg.com` is just a CNAME to npm, you'll have to contact them about these sorts of issues

https://yarnpkg.com/getting-started/qa/#why-registryyarnpkgcom-does-facebook-track-us
