### ISSUE TITLE
Installation Problem: [title] CAN'T UPDATE / SET MOST CURRENT YARN VERSION EVEN THOUGH MOST CURRENT VERSION INSTALLED

### ISSUE THREAD

**Issue by ktochow1** [yarnpkg/yarn#8528]
**Which operating system are you using:**
I'm using Mac OS 11.0.1

**Please describe the steps you took when trying to install Yarn and what went wrong:**

I'm trying to run my rails api server and when I try to I get this error: 
 `Webpacker configuration file not found /Users/katrinatochowicz/Development/code/Projects/covid-api-2/covid2_api/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/katrinatochowicz/Development/code/Projects/covid-api-2/covid2_api/config/webpacker.yml (RuntimeError)`

When I try to run `rails webpacker:install` I get:
`katrinatochowicz@Katrinas-MacBook-Air covid2_api % rails webpacker:install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
Webpacker requires Yarn ">=1 <2" and you are using Yarn v0.1.1 2011 Jesper Kjeldgaard
Please upgrade Yarn https://yarnpkg.com/lang/en/docs/install/
Exiting!`

I try following the yarn documentation by installing it, reinstalling it, updating it, switching to the most current version (which gives me this error: `katrinatochowicz@Katrinas-MacBook-Air covid2_api % yarn set version 1.22.5
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
Traceback (most recent call last):
	8: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
	7: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
	6: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/bin/yarn:23:in `<main>'
	5: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/bin/yarn:23:in `load'
	4: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/gems/yarn-0.1.1/bin/yarn:26:in `<top (required)>'
	3: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/gems/yarn-0.1.1/bin/yarn:26:in `require'
	2: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/gems/yarn-0.1.1/lib/yarn/server.rb:4:in `<top (required)>'
	1: from /Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/gems/yarn-0.1.1/lib/yarn/server.rb:6:in `<module:Yarn>'
/Users/katrinatochowicz/.rvm/gems/ruby-2.6.1/gems/yarn-0.1.1/lib/yarn/server.rb:14:in `<class:Server>': uninitialized constant Socket::SOL_TCP (NameError)
Did you mean?  Socket::SO_TYPE`

Is there something I'm missing? I feel like I've been running around in circles and I'd really appreciate some help. Thanks.

**Comment by ktochow1** [comment]
SOLVED

**Comment by merceyz** [comment]
I'll close it then
