### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vincentpham13** [yarnpkg/yarn#8530]
### Bug description
![image](https://user-images.githubusercontent.com/63580042/103342431-10bc1200-4abc-11eb-9d42-b8b444febfb4.png)
Can not remove empty cache folder

**Comment by merceyz** [comment]
Since `rm -rf` is unable to delete it i'd guess it's some sort of issue with your filesystem, perhaps some files are in use. Nothing actionable from Yarns' point of view
