### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by percylim** [yarnpkg/yarn#8532]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by percylim** [comment]
cannot run yarn command e.g. yarn --version or yarn build etc after brew install -g yarn, a error of "Cannot find module '/Users/fannweilim/.yarn/releases/yarn-1.22.10.cjs" dispaly

**Comment by merceyz** [comment]
Duplicate of https://github.com/yarnpkg/yarn/issues/8532
