### ISSUE TITLE
yarn add segmentation fault

### ISSUE THREAD

**Issue by liza-mae** [yarnpkg/yarn#8536]
yarn add command is throwing a segmentation fault on RHEL aarch64 platform with node 14.x or 15.x. 

Current setup: 

```
Yarn: 1.22.10
Node: 14.15.4
OS:  Linux ip-10-0-0-100.us-west-2.compute.internal 4.18.0-221.el8.aarch64 #1 SMP Thu Jun 25 22:08:25 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

```
Steps: 
yarn add <<package>>
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[-------] 0/7Segmentation fault (core dumped)
```

Other info: 
If I use Ubuntu 20.04 of the same architecture aarch64, it works.  
If I switch the node version back to 12.20.1, it works.

**Comment by merceyz** [comment]
Provide a full reproduction please

**Comment by liza-mae** [comment]
Sure, I am a VM CentOS 8.3.2011 aarch64 on AWS. 

```
export PATH=$PATH:~/node/14.15.3/bin
mkdir yarntest
cd yarntest
yarn init
yarn add colors
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[-] 0/1Segmentation fault (core dumped)
```

**Comment by arcanis** [comment]
Yarn being exclusively JS, segfaults can't happen under normal circumstances. The problem comes from something in your setup.

**Comment by navono** [comment]
@arcanis I'm having the same problem on linux aarch64, is there any way to continue troubleshooting?

**Comment by navono** [comment]
check this [issue](https://github.com/termux/termux-packages/issues/5140).

**Comment by jbudz** [comment]
I was able to reproduce this on an empty repository.  Didn't get much from the core dump -
```
Core was generated by `node /usr/share/yarn/bin/yarn.js add express --save'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000d74690 in ?? ()
[Current thread is 1 (LWP 17428)]
(gdb) bt
#0  0x0000000000d74690 in ?? ()
#1  0x0000000000d089bc in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by liza-mae** [comment]
We would like to re-iterate it is specific to RedHat ARM.
