### ISSUE TITLE
Unexpected end of data

### ISSUE THREAD

**Issue by binex-dsk** [yarnpkg/yarn#8541]
When installing [session-desktop](https://github.com/loki-project/session-desktop), I get this error:
```
tmoment@the ~/random/session-desktop/src/session-desktop $ yarn install --frozen-lockfile           
yarn install v1.22.10
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
error An unexpected error occurred: "Unexpected end of data".
info If you think this is a bug, please open a bug report with the information provided in "/home/tmoment/random/session-desktop/src/session-desktop/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Attached my `yarn-error.log`. I searched through the issues both here and in session-desktop and neither have a single issue about this exact error, neither does the docs say anything.

**Comment by binex-dsk** [comment]
Yeah ok thanks for attaching
[yarn-error.log](https://github.com/yarnpkg/yarn/files/5785037/yarn-error.log)

**Comment by merceyz** [comment]
The registry seems to have closed the connection, nothing we can do about this one

**Comment by binex-dsk** [comment]
incredibl
