### ISSUE TITLE
[Bug] Hangs when offline mirror cannot be reached

### ISSUE THREAD

**Issue by rifftual** [yarnpkg/yarn#8545]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Yarn hangs when running any command if **yarn-offline-mirror** if defined in _.yarnrc_ and the mirror path cannot be reached. In our case it was a network drive that was not mapped on the host the commands were run at.

I think at least verbose log messages should indicate where the problem is.

**To Reproduce**

Set **yarn-offline-mirror** in .yarnrc that points to an unmapped network drive (In Windows)

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows 10 / Server 2019
 - Node version: 13.2.0
 - Yarn version: 1.22.10

**Additional context**

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
