### ISSUE TITLE
yarn install fails with workspaces if file system does not support symlinks

### ISSUE THREAD

**Issue by FreeSlave** [yarnpkg/yarn#8549]
Running yarn install on a project with workspace submodules leads to the error if the file system does not support symlinks. I could not find an option to do copying instead of symlinking.

`error An unexpected error occurred: "EPERM: operation not permitted, symlink '../submodule' -> '/media/sf_projects/nodetest/node_modules/submodule'"`

```json
{
  "private": true,
  "name": "nodetest",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "workspaces": {
    "packages": [
      "submodule"
    ],
    "nohoist": [
      "**",
      "**/**"
    ]
  }
}
```

**Comment by merceyz** [comment]
Yarn doesn't use copying for workspaces as every change you make would force you to run another install, if you want to avoid the symlinks you can use [Yarn PnP](https://yarnpkg.com/features/pnp)

https://yarnpkg.com/getting-started/migration
