### ISSUE TITLE
Yarn could not be found for Angular CLI Install

### ISSUE THREAD

**Issue by damuakula** [yarnpkg/yarn#8556]
I am using "NPM install" to install Angular CLI. A suggestion or error came out to use Yarn as stated below. Yarn is not recognized command. Let me know what the issue is?  I have downloaded the zip version of Angular Master CLI and extracted before attempting to install using NPM or Yarn

Error: Please use Yarn instead of NPM to install dependencies. See: https://yarnpkg.com/lang/en/docs/install/

**Comment by merceyz** [comment]
> Yarn is not recognized command. Let me know what the issue is?

Install yarn
