### ISSUE TITLE
Yarn Install Error

### ISSUE THREAD

**Issue by Sentrycs** [yarnpkg/yarn#8558]
OS=Windows 10
Node 10.16.0
Yarn 1.22.10
![Screenshot 2021-01-20 162527](https://user-images.githubusercontent.com/42841002/105311580-22c63780-5bc6-11eb-9a70-c9f0ae6265df.jpg)
![Screenshot 2021-01-20 162436](https://user-images.githubusercontent.com/42841002/105311715-2a85dc00-5bc6-11eb-9bc6-9ef65cd276fb.jpg)

**Comment by merceyz** [comment]
Closing as an external issue (they fail to build because of a `node-gyp` error)

**Comment by Sentrycs** [comment]
"they fail to build because of a node-gyp error"
What should I do about it?

**Comment by merceyz** [comment]
Your screenshots (don't send screenshots of errors btw, send text) show that `sha3` and `weak` fail to build so raise it with those projects
