### ISSUE TITLE
why i try to install type npx create-react-app myapp its give me error what i need to do??????

### ISSUE THREAD

**Issue by NANI1734** [yarnpkg/yarn#8561]
Creating a new React app in C:\Users\nadia\Desktop\react native\imdb.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/react: error:0909006C:PEM routines:get_name:no start line".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\nadia\\Desktop\\react native\\imdb\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts cra-template --cwd C:\Users\nadia\Desktop\react native\imdb has failed.

Deleting generated file... package.json
Done.

**Comment by merceyz** [comment]
Looks to be a certificate issue on your side, which we can't do much about
