### ISSUE TITLE
error  An unexpected error occurred: "Cannot create property

### ISSUE THREAD

**Issue by BubbleM** [yarnpkg/yarn#8564]
Arguments: 
  /Users/xxx/.nvm/versions/node/v12.20.0/bin/node /Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/bin/yarn.js start

PATH: 
  /var/folders/nb/qcwvhghn17lgs20bb_r80k300000gn/T/yarn--1611567995352-0.6440400600565102:/Users/xxx/youxinpai/admin/qiankun/node_modules/.bin:/Users/xxx/.config/yarn/link/node_modules/.bin:/Users/xxx/.nvm/versions/node/v12.20.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/xxx/.nvm/versions/node/v12.20.0/bin/node_modules/npm/bin/node-gyp-bin:/var/folders/nb/qcwvhghn17lgs20bb_r80k300000gn/T/yarn--1611567994419-0.29579570064243565:/Users/xxx/youxinpai/admin/qiankun/node_modules/.bin:/Users/xxx/.config/yarn/link/node_modules/.bin:/Users/xxx/.nvm/versions/node/v12.20.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/xxx/.nvm/versions/node/v12.20.0/bin/node_modules/npm/bin/node-gyp-bin:/Users/xxx/.nvm/versions/node/v12.20.0/bin:/Users/xxx/flutter/bin:/Users/xxx/.deno/bin:/usr/local/mongodb/bin:/usr/local/mysql/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/xxx/flutter/bin:/Users/xxx/.deno/bin:/usr/local/mongodb/bin:/usr/local/mysql/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin

Yarn version: 
  1.22.10

Node version: 
  12.20.0

Platform: 
  darwin x64

Trace: 
  TypeError: Cannot create property '-ires-168corp-com-repository-168npm-' on string '{"-ires-168corp-com-repository-168npm-":true}'
      at set (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:53902:28)
      at set (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:53916:14)
      at set (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:53896:16)
      at Function.objectPath.set (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:53949:14)
      at NpmRegistry.mergeEnv (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:95657:18)
      at NpmRegistry.<anonymous> (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:31899:12)
      at Generator.next (<anonymous>)
      at step (/Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:310:30)
      at /Users/xxx/.nvm/versions/node/v12.20.0/lib/node_modules/yarn/lib/cli.js:328:14
      at new Promise (<anonymous>)

npm manifest: 
  {
    "name": "react15",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "start": "webpack-dev-server",
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "dependencies": {
      "antd": "2.13.14",
      "react": "15.6.2",
      "react-dom": "15.6.2"
    },
    "devDependencies": {
      "@babel/core": "^7.7.2",
      "@babel/plugin-transform-react-jsx": "^7.7.0",
      "@babel/preset-env": "^7.7.1",
      "babel-loader": "^8.0.6",
      "css-loader": "^3.2.0",
      "html-webpack-plugin": "^3.2.0",
      "style-loader": "^1.0.0",
      "webpack": "^4.41.2",
      "webpack-cli": "^3.3.10",
      "webpack-dev-server": "^3.9.0"
    },
    "browserslist": [
      "last 2 Chrome versions"
    ]
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by merceyz** [comment]
Need to provide enough information to reproduce the issue, you haven't done that so not much we can do. Though if I were to guess you have a invalid config in `~/.yarnrc`

**Comment by ghoshabhi** [comment]
@merceyz Here in 2024, and i am still seeing this issue! This is what my yarnrc file looks like:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lastUpdateCheck 1725840388464
nmHoistingLimits workspaces
nodeLinker node-modules
```

Other deets:
- yarn version: `1.22.22`
- node version: `v18.18.0`

**Comment by ghoshabhi** [comment]
Make sure your `.npmrc` file is valid. I.e. no invalid entries in the file. The format is `key=value`. Example `registry=...`.
