### ISSUE TITLE
'Signatures were invalid' error

### ISSUE THREAD

**Issue by RVolmer** [yarnpkg/yarn#8569]
Starting today, I am getting the below error.  Has the key expired?  

Err:2 https://dl.yarnpkg.com/debian stable InRelease
--
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>

**Comment by billycastelli** [comment]
Getting a similar error. In the meantime, we added
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`
to our pipeline.

**Comment by merceyz** [comment]
See https://github.com/yarnpkg/yarn/issues/7866
