### ISSUE TITLE
`yarn install` is very slow (20+ minutes)

### ISSUE THREAD

**Issue by emilyjablonski** [yarnpkg/yarn#8571]
I just cloned a small new project and `yarn` and `yarn install` are running very, very slow, and only for me and not for others on the project. 

I've looked at a number of other issues around performance, and have yet to find a fix.

macOS Big Sur 11.2, M1 chip
yarn: 1.23.0
node: 12.18.4
npm: 6.14.6

I've attached the output of running `yarn install --verbose` and from looking over the log file, there's a lot of lines of the below format but I'm not sure what to do with this information:
`Skipping copying of file "/Users/emilyjablonski/Library/Caches/Yarn/....etc" as the file at "/Users/emilyjablonski/code/bloom/backend/core/node_modules/...etc" is the same size (xx) and mtime (xxx).

Would love any ideas! It is a monorepo w a few high level packages.

[log.zip](https://github.com/yarnpkg/yarn/files/5935866/log.zip)

**Comment by eliduke** [comment]
I am having this exact same problem with nearly identical macOS, yarn, node, and npm versions. And, it's interesting because it spends most of it's time on:
```
Running "watch" task
 66% building modules
```
And some times it actually goes back and forth. Like it gets up to 50% and then works it way down to 40% and then back up to 50% and then hangs out around 66% for about 10 or 15 minutes. Sometimes wavering between 66 to 67 to 68 and then back to 66%. It's a wild ride, let me tell you!

**Comment by emilyjablonski** [comment]
Due to many other network issues I ended up having w my brand new M1 Mac, I actually ended up replacing it with an Intel version 😬  I don't have the problems anymore but ideally there's an actual solution for you!

**Comment by rally25rs** [comment]
@eliduke  the output there is not from `yarn` itself, it is from whatever your `start` script is running.

@emilyjablonski were you running yarn in a VM by chance? Poking through your log it looks like there are occasionally almost 0.8s gaps between just creating directories:

```
verbose 212.162569292 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/loader-utils/lib".
verbose 212.957526959 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/lodash/fp".
verbose 213.431658542 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/lower-case/dist".
verbose 213.432915292 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/lower-case/dist.es2015".

...

verbose 264.976544209 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/@nestjs/schematics/node_modules/rxjs/migrations/update-6_0_0".
verbose 265.795486 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/@nestjs/schematics/node_modules/rxjs/observable/dom".
verbose 266.372487375 Creating directory "/Users/emilyjablonski/code/bloom/node_modules/@nestjs/schematics/node_modules/rxjs/src/add".
```

(the number at the beginning of each line is the current time into the install)

Seems like it took about 14min to copy all the files into node_modules. Usually I see pretty bad file i/o performance if I am in a VM or running in Vagrant or Docker.

**Comment by Saquib764** [comment]
I am having the same issue on brand new M1 macbook pro. Did anyone find a solution.

I can do `yarn install` on ubuntu on the same network.

**Comment by emilyjablonski** [comment]
> @emilyjablonski were you running yarn in a VM by chance? 

At the time I wasn't running a VM, I'm wondering if I didn't have the M1 flavor of yarn properly installed

**Comment by Saquib764** [comment]
Switching the node version to 16.0.0 helped. Everything was blazing fast. `yarn install` got completed in few seconds!!

Earlier I was using node 12.0.0

This article helped me - https://www.reddit.com/r/node/comments/lp9xlk/mac_mini_m1_issues_with_node_js_15/

**Comment by mattread90** [comment]
I had this issue and it turned out the node binary I had installed via nvm wasn't compiled for the M1 chip architecture. Seems like this can happen with any node version <15. There is a small section in the nvm README detailing some steps you can take to identify and resolve this issue (look for the **Macs with M1 chip** header): https://github.com/nvm-sh/nvm#macos-troubleshooting

**Comment by itemka** [comment]
@mattread90 you are definitely right. I've applied this nvm note about M1 from README.md and it helps, thanks a lot!

**Comment by pavanmehta91** [comment]
Thanks @mattread90 It really helped.

**Comment by merceyz** [comment]
Closing as this seems to be a Node and M1 thing and not an issue with Yarn

**Comment by OriginZero** [comment]
Check your node architecture version by running `node -p os.arch()` If it is x86/64, that may be the reason why it is running slowly.
