### ISSUE TITLE
Add --online option to upgrade (and add) to skip offline cache

### ISSUE THREAD

**Issue by FokkeZB** [yarnpkg/yarn#858]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I can use `--offline` to force using cache, but I cannot do the opposite.

**What is the expected behavior?**
I'd like to be able to skip cache, e.g. when I depend directly on a GitHub repository and I want to get the latest, even though the version hasn't changed.

**Please mention your node.js, yarn and operating system version.**
Node 4.2.3, Yarn 0.15.1, Mac OS Sierra 10.12.1 Beta (16B2333a)

**Comment by dylanparry** [comment]
Does `yarn add <package_name> --force` do this?

**Comment by FokkeZB** [comment]
I dunno, it's not documented in `yarn add --help` and `force` by itself is not really descriptive. Force what?

BTW, if we add `--online` to upgrade then it also needs to be able to upgrade only a single package (like `add`). It doesn't make sense to use `--online` for all of your dependencies.

**Comment by AlicanC** [comment]
`yarn help add` doesn't have a description for `--force`. If it does what @FokkeZB needs, then we can repurpose this issue to add a description to `--force`.

**Comment by dylanparry** [comment]
Although it doesn't have any documentation in `yarn add --help`, there's a similar option for `yarn --force` which forces all packages to be refetched. This (unhelpfully) also isn't documented in `yarn --help`, but there's a description here: https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-force

Oddly, there's no entry for the `--force` flag on the page for `yarn add`, but it definitely exists.

**Comment by FokkeZB** [comment]
Closing as #870 documents force, which does what this issue asks for.
