### ISSUE TITLE
yarn seems to use some cache within docker container despite all docker [...] prunes

### ISSUE THREAD

**Issue by desmap** [yarnpkg/yarn#8581]
Despite cleaning all possible caches with...
```
docker builder prune
docker volume prune
docker system prune -a
```
yarn seems to find a way to cache somehow and when the image is being built and `RUN yarn install` is executed, yarn need something like 0.21s for a huge repo. Also in the local app folder which is the volume is nowhere any `.yarn` cache folder.

What do I miss?

**Comment by desmap** [comment]
Even if I put a `RUN yarn cache clean` before `RUN yarn install` yarn needs still 0.21s.

**Comment by rally25rs** [comment]
You could try running `yarn cache dir` to get the location of the yarn cache, and `yarn cache list` to list all packages currently in the cache.

**Comment by merceyz** [comment]
If you're copying in the `node_modules` folder Yarn will see that your `package.json` and `yarn.lock` hasn't changed since last it ran and just bail out

**Comment by rally25rs** [comment]
Good point, make sure you have `node_modules` in your `.dockerignore`
