### ISSUE TITLE
Failed to compile after deleting yarn.lock

### ISSUE THREAD

**Issue by bigybig** [yarnpkg/yarn#8587]
Hi,

I was not able to compile typescript project after I deleted yarn.lock and install dependecies again.
Step by step:

1. I used this small libraries to sync version from yarn.lock to package.json https://github.com/vasilevich/sync-yarnlock-into-packagejson
2. I deleted yarn.lock
3. I run yarn install
4. I got compilation error

**BUT If I follow these steps (skip deleting yarn.lock) below, I did not get compilation error**

1. I used this small libraries to sync version from yarn.lock to package.json https://github.com/vasilevich/sync-yarnlock-into-packagejson
2. I run yarn install
3. I got compilation error

Could you some explain how it is possible? Thank you

**Comment by merceyz** [comment]
When you delete the lockfile of the package manager Yarn, pnpm, and npm will fetch the latest version of everything (as long as it matches the semver ranges) which means you can get stuff that is no longer compatible with whatever it was setup with originally.

**Comment by bigybig** [comment]
I would accept you answer in case when I did not do point 1. in which I use absolutely same versions of libraries from yarn.lock
