### ISSUE TITLE
 bug i have this always error when i try to install pkg

### ISSUE THREAD

**Issue by NANI1734** [yarnpkg/yarn#8588]
**error An unexpected error occurred: "https://registry.npmjs.org/react: error:0909006C:PEM routines:get_name:no start line".**

my full report

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js add --exact react react-dom react-scripts cra-template --cwd C:\Users\...\Desktop\yarn\testing

PATH: 
  C:\Users\...\Desktop\yarn\node_modules\.bin;C:\Users\....\Desktop\node_modules\.bin;C:\Users\...\node_modules\.bin;C:\Users\node_modules\.bin;C:\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\node-gyp-bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Java\jre1.8.0_271\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\nadia\.windows-build-tools\python27;C:\Users\nadia\AppData\Local\Microsoft\WindowsApps;C:\Users\nadia\.dotnet\tools;C:\Users\nadia\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\nadia\AppData\Local\atom\bin;C:\Program Files\JetBrains\PyCharm 2020.2.4\bin;;C:\Users\nadia\AppData\Local\GitHubDesktop\bin;C:\Users\nadia\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\nadia\.dotnet\tools;C:\ffmpeg\bin;C:\Program Files\heroku\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\bin;;C:\Users\nadia\AppData\Local\Yarn\bin;C:\Users\nadia\.dotnet\tools;C:\Users\nadia\AppData\Roaming\npm;C:\Users\nadia\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Users\nadia\AppData\Local\npm-cache\_npx\c67e74de0542c87c\node_modules\.bin

Yarn version: 
  1.22.5

Node version: 
  14.15.5

Platform: 
  win32 x64

Trace: 
  Error: https://registry.npmjs.org/react: error:0909006C:PEM routines:get_name:no start line
      at Object.createSecureContext (_tls_common.js:149:17)
      at Object.connect (_tls_wrap.js:1580:48)
      at Agent.createConnection (https.js:129:22)
      at Agent.createSocket (_http_agent.js:323:26)
      at Agent.addRequest (_http_agent.js:274:10)
      at new ClientRequest (_http_client.js:306:16)
      at Object.request (https.js:313:10)
      at Request.module.exports.Request.start (C:\Program Files (x86)\Yarn\lib\cli.js:141311:32)
      at Request.module.exports.Request.end (C:\Program Files (x86)\Yarn\lib\cli.js:142070:10)
      at end (C:\Program Files (x86)\Yarn\lib\cli.js:141124:14)

npm manifest: 
  {
    "name": "testing",
    "version": "0.1.0",
    "private": true
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by NANI1734** [comment]
pls help

**Comment by rally25rs** [comment]
Everything I've seen come up in search results makes it sound like this error indicates an invalidly formatted SSL certificate. From the stack trace it just looks like it happens during an HTTPS request 😕 Not sure how the TLS cert would be invalid 🤷

**Comment by NANI1734** [comment]
i fix it by removing config files
