### ISSUE TITLE
registry yarnpkg not found

### ISSUE THREAD

**Issue by binajmen** [yarnpkg/yarn#8593]
## Bug report

I'm trying to add new package with `yarn add ..` but I receive the following error:
```
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@/types/lodash.mergewith/-/lodash.mergewith-4.6.6.tgz: Request failed \"404 Not Found\"".
```

I have the same issue whith the package `object-assign`. Both packages are listed as dependencies in `yarn.lock`:
```
  "@chakra-ui/utils@1.2.0":
    version "1.2.0"
    resolved "https://registry.yarnpkg.com/@chakra-ui/utils/-/utils-1.2.0.tgz#9385950e91455ecf480eb52bca268d3a5f8c9d6d"
    integrity sha512-oMTX8BX1+MUf+iYUafFm9tNfwa3m1cqzMcE/5iQFmNcqKlZmuADnVL28Yw7jhoeouIjANaGY+f51qj9zHgDn9Q==
    dependencies:
      "@/types/lodash.mergewith" "4.6.6"
      "@/types/object-assign" "4.0.30"
      css-box-model "1.2.1"
      lodash.mergewith "4.6.2"
```

If I visit https://registry.yarnpkg.com/@/types/lodash.mergewith/-/lodash.mergewith-4.6.6.tgz, I receive a 404 ResourceNotFound.

## Steps to reproduce

Install a new package using `yarn add`

## System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Yarn       |     1.22.10       |
| Browser          |      Chrome      |
| Operating System |        macOS    |

**Comment by thealitahir** [comment]
Were you able to resolve this? @binajmen

**Comment by merceyz** [comment]
`@/types/lodash.mergewith` isn't valid, it should be `@types/lodash.mergewith`

**Comment by binajmen** [comment]
Yes, the issue was I replaced a little bit too much the occurrences of `@types` with `@/types`. Be sure to exclude non source files when bulk replacing ;)
