### ISSUE TITLE
support --immutable as alias for --frozen-lockfile

### ISSUE THREAD

**Issue by macrozone** [yarnpkg/yarn#8597]
I am maintaining CI build pipeline and I want to slowly migrate to yarn2,
the problem is now that the pipeline does a  `yarn install --frozen-lockfile`  and that will throw an error in yarn2.

in yarn 2 i need `--immutable` instead.

apart from that the pipeline would not need to care whether the project uses yarn1 or yarn2 and i hope that i do not need to check whether the project uses yarn1 or yarn2.

if yarn 1 would already support `--immutable` (just an alias to `--frozen-lockfile`), this would be trivial.

On a sidenote: yarn 2 **errors** that `--frozen-lockfile` is deprecated, but there was never a grace period for it. In my opinion this is not how you should deprecate stuff.

**Comment by merceyz** [comment]
We have no plans of adding that to Yarn 1, however Yarn 2 changed `--frozen-lockfile` from an error to an alias for `--immutable` + a warning in https://github.com/yarnpkg/berry/pull/2488.
You can use the latest version from sources by running
```
yarn set version berry && yarn set version from sources
```

**Comment by macrozone** [comment]
that would help a bit, but is not very satisfying as we will still have a deprecation warning and its clear that this will just break in the future as it is breaking now.

Adding an alias to yarn1 is a no-brainer and some few lines of code that would solve a lot of headaches. The name is also correct as it does not mutate the lockfile.

**Comment by dimaqq** [comment]
Could someone clue me in why it's working for me on macos but not linux?

macOS, via `npm install -g yarn`

```
~/proj (branch-blah|…) > yarn --version
1.22.10
~/proj (branch-blah|…) > yarn install --immutable
yarn install v1.22.10
[blah blah]
success Already up-to-date.
✨  Done in 0.34s.
```

Ubuntu (container) via `apt-get install yarnpkg; ln -sf yarnpkg /usr/bin/yarn`

```
root@4dc3c8923323:/# yarn --version
1.22.10
root@4dc3c8923323:/# yarn install --immutable
error: unknown option '--immutable'
```
