### ISSUE TITLE
Problems at excute commando  yarn workspace

### ISSUE THREAD

**Issue by breno-felipe** [yarnpkg/yarn#8598]
Hey, guys,

In the company where I work we use yarn workspaces to raise our frontend, and lately I have been having some problems executing this command.

Below is a print of the command script that we execute
Command `yarn run vigia-elite`

![image](https://user-images.githubusercontent.com/50807243/111773402-e3962900-888c-11eb-8c10-6530b6dbe825.png)

The photo below shows the problem that happens when I run yarn

![image](https://user-images.githubusercontent.com/50807243/111773218-a6319b80-888c-11eb-96fb-17bfdb5575d6.png)

Someone who has had this problem and managed to solve it?

If someone has succeeded if you can share thank you!

Versions:

`node.js > v12.21.0`
`yarn > 1.22.5`

**Comment by merceyz** [comment]
Based on what you posted in https://github.com/yarnpkg/berry/discussions/2617 it looks like your development server is crashing which isn't something Yarn has control over.
