### ISSUE TITLE
cssnano yarn resgistry points to incorrect repo

### ISSUE THREAD

**Issue by arderyp** [yarnpkg/yarn#8602]
My project includes [@symfony/webpack-encore](https://github.com/symfony/webpack-encore), which has a dependency chain that includes cssnano. I just ran an update and yarn appears to determine to location of cssnano package from:

https://registry.yarnpkg.com/cssnano/

this page point to https://github.com/ben-eb/css-nano (which doesn't exist) instead of https://github.com/cssnano/cssnano.

It does look like https://github.com/ben-eb/cssnano (note the lack of the hyphen) *does* exist, and accurately forwards to The correct https://github.com/cssnano/cssnano repo.

**Comment by merceyz** [comment]
That's the old versions, https://registry.yarnpkg.com/cssnano/4.1.10 points to https://github.com/cssnano/cssnano

https://yarnpkg.com/getting-started/qa/#why-registryyarnpkgcom-does-facebook-track-us

**Comment by arderyp** [comment]
thanks for the clarification @merceyz
