### ISSUE TITLE
Update README to clarify that this repository is unmaintained

### ISSUE THREAD

**Issue by schmod** [yarnpkg/yarn#8614]
Currently, [the GitHub Issue Template](https://raw.githubusercontent.com/yarnpkg/yarn/master/.github/ISSUE_TEMPLATE/bug_report.md) for this repository states: 

> we don't plan to merge pull requests or release future versions of Classic unless it's to solve an critical vulnerability report (which is unlikely). 

This appears to be the _only_ place where Yarn 1's deprecation is noted – at that, the notice is placed in _in a HTML comment_, which [renders it invisible](https://github.com/yarnpkg/yarn/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)!).  

Neither `README.md` nor the pull-request template note that this repository is unmaintained.

Before others waste hours contributing fixes and pull-requests, can we please put this notice in a more prominent place so that contributors (such as myself) do not waste their time fixing bugs or creating pull-requests?

**Can a maintainer please update `README.md` to clarify that the Yarn 1.x release line is unmaintained, and will not receive fixes for non-security-related issues?**

Also, the link to the 'Contributing' guide is broken.

**Comment by alanrps** [comment]
You are greek god, thank you @schmod! I was also wasting time.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/commit/0a121f66ffcb4fc48ed6ea9e5ad928bd7cdc9b5f
