### ISSUE TITLE
Shutting down parts of legacy Yarn v1 build infra

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#8618]
I'm going to shut down some legacy parts of the Yarn v1 build infra, namely the Jenkins build server. I'm not sure it's even working properly any more, but this will serve as a formal deprecation.

This was used for doing the following when new GitHub releases were published:
 - Updating the version number on the https://classic.yarnpkg.com site (`./scripts/set-version.sh` in website repo)
 - Pushing the update to Chocolatey (`.\scripts\build-chocolatey.ps1 -Publish`)
 - Pushing the update to Homebrew (`./scripts/update-homebrew.sh`)

For reference, the jobs were configured via the [jenkins_jobs.groovy](https://github.com/yarnpkg/yarn/blob/master/jenkins_jobs.groovy) file in the repo root.

For context, this was all built out before CircleCI was as flexible as it is now, and neither Azure Pipelines nor GitHub Actions existed yet. If we were to redo the exact same thing today, it'd likely be done using GitHub actions.

There's still some other parts of the build process that are running on a separate system that's still up, but I'll likely decommission that at some point too:
- Pushing files to GitHub releases from CircleCI and AppVeyor build artifacts
- Authenticode signing Windows installer (.msi)
- GPG signing releases
- Updating Debian and RPM repos based on GitHub releases

If we decide to release any new versions of Yarn 1.x, we can perform all these release steps manually - Just ping me if you'd like me to do it 😃 

cc @arcanis

**Comment by arcanis** [comment]
Hey Daniel! That sounds fine to me, I think the latest few releases (not many changes anyway) were done manually anyway.

I was however looking at automating releases on the @yarnpkg/berry repository (via a GH action), can you add `yarnbot` to the npm org to this effect (otherwise I'd have to put my own account's token in the repo secrets)?

**Comment by arcanis** [comment]
Ping @Daniel15 ?

**Comment by Daniel15** [comment]
Hey @arcanis, sorry for the delay in replying. I didn't see this the email was filed away in a folder for "miscellaneous GitHub emails" that I don't check often.

I can add Yarnbot to the npm org, however I don't actually have the password to log in to that account. Do you have it? Otherwise we can just make a brand new npm user and I can add that?

**Comment by arcanis** [comment]
> I can add Yarnbot to the npm org, however I don't actually have the password to log in to that account. Do you have it? Otherwise we can just make a brand new npm user and I can add that?

Yep, I have it! I created it a while ago for automation purposes, but forgot about it until recently 😃

**Comment by Daniel15** [comment]
@arcanis I sent an invite to yarnbot; you'll have to accept that :)

**Comment by Daniel15** [comment]
Closing this old issue.
