### ISSUE TITLE
Installation Problem: [.msi Installer Page not found]

### ISSUE THREAD

**Issue by scyq** [yarnpkg/yarn#8619]
**Which operating system are you using:**
Windows10

**Please describe the steps you took when trying to install Yarn and what went wrong:**
In Chinese page, it is unable to open the .msi download page of all versions.
![image](https://user-images.githubusercontent.com/45393064/115191446-0467cd80-a11c-11eb-9697-c08c6882ef1d.png)

**Comment by merceyz** [comment]
We don't control that page so closing as unactionable

**Comment by yyanus** [comment]
Le lun. 19 avr. 2021 02 h 33, Yuqing Chen ***@***.***> a
écrit :

**Comment by SumanthSrungavarapu** [comment]
I am also facing the same problem. please share the solution.
