### ISSUE TITLE
Yarn does not execute the postinstall script from package.json

### ISSUE THREAD

**Issue by andi-d** [yarnpkg/yarn#862]
**Do you want to request a *feature* or report a *bug*?**
bug/feature

**What is the current behavior?**
yarn does not execute the postinstall script from the package.json after running `yarn`

**If the current behavior is a bug, please provide the steps to reproduce.**
in my case, i need to run `bower install` after installing the dependencies. installing the dependencies with `npm install` executes `bower install` automatically.

**What is the expected behavior?**
executing whatever is in the postinstall in the `package.json`

**Please mention your node.js, yarn and operating system version.**
yarn 0.15.1
node v5.10.1
OS Win10

**Comment by Itrulia** [comment]
duplicate of #853

**Comment by andi-d** [comment]
ah, sorry. i searched beforehand but somehow missed that.
