### ISSUE TITLE
Yarn add {package} error An unexpected error occurred

### ISSUE THREAD

**Issue by Luk-kar** [yarnpkg/yarn#8621]
## 1) Do you want to request a feature or report a bug?
bug
## 2) What is the current behavior?
When I try to add any package or any other yarn command with the exception yarn --version, I get the following error:
D:\UserData\Documents\MyProject> yarn add --dev @testing-library/react-native
1.22.10
```
error An unexpected error occurred: "D:\\UserData\Documents\MyProject\\package.json: Unexpected token } in JSON at position 323". 
info If you think this is a bug, please open a bug report with the information provided in "D:\\UserData\Documents\MyProject\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Here is the error log:
```
  SyntaxError: D:\\UserData\Documents\MyProject\package.json: Unexpected token } in JSON at position 323
      at JSON.parse (<anonymous>)
      at C:\Users\UserName\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:1625:59
      at Generator.next (<anonymous>)
      at step (C:\Users\UserName\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
      at C:\Users\UserName\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:321:13
```

which appears to point at this being the problem at line 1625 in the first file above:
```
var readJsonAndFile = exports.readJsonAndFile = function () {
  var _ref24 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (loc) {
    var file = yield readFile(loc);
    try {
      return {
        object: (0, (_map2 || _load_map2()).default)(JSON.parse(stripBOM(file))), // <= line 1625
        content: file
      };
    } catch (err) {
      err.message = `${loc}: ${err.message}`;
      throw err;
    }
  });

  return function readJsonAndFile(_x21) {
    return _ref24.apply(this, arguments);
  };
}();
```

## 3) If the current behavior is a bug, please provide the steps to reproduce it.
- I'm not sure what hapanned, it worked until I wanted to install --dev @testing-library/react-native
- Now even npm uninstall -g yarn and npm install -g yarn does not solve the case
- I also can't update yarn by command yarn set version berry

## 4) What is the expected behavior?
Put the dependency in the package.js file

## 5) Please mention your node.js, yarn, and operating system version.
Windows 10, Yarn v1.22.10, Node v12.18.2

--------------------

The solution mentioned in https://github.com/yarnpkg/yarn/issues/7639 didn't work out. I don't have any package.json in home directory

**Comment by merceyz** [comment]
Closing for the same reason as https://github.com/yarnpkg/yarn/issues/7639#issuecomment-753419985
