### ISSUE TITLE
Error creating react app using yarn

### ISSUE THREAD

**Issue by brianmureithi** [yarnpkg/yarn#8628]
[1/4] Resolving packages...
[2/4] Fetching packages...
An unexpected error occurred: "C:\\Users\\gt\\AppData\\Local\\Yarn\\Cache\\v6\\npm-array-includes-3.1.3-c7f619b382ad2afaf5326cddfdc0afc61af7690a-integrity\\node_modules\\array-includes\\.yarn-metadata.json: Unexpected token \u0000 in JSON at position 0"

**Comment by haneenmahd** [comment]
try cleaning the cache using
```
yarn cache clean --all
```
or 
```
npm cache clean -f
```
