### ISSUE TITLE
`yarn create react-app app` - hangs as well as `npx create-react-app app`

### ISSUE THREAD

**Issue by koala-lava** [yarnpkg/yarn#8631]
The above commands hang at `Installing packages. This might take a couple of minutes` stage. 
npx command works if there's no yarn installed(no matter if it's through system repo or `npm install -g yarn`)
the same with yarn 2 `yarn dlx create-react-app app`
the behavior is present in node v14.15.1 and v16.1.0, also tried nvm(the same thing occurs).

yarn 1.22.10
npm 6.14.8

**yarn config list**
```
{
'version-tag-prefix': 'v',
'version-git-tag': true,
'version-commit-hooks': true,
'version-git-sign': false,
'version-git-message': 'v%s',
'init-version': '1.0.0',
'init-license': 'MIT',
'save-prefix': '^',
'bin-links': true,
'ignore-scripts': false,
'ignore-optional': false,
registry: 'http://registry.npmjs.org',
'strict-ssl': true,
'user-agent': 'yarn/1.22.10 npm/? node/v14.15.1 linux x64',
lastUpdateCheck: 1620817309015,
prefix: '/home/user/.yarn'
}
info npm config
{
registry: 'http://registry.npmjs.org/',
'http-proxy': null
}
```

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.10.34-1-MANJARO
OS Type: 64-bit

**Comment by merceyz** [comment]
Closing as unactionable, there isn't much we can do about this

> the same with yarn 2 yarn dlx create-react-app app

Some specifics here would be appreciated, like the exact version

**Comment by koala-lava** [comment]
yarn 2.4.1
Guys, I need a solution. This is certainly a yarn issue.
```
Trace: 
Error: https://registry.yarnpkg.com/create-react-app: ETIMEDOUT
at Timeout._onTimeout (/usr/lib/node_modules/yarn/lib/cli.js:141409:19)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
```
Tried increasing timeout, cleaning cache, removing configs etc.
`yarn install` works, it only those commands that fail to work. It only appears when I install yarn. 
Those commands work on my mobile internet, but not on my home Wi-Fi, but the commands work on another laptop with Windows 10 on the same home Wi-Fi so the issue has nothing to do with a router(did factory-reset) or ISP.

**Comment by koala-lava** [comment]
I fixed the issue by flushing DNS cache(on Linux):
`sudo systemd-resolve --flush-caches` 
or if that doesn't help
`sudo killall -USR2 systemd-resolved`
