### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/libpng-dev: Not found".

### ISSUE THREAD

**Issue by su-dd** [yarnpkg/yarn#8632]
error An unexpected error occurred: "https://registry.yarnpkg.com/libpng-dev: Not found".

**Comment by merceyz** [comment]
Closing as unactionable, we don't control the registry and missing/private packages isn't something we can help with.

https://yarnpkg.com/getting-started/qa/#why-registryyarnpkgcom-does-facebook-track-us
