### ISSUE TITLE
yarn compatibility error on ubuntu linux when trying to use tailwind with Nuxt and Vue

### ISSUE THREAD

**Issue by yash982000** [yarnpkg/yarn#8643]
The command run was `yarn upgrade nuxt`

which gave the below error

info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error tailwindcss@2.1.4: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.

**Comment by merceyz** [comment]
As the error explicitly states: `tailwindcss@2.1.4` requires you to use `node@>=12.13.0` while you're using `node@10.19.0`.

To disable engine checks see https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-engines

**Comment by yash982000** [comment]
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /home/yash982000/Desktop/People Of Prints/thememory-fe/node_modules/deasync
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.2.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
(node:9908) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/yash982000/Desktop/People Of Prints/thememory-fe/node_modules/deasync/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/yash982000/.cache/node-gyp/16.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/yash982000/.cache/node-gyp/16.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/yash982000/.cache/node-gyp/16.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/yash982000/Desktop/People Of Prints/thememory-fe/node_modules/deasync',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/yash982000/Desktop/People Of Prints/thememory-fe/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
g++: error: Of: No such file or directory
g++: error: Prints/thememory-fe/node_modules/node-addon-api: No such file or directory
make: *** [deasync.target.mk:111: Release/obj.target/deasync/src/deasync.o] Error 1
make: Leaving directory '/home/yash982000/Desktop/People Of Prints/thememory-fe/node_modules/deasync/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.8.0-53-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/yash982000/Desktop/People Of Prints/thememory-fe/node_modules/deasync
gyp ERR! node -v v16.2.0
