### ISSUE TITLE
Error when use WSL in VSCode

### ISSUE THREAD

**Issue by LGDHuaOPER** [yarnpkg/yarn#8651]
When I use VSCode in Windows10, click the script in NPM SCRIPT sidebar, then show the error under:

> Executing task: yarn run dev <

Yarn requires Node.js 4.0 or higher to be installed.
The terminal process "C:\WINDOWS\System32\wsl.exe -d Ubuntu -e yarn run dev" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

![image](https://user-images.githubusercontent.com/22699037/122644250-d700c580-d146-11eb-8d94-92fbcea88924.png)

My tools are:
![image](https://user-images.githubusercontent.com/22699037/122644314-2e069a80-d147-11eb-98e0-6a137491f797.png)

**Comment by RDIL** [comment]
Looks like Yarn is using some other node version somehow.  Please comment if this is still a problem.
