### ISSUE TITLE
yarn start inside a script failed with error Could not write file

### ISSUE THREAD

**Issue by olechnwin** [yarnpkg/yarn#8652]
Hi,
I am trying to run yarn inside a script as follows:

`sbatch --time=10:00 --wrap "singularity exec $momig_frontend_img bash -c 'cd /opt/MoMI-G && yarn start'"`

but got this error:

```
yarn run v1.22.10
$ react-app-rewired start --scripts-version react-scripts-ts
error Could not write file "/opt/MoMI-G/yarn-error.log": "EROFS: read-only file system, open '/opt/MoMI-G/yarn-error.log'"
error An unexpected error occurred: "EROFS: read-only file system, mkdir '/gpfs0'".
```
However, the following command works:

`singularity exec $momig_frontend_img bash -c 'cd /opt/MoMI-G && yarn start'
`

What do I have to do to run `yarn start` inside a script?

Thank you in advance for your help.

**Comment by iDuuck** [comment]
From which user are you executing the script? And what exactly is `singularity`? Also, are you sure, the `cd` Is actually being run? Since both scripts should not work, when the file system is being under „Read-Only“.

**Comment by olechnwin** [comment]
Thanks for your help. I'm running the script as a user not root if that's what you're asking. singularity is a container just like docker so I'm running it inside a singularity container which contains its own OS.
I'm pretty sure the cd is being run because I have the `yarn` installed in `/opt/MoMI-G`.
That's what confuses me, I thought both commands should not work if the file system is under "Read-only"

**Comment by RDIL** [comment]
Looks like a filesystem error instead of a Yarn error.
