### ISSUE TITLE
1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c

### ISSUE THREAD

**Issue by jkdz12** [yarnpkg/yarn#8654]
[yarn-error.log](https://github.com/yarnpkg/yarn/files/6720581/yarn-error.log)

**Comment by luz0073** [comment]
Tried to create a project using create-react-app and yarn returned me this log

**Comment by RDIL** [comment]
I think this is an OpenSSL/Node.js/system issue of some kind... Yarn doesn't handle SSL, so I believe this is out of scope.
