### ISSUE TITLE
The installed package is missing the src folder

### ISSUE THREAD

**Issue by youzouzou** [yarnpkg/yarn#8667]
### Describe the bug

When I installed [v-viewer](https://github.com/mirari/v-viewer), I found that the `src` folder was missing in the package.
And I found that it was a problem with this package：
https://registry.yarnpkg.com/v-viewer/-/v-viewer-1.6.4.tgz#39e36b534baab34076fb816704c6a734de0dc72f

### To reproduce

package.json:
```
"dependencies": {
      "v-viewer": "^1.5.1"
},
```

`yarn`

yarn.lock： 
```
v-viewer@^1.5.1:
  version "1.6.4"
  resolved "https://registry.yarnpkg.com/v-viewer/-/v-viewer-1.6.4.tgz#39e36b534baab34076fb816704c6a734de0dc72f"
  integrity sha512-LVkiUHpmsbsZXebeNXnu8krRCi5i2n07FeLFxoIVGhw8lVvTBO0ffpbDC6mLEuacCjrIh09HjIqpciwUtWE8lQ==
  dependencies:
    throttle-debounce "^2.0.1"
    viewerjs "^1.5.0"
```

### Environment

Node: 14.15.4
npm: 6.14.10

**Comment by merceyz** [comment]
You already opened an issue at https://github.com/yarnpkg/berry/issues/3161
