### ISSUE TITLE
yarn audit in a monorepo

### ISSUE THREAD

**Issue by YuriGal** [yarnpkg/yarn#8668]
We're using `yarn audit` extensively in our daily workflow, but we encountered an issue: in a monorepo that uses yarn workspaces `yarn audit` seems to scan _the entire repo_. Our current workaround is to run the audit, cache the result, and filter it by the path to actual service we're auditing - but this is slow and counterproductive. Is there a way to limit audit to actual service being audited?

**Comment by merceyz** [comment]
This was implemented in https://github.com/yarnpkg/berry/pull/1892 which was released in 2.4.0

https://yarnpkg.com/getting-started/migration
https://yarnpkg.com/cli/npm/audit
