### ISSUE TITLE
[Website] Latest version is incorrect

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [yarnpkg/yarn#8677]
Right now, on the landing page https://classic.yarnpkg.com/ it states "Classic Stable: v1.22.5" but is linking to the changelog with new releases present. This leads to confusion. Even bigger problem is what https://classic.yarnpkg.com/latest-version returns, also 1.22.5
Confusion it caused: https://github.com/nodejs/docker-node/issues/1542

**Comment by FlorianWendelborn** [comment]
Seems related to the incredibly "high-priority" #8374

FYI, yarn 1 is pretty much dead. You can tell by the issue templates explicitly mentioning that anything but high risk security issues will no longer be handled.

Would be fine if yarn 2 wouldn't break half the ecosystem 🥲

**Comment by merceyz** [comment]
> Would be fine if yarn 2 wouldn't break half the ecosystem 🥲

Yarn 2 (and 3) can install using `node_modules` so you'll have to be a bit more specific about what breaks and open issues about it. Just saying "it breaks stuff" is completely useless for everyone as it's unactionable.

**Comment by arcanis** [comment]
I've just manually updated the website to reflect the current latest release from the 1.x branch (the newly released [1.22.13](https://github.com/yarnpkg/yarn/releases/tag/v1.22.13))
