### ISSUE TITLE
yarn i

### ISSUE THREAD

**Issue by JimLynchCodes** [yarnpkg/yarn#8678]
I have to do "yarn install" every time I would like to install dependencies.

This is insane. Really Forcing users to type out the entire word "install"?? Why??

With regular npm I can do this:
```
npm i
```

wow, now nice. such beautiful;!

Would like to do a similar with yarn:
```
yarn i
```

thanks! ♥️

**Comment by merceyz** [comment]
We can go even further, you can run just `yarn` to perform an install

**Comment by betterhgl** [comment]
You can use the abbreviate command:
`yarn`
to install dependencies.
