### ISSUE TITLE
yarn erroring when run from Dockerfile

### ISSUE THREAD

**Issue by nealstewart** [yarnpkg/yarn#869]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

When running yarn inside of a Dockerfile, it is 

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a Dockerfile along these lines

```
FROM node:4.5.0
WORKDIR /opt/my-app
RUN npm install -g yarn
ADD package.json /opt/my-app/
ADD yarn.lock /opt/my-app/
RUN yarn
```

This spits out an error:

```
error https://registry.yarnpkg.com/forever/-/forever-0.15.2.tgz: EINVAL: invalid argument, chown '/root/.yarn-cache/npm-forever-0.15.2/package.json'
    at Error (native)
```

**What is the expected behavior?**

`yarn` installing inside of the Docker image

**Please mention your node.js, yarn and operating system version.**

Node 4.5, yarn 0.15.1, Ubuntu 12.04 (Precise) on Circle CI

**Comment by cmwd** [comment]
@nealstewart have you tried to install yarn via script ?
```dockerfile
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
...
RUN $HOME/.yarn/bin/yarn install
```

This works for me ;)

**Comment by Daniel15** [comment]
Try using the Ubuntu package or the install script rather than npm. Details are at https://yarnpkg.com/en/docs/install. For old Ubuntu versions, you'll need to add the [NodeSource repo](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) to get a recent enough version of Node.js.

> Ubuntu **12.04** (Precise)
![](https://i.imgur.com/BO7rmKK.png)

That's a very old Ubuntu version 😮

**Comment by tristanbes** [comment]
its travis year. All container-infrastructure on travis runs on unbutu 12.04 /cc @Daniel15

**Comment by Daniel15** [comment]
Ubuntu 12.04 is super old (original release was April 2012) and will be unsupported from April next year, so if Travis are using it then I really hope they upgrade soon 😛

**Comment by mfornasa** [comment]
If you're running Alpine containers the install script is not going to work. You can install using the tarball as I did here: https://medium.com/@mfornasa/using-yarn-with-docker-c116ad289d56

**Comment by kop** [comment]
Having a problem with Docker builds too (image is based on Alpine):

```
Step 6 : RUN yarn global add nodemon
 ---> Running in aba54ec6f9f4
yarn global v0.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occured, please open a bug report with the information provided in "/root/.yarn-config/global/yarn-error.log".
```

But since build is done in container, I can't really get `"/root/.yarn-config/global/yarn-error.log"` contents.
I think Yarn is definitely missing some verbose logging settings.

**Comment by mfornasa** [comment]
@kop You can extract the file from the image with `docker cp`.

**Comment by kop** [comment]
@mfornasa, you are right totally forgot about this.

I've found this (`yarn-error.log`):

```
Arguments: 
  /usr/bin/node /opt/yarn/bin/yarn.js global add nodemon

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/yarn/bin

Yarn version: 
  0.16.0

Node version: 
  6.2.0

Platform: 
  linux x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/ps-tree/-/ps-tree-1.1.0.tgz: EINVAL: invalid argument, chown '/root/.yarn-cache/npm-ps-tree-1.1.0/package.json'
      at Error (native)
```

The interesting detail is that this build is passing when I'm running it from my local system (Ubuntu 16.04, Docker 1.12.2), but fails inside the CircleCI (Ubuntu 14.04, Docker 1.9.1).

**Comment by laggingreflex** [comment]
I'm having a similar problem, except for me yarn gets stuck 

```sh
...
Step 6 : RUN $HOME/.yarn/bin/yarn
 ---> Running in 3f12350ceae0
yarn install v0.16.0
info No lockfile found.
```

Nothing happens after that. I've tried both the `npm i -g yarn` and the curl method of install, it just gets stuck there and nothing happens.

**Comment by joeandaverde** [comment]
+1

**Comment by oshalygin** [comment]
Using @cmwd script successfully.  Pretty smooth, just takes a ton of time to install yarn as well as the packages.  Going to try to optimize in the near future.

Keeping subscribed to the thread.

**Comment by Daniel15** [comment]
> Pretty smooth, just takes a ton of time to install yarn

This should only happen the first time - Docker will cache the layer so future runs shouldn't have to install Yarn again.

**Comment by oshalygin** [comment]
@Daniel15 good call, the second time was super fast.

**Comment by bestander** [comment]
Looks like this was mitigated by now

**Comment by olalonde** [comment]
I had a similar error on CircleCI but with npm@5: https://discuss.circleci.com/t/getting-a-weird-einval-error-with-npm-on-circleci-2-0/13465
