### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [yarnpkg/yarn#8691]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by merceyz** [comment]
For now you can contact us on Discord - https://discord.com/invite/yarnpkg

**Comment by ready-research** [comment]
@merceyz You can view the report using huntr link https://www.huntr.dev/bounties/db3f7344-cc8f-4642-a189-e59ae74119b5/ and validate this. Thanks.

**Comment by merceyz** [comment]
Thanks, we'll look into it. We also added a `security.md` document in https://github.com/yarnpkg/yarn/commit/728feb1414cec2d5cb8ecf8c061bc10f03b99def so I'll close this.

**Comment by JamieSlome** [comment]
@merceyz - thanks! I have spoken with @arcanis as well ❤️
