### ISSUE TITLE
Jest error with v1.22.13

### ISSUE THREAD

**Issue by simone989** [yarnpkg/yarn#8698]
An error was encountered while I perform jest with yarn v1.22.13.

Log: 
`error An unexpected error occurred: "Potentially dangerous call to \"jest\" in /home/gitlab-runner/builds/XXXX".
info If you think this is a bug, please open a bug report with the information provided in "/home/gitlab-runner/builds/XXXX.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

With v1.22.10 works properly

**Comment by arcanis** [comment]
Can you share the directory listing of `/home/gitlab-runner/builds`? In particular, does it contain a folder (or a file) named `jest`?

This should be fixed in the 1.22.14 - it'd be great if you can confirm and close the issue if it's good on your side.

**Comment by TimBarham** [comment]
I've just hit a similar issue in 1.22.14...

"An unexpected error occurred: "Potentially dangerous call to \"node_modules\\.bin\\jest\" in D:\\[path]"

**Comment by arcanis** [comment]
Seems like it was a separate but related bug; care to try 1.22.15?

**Comment by TimBarham** [comment]
Yep, all good. Thanks!

**Comment by simone989** [comment]
I tested with 1.22.15, works properly.
Thank you.

I will close the issue.
