### ISSUE TITLE
yarn global add error => raw-socket: Command failed.

### ISSUE THREAD

**Issue by whatwewant** [yarnpkg/yarn#8703]
#10 0.271 yarn global v1.22.5
#10 0.341 [1/4] Resolving packages...
#10 3.824 [2/4] Fetching packages...
#10 11.99 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#10 11.99 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#10 12.00 [3/4] Linking dependencies...
#10 15.15 [4/4] Building fresh packages...
#10 15.38 error /usr/local/share/.config/yarn/global/node_modules/raw-socket: Command failed.
#10 15.38 Exit code: 1

Environment:
Docker Image: node:16-alpine
Yarn Version: v1.22.5
Node Version: v16.10.0
node-gyp v7.1.2

**Comment by RDIL** [comment]
Need more details, looks like an issue with the package's compatibility with the OS.
