### ISSUE TITLE
yarn add issue

### ISSUE THREAD

**Issue by hamza2806** [yarnpkg/yarn#8710]
Hello everyone,
I'm creating simple app with react and typescript, when I type "npx create-react-app app-name --template -typescript" I'm getting this error : 

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template--typescript...

yarn add v1.21.1
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/cra-template--typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/agrodz/Desktop/web-projects/react-shopping-cart/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts cra-template--typescript --cwd /home/agrodz/Desktop/web-projects/react-shopping-cart has failed.

Deleting generated file... package.json
Deleting generated file... yarn.lock
Done.

someone know how to fix that please?

**Comment by hw4n** [comment]
Hi I'm just passing by, however I think you found the solution by now, (it's been 20 days)

you entered the following command right?
```
npx create-react-app app-name --template -typescript
```

remove the '-' from last '-typescript', so it becomes
```
npx create-react-app app-name --template typescript
```

**Comment by RDIL** [comment]
Yup, hw4n is correct, extra dash, not a Yarn problem.
