### ISSUE TITLE
yarn/CONTRIBUTING.md points to a non existing page

### ISSUE THREAD

**Issue by bchabrier** [yarnpkg/yarn#8718]
The page [https://github.com/yarnpkg/yarn/issues](https://github.com/yarnpkg/yarn/issues) recommends to read the contributing guidelines in [https://github.com/yarnpkg/yarn/blob/ba0a33b7dc513d262bce505d9446d18a173a839c/CONTRIBUTING.md](https://github.com/yarnpkg/yarn/blob/ba0a33b7dc513d262bce505d9446d18a173a839c/CONTRIBUTING.md), which points to a non existent page [https://yarnpkg.com/org/contributing/](https://yarnpkg.com/org/contributing/)...

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/commit/0a121f66ffcb4fc48ed6ea9e5ad928bd7cdc9b5f
