### ISSUE TITLE
EACCES Issue

### ISSUE THREAD

**Issue by niftylettuce** [yarnpkg/yarn#872]
I did not run with sudo, I did normal bash installation on Mac and then `yarn install`.  Before running this, I cleared `~/.npm` and `node_modules`.

<img width="626" alt="screen shot 2016-10-12 at 1 58 02 am" src="https://cloud.githubusercontent.com/assets/523141/19310170/cd1a9d1a-9056-11e6-92ce-f306c6c1f822.png">

**Comment by iamstarkov** [comment]
Try this to fix

    $ sudo chown -R $USER /Users/nexus/.yarn-cache

**Comment by niftylettuce** [comment]
That's not a fix, I never used sudo, why would there be permission errors.  Something isn't right.

**Comment by ubaltaci** [comment]
I also have same permission problem for [sharp](https://github.com/lovell/sharp).

````EACCES: permission denied , open '/Users/user/.yarn-cache/npm-sharp-0.16.0/include/glibconfig.h'````

**Comment by iamstarkov** [comment]
maybe related https://github.com/lovell/sharp/issues/428#issuecomment-218827659

**Comment by iamstarkov** [comment]
@niftylettuce @ubaltaci you dont have such issues with npm?

**Comment by iamstarkov** [comment]
does yarn generates smth like `./npm-debug.log`?

**Comment by niftylettuce** [comment]
I don't have those issues, and I haven't seen any log files generated by `yarn`.

**Comment by chriscohoat** [comment]
I'm getting the same error while trying to install `sharp` with `yarn`...`npm` works just fine.

**Comment by asokani** [comment]
I have probably the same problem. npm works.

![err](https://cloud.githubusercontent.com/assets/1385293/19349281/82732320-9152-11e6-918c-c62ac7894787.png)

**Comment by ubaltaci** [comment]
probably related to #961

**Comment by asokani** [comment]
@ubaltaci is probably right, The offending package has indeed wrong permissions inside. There is missing +x for lib folder.

**Comment by lovell** [comment]
@niftylettuce @ubaltaci Are you able to provide the permissions on the sharp file that is generating the EACCES?
```sh
ls -al ~/.yarn-cache/npm-sharp-0.16.0/include/glibconfig.h
```
This should hopefully reveal the user (and possibly reveal the umask, given the tarball) used by yarn when invoking node-gyp.

**Comment by ubaltaci** [comment]
@lovell 

```-r--r--r--  1 myusername  staff  5496 Aug 10 10:59 /Users/myusername/.yarn-cache/npm-sharp-0.16.0/include/glibconfig.h```

**Comment by lovell** [comment]
@ubaltaci Thanks, the permissions match the tarball.
```
$ tar tfv libvips-8.3.3-darwin-x64.tar.gz | grep glibconfig
-r--r--r-- travis/staff   5496 2016-08-10 08:59 include/glibconfig.h
```
My best guess would be that yarn is trying to overwrite files in its own cache.

**Comment by puzrin** [comment]
About `sharp` install problems:

1. yarn fails under OSX
2. yarn works in Ubuntu
3. npm works buth in OSX & Ubuntu.

node was installed via `nvm` everywhere.

**Comment by lovell** [comment]
To allow `sharp` to be installed on OS X using `yarn`, I've manually updated the permissions on the `glibconfig.h` file in the relevant tarball to include o+w:
```sh
$ tar tfv libvips-8.3.3-darwin-x64.tar.gz | grep glibconfig
-rw-r--r-- travis/staff   5496 2016-08-10 08:59 include/glibconfig.h
```
The underlying cause of this problem remains, namely that `yarn` requires write access to files in its cache but is not currently verifying/ensuring the relevant permission to do so.

**Comment by niftylettuce** [comment]
It has been two weeks, why is this not fixed yet?..  I thought Yarn was the real deal 😦

**Comment by samccone** [comment]
I am no longer able to reproduce this on master. can someone else verify @yarnpkg/core 

### test case:
```yarn add sharp```

**Comment by lovell** [comment]
@samccone sharp no longer provides a suitable test case for this problem as it has been patched to include user+write file permissions.

**Comment by despairblue** [comment]
@samccone these are suitable test cases:

```sh
yarn add @types/react-router@2.0.37
yarn add easy-table@0.0.1
```

**Comment by kvz** [comment]
I think I just ran into this when yarn was installing `easy-table`:

```
$ yarn
yarn install v0.17.8
info No lockfile found.
[1/4] Resolving packages...
warning node-uuid@1.4.3: use uuid module instead
warning azure-cli > node-uuid@1.2.0: use uuid module instead
warning stackvis > node-uuid@1.4.1: use uuid module instead
warning request > node-uuid@1.4.7: use uuid module instead
warning airbud > request > node-uuid@1.4.7: use uuid module instead
warning azure-cli > azure-keyvault > node-uuid@1.4.7: use uuid module instead
warning mocha > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning node-gyp > minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning coffeelint > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning mocha > glob > graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning youtube-api > googleapis > request > node-uuid@1.4.7: use uuid module instead
warning intercom-client > babel-eslint > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning stackvis > manta > showdown@0.3.1: IMPORTANT hotfix
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/easy-table/-/easy-table-0.0.1.tgz: EACCES: permission denied, open '/home/vagrant/.cache/yarn/npm-easy-table-0.0.1-dbd809177a1dd7afc06b4849d1ca7eff13e299eb/lib/table.js'".
info If you think this is a bug, please open a bug report with the information provided in "/srv/current/api2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by alcmoraes** [comment]
For me, I was having issues initing a react-native app. Cleaning up cache folder from Yarn solved the problem.

sudo rm -rf /Users/alcmoraes/Library/Caches/Yarn/*

After that, react-native init <AppName> got working again.

**Comment by yunxing** [comment]
We are also seeing a lot of this, @alcmoraes's solution works best so far.

**Comment by kvz** [comment]
> sudo rm -rf /Users/<User>/Library/Caches/Yarn/*

Ran into `Argument list too long` error, worked around that via

```
rm -rf /Users/$USER/Library/Caches/Yarn/ && mkdir -p /Users/$USER/Library/Caches/Yarn/
```

Retried `yarn`, still got:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/easy-table/-/easy-table-0.0.1.tgz: EACCES: permission denied, open '/Users/kvz/Library/Caches/Yarn/npm-easy-table-0.0.1-dbd809177a1dd7afc06b4849d1ca7eff13e299eb/lib/table.js'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kvz/code/api2/api2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by batjko** [comment]
I keep getting this EACCESS error during `yarn` or `yarn add` for a quite a few packages, which install just fine using `npm install`, however.

So falling back to npm is my workaround, but it's annoying always having to switch between the two, so I might just stick with npm entirely until these issues are sorted out for good.

**Comment by davidcalhoun** [comment]
@alcmoraes Thanks, that seems to fix the issue I was having with the Yarn cache directory:

```error An unexpected error occurred: "EACCES: permission denied, mkdir '/Users/davidcalhoun/Library/Caches/Yarn/npm-whatwg-fetch-2.0.1-078b9461bbe91cea73cbce8bb122a05f9e92b772'".```

But now I'm seeing a new issue:
```Error: EACCES: permission denied, open '/Users/davidcalhoun/.yarnrc'```

**Comment by bestander** [comment]
@davidcalhoun, probably your cache folder was created by a su user.
Try removing /Users/davidcalhoun/Library/Caches/Yarn

**Comment by bestander** [comment]
Can't reproduce this issue anymore, following the steps https://github.com/yarnpkg/yarn/issues/872#issuecomment-256284723.

Please open a new one with repro steps if you see it

**Comment by iamkdev** [comment]
error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/user/path/to/app/node_modules/escodegen/node_modules/estraverse'

**Comment by SaidTayebi** [comment]
yarn EACCES: permission denied

**Comment by Jahans3** [comment]
This worked for me:

    sudo chmod -R 777 ~/Documents/path/to/project

**Comment by dsisodia30** [comment]
Upgrade yarn

**Comment by alcmoraes** [comment]
I've solved the issue by running `ls -lah` into my home folder. Noticed only `.config` folder was owned by `root` user.  So..

`sudo chown -R <your-username> <home-dir>/.config`

Problem gone.

**Comment by Imtayaz** [comment]
sudo chown -R $(whoami) /usr/local/share/man/man8

this will upgrade yarn

**Comment by WeihanLi** [comment]
error in my docker container

```
error An unexpected error occurred: "EACCES: permission denied, unlink '/app/node_modules/.yarn-integrity'"
```

**Comment by ftred001** [comment]
> I fixed this by removing my `node_modules` directory and running yarn install again.

This was the solution for me :)

**Comment by youyiqin** [comment]
Holy shit!

> I fixed this by removing my node_modules directory and running yarn install again.

It is works!Thanks!

**Comment by WeihanLi** [comment]
> error in my docker container
> 
> ```
> error An unexpected error occurred: "EACCES: permission denied, unlink '/app/node_modules/.yarn-integrity'"
> ```

I've fixed this error by specific the permission to the user, for example:
``` bash
COPY --chown=pptruser:pptruser ./src .
```

**Comment by Ayesha-Mulla** [comment]
if you are using terminal,
login with local user, and then you can run this script

sudo chown -R $USER <directory_project>

**Comment by ElijahLynn** [comment]
I was getting `"Error: EACCES: permission denied, open '/var/www/.yarnrc'"`, when there was no .yarnrc file there at all. I added the `--verbose` flag and it was in fact trying to load it, the parent directory perms did not allow for even `ls` ing `/var/www`. I created that file with the right perms and it worked fine after that.

**Comment by simkessy** [comment]
I still get this issue. Removing node fixes it but it keeps coming back

**Comment by yuriwc** [comment]
> I fixed this by removing my `node_modules` directory and running yarn install again.

Perfect solution for me
