### ISSUE TITLE
Fix yarn timeout issue using lerna bootstrap

### ISSUE THREAD

**Issue by sunakshitejwani** [yarnpkg/yarn#8739]
Hi 
I am trying to resolve yarn timeout errors, to which I found this solution : `yarn install --network-timeout 1000000`
How to use the similar timeout flag for `lerna bootstrap`  command? 

Yarn version : 1.22.10 
lerna version: 4.0.0

**Comment by merceyz** [comment]
This isn't the issue tracker for Lerna
