### ISSUE TITLE
Lerna bootstrap command doesn't generate yarn.lock file 

### ISSUE THREAD

**Issue by sunakshitejwani** [yarnpkg/yarn#8740]
Hi 

I am using yarn with lerna to manage multi module Javascript project. 
However it is NOT generating **yarn.lock** for each sub-project while running `lerna bootstrap` command
It is necessary step to generate yarn.lock file in Jenkins pipeline for OSS scan report. 
How to fix this? 

Current yarn version : 1.22.10
lerna version: 4.0.0

**Comment by merceyz** [comment]
This isn't the issue tracker for Lerna
