### ISSUE TITLE
Windows .msi installer not included in most recent 2 releases, 1.22.17 and 1.22.16

### ISSUE THREAD

**Issue by minaelee** [yarnpkg/yarn#8750]
The 1.22.16 and 1.22.17 lack an .msi file. The last release where an .msi was included was 1.22.15.

If this change is intentional, to no longer include the .msi, then the installer page needs to be updated. 

Right now, the installer page has this download link:
![image](https://user-images.githubusercontent.com/4936954/146320901-7be4cc7a-6f9e-4c76-99fb-4ebdd2749349.png)
When the Download Installer button is clicked, it tries to go to https://github.com/yarnpkg/yarn/releases/download/v1.22.17/yarn-1.22.17.msi which leads to a 404 page not found. 

Either the releases need to include the .msi again, or the link should be removed/changed.

**Comment by halex2005** [comment]
I'm here after `yarn install` showed me 

```
warning Your current version of Yarn is out of date. The latest version is "1.22.17", while you're on "1.22.5".
info To upgrade, download the latest installer at "https://yarnpkg.com/latest.msi".
```

So sad that msi is missing and links are broken

**Comment by amjedomar** [comment]
Any updates? I'm facing the same problem.

**Comment by minaelee** [comment]
FYI to those who are looking for the latest available .msi - the last release that had one was 1.22.15 and you can get it here: https://github.com/yarnpkg/yarn/releases/download/v1.22.15/yarn-1.22.15.msi

**Comment by Daniel15** [comment]
v1.22.22 has a Windows installer.
