### ISSUE TITLE
[Bug?]: Deployment Failed

### ISSUE THREAD

**Issue by buddywhitman** [yarnpkg/yarn#8756]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I had only edited some static text in my next.js site and after committing the changes, when I tried to deploy the app through Vercel, the deployment failed.

This is the entire log:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/39520468/146784140-4a781b1b-2be7-4c36-8ac7-cca133606c24.png">

The error codes of interest are highlighted below:
error An unexpected error occurred: "https://registry.yarnpkg.com/tslib/-/tslib-2.1.0.tgz: Request failed \"503 Service Unavailable\"".
Error: Command "yarn install" exited with 1

Kindly bear with me since I am new to development with yarn. Also, I need to fix this ASAP since this is a critical project.
Thanks a ton in advance!

### To reproduce

(post changes in static independent & irrelevant text)

git commit
yarn install v1.22.17

### Environment

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 997.64 MB / 7.88 GB
  Binaries:
    Node: 17.3.0 - C:\Program Files\nodejs\node.EXE      
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Maven: 3.6.2 - D:\opt\apache-maven-3.6.2\bin\mvn.CMD
    pip3: 20.2.4 - D:\Anaconda\Scripts\pip3.EXE
  Utilities:
    Git: 2.23.0.
    Ninja: 1.10.0.
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    VSCode: 1.63.2 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Java: 14.0.2
    Perl: 5.20.0 - C:\Perl64\bin\perl.EXE
    Python: 3.8.5
    Python3: 3.8.10
  Databases:
    SQLite: 3.33.0 - D:\Anaconda\Library\bin\sqlite3.EXE
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.18362.1533.0)
```

### Additional context

The only changes I committed:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/39520468/146785686-cf67fe47-fa6b-400f-9c43-acda4dd44565.png">

Complete deployment log:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/39520468/146785775-19d94026-d753-49ee-a3b8-af56207d0bf3.png">

**Comment by arcanis** [comment]
Servers errors (like 503) [aren't Yarn's responsibility](https://yarnpkg.com/getting-started/qa#queries-to-registryyarnpkgcom-return-a-404500-is-it-down).

**Comment by buddywhitman** [comment]
> Servers errors (like 503) [aren't actionable by our team](https://yarnpkg.com/getting-started/qa#queries-to-registryyarnpkgcom-return-a-404500-is-it-down).

Thanks! got it resolved automatically later..
