### ISSUE TITLE
v1.23.0-20211220.1904?

### ISSUE THREAD

**Issue by mwoodpatrick** [yarnpkg/yarn#8772]
I'm running on wsl-2 with nvm and using node v16.13.1 and when I run "yarn -v" I get:

1.23.0-20211220.1904

but when I do 'which yarn' I get:

/home/mwoodpatrick/.nvm/versions/node/v16.13.1/bin/yarn

If I look at 

/home/mwoodpatrick/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/package.json

it shows:

"version": "1.22.17",

How do I figure out where this weird version 1.23.0-20211220.1904 is coming from? Is there a better place to ask this question?

**Comment by merceyz** [comment]
You most likely ran `yarn set version ...` which updated `yarn-path` in `~/.yarnrc` to point to that version

https://classic.yarnpkg.com/en/docs/cli/policies
https://classic.yarnpkg.com/en/docs/yarnrc#toc-yarn-path

**Comment by mwoodpatrick** [comment]
I was running yarn 3.1.1 and for some code I needed to use yarn 1 and so had done

yarn set version classic 

and got this strange version and was expecting tp get the latest stable version of yarn 1 e.g. v1.22.17
