### ISSUE TITLE
[Bug] Yarn hangs at last package

### ISSUE THREAD

**Issue by ShomaGujjar** [yarnpkg/yarn#8775]
I am trying to install @types/react-icons and it always hangs on the last package. Can you please advice.I am using the latest react and yarn.
![yarn-hang](https://user-images.githubusercontent.com/6553457/151546065-078e2e24-a2eb-4ca5-814a-e9d2cc115301.png)

**Comment by U-4-E-A** [comment]
I believe this is a timeout issue while installing a large package.

This may help - https://stackoverflow.com/questions/51508364/yarn-there-appears-to-be-trouble-with-your-network-connection-retrying

**Comment by RDIL** [comment]
Yeah, you very likely have a big package as a dependency that your internet connection is struggling with.  Closing as this isn't really Yarn's fault.
