### ISSUE TITLE
Decrease `yarn` size (21 MB, 171 dependency)?

### ISSUE THREAD

**Issue by nodkz** [yarnpkg/yarn#878]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
21 MB, 171 dependency

**What is the expected behavior?**
I don't know cool or not that package manager has so many dependencies.

----

Maybe bundle dependencies with tree-shaking?

PS. Trying to add `yarn` to official `node` docker image:
https://github.com/nodejs/docker-node/issues/243

**Comment by kittens** [comment]
This is easier said than done. We have a 2MB single JavaScript script you can use if you want, that's available [here](https://github.com/yarnpkg/yarn/releases/tag/v0.15.0) from the releases page. All the dependencies we use are critical or would be worse if we wrote them ourselves. This issue isn't very specific so I'm going to close it.

**Comment by rjmunro** [comment]
The 2Mb single file solution seems to be some sort of bundle - exactly what this bug is asking for.

**Comment by nodkz** [comment]
One problem stays: 
how to provide CLI from this bundled js in the docker container?

**Comment by rjmunro** [comment]
It would be good if that download had a shebang line at the top, something like:

    #!/usr/bin/env node

Then you could just copy it to /usr/local/bin or a similar folder. But in the absense of that add a file called yarn with content like:

    #!/bin/bash
    node path/to/yarn "$@"

**Comment by Daniel15** [comment]
We do include a number of files that aren't needed though. I want to clean up what we can at some point, and avoid including things like example files and readmes for third-party modules in our tarballs / installers. Filed #908 for that.
