### ISSUE TITLE
--registry argument

### ISSUE THREAD

**Issue by kittens** [yarnpkg/yarn#879]

**Comment by wyze** [comment]
Duplicate of #792.

**Comment by addyosmani** [comment]
@kittens happy to help with closing issues if my privs could be bumped.. 😄 This is indeed a dupe. I'd also support opting for `publishConfig` instead of the arg, but there may be good reasons to support this otherwise.

**Comment by wyze** [comment]
I have some power now to close this as a duplicate of #792.
