### ISSUE TITLE
yarn corepack can't setting proxy

### ISSUE THREAD

**Issue by jjasoncool** [yarnpkg/yarn#8790]
使用 corepack enable 的 yarn 似乎無法正確設定 proxy
需要使用 npm install --global yarn 才可以正常設定
![2022-02-23_nodejs_network](https://user-images.githubusercontent.com/24731867/156119190-1b7e19e9-9000-4e7c-b921-31f9d1996908.png)

**Comment by merceyz** [comment]
See https://github.com/nodejs/corepack/issues/67

**Comment by jjasoncool** [comment]
> See [nodejs/corepack#67](https://github.com/nodejs/corepack/issues/67)

Thank you.
