### ISSUE TITLE
yarn create next-app not working

### ISSUE THREAD

**Issue by FeelipePM** [yarnpkg/yarn#8804]
why this command not working? 
is a problem in yarn 1x
my version is v1.22.17, if  anyone can help me!

```bash
❯ yarn create next-app
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-next-app@12.1.0" with binaries:
      - create-next-app
error Cannot create "/usr/local/bin/create-next-app" due to insufficient permissions.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by merceyz** [comment]
As the error states, you don't have access to create the required files.

**Comment by RudrakshaBillore1** [comment]
In Ubuntu you must use  " sudo yarn create next-app " Command

**Comment by alecpetrosky** [comment]
A bag you pardon, but why does create-next-app require root permission to create an app inside directory owned by non-privileged user?

**Comment by seshaljain** [comment]
On Fedora 36, sudo yarn create ... causes all files in the created project to be owned by root. Modifying these files requires root permissions.

**Comment by alecpetrosky** [comment]
@seshaljain you're absolutely right. But my question was, why does this command need to be run with `sudo` if I just want to create the base project in my `~/` dir?

**Comment by xpanvictor** [comment]
same issue in fedora 36
i wont suggest using sudo as the project will need admin for anything you do like installing packages, deleting files...
instead, you can use sudo to install create-next-app
`sudo yarn global add create-next-app `
then use the global package
`create-next-app --typescript`
try to avoid this if possible though as you're installing the binary and it wont be using an updated version unless you update it
