### ISSUE TITLE
[Bug?]:  on Install GPG signature for this Yarn release is invalid! 

### ISSUE THREAD

**Issue by socraticDevBlog** [yarnpkg/yarn#8806]
### Describe the bug

Failure during install process 
via this command: 
`curl -o- -L https://yarnpkg.com/install.sh | bash`

We have been running this job in our pipeline multiple times every day for many weeks.

It just stopped working today with GPG error.

it had been working up until 2022-03-16 18:50 UTC

but next pipeline ran at 2022-03-16 19:12 UTC and it errorred

We think the issue is on your side. 

Kindly let us know !!!

```
> Verifying integrity...
gpg: key 1646B01B86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Mar 16 18:39:25 2022 UTC
gpg:                using RSA key 6D98490C6F1ACDDD448E45954F77679369475BAA
gpg: BAD signature from "Yarn Packaging <yarn@dan.cx>" [unknown]
> GPG signature for this Yarn release is invalid! This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.

```

### To reproduce

`curl -o- -L https://yarnpkg.com/install.sh | bash`

### Environment

```shell
yarn is yet to be installed :)
```

**Comment by merceyz** [comment]
Duplicate of https://github.com/yarnpkg/yarn/issues/8805
