### ISSUE TITLE
[Bug?]: Duplicated installing cause a module has multiple instance and they are not interoperable.

### ISSUE THREAD

**Issue by littleprincewdk** [yarnpkg/yarn#8807]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

This has a lib called `my-sun-core`, it depends on `my-sun-a` and `my-sub-b`,  then `my-sun-a` and `my-sun-b` depend on `my-sun-c`. `my-sun-c` just export an array：
<img width="300" src="https://user-images.githubusercontent.com/20736912/158776835-b4b37c6f-b8da-4ffc-9c65-074e57062673.png" />
`my-sun-a` and `my-sub-b` separately import `my-sun-c `, print `c` and push `1`:
<img width="300" src="https://user-images.githubusercontent.com/20736912/158798469-13861b5d-f4a9-45f7-a8fe-40e78e9bb0d7.png" />
<img width="300" src="https://user-images.githubusercontent.com/20736912/158777325-7e6d1f67-bb27-475b-9250-44034dbf7086.png" />
`my-sun-core` just only import `my-sun-a` and `my-sun-b​`:
<img width="300" src="https://user-images.githubusercontent.com/20736912/158777895-863ed02e-db48-4bee-b56b-1681de239e23.png" />
Normally running index.js will output this:
<img width="300" src="https://user-images.githubusercontent.com/20736912/158777913-0227d641-2d8f-459b-bd64-73d453801cf7.png" />
Now release my-sun-core@0.3.0, version is dependent on:
```
my-sun-core@0.3.0
my-sun-a@0.3.0
my-sun-b@0.3.0
my-sun-c@0.1.0 // the real scene is to use lerna management, so the version has not changed because there is no change.
```
also release a my-sun-core@0.2.0-alpha.1, the version is dependent on:
```
my-sun-core@0.2.0-alpha.1
my-sun-a@0.2.0-alpha.1
my-sun-b@0.2.0-alpha.1
my-sun-c@0.2.0-alpha.1
```
Then install these two versions through npm alias in `use-my-sun`:
<img width="300" src="https://user-images.githubusercontent.com/20736912/158779124-84155315-97c6-4c63-85ed-be59d30926a9.png" />
The actual operation result is as follows:
<img width="300" src="https://user-images.githubusercontent.com/20736912/158779256-d60ca755-270e-4af7-80bb-fd809f3012d5.png" />
<img width="300" src="https://user-images.githubusercontent.com/20736912/158779286-23105ba8-3fc4-45bb-a1a8-9bfff9c47888.png" />
`my-sun-core-alpha` output is abnormal because its dependent `my-sun-a` and `my-sun-b` have each installed `my-sun-c`, and two module instances are not interoperable.
Here is the node_modules structrue:
```
node_modules
  my-sun-a@0.2.0-alpha.1
    node_modules
       my-sun-c@0.2.0-alpha.1
  my-sun-b@0.2.0-alpha.1
    node_modules
       my-sun-c@0.2.0-alpha.1
  my-sun-c@0.1.0
  my-sun-core@0.3.0
    node_modules
       my-sun-a@0.3.0
       my-sun-b@0.3.0
  my-sun-core-alpha@0.2.0-alpha.1
```
why `my-sun-c@0.2.0-alpha.1` does not hoist？ it's because there is `my-sun-c@0.1.0` already outside。

If the structure is like this, there should be no problem： 
```
node_modules
  my-sun-core@0.3.0
    node_modules
       my-sun-a@0.3.0
       my-sun-b@0.3.0
       my-sun-c@0.1.0
  my-sun-core-alpha@0.2.0-alpha.1
    node_modules
       my-sun-a@0.2.0-alpha.1
       my-sun-b@0.2.0-alpha.1
       my-sun-c@0.2.0-alpha.1
```
What should I do？😘

### To reproduce

1. open [use-my-sun.zip](https://github.com/yarnpkg/berry/files/8283441/use-my-sun.zip) 
2. run `yarn`
3. run `node index.js`
4. uncomment `// require("my-sun-core-alpha");` and run `node index.js`

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
  npmPackages:
    jest: 26.6.3 => 26.6.3
```

**Comment by merceyz** [comment]
Testing with Yarn 3.2.0 I see the same output from both modules
```sh
$ node -e "require('my-sun-core')"
a []
b [ 1 ]

$ node -e "require('my-sun-core-alpha')"
a []
b [ 1 ]
```

**Comment by littleprincewdk** [comment]
Thanks, this solved my problem。
