### ISSUE TITLE
Yarn 1.22.18 is not on npm, breaking flow with Volta with no way to get rid of out of date warning 

### ISSUE THREAD

**Issue by synaptiko** [yarnpkg/yarn#8808]
Recently I started having:
> warning Your current version of Yarn is out of date. The latest version is "1.22.18", while you're on "1.22.17".
in my project where we use [`volta`](https://volta.sh/)

But when I upgrade version of `yarn` in volta's config, I'll get:
> Volta error: Could not download yarn@1.22.18
> from https://registry.npmjs.org/yarn/-/yarn-1.22.18.tgz
because `yarn`'s latest version on `npm` is 5 months old: https://www.npmjs.com/package/yarn/v/latest
![image](https://user-images.githubusercontent.com/1593280/159013141-3fde24e2-fdfa-41b0-bb40-1c7f5c25b251.png)

Some linux distributions are distributing version "1.22.18" already: https://archlinux.org/packages/community/any/yarn/ but this won't help if you use tools like `volta` which relies on `npm` for installations.

**Comment by NekR** [comment]
Just came here to report the same issue. I breaks development flow with JetBrains IDE if installed manually and not from npm.

**Comment by arcanis** [comment]
Can you try again? I manually pushed the 1.22.18

**Comment by o5** [comment]
It worked but now not :-/

```bash
yarn set version 1.22.18
error An unexpected error occurred: "Release not found: 1.22.18".
info If you think this is a bug, please open a bug report with the information provided in "/src/uep/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```

**Comment by arcanis** [comment]
That's super weird - the release clearly shows on WebArchive:
https://web.archive.org/web/20220415181438/https://github.com/yarnpkg/yarn/releases

And going to the direct link, it actually exists!
https://github.com/yarnpkg/yarn/releases/tag/v1.22.18

I have no idea why GitHub doesn't show it - cc @Daniel15, in case you have an idea? The problem also occured for the 1.22.17, back in https://github.com/yarnpkg/yarn/issues/8800

**Comment by arcanis** [comment]
I only clicked "Update release" on the release (without changing anything) and it re-appeared in the list ... 🤯
