### ISSUE TITLE
Yarn installs incorrect package with yarn install command

### ISSUE THREAD

**Issue by stetsonthree** [yarnpkg/yarn#8809]
My `package.json` includes `"esbuild-rails": "^1.0.3"` in the `dependencies`

However, when `yarn install` runs and I check the `node_modules` directory, I'm seeing the wrong package inside `node_modules/esbuild-rails`. I'm getting the files from `escape-html` instead.

From my `yarn.lock`:
```
esbuild-rails@^1.0.3:
  version "1.0.3"
  resolved "https://registry.yarnpkg.com/escape-html/-/escape-html-1.0.3.tgz#0258eae4d3d0c0974de1c169188ef0051d1d1988"
  integrity sha1-Aljq5NPQwJdN4cFpGI7wBR0dGYg=
```

I'm experiencing this issue on a local dev machine running v1.22.17 and a remote server running v1.22.15

esbuild-rails previously installed without issue. This only started to be an issue within the last 24 hours for me. So far, I have only witnessed esbuild-rails install the wrong package in node_modules.

I have removed my node_modules directory and run `yarn install` again, several times, and I continue to get the wrong package.

Packages mentioned:
https://yarnpkg.com/package/esbuild-rails
https://yarnpkg.com/package/escape-html

**Comment by merceyz** [comment]
That looks like the result of a merge conflict, remove the entry from the lockfile to have Yarn resolve it anew.

**Comment by stetsonthree** [comment]
Thank you for the response. Whether directly related to your suggested solution or not, I removed a few packages I no longer needed, and `yarn install` completed without errors.
