### ISSUE TITLE
error There are more than one workspace with name "maker"

### ISSUE THREAD

**Issue by unicardano** [yarnpkg/yarn#8820]
Sorry but this is something very strange about the current yarn version and the workspaces feature looks broken at least on current mac os versions.

Errors
Tried execute
```
yarn workspaces info

yarn workspaces v1.22.17

error There are more than one workspace with name "maker"

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
```

This project should work perfectly, it doesn't for no reason.

https://github.com/sushiswap/sushiswap-subgraph

**Comment by merceyz** [comment]
As the error says, you have two workspaces with the same name.
https://github.com/sushiswap/sushiswap-subgraph/blob/a10e0e93172040bbd0f501133e0daade9332fe46/subgraphs/maker/package.json#L2
https://github.com/sushiswap/sushiswap-subgraph/blob/a10e0e93172040bbd0f501133e0daade9332fe46/subgraphs/makerV2/package.json#L2
