### ISSUE TITLE
[Bug?]: Can't upgrade `expo-cli@5.4.3`

### ISSUE THREAD

**Issue by SohelIslamImran** [yarnpkg/yarn#8826]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Can't upgrade `expo-cli@5.4.3`

![image](https://user-images.githubusercontent.com/76745339/166121787-a56b36aa-3594-4637-9183-cb5bf7c1c3b8.png)

[yarn-error.log](https://github.com/yarnpkg/yarn/files/8597782/yarn-error.log)

### To reproduce

"dependencies": {
      "@expo/ngrok": "^4.1.0",
      "expo-cli": "5.3.1",
      "firebase-tools": "^10.6.0",
      "react-devtools": "^4.24.4",
      "yarn": "1.22.18"
    }

### Environment

```shell
Yarn version: 
  1.22.18

Node version: 
  16.14.2

Platform: 
  win32 x64
```

**Comment by RDIL** [comment]
Sounds as if expo-cli is currently in use.  Is this still an issue?
