### ISSUE TITLE
Yarn replaces "/" with %2f

### ISSUE THREAD

**Issue by Asd2812** [yarnpkg/yarn#8827]
I'm trying to run yarn install on a repo I have with private packages on npmjs. I set the registry to registry.npmjs.com (and removed the yarn.lock) but still nothing works. I keep getting

`An unexpected error occurred: "https://registry.npmjs.com/@company%2fpackage: Not found"`

My issue is in trying to understand why yarn uses %2f instead of a normal "/" since this is the latest issue I've run into. Other solutions found online didn't help (tried uninstalling & re-installing repo & yarn).

If anyone has any idea what's happening that would be great. Thanks

**Comment by bogdantica** [comment]
I have exactly the same issue! Is there any solution for this?
