### ISSUE TITLE
Package resolved to relying on unencrypted git protocol is now broken

### ISSUE THREAD

**Issue by fangpenlin** [yarnpkg/yarn#8833]
Just realized all my CI build pipeline with yarn are broken with error similar to this one:

![Screenshot 2022-05-15 170211](https://user-images.githubusercontent.com/201615/168500400-d9156216-3726-4f6a-8191-f041f5123c4a.png)

After looking into the issue, it appears that GitHub is dropping support for unauthenticated git protocol:

https://github.blog/2021-09-01-improving-git-protocol-security-github/

It says March 15, 2022 the support will be dropped, but I guess the real feature may be dropped today? As if there are many package resolved to install via git protocol, they are now all broken. Is there a way to force yarn to avoid resolving packages to use git protocol ?

**Comment by RDIL** [comment]
I'm going to close this as it appears to be just a breaking change on GitHub's end.
