### ISSUE TITLE
yarn v1.22.19 was not published on npm

### ISSUE THREAD

**Issue by hakimio** [yarnpkg/yarn#8834]
The script for publishing new version on npm failing? yarn is telling me to upgrade but the latest version [on npm](https://www.npmjs.com/package/yarn?activeTab=versions) is still 1.22.18.

**Comment by kj** [comment]
Any plans to resolve this or are we supposed to wait for the next release? 1.22.19 has been out for almost a month.

**Comment by hakimio** [comment]
@Daniel15 can you take a look?

**Comment by Daniel15** [comment]
It's nearly 1AM here but I'll take a look in the morning.
-- 
Regards,
Daniel Lo Nigro
https://d.sb[https://d.sb/]

Sent from my phone

Jun 7, 2022 12:37:58 AM Tomas Rimkus ***@***.***>:

**Comment by Daniel15** [comment]
Sorry for the delay - This should be published now :)

**Comment by larouxn** [comment]
Indeed, is available on [NPM](https://www.npmjs.com/package/yarn). Thanks @Daniel15!
<img width="1920" alt="Screen Shot 2022-06-08 at 10 48 12" src="https://user-images.githubusercontent.com/1557529/172513879-205c1e85-974c-4edb-a6e1-07eb3b458c86.png">
