### ISSUE TITLE
Usage Error: Failed to successfully resolve '1.22.19' to a valid yarn release

### ISSUE THREAD

**Issue by shervinchen** [yarnpkg/yarn#8839]
node version: v16.15.0

I install yarn by `corepack enable`, but default version of yarn is 1.22.15
I want to update my yarn version, so I run `corepack prepare yarn@1.22.19 --activate`
but it return `Usage Error: Failed to successfully resolve '1.22.19' to a valid yarn release`
How can i update it to the relatest version?

**Comment by Daniel15** [comment]
This should be fixed now.
