### ISSUE TITLE
`sudo yarn install` fails with error `Failed to replace env in config` in .npmrc

### ISSUE THREAD

**Issue by BhuwanBhaskar** [yarnpkg/yarn#8845]
Yarn version: 1.22.4
NPM Version: 6.4.1
Node Version: 12.13.0

If I do a simple `yarn install`,  yarn is able to replace env variable correctly and install private packages.
But if I do `sudo yarn install`, yarn complains about not being able to replace env variable used in `.npmrc`.

Please help

**Comment by RDIL** [comment]
You shouldn't run it under sudo, it just grants more permissions than it needs.  Closing as no reproduction or other details have been provided.
