### ISSUE TITLE
can't find "@types%2fnode" module on install

### ISSUE THREAD

**Issue by Nolbir01** [yarnpkg/yarn#8848]
Hello guys.

I get Received `malformed response from registry for "@types%2fnode". The registry may be down.` error when I run the `yarn add global @quasar/cli` command

![WX20220708-181305](https://user-images.githubusercontent.com/3325790/177972820-3844c171-e052-4800-b91d-3d0cf991754e.png)

**Comment by kiwimoe** [comment]
Hello
I'm unable to reproduce the error that you're currently facing
![image](https://user-images.githubusercontent.com/71683721/180505392-b4e3dd6a-1309-4554-9e5c-f17d7a94f262.png)
For me it installed correctly, however, it might be an issue with Windows Powershell, as `%2f` in an encoded text and decoded will be `/`. As a result it should be `@types/node` instead encoded `@types%2fnode`. Can you try with command prompt (cmd) on a local directory and see if it throws the same error or not.

**Comment by RDIL** [comment]
Looks to be a PS issue.
