### ISSUE TITLE
sudo apt update warning message

### ISSUE THREAD

**Issue by Overcraft90** [yarnpkg/yarn#8849]
Hi there,

I just got `Yarn` installed on 22.04 "Jammy Jellyfish" following one of the issues open in the GitHub repo. I'm currently running version `1.22.19`; however, for some weird reason I'm getting the following message when sunning `sudo apt update`. Please can you help me to resolve this?

> W: https://dl.yarnpkg.com/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

Then, once done I might plan to switch to `Yarn` 2.x according to my needs and future usage. Thanks in advance!

**Comment by RDIL** [comment]
How did you install Yarn?

**Comment by Overcraft90** [comment]
I'm not actually sure; however, I have to say the problem is fixed now. I routinely run the `yarn serve` command without any issue! I think we can close for now, thanks again.

**Comment by mvl22** [comment]
That will happen when using the following to install Yarn:

```
sudo apt-get install -y curl
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install -y yarn
```
