### ISSUE TITLE
bower_components deleted when installing node_modules

### ISSUE THREAD

**Issue by sb8244** [yarnpkg/yarn#885]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

When installing node_modules from yarn, with an existing bower_components directory (custom through .bowerrc), the bower_components directory is cleared.

When re-running yarn with already installed packages, nothing is deleted.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Have package.json and bower.json in same directory
2. .bowerrc

```
{
  "directory": "bower_components"
}
```

3. Populate bower with `bower install`
4. Run `yarn`
5. `node_modules` exists but `bower_components` is empty.

**What is the expected behavior?**

`bower_components` should not be touched, because it is installed correctly.

**Please mention your node.js, yarn and operating system version.**

```
➜ yarn --version
0.15.1
➜ node --version
v4.3.2
➜ sw_vers -productVersion
10.11.6
```

**Comment by alextreppass** [comment]
Suspect this is a dupe of #616

**Comment by sb8244** [comment]
Thanks
