### ISSUE TITLE
Use recommended storage locations for app and user data

### ISSUE THREAD

**Issue by danielniccoli** [yarnpkg/yarn#8853]
On Windows, Yarn is putting application data directly in the user profile at `$env:userprofile\.yarn`. This violates Microsoft recommendations for Windows operating systems and should be moved to the recommended locations.

![grafik](https://user-images.githubusercontent.com/2971735/179354012-92c1e0b4-5fb4-4a60-b6e8-87242a638e2c.png)

A selection of recommended storage locations are

- ApplicationData (roaming)
- LocalApplicationData (non-roaming e.g., Local/LocalLow)
- CommonApplicationData (non-roaming)
- CommonProgramFiles (non-roaming)

Source and details about recommended storage locations:  
https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-6.0

**Comment by merceyz** [comment]
This was implemented in v2, there the default location on Windows is
```
C:\Users\<name>\AppData\Local\Yarn\Berry
```
https://github.com/yarnpkg/berry/blob/5f0439a087b8463d97fb70c96dc6f983a91be512/packages/yarnpkg-core/sources/folderUtils.ts#L5-L8

**Comment by danielniccoli** [comment]
Oh, you're right. I was probably seeing old files and folders, so I cleaned them up in the process. Thanks and sorry for the inconvenience.
