### ISSUE TITLE
"EROFS: read-only file system, mkdir '/path'"

### ISSUE THREAD

**Issue by xiaolee55** [yarnpkg/yarn#8855]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/37341547/180354386-91491b85-9ea3-4052-b311-3005b2e2debb.png">

**Comment by kiwimoe** [comment]
Because you're executing `yarn` in root directory or other kind of area where node don't have permission to write there,

**Comment by robbybenta** [comment]
What are you doing?
