### ISSUE TITLE
Error: unexpected end of file at Zlib.zlibOnError [as onerror] (zlib.js:187:17)

### ISSUE THREAD

**Issue by CamaroSS844** [yarnpkg/yarn#8861]
upon creating a new react native app using expo init, i got a message saying that Somethimg went wrong installing JavaScript dependencies. when i checked the yarn error log i found this error.
i am new to react native so i have no idea what i should do to resolve this problem

**Comment by RDIL** [comment]
Please provide more details, e.g. a full log file.  Closing, as this issue currently doesn't have enough to troubleshoot with.
