### ISSUE TITLE
Yarn set version stable ERROR

### ISSUE THREAD

**Issue by Stiefel98** [yarnpkg/yarn#8865]
I am trying to migrate to Yarn 3. I currently have Yarn@1.22.19 and I want to set it to the latest stable build. However whenever I run Yarn set version stable, it returns an error saying no such file or directory found.
Here is the full log output:
$ yarn set version stable
Internal Error: ENOENT: no such file or directory, stat 'C:\Users\ajsti\.node\co
repack\yarn\3.2.2'
Error: ENOENT: no such file or directory, stat 'C:\Users\ajsti\.node\corepack\ya
rn\3.2.2'
error Command failed.
Exit code: 1
Command: C:\Users\ajsti\.nvm\versions\node\v18.7.0\bin\node.exe
Arguments: C:\Users\ajsti\.nvm\versions\node\v18.7.0\bin\node_modules\corepack\d
ist\corepack.js yarn@stable set version stable
Directory: C:\Users\ajsti
Output:

info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this
 command.

I'm unsure if it's because it is looking in a folder for 3.2.2. Because I'm on 1.22.19 so there wouldn't be a 3.2.2 folder even created until I update to that version, right?? Any suggestions would be greatly appreciated!

**Comment by fh-igd-mueller-roemer** [comment]
How did you resolve this? Running into a similar `ENOENT` error when trying corepack yarn on Windows (with nvm-windows). Disabling corepack and installing yarn via NPM works, but I would consider that a workaround, not a resolution

**Comment by abdes** [comment]
How did you solve this?

**Comment by Aryanrt** [comment]
Any solution?

**Comment by jakeuj** [comment]
```
❯ corepack prepare yarn@stable --activate
Preparing yarn@stable for immediate activation...
Internal Error: ENOENT: no such file or directory, stat 'C:\Users\Jake\AppData\Local\node\corepack\yarn\3.3.0'
Error: ENOENT: no such file or directory, stat 'C:\Users\Jake\AppData\Local\node\corepack\yarn\3.3.0'
```
