### ISSUE TITLE
Yarn Start - Usage Error: Couldn't find a script named "start".

### ISSUE THREAD

**Issue by elthombre** [yarnpkg/yarn#8867]
Installed yarn via corepack instructions. Version 3.2.2 running.

In my project, ran: yarn install, successfully. Attempted to run: yarn start, and it failed with the exception as noted.

**Comment by xtlmrfighting** [comment]
insert “npm install @babel/core @babel/preset-env”
then rewrite yarn start

**Comment by RDIL** [comment]
No reproduction or details provided.

**Comment by ArchanaSharma95** [comment]
I am having the same issue. I found below mentioned error inside terminal

```
Usage Error: Couldn't find a script named "start".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```
