### ISSUE TITLE
Dry run / preview mode?

### ISSUE THREAD

**Issue by glenjamin** [yarnpkg/yarn#887]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There's no way to see what yarn would do without having your node_modules folder modified. (as far as I can tell).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
s/expected/desired/

It would be nice if there was a way to halt the install/upgrade process after the lockfile has been generated, and then either only modify the lockfile, or spit it out on stdout.

This would allow the user to diff it against their existing lockfile and decide if they're happy to proceed with downloading and installing the packages.

The two concrete times I've wanted to do this are:
1. When first downloading yarn, to see if it would process my project successfully and get an idea of what versions it would choose (workaround was to temporarily rename `node_modules`)
2. When re-installing after patching in the optional-dependencies fix, I wanted to know if it would just add in the optionals, or if it would also modify some other versions.

**Please mention your node.js, yarn and operating system version.**
node 5.12, yarn 0.15.1, OS X 10.11.3

**Comment by samccone** [comment]
https://github.com/yarnpkg/rfcs

Mind opening here?

Thanks 😁

**Comment by glenjamin** [comment]
Yep, no probs - might be worth updating the issue template to nudge people there as well?

**Comment by frontsideair** [comment]
I also needed this today, but with a completely different use case. @glenjamin will you open an RFC or shall I? I may never have the time though, so go ahead if you do.

**Comment by glenjamin** [comment]
Go for it, looks like I forgot to do this!

**Comment by OnkelTem** [comment]
So?
