### ISSUE TITLE
update Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by rajacyber** [yarnpkg/yarn#8871]
"Error upgrading application Adobe Acrobat Reader DC - \nWARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else 

please anyone help me why im getting this error.

**Comment by merceyz** [comment]
Yarn has no control over `Adobe Acrobat Reader DC` and does not provide support for it.
