### ISSUE TITLE
Unable to install @mui/icons-material

### ISSUE THREAD

**Issue by moezguedri** [yarnpkg/yarn#8876]
I am using the latest version of node and yarn.
It is impossible to install @mui/icons-material.
I am having the same issue when I try with npm.
I am not behind a proxy.

[yarn-error.log](https://github.com/yarnpkg/yarn/files/9435975/yarn-error.log)
[yarn-error.log](https://github.com/yarnpkg/yarn/files/9435976/yarn-error.log)

**Comment by RDIL** [comment]
This is just a [generic request timeout](https://smallbusiness.chron.com/server-connection-timeout-mean-71381.html) - Yarn tried to fetch the package, but it couldn't be downloaded.  Likely, your internet connection is too slow or something like that.  MUI's material icons package is also a pretty big file, which is likely a factor.
