### ISSUE TITLE
Time to add a deprecation to the top of the README?

### ISSUE THREAD

**Issue by cc-ebay** [yarnpkg/yarn#8877]
@arcanis I see a lot of issues and PRs with no comments. 
I had a problem today with `yarn` but before I file an issue I want to ask: is `yarn` still maintained? 
If not maybe you should put a deprecation message at the top of the README and direct people to `npm`.
Thanks!

**Comment by softorangetech200** [comment]
> is yarn still maintained?

This is the v1.x Yarn codebase, which is not maintained. v2.x is actively maintained.

**Comment by arcanis** [comment]
We don't receive many PRs on this repo nowadays, but I've also updated the PR template to point people to the new repo.
