### ISSUE TITLE
yarn install => 401 unauthorized

### ISSUE THREAD

**Issue by ravi-chukka** [yarnpkg/yarn#8878]
While using "yarn install", got the following error,

"https://npm.pkg.github.com/download/@discoveryed/de-analytics/0.4.0/3b6828c09a478da75658c90cf6ec015ad7e68ad542d69588d5f22303572009a4: Request failed \"401 Unauthorized\""

**Comment by RDIL** [comment]
I believe you need to sign in to use the GitHub package registry.  Try ensuring you are authenticated properly.
