### ISSUE TITLE
Single JS file release has no shebang line

### ISSUE THREAD

**Issue by rjmunro** [yarnpkg/yarn#888]
Feature request:

**What is the current behavior?**

No shebang line (like `#!/usr/bin/env node`) is added to yarn-[version].js build, e.g. yarn-0.15.0.js from https://github.com/yarnpkg/yarn/releases

**What is the expected behavior?**

There should be a shebang line so that the file can be run directly from a terminal after setting appropriate permissions (e.g. `chmod +x yarn.js`).

This was inspired by #878 - it would enable a very minimal install for things like docker containers:

    curl https://github.com/yarnpkg/yarn/releases/download/v0.15.0/yarn-0.15.0.js > /usr/local/bin/yarn
    chmod +x /usr/local/bin/yarn

It would also be good if the file was available minified.

**Comment by Daniel15** [comment]
The bundle is built here: https://github.com/yarnpkg/yarn/blob/master/scripts/build-webpack.js. Would you like to try and add this and send a pull request? 😄 

>  it would enable a very minimal install for things like docker containers

There's an issue talking about Docker here: #749. I'd suggest using the Debian or CentOS package if possible in your environment, it's almost as easy as using the combined .js file.

> curl https://github.com/yarnpkg/yarn/releases/download/v0.15.0/yarn-0.15.0.js > /usr/local/bin/yarn
Please use `https://yarnpkg.com/downloads/0.15.0/yarn-0.15.0.js` as the URL.
