### ISSUE TITLE
error boxen@7.0.0: The engine "node" is incompatible with this module. Expected version ">=14.16". Got "12.22.12" error Found incompatible module

### ISSUE THREAD

**Issue by chiaweilee** [yarnpkg/yarn#8886]
```bash
yarn -v
1.13.0
yarn
error boxen@7.0.0: The engine "node" is incompatible with this module. Expected version ">=14.16". Got "12.22.12"
error Found incompatible module
```

Macbook Pro M1
Node version is indeed 12.22.12, and >=14.16 is incompatible with my company enviorment.
No Error Reported when using `npm install`

**Comment by RDIL** [comment]
Not an issue, just means that package wants a newer version of Node than you have.  Either upgrade Node, downgrade boxen, or find a different package.
