### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by Jsonen** [yarnpkg/yarn#8888]
**Which operating system are you using:**
MOS 12.4 系统

**Please describe the steps you took when trying to install Yarn and what went wrong:**
下载 year  的时候提示出错，但是已经下载了 ， 使用  yarn --version  又查不到  我应该害死操作问题

<img width="856" alt="image" src="https://user-images.githubusercontent.com/108827406/192076441-4366ec19-f6ff-4705-be35-c6e36654be99.png">

**Comment by merceyz** [comment]
That doesn't look like an issue with Yarn, we can't help with `brew` issues.
