### ISSUE TITLE
yarn dev not working

### ISSUE THREAD

**Issue by DumitrasAndrei** [yarnpkg/yarn#8915]
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\dumit\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js dev

PATH: 
  C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Wiimm\WIT;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\dumit\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\dumit\AppData\Local\Programs\Python\Python39\;C:\Users\dumit\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2\bin;;C:\Users\dumit\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Program Files\Wiimm\WIT;C:\Users\dumit\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\dumit\AppData\Roaming\npm

Yarn version: 
  1.22.19

Node version: 
  18.13.0

Platform: 
  win32 x64

Trace: 
  TypeError [ERR_INVALID_ARG_VALUE]: The property 'options.env['npm_package_description']' must be a string without null bytes. Received '#\x00 \x00s\x00t\x00u\x00d\x00b\x00a\x00s\x00e\x00-\x00b\x00a\x00c\x00k\x00e\x00n\x00d\x00\r\x00 \x00'
      at new NodeError (node:internal/errors:400:5)
      at validateArgumentNullCheck (node:child_process:968:11)
      at normalizeSpawnArguments (node:child_process:697:7)
      at Object.spawn (node:child_process:750:13)
      at C:\Users\dumit\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25732:24
      at new Promise (<anonymous>)
      at new F (C:\Users\dumit\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:5305:28)
      at C:\Users\dumit\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25729:12
      at run (C:\Users\dumit\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:43184:7)
      at BlockingQueue.maybePushConcurrencyQueue (C:\Users\dumit\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:43199:7)

npm manifest: 
  {
      "name": "studbase-backend",
      "packageManager": "yarn@3.2.4",
      "scripts": {
          "dev": "ts-node-dev ./src/index.ts",
          "build": "yarn tsc",
          "lint": "eslint . --fix"
      },
      "devDependencies": {
          "@tsconfig/node16": "^1.0.3",
          "@types/bcrypt": "^5.0.0",
          "@types/cookie-parser": "^1.4.3",
          "@types/cors": "^2.8.12",
          "@types/express": "^4.17.14",
          "@types/node": "^18.11.9",
          "ts-node": "^10.9.1",
          "ts-node-dev": "^2.0.0",
          "typescript": "^4.8.4"
      },
      "dependencies": {
          "@types/express-session": "^1.17.5",
          "@types/nodemailer": "^6.4.7",
          "@types/passport": "^1.0.11",
          "@types/passport-local": "^1.0.34",
          "bcrypt": "^5.1.0",
          "cookie-parser": "^1.4.6",
          "cors": "^2.8.5",
          "dotenv": "^16.0.3",
          "express": "^4.18.2",
          "express-session": "^1.17.3",
          "mongoose": "^6.7.2",
          "nodemailer": "^6.8.0",
          "passport": "^0.6.0",
          "passport-local": "^1.0.0"
      }
  }

**Comment by layerok** [comment]
I fixed this by providing description in my package.json
