### ISSUE TITLE
Certificate of https://classic.yarnpkg.com has expired

### ISSUE THREAD

**Issue by alfjesus** [yarnpkg/yarn#8923]
![image](https://user-images.githubusercontent.com/13332989/218318459-43115658-59c5-495f-9b35-8653d8d63c12.png)

**Comment by leonardorb** [comment]
Yes. All my builds on GitHub Actions are failing. 😱 
https://twitter.com/leonardorb/status/1624786984945299456

**Comment by arcanis** [comment]
It seems Let's Encrypt had a fluke that prevented Netlify from auto-renewing the certificate. I pressed retry and it seems to be fixed. No idea if we can do anything else 🤔

**Comment by leonardorb** [comment]
@arcanis thank you.
