### ISSUE TITLE
Cancelling Yarn command generates an exit error

### ISSUE THREAD

**Issue by lexman1958** [yarnpkg/yarn#8937]
I am running yarn in the VS Code Terminal Window and the version shows 1.22.19. The command i run is "yarn dev" in vuejs. This works fine. When i cancel the command, with cntrl-c, it exists the dev server with the message "error Command failed with exit code 1". 

Following the advise here, i tried "npm install -g yarn" with the intend to upgrade to yarn 2. The install seems to go thru but when i run the "yarn dev" it still show version 1.22.19 and error is still there.

Please advise.

![Screenshot_2](https://user-images.githubusercontent.com/127527088/228867897-13269cf0-528b-48b3-9373-8f86db1276a6.png)

**Comment by Haroenv** [comment]
That's normal. When you exit a program with control c, you're invoking an error (sigkill) in the program, so that means its last exit code is an error.
