### ISSUE TITLE
still not fixed: tmp directory filled by yarn (and not cleaned)

### ISSUE THREAD

**Issue by ticmaidev** [yarnpkg/yarn#8944]
this problem is not fixed in 1.22.19
what modern releases are you guys talking about? how do I upgrade to that 

> @jcruz97 No, because it's [already fixed](https://github.com/yarnpkg/yarn/issues/6685#issuecomment-503028465) in modern releases - upgrade and you won't have this problem anymore.

_Originally posted by @arcanis in https://github.com/yarnpkg/yarn/issues/6685#issuecomment-1499043486_

**Comment by ticmaidev** [comment]
I had to use:

> yarn set version stable

**Comment by jcruz97** [comment]
@ticmaidev he was talking about v2, makes sense afterwards but when you are not used to frontend stack it can be tricky to update yarn and packages.
