### ISSUE TITLE
React Native use case

### ISSUE THREAD

**Issue by jbrodriguez** [yarnpkg/yarn#895]
Just wondering what the workflow for a fresh React Native project would be.

Is it 

``` bash
react-native init AwesomeProject
cd AwesomeProject
rm -rf node_modules
yarn
```

?

**Comment by PaulBGD** [comment]
I'm assuming facebook will update their project creation tool to use yarn eventually.

**Comment by SamSaffron** [comment]
fwiw I did not have to do `rm -rf node_modules`

**Comment by busches** [comment]
@jbrodriguez @kittens this is not an issue for yarn and can be closed.

**Comment by wyze** [comment]
As of [v0.38.0](https://github.com/facebook/react-native/releases/tag/v0.38.0), React Native will use yarn when available.
