### ISSUE TITLE
Yarn crashes whenever there is a `.yarnrc.yml` that is not empty but does not set any YAML nodes

### ISSUE THREAD

**Issue by kalrish** [yarnpkg/yarn#8965]
# Issue

The [corresponding issue template][GitHub repository yarnpkg/yarn issue template bug_report] did not set a structure. I can edit this issue's description to match the [new repository's issue template for bug reports][GitHub repository yarnpkg/yarn issue template bug-report].

## Affected versions

I have run into this issue with version 1.22.19 of Yarn as [distributed by Arch Linux][Arch Linux package yarn] on version 20.2.0 of Node.js as [distributed by Arch Linux][Arch Linux package nodejs]:

```Shell
pacman --query --owns -- "$(which -- node)"
```
```
/usr/bin/node is owned by nodejs 20.2.0-1
```
```Shell
pacman --query --owns -- "$(which -- yarn)"
```
```
/usr/bin/yarn is owned by yarn 1.22.19-1
```

## Reproduction

Yarn runs fine when there is no `.yarnrc.yml`:

```Shell
ls -A
yarn --version
```
```
1.22.19
```

Yarn runs fine when there is an empty `.yarnrc.yml`:

```Shell
touch -- .yarnrc.yml
yarn --version
```
```
1.22.19
```

Yarn runs fine when there is a `.yarnrc.yml` with a single line feed (LF) character:

```Shell
echo > .yarnrc.yml
yarn --version
```
```
1.22.19
```

Yarn crashes when there is a `.yarnrc.yml` with two line feed (LF) characters:

```Shell
echo >> .yarnrc.yml
yarn --version
```
```
TypeError: Cannot read properties of null (reading 'yarnPath')
    at loadRcFile (/usr/lib/node_modules/yarn/lib/cli.js:56995:49)
    at /usr/lib/node_modules/yarn/lib/cli.js:56966:14
    at /usr/lib/node_modules/yarn/lib/cli.js:97395:14
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:97393:78)
    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:97407:10)
    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56965:74)
    at /usr/lib/node_modules/yarn/lib/cli.js:88756:56
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
```

Yarn crashes when there is a `.yarnrc.yml` with only a comment:

```Shell
echo '# foobar' > .yarnrc.yml
```
```Shell
yarn --version
```
```
TypeError: Cannot read properties of null (reading 'yarnPath')
    at loadRcFile (/usr/lib/node_modules/yarn/lib/cli.js:56995:49)
    at /usr/lib/node_modules/yarn/lib/cli.js:56966:14
    at /usr/lib/node_modules/yarn/lib/cli.js:97395:14
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:97393:78)
    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:97407:10)
    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56965:74)
    at /usr/lib/node_modules/yarn/lib/cli.js:88756:56
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
```

Yarn seems to crash whenever there is a `.yarnrc.yml` that is not empty but does not set any [nodes][YAML nodes].

I wrote a reproduction case for [Sherlock][] following the [guide][Yarn contributing guide Sherlock]:

```js repro
const fs = require("node:fs");

fs.writeFileSync(
    ".yarnrc.yml",
    "\n",
);

expect(
    yarn(
        "--version",
    ),
)
.resolves
.not
.toThrow(
)
;
```

## Contribution

I would like to propose a fix. Please let me know whether one is desired or this issue does not warrant an update to the otherwise frozen Yarn Classic.

[Arch Linux package nodejs]: https://archlinux.org/packages/extra/x86_64/nodejs/
[Arch Linux package yarn]: https://archlinux.org/packages/extra/any/yarn/
[GitHub repository yarnpkg/yarn issue template bug-report]: https://github.com/yarnpkg/berry/blob/839aabd1668f837c346504e62d1c71c1cbd89c22/.github/ISSUE_TEMPLATE/bug-report.yml
[GitHub repository yarnpkg/yarn issue template bug_report]: https://github.com/yarnpkg/yarn/blob/14bcd15a401e063c2130ab31568c80aeb914165f/.github/ISSUE_TEMPLATE/bug_report.md?plain=1
[Sherlock]: https://github.com/arcanis/sherlock
[YAML nodes]: https://yaml.org/spec/1.2.2/ext/glossary/#node
[Yarn contributing guide Sherlock]: https://yarnpkg.com/advanced/sherlock

**Comment by merceyz** [comment]
Fixed in #9009
