### ISSUE TITLE
Archive this repository please

### ISSUE THREAD

**Issue by landsman** [yarnpkg/yarn#8973]
> If you decide to stay on Yarn 1 regardless, please be aware that we don't plan to
  merge pull requests or release future versions of Classic unless it's to solve an
  critical vulnerability report (which is unlikely). By contrast, the 2.x line is very
  actively supported. 

Could you please flag this repository [as archived](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)? 🙏
The GitHub feature is dedicated to repositories like this one. 

It will make it clear for anyone who visits this repo for the first time.

**Comment by Daniel15** [comment]
It's possible that we'll still have to release security updates for Yarn v1, so I don't think it can be archived.
