### ISSUE TITLE
Getting @yarnpkg/parsers@3.0.0-rc.49: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by doregg** [yarnpkg/yarn#8975]
### Describe the bug

Start getting an error:
```
error @yarnpkg/parsers@3.0.0-rc.49: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "16.15.1"
error Found incompatible module.
```
when running `yarn global add lerna@^5.5.0`.
I realized that you pushed `3.0.0-rc.49` 2 hours ago. It worked before.

### To reproduce

```
yarn global add lerna@^5.5.0
```

### Environment

```shell
Github pipelines
Node 16.15.1
yarn 1.22.19
```

**Comment by lira1705** [comment]
Same problem happened after trying to do a clean install (no node-modules and yarn.lock). Keeping the yarn.lock version outdated kept things working.

**Comment by onemargaro** [comment]
Same problem happened to me as well, i did a clean docker-image with node:16-alpine and only works with v7+ lerna
```
/ # yarn add global lerna@6.6.2
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning lerna > libnpmaccess > npm-registry-fetch > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[2/4] Fetching packages...
error @yarnpkg/parsers@3.0.0-rc.49: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "16.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
/ # node -v
v16.20.0
```

**Comment by bryaningl3** [comment]
Until this gets fixed, maybe add the following to your package.json file:

```json
  "resolutions": {
    "@yarnpkg/parsers": "3.0.0-rc.48.1"
  }
```

**Comment by yanweibing** [comment]
> Until this gets fixed, maybe add the following to your package.json file:
> 
> ```json
>   "resolutions": {
>     "@yarnpkg/parsers": "3.0.0-rc.48.1"
>   }
> ```

niu bi

**Comment by divyesh-puri** [comment]
@doregg You able to figure this out?

**Comment by doregg** [comment]
@divyesh-puri, For now, our workaround is not to use `yarn global add`. 
We're waiting for the yarn team/contributors reference

**Comment by merceyz** [comment]
One of your dependencies depends on a version of `@yarnpkg/parsers` that doesn't support the version of Node.js you're using.
You can either upgrade your version of Node.js, use resolutions to force Yarn to install a version that does support your Node.js version, or report the issue to the relevant dependency.

Closing as this isn't a Yarn issue.

**Comment by zhfkt** [comment]
> `"resolutions": { "@yarnpkg/parsers": "3.0.0-rc.48.1" }`
> 
> After adding this, it's still breaking, it can't see the resolution i've put in my package.json file? Any help on how to force it?
> 
> error @yarnpkg/parsers@3.0.0-rc.49: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "14.21.3" error Found incompatible module.

Just paste the following in the yarn global package.json. Mine is `/usr/local/share/.config/yarn/global/package.json`. Pls run `yarn global dir` to check yours.

```json
{
  "resolutions": {
    "@yarnpkg/parsers": "3.0.0-rc.48.1"
  }
}


```

**Comment by asotog** [comment]
last month I have been many packages providers/vendors are not using semantic versioning the right way, this is braking change

**Comment by vinhnguyen0429** [comment]
> 

Thanks @zhfkt, that did the trick!!! I was adding it into my local package.json rather than my global package.json 

Thanks for your help

**Comment by RockyCott** [comment]
you can try running yarn install  --ignore-engines

**Comment by divyesh-puri** [comment]
What worked for me is

1. Adding `resolutions` to package.json
```
{
  "resolutions": {
    "@yarnpkg/parsers": "3.0.0-rc.48.1"
  }
}
```
2. Instead of doing `yarn global add json lerna@6.6.2` on dockerfile I changed it to `yarn global add json lerna@6.6.2 @yarnpkg/parsers@3.0.0-rc.48.1 --ignore-engines`

These changes worked for me

**Comment by JMuhire** [comment]
Upgrade node to node lts will fix the issue
