### ISSUE TITLE
Yarn install wrong package version from github

### ISSUE THREAD

**Issue by tanlucvo** [yarnpkg/yarn#8978]
This is my `yarn.lock` file, i install `react-native-navigation` ver `7.26.0` then it resolved version `7.37.0`
<img width="597" alt="image" src="https://github.com/yarnpkg/yarn/assets/57494001/0857c30f-166a-40d0-81ab-f62a2b03eea7">

**Comment by merceyz** [comment]
That's how caret ranges work, see https://github.com/npm/node-semver/tree/cce61804ba6f997225a1267135c06676fe0524d2#caret-ranges-123-025-004
