### ISSUE TITLE
yarn install building fresh packages waiting an hours. is it normal?

### ISSUE THREAD

**Issue by putuoka** [yarnpkg/yarn#8987]
yarn install 

![image](https://github.com/yarnpkg/yarn/assets/20880839/14a8f841-2683-42fb-ae20-341f6591c8a6)

**Comment by Sourabh20022002** [comment]
No, waiting for an hour for a "yarn install" to build fresh packages is not normal @putuoka  and likely indicates an issue that needs investigation.

**Comment by MikeNitsenko** [comment]
@putuoka were you able to resolve this?

**Comment by putuoka** [comment]
> @putuoka were you able to resolve this?

yes i finally use npm install instead of yarn

seem like yarn lock file problem not sure.
