### ISSUE TITLE
garbled output in CI tool

### ISSUE THREAD

**Issue by pdeva** [yarnpkg/yarn#899]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Garbled console output when run from TeamCity

**If the current behavior is a bug, please provide the steps to reproduce.**

Run 'yarn install' from Teamcity

**What is the expected behavior?**

Readable output

**Please mention your node.js, yarn and operating system version.**
Ubuntu 14
yarn 0.15.0

Details:

Screenshot explains all:
http://screencast.com/t/ufutpHiSm

Relevant Teamcity issue:
https://youtrack.jetbrains.com/issue/TW-47303

**Comment by Daniel15** [comment]
Thank you  for reporting this! This is the same issue as #728. Those characters are called "ANSI escape codes". They let you specify that text should be rendered in a different colour. However, we should only be using them when the output is  going to a TTY (such as a terminal). When a tool is using the output, we should not render them (unless you force it with `--color` or something similar).

In your TeamCity issue, you should mention that TeamCity should support ANSI escape codes :)

I'm going to close this out. Please follow #728 for updates. Thank you!
