### ISSUE TITLE
[Documentation] Grammatical typo in readme

### ISSUE THREAD

**Issue by palerdot** [yarnpkg/yarn#900]
Possible grammatical typo in the following line in README

`Fast: Yarn caches every package it downloads so it never needs to again.`

Not sure, what it implies by this line.

**Comment by Daniel15** [comment]
I think it means something like "Yarn caches every package it downloads, so you never need to download the same package again". Would you like to send a pull request to clarify it? 😄

**Comment by palerdot** [comment]
I think a pull request is already been given for this issue
https://github.com/ankurkaushal/yarn/commit/d2580ce201b290903c56d343d6517fc20578b1a3

**Comment by kittens** [comment]
Fixed by #957.
