### ISSUE TITLE
missing artifacts (.msi/.rpm/.deb/.asc files) for the most recent two releases (v1.22.20/v1.22.21)

### ISSUE THREAD

**Issue by chenrui333** [yarnpkg/yarn#9020]
👋 i saw there are two separate comments in the release notes about the missing files, but I did not see any tracking issue that I can subscribe to wrt triaging the issue. Thus creating one for me to follow on it. Thanks!

**Comment by MikeMcC399** [comment]
- Also asked in https://github.com/yarnpkg/yarn/issues/9035

**Comment by n-rodriguez** [comment]
ping @Daniel15

**Comment by Daniel15** [comment]
I'm not sure what's going on here and don't really work on Yarn any more. I can manually rebuild the files if needed. Do you need both versions or just the most recent one?

**Comment by Daniel15** [comment]
Closing in favour of #9035 - Let's track in there.
