### ISSUE TITLE
New Feature: `yarn licenses check`

### ISSUE THREAD

**Issue by hzoo** [yarnpkg/yarn#904]
👋  Ref https://twitter.com/rstacruz/status/786052262841896960

I was thinking could be another command, not sure the name (maybe `yarn licenses check`) which could warn/error when one of your dependencies uses licenses that you disallow.

I've implemented this in a separate package already on npm with https://github.com/behance/license-to-fail (check out the readme). It uses https://github.com/davglass/license-checker (does the same as `yarn licenses ls`).

Somehow you would need to able to provide a list of licenses you approve of (either extra parameters or using a config (.yarnrc, package.json, etc) - I just made a [config](https://github.com/behance/license-to-fail#config) file but I know a lot of people hate multiple of those.

Output can look the same as ls

```
yarn licenses v0.14.0
Disallowed Licenses
├─ a-pkg@1.0.3
│  ├─ License: not-allowed-license
│  └─ URL: git+https://github.com/pkg/here.git
```

Another important thing is whether to warn/error if the license cannot be determined (unknown): the options I made before were to add a list of exceptions or even pr the repo to update their license, etc.

It would be nice to know where each pkg comes from as well (like the `why` command)

**Comment by SethMichaelLarson** [comment]
Might be even better to do a license compatibility check. For instance if your project is licensed under MIT and you depend on a module licensed under Apache 2.0 it will warn you about license incompatibility. A good baseline might be this diagram: http://www.dwheeler.com/essays/floss-license-slide-image.png (source: http://www.dwheeler.com/essays/floss-license-slide.html)

**Comment by samccone** [comment]
https://github.com/yarnpkg/rfcs

Mind opening here?

Thanks 😁

**Comment by hzoo** [comment]
@samccone Ah ok - maybe we should update the issue template to link to https://github.com/yarnpkg/rfcs if a user is planning on asking for a feature?
