### ISSUE TITLE
Yarn audit suddenly stopped auditing packages

### ISSUE THREAD

**Issue by yoieh** [yarnpkg/yarn#9054]
This worked fine yesterday but today audit stopped working on any project I tried to audit...

`0 vulnerabilities found - Packages audited: 0`

![image](https://github.com/yarnpkg/yarn/assets/5743837/9546316c-50a1-4f36-b8ec-541d64410fc6)

### Recreate
yarn version: v1.22.21
node version: v20.11.1
The same results on Mac, and Ubuntu

- `yarn create vite`
- create with any template.
- `cd <TO-PROJECT>`
- `yarn install`
- `yarn audit`

Results in:
```
yarn audit v1.22.21
0 vulnerabilities found - Packages audited: 0
✨  Done in 0.47s.
```

### verbose log
`yarn audit --verbose`

[yarn-audit.log](https://github.com/yarnpkg/yarn/files/15161468/yarn-audit.log)

**Comment by mnikolaus** [comment]
The same issue with
yarn 1.22.19
node 18.17.1

**Comment by yoieh** [comment]
Might be something bigger... 
tested an audit with npm as well but no vulnerabilities are found when I have installed packages that should have a known vulnerability. 🤔

**Comment by yoieh** [comment]
My guess is that yarn audit uses on NPMs Security Audit just like `npm audit`.
There's something wrong with Security Audit even tho it's up and running according to the status page...
https://status.npmjs.org/
I created a support ticket at https://www.npmjs.com/support since this feels like a bigger issue :)

Leaving this open for others to see until it gets fixed.

**Comment by yoieh** [comment]
This has now been fixed by npm 😄
