### ISSUE TITLE
error Command "up" not found.

### ISSUE THREAD

**Issue by fahimahammed** [yarnpkg/yarn#9059]
### Bug description
I am encountering difficulties while attempting to upgrade Prisma ORM to version 5 from an earlier version. Following the documentation provided, I executed the command yarn up prisma@5 @prisma/client@5. However, I encountered an error stating "Command 'up' not found."

### How to reproduce

1. Navigate to a project using an earlier version of Prisma ORM.
2. Execute the command `yarn up prisma@5 @prisma/client@5`.

### Expected behavior
The command should upgrade both the prisma and @prisma/client packages to version 5 as documented, without throwing an error.

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 20..10.0

**Comment by fahimahammed** [comment]
Yarn doesn't use up for upgrades. Here's the correct approach using the standard yarn upgrade command: 

`yarn upgrade prisma @prisma/client`

**Comment by Daniel15** [comment]
Closing as question was answered above
