### ISSUE TITLE
Public JS API

### ISSUE THREAD

**Issue by maseh87** [yarnpkg/yarn#906]
I read on this [Facebook article](https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/) that Yarn exposes a public javascript API but the api.js file is currently empty. Is this feature in the works or is there documentation on how to get started using the api?

**Comment by j** [comment]
Yes, I too was about to create an issue regarding being able to programmatically use Yarn as part of my build tools.

**Comment by samccone** [comment]
https://github.com/yarnpkg/rfcs

Mind opening here? 

Thanks 😁

**Comment by FLGMwt** [comment]
Was the post referring to the `--json` argument?

```
> yarn
yarn install v0.15.1
success Already up-to-date.
Done in 0.15s.
```

```
> yarn --json
{"type":"success","data":"Already up-to-date."}
{"type":"finished","data":142}
```

**Comment by j** [comment]
@FLGMwt no, having the ability to do something like `import { install } from 'yarn/lib/api'` and use something in the matter of `await install(/* options etc */)`

**Comment by FLGMwt** [comment]
Ahhh, gotcha. Thought you meant more structured output for parsing as part of a build script. That makes more sense : )

**Comment by j** [comment]
Created RFC issue here: https://github.com/yarnpkg/rfcs/issues/6

**Comment by southpolesteve** [comment]
Anyone know what happened to this RFC? The link to https://github.com/yarnpkg/rfcs/issues/6 404's

**Comment by destroyerofbuilds** [comment]
@southpolesteve from their GitHub repo page (https://github.com/yarnpkg/rfcs/pulls) you can see that they disabled the issues feature.

Therefore all issues non 404.

**Comment by smitt04** [comment]
Since the other repo has no issues, i think this should be opened again, unless there is an API.

**Comment by Hendrixer** [comment]
@samccone can we re open this issue please?

**Comment by onbjerg** [comment]
Ping pong

**Comment by Inventicon** [comment]
Is there still no sign of a JS API?

**Comment by arcanis** [comment]
We recently split the lockfile parser in a new package, but we have not converged on any unified API yet.

**Comment by Inventicon** [comment]
Oh, bummer. 

I'll need to see if [this package](https://github.com/jonschlinkert/yarn-api) is a viable alternative for now.

**Comment by davidnagli** [comment]
Can someone please re-open this? I also really need a way to access yarn programmatically

**Comment by pacop** [comment]
Is some news right here?

**Comment by Inventicon** [comment]
Not unless someone wants to add the feature themselves and submit a PR.

<img width="722" alt="screen shot 2018-06-27 at 11 54 53 am" src="https://user-images.githubusercontent.com/13405600/41990885-f39542fc-7a00-11e8-8652-5dfd34582288.png">

**Comment by sarpik** [comment]
bump

**Comment by CanRau** [comment]
Yarn 2 core will come as Node API

**Comment by KaivnD** [comment]
> Yarn 2 core will come as Node API
> 
> Edit missed the Link https://github.com/yarnpkg/berry/blob/master/README.md#generic-packages
@CanRau 

No example provide, it's hard to understand how to use this api
