### ISSUE TITLE
CircleCI nightly job is broken

### ISSUE THREAD

**Issue by MikeMcC399** [yarnpkg/yarn#9069]
## Issue

The CircleCI job which is linked to by https://github.com/yarnpkg/yarn/blob/master/README.md runs nightly and fails nightly.

![image](https://github.com/yarnpkg/yarn/assets/66998419/515343a4-5b69-457b-87cd-69b9dc80372b)

See https://app.circleci.com/pipelines/github/yarnpkg/yarn

The badge also fails to show the status:

<a href="https://circleci.com/gh/yarnpkg/yarn"><img alt="Circle Status" src="https://circleci.com/gh/yarnpkg/yarn.svg?style=shield&circle-token=5f0a78473b0f440afb218bf2b82323cc6b3cb43f"></a>

```html
<a href="https://circleci.com/gh/yarnpkg/yarn"><img alt="Circle Status" src="https://circleci.com/gh/yarnpkg/yarn.svg?style=shield&circle-token=5f0a78473b0f440afb218bf2b82323cc6b3cb43f"></a>
```

Tests are failing using Docker images for Ubuntu versions which entered end-of-life several years ago. See https://endoflife.date/ubuntu for a convenient reference table:

| Image        | End-of-life |
| ------------ | ----------- |
| ubuntu:16.04 | Apr 2021    |
| ubuntu:14.04 | Apr 2019    |
| ubuntu:12.04 | Apr 2017    |

## Suggestion

Either disable the job and remove the badge OR update the job so it runs successfully and update the badge link, for example:

using Markdown syntax:

```markdown
[![Circle Status](https://circleci.com/gh/yarnpkg/yarn/tree/master.svg?style=svg)](https://circleci.com/gh/yarnpkg/yarn/tree/master)
```

[![Circle Status](https://circleci.com/gh/yarnpkg/yarn/tree/master.svg?style=svg)](https://circleci.com/gh/yarnpkg/yarn/tree/master)

**Comment by Daniel15** [comment]
Yarn v1 is not under active development so I'm not sure it even needs CI any more.

**Comment by MikeMcC399** [comment]
@Daniel15 

> Yarn v1 is not under active development so I'm not sure it even needs CI any more.

Do you have admin access to CircleCI to disable it?

**Comment by MikeMcC399** [comment]
@Daniel15 

> Yarn v1 is not under active development so I'm not sure it even needs CI any more.

If Yarn v1 Classic is an approved step to installing Yarn Modern, without relying on corepack, which the documentation describes as being [experimental](https://nodejs.org/docs/latest/api/corepack.html#corepack) and not suitable for production, why isn't Yarn v1 Classic being tested on current Node.js versions in a CI workflow?

**Comment by MikeMcC399** [comment]
The CircleCI job https://app.circleci.com/pipelines/github/yarnpkg/yarn continues to run nightly and fails nightly.

**Comment by MikeMcC399** [comment]
I'm abandoning this issue as it appears there is no intention to fix it.

**Comment by MikeMcC399** [comment]
- This issue was resolved by https://github.com/yarnpkg/yarn/pull/9219
