### ISSUE TITLE
Remove junk from dist

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#908]
There's a bunch of files in `dist` that we don't actually need, mainly readmes and examples from third-party modules. This unnecessarily bloats out the download size. I already had to clean up some of them to avoid lint errors in the Debian package (https://github.com/yarnpkg/yarn/blob/master/scripts/build-deb.sh#L45-L47) but we should try to clean up other stuff where possible.

**Comment by Daniel15** [comment]
There's ~2.3 MB of files in node_modules\rx\ts we probably don't need

**Comment by thejameskyle** [comment]
Here's a fun idea, you could use [`module-deps`](https://github.com/substack/module-deps) to find all the things that are actually necessary to run Yarn and only copy those files into `dist`

**Comment by Daniel15** [comment]
That's an interesting idea. We do have the standalone .js file built using Webpack, I wonder if we can get Webpack to output the dependency tree in a similar way.

We do need to keep the LICENSE files, so we should be sure to special-case those regardless of the approach we take 😄

**Comment by Daniel15** [comment]
Not needed now that we have a flat bundle (#3030)
