### ISSUE TITLE
yarn build  is very slow- more than 10 min (Usually takes only 2 min)

### ISSUE THREAD

**Issue by Sonubj7** [yarnpkg/yarn#9080]
yarn run build is taking way more time to build

Earlier on the same server it used to take only 2 min

May I know what would be the reason behind it.

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
yarn version -  v1.22.21
node version - v18.16.0
-->

**Comment by merceyz** [comment]
Closing as unactionable, `yarn run build` runs your `build` script in `package.json` which is out of our control.
