### ISSUE TITLE
[Bug?]: yarn add 出现问题info There appears to be trouble with your network connection. Retrying... error An unexpected error occurred: "https://registry.npmjs.org/react-refresh/-/react-refresh-0.14.2.tgz: connect ETIMEDOUT 104.16.3.35:443".

### ISSUE THREAD

**Issue by chaijindegerenboeke** [yarnpkg/yarn#9111]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.npmjs.org/react-refresh/-/react-refresh-0.14.2.tgz: connect ETIMEDOUT 104.16.3.35:443".
info If you think this is a bug, please open a bug report with the information provided in "E:\\xingmu\\开源简历项目\\kawa-resume\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### To reproduce

info There appears to be trouble with your network connection. Retrying...

### Environment

yarn: v1.22.19

**Comment by clemyan** [comment]
As noted in the error message, this is a problem in your network connection
