### ISSUE TITLE
Error when run Install: socket hang up

### ISSUE THREAD

**Issue by juangl** [yarnpkg/yarn#912]
**Do you want to request a *feature* or report a *bug*?** Report a bug

**What is the current behavior?**

`yarn install` fails randomly when is installing some package. I mean everytime that I run on the same `package.json` not allways fails in the same package but allways fails.

```
yarn install v0.15.1
info No lockfile found.
[1/4] Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
error https://registry.yarnpkg.com/redbox-react: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**If the current behavior is a bug, please provide the steps to reproduce.**

I intalled `yarn` with `npm i yarn --global`.

Run `yarn install` into a project with `package.json`. It's worth to say I have slow Internet connection.

**What is the expected behavior?**

Write `node_modules` with `package.json` deps.

**Please mention your node.js, yarn and operating system version.**

-  **yarn:** v0.15.1
- **node:** v6.7.0
- **Archlinux**

**Comment by AlicanC** [comment]
Your problem might be related with #668 or #746.

**Comment by juangl** [comment]
@AlicanC Thank you for response. I'll close this issue in favor of #746. 👍
