### ISSUE TITLE
Feature request: yarn doc [PACKAGE_FOO] - open default browser to package homepage/repo

### ISSUE THREAD

**Issue by jeffbski** [yarnpkg/yarn#913]
**Do you want to request a *feature* or report a *bug*?**
Feature request

yarn doc [PACKAGE_FOO]

It would be nice to have something like `npm doc PACKAGE_FOO` which opens a browser to the PACKAGE_FOO homepage (or github repo). **This is one of my favorite features in npm** so it would be nice to have it in yarn. **It saves a ton of time** eliminating the need to fumble around searching for the url to look up some docs for the package.

If you omit the package name and your current directory has a package.json then it will look for the homepage or repo of it.

It brings up the homepage in the default browser.

**Comment by AlicanC** [comment]
Does #897 suit your needs?

**Comment by jeffbski** [comment]
yes, I guess `home` is an alias for `doc` in npm so that is the same command. I'll close it since #897 is sufficient.
