### ISSUE TITLE
Unnecessary warning for built-in modules: React-Native redboxes if I remove the url dependency

### ISSUE THREAD

**Issue by danieldunderfelt** [yarnpkg/yarn#917]
I happily jumped on yarn when it released and have been a very happy user so far! The first project I yarned was a React-native project where I use the `url` module to resolve some url's, as you do. Yarn complained (warning-level) that `url` is a built-in module, so I uninstalled it. React-native did not like this turn of events so I had to reinstall `url` to make my app work again.

I get the rationale behind this warning, but in these cases where the build tool or environment (RN packager in this case) does not have the node.js built-in modules available by default it is unnecessary. I suggest we should trust the dev in this case and not complain if they depend on a built-in module.

Thoughts?

**Comment by ide** [comment]
Similarly we run into this warning when using modules like `url` and `querystring` in universal JS that runs on the server and client. In fact we intentionally don't want to use Node's built-in version since we want to ensure the same behavior in all environments.

**Comment by ide** [comment]
I sent a PR ^ that removes the warning, feel free to reject it though.
