### ISSUE TITLE
Installing in a Docker container on CircleCI fails with "error <package url>: EINVAL: invalid argument, chown '/root/.yarn-cache/<package>/package.json'"

### ISSUE THREAD

**Issue by ide** [yarnpkg/yarn#918]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Running `yarn` in a Docker container (ex: from a Dockerfile) on CircleCI prints errors like this:

```
yarn install v0.15.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/react/-/react-15.3.2.tgz: EINVAL: invalid argument, chown '/root/.yarn-cache/npm-react-15.3.2/package.json'
    at Error (native)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Make a circle.yml file that starts building a Docker image:

``` yml
machine:
  node:
    version: node
  services:
    - docker

dependencies:
  pre:
    - docker build .
```

In the Dockerfile, have some commands like:

```
RUN npm install -g yarn
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn
```

**What is the expected behavior?**
Yarn should successfully install the packages.

**Please mention your node.js, yarn and operating system version.**
Node 6.7.0 (on CircleCI) 
Yarn 0.15.1, 0.16.1
Ubuntu 14.04 (on CircleCI)

**Comment by ide** [comment]
The bug is potentially related to this issue with the `tar` package that also affects jspm: https://github.com/npm/node-tar/issues/39. If that's the case, this problem isn't directly due to Yarn's own code.

**Comment by artempartos** [comment]
Have this problem to

**Comment by daveisfera** [comment]
When I run the same Dockerfile on my local machine, it builds without issue but fails when doing the build on CircleCI. My local machine is using docker 1.12.1, build 6f9534c but CircleCI is using a much older version (1.8, I think), so maybe that's part of the problem.
I tried running with [1.9.1](https://discuss.circleci.com/t/docker-1-9-1-is-available/1009) and [1.10.0](https://discuss.circleci.com/t/docker-1-10-0-is-available-beta/2100) in CircleCI and the error still happened.

**Comment by jspiro** [comment]
Any ideas for workarounds?

**Comment by artempartos** [comment]
@jspiro this is working workaround for this, but you need a non-root user
https://github.com/artempartos/test_yarn

**Comment by guybedford** [comment]
Switching to tar-fs (https://github.com/jspm/npm/pull/141) may have helped in jspm here but I'm not sure. It did offer a good speed improvement though.

**Comment by andrewmclagan** [comment]
bumping this as there seems to be allot of others suffering the same issue

**Comment by revett** [comment]
+1

**Comment by paflopes** [comment]
The workaround mentioned by @artempartos works just fine for me. You just need to create a new user and do stuff inside its own folder on Docker.

**Comment by hobofan** [comment]
Duplicate of https://github.com/yarnpkg/yarn/issues/869.

**Comment by joeandaverde** [comment]
+1

**Comment by ide** [comment]
Closing this since I think https://github.com/yarnpkg/yarn/pull/1837 fixes it (untested).

**Comment by dangreen** [comment]
yarn@0.17.8 
```
error An unexpected error occurred: "https://registry.yarnpkg.com/react-dom/-/react-dom-15.4.1.tgz: EINVAL: invalid argument, chown '/root/.cache/yarn/npm-react-dom-15.4.1-d54c913261aaedb17adc20410d029dcc18a1344a/package.json'".
info If you think this is a bug, please open a bug report with the information provided in "/src/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c NODE_ENV=development yarn' returned a non-zero code: 1
```

**Comment by daveisfera** [comment]
I did a test on CircleCI using the nightly build of yarn and it resolved this issue. Is there a timeline for when 0.18.0 will be released so this fix will be available? Or if that won't be happening soon, then could it be backported to 0.17.x?

**Comment by andrewmclagan** [comment]
Plus one to that

**Comment by dave-nm** [comment]
I cherry picked the change and made a pull request against 0.17 branch. Is there something I can do to get this reviewed and merged for release?
