### ISSUE TITLE
Nexus support

### ISSUE THREAD

**Issue by jbadeau** [yarnpkg/yarn#924]
Do you plan to add support for maven/nexus? Would be really nice to be able to install webjars.

Is the API stable enough to build nexus support on?

**Comment by svieira** [comment]
Just an FYI for those who don't know, Nexus has support for hosting NPM repositories, so you can just point `yarn` at it using `.yarnrc`'s `registry` key. 

```
registry "http://location.of/nexus/npm/repository"
```

**Comment by samccone** [comment]
Mind opening this request here
https://github.com/yarnpkg/rfcs

So it can be discussed in the appropriate place. Thanks!
