### ISSUE TITLE
Can't use local packages in package.json scripts without relative paths

### ISSUE THREAD

**Issue by Skahrz** [yarnpkg/yarn#925]
**Bug**

**What is the current behavior?**

The local node_modules are not known when using scripts part of package.json. For example, if I try to run a command called gulp serve in npm start, I'm having the fact that gulp is not defined.
Same while trying to run JEST tests.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install gulp or jest locally, and try to make it run through a package.json script, without using relative path, just as npm make it.

**What is the expected behavior?**
Run the gulp or jest (or any dev tool) cli correctly without giving the relative path in cmds.

**Please mention your node.js, yarn and operating system version.**
Node V4.6.0, Yarn 0.15.1, OSX El Capitan

**Comment by shepmaster** [comment]
Perhaps fixed by #809?

**Comment by busches** [comment]
Fixed in `0.16.0` with #809, please retest.

**Comment by wyze** [comment]
Should be solved by #809. If it is still an issue, please reopen.
