### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by corysimmons** [yarnpkg/yarn#933]
![image](https://cloud.githubusercontent.com/assets/224636/19328253/cec16b40-90a0-11e6-8812-e52f04535888.png)

On behalf of rural folks w/o internet: Thank God for you...

[sorry for the Issue instead of Tweet. feel free to close]

**Comment by samccone** [comment]
:smile:

**Comment by corysimmons** [comment]
o ffs trollccone is here too?! 😭
