### ISSUE TITLE
link does not work for scoped packages (at least on Windows)

### ISSUE THREAD

**Issue by Ventajou** [yarnpkg/yarn#935]
Running node 6.8.0 on Windows 10, I'm working with a scoped package (`@rightscale/ui-charts`) and `yarn link` fails to register the package.

I fixed it by manually creating the scope's folder in `AppData\Local\Yarn\.link`

**Comment by vraa** [comment]
I face the same issue even in Mac.

**Comment by simenbrekken** [comment]
I can confirm @Ventajou's workaround also works on OSX (Sierra)

**Comment by kittens** [comment]
Fixed via #910.
