### ISSUE TITLE
yarn run - Running tasks in parallel or sequential

### ISSUE THREAD

**Issue by oieduardorabelo** [yarnpkg/yarn#941]
**Do you want to request a _feature_ or report a _bug_?**

_feature_

**What is the current behavior?**

Kind of native script for `yarn run-all`, to run tasks in parallel or sequential, similar to https://www.npmjs.com/package/npm-run-all

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

N/A

**Please mention your node.js, yarn and operating system version.**

N/A

**Comment by arxpoetica** [comment]
This can now be donw w/ npm-run-all by specifying the right env variable. See: https://github.com/mysticatea/npm-run-all/issues/68

**Comment by bestander** [comment]
Send an RFC.

**Comment by gsklee** [comment]
@oieduardorabelo The scope of such a feature request would mandate an [RFC](https://github.com/yarnpkg/rfcs) be submitted to enable further discussions. If you still feel like it, please feel free to head over there and submit this idea 😄

**Comment by nelson6e65** [comment]
Composer runs sequential scripts by using an array of multiple scripts.

The Composer behavior should be nice for Yarn.

**Comment by ivosabev** [comment]
What is the status of this proposal, it seems very common sense and often needed?

**Comment by P0oOOOo0YA** [comment]
Agreed this should be supported using yarn itself instead of hacks.
