### ISSUE TITLE
Installation Problem: "Error: watch ENOENT"

### ISSUE THREAD

**Issue by lorensr** [yarnpkg/yarn#943]
**Which operating system are you using:**
Latest macSierra

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Non-fatal error. Seems to have completed installation successfully after dismissing the error popup.

```
curl -o- -L https://yarnpkg.com/install.sh | bash
```

![image](https://cloud.githubusercontent.com/assets/251288/19330575/38e4982e-90ad-11e6-945e-6af7bf141ce8.png)

![image](https://cloud.githubusercontent.com/assets/251288/19330565/31964afe-90ad-11e6-9bcd-ac607a370943.png)

I clicked OK, then:

![image](https://cloud.githubusercontent.com/assets/251288/19330611/74fba794-90ad-11e6-8fb6-fc3ed9976e12.png)

**Comment by Daniel15** [comment]
To me this looks like an error in HyperTerm rather than an error in Yarn?

**Comment by JelaniThompson** [comment]
@lorensr Yeah this definitely seems like an issue with HyperTerm. Do you get an error when you use the default terminal as well?

**Comment by lorensr** [comment]
This now works for me in hyperterm:

```
macbook:test me$ rm -rf ~/.yarn
macbook:test me$ curl -o- -L https://yarnpkg.com/install.sh | bash
```
