### ISSUE TITLE
Make it easier to download a specific tarball version

### ISSUE THREAD

**Issue by pcj** [yarnpkg/yarn#956]
Excited about replacing broken npm, working on how this might integrate with Bazel.

Finding it ironic however that a package manager which purports determinism only offers download tarball `latest.tar.gz`.  The "download tarball" link should be to a directory of zip or tar.gz files that I can choose from.  Alternatively, publish to specific dist branches on github.

I may have missed it in the documentation.  If someone can point me to the correct location, I can PR to improve the docs.

**Comment by pcj** [comment]
Actually you are publishing artifacts at various releases (but not all). I can work with that.

**Comment by val-litvak** [comment]
@pcj I ran into the same problem, 4 years later :) where do you find the tarballs with specific versions? is it on this page: https://github.com/yarnpkg/yarn/releases ?
