### ISSUE TITLE
Optional emoji support

### ISSUE THREAD

**Issue by daltones** [yarnpkg/yarn#960]
**Do you want to request a *feature* or report a *bug*?**
*Feature* (maybe a *bug*, once one of the features in README is “More emojis. 🐈” 😸)

**What is the current behavior?**
Emojis only for OSX

**What is the expected behavior?**
Emojis for other platforms

**Please mention your node.js, yarn and operating system version.**
node.js: v6.7.0
yarn: v0.15.1
OS: Arch Linux

This is sort of related to #405 and 9f58576d127b34aadbb0c5b89e506faf503b3e34.

As discussed in #405, emojis on Powershell are bad. But it could be good someplace else…

I tried to force enable emojis here (Gnome Terminal on Arch Linux) and worked very well (although limited to monochrome). That's because I have the properly font and configuration.

![captura de tela de 2016-10-13 02-16-05](https://cloud.githubusercontent.com/assets/5603632/19337371/0ef8e748-90eb-11e6-902a-1f671f37a779.png)

So it would be nicer if we could optionally enable emojis. It could be even an environment variable `YARN_EMOJIS=1`.

**Comment by GRIM2D** [comment]
*Subjective opinion*

Emojis aren't meant to be used in professional development tools. Not all people like emojis. And I'm sure not only I am here, who dislikes image usages on CLI interface.

However, if this tool can handler emojis well, it should be optionally enabled (or disabled).

**Comment by daltones** [comment]
@GRIM2D yeah, your “(or disabled)” is implicitly inside my proposal of optional emojis.

I was testing yarn today and I was curious why my outputs didn't have emojis (as the documentation did). Then checking the code I found this:
```js
emoji: process.stdout.isTTY && process.platform === 'darwin'
```

That's a weird imposition. The issue isn't just a opinion about emojis.

**Comment by patrys** [comment]
@GRIM2D In this context emoji are used as equivalents of icons that your usual GUI would have. Just because the Unicode spec calls them emoji does not automatically make them unprofessional.

**Comment by GRIM2D** [comment]
@patrys 

> emoji does not automatically make them unprofessional

But, emojis are widely used while chatting. Also I do. And I'm not saying that using emojis make tools unprofessional. I meant CLI is mostly text-based. And mostly uses English as primary language. Even being Russian native-speaker, seeing cyrillic chars on my terminal is not comfortable for me. Same goes emojis.

At least, supporting emojis only on some platforms is bad idea. While macOS (formerly OS X) fully supports emojis, how about other platforms? 
And then there is a **big** issue with emojis - everyone interprets emojis differently. It affects designers, who draw every emoji. Just google "Same emoji different phone"

**Comment by patrys** [comment]
> everyone interprets emojis differently

Keep in mind we're talking about glyphs such as "magnifying glass" not "slightly frowning fisherman wearing a clown suit".

**Comment by mazameli** [comment]
Begun, the Emoji War, has.

**Comment by ifzm** [comment]
I think I need this feature.

**Comment by ifzm** [comment]
I think I need to support Windows.

**Comment by ZakariaRidouh** [comment]
Is there a way for chalk to render in the emojis being used along with the strings? Im not how it works.

/CC @sindresorhus

**Comment by kittens** [comment]
Resolved by #922.

**Comment by ahmad2smile** [comment]
The pull request you mentioned isn't for windows support... It's for disabling Emojis... What are you doing..

**Comment by daltones** [comment]
Yeah, #922 is not a solution for this issue. But maybe it's good for now. Yarn seems great but it has lots of important bugs to fix.

**Comment by ahmad2smile** [comment]
@daltones I understand that man ... I know its just a silly thing but He shouldn't have closed it without at least checking it first

**Comment by madrobby** [comment]
🍿

**Comment by luislobo** [comment]
@kittens It is not resolved by #922. That issue makes emojis optional. This issue actually is about bringing emojis to other platforms like Linux

**Comment by arutkowski00** [comment]
@kittens It is not resolved...

**Comment by tech4him1** [comment]
Why not just add an option?

**Comment by elyobo** [comment]
#922 is not a fix for this (and saying that it is suggests that @kittens has misunderstood this issue). It _is_ a useful fix (there are situations where you want to disable emojis), but this is about the opposite, situations where we want to _enable_ emojis where they're currently disabled.

I assume that support under other platforms is too difficult and they don't want to deal with the support issues that they'd have by enabling it (even behind something like a `--emoji` flag) for something that's a bit of a gimmick rather than a key feature.  Which is fair enough, but just say it if that's the case :)

**Comment by elyobo** [comment]
Above PR has been merged, so `--emoji` is now in master for non-Mac users :tada:

**Comment by luislobo** [comment]
@elyobo thank you! btw, I tried it but for some reason on my terminal I don't see any Emoji (Not that it takes my sleep away...). may be @daltones can share what he did to make Emojis work on his setup?
I'm using Ubuntu + i3

**Comment by ifzm** [comment]
@luislobo  Hello, I have encountered this problem, tried various methods, including the installation of color emoji can not be achieved. 
Can refer to http://www.omgubuntu.co.uk/2016/12/quickly-find-emoji-from-the-command-line
If you can succeed, hope to be able to share here.  :)

**Comment by elyobo** [comment]
@luislobo I suspect not wanting to deal with Linux users' emoji issues is why they didn't originally support this... I have no idea why your emojis aren't working, but I'm on Ubuntu too and mine are fine (although not in colour).

**Comment by ifzm** [comment]
@elyobo thanks ) 
I also encountered the same problem, can not show emoji on Linux, i would like to configure what or install special fonts?
OS：Ubuntu 16.04

@daltones I hope you can share under the Linux emoji font and related configuration，thank you very much )

**Comment by elyobo** [comment]
I'm also on 16.04, didn't do anything in particular to set it up.

**Comment by ifzm** [comment]
Thank you for your answer ) 
I  will find a good reason

**Comment by willnode** [comment]
@elyobo sorry if this has been discussed somewhere, but is there a way to always turn on emoji so that I don't have to type `--emoji` all the time?

**Comment by elyobo** [comment]
@willnode you can put a `--emoji true` into your [`.yarnrc` ](https://yarnpkg.com/lang/en/docs/yarnrc/) to set this as the default.

**Comment by willnode** [comment]
`yarn config set -- --emoji true`.

@elyobo It works! Thanks 😉.

**Comment by R-A-S** [comment]
`yarn config set -- --emoji false` also works. Thanks!😌

**Comment by elyobo** [comment]
Hey, hey, hey, why would you want to go and do that @R-A-S? :D

**Comment by R-A-S** [comment]
> 
> 
> Hey, hey, hey, why would you want to go and do that @R-A-S? :D

Just checked. And turned back "true" 😃

**Comment by Usamaliaquat123** [comment]
yarn config set -- --emoji true its worked thanks boii
