### ISSUE TITLE
Should I include yarn.lock in `files`?

### ISSUE THREAD

**Issue by tunnckoCore** [yarnpkg/yarn#963]
I think yes, but not very sure. I see you didn't include it in this repo, so.. ?

**AMAIZING JOB!**  Absolutely awesome and freakin fast. 6s even with `--force` for things/deps/devDeps/config that got me ~5mins with npm.

**Comment by Nicholaiii** [comment]
Except they did; https://github.com/yarnpkg/yarn/blob/master/yarn.lock
And you'd be ruining half the purpose of yarn if you didn't include it; Locking dependencies down with checksums.

**Comment by kittens** [comment]
Yarn doesn't respect lockfiles in transitive dependencies, this was a deliberate choice. Including it in npm releases wont do anything.

**Comment by tunnckoCore** [comment]
hmm... actually yea. make sense, got it thanks
