### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by angelfreedomv** [yarnpkg/yarn#964]
**Which operating system are you using:**

C:\Users\admin\yarn>yarn init
'yarn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by montogeek** [comment]
Try these solutions: https://github.com/yarnpkg/yarn/issues/601

**Comment by torifat** [comment]
Closing this issues. Feel free to ping back if you are still facing the problem.
