### ISSUE TITLE
Debian/Ubuntu repositories are not up to date

### ISSUE THREAD

**Issue by andi5** [yarnpkg/yarn#965]
Switched from `npm install -g yarn` to the recommended way to install yarn on Debian Testing (https://yarnpkg.com/en/docs/install).

Now I am running `yarn 0.15.0` from the archives, whereas before it was `yarn 0.15.1` from npmjs (https://www.npmjs.com/package/yarn).

As user I would expect both sources to be equivalent.

**Comment by kittens** [comment]
`0.15.1` was only pushed with a couple of changes that effected the npm and tarball releases.
