### ISSUE TITLE
yarn and lerna concurrency

### ISSUE THREAD

**Issue by joscha** [yarnpkg/yarn#966]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When using yarn with [lerna](https://github.com/lerna/lerna) the default concurrency is 4. Apparently yarn does not like concurrent installs, it fails with lots of errors in the cache:

```
error https://registry.npmjs.org/ak-editor-prosemirror/-/ak-editor-prosemirror-2.3.2.tgz: ENOENT: no such file or directory, utime '/root/.yarn-cache/npm-ak-editor-prosemirror-2.3.2/package.json'
    at Error (native)
[ak-editor-plugin-mentions] [2/4] Fetching packages...sed: write error
error ENOTEMPTY: directory not empty, rmdir '/root/.yarn-cache/npm-ak-editor-schema-2.4.0'
    at Error (native)
```

They are kinda random based on the current execution order but always happen: https://bitbucket.org/atlassian/atlaskit/addon/pipelines/home#!/results/%7Bd6caae96-c5a0-44b9-90cf-676525874320%7D

**If the current behavior is a bug, please provide the steps to reproduce.**

Use yarn in a lerna repo: `lerna exec -- yarn install`

**What is the expected behavior?**

That the install works.

If I do a `lerna exec --concurrency=1 -- yarn install` everything works.

**Please mention your node.js, yarn and operating system version.**
node 6.5.0
yarn 0.15.1
OSX 10.12

**Comment by singggum3b** [comment]
Same error when using yarn inside an alpine linux docker container

**Comment by mandragorn** [comment]
the root cause seems to be the same as #1275

**Comment by samccone** [comment]
1275 dup

**Comment by realyze** [comment]
@joscha I think you just solved the issue that made me scratch my head for the last 30 minutes, thanks! :-D
