### ISSUE TITLE
file dependency's relative path resolution is different than npm's

### ISSUE THREAD

**Issue by unbornchikken** [yarnpkg/yarn#973]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

I have a local module that is referenced by path in my application's package.json, e.g:

```
"co-main": "file:../CompanyModules/base/co-main/"
```

That `co-main` module depends on another company module that is reside an other directory. So in `co-main`'s package.json has this:

```
"co-utils": "file:../co-utils"
```

So, for the better understanding, the directory structure is the following:

```
C:
|- Dev
    |- MyCoolApplication (co-main referenced there)
    |- CompanyModules
        |- base
            |- co-main (here lies co-main that references utils with file:../co-utils)
            |- co-utils
```

`npm install` runs fine, but `yarn install` fails with the following:

```
error "C:\\Dev\\co-utils" doesn't exist.
```

So the bug is obvious, yarn resolves co-main's relative path by using the main package.json's path (C:\Dev\MyCoolApplication), but npm uses the submodule's root path for relative resolution (C:\Dev\CompanyModules\base\co-main).

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an environment described above
2. Run `npm install`, it gets succeeded
3. Run `yarn install`, it gets failed with the above error

**What is the expected behavior?**

yarn resolves relative paths exactly like npm does.

**Please mention your node.js, yarn and operating system version.**

Windows 10, Node.js 4.6.0, yarn 0.15.1, npm 3.10.5

**Comment by leecade** [comment]
any plan to support this key feature?

**Comment by ozsay** [comment]
https://github.com/yarnpkg/yarn/blob/ba5a20307992057c49663fce2569c01f59266701/src/resolvers/exotics/file-resolver.js#L26

seems like the file resolver always resolves relative to `cwd` when the module path is not absolute.

**Comment by hpurmann** [comment]
Solved by https://github.com/yarnpkg/yarn/pull/1498. I can confirm that this is fixed (macOS though).

**Comment by vance** [comment]
So before I open a new issue, posting this to see if it might be related. when I have a published module referencing a relative path that is not found, `"@something/my-thing":"file:.."` and that path does not contain the plugin, I get an error `error Couldn't find a package.json file in "/Users/mememe/dev/blah/packages"` even though i'm running it from `/Users/mememe/dev/blah/packages/my-app` and there is 100% a valid `package.json` in there. 

this is as of Yarn **0.22.0** 

that's the version we are locked at currently.
