### ISSUE TITLE
"Good first task" label / Roadmap

### ISSUE THREAD

**Issue by Kureev** [yarnpkg/yarn#982]
Hey guys,

I'd like to help contributing to this awesome project. However, it's hard to pick something from existing issues due to lack of priorities / roadmap. 

It would be nice if you can add **"Good first task"** label or **compose a roadmap** so people from the community can pick them up.

**Comment by rjmunro** [comment]
Maybe figure out why the CircleCI build broke at this commit: https://github.com/yarnpkg/yarn/commit/5d1704d3b5be0983f58bbdae3002dd560637cba1

(see https://circleci.com/gh/yarnpkg/yarn/tree/master)

**Comment by cpojer** [comment]
Created the label but we are currently a bit behind. The open source release was way bigger than expected and it's hard to keep up! Please give us some time to get everything in order.

I'll close this out as it isn't immediately actionable and it is part of our plans already. Hope that's ok :)
