### ISSUE TITLE
"^1.0.0-beta.16" installing "1.0.0-beta.2-mobile.4"

### ISSUE THREAD

**Issue by AilisObrian** [yarnpkg/yarn#985]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
```json
{
  "devDependencies": {
    "angular-cli": "^1.0.0-beta.16",
  }
}
```
With this `package.json`, yarn installs "1.0.0-beta.2-mobile.4",
but npm will install "1.0.0-beta.16".

**If the current behavior is a bug, please provide the steps to reproduce.**
above.

**What is the expected behavior?**
Same as npm, installing "1.0.0-beta.16" expected.

**Please mention your node.js, yarn and operating system version.**
Yarn v0.15.1
npm 3.10.3
Node v6.7.0
OS X El Capitan

**Comment by AilisObrian** [comment]
```node
> require("semver").satisfies("1.0.0-beta.2-mobile.4", "^1.0.0-beta.16")
true
```
[according to semver docs](http://semver.org/#spec-item-11), why?

**Comment by samccone** [comment]
semver question not related to yarn. closing (best to follow up with these kind of questions on stackoverflow)
