### ISSUE TITLE
Do not download dependencies if not needed

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/yarn#988]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
If I have a fully populated `node_modules` (with respect to the lockfile) and my cache is empty, if I call `yarn --pure-lockfile`, yarn will download the dependencies to the cache even though they already are in my `node_modules`.

**What is the expected behavior?**
If there is no need to install a new package to `node_modules`, then yarn should not download it to the cache.

**Why?**
It is related to #986 in a way: I want to avoid downloading packages when it is not needed.

**Please mention your node.js, yarn and operating system version.**
yarn v0.15.1, node v6.7.0 and linux

**Comment by bstro** [comment]
+1 need this.

**Comment by bestander** [comment]
Fixed now
