### ISSUE TITLE
https://yarnpkg.com/latest-version is incorrect

### ISSUE THREAD

**Issue by ithinkihaveacat** [yarnpkg/yarn#989]
Expected value (as of now):

0.15.1

Actual value:

0.15.0

```sh
$ yarn -V
0.15.1
$ curl -s https://yarnpkg.com/latest-version
0.15.0
```

(https://www.npmjs.com/package/yarnpkg also lists 0.15.1.)

**Comment by Daniel15** [comment]
We can't update the version number unless we rebuild the Debian, CentOS and Windows packages with 0.15.1. That version was just a patch to the tarball so it's not an official release version number. Unfortunately that means the version number of the tarball is out of sync with everything else :(
