### ISSUE TITLE
Installing directories deletes scoped dependencies

### ISSUE THREAD

**Issue by Jameskmonger** [yarnpkg/yarn#991]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Installing typed packages and then adding a new package removes the typed packages.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `yarn add @types/node`
2. Notice that `node_modules/@types/node` exists
3. `yarn add inversify-inject-decorators`
4. Notice that `node_modules/@types/node` no longer exists

**What is the expected behavior?**

Adding packages should not delete others.

**Please mention your node.js, yarn and operating system version.**

Node: `5.6.0`
Yarn: `0.15.1`
OS: `Windows 10`

**Comment by wyze** [comment]
Works fine on macOS, could be Windows specific.

**Comment by bestander** [comment]
This should be fixed now, please reopen if it is still an issue
