### ISSUE TITLE
yarn install --flat causes yarn check to fail

### ISSUE THREAD

**Issue by philipp-spiess** [yarnpkg/yarn#993]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**

When I install packages using `yarn install --flat` and run a check afterwards `yarn check`, I get a number of issues reported. I'm not 100% if this is related to https://github.com/yarnpkg/yarn/issues/893 which I can test when this fix will be released. I tried `yarn install` before and after the flat instal in different example runs but the issue was persistent

**If the current behavior is a bug, please provide the steps to reproduce.**
- `yarn install --flat`
- `yarn check`

**What is the expected behavior?**

It should be green since all packages reported in the lock file and the `package.json` should be installed.

**Please mention your node.js, yarn and operating system version.**
- node `v4.4.5`
- npm `v3.9.3`
- yarn `v0.15.1`

**Comment by verth** [comment]
Is this still happening on the latest version? 

I tried to reproduce but was unable to, when I rolled back to `0.15.1` I could reproduce though.

**Comment by wyze** [comment]
Confirmed as well this is working on 0.16.1. @philipp-spiess please upgrade and try it out again. If you're still having issues, provide your `package.json` and we can reopen the issue. Thanks!
