### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by jondot** [yarnpkg/yarn#994]
Hi guys,

In continuation to [this](https://github.com/yarnpkg/yarn/issues/982) I'd love if there was a set of context documentation for developers, so that we get familiar with the basic architecture and building blocks or terminology.

For example, from what I've read the yarn code so far, I've been mostly interested in how the cache works, so sifting through resolvers and fetchers, it only occurred to me at the end that both realms are dynamic and resolvers and fetchers are factories etc. A quick sketch and overview of the building blocks would have been really helpful.

I'll be happy to tackle that myself with the help of a core committer if this is low-priority.

**Comment by AlicanC** [comment]
Something like Lee Byron's [DataLoader – Source code walkthrough](https://www.youtube.com/watch?v=OQTnXNCDywA) would be great.

**Comment by jondot** [comment]
Definitely.
Also, It would be a good start with something like this https://facebook.github.io/react/contributing/codebase-overview.html

**Comment by bestander** [comment]
I think it is a great idea and I just recommend going to it and starting such a thing.
We are planning to publish a few blog posts in the near future but the workload is always large, it would be great if someone in the community would want to get this role.
