### ISSUE TITLE
Trouble resolving git url dependencies

### ISSUE THREAD

**Issue by alathon** [yarnpkg/yarn#995]
**Do you want to request a _feature_ or report a _bug_?**
This is a bug.

**What is the current behavior?**
Running yarn to install dependencies will not install certain dependencies that the `devDependencies` package `ava` requires. This only happens when the dependency to ava is declared as a git URL, if we point to the real ava repository as an npm repository dependency, everything works.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new folder, e.g. `./tst`
2. Add the `./tst/package.json` and `./tst/test.js` files described below.
3. Run `yarn` to fetch dependencies.
4. Run `npm test` to run the test, giving you an `Error: Cannot find module 'not-so-shallow'`

_./tst/package.json_:

``` json
{
  "name": "tst",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ava test.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ava": "git://github.com/alathon/ava.git#2a65c1295588ebdf36dcc833484c34f3ed956add"
  }
}
```

_./tst/test.js_

``` javascript
import test from 'ava'

test(t => { t.pass() })
```

**What is the expected behavior?**
The expected behavior is that the above `npm test` executes and runs the single test. If you replace running `yarn` with `npm install`, the same exact scenario seems to work. If you replace the `ava` dependency with: "ava": "^0.16.0" it works. **note**: the commit pointed to in the above `package.json` file is branched off of `0.16.0`, so that is not the issue.

**Please mention your node.js, yarn and operating system version.**
`node v6.7.0`, `yarn v0.15.1`, OS: `4.7.6-1-ARCH`

**Comment by timmui** [comment]
Similar to #513

**Comment by paralin** [comment]
Confirmed, same problem

**Comment by hpurmann** [comment]
Tried to reproduce. Everything works if you do
```json
{
  "devDependencies": {
    "ava": "github:alathon/ava#2a65c1295588ebdf36dcc833484c34f3ed956add"
  }
}
```

https://github.com/yarnpkg/yarn/issues/513 is closed so this can be closed as well.

**Comment by bestander** [comment]
Fixed then?

**Comment by PaulRBerg** [comment]
I had a similar problem and I fixed it by applying @hpurmann's format recommended above. Does yarn document all the different kinds of format one can use to refer to a git-based dependency?
