### ISSUE TITLE
install --har options doesn't work

### ISSUE THREAD

**Issue by xujihui1985** [yarnpkg/yarn#996]
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behavior?**
when request with --har,  the resolve step will be hang
**If the current behavior is a bug, please provide the steps to reproduce.**
yarn install --har
**What is the expected behavior?**
dump the har trace file
**Please mention your node.js, yarn and operating system version.**
node v6.5.0,  operating system macos

**Comment by xujihui1985** [comment]
![image](https://cloud.githubusercontent.com/assets/1619030/19351196/5c80ac7e-918d-11e6-9d6b-f0e7128e6fea.png)
the callback you pass to the options will be overwrite by the callback, hence the promise will not be resolved

**Comment by Daniel15** [comment]
Thanks for reporting this bug! We got another report of this (#536) but couldn't repro, and I'm unable to replicate the issue on Windows. Would you be able to provide a `package.json` that replicates the problem?

**Comment by xujihui1985** [comment]
@Daniel15  Hi Daniel, thanks for reply, I can consistent reproduce this on my mac and doesn't matter what the package.json is, I have attach the screen shot that cause the problem, the reason is the callback function request-manager pass to the requestModule was shadowed by the callback of the HarWrapper.request method thus the it's never resolve

**Comment by 2oo** [comment]
I have the same issue on my mac. El Capitan 10.11.4 (15E65). It occurs even if I have only one dependency in my package.json.
