### ISSUE TITLE
Feature request: yarn init --yes

### ISSUE THREAD

**Issue by doug-wade** [yarnpkg/yarn#997]
**Do you want to request a *feature* or report a *bug*?**
Request a feature!

**What is the current behavior?**
```
» yarn init --yes
yarn init v0.15.1
error This command doesn't require any arguments.
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

**What is the expected behavior?**
A package.json with reasonable defaults is created, similar to `npm init --yes`

**Please mention your node.js, yarn and operating system version.**
```
doug-UX301LAA packages/kniffiti-pattern ‹master*› » yarn --version                                                                                                                                                                1 ↵
0.15.1
doug-UX301LAA packages/kniffiti-pattern ‹master*› » node -v
v6.8.0
doug-UX301LAA packages/kniffiti-pattern ‹master*› » lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

If this feature is something that is in-scope for yarn, I'd be willing to implement it.

**Comment by eknkc** [comment]
Discussed in #873

**Comment by doug-wade** [comment]
@eknkc sorry! I searched the open issues, but not closed prs.  I won't start hacking together a commit, but should I close the issue, or should we leave it open until a version of https://github.com/yarnpkg/yarn/commit/04930493ec86c82403a426af10218c5411b982b1 lands that doesn't break the tests?
