### ISSUE TITLE
yarn install fails if package.json contains local tarball dependency

### ISSUE THREAD

**Issue by shahmirn** [yarnpkg/yarn#999]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
...
...
[1/4] Resolving packages...
error https://registry.yarnpkg.com/@slb-planck-ui%2fasync-loader: Not found
    at Request.params.callback [as _callback] 

**If the current behavior is a bug, please provide the steps to reproduce.**
Have a dependency in package.json that references a tarball. Somethine like:

{
  "dependencies": {
    "@angular/common": "~2.0.2",
    ...
    "@slb-planck-ui/async-loader": "slb-planck-ui-async-loader-0.0.1-dev.3.tgz",
    ...
  },
  "devDependencies": {
    "@angular/compiler": "~2.0.2",
    "@angular/compiler-cli": "^0.6.2",
    "@angular/platform-server": "~2.0.2",
    ...
  }
}

**What is the expected behavior?**
Local tar packages are installed successfully
**Please mention your node.js, yarn and operating system version.**
Node: 4.4.5
npm: 3.10.8
yarn: 0.15.1
OS: Windows 7

**Comment by anjianshi** [comment]
try this?
```json
{
  "dependencies": {
    "@slb-planck-ui/async-loader": "file:slb-planck-ui-async-loader-0.0.1-dev.3.tgz",
  }
}
```

**Comment by shahmirn** [comment]
Tried with file:

and I get back:

Error: Invalid URI "file:///slb-planck-ui-async-loader-0.0.1-dev.3.tgz"

**Comment by josercruz01** [comment]
I'm running into this same issue. I created a very simple repository that replicates this error: https://github.com/josercruz01/yarn-tarball-issue

I'm using `file:package1-1.0.0.tgz` as the URI to the dependency.

If you want to take a look at the repo just go into the `package2` folder and run `yarn` and you should see the problem.

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? I'm not able to recreate the issue using the latest Yarn `v0.17.10` and your git repo.

```sh
cd package2
yarn
yarn install v0.17.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.52s.
```

**Comment by shahmirn** [comment]
@busches This was fixed with https://github.com/yarnpkg/yarn/pull/1775

**Comment by warwr1ck** [comment]
```
$ yarn
yarn install v0.20.3
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https:/registry.yarnpkg.com/immediate: Inva
lid URI \"https:/registry.yarnpkg.com/immediate\"".
info If you think this is a bug, please open a bug report with the information p
rovided in "F:\\Code\\lie\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.
```
node: v6.10.0
npm: v3.8.2
yarn: v0.20.3
OS: window10

**Comment by evan-scott-zocdoc** [comment]
This isn't fixed.

**Comment by busches** [comment]
@evan-scott-zocdoc providing a reproducible test case and your yarn version is the most efficient way to getting some traction on someone helping you.
